{{ config(tags=['spine_generated']) }}

-- GRAIN: one row per place (GEOM is unique)
-- SPINE_ENTITY: place  (natural_key: DATASPATIAL_WKB)
-- Generated by scripts/generate_staging_models.py from SOURCE_REGISTRY -- deterministic,
-- no LLM. Casts kept as landed (TEXT) -- add explicit type casts by hand once each
-- column's real type is confirmed; this generator has no semantic type knowledge.
-- spine_entity 'place' has no connect/ resolver yet (see connect/spine_entity.py) -- no SPINE_ENTITY_ID emitted.
-- landing table's ingestion timestamp is named INGESTED_AT (no leading underscore) rather than the usual _INGESTED_AT -- confirmed via INFORMATION_SCHEMA, not assumed.

with source as (

    select * from {{ source('ripple_raw', 'PORTAL_CKA_WPRDC_ALLEGHENY_B62C61BBEB') }}

),

renamed as (

    select
        "BL_SYEARTO" as bl_syearto,
        "RS" as rs,
        "BLNAME" as blname,
        "YEARTOT" as yeartot,
        "NOTE" as note,
        "BIKEINFDIS" as bikeinfdis,
        "CROSSST" as crossst,
        "SLMDIST" as slmdist,
        "YEAR_ADDED" as year_added,
        "ID" as id,
        "BLDIST" as bldist,
        "RBL" as rbl,
        "DATASPATIAL_WKB" as dataspatial_wkb,
        INGESTED_AT as _loaded_at,
        'https://data.wprdc.org/dataset/shape-files-for-bikepgh-s-pittsburgh-bike-map' as _source_url

    from source

)

select * from renamed
qualify row_number() over (partition by dataspatial_wkb order by _loaded_at desc) = 1
