{{ config(tags=['spine_generated']) }}

-- GRAIN: one row per record (spine_entity not determined -- no registry hint available) (HAZARD_MODEL_ID unique)
-- SPINE_ENTITY: (not determined)  (natural_key: HAZARD_MODEL_ID)
-- Generated by scripts/generate_staging_models.py from SOURCE_REGISTRY -- deterministic,
-- no LLM. Casts kept as landed (TEXT) -- add explicit type casts by hand once each
-- column's real type is confirmed; this generator has no semantic type knowledge.
-- spine_entity not determined (grain/natural_key proven, but no registry hint says what this row is ABOUT) -- no SPINE_ENTITY_ID emitted.

with source as (

    select * from {{ source('ripple_raw', 'INTL_GEM_HAZARD') }}

),

renamed as (

    select
        "MODEL_VERSION" as model_version,
        "COUNTRY" as country,
        "FIPS" as fips,
        "LATITUDE" as latitude,
        "LONGITUDE" as longitude,
        "PGA_10PCT_50YR" as pga_10pct_50yr,
        "VS30" as vs30,
        "HAZARD_MODEL_ID" as hazard_model_id,
        "DOI" as doi,
        _INGESTED_AT as _loaded_at,
        'https://hazard.openquake.org/gem/' as _source_url

    from source

)

select * from renamed
qualify row_number() over (partition by hazard_model_id order by _loaded_at desc) = 1
