{{ config(tags=['spine_generated']) }}

-- GRAIN: one row per organization (DUNS+PERIOD_OF_PERFORMANCE_START+PERIOD_OF_PERFORMANCE_CURRENT+LAST_MODIFIED_DATE+AWARD_ID_FAIN+AWARD_ID_URI unique)
-- SPINE_ENTITY: organization  (natural_key: RECIPIENT_DUNS, PERIOD_OF_PERFORMANCE_START, PERIOD_OF_PERFORMANCE_CURRENT, LAST_MODIFIED_DATE, AWARD_ID_FAIN, AWARD_ID_URI)
-- Generated by scripts/generate_staging_models.py from SOURCE_REGISTRY -- deterministic,
-- no LLM.
-- CASTS: 13 of 63 columns, from landing_column_profile_2026-09-19.tsv. A column is cast only
-- when every filled value in the sample parsed. try_ casts: a value that does not
-- parse reads NULL. The natural key and join-key columns stay TEXT.
--   total_funding_amount: ID: whole numbers, over 90% distinct -- stays TEXT, '.0' tail removed
--   obligated_amount: float
--   non_federal_funding_amount: float
--   awarding_agency_code: integer
--   funding_agency_code: integer
--   primary_place_of_performance_8: integer
--   assistance_type_code: integer
--   record_type_code: integer
--   face_value_of_loan: integer
--   primary_place_of_performance_4: integer
--   original_subsidy_cost: float
--   total_subsidy_cost: float
--   total_loan_value: integer
-- spine_entity 'organization' has no connect/ resolver yet (see connect/spine_entity.py) -- no SPINE_ENTITY_ID emitted.
-- landing table's ingestion timestamp is named INGESTED_AT (no leading underscore) rather than the usual _INGESTED_AT -- confirmed via INFORMATION_SCHEMA, not assumed.

with source as (

    select * from {{ source('ripple_raw', 'PORTAL_SOC_UTAH_OPEN_DATA_P_103F7D641F') }}
    qualify row_number() over (partition by "RECIPIENT_DUNS", "PERIOD_OF_PERFORMANCE_START", "PERIOD_OF_PERFORMANCE_CURRENT", "LAST_MODIFIED_DATE", "AWARD_ID_FAIN", "AWARD_ID_URI" order by INGESTED_AT desc) = 1

),

renamed as (

    select
        {{ null_junk('"RECIPIENT_NAME"') }} as recipient_name,
        {{ stg_id_text('"TOTAL_FUNDING_AMOUNT"') }} as total_funding_amount,
        {{ null_junk('"AWARD_ID_FAIN"') }} as award_id_fain,
        {{ null_junk('"SAI_NUMBER"') }} as sai_number,
        {{ stg_float('"OBLIGATED_AMOUNT"') }} as obligated_amount,
        {{ stg_float('"NON_FEDERAL_FUNDING_AMOUNT"') }} as non_federal_funding_amount,
        {{ null_junk('"PERIOD_OF_PERFORMANCE_START"') }} as period_of_performance_start,
        {{ null_junk('"PERIOD_OF_PERFORMANCE_CURRENT"') }} as period_of_performance_current,
        {{ stg_int('"AWARDING_AGENCY_CODE"') }} as awarding_agency_code,
        {{ null_junk('"AWARDING_AGENCY_NAME"') }} as awarding_agency_name,
        {{ null_junk('"AWARDING_SUB_AGENCY_CODE"') }} as awarding_sub_agency_code,
        {{ null_junk('"AWARDING_SUB_AGENCY_NAME"') }} as awarding_sub_agency_name,
        {{ null_junk('"AWARDING_OFFICE_CODE"') }} as awarding_office_code,
        {{ stg_int('"FUNDING_AGENCY_CODE"') }} as funding_agency_code,
        {{ null_junk('"FUNDING_AGENCY_NAME"') }} as funding_agency_name,
        {{ null_junk('"FUNDING_SUB_AGENCY_CODE"') }} as funding_sub_agency_code,
        {{ null_junk('"FUNDING_SUB_AGENCY_NAME"') }} as funding_sub_agency_name,
        {{ null_junk('"FUNDING_OFFICE_CODE"') }} as funding_office_code,
        {{ null_junk('"RECIPIENT_DUNS"') }} as recipient_duns,
        {{ null_junk('"RECIPIENT_PARENT_DUNS"') }} as recipient_parent_duns,
        {{ null_junk('"RECIPIENT_PARENT_NAME"') }} as recipient_parent_name,
        {{ null_junk('"RECIPIENT_COUNTRY_CODE"') }} as recipient_country_code,
        {{ null_junk('"RECIPIENT_COUNTRY_NAME"') }} as recipient_country_name,
        {{ null_junk('"RECIPIENT_ADDRESS_LINE_1"') }} as recipient_address_line_1,
        {{ null_junk('"RECIPIENT_CITY_CODE"') }} as recipient_city_code,
        {{ null_junk('"RECIPIENT_CITY_NAME"') }} as recipient_city_name,
        {{ null_junk('"RECIPIENT_COUNTY_CODE"') }} as recipient_county_code,
        {{ null_junk('"RECIPIENT_COUNTY_NAME"') }} as recipient_county_name,
        {{ null_junk('"RECIPIENT_STATE_CODE"') }} as recipient_state_code,
        {{ null_junk('"RECIPIENT_STATE_NAME"') }} as recipient_state_name,
        {{ null_junk('"RECIPIENT_ZIP_CODE"') }} as recipient_zip_code,
        {{ null_junk('"RECIPIENT_ZIP_LAST_4_CODE"') }} as recipient_zip_last_4_code,
        {{ null_junk('"RECIPIENT_CONGRESSIONAL"') }} as recipient_congressional,
        {{ null_junk('"PRIMARY_PLACE_OF_PERFORMANCE"') }} as primary_place_of_performance,
        {{ null_junk('"PRIMARY_PLACE_OF_PERFORMANCE_1"') }} as primary_place_of_performance_1,
        {{ null_junk('"PRIMARY_PLACE_OF_PERFORMANCE_2"') }} as primary_place_of_performance_2,
        {{ null_junk('"PRIMARY_PLACE_OF_PERFORMANCE_6"') }} as primary_place_of_performance_6,
        {{ stg_int('"PRIMARY_PLACE_OF_PERFORMANCE_8"') }} as primary_place_of_performance_8,
        {{ null_junk('"CFDA_NUMBER"') }} as cfda_number,
        {{ null_junk('"CFDA_TITLE"') }} as cfda_title,
        {{ stg_int('"ASSISTANCE_TYPE_CODE"') }} as assistance_type_code,
        {{ null_junk('"ASSISTANCE_TYPE_DESCRIPTION"') }} as assistance_type_description,
        {{ null_junk('"AWARD_DESCRIPTION"') }} as award_description,
        {{ null_junk('"BUSINESS_FUNDS_INDICATOR"') }} as business_funds_indicator,
        {{ null_junk('"BUSINESS_FUNDS_INDICATOR_1"') }} as business_funds_indicator_1,
        {{ null_junk('"BUSINESS_TYPES_CODE"') }} as business_types_code,
        {{ null_junk('"BUSINESS_TYPES_DESCRIPTION"') }} as business_types_description,
        {{ stg_int('"RECORD_TYPE_CODE"') }} as record_type_code,
        {{ null_junk('"RECORD_TYPE_DESCRIPTION"') }} as record_type_description,
        {{ null_junk('"LAST_MODIFIED_DATE"') }} as last_modified_date,
        {{ stg_int('"FACE_VALUE_OF_LOAN"') }} as face_value_of_loan,
        {{ null_junk('"PRIMARY_PLACE_OF_PERFORMANCE_3"') }} as primary_place_of_performance_3,
        {{ stg_int('"PRIMARY_PLACE_OF_PERFORMANCE_4"') }} as primary_place_of_performance_4,
        {{ null_junk('"PRIMARY_PLACE_OF_PERFORMANCE_5"') }} as primary_place_of_performance_5,
        {{ null_junk('"PRIMARY_PLACE_OF_PERFORMANCE_7"') }} as primary_place_of_performance_7,
        {{ stg_float('"ORIGINAL_SUBSIDY_COST"') }} as original_subsidy_cost,
        {{ stg_float('"TOTAL_SUBSIDY_COST"') }} as total_subsidy_cost,
        {{ null_junk('"FUNDING_OFFICE_NAME"') }} as funding_office_name,
        {{ null_junk('"RECIPIENT_ADDRESS_LINE_2"') }} as recipient_address_line_2,
        {{ null_junk('"AWARDING_OFFICE_NAME"') }} as awarding_office_name,
        {{ stg_int('"TOTAL_LOAN_VALUE"') }} as total_loan_value,
        {{ null_junk('"AWARD_ID_URI"') }} as award_id_uri,
        {{ null_junk('"PRIMARY_PLACE_OF_PERFORMANCE_9"') }} as primary_place_of_performance_9,
        INGESTED_AT as _loaded_at,
        'https://opendata.utah.gov/d/7n5d-er3z' as _source_url

    from source

)

select * from renamed
