{{ config(tags=['spine_generated']) }}

-- GRAIN: one row per place (FIPS is unique)
-- SPINE_ENTITY: place  (natural_key: GEOID10)
-- Generated by scripts/generate_staging_models.py from SOURCE_REGISTRY -- deterministic,
-- no LLM. Casts kept as landed (TEXT) -- add explicit type casts by hand once each
-- column's real type is confirmed; this generator has no semantic type knowledge.
-- spine_entity 'place' has no connect/ resolver yet (see connect/spine_entity.py) -- no SPINE_ENTITY_ID emitted.
-- landing table's ingestion timestamp is named INGESTED_AT (no leading underscore) rather than the usual _INGESTED_AT -- confirmed via INFORMATION_SCHEMA, not assumed.

with source as (

    select * from {{ source('ripple_raw', 'PORTAL_CKA_WESTERN_PENNSYLV_2CFAAEA4FD') }}

),

renamed as (

    select
        "SHAPE__AREA" as shape__area,
        "SHAPE__LENGTH" as shape__length,
        "ACRES" as acres,
        "ALAND10" as aland10,
        "AWATER10" as awater10,
        "BLKGRPCE10" as blkgrpce10,
        "CDBG2014" as cdbg2014,
        "CDBG2018" as cdbg2018,
        "CNT_TRACTCE10" as cnt_tractce10,
        "COUNTYFP10" as countyfp10,
        "FUNCSTAT10" as funcstat10,
        "GEOID10" as geoid10,
        "HOOD" as hood,
        "HOOD_NO" as hood_no,
        "INTPTLAT10" as intptlat10,
        "INTPTLON10" as intptlon10,
        "LOWMODPERCANNO" as lowmodpercanno,
        "LOWMODPERCT" as lowmodperct,
        "MTFCC10" as mtfcc10,
        "NAMELSAD10" as namelsad10,
        "OBJECTID" as objectid,
        "OBJECTID_1" as objectid_1,
        "SECTORS" as sectors,
        "SQMILES" as sqmiles,
        "STATEFP10" as statefp10,
        "SUM_LOWMOD2018" as sum_lowmod2018,
        "SUM_LOWMODUNIV" as sum_lowmoduniv,
        "TRACT" as tract,
        "TRACTCE10" as tractce10,
        "TRACTCE10_1" as tractce10_1,
        "TRACTTEXT" as tracttext,
        "GEOMETRY" as geometry,
        INGESTED_AT as _loaded_at,
        'https://data.wprdc.org/dataset/pittsburgh-2014-cdbg-census-tracts' as _source_url

    from source

)

select * from renamed
qualify row_number() over (partition by geoid10 order by _loaded_at desc) = 1
