{{ config(materialized='table', schema='IMMIGRATION') }}

-- Source: FED_CMS_HOSPICE_ENROLLMENTS (6066 rows)
-- Generated by scripts/gen_mart_models.py

with source as (
    select * from {{ source('ripple_raw', 'FED_CMS_HOSPICE_ENROLLMENTS') }}
)

select
    ENROLLMENT_ID as enrollment_id,
    ENROLLMENT_STATE as enrollment_state,
    PROVIDER_TYPE_CODE as provider_type_code,
    PROVIDER_TYPE_TEXT as provider_type_text,
    NPI as npi,
    MULTIPLE_NPI_FLAG as multiple_npi_flag,
    CCN as ccn,
    ASSOCIATE_ID as associate_id,
    ORGANIZATION_NAME as organization_name,
    DOING_BUSINESS_AS_NAME as doing_business_as_name,
    try_to_date(INCORPORATION_DATE) as incorporation_date,
    INCORPORATION_STATE as incorporation_state,
    ORGANIZATION_TYPE_STRUCTURE as organization_type_structure,
    ORGANIZATION_OTHER_TYPE_TEXT as organization_other_type_text,
    PROPRIETARY_NONPROFIT as proprietary_nonprofit,
    ADDRESS_LINE_1 as address_line_1,
    ADDRESS_LINE_2 as address_line_2,
    CITY as city,
    STATE as state,
    ZIP_CODE as zip_code
from source
