{{ config(materialized='table', schema='IMMIGRATION') }}

-- Source: OWID ? Refugee population by country of origin (7442 rows)
-- Generated by gen_mart_models.py

with source as (
    select * from {{ source('ripple_raw', 'XC_OWID_REFUGEES') }}
)

select
    ENTITY as entity,
    CODE as code,
    try_to_number("YEAR") as year,
    try_to_number(REFUGEES_BY_COUNTRY_OF_ORIGIN) as refugees_by_country_of_origin,
    WORLD_REGION_ACCORDING_TO_OWID as world_region_according_to_owid
from source
