{{ config(materialized='table', schema='IMMIGRATION') }}

-- Source: ICE Enforcement and Removal Operations Statistics (221 rows)
-- Generated by gen_mart_models.py
-- Fixed 2026-09-20: bare try_to_number()/try_to_double()/try_to_date() casts replaced in place with the project's guarded macros (stg_int/stg_float/stg_date, macros/staging_casts.sql) -- a value that doesn't parse cleanly now reads NULL instead of being silently rounded or misparsed. Kept on source() (not ref()) because this mart carries its own dedup (qualify) that must stay intact.

-- DEDUP (2026-08-18 verification): the entire 17-row surplus is one group of 18
-- completely blank rows (METRIC_TYPE='unknown', every other field blank, one
-- shared SNAPSHOT_DATE) -- a failed-parse placeholder inserted repeatedly, not
-- real ICE statistics repeating. Confirm query showed a SINGLE load run
-- (1 distinct _SOURCE_RUN_ID); live: 221 rows / 204 distinct -- single-load
-- duplication, exact dups carry no information. Also independently flagged in
-- outputs/dedup_fix_batches/fixbatch_03.json from a prior sweep. FLAG: this
-- dedup only removes the symptom -- the real fix is the underlying parse
-- failure that produced the 18 blank placeholder rows in the first place
-- (18 sections/pages the loader couldn't extract); that root cause is still live.
with source as (
    select * from {{ source('ripple_raw', 'FED_ICE_STATISTICS') }}
    qualify row_number() over (
        partition by FISCAL_YEAR, FISCAL_QUARTER, METRIC_TYPE,
                     COUNTRY_OF_CITIZENSHIP, CRIMINAL_HISTORY_CATEGORY, AOR,
                     COUNT, REMOVAL_AUTHORITY, ATD_MONITORING_TYPE, SNAPSHOT_DATE
        order by _INGESTED_AT) = 1
)

select
    {{ stg_int('"FISCAL_YEAR"') }} as fiscal_year,
    FISCAL_QUARTER as fiscal_quarter,
    METRIC_TYPE as metric_type,
    COUNTRY_OF_CITIZENSHIP as country_of_citizenship,
    CRIMINAL_HISTORY_CATEGORY as criminal_history_category,
    AOR as aor,
    {{ stg_int('"COUNT"') }} as count,
    REMOVAL_AUTHORITY as removal_authority,
    ATD_MONITORING_TYPE as atd_monitoring_type,
    {{ stg_date('"SNAPSHOT_DATE"') }} as snapshot_date
from source
