from wq import run
import json
q3="""SELECT _SOURCE_RUN_ID, MIN(_INGESTED_AT)::STRING i0, MAX(_INGESTED_AT)::STRING i1, COUNT(*) n,
  COUNT_IF(OUTLIER_SRVCS IS NULL) o_null, COUNT_IF(OUTLIER_SRVCS = '') o_empty,
  COUNT_IF(OUTLIER_SRVCS IS NOT NULL AND OUTLIER_SRVCS <> '' AND TRY_TO_DOUBLE(OUTLIER_SRVCS) IS NULL) o_nonnum,
  ARRAY_AGG(DISTINCT IFF(TRY_TO_DOUBLE(OUTLIER_SRVCS) IS NULL, OUTLIER_SRVCS, NULL)) o_nonnum_vals,
  COUNT_IF(TRY_TO_DOUBLE(CAPC_SRVCS) IS NULL) s_blank,
  COUNT_IF(TRY_TO_DOUBLE(CAPC_SRVCS) IS NOT NULL AND TRY_TO_DOUBLE(OUTLIER_SRVCS) IS NULL) hidden
FROM LIBRARY_RAW.LANDING.FED_CMS_MEDICARE_OUTPATIENT_HOSPITALS_BY_PROVIDER_AND_SERVICE GROUP BY 1"""
for x in run('W3_raw_lineage_suppression',q3): print(x)
q4="""SELECT * FROM LIBRARY_META.REGISTRY.SOURCE_REGISTRY WHERE SOURCE_ID ILIKE '%outpatient%' OR TO_VARCHAR(OBJECT_CONSTRUCT(*)) ILIKE '%outpatient hospitals%'"""
for x in run('W4_registry',q4): print(json.dumps(x,default=str)[:2500]); print()
q5="""SELECT CCN, FAC_NAME, CITY_NAME, STATE_CD, PRVDR_CTGRY_CD, PRVDR_CTGRY_SBTYP_CD, ORGNL_PRTCPTN_DT::STRING opd, PGM_TRMNTN_CD, TRMNTN_EXPRTN_DT::STRING term,
  INTRMDRY_CARR_CD, MDCL_SCHL_AFLTN_CD, BED_CNT, RELATED_PROVIDER_NUMBER, CROSS_REF_PROVIDER_NUMBER
FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_POS_OTHER
WHERE STATE_CD='PA' AND (FAC_NAME ILIKE '%PENN STATE%' OR FAC_NAME ILIKE '%HERSHEY%' OR CCN IN ('390004','390096','390256','390336','390339'))"""
for x in run('W5_pos_penn_state',q5): print(x)
