from wq import run
q5="""SELECT CCN, FAC_NAME, CITY_NAME, PRVDR_CTGRY_CD, PRVDR_CTGRY_SBTYP_CD, ORGNL_PRTCPTN_DT::STRING opd, PGM_TRMNTN_CD, TRMNTN_EXPRTN_DT::STRING term,
  INTRMDRY_CARR_CD, MDCL_SCHL_AFLTN_CD, BED_CNT, MLT_FAC_ORG_NAME
FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_POS_OTHER
WHERE STATE_CD='PA' AND (FAC_NAME ILIKE '%PENN STATE%' OR FAC_NAME ILIKE '%HERSHEY%' OR MLT_FAC_ORG_NAME ILIKE '%PENN STATE%' OR CCN IN ('390004','390096','390256','390336','390339'))"""
for x in run('W5_pos_penn_state',q5): print(x)
q6="""WITH op AS (SELECT DISTINCT RNDRNG_PRVDR_CCN CCN FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_MEDICARE_OUTPATIENT_HOSPITALS_BY_PROVIDER_AND_SERVICE)
SELECT p.CCN, p.MLT_FAC_ORG_NAME, p.MLT_OWND_FAC_ORG_SW, p.INTRMDRY_CARR_CD FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_POS_OTHER p JOIN op ON op.CCN=p.CCN"""
r=run('W6_pos_system_names',q6)
print(len(r), 'with system name', sum(1 for x in r if x['MLT_FAC_ORG_NAME'] and str(x['MLT_FAC_ORG_NAME']).strip()))
