-- W1_mart_rederive
WITH b AS (
  SELECT RNDRNG_PRVDR_CCN ccn, APC_CD apc, TRY_TO_DOUBLE(CAPC_SRVCS) s, TRY_TO_DOUBLE(OUTLIER_SRVCS) o,
         AVG_MDCR_OUTLIER_AMT oa, AVG_MDCR_PYMT_AMT pa
  FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_MEDICARE_OUTPATIENT_HOSPITALS_BY_PROVIDER_AND_SERVICE),
a AS (SELECT apc, SUM(o*oa)/SUM(s) rate FROM b WHERE s IS NOT NULL AND o IS NOT NULL GROUP BY apc),
h AS (
  SELECT b.ccn, SUM(IFF(o IS NOT NULL, s, 0)) srv, SUM(IFF(o IS NOT NULL, o*oa, 0)) obs,
         SUM(IFF(o IS NOT NULL, s*a.rate, 0)) exp, COUNT_IF(s IS NOT NULL AND o IS NULL) hidden_rows,
         SUM(IFF(o IS NOT NULL, o, 0)) osrv
  FROM b JOIN a ON a.apc=b.apc GROUP BY b.ccn),
r AS (SELECT ccn, obs, ROW_NUMBER() OVER (ORDER BY obs DESC) rk FROM h)
SELECT
  (SELECT COUNT(*) FROM b) n_rows,
  (SELECT COUNT(DISTINCT ccn||'|'||apc) FROM b) n_pairs,
  (SELECT COUNT_IF(s IS NULL) FROM b) stub_rows,
  (SELECT COUNT_IF(s IS NOT NULL AND o IS NULL) FROM b) hidden_outlier_rows,
  (SELECT COUNT_IF(o BETWEEN 1 AND 10) FROM b) shown_1_to_10,
  (SELECT COUNT_IF(o = 0) FROM b) shown_zero,
  (SELECT SUM(o*oa) FROM b WHERE o IS NOT NULL) shown_outlier_usd,
  (SELECT SUM(s*pa) FROM b WHERE s IS NOT NULL) paid_usd,
  (SELECT SUM(obs) FROM r WHERE rk<=50) top50_usd,
  (SELECT COUNT(*) FROM h WHERE srv>=1000) big,
  (SELECT COUNT(*) FROM h WHERE srv>=1000 AND obs=0) big_zero,
  (SELECT COUNT(*) FROM h WHERE srv>=1000 AND obs=0 AND hidden_rows>0) big_zero_with_hidden,
  (SELECT SUM(obs) FROM h WHERE ccn IN ('390004','390096','390256','390336','390339')) psh_obs,
  (SELECT SUM(exp) FROM h WHERE ccn IN ('390004','390096','390256','390336','390339')) psh_exp,
  (SELECT SUM(osrv)||' of '||SUM(srv) FROM h WHERE ccn IN ('390004','390096','390256','390336','390339')) psh_cases,
  (SELECT osrv||' of '||srv||' oe '||ROUND(obs/exp,1) FROM h WHERE ccn='390339') lancaster,
  (SELECT osrv||' of '||srv||' oe '||ROUND(obs/exp,1) FROM h WHERE ccn='390256') hershey;

ALTER SESSION SET STATEMENT_TIMEOUT_IN_SECONDS = 300;
ALTER SESSION SET QUERY_TAG = 'deep3-skeptic-2026-09-24';

-- W2_landing_outpatient_tables
SELECT TABLE_SCHEMA, TABLE_NAME, LISTAGG(COLUMN_NAME, ',') WITHIN GROUP (ORDER BY ORDINAL_POSITION) cols
FROM LIBRARY_RAW.INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME ILIKE '%OUTPATIENT%' OR TABLE_NAME ILIKE '%OPPS%' GROUP BY 1,2;

-- W3_raw_lineage_suppression
SELECT _SOURCE_RUN_ID, MIN(_INGESTED_AT)::STRING i0, MAX(_INGESTED_AT)::STRING i1, COUNT(*) n,
  COUNT_IF(OUTLIER_SRVCS IS NULL) o_null, COUNT_IF(OUTLIER_SRVCS = '') o_empty,
  COUNT_IF(OUTLIER_SRVCS IS NOT NULL AND OUTLIER_SRVCS <> '' AND TRY_TO_DOUBLE(OUTLIER_SRVCS) IS NULL) o_nonnum,
  ARRAY_AGG(DISTINCT IFF(TRY_TO_DOUBLE(OUTLIER_SRVCS) IS NULL, OUTLIER_SRVCS, NULL)) o_nonnum_vals,
  COUNT_IF(TRY_TO_DOUBLE(CAPC_SRVCS) IS NULL) s_blank,
  COUNT_IF(TRY_TO_DOUBLE(CAPC_SRVCS) IS NOT NULL AND TRY_TO_DOUBLE(OUTLIER_SRVCS) IS NULL) hidden
FROM LIBRARY_RAW.LANDING.FED_CMS_MEDICARE_OUTPATIENT_HOSPITALS_BY_PROVIDER_AND_SERVICE GROUP BY 1;

ALTER SESSION SET STATEMENT_TIMEOUT_IN_SECONDS = 300;
ALTER SESSION SET QUERY_TAG = 'deep3-skeptic-2026-09-24';

-- W4_registry
SELECT * FROM LIBRARY_META.REGISTRY.SOURCE_REGISTRY WHERE SOURCE_ID ILIKE '%outpatient%' OR TO_VARCHAR(OBJECT_CONSTRUCT(*)) ILIKE '%outpatient hospitals%';

-- W5_pos_penn_state
SELECT CCN, FAC_NAME, CITY_NAME, PRVDR_CTGRY_CD, PRVDR_CTGRY_SBTYP_CD, ORGNL_PRTCPTN_DT::STRING opd, PGM_TRMNTN_CD, TRMNTN_EXPRTN_DT::STRING term,
  INTRMDRY_CARR_CD, MDCL_SCHL_AFLTN_CD, BED_CNT, MLT_FAC_ORG_NAME
FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_POS_OTHER
WHERE STATE_CD='PA' AND (FAC_NAME ILIKE '%PENN STATE%' OR FAC_NAME ILIKE '%HERSHEY%' OR MLT_FAC_ORG_NAME ILIKE '%PENN STATE%' OR CCN IN ('390004','390096','390256','390336','390339'));

ALTER SESSION SET STATEMENT_TIMEOUT_IN_SECONDS = 300;
ALTER SESSION SET QUERY_TAG = 'deep3-skeptic-2026-09-24';

-- W6_pos_system_names
WITH op AS (SELECT DISTINCT RNDRNG_PRVDR_CCN CCN FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_MEDICARE_OUTPATIENT_HOSPITALS_BY_PROVIDER_AND_SERVICE)
SELECT p.CCN, p.MLT_FAC_ORG_NAME, p.MLT_OWND_FAC_ORG_SW, p.INTRMDRY_CARR_CD FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_POS_OTHER p JOIN op ON op.CCN=p.CCN;

