-- @county_shape
WITH t AS (SELECT * FROM LIBRARY_MARTS.REFERENCE.REFERENCE__CENSUS_CB_COUNTY)
SELECT COUNT(*) n, COUNT(DISTINCT GEOID) geoid_nd, COUNT(DISTINCT GEOIDFQ) geoidfq_nd, COUNT(DISTINCT COUNTYNS) ns_nd,
       COUNT_IF(LENGTH(GEOID::VARCHAR) <> 5) geoid_not5, COUNT_IF(GEOID::VARCHAR <> STATEFP::VARCHAR || COUNTYFP::VARCHAR) geoid_ne_parts,
       COUNT(DISTINCT STATEFP) states, COUNT_IF(TRY_TO_NUMBER(STATEFP::VARCHAR) >= 60) territory_rows, COUNT_IF(STATEFP::VARCHAR = '72') pr_rows,
       COUNT_IF(STATEFP::VARCHAR = '09') ct_rows,
       (SELECT ARRAY_AGG(GEOID || ' ' || NAMELSAD) WITHIN GROUP (ORDER BY GEOID) FROM t WHERE STATEFP::VARCHAR = '09') ct_list,
       (SELECT OBJECT_AGG(COALESCE(VINTAGE::VARCHAR, '(null)'), c) FROM (SELECT VINTAGE, COUNT(*) c FROM t GROUP BY 1)) by_vintage,
       (SELECT OBJECT_AGG(COALESCE(LSAD::VARCHAR, '(null)'), c) FROM (SELECT LSAD, COUNT(*) c FROM t GROUP BY 1)) by_lsad,
       COUNT(DISTINCT _SOURCE_RUN_ID) runs, COUNT(DISTINCT _SRC_SHA256) files, MIN(_INGESTED_AT) i0, MAX(_INGESTED_AT) i1,
       COUNT_IF(TRY_TO_NUMBER(ALAND::VARCHAR) IS NULL) aland_bad, COUNT_IF(TRY_TO_NUMBER(ALAND::VARCHAR) = 0) aland_zero,
       COUNT_IF(GEOMETRY IS NULL) geom_null,
       (SELECT MAX(c) FROM (SELECT COUNT(*) c FROM t GROUP BY COUNTYNS)) max_rows_per_ns,
       (SELECT MAX(c) FROM (SELECT COUNT(*) c FROM t GROUP BY GEOID)) max_rows_per_geoid,
       COUNT_IF(COUNTYNS::VARCHAR = '01804502') rows_battery_top_ns,
       (SELECT ARRAY_AGG(GEOID || ' ' || NAMELSAD || ' ' || STUSPS) FROM (SELECT * FROM t WHERE COUNTYNS::VARCHAR = '01804502' LIMIT 5)) battery_ns_rows
FROM t;

-- @county_vs_dim_county
WITH cb AS (SELECT GEOID::VARCHAR g, NAMELSAD nm FROM LIBRARY_MARTS.REFERENCE.REFERENCE__CENSUS_CB_COUNTY),
dc0 AS (SELECT TRY_TO_NUMBER(COUNTY_FIPS::VARCHAR) cf, TRY_TO_NUMBER(STATE_FIPS::VARCHAR) sf, COUNTY_NAME nm, VINTAGE v FROM LIBRARY_MARTS.CORE.DIM_COUNTY),
dc AS (SELECT CASE WHEN cf >= 1000 THEN LPAD(cf::VARCHAR, 5, '0') ELSE LPAD(sf::VARCHAR, 2, '0') || LPAD(cf::VARCHAR, 3, '0') END g, nm, v FROM dc0)
SELECT (SELECT COUNT(*) FROM dc) dc_n, (SELECT COUNT(DISTINCT g) FROM dc) dc_nd,
       (SELECT ARRAY_AGG(DISTINCT v) FROM dc) dc_vintages,
       (SELECT COUNT(*) FROM cb WHERE g IN (SELECT g FROM dc WHERE g IS NOT NULL)) cb_land,
       (SELECT COUNT(*) FROM cb WHERE g NOT IN (SELECT g FROM dc WHERE g IS NOT NULL)) cb_only_n,
       (SELECT ARRAY_AGG(g || ' ' || nm) FROM (SELECT g, nm FROM cb WHERE g NOT IN (SELECT g FROM dc WHERE g IS NOT NULL) ORDER BY g LIMIT 40)) cb_only_sample,
       (SELECT COUNT(*) FROM dc WHERE g NOT IN (SELECT g FROM cb)) dc_only_n,
       (SELECT ARRAY_AGG(g || ' ' || nm) FROM (SELECT g, nm FROM dc WHERE g NOT IN (SELECT g FROM cb) ORDER BY g LIMIT 40)) dc_only_sample;

-- @county_ct_codes_across_tables
WITH cb AS (SELECT GEOID::VARCHAR g FROM LIBRARY_MARTS.REFERENCE.REFERENCE__CENSUS_CB_COUNTY),
a AS (SELECT DISTINCT LPAD(TRY_TO_NUMBER(FIPS::VARCHAR)::VARCHAR, 5, '0') g FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CDC_DRUG_POISONING_COUNTY WHERE TRY_TO_NUMBER(FIPS::VARCHAR) >= 1000),
b AS (SELECT DISTINCT LPAD(TRY_TO_NUMBER(GEOID::VARCHAR)::VARCHAR, 5, '0') g FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CDC_INJURY_VIOLENCE_COUNTY WHERE TRY_TO_NUMBER(GEOID::VARCHAR) >= 1000),
j AS (SELECT DISTINCT LPAD(TRY_TO_NUMBER(FIPS::VARCHAR)::VARCHAR, 5, '0') g FROM LIBRARY_MARTS.JUSTICE.JUSTICE__COUNTY_DOUBLE_BURDEN WHERE TRY_TO_NUMBER(FIPS::VARCHAR) >= 1000)
SELECT 'cdc_drug_poisoning' src, COUNT(*) keys, COUNT_IF(g IN (SELECT g FROM cb)) land_in_cb, COUNT_IF(g LIKE '090%') ct_old_counties, COUNT_IF(g LIKE '091%') ct_new_regions FROM a
UNION ALL SELECT 'cdc_injury_violence', COUNT(*), COUNT_IF(g IN (SELECT g FROM cb)), COUNT_IF(g LIKE '090%'), COUNT_IF(g LIKE '091%') FROM b
UNION ALL SELECT 'justice_double_burden', COUNT(*), COUNT_IF(g IN (SELECT g FROM cb)), COUNT_IF(g LIKE '090%'), COUNT_IF(g LIKE '091%') FROM j
UNION ALL SELECT 'cb_county_itself', COUNT(*), COUNT(*), COUNT_IF(g LIKE '090%'), COUNT_IF(g LIKE '091%') FROM cb;
