-- @county_shape_rerun
WITH t AS (SELECT * FROM LIBRARY_MARTS.REFERENCE.REFERENCE__CENSUS_CB_COUNTY)
SELECT COUNT(*) n, COUNT(DISTINCT GEOID) geoid_nd, COUNT(DISTINCT GEOIDFQ) geoidfq_nd, COUNT(DISTINCT COUNTYNS) ns_nd,
       COUNT_IF(LENGTH(GEOID::VARCHAR) <> 5) geoid_not5, COUNT_IF(GEOID::VARCHAR <> STATEFP::VARCHAR || COUNTYFP::VARCHAR) geoid_ne_parts,
       COUNT(DISTINCT STATEFP) states, COUNT_IF(TRY_TO_NUMBER(STATEFP::VARCHAR) >= 60) territory_rows, COUNT_IF(STATEFP::VARCHAR = '72') pr_rows,
       COUNT_IF(STATEFP::VARCHAR = '09') ct_rows,
       (SELECT ARRAY_AGG(GEOID || ' ' || NAMELSAD) WITHIN GROUP (ORDER BY GEOID) FROM t WHERE STATEFP::VARCHAR = '09') ct_list,
       (SELECT OBJECT_AGG(COALESCE(VINTAGE::VARCHAR, '(null)'), c) FROM (SELECT VINTAGE, COUNT(*) c FROM t GROUP BY 1)) by_vintage,
       (SELECT OBJECT_AGG(COALESCE(LSAD::VARCHAR, '(null)'), c) FROM (SELECT LSAD, COUNT(*) c FROM t GROUP BY 1)) by_lsad,
       COUNT(DISTINCT _SOURCE_RUN_ID) runs, COUNT(DISTINCT _SRC_SHA256) files,
       MIN(_INGESTED_AT)::VARCHAR i0, MAX(_INGESTED_AT)::VARCHAR i1, SYSTEM$TYPEOF(MIN(_INGESTED_AT)) i_type,
       COUNT_IF(TRY_TO_NUMBER(ALAND::VARCHAR) IS NULL) aland_bad, COUNT_IF(TRY_TO_NUMBER(ALAND::VARCHAR) = 0) aland_zero,
       COUNT_IF(GEOMETRY IS NULL) geom_null,
       (SELECT MAX(c) FROM (SELECT COUNT(*) c FROM t GROUP BY COUNTYNS)) max_rows_per_ns,
       (SELECT MAX(c) FROM (SELECT COUNT(*) c FROM t GROUP BY GEOID)) max_rows_per_geoid,
       COUNT_IF(COUNTYNS::VARCHAR = '01804502') rows_battery_top_ns,
       (SELECT ARRAY_AGG(GEOID || ' ' || NAMELSAD || ' ' || STUSPS) FROM (SELECT * FROM t WHERE COUNTYNS::VARCHAR = '01804502' LIMIT 5)) battery_ns_rows
FROM t;

-- @county_misses_other_tables
WITH cb AS (SELECT GEOID::VARCHAR g FROM LIBRARY_MARTS.REFERENCE.REFERENCE__CENSUS_CB_COUNTY),
a AS (SELECT DISTINCT LPAD(TRY_TO_NUMBER(FIPS::VARCHAR)::VARCHAR, 5, '0') g, COUNTY nm FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CDC_DRUG_POISONING_COUNTY WHERE TRY_TO_NUMBER(FIPS::VARCHAR) >= 1000),
b AS (SELECT DISTINCT LPAD(TRY_TO_NUMBER(GEOID::VARCHAR)::VARCHAR, 5, '0') g, NAME nm FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CDC_INJURY_VIOLENCE_COUNTY WHERE TRY_TO_NUMBER(GEOID::VARCHAR) >= 1000)
SELECT 'cdc_drug_poisoning' src, g, nm FROM a WHERE g NOT IN (SELECT g FROM cb)
UNION ALL SELECT 'cdc_injury_violence', g, nm FROM b WHERE g NOT IN (SELECT g FROM cb)
ORDER BY 1, 2;
