-- @geodiv_shape
WITH t AS (SELECT * FROM LIBRARY_MARTS.REFERENCE.REFERENCE__FED_ITIS_GEOGRAPHIC_DIV)
SELECT COUNT(*) n, COUNT(DISTINCT TSN) tsn_nd, COUNT(DISTINCT ITIS_GEOGRAPHIC_DIV_KEY) key_nd, COUNT(DISTINCT TSN, GEOGRAPHIC_VALUE) pair_nd,
       (SELECT OBJECT_AGG(COALESCE(GEOGRAPHIC_VALUE, '(null)'), c) FROM (SELECT GEOGRAPHIC_VALUE, COUNT(*) c FROM t GROUP BY 1)) by_region,
       COUNT_IF(LEFT(UPDATE_DATE::VARCHAR, 10) = '1900-01-01') d1900, MIN(UPDATE_DATE)::VARCHAR d0, MAX(UPDATE_DATE)::VARCHAR d1,
       (SELECT OBJECT_AGG(y, c) FROM (SELECT LEFT(UPDATE_DATE::VARCHAR, 4) y, COUNT(*) c FROM t GROUP BY 1)) by_year,
       COUNT(DISTINCT _SOURCE_RUN_ID) runs, COUNT(DISTINCT _SRC_SHA256) files,
       (SELECT MAX(c) FROM (SELECT COUNT(*) c FROM t GROUP BY TSN)) max_regions_per_tsn,
       (SELECT MEDIAN(c) FROM (SELECT COUNT(*) c FROM t GROUP BY TSN)) med_regions_per_tsn
FROM t;

-- @geodiv_join_taxonomic_units
WITH g AS (SELECT TSN, LEFT(UPDATE_DATE::VARCHAR, 10) = '1900-01-01' d1900 FROM LIBRARY_MARTS.REFERENCE.REFERENCE__FED_ITIS_GEOGRAPHIC_DIV),
tu AS (SELECT TSN, NAME_USAGE, RANK_ID FROM LIBRARY_MARTS.REFERENCE.REFERENCE__FED_ITIS_TAXONOMIC_UNITS)
SELECT g.d1900, COALESCE(tu.NAME_USAGE::VARCHAR, '(no taxon row)') usage, COUNT(*) n, COUNT(DISTINCT g.TSN) tsns,
       COUNT_IF(tu.RANK_ID = 220) species_rank_rows
FROM g LEFT JOIN tu ON g.TSN = tu.TSN GROUP BY 1, 2 ORDER BY 1, 3 DESC;

-- @geodiv_coverage_by_kingdom
WITH g AS (SELECT DISTINCT TSN FROM LIBRARY_MARTS.REFERENCE.REFERENCE__FED_ITIS_GEOGRAPHIC_DIV),
tu AS (SELECT TSN, KINGDOM_ID FROM LIBRARY_MARTS.REFERENCE.REFERENCE__FED_ITIS_TAXONOMIC_UNITS WHERE RANK_ID = 220 AND NAME_USAGE IN ('valid', 'accepted')),
k AS (SELECT KINGDOM_ID, KINGDOM_NAME FROM LIBRARY_MARTS.REFERENCE.REFERENCE__FED_ITIS_KINGDOMS)
SELECT tu.KINGDOM_ID, MAX(k.KINGDOM_NAME) kingdom, COUNT(*) accepted_species, COUNT_IF(g.TSN IS NOT NULL) with_region,
       ROUND(100 * COUNT_IF(g.TSN IS NOT NULL) / COUNT(*), 1) pct
FROM tu LEFT JOIN g ON tu.TSN = g.TSN LEFT JOIN k ON tu.KINGDOM_ID = k.KINGDOM_ID
GROUP BY 1 ORDER BY 3 DESC;

-- @nodc_shape
WITH t AS (SELECT * FROM LIBRARY_MARTS.REFERENCE.REFERENCE__FED_ITIS_NODC_IDS)
SELECT COUNT(*) n, COUNT(DISTINCT TSN) tsn_nd, COUNT(DISTINCT NODC_ID) nodc_nd, COUNT(DISTINCT ITIS_NODC_IDS_KEY) key_nd,
       MIN(TSN) tsn0, MAX(TSN) tsn1, MAX(TSN) - MIN(TSN) + 1 - COUNT(DISTINCT TSN) tsn_gaps,
       (SELECT MAX(c) FROM (SELECT COUNT(*) c FROM t GROUP BY TSN)) max_per_tsn,
       (SELECT MAX(c) FROM (SELECT COUNT(*) c FROM t GROUP BY NODC_ID)) max_per_nodc,
       MIN(LENGTH(NODC_ID::VARCHAR)) len0, MAX(LENGTH(NODC_ID::VARCHAR)) len1, SYSTEM$TYPEOF(MIN(NODC_ID)) nodc_type,
       (SELECT OBJECT_AGG(ym, c) FROM (SELECT LEFT(UPDATE_DATE::VARCHAR, 7) ym, COUNT(*) c FROM t GROUP BY 1)) by_month,
       COUNT(DISTINCT _SOURCE_RUN_ID) runs,
       (SELECT ARRAY_AGG(NODC_ID || '|' || TSN || '|' || UPDATE_DATE::VARCHAR) WITHIN GROUP (ORDER BY TSN) FROM (SELECT * FROM t ORDER BY TSN LIMIT 8)) first_rows
FROM t;

-- @nodc_join_taxonomic_units
WITH t AS (SELECT TSN, NODC_ID FROM LIBRARY_MARTS.REFERENCE.REFERENCE__FED_ITIS_NODC_IDS),
tu AS (SELECT TSN, NAME_USAGE, COMPLETE_NAME, RANK_ID FROM LIBRARY_MARTS.REFERENCE.REFERENCE__FED_ITIS_TAXONOMIC_UNITS),
s AS (SELECT COALESCE(tu.NAME_USAGE::VARCHAR, '(no taxon row)') usage, COUNT(*) n FROM t LEFT JOIN tu ON t.TSN = tu.TSN GROUP BY 1),
e AS (SELECT t.NODC_ID::VARCHAR || ' -> ' || t.TSN || ' ' || COALESCE(tu.COMPLETE_NAME, '?') || ' [' || COALESCE(tu.NAME_USAGE, '?') || ']' r
      FROM t LEFT JOIN tu ON t.TSN = tu.TSN WHERE MOD(t.TSN, 20011) = 7 LIMIT 8)
SELECT 'usage' kind, usage label, n FROM s
UNION ALL SELECT 'eyeball', r, NULL FROM e
ORDER BY 1 DESC, 3 DESC;

-- @strippedauthor_shape
WITH t AS (SELECT * FROM LIBRARY_MARTS.REFERENCE.REFERENCE__FED_ITIS_STRIPPEDAUTHOR),
l AS (SELECT TAXON_AUTHOR_ID, SHORT_AUTHOR FROM LIBRARY_MARTS.REFERENCE.REFERENCE__FED_ITIS_TAXON_AUTHORS_LKP)
SELECT COUNT(*) n, COUNT(DISTINCT TAXON_AUTHOR_ID) id_nd, COUNT(DISTINCT SHORT_AUTHOR) sa_nd,
       (SELECT MAX(c) FROM (SELECT COUNT(*) c FROM t GROUP BY TAXON_AUTHOR_ID)) max_per_id,
       (SELECT ARRAY_AGG(s || ' : ' || c) WITHIN GROUP (ORDER BY c DESC) FROM (SELECT SHORT_AUTHOR s, COUNT(*) c FROM t GROUP BY 1 ORDER BY 2 DESC LIMIT 6)) top_short,
       COUNT_IF(SHORT_AUTHOR = 'Schmid-Egger 2022') rows_battery_top,
       COUNT_IF(TAXON_AUTHOR_ID = 0) id0, COUNT_IF(NULLIF(TRIM(SHORT_AUTHOR), '') IS NULL) sa_blank,
       COUNT(DISTINCT _SOURCE_RUN_ID) runs, COUNT(DISTINCT _SRC_SHA256) files,
       (SELECT COUNT(*) FROM l) lkp_n, (SELECT COUNT(DISTINCT TAXON_AUTHOR_ID) FROM l) lkp_id_nd,
       COUNT_IF(TAXON_AUTHOR_ID IN (SELECT TAXON_AUTHOR_ID FROM l)) land_in_lkp,
       (SELECT COUNT(*) FROM t s WHERE EXISTS (SELECT 1 FROM l WHERE l.TAXON_AUTHOR_ID = s.TAXON_AUTHOR_ID AND l.SHORT_AUTHOR = s.SHORT_AUTHOR)) same_text_as_lkp,
       (SELECT COUNT(DISTINCT TAXON_AUTHOR_ID) FROM LIBRARY_MARTS.REFERENCE.REFERENCE__FED_ITIS_TAXONOMIC_UNITS WHERE TAXON_AUTHOR_ID <> 0) tu_author_ids,
       (SELECT COUNT(DISTINCT TAXON_AUTHOR_ID) FROM LIBRARY_MARTS.REFERENCE.REFERENCE__FED_ITIS_TAXONOMIC_UNITS WHERE TAXON_AUTHOR_ID <> 0 AND TAXON_AUTHOR_ID IN (SELECT TAXON_AUTHOR_ID FROM t)) tu_author_ids_in_sa,
       (SELECT ARRAY_AGG(TAXON_AUTHOR_ID || ' | ' || SHORT_AUTHOR) FROM (SELECT * FROM t WHERE MOD(TAXON_AUTHOR_ID, 9973) = 11 LIMIT 8)) eyeball
FROM t;

-- @synonym_shape
WITH t AS (SELECT * FROM LIBRARY_MARTS.REFERENCE.REFERENCE__FED_ITIS_SYNONYM_LINKS)
SELECT COUNT(*) n, COUNT(DISTINCT TSN) tsn_nd, COUNT(DISTINCT TSN_ACCEPTED) acc_nd, COUNT(DISTINCT ITIS_SYNONYM_LINKS_KEY) key_nd,
       COUNT_IF(TSN = TSN_ACCEPTED) self_links,
       (SELECT COUNT(*) FROM (SELECT TSN FROM t GROUP BY 1 HAVING COUNT(DISTINCT TSN_ACCEPTED) > 1)) tsn_multi_acc,
       COUNT_IF(TSN_ACCEPTED IN (SELECT TSN FROM t)) chained_rows,
       (SELECT MEDIAN(c) FROM (SELECT COUNT(*) c FROM t GROUP BY TSN_ACCEPTED)) med_syn_per_acc,
       (SELECT ARRAY_AGG(a || ' : ' || c) WITHIN GROUP (ORDER BY c DESC) FROM (SELECT TSN_ACCEPTED a, COUNT(*) c FROM t GROUP BY 1 ORDER BY 2 DESC LIMIT 6)) top_acc,
       COUNT_IF(LEFT(UPDATE_DATE::VARCHAR, 10) = '1900-01-01') d1900, MIN(UPDATE_DATE)::VARCHAR d0, MAX(UPDATE_DATE)::VARCHAR d1,
       (SELECT OBJECT_AGG(y, c) FROM (SELECT LEFT(UPDATE_DATE::VARCHAR, 4) y, COUNT(*) c FROM t GROUP BY 1)) by_year,
       COUNT(DISTINCT _SOURCE_RUN_ID) runs
FROM t;

-- @synonym_join_taxonomic_units
WITH s AS (SELECT TSN, TSN_ACCEPTED FROM LIBRARY_MARTS.REFERENCE.REFERENCE__FED_ITIS_SYNONYM_LINKS),
tu AS (SELECT TSN, NAME_USAGE, COMPLETE_NAME FROM LIBRARY_MARTS.REFERENCE.REFERENCE__FED_ITIS_TAXONOMIC_UNITS),
top5 AS (SELECT TSN_ACCEPTED, COUNT(*) c FROM s GROUP BY 1 ORDER BY 2 DESC LIMIT 5)
SELECT 'synonym side' side, COALESCE(tu.NAME_USAGE::VARCHAR, '(no taxon row)') label, COUNT(*) n FROM s LEFT JOIN tu ON s.TSN = tu.TSN GROUP BY 1, 2
UNION ALL SELECT 'accepted side', COALESCE(tu.NAME_USAGE::VARCHAR, '(no taxon row)'), COUNT(*) FROM s LEFT JOIN tu ON s.TSN_ACCEPTED = tu.TSN GROUP BY 1, 2
UNION ALL SELECT 'unaccepted names with no link', tu.NAME_USAGE::VARCHAR, COUNT(*) FROM tu WHERE tu.NAME_USAGE IN ('invalid', 'not accepted') AND tu.TSN NOT IN (SELECT TSN FROM s) GROUP BY 1, 2
UNION ALL SELECT 'top accepted', COALESCE(tu.COMPLETE_NAME, '?') || ' (' || top5.TSN_ACCEPTED || ')', top5.c FROM top5 LEFT JOIN tu ON top5.TSN_ACCEPTED = tu.TSN
ORDER BY 1, 3 DESC;
