-- @nodc_code_reuse
WITH t AS (SELECT TSN, NODC_ID FROM LIBRARY_MARTS.REFERENCE.REFERENCE__FED_ITIS_NODC_IDS),
tu AS (SELECT TSN, NAME_USAGE, COMPLETE_NAME FROM LIBRARY_MARTS.REFERENCE.REFERENCE__FED_ITIS_TAXONOMIC_UNITS),
m AS (SELECT NODC_ID FROM t GROUP BY 1 HAVING COUNT(*) > 1),
j AS (SELECT t.NODC_ID, t.TSN, tu.NAME_USAGE u, tu.COMPLETE_NAME nm FROM t JOIN m ON t.NODC_ID = m.NODC_ID LEFT JOIN tu ON t.TSN = tu.TSN),
per AS (SELECT NODC_ID, COUNT(*) c, COUNT_IF(u IN ('valid', 'accepted')) n_ok FROM j GROUP BY 1),
top1 AS (SELECT NODC_ID FROM per ORDER BY c DESC, NODC_ID LIMIT 1)
SELECT 'codes with >1 TSN' k, COUNT(*)::VARCHAR v FROM per
UNION ALL SELECT 'rows on those codes', SUM(c)::VARCHAR FROM per
UNION ALL SELECT 'codes with exactly 1 accepted TSN', COUNT_IF(n_ok = 1)::VARCHAR FROM per
UNION ALL SELECT 'codes with 0 accepted TSN', COUNT_IF(n_ok = 0)::VARCHAR FROM per
UNION ALL SELECT 'codes with 2+ accepted TSN', COUNT_IF(n_ok >= 2)::VARCHAR FROM per
UNION ALL SELECT 'top code ' || MAX(j.NODC_ID), LISTAGG(j.nm || ' [' || j.u || ']', '; ') WITHIN GROUP (ORDER BY j.u DESC, j.nm) FROM j JOIN top1 ON j.NODC_ID = top1.NODC_ID;

-- @county_ct_impact
WITH ct_old AS (SELECT column1 g FROM VALUES ('09001'), ('09003'), ('09005'), ('09007'), ('09009'), ('09011'), ('09013'), ('09015')),
dp AS (SELECT LPAD(TRY_TO_NUMBER(FIPS::VARCHAR)::VARCHAR, 5, '0') g, YEAR y FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CDC_DRUG_POISONING_COUNTY),
iv AS (SELECT LPAD(TRY_TO_NUMBER(GEOID::VARCHAR)::VARCHAR, 5, '0') g, PERIOD p FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CDC_INJURY_VIOLENCE_COUNTY)
SELECT 'dim_county CT population_2020' k, SUM(POPULATION_2020)::VARCHAR v FROM LIBRARY_MARTS.CORE.DIM_COUNTY WHERE LPAD(TRY_TO_NUMBER(STATE_FIPS::VARCHAR)::VARCHAR, 2, '0') = '09'
UNION ALL SELECT 'dim_county CT rows', COUNT(*)::VARCHAR FROM LIBRARY_MARTS.CORE.DIM_COUNTY WHERE LPAD(TRY_TO_NUMBER(STATE_FIPS::VARCHAR)::VARCHAR, 2, '0') = '09'
UNION ALL SELECT 'drug_poisoning CT old-code rows', COUNT(*)::VARCHAR FROM dp WHERE g IN (SELECT g FROM ct_old)
UNION ALL SELECT 'drug_poisoning CT years', MIN(y)::VARCHAR || '-' || MAX(y)::VARCHAR FROM dp WHERE g IN (SELECT g FROM ct_old)
UNION ALL SELECT 'drug_poisoning rows off-map (no CB match, county-level)', COUNT(*)::VARCHAR FROM dp WHERE TRY_TO_NUMBER(g) >= 1000 AND g NOT IN (SELECT GEOID::VARCHAR FROM LIBRARY_MARTS.REFERENCE.REFERENCE__CENSUS_CB_COUNTY)
UNION ALL SELECT 'drug_poisoning county-level rows', COUNT(*)::VARCHAR FROM dp WHERE TRY_TO_NUMBER(g) >= 1000
UNION ALL SELECT 'injury CT old-code rows', COUNT(*)::VARCHAR FROM iv WHERE g IN (SELECT g FROM ct_old)
UNION ALL SELECT 'injury CT periods', COUNT(DISTINCT p)::VARCHAR FROM iv WHERE g IN (SELECT g FROM ct_old);
