{{ config(materialized='view', schema='TIMELINE', alias='FINANCE__FED_SEC_EDGAR_INSIDERS') }}

-- GENERATED by scripts/census/gen_time_views.py -- do not hand-edit.
-- Regenerate after any change to reports/time_index/clock_index.csv.
--
-- Canonical clock for FINANCE.FINANCE__FED_SEC_EDGAR_INSIDERS.
--   column : PERIOD_OF_REPORT   (TEXT)
--   means  : happened -- Raw uncast passthrough; on Forms 3/4/5 the period of report is the date of the event requiring the statement (the transaction), so it is the closest thing to a 
--   grain  : day
--
-- happened cannot be in the future -- if this row's value is, ripple_clock
-- reads 'planned' instead, not 'happened'. See ripple_row_clock in
-- macros/ripple_time.sql.
--
-- The original columns pass through untouched; the canonical four sit in front
-- of them. Rule 8 of the datetime standard: the raw column is never overwritten,
-- so a mis-parse is always recoverable.

select
    {{ ripple_ts_from_date('src."PERIOD_OF_REPORT"') }} as ripple_ts,
    {{ ripple_grain('day') }} as ripple_grain,
    {{ ripple_row_clock(ripple_ts_from_date('src."PERIOD_OF_REPORT"'), 'happened') }} as ripple_clock,
    'FINANCE.FINANCE__FED_SEC_EDGAR_INSIDERS'::varchar as ripple_source,
    src.*
from {{ ref('finance__fed_sec_edgar_insiders') }} as src
