{{ config(materialized='view', schema='TIMELINE', alias='FINANCE__FED_SEC_DERA_SUB_2025Q3') }}

-- GENERATED by scripts/census/gen_time_views.py -- do not hand-edit.
-- Regenerate after any change to reports/time_index/clock_index.csv.
--
-- Canonical clock for FINANCE.FINANCE__FED_SEC_DERA_SUB_2025Q3.
--   column : FILED   (TEXT)
--   means  : reported -- Raw FILED passthrough - the YYYYMMDD SEC filing date; uncast text.
--   grain  : day
--
-- The original columns pass through untouched; the canonical four sit in front
-- of them. Rule 8 of the datetime standard: the raw column is never overwritten,
-- so a mis-parse is always recoverable.

select
    {{ ripple_event_ts(ripple_ts_from_date('src."FILED"')) }} as ripple_ts,
    {{ ripple_grain('day') }} as ripple_grain,
    {{ ripple_clock('reported') }} as ripple_clock,
    'FINANCE.FINANCE__FED_SEC_DERA_SUB_2025Q3'::varchar as ripple_source,
    src.*
from {{ ref('finance__fed_sec_dera_sub_2025q3') }} as src
