{{ config(materialized='table', schema='HEALTH') }}

-- Source: FED_CDC_NNDSS_WEEKLY_2024 (500000 rows)
-- Generated by scripts/gen_mart_models.py

with source as (
    select * from {{ source('ripple_raw', 'FED_CDC_NNDSS_WEEKLY_2024') }}
)

select
    REPORTING_AREA as reporting_area,
    CURRENT_MMWR_YEAR as current_mmwr_year,
    MMWR_WEEK as mmwr_week,
    LABEL as label,
    CURRENT_WEEK as current_week,
    CURRENT_WEEK_FLAG as current_week_flag,
    PREVIOUS_52_WEEK_MAX as previous_52_week_max,
    PREVIOUS_52_WEEKS_MAX_FLAG as previous_52_weeks_max_flag,
    CUMULATIVE_YTD_CURRENT_MMWR_YEAR as cumulative_ytd_current_mmwr_year,
    CUMULATIVE_YTD_CURRENT_MMWR_YEAR_FLAG as cumulative_ytd_current_mmwr_year_flag,
    CUMULATIVE_YTD_PREVIOUS_MMWR_YEAR as cumulative_ytd_previous_mmwr_year,
    CUMULATIVE_YTD_PREVIOUS_MMWR_YEAR_FLAG as cumulative_ytd_previous_mmwr_year_flag,
    LOCATION1 as location1,
    LOCATION2 as location2,
    SORT_ORDER as sort_order,
    GEOCODE as geocode
from source
