{{ config(materialized='table', schema='HEALTH') }}
-- GRAIN: one row per payment record (RECORD_ID)
-- Key: NPI (National Provider Identifier)

with source as (
    select * from {{ source('ripple_raw', 'FED_CMS_OPEN_PAYMENTS_2022') }}
)

select
    RECORD_ID,
    NPI,
    COVERED_RECIPIENT_TYPE,
    COVERED_RECIPIENT_PROFILE_ID,
    COVERED_RECIPIENT_FIRST_NAME,
    COVERED_RECIPIENT_LAST_NAME,
    RECIPIENT_CITY,
    RECIPIENT_STATE,
    RECIPIENT_ZIP_CODE,
    COVERED_RECIPIENT_PRIMARY_TYPE_1,
    COVERED_RECIPIENT_SPECIALTY_1,
    SUBMITTING_APPLICABLE_MANUFACTURER_OR_APPLICABLE_GPO_NAME,
    APPLICABLE_MANUFACTURER_OR_APPLICABLE_GPO_MAKING_PAYMENT_NAME,
    APPLICABLE_MANUFACTURER_OR_APPLICABLE_GPO_MAKING_PAYMENT_STATE,
    TOTAL_AMOUNT_OF_PAYMENT_USDOLLARS,
    DATE_OF_PAYMENT,
    FORM_OF_PAYMENT_OR_TRANSFER_OF_VALUE,
    NATURE_OF_PAYMENT_OR_TRANSFER_OF_VALUE,
    PHYSICIAN_OWNERSHIP_INDICATOR,
    PROGRAM_YEAR,
    TEACHING_HOSPITAL_NAME,
    CCN
from source
