{{ config(materialized='table', schema='HEALTH') }}

-- Source: FED_FDA_FAERS_INDI (9833260 rows)
-- Generated by scripts/gen_mart_models.py

with source as (
    select * from {{ source('ripple_raw', 'FED_FDA_FAERS_INDI') }}
)

select
    ISR as isr,
    DRUG_SEQ as drug_seq,
    INDI_PT as indi_pt,
    _SRC_QUARTER as src_quarter,
    PRIMARYID as primaryid,
    CASEID as caseid,
    INDI_DRUG_SEQ as indi_drug_seq
from source
