{{ config(materialized='table', schema='HEALTH') }}

-- Source: FED_CMS_SKILLED_NURSING_FACILITY_ENROLLMENTS (14425 rows)
-- Generated by scripts/gen_mart_models.py
-- Fixed 2026-09-20: was reading source() with a bare try_to_date() on
-- INCORPORATION_DATE -- unguarded against the epoch trap (a pure-digit value
-- silently reads as epoch seconds). Live-checked all 14,425 rows: 8,989
-- filled, 0 pure-digit, 0 no-separator (all ordinary dashed dates) -- clean
-- today, but a landmine on the next load, not a live bug. A matching staging
-- model exists (stg_fed_cms_skilled_nursing_facility_enrollments__records)
-- but it also casts AFFILIATION_ENTITY_ID to a guarded int, where this mart
-- deliberately leaves that column as plain text (no cast at all) -- swapping
-- to ref() would silently change that untouched column's type, so this stays
-- on source() and only the one bare cast this mart already makes is wrapped,
-- with stg_date (macros/staging_casts.sql).

with source as (
    select * from {{ source('ripple_raw', 'FED_CMS_SKILLED_NURSING_FACILITY_ENROLLMENTS') }}
)

select
    ENROLLMENT_ID as enrollment_id,
    ENROLLMENT_STATE as enrollment_state,
    PROVIDER_TYPE_CODE as provider_type_code,
    PROVIDER_TYPE_TEXT as provider_type_text,
    NPI as npi,
    MULTIPLE_NPI_FLAG as multiple_npi_flag,
    CCN as ccn,
    ASSOCIATE_ID as associate_id,
    ORGANIZATION_NAME as organization_name,
    DOING_BUSINESS_AS_NAME as doing_business_as_name,
    {{ stg_date('INCORPORATION_DATE') }} as incorporation_date,
    INCORPORATION_STATE as incorporation_state,
    ORGANIZATION_TYPE_STRUCTURE as organization_type_structure,
    ORGANIZATION_OTHER_TYPE_TEXT as organization_other_type_text,
    PROPRIETARY_NONPROFIT as proprietary_nonprofit,
    NURSING_HOME_PROVIDER_NAME as nursing_home_provider_name,
    AFFILIATION_ENTITY_NAME as affiliation_entity_name,
    AFFILIATION_ENTITY_ID as affiliation_entity_id,
    ADDRESS_LINE_1 as address_line_1,
    ADDRESS_LINE_2 as address_line_2,
    CITY as city,
    STATE as state,
    ZIP_CODE as zip_code
from source
