{{ config(materialized='table', schema='HEALTH') }}

-- Source: FED_CMS_MEDICARE_INPATIENT_HOSPITALS_BY_PROVIDER (3044 rows)
-- Generated by scripts/gen_mart_models.py
-- Fixed 2026-09-20: 41 bare try_to_number()/try_to_double() casts -- a landmine,
-- not an active bug today (live-checked: 0 of 3,044 rows round on any of the 14
-- BENE_* count columns, 0 literal 'nan' anywhere). Stayed on source() instead of
-- the stg_fed_cms_medicare_inpatient_hospitals_by_provider__facilities staging
-- model that exists for this same table: that model's generator marks
-- TOT_PYMT_AMT and TOT_MDCR_PYMT_AMT "ID: whole numbers, over 90% distinct" and
-- keeps them TEXT, because every one of this table's 3,044 rows for both
-- columns is a whole dollar figure (live-checked) -- but they are payment
-- DOLLAR AMOUNTS, not identifiers, and this mart already types them as numbers.
-- Ref-swapping would silently turn a summable float into un-summable TEXT.
-- Wrapped the casts in place instead: try_to_double -> stg_float for the two
-- amount columns, try_to_number -> stg_int for the 14 whole-number BENE_* counts.

with source as (
    select * from {{ source('ripple_raw', 'FED_CMS_MEDICARE_INPATIENT_HOSPITALS_BY_PROVIDER') }}
)

select
    RNDRNG_PRVDR_CCN as rndrng_prvdr_ccn,
    RNDRNG_PRVDR_ORG_NAME as rndrng_prvdr_org_name,
    RNDRNG_PRVDR_ST as rndrng_prvdr_st,
    RNDRNG_PRVDR_CITY as rndrng_prvdr_city,
    RNDRNG_PRVDR_ZIP5 as rndrng_prvdr_zip5,
    RNDRNG_PRVDR_STATE_ABRVTN as rndrng_prvdr_state_abrvtn,
    RNDRNG_PRVDR_STATE_FIPS as rndrng_prvdr_state_fips,
    RNDRNG_PRVDR_RUCA as rndrng_prvdr_ruca,
    RNDRNG_PRVDR_RUCA_DESC as rndrng_prvdr_ruca_desc,
    TOT_BENES as tot_benes,
    TOT_SUBMTD_CVRD_CHRG as tot_submtd_cvrd_chrg,
    {{ stg_float('TOT_PYMT_AMT') }} as tot_pymt_amt,
    {{ stg_float('TOT_MDCR_PYMT_AMT') }} as tot_mdcr_pymt_amt,
    TOT_DSCHRGS as tot_dschrgs,
    TOT_CVRD_DAYS as tot_cvrd_days,
    TOT_DAYS as tot_days,
    {{ ripple_num('BENE_AVG_AGE') }} as bene_avg_age,
    {{ stg_int('BENE_AGE_LT_65_CNT') }} as bene_age_lt_65_cnt,
    {{ stg_int('BENE_AGE_65_74_CNT') }} as bene_age_65_74_cnt,
    {{ stg_int('BENE_AGE_75_84_CNT') }} as bene_age_75_84_cnt,
    {{ stg_int('BENE_AGE_GT_84_CNT') }} as bene_age_gt_84_cnt,
    {{ stg_int('BENE_FEML_CNT') }} as bene_feml_cnt,
    {{ stg_int('BENE_MALE_CNT') }} as bene_male_cnt,
    {{ stg_int('BENE_RACE_WHT_CNT') }} as bene_race_wht_cnt,
    {{ stg_int('BENE_RACE_BLACK_CNT') }} as bene_race_black_cnt,
    {{ stg_int('BENE_RACE_API_CNT') }} as bene_race_api_cnt,
    {{ stg_int('BENE_RACE_HSPNC_CNT') }} as bene_race_hspnc_cnt,
    {{ stg_int('BENE_RACE_NATIND_CNT') }} as bene_race_natind_cnt,
    {{ stg_int('BENE_RACE_OTHR_CNT') }} as bene_race_othr_cnt,
    {{ stg_int('BENE_DUAL_CNT') }} as bene_dual_cnt,
    {{ stg_int('BENE_NDUAL_CNT') }} as bene_ndual_cnt,
    {{ stg_float('BENE_CC_BH_ADHD_OTHCD_V1_PCT') }} as bene_cc_bh_adhd_othcd_v1_pct,
    {{ stg_float('BENE_CC_BH_ALCOHOL_DRUG_V1_PCT') }} as bene_cc_bh_alcohol_drug_v1_pct,
    {{ stg_float('BENE_CC_BH_TOBACCO_V1_PCT') }} as bene_cc_bh_tobacco_v1_pct,
    {{ stg_float('BENE_CC_BH_ALZ_NONALZDEM_V2_PCT') }} as bene_cc_bh_alz_nonalzdem_v2_pct,
    {{ stg_float('BENE_CC_BH_ANXIETY_V1_PCT') }} as bene_cc_bh_anxiety_v1_pct,
    {{ stg_float('BENE_CC_BH_BIPOLAR_V1_PCT') }} as bene_cc_bh_bipolar_v1_pct,
    {{ stg_float('BENE_CC_BH_MOOD_V2_PCT') }} as bene_cc_bh_mood_v2_pct,
    {{ stg_float('BENE_CC_BH_DEPRESS_V1_PCT') }} as bene_cc_bh_depress_v1_pct,
    {{ stg_float('BENE_CC_BH_PD_V1_PCT') }} as bene_cc_bh_pd_v1_pct,
    {{ stg_float('BENE_CC_BH_PTSD_V1_PCT') }} as bene_cc_bh_ptsd_v1_pct,
    {{ stg_float('BENE_CC_BH_SCHIZO_OTHPSY_V1_PCT') }} as bene_cc_bh_schizo_othpsy_v1_pct,
    {{ stg_float('BENE_CC_PH_ASTHMA_V2_PCT') }} as bene_cc_ph_asthma_v2_pct,
    {{ stg_float('BENE_CC_PH_AFIB_V2_PCT') }} as bene_cc_ph_afib_v2_pct,
    {{ stg_float('BENE_CC_PH_CANCER6_V2_PCT') }} as bene_cc_ph_cancer6_v2_pct,
    {{ stg_float('BENE_CC_PH_CKD_V2_PCT') }} as bene_cc_ph_ckd_v2_pct,
    {{ stg_float('BENE_CC_PH_COPD_V2_PCT') }} as bene_cc_ph_copd_v2_pct,
    {{ stg_float('BENE_CC_PH_DIABETES_V2_PCT') }} as bene_cc_ph_diabetes_v2_pct,
    {{ stg_float('BENE_CC_PH_HF_NONIHD_V2_PCT') }} as bene_cc_ph_hf_nonihd_v2_pct,
    {{ stg_float('BENE_CC_PH_HYPERLIPIDEMIA_V2_PCT') }} as bene_cc_ph_hyperlipidemia_v2_pct,
    {{ stg_float('BENE_CC_PH_HYPERTENSION_V2_PCT') }} as bene_cc_ph_hypertension_v2_pct,
    {{ stg_float('BENE_CC_PH_ISCHEMICHEART_V2_PCT') }} as bene_cc_ph_ischemicheart_v2_pct,
    {{ stg_float('BENE_CC_PH_OSTEOPOROSIS_V2_PCT') }} as bene_cc_ph_osteoporosis_v2_pct,
    {{ stg_float('BENE_CC_PH_PARKINSON_V2_PCT') }} as bene_cc_ph_parkinson_v2_pct,
    {{ stg_float('BENE_CC_PH_ARTHRITIS_V2_PCT') }} as bene_cc_ph_arthritis_v2_pct,
    {{ stg_float('BENE_CC_PH_STROKE_TIA_V2_PCT') }} as bene_cc_ph_stroke_tia_v2_pct,
    {{ ripple_num('BENE_AVG_RISK_SCRE') }} as bene_avg_risk_scre
from source
