{{ config(materialized='table', schema='HEALTH') }}

-- Source: FED_CMS_AMBULATORY_SPECIALTY_MODEL_PARTICIPANTS (6637 rows)
-- Generated by scripts/gen_mart_models.py

with source as (
    select * from {{ source('ripple_raw', 'FED_CMS_AMBULATORY_SPECIALTY_MODEL_PARTICIPANTS') }}
)

select
    NPI as npi,
    FIRST_NAME as first_name,
    LAST_NAME as last_name,
    STATE as state,
    ASM_COHORT as asm_cohort,
    ORGANIZATION_LEGAL_NAME as organization_legal_name,
    ASM_CY27_PARTICIPANT as asm_cy27_participant,
    ASM_CY27_SMALLPRACTICE as asm_cy27_smallpractice,
    ASM_CY28_PARTICIPANT as asm_cy28_participant,
    ASM_CY28_SMALLPRACTICE as asm_cy28_smallpractice,
    ASM_CY29_PARTICIPANT as asm_cy29_participant,
    ASM_CY29_SMALLPRACTICE as asm_cy29_smallpractice,
    ASM_CY30_PARTICIPANT as asm_cy30_participant,
    ASM_CY30_SMALLPRACTICE as asm_cy30_smallpractice,
    ASM_CY31_PARTICIPANT as asm_cy31_participant,
    ASM_CY31_SMALLPRACTICE as asm_cy31_smallpractice
from source
