{{ config(materialized='table', schema='HEALTH') }}

-- Source: FED_CMS_MEDICARE_INPATIENT_HOSPITALS_BY_PROVIDER_AND_SERVICE (145879 rows)
-- Generated by scripts/gen_mart_models.py

with source as (
    select * from {{ source('ripple_raw', 'FED_CMS_MEDICARE_INPATIENT_HOSPITALS_BY_PROVIDER_AND_SERVICE') }}
)

select
    RNDRNG_PRVDR_CCN as rndrng_prvdr_ccn,
    RNDRNG_PRVDR_ORG_NAME as rndrng_prvdr_org_name,
    RNDRNG_PRVDR_CITY as rndrng_prvdr_city,
    RNDRNG_PRVDR_ST as rndrng_prvdr_st,
    RNDRNG_PRVDR_STATE_FIPS as rndrng_prvdr_state_fips,
    RNDRNG_PRVDR_ZIP5 as rndrng_prvdr_zip5,
    RNDRNG_PRVDR_STATE_ABRVTN as rndrng_prvdr_state_abrvtn,
    RNDRNG_PRVDR_RUCA as rndrng_prvdr_ruca,
    RNDRNG_PRVDR_RUCA_DESC as rndrng_prvdr_ruca_desc,
    DRG_CD as drg_cd,
    DRG_DESC as drg_desc,
    TOT_DSCHRGS as tot_dschrgs,
    AVG_SUBMTD_CVRD_CHRG as avg_submtd_cvrd_chrg,
    try_to_double(AVG_TOT_PYMT_AMT) as avg_tot_pymt_amt,
    try_to_double(AVG_MDCR_PYMT_AMT) as avg_mdcr_pymt_amt
from source
