{{ config(materialized='table', schema='HEALTH') }}

-- Source: FED_CMS_PECOS_PROVIDER_ENROLLMENT (2978925 rows)
-- Generated by scripts/gen_mart_models.py
-- Fixed 2026-09-20: PECOS_ASCT_CNTL_ID was a bare try_to_number() -- unguarded,
-- so any non-whole value would silently round instead of reading NULL.
-- Live-checked a 1M-row sample of this table directly: 0 fractional values,
-- 0 non-numeric filled values -- clean today, a landmine not a live bug. No
-- staging model exists for this exact source table (checked models/staging/;
-- the sibling FED_CMS_MEDICARE_FEE_FOR_SERVICE_PUBLIC_PROVIDER_ENROLLMENT
-- table has one, but it leaves this same column as TEXT, a different type
-- than this mart wants), so this stays on source() -- the bare cast is
-- wrapped with stg_int (macros/staging_casts.sql), keeping the mart's
-- existing whole-number type.

with source as (
    select * from {{ source('ripple_raw', 'FED_CMS_PECOS_PROVIDER_ENROLLMENT') }}
)

select
    NPI as npi,
    MULTIPLE_NPI_FLAG as multiple_npi_flag,
    {{ stg_int('PECOS_ASCT_CNTL_ID') }} as pecos_asct_cntl_id,
    ENRLMT_ID as enrlmt_id,
    PROVIDER_TYPE_CD as provider_type_cd,
    PROVIDER_TYPE_DESC as provider_type_desc,
    STATE_CD as state_cd,
    FIRST_NAME as first_name,
    MDL_NAME as mdl_name,
    LAST_NAME as last_name,
    ORG_NAME as org_name
from source
