{{ config(materialized='table', schema='HEALTH') }}

-- Source: FED_CMS_HOME_HEALTH_AGENCY_ENROLLMENTS (11508 rows)
-- Generated by scripts/gen_mart_models.py
-- Fixed 2026-09-20: was reading source() with a bare try_to_date() on
-- INCORPORATION_DATE -- unguarded against the epoch trap (a pure-digit value
-- silently reads as epoch seconds). Live-checked all 11,508 rows: 9,211
-- filled, 0 pure-digit, 0 no-separator (all ordinary dashed dates) -- clean
-- today, but a landmine on the next load, not a live bug. Now reads the
-- already-guarded staging model instead -- same 22 columns, same names, same
-- order; its one date cast runs through stg_date (macros/staging_casts.sql),
-- which regex-guards first and reads NULL instead of a wrong date.

select
    enrollment_id,
    enrollment_state,
    provider_type_code,
    provider_type_text,
    npi,
    multiple_npi_flag,
    ccn,
    associate_id,
    organization_name,
    doing_business_as_name,
    incorporation_date,
    incorporation_state,
    organization_type_structure,
    organization_other_type_text,
    proprietary_nonprofit,
    address_line_1,
    address_line_2,
    city,
    state,
    zip_code,
    practice_location_type,
    location_other_type_text
from {{ ref('stg_fed_cms_home_health_agency_enrollments__records') }}
