{{ config(tags=['spine_generated']) }}

-- GRAIN: one row per record (spine_entity not determined -- no registry hint available) (OBJECT_ID unique)
-- SPINE_ENTITY: (not determined)  (natural_key: OBJECT_ID)
-- Generated by scripts/generate_staging_models.py from SOURCE_REGISTRY -- deterministic,
-- no LLM. Casts kept as landed (TEXT) -- add explicit type casts by hand once each
-- column's real type is confirmed; this generator has no semantic type knowledge.
-- spine_entity not determined (grain/natural_key proven, but no registry hint says what this row is ABOUT) -- no SPINE_ENTITY_ID emitted.

with source as (

    select * from {{ source('ripple_raw', 'FED_DENSHO_DDR') }}

),

renamed as (

    select
        "OBJECT_ID" as object_id,
        "COLLECTION_ID" as collection_id,
        "TITLE" as title,
        "OBJECT_TYPE" as object_type,
        "NARRATOR" as narrator,
        "FACILITY" as facility,
        "TOPIC" as topic,
        "DATE" as date,
        "DESCRIPTION" as description,
        "RIGHTS" as rights,
        "URL" as url,
        "FIPS" as fips,
        _INGESTED_AT as _loaded_at,
        'https://ddr.densho.org/' as _source_url

    from source

)

select * from renamed
qualify row_number() over (partition by object_id order by _loaded_at desc) = 1
