{{ config(materialized='view') }}

with source as (

    select * from {{ source('ripple_raw', 'FED_CMS_NPPES') }}

),

renamed as (

    select

        -- primary identifiers
        nullif(trim(NPI), '')                                                        as npi,
        nullif(trim(EMPLOYER_IDENTIFICATION_NUMBER_EIN), '')                         as ein,
        try_to_number(nullif(trim(ENTITY_TYPE_CODE), ''))                            as entity_type_code,
        nullif(trim(REPLACEMENT_NPI), '')                                            as replacement_npi,

        -- organization name
        nullif(trim(PROVIDER_ORGANIZATION_NAME_LEGAL_BUSINESS_NAME), '')             as provider_organization_name_legal_business_name,
        nullif(trim(PROVIDER_OTHER_ORGANIZATION_NAME), '')                           as provider_other_organization_name,
        nullif(trim(PROVIDER_OTHER_ORGANIZATION_NAME_TYPE_CODE), '')                 as provider_other_organization_name_type_code,

        -- individual provider name
        nullif(trim(PROVIDER_LAST_NAME_LEGAL_NAME), '')                              as provider_last_name,
        nullif(trim(PROVIDER_FIRST_NAME), '')                                        as provider_first_name,
        nullif(trim(PROVIDER_MIDDLE_NAME), '')                                       as provider_middle_name,
        nullif(trim(PROVIDER_NAME_PREFIX_TEXT), '')                                  as provider_name_prefix,
        nullif(trim(PROVIDER_NAME_SUFFIX_TEXT), '')                                  as provider_name_suffix,
        nullif(trim(PROVIDER_CREDENTIAL_TEXT), '')                                   as provider_credential,

        -- other provider name
        nullif(trim(PROVIDER_OTHER_LAST_NAME), '')                                   as provider_other_last_name,
        nullif(trim(PROVIDER_OTHER_FIRST_NAME), '')                                  as provider_other_first_name,
        nullif(trim(PROVIDER_OTHER_MIDDLE_NAME), '')                                 as provider_other_middle_name,
        nullif(trim(PROVIDER_OTHER_NAME_PREFIX_TEXT), '')                            as provider_other_name_prefix,
        nullif(trim(PROVIDER_OTHER_NAME_SUFFIX_TEXT), '')                            as provider_other_name_suffix,
        nullif(trim(PROVIDER_OTHER_CREDENTIAL_TEXT), '')                             as provider_other_credential,
        nullif(trim(PROVIDER_OTHER_LAST_NAME_TYPE_CODE), '')                         as provider_other_last_name_type_code,

        -- mailing address
        nullif(trim(PROVIDER_FIRST_LINE_BUSINESS_MAILING_ADDRESS), '')               as mailing_address_line_1,
        nullif(trim(PROVIDER_SECOND_LINE_BUSINESS_MAILING_ADDRESS), '')              as mailing_address_line_2,
        nullif(trim(PROVIDER_BUSINESS_MAILING_ADDRESS_CITY_NAME), '')                as mailing_city,
        nullif(trim(PROVIDER_BUSINESS_MAILING_ADDRESS_STATE_NAME), '')               as mailing_state,
        nullif(trim(PROVIDER_BUSINESS_MAILING_ADDRESS_POSTAL_CODE), '')              as mailing_zip,
        nullif(trim(PROVIDER_BUSINESS_MAILING_ADDRESS_COUNTRY_CODE_IF_OUTSIDE_U_S), '') as mailing_country_code,
        nullif(trim(PROVIDER_BUSINESS_MAILING_ADDRESS_TELEPHONE_NUMBER), '')         as mailing_phone,
        nullif(trim(PROVIDER_BUSINESS_MAILING_ADDRESS_FAX_NUMBER), '')               as mailing_fax,

        -- practice location address
        nullif(trim(PROVIDER_FIRST_LINE_BUSINESS_PRACTICE_LOCATION_ADDRESS), '')     as practice_address_line_1,
        nullif(trim(PROVIDER_SECOND_LINE_BUSINESS_PRACTICE_LOCATION_ADDRESS), '')    as practice_address_line_2,
        nullif(trim(PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_CITY_NAME), '')      as practice_city,
        nullif(trim(PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_STATE_NAME), '')     as practice_state,
        nullif(trim(PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_POSTAL_CODE), '')    as practice_zip,
        nullif(trim(PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_COUNTRY_CODE_IF_OUTSIDE_U_S), '') as practice_country_code,
        nullif(trim(PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_TELEPHONE_NUMBER), '') as practice_phone,
        nullif(trim(PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_FAX_NUMBER), '')     as practice_fax,

        -- enumeration / status dates
        try_to_date(nullif(trim(PROVIDER_ENUMERATION_DATE), ''), 'MM/DD/YYYY')       as provider_enumeration_date,
        try_to_date(nullif(trim(LAST_UPDATE_DATE), ''), 'MM/DD/YYYY')                as last_update_date,
        nullif(trim(NPI_DEACTIVATION_REASON_CODE), '')                               as npi_deactivation_reason_code,
        try_to_date(nullif(trim(NPI_DEACTIVATION_DATE), ''), 'MM/DD/YYYY')           as npi_deactivation_date,
        try_to_date(nullif(trim(NPI_REACTIVATION_DATE), ''), 'MM/DD/YYYY')           as npi_reactivation_date,
        try_to_date(nullif(trim(CERTIFICATION_DATE), ''), 'MM/DD/YYYY')              as certification_date,

        -- demographics
        nullif(trim(PROVIDER_SEX_CODE), '')                                          as provider_sex_code,

        -- authorized official
        nullif(trim(AUTHORIZED_OFFICIAL_LAST_NAME), '')                              as authorized_official_last_name,
        nullif(trim(AUTHORIZED_OFFICIAL_FIRST_NAME), '')                             as authorized_official_first_name,
        nullif(trim(AUTHORIZED_OFFICIAL_MIDDLE_NAME), '')                            as authorized_official_middle_name,
        nullif(trim(AUTHORIZED_OFFICIAL_TITLE_OR_POSITION), '')                      as authorized_official_title,
        nullif(trim(AUTHORIZED_OFFICIAL_TELEPHONE_NUMBER), '')                       as authorized_official_phone,
        nullif(trim(AUTHORIZED_OFFICIAL_NAME_PREFIX_TEXT), '')                       as authorized_official_name_prefix,
        nullif(trim(AUTHORIZED_OFFICIAL_NAME_SUFFIX_TEXT), '')                       as authorized_official_name_suffix,
        nullif(trim(AUTHORIZED_OFFICIAL_CREDENTIAL_TEXT), '')                        as authorized_official_credential,

        -- organization flags
        nullif(trim(IS_SOLE_PROPRIETOR), '')                                         as is_sole_proprietor,
        nullif(trim(IS_ORGANIZATION_SUBPART), '')                                    as is_organization_subpart,
        nullif(trim(PARENT_ORGANIZATION_LBN), '')                                    as parent_organization_lbn,
        nullif(trim(PARENT_ORGANIZATION_TIN), '')                                    as parent_organization_tin,

        -- taxonomy slot 1
        nullif(trim(HEALTHCARE_PROVIDER_TAXONOMY_CODE_1), '')                        as taxonomy_code_1,
        nullif(trim(PROVIDER_LICENSE_NUMBER_1), '')                                  as license_number_1,
        nullif(trim(PROVIDER_LICENSE_NUMBER_STATE_CODE_1), '')                       as license_state_1,
        nullif(trim(HEALTHCARE_PROVIDER_PRIMARY_TAXONOMY_SWITCH_1), '')              as primary_taxonomy_switch_1,
        nullif(trim(HEALTHCARE_PROVIDER_TAXONOMY_GROUP_1), '')                       as taxonomy_group_1,

        -- taxonomy slot 2
        nullif(trim(HEALTHCARE_PROVIDER_TAXONOMY_CODE_2), '')                        as taxonomy_code_2,
        nullif(trim(PROVIDER_LICENSE_NUMBER_2), '')                                  as license_number_2,
        nullif(trim(PROVIDER_LICENSE_NUMBER_STATE_CODE_2), '')                       as license_state_2,
        nullif(trim(HEALTHCARE_PROVIDER_PRIMARY_TAXONOMY_SWITCH_2), '')              as primary_taxonomy_switch_2,
        nullif(trim(HEALTHCARE_PROVIDER_TAXONOMY_GROUP_2), '')                       as taxonomy_group_2,

        -- taxonomy slot 3
        nullif(trim(HEALTHCARE_PROVIDER_TAXONOMY_CODE_3), '')                        as taxonomy_code_3,
        nullif(trim(PROVIDER_LICENSE_NUMBER_3), '')                                  as license_number_3,
        nullif(trim(PROVIDER_LICENSE_NUMBER_STATE_CODE_3), '')                       as license_state_3,
        nullif(trim(HEALTHCARE_PROVIDER_PRIMARY_TAXONOMY_SWITCH_3), '')              as primary_taxonomy_switch_3,
        nullif(trim(HEALTHCARE_PROVIDER_TAXONOMY_GROUP_3), '')                       as taxonomy_group_3,

        -- taxonomy slot 4
        nullif(trim(HEALTHCARE_PROVIDER_TAXONOMY_CODE_4), '')                        as taxonomy_code_4,
        nullif(trim(PROVIDER_LICENSE_NUMBER_4), '')                                  as license_number_4,
        nullif(trim(PROVIDER_LICENSE_NUMBER_STATE_CODE_4), '')                       as license_state_4,
        nullif(trim(HEALTHCARE_PROVIDER_PRIMARY_TAXONOMY_SWITCH_4), '')              as primary_taxonomy_switch_4,
        nullif(trim(HEALTHCARE_PROVIDER_TAXONOMY_GROUP_4), '')                       as taxonomy_group_4,

        -- taxonomy slot 5
        nullif(trim(HEALTHCARE_PROVIDER_TAXONOMY_CODE_5), '')                        as taxonomy_code_5,
        nullif(trim(PROVIDER_LICENSE_NUMBER_5), '')                                  as license_number_5,
        nullif(trim(PROVIDER_LICENSE_NUMBER_STATE_CODE_5), '')                       as license_state_5,
        nullif(trim(HEALTHCARE_PROVIDER_PRIMARY_TAXONOMY_SWITCH_5), '')              as primary_taxonomy_switch_5,
        nullif(trim(HEALTHCARE_PROVIDER_TAXONOMY_GROUP_5), '')                       as taxonomy_group_5,

        -- taxonomy slot 6
        nullif(trim(HEALTHCARE_PROVIDER_TAXONOMY_CODE_6), '')                        as taxonomy_code_6,
        nullif(trim(PROVIDER_LICENSE_NUMBER_6), '')                                  as license_number_6,
        nullif(trim(PROVIDER_LICENSE_NUMBER_STATE_CODE_6), '')                       as license_state_6,
        nullif(trim(HEALTHCARE_PROVIDER_PRIMARY_TAXONOMY_SWITCH_6), '')              as primary_taxonomy_switch_6,
        nullif(trim(HEALTHCARE_PROVIDER_TAXONOMY_GROUP_6), '')                       as taxonomy_group_6,

        -- taxonomy slot 7
        nullif(trim(HEALTHCARE_PROVIDER_TAXONOMY_CODE_7), '')                        as taxonomy_code_7,
        nullif(trim(PROVIDER_LICENSE_NUMBER_7), '')                                  as license_number_7,
        nullif(trim(PROVIDER_LICENSE_NUMBER_STATE_CODE_7), '')                       as license_state_7,
        nullif(trim(HEALTHCARE_PROVIDER_PRIMARY_TAXONOMY_SWITCH_7), '')              as primary_taxonomy_switch_7,
        nullif(trim(HEALTHCARE_PROVIDER_TAXONOMY_GROUP_7), '')                       as taxonomy_group_7,

        -- taxonomy slot 8
        nullif(trim(HEALTHCARE_PROVIDER_TAXONOMY_CODE_8), '')                        as taxonomy_code_8,
        nullif(trim(PROVIDER_LICENSE_NUMBER_8), '')                                  as license_number_8,
        nullif(trim(PROVIDER_LICENSE_NUMBER_STATE_CODE_8), '')                       as license_state_8,
        nullif(trim(HEALTHCARE_PROVIDER_PRIMARY_TAXONOMY_SWITCH_8), '')              as primary_taxonomy_switch_8,
        nullif(trim(HEALTHCARE_PROVIDER_TAXONOMY_GROUP_8), '')                       as taxonomy_group_8,

        -- taxonomy slot 9
        nullif(trim(HEALTHCARE_PROVIDER_TAXONOMY_CODE_9), '')                        as taxonomy_code_9,
        nullif(trim(PROVIDER_LICENSE_NUMBER_9), '')                                  as license_number_9,
        nullif(trim(PROVIDER_LICENSE_NUMBER_STATE_CODE_9), '')                       as license_state_9,
        nullif(trim(HEALTHCARE_PROVIDER_PRIMARY_TAXONOMY_SWITCH_9), '')              as primary_taxonomy_switch_9,
        nullif(trim(HEALTHCARE_PROVIDER_TAXONOMY_GROUP_9), '')                       as taxonomy_group_9,

        -- taxonomy slot 10
        nullif(trim(HEALTHCARE_PROVIDER_TAXONOMY_CODE_10), '')                       as taxonomy_code_10,
        nullif(trim(PROVIDER_LICENSE_NUMBER_10), '')                                 as license_number_10,
        nullif(trim(PROVIDER_LICENSE_NUMBER_STATE_CODE_10), '')                      as license_state_10,
        nullif(trim(HEALTHCARE_PROVIDER_PRIMARY_TAXONOMY_SWITCH_10), '')             as primary_taxonomy_switch_10,
        nullif(trim(HEALTHCARE_PROVIDER_TAXONOMY_GROUP_10), '')                      as taxonomy_group_10,

        -- taxonomy slot 11
        nullif(trim(HEALTHCARE_PROVIDER_TAXONOMY_CODE_11), '')                       as taxonomy_code_11,
        nullif(trim(PROVIDER_LICENSE_NUMBER_11), '')                                 as license_number_11,
        nullif(trim(PROVIDER_LICENSE_NUMBER_STATE_CODE_11), '')                      as license_state_11,
        nullif(trim(HEALTHCARE_PROVIDER_PRIMARY_TAXONOMY_SWITCH_11), '')             as primary_taxonomy_switch_11,
        nullif(trim(HEALTHCARE_PROVIDER_TAXONOMY_GROUP_11), '')                      as taxonomy_group_11,

        -- taxonomy slot 12
        nullif(trim(HEALTHCARE_PROVIDER_TAXONOMY_CODE_12), '')                       as taxonomy_code_12,
        nullif(trim(PROVIDER_LICENSE_NUMBER_12), '')                                 as license_number_12,
        nullif(trim(PROVIDER_LICENSE_NUMBER_STATE_CODE_12), '')                      as license_state_12,
        nullif(trim(HEALTHCARE_PROVIDER_PRIMARY_TAXONOMY_SWITCH_12), '')             as primary_taxonomy_switch_12,
        nullif(trim(HEALTHCARE_PROVIDER_TAXONOMY_GROUP_12), '')                      as taxonomy_group_12,

        -- taxonomy slot 13
        nullif(trim(HEALTHCARE_PROVIDER_TAXONOMY_CODE_13), '')                       as taxonomy_code_13,
        nullif(trim(PROVIDER_LICENSE_NUMBER_13), '')                                 as license_number_13,
        nullif(trim(PROVIDER_LICENSE_NUMBER_STATE_CODE_13), '')                      as license_state_13,
        nullif(trim(HEALTHCARE_PROVIDER_PRIMARY_TAXONOMY_SWITCH_13), '')             as primary_taxonomy_switch_13,
        nullif(trim(HEALTHCARE_PROVIDER_TAXONOMY_GROUP_13), '')                      as taxonomy_group_13,

        -- taxonomy slot 14
        nullif(trim(HEALTHCARE_PROVIDER_TAXONOMY_CODE_14), '')                       as taxonomy_code_14,
        nullif(trim(PROVIDER_LICENSE_NUMBER_14), '')                                 as license_number_14,
        nullif(trim(PROVIDER_LICENSE_NUMBER_STATE_CODE_14), '')                      as license_state_14,
        nullif(trim(HEALTHCARE_PROVIDER_PRIMARY_TAXONOMY_SWITCH_14), '')             as primary_taxonomy_switch_14,
        nullif(trim(HEALTHCARE_PROVIDER_TAXONOMY_GROUP_14), '')                      as taxonomy_group_14,

        -- taxonomy slot 15
        nullif(trim(HEALTHCARE_PROVIDER_TAXONOMY_CODE_15), '')                       as taxonomy_code_15,
        nullif(trim(PROVIDER_LICENSE_NUMBER_15), '')                                 as license_number_15,
        nullif(trim(PROVIDER_LICENSE_NUMBER_STATE_CODE_15), '')                      as license_state_15,
        nullif(trim(HEALTHCARE_PROVIDER_PRIMARY_TAXONOMY_SWITCH_15), '')             as primary_taxonomy_switch_15,
        nullif(trim(HEALTHCARE_PROVIDER_TAXONOMY_GROUP_15), '')                      as taxonomy_group_15,

        -- other identifiers 1-10
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_1), '')                                as other_identifier_1,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_TYPE_CODE_1), '')                      as other_identifier_type_1,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_STATE_1), '')                          as other_identifier_state_1,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_ISSUER_1), '')                         as other_identifier_issuer_1,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_2), '')                                as other_identifier_2,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_TYPE_CODE_2), '')                      as other_identifier_type_2,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_STATE_2), '')                          as other_identifier_state_2,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_ISSUER_2), '')                         as other_identifier_issuer_2,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_3), '')                                as other_identifier_3,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_TYPE_CODE_3), '')                      as other_identifier_type_3,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_STATE_3), '')                          as other_identifier_state_3,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_ISSUER_3), '')                         as other_identifier_issuer_3,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_4), '')                                as other_identifier_4,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_TYPE_CODE_4), '')                      as other_identifier_type_4,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_STATE_4), '')                          as other_identifier_state_4,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_ISSUER_4), '')                         as other_identifier_issuer_4,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_5), '')                                as other_identifier_5,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_TYPE_CODE_5), '')                      as other_identifier_type_5,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_STATE_5), '')                          as other_identifier_state_5,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_ISSUER_5), '')                         as other_identifier_issuer_5,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_6), '')                                as other_identifier_6,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_TYPE_CODE_6), '')                      as other_identifier_type_6,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_STATE_6), '')                          as other_identifier_state_6,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_ISSUER_6), '')                         as other_identifier_issuer_6,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_7), '')                                as other_identifier_7,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_TYPE_CODE_7), '')                      as other_identifier_type_7,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_STATE_7), '')                          as other_identifier_state_7,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_ISSUER_7), '')                         as other_identifier_issuer_7,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_8), '')                                as other_identifier_8,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_TYPE_CODE_8), '')                      as other_identifier_type_8,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_STATE_8), '')                          as other_identifier_state_8,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_ISSUER_8), '')                         as other_identifier_issuer_8,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_9), '')                                as other_identifier_9,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_TYPE_CODE_9), '')                      as other_identifier_type_9,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_STATE_9), '')                          as other_identifier_state_9,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_ISSUER_9), '')                         as other_identifier_issuer_9,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_10), '')                               as other_identifier_10,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_TYPE_CODE_10), '')                     as other_identifier_type_10,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_STATE_10), '')                         as other_identifier_state_10,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_ISSUER_10), '')                        as other_identifier_issuer_10,

        -- other identifiers 11-20
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_11), '')                               as other_identifier_11,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_TYPE_CODE_11), '')                     as other_identifier_type_11,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_STATE_11), '')                         as other_identifier_state_11,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_ISSUER_11), '')                        as other_identifier_issuer_11,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_12), '')                               as other_identifier_12,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_TYPE_CODE_12), '')                     as other_identifier_type_12,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_STATE_12), '')                         as other_identifier_state_12,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_ISSUER_12), '')                        as other_identifier_issuer_12,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_13), '')                               as other_identifier_13,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_TYPE_CODE_13), '')                     as other_identifier_type_13,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_STATE_13), '')                         as other_identifier_state_13,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_ISSUER_13), '')                        as other_identifier_issuer_13,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_14), '')                               as other_identifier_14,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_TYPE_CODE_14), '')                     as other_identifier_type_14,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_STATE_14), '')                         as other_identifier_state_14,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_ISSUER_14), '')                        as other_identifier_issuer_14,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_15), '')                               as other_identifier_15,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_TYPE_CODE_15), '')                     as other_identifier_type_15,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_STATE_15), '')                         as other_identifier_state_15,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_ISSUER_15), '')                        as other_identifier_issuer_15,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_16), '')                               as other_identifier_16,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_TYPE_CODE_16), '')                     as other_identifier_type_16,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_STATE_16), '')                         as other_identifier_state_16,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_ISSUER_16), '')                        as other_identifier_issuer_16,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_17), '')                               as other_identifier_17,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_TYPE_CODE_17), '')                     as other_identifier_type_17,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_STATE_17), '')                         as other_identifier_state_17,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_ISSUER_17), '')                        as other_identifier_issuer_17,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_18), '')                               as other_identifier_18,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_TYPE_CODE_18), '')                     as other_identifier_type_18,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_STATE_18), '')                         as other_identifier_state_18,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_ISSUER_18), '')                        as other_identifier_issuer_18,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_19), '')                               as other_identifier_19,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_TYPE_CODE_19), '')                     as other_identifier_type_19,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_STATE_19), '')                         as other_identifier_state_19,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_ISSUER_19), '')                        as other_identifier_issuer_19,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_20), '')                               as other_identifier_20,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_TYPE_CODE_20), '')                     as other_identifier_type_20,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_STATE_20), '')                         as other_identifier_state_20,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_ISSUER_20), '')                        as other_identifier_issuer_20,

        -- other identifiers 21-30
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_21), '')                               as other_identifier_21,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_TYPE_CODE_21), '')                     as other_identifier_type_21,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_STATE_21), '')                         as other_identifier_state_21,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_ISSUER_21), '')                        as other_identifier_issuer_21,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_22), '')                               as other_identifier_22,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_TYPE_CODE_22), '')                     as other_identifier_type_22,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_STATE_22), '')                         as other_identifier_state_22,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_ISSUER_22), '')                        as other_identifier_issuer_22,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_23), '')                               as other_identifier_23,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_TYPE_CODE_23), '')                     as other_identifier_type_23,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_STATE_23), '')                         as other_identifier_state_23,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_ISSUER_23), '')                        as other_identifier_issuer_23,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_24), '')                               as other_identifier_24,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_TYPE_CODE_24), '')                     as other_identifier_type_24,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_STATE_24), '')                         as other_identifier_state_24,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_ISSUER_24), '')                        as other_identifier_issuer_24,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_25), '')                               as other_identifier_25,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_TYPE_CODE_25), '')                     as other_identifier_type_25,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_STATE_25), '')                         as other_identifier_state_25,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_ISSUER_25), '')                        as other_identifier_issuer_25,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_26), '')                               as other_identifier_26,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_TYPE_CODE_26), '')                     as other_identifier_type_26,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_STATE_26), '')                         as other_identifier_state_26,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_ISSUER_26), '')                        as other_identifier_issuer_26,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_27), '')                               as other_identifier_27,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_TYPE_CODE_27), '')                     as other_identifier_type_27,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_STATE_27), '')                         as other_identifier_state_27,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_ISSUER_27), '')                        as other_identifier_issuer_27,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_28), '')                               as other_identifier_28,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_TYPE_CODE_28), '')                     as other_identifier_type_28,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_STATE_28), '')                         as other_identifier_state_28,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_ISSUER_28), '')                        as other_identifier_issuer_28,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_29), '')                               as other_identifier_29,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_TYPE_CODE_29), '')                     as other_identifier_type_29,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_STATE_29), '')                         as other_identifier_state_29,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_ISSUER_29), '')                        as other_identifier_issuer_29,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_30), '')                               as other_identifier_30,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_TYPE_CODE_30), '')                     as other_identifier_type_30,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_STATE_30), '')                         as other_identifier_state_30,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_ISSUER_30), '')                        as other_identifier_issuer_30,

        -- other identifiers 31-50
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_31), '')                               as other_identifier_31,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_TYPE_CODE_31), '')                     as other_identifier_type_31,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_STATE_31), '')                         as other_identifier_state_31,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_ISSUER_31), '')                        as other_identifier_issuer_31,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_32), '')                               as other_identifier_32,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_TYPE_CODE_32), '')                     as other_identifier_type_32,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_STATE_32), '')                         as other_identifier_state_32,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_ISSUER_32), '')                        as other_identifier_issuer_32,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_33), '')                               as other_identifier_33,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_TYPE_CODE_33), '')                     as other_identifier_type_33,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_STATE_33), '')                         as other_identifier_state_33,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_ISSUER_33), '')                        as other_identifier_issuer_33,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_34), '')                               as other_identifier_34,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_TYPE_CODE_34), '')                     as other_identifier_type_34,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_STATE_34), '')                         as other_identifier_state_34,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_ISSUER_34), '')                        as other_identifier_issuer_34,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_35), '')                               as other_identifier_35,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_TYPE_CODE_35), '')                     as other_identifier_type_35,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_STATE_35), '')                         as other_identifier_state_35,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_ISSUER_35), '')                        as other_identifier_issuer_35,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_36), '')                               as other_identifier_36,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_TYPE_CODE_36), '')                     as other_identifier_type_36,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_STATE_36), '')                         as other_identifier_state_36,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_ISSUER_36), '')                        as other_identifier_issuer_36,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_37), '')                               as other_identifier_37,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_TYPE_CODE_37), '')                     as other_identifier_type_37,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_STATE_37), '')                         as other_identifier_state_37,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_ISSUER_37), '')                        as other_identifier_issuer_37,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_38), '')                               as other_identifier_38,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_TYPE_CODE_38), '')                     as other_identifier_type_38,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_STATE_38), '')                         as other_identifier_state_38,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_ISSUER_38), '')                        as other_identifier_issuer_38,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_39), '')                               as other_identifier_39,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_TYPE_CODE_39), '')                     as other_identifier_type_39,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_STATE_39), '')                         as other_identifier_state_39,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_ISSUER_39), '')                        as other_identifier_issuer_39,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_40), '')                               as other_identifier_40,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_TYPE_CODE_40), '')                     as other_identifier_type_40,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_STATE_40), '')                         as other_identifier_state_40,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_ISSUER_40), '')                        as other_identifier_issuer_40,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_41), '')                               as other_identifier_41,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_TYPE_CODE_41), '')                     as other_identifier_type_41,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_STATE_41), '')                         as other_identifier_state_41,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_ISSUER_41), '')                        as other_identifier_issuer_41,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_42), '')                               as other_identifier_42,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_TYPE_CODE_42), '')                     as other_identifier_type_42,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_STATE_42), '')                         as other_identifier_state_42,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_ISSUER_42), '')                        as other_identifier_issuer_42,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_43), '')                               as other_identifier_43,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_TYPE_CODE_43), '')                     as other_identifier_type_43,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_STATE_43), '')                         as other_identifier_state_43,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_ISSUER_43), '')                        as other_identifier_issuer_43,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_44), '')                               as other_identifier_44,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_TYPE_CODE_44), '')                     as other_identifier_type_44,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_STATE_44), '')                         as other_identifier_state_44,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_ISSUER_44), '')                        as other_identifier_issuer_44,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_45), '')                               as other_identifier_45,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_TYPE_CODE_45), '')                     as other_identifier_type_45,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_STATE_45), '')                         as other_identifier_state_45,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_ISSUER_45), '')                        as other_identifier_issuer_45,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_46), '')                               as other_identifier_46,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_TYPE_CODE_46), '')                     as other_identifier_type_46,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_STATE_46), '')                         as other_identifier_state_46,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_ISSUER_46), '')                        as other_identifier_issuer_46,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_47), '')                               as other_identifier_47,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_TYPE_CODE_47), '')                     as other_identifier_type_47,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_STATE_47), '')                         as other_identifier_state_47,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_ISSUER_47), '')                        as other_identifier_issuer_47,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_48), '')                               as other_identifier_48,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_TYPE_CODE_48), '')                     as other_identifier_type_48,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_STATE_48), '')                         as other_identifier_state_48,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_ISSUER_48), '')                        as other_identifier_issuer_48,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_49), '')                               as other_identifier_49,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_TYPE_CODE_49), '')                     as other_identifier_type_49,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_STATE_49), '')                         as other_identifier_state_49,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_ISSUER_49), '')                        as other_identifier_issuer_49,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_50), '')                               as other_identifier_50,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_TYPE_CODE_50), '')                     as other_identifier_type_50,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_STATE_50), '')                         as other_identifier_state_50,
        nullif(trim(OTHER_PROVIDER_IDENTIFIER_ISSUER_50), '')                        as other_identifier_issuer_50,

        -- metadata
        _ingested_at,
        _source_run_id

    from source
    qualify row_number() over (partition by NPI order by _ingested_at desc) = 1

)

select * from renamed
