{{ config(materialized='table', schema='OPEN_DATA') }}

-- Source: dados.gov.br (10 rows)
-- Generated by gen_mart_models.py

with source as (
    select * from {{ source('ripple_raw', 'INTL_BR_DADOS_GOV') }}
)

select
    DATASET_ID as dataset_id,
    TITLE as title,
    C_ORGANIZATION as c_organization,
    THEME as theme,
    try_to_number(NUM_RESOURCES) as num_resources,
    try_to_number(DOWNLOAD_COUNT) as download_count,
    try_to_date(LAST_UPDATED) as last_updated,
    LICENSE as license,
    DESCRIPTION as description,
    RESOURCE_URLS as resource_urls,
    TAGS as tags,
    GEOGRAPHIC_COVERAGE as geographic_coverage,
    TEMPORAL_COVERAGE as temporal_coverage
from source
