{{ config(tags=['minimal_staging']) }}

-- GRAIN: NOT YET DETERMINED (profiler returned AMBIGUOUS -- needs manual review)
-- This is a passthrough staging view: snake_case rename only, no dedup.
-- Once grain is resolved, replace with a full staging model via generate_staging_models.py.
-- Generated by scripts/generate_minimal_staging.py

with source as (

    select * from {{ source('ripple_raw', 'XC_OWID_TEMP_ANOMALY') }}

),

renamed as (

    select
        ENTITY as entity,
        CODE as code,
        YEAR as year,
        AVERAGE as average,
        LOWER_BOUND as lower_bound,
        UPPER_BOUND as upper_bound,
        INGESTED_AT as _loaded_at,
        'https://ourworldindata.org/grapher/temperature-anomaly.csv?csvType=full' as _source_url

    from source

)

select * from renamed
