-- S02 column names and types for the five tables plus the join partners (S01 retry; S01 failed on an ESCAPE parse error)
SELECT TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME, DATA_TYPE, ORDINAL_POSITION
FROM LIBRARY_MARTS.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME IN ('ENVIRONMENT__XC_EPA_CORPORATE_CROSSWALK','ENVIRONMENT__FED_EPA_AQS_SITES','ENVIRONMENT__FED_EPA_FRS_FRS_NAICS_CODES',
 'ENVIRONMENT__FED_FRACFOCUS_WATER_SOURCE','ENVIRONMENT__FED_EPA_FRS_FRS_SIC_CODES','ENVIRONMENT__FED_FRACFOCUS_DISCLOSURE_LIST','DIM_COUNTY')
  AND LEFT(COLUMN_NAME, 1) <> '_'
ORDER BY TABLE_NAME, ORDINAL_POSITION
