-- S03 crosswalk profile: match method x confidence x review flag, fill of every ID column, first-word sanity
SELECT MATCH_METHOD, MATCH_CONFIDENCE, REVIEW_FLAG, COUNT(*) n, COUNT(DISTINCT EPA_REGISTRY_ID) ids,
       COUNT_IF(NULLIF(TRIM(MATCHED_LEI),'') IS NOT NULL) lei_filled, COUNT(DISTINCT MATCHED_LEI) d_lei,
       COUNT_IF(NULLIF(TRIM(MATCHED_LEGAL_NAME),'') IS NOT NULL) name_filled,
       COUNT_IF(NULLIF(TRIM(ULTIMATE_PARENT_LEI),'') IS NOT NULL) ult_filled, COUNT(DISTINCT ULTIMATE_PARENT_LEI) d_ult,
       COUNT_IF(NULLIF(TRIM(PARENT_CIK),'') IS NOT NULL) cik_filled, COUNT(DISTINCT PARENT_CIK) d_cik,
       COUNT_IF(NULLIF(TRIM(PARENT_UEI),'') IS NOT NULL) uei_filled, COUNT(DISTINCT PARENT_UEI) d_uei,
       COUNT_IF(MATCHED_LEGAL_NAME = PARENT_LEGAL_NAME) same_parent_name,
       COUNT_IF(CONTAINS(UPPER(FACILITY_NAME), UPPER(SPLIT_PART(MATCHED_LEGAL_NAME,' ',1)))) first_word_in_fac,
       COUNT_IF(NULLIF(TRIM(FACILITY_NAME),'') IS NULL) blank_fac
FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__XC_EPA_CORPORATE_CROSSWALK
GROUP BY 1,2,3 ORDER BY n DESC;

-- S04 crosswalk: the 50 matched companies holding the most facilities, with sample facility names
SELECT MATCHED_LEGAL_NAME, PARENT_LEGAL_NAME, MAX(PARENT_CIK) cik, MAX(PARENT_UEI) uei, COUNT(*) facilities,
       LISTAGG(DISTINCT MATCH_METHOD, ',') methods,
       COUNT_IF(CONTAINS(UPPER(FACILITY_NAME), UPPER(SPLIT_PART(MATCHED_LEGAL_NAME,' ',1)))) first_word_hit,
       ARRAY_TO_STRING(ARRAY_SLICE(ARRAY_AGG(DISTINCT FACILITY_NAME), 0, 6), ' / ') sample_fac
FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__XC_EPA_CORPORATE_CROSSWALK
WHERE NULLIF(TRIM(MATCHED_LEGAL_NAME),'') IS NOT NULL
GROUP BY 1,2 ORDER BY facilities DESC LIMIT 50;

-- S05 crosswalk: 60 random matched rows to eyeball the name match
SELECT EPA_REGISTRY_ID, FACILITY_NAME, MATCHED_LEGAL_NAME, MATCH_METHOD, MATCH_CONFIDENCE, PARENT_LEGAL_NAME, PARENT_CIK, PARENT_UEI
FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__XC_EPA_CORPORATE_CROSSWALK SAMPLE (0.02)
WHERE NULLIF(TRIM(MATCHED_LEGAL_NAME),'') IS NOT NULL
LIMIT 60;

-- S06 FRS NAICS and SIC code tables: per program, rows, facilities, exact duplicates, code shape, blanks
SELECT 'NAICS' tbl, PGM_SYS_ACNRM, COUNT(*) n, COUNT(DISTINCT REGISTRY_ID) ids, COUNT(DISTINCT REGISTRY_ID, PGM_SYS_ID, NAICS_CODE) uniq_rows,
       COUNT_IF(LEN(TRIM(NAICS_CODE)) = 6) len6, COUNT_IF(LEN(TRIM(NAICS_CODE)) BETWEEN 1 AND 5) short, COUNT_IF(NULLIF(TRIM(NAICS_CODE),'') IS NULL) blank,
       COUNT_IF(TRY_TO_NUMBER(NAICS_CODE) = 0) zeros, MODE(NAICS_CODE) top_code, COUNT_IF(LEFT(REGISTRY_ID,3) <> '110') bad_id
FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_FRS_FRS_NAICS_CODES GROUP BY 1,2
UNION ALL
SELECT 'SIC', PGM_SYS_ACNRM, COUNT(*), COUNT(DISTINCT REGISTRY_ID), COUNT(DISTINCT REGISTRY_ID, PGM_SYS_ID, SIC_CODE),
       COUNT_IF(LEN(TRIM(SIC_CODE)) = 4), COUNT_IF(LEN(TRIM(SIC_CODE)) BETWEEN 1 AND 3), COUNT_IF(NULLIF(TRIM(SIC_CODE),'') IS NULL),
       COUNT_IF(TRY_TO_NUMBER(SIC_CODE) = 0), MODE(SIC_CODE), COUNT_IF(LEFT(REGISTRY_ID,3) <> '110')
FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_FRS_FRS_SIC_CODES GROUP BY 1,2
ORDER BY 1, 3 DESC;

-- S07 AQS: sites opened and closed per year
SELECT yr, SUM(opened) opened, SUM(closed) closed FROM (
  SELECT YEAR(SITE_ESTABLISHED_DATE) yr, 1 opened, 0 closed FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_AQS_SITES
  UNION ALL
  SELECT YEAR(SITE_CLOSED_DATE), 0, 1 FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_AQS_SITES WHERE SITE_CLOSED_DATE IS NOT NULL
) GROUP BY yr ORDER BY yr;

-- S08 AQS: open vs closed by setting, date sanity, coordinate sanity, duplicate IDs
SELECT LOCATION_SETTING, COUNT(*) n, COUNT(DISTINCT AQS_SITE_ID) ids, COUNT_IF(SITE_CLOSED_DATE IS NULL) open_now,
       COUNT_IF(SITE_ESTABLISHED_DATE > EXTRACTION_DATE) opened_after_extract, COUNT_IF(SITE_CLOSED_DATE > EXTRACTION_DATE) closed_after_extract,
       COUNT_IF(SITE_CLOSED_DATE < SITE_ESTABLISHED_DATE) closed_before_open, COUNT_IF(SITE_ESTABLISHED_DATE IS NULL) no_open_date,
       COUNT_IF(MONTH(SITE_ESTABLISHED_DATE) = 1 AND DAY(SITE_ESTABLISHED_DATE) = 1) jan1_open,
       COUNT_IF(LATITUDE IS NULL OR LATITUDE = 0) no_lat, COUNT(DISTINCT STATE_CODE) states, COUNT(DISTINCT OWNING_AGENCY) agencies,
       MIN(EXTRACTION_DATE) ex0, MAX(EXTRACTION_DATE) ex1
FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_AQS_SITES
GROUP BY ROLLUP(1) ORDER BY n DESC;

-- S09 FracFocus water: every DESCRIPTION value, percent shape, landing rate in the disclosure list
WITH d AS (SELECT DISTINCT DISCLOSURE_ID FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_FRACFOCUS_DISCLOSURE_LIST)
SELECT w.DESCRIPTION, COUNT(*) n, COUNT(DISTINCT w.DISCLOSURE_ID) discl, COUNT(d.DISCLOSURE_ID) landed,
       SUM(PERCENT) pct_sum, MEDIAN(PERCENT) pct_med, COUNT_IF(PERCENT = 0) pct0, COUNT_IF(PERCENT IS NULL) pct_null,
       COUNT_IF(PERCENT > 100) pct_over100, COUNT(DISTINCT OPERATOR_NAME) ops, COUNT(DISTINCT STATE_NAME) states
FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_FRACFOCUS_WATER_SOURCE w LEFT JOIN d ON d.DISCLOSURE_ID = w.DISCLOSURE_ID
GROUP BY ROLLUP(1) ORDER BY n DESC;

-- S10 FracFocus: disclosures by form version, how many carry water rows, per-disclosure percent sums and duplicate rows
WITH ws AS (SELECT DISCLOSURE_ID, COUNT(*) n, SUM(PERCENT) p, COUNT(DISTINCT DESCRIPTION, PERCENT) u, COUNT(DISTINCT WATER_SOURCE_ID) wid
            FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_FRACFOCUS_WATER_SOURCE GROUP BY 1),
     d AS (SELECT DISCLOSURE_ID, ANY_VALUE(FF_VERSION) ffv, COUNT(*) dn, MAX(JOB_START_DATE) js, MAX(TOTAL_BASE_WATER_VOLUME) vol
           FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_FRACFOCUS_DISCLOSURE_LIST GROUP BY 1)
SELECT COALESCE(d.ffv, 'not in list') ffv, COUNT(*) discl, COUNT_IF(d.dn > 1) dup_in_list, COUNT(ws.DISCLOSURE_ID) with_water,
       COUNT_IF(ABS(ws.p - 100) < 0.5) p100, COUNT_IF(ws.p > 100.5) p_over, COUNT_IF(ws.p < 99.5) p_under,
       COUNT_IF(ws.n > ws.u) dup_rows, COUNT_IF(ws.n > ws.wid) dup_wsid, COUNT(d.js) has_job_date,
       COUNT_IF(d.vol > 0) vol_pos, MEDIAN(d.vol) vol_med
FROM d FULL OUTER JOIN ws ON ws.DISCLOSURE_ID = d.DISCLOSURE_ID
GROUP BY 1 ORDER BY 1
