-- S17 raw landing: do the FracFocus landing tables still carry job dates the mart dropped?
SELECT TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME, DATA_TYPE, ROW_COUNT
FROM LIBRARY_RAW.INFORMATION_SCHEMA.COLUMNS c JOIN LIBRARY_RAW.INFORMATION_SCHEMA.TABLES t USING (TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME)
WHERE TABLE_NAME ILIKE '%FRACFOCUS%' AND (COLUMN_NAME ILIKE '%DATE%' OR COLUMN_NAME ILIKE '%DISCLOSUREID%' OR COLUMN_NAME ILIKE '%DISCLOSURE_ID%')
ORDER BY 2, 3
