{{ config(tags=['spine_generated']) }}

-- GRAIN: one row per place (ZIP+SR_CREATE_DATE+DUE_DATE+DATE_CLOSED+TAX_ID unique)
-- SPINE_ENTITY: place  (natural_key: ZIPCODE, SR_CREATE_DATE, DUE_DATE, DATE_CLOSED, TAX_ID)
-- Generated by scripts/generate_staging_models.py from SOURCE_REGISTRY -- deterministic,
-- no LLM. Casts kept as landed (TEXT) -- add explicit type casts by hand once each
-- column's real type is confirmed; this generator has no semantic type knowledge.
-- spine_entity 'place' has no connect/ resolver yet (see connect/spine_entity.py) -- no SPINE_ENTITY_ID emitted.
-- landing table's ingestion timestamp is named INGESTED_AT (no leading underscore) rather than the usual _INGESTED_AT -- confirmed via INFORMATION_SCHEMA, not assumed.
-- DEDUPE: registry natural_key (ZIPCODE, SR_CREATE_DATE, DUE_DATE, DATE_CLOSED, TAX_ID) is NOT unique within a load as landed at generation time -- it would collapse 4,526 of 196,552 rows. Deduping on the WHOLE ROW instead (exact copies only). A record that changes between loads shows once per version. Find the real key, fix SOURCE_REGISTRY, regenerate.

with source as (

    select * from {{ source('ripple_raw', 'PORTAL_CKA_HOUSTON_OPEN_DAT_A4490182BA') }}

),

renamed as (

    select
        "ANIMAL_PUBLIC_BARC_DATA_KEY" as animal_public_barc_data_key,
        "UNIQUE_ACTIVITY_NO" as unique_activity_no,
        "MIN_ACTIVITY_SEQ" as min_activity_seq,
        "MAX_ACTIVITY_SEQ" as max_activity_seq,
        "COUNT_SEQ" as count_seq,
        "CASE_NUMBER" as case_number,
        "SR_LOCATION" as sr_location,
        "COUNTY" as county,
        "DISTRICT" as district,
        "NEIGHBORHOOD" as neighborhood,
        "TAX_ID" as tax_id,
        "TRASH_QUAD" as trash_quad,
        "RECYCLE_QUAD" as recycle_quad,
        "TRASH_DAY" as trash_day,
        "HEAVY_TRASH_DAY" as heavy_trash_day,
        "RECYCLE_DAY" as recycle_day,
        "KEY_MAP" as key_map,
        "MANAGEMENT_DISTRICT" as management_district,
        "DEPARTMENT" as department,
        "DIVISION" as division,
        "SR_TYPE" as sr_type,
        "QUEUE" as queue,
        "SLA" as sla,
        "STATUS" as status,
        "SR_CREATE_DATE" as sr_create_date,
        "SR_CREATE_TIME" as sr_create_time,
        "DUE_DATE" as due_date,
        "DUE_TIME" as due_time,
        "DATE_CLOSED" as date_closed,
        "TIME_CLOSED" as time_closed,
        "OVERDUE" as overdue,
        "TITLE" as title,
        "X_COORD" as x_coord,
        "Y_COORD" as y_coord,
        "LATITUDE" as latitude,
        "LONGITUDE" as longitude,
        "CHANNEL_TYPE" as channel_type,
        "STREET_NUM" as street_num,
        "STREET_NAME" as street_name,
        "CITY" as city,
        "STATE" as state,
        "ZIPCODE" as zipcode,
        "ADDRESS" as address,
        "IS_GEOCODED" as is_geocoded,
        "EXPORTDATE" as exportdate,
        INGESTED_AT as _loaded_at,
        'https://data.houstontx.gov/dataset/barc-animal-service-requests' as _source_url

    from source

)

select * from renamed
qualify row_number() over (partition by animal_public_barc_data_key, unique_activity_no, min_activity_seq, max_activity_seq, count_seq, case_number, sr_location, county, district, neighborhood, tax_id, trash_quad, recycle_quad, trash_day, heavy_trash_day, recycle_day, key_map, management_district, department, division, sr_type, queue, sla, status, sr_create_date, sr_create_time, due_date, due_time, date_closed, time_closed, overdue, title, x_coord, y_coord, latitude, longitude, channel_type, street_num, street_name, city, state, zipcode, address, is_geocoded, exportdate order by _loaded_at desc) = 1
