select RNDRNG_NPI, RNDRNG_PRVDR_LAST_ORG_NAME, RNDRNG_PRVDR_FIRST_NAME, RNDRNG_PRVDR_CRDNTLS, RNDRNG_PRVDR_TYPE, RNDRNG_PRVDR_ST1, RNDRNG_PRVDR_CITY, RNDRNG_PRVDR_ZIP5, HCPCS_CD, left(HCPCS_DESC,50) d, PLACE_OF_SRVC, TOT_BENES, TOT_SRVCS, AVG_MDCR_ALOWD_AMT, AVG_MDCR_PYMT_AMT,
 round(try_to_double(AVG_MDCR_ALOWD_AMT::varchar)*try_to_double(TOT_SRVCS::varchar)) allowed, PROVIDER_TOT_MDCR_PYMT_AMT, SERVICE_ROWS_COVER_PCT
from LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_MEDICARE_PHYSICIAN_OTHER_PRACTITIONERS_BY_PROVIDER_AND_SERVI
where RNDRNG_PRVDR_LAST_ORG_NAME ilike 'KAPADIA' and RNDRNG_PRVDR_STATE_ABRVTN='CA'
order by allowed desc nulls last
