with op as (
 select PROGRAM_YEAR y, APPLICABLE_MANUFACTURER_OR_APPLICABLE_GPO_MAKING_PAYMENT_NAME m, NPI, try_to_double(TOTAL_AMOUNT_OF_PAYMENT_USDOLLARS::varchar) amt from LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_OPEN_PAYMENTS
 union all select PROGRAM_YEAR, APPLICABLE_MANUFACTURER_OR_APPLICABLE_GPO_MAKING_PAYMENT_NAME, NPI, try_to_double(TOTAL_AMOUNT_OF_PAYMENT_USDOLLARS::varchar) from LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_OPEN_PAYMENTS_2023
 union all select PROGRAM_YEAR, APPLICABLE_MANUFACTURER_OR_APPLICABLE_GPO_MAKING_PAYMENT_NAME, NPI, try_to_double(TOTAL_AMOUNT_OF_PAYMENT_USDOLLARS::varchar) from LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_OPEN_PAYMENTS_2022)
select m, count(*) n, round(sum(amt)) amt, count(distinct NPI) npis, listagg(distinct y::varchar, ',') within group (order by y::varchar) yrs
from op
where regexp_like(upper(m), '.*(ENCOLL|BIOLAB|LEGACY MEDICAL|TIDES|STIMLABS|STIM LABS|ESANO|LUCINA|AMNIO|BIOSTEM|STABILITY BIO|TIGER|APPLIED BIOLOGICS|ROYAL BIOLOGICS|EXTREMITY CARE|VIVEX|SANARA|SKYE|SURGENEX|MERAKRIS|SAMARITAN|NEXTGEN|ARCHITECT|OMNIGEN|BIOWOUND|NOVA|HEALTHTECH|PRECISION|TISSUE|WOUND|REGENERAT|GRAFT|MEMBRANE|HUMAN REGEN|BIOTISSUE|SEQUENCE|AZIYO|ELUTIA|PROTEAR|CELLRIGHT|NUTECH|BIO LAB).*')
group by m order by amt desc limit 80
