select 'cl' src, COURT_ID, DATE_FILED::varchar df, DATE_TERMINATED::varchar dt, DOCKET_NUMBER, left(CASE_NAME,120) cn, NATURE_OF_SUIT, CAUSE
from LIBRARY_MARTS.JUSTICE.JUSTICE__FED_COURTLISTENER_DOCKETS
where DATE_FILED >= '2018-01-01'
  and regexp_like(upper(CASE_NAME), '.*\b(KAPADIA|AARON JENG|JENG|REYES CHOUZA|YUKEE|CASTILLO MADRIGAL|TULSYAN|BAHARLOO|KOHANZADEH|HAJHOSSEINI|LIMPEROS|YALAMURI|IRA DENNY|GINA PALACIOS|JORGE KINDS|ALLISON CHARLES|GUTSTEIN|PIASECKI|RAHUL PANDEY|MARIZEL|PHILLIP MYERS|ANDREA VASQUEZ|KELLY POWELL|JAMI GORTON|BRENT BYERS|CHIBUIKEM|OKORO|THOMAS DENMARK|DENMARK, THOMAS|KAPADIA, RAVI)\b.*')
order by df desc limit 200
