select DISTRICT, OFFICE, DOCKET, DEFENDANT_NUMBER, DEFENDANT_NAME, FILE_DATE::varchar fd, FILING_TITLE_1, FILING_OFFENSE_CODE_1, D2_FILING_OFFENSE_CODE_1, FILING_TITLE_2, FILING_TITLE_3, CT_FIL, STATUS_CODE, TERM_DATE::varchar td, DISPOSITION_1, PRISON_TOTAL, FINE_TOTAL, TAPE_YEAR,
 (select max(FILE_DATE)::varchar from LIBRARY_MARTS.JUSTICE.JUSTICE__FED_FJC_IDB_CRIMINAL) max_file_date
from LIBRARY_MARTS.JUSTICE.JUSTICE__FED_FJC_IDB_CRIMINAL
where FILE_DATE >= '2020-01-01' and (
  upper(DEFENDANT_NAME) like '%DENNY%' or upper(DEFENDANT_NAME) like '%YUKEE%' or upper(DEFENDANT_NAME) like '%KAPADIA%'
  or (upper(DEFENDANT_NAME) like '%PALACIOS%' and upper(DEFENDANT_NAME) like '%GINA%') or upper(DEFENDANT_NAME) like '%REYES CHOUZA%' or upper(DEFENDANT_NAME) like '%CASTILLO MADRIGAL%'
  or (upper(DEFENDANT_NAME) like '%KINDS%' and upper(DEFENDANT_NAME) like '%JORGE%') or (upper(DEFENDANT_NAME) like '%CHARLES%' and upper(DEFENDANT_NAME) like '%ALLISON%'))
order by fd desc
