select DISTRICT, OFFICE, DOCKET, DEFENDANT_NUMBER, CT_DEFENDANTS, FILE_DATE::varchar fd, FILING_TITLE_1, FILING_TITLE_2, FILING_TITLE_3, FILING_TITLE_4, FILING_TITLE_5, CT_FIL, STATUS_CODE, FUGITIVE_STATUS, TERM_DATE::varchar td, DISPOSITION_1, PRISON_TOTAL, COUNTY
from LIBRARY_MARTS.JUSTICE.JUSTICE__FED_FJC_IDB_CRIMINAL
where (DISTRICT='70' and OFFICE='2' and DOCKET in ('2500944','2500947'))
   or (OFFICE='4' and DOCKET='2600370')
order by DISTRICT, DOCKET, DEFENDANT_NUMBER
