select 'partb' src, RNDRNG_NPI, RNDRNG_PRVDR_LAST_ORG_NAME||' '||coalesce(RNDRNG_PRVDR_FIRST_NAME,'') nm, RNDRNG_PRVDR_TYPE, RNDRNG_PRVDR_CITY, TOT_BENES::varchar b, TOT_MDCR_ALOWD_AMT::varchar a, DRUG_MDCR_ALOWD_AMT::varchar d
from LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_MEDICARE_PHYSICIAN_OTHER_PRACTITIONERS_BY_PROVIDER where RNDRNG_NPI in ('1508551276','1235016452','1902217854')
union all
select 'nppes', NPI, PROVIDER_LAST_NAME_LEGAL_NAME||' '||PROVIDER_FIRST_NAME, HEALTHCARE_PROVIDER_TAXONOMY_CODE_1, PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_CITY_NAME, PROVIDER_ENUMERATION_DATE::varchar, null, null
from LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_NPPES where NPI='1902217854'
