with op as (
 select PROGRAM_YEAR y, NPI, COVERED_RECIPIENT_FIRST_NAME fn, COVERED_RECIPIENT_LAST_NAME ln, RECIPIENT_STATE st, RECIPIENT_CITY c, APPLICABLE_MANUFACTURER_OR_APPLICABLE_GPO_MAKING_PAYMENT_NAME m, try_to_double(TOTAL_AMOUNT_OF_PAYMENT_USDOLLARS::varchar) amt from LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_OPEN_PAYMENTS where upper(COVERED_RECIPIENT_LAST_NAME) in ('CASTILLO MADRIGAL','VASQUEZ','GORTON','DENNY','PALACIOS','KINDS','CHARLES','REYES CHOUZA','KAPADIA')
 union all select PROGRAM_YEAR, NPI, COVERED_RECIPIENT_FIRST_NAME, COVERED_RECIPIENT_LAST_NAME, RECIPIENT_STATE, RECIPIENT_CITY, APPLICABLE_MANUFACTURER_OR_APPLICABLE_GPO_MAKING_PAYMENT_NAME, try_to_double(TOTAL_AMOUNT_OF_PAYMENT_USDOLLARS::varchar) from LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_OPEN_PAYMENTS_2023 where upper(COVERED_RECIPIENT_LAST_NAME) in ('CASTILLO MADRIGAL','VASQUEZ','GORTON','DENNY','PALACIOS','KINDS','CHARLES','REYES CHOUZA','KAPADIA'))
select y::varchar y, NPI, fn, ln, st, c, m, count(*) n, round(sum(amt)) amt from op
where (upper(fn) in ('MICHEL','ANDREA','JAMI','IRA','GINA','JORGE','ALLISON','CARLOS','RAVI')) and st in ('FL','CA','CO','AZ','WV')
group by all order by ln, fn, y
