version: 2

sources:
  - name: ripple_raw
    database: LIBRARY_RAW
    schema: LANDING
    tables:
      - name: FED_EIA860_PLANT_Y2020

models:
  - name: stg_fed_eia860_plant_y2020__all
    description: "EIA-860 Plant 2020, all sheets"
    columns:
      - name: PLANT_CODE
        tests:
          - not_null
          - unique
