{{ config(tags=['spine_generated']) }}

-- GRAIN: one row per facility (TRI_FACILITY_ID unique)
-- SPINE_ENTITY: facility  (natural_key: TRI_FACILITY_ID)
-- Generated by scripts/generate_staging_models.py from SOURCE_REGISTRY -- deterministic,
-- no LLM. Casts kept as landed (TEXT) -- add explicit type casts by hand once each
-- column's real type is confirmed; this generator has no semantic type knowledge.
-- spine_entity 'facility' has no connect/ resolver yet (see connect/spine_entity.py) -- no SPINE_ENTITY_ID emitted.
-- landing table's ingestion timestamp is named INGESTED_AT (no leading underscore) rather than the usual _INGESTED_AT -- confirmed via INFORMATION_SCHEMA, not assumed.

with source as (

    select * from {{ source('ripple_raw', 'PORTAL_ARC_LA_COUNTY_OPEN_D_D75E8EA051') }}

),

renamed as (

    select
        "TRI_FACILITY_NAME" as tri_facility_name,
        "OBJECTID" as objectid,
        "TRI_FACILITY_ID" as tri_facility_id,
        "PARENT_COMPANY" as parent_company,
        "STREET_ADDRESS" as street_address,
        "CITY" as city,
        "STATE" as state,
        "ZIP_CODE" as zip_code,
        "INDUSTRY_SECTOR" as industry_sector,
        "NORTH_AMERICA_INDUSTRY_CLASSIFI" as north_america_industry_classifi,
        "NAICS_CODE" as naics_code,
        "SUBMISSION_YEAR" as submission_year,
        "TOTAL_FACILITY_RSEI_SCORE" as total_facility_rsei_score,
        "TOTAL_FACILITY_RSEI_SCORE_CANCE" as total_facility_rsei_score_cance,
        "TOTAL_FACILITY_RSEI_SCORE_NONCA" as total_facility_rsei_score_nonca,
        "LIST_OF_FACILITY_CHEMICALS" as list_of_facility_chemicals,
        "NAME_CHEMICAL1" as name_chemical1,
        "RSEI_CHEM1" as rsei_chem1,
        "RSEI_CA_CHEM1" as rsei_ca_chem1,
        "RSEI_NCA_CHEM1" as rsei_nca_chem1,
        "RSEI_CHEM_MODLBS1" as rsei_chem_modlbs1,
        "NAME_CHEMICAL2" as name_chemical2,
        "RSEI_CHEM2" as rsei_chem2,
        "RSEI_CA_CHEM2" as rsei_ca_chem2,
        "RSEI_NCA_CHEM2" as rsei_nca_chem2,
        "RSEI_CHEM_MODLBS2" as rsei_chem_modlbs2,
        "NAME_CHEMICAL3" as name_chemical3,
        "RSEI_CHEM3" as rsei_chem3,
        "RSEI_CA_CHEM3" as rsei_ca_chem3,
        "RSEI_NCA_CHEM3" as rsei_nca_chem3,
        "RSEI_CHEM_MODLBS3" as rsei_chem_modlbs3,
        "LATITUDE" as latitude,
        "LONGITUDE" as longitude,
        "CT" as ct,
        "TOTAL_RSEI_URL" as total_rsei_url,
        "TOP_CHEM_RSEI_URL" as top_chem_rsei_url,
        "GEOMETRY" as geometry,
        INGESTED_AT as _loaded_at,
        'https://data.lacounty.gov/datasets/5156c7e65ea848aab24dfa509ba49441_0' as _source_url

    from source

)

select * from renamed
qualify row_number() over (partition by tri_facility_id order by _loaded_at desc) = 1
