{{ config(tags=['spine_generated']) }}

-- GRAIN: one row per facility (TRI_FACILITY_ID unique)
-- SPINE_ENTITY: facility  (natural_key: TRI_FACILITY_ID)
-- Generated by scripts/generate_staging_models.py from SOURCE_REGISTRY -- deterministic,
-- no LLM.
-- CASTS: 18 of 37 columns, from landing_column_profile_2026-09-19.tsv. A column is cast only
-- when every filled value in the sample parsed. try_ casts: a value that does not
-- parse reads NULL. The natural key and join-key columns stay TEXT.
--   objectid: ID: whole numbers, over 90% distinct -- stays TEXT, '.0' tail removed
--   submission_year: integer
--   total_facility_rsei_score: integer
--   total_facility_rsei_score_cance: integer
--   total_facility_rsei_score_nonca: integer
--   rsei_chem1: integer
--   rsei_ca_chem1: integer
--   rsei_nca_chem1: integer
--   rsei_chem_modlbs1: integer
--   rsei_chem2: integer
--   rsei_ca_chem2: integer
--   rsei_nca_chem2: integer
--   rsei_chem_modlbs2: integer
--   rsei_chem3: integer
--   rsei_ca_chem3: integer
--   rsei_nca_chem3: integer
--   rsei_chem_modlbs3: integer
--   ct: integer
-- spine_entity 'facility' has no connect/ resolver yet (see connect/spine_entity.py) -- no SPINE_ENTITY_ID emitted.
-- landing table's ingestion timestamp is named INGESTED_AT (no leading underscore) rather than the usual _INGESTED_AT -- confirmed via INFORMATION_SCHEMA, not assumed.

with source as (

    select * from {{ source('ripple_raw', 'PORTAL_ARC_LA_COUNTY_OPEN_D_D75E8EA051') }}
    qualify row_number() over (partition by "TRI_FACILITY_ID" order by INGESTED_AT desc) = 1

),

renamed as (

    select
        {{ null_junk('"TRI_FACILITY_NAME"') }} as tri_facility_name,
        {{ stg_id_text('"OBJECTID"') }} as objectid,
        {{ null_junk('"TRI_FACILITY_ID"') }} as tri_facility_id,
        {{ null_junk('"PARENT_COMPANY"') }} as parent_company,
        {{ null_junk('"STREET_ADDRESS"') }} as street_address,
        {{ null_junk('"CITY"') }} as city,
        {{ null_junk('"STATE"') }} as state,
        {{ null_junk('"ZIP_CODE"') }} as zip_code,
        {{ null_junk('"INDUSTRY_SECTOR"') }} as industry_sector,
        {{ null_junk('"NORTH_AMERICA_INDUSTRY_CLASSIFI"') }} as north_america_industry_classifi,
        {{ null_junk('"NAICS_CODE"') }} as naics_code,
        {{ stg_int('"SUBMISSION_YEAR"') }} as submission_year,
        {{ stg_int('"TOTAL_FACILITY_RSEI_SCORE"') }} as total_facility_rsei_score,
        {{ stg_int('"TOTAL_FACILITY_RSEI_SCORE_CANCE"') }} as total_facility_rsei_score_cance,
        {{ stg_int('"TOTAL_FACILITY_RSEI_SCORE_NONCA"') }} as total_facility_rsei_score_nonca,
        {{ null_junk('"LIST_OF_FACILITY_CHEMICALS"') }} as list_of_facility_chemicals,
        {{ null_junk('"NAME_CHEMICAL1"') }} as name_chemical1,
        {{ stg_int('"RSEI_CHEM1"') }} as rsei_chem1,
        {{ stg_int('"RSEI_CA_CHEM1"') }} as rsei_ca_chem1,
        {{ stg_int('"RSEI_NCA_CHEM1"') }} as rsei_nca_chem1,
        {{ stg_int('"RSEI_CHEM_MODLBS1"') }} as rsei_chem_modlbs1,
        {{ null_junk('"NAME_CHEMICAL2"') }} as name_chemical2,
        {{ stg_int('"RSEI_CHEM2"') }} as rsei_chem2,
        {{ stg_int('"RSEI_CA_CHEM2"') }} as rsei_ca_chem2,
        {{ stg_int('"RSEI_NCA_CHEM2"') }} as rsei_nca_chem2,
        {{ stg_int('"RSEI_CHEM_MODLBS2"') }} as rsei_chem_modlbs2,
        {{ null_junk('"NAME_CHEMICAL3"') }} as name_chemical3,
        {{ stg_int('"RSEI_CHEM3"') }} as rsei_chem3,
        {{ stg_int('"RSEI_CA_CHEM3"') }} as rsei_ca_chem3,
        {{ stg_int('"RSEI_NCA_CHEM3"') }} as rsei_nca_chem3,
        {{ stg_int('"RSEI_CHEM_MODLBS3"') }} as rsei_chem_modlbs3,
        {{ null_junk('"LATITUDE"') }} as latitude,
        {{ null_junk('"LONGITUDE"') }} as longitude,
        {{ stg_int('"CT"') }} as ct,
        {{ null_junk('"TOTAL_RSEI_URL"') }} as total_rsei_url,
        {{ null_junk('"TOP_CHEM_RSEI_URL"') }} as top_chem_rsei_url,
        {{ null_junk('"GEOMETRY"') }} as geometry,
        INGESTED_AT as _loaded_at,
        'https://data.lacounty.gov/datasets/5156c7e65ea848aab24dfa509ba49441_0' as _source_url

    from source

)

select * from renamed
