-- [1]
-- columns for all my tables
SELECT table_schema, table_name, row_count FROM LIBRARY_MARTS.INFORMATION_SCHEMA.TABLES WHERE table_name IN ('JUSTICE__FED_COURTLISTENER_SCHOOLS','XWALK_HOSPITAL_CCN_EIN','HEALTH__FED_CMS_HOME_HEALTH','HEALTH__FED_CMS_NURSING_HOME_PENALTIES','HEALTH__FED_CMS_NURSING_HOME','HEALTH__FED_NURSINGHOME411','HEALTH__FED_CMS_NURSING_HOME_DEFICIENCIES','FINANCE__FED_IRS527_SCHEDULE_A_CONTRIBUTIONS','LABOR__FED_OSHA_ITA_CASE_DETAIL_2024','LABOR__FED_OSHA_ITA_CASE_DETAIL_2025','LABOR__FED_OSHA_ITA_300A_SUMMARY_2023','LABOR__FED_OSHA_ITA_300A_SUMMARY_2024','LABOR__FED_OSHA_ITA_300A_SUMMARY_2025','LABOR__FED_OSHA_ITA_CASE_DETAIL_2023','HOUSING__FED_CFPB_HMDA','HOUSING__FED_CFPB_HMDA_DC_ONLY','HOUSING__FED_CFPB_HMDA_LAR','IMMIGRATION__FED_ICE_DETENTION_STINTS','IMMIGRATION__FED_ICE_DETAINERS','LABOR__FED_MSHA_VIOLATIONS','LABOR__FED_MSHA_ACCIDENTS','ENVIRONMENT__FED_EPA_SDWA_SDWA_VIOLATIONS_ENFORCEMENT','ENVIRONMENT__FED_EPA_SDWA_SDWA_PN_VIOLATION_ASSOC','ENVIRONMENT__FED_EPA_NPDES_NPDES_INFORMAL_ENFORCEMENT_ACTIONS') ORDER BY 2;

-- [2]
-- schools profile
SELECT COUNT(*) n, COUNT_IF(TRIM(EIN)<>'') ein_rows, COUNT(DISTINCT NULLIF(TRIM(EIN),'')) d_ein, COUNT_IF(REGEXP_LIKE(TRIM(EIN),'^[0-9]{8,9}$') AND TRY_TO_NUMBER(EIN)>0) ein_ok, COUNT_IF(TRIM(IS_ALIAS_OF_ID::VARCHAR)<>'') alias_rows FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_COURTLISTENER_SCHOOLS;

-- [3]
-- schools sample with EIN
SELECT ID, NAME, EIN, IS_ALIAS_OF_ID FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_COURTLISTENER_SCHOOLS WHERE TRIM(EIN)<>'' ORDER BY HASH(ID) LIMIT 8;

-- [4]
-- xwalk EINs landing in schools
SELECT x.CCN, x.CCN_NAME, x.EIN, x.EIN_NAME, s.NAME school, x.MATCH_TIER FROM LIBRARY_MARTS.CORE.XWALK_HOSPITAL_CCN_EIN x JOIN (SELECT DISTINCT LPAD(TRIM(EIN),9,'0') e, NAME FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_COURTLISTENER_SCHOOLS WHERE REGEXP_LIKE(TRIM(EIN),'^[0-9]{8,9}$') AND TRY_TO_NUMBER(EIN)>0) s ON s.e=LPAD(TRIM(x.EIN),9,'0') LIMIT 40;

-- [5]
-- key columns for my tables
SELECT table_schema, table_name, LISTAGG(column_name||':'||data_type, ', ') WITHIN GROUP (ORDER BY ordinal_position) cols FROM LIBRARY_MARTS.INFORMATION_SCHEMA.COLUMNS WHERE table_schema<>'TIMELINE' AND table_name IN ('HEALTH__FED_CMS_HOME_HEALTH','HEALTH__FED_CMS_NURSING_HOME_PENALTIES','HEALTH__FED_CMS_NURSING_HOME','HEALTH__FED_NURSINGHOME411','HEALTH__FED_CMS_NURSING_HOME_DEFICIENCIES','FINANCE__FED_IRS527_SCHEDULE_A_CONTRIBUTIONS','LABOR__FED_OSHA_ITA_300A_SUMMARY_2024','HOUSING__FED_CFPB_HMDA','HOUSING__FED_CFPB_HMDA_LAR','IMMIGRATION__FED_ICE_DETENTION_STINTS','IMMIGRATION__FED_ICE_DETAINERS','LABOR__FED_MSHA_VIOLATIONS','LABOR__FED_MSHA_ACCIDENTS','ENVIRONMENT__FED_EPA_SDWA_SDWA_VIOLATIONS_ENFORCEMENT','ENVIRONMENT__FED_EPA_SDWA_SDWA_PN_VIOLATION_ASSOC','ENVIRONMENT__FED_EPA_NPDES_NPDES_INFORMAL_ENFORCEMENT_ACTIONS') AND (column_name ILIKE ANY ('%CCN%','%EIN%','%LEI%','%MINE_ID%','%CONTROLLER%','%PWSID%','%FACILITY%','%REGISTRY%','%NPDES_ID%','%DATE%','%AMOUNT%','%FINE%','%DEATH%','%SPEND%','%YEAR%','%YR%','%PROVIDER%','%ACTION%','%OPERATOR%','%VIOLATION_ID%') ) GROUP BY 1,2 ORDER BY 2;

-- [6]
-- CCN hops A -> XWALK -> SCHOOLS, four nursing/home-health tables
WITH x AS (SELECT DISTINCT TRIM(CCN) c, LPAD(TRIM(EIN),9,'0') e FROM LIBRARY_MARTS.CORE.XWALK_HOSPITAL_CCN_EIN WHERE TRIM(CCN)<>''),
s AS (SELECT DISTINCT LPAD(TRIM(EIN),9,'0') e FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_COURTLISTENER_SCHOOLS WHERE REGEXP_LIKE(TRIM(EIN),'^[0-9]{8,9}$') AND TRY_TO_NUMBER(EIN)>0),
a AS (
 SELECT 'HOME_HEALTH' t, TRIM(CCN) c FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_HOME_HEALTH
 UNION SELECT 'NH_PENALTIES', TRIM(CMS_CERTIFICATION_NUMBER_CCN) FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_NURSING_HOME_PENALTIES
 UNION SELECT 'NURSING_HOME', TRIM(CMS_CERTIFICATION_NUMBER_CCN) FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_NURSING_HOME
 UNION SELECT 'NH411', TRIM(CMS_CERTIFICATION_NUMBER_CCN) FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_NURSINGHOME411
 UNION SELECT 'NH_DEFICIENCIES', TRIM(CMS_CERTIFICATION_NUMBER_CCN) FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_NURSING_HOME_DEFICIENCIES)
SELECT a.t, COUNT(DISTINCT a.c) d_ccn, MIN(a.c) mn, MAX(a.c) mx, COUNT(DISTINCT CASE WHEN x.c IS NOT NULL THEN a.c END) ccn_in_xwalk, COUNT(DISTINCT CASE WHEN s.e IS NOT NULL THEN a.c END) ccn_to_schools,
 COUNT(DISTINCT CASE WHEN REGEXP_LIKE(a.c,'^[0-9]{6}$') AND SUBSTR(a.c,3,4)::INT BETWEEN 5000 AND 6499 THEN a.c END) nh_range, COUNT(DISTINCT CASE WHEN REGEXP_LIKE(a.c,'^[0-9]{6}$') AND SUBSTR(a.c,3,4)::INT BETWEEN 7000 AND 9999 THEN a.c END) hha_range
FROM a LEFT JOIN x ON x.c=a.c LEFT JOIN s ON s.e=x.e GROUP BY 1
UNION ALL
SELECT 'XWALK', COUNT(DISTINCT c), MIN(c), MAX(c), NULL, COUNT(DISTINCT CASE WHEN e IN (SELECT e FROM s) THEN c END), COUNT(DISTINCT CASE WHEN REGEXP_LIKE(c,'^[0-9]{6}$') AND SUBSTR(c,3,4)::INT BETWEEN 5000 AND 6499 THEN c END), COUNT(DISTINCT CASE WHEN REGEXP_LIKE(c,'^[0-9]{6}$') AND SUBSTR(c,3,4)::INT BETWEEN 7000 AND 9999 THEN c END) FROM x;

-- [7]
-- IRS527 EIN -> XWALK -> NH deficiencies
WITH p AS (SELECT LPAD(REGEXP_REPLACE(EIN,'[^0-9]',''),9,'0') e, COUNT(*) n, SUM(CONTRIBUTION_AMOUNT) usd FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_IRS527_SCHEDULE_A_CONTRIBUTIONS WHERE LENGTH(REGEXP_REPLACE(EIN,'[^0-9]',''))>=8 GROUP BY 1),
x AS (SELECT DISTINCT TRIM(CCN) c, LPAD(TRIM(EIN),9,'0') e, EIN_NAME FROM LIBRARY_MARTS.CORE.XWALK_HOSPITAL_CCN_EIN),
d AS (SELECT DISTINCT TRIM(CMS_CERTIFICATION_NUMBER_CCN) c FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_NURSING_HOME_DEFICIENCIES)
SELECT (SELECT COUNT(*) FROM p) d_ein_527, COUNT(DISTINCT p.e) ein_in_xwalk, COUNT(DISTINCT CASE WHEN d.c IS NOT NULL THEN p.e END) ein_to_nh_def, LISTAGG(DISTINCT x.EIN_NAME, '; ') names
FROM p JOIN x ON x.e=p.e LEFT JOIN d ON d.c=x.c;

-- [8]
-- Open Payments 2022/2023 CCN -> XWALK -> five OSHA tables: land rate and dollar gap
WITH op AS (
 SELECT 'OP2022' y, TRIM(CCN) c, COUNT(*) n, SUM(TRY_TO_DOUBLE(TOTAL_AMOUNT_OF_PAYMENT_USDOLLARS::VARCHAR)) usd, MIN(PROGRAM_YEAR) py FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_OPEN_PAYMENTS_2022 WHERE TRIM(CCN)<>'' GROUP BY 2
 UNION ALL SELECT 'OP2023', TRIM(CCN), COUNT(*), SUM(TRY_TO_DOUBLE(TOTAL_AMOUNT_OF_PAYMENT_USDOLLARS::VARCHAR)), MIN(PROGRAM_YEAR) FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_OPEN_PAYMENTS_2023 WHERE TRIM(CCN)<>'' GROUP BY 2),
x AS (SELECT TRIM(CCN) c, MAX(LPAD(TRIM(EIN),9,'0')) e FROM LIBRARY_MARTS.CORE.XWALK_HOSPITAL_CCN_EIN GROUP BY 1),
o AS (
 SELECT 'CD2024' t, LPAD(TRIM(EIN),9,'0') e FROM LIBRARY_MARTS.LABOR.LABOR__FED_OSHA_ITA_CASE_DETAIL_2024 WHERE REGEXP_LIKE(TRIM(EIN),'^[0-9]{8,9}$') AND TRY_TO_NUMBER(EIN)>0 GROUP BY 2
 UNION ALL SELECT 'CD2025', LPAD(TRIM(EIN),9,'0') FROM LIBRARY_MARTS.LABOR.LABOR__FED_OSHA_ITA_CASE_DETAIL_2025 WHERE REGEXP_LIKE(TRIM(EIN),'^[0-9]{8,9}$') AND TRY_TO_NUMBER(EIN)>0 GROUP BY 2
 UNION ALL SELECT '300A2023', LPAD(TRIM(EIN),9,'0') FROM LIBRARY_MARTS.LABOR.LABOR__FED_OSHA_ITA_300A_SUMMARY_2023 WHERE REGEXP_LIKE(TRIM(EIN),'^[0-9]{8,9}$') AND TRY_TO_NUMBER(EIN)>0 GROUP BY 2
 UNION ALL SELECT '300A2024', LPAD(TRIM(EIN),9,'0') FROM LIBRARY_MARTS.LABOR.LABOR__FED_OSHA_ITA_300A_SUMMARY_2024 WHERE REGEXP_LIKE(TRIM(EIN),'^[0-9]{8,9}$') AND TRY_TO_NUMBER(EIN)>0 GROUP BY 2
 UNION ALL SELECT '300A2025', LPAD(TRIM(EIN),9,'0') FROM LIBRARY_MARTS.LABOR.LABOR__FED_OSHA_ITA_300A_SUMMARY_2025 WHERE REGEXP_LIKE(TRIM(EIN),'^[0-9]{8,9}$') AND TRY_TO_NUMBER(EIN)>0 GROUP BY 2),
tl AS (SELECT DISTINCT t FROM o)
SELECT op.y, tl.t, MIN(op.py) py, COUNT(*) d_ccn, COUNT(x.c) ccn_in_xwalk, COUNT(o.e) ccn_reach_osha, ROUND(COUNT(o.e)/COUNT(*),3) land,
 ROUND(SUM(CASE WHEN o.e IS NOT NULL THEN usd END)/1e6,1) usd_m_matched, ROUND(SUM(CASE WHEN o.e IS NULL THEN usd END)/1e6,1) usd_m_unmatched,
 ROUND(MEDIAN(CASE WHEN o.e IS NOT NULL THEN usd END)) med_matched, ROUND(MEDIAN(CASE WHEN o.e IS NULL AND x.c IS NOT NULL THEN usd END)) med_xwalk_not_osha, ROUND(MEDIAN(CASE WHEN x.c IS NULL THEN usd END)) med_not_xwalk
FROM op CROSS JOIN tl LEFT JOIN x ON x.c=op.c LEFT JOIN o ON o.t=tl.t AND o.e=x.e GROUP BY 1,2 ORDER BY 1,2;

-- [9]
-- top-dollar OP2022 CCNs and which OSHA tables they reach
WITH op AS (SELECT TRIM(CCN) c, MAX(TEACHING_HOSPITAL_NAME) nm, SUM(TRY_TO_DOUBLE(TOTAL_AMOUNT_OF_PAYMENT_USDOLLARS::VARCHAR)) usd FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_OPEN_PAYMENTS_2022 WHERE TRIM(CCN)<>'' GROUP BY 1),
x AS (SELECT TRIM(CCN) c, MAX(LPAD(TRIM(EIN),9,'0')) e, MAX(EIN_NAME) en FROM LIBRARY_MARTS.CORE.XWALK_HOSPITAL_CCN_EIN GROUP BY 1)
SELECT op.c, op.nm, x.en, ROUND(op.usd/1e6,1) usd_m, x.e,
 x.e IN (SELECT LPAD(TRIM(EIN),9,'0') FROM LIBRARY_MARTS.LABOR.LABOR__FED_OSHA_ITA_300A_SUMMARY_2024) in_300a24,
 x.e IN (SELECT LPAD(TRIM(EIN),9,'0') FROM LIBRARY_MARTS.LABOR.LABOR__FED_OSHA_ITA_300A_SUMMARY_2025) in_300a25
FROM op LEFT JOIN x ON x.c=op.c ORDER BY op.usd DESC LIMIT 8;

-- [10]
-- OSHA 300A 2024 side: EINs reached from Open Payments hospitals vs all other EINs; name/state check on 20
WITH hx AS (SELECT DISTINCT LPAD(TRIM(x.EIN),9,'0') e FROM LIBRARY_MARTS.CORE.XWALK_HOSPITAL_CCN_EIN x JOIN (SELECT DISTINCT TRIM(CCN) c FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_OPEN_PAYMENTS_2023 WHERE TRIM(CCN)<>'') op ON op.c=TRIM(x.CCN)),
a AS (SELECT LPAD(TRIM(EIN),9,'0') e, COUNT(*) sites, SUM(TOTAL_DEATHS) deaths, SUM(TRY_TO_DOUBLE(ANNUAL_AVERAGE_EMPLOYEES::VARCHAR)) emp, SUM(TRY_TO_DOUBLE(TOTAL_DAFW_CASES::VARCHAR)) dafw FROM LIBRARY_MARTS.LABOR.LABOR__FED_OSHA_ITA_300A_SUMMARY_2024 WHERE REGEXP_LIKE(TRIM(EIN),'^[0-9]{8,9}$') AND TRY_TO_NUMBER(EIN)>0 GROUP BY 1)
SELECT (hx.e IS NOT NULL) op_hospital, COUNT(*) eins, SUM(sites) sites, MEDIAN(emp) med_emp, SUM(deaths) deaths, ROUND(SUM(deaths)/SUM(emp)*1e5,2) deaths_per_100k_emp, ROUND(SUM(dafw)/SUM(emp)*100,2) dafw_per_100_emp FROM a LEFT JOIN hx ON hx.e=a.e GROUP BY 1;

-- [11]
-- name / state agreement, 20 random xwalk->300A 2024 pairs
SELECT x.CCN, x.CCN_NAME, x.CCN_ZIP5, o.COMPANY_NAME, o.ESTABLISHMENT_NAME, o.STATE, LEFT(o.ZIP_CODE,5) zip, x.MATCH_TIER FROM LIBRARY_MARTS.CORE.XWALK_HOSPITAL_CCN_EIN x JOIN (SELECT DISTINCT TRIM(CCN) c FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_OPEN_PAYMENTS_2023 WHERE TRIM(CCN)<>'') op ON op.c=TRIM(x.CCN)
JOIN LIBRARY_MARTS.LABOR.LABOR__FED_OSHA_ITA_300A_SUMMARY_2024 o ON LPAD(TRIM(o.EIN),9,'0')=LPAD(TRIM(x.EIN),9,'0') QUALIFY ROW_NUMBER() OVER (PARTITION BY x.CCN ORDER BY HASH(o.ESTABLISHMENT_NAME))=1 ORDER BY HASH(x.CCN) LIMIT 20;

-- [12]
-- XC crosswalk -> NPDES informal: registry format, reach
WITH n AS (SELECT TRIM(REGISTRY_ID) r, COUNT(*) acts, MIN(ACHIEVED_DATE) d0, MAX(ACHIEVED_DATE) d1 FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_NPDES_NPDES_INFORMAL_ENFORCEMENT_ACTIONS GROUP BY 1),
x AS (SELECT EPA_REGISTRY_ID::VARCHAR r, TRIM(PARENT_UEI) u FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__XC_EPA_CORPORATE_CROSSWALK)
SELECT (SELECT COUNT(*) FROM n) npdes_registry_ids, (SELECT COUNT_IF(REGEXP_LIKE(r,'^110[0-9]{9}$')) FROM n) frs_shaped, (SELECT SUM(acts) FROM n) acts, (SELECT MIN(d0)||' to '||MAX(d1) FROM n) dates,
 COUNT(*) xc_rows, COUNT(DISTINCT x.r) xc_frs, COUNT(DISTINCT CASE WHEN n.r IS NOT NULL THEN x.r END) xc_frs_in_npdes, COUNT(DISTINCT NULLIF(x.u,'')) xc_uei, COUNT(DISTINCT CASE WHEN n.r IS NOT NULL THEN NULLIF(x.u,'') END) xc_uei_to_npdes, SUM(CASE WHEN n.r IS NOT NULL AND x.u<>'' THEN n.acts END) npdes_acts_reached
FROM x LEFT JOIN n ON n.r=x.r;

-- [13]
-- R2 columns
SELECT column_name, data_type FROM LIBRARY_MARTS.INFORMATION_SCHEMA.COLUMNS WHERE table_name='ECONOMICS__FED_USASPENDING_CONTRACTS_FULL_R2' AND (column_name ILIKE '%AWARD%ID%' OR column_name ILIKE '%PIID%' OR column_name ILIKE '%MODIF%' OR column_name ILIKE '%ACTION_DATE%' OR column_name ILIKE '%UEI%' OR column_name ILIKE '%OBLIGATION%' OR column_name ILIKE 'RECIPIENT_NAME');

-- [14]
-- UEI hop CONTRACTS -> XC -> NPDES informal: land rate and dollar gap
WITH a AS (SELECT TRIM(RECIPIENT_UEI) u, COUNT(*) n, SUM(TRY_TO_DOUBLE(FEDERAL_ACTION_OBLIGATION::VARCHAR)) usd, MIN(ACTION_DATE::VARCHAR) d0, MAX(ACTION_DATE::VARCHAR) d1 FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_USASPENDING_CONTRACTS WHERE TRIM(RECIPIENT_UEI)<>'' GROUP BY 1),
x AS (SELECT DISTINCT TRIM(PARENT_UEI) u FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__XC_EPA_CORPORATE_CROSSWALK WHERE TRIM(PARENT_UEI)<>''),
xn AS (SELECT DISTINCT TRIM(x.PARENT_UEI) u FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__XC_EPA_CORPORATE_CROSSWALK x JOIN (SELECT DISTINCT TRIM(REGISTRY_ID) r FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_NPDES_NPDES_INFORMAL_ENFORCEMENT_ACTIONS) n ON n.r=x.EPA_REGISTRY_ID::VARCHAR WHERE TRIM(x.PARENT_UEI)<>'')
SELECT 'CONTRACTS' t, COUNT(*) d_uei, SUM(a.n) rows_, MIN(a.d0) d0, MAX(a.d1) d1, COUNT(x.u) uei_in_xc, COUNT(xn.u) uei_to_npdes, ROUND(COUNT(xn.u)/COUNT(*)*100,3) pct,
 ROUND(SUM(CASE WHEN xn.u IS NOT NULL THEN a.usd END)/1e9,2) usd_b_matched, ROUND(SUM(CASE WHEN xn.u IS NULL THEN a.usd END)/1e9,2) usd_b_unmatched,
 ROUND(MEDIAN(CASE WHEN xn.u IS NOT NULL THEN a.usd END)) med_matched, ROUND(MEDIAN(CASE WHEN x.u IS NOT NULL AND xn.u IS NULL THEN a.usd END)) med_xc_not_npdes, ROUND(MEDIAN(CASE WHEN x.u IS NULL THEN a.usd END)) med_not_xc
FROM a LEFT JOIN x ON x.u=a.u LEFT JOIN xn ON xn.u=a.u;

-- [15]
-- UEI hop CONTRACTS_FULL -> XC -> NPDES informal: land rate and dollar gap
WITH a AS (SELECT TRIM(RECIPIENT_UEI) u, COUNT(*) n, SUM(TRY_TO_DOUBLE(FEDERAL_ACTION_OBLIGATION::VARCHAR)) usd, MIN(ACTION_DATE::VARCHAR) d0, MAX(ACTION_DATE::VARCHAR) d1 FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_USASPENDING_CONTRACTS_FULL WHERE TRIM(RECIPIENT_UEI)<>'' GROUP BY 1),
x AS (SELECT DISTINCT TRIM(PARENT_UEI) u FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__XC_EPA_CORPORATE_CROSSWALK WHERE TRIM(PARENT_UEI)<>''),
xn AS (SELECT DISTINCT TRIM(x.PARENT_UEI) u FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__XC_EPA_CORPORATE_CROSSWALK x JOIN (SELECT DISTINCT TRIM(REGISTRY_ID) r FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_NPDES_NPDES_INFORMAL_ENFORCEMENT_ACTIONS) n ON n.r=x.EPA_REGISTRY_ID::VARCHAR WHERE TRIM(x.PARENT_UEI)<>'')
SELECT 'CONTRACTS_FULL' t, COUNT(*) d_uei, SUM(a.n) rows_, MIN(a.d0) d0, MAX(a.d1) d1, COUNT(x.u) uei_in_xc, COUNT(xn.u) uei_to_npdes, ROUND(COUNT(xn.u)/COUNT(*)*100,3) pct,
 ROUND(SUM(CASE WHEN xn.u IS NOT NULL THEN a.usd END)/1e9,2) usd_b_matched, ROUND(SUM(CASE WHEN xn.u IS NULL THEN a.usd END)/1e9,2) usd_b_unmatched,
 ROUND(MEDIAN(CASE WHEN xn.u IS NOT NULL THEN a.usd END)) med_matched, ROUND(MEDIAN(CASE WHEN x.u IS NOT NULL AND xn.u IS NULL THEN a.usd END)) med_xc_not_npdes, ROUND(MEDIAN(CASE WHEN x.u IS NULL THEN a.usd END)) med_not_xc
FROM a LEFT JOIN x ON x.u=a.u LEFT JOIN xn ON xn.u=a.u;

-- [16]
-- UEI hop CONTRACTS_FULL_R2 -> XC -> NPDES informal: land rate and dollar gap
WITH a AS (SELECT TRIM(RECIPIENT_UEI) u, COUNT(*) n, SUM(TRY_TO_DOUBLE(FEDERAL_ACTION_OBLIGATION::VARCHAR)) usd, MIN(ACTION_DATE::VARCHAR) d0, MAX(ACTION_DATE::VARCHAR) d1 FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_USASPENDING_CONTRACTS_FULL_R2 WHERE TRIM(RECIPIENT_UEI)<>'' GROUP BY 1),
x AS (SELECT DISTINCT TRIM(PARENT_UEI) u FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__XC_EPA_CORPORATE_CROSSWALK WHERE TRIM(PARENT_UEI)<>''),
xn AS (SELECT DISTINCT TRIM(x.PARENT_UEI) u FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__XC_EPA_CORPORATE_CROSSWALK x JOIN (SELECT DISTINCT TRIM(REGISTRY_ID) r FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_NPDES_NPDES_INFORMAL_ENFORCEMENT_ACTIONS) n ON n.r=x.EPA_REGISTRY_ID::VARCHAR WHERE TRIM(x.PARENT_UEI)<>'')
SELECT 'CONTRACTS_FULL_R2' t, COUNT(*) d_uei, SUM(a.n) rows_, MIN(a.d0) d0, MAX(a.d1) d1, COUNT(x.u) uei_in_xc, COUNT(xn.u) uei_to_npdes, ROUND(COUNT(xn.u)/COUNT(*)*100,3) pct,
 ROUND(SUM(CASE WHEN xn.u IS NOT NULL THEN a.usd END)/1e9,2) usd_b_matched, ROUND(SUM(CASE WHEN xn.u IS NULL THEN a.usd END)/1e9,2) usd_b_unmatched,
 ROUND(MEDIAN(CASE WHEN xn.u IS NOT NULL THEN a.usd END)) med_matched, ROUND(MEDIAN(CASE WHEN x.u IS NOT NULL AND xn.u IS NULL THEN a.usd END)) med_xc_not_npdes, ROUND(MEDIAN(CASE WHEN x.u IS NULL THEN a.usd END)) med_not_xc
FROM a LEFT JOIN x ON x.u=a.u LEFT JOIN xn ON xn.u=a.u;

-- [17]
-- UEI hop ASSISTANCE_FULL -> XC -> NPDES informal: land rate and dollar gap
WITH a AS (SELECT TRIM(RECIPIENT_UEI) u, COUNT(*) n, SUM(TRY_TO_DOUBLE(FEDERAL_ACTION_OBLIGATION::VARCHAR)) usd, MIN(ACTION_DATE::VARCHAR) d0, MAX(ACTION_DATE::VARCHAR) d1 FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_USASPENDING_ASSISTANCE_FULL WHERE TRIM(RECIPIENT_UEI)<>'' GROUP BY 1),
x AS (SELECT DISTINCT TRIM(PARENT_UEI) u FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__XC_EPA_CORPORATE_CROSSWALK WHERE TRIM(PARENT_UEI)<>''),
xn AS (SELECT DISTINCT TRIM(x.PARENT_UEI) u FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__XC_EPA_CORPORATE_CROSSWALK x JOIN (SELECT DISTINCT TRIM(REGISTRY_ID) r FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_NPDES_NPDES_INFORMAL_ENFORCEMENT_ACTIONS) n ON n.r=x.EPA_REGISTRY_ID::VARCHAR WHERE TRIM(x.PARENT_UEI)<>'')
SELECT 'ASSISTANCE_FULL' t, COUNT(*) d_uei, SUM(a.n) rows_, MIN(a.d0) d0, MAX(a.d1) d1, COUNT(x.u) uei_in_xc, COUNT(xn.u) uei_to_npdes, ROUND(COUNT(xn.u)/COUNT(*)*100,3) pct,
 ROUND(SUM(CASE WHEN xn.u IS NOT NULL THEN a.usd END)/1e9,2) usd_b_matched, ROUND(SUM(CASE WHEN xn.u IS NULL THEN a.usd END)/1e9,2) usd_b_unmatched,
 ROUND(MEDIAN(CASE WHEN xn.u IS NOT NULL THEN a.usd END)) med_matched, ROUND(MEDIAN(CASE WHEN x.u IS NOT NULL AND xn.u IS NULL THEN a.usd END)) med_xc_not_npdes, ROUND(MEDIAN(CASE WHEN x.u IS NULL THEN a.usd END)) med_not_xc
FROM a LEFT JOIN x ON x.u=a.u LEFT JOIN xn ON xn.u=a.u;

-- [18]
-- name check: R2 recipient name vs XC facility name for UEIs reaching NPDES informal, 20 random
WITH xn AS (SELECT TRIM(x.PARENT_UEI) u, x.EPA_REGISTRY_ID::VARCHAR r, x.FACILITY_NAME fn FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__XC_EPA_CORPORATE_CROSSWALK x WHERE TRIM(x.PARENT_UEI)<>'' AND x.EPA_REGISTRY_ID::VARCHAR IN (SELECT TRIM(REGISTRY_ID) FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_NPDES_NPDES_INFORMAL_ENFORCEMENT_ACTIONS)),
s AS (SELECT u, ANY_VALUE(r) r, ANY_VALUE(fn) fn FROM xn GROUP BY u ORDER BY HASH(u) LIMIT 20)
SELECT s.u, s.fn xc_facility, (SELECT MAX(RECIPIENT_NAME) FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_USASPENDING_CONTRACTS_FULL_R2 r WHERE TRIM(r.RECIPIENT_UEI)=s.u) r2_name FROM s;

-- [19]
-- after: new R2 awards (first action date) before vs after each UEI's first NPDES informal action (1990-2026 dates only)
WITH xn AS (SELECT TRIM(x.PARENT_UEI) u, MIN(n.ACHIEVED_DATE) first_enf, COUNT(*) acts FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__XC_EPA_CORPORATE_CROSSWALK x JOIN LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_NPDES_NPDES_INFORMAL_ENFORCEMENT_ACTIONS n ON TRIM(n.REGISTRY_ID)=x.EPA_REGISTRY_ID::VARCHAR WHERE TRIM(x.PARENT_UEI)<>'' AND n.ACHIEVED_DATE BETWEEN '1990-01-01' AND '2026-09-24' GROUP BY 1),
aw AS (SELECT TRIM(RECIPIENT_UEI) u, AWARD_ID_PIID p, MIN(TRY_TO_DATE(ACTION_DATE)) d0, SUM(FEDERAL_ACTION_OBLIGATION) usd, MAX(RECIPIENT_NAME) nm FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_USASPENDING_CONTRACTS_FULL_R2 WHERE TRIM(RECIPIENT_UEI) IN (SELECT u FROM xn) GROUP BY 1,2)
SELECT xn.u, MAX(aw.nm) nm, MIN(xn.first_enf) first_enf, MAX(xn.acts) npdes_acts, COUNT_IF(aw.d0<xn.first_enf) awards_before, COUNT_IF(aw.d0>=xn.first_enf) awards_after, ROUND(SUM(CASE WHEN aw.d0>=xn.first_enf THEN aw.usd END)/1e6,1) usd_m_after, MIN(aw.d0) first_award
FROM xn JOIN aw ON aw.u=xn.u GROUP BY 1 ORDER BY usd_m_after DESC NULLS LAST LIMIT 12;

-- [20]
-- R:LEI overlap across the three HMDA tables
WITH h AS (SELECT 'HMDA' t, TRIM(LEI) l, COUNT(*) n, COUNT_IF(TRIM(ACTION_TAKEN)='3') den, MIN(ACTIVITY_YEAR::VARCHAR) y FROM LIBRARY_MARTS.HOUSING.HOUSING__FED_CFPB_HMDA GROUP BY 2
 UNION ALL SELECT 'DC_ONLY', TRIM(LEI), COUNT(*), COUNT_IF(TRIM(ACTION_TAKEN)='3'), MIN(ACTIVITY_YEAR::VARCHAR) FROM LIBRARY_MARTS.HOUSING.HOUSING__FED_CFPB_HMDA_DC_ONLY GROUP BY 2
 UNION ALL SELECT 'LAR', TRIM(LEI), COUNT(*), COUNT_IF(TRIM(ACTION_TAKEN)='3'), MIN(ACTIVITY_YEAR::VARCHAR) FROM LIBRARY_MARTS.HOUSING.HOUSING__FED_CFPB_HMDA_LAR GROUP BY 2),
p AS (SELECT l, COUNT(DISTINCT t) nt, LISTAGG(t,',') WITHIN GROUP (ORDER BY t) ts, SUM(IFF(t='HMDA',n,0)) n22, SUM(IFF(t='LAR',n,0)) n23, SUM(IFF(t='HMDA',den,0)) den22, SUM(IFF(t='LAR',den,0)) den23 FROM h GROUP BY 1)
SELECT ts, COUNT(*) leis, SUM(n22) rows22, SUM(n23) rows23, ROUND(SUM(den22)/NULLIF(SUM(n22),0),3) den_rate22, ROUND(SUM(den23)/NULLIF(SUM(n23),0),3) den_rate23 FROM p GROUP BY 1 ORDER BY 2 DESC;

-- [21]
-- R:EIN overlap: OSHA case detail 2023 vs 300A 2024
WITH c AS (SELECT LPAD(TRIM(EIN),9,'0') e, COUNT(*) cases, MAX(COMPANY_NAME) nm FROM LIBRARY_MARTS.LABOR.LABOR__FED_OSHA_ITA_CASE_DETAIL_2023 WHERE REGEXP_LIKE(TRIM(EIN),'^[0-9]{8,9}$') AND TRY_TO_NUMBER(EIN)>0 GROUP BY 1),
s AS (SELECT LPAD(TRIM(EIN),9,'0') e, COUNT(*) sites, SUM(TOTAL_DEATHS) deaths, SUM(TRY_TO_DOUBLE(TOTAL_DAFW_CASES::VARCHAR)) dafw, MAX(COMPANY_NAME) nm FROM LIBRARY_MARTS.LABOR.LABOR__FED_OSHA_ITA_300A_SUMMARY_2024 WHERE REGEXP_LIKE(TRIM(EIN),'^[0-9]{8,9}$') AND TRY_TO_NUMBER(EIN)>0 GROUP BY 1)
SELECT (c.e IS NOT NULL)::INT in_cd23, (s.e IS NOT NULL)::INT in_300a24, COUNT(*) eins, SUM(c.cases) cases, SUM(s.deaths) deaths FROM c FULL JOIN s ON s.e=c.e GROUP BY 1,2;

-- [22]
-- R:EIN top 10 by 2023 cases, on both tables
WITH c AS (SELECT LPAD(TRIM(EIN),9,'0') e, COUNT(*) cases, COUNT_IF(TRY_TO_DATE(DATE_OF_DEATH::VARCHAR) IS NOT NULL) death_cases, MAX(COMPANY_NAME) nm FROM LIBRARY_MARTS.LABOR.LABOR__FED_OSHA_ITA_CASE_DETAIL_2023 WHERE REGEXP_LIKE(TRIM(EIN),'^[0-9]{8,9}$') AND TRY_TO_NUMBER(EIN)>0 GROUP BY 1),
s AS (SELECT LPAD(TRIM(EIN),9,'0') e, COUNT(*) sites, SUM(TOTAL_DEATHS) deaths, SUM(TRY_TO_DOUBLE(ANNUAL_AVERAGE_EMPLOYEES::VARCHAR)) emp, COUNT(DISTINCT UPPER(COMPANY_NAME)) names, MAX(COMPANY_NAME) nm FROM LIBRARY_MARTS.LABOR.LABOR__FED_OSHA_ITA_300A_SUMMARY_2024 WHERE REGEXP_LIKE(TRIM(EIN),'^[0-9]{8,9}$') AND TRY_TO_NUMBER(EIN)>0 GROUP BY 1)
SELECT c.e, c.nm cd_name, s.nm a_name, s.names, c.cases, c.death_cases, s.sites, s.deaths, s.emp FROM c JOIN s ON s.e=c.e ORDER BY c.cases DESC LIMIT 10;

-- [23]
-- R:ICE_FACILITY overlap: stints vs detainers by facility code
WITH a AS (SELECT TRIM(DETENTION_FACILITY_CODE) f, COUNT(*) stints, MAX(DETENTION_FACILITY) nm FROM LIBRARY_MARTS.IMMIGRATION.IMMIGRATION__FED_ICE_DETENTION_STINTS GROUP BY 1),
b AS (SELECT TRIM(DETENTION_FACILITY_CODE) f, COUNT(*) detainers, MAX(DETENTION_FACILITY) nm FROM LIBRARY_MARTS.IMMIGRATION.IMMIGRATION__FED_ICE_DETAINERS GROUP BY 1)
SELECT (a.f IS NOT NULL)::INT in_stints, (b.f IS NOT NULL)::INT in_detainers, COUNT(*) codes, SUM(stints) stints, SUM(detainers) detainers, COUNT_IF(COALESCE(a.f,b.f) IS NULL OR COALESCE(a.f,b.f)='') blank_code FROM a FULL JOIN b ON a.f=b.f GROUP BY 1,2;

-- [24]
-- R:ICE_FACILITY top 10 by stints, detainers alongside
WITH a AS (SELECT TRIM(DETENTION_FACILITY_CODE) f, COUNT(*) stints, MAX(DETENTION_FACILITY) nm, MAX(STATE) st FROM LIBRARY_MARTS.IMMIGRATION.IMMIGRATION__FED_ICE_DETENTION_STINTS GROUP BY 1),
b AS (SELECT TRIM(DETENTION_FACILITY_CODE) f, COUNT(*) detainers, MAX(DETENTION_FACILITY) nm FROM LIBRARY_MARTS.IMMIGRATION.IMMIGRATION__FED_ICE_DETAINERS GROUP BY 1)
SELECT a.f, a.nm, a.st, a.stints, b.detainers, b.nm det_name FROM a LEFT JOIN b ON b.f=a.f ORDER BY a.stints DESC LIMIT 10;

-- [25]
-- R:ICE detainers top 10 facilities
SELECT TRIM(DETENTION_FACILITY_CODE) f, MAX(DETENTION_FACILITY) nm, COUNT(*) n, COUNT_IF(TRIM(DETENTION_FACILITY_CODE)='' OR DETENTION_FACILITY_CODE IS NULL) blank FROM LIBRARY_MARTS.IMMIGRATION.IMMIGRATION__FED_ICE_DETAINERS GROUP BY 1 ORDER BY n DESC LIMIT 10;

-- [26]
-- MSHA key formats both tables
SELECT 'VIOL' t, COUNT(*) n, COUNT(DISTINCT MINE_ID) d_mine, COUNT(DISTINCT CONTROLLER_ID) d_ctrl, COUNT_IF(MINE_ID LIKE '"%') quoted_mine, COUNT_IF(CONTROLLER_ID LIKE '"%') quoted_ctrl, MIN(MINE_ID) mn, MAX(MINE_ID) mx, MIN(CONTROLLER_ID) cmn, MAX(CONTROLLER_ID) cmx, MIN(CAL_YR) y0, MAX(CAL_YR) y1 FROM LIBRARY_MARTS.LABOR.LABOR__FED_MSHA_VIOLATIONS
UNION ALL SELECT 'ACC', COUNT(*), COUNT(DISTINCT MINE_ID), COUNT(DISTINCT CONTROLLER_ID), COUNT_IF(MINE_ID LIKE '"%'), COUNT_IF(CONTROLLER_ID LIKE '"%'), MIN(MINE_ID), MAX(MINE_ID), MIN(CONTROLLER_ID), MAX(CONTROLLER_ID), MIN(CAL_YR), MAX(CAL_YR) FROM LIBRARY_MARTS.LABOR.LABOR__FED_MSHA_ACCIDENTS;

-- [27]
-- MSHA accidents: degree/fatal columns
SELECT column_name, data_type FROM LIBRARY_MARTS.INFORMATION_SCHEMA.COLUMNS WHERE table_name='LABOR__FED_MSHA_ACCIDENTS' AND table_schema='LABOR' AND (column_name ILIKE '%DEGREE%' OR column_name ILIKE '%INJ%' OR column_name ILIKE '%FATAL%' OR column_name ILIKE '%DAYS%');

-- [28]
-- PWSID overlap: SDWA violations/enforcement vs PN violation links
WITH v AS (SELECT TRIM(PWSID) p, COUNT(*) n, COUNT(DISTINCT VIOLATION_ID) nv FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_SDWA_SDWA_VIOLATIONS_ENFORCEMENT GROUP BY 1),
pn AS (SELECT TRIM(PWSID) p, COUNT(*) n, COUNT(DISTINCT PN_VIOLATION_ID) npn FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_SDWA_SDWA_PN_VIOLATION_ASSOC GROUP BY 1)
SELECT (v.p IS NOT NULL)::INT in_viol, (pn.p IS NOT NULL)::INT in_pn, COUNT(*) pwsids, SUM(v.n) viol_rows, SUM(pn.n) pn_rows FROM v FULL JOIN pn ON pn.p=v.p GROUP BY 1,2;

-- [29]
-- PN link ids land in the violations table?
WITH pn AS (SELECT TRIM(PWSID) p, TRIM(PN_VIOLATION_ID) pv, TRIM(RELATED_VIOLATION_ID) rv FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_SDWA_SDWA_PN_VIOLATION_ASSOC),
v AS (SELECT DISTINCT TRIM(PWSID) p, TRIM(VIOLATION_ID) vid FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_SDWA_SDWA_VIOLATIONS_ENFORCEMENT WHERE PWSID IN (SELECT PWSID FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_SDWA_SDWA_PN_VIOLATION_ASSOC))
SELECT COUNT(*) links, COUNT(DISTINCT pn.p) pws, COUNT(v1.vid) pn_id_found, COUNT(v2.vid) related_id_found FROM pn LEFT JOIN v v1 ON v1.p=pn.p AND v1.vid=pn.pv LEFT JOIN v v2 ON v2.p=pn.p AND v2.vid=pn.rv;

-- [30]
-- MSHA mine overlap 2000+ and fatality flag values
WITH v AS (SELECT TRIM(MINE_ID) m, COUNT(*) viol FROM LIBRARY_MARTS.LABOR.LABOR__FED_MSHA_VIOLATIONS WHERE CAL_YR>=2000 GROUP BY 1),
a AS (SELECT TRIM(MINE_ID) m, COUNT(*) acc, COUNT_IF(IS_FATALITY) fat, COUNT_IF(IS_FATALITY IS NULL) fat_null FROM LIBRARY_MARTS.LABOR.LABOR__FED_MSHA_ACCIDENTS GROUP BY 1)
SELECT (v.m IS NOT NULL)::INT in_viol, (a.m IS NOT NULL)::INT in_acc, COUNT(*) mines, SUM(viol) viol, SUM(acc) acc, SUM(fat) fatal, SUM(fat_null) fat_null FROM v FULL JOIN a ON a.m=v.m GROUP BY 1,2;

-- [31]
-- MSHA top 10 mines by fatalities, with violations and penalty paid share
WITH v AS (SELECT TRIM(MINE_ID) m, COUNT(*) viol, SUM(AMOUNT_DUE) due, SUM(AMOUNT_PAID) paid, MAX(MINE_NAME) nm, MAX(CONTROLLER_NAME) ctl FROM LIBRARY_MARTS.LABOR.LABOR__FED_MSHA_VIOLATIONS WHERE CAL_YR>=2000 GROUP BY 1),
a AS (SELECT TRIM(MINE_ID) m, COUNT(*) acc, COUNT_IF(IS_FATALITY) fat, MIN(CASE WHEN IS_FATALITY THEN ACCIDENT_DATE END) f0, MAX(CASE WHEN IS_FATALITY THEN ACCIDENT_DATE END) f1 FROM LIBRARY_MARTS.LABOR.LABOR__FED_MSHA_ACCIDENTS GROUP BY 1)
SELECT a.m, v.nm, v.ctl, a.fat, a.f0, a.f1, a.acc, v.viol, ROUND(v.due) due, ROUND(v.paid) paid FROM a JOIN v ON v.m=a.m ORDER BY a.fat DESC, a.acc DESC LIMIT 10;

-- [32]
-- MSHA controller overlap and top 10 by fatalities
WITH v AS (SELECT TRIM(CONTROLLER_ID) c, COUNT(*) viol, SUM(AMOUNT_DUE) due, SUM(AMOUNT_PAID) paid, COUNT(DISTINCT MINE_ID) mines, MAX(CONTROLLER_NAME) nm FROM LIBRARY_MARTS.LABOR.LABOR__FED_MSHA_VIOLATIONS WHERE CAL_YR>=2000 GROUP BY 1),
a AS (SELECT TRIM(CONTROLLER_ID) c, COUNT(*) acc, COUNT_IF(IS_FATALITY) fat, MAX(CONTROLLER_NAME) nm FROM LIBRARY_MARTS.LABOR.LABOR__FED_MSHA_ACCIDENTS GROUP BY 1)
SELECT COALESCE(a.c,v.c) c, COALESCE(v.nm,a.nm) nm, a.fat, a.acc, v.viol, v.mines, ROUND(v.due) due, ROUND(v.paid) paid, (SELECT COUNT(*) FROM a JOIN v v2 ON v2.c=a.c) both_ctrl, (SELECT COUNT(*) FROM a) acc_ctrl, (SELECT COUNT(*) FROM v) viol_ctrl FROM a JOIN v ON v.c=a.c ORDER BY a.fat DESC LIMIT 10;

-- [33]
-- PWSID top 10 by public-notice violations (failure to warn), with all violations
WITH pn AS (SELECT TRIM(PWSID) p, COUNT(DISTINCT PN_VIOLATION_ID) npn, COUNT(DISTINCT RELATED_VIOLATION_ID) nrel, MIN(NON_COMPL_PER_BEGIN_DATE) d0, MAX(NON_COMPL_PER_BEGIN_DATE) d1 FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_SDWA_SDWA_PN_VIOLATION_ASSOC GROUP BY 1),
v AS (SELECT TRIM(PWSID) p, COUNT(DISTINCT VIOLATION_ID) nv, COUNT_IF(TRIM(CONTAMINANT_CODE) IN ('PB90','1030')) lead_rows FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_SDWA_SDWA_VIOLATIONS_ENFORCEMENT WHERE PWSID IN (SELECT PWSID FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_SDWA_SDWA_PN_VIOLATION_ASSOC) GROUP BY 1)
SELECT pn.p, pn.npn, pn.nrel, pn.d0, pn.d1, v.nv, v.lead_rows FROM pn JOIN v ON v.p=pn.p ORDER BY pn.npn DESC LIMIT 10;

-- [34]
-- Open Payments (2024) CCN -> XWALK -> OSHA case detail 2024, land rate, dollar gap, employee gap
WITH op AS (SELECT TRIM(CCN) c, SUM(TRY_TO_DOUBLE(TOTAL_AMOUNT_OF_PAYMENT_USDOLLARS::VARCHAR)) usd, MIN(PROGRAM_YEAR) py FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_OPEN_PAYMENTS WHERE TRIM(CCN)<>'' GROUP BY 1),
x AS (SELECT TRIM(CCN) c, MAX(LPAD(TRIM(EIN),9,'0')) e FROM LIBRARY_MARTS.CORE.XWALK_HOSPITAL_CCN_EIN GROUP BY 1),
o AS (SELECT LPAD(TRIM(EIN),9,'0') e, COUNT(*) cases, MEDIAN(TRY_TO_DOUBLE(ANNUAL_AVERAGE_EMPLOYEES::VARCHAR)) emp FROM LIBRARY_MARTS.LABOR.LABOR__FED_OSHA_ITA_CASE_DETAIL_2024 WHERE REGEXP_LIKE(TRIM(EIN),'^[0-9]{8,9}$') AND TRY_TO_NUMBER(EIN)>0 GROUP BY 1)
SELECT MIN(op.py) py, COUNT(*) d_ccn, COUNT(x.c) in_xwalk, COUNT(o.e) reach_cd24, ROUND(COUNT(o.e)/COUNT(*),3) land, ROUND(SUM(CASE WHEN o.e IS NOT NULL THEN usd END)/1e6,1) usd_m_matched, ROUND(SUM(CASE WHEN o.e IS NULL THEN usd END)/1e6,1) usd_m_unmatched, ROUND(MEDIAN(CASE WHEN o.e IS NOT NULL THEN usd END)) med_matched, ROUND(MEDIAN(CASE WHEN o.e IS NULL THEN usd END)) med_unmatched,
 MEDIAN(o.emp) med_emp_matched, (SELECT MEDIAN(emp) FROM o) med_emp_all_osha
FROM op LEFT JOIN x ON x.c=op.c LEFT JOIN o ON o.e=x.e;

