-- [1] locate tables; USASPENDING_API EIN fill (bridge for 8 OSHA hops)
SELECT table_schema, table_name, row_count, table_type FROM LIBRARY_MARTS.INFORMATION_SCHEMA.TABLES WHERE table_name IN ('XWALK_HOSPITAL_CCN_EIN','XC_EPA_CORPORATE_CROSSWALK','FED_US_USASPENDING_API','FED_OSHA_ITA_CASE_DETAIL_2023','FED_OSHA_ITA_CASE_DETAIL_2024','FED_OSHA_ITA_300A_SUMMARY_2024','FED_EPA_AIR_EMISSIONS_POLL_RPT_COMBINED_EMISSIONS','FQHC_SITE_PEOPLE','FED_HHS_OIG_LEIE','SAM_EXCLUDED_PROVIDERS','FED_SAM_EXCLUSIONS','FED_CMS_NURSING_HOME_DEFICIENCIES','FED_CMS_NURSING_HOME_FIRE_DEFICIENCIES','FED_CMS_NURSING_HOME_PENALTIES','FED_NURSINGHOME411','FED_CMS_NURSING_HOME','FED_CMS_HOME_HEALTH','FED_EPA_NPDES_NPDES_INFORMAL_ENFORCEMENT_ACTIONS','FED_EPA_ICIS_AIR_ICIS_AIR_FACILITIES','FED_EPA_ICIS_FEC_CASE_ENFORCEMENT_CONCLUSION_FACILITIES','FED_EPA_ICIS_FEC_EPA_INFORMAL_ENFORCEMENT_ACTIONS','FED_EPA_ECHO','EPA_PENALTY_GAP','FED_EPA_NPDES_NPDES_PS_VIOLATIONS','FED_EPA_NPDES_NPDES_SE_VIOLATIONS','FED_EPA_NPDES_NPDES_FORMAL_ENFORCEMENT_ACTIONS','FED_EPA_NPDES_NPDES_CS_VIOLATIONS','FED_CMS_OPEN_PAYMENTS','FED_CMS_OPEN_PAYMENTS_2022','FED_CMS_OPEN_PAYMENTS_2023') ORDER BY 2;

-- [2] locate tables; USASPENDING_API EIN fill (bridge for 8 OSHA hops)
SELECT COUNT(*) n, COUNT_IF(TRIM(RECIPIENT_EIN)<>'') ein_filled, COUNT_IF(REGEXP_LIKE(TRIM(RECIPIENT_EIN),'^[0-9]{9}$')) ein9, COUNT_IF(TRIM(RECIPIENT_DUNS)<>'') duns_filled, COUNT_IF(TRIM(RECIPIENT_UEI)<>'') uei_filled, COUNT(DISTINCT RECIPIENT_EIN) d_ein FROM LIBRARY_MARTS.ECONOMICS.FED_US_USASPENDING_API;

-- [3] locate tables by pattern
SELECT table_schema, table_name, row_count, table_type FROM LIBRARY_MARTS.INFORMATION_SCHEMA.TABLES WHERE table_name ILIKE ANY ('%USASPENDING%','%OSHA_ITA%','%EPA_AIR_EMISSIONS%','%CORPORATE_CROSSWALK%','%LEIE%','%SAM_EXCL%','%FQHC_SITE%','%NURSING_HOME%','%NURSINGHOME411%','%HOME_HEALTH%','%NPDES_NPDES%','%ICIS_AIR_FACILITIES%','%ICIS_FEC%','%EPA_ECHO%','%PENALTY_GAP%','%OPEN_PAYMENTS%') ORDER BY 2;

-- [4] bridge fill checks
SELECT COUNT(*) n, COUNT_IF(TRIM(RECIPIENT_EIN)<>'') ein_filled, COUNT_IF(REGEXP_LIKE(TRIM(RECIPIENT_EIN),'^[0-9]{9}$')) ein9, COUNT_IF(TRIM(RECIPIENT_DUNS)<>'') duns_filled, COUNT_IF(TRIM(RECIPIENT_UEI)<>'') uei_filled, COUNT(DISTINCT RECIPIENT_UEI) d_uei FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_US_USASPENDING_API;

-- [5] bridge fill checks
SELECT COUNT(*) n, COUNT(DISTINCT EPA_REGISTRY_ID) d_frs, COUNT_IF(TRIM(PARENT_UEI)<>'') uei_rows, COUNT(DISTINCT NULLIF(TRIM(PARENT_UEI),'')) d_uei, COUNT_IF(TRIM(MATCHED_LEI)<>'') lei_rows, COUNT(DISTINCT NULLIF(TRIM(MATCH_METHOD),'')) d_method FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__XC_EPA_CORPORATE_CROSSWALK;

-- [6] bridge fill checks
SELECT PARENT_UEI, PARENT_LEGAL_NAME, MATCHED_LEGAL_NAME, MATCH_METHOD, COUNT(*) n FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__XC_EPA_CORPORATE_CROSSWALK WHERE TRIM(PARENT_UEI)<>'' GROUP BY 1,2,3,4 ORDER BY n DESC LIMIT 10;

-- [7] bridge fill checks
SELECT COUNT(*) n, COUNT(DISTINCT CCN) d_ccn, COUNT(DISTINCT EIN) d_ein, COUNT_IF(REGEXP_LIKE(TRIM(EIN),'^[0-9]{9}$') AND EIN<>'000000000') ein9, COUNT_IF(LENGTH(TRIM(EIN))<9) short_ein, MIN(MATCH_TIER), MAX(MATCH_TIER) FROM LIBRARY_MARTS.CORE.XWALK_HOSPITAL_CCN_EIN;

-- [8] bridge fill checks
SELECT 'OP' t, COUNT(*) n, COUNT_IF(TRIM(CCN)<>'') ccn_rows, COUNT(DISTINCT NULLIF(TRIM(CCN),'')) d_ccn, COUNT_IF(TRIM(TEACHING_HOSPITAL_NAME)<>'') th_rows FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_OPEN_PAYMENTS
UNION ALL SELECT 'OP22', COUNT(*), COUNT_IF(TRIM(CCN)<>''), COUNT(DISTINCT NULLIF(TRIM(CCN),'')), COUNT_IF(TRIM(TEACHING_HOSPITAL_NAME)<>'') FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_OPEN_PAYMENTS_2022
UNION ALL SELECT 'OP23', COUNT(*), COUNT_IF(TRIM(CCN)<>''), COUNT(DISTINCT NULLIF(TRIM(CCN),'')), COUNT_IF(TRIM(TEACHING_HOSPITAL_NAME)<>'') FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_OPEN_PAYMENTS_2023;

-- [9] bridge fill checks
SELECT '23' y, COUNT(*) n, COUNT(DISTINCT EIN) d_ein, COUNT_IF(REGEXP_LIKE(TRIM(EIN),'^[0-9]{9}$') AND TRIM(EIN)<>'000000000') ein9_rows, COUNT(DISTINCT CASE WHEN REGEXP_LIKE(TRIM(EIN),'^[0-9]{8,9}$') AND TRY_TO_NUMBER(EIN)>0 THEN LPAD(TRIM(EIN),9,'0') END) d_ein_clean, COUNT(DISTINCT ESTABLISHMENT_ID) d_est FROM LIBRARY_MARTS.LABOR.LABOR__FED_OSHA_ITA_CASE_DETAIL_2023
UNION ALL SELECT '24', COUNT(*), COUNT(DISTINCT EIN), COUNT_IF(REGEXP_LIKE(TRIM(EIN),'^[0-9]{9}$') AND TRIM(EIN)<>'000000000'), COUNT(DISTINCT CASE WHEN REGEXP_LIKE(TRIM(EIN),'^[0-9]{8,9}$') AND TRY_TO_NUMBER(EIN)>0 THEN LPAD(TRIM(EIN),9,'0') END), COUNT(DISTINCT ESTABLISHMENT_ID) FROM LIBRARY_MARTS.LABOR.LABOR__FED_OSHA_ITA_CASE_DETAIL_2024;

-- [10] XC bridge -> air emissions land rate (shared by 4 UEI hops)
SELECT * FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_AIR_EMISSIONS_POLL_RPT_COMBINED_EMISSIONS LIMIT 5;

-- [11] XC bridge -> air emissions land rate (shared by 4 UEI hops)
WITH e AS (SELECT REGISTRY_ID::VARCHAR r, COUNT(*) n, COUNT_IF(TRIM(POLLUTANT_NAME)<>'') np, MIN(REPORTING_YEAR) y0, MAX(REPORTING_YEAR) y1 FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_AIR_EMISSIONS_POLL_RPT_COMBINED_EMISSIONS GROUP BY 1),
x AS (SELECT EPA_REGISTRY_ID::VARCHAR r, TRIM(PARENT_UEI) u FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__XC_EPA_CORPORATE_CROSSWALK WHERE TRIM(PARENT_UEI)<>'')
SELECT (SELECT COUNT(*) FROM e) air_facilities, (SELECT SUM(n) FROM e) air_rows, (SELECT SUM(np)/SUM(n) FROM e) pollutant_fill, (SELECT MIN(y0)||'-'||MAX(y1) FROM e) yrs,
 COUNT(*) xc_uei_rows, COUNT(DISTINCT x.u) xc_d_uei, COUNT(e.r) xc_rows_in_air, COUNT(DISTINCT CASE WHEN e.r IS NOT NULL THEN x.u END) uei_reaching_air, SUM(e.n) air_rows_matched, SUM(e.np)/NULLIF(SUM(e.n),0) pollutant_fill_matched
FROM x LEFT JOIN e ON e.r=x.r;

-- [12] UEI hop land rate A -> XC -> air, dollars matched vs not
WITH a AS (SELECT TRIM(RECIPIENT_UEI) u, MAX(TRIM(RECIPIENT_PARENT_UEI)) pu, COUNT(*) n, SUM(TRY_TO_DOUBLE(FEDERAL_ACTION_OBLIGATION::VARCHAR)) usd, MIN(ACTION_DATE::VARCHAR) d0, MAX(ACTION_DATE::VARCHAR) d1 FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_USASPENDING_CONTRACTS GROUP BY 1),
x AS (SELECT TRIM(PARENT_UEI) u, COUNT(*) fac FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__XC_EPA_CORPORATE_CROSSWALK WHERE TRIM(PARENT_UEI)<>'' GROUP BY 1),
xa AS (SELECT DISTINCT TRIM(x.PARENT_UEI) u FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__XC_EPA_CORPORATE_CROSSWALK x JOIN (SELECT DISTINCT REGISTRY_ID::VARCHAR r FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_AIR_EMISSIONS_POLL_RPT_COMBINED_EMISSIONS) e ON e.r=x.EPA_REGISTRY_ID::VARCHAR WHERE TRIM(x.PARENT_UEI)<>'')
SELECT 'ECONOMICS__FED_USASPENDING_CONTRACTS' t, SUM(a.n) rows_, COUNT_IF(a.u<>'') d_uei, SUM(CASE WHEN a.u<>'' THEN a.n END) rows_with_uei, MIN(a.d0) d0, MAX(a.d1) d1,
 COUNT_IF(x.u IS NOT NULL) uei_reach_bridge, COUNT_IF(xa.u IS NOT NULL) uei_reach_air,
 COUNT_IF(x.u IS NULL AND a.pu IN (SELECT u FROM x)) extra_via_parent_uei,
 SUM(CASE WHEN xa.u IS NOT NULL THEN a.usd END) usd_matched_air, SUM(CASE WHEN xa.u IS NULL THEN a.usd END) usd_unmatched,
 MEDIAN(CASE WHEN xa.u IS NOT NULL THEN a.usd END) med_usd_matched, MEDIAN(CASE WHEN xa.u IS NULL AND a.u<>'' THEN a.usd END) med_usd_unmatched
FROM a LEFT JOIN x ON x.u=a.u LEFT JOIN xa ON xa.u=a.u;

-- [13] UEI hop land rate A -> XC -> air, dollars matched vs not
WITH a AS (SELECT TRIM(RECIPIENT_UEI) u, MAX(TRIM(RECIPIENT_PARENT_UEI)) pu, COUNT(*) n, SUM(TRY_TO_DOUBLE(FEDERAL_ACTION_OBLIGATION::VARCHAR)) usd, MIN(ACTION_DATE::VARCHAR) d0, MAX(ACTION_DATE::VARCHAR) d1 FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_USASPENDING_CONTRACTS_FULL GROUP BY 1),
x AS (SELECT TRIM(PARENT_UEI) u, COUNT(*) fac FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__XC_EPA_CORPORATE_CROSSWALK WHERE TRIM(PARENT_UEI)<>'' GROUP BY 1),
xa AS (SELECT DISTINCT TRIM(x.PARENT_UEI) u FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__XC_EPA_CORPORATE_CROSSWALK x JOIN (SELECT DISTINCT REGISTRY_ID::VARCHAR r FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_AIR_EMISSIONS_POLL_RPT_COMBINED_EMISSIONS) e ON e.r=x.EPA_REGISTRY_ID::VARCHAR WHERE TRIM(x.PARENT_UEI)<>'')
SELECT 'ECONOMICS__FED_USASPENDING_CONTRACTS_FULL' t, SUM(a.n) rows_, COUNT_IF(a.u<>'') d_uei, SUM(CASE WHEN a.u<>'' THEN a.n END) rows_with_uei, MIN(a.d0) d0, MAX(a.d1) d1,
 COUNT_IF(x.u IS NOT NULL) uei_reach_bridge, COUNT_IF(xa.u IS NOT NULL) uei_reach_air,
 COUNT_IF(x.u IS NULL AND a.pu IN (SELECT u FROM x)) extra_via_parent_uei,
 SUM(CASE WHEN xa.u IS NOT NULL THEN a.usd END) usd_matched_air, SUM(CASE WHEN xa.u IS NULL THEN a.usd END) usd_unmatched,
 MEDIAN(CASE WHEN xa.u IS NOT NULL THEN a.usd END) med_usd_matched, MEDIAN(CASE WHEN xa.u IS NULL AND a.u<>'' THEN a.usd END) med_usd_unmatched
FROM a LEFT JOIN x ON x.u=a.u LEFT JOIN xa ON xa.u=a.u;

-- [14] UEI hop land rate A -> XC -> air, dollars matched vs not
WITH a AS (SELECT TRIM(RECIPIENT_UEI) u, MAX(TRIM(RECIPIENT_PARENT_UEI)) pu, COUNT(*) n, SUM(TRY_TO_DOUBLE(FEDERAL_ACTION_OBLIGATION::VARCHAR)) usd, MIN(ACTION_DATE::VARCHAR) d0, MAX(ACTION_DATE::VARCHAR) d1 FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_USASPENDING_CONTRACTS_FULL_R2 GROUP BY 1),
x AS (SELECT TRIM(PARENT_UEI) u, COUNT(*) fac FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__XC_EPA_CORPORATE_CROSSWALK WHERE TRIM(PARENT_UEI)<>'' GROUP BY 1),
xa AS (SELECT DISTINCT TRIM(x.PARENT_UEI) u FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__XC_EPA_CORPORATE_CROSSWALK x JOIN (SELECT DISTINCT REGISTRY_ID::VARCHAR r FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_AIR_EMISSIONS_POLL_RPT_COMBINED_EMISSIONS) e ON e.r=x.EPA_REGISTRY_ID::VARCHAR WHERE TRIM(x.PARENT_UEI)<>'')
SELECT 'ECONOMICS__FED_USASPENDING_CONTRACTS_FULL_R2' t, SUM(a.n) rows_, COUNT_IF(a.u<>'') d_uei, SUM(CASE WHEN a.u<>'' THEN a.n END) rows_with_uei, MIN(a.d0) d0, MAX(a.d1) d1,
 COUNT_IF(x.u IS NOT NULL) uei_reach_bridge, COUNT_IF(xa.u IS NOT NULL) uei_reach_air,
 COUNT_IF(x.u IS NULL AND a.pu IN (SELECT u FROM x)) extra_via_parent_uei,
 SUM(CASE WHEN xa.u IS NOT NULL THEN a.usd END) usd_matched_air, SUM(CASE WHEN xa.u IS NULL THEN a.usd END) usd_unmatched,
 MEDIAN(CASE WHEN xa.u IS NOT NULL THEN a.usd END) med_usd_matched, MEDIAN(CASE WHEN xa.u IS NULL AND a.u<>'' THEN a.usd END) med_usd_unmatched
FROM a LEFT JOIN x ON x.u=a.u LEFT JOIN xa ON xa.u=a.u;

-- [15] UEI hop land rate A -> XC -> air, dollars matched vs not
WITH a AS (SELECT TRIM(RECIPIENT_UEI) u, MAX(TRIM(RECIPIENT_PARENT_UEI)) pu, COUNT(*) n, SUM(TRY_TO_DOUBLE(FEDERAL_ACTION_OBLIGATION::VARCHAR)) usd, MIN(ACTION_DATE::VARCHAR) d0, MAX(ACTION_DATE::VARCHAR) d1 FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_USASPENDING_ASSISTANCE_FULL GROUP BY 1),
x AS (SELECT TRIM(PARENT_UEI) u, COUNT(*) fac FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__XC_EPA_CORPORATE_CROSSWALK WHERE TRIM(PARENT_UEI)<>'' GROUP BY 1),
xa AS (SELECT DISTINCT TRIM(x.PARENT_UEI) u FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__XC_EPA_CORPORATE_CROSSWALK x JOIN (SELECT DISTINCT REGISTRY_ID::VARCHAR r FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_AIR_EMISSIONS_POLL_RPT_COMBINED_EMISSIONS) e ON e.r=x.EPA_REGISTRY_ID::VARCHAR WHERE TRIM(x.PARENT_UEI)<>'')
SELECT 'ECONOMICS__FED_USASPENDING_ASSISTANCE_FULL' t, SUM(a.n) rows_, COUNT_IF(a.u<>'') d_uei, SUM(CASE WHEN a.u<>'' THEN a.n END) rows_with_uei, MIN(a.d0) d0, MAX(a.d1) d1,
 COUNT_IF(x.u IS NOT NULL) uei_reach_bridge, COUNT_IF(xa.u IS NOT NULL) uei_reach_air,
 COUNT_IF(x.u IS NULL AND a.pu IN (SELECT u FROM x)) extra_via_parent_uei,
 SUM(CASE WHEN xa.u IS NOT NULL THEN a.usd END) usd_matched_air, SUM(CASE WHEN xa.u IS NULL THEN a.usd END) usd_unmatched,
 MEDIAN(CASE WHEN xa.u IS NOT NULL THEN a.usd END) med_usd_matched, MEDIAN(CASE WHEN xa.u IS NULL AND a.u<>'' THEN a.usd END) med_usd_unmatched
FROM a LEFT JOIN x ON x.u=a.u LEFT JOIN xa ON xa.u=a.u;

-- [16] XC UEI hop: 20-row name agreement sample
WITH x AS (SELECT TRIM(PARENT_UEI) u, EPA_REGISTRY_ID::VARCHAR r, FACILITY_NAME FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__XC_EPA_CORPORATE_CROSSWALK WHERE TRIM(PARENT_UEI)<>'' AND EPA_REGISTRY_ID::VARCHAR IN (SELECT DISTINCT REGISTRY_ID::VARCHAR FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_AIR_EMISSIONS_POLL_RPT_COMBINED_EMISSIONS)),
a AS (SELECT TRIM(RECIPIENT_UEI) u, MAX(RECIPIENT_NAME) nm, MAX(RECIPIENT_PARENT_NAME) pnm, MAX(RECIPIENT_STATE_CODE) st FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_USASPENDING_CONTRACTS WHERE TRIM(RECIPIENT_UEI) IN (SELECT u FROM x) GROUP BY 1)
SELECT a.u, a.nm, a.pnm, a.st, x.FACILITY_NAME, x.r FROM a JOIN x ON x.u=a.u QUALIFY ROW_NUMBER() OVER (PARTITION BY a.u ORDER BY x.r)=1 ORDER BY HASH(a.u) LIMIT 20;

-- [17] XC UEI hop: 20-row name agreement sample
SELECT COUNT(*) n, COUNT(DISTINCT TRIM(PARENT_UEI)) d_uei, COUNT(DISTINCT EPA_REGISTRY_ID) d_fac, MAX(c) max_fac_per_uei FROM (SELECT PARENT_UEI, EPA_REGISTRY_ID, COUNT(*) OVER (PARTITION BY PARENT_UEI) c FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__XC_EPA_CORPORATE_CROSSWALK WHERE TRIM(PARENT_UEI)<>'');

-- [18] CCN hop: Open Payments -> XWALK -> OSHA 2023
SELECT 'HEALTH__FED_CMS_OPEN_PAYMENTS_2022' t, COUNT(*) d_ccn, SUM(n) rows_, COUNT(xw.CCN) ccn_reach_xwalk, COUNT(DISTINCT CASE WHEN o.e IS NOT NULL THEN op.c END) ccn_reach_osha23,
 SUM(CASE WHEN o.e IS NOT NULL THEN usd END) usd_matched, SUM(CASE WHEN o.e IS NULL THEN usd END) usd_unmatched,
 MEDIAN(CASE WHEN o.e IS NOT NULL THEN usd END) med_matched, MEDIAN(CASE WHEN o.e IS NULL THEN usd END) med_unmatched, MIN(y0), MAX(y1)
FROM (SELECT TRIM(CCN) c, COUNT(*) n, SUM(TRY_TO_DOUBLE(TOTAL_AMOUNT_OF_PAYMENT_USDOLLARS::VARCHAR)) usd, MIN(PROGRAM_YEAR) y0, MAX(PROGRAM_YEAR) y1 FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_OPEN_PAYMENTS_2022 WHERE TRIM(CCN)<>'' GROUP BY 1) op
LEFT JOIN LIBRARY_MARTS.CORE.XWALK_HOSPITAL_CCN_EIN xw ON TRIM(xw.CCN)=op.c
LEFT JOIN (SELECT DISTINCT LPAD(TRIM(EIN),9,'0') e FROM LIBRARY_MARTS.LABOR.LABOR__FED_OSHA_ITA_CASE_DETAIL_2023 WHERE REGEXP_LIKE(TRIM(EIN),'^[0-9]{8,9}$') AND TRY_TO_NUMBER(EIN)>0) o ON o.e=LPAD(TRIM(xw.EIN),9,'0');

-- [19] CCN hop: Open Payments -> XWALK -> OSHA 2023
SELECT 'HEALTH__FED_CMS_OPEN_PAYMENTS_2023' t, COUNT(*) d_ccn, SUM(n) rows_, COUNT(xw.CCN) ccn_reach_xwalk, COUNT(DISTINCT CASE WHEN o.e IS NOT NULL THEN op.c END) ccn_reach_osha23,
 SUM(CASE WHEN o.e IS NOT NULL THEN usd END) usd_matched, SUM(CASE WHEN o.e IS NULL THEN usd END) usd_unmatched,
 MEDIAN(CASE WHEN o.e IS NOT NULL THEN usd END) med_matched, MEDIAN(CASE WHEN o.e IS NULL THEN usd END) med_unmatched, MIN(y0), MAX(y1)
FROM (SELECT TRIM(CCN) c, COUNT(*) n, SUM(TRY_TO_DOUBLE(TOTAL_AMOUNT_OF_PAYMENT_USDOLLARS::VARCHAR)) usd, MIN(PROGRAM_YEAR) y0, MAX(PROGRAM_YEAR) y1 FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_OPEN_PAYMENTS_2023 WHERE TRIM(CCN)<>'' GROUP BY 1) op
LEFT JOIN LIBRARY_MARTS.CORE.XWALK_HOSPITAL_CCN_EIN xw ON TRIM(xw.CCN)=op.c
LEFT JOIN (SELECT DISTINCT LPAD(TRIM(EIN),9,'0') e FROM LIBRARY_MARTS.LABOR.LABOR__FED_OSHA_ITA_CASE_DETAIL_2023 WHERE REGEXP_LIKE(TRIM(EIN),'^[0-9]{8,9}$') AND TRY_TO_NUMBER(EIN)>0) o ON o.e=LPAD(TRIM(xw.EIN),9,'0');

-- [20] CCN hop: Open Payments -> XWALK -> OSHA 2023
SELECT 'HEALTH__FED_CMS_OPEN_PAYMENTS' t, COUNT(*) d_ccn, SUM(n) rows_, COUNT(xw.CCN) ccn_reach_xwalk, COUNT(DISTINCT CASE WHEN o.e IS NOT NULL THEN op.c END) ccn_reach_osha23,
 SUM(CASE WHEN o.e IS NOT NULL THEN usd END) usd_matched, SUM(CASE WHEN o.e IS NULL THEN usd END) usd_unmatched,
 MEDIAN(CASE WHEN o.e IS NOT NULL THEN usd END) med_matched, MEDIAN(CASE WHEN o.e IS NULL THEN usd END) med_unmatched, MIN(y0), MAX(y1)
FROM (SELECT TRIM(CCN) c, COUNT(*) n, SUM(TRY_TO_DOUBLE(TOTAL_AMOUNT_OF_PAYMENT_USDOLLARS::VARCHAR)) usd, MIN(PROGRAM_YEAR) y0, MAX(PROGRAM_YEAR) y1 FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_OPEN_PAYMENTS WHERE TRIM(CCN)<>'' GROUP BY 1) op
LEFT JOIN LIBRARY_MARTS.CORE.XWALK_HOSPITAL_CCN_EIN xw ON TRIM(xw.CCN)=op.c
LEFT JOIN (SELECT DISTINCT LPAD(TRIM(EIN),9,'0') e FROM LIBRARY_MARTS.LABOR.LABOR__FED_OSHA_ITA_CASE_DETAIL_2023 WHERE REGEXP_LIKE(TRIM(EIN),'^[0-9]{8,9}$') AND TRY_TO_NUMBER(EIN)>0) o ON o.e=LPAD(TRIM(xw.EIN),9,'0');

-- [21] CCN hop: Open Payments -> XWALK -> OSHA 2023
WITH o AS (SELECT LPAD(TRIM(EIN),9,'0') e, COUNT(*) cases, COUNT(DISTINCT ESTABLISHMENT_ID) sites, MAX(COMPANY_NAME) co, MAX(ESTABLISHMENT_NAME) est, MAX(LEFT(ZIP_CODE,5)) zip, MEDIAN(TRY_TO_DOUBLE(ANNUAL_AVERAGE_EMPLOYEES::VARCHAR)) med_emp FROM LIBRARY_MARTS.LABOR.LABOR__FED_OSHA_ITA_CASE_DETAIL_2023 WHERE REGEXP_LIKE(TRIM(EIN),'^[0-9]{8,9}$') AND TRY_TO_NUMBER(EIN)>0 GROUP BY 1)
SELECT xw.CCN, xw.CCN_NAME, xw.CCN_ZIP5, xw.EIN_NAME, o.co, o.est, o.zip, o.cases, o.sites, xw.MATCH_TIER FROM LIBRARY_MARTS.CORE.XWALK_HOSPITAL_CCN_EIN xw JOIN o ON o.e=LPAD(TRIM(xw.EIN),9,'0') ORDER BY HASH(xw.CCN) LIMIT 20;

-- [22] CCN hop: Open Payments -> XWALK -> OSHA 2023
WITH o AS (SELECT LPAD(TRIM(EIN),9,'0') e, ESTABLISHMENT_ID, MAX(TRY_TO_DOUBLE(ANNUAL_AVERAGE_EMPLOYEES::VARCHAR)) emp FROM LIBRARY_MARTS.LABOR.LABOR__FED_OSHA_ITA_CASE_DETAIL_2023 WHERE REGEXP_LIKE(TRIM(EIN),'^[0-9]{8,9}$') AND TRY_TO_NUMBER(EIN)>0 GROUP BY 1,2)
SELECT (o.e IN (SELECT LPAD(TRIM(EIN),9,'0') FROM LIBRARY_MARTS.CORE.XWALK_HOSPITAL_CCN_EIN)) in_xwalk, COUNT(*) sites, COUNT(DISTINCT e) eins, MEDIAN(emp) med_emp FROM o GROUP BY 1;

-- [23] NPI harm tables: profile
SELECT NPI, LAST_NAME, FIRST_NAME, BUSINESS_NAME, EXCLUSION_TYPE, EXCLUSION_DATE, REINSTATEMENT_DATE, NPI_IS_REAL, STATE FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_HHS_OIG_LEIE LIMIT 5;

-- [24] NPI harm tables: profile
SELECT 'LEIE' t, COUNT(*) n, COUNT_IF(REGEXP_LIKE(TRIM(NPI),'^[0-9]{10}$') AND TRIM(NPI)<>'0000000000') npi_ok, COUNT(DISTINCT CASE WHEN REGEXP_LIKE(TRIM(NPI),'^[0-9]{10}$') AND TRIM(NPI)<>'0000000000' THEN TRIM(NPI) END) d_npi, COUNT_IF(NPI_IS_REAL::VARCHAR ILIKE 'true') npi_is_real, MIN(EXCLUSION_DATE::VARCHAR) mn, MAX(EXCLUSION_DATE::VARCHAR) mx FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_HHS_OIG_LEIE
UNION ALL SELECT 'SAMP', COUNT(*), COUNT_IF(REGEXP_LIKE(TRIM(NPI),'^[0-9]{10}$') AND TRIM(NPI)<>'0000000000'), COUNT(DISTINCT CASE WHEN REGEXP_LIKE(TRIM(NPI),'^[0-9]{10}$') AND TRIM(NPI)<>'0000000000' THEN TRIM(NPI) END), COUNT_IF(REGEXP_LIKE(TRIM(SAM_NPI),'^[0-9]{10}$')), MIN(ACTIVATION_DATE::VARCHAR), MAX(ACTIVATION_DATE::VARCHAR) FROM LIBRARY_MARTS.HEALTH.HEALTH__SAM_EXCLUDED_PROVIDERS
UNION ALL SELECT 'FQHC', COUNT(*), COUNT_IF(REGEXP_LIKE(TRIM(NPI),'^[0-9]{10}$')), COUNT(DISTINCT NPI), COUNT_IF(IS_EXCLUDED::VARCHAR ILIKE 'true'), MIN(EXCLUSION_DATE::VARCHAR), MAX(EXCLUSION_DATE::VARCHAR) FROM LIBRARY_MARTS.HEALTH.HEALTH__FQHC_SITE_PEOPLE
UNION ALL SELECT 'SAMX', COUNT(*), COUNT_IF(REGEXP_LIKE(TRIM(NPI),'^[0-9]{10}$') AND TRIM(NPI)<>'0000000000'), COUNT(DISTINCT CASE WHEN REGEXP_LIKE(TRIM(NPI),'^[0-9]{10}$') AND TRIM(NPI)<>'0000000000' THEN TRIM(NPI) END), COUNT(DISTINCT NULLIF(TRIM(UEI),'')), MIN(ACTIVATION_DATE::VARCHAR), MAX(ACTIVATION_DATE::VARCHAR) FROM LIBRARY_MARTS.PROCUREMENT.PROCUREMENT__FED_SAM_EXCLUSIONS;

-- [25] NPI harm tables: profile
SELECT MATCH_METHOD, COUNT(*) n, COUNT(DISTINCT NPI) d FROM LIBRARY_MARTS.HEALTH.HEALTH__SAM_EXCLUDED_PROVIDERS GROUP BY 1 ORDER BY 2 DESC LIMIT 10;

-- [26] NPI harm tables: profile
SELECT COUNT(*) n, COUNT(DISTINCT NULLIF(TRIM(UEI),'')) d_uei, COUNT_IF(TRIM(UEI)<>'') uei_rows, COUNT_IF(IS_CURRENTLY_EXCLUDED::VARCHAR ILIKE 'true') cur FROM LIBRARY_MARTS.HEALTH.HEALTH__SAM_EXCLUDED_PROVIDERS;

-- [27] R:NPI:worst overlap
WITH l AS (SELECT DISTINCT TRIM(NPI) npi FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_HHS_OIG_LEIE WHERE REGEXP_LIKE(TRIM(NPI),'^[0-9]{10}$') AND TRIM(NPI)<>'0000000000'),
s AS (SELECT DISTINCT TRIM(NPI) npi FROM LIBRARY_MARTS.HEALTH.HEALTH__SAM_EXCLUDED_PROVIDERS WHERE REGEXP_LIKE(TRIM(NPI),'^[0-9]{10}$') AND TRIM(NPI)<>'0000000000'),
f AS (SELECT DISTINCT TRIM(NPI) npi FROM LIBRARY_MARTS.HEALTH.HEALTH__FQHC_SITE_PEOPLE WHERE REGEXP_LIKE(TRIM(NPI),'^[0-9]{10}$')),
fx AS (SELECT DISTINCT TRIM(NPI) npi FROM LIBRARY_MARTS.HEALTH.HEALTH__FQHC_SITE_PEOPLE WHERE IS_EXCLUDED::VARCHAR ILIKE 'true'),
u AS (SELECT npi FROM l UNION SELECT npi FROM s UNION SELECT npi FROM f)
SELECT (l.npi IS NOT NULL)::INT in_leie, (s.npi IS NOT NULL)::INT in_samprov, (f.npi IS NOT NULL)::INT in_fqhc, (fx.npi IS NOT NULL)::INT fqhc_excl_flag, COUNT(*) npis
FROM u LEFT JOIN l ON l.npi=u.npi LEFT JOIN s ON s.npi=u.npi LEFT JOIN f ON f.npi=u.npi LEFT JOIN fx ON fx.npi=u.npi GROUP BY 1,2,3,4 ORDER BY 5 DESC;

-- [28] R:NPI:worst overlap
WITH l AS (SELECT TRIM(NPI) npi, MAX(LAST_NAME) ln, MAX(FIRST_NAME) fn, MAX(EXCLUSION_TYPE) et, MIN(EXCLUSION_DATE) ed, MAX(STATE) st FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_HHS_OIG_LEIE WHERE REGEXP_LIKE(TRIM(NPI),'^[0-9]{10}$') AND TRIM(NPI)<>'0000000000' GROUP BY 1),
s AS (SELECT TRIM(NPI) npi, MAX(LAST_NAME) ln, MAX(FIRST_NAME) fn, MAX(EXCLUDING_AGENCY) ag, MIN(ACTIVATION_DATE) ad FROM LIBRARY_MARTS.HEALTH.HEALTH__SAM_EXCLUDED_PROVIDERS WHERE REGEXP_LIKE(TRIM(NPI),'^[0-9]{10}$') AND TRIM(NPI)<>'0000000000' GROUP BY 1),
f AS (SELECT TRIM(NPI) npi, MAX(LAST_NAME) ln, MAX(HEALTH_CENTER_NAME) hc, MAX(IS_EXCLUDED::VARCHAR) ix FROM LIBRARY_MARTS.HEALTH.HEALTH__FQHC_SITE_PEOPLE GROUP BY 1)
SELECT COALESCE(l.npi,s.npi) npi, l.ln, l.fn, l.et, l.ed, l.st, s.ln s_ln, s.fn s_fn, s.ag, s.ad, f.ln f_ln, f.hc, f.ix FROM l FULL JOIN s ON s.npi=l.npi LEFT JOIN f ON f.npi=COALESCE(l.npi,s.npi)
WHERE (l.npi IS NOT NULL)::INT+(s.npi IS NOT NULL)::INT+(f.npi IS NOT NULL)::INT>=2 ORDER BY (l.npi IS NOT NULL)::INT+(s.npi IS NOT NULL)::INT+(f.npi IS NOT NULL)::INT DESC, l.ed LIMIT 25;

-- [29] R:NPI:harm-money: excluded NPIs paid by Part B
SELECT * FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_MEDICARE_PHYSICIAN_OTHER_PRACTITIONERS_BY_PROVIDER LIMIT 2;

-- [30] R:NPI:harm-money: excluded NPIs paid by Part B
WITH h AS (SELECT TRIM(NPI) npi, 'LEIE' src, MAX(LAST_NAME) ln, MAX(FIRST_NAME) fn, MIN(EXCLUSION_DATE) ed, MAX(EXCLUSION_TYPE) et FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_HHS_OIG_LEIE WHERE REGEXP_LIKE(TRIM(NPI),'^[0-9]{10}$') AND TRIM(NPI)<>'0000000000' GROUP BY 1
  UNION ALL SELECT TRIM(NPI), 'SAMPROV', MAX(LAST_NAME), MAX(FIRST_NAME), MIN(ACTIVATION_DATE), MAX(EXCLUDING_AGENCY) FROM LIBRARY_MARTS.HEALTH.HEALTH__SAM_EXCLUDED_PROVIDERS WHERE REGEXP_LIKE(TRIM(NPI),'^[0-9]{10}$') AND TRIM(NPI)<>'0000000000' GROUP BY 1),
b AS (SELECT TRIM(RNDRNG_NPI::VARCHAR) npi, MAX(RNDRNG_PRVDR_LAST_ORG_NAME) bln, MAX(RNDRNG_PRVDR_FIRST_NAME) bfn, SUM(TRY_TO_DOUBLE(TOT_MDCR_PYMT_AMT::VARCHAR)) pay FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_MEDICARE_PHYSICIAN_OTHER_PRACTITIONERS_BY_PROVIDER GROUP BY 1)
SELECT h.src, CASE WHEN h.ed < '2024-01-01' THEN 'excluded_before_2024' ELSE 'excluded_2024_or_later' END timing, COUNT(*) harm_npis, COUNT(b.npi) paid_2024, COUNT_IF(b.npi IS NOT NULL AND UPPER(b.bln)=UPPER(h.ln)) lastname_agrees, SUM(b.pay) pay_2024, MEDIAN(b.pay) med_pay
FROM h LEFT JOIN b ON b.npi=h.npi GROUP BY 1,2 ORDER BY 1,2;

-- [31] R:NPI:harm-money: excluded NPIs paid by Part B
SELECT COUNT(*) all_npis, SUM(TRY_TO_DOUBLE(TOT_MDCR_PYMT_AMT::VARCHAR)) all_pay, MEDIAN(TRY_TO_DOUBLE(TOT_MDCR_PYMT_AMT::VARCHAR)) med_pay FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_MEDICARE_PHYSICIAN_OTHER_PRACTITIONERS_BY_PROVIDER;

-- [32] R:NPI:harm-money: top excluded-then-paid, by agency and termination
WITH s AS (SELECT TRIM(NPI) npi, MAX(LAST_NAME) ln, MAX(FIRST_NAME) fn, MAX(STATE) st, MAX(CITY) city, MAX(EXCLUDING_AGENCY) ag, MAX(EXCLUSION_TYPE) et, MAX(EXCLUSION_PROGRAM) ep, MIN(ACTIVATION_DATE) ad, MAX(TERMINATION_DATE_RAW) td, MAX(MATCH_METHOD) mm, MAX(MATCH_NOTE) mn, MAX(CLASSIFICATION) cl FROM LIBRARY_MARTS.HEALTH.HEALTH__SAM_EXCLUDED_PROVIDERS WHERE REGEXP_LIKE(TRIM(NPI),'^[0-9]{10}$') AND TRIM(NPI)<>'0000000000' GROUP BY 1
  UNION ALL SELECT TRIM(NPI), MAX(LAST_NAME), MAX(FIRST_NAME), MAX(STATE), MAX(CITY), 'OIG-LEIE', MAX(EXCLUSION_TYPE), NULL, MIN(EXCLUSION_DATE), MAX(REINSTATEMENT_DATE::VARCHAR), NULL, NULL, NULL FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_HHS_OIG_LEIE WHERE REGEXP_LIKE(TRIM(NPI),'^[0-9]{10}$') AND TRIM(NPI)<>'0000000000' GROUP BY 1 HAVING MIN(EXCLUSION_DATE)<'2024-01-01'),
b AS (SELECT TRIM(RNDRNG_NPI::VARCHAR) npi, MAX(RNDRNG_PRVDR_LAST_ORG_NAME) bln, MAX(RNDRNG_PRVDR_FIRST_NAME) bfn, MAX(RNDRNG_PRVDR_CITY) bcity, MAX(RNDRNG_PRVDR_STATE_ABRVTN) bst, MAX(RNDRNG_PRVDR_TYPE) btype, SUM(TRY_TO_DOUBLE(TOT_MDCR_PYMT_AMT::VARCHAR)) pay FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_MEDICARE_PHYSICIAN_OTHER_PRACTITIONERS_BY_PROVIDER GROUP BY 1)
SELECT s.*, b.bln, b.bfn, b.bcity, b.bst, b.btype, ROUND(b.pay) pay_2024 FROM s JOIN b ON b.npi=s.npi WHERE s.ad<'2024-01-01' ORDER BY b.pay DESC LIMIT 25;

-- [33] R:NPI:harm-money: top excluded-then-paid, by agency and termination
WITH s AS (SELECT TRIM(NPI) npi, MIN(ACTIVATION_DATE) ad, MAX(TERMINATION_DATE_RAW) td, MAX(EXCLUDING_AGENCY) ag, MAX(EXCLUSION_TYPE) et FROM LIBRARY_MARTS.HEALTH.HEALTH__SAM_EXCLUDED_PROVIDERS WHERE REGEXP_LIKE(TRIM(NPI),'^[0-9]{10}$') AND TRIM(NPI)<>'0000000000' GROUP BY 1 HAVING MIN(ACTIVATION_DATE)<'2024-01-01'),
b AS (SELECT DISTINCT TRIM(RNDRNG_NPI::VARCHAR) npi FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_MEDICARE_PHYSICIAN_OTHER_PRACTITIONERS_BY_PROVIDER)
SELECT s.ag, s.et, CASE WHEN s.td ILIKE 'indef%' THEN 'indefinite' WHEN TRY_TO_DATE(s.td) < '2024-01-01' THEN 'ended_before_2024' ELSE 'active_in_2024' END term, COUNT(*) npis, COUNT(b.npi) paid FROM s LEFT JOIN b ON b.npi=s.npi GROUP BY 1,2,3 ORDER BY 5 DESC LIMIT 20;

-- [34] R:NPI:harm-money: Miranda check, Part D 2022, Open Payments 2024
SELECT NPI, LAST_NAME, FIRST_NAME, SPECIALTY, GENERAL_CATEGORY, EXCLUSION_TYPE, EXCLUSION_DATE, HAS_WAIVER, ADDRESS, CITY, STATE, ZIP FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_HHS_OIG_LEIE WHERE TRIM(NPI)='1285673012' OR (LAST_NAME='MIRANDA' AND FIRST_NAME='EDUARDO');

-- [35] R:NPI:harm-money: Miranda check, Part D 2022, Open Payments 2024
WITH l AS (SELECT TRIM(NPI) npi, MAX(LAST_NAME) ln, MAX(CITY) city, MIN(EXCLUSION_DATE) ed, MAX(HAS_WAIVER::VARCHAR) w FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_HHS_OIG_LEIE WHERE REGEXP_LIKE(TRIM(NPI),'^[0-9]{10}$') AND TRIM(NPI)<>'0000000000' GROUP BY 1 HAVING MIN(EXCLUSION_DATE)<'2022-01-01'),
d AS (SELECT TRIM(NPI::VARCHAR) npi, MAX(PRESCRIBER_LAST_ORG_NAME) dln, SUM(TRY_TO_DOUBLE(TOTAL_DRUG_COST::VARCHAR)) cost, MIN(DATA_YEAR) y FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_PARTD_PRESCRIBERS WHERE TRIM(NPI::VARCHAR) IN (SELECT npi FROM l) GROUP BY 1)
SELECT l.npi, l.ln, l.city, l.ed, l.w, d.dln, d.y, ROUND(d.cost) partd_cost FROM l JOIN d ON d.npi=l.npi ORDER BY d.cost DESC LIMIT 15;

-- [36] R:NPI:harm-money: Miranda check, Part D 2022, Open Payments 2024
WITH l AS (SELECT TRIM(NPI) npi, MIN(EXCLUSION_DATE) ed FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_HHS_OIG_LEIE WHERE REGEXP_LIKE(TRIM(NPI),'^[0-9]{10}$') AND TRIM(NPI)<>'0000000000' GROUP BY 1 HAVING MIN(EXCLUSION_DATE)<'2024-01-01')
SELECT COUNT(DISTINCT TRIM(o.NPI)) npis_paid, COUNT(*) payments, SUM(TRY_TO_DOUBLE(o.TOTAL_AMOUNT_OF_PAYMENT_USDOLLARS::VARCHAR)) usd FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_OPEN_PAYMENTS o JOIN l ON l.npi=TRIM(o.NPI);

-- [37] R:UEI:worst overlap + exclusion mix
WITH a AS (SELECT DISTINCT TRIM(UEI) u FROM LIBRARY_MARTS.PROCUREMENT.PROCUREMENT__FED_SAM_EXCLUSIONS WHERE TRIM(UEI)<>''),
b AS (SELECT DISTINCT TRIM(UEI) u FROM LIBRARY_MARTS.HEALTH.HEALTH__SAM_EXCLUDED_PROVIDERS WHERE TRIM(UEI)<>''),
sn AS (SELECT COUNT(*) samprov_rows, COUNT_IF(SAM_NUMBER IN (SELECT SAM_NUMBER FROM LIBRARY_MARTS.PROCUREMENT.PROCUREMENT__FED_SAM_EXCLUSIONS)) samnum_in_samx FROM LIBRARY_MARTS.HEALTH.HEALTH__SAM_EXCLUDED_PROVIDERS)
SELECT (SELECT COUNT(*) FROM a) samx_uei, (SELECT COUNT(*) FROM b) samprov_uei, (SELECT COUNT(*) FROM a JOIN b USING (u)) both_, (SELECT samprov_rows FROM sn), (SELECT samnum_in_samx FROM sn);

-- [38] R:UEI:worst overlap + exclusion mix
SELECT CLASSIFICATION, EXCLUSION_TYPE, COUNT(*) n, COUNT(DISTINCT NULLIF(TRIM(UEI),'')) d_uei FROM LIBRARY_MARTS.PROCUREMENT.PROCUREMENT__FED_SAM_EXCLUSIONS GROUP BY 1,2 ORDER BY 3 DESC LIMIT 15;

-- [39] R:UEI:worst overlap + exclusion mix
SELECT TRIM(UEI) u, COUNT(*) n, COUNT(DISTINCT SAM_NUMBER) sams, MAX(ENTITY_NAME) nm FROM LIBRARY_MARTS.PROCUREMENT.PROCUREMENT__FED_SAM_EXCLUSIONS WHERE TRIM(UEI)<>'' GROUP BY 1 ORDER BY 2 DESC LIMIT 10;

-- [40] R:UEI:harm-money: contracts to excluded UEIs during exclusion (R2)
WITH x AS (SELECT TRIM(UEI) u, MIN(ACTIVATION_DATE) ad, MAX(COALESCE(TERMINATION_DATE, '2100-01-01'::DATE)) td, MAX(ENTITY_NAME) nm, MAX(CLASSIFICATION) cl, MAX(EXCLUDING_AGENCY) ag, MAX(EXCLUSION_TYPE) et FROM LIBRARY_MARTS.PROCUREMENT.PROCUREMENT__FED_SAM_EXCLUSIONS WHERE TRIM(UEI)<>'' GROUP BY 1),
r AS (SELECT TRIM(RECIPIENT_UEI) u, CONTRACT_AWARD_UNIQUE_KEY k, TRY_TO_DATE(ACTION_DATE::VARCHAR) dt, TRY_TO_DOUBLE(FEDERAL_ACTION_OBLIGATION::VARCHAR) usd, RECIPIENT_NAME rn, AWARDING_AGENCY_NAME aa FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_USASPENDING_CONTRACTS_FULL_R2 WHERE TRIM(RECIPIENT_UEI) IN (SELECT u FROM x)),
k AS (SELECT k, MIN(dt) k0 FROM r GROUP BY 1),
j AS (SELECT x.*, r.*, k.k0 FROM r JOIN x ON x.u=r.u JOIN k ON k.k=r.k WHERE r.dt>=x.ad AND r.dt<=x.td)
SELECT u, MAX(nm) sam_name, MAX(rn) usas_name, MAX(cl) cl, MAX(ag) ag, MAX(et) et, MIN(ad) excl_from, COUNT(*) actions_during, COUNT(DISTINCT k) awards, COUNT(DISTINCT CASE WHEN k0>=ad THEN k END) new_awards_after_excl, ROUND(SUM(usd)) usd_during, ROUND(SUM(CASE WHEN k0>=ad THEN usd END)) usd_new_awards, MAX(aa) agency, MIN(dt), MAX(dt)
FROM j GROUP BY u ORDER BY usd_new_awards DESC NULLS LAST LIMIT 20;

-- [41] R:UEI:harm-money: contracts to excluded UEIs during exclusion (R2)
WITH x AS (SELECT TRIM(UEI) u, MIN(ACTIVATION_DATE) ad, MAX(COALESCE(TERMINATION_DATE, '2100-01-01'::DATE)) td FROM LIBRARY_MARTS.PROCUREMENT.PROCUREMENT__FED_SAM_EXCLUSIONS WHERE TRIM(UEI)<>'' GROUP BY 1),
r AS (SELECT TRIM(RECIPIENT_UEI) u, CONTRACT_AWARD_UNIQUE_KEY k, TRY_TO_DATE(ACTION_DATE::VARCHAR) dt, TRY_TO_DOUBLE(FEDERAL_ACTION_OBLIGATION::VARCHAR) usd FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_USASPENDING_CONTRACTS_FULL_R2 WHERE TRIM(RECIPIENT_UEI) IN (SELECT u FROM x)),
k AS (SELECT k, MIN(dt) k0 FROM r GROUP BY 1)
SELECT COUNT(DISTINCT r.u) uei_ever_paid, COUNT(DISTINCT CASE WHEN r.dt BETWEEN x.ad AND x.td THEN r.u END) uei_paid_during, COUNT(DISTINCT CASE WHEN r.dt BETWEEN x.ad AND x.td AND k.k0>=x.ad THEN r.u END) uei_new_award_during, ROUND(SUM(CASE WHEN r.dt BETWEEN x.ad AND x.td THEN usd END)) usd_during, ROUND(SUM(CASE WHEN r.dt BETWEEN x.ad AND x.td AND k.k0>=x.ad THEN usd END)) usd_new_during, (SELECT COUNT(*) FROM x) excluded_uei
FROM r JOIN x ON x.u=r.u JOIN k ON k.k=r.k;

-- [42] R:UEI:harm-money: new awards after exclusion, top 20
WITH x AS (SELECT TRIM(UEI) xu, MIN(ACTIVATION_DATE) ad, MAX(COALESCE(TERMINATION_DATE, '2100-01-01'::DATE)) td, MAX(ENTITY_NAME) nm, MAX(CLASSIFICATION) cl, MAX(EXCLUDING_AGENCY) ag, MAX(EXCLUSION_TYPE) et FROM LIBRARY_MARTS.PROCUREMENT.PROCUREMENT__FED_SAM_EXCLUSIONS WHERE TRIM(UEI)<>'' GROUP BY 1),
r AS (SELECT TRIM(RECIPIENT_UEI) ru, CONTRACT_AWARD_UNIQUE_KEY k, TRY_TO_DATE(ACTION_DATE::VARCHAR) dt, TRY_TO_DOUBLE(FEDERAL_ACTION_OBLIGATION::VARCHAR) usd, RECIPIENT_NAME rn, AWARDING_AGENCY_NAME aa FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_USASPENDING_CONTRACTS_FULL_R2 WHERE TRIM(RECIPIENT_UEI) IN (SELECT xu FROM x)),
k AS (SELECT k kk, MIN(dt) k0 FROM r GROUP BY 1)
SELECT x.xu, MAX(x.nm) sam_name, MAX(r.rn) usas_name, MAX(x.cl) cl, MAX(x.ag) ag, MAX(x.et) et, MIN(x.ad) excl_from, MAX(x.td) excl_to, COUNT(DISTINCT r.k) new_awards, ROUND(SUM(r.usd)) usd_new, MAX(r.aa) agency, MIN(r.dt) d0, MAX(r.dt) d1
FROM r JOIN x ON x.xu=r.ru JOIN k ON k.kk=r.k WHERE r.dt BETWEEN x.ad AND x.td AND k.k0>=x.ad GROUP BY x.xu ORDER BY usd_new DESC NULLS LAST LIMIT 20;

-- [43] R:UEI:harm-money: assistance to excluded UEIs during exclusion (floor, 1M/yr cap)
WITH x AS (SELECT TRIM(UEI) xu, MIN(ACTIVATION_DATE) ad, MAX(COALESCE(TERMINATION_DATE, '2100-01-01'::DATE)) td, MAX(ENTITY_NAME) nm, MAX(CLASSIFICATION) cl, MAX(EXCLUDING_AGENCY) ag, MAX(EXCLUSION_TYPE) et FROM LIBRARY_MARTS.PROCUREMENT.PROCUREMENT__FED_SAM_EXCLUSIONS WHERE TRIM(UEI)<>'' GROUP BY 1),
r AS (SELECT TRIM(RECIPIENT_UEI) ru, TRY_TO_DATE(ACTION_DATE::VARCHAR) dt, TRY_TO_DOUBLE(FEDERAL_ACTION_OBLIGATION::VARCHAR) usd, RECIPIENT_NAME rn FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_USASPENDING_ASSISTANCE_FULL WHERE TRIM(RECIPIENT_UEI) IN (SELECT xu FROM x))
SELECT x.xu, MAX(x.nm) sam_name, MAX(r.rn) usas_name, MAX(x.cl) cl, MAX(x.ag) ag, MAX(x.et) et, MIN(x.ad) excl_from, COUNT(*) actions_during, ROUND(SUM(r.usd)) usd_during, MIN(r.dt), MAX(r.dt)
FROM r JOIN x ON x.xu=r.ru WHERE r.dt BETWEEN x.ad AND x.td GROUP BY x.xu ORDER BY usd_during DESC LIMIT 12;

-- [44] R:EIN: OSHA 300A + FAC profile
SELECT COUNT(*) n, COUNT_IF(REGEXP_LIKE(TRIM(EIN),'^[0-9]{8,9}$') AND TRY_TO_NUMBER(EIN)>0) ein_ok, COUNT(DISTINCT CASE WHEN REGEXP_LIKE(TRIM(EIN),'^[0-9]{8,9}$') AND TRY_TO_NUMBER(EIN)>0 THEN LPAD(TRIM(EIN),9,'0') END) d_ein, SUM(TRY_TO_NUMBER(TOTAL_DEATHS::VARCHAR)) deaths, MAX(TRY_TO_NUMBER(TOTAL_DEATHS::VARCHAR)) max_deaths, COUNT(DISTINCT TOTAL_DEATHS) d_vals, SUM(TRY_TO_NUMBER(TOTAL_INJURIES::VARCHAR)) inj FROM LIBRARY_MARTS.LABOR.LABOR__FED_OSHA_ITA_300A_SUMMARY_2024;

-- [45] R:EIN: OSHA 300A + FAC profile
SELECT LPAD(TRIM(EIN),9,'0') ein, COUNT(*) sites, COUNT(DISTINCT UPPER(COMPANY_NAME)) names, MAX(COMPANY_NAME) nm, MIN(COMPANY_NAME) nm2 FROM LIBRARY_MARTS.LABOR.LABOR__FED_OSHA_ITA_300A_SUMMARY_2024 WHERE REGEXP_LIKE(TRIM(EIN),'^[0-9]{8,9}$') AND TRY_TO_NUMBER(EIN)>0 GROUP BY 1 ORDER BY names DESC LIMIT 10;

-- [46] R:EIN: OSHA 300A + FAC profile
SELECT COUNT(*) n, COUNT(DISTINCT AUDITEE_EIN) d_ein, MIN(AUDIT_YEAR), MAX(AUDIT_YEAR), COUNT_IF(REGEXP_LIKE(TRIM(AUDITEE_EIN::VARCHAR),'^[0-9]{9}$')) ein9 FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_FAC_SINGLE_AUDIT;

-- [47] R:EIN:harm-money: OSHA harm EINs vs FAC single audit + hospital pay
WITH a AS (SELECT LPAD(TRIM(EIN),9,'0') e, COUNT(*) cases23, COUNT_IF(INCIDENT_OUTCOME::VARCHAR='1') deaths23, MAX(COMPANY_NAME) nm23 FROM LIBRARY_MARTS.LABOR.LABOR__FED_OSHA_ITA_CASE_DETAIL_2023 WHERE REGEXP_LIKE(TRIM(EIN),'^[0-9]{8,9}$') AND TRY_TO_NUMBER(EIN)>0 GROUP BY 1),
b AS (SELECT LPAD(TRIM(EIN),9,'0') e, COUNT(*) sites24, SUM(TRY_TO_NUMBER(TOTAL_DEATHS::VARCHAR)) deaths24, SUM(TRY_TO_NUMBER(TOTAL_INJURIES::VARCHAR)) inj24, MAX(COMPANY_NAME) nm24 FROM LIBRARY_MARTS.LABOR.LABOR__FED_OSHA_ITA_300A_SUMMARY_2024 WHERE REGEXP_LIKE(TRIM(EIN),'^[0-9]{8,9}$') AND TRY_TO_NUMBER(EIN)>0 GROUP BY 1),
f AS (SELECT LPAD(TRIM(AUDITEE_EIN::VARCHAR),9,'0') e, MAX(AUDITEE_NAME) fnm, MAX_BY(TRY_TO_DOUBLE(TOTAL_AMOUNT_EXPENDED::VARCHAR), AUDIT_YEAR) fed_exp_latest, MAX(AUDIT_YEAR) fy FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_FAC_SINGLE_AUDIT GROUP BY 1),
h AS (SELECT DISTINCT LPAD(TRIM(EIN::VARCHAR),9,'0') e FROM LIBRARY_MARTS.HEALTH.HEALTH__HOSPITAL_OFFICER_PAY),
u AS (SELECT e FROM a UNION SELECT e FROM b),
j AS (SELECT u.e, a.cases23, a.deaths23, b.sites24, b.deaths24, b.inj24, COALESCE(b.nm24,a.nm23) osha_name, f.fnm, f.fed_exp_latest, f.fy, (h.e IS NOT NULL) hosp, (a.e IS NOT NULL)::INT+(b.e IS NOT NULL)::INT n_harm FROM u LEFT JOIN a ON a.e=u.e LEFT JOIN b ON b.e=u.e LEFT JOIN f ON f.e=u.e LEFT JOIN h ON h.e=u.e)
SELECT 'summary' k, COUNT(*) eins, COUNT_IF(n_harm=2) in_both_harm, COUNT_IF(fnm IS NOT NULL) in_fac, COUNT_IF(hosp) in_hosp_pay, COUNT_IF(fnm IS NOT NULL AND COALESCE(deaths23,0)+COALESCE(deaths24,0)>0) fac_with_death, SUM(CASE WHEN fnm IS NOT NULL THEN fed_exp_latest END) fac_usd, NULL x1, NULL x2, NULL x3 FROM j
UNION ALL SELECT * FROM (SELECT e, cases23, deaths23, sites24, deaths24, inj24, osha_name, fnm, fed_exp_latest, fy FROM j WHERE fnm IS NOT NULL ORDER BY COALESCE(deaths23,0)+COALESCE(deaths24,0) DESC, inj24 DESC NULLS LAST LIMIT 15);

-- [48] R:EIN:harm-money: OSHA harm EINs vs FAC single audit + hospital pay
WITH a AS (SELECT LPAD(TRIM(EIN),9,'0') e, COUNT(*) cases23, COUNT_IF(INCIDENT_OUTCOME::VARCHAR='1') deaths23, MAX(COMPANY_NAME) nm23 FROM LIBRARY_MARTS.LABOR.LABOR__FED_OSHA_ITA_CASE_DETAIL_2023 WHERE REGEXP_LIKE(TRIM(EIN),'^[0-9]{8,9}$') AND TRY_TO_NUMBER(EIN)>0 GROUP BY 1),
b AS (SELECT LPAD(TRIM(EIN),9,'0') e, COUNT(*) sites24, SUM(TRY_TO_NUMBER(TOTAL_DEATHS::VARCHAR)) deaths24, SUM(TRY_TO_NUMBER(TOTAL_INJURIES::VARCHAR)) inj24, MAX(COMPANY_NAME) nm24 FROM LIBRARY_MARTS.LABOR.LABOR__FED_OSHA_ITA_300A_SUMMARY_2024 WHERE REGEXP_LIKE(TRIM(EIN),'^[0-9]{8,9}$') AND TRY_TO_NUMBER(EIN)>0 GROUP BY 1),
f AS (SELECT LPAD(TRIM(AUDITEE_EIN::VARCHAR),9,'0') e, MAX(AUDITEE_NAME) fnm, MAX_BY(TRY_TO_DOUBLE(TOTAL_AMOUNT_EXPENDED::VARCHAR), AUDIT_YEAR) fed_exp_latest, MAX(AUDIT_YEAR) fy FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_FAC_SINGLE_AUDIT GROUP BY 1),
h AS (SELECT DISTINCT LPAD(TRIM(EIN::VARCHAR),9,'0') e FROM LIBRARY_MARTS.HEALTH.HEALTH__HOSPITAL_OFFICER_PAY),
u AS (SELECT e FROM a UNION SELECT e FROM b),
j AS (SELECT u.e, a.cases23, a.deaths23, b.sites24, b.deaths24, b.inj24, COALESCE(b.nm24,a.nm23) osha_name, f.fnm, f.fed_exp_latest, f.fy, (h.e IS NOT NULL) hosp, (a.e IS NOT NULL)::INT+(b.e IS NOT NULL)::INT n_harm FROM u LEFT JOIN a ON a.e=u.e LEFT JOIN b ON b.e=u.e LEFT JOIN f ON f.e=u.e LEFT JOIN h ON h.e=u.e)
SELECT COUNT(*) eins, COUNT_IF(n_harm=2) in_both_harm, COUNT_IF(fnm IS NOT NULL) in_fac, COUNT_IF(hosp) in_hosp_pay, COUNT_IF(fnm IS NOT NULL AND COALESCE(deaths23,0)+COALESCE(deaths24,0)>0) fac_with_death, SUM(CASE WHEN fnm IS NOT NULL THEN fed_exp_latest END) fac_usd, COUNT_IF(COALESCE(deaths23,0)+COALESCE(deaths24,0)>0) eins_with_death FROM j;

-- [49] R:EIN:harm-money: OSHA harm EINs vs FAC single audit + hospital pay
WITH a AS (SELECT LPAD(TRIM(EIN),9,'0') e, COUNT(*) cases23, COUNT_IF(INCIDENT_OUTCOME::VARCHAR='1') deaths23, MAX(COMPANY_NAME) nm23 FROM LIBRARY_MARTS.LABOR.LABOR__FED_OSHA_ITA_CASE_DETAIL_2023 WHERE REGEXP_LIKE(TRIM(EIN),'^[0-9]{8,9}$') AND TRY_TO_NUMBER(EIN)>0 GROUP BY 1),
b AS (SELECT LPAD(TRIM(EIN),9,'0') e, COUNT(*) sites24, SUM(TRY_TO_NUMBER(TOTAL_DEATHS::VARCHAR)) deaths24, SUM(TRY_TO_NUMBER(TOTAL_INJURIES::VARCHAR)) inj24, MAX(COMPANY_NAME) nm24 FROM LIBRARY_MARTS.LABOR.LABOR__FED_OSHA_ITA_300A_SUMMARY_2024 WHERE REGEXP_LIKE(TRIM(EIN),'^[0-9]{8,9}$') AND TRY_TO_NUMBER(EIN)>0 GROUP BY 1),
f AS (SELECT LPAD(TRIM(AUDITEE_EIN::VARCHAR),9,'0') e, MAX(AUDITEE_NAME) fnm, MAX_BY(TRY_TO_DOUBLE(TOTAL_AMOUNT_EXPENDED::VARCHAR), AUDIT_YEAR) fed_exp_latest, MAX(AUDIT_YEAR) fy FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_FAC_SINGLE_AUDIT GROUP BY 1),
h AS (SELECT DISTINCT LPAD(TRIM(EIN::VARCHAR),9,'0') e FROM LIBRARY_MARTS.HEALTH.HEALTH__HOSPITAL_OFFICER_PAY),
u AS (SELECT e FROM a UNION SELECT e FROM b),
j AS (SELECT u.e, a.cases23, a.deaths23, b.sites24, b.deaths24, b.inj24, COALESCE(b.nm24,a.nm23) osha_name, f.fnm, f.fed_exp_latest, f.fy, (h.e IS NOT NULL) hosp, (a.e IS NOT NULL)::INT+(b.e IS NOT NULL)::INT n_harm FROM u LEFT JOIN a ON a.e=u.e LEFT JOIN b ON b.e=u.e LEFT JOIN f ON f.e=u.e LEFT JOIN h ON h.e=u.e)
SELECT e, cases23, deaths23, sites24, deaths24, inj24, osha_name, fnm, ROUND(fed_exp_latest) fed_exp, fy, hosp FROM j WHERE fnm IS NOT NULL ORDER BY COALESCE(deaths23,0)+COALESCE(deaths24,0) DESC, inj24 DESC NULLS LAST LIMIT 15;

-- [50] R:CCN: harm x money table-count overlap
WITH hm AS (
 SELECT DISTINCT 'H_DEF' t, TRIM(CMS_CERTIFICATION_NUMBER_CCN::VARCHAR) c FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_NURSING_HOME_DEFICIENCIES
 UNION ALL SELECT DISTINCT 'H_FIRE', TRIM(CMS_CERTIFICATION_NUMBER_CCN::VARCHAR) FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_NURSING_HOME_FIRE_DEFICIENCIES
 UNION ALL SELECT DISTINCT 'H_PEN', TRIM(CMS_CERTIFICATION_NUMBER_CCN::VARCHAR) FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_NURSING_HOME_PENALTIES
 UNION ALL SELECT DISTINCT 'H_NH411', TRIM(CMS_CERTIFICATION_NUMBER_CCN::VARCHAR) FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_NURSINGHOME411
 UNION ALL SELECT DISTINCT 'H_NH', TRIM(CMS_CERTIFICATION_NUMBER_CCN::VARCHAR) FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_NURSING_HOME
 UNION ALL SELECT DISTINCT 'H_HHA', TRIM(CCN::VARCHAR) FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_HOME_HEALTH
 UNION ALL SELECT DISTINCT 'M_OP', TRIM(CCN) FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_OPEN_PAYMENTS WHERE TRIM(CCN)<>''
 UNION ALL SELECT DISTINCT 'M_INP', TRIM(RNDRNG_PRVDR_CCN::VARCHAR) FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_MEDICARE_INPATIENT_HOSPITALS_BY_PROVIDER
 UNION ALL SELECT DISTINCT 'M_HCRIS', TRIM(PROVIDER_CCN::VARCHAR) FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_HCRIS),
p AS (SELECT c, LISTAGG(t, ',') WITHIN GROUP (ORDER BY t) ts, COUNT_IF(t LIKE 'H_%') nh, COUNT_IF(t LIKE 'M_%') nm FROM hm GROUP BY 1)
SELECT nh, nm, COUNT(*) ccns, ANY_VALUE(ts) example_combo, MIN(c), MAX(c) FROM p GROUP BY 1,2 ORDER BY 1 DESC,2 DESC;

-- [51] R:CCN: harm x money table-count overlap
SELECT CCN_FACILITY_TYPE, COUNT(*) n, COUNT(DISTINCT PROVIDER_CCN) d, MIN(PROVIDER_CCN::VARCHAR), MAX(PROVIDER_CCN::VARCHAR) FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_HCRIS GROUP BY 1 ORDER BY 2 DESC LIMIT 10;

-- [52] R:CCN:worst: top penalized homes by deficiency count
WITH d AS (SELECT TRIM(CMS_CERTIFICATION_NUMBER_CCN::VARCHAR) c, COUNT(*) defs, MIN(SURVEY_DATE) d0, MAX(SURVEY_DATE) d1 FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_NURSING_HOME_DEFICIENCIES GROUP BY 1),
f AS (SELECT TRIM(CMS_CERTIFICATION_NUMBER_CCN::VARCHAR) c, COUNT(*) fire FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_NURSING_HOME_FIRE_DEFICIENCIES GROUP BY 1),
p AS (SELECT TRIM(CMS_CERTIFICATION_NUMBER_CCN::VARCHAR) c, COUNT(*) pens, SUM(TRY_TO_DOUBLE(FINE_AMOUNT::VARCHAR)) fines, MIN(PENALTY_DATE) p0, MAX(PENALTY_DATE) p1, MAX(PROVIDER_NAME) nm FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_NURSING_HOME_PENALTIES GROUP BY 1),
n AS (SELECT TRIM(CMS_CERTIFICATION_NUMBER_CCN::VARCHAR) c, MAX(PROVIDER_NAME) nm, MAX(CHAIN_NAME) chain, MAX(TRY_TO_DOUBLE(TOTAL_AMOUNT_OF_FINES_IN_DOLLARS::VARCHAR)) nh_fines, MAX(STATE) st FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_NURSING_HOME GROUP BY 1)
SELECT p.c, COALESCE(n.nm,p.nm) name, n.st, n.chain, d.defs, f.fire, p.pens, ROUND(p.fines) pen_fines, ROUND(n.nh_fines) nh_table_fines, p.p0, p.p1, d.d0, d.d1 FROM p LEFT JOIN d ON d.c=p.c LEFT JOIN f ON f.c=p.c LEFT JOIN n ON n.c=p.c ORDER BY COALESCE(d.defs,0)+COALESCE(f.fire,0) DESC LIMIT 12;

-- [53] R:CCN:worst: top penalized homes by deficiency count
WITH d AS (SELECT TRIM(CMS_CERTIFICATION_NUMBER_CCN::VARCHAR) c, COUNT(*) defs FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_NURSING_HOME_DEFICIENCIES GROUP BY 1),
p AS (SELECT TRIM(CMS_CERTIFICATION_NUMBER_CCN::VARCHAR) c, SUM(TRY_TO_DOUBLE(FINE_AMOUNT::VARCHAR)) fines FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_NURSING_HOME_PENALTIES GROUP BY 1),
n AS (SELECT TRIM(CMS_CERTIFICATION_NUMBER_CCN::VARCHAR) c, MAX(TRY_TO_DOUBLE(TOTAL_AMOUNT_OF_FINES_IN_DOLLARS::VARCHAR)) nf FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_NURSING_HOME GROUP BY 1)
SELECT COUNT(*) homes, COUNT(d.c) with_defs, COUNT(p.c) with_pen, CORR(d.defs, COALESCE(p.fines,0)) corr_defs_fines, COUNT_IF(p.c IS NOT NULL AND ABS(COALESCE(p.fines,0)-COALESCE(n.nf,0))<1) fines_agree, COUNT_IF(p.c IS NOT NULL) pen_homes FROM n LEFT JOIN d ON d.c=n.c LEFT JOIN p ON p.c=n.c;

-- [54] R:FRS_ID: harm table overlap + ECHO penalties
SELECT 'echo' t, COUNT(*) n, COUNT(DISTINCT FRS_ID) d, COUNT_IF(TRY_TO_DOUBLE(LAST_PENALTY_AMT::VARCHAR)>0) pen_rows, MIN(FRS_ID::VARCHAR), MAX(FRS_ID::VARCHAR) FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ECHO
UNION ALL SELECT 'gap', COUNT(*), COUNT(DISTINCT FRS_ID), COUNT_IF(TRY_TO_DOUBLE(LAST_PENALTY_AMT::VARCHAR)>0), MIN(FRS_ID::VARCHAR), MAX(FRS_ID::VARCHAR) FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__EPA_PENALTY_GAP
UNION ALL SELECT 'fec_concl', COUNT(*), COUNT(DISTINCT FACILITY_UIN), NULL, MIN(FACILITY_UIN::VARCHAR), MAX(FACILITY_UIN::VARCHAR) FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_EPA_ICIS_FEC_CASE_ENFORCEMENT_CONCLUSION_FACILITIES
UNION ALL SELECT 'fec_inf', COUNT(*), COUNT(DISTINCT REGISTRY_ID), NULL, MIN(REGISTRY_ID::VARCHAR), MAX(REGISTRY_ID::VARCHAR) FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_EPA_ICIS_FEC_EPA_INFORMAL_ENFORCEMENT_ACTIONS
UNION ALL SELECT 'npdes_inf', COUNT(*), COUNT(DISTINCT REGISTRY_ID), NULL, MIN(REGISTRY_ID::VARCHAR), MAX(REGISTRY_ID::VARCHAR) FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_NPDES_NPDES_INFORMAL_ENFORCEMENT_ACTIONS
UNION ALL SELECT 'air_fac', COUNT(*), COUNT(DISTINCT REGISTRY_ID), NULL, MIN(REGISTRY_ID::VARCHAR), MAX(REGISTRY_ID::VARCHAR) FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_FACILITIES;

-- [55] R:FRS_ID: harm table overlap + ECHO penalties
WITH h AS (
 SELECT DISTINCT 'AIR_EMIS' t, REGISTRY_ID::VARCHAR r FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_AIR_EMISSIONS_POLL_RPT_COMBINED_EMISSIONS
 UNION ALL SELECT DISTINCT 'NPDES_INF', REGISTRY_ID::VARCHAR FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_NPDES_NPDES_INFORMAL_ENFORCEMENT_ACTIONS
 UNION ALL SELECT DISTINCT 'AIR_FAC', REGISTRY_ID::VARCHAR FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_FACILITIES
 UNION ALL SELECT DISTINCT 'FEC_CONCL', FACILITY_UIN::VARCHAR FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_EPA_ICIS_FEC_CASE_ENFORCEMENT_CONCLUSION_FACILITIES
 UNION ALL SELECT DISTINCT 'FEC_INF', REGISTRY_ID::VARCHAR FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_EPA_ICIS_FEC_EPA_INFORMAL_ENFORCEMENT_ACTIONS),
p AS (SELECT r, COUNT(*) nh, LISTAGG(t, ',') WITHIN GROUP (ORDER BY t) ts FROM h WHERE r IS NOT NULL AND r<>'' GROUP BY 1),
e AS (SELECT FRS_ID::VARCHAR r, MAX(TRY_TO_DOUBLE(LAST_PENALTY_AMT::VARCHAR)) pen FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ECHO GROUP BY 1)
SELECT p.nh, COUNT(*) ids, COUNT(e.r) in_echo, COUNT_IF(e.pen>0) with_penalty, ROUND(SUM(e.pen)) pen_sum, MEDIAN(CASE WHEN e.pen>0 THEN e.pen END) med_pen, ANY_VALUE(ts) FROM p LEFT JOIN e ON e.r=p.r GROUP BY 1 ORDER BY 1 DESC;

-- [56] R:FRS_ID:worst top + NPDES informal registry-id check
WITH h AS (
 SELECT DISTINCT 'AIR_EMIS' t, REGISTRY_ID::VARCHAR r FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_AIR_EMISSIONS_POLL_RPT_COMBINED_EMISSIONS
 UNION ALL SELECT DISTINCT 'NPDES_INF', REGISTRY_ID::VARCHAR FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_NPDES_NPDES_INFORMAL_ENFORCEMENT_ACTIONS
 UNION ALL SELECT DISTINCT 'AIR_FAC', REGISTRY_ID::VARCHAR FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_FACILITIES
 UNION ALL SELECT DISTINCT 'FEC_CONCL', FACILITY_UIN::VARCHAR FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_EPA_ICIS_FEC_CASE_ENFORCEMENT_CONCLUSION_FACILITIES
 UNION ALL SELECT DISTINCT 'FEC_INF', REGISTRY_ID::VARCHAR FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_EPA_ICIS_FEC_EPA_INFORMAL_ENFORCEMENT_ACTIONS),
p AS (SELECT r FROM h GROUP BY 1 HAVING COUNT(*)=5),
c AS (SELECT FACILITY_UIN::VARCHAR r, COUNT(DISTINCT ENF_CONCLUSION_ID) concl, MAX(FACILITY_NAME) cn, MAX(FACILITY_STATE) st FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_EPA_ICIS_FEC_CASE_ENFORCEMENT_CONCLUSION_FACILITIES WHERE FACILITY_UIN::VARCHAR IN (SELECT r FROM p) GROUP BY 1),
n AS (SELECT REGISTRY_ID::VARCHAR r, COUNT(*) npdes_inf FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_NPDES_NPDES_INFORMAL_ENFORCEMENT_ACTIONS WHERE REGISTRY_ID::VARCHAR IN (SELECT r FROM p) GROUP BY 1),
f AS (SELECT REGISTRY_ID::VARCHAR r, COUNT(*) fec_inf FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_EPA_ICIS_FEC_EPA_INFORMAL_ENFORCEMENT_ACTIONS WHERE REGISTRY_ID::VARCHAR IN (SELECT r FROM p) GROUP BY 1),
e AS (SELECT FRS_ID::VARCHAR r, MAX(FACILITY_NAME) en, MAX(TRY_TO_DOUBLE(LAST_PENALTY_AMT::VARCHAR)) pen, MAX(PENALTY_COUNT) pc FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ECHO WHERE FRS_ID::VARCHAR IN (SELECT r FROM p) GROUP BY 1)
SELECT p.r, e.en echo_name, c.cn fec_name, c.st, c.concl, n.npdes_inf, f.fec_inf, e.pc penalty_count, ROUND(e.pen) last_pen FROM p LEFT JOIN c ON c.r=p.r LEFT JOIN n ON n.r=p.r LEFT JOIN f ON f.r=p.r LEFT JOIN e ON e.r=p.r ORDER BY COALESCE(c.concl,0)+COALESCE(n.npdes_inf,0)+COALESCE(f.fec_inf,0) DESC LIMIT 12;

-- [57] R:FRS_ID:worst top + NPDES informal registry-id check
SELECT COUNT(*) n, COUNT_IF(NOT REGEXP_LIKE(REGISTRY_ID::VARCHAR,'^110[0-9]{9}$')) not_frs, COUNT(DISTINCT CASE WHEN NOT REGEXP_LIKE(REGISTRY_ID::VARCHAR,'^110[0-9]{9}$') THEN REGISTRY_ID END) d_not_frs, COUNT_IF(REGISTRY_ID::VARCHAR=NPDES_ID::VARCHAR) reg_eq_npdes, COUNT_IF(REGISTRY_ID IS NULL) nulls FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_NPDES_NPDES_INFORMAL_ENFORCEMENT_ACTIONS;

-- [58] R:NPDES_ID:worst overlap + top permits
WITH h AS (
 SELECT 'INF' t, NPDES_ID::VARCHAR p, COUNT(*) n FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_NPDES_NPDES_INFORMAL_ENFORCEMENT_ACTIONS GROUP BY 1,2
 UNION ALL SELECT 'PS', NPDES_ID::VARCHAR, COUNT(*) FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_NPDES_NPDES_PS_VIOLATIONS GROUP BY 1,2
 UNION ALL SELECT 'SE', NPDES_ID::VARCHAR, COUNT(*) FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_NPDES_NPDES_SE_VIOLATIONS GROUP BY 1,2
 UNION ALL SELECT 'FORMAL', NPDES_ID::VARCHAR, COUNT(*) FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_NPDES_NPDES_FORMAL_ENFORCEMENT_ACTIONS GROUP BY 1,2
 UNION ALL SELECT 'CS', NPDES_ID::VARCHAR, COUNT(*) FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_NPDES_NPDES_CS_VIOLATIONS GROUP BY 1,2),
p AS (SELECT p, COUNT(*) nt, SUM(n) events, LISTAGG(t||':'||n, ' ') WITHIN GROUP (ORDER BY t) detail FROM h WHERE p IS NOT NULL GROUP BY 1)
SELECT 'dist' k, nt, COUNT(*) permits, SUM(events) events, NULL detail FROM p GROUP BY 1,2
UNION ALL SELECT * FROM (SELECT p, nt, 1, events, detail FROM p WHERE nt>=4 ORDER BY nt DESC, events DESC LIMIT 12);

-- [59] R:NPDES_ID:worst overlap + top permits
WITH f AS (SELECT NPDES_ID::VARCHAR p, COUNT(*) formal, SUM(TRY_TO_DOUBLE(FED_PENALTY_ASSESSED_AMT::VARCHAR)) fed_pen, SUM(TRY_TO_DOUBLE(STATE_LOCAL_PENALTY_AMT::VARCHAR)) st_pen FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_NPDES_NPDES_FORMAL_ENFORCEMENT_ACTIONS GROUP BY 1),
s AS (SELECT NPDES_ID::VARCHAR p, COUNT(*) se FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_NPDES_NPDES_SE_VIOLATIONS GROUP BY 1),
i AS (SELECT NPDES_ID::VARCHAR p, MAX(REGISTRY_ID) reg FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_NPDES_NPDES_INFORMAL_ENFORCEMENT_ACTIONS GROUP BY 1),
e AS (SELECT FRS_ID::VARCHAR r, MAX(FACILITY_NAME) nm FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ECHO GROUP BY 1)
SELECT s.p, e.nm, s.se single_event_viol, f.formal, ROUND(f.fed_pen) fed_pen, ROUND(f.st_pen) st_pen FROM s LEFT JOIN f ON f.p=s.p LEFT JOIN i ON i.p=s.p LEFT JOIN e ON e.r=i.reg::VARCHAR ORDER BY s.se DESC LIMIT 12;

-- [60] R:UEI:harm-money: verify Amerihost + A&S exclusion records
SELECT UEI, ENTITY_NAME, CLASSIFICATION, EXCLUDING_AGENCY, EXCLUSION_TYPE, EXCLUSION_PROGRAM, ACTIVATION_DATE, TERMINATION_DATE, TERMINATION_DATE_RAW, CITY, STATE FROM LIBRARY_MARTS.PROCUREMENT.PROCUREMENT__FED_SAM_EXCLUSIONS WHERE TRIM(UEI) IN ('KYVXWCGG27M9','DLDBNGNA7CB6');

-- [61] R:UEI:harm-money: Amerihost assistance actions
SELECT ACTION_DATE, FEDERAL_ACTION_OBLIGATION, AWARDING_AGENCY_NAME, CFDA_TITLE, ASSISTANCE_TYPE_DESCRIPTION, ACTION_TYPE_DESCRIPTION, AWARD_ID_FAIN, RECIPIENT_STATE_CODE, LEFT(TRANSACTION_DESCRIPTION,80) descr FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_USASPENDING_ASSISTANCE_FULL WHERE TRIM(RECIPIENT_UEI)='KYVXWCGG27M9' ORDER BY ACTION_DATE LIMIT 30;

