-- [1] column types for lead columns, all 25 tables
SELECT table_schema, table_name, column_name, data_type
FROM LIBRARY_MARTS.INFORMATION_SCHEMA.COLUMNS
WHERE (table_schema||'__'||table_name) IN ('HEALTH__FED_HRSA_NPDB','ECONOMICS__FED_USASPENDING_CONTRACTS_FULL','JUSTICE__FED_COURTLISTENER_FJC_IDB_CL_LINKED','HOUSING__FED_CFPB_HMDA','HOUSING__FED_CFPB_HMDA_DC_ONLY','IMMIGRATION__FED_ICE_DETENTION_STINTS','HOUSING__FED_CFPB_HMDA_LAR','TRANSPORT__FED_FRA_CROSSING_INCIDENTS','JUSTICE__FED_FJC_IDB_CRIMINAL','PROCUREMENT__FED_USASPENDING_BULK','ECONOMICS__FED_USASPENDING_ASSISTANCE_FULL','JUSTICE__XC_MAPPING_POLICE_VIOLENCE','ECONOMICS__FED_SBA_LOANS','ECONOMICS__FED_USASPENDING_CONTRACTS_FULL_R2','JUSTICE__XC_WAPO_FATAL_FORCE','JUSTICE__FED_FJC_ARTICLE_III_JUDGES','POLITICS__FED_FJC_JUDGES','HOUSING__FED_FEMA_IA_HOUSING_REGISTRATIONS','JUSTICE__INTL_HUDOC','TRANSPORT__FED_FRA_EQUIPMENT_ACCIDENTS','POLITICS__MEMBER_INDIV_DONATIONS','POLITICS__MEMBER_MONEY_RAISED','CRIMINAL_JUSTICE__FED_BJS_DATA','ECONOMICS__FED_USASPENDING_CONTRACTS','FINANCE__FED_FEC_INDIV_CONTRIBUTIONS')
AND column_name IN ('TOTAL_PAYMENT','PAYMENT','FEDERAL_ACTION_OBLIGATION','ACTION_DATE','ACTION_DATE_FISCAL_YEAR','RECIPIENT_NAME','RECIPIENT_UEI','AWARDING_AGENCY_NAME','AMOUNT_RECEIVED','NATURE_OF_SUIT','DISTRICT','LOAN_AMOUNT','ACTION_TAKEN','LEI','INITIAL_BOND_SET_AMOUNT','ICE_FACILITY','STAY_BOOK_IN_AT','VEHICLE_DAMAGE_COST','CROSSING_USERS_KILLED','RAILROAD_CODE','REPORTING_RAILROAD_CODE','STATE_NAME','STATE','DATE','YEAR','FINE_AMOUNT_1','DEFENDANT_NAME','DOCKET','PRISON_TOTAL','THIRD_PARTY_DOLLARS','GROSS_APPROVAL_AMOUNT','GROSS_CHARGEOFF_AMOUNT','BORROWER_NAME','BANK_NAME','LOAN_STATUS','AGENCY_RESPONSIBLE_FOR_DEATH','DATE_OF_INCIDENT_MONTH_DAY_YEAR','INCIDENT_DATE','FLEE_STATUS','MENTAL_ILLNESS_RELATED','JUDICIARY_COMMITTEE_ACTION_1','NOMINATION_DATE_1','GROSS_INCOME','HA_AMOUNT','IHP_AMOUNT','DAMAGED_STATE_ABBREVIATION','DISASTER_NUMBER','VIOLATION','RESPONDENT','JUDGMENT_DATE','IMPORTANCE','EQUIPMENT_DAMAGE_COST','TOTAL_DAMAGE_COST','SELF_CONTRIB_15C','BIOGUIDE_ID','TTL_RECEIPTS_GROSS','CYCLE','VICTIMIZATION_WEIGHT','CL_PERSON_ID','YEAR_OF_SURVEY','TRANSACTION_AMT','TRANSACTION_DATE','IS_MEMO_TRANSACTION','FEC_CMTE_ID','DONOR_NAME','REPORTING_YEAR','PAYMENT_YEAR','LICENSE_STATE','WORK_STATE','FISCAL_YEAR','TOTAL_DOLLARS_OBLIGATED','CANDIDATE_NAME','NAME','STATE_ABBREVIATION')
ORDER BY 1,2,3;

-- [2] locate tables
SELECT table_catalog, table_schema, table_name, table_type, row_count FROM LIBRARY_MARTS.INFORMATION_SCHEMA.TABLES WHERE table_name IN ('FED_HRSA_NPDB','FED_SBA_LOANS','FED_FEC_INDIV_CONTRIBUTIONS','MEMBER_MONEY_RAISED','FED_USASPENDING_CONTRACTS_FULL_R2');

-- [3] NPDB sample + profile
SELECT SEQNO, REC_TYPE, ORIG_YEAR, LICENSE_STATE, TOTAL_PAYMENT, PAYMENT_NUMBER, NUM_PERSONS, PAYMENT_FLAG, PRACTITIONER_REPORT_SEQ, ACCRUED_REPORT_COUNT, PRIOR_MALPRACTICE_REPORTS, PRIOR_EXCLUSION_REPORTS, ALLEGATION_NATURE, OUTCOME_CODE FROM LIBRARY_MARTS.HEALTH.FED_HRSA_NPDB WHERE TOTAL_PAYMENT IS NOT NULL LIMIT 5;

-- [4] NPDB sample + profile
WITH b AS (SELECT *, TRY_TO_DOUBLE(REGEXP_REPLACE(TOTAL_PAYMENT::varchar,'[$,]','')) p FROM LIBRARY_MARTS.HEALTH.FED_HRSA_NPDB)
SELECT COUNT(*) n, COUNT(TOTAL_PAYMENT) filled, COUNT(p) parsed, MIN(p), MEDIAN(p), MAX(p), SUM(p), MIN(ORIG_YEAR), MAX(ORIG_YEAR),
 COUNT_IF(p>=1e6) over_1m, COUNT_IF(p BETWEEN 9000 AND 9999) near10k_under, COUNT_IF(p BETWEEN 10000 AND 10999) near10k_over,
 MAX(TRY_TO_NUMBER(ACCRUED_REPORT_COUNT::varchar)) max_accrued, MAX(TRY_TO_NUMBER(PRIOR_MALPRACTICE_REPORTS::varchar)) max_prior_mal, MAX(TRY_TO_NUMBER(PRIOR_EXCLUSION_REPORTS::varchar)) max_prior_excl
FROM b;

-- [5] NPDB sample + profile
WITH b AS (SELECT *, TRY_TO_DOUBLE(REGEXP_REPLACE(TOTAL_PAYMENT::varchar,'[$,]','')) p FROM LIBRARY_MARTS.HEALTH.FED_HRSA_NPDB)
SELECT LICENSE_STATE, COUNT(p) payments, ROUND(SUM(p)/1e9,2) bn, MEDIAN(p) med, ROUND(SUM(p)/NULLIF(COUNT(p),0)) mean FROM b GROUP BY 1 ORDER BY bn DESC NULLS LAST LIMIT 10;

-- [6] session check + find NPDB
SELECT CURRENT_ROLE(), CURRENT_DATABASE(), CURRENT_WAREHOUSE(), (SELECT COUNT(*) FROM LIBRARY_MARTS.INFORMATION_SCHEMA.TABLES) n_tables, (SELECT LISTAGG(table_schema||'.'||table_name, ', ') FROM LIBRARY_MARTS.INFORMATION_SCHEMA.TABLES WHERE table_name ILIKE '%NPDB%' OR table_name ILIKE '%SBA_LOAN%') hits;

-- [7] map 25 ids to real mart names
WITH ids(id) AS (SELECT column1 FROM VALUES ('HEALTH__FED_HRSA_NPDB'),('ECONOMICS__FED_USASPENDING_CONTRACTS_FULL'),('JUSTICE__FED_COURTLISTENER_FJC_IDB_CL_LINKED'),('HOUSING__FED_CFPB_HMDA'),('HOUSING__FED_CFPB_HMDA_DC_ONLY'),('IMMIGRATION__FED_ICE_DETENTION_STINTS'),('HOUSING__FED_CFPB_HMDA_LAR'),('TRANSPORT__FED_FRA_CROSSING_INCIDENTS'),('JUSTICE__FED_FJC_IDB_CRIMINAL'),('PROCUREMENT__FED_USASPENDING_BULK'),('ECONOMICS__FED_USASPENDING_ASSISTANCE_FULL'),('JUSTICE__XC_MAPPING_POLICE_VIOLENCE'),('ECONOMICS__FED_SBA_LOANS'),('ECONOMICS__FED_USASPENDING_CONTRACTS_FULL_R2'),('JUSTICE__XC_WAPO_FATAL_FORCE'),('JUSTICE__FED_FJC_ARTICLE_III_JUDGES'),('POLITICS__FED_FJC_JUDGES'),('HOUSING__FED_FEMA_IA_HOUSING_REGISTRATIONS'),('JUSTICE__INTL_HUDOC'),('TRANSPORT__FED_FRA_EQUIPMENT_ACCIDENTS'),('POLITICS__MEMBER_INDIV_DONATIONS'),('POLITICS__MEMBER_MONEY_RAISED'),('CRIMINAL_JUSTICE__FED_BJS_DATA'),('ECONOMICS__FED_USASPENDING_CONTRACTS'),('FINANCE__FED_FEC_INDIV_CONTRIBUTIONS'))
SELECT i.id, LISTAGG(t.table_schema||'.'||t.table_name||' ['||t.table_type||' '||COALESCE(t.row_count::varchar,'')||']', ', ') found
FROM ids i LEFT JOIN LIBRARY_MARTS.INFORMATION_SCHEMA.TABLES t ON t.table_name = i.id OR t.table_name ILIKE '%'||SPLIT_PART(i.id,'__',2)
GROUP BY 1 ORDER BY 1;

-- [8] NPDB
SELECT SEQNO, REC_TYPE, ORIG_YEAR, LICENSE_STATE, TOTAL_PAYMENT, PAYMENT_NUMBER, NUM_PERSONS, PAYMENT_FLAG, PRACTITIONER_REPORT_SEQ, ACCRUED_REPORT_COUNT, PRIOR_MALPRACTICE_REPORTS, PRIOR_EXCLUSION_REPORTS, ALLEGATION_NATURE, OUTCOME_CODE FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_HRSA_NPDB WHERE TOTAL_PAYMENT IS NOT NULL LIMIT 5;

-- [9] NPDB
WITH b AS (SELECT *, TRY_TO_DOUBLE(REGEXP_REPLACE(TOTAL_PAYMENT::varchar,'[$,]','')) p FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_HRSA_NPDB)
SELECT COUNT(*) n, COUNT(TOTAL_PAYMENT) filled, COUNT(p) parsed, MIN(p), MEDIAN(p), MAX(p), SUM(p), MIN(ORIG_YEAR), MAX(ORIG_YEAR),
 COUNT_IF(p>=1e6) over_1m, COUNT_IF(p BETWEEN 9000 AND 9999) b9k, COUNT_IF(p BETWEEN 10000 AND 10999) b10k, COUNT_IF(p BETWEEN 140000 AND 149999) b140k, COUNT_IF(p BETWEEN 150000 AND 159999) b150k,
 MAX(TRY_TO_NUMBER(ACCRUED_REPORT_COUNT::varchar)) max_accrued, MAX(TRY_TO_NUMBER(PRIOR_MALPRACTICE_REPORTS::varchar)) max_prior_mal, MAX(TRY_TO_NUMBER(PRIOR_EXCLUSION_REPORTS::varchar)) max_prior_excl
FROM b;

-- [10] NPDB
WITH b AS (SELECT *, TRY_TO_DOUBLE(REGEXP_REPLACE(TOTAL_PAYMENT::varchar,'[$,]','')) p FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_HRSA_NPDB)
SELECT LICENSE_STATE, COUNT(p) payments, ROUND(SUM(p)/1e9,2) bn, MEDIAN(p) med, ROUND(SUM(p)/NULLIF(COUNT(p),0)) mean FROM b GROUP BY 1 ORDER BY bn DESC NULLS LAST LIMIT 10;

-- [11] NPDB: where did payment go
SELECT table_schema, table_name, row_count FROM LIBRARY_RAW.INFORMATION_SCHEMA.TABLES WHERE table_name ILIKE '%NPDB%';

-- [12] NPDB: where did payment go
SELECT REC_TYPE, COUNT(*) n, COUNT(TOTAL_PAYMENT) pay, COUNT(PAYMENT_NUMBER) paynum, COUNT(NUM_PERSONS) numpers, COUNT(PAYMENT_FLAG) pflag, COUNT_IF(TRY_TO_NUMBER(PRIOR_MALPRACTICE_REPORTS::varchar)>=50) prior50, MEDIAN(TRY_TO_NUMBER(PRIOR_MALPRACTICE_REPORTS::varchar)) med_prior FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_HRSA_NPDB GROUP BY 1 ORDER BY 2 DESC;

-- [13] NPDB landing raw row
SELECT OBJECT_CONSTRUCT(*)::varchar raw FROM LIBRARY_RAW.LANDING.FED_HRSA_NPDB LIMIT 3;

-- [14] NPDB landing payment keys
WITH s AS (SELECT OBJECT_CONSTRUCT(*) o FROM LIBRARY_RAW.LANDING.FED_HRSA_NPDB SAMPLE (20000 ROWS))
SELECT f.key, COUNT(*) n, COUNT_IF(NULLIF(TRIM(f.value::varchar),'') IS NOT NULL) filled, ANY_VALUE(f.value::varchar) ex, MAX(f.value::varchar) mx
FROM s, LATERAL FLATTEN(s.o) f WHERE f.key ILIKE '%PAY%' OR f.key ILIKE '%PMT%' OR f.key ILIKE '%REC%' GROUP BY 1;

-- [15] NPDB landing payment profile
WITH b AS (SELECT LICSTATE, TRY_TO_DOUBLE(REGEXP_REPLACE(PAYMENT,'[$,]','')) p, TRY_TO_DOUBLE(REGEXP_REPLACE(TOTALPMT,'[$,]','')) t, ORIGYEAR FROM LIBRARY_RAW.LANDING.FED_HRSA_NPDB)
SELECT COUNT(p) n_pay, MIN(p), MEDIAN(p), MAX(p), ROUND(SUM(p)/1e9,2) sum_bn, COUNT(t) n_tot, MEDIAN(t) med_t, MAX(t) max_t,
 COUNT_IF(p BETWEEN 90000 AND 99999) b90k, COUNT_IF(p BETWEEN 100000 AND 109999) b100k, COUNT_IF(p BETWEEN 240000 AND 249999) b240k, COUNT_IF(p BETWEEN 250000 AND 259999) b250k,
 COUNT_IF(p BETWEEN 990000 AND 999999) b990k, COUNT_IF(p BETWEEN 1000000 AND 1009999) b1m, COUNT_IF(p=995000) eq995k, COUNT_IF(p>995000) over995k
FROM b;

-- [16] NPDB landing payment profile
WITH b AS (SELECT LICSTATE, TRY_TO_DOUBLE(REGEXP_REPLACE(PAYMENT,'[$,]','')) p FROM LIBRARY_RAW.LANDING.FED_HRSA_NPDB)
SELECT LICSTATE, COUNT(p) n, ROUND(SUM(p)/1e9,2) bn, MEDIAN(p) med FROM b GROUP BY 1 ORDER BY bn DESC NULLS LAST LIMIT 10;

-- [17] NPDB landing payment profile (retry)
WITH b AS (SELECT TRY_TO_DOUBLE(REGEXP_REPLACE(PAYMENT,'[$,]','')) p, TRY_TO_DOUBLE(REGEXP_REPLACE(TOTALPMT,'[$,]','')) t FROM LIBRARY_RAW.LANDING.FED_HRSA_NPDB)
SELECT COUNT(p) n_pay, MIN(p), MEDIAN(p), MAX(p), ROUND(SUM(p)/1e9,2) sum_bn, COUNT(t) n_tot, MEDIAN(t) med_t, MAX(t) max_t,
 COUNT_IF(p BETWEEN 90000 AND 99999) b90k, COUNT_IF(p BETWEEN 100000 AND 109999) b100k, COUNT_IF(p BETWEEN 240000 AND 249999) b240k, COUNT_IF(p BETWEEN 250000 AND 259999) b250k,
 COUNT_IF(p BETWEEN 990000 AND 999999) b990k, COUNT_IF(p=995000) eq995k, COUNT_IF(p>995000) over995k, COUNT_IF(t=995000) t995k, COUNT_IF(t>995000) t_over
FROM b;

-- [18] FEC indiv
SELECT SUB_ID, CMTE_ID, DONOR_NAME, STATE, TRANSACTION_DATE, TRANSACTION_AMT, TRANSACTION_TYPE, ENTITY_TYPE, MEMO_CD, IS_MEMO_TRANSACTION, CYCLE_FILE FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_FEC_INDIV_CONTRIBUTIONS LIMIT 5;

-- [19] FEC indiv
SELECT CYCLE_FILE, IS_MEMO_TRANSACTION, COUNT(*) n, COUNT(TRANSACTION_AMT) amt, MIN(TRANSACTION_AMT) mn, APPROX_PERCENTILE(TRANSACTION_AMT,0.5) med, MAX(TRANSACTION_AMT) mx, ROUND(SUM(TRANSACTION_AMT)/1e9,2) bn, COUNT_IF(TRANSACTION_AMT<0) neg, MIN(TRANSACTION_DATE) d0, MAX(TRANSACTION_DATE) d1
FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_FEC_INDIV_CONTRIBUTIONS GROUP BY 1,2 ORDER BY 1,2;

-- [20] FEC indiv top committees and rows
SELECT CMTE_ID, COUNT(*) n, ROUND(SUM(TRANSACTION_AMT)/1e9,2) bn, COUNT_IF(TRANSACTION_TYPE IN ('15E','24T')) earmark_rows, MODE(TRANSACTION_TYPE) top_type FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_FEC_INDIV_CONTRIBUTIONS WHERE NOT IS_MEMO_TRANSACTION GROUP BY 1 ORDER BY bn DESC LIMIT 10;

-- [21] FEC indiv top committees and rows
SELECT DONOR_NAME, CMTE_ID, TRANSACTION_DATE, TRANSACTION_AMT, TRANSACTION_TYPE, ENTITY_TYPE, EMPLOYER, CYCLE_FILE FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_FEC_INDIV_CONTRIBUTIONS WHERE NOT IS_MEMO_TRANSACTION AND TRANSACTION_AMT >= 20000000 ORDER BY TRANSACTION_AMT DESC LIMIT 15;

-- [22] contracts R2
SELECT LEFT(ACTION_DATE::varchar,4) yr, COUNT(*) n, COUNT(FEDERAL_ACTION_OBLIGATION) filled, MIN(FEDERAL_ACTION_OBLIGATION) mn, APPROX_PERCENTILE(FEDERAL_ACTION_OBLIGATION,0.5) med, MAX(FEDERAL_ACTION_OBLIGATION) mx, ROUND(SUM(FEDERAL_ACTION_OBLIGATION)/1e9,1) bn FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_USASPENDING_CONTRACTS_FULL_R2 GROUP BY 1 ORDER BY 1;

-- [23] contracts R2
SELECT RECIPIENT_PARENT_NAME, COUNT(*) n, ROUND(SUM(FEDERAL_ACTION_OBLIGATION)/1e9,1) bn FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_USASPENDING_CONTRACTS_FULL_R2 GROUP BY 1 ORDER BY bn DESC NULLS LAST LIMIT 12;

-- [24] assistance full
SELECT ACTION_DATE_FISCAL_YEAR fy, COUNT(*) n, MIN(ACTION_DATE) d0, MAX(ACTION_DATE) d1, COUNT(DISTINCT LEFT(ACTION_DATE::varchar,7)) months, APPROX_PERCENTILE(FEDERAL_ACTION_OBLIGATION,0.5) med, MIN(FEDERAL_ACTION_OBLIGATION) mn, MAX(FEDERAL_ACTION_OBLIGATION) mx, ROUND(SUM(FEDERAL_ACTION_OBLIGATION)/1e9,1) bn FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_USASPENDING_ASSISTANCE_FULL GROUP BY 1 ORDER BY 1;

-- [25] assistance 9999999999 rows + top recipients
SELECT FEDERAL_ACTION_OBLIGATION, ACTION_DATE, RECIPIENT_NAME, AWARDING_AGENCY_NAME, CFDA_TITLE, ASSISTANCE_TYPE_DESCRIPTION, ASSISTANCE_AWARD_UNIQUE_KEY, MODIFICATION_NUMBER FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_USASPENDING_ASSISTANCE_FULL WHERE ABS(FEDERAL_ACTION_OBLIGATION) BETWEEN 9999999990 AND 9999999999.99 ORDER BY ACTION_DATE LIMIT 20;

-- [26] assistance 9999999999 rows + top recipients
SELECT RECIPIENT_NAME, COUNT(*) n, ROUND(SUM(FEDERAL_ACTION_OBLIGATION)/1e9,1) bn, MODE(AWARDING_AGENCY_NAME) agency FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_USASPENDING_ASSISTANCE_FULL GROUP BY 1 ORDER BY bn DESC NULLS LAST LIMIT 12;

-- [27] contracts_full + contracts + bulk: is the cap still there
SELECT 'FULL' t, LEFT(ACTION_DATE::varchar,4) yr, COUNT(*) n, COUNT(DISTINCT LEFT(ACTION_DATE::varchar,7)) months, ROUND(SUM(FEDERAL_ACTION_OBLIGATION)/1e9,1) bn FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_USASPENDING_CONTRACTS_FULL GROUP BY 1,2
UNION ALL SELECT 'CONTRACTS', LEFT(ACTION_DATE::varchar,4), COUNT(*), COUNT(DISTINCT LEFT(ACTION_DATE::varchar,7)), ROUND(SUM(FEDERAL_ACTION_OBLIGATION)/1e9,1) FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_USASPENDING_CONTRACTS GROUP BY 1,2
UNION ALL SELECT 'BULK', LEFT(PERIOD_OF_PERFORMANCE_CURRENT_END_DATE::varchar,4), COUNT(*), NULL, ROUND(SUM(FEDERAL_ACTION_OBLIGATION)/1e9,1) FROM LIBRARY_MARTS.PROCUREMENT.PROCUREMENT__FED_USASPENDING_BULK GROUP BY 1,2
ORDER BY 1,2;

-- [28] HMDA three samples
SELECT 'HMDA' t, ACTIVITY_YEAR yr, STATE_CODE st, ACTION_TAKEN, COUNT(*) n, MEDIAN(TRY_TO_DOUBLE(LOAN_AMOUNT::varchar)) med_amt, MAX(TRY_TO_DOUBLE(LOAN_AMOUNT::varchar)) max_amt, COUNT(DISTINCT LEI) leis FROM LIBRARY_MARTS.HOUSING.HOUSING__FED_CFPB_HMDA GROUP BY 1,2,3,4
UNION ALL SELECT 'DC_ONLY', ACTIVITY_YEAR, STATE_CODE, ACTION_TAKEN, COUNT(*), MEDIAN(TRY_TO_DOUBLE(LOAN_AMOUNT::varchar)), MAX(TRY_TO_DOUBLE(LOAN_AMOUNT::varchar)), COUNT(DISTINCT LEI) FROM LIBRARY_MARTS.HOUSING.HOUSING__FED_CFPB_HMDA_DC_ONLY GROUP BY 1,2,3,4
UNION ALL SELECT 'LAR', ACTIVITY_YEAR, STATE_CODE, ACTION_TAKEN, COUNT(*), MEDIAN(TRY_TO_DOUBLE(LOAN_AMOUNT::varchar)), MAX(TRY_TO_DOUBLE(LOAN_AMOUNT::varchar)), COUNT(DISTINCT LEI) FROM LIBRARY_MARTS.HOUSING.HOUSING__FED_CFPB_HMDA_LAR GROUP BY 1,2,3,4
ORDER BY 1,4;

-- [29] HMDA three samples
SELECT (SELECT COUNT(*) FROM (SELECT LEI, CENSUS_TRACT, LOAN_AMOUNT, ACTION_TAKEN, INCOME FROM LIBRARY_MARTS.HOUSING.HOUSING__FED_CFPB_HMDA EXCEPT SELECT LEI, CENSUS_TRACT, LOAN_AMOUNT, ACTION_TAKEN, INCOME FROM LIBRARY_MARTS.HOUSING.HOUSING__FED_CFPB_HMDA_DC_ONLY)) hmda_not_in_dconly;

-- [30] ICE stints
SELECT PERSON_HASH, DETENTION_FACILITY, STATE, STAY_BOOK_IN_AT, INITIAL_BOND_SET_AMOUNT, BOND_POSTED_AMOUNT, MSC_CRIME_CLASS, DUPLICATE_DROP_ROW, DUPLICATE_LIKELY FROM LIBRARY_MARTS.IMMIGRATION.IMMIGRATION__FED_ICE_DETENTION_STINTS WHERE INITIAL_BOND_SET_AMOUNT IS NOT NULL LIMIT 5;

-- [31] ICE stints
WITH b AS (SELECT *, TRY_TO_DOUBLE(INITIAL_BOND_SET_AMOUNT::varchar) bs, TRY_TO_DOUBLE(BOND_POSTED_AMOUNT::varchar) bp FROM LIBRARY_MARTS.IMMIGRATION.IMMIGRATION__FED_ICE_DETENTION_STINTS)
SELECT COUNT(*) n, COUNT(DISTINCT PERSON_HASH) people, COUNT(bs) bond_set, MIN(bs), MEDIAN(bs), MAX(bs), COUNT_IF(bs=0) zero, COUNT(bp) posted, MEDIAN(bp) med_posted, COUNT_IF(bs>=50000) ge50k, COUNT_IF(bs BETWEEN 1500 AND 1500) eq1500, MIN(STAY_BOOK_IN_AT) d0, MAX(STAY_BOOK_IN_AT) d1, COUNT_IF(isnan(bs)) nans
FROM b;

-- [32] ICE stints
WITH b AS (SELECT *, TRY_TO_DOUBLE(INITIAL_BOND_SET_AMOUNT::varchar) bs, TRY_TO_DOUBLE(BOND_POSTED_AMOUNT::varchar) bp FROM LIBRARY_MARTS.IMMIGRATION.IMMIGRATION__FED_ICE_DETENTION_STINTS)
SELECT DETENTION_FACILITY, STATE, COUNT(*) stints, COUNT(bs) bonds, MEDIAN(bs) med_bond, ROUND(COUNT(bp)/NULLIF(COUNT(bs),0),2) posted_rate FROM b GROUP BY 1,2 ORDER BY bonds DESC LIMIT 10;

-- [33] ICE stints profile retry
WITH b AS (SELECT *, TRY_TO_DOUBLE(INITIAL_BOND_SET_AMOUNT::varchar) bs, TRY_TO_DOUBLE(BOND_POSTED_AMOUNT::varchar) bp FROM LIBRARY_MARTS.IMMIGRATION.IMMIGRATION__FED_ICE_DETENTION_STINTS)
SELECT COUNT(*) n, COUNT(DISTINCT PERSON_HASH) people, COUNT(bs) bond_set, MIN(bs), MEDIAN(bs), MAX(bs), COUNT_IF(bs=0) zero, COUNT(bp) posted, COUNT_IF(bp IS NOT NULL AND bs IS NULL) posted_no_set, MEDIAN(bp) med_posted, COUNT_IF(bs>=50000) ge50k, MIN(STAY_BOOK_IN_AT) d0, MAX(STAY_BOOK_IN_AT) d1,
 COUNT_IF(bs IS NOT NULL AND YEAR(STAY_BOOK_IN_AT)<2023) bonds_pre2023, COUNT_IF(YEAR(STAY_BOOK_IN_AT)<2023) stints_pre2023
FROM b;

-- [34] FRA crossings
WITH b AS (SELECT *, TRY_TO_DOUBLE(VEHICLE_DAMAGE_COST::varchar) v, TRY_TO_NUMBER(CROSSING_USERS_KILLED::varchar) k FROM LIBRARY_MARTS.TRANSPORT.TRANSPORT__FED_FRA_CROSSING_INCIDENTS)
SELECT COUNT(*) n, COUNT(v) vfilled, MIN(v), MEDIAN(v), MAX(v), COUNT(k) kfilled, SUM(k) killed, MAX(k) max_k, MIN(DATE) d0, MAX(DATE) d1, COUNT(DISTINCT REPORT_YEAR) yrs FROM b;

-- [35] FRA crossings
WITH b AS (SELECT *, TRY_TO_NUMBER(CROSSING_USERS_KILLED::varchar) k, TRY_TO_NUMBER(CROSSING_USERS_INJURED::varchar) i FROM LIBRARY_MARTS.TRANSPORT.TRANSPORT__FED_FRA_CROSSING_INCIDENTS)
SELECT REPORTING_PARENT_RAILROAD_NAME, COUNT(*) incidents, SUM(k) killed, SUM(i) injured, ROUND(SUM(k)/COUNT(*),3) kill_per_incident, MIN(REPORT_YEAR) y0 FROM b GROUP BY 1 ORDER BY killed DESC NULLS LAST LIMIT 10;

-- [36] FRA crossings
SELECT LEFT(REPORT_YEAR::varchar,3)||'0s' decade, COUNT(*) n, SUM(TRY_TO_NUMBER(CROSSING_USERS_KILLED::varchar)) killed FROM LIBRARY_MARTS.TRANSPORT.TRANSPORT__FED_FRA_CROSSING_INCIDENTS GROUP BY 1 ORDER BY 1;

-- [37] FRA equipment accidents
WITH b AS (SELECT *, TRY_TO_DOUBLE(EQUIPMENT_DAMAGE_COST::varchar) e, TRY_TO_DOUBLE(TOTAL_DAMAGE_COST::varchar) t FROM LIBRARY_MARTS.TRANSPORT.TRANSPORT__FED_FRA_EQUIPMENT_ACCIDENTS)
SELECT COUNT(*) n, COUNT(DISTINCT INCIDENT_KEY) incidents, COUNT(e) efilled, MIN(e), MEDIAN(e), MAX(e), ROUND(SUM(t)/1e9,2) total_bn, MEDIAN(t) med_t, MAX(t) max_t, MIN(DATE) d0, MAX(DATE) d1,
 SUM(TRY_TO_NUMBER(HAZMAT_RELEASED_CARS::varchar)) hz_rel, SUM(TRY_TO_NUMBER(PERSONS_EVACUATED::varchar)) evac FROM b;

-- [38] FRA equipment accidents
WITH b AS (SELECT *, TRY_TO_DOUBLE(TOTAL_DAMAGE_COST::varchar) t FROM LIBRARY_MARTS.TRANSPORT.TRANSPORT__FED_FRA_EQUIPMENT_ACCIDENTS)
SELECT REPORTING_PARENT_RAILROAD_NAME, COUNT(*) rows_, ROUND(SUM(t)/1e9,2) dmg_bn, SUM(TRY_TO_NUMBER(HAZMAT_RELEASED_CARS::varchar)) hz_rel, ROUND(SUM(t)/COUNT(*)) per_acc FROM b GROUP BY 1 ORDER BY dmg_bn DESC NULLS LAST LIMIT 10;

-- [39] FRA equipment accidents
SELECT DATE, REPORTING_RAILROAD_NAME, STATE_NAME, ACCIDENT_TYPE, TOTAL_DAMAGE_COST, PERSONS_EVACUATED, HAZMAT_RELEASED_CARS FROM LIBRARY_MARTS.TRANSPORT.TRANSPORT__FED_FRA_EQUIPMENT_ACCIDENTS ORDER BY TRY_TO_DOUBLE(TOTAL_DAMAGE_COST::varchar) DESC NULLS LAST LIMIT 8;

-- [40] FJC IDB criminal
WITH b AS (SELECT *, TRY_TO_DOUBLE(FINE_AMOUNT_1::varchar) f FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_FJC_IDB_CRIMINAL)
SELECT COUNT(*) n, COUNT(DISTINCT DEFENDANT_LINK_KEY) defendants, COUNT(DISTINCT DEFENDANT_RECORD_ID) recs, COUNT(f) ffilled, COUNT_IF(f>0) fpos, MIN(f), MEDIAN(IFF(f>0,f,NULL)) med_pos, MAX(f), COUNT_IF(f>=99999999) nines, MIN(FISCAL_YEAR) fy0, MAX(FISCAL_YEAR) fy1, COUNT(DISTINCT TAPE_YEAR) tapes FROM b;

-- [41] FJC IDB criminal
WITH b AS (SELECT *, TRY_TO_DOUBLE(FINE_AMOUNT_1::varchar) f FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_FJC_IDB_CRIMINAL)
SELECT f, COUNT(*) n, COUNT(DISTINCT DEFENDANT_LINK_KEY) defs, ANY_VALUE(DEFENDANT_NAME) ex_name, ANY_VALUE(DISTRICT) ex_dist, ANY_VALUE(TERM_TITLE_1) title FROM b WHERE f IS NOT NULL GROUP BY 1 ORDER BY f DESC LIMIT 12;

-- [42] CourtListener FJC IDB
WITH b AS (SELECT DATASET_SOURCE, DATE_FILED, TRY_TO_DOUBLE(AMOUNT_RECEIVED::varchar) a, TRY_TO_DOUBLE(MONETARY_DEMAND::varchar) m FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_COURTLISTENER_FJC_IDB_CL_LINKED)
SELECT DATASET_SOURCE, COUNT(*) n, COUNT(a) afilled, COUNT_IF(a>0) apos, MEDIAN(IFF(a>0,a,NULL)) a_med, MAX(a) a_max, COUNT_IF(a=9999) a9999, COUNT_IF(m>0) mpos, MEDIAN(IFF(m>0,m,NULL)) m_med, MAX(m) m_max, COUNT_IF(m=9999) m9999, MIN(DATE_FILED) d0, MAX(DATE_FILED) d1 FROM b GROUP BY 1 ORDER BY 2 DESC;

-- [43] CourtListener FJC IDB
SELECT NATURE_OF_SUIT, COUNT(*) n, COUNT_IF(TRY_TO_DOUBLE(AMOUNT_RECEIVED::varchar)>0) paid, MEDIAN(NULLIF(TRY_TO_DOUBLE(AMOUNT_RECEIVED::varchar),0)) med_paid FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_COURTLISTENER_FJC_IDB_CL_LINKED GROUP BY 1 ORDER BY n DESC LIMIT 10;

-- [44] MPV + WaPo
SELECT COUNT(*) n, MIN(DATE_OF_INCIDENT_MONTH_DAY_YEAR) d0, MAX(DATE_OF_INCIDENT_MONTH_DAY_YEAR) d1, COUNT(DISTINCT AGENCY_RESPONSIBLE_FOR_DEATH) agencies, COUNT(DISTINCT CRIMINAL_CHARGES) charge_vals, LISTAGG(DISTINCT LEFT(CRIMINAL_CHARGES,25), ' | ') WITHIN GROUP (ORDER BY LEFT(CRIMINAL_CHARGES,25)) charges, COUNT_IF(CRIMINAL_CHARGES ILIKE 'Charged%') charged, COUNT(WAPO_ID_IF_INCLUDED_IN_WAPO_DATABASE) in_wapo FROM LIBRARY_MARTS.JUSTICE.JUSTICE__XC_MAPPING_POLICE_VIOLENCE;

-- [45] MPV + WaPo
SELECT AGENCY_RESPONSIBLE_FOR_DEATH, STATE, COUNT(*) deaths, COUNT_IF(CRIMINAL_CHARGES ILIKE 'Charged%') charged, COUNT_IF(ARMED_UNARMED_STATUS ILIKE 'Unarmed%') unarmed FROM LIBRARY_MARTS.JUSTICE.JUSTICE__XC_MAPPING_POLICE_VIOLENCE GROUP BY 1,2 ORDER BY 3 DESC LIMIT 12;

-- [46] MPV + WaPo
SELECT YEAR(TRY_TO_DATE(INCIDENT_DATE::varchar)) yr, COUNT(*) n, COUNT_IF(MENTAL_ILLNESS_RELATED::varchar ILIKE 'true') mi, COUNT_IF(BODY_CAMERA_PRESENT::varchar ILIKE 'true') bodycam, COUNT_IF(FLEE_STATUS ILIKE 'not%') not_flee, COUNT(FLEE_STATUS) flee_filled FROM LIBRARY_MARTS.JUSTICE.JUSTICE__XC_WAPO_FATAL_FORCE GROUP BY 1 ORDER BY 1;

-- [47] WaPo flag values
SELECT MENTAL_ILLNESS_RELATED::varchar mi, BODY_CAMERA_PRESENT::varchar bc, COUNT(*) n, MIN(INCIDENT_DATE) d0, MAX(INCIDENT_DATE) d1 FROM LIBRARY_MARTS.JUSTICE.JUSTICE__XC_WAPO_FATAL_FORCE GROUP BY 1,2 ORDER BY 3 DESC;

-- [48] SBA loans
SELECT PROGRAM, LOAN_STATUS, IS_DEFAULTED::varchar dflt, COUNT(*) n, MEDIAN(GROSS_APPROVAL_AMOUNT) med_appr, MAX(GROSS_APPROVAL_AMOUNT) max_appr, COUNT(THIRD_PARTY_DOLLARS) tp_filled, MEDIAN(THIRD_PARTY_DOLLARS) tp_med, MAX(THIRD_PARTY_DOLLARS) tp_max, ROUND(SUM(GROSS_CHARGEOFF_AMOUNT)/1e9,2) co_bn, MIN(APPROVAL_DATE) d0, MAX(APPROVAL_DATE) d1 FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_SBA_LOANS GROUP BY 1,2,3 ORDER BY 1,4 DESC;

-- [49] SBA loans
SELECT LENDER_NAME, COUNT(*) loans, ROUND(SUM(GROSS_APPROVAL_AMOUNT)/1e9,2) appr_bn, COUNT_IF(LOAN_STATUS='CHGOFF') chgoff, ROUND(COUNT_IF(LOAN_STATUS='CHGOFF')/NULLIF(COUNT_IF(LOAN_STATUS IN ('CHGOFF','PIF')),0),3) co_rate_closed, ROUND(SUM(GROSS_CHARGEOFF_AMOUNT)/1e6,0) co_mn FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_SBA_LOANS WHERE PROGRAM ILIKE '7%' GROUP BY 1 HAVING COUNT_IF(LOAN_STATUS IN ('CHGOFF','PIF'))>=2000 ORDER BY co_rate_closed DESC LIMIT 12;

-- [50] SBA 7a lenders by chargeoff rate (fixed status codes)
SELECT LENDER_NAME, COUNT(*) loans, ROUND(SUM(GROSS_APPROVAL_AMOUNT)/1e9,2) appr_bn, COUNT_IF(LOAN_STATUS='CHGOFF') chgoff, COUNT_IF(LOAN_STATUS='P I F') pif, ROUND(COUNT_IF(LOAN_STATUS='CHGOFF')/NULLIF(COUNT_IF(LOAN_STATUS IN ('CHGOFF','P I F')),0),3) co_rate_closed, ROUND(SUM(GROSS_CHARGEOFF_AMOUNT)/1e6,0) co_mn, MIN(YEAR(APPROVAL_DATE)) y0, MEDIAN(YEAR(APPROVAL_DATE)) ymed FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_SBA_LOANS WHERE TRIM(PROGRAM)='7A' GROUP BY 1 HAVING COUNT_IF(LOAN_STATUS IN ('CHGOFF','P I F'))>=3000 ORDER BY co_rate_closed DESC LIMIT 12;

-- [51] SBA 7a lenders by chargeoff rate (fixed status codes)
SELECT YEAR(APPROVAL_DATE) yr, COUNT(*) n, ROUND(COUNT_IF(LOAN_STATUS='CHGOFF')/NULLIF(COUNT_IF(LOAN_STATUS IN ('CHGOFF','P I F')),0),3) co_rate FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_SBA_LOANS WHERE TRIM(PROGRAM)='7A' GROUP BY 1 ORDER BY 1;

-- [52] FJC judges two tables
SELECT 'ART3' t, JUDICIARY_COMMITTEE_ACTION_1 act, COUNT(*) n, COUNT_IF(GENDER ILIKE 'F%') women, COUNT_IF(RACE_OR_ETHNICITY NOT ILIKE 'White%') nonwhite, COUNT(RECESS_APPOINTMENT_DATE_1) recess, MIN(NOMINATION_DATE_1) d0, MAX(NOMINATION_DATE_1) d1 FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_FJC_ARTICLE_III_JUDGES GROUP BY 1,2
UNION ALL SELECT 'POL', JUDICIARY_COMMITTEE_ACTION_1, COUNT(*), COUNT_IF(GENDER ILIKE 'F%'), COUNT_IF(RACE_OR_ETHNICITY NOT ILIKE 'White%'), COUNT(RECESS_APPOINTMENT_DATE_1), MIN(NOMINATION_DATE_1), MAX(NOMINATION_DATE_1) FROM LIBRARY_MARTS.POLITICS.POLITICS__FED_FJC_JUDGES GROUP BY 1,2
ORDER BY 1,3 DESC;

-- [53] FJC judges two tables
SELECT (SELECT COUNT(DISTINCT NID) FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_FJC_ARTICLE_III_JUDGES) a_nid, (SELECT COUNT(DISTINCT NID) FROM LIBRARY_MARTS.POLITICS.POLITICS__FED_FJC_JUDGES) p_nid,
 (SELECT COUNT(*) FROM (SELECT NID FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_FJC_ARTICLE_III_JUDGES INTERSECT SELECT NID FROM LIBRARY_MARTS.POLITICS.POLITICS__FED_FJC_JUDGES)) both_nid,
 (SELECT LISTAGG(LAST_NAME||' '||NOMINATION_DATE_1, '; ') FROM (SELECT * FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_FJC_ARTICLE_III_JUDGES ORDER BY NOMINATION_DATE_1 DESC NULLS LAST LIMIT 3)) newest_a;

-- [54] FEMA IA registrations
WITH b AS (SELECT *, TRY_TO_DOUBLE(GROSS_INCOME::varchar) gi, TRY_TO_DOUBLE(IHP_AMOUNT::varchar) ihp FROM LIBRARY_MARTS.HOUSING.HOUSING__FED_FEMA_IA_HOUSING_REGISTRATIONS)
SELECT COUNT(*) n, COUNT(DISTINCT REGISTRATION_ID) regs, APPROX_COUNT_DISTINCT(REGISTRATION_ID||'|'||DISASTER_NUMBER) reg_dis, COUNT(DISTINCT _SOURCE_RUN_ID) runs, COUNT(DISTINCT DISASTER_NUMBER) disasters, COUNT(gi) gi_filled, MIN(gi), APPROX_PERCENTILE(gi,0.5) gi_med, MAX(gi), COUNT_IF(gi=0) gi_zero, COUNT_IF(ihp>0) ihp_pos, ROUND(SUM(ihp)/1e9,2) ihp_bn, MIN(APPLIED_DATE) d0, MAX(APPLIED_DATE) d1 FROM b;

-- [55] FEMA gross income raw + top disasters
SELECT 'gi' k, GROSS_INCOME::varchar v, COUNT(*) n, NULL bn FROM LIBRARY_MARTS.HOUSING.HOUSING__FED_FEMA_IA_HOUSING_REGISTRATIONS GROUP BY 1,2
UNION ALL SELECT * FROM (SELECT 'disaster', DISASTER_NUMBER::varchar||' '||ANY_VALUE(DAMAGED_STATE_ABBREVIATION)||' '||MIN(DECLARATION_DATE)::varchar, COUNT(*), ROUND(SUM(TRY_TO_DOUBLE(IHP_AMOUNT::varchar))/1e9,2) FROM LIBRARY_MARTS.HOUSING.HOUSING__FED_FEMA_IA_HOUSING_REGISTRATIONS GROUP BY DISASTER_NUMBER ORDER BY 4 DESC NULLS LAST LIMIT 10)
ORDER BY 1,3 DESC;

-- [56] HUDOC
SELECT DOC_TYPE, COUNT(*) n, COUNT(DISTINCT APPNO) apps, COUNT(NULLIF(VIOLATION,'')) viol_filled, MIN(JUDGMENT_DATE) d0, MAX(JUDGMENT_DATE) d1, ANY_VALUE(LEFT(VIOLATION,40)) ex_v, ANY_VALUE(RESPONDENT) ex_r FROM LIBRARY_MARTS.JUSTICE.JUSTICE__INTL_HUDOC GROUP BY 1 ORDER BY 2 DESC LIMIT 10;

-- [57] HUDOC
SELECT RESPONDENT, COUNT(DISTINCT APPNO) judgments_w_violation, COUNT(*) docs FROM LIBRARY_MARTS.JUSTICE.JUSTICE__INTL_HUDOC WHERE NULLIF(TRIM(VIOLATION),'') IS NOT NULL GROUP BY 1 ORDER BY 2 DESC LIMIT 10;

-- [58] member money tables
SELECT CYCLE, COUNT(*) n, COUNT(DISTINCT BIOGUIDE) members, SUM(SELF_CONTRIB_15C) self_sum, COUNT_IF(SELF_CONTRIB_15C>0) self_pos, MAX(SELF_CONTRIB_15C) self_max, MEDIAN(ITEMIZED_INDIV) med_item, MEDIAN(EARMARKED_SHARE) med_earmark_share, MAX(REATTRIB_AMOUNT) max_reattr FROM LIBRARY_MARTS.POLITICS.POLITICS__MEMBER_INDIV_DONATIONS GROUP BY 1 ORDER BY 1;

-- [59] member money tables
SELECT FULL_NAME, STATE, CHAMBER, PARTY, CYCLE, SELF_CONTRIB_15C, ITEMIZED_INDIV, EARMARKED_SHARE, REATTRIB_AMOUNT FROM LIBRARY_MARTS.POLITICS.POLITICS__MEMBER_INDIV_DONATIONS ORDER BY SELF_CONTRIB_15C DESC NULLS LAST LIMIT 8;

-- [60] member money tables
SELECT CYCLE, COUNT(*) n, MEDIAN(TTL_RECEIPTS_GROSS) med, MAX(TTL_RECEIPTS_GROSS) mx, ROUND(SUM(TTL_RECEIPTS_GROSS)/1e6) sum_mn, COUNT_IF(N_CANDIDATE_IDS>1) multi_ids, MAX(N_CANDIDATE_IDS) max_ids, MAX_BY(FULL_NAME, TTL_RECEIPTS_GROSS) top_name, COUNT_IF(MONEY_RAISED_NET>TTL_RECEIPTS_GROSS) net_gt_gross FROM LIBRARY_MARTS.POLITICS.POLITICS__MEMBER_MONEY_RAISED GROUP BY 1 ORDER BY 1;

-- [61] BJS NCVS
SELECT SERIES_FLAG::varchar sf, COUNT(*) n, COUNT(DISTINCT PERSON_ID) persons, MIN(SURVEY_YEAR) y0, MAX(SURVEY_YEAR) y1, COUNT(DISTINCT SURVEY_YEAR) yrs, MIN(TRY_TO_DOUBLE(VICTIMIZATION_WEIGHT::varchar)) wmin, MEDIAN(TRY_TO_DOUBLE(VICTIMIZATION_WEIGHT::varchar)) wmed, MAX(TRY_TO_DOUBLE(VICTIMIZATION_WEIGHT::varchar)) wmax, ROUND(SUM(TRY_TO_DOUBLE(VICTIMIZATION_WEIGHT::varchar))/1e6,1) weighted_mn, COUNT_IF(TRY_TO_DOUBLE(VICTIMIZATION_WEIGHT::varchar)>10*9000) over10x FROM LIBRARY_MARTS.CRIMINAL_JUSTICE.CRIMINAL_JUSTICE__FED_BJS_DATA GROUP BY 1;

-- [62] BJS NCVS
SELECT PERSON_ID, COUNT(*) n, MIN(SURVEY_YEAR) y0, MAX(SURVEY_YEAR) y1, ANY_VALUE(SERIES_FLAG) sf FROM LIBRARY_MARTS.CRIMINAL_JUSTICE.CRIMINAL_JUSTICE__FED_BJS_DATA GROUP BY 1 ORDER BY 2 DESC LIMIT 8;

-- [63] SBA 7A vintage charge-off on all funded loans
SELECT YEAR(APPROVAL_DATE) yr, COUNT_IF(LOAN_STATUS<>'CANCLD') funded, COUNT_IF(LOAN_STATUS='CHGOFF') chgoff, COUNT_IF(LOAN_STATUS IN ('CURR','DELINQ','PSTDUE','DEFERD','LIQUID','PURCH(NOT C/O)')) still_open,
 ROUND(COUNT_IF(LOAN_STATUS='CHGOFF')/NULLIF(COUNT_IF(LOAN_STATUS<>'CANCLD'),0),3) co_share_all, ROUND(SUM(GROSS_CHARGEOFF_AMOUNT)/NULLIF(SUM(IFF(LOAN_STATUS<>'CANCLD',GROSS_APPROVAL_AMOUNT,0)),0),3) co_dollar_share,
 MIN(CHARGEOFF_DATE) co0, MEDIAN(DATEDIFF(month, APPROVAL_DATE, CHARGEOFF_DATE)) med_months_to_co
FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_SBA_LOANS WHERE TRIM(PROGRAM)='7A' AND YEAR(APPROVAL_DATE) BETWEEN 2004 AND 2025 GROUP BY 1 ORDER BY 1;

