-- [1]
-- columns for all tables in my rows
SELECT table_name, LISTAGG(column_name||':'||data_type, ', ') WITHIN GROUP (ORDER BY ordinal_position) cols
FROM LIBRARY_MARTS.INFORMATION_SCHEMA.COLUMNS
WHERE table_name IN ('CORPORATE_REGISTRY__FED_IRS_EO_BMF','ECONOMICS__FED_FAC_SINGLE_AUDIT','FINANCE__FED_IRS527_SCHEDULE_B_EXPENDITURES','HEALTH__FQHC_SITE_PEOPLE','FINANCE__FED_EPA_ICIS_FEC_CASE_ENFORCEMENT_CONCLUSION_FACILITIES','ENVIRONMENT__FED_EPA_ECHO','LABOR__FED_OSHA_ITA_300A_SUMMARY_2025','HEALTH__FED_CMS_QUALITY_PAYMENT_PROGRAM_EXPERIENCE','HEALTH__FED_CMS_MEDICARE_PROVIDER','HEALTH__FED_CMS_MEDICARE_DURABLE_MEDICAL_EQUIPMENT_DEVICES_SUPPLIES_BY_REFER','HEALTH__FED_CMS_MEDICARE_DURABLE_MEDICAL_EQUIPMENT_DEVICES_SUPPLIES_BY_SUPPL','HEALTH__FED_CMS_OPEN_PAYMENTS')
GROUP BY 1
;

-- [2]
SELECT * FROM LIBRARY_MARTS.HEALTH.HEALTH__FQHC_SITE_PEOPLE LIMIT 5
;

-- [3]
-- FQHC site people: shape, match notes, campus flag
SELECT MATCH_NOTE, IS_HIGH_DENSITY_CAMPUS, COUNT(*) n, COUNT(DISTINCT NPI) npis, COUNT(DISTINCT BPHC_ASSIGNED_NUMBER) sites, MEDIAN(PEOPLE_AT_SITE) med_ppl, MAX(PEOPLE_AT_SITE) max_ppl, COUNT_IF(IS_EXCLUDED) excl, COUNT_IF(IS_OPTED_OUT) optout, COUNT_IF(NPI_DEACTIVATION_DATE IS NOT NULL) deact
FROM LIBRARY_MARTS.HEALTH.HEALTH__FQHC_SITE_PEOPLE GROUP BY ROLLUP(1,2) ORDER BY 1,2
;

-- [4]
-- FQHC NPIs landing in each of the 10 CMS NPI tables
WITH f AS (SELECT DISTINCT TRIM(NPI) npi FROM LIBRARY_MARTS.HEALTH.HEALTH__FQHC_SITE_PEOPLE WHERE REGEXP_LIKE(TRIM(NPI),'^[0-9]{10}$'))
SELECT 'fqhc' t, COUNT(*) n FROM f
UNION ALL SELECT 'DME_REFER', COUNT(DISTINCT TRIM(RFRG_NPI)) FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_MEDICARE_DURABLE_MEDICAL_EQUIPMENT_DEVICES_SUPPLIES_BY_REFER WHERE TRIM(RFRG_NPI) IN (SELECT npi FROM f)
UNION ALL SELECT 'DME_SUPPL', COUNT(DISTINCT TRIM(SUPLR_NPI)) FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_MEDICARE_DURABLE_MEDICAL_EQUIPMENT_DEVICES_SUPPLIES_BY_SUPPL WHERE TRIM(SUPLR_NPI) IN (SELECT npi FROM f)
UNION ALL SELECT 'PHYS_BY_SERVICE', COUNT(DISTINCT TRIM(RNDRNG_NPI)) FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_MEDICARE_PHYSICIAN_OTHER_PRACTITIONERS_BY_PROVIDER_AND_SERVI WHERE TRIM(RNDRNG_NPI) IN (SELECT npi FROM f)
UNION ALL SELECT 'PHYS_BY_PROVIDER', COUNT(DISTINCT TRIM(RNDRNG_NPI)) FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_MEDICARE_PHYSICIAN_OTHER_PRACTITIONERS_BY_PROVIDER WHERE TRIM(RNDRNG_NPI) IN (SELECT npi FROM f)
UNION ALL SELECT 'MEDICARE_PROVIDER', COUNT(DISTINCT TRIM(NPI)) FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_MEDICARE_PROVIDER WHERE TRIM(NPI) IN (SELECT npi FROM f)
UNION ALL SELECT 'OP_2022', COUNT(DISTINCT TRIM(NPI)) FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_OPEN_PAYMENTS_2022 WHERE TRIM(NPI) IN (SELECT npi FROM f)
UNION ALL SELECT 'OP_2023', COUNT(DISTINCT TRIM(NPI)) FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_OPEN_PAYMENTS_2023 WHERE TRIM(NPI) IN (SELECT npi FROM f)
UNION ALL SELECT 'OP', COUNT(DISTINCT TRIM(NPI)) FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_OPEN_PAYMENTS WHERE TRIM(NPI) IN (SELECT npi FROM f)
UNION ALL SELECT 'PARTD', COUNT(DISTINCT TRIM(NPI)) FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_PARTD_PRESCRIBERS WHERE TRIM(NPI) IN (SELECT npi FROM f)
UNION ALL SELECT 'QPP', COUNT(DISTINCT TRIM(NPI)) FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_QUALITY_PAYMENT_PROGRAM_EXPERIENCE WHERE TRIM(NPI) IN (SELECT npi FROM f)
;

-- [5]
-- FQHC x provider-level CMS tables: name + state agreement, allowed $ matched vs unmatched
WITH f AS (SELECT TRIM(NPI) npi, MAX(UPPER(LAST_NAME)) ln, ARRAY_AGG(DISTINCT SITE_STATE) sts, MAX(IFF(IS_HIGH_DENSITY_CAMPUS,1,0)) campus FROM LIBRARY_MARTS.HEALTH.HEALTH__FQHC_SITE_PEOPLE WHERE REGEXP_LIKE(TRIM(NPI),'^[0-9]{10}$') GROUP BY 1),
p AS (SELECT TRIM(RNDRNG_NPI) npi, MAX(UPPER(RNDRNG_PRVDR_LAST_ORG_NAME)) ln, MAX(RNDRNG_PRVDR_STATE_ABRVTN) st, SUM(TOT_MDCR_ALOWD_AMT) amt FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_MEDICARE_PHYSICIAN_OTHER_PRACTITIONERS_BY_PROVIDER GROUP BY 1),
mp AS (SELECT TRIM(NPI) npi, SUM(TOT_MDCR_ALOWD_AMT) amt FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_MEDICARE_PROVIDER GROUP BY 1),
d AS (SELECT TRIM(RFRG_NPI) npi, MAX(UPPER(RFRG_PRVDR_LAST_NAME_ORG)) ln, MAX(RFRG_PRVDR_STATE_ABRVTN) st, SUM(SUPLR_MDCR_ALOWD_AMT) amt FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_MEDICARE_DURABLE_MEDICAL_EQUIPMENT_DEVICES_SUPPLIES_BY_REFER GROUP BY 1),
q AS (SELECT TRIM(NPI) npi, NULL ln, MAX(PRACTICE_STATE_OR_US_TERRITORY) st, SUM(ALLOWED_CHARGES) amt, COUNT(*) r FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_QUALITY_PAYMENT_PROGRAM_EXPERIENCE WHERE PARTICIPATION_OPTION='Individual' GROUP BY 1)
SELECT 'PHYS_BY_PROVIDER' t, COUNT(f.npi) matched, COUNT_IF(f.npi IS NOT NULL AND f.ln=p.ln) name_ok, COUNT_IF(f.npi IS NOT NULL AND ARRAY_CONTAINS(p.st::variant, f.sts)) st_ok,
  MEDIAN(IFF(f.npi IS NOT NULL, p.amt, NULL)) med_matched, MEDIAN(IFF(f.npi IS NULL, p.amt, NULL)) med_unmatched, SUM(IFF(f.npi IS NOT NULL, p.amt, 0)) sum_matched, COUNT(*) all_npis,
  MEDIAN(IFF(f.campus=0, p.amt, NULL)) med_matched_noncampus FROM p LEFT JOIN f USING(npi)
UNION ALL SELECT 'MEDICARE_PROVIDER', COUNT(f.npi), NULL, NULL, MEDIAN(IFF(f.npi IS NOT NULL, mp.amt, NULL)), MEDIAN(IFF(f.npi IS NULL, mp.amt, NULL)), SUM(IFF(f.npi IS NOT NULL, mp.amt, 0)), COUNT(*), (SELECT COUNT(*) FROM mp JOIN p USING(npi) WHERE ABS(mp.amt-p.amt)<1) FROM mp LEFT JOIN f USING(npi)
UNION ALL SELECT 'DME_REFER', COUNT(f.npi), COUNT_IF(f.npi IS NOT NULL AND f.ln=d.ln), COUNT_IF(f.npi IS NOT NULL AND ARRAY_CONTAINS(d.st::variant, f.sts)),
  MEDIAN(IFF(f.npi IS NOT NULL, d.amt, NULL)), MEDIAN(IFF(f.npi IS NULL, d.amt, NULL)), SUM(IFF(f.npi IS NOT NULL, d.amt, 0)), COUNT(*), MEDIAN(IFF(f.campus=0, d.amt, NULL)) FROM d LEFT JOIN f USING(npi)
UNION ALL SELECT 'QPP_indiv', COUNT(f.npi), NULL, COUNT_IF(f.npi IS NOT NULL AND ARRAY_CONTAINS(q.st::variant, f.sts)),
  MEDIAN(IFF(f.npi IS NOT NULL, q.amt, NULL)), MEDIAN(IFF(f.npi IS NULL, q.amt, NULL)), SUM(IFF(f.npi IS NOT NULL, q.amt, 0)), COUNT(*), MAX(q.r) FROM q LEFT JOIN f USING(npi)
;

-- [6]
-- FQHC x Open Payments (3 tables) and Part D: state agreement, $ matched vs unmatched
WITH f AS (SELECT TRIM(NPI) npi, MAX(UPPER(LAST_NAME)) ln, ARRAY_AGG(DISTINCT SITE_STATE) sts, MAX(IFF(IS_HIGH_DENSITY_CAMPUS,1,0)) campus FROM LIBRARY_MARTS.HEALTH.HEALTH__FQHC_SITE_PEOPLE WHERE REGEXP_LIKE(TRIM(NPI),'^[0-9]{10}$') GROUP BY 1),
o AS (SELECT 'OP' t, TRIM(NPI) npi, MAX(UPPER(COVERED_RECIPIENT_LAST_NAME)) ln, MAX(RECIPIENT_STATE) st, SUM(TOTAL_AMOUNT_OF_PAYMENT_USDOLLARS) amt, MIN(PROGRAM_YEAR)||'-'||MAX(PROGRAM_YEAR) yr FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_OPEN_PAYMENTS WHERE NULLIF(TRIM(NPI),'') IS NOT NULL GROUP BY 2
  UNION ALL SELECT 'OP_2023', TRIM(NPI), MAX(UPPER(COVERED_RECIPIENT_LAST_NAME)), MAX(RECIPIENT_STATE), SUM(TOTAL_AMOUNT_OF_PAYMENT_USDOLLARS), MIN(PROGRAM_YEAR)||'-'||MAX(PROGRAM_YEAR) FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_OPEN_PAYMENTS_2023 WHERE NULLIF(TRIM(NPI),'') IS NOT NULL GROUP BY 2
  UNION ALL SELECT 'OP_2022', TRIM(NPI), MAX(UPPER(COVERED_RECIPIENT_LAST_NAME)), MAX(RECIPIENT_STATE), SUM(TOTAL_AMOUNT_OF_PAYMENT_USDOLLARS), MIN(PROGRAM_YEAR)||'-'||MAX(PROGRAM_YEAR) FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_OPEN_PAYMENTS_2022 WHERE NULLIF(TRIM(NPI),'') IS NOT NULL GROUP BY 2
  UNION ALL SELECT 'PARTD', TRIM(NPI), MAX(UPPER(PRESCRIBER_LAST_ORG_NAME)), MAX(PRESCRIBER_STATE), SUM(TRY_TO_DOUBLE(TOTAL_DRUG_COST::string)), MIN(DATA_YEAR)||'-'||MAX(DATA_YEAR) FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_PARTD_PRESCRIBERS GROUP BY 2)
SELECT o.t, COUNT(f.npi) matched, COUNT_IF(f.npi IS NOT NULL AND f.ln=o.ln) name_ok, COUNT_IF(f.npi IS NOT NULL AND ARRAY_CONTAINS(o.st::variant, f.sts)) st_ok,
  MEDIAN(IFF(f.npi IS NOT NULL, o.amt, NULL)) med_matched, MEDIAN(IFF(f.npi IS NULL, o.amt, NULL)) med_unmatched, SUM(IFF(f.npi IS NOT NULL, o.amt, 0)) sum_matched, SUM(o.amt) sum_all, COUNT(*) all_npis, MAX(o.yr) yrs,
  MEDIAN(IFF(f.campus=0, o.amt, NULL)) med_noncampus
FROM o LEFT JOIN f USING(npi) GROUP BY 1
;

-- [7]
-- EIN land: six OSHA tables vs EO BMF, FAC auditee EIN, FAC auditor EIN, IRS527 Sched B (padded to 9, 000000000 dropped); plus state agreement
WITH o AS (
  SELECT 'A300_2023' t, LPAD(REGEXP_REPLACE(EIN,'[^0-9]',''),9,'0') e, MODE(STATE) st, MODE(UPPER(COMPANY_NAME)) nm, SUM(TOTAL_DEATHS) deaths, COUNT(*) sites FROM LIBRARY_MARTS.LABOR.LABOR__FED_OSHA_ITA_300A_SUMMARY_2023 GROUP BY 2
  UNION ALL SELECT 'A300_2024', LPAD(REGEXP_REPLACE(EIN,'[^0-9]',''),9,'0'), MODE(STATE), MODE(UPPER(COMPANY_NAME)), SUM(TOTAL_DEATHS), COUNT(*) FROM LIBRARY_MARTS.LABOR.LABOR__FED_OSHA_ITA_300A_SUMMARY_2024 GROUP BY 2
  UNION ALL SELECT 'A300_2025', LPAD(REGEXP_REPLACE(EIN,'[^0-9]',''),9,'0'), MODE(STATE), MODE(UPPER(COMPANY_NAME)), SUM(TOTAL_DEATHS), COUNT(*) FROM LIBRARY_MARTS.LABOR.LABOR__FED_OSHA_ITA_300A_SUMMARY_2025 GROUP BY 2
  UNION ALL SELECT 'CD_2023', LPAD(REGEXP_REPLACE(EIN,'[^0-9]',''),9,'0'), MODE(STATE), MODE(UPPER(COMPANY_NAME)), COUNT_IF(INCIDENT_OUTCOME::string='1'), COUNT(*) FROM LIBRARY_MARTS.LABOR.LABOR__FED_OSHA_ITA_CASE_DETAIL_2023 GROUP BY 2
  UNION ALL SELECT 'CD_2024', LPAD(REGEXP_REPLACE(EIN,'[^0-9]',''),9,'0'), MODE(STATE), MODE(UPPER(COMPANY_NAME)), COUNT_IF(INCIDENT_OUTCOME::string='1'), COUNT(*) FROM LIBRARY_MARTS.LABOR.LABOR__FED_OSHA_ITA_CASE_DETAIL_2024 GROUP BY 2
  UNION ALL SELECT 'CD_2025', LPAD(REGEXP_REPLACE(EIN,'[^0-9]',''),9,'0'), MODE(STATE), MODE(UPPER(COMPANY_NAME)), COUNT_IF(INCIDENT_OUTCOME::string='1'), COUNT(*) FROM LIBRARY_MARTS.LABOR.LABOR__FED_OSHA_ITA_CASE_DETAIL_2025 GROUP BY 2),
o2 AS (SELECT * FROM o WHERE LENGTH(REGEXP_REPLACE(e,'[^0-9]',''))=9 AND e<>'000000000' AND LENGTH(e)=9),
b AS (SELECT LPAD(REGEXP_REPLACE(EIN,'[^0-9]',''),9,'0') e, MAX(STATE) st FROM LIBRARY_MARTS.CORPORATE_REGISTRY.CORPORATE_REGISTRY__FED_IRS_EO_BMF GROUP BY 1),
fa AS (SELECT LPAD(REGEXP_REPLACE(AUDITEE_EIN,'[^0-9]',''),9,'0') e, MODE(AUDITEE_STATE) st FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_FAC_SINGLE_AUDIT GROUP BY 1),
fr AS (SELECT DISTINCT LPAD(REGEXP_REPLACE(AUDITOR_EIN,'[^0-9]',''),9,'0') e FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_FAC_SINGLE_AUDIT),
s AS (SELECT DISTINCT LPAD(REGEXP_REPLACE(EIN,'[^0-9]',''),9,'0') e FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_IRS527_SCHEDULE_B_EXPENDITURES)
SELECT o2.t, COUNT(*) osha_eins, SUM(o2.sites) osha_rows,
  COUNT(b.e) bmf_land, COUNT_IF(b.st=o2.st) bmf_st_ok,
  COUNT(fa.e) fac_land, COUNT_IF(fa.st=o2.st) fac_st_ok,
  COUNT_IF(o2.e IN (SELECT e FROM fr)) auditor_land,
  COUNT_IF(o2.e IN (SELECT e FROM s)) s527b_land,
  SUM(IFF(b.e IS NOT NULL, o2.deaths,0)) bmf_deaths, SUM(IFF(b.e IS NULL, o2.deaths,0)) nonbmf_deaths,
  SUM(IFF(fa.e IS NOT NULL, o2.deaths,0)) fac_deaths, SUM(o2.deaths) all_deaths
FROM o2 LEFT JOIN b ON b.e=o2.e LEFT JOIN fa ON fa.e=o2.e GROUP BY 1 ORDER BY 1
;

-- [8]
-- BMF gap: ASSET_AMT for BMF EINs that land in any OSHA 300A year vs not; NTEE mix of matched
WITH a AS (SELECT DISTINCT LPAD(REGEXP_REPLACE(EIN,'[^0-9]',''),9,'0') e FROM (SELECT EIN FROM LIBRARY_MARTS.LABOR.LABOR__FED_OSHA_ITA_300A_SUMMARY_2023 UNION ALL SELECT EIN FROM LIBRARY_MARTS.LABOR.LABOR__FED_OSHA_ITA_300A_SUMMARY_2024 UNION ALL SELECT EIN FROM LIBRARY_MARTS.LABOR.LABOR__FED_OSHA_ITA_300A_SUMMARY_2025 UNION ALL SELECT EIN FROM LIBRARY_MARTS.LABOR.LABOR__FED_OSHA_ITA_CASE_DETAIL_2025)),
b AS (SELECT LPAD(REGEXP_REPLACE(EIN,'[^0-9]',''),9,'0') e, MAX(ASSET_AMT) asset, MAX(LEFT(NTEE_CODE,1)) ntee FROM LIBRARY_MARTS.CORPORATE_REGISTRY.CORPORATE_REGISTRY__FED_IRS_EO_BMF GROUP BY 1)
SELECT IFF(a.e IS NULL,'unmatched','matched') grp, b.ntee, COUNT(*) n, MEDIAN(asset) med_asset, SUM(asset) sum_asset
FROM b LEFT JOIN a ON a.e=b.e GROUP BY ROLLUP(1,2) HAVING b.ntee IS NULL OR COUNT(*)>2000 OR grp='matched' ORDER BY 1, 3 DESC
;

-- [9]
-- 20-row name sample, BMF x OSHA 300A 2025 and FAC x OSHA 300A 2025
WITH o AS (SELECT LPAD(REGEXP_REPLACE(EIN,'[^0-9]',''),9,'0') e, MODE(UPPER(COMPANY_NAME)) cn, MODE(UPPER(ESTABLISHMENT_NAME)) en, MODE(STATE) st FROM LIBRARY_MARTS.LABOR.LABOR__FED_OSHA_ITA_300A_SUMMARY_2025 GROUP BY 1),
b AS (SELECT LPAD(REGEXP_REPLACE(EIN,'[^0-9]',''),9,'0') e, MAX(ORG_NAME) bn, MAX(STATE) bst FROM LIBRARY_MARTS.CORPORATE_REGISTRY.CORPORATE_REGISTRY__FED_IRS_EO_BMF GROUP BY 1),
fa AS (SELECT LPAD(REGEXP_REPLACE(AUDITEE_EIN,'[^0-9]',''),9,'0') e, MAX(AUDITEE_NAME) fn, MODE(AUDITEE_STATE) fst FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_FAC_SINGLE_AUDIT GROUP BY 1)
(SELECT 'BMF' k, o.e, o.cn, o.en, o.st, b.bn other_name, b.bst other_st, JAROWINKLER_SIMILARITY(COALESCE(o.cn,''), UPPER(b.bn)) jw FROM o JOIN b USING(e) WHERE o.e<>'000000000' ORDER BY HASH(o.e) LIMIT 20)
UNION ALL
(SELECT 'FAC', o.e, o.cn, o.en, o.st, fa.fn, fa.fst, JAROWINKLER_SIMILARITY(COALESCE(o.cn,''), UPPER(fa.fn)) FROM o JOIN fa USING(e) WHERE o.e<>'000000000' ORDER BY HASH(o.e) LIMIT 20)
;

-- [10]
-- FAC gap: latest TOTAL_AMOUNT_EXPENDED for auditees landing in any OSHA 300A year vs not, by entity type
WITH a AS (SELECT LPAD(REGEXP_REPLACE(EIN,'[^0-9]',''),9,'0') e, SUM(TOTAL_DEATHS) deaths, SUM(ANNUAL_AVERAGE_EMPLOYEES) emp FROM (SELECT EIN, TOTAL_DEATHS, ANNUAL_AVERAGE_EMPLOYEES FROM LIBRARY_MARTS.LABOR.LABOR__FED_OSHA_ITA_300A_SUMMARY_2023 UNION ALL SELECT EIN, TOTAL_DEATHS, ANNUAL_AVERAGE_EMPLOYEES FROM LIBRARY_MARTS.LABOR.LABOR__FED_OSHA_ITA_300A_SUMMARY_2024 UNION ALL SELECT EIN, TOTAL_DEATHS, ANNUAL_AVERAGE_EMPLOYEES FROM LIBRARY_MARTS.LABOR.LABOR__FED_OSHA_ITA_300A_SUMMARY_2025) GROUP BY 1),
f AS (SELECT LPAD(REGEXP_REPLACE(AUDITEE_EIN,'[^0-9]',''),9,'0') e, MAX_BY(TOTAL_AMOUNT_EXPENDED, AUDIT_YEAR) amt, MAX_BY(ENTITY_TYPE, AUDIT_YEAR) et, MAX(AUDIT_YEAR) y, MIN(AUDIT_YEAR) y0 FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_FAC_SINGLE_AUDIT GROUP BY 1)
SELECT IFF(a.e IS NULL,'unmatched','matched') grp, f.et, COUNT(*) n, MEDIAN(amt) med_amt, SUM(amt) sum_amt, SUM(a.deaths) deaths, MIN(y0) y0, MAX(y) y1
FROM f LEFT JOIN a ON a.e=f.e AND a.e<>'000000000' GROUP BY 1,2 ORDER BY 1,3 DESC
;

-- [11]
-- top FAC auditees by OSHA deaths 2023-25, with federal $ and audit flags
WITH a AS (SELECT LPAD(REGEXP_REPLACE(EIN,'[^0-9]',''),9,'0') e, SUM(TOTAL_DEATHS) deaths, MODE(UPPER(COMPANY_NAME)) cn, COUNT(DISTINCT ESTABLISHMENT_ID) sites, SUM(ANNUAL_AVERAGE_EMPLOYEES) emp FROM (SELECT EIN, TOTAL_DEATHS, COMPANY_NAME, ESTABLISHMENT_ID, ANNUAL_AVERAGE_EMPLOYEES FROM LIBRARY_MARTS.LABOR.LABOR__FED_OSHA_ITA_300A_SUMMARY_2023 UNION ALL SELECT EIN, TOTAL_DEATHS, COMPANY_NAME, ESTABLISHMENT_ID, ANNUAL_AVERAGE_EMPLOYEES FROM LIBRARY_MARTS.LABOR.LABOR__FED_OSHA_ITA_300A_SUMMARY_2024 UNION ALL SELECT EIN, TOTAL_DEATHS, COMPANY_NAME, ESTABLISHMENT_ID, ANNUAL_AVERAGE_EMPLOYEES FROM LIBRARY_MARTS.LABOR.LABOR__FED_OSHA_ITA_300A_SUMMARY_2025) GROUP BY 1),
f AS (SELECT LPAD(REGEXP_REPLACE(AUDITEE_EIN,'[^0-9]',''),9,'0') e, MAX(AUDITEE_NAME) fn, MAX_BY(TOTAL_AMOUNT_EXPENDED, AUDIT_YEAR) amt, MAX_BY(ENTITY_TYPE, AUDIT_YEAR) et, MAX(AUDITEE_STATE) st, COUNT_IF(IS_MATERIAL_NONCOMPLIANCE_DISCLOSED ILIKE 'y%') noncomp, COUNT_IF(IS_GOING_CONCERN_INCLUDED ILIKE 'y%') gc FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_FAC_SINGLE_AUDIT GROUP BY 1)
SELECT a.e, a.cn, f.fn, f.st, f.et, a.deaths, a.sites, a.emp, f.amt, f.noncomp, f.gc FROM a JOIN f USING(e) WHERE a.e<>'000000000' ORDER BY a.deaths DESC NULLS LAST LIMIT 15
;

-- [12]
-- ECHO x ICIS FEC case conclusion facilities: land rate, state agreement, penalties matched vs unmatched
WITH c AS (SELECT TRIM(FACILITY_UIN) r, COUNT(DISTINCT ENF_CONCLUSION_ID) concl, COUNT(DISTINCT CASE_NUMBER) cases, MODE(FACILITY_STATE) st, MAX(UPPER(FACILITY_NAME)) cn FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_EPA_ICIS_FEC_CASE_ENFORCEMENT_CONCLUSION_FACILITIES WHERE NULLIF(TRIM(FACILITY_UIN),'') IS NOT NULL GROUP BY 1),
e AS (SELECT TRIM(FRS_ID) r, MAX(STATE) st, MAX(UPPER(FACILITY_NAME)) en, MAX(TOTAL_PENALTIES) pen, MAX(PENALTY_COUNT) pc, MAX(FORMAL_ACTION_COUNT) fa, MAX(IFF(IS_ACTIVE,1,0)) act FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ECHO GROUP BY 1)
SELECT (SELECT COUNT(*) FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_EPA_ICIS_FEC_CASE_ENFORCEMENT_CONCLUSION_FACILITIES) fec_rows, (SELECT COUNT(*) FROM c) fec_uins, (SELECT COUNT(*) FROM e) echo_ids,
  COUNT(c.r) both_, COUNT_IF(c.st=e.st) st_ok, COUNT_IF(JAROWINKLER_SIMILARITY(c.cn,e.en)>=85) name_ok,
  MEDIAN(IFF(c.r IS NOT NULL, e.pen, NULL)) med_pen_matched, MEDIAN(IFF(c.r IS NULL, e.pen, NULL)) med_pen_unmatched,
  AVG(IFF(c.r IS NOT NULL, IFF(e.pen>0,1,0), NULL)) pct_pen_matched, AVG(IFF(c.r IS NULL, IFF(e.pen>0,1,0), NULL)) pct_pen_unmatched,
  SUM(IFF(c.r IS NOT NULL, e.pen, 0)) sum_pen_matched, SUM(e.pen) sum_pen_all,
  COUNT_IF(c.r IS NOT NULL AND COALESCE(e.pen,0)=0) matched_zero_pen, COUNT_IF(c.r IS NOT NULL AND COALESCE(e.fa,0)=0) matched_zero_formal
FROM e LEFT JOIN c ON c.r=e.r
;

-- [13]
-- small public employers with 300A deaths: per-year 300A deaths vs case-detail death rows
WITH x AS (SELECT * FROM VALUES ('936000392'),('416008848'),('376002586'),('616001914') v(e))
SELECT '300A' src, YEAR_FILING_FOR::string y, LPAD(REGEXP_REPLACE(EIN,'[^0-9]',''),9,'0') e, MAX(ESTABLISHMENT_NAME) nm, SUM(TOTAL_DEATHS) deaths, SUM(ANNUAL_AVERAGE_EMPLOYEES) emp, MAX(INDUSTRY_DESCRIPTION) ind FROM (SELECT EIN, YEAR_FILING_FOR, ESTABLISHMENT_NAME, TOTAL_DEATHS, ANNUAL_AVERAGE_EMPLOYEES, INDUSTRY_DESCRIPTION FROM LIBRARY_MARTS.LABOR.LABOR__FED_OSHA_ITA_300A_SUMMARY_2023 UNION ALL SELECT EIN, YEAR_FILING_FOR, ESTABLISHMENT_NAME, TOTAL_DEATHS, ANNUAL_AVERAGE_EMPLOYEES, INDUSTRY_DESCRIPTION FROM LIBRARY_MARTS.LABOR.LABOR__FED_OSHA_ITA_300A_SUMMARY_2024 UNION ALL SELECT EIN, YEAR_FILING_FOR, ESTABLISHMENT_NAME, TOTAL_DEATHS, ANNUAL_AVERAGE_EMPLOYEES, INDUSTRY_DESCRIPTION FROM LIBRARY_MARTS.LABOR.LABOR__FED_OSHA_ITA_300A_SUMMARY_2025) WHERE LPAD(REGEXP_REPLACE(EIN,'[^0-9]',''),9,'0') IN (SELECT e FROM x) AND TOTAL_DEATHS>0 GROUP BY 1,2,3
UNION ALL
SELECT 'CD', '20'||t, LPAD(REGEXP_REPLACE(EIN,'[^0-9]',''),9,'0'), MAX(ESTABLISHMENT_NAME), COUNT_IF(INCIDENT_OUTCOME::string='1'), COUNT(*), NULL FROM (SELECT '23' t, EIN, ESTABLISHMENT_NAME, INCIDENT_OUTCOME FROM LIBRARY_MARTS.LABOR.LABOR__FED_OSHA_ITA_CASE_DETAIL_2023 UNION ALL SELECT '24', EIN, ESTABLISHMENT_NAME, INCIDENT_OUTCOME FROM LIBRARY_MARTS.LABOR.LABOR__FED_OSHA_ITA_CASE_DETAIL_2024 UNION ALL SELECT '25', EIN, ESTABLISHMENT_NAME, INCIDENT_OUTCOME FROM LIBRARY_MARTS.LABOR.LABOR__FED_OSHA_ITA_CASE_DETAIL_2025) WHERE LPAD(REGEXP_REPLACE(EIN,'[^0-9]',''),9,'0') IN (SELECT e FROM x) GROUP BY 1,2,3
ORDER BY 3,2,1
;

-- [14]
-- ECHO x FEC: is the "in a case conclusion but ECHO shows 0 formal actions" gap just ECHO's 5-year window? Year from CASE_NUMBER (NN-YYYY-NNNN)
WITH c AS (SELECT TRIM(FACILITY_UIN) r, MAX(TRY_TO_NUMBER(SPLIT_PART(CASE_NUMBER,'-',2))) y FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_EPA_ICIS_FEC_CASE_ENFORCEMENT_CONCLUSION_FACILITIES WHERE NULLIF(TRIM(FACILITY_UIN),'') IS NOT NULL GROUP BY 1),
e AS (SELECT TRIM(FRS_ID) r, MAX(TOTAL_PENALTIES) pen, MAX(FORMAL_ACTION_COUNT) fa, MAX(DATE_LAST_FORMAL_ACTION) dlf FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ECHO GROUP BY 1)
SELECT CASE WHEN c.y IS NULL OR c.y NOT BETWEEN 1970 AND 2026 THEN 'no year' WHEN c.y>=2021 THEN '2021+' WHEN c.y>=2016 THEN '2016-20' ELSE 'pre-2016' END yb,
  COUNT(*) n, COUNT_IF(COALESCE(e.fa,0)=0) zero_formal, COUNT_IF(COALESCE(e.pen,0)=0) zero_pen, MIN(e.dlf) min_dlf, MAX(e.dlf) max_dlf
FROM c JOIN e ON e.r=c.r GROUP BY 1 ORDER BY 1
;

-- [15]
-- FQHC (non-campus) NPIs: top 10 by Open Payments 2024 and by Part D cost, with city/state agreement
WITH f AS (SELECT TRIM(NPI) npi, MAX(UPPER(LAST_NAME)) ln, MAX(UPPER(SITE_CITY)) city, MAX(SITE_STATE) st, MAX(HEALTH_CENTER_NAME) hc, MAX(TAXONOMY_CODE_1) tx FROM LIBRARY_MARTS.HEALTH.HEALTH__FQHC_SITE_PEOPLE WHERE NOT IS_HIGH_DENSITY_CAMPUS GROUP BY 1),
o AS (SELECT TRIM(NPI) npi, SUM(TOTAL_AMOUNT_OF_PAYMENT_USDOLLARS) amt, MAX(UPPER(RECIPIENT_CITY)) city, MAX(RECIPIENT_STATE) st, MAX(COVERED_RECIPIENT_SPECIALTY_1) sp, MODE(NATURE_OF_PAYMENT_OR_TRANSFER_OF_VALUE) nat FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_OPEN_PAYMENTS WHERE TRIM(NPI) IN (SELECT npi FROM f) GROUP BY 1),
d AS (SELECT TRIM(NPI) npi, SUM(TRY_TO_DOUBLE(TOTAL_DRUG_COST::string)) amt, MAX(UPPER(PRESCRIBER_CITY)) city, MAX(PRESCRIBER_STATE) st, MAX(PRESCRIBER_TYPE) sp, NULL nat FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_PARTD_PRESCRIBERS WHERE TRIM(NPI) IN (SELECT npi FROM f) GROUP BY 1)
(SELECT 'OP2024' k, f.npi, f.ln, f.hc, f.city fcity, o.city ocity, f.st, o.st ost, o.sp, o.nat, o.amt FROM o JOIN f USING(npi) ORDER BY o.amt DESC LIMIT 10)
UNION ALL
(SELECT 'PARTD', f.npi, f.ln, f.hc, f.city, d.city, f.st, d.st, d.sp, NULL, d.amt FROM d JOIN f USING(npi) ORDER BY d.amt DESC LIMIT 10)
;

-- [16]
-- Part D DY2022: top drugs for the two biggest FQHC-address prescribers, and their rank among all prescribers of the same type
WITH t AS (SELECT TRIM(NPI) npi, MAX(PRESCRIBER_TYPE) pt, SUM(TRY_TO_DOUBLE(TOTAL_DRUG_COST::string)) cost FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_PARTD_PRESCRIBERS GROUP BY 1),
r AS (SELECT npi, pt, cost, RANK() OVER (PARTITION BY pt ORDER BY cost DESC) rk, COUNT(*) OVER (PARTITION BY pt) n_type, MEDIAN(cost) OVER (PARTITION BY pt) med_type FROM t),
d AS (SELECT TRIM(NPI) npi, GENERIC_NAME g, SUM(TRY_TO_DOUBLE(TOTAL_DRUG_COST::string)) cost, SUM(TRY_TO_NUMBER(TOTAL_CLAIMS::string)) clm, SUM(TRY_TO_NUMBER(TOTAL_BENEFICIARIES::string)) benes FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_PARTD_PRESCRIBERS WHERE TRIM(NPI) IN ('1366754715','1821068420') GROUP BY 1,2)
SELECT 'rank' k, r.npi, r.pt, NULL g, r.cost, r.rk, r.n_type, r.med_type FROM r WHERE r.npi IN ('1366754715','1821068420')
UNION ALL (SELECT 'drug', npi, NULL, g, cost, clm, benes, NULL FROM d QUALIFY ROW_NUMBER() OVER (PARTITION BY npi ORDER BY cost DESC)<=6)
ORDER BY 2,1 DESC,5 DESC
;

-- [17]
-- Hinojosa (NP, 1366754715): FQHC rows, Part B 2024 billing, Open Payments 2022-2024, Part D beneficiary count
SELECT 'fqhc' k, SITE_NAME a, HEALTH_CENTER_NAME b, SITE_ADDRESS c, TAXONOMY_CODE_1 d, PEOPLE_AT_SITE::string e, NPPES_LAST_UPDATE_DATE::string f FROM LIBRARY_MARTS.HEALTH.HEALTH__FQHC_SITE_PEOPLE WHERE TRIM(NPI)='1366754715'
UNION ALL SELECT 'partb', RNDRNG_PRVDR_TYPE, RNDRNG_PRVDR_ST1, RNDRNG_PRVDR_CITY, TOT_BENES::string, TOT_MDCR_ALOWD_AMT::string, DRUG_MDCR_ALOWD_AMT::string FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_MEDICARE_PHYSICIAN_OTHER_PRACTITIONERS_BY_PROVIDER WHERE TRIM(RNDRNG_NPI)='1366754715'
UNION ALL SELECT 'op'||PROGRAM_YEAR::int, APPLICABLE_MANUFACTURER_OR_APPLICABLE_GPO_MAKING_PAYMENT_NAME, NATURE_OF_PAYMENT_OR_TRANSFER_OF_VALUE, RECIPIENT_CITY, COUNT(*)::string, SUM(TOTAL_AMOUNT_OF_PAYMENT_USDOLLARS)::string, NULL FROM (SELECT * FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_OPEN_PAYMENTS WHERE TRIM(NPI)='1366754715' UNION ALL SELECT * FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_OPEN_PAYMENTS_2023 WHERE TRIM(NPI)='1366754715' UNION ALL SELECT * FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_OPEN_PAYMENTS_2022 WHERE TRIM(NPI)='1366754715') GROUP BY 1,2,3,4
UNION ALL SELECT 'partd_total', MAX(PRESCRIBER_CITY), MAX(PRESCRIBER_FIRST_NAME), COUNT(DISTINCT GENERIC_NAME)::string, SUM(TRY_TO_NUMBER(TOTAL_CLAIMS::string))::string, MAX(DATA_YEAR)::string, NULL FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_PARTD_PRESCRIBERS WHERE TRIM(NPI)='1366754715'
;

