-- [1] types of lead columns across the 25 claimed tables
SELECT table_schema, table_name, column_name, data_type FROM LIBRARY_MARTS.INFORMATION_SCHEMA.COLUMNS
WHERE table_name IN ('CORPORATE_REGISTRY__FED_IRS_EO_BMF','ECONOMICS__FED_IRS_BMF','EDUCATION__FED_SENATE_LDA_FILINGS','HEALTH__FED_CMS_NURSING_HOME','HEALTH__FED_NURSINGHOME411','JUSTICE__FED_COURTLISTENER_DISCLOSURE_NON_INVESTMENT_INCOME','JUSTICE__FED_COURTLISTENER_JUDGES','POLITICS__FED_CONGRESS_LEGISLATORS','POLITICS__MEMBER_CROSSWALK','ECONOMICS__FED_SBA_PPP','TRANSPORT__FED_FRA_CASUALTIES','HEALTH__FED_CMS_QUALITY_PAYMENT_PROGRAM_EXPERIENCE','IMMIGRATION__FED_ICE_DETAINERS','JUSTICE__FED_COURTLISTENER_DOCKETS','POLITICS__ST_NYC_CFB_CAMPAIGN_2021_CONTRIBUTIONS','HEALTH__FED_CMS_PARTD_PRESCRIBERS','POLITICS__ST_NYC_CFB_CAMPAIGN_2025_CONTRIBUTIONS','CONSUMER_PROTECTION__FED_CFPB_COMPLAINTS','CORPORATE_REGISTRY__UK_COMPANIES_HOUSE_PSC','HEALTH__FED_CMS_OPEN_PAYMENTS','HEALTH__FED_CMS_OPEN_PAYMENTS_2022','HEALTH__FED_CMS_OPEN_PAYMENTS_2023','JUSTICE__FED_COURTLISTENER_CITATIONS','POLITICS__ST_NYC_CFB_CAMPAIGN_2001_CONTRIBUTION','POLITICS__ST_NYC_CFB_CAMPAIGN_2009_CONTRIBUTION')
AND column_name IN ('ASSET_AMT','INCOME_AMT','REVENUE_AMT','INCOME','EXPENSES','FILING_YEAR','TOTAL_AMOUNT_OF_FINES_IN_DOLLARS','NUMBER_OF_FINES','ABUSE_ICON','INCOME_AMOUNT','FTM_TOTAL_RECEIVED','N_TERMS','LEGISLATOR_SET','INITIAL_APPROVAL_AMOUNT','CURRENT_APPROVAL_AMOUNT','DAYS_AWAY_FROM_WORK','FATALITY','DATE','ALLOWED_CHARGES','PAYMENT_ADJUSTMENT_PERCENTAGE','MSC_SENTENCE_DAYS','DETAINER_PREPARE_DATE','VIEW_COUNT','DATE_FILED','AMOUNT','MATCH_AMOUNT','TOTAL_DRUG_COST','DAYS_RECEIVED_TO_COMPANY','NOTIFIED_ON','TOTAL_AMOUNT_OF_PAYMENT_USDOLLARS','VOLUME','CONTRIBUTION_DATE','DATE_CREATED','FINAL_SCORE','INCIDENT_YEAR','DATE_RECEIVED','DOB_YEAR','PROGRAM_YEAR')
ORDER BY 2,3;

-- [2] EO_BMF profile ASSET_AMT (count, nulls, zeros, min, median, max, sum, top1pct share, distinct EIN)
WITH t AS (SELECT ASSET_AMT a, EIN FROM LIBRARY_MARTS.CORPORATE_REGISTRY.CORPORATE_REGISTRY__FED_IRS_EO_BMF),
r AS (SELECT a, PERCENT_RANK() OVER (ORDER BY a) pr FROM t WHERE a IS NOT NULL)
SELECT (SELECT COUNT(*) FROM t) n, (SELECT COUNT(DISTINCT EIN) FROM t) d_ein, (SELECT COUNT_IF(a IS NULL) FROM t) nulls, (SELECT COUNT_IF(a=0) FROM t) zeros,
 MIN(a), MEDIAN(a), MAX(a), SUM(a), SUM(IFF(pr>=0.99,a,0))/NULLIF(SUM(a),0) top1_share FROM r;

-- [3] EO_BMF top 10 by ASSET_AMT
SELECT EIN, ORG_NAME, STATE, SUBSECTION_CODE, FOUNDATION_CODE, NTEE_CODE, ASSET_AMT, INCOME_AMT, REVENUE_AMT, TAX_PERIOD_YYYYMM
FROM LIBRARY_MARTS.CORPORATE_REGISTRY.CORPORATE_REGISTRY__FED_IRS_EO_BMF ORDER BY ASSET_AMT DESC NULLS LAST LIMIT 12;

-- [4] IRS_BMF profile ASSET_AMT
WITH t AS (SELECT ASSET_AMT a, EIN FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_IRS_BMF),
r AS (SELECT a, PERCENT_RANK() OVER (ORDER BY a) pr FROM t WHERE a IS NOT NULL)
SELECT (SELECT COUNT(*) FROM t) n, (SELECT COUNT(DISTINCT EIN) FROM t) d_ein, (SELECT COUNT_IF(a IS NULL) FROM t) nulls, (SELECT COUNT_IF(a=0) FROM t) zeros,
 MIN(a), MEDIAN(a), MAX(a), SUM(a), SUM(IFF(pr>=0.99,a,0))/NULLIF(SUM(a),0) top1_share FROM r;

-- [5] IRS_BMF top 10 by ASSET_AMT
SELECT EIN, ORGANIZATION_NAME, STATE, SUBSECTION_CODE, NTEE_CODE, ASSET_AMT, INCOME_AMT, REVENUE_AMT, TAX_PERIOD, IRS_STATUS
FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_IRS_BMF ORDER BY ASSET_AMT DESC NULLS LAST LIMIT 12;

-- [6] LDA sample 5 + count
SELECT (SELECT COUNT(*) FROM LIBRARY_MARTS.EDUCATION.EDUCATION__FED_SENATE_LDA_FILINGS) n, FILING_UUID, FILING_YEAR, FILING_TYPE, REGISTRANT_NAME, CLIENT_NAME, INCOME, EXPENSES, TERMINATION_DATE
FROM LIBRARY_MARTS.EDUCATION.EDUCATION__FED_SENATE_LDA_FILINGS LIMIT 5;

-- [7] LDA profile INCOME (text): numeric share, min/median/max, by year span
WITH t AS (SELECT INCOME, TRY_TO_NUMBER(REPLACE(INCOME,',',''),38,2) a, FILING_YEAR, FILING_UUID FROM LIBRARY_MARTS.EDUCATION.EDUCATION__FED_SENATE_LDA_FILINGS)
SELECT COUNT(*) n, COUNT(DISTINCT FILING_UUID) d_uuid, COUNT_IF(INCOME IS NULL OR INCOME='') blank, COUNT_IF(a IS NULL AND INCOME<>'') nonnum,
 MIN(a), MEDIAN(a), MAX(a), SUM(a), MIN(FILING_YEAR), MAX(FILING_YEAR), COUNT_IF(a>=5000000) ge5m FROM t;

-- [8] LDA top 10 clients by summed INCOME
SELECT CLIENT_NAME, COUNT(*) filings, SUM(TRY_TO_NUMBER(REPLACE(INCOME,',',''),38,2)) inc, MAX(TRY_TO_NUMBER(REPLACE(INCOME,',',''),38,2)) mx, MIN(FILING_YEAR), MAX(FILING_YEAR)
FROM LIBRARY_MARTS.EDUCATION.EDUCATION__FED_SENATE_LDA_FILINGS GROUP BY 1 ORDER BY inc DESC NULLS LAST LIMIT 10;

-- [9] NH (CMS_NURSING_HOME) profile fines
SELECT COUNT(*) n, COUNT(DISTINCT CMS_CERTIFICATION_NUMBER_CCN) d_ccn, COUNT_IF(TOTAL_AMOUNT_OF_FINES_IN_DOLLARS IS NULL) nulls, COUNT_IF(TOTAL_AMOUNT_OF_FINES_IN_DOLLARS=0) zeros,
 MIN(TOTAL_AMOUNT_OF_FINES_IN_DOLLARS), MEDIAN(TOTAL_AMOUNT_OF_FINES_IN_DOLLARS), MAX(TOTAL_AMOUNT_OF_FINES_IN_DOLLARS), SUM(TOTAL_AMOUNT_OF_FINES_IN_DOLLARS),
 COUNT_IF(ABUSE_ICON IN ('Y','Yes','TRUE','true','1')) abuse_y, LISTAGG(DISTINCT ABUSE_ICON, ',') abuse_vals, LISTAGG(DISTINCT SPECIAL_FOCUS_STATUS, ',') sff_vals,
 MIN(PROCESSING_DATE), MAX(PROCESSING_DATE), COUNT(DATE_OF_MOST_RECENT_HEALTH_INSPECTION) inspdate_nonnull
FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_NURSING_HOME;

-- [10] NH top 12 by fines
SELECT CMS_CERTIFICATION_NUMBER_CCN, PROVIDER_NAME, STATE, CHAIN_NAME, NUMBER_OF_FINES, TOTAL_AMOUNT_OF_FINES_IN_DOLLARS, ABUSE_ICON, SPECIAL_FOCUS_STATUS, OVERALL_RATING, NUMBER_OF_CERTIFIED_BEDS
FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_NURSING_HOME ORDER BY TOTAL_AMOUNT_OF_FINES_IN_DOLLARS DESC NULLS LAST LIMIT 12;

-- [11] NH411 profile fines
SELECT COUNT(*) n, COUNT(DISTINCT CMS_CERTIFICATION_NUMBER_CCN) d_ccn, COUNT_IF(TOTAL_AMOUNT_OF_FINES_IN_DOLLARS IS NULL) nulls, COUNT_IF(TOTAL_AMOUNT_OF_FINES_IN_DOLLARS=0) zeros,
 MIN(TOTAL_AMOUNT_OF_FINES_IN_DOLLARS), MEDIAN(TOTAL_AMOUNT_OF_FINES_IN_DOLLARS), MAX(TOTAL_AMOUNT_OF_FINES_IN_DOLLARS), SUM(TOTAL_AMOUNT_OF_FINES_IN_DOLLARS),
 LISTAGG(DISTINCT ABUSE_ICON, ',') abuse_vals, COUNT_IF(ABUSE_ICON='Y') abuse_y, LISTAGG(DISTINCT SPECIAL_FOCUS_STATUS, ',') sff_vals, MIN(PROCESSING_DATE), MAX(PROCESSING_DATE),
 LISTAGG(DISTINCT PROVIDER_CHANGED_OWNERSHIP_IN_LAST_12_MONTHS, ',') chow_vals, COUNT_IF(PROVIDER_CHANGED_OWNERSHIP_IN_LAST_12_MONTHS='Y') chow_y
FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_NURSINGHOME411;

-- [12] NH411 top chains by fines (chain level, abuse count)
SELECT CHAIN_NAME, COUNT(*) homes, SUM(TOTAL_AMOUNT_OF_FINES_IN_DOLLARS) fines, COUNT_IF(ABUSE_ICON='Y') abuse_homes, ROUND(COUNT_IF(ABUSE_ICON='Y')/COUNT(*),3) abuse_rate, AVG(OVERALL_RATING) avg_star
FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_NURSINGHOME411 GROUP BY 1 ORDER BY fines DESC NULLS LAST LIMIT 12;

-- [13] LDA rows with INCOME >= 5M (the 24)
SELECT FILING_YEAR, FILING_PERIOD, FILING_TYPE, REGISTRANT_NAME, CLIENT_NAME, INCOME, EXPENSES FROM LIBRARY_MARTS.EDUCATION.EDUCATION__FED_SENATE_LDA_FILINGS
WHERE TRY_TO_NUMBER(REPLACE(INCOME,',',''),38,2) >= 5000000 ORDER BY TRY_TO_NUMBER(REPLACE(INCOME,',',''),38,2) DESC;

-- [14] CL non-investment income: count + sample 5
SELECT (SELECT COUNT(*) FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_COURTLISTENER_DISCLOSURE_NON_INVESTMENT_INCOME) n, * FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_COURTLISTENER_DISCLOSURE_NON_INVESTMENT_INCOME LIMIT 5;

-- [15] CL non-investment income: INCOME_AMOUNT distinct values top 25 (text?)
SELECT INCOME_AMOUNT, COUNT(*) c FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_COURTLISTENER_DISCLOSURE_NON_INVESTMENT_INCOME GROUP BY 1 ORDER BY c DESC LIMIT 25;

-- [16] CL judges: count + sample
SELECT (SELECT COUNT(*) FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_COURTLISTENER_JUDGES) n, ID, NAME_FIRST, NAME_LAST, GENDER, DATE_DOB, FJC_ID, FTM_TOTAL_RECEIVED, FTM_EID, HAS_PHOTO, IS_ALIAS_OF_ID FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_COURTLISTENER_JUDGES LIMIT 5;

-- [17] CL judges profile FTM_TOTAL_RECEIVED + gender
SELECT COUNT(*) n, COUNT(DISTINCT ID) d_id, COUNT(FTM_TOTAL_RECEIVED) ftm_nonnull, COUNT_IF(TRY_TO_DOUBLE(FTM_TOTAL_RECEIVED::string)>0) ftm_pos, MIN(TRY_TO_DOUBLE(FTM_TOTAL_RECEIVED::string)), MEDIAN(TRY_TO_DOUBLE(FTM_TOTAL_RECEIVED::string)), MAX(TRY_TO_DOUBLE(FTM_TOTAL_RECEIVED::string)),
 COUNT_IF(GENDER='f') f, COUNT_IF(GENDER='m') m, LISTAGG(DISTINCT GENDER, ',') gvals, COUNT(IS_ALIAS_OF_ID) alias_nonnull, COUNT(FJC_ID) fjc_nonnull, LISTAGG(DISTINCT HAS_PHOTO::string, ',') photo_vals
FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_COURTLISTENER_JUDGES;

-- [18] CL judges top 10 by FTM_TOTAL_RECEIVED
SELECT ID, NAME_FIRST, NAME_LAST, DOB_STATE, FJC_ID, FTM_TOTAL_RECEIVED, FTM_EID FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_COURTLISTENER_JUDGES ORDER BY TRY_TO_DOUBLE(FTM_TOTAL_RECEIVED::string) DESC NULLS LAST LIMIT 10;

-- [19] LEGISLATORS profile N_TERMS / LEGISLATOR_SET / gender / bioguide dupes
SELECT COUNT(*) n, COUNT(DISTINCT BIOGUIDE) d_bio, LISTAGG(DISTINCT LEGISLATOR_SET, ',') sets, COUNT_IF(GENDER='F') f, COUNT_IF(GENDER='M') m,
 MIN(N_TERMS), MEDIAN(N_TERMS), MAX(N_TERMS), COUNT(FEC_IDS) fec_nonnull, COUNT(OPENSECRETS) os_nonnull, COUNT(ICPSR) icpsr_nonnull
FROM LIBRARY_MARTS.POLITICS.POLITICS__FED_CONGRESS_LEGISLATORS;

-- [20] LEGISLATORS top 10 by N_TERMS
SELECT BIOGUIDE, NAME_FIRST, NAME_LAST, STATE, PARTY, N_TERMS, TERM_START, TERM_END, LEGISLATOR_SET FROM LIBRARY_MARTS.POLITICS.POLITICS__FED_CONGRESS_LEGISLATORS ORDER BY N_TERMS DESC NULLS LAST LIMIT 10;

-- [21] MEMBER_CROSSWALK profile
SELECT COUNT(*) n, COUNT(DISTINCT BIOGUIDE) d_bio, COUNT(DISTINCT MEMBER_KEY) d_key, COUNT_IF(BIOGUIDE IS NULL) bio_null, LISTAGG(DISTINCT LEGISLATOR_SET, ',') sets,
 COUNT_IF(GENDER='F') f, MIN(N_TERMS), MEDIAN(N_TERMS), MAX(N_TERMS), COUNT(ICPSR) icpsr_nn, COUNT(DISTINCT ICPSR) d_icpsr, MIN(ICPSR), MAX(ICPSR), COUNT(FEC_IDS) fec_nn
FROM LIBRARY_MARTS.POLITICS.POLITICS__MEMBER_CROSSWALK;

-- [22] MEMBER_CROSSWALK duplicated bioguides / ICPSR shared by 2+ members
SELECT 'bio' k, BIOGUIDE v, COUNT(*) c, LISTAGG(FULL_NAME,' / ') nm FROM LIBRARY_MARTS.POLITICS.POLITICS__MEMBER_CROSSWALK GROUP BY BIOGUIDE HAVING COUNT(*)>1
UNION ALL SELECT 'icpsr', ICPSR::string, COUNT(*), LISTAGG(FULL_NAME,' / ') FROM LIBRARY_MARTS.POLITICS.POLITICS__MEMBER_CROSSWALK WHERE ICPSR IS NOT NULL GROUP BY ICPSR HAVING COUNT(*)>1
ORDER BY c DESC LIMIT 20;

-- [23] LEGISLATORS vs CROSSWALK N_TERMS for long-serving members; blank-string check on id columns
SELECT l.BIOGUIDE, l.NAME_LAST, l.N_TERMS leg_terms, x.N_TERMS xw_terms, x.LEGISLATOR_SET, x.FIRST_TERM_START, x.LAST_TERM_END,
 (SELECT COUNT_IF(FEC_IDS IN ('','[]')) FROM LIBRARY_MARTS.POLITICS.POLITICS__FED_CONGRESS_LEGISLATORS) leg_fec_blank,
 (SELECT COUNT_IF(OPENSECRETS='') FROM LIBRARY_MARTS.POLITICS.POLITICS__FED_CONGRESS_LEGISLATORS) leg_os_blank,
 (SELECT COUNT_IF(LEGISLATOR_SET='' OR LEGISLATOR_SET IS NULL) FROM LIBRARY_MARTS.POLITICS.POLITICS__FED_CONGRESS_LEGISLATORS) leg_set_blank
FROM LIBRARY_MARTS.POLITICS.POLITICS__FED_CONGRESS_LEGISLATORS l JOIN LIBRARY_MARTS.POLITICS.POLITICS__MEMBER_CROSSWALK x ON x.BIOGUIDE=l.BIOGUIDE
WHERE l.BIOGUIDE IN ('D000355','Y000033','C000714','R000395','S001148') OR x.N_TERMS>=25 ORDER BY x.N_TERMS DESC LIMIT 12;

-- [24] LEGISLATORS vs CROSSWALK: N_TERMS agreement over all shared bioguides
SELECT COUNT(*) shared, COUNT_IF(l.N_TERMS=x.N_TERMS) same, COUNT_IF(x.N_TERMS>l.N_TERMS) xw_more, COUNT_IF(x.N_TERMS<l.N_TERMS) xw_less, COUNT_IF(l.N_TERMS=9 AND x.N_TERMS>9) capped_at_9
FROM LIBRARY_MARTS.POLITICS.POLITICS__FED_CONGRESS_LEGISLATORS l JOIN LIBRARY_MARTS.POLITICS.POLITICS__MEMBER_CROSSWALK x ON x.BIOGUIDE=l.BIOGUIDE;

-- [25] PPP count + sample
SELECT (SELECT COUNT(*) FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_SBA_PPP) n, LOAN_NUMBER, BORROWER_NAME, BORROWER_STATE, DATE_APPROVED, INITIAL_APPROVAL_AMOUNT, CURRENT_APPROVAL_AMOUNT, LOAN_STATUS, JOBS_REPORTED, RACE, BUSINESS_AGE
FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_SBA_PPP LIMIT 5;

-- [26] PPP profile INITIAL_APPROVAL_AMOUNT
SELECT COUNT(*) n, COUNT(DISTINCT LOAN_NUMBER) d_loan, COUNT_IF(INITIAL_APPROVAL_AMOUNT IS NULL) nulls, MIN(INITIAL_APPROVAL_AMOUNT), MEDIAN(INITIAL_APPROVAL_AMOUNT), MAX(INITIAL_APPROVAL_AMOUNT), SUM(INITIAL_APPROVAL_AMOUNT),
 MIN(DATE_APPROVED), MAX(DATE_APPROVED), COUNT_IF(INITIAL_APPROVAL_AMOUNT BETWEEN 149000 AND 149999.99) just_under_150k, COUNT_IF(INITIAL_APPROVAL_AMOUNT BETWEEN 150000 AND 150999.99) just_over_150k,
 COUNT_IF(CURRENT_APPROVAL_AMOUNT < INITIAL_APPROVAL_AMOUNT) cut, COUNT_IF(INITIAL_APPROVAL_AMOUNT>=150000) ge150k, COUNT_IF(JOBS_REPORTED=0) jobs0
FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_SBA_PPP;

-- [27] PPP top 12 borrowers by INITIAL_APPROVAL_AMOUNT
SELECT BORROWER_NAME, BORROWER_STATE, COUNT(*) loans, SUM(INITIAL_APPROVAL_AMOUNT) amt, MAX(INITIAL_APPROVAL_AMOUNT) mx, SUM(JOBS_REPORTED) jobs, LISTAGG(DISTINCT LOAN_STATUS, ',') st
FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_SBA_PPP GROUP BY 1,2 ORDER BY amt DESC LIMIT 12;

-- [28] PPP amount bands: where the 968K sit (is it the <150K file or the >150K file?)
SELECT WIDTH_BUCKET(INITIAL_APPROVAL_AMOUNT, 0, 10000000, 20) b, MIN(INITIAL_APPROVAL_AMOUNT), MAX(INITIAL_APPROVAL_AMOUNT), COUNT(*) FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_SBA_PPP GROUP BY 1 ORDER BY 1;

-- [29] FRA casualties count + sample
SELECT (SELECT COUNT(*) FROM LIBRARY_MARTS.TRANSPORT.TRANSPORT__FED_FRA_CASUALTIES) n, RAILROAD_CODE, INCIDENT_NUMBER, DATE, TYPE_OF_PERSON, FATALITY, AGE_OF_PERSON, NATURE_OF_INJURY, DAYS_AWAY_FROM_WORK, POSITIVE_ALCOHOL_TESTS, CASUALTY_OCCURRENCE_CODE
FROM LIBRARY_MARTS.TRANSPORT.TRANSPORT__FED_FRA_CASUALTIES LIMIT 5;

-- [30] FRA profile: fatality values, days away, years, dupes
SELECT COUNT(*) n, COUNT(DISTINCT REPORT_KEY) d_rk, LISTAGG(DISTINCT FATALITY::string, ',') fat_vals, MIN(DATE), MAX(DATE), MIN(INCIDENT_YEAR), MAX(INCIDENT_YEAR),
 MIN(TRY_TO_NUMBER(DAYS_AWAY_FROM_WORK::string)), MEDIAN(TRY_TO_NUMBER(DAYS_AWAY_FROM_WORK::string)), MAX(TRY_TO_NUMBER(DAYS_AWAY_FROM_WORK::string)), COUNT_IF(TRY_TO_NUMBER(DAYS_AWAY_FROM_WORK::string) IS NULL) days_null,
 LISTAGG(DISTINCT POSITIVE_ALCOHOL_TESTS::string, ',') alc_vals
FROM LIBRARY_MARTS.TRANSPORT.TRANSPORT__FED_FRA_CASUALTIES;

-- [31] FRA by incident year: rows, fatalities, date null share
SELECT INCIDENT_YEAR, COUNT(*) n, COUNT_IF(FATALITY='Yes') deaths, COUNT_IF(DATE IS NULL) date_null FROM LIBRARY_MARTS.TRANSPORT.TRANSPORT__FED_FRA_CASUALTIES GROUP BY 1 ORDER BY 1;

-- [32] FRA top 10 railroads by fatalities since 2015, with type of person split
SELECT RAILROAD_NAME, COUNT_IF(FATALITY='Yes') deaths, COUNT_IF(FATALITY='Yes' AND TYPE_OF_PERSON ILIKE 'Trespass%') tresp_deaths, COUNT_IF(FATALITY='Yes' AND TYPE_OF_PERSON ILIKE 'Worker%') worker_deaths, COUNT(*) casualties
FROM LIBRARY_MARTS.TRANSPORT.TRANSPORT__FED_FRA_CASUALTIES WHERE INCIDENT_YEAR BETWEEN 2015 AND 2025 GROUP BY 1 ORDER BY deaths DESC LIMIT 10;

-- [33] QPP count + sample
SELECT (SELECT COUNT(*) FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_QUALITY_PAYMENT_PROGRAM_EXPERIENCE) n, NPI, PROVIDER_KEY, PRACTICE_STATE_OR_US_TERRITORY, CLINICIAN_SPECIALTY, MEDICARE_PATIENTS, ALLOWED_CHARGES, SERVICES, FINAL_SCORE, PAYMENT_ADJUSTMENT_PERCENTAGE, NON_REPORTING
FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_QUALITY_PAYMENT_PROGRAM_EXPERIENCE LIMIT 5;

-- [34] QPP profile ALLOWED_CHARGES, FINAL_SCORE, adjustment
SELECT COUNT(*) n, COUNT(DISTINCT NPI) d_npi, COUNT_IF(ALLOWED_CHARGES IS NULL) ac_null, MIN(ALLOWED_CHARGES), MEDIAN(ALLOWED_CHARGES), MAX(ALLOWED_CHARGES), SUM(ALLOWED_CHARGES),
 MIN(FINAL_SCORE), MEDIAN(FINAL_SCORE), MAX(FINAL_SCORE), MIN(PAYMENT_ADJUSTMENT_PERCENTAGE), MAX(PAYMENT_ADJUSTMENT_PERCENTAGE), COUNT_IF(PAYMENT_ADJUSTMENT_PERCENTAGE<0) cut, COUNT_IF(PAYMENT_ADJUSTMENT_PERCENTAGE=-9) max_cut,
 LISTAGG(DISTINCT NON_REPORTING::string, ',') nr_vals, COUNT_IF(NON_REPORTING::string IN ('true','True','TRUE','1')) nonrep
FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_QUALITY_PAYMENT_PROGRAM_EXPERIENCE;

-- [35] QPP top 10 by ALLOWED_CHARGES (sum per NPI), with adjustment
SELECT NPI, COUNT(*) rows_, SUM(ALLOWED_CHARGES) ac, MAX(MEDICARE_PATIENTS) pts, MAX(CLINICIAN_SPECIALTY) spec, MAX(PRACTICE_STATE_OR_US_TERRITORY) st, MIN(FINAL_SCORE) fs_min, MIN(PAYMENT_ADJUSTMENT_PERCENTAGE) adj_min
FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_QUALITY_PAYMENT_PROGRAM_EXPERIENCE GROUP BY 1 ORDER BY ac DESC NULLS LAST LIMIT 10;

-- [36] QPP: dollars sitting under max penalty (-9%) by specialty
SELECT CLINICIAN_SPECIALTY, COUNT(*) n_cut9, SUM(ALLOWED_CHARGES) ac, ROUND(SUM(ALLOWED_CHARGES)*0.09) est_penalty FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_QUALITY_PAYMENT_PROGRAM_EXPERIENCE
WHERE PAYMENT_ADJUSTMENT_PERCENTAGE <= -8.99 GROUP BY 1 ORDER BY ac DESC NULLS LAST LIMIT 10;

-- [37] ICE detainers count + sample
SELECT (SELECT COUNT(*) FROM LIBRARY_MARTS.IMMIGRATION.IMMIGRATION__FED_ICE_DETAINERS) n, PERSON_HASH, DETAINER_PREPARE_DATE, FACILITY_STATE, DETENTION_FACILITY, DETAINER_PREPARED_CRIMINALITY, MOST_SERIOUS_CONVICTION_CHARGE, MSC_SENTENCE_DAYS, CITIZENSHIP_COUNTRY, DUPLICATE_LIKELY, DETAINER_LIFT_REASON
FROM LIBRARY_MARTS.IMMIGRATION.IMMIGRATION__FED_ICE_DETAINERS LIMIT 5;

-- [38] ICE profile: persons, dupes, dates, criminality mix, sentence days
SELECT COUNT(*) n, COUNT(DISTINCT PERSON_HASH) d_person, LISTAGG(DISTINCT DUPLICATE_LIKELY::string, ',') dup_vals, COUNT_IF(DUPLICATE_LIKELY::string IN ('true','True','Y','1','Yes')) dup_y,
 MIN(DETAINER_PREPARE_DATE), MAX(DETAINER_PREPARE_DATE), COUNT_IF(MOST_SERIOUS_CONVICTION_CHARGE IS NULL OR MOST_SERIOUS_CONVICTION_CHARGE='') no_conviction,
 MIN(MSC_SENTENCE_DAYS), MEDIAN(MSC_SENTENCE_DAYS), MAX(MSC_SENTENCE_DAYS), COUNT(MSC_SENTENCE_DAYS) sd_nonnull, LISTAGG(DISTINCT DETAINER_PREPARED_CRIMINALITY, ' | ') crim_vals
FROM LIBRARY_MARTS.IMMIGRATION.IMMIGRATION__FED_ICE_DETAINERS;

-- [39] ICE by month: detainers, share with no conviction
SELECT DATE_TRUNC('quarter', DETAINER_PREPARE_DATE) q, COUNT(*) n, ROUND(COUNT_IF(MOST_SERIOUS_CONVICTION_CHARGE IS NULL OR MOST_SERIOUS_CONVICTION_CHARGE='')/COUNT(*),3) no_conv_share
FROM LIBRARY_MARTS.IMMIGRATION.IMMIGRATION__FED_ICE_DETAINERS GROUP BY 1 ORDER BY 1;

-- [40] ICE top 10 facilities by detainers, no-conviction share
SELECT DETENTION_FACILITY, FACILITY_STATE, COUNT(*) n, ROUND(COUNT_IF(MOST_SERIOUS_CONVICTION_CHARGE IS NULL OR MOST_SERIOUS_CONVICTION_CHARGE='')/COUNT(*),3) no_conv
FROM LIBRARY_MARTS.IMMIGRATION.IMMIGRATION__FED_ICE_DETAINERS GROUP BY 1,2 ORDER BY n DESC LIMIT 10;

-- [41] ICE criminality-at-prepare by fiscal year (no lag), deduped person-hash count
SELECT YEAR(DATEADD(month,3,DETAINER_PREPARE_DATE)) fy, COUNT(*) n, COUNT(DISTINCT PERSON_HASH) persons,
 ROUND(COUNT_IF(DETAINER_PREPARED_CRIMINALITY LIKE '1%')/COUNT(*),3) convicted, ROUND(COUNT_IF(DETAINER_PREPARED_CRIMINALITY LIKE '2%')/COUNT(*),3) pending, ROUND(COUNT_IF(DETAINER_PREPARED_CRIMINALITY LIKE '3%')/COUNT(*),3) other_imm,
 COUNT_IF(DETAINER_PREPARE_DATE BETWEEN '2026-04-01' AND '2026-06-30') q2_2026_rows, MAX(DETAINER_PREPARE_DATE) mx
FROM LIBRARY_MARTS.IMMIGRATION.IMMIGRATION__FED_ICE_DETAINERS GROUP BY 1 ORDER BY 1;

-- [42] QPP: is ALLOWED_CHARGES repeated across clinicians (practice-level)?
SELECT COUNT(*) n, COUNT(DISTINCT ALLOWED_CHARGES) d_ac, (SELECT MAX(c) FROM (SELECT ALLOWED_CHARGES, COUNT(*) c FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_QUALITY_PAYMENT_PROGRAM_EXPERIENCE GROUP BY 1)) max_rows_one_value,
 (SELECT COUNT(*) FROM (SELECT ALLOWED_CHARGES FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_QUALITY_PAYMENT_PROGRAM_EXPERIENCE GROUP BY 1 HAVING COUNT(*)>=10)) values_on_10plus_rows,
 COUNT(DISTINCT MEDICARE_PATIENTS) d_pts, LISTAGG(DISTINCT PARTICIPATION_OPTION, ',') part_opts
FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_QUALITY_PAYMENT_PROGRAM_EXPERIENCE;

-- [43] QPP: individual-participation rows only, top 10 by ALLOWED_CHARGES
SELECT PARTICIPATION_OPTION, COUNT(*) n, MEDIAN(ALLOWED_CHARGES) med_ac, MAX(ALLOWED_CHARGES) mx_ac, COUNT_IF(PAYMENT_ADJUSTMENT_PERCENTAGE<=-8.99) max_cut, ROUND(AVG(FINAL_SCORE),1) avg_fs
FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_QUALITY_PAYMENT_PROGRAM_EXPERIENCE GROUP BY 1 ORDER BY n DESC;

-- [44] DOCKETS profile (71.7M; single pass) VIEW_COUNT, DATE_FILED range, bad years
SELECT COUNT(*) n, COUNT_IF(DATE_FILED IS NULL) df_null, MIN(DATE_FILED), MAX(DATE_FILED), COUNT_IF(DATE_FILED > '2026-12-31') future, COUNT_IF(DATE_FILED < '1900-01-01') pre1900,
 MIN(VIEW_COUNT), MEDIAN(VIEW_COUNT), MAX(VIEW_COUNT), COUNT_IF(VIEW_COUNT>0) viewed, APPROX_COUNT_DISTINCT(COURT_ID) courts, COUNT(ASSIGNED_TO_ID) judge_nonnull
FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_COURTLISTENER_DOCKETS;

-- [45] DOCKETS top 10 by VIEW_COUNT
SELECT ID, COURT_ID, CASE_NAME, DATE_FILED, NATURE_OF_SUIT, VIEW_COUNT FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_COURTLISTENER_DOCKETS ORDER BY VIEW_COUNT DESC NULLS LAST LIMIT 10;

-- [46] DOCKETS future-dated sample
SELECT ID, COURT_ID, CASE_NAME, DATE_FILED, DATE_CREATED, DOCKET_NUMBER FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_COURTLISTENER_DOCKETS WHERE DATE_FILED > '2026-12-31' LIMIT 8;

-- [47] NYC CFB 2001/2009/2021/2025: count + profile AMOUNT/MATCH (one statement, four tables)
WITH u AS (
 SELECT '2001' y, AMOUNT, MATCH_AMOUNT, CONTRIBUTION_DATE, SCHEDULE, CONTRIBUTION_RECORD_ID, ELECTION_CYCLE FROM LIBRARY_MARTS.POLITICS.POLITICS__ST_NYC_CFB_CAMPAIGN_2001_CONTRIBUTION
 UNION ALL SELECT '2009', AMOUNT, MATCH_AMOUNT, CONTRIBUTION_DATE, SCHEDULE, CONTRIBUTION_RECORD_ID, ELECTION_CYCLE FROM LIBRARY_MARTS.POLITICS.POLITICS__ST_NYC_CFB_CAMPAIGN_2009_CONTRIBUTION
 UNION ALL SELECT '2021', AMOUNT, MATCH_AMOUNT, CONTRIBUTION_DATE, SCHEDULE, CONTRIBUTION_RECORD_ID, ELECTION_CYCLE FROM LIBRARY_MARTS.POLITICS.POLITICS__ST_NYC_CFB_CAMPAIGN_2021_CONTRIBUTIONS
 UNION ALL SELECT '2025', AMOUNT, MATCH_AMOUNT, CONTRIBUTION_DATE, SCHEDULE, CONTRIBUTION_RECORD_ID, ELECTION_CYCLE FROM LIBRARY_MARTS.POLITICS.POLITICS__ST_NYC_CFB_CAMPAIGN_2025_CONTRIBUTIONS)
SELECT y, COUNT(*) n, COUNT(DISTINCT CONTRIBUTION_RECORD_ID) d_id, COUNT_IF(TRY_TO_DOUBLE(AMOUNT::string) IS NULL) amt_null, MIN(TRY_TO_DOUBLE(AMOUNT::string)) mn, MEDIAN(TRY_TO_DOUBLE(AMOUNT::string)) med, MAX(TRY_TO_DOUBLE(AMOUNT::string)) mx,
 SUM(TRY_TO_DOUBLE(AMOUNT::string)) tot, SUM(TRY_TO_DOUBLE(MATCH_AMOUNT::string)) match_tot, COUNT_IF(TRY_TO_DOUBLE(AMOUNT::string)<0) neg, MIN(CONTRIBUTION_DATE) d0, MAX(CONTRIBUTION_DATE) d1,
 LISTAGG(DISTINCT SCHEDULE, ',') sched, LISTAGG(DISTINCT ELECTION_CYCLE::string, ',') cyc
FROM u GROUP BY 1 ORDER BY 1;

-- [48] NYC CFB 2021 top 10 recipients by AMOUNT + match
SELECT RECIPIENT_NAME, OFFICE_CODE, COUNT(*) n, SUM(TRY_TO_DOUBLE(AMOUNT::string)) amt, SUM(TRY_TO_DOUBLE(MATCH_AMOUNT::string)) mtch FROM LIBRARY_MARTS.POLITICS.POLITICS__ST_NYC_CFB_CAMPAIGN_2021_CONTRIBUTIONS GROUP BY 1,2 ORDER BY amt DESC LIMIT 10;

-- [49] NYC CFB 2025 top 10 recipients by AMOUNT + match
SELECT RECIPIENT_NAME, OFFICE_CODE, COUNT(*) n, SUM(TRY_TO_DOUBLE(AMOUNT::string)) amt, SUM(TRY_TO_DOUBLE(MATCH_AMOUNT::string)) mtch FROM LIBRARY_MARTS.POLITICS.POLITICS__ST_NYC_CFB_CAMPAIGN_2025_CONTRIBUTIONS GROUP BY 1,2 ORDER BY amt DESC LIMIT 10;

-- [50] NYC CFB 2001 top 10 recipients
SELECT CANDIDATE_LAST_NAME, CANDIDATE_FIRST_NAME, OFFICE_CODE, COUNT(*) n, SUM(TRY_TO_DOUBLE(AMOUNT::string)) amt, SUM(TRY_TO_DOUBLE(MATCH_AMOUNT::string)) mtch FROM LIBRARY_MARTS.POLITICS.POLITICS__ST_NYC_CFB_CAMPAIGN_2001_CONTRIBUTION GROUP BY 1,2,3 ORDER BY amt DESC LIMIT 10;

-- [51] NYC CFB 2009 top 10 recipients
SELECT RECIPIENT_NAME, OFFICE_CODE, COUNT(*) n, SUM(TRY_TO_DOUBLE(AMOUNT::string)) amt, SUM(TRY_TO_DOUBLE(MATCH_AMOUNT::string)) mtch FROM LIBRARY_MARTS.POLITICS.POLITICS__ST_NYC_CFB_CAMPAIGN_2009_CONTRIBUTION GROUP BY 1,2 ORDER BY amt DESC LIMIT 10;

-- [52] NYC CFB 2025 top 10 contributor names by count with amount (bundling / straw check)
SELECT CONTRIBUTOR_NAME, COUNT(*) n, COUNT(DISTINCT RECIPIENT_NAME) recips, SUM(TRY_TO_DOUBLE(AMOUNT::string)) amt, MAX(EMPLOYER_NAME) emp FROM LIBRARY_MARTS.POLITICS.POLITICS__ST_NYC_CFB_CAMPAIGN_2025_CONTRIBUTIONS
WHERE CONTRIBUTOR_CODE NOT IN ('CAN','SPO') OR CONTRIBUTOR_CODE IS NULL GROUP BY 1 ORDER BY amt DESC NULLS LAST LIMIT 12;

-- [53] PARTD profile TOTAL_DRUG_COST + suppression + years
SELECT COUNT(*) n, APPROX_COUNT_DISTINCT(NPI) npis, COUNT_IF(TOTAL_DRUG_COST IS NULL) cost_null, MIN(TOTAL_DRUG_COST), MEDIAN(TOTAL_DRUG_COST), MAX(TOTAL_DRUG_COST), SUM(TOTAL_DRUG_COST),
 COUNT_IF(TOTAL_BENEFICIARIES IS NULL) benes_null, MIN(TOTAL_CLAIMS), LISTAGG(DISTINCT DATA_YEAR::string, ',') yrs, COUNT_IF(GE65_TOTAL_DRUG_COST IS NULL) ge65_null
FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_PARTD_PRESCRIBERS;

-- [54] PARTD top 10 prescribers by summed TOTAL_DRUG_COST, with top drug
WITH p AS (SELECT NPI, SUM(TOTAL_DRUG_COST) cost, SUM(TOTAL_CLAIMS) claims, MAX(PRESCRIBER_LAST_ORG_NAME) nm, MAX(PRESCRIBER_TYPE) typ, MAX(PRESCRIBER_STATE) st, MAX_BY(GENERIC_NAME, TOTAL_DRUG_COST) top_drug, MAX(TOTAL_DRUG_COST) top_drug_cost
 FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_PARTD_PRESCRIBERS GROUP BY NPI)
SELECT * FROM p ORDER BY cost DESC LIMIT 10;

-- [55] PARTD concentration: top 1% of prescribers' share of cost
WITH p AS (SELECT NPI, SUM(TOTAL_DRUG_COST) cost FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_PARTD_PRESCRIBERS GROUP BY NPI), r AS (SELECT cost, PERCENT_RANK() OVER (ORDER BY cost) pr FROM p)
SELECT COUNT(*) npis, SUM(IFF(pr>=0.99,cost,0))/SUM(cost) top1_share, MEDIAN(cost) med_npi_cost FROM r;

-- [56] CFPB count + sample
SELECT (SELECT COUNT(*) FROM LIBRARY_MARTS.CONSUMER_PROTECTION.CONSUMER_PROTECTION__FED_CFPB_COMPLAINTS) n, COMPLAINT_ID, DATE_RECEIVED, COMPANY, PRODUCT, ISSUE, COMPANY_RESPONSE, IS_TIMELY, DAYS_RECEIVED_TO_COMPANY, STATE
FROM LIBRARY_MARTS.CONSUMER_PROTECTION.CONSUMER_PROTECTION__FED_CFPB_COMPLAINTS LIMIT 5;

-- [57] CFPB profile
SELECT COUNT(*) n, COUNT(DISTINCT COMPLAINT_ID) d_id, MIN(DATE_RECEIVED), MAX(DATE_RECEIVED), MIN(DAYS_RECEIVED_TO_COMPANY), MEDIAN(DAYS_RECEIVED_TO_COMPANY), MAX(DAYS_RECEIVED_TO_COMPANY),
 LISTAGG(DISTINCT IS_TIMELY::string, ',') timely_vals, COUNT_IF(IS_TIMELY::string IN ('false','False','No','FALSE')) untimely, COUNT_IF(HAS_NARRATIVE::string IN ('true','True','TRUE')) narr,
 COUNT_IF(DAYS_RECEIVED_TO_COMPANY<0) neg_days
FROM LIBRARY_MARTS.CONSUMER_PROTECTION.CONSUMER_PROTECTION__FED_CFPB_COMPLAINTS;

-- [58] CFPB top 10 companies, by year split last 3 years, untimely + relief
SELECT COMPANY, COUNT(*) n, COUNT_IF(YEAR(DATE_RECEIVED)=2023) y23, COUNT_IF(YEAR(DATE_RECEIVED)=2024) y24, COUNT_IF(YEAR(DATE_RECEIVED)=2025) y25,
 ROUND(COUNT_IF(COMPANY_RESPONSE ILIKE '%monetary relief%' AND COMPANY_RESPONSE NOT ILIKE '%non-monetary%')/COUNT(*),4) money_relief, COUNT_IF(IS_TIMELY::string IN ('false','False','No','FALSE')) untimely
FROM LIBRARY_MARTS.CONSUMER_PROTECTION.CONSUMER_PROTECTION__FED_CFPB_COMPLAINTS GROUP BY 1 ORDER BY n DESC LIMIT 10;

-- [59] UK PSC count + sample
SELECT (SELECT COUNT(*) FROM LIBRARY_MARTS.CORPORATE_REGISTRY.CORPORATE_REGISTRY__UK_COMPANIES_HOUSE_PSC) n, COMPANY_NUMBER, KIND, NAME, NATIONALITY, COUNTRY_OF_RESIDENCE, DOB_YEAR, NOTIFIED_ON, CEASED_ON, ADDRESS_POSTAL_CODE
FROM LIBRARY_MARTS.CORPORATE_REGISTRY.CORPORATE_REGISTRY__UK_COMPANIES_HOUSE_PSC LIMIT 5;

-- [60] UK PSC profile: companies, dupes, dates, kinds
SELECT COUNT(*) n, APPROX_COUNT_DISTINCT(COMPANY_NUMBER) cos, APPROX_COUNT_DISTINCT(PSC_LINK_SELF) d_link, APPROX_COUNT_DISTINCT(_SRC_SHA256) d_sha, MIN(NOTIFIED_ON), MAX(NOTIFIED_ON), COUNT_IF(NOTIFIED_ON IS NULL) nn,
 COUNT_IF(CEASED_ON IS NOT NULL) ceased, MIN(DOB_YEAR), MAX(DOB_YEAR), COUNT_IF(KIND ILIKE 'individual%') indiv, COUNT_IF(KIND ILIKE 'corporate%') corp, COUNT_IF(KIND ILIKE '%super-secure%') secure
FROM LIBRARY_MARTS.CORPORATE_REGISTRY.CORPORATE_REGISTRY__UK_COMPANIES_HOUSE_PSC;

-- [61] UK PSC top 10 names by active controlled companies (concentration / nominee check)
SELECT NAME, DOB_YEAR, NATIONALITY, COUNT(DISTINCT COMPANY_NUMBER) cos, MAX(ADDRESS_POSTAL_CODE) pc FROM LIBRARY_MARTS.CORPORATE_REGISTRY.CORPORATE_REGISTRY__UK_COMPANIES_HOUSE_PSC
WHERE CEASED_ON IS NULL AND KIND ILIKE 'individual%' GROUP BY 1,2,3 ORDER BY cos DESC LIMIT 12;

-- [62] UK PSC top nationalities (active individuals)
SELECT NATIONALITY, COUNT(*) n FROM LIBRARY_MARTS.CORPORATE_REGISTRY.CORPORATE_REGISTRY__UK_COMPANIES_HOUSE_PSC WHERE CEASED_ON IS NULL AND KIND ILIKE 'individual%' GROUP BY 1 ORDER BY n DESC LIMIT 12;

-- [63] OPEN PAYMENTS x3 profile (one statement)
WITH u AS (
 SELECT 'main' t, PROGRAM_YEAR py, TOTAL_AMOUNT_OF_PAYMENT_USDOLLARS a, RECORD_ID FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_OPEN_PAYMENTS
 UNION ALL SELECT '2022', PROGRAM_YEAR, TOTAL_AMOUNT_OF_PAYMENT_USDOLLARS, RECORD_ID FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_OPEN_PAYMENTS_2022
 UNION ALL SELECT '2023', PROGRAM_YEAR, TOTAL_AMOUNT_OF_PAYMENT_USDOLLARS, RECORD_ID FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_OPEN_PAYMENTS_2023)
SELECT t, py, COUNT(*) n, APPROX_COUNT_DISTINCT(RECORD_ID) d_rec, COUNT_IF(a IS NULL) nulls, MIN(a), MEDIAN(a), MAX(a), SUM(a) FROM u GROUP BY 1,2 ORDER BY 1,2;

-- [64] OPEN PAYMENTS top 8 recipients per year (individuals by NPI/profile, hospitals by name), with nature
WITH u AS (
 SELECT '2024' t, COALESCE(NPI::string, COVERED_RECIPIENT_PROFILE_ID::string, TEACHING_HOSPITAL_NAME) k, COVERED_RECIPIENT_LAST_NAME ln, COVERED_RECIPIENT_FIRST_NAME fn, TEACHING_HOSPITAL_NAME th, COVERED_RECIPIENT_SPECIALTY_1 sp, RECIPIENT_STATE st, TOTAL_AMOUNT_OF_PAYMENT_USDOLLARS a, NATURE_OF_PAYMENT_OR_TRANSFER_OF_VALUE nat FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_OPEN_PAYMENTS
 UNION ALL SELECT '2022', COALESCE(NPI::string, COVERED_RECIPIENT_PROFILE_ID::string, TEACHING_HOSPITAL_NAME), COVERED_RECIPIENT_LAST_NAME, COVERED_RECIPIENT_FIRST_NAME, TEACHING_HOSPITAL_NAME, COVERED_RECIPIENT_SPECIALTY_1, RECIPIENT_STATE, TOTAL_AMOUNT_OF_PAYMENT_USDOLLARS, NATURE_OF_PAYMENT_OR_TRANSFER_OF_VALUE FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_OPEN_PAYMENTS_2022
 UNION ALL SELECT '2023', COALESCE(NPI::string, COVERED_RECIPIENT_PROFILE_ID::string, TEACHING_HOSPITAL_NAME), COVERED_RECIPIENT_LAST_NAME, COVERED_RECIPIENT_FIRST_NAME, TEACHING_HOSPITAL_NAME, COVERED_RECIPIENT_SPECIALTY_1, RECIPIENT_STATE, TOTAL_AMOUNT_OF_PAYMENT_USDOLLARS, NATURE_OF_PAYMENT_OR_TRANSFER_OF_VALUE FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_OPEN_PAYMENTS_2023),
g AS (SELECT t, k, MAX(ln) ln, MAX(fn) fn, MAX(th) th, MAX(sp) sp, MAX(st) st, SUM(a) amt, COUNT(*) n, MAX_BY(nat, a) top_nat, MAX(a) mx FROM u GROUP BY 1,2)
SELECT * FROM g QUALIFY ROW_NUMBER() OVER (PARTITION BY t ORDER BY amt DESC) <= 8 ORDER BY t, amt DESC;

-- [65] OPEN PAYMENTS concentration per year: top 1% of recipients' share, and royalty share
WITH u AS (
 SELECT '2024' t, COALESCE(NPI::string, COVERED_RECIPIENT_PROFILE_ID::string, TEACHING_HOSPITAL_NAME) k, TOTAL_AMOUNT_OF_PAYMENT_USDOLLARS a, NATURE_OF_PAYMENT_OR_TRANSFER_OF_VALUE nat FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_OPEN_PAYMENTS
 UNION ALL SELECT '2022', COALESCE(NPI::string, COVERED_RECIPIENT_PROFILE_ID::string, TEACHING_HOSPITAL_NAME), TOTAL_AMOUNT_OF_PAYMENT_USDOLLARS, NATURE_OF_PAYMENT_OR_TRANSFER_OF_VALUE FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_OPEN_PAYMENTS_2022
 UNION ALL SELECT '2023', COALESCE(NPI::string, COVERED_RECIPIENT_PROFILE_ID::string, TEACHING_HOSPITAL_NAME), TOTAL_AMOUNT_OF_PAYMENT_USDOLLARS, NATURE_OF_PAYMENT_OR_TRANSFER_OF_VALUE FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_OPEN_PAYMENTS_2023),
g AS (SELECT t, k, SUM(a) amt FROM u GROUP BY 1,2), r AS (SELECT t, amt, PERCENT_RANK() OVER (PARTITION BY t ORDER BY amt) pr FROM g),
roy AS (SELECT t, SUM(IFF(nat ILIKE 'Royalty%', a, 0))/SUM(a) royalty_share FROM u GROUP BY 1)
SELECT r.t, COUNT(*) recips, SUM(IFF(pr>=0.99,amt,0))/SUM(amt) top1_share, MEDIAN(amt) med, MAX(roy.royalty_share) royalty_share FROM r JOIN roy ON roy.t=r.t GROUP BY 1 ORDER BY 1;

-- [66] CITATIONS profile
SELECT COUNT(*) n, COUNT(DISTINCT CLUSTER_ID) clusters, MIN(TRY_TO_NUMBER(VOLUME::string)), MEDIAN(TRY_TO_NUMBER(VOLUME::string)), MAX(TRY_TO_NUMBER(VOLUME::string)), COUNT_IF(TRY_TO_NUMBER(VOLUME::string) IS NULL) vol_null,
 MIN(DATE_CREATED), MAX(DATE_CREATED), APPROX_COUNT_DISTINCT(REPORTER) reporters, LISTAGG(DISTINCT TYPE::string, ',') types
FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_COURTLISTENER_CITATIONS;

-- [67] CITATIONS top 10 reporters + created-year spikes
SELECT 'rep' k, REPORTER v, COUNT(*) n FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_COURTLISTENER_CITATIONS GROUP BY 2 QUALIFY ROW_NUMBER() OVER (ORDER BY COUNT(*) DESC)<=10
UNION ALL SELECT 'yr', YEAR(DATE_CREATED)::string, COUNT(*) FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_COURTLISTENER_CITATIONS GROUP BY 2 ORDER BY 1, 3 DESC;

-- [68] UK PSC: the top multi-company controllers - notification dates spread and company count per postcode
SELECT NAME, DOB_YEAR, COUNT(DISTINCT COMPANY_NUMBER) cos, MIN(NOTIFIED_ON), MAX(NOTIFIED_ON), COUNT(DISTINCT NOTIFIED_ON) days, COUNT(DISTINCT ADDRESS_POSTAL_CODE) pcs, MODE(ADDRESS_POSTAL_CODE) top_pc
FROM LIBRARY_MARTS.CORPORATE_REGISTRY.CORPORATE_REGISTRY__UK_COMPANIES_HOUSE_PSC
WHERE CEASED_ON IS NULL AND NAME IN ('Mr Mohammed Ayyaz','Dr Mohammed Ayyaz','Mr Salaheldin Samir Ismail Abdelbaky Eltantawy','Mr Ashraf Mohammed Abdou Awad Ibrahim','Miss Gabrielle Southern','Michael Gleissner','Mr Peter Valaitis')
GROUP BY 1,2 ORDER BY cos DESC;

-- [69] FRA Brightline + all trespasser deaths by year 2018-2025
SELECT INCIDENT_YEAR, COUNT_IF(FATALITY='Yes' AND RAILROAD_NAME ILIKE 'Brightline%') brightline_deaths, COUNT_IF(RAILROAD_NAME ILIKE 'Brightline%') brightline_cas,
 COUNT_IF(FATALITY='Yes' AND TYPE_OF_PERSON ILIKE 'Trespass%') tresp_deaths, COUNT_IF(FATALITY='Yes') all_deaths, COUNT(DISTINCT IFF(FATALITY='Yes', INCIDENT_KEY, NULL)) death_incidents
FROM LIBRARY_MARTS.TRANSPORT.TRANSPORT__FED_FRA_CASUALTIES WHERE INCIDENT_YEAR BETWEEN 2017 AND 2025 GROUP BY 1 ORDER BY 1;

-- [70] ICE: FY convicted share with DUPLICATE_LIKELY rows removed, one row per person-year
WITH d AS (SELECT YEAR(DATEADD(month,3,DETAINER_PREPARE_DATE)) fy, PERSON_HASH, MIN(DETAINER_PREPARED_CRIMINALITY) crim FROM LIBRARY_MARTS.IMMIGRATION.IMMIGRATION__FED_ICE_DETAINERS
 WHERE DUPLICATE_LIKELY::string <> 'True' GROUP BY 1,2)
SELECT fy, COUNT(*) persons, ROUND(COUNT_IF(crim LIKE '1%')/COUNT(*),3) convicted, ROUND(COUNT_IF(crim LIKE '2%')/COUNT(*),3) pending, ROUND(COUNT_IF(crim LIKE '3%')/COUNT(*),3) other_imm FROM d GROUP BY 1 ORDER BY 1;

-- [71] NH: Bria + Cahokia/Belleville chain homes, both snapshots, abuse and fines
SELECT 'may26' snap, PROVIDER_NAME, CITY, ABUSE_ICON, TOTAL_AMOUNT_OF_FINES_IN_DOLLARS, OVERALL_RATING, SPECIAL_FOCUS_STATUS FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_NURSING_HOME WHERE CHAIN_NAME='BRIA HEALTH SERVICES'
UNION ALL SELECT 'dec25', PROVIDER_NAME, CITY_TOWN, ABUSE_ICON, TOTAL_AMOUNT_OF_FINES_IN_DOLLARS, OVERALL_RATING, SPECIAL_FOCUS_STATUS FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_NURSINGHOME411 WHERE CHAIN_NAME='BRIA HEALTH SERVICES' ORDER BY 2,1;

-- [72] NH: chains with 10+ homes ranked by abuse-flag rate (May 2026 snapshot)
SELECT CHAIN_NAME, COUNT(*) homes, COUNT_IF(ABUSE_ICON='Y') abuse, ROUND(COUNT_IF(ABUSE_ICON='Y')/COUNT(*),3) rate, SUM(TOTAL_AMOUNT_OF_FINES_IN_DOLLARS) fines, ROUND(AVG(OVERALL_RATING),2) star
FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_NURSING_HOME WHERE CHAIN_NAME IS NOT NULL AND CHAIN_NAME<>'' GROUP BY 1 HAVING COUNT(*)>=10 ORDER BY rate DESC LIMIT 10;

