-- [1] columns of my tables
SELECT table_name, LISTAGG(column_name||':'||data_type, ', ') WITHIN GROUP (ORDER BY ordinal_position) cols
FROM LIBRARY_MARTS.INFORMATION_SCHEMA.COLUMNS
WHERE table_name IN ('ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_FACILITIES','FINANCE__FED_EPA_ICIS_FEC_CASE_ENFORCEMENT_CONCLUSION_FACILITIES','FINANCE__FED_EPA_ICIS_FEC_EPA_INFORMAL_ENFORCEMENT_ACTIONS','ENVIRONMENT__FED_EPA_ECHO','ENVIRONMENT__EPA_PENALTY_GAP','PROCUREMENT__FED_SAM_EXCLUSIONS','PROCUREMENT__FED_USASPENDING_BULK','ENVIRONMENT__XC_EPA_CORPORATE_CROSSWALK','LABOR__FED_OSHA_ITA_300A_SUMMARY_2024','LABOR__FED_OSHA_ITA_CASE_DETAIL_2025')
GROUP BY 1 ORDER BY 1;

-- [2] ID shape profile across EPA tables, crosswalk, SAM
SELECT 'FEC_CASE.FACILITY_UIN' col, COUNT(*) n, COUNT(DISTINCT FACILITY_UIN) d, COUNT_IF(REGEXP_LIKE(TRIM(FACILITY_UIN),'^110[0-9]{9}$')) frs_shaped, MIN(FACILITY_UIN) mn, MAX(FACILITY_UIN) mx, COUNT(DISTINCT CASE_NUMBER) cases FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_EPA_ICIS_FEC_CASE_ENFORCEMENT_CONCLUSION_FACILITIES
UNION ALL SELECT 'FEC_CASE.ICIS_FACILITY_INTEREST_ID', COUNT(*), COUNT(DISTINCT ICIS_FACILITY_INTEREST_ID), COUNT_IF(REGEXP_LIKE(TRIM(ICIS_FACILITY_INTEREST_ID),'^110[0-9]{9}$')), MIN(ICIS_FACILITY_INTEREST_ID), MAX(ICIS_FACILITY_INTEREST_ID), NULL FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_EPA_ICIS_FEC_CASE_ENFORCEMENT_CONCLUSION_FACILITIES
UNION ALL SELECT 'ICIS_AIR.REGISTRY_ID', COUNT(*), COUNT(DISTINCT REGISTRY_ID), COUNT_IF(REGEXP_LIKE(TRIM(REGISTRY_ID),'^110[0-9]{9}$')), MIN(REGISTRY_ID), MAX(REGISTRY_ID), COUNT(DISTINCT AIR_POLLUTANT_CLASS_DESC) FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_FACILITIES
UNION ALL SELECT 'FEC_INFORMAL.REGISTRY_ID', COUNT(*), COUNT(DISTINCT REGISTRY_ID), COUNT_IF(REGEXP_LIKE(TRIM(REGISTRY_ID),'^110[0-9]{9}$')), MIN(REGISTRY_ID), MAX(REGISTRY_ID), NULL FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_EPA_ICIS_FEC_EPA_INFORMAL_ENFORCEMENT_ACTIONS
UNION ALL SELECT 'ECHO.FRS_ID', COUNT(*), COUNT(DISTINCT FRS_ID), COUNT_IF(REGEXP_LIKE(TRIM(FRS_ID),'^110[0-9]{9}$')), MIN(FRS_ID), MAX(FRS_ID), NULL FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ECHO
UNION ALL SELECT 'PENALTY_GAP.FRS_ID', COUNT(*), COUNT(DISTINCT FRS_ID), COUNT_IF(REGEXP_LIKE(TRIM(FRS_ID),'^110[0-9]{9}$')), MIN(FRS_ID), MAX(FRS_ID), NULL FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__EPA_PENALTY_GAP
UNION ALL SELECT 'XWALK.EPA_REGISTRY_ID w/ UEI', COUNT(*), COUNT(DISTINCT EPA_REGISTRY_ID), COUNT_IF(REGEXP_LIKE(TRIM(EPA_REGISTRY_ID),'^110[0-9]{9}$')), MIN(EPA_REGISTRY_ID), MAX(EPA_REGISTRY_ID), COUNT(DISTINCT PARENT_UEI) FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__XC_EPA_CORPORATE_CROSSWALK WHERE TRIM(PARENT_UEI)<>''
UNION ALL SELECT 'SAM_EXCL.UEI', COUNT(*), COUNT(DISTINCT UEI), COUNT_IF(LENGTH(TRIM(UEI))=12), MIN(UEI), MAX(UEI), COUNT_IF(IS_CURRENTLY_EXCLUDED::VARCHAR ILIKE 't%') FROM LIBRARY_MARTS.PROCUREMENT.PROCUREMENT__FED_SAM_EXCLUSIONS;

-- [3] EPA side: facility IDs reaching crosswalk UEIs, and UEIs in SAM exclusions
WITH x AS (SELECT TRIM(EPA_REGISTRY_ID) r, TRIM(PARENT_UEI) u FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__XC_EPA_CORPORATE_CROSSWALK WHERE TRIM(PARENT_UEI)<>''),
sam AS (SELECT DISTINCT TRIM(UEI) u FROM LIBRARY_MARTS.PROCUREMENT.PROCUREMENT__FED_SAM_EXCLUSIONS WHERE LENGTH(TRIM(UEI))=12),
t AS (
 SELECT DISTINCT 'ICIS_AIR' t, TRIM(REGISTRY_ID) r FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_FACILITIES
 UNION ALL SELECT DISTINCT 'FEC_CASE', TRIM(FACILITY_UIN) FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_EPA_ICIS_FEC_CASE_ENFORCEMENT_CONCLUSION_FACILITIES
 UNION ALL SELECT DISTINCT 'FEC_INFORMAL', TRIM(REGISTRY_ID) FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_EPA_ICIS_FEC_EPA_INFORMAL_ENFORCEMENT_ACTIONS
 UNION ALL SELECT DISTINCT 'ECHO', TRIM(FRS_ID) FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ECHO
 UNION ALL SELECT DISTINCT 'PENALTY_GAP', TRIM(FRS_ID) FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__EPA_PENALTY_GAP
 UNION ALL SELECT DISTINCT 'NPDES_INFORMAL', TRIM(REGISTRY_ID) FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_NPDES_NPDES_INFORMAL_ENFORCEMENT_ACTIONS
 UNION ALL SELECT DISTINCT 'AIR_EMISSIONS', TRIM(FRS_ID) FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_AIR_EMISSIONS_POLL_RPT_COMBINED_EMISSIONS)
SELECT t.t, COUNT(DISTINCT t.r) ids, COUNT(DISTINCT x.r) ids_in_xwalk, COUNT(DISTINCT x.u) ueis, COUNT(DISTINCT sam.u) ueis_in_sam_excl
FROM t LEFT JOIN x ON x.r=t.r LEFT JOIN sam ON sam.u=x.u GROUP BY 1 ORDER BY 1;

-- [4] EPA side land via crosswalk (rerun, air emissions key fixed)
WITH x AS (SELECT TRIM(EPA_REGISTRY_ID) r, TRIM(PARENT_UEI) u FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__XC_EPA_CORPORATE_CROSSWALK WHERE TRIM(PARENT_UEI)<>''),
sam AS (SELECT DISTINCT TRIM(UEI) u FROM LIBRARY_MARTS.PROCUREMENT.PROCUREMENT__FED_SAM_EXCLUSIONS WHERE LENGTH(TRIM(UEI))=12),
t AS (
 SELECT DISTINCT 'ICIS_AIR' t, TRIM(REGISTRY_ID) r FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_FACILITIES
 UNION ALL SELECT DISTINCT 'FEC_CASE', TRIM(FACILITY_UIN) FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_EPA_ICIS_FEC_CASE_ENFORCEMENT_CONCLUSION_FACILITIES
 UNION ALL SELECT DISTINCT 'FEC_INFORMAL', TRIM(REGISTRY_ID) FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_EPA_ICIS_FEC_EPA_INFORMAL_ENFORCEMENT_ACTIONS
 UNION ALL SELECT DISTINCT 'ECHO', TRIM(FRS_ID) FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ECHO
 UNION ALL SELECT DISTINCT 'PENALTY_GAP', TRIM(FRS_ID) FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__EPA_PENALTY_GAP
 UNION ALL SELECT DISTINCT 'NPDES_INFORMAL', TRIM(REGISTRY_ID) FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_NPDES_NPDES_INFORMAL_ENFORCEMENT_ACTIONS
 UNION ALL SELECT DISTINCT 'AIR_EMISSIONS', TRIM(REGISTRY_ID::VARCHAR) FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_AIR_EMISSIONS_POLL_RPT_COMBINED_EMISSIONS)
SELECT t.t, COUNT(DISTINCT t.r) ids, COUNT(DISTINCT x.r) ids_in_xwalk, COUNT(DISTINCT x.u) ueis, COUNT(DISTINCT sam.u) ueis_in_sam_excl
FROM t LEFT JOIN x ON x.r=t.r LEFT JOIN sam ON sam.u=x.u GROUP BY 1 ORDER BY 1;

-- [5] A side: 4 USAspending tables -> crosswalk -> ICIS air / FEC case / FEC informal, land + dollars
WITH x AS (SELECT TRIM(EPA_REGISTRY_ID) r, TRIM(PARENT_UEI) u FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__XC_EPA_CORPORATE_CROSSWALK WHERE TRIM(PARENT_UEI)<>''),
f AS (SELECT x.u,
  MAX(IFF(x.r IN (SELECT TRIM(REGISTRY_ID) FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_FACILITIES),1,0)) air,
  MAX(IFF(x.r IN (SELECT TRIM(FACILITY_UIN) FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_EPA_ICIS_FEC_CASE_ENFORCEMENT_CONCLUSION_FACILITIES),1,0)) fcase,
  MAX(IFF(x.r IN (SELECT TRIM(REGISTRY_ID) FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_EPA_ICIS_FEC_EPA_INFORMAL_ENFORCEMENT_ACTIONS),1,0)) finf
  FROM x GROUP BY 1),
a AS (
  SELECT 'CONTRACTS' t, TRIM(RECIPIENT_UEI) u, SUM(TRY_TO_DOUBLE(FEDERAL_ACTION_OBLIGATION::VARCHAR)) usd FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_USASPENDING_CONTRACTS GROUP BY 1,2
  UNION ALL SELECT 'CONTRACTS_FULL', TRIM(RECIPIENT_UEI), SUM(TRY_TO_DOUBLE(FEDERAL_ACTION_OBLIGATION::VARCHAR)) FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_USASPENDING_CONTRACTS_FULL GROUP BY 1,2
  UNION ALL SELECT 'CONTRACTS_FULL_R2', TRIM(RECIPIENT_UEI), SUM(TRY_TO_DOUBLE(FEDERAL_ACTION_OBLIGATION::VARCHAR)) FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_USASPENDING_CONTRACTS_FULL_R2 GROUP BY 1,2
  UNION ALL SELECT 'ASSISTANCE_FULL', TRIM(RECIPIENT_UEI), SUM(TRY_TO_DOUBLE(FEDERAL_ACTION_OBLIGATION::VARCHAR)) FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_USASPENDING_ASSISTANCE_FULL GROUP BY 1,2)
SELECT a.t, COUNT_IF(a.u<>'') ueis, ROUND(SUM(a.usd)/1e9,1) usd_b,
 COUNT(f.u) in_xwalk,
 COUNT_IF(f.air=1) to_air, ROUND(SUM(IFF(f.air=1,a.usd,0))/1e9,1) air_usd_b, MEDIAN(IFF(f.air=1,a.usd,NULL)) air_med, MEDIAN(IFF(f.air=0,a.usd,NULL)) xw_not_air_med, MEDIAN(IFF(f.u IS NULL AND a.u<>'',a.usd,NULL)) not_xw_med,
 COUNT_IF(f.fcase=1) to_case, ROUND(SUM(IFF(f.fcase=1,a.usd,0))/1e9,1) case_usd_b, MEDIAN(IFF(f.fcase=1,a.usd,NULL)) case_med, MEDIAN(IFF(f.fcase=0,a.usd,NULL)) xw_not_case_med,
 COUNT_IF(f.finf=1) to_inf, ROUND(SUM(IFF(f.finf=1,a.usd,0))/1e9,1) inf_usd_b
FROM a LEFT JOIN f ON f.u=a.u GROUP BY 1 ORDER BY 1;

-- [6] ICIS air gap: class, major, operating, HPV, matched vs not
WITH x AS (SELECT DISTINCT TRIM(EPA_REGISTRY_ID) r FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__XC_EPA_CORPORATE_CROSSWALK WHERE TRIM(PARENT_UEI)<>'')
SELECT IFF(x.r IS NULL,'not matched','contractor-matched') grp, COUNT(*) rows_,
 COUNT_IF(TRIM(i.AIR_POLLUTANT_CLASS_DESC)<>'') has_class,
 COUNT_IF(i.AIR_POLLUTANT_CLASS_DESC ILIKE 'Major%') major_rows,
 COUNT_IF(i.AIR_OPERATING_STATUS_DESC ILIKE 'Operating%') operating,
 COUNT_IF(UPPER(TRIM(i.CURRENT_HPV::VARCHAR)) NOT IN ('','N','NO','FALSE','0') AND i.CURRENT_HPV IS NOT NULL) hpv_rows,
 LISTAGG(DISTINCT LEFT(i.CURRENT_HPV::VARCHAR,30), ' / ') hpv_values
FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_FACILITIES i LEFT JOIN x ON x.r=TRIM(i.REGISTRY_ID)
GROUP BY 1;

-- [7] ICIS air CURRENT_HPV values, matched vs not, with major split
WITH x AS (SELECT DISTINCT TRIM(EPA_REGISTRY_ID) r FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__XC_EPA_CORPORATE_CROSSWALK WHERE TRIM(PARENT_UEI)<>'')
SELECT COALESCE(i.CURRENT_HPV::VARCHAR,'<null>') hpv, COUNT_IF(x.r IS NOT NULL) matched, COUNT_IF(x.r IS NULL) not_matched,
 COUNT_IF(x.r IS NOT NULL AND i.AIR_POLLUTANT_CLASS_DESC ILIKE 'Major%') matched_major, COUNT_IF(x.r IS NULL AND i.AIR_POLLUTANT_CLASS_DESC ILIKE 'Major%') not_matched_major
FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_FACILITIES i LEFT JOIN x ON x.r=TRIM(i.REGISTRY_ID)
GROUP BY 1 ORDER BY 3 DESC;

-- [8] contractor-linked air facilities in open HPV status, R2 dollars 2024 on
WITH h AS (SELECT TRIM(i.REGISTRY_ID) r, i.FACILITY_NAME fn, i.CITY, i.STATE, i.CURRENT_HPV hpv, i.AIR_POLLUTANT_CLASS_DESC cls, x.PARENT_UEI u, x.FACILITY_NAME xfn
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_FACILITIES i
  JOIN LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__XC_EPA_CORPORATE_CROSSWALK x ON TRIM(x.EPA_REGISTRY_ID)=TRIM(i.REGISTRY_ID) AND TRIM(x.PARENT_UEI)<>''
  WHERE i.CURRENT_HPV IN ('Unaddressed-State','Violation-Unresolved','Unaddressed-Local','Unaddressed-EPA','Violation w/in 1 Year')),
r AS (SELECT TRIM(RECIPIENT_UEI) u, MAX(RECIPIENT_NAME) rn, SUM(TRY_TO_DOUBLE(FEDERAL_ACTION_OBLIGATION::VARCHAR)) usd_all,
  SUM(IFF(TRY_TO_DATE(ACTION_DATE::VARCHAR)>='2024-01-01',TRY_TO_DOUBLE(FEDERAL_ACTION_OBLIGATION::VARCHAR),0)) usd_2024on, MAX(ACTION_DATE::VARCHAR) last_action
  FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_USASPENDING_CONTRACTS_FULL_R2 WHERE TRIM(RECIPIENT_UEI) IN (SELECT TRIM(u) FROM h) GROUP BY 1)
SELECT h.hpv, h.fn, h.CITY, h.STATE, LEFT(h.cls,20) cls, h.u, r.rn, ROUND(r.usd_all/1e6,1) usd_all_m, ROUND(r.usd_2024on/1e6,1) usd_2024on_m, r.last_action
FROM h LEFT JOIN r ON r.u=TRIM(h.u) ORDER BY r.usd_2024on DESC NULLS LAST;

-- [9] FEC case conclusions: top contractors by case count + random 20 name check
WITH x AS (SELECT TRIM(EPA_REGISTRY_ID) r, TRIM(PARENT_UEI) u FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__XC_EPA_CORPORATE_CROSSWALK WHERE TRIM(PARENT_UEI)<>''),
c AS (SELECT x.u, COUNT(DISTINCT f.CASE_NUMBER) cases, COUNT(DISTINCT f.FACILITY_UIN) sites, MAX(f.FACILITY_NAME) fec_name, MAX(f.FACILITY_STATE) st, MAX(f.CASE_NUMBER) sample_case
  FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_EPA_ICIS_FEC_CASE_ENFORCEMENT_CONCLUSION_FACILITIES f JOIN x ON x.r=TRIM(f.FACILITY_UIN) GROUP BY 1),
r AS (SELECT TRIM(RECIPIENT_UEI) u, MAX(RECIPIENT_NAME) rn, MAX(RECIPIENT_STATE_CODE) rst, SUM(TRY_TO_DOUBLE(FEDERAL_ACTION_OBLIGATION::VARCHAR)) usd
  FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_USASPENDING_CONTRACTS_FULL_R2 WHERE TRIM(RECIPIENT_UEI) IN (SELECT u FROM c) GROUP BY 1)
SELECT * FROM (
 SELECT 'top_by_cases' k, c.*, r.rn, r.rst, ROUND(r.usd/1e6,1) usd_m FROM c LEFT JOIN r ON r.u=c.u QUALIFY ROW_NUMBER() OVER (ORDER BY c.cases DESC)<=15
 UNION ALL
 SELECT 'random20', c.*, r.rn, r.rst, ROUND(r.usd/1e6,1) FROM c LEFT JOIN r ON r.u=c.u QUALIFY ROW_NUMBER() OVER (ORDER BY HASH(c.u))<=20)
ORDER BY k, cases DESC;

-- [10] ASSISTANCE_FULL money before/after first EPA informal action (FEC) per crosswalk UEI
WITH x AS (SELECT TRIM(EPA_REGISTRY_ID) r, TRIM(PARENT_UEI) u FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__XC_EPA_CORPORATE_CROSSWALK WHERE TRIM(PARENT_UEI)<>''),
e AS (SELECT x.u, MIN(TRY_TO_DATE(i.ACHIEVED_DATE::VARCHAR)) first_enf, MAX(TRY_TO_DATE(i.ACHIEVED_DATE::VARCHAR)) last_enf, COUNT(*) acts,
   LISTAGG(DISTINCT i.STATUTE, '/') statutes, MAX(i.ENF_TYPE_DESC) enf_type
  FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_EPA_ICIS_FEC_EPA_INFORMAL_ENFORCEMENT_ACTIONS i JOIN x ON x.r=TRIM(i.REGISTRY_ID)
  WHERE TRY_TO_DATE(i.ACHIEVED_DATE::VARCHAR) BETWEEN '1990-01-01' AND '2026-09-24' GROUP BY 1),
a AS (SELECT TRIM(RECIPIENT_UEI) u, TRY_TO_DATE(ACTION_DATE::VARCHAR) dt, TRY_TO_DOUBLE(FEDERAL_ACTION_OBLIGATION::VARCHAR) usd, RECIPIENT_NAME rn, AWARDING_AGENCY_NAME ag
  FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_USASPENDING_ASSISTANCE_FULL WHERE TRIM(RECIPIENT_UEI) IN (SELECT u FROM e))
SELECT e.u, MAX(a.rn) rn, MAX(a.ag) agency, e.first_enf, e.last_enf, e.acts, e.statutes, e.enf_type, MIN(a.dt) a0, MAX(a.dt) a1,
 ROUND(SUM(IFF(a.dt<e.first_enf,a.usd,0))/1e6,1) before_m, ROUND(SUM(IFF(a.dt>=e.first_enf,a.usd,0))/1e6,1) after_m, COUNT_IF(a.dt>=e.first_enf) after_actions
FROM e JOIN a ON a.u=e.u GROUP BY e.u, e.first_enf, e.last_enf, e.acts, e.statutes, e.enf_type ORDER BY after_m DESC NULLS LAST LIMIT 30;

-- [11] ECHO facilities whose crosswalk UEI is in SAM exclusions: who, which agency, dates, penalties
WITH x AS (SELECT TRIM(EPA_REGISTRY_ID) r, TRIM(PARENT_UEI) u, FACILITY_NAME xfn FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__XC_EPA_CORPORATE_CROSSWALK WHERE TRIM(PARENT_UEI)<>''),
s AS (SELECT TRIM(UEI) u, MAX(ENTITY_NAME) sam_name, LISTAGG(DISTINCT EXCLUDING_AGENCY,'/') agency, LISTAGG(DISTINCT EXCLUSION_TYPE,'/') etype, MIN(ACTIVATION_DATE) act0, MAX(TERMINATION_DATE) term1, MAX(STATE) sam_st, MAX(IS_CURRENTLY_EXCLUDED::VARCHAR) cur
  FROM LIBRARY_MARTS.PROCUREMENT.PROCUREMENT__FED_SAM_EXCLUSIONS WHERE LENGTH(TRIM(UEI))=12 GROUP BY 1)
SELECT x.u, s.sam_name, e.FACILITY_NAME echo_name, e.CITY, e.STATE, s.sam_st, s.agency, LEFT(s.etype,40) etype, s.act0, s.term1, s.cur,
  e.TOTAL_PENALTIES, e.DATE_LAST_PENALTY, e.FORMAL_ACTION_COUNT, e.DATE_LAST_FORMAL_ACTION, e.COMPLIANCE_STATUS, e.PENALTY_GAP_FLAG,
  IFF(x.r IN (SELECT TRIM(FRS_ID) FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__EPA_PENALTY_GAP),'Y','N') in_gap
FROM x JOIN s ON s.u=x.u JOIN LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ECHO e ON TRIM(e.FRS_ID)=x.r
ORDER BY s.act0;

-- [12] ECHO: penalty date set but TOTAL_PENALTIES zero - trap check
SELECT COUNT(*) n, COUNT_IF(DATE_LAST_PENALTY IS NOT NULL) has_pen_date,
 COUNT_IF(DATE_LAST_PENALTY IS NOT NULL AND COALESCE(TOTAL_PENALTIES,0)=0) pen_date_zero_total,
 COUNT_IF(DATE_LAST_PENALTY IS NOT NULL AND COALESCE(TOTAL_PENALTIES,0)=0 AND COALESCE(LAST_PENALTY_AMT,0)>0) of_which_last_amt_pos,
 COUNT_IF(COALESCE(TOTAL_PENALTIES,0)>0) total_pos, COUNT_IF(COALESCE(LAST_PENALTY_AMT,0)>0) last_amt_pos,
 COUNT_IF(COALESCE(PENALTY_COUNT,0)>0) pen_count_pos,
 COUNT_IF(COALESCE(PENALTY_COUNT,0)>0 AND COALESCE(TOTAL_PENALTIES,0)=0) pen_count_pos_total_zero,
 COUNT_IF(COALESCE(LAST_PENALTY_AMT,0)>COALESCE(TOTAL_PENALTIES,0)) last_gt_total
FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ECHO;

-- [13] USASPENDING_BULK 50K sample: land via crosswalk to 4 EPA tables
WITH x AS (SELECT TRIM(EPA_REGISTRY_ID) r, TRIM(PARENT_UEI) u FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__XC_EPA_CORPORATE_CROSSWALK WHERE TRIM(PARENT_UEI)<>''),
b AS (SELECT TRIM(RECIPIENT_UEI) u, SUM(TRY_TO_DOUBLE(FEDERAL_ACTION_OBLIGATION::VARCHAR)) usd, MIN(ACTION_DATE::VARCHAR) d0, MAX(ACTION_DATE::VARCHAR) d1 FROM LIBRARY_MARTS.PROCUREMENT.PROCUREMENT__FED_USASPENDING_BULK GROUP BY 1),
f AS (SELECT x.u,
  MAX(IFF(x.r IN (SELECT REGISTRY_ID::VARCHAR FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_AIR_EMISSIONS_POLL_RPT_COMBINED_EMISSIONS),1,0)) em,
  MAX(IFF(x.r IN (SELECT TRIM(REGISTRY_ID) FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_FACILITIES),1,0)) air,
  MAX(IFF(x.r IN (SELECT TRIM(REGISTRY_ID) FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_NPDES_NPDES_INFORMAL_ENFORCEMENT_ACTIONS),1,0)) npdes,
  MAX(IFF(x.r IN (SELECT TRIM(FACILITY_UIN) FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_EPA_ICIS_FEC_CASE_ENFORCEMENT_CONCLUSION_FACILITIES),1,0)) fcase
  FROM x GROUP BY 1)
SELECT COUNT(*) bulk_ueis, MIN(b.d0) d0, MAX(b.d1) d1, ROUND(SUM(b.usd)/1e9,2) usd_b, COUNT(f.u) in_xwalk, COUNT_IF(f.em=1) to_emis, COUNT_IF(f.air=1) to_icis_air, COUNT_IF(f.npdes=1) to_npdes_inf, COUNT_IF(f.fcase=1) to_fec_case,
 ROUND(SUM(IFF(f.air=1,b.usd,0))/1e6,1) air_usd_m
FROM b LEFT JOIN f ON f.u=b.u WHERE b.u<>'';

-- [14] Open Payments CCN -> hospital xwalk -> OSHA EIN land, my 5 year pairs
WITH x AS (SELECT TRIM(CCN) c, MAX(LPAD(TRIM(EIN),9,'0')) e FROM LIBRARY_MARTS.CORE.XWALK_HOSPITAL_CCN_EIN WHERE TRIM(CCN)<>'' GROUP BY 1),
op AS (SELECT 'OP2024' t, TRIM(CCN) c FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_OPEN_PAYMENTS WHERE TRIM(CCN)<>'' GROUP BY 2
  UNION ALL SELECT 'OP2023', TRIM(CCN) FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_OPEN_PAYMENTS_2023 WHERE TRIM(CCN)<>'' GROUP BY 2),
o AS (
  SELECT '300A2023' t, LPAD(TRIM(EIN),9,'0') e FROM LIBRARY_MARTS.LABOR.LABOR__FED_OSHA_ITA_300A_SUMMARY_2023 WHERE REGEXP_LIKE(TRIM(EIN),'^[0-9]{8,9}$') AND TRY_TO_NUMBER(EIN)>0 GROUP BY 2
  UNION ALL SELECT '300A2024', LPAD(TRIM(EIN),9,'0') FROM LIBRARY_MARTS.LABOR.LABOR__FED_OSHA_ITA_300A_SUMMARY_2024 WHERE REGEXP_LIKE(TRIM(EIN),'^[0-9]{8,9}$') AND TRY_TO_NUMBER(EIN)>0 GROUP BY 2
  UNION ALL SELECT '300A2025', LPAD(TRIM(EIN),9,'0') FROM LIBRARY_MARTS.LABOR.LABOR__FED_OSHA_ITA_300A_SUMMARY_2025 WHERE REGEXP_LIKE(TRIM(EIN),'^[0-9]{8,9}$') AND TRY_TO_NUMBER(EIN)>0 GROUP BY 2
  UNION ALL SELECT 'CD2025', LPAD(TRIM(EIN),9,'0') FROM LIBRARY_MARTS.LABOR.LABOR__FED_OSHA_ITA_CASE_DETAIL_2025 WHERE REGEXP_LIKE(TRIM(EIN),'^[0-9]{8,9}$') AND TRY_TO_NUMBER(EIN)>0 GROUP BY 2)
SELECT op.t a, tt.t c, COUNT(DISTINCT op.c) a_ccns, COUNT(DISTINCT x.c) in_xwalk, COUNT(DISTINCT IFF(o.e IS NOT NULL, op.c, NULL)) reach_c, COUNT(DISTINCT o.e) eins
FROM op LEFT JOIN x ON x.c=op.c
CROSS JOIN (SELECT DISTINCT t FROM o) tt
LEFT JOIN o ON o.e=x.e AND o.t=tt.t
WHERE (op.t='OP2024') OR (op.t='OP2023' AND tt.t='CD2025')
GROUP BY 1,2 ORDER BY 1,2;

-- [15] Gap within hospitals (NAICS 6221): injury rate by Open Payments tier, 300A 2024
WITH x AS (SELECT TRIM(CCN) c, MAX(LPAD(TRIM(EIN),9,'0')) e FROM LIBRARY_MARTS.CORE.XWALK_HOSPITAL_CCN_EIN WHERE TRIM(CCN)<>'' GROUP BY 1),
op AS (SELECT TRIM(CCN) c, SUM(TRY_TO_DOUBLE(TOTAL_AMOUNT_OF_PAYMENT_USDOLLARS::VARCHAR)) usd FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_OPEN_PAYMENTS WHERE TRIM(CCN)<>'' GROUP BY 1),
ope AS (SELECT x.e, SUM(op.usd) usd FROM op JOIN x ON x.c=op.c GROUP BY 1),
opt AS (SELECT e, usd, NTILE(3) OVER (ORDER BY usd) tier FROM ope),
xe AS (SELECT DISTINCT e FROM x),
s AS (SELECT LPAD(TRIM(EIN),9,'0') e, TRY_TO_DOUBLE(TOTAL_HOURS_WORKED::VARCHAR) hrs, TRY_TO_DOUBLE(ANNUAL_AVERAGE_EMPLOYEES::VARCHAR) emp,
   COALESCE(TRY_TO_DOUBLE(TOTAL_DAFW_CASES::VARCHAR),0)+COALESCE(TRY_TO_DOUBLE(TOTAL_DJTR_CASES::VARCHAR),0)+COALESCE(TRY_TO_DOUBLE(TOTAL_OTHER_CASES::VARCHAR),0) rec,
   COALESCE(TRY_TO_DOUBLE(TOTAL_DAFW_CASES::VARCHAR),0) dafw, COALESCE(TRY_TO_DOUBLE(TOTAL_DEATHS::VARCHAR),0) deaths
  FROM LIBRARY_MARTS.LABOR.LABOR__FED_OSHA_ITA_300A_SUMMARY_2024
  WHERE LEFT(TRIM(NAICS_CODE::VARCHAR),4)='6221' AND REGEXP_LIKE(TRIM(EIN),'^[0-9]{8,9}$') AND TRY_TO_NUMBER(EIN)>0
    AND TRY_TO_DOUBLE(TOTAL_HOURS_WORKED::VARCHAR) BETWEEN 1000 AND 2e8 AND TRY_TO_DOUBLE(ANNUAL_AVERAGE_EMPLOYEES::VARCHAR) < 100000)
SELECT CASE WHEN opt.e IS NOT NULL THEN 'OP-paid tier '||opt.tier WHEN xe.e IS NOT NULL THEN 'in xwalk, no OP' ELSE 'hospital not in xwalk' END grp,
 COUNT(*) sites, COUNT(DISTINCT s.e) eins, ROUND(SUM(s.emp)) emp, SUM(s.deaths) deaths,
 ROUND(SUM(s.rec)*200000/SUM(s.hrs),2) tcir_pooled, ROUND(MEDIAN(s.rec*200000/s.hrs),2) tcir_median, ROUND(SUM(s.dafw)*200000/SUM(s.hrs),2) dart_pooled,
 ROUND(MEDIAN(opt.usd)) med_op_usd, ROUND(MEDIAN(s.emp)) med_emp
FROM s LEFT JOIN opt ON opt.e=s.e LEFT JOIN xe ON xe.e=s.e GROUP BY 1 ORDER BY 1;

-- [16] CD2025 hospitals: employees and violent-incident share, OP-paid vs other
WITH x AS (SELECT TRIM(CCN) c, MAX(LPAD(TRIM(EIN),9,'0')) e FROM LIBRARY_MARTS.CORE.XWALK_HOSPITAL_CCN_EIN WHERE TRIM(CCN)<>'' GROUP BY 1),
ope AS (SELECT DISTINCT x.e FROM (SELECT DISTINCT TRIM(CCN) c FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_OPEN_PAYMENTS WHERE TRIM(CCN)<>'') op JOIN x ON x.c=op.c),
d AS (SELECT LPAD(TRIM(EIN),9,'0') e, ESTABLISHMENT_ID est, TRY_TO_DOUBLE(ANNUAL_AVERAGE_EMPLOYEES::VARCHAR) emp, TRY_TO_DOUBLE(TOTAL_HOURS_WORKED::VARCHAR) hrs,
   IFF(REGEXP_LIKE(UPPER(COALESCE(NEW_NAR_WHAT_HAPPENED,'')||' '||COALESCE(NEW_INCIDENT_DESCRIPTION,'')), '.*(ASSAULT|COMBATIVE|AGGRESSIVE|PUNCH|KICKED|BIT |BITTEN|STRUCK BY (A |THE )?PATIENT|HIT BY (A |THE )?PATIENT|ATTACK).*'),1,0) violent,
   IFF(TRY_TO_DATE(DATE_OF_DEATH::VARCHAR) IS NOT NULL,1,0) died
  FROM LIBRARY_MARTS.LABOR.LABOR__FED_OSHA_ITA_CASE_DETAIL_2025
  WHERE LEFT(TRIM(NAICS_CODE::VARCHAR),4)='6221' AND REGEXP_LIKE(TRIM(EIN),'^[0-9]{8,9}$') AND TRY_TO_NUMBER(EIN)>0),
est AS (SELECT e, est, MAX(emp) emp, MAX(hrs) hrs, COUNT(*) cases, SUM(violent) violent, SUM(died) died FROM d GROUP BY 1,2)
SELECT IFF(ope.e IS NOT NULL,'OP-paid hospital EIN','other hospital EIN') grp, COUNT(*) establishments, COUNT(DISTINCT est.e) eins,
 SUM(cases) cases, SUM(violent) violent_cases, ROUND(SUM(violent)/SUM(cases)*100,1) violent_pct, SUM(died) deaths,
 ROUND(MEDIAN(emp)) med_emp, ROUND(AVG(IFF(emp<1e6,emp,NULL))) avg_emp_capped, COUNT_IF(emp>=1e6) emp_over_1m,
 ROUND(SUM(IFF(hrs BETWEEN 1000 AND 2e8, violent,0))*200000/SUM(IFF(hrs BETWEEN 1000 AND 2e8, hrs,0)),3) violent_per_100fte
FROM est LEFT JOIN ope ON ope.e=est.e GROUP BY 1;

