
-- [1]
-- EIN profile across all 9 EIN tables in my rows: rows, non-blank, widths, zero placeholder, distinct normalized
WITH src AS (
  SELECT 'IRS527' t, EIN::string e FROM LIBRARY_MARTS.FINANCE.FED_IRS527_SCHEDULE_A_CONTRIBUTIONS
  UNION ALL SELECT 'HOP', EIN::string FROM LIBRARY_MARTS.HEALTH.HOSPITAL_OFFICER_PAY
  UNION ALL SELECT 'F5500_EIN', EIN::string FROM LIBRARY_MARTS.ECONOMICS.FED_DOL_FORM5500
  UNION ALL SELECT 'F5500_SPONS', SPONS_DFE_EIN::string FROM LIBRARY_MARTS.ECONOMICS.FED_DOL_FORM5500
  UNION ALL SELECT 'A300_2023', EIN::string FROM LIBRARY_MARTS.LABOR.FED_OSHA_ITA_300A_SUMMARY_2023
  UNION ALL SELECT 'A300_2024', EIN::string FROM LIBRARY_MARTS.LABOR.FED_OSHA_ITA_300A_SUMMARY_2024
  UNION ALL SELECT 'A300_2025', EIN::string FROM LIBRARY_MARTS.LABOR.FED_OSHA_ITA_300A_SUMMARY_2025
  UNION ALL SELECT 'CD_2023', EIN::string FROM LIBRARY_MARTS.LABOR.FED_OSHA_ITA_CASE_DETAIL_2023
  UNION ALL SELECT 'CD_2024', EIN::string FROM LIBRARY_MARTS.LABOR.FED_OSHA_ITA_CASE_DETAIL_2024
  UNION ALL SELECT 'CD_2025', EIN::string FROM LIBRARY_MARTS.LABOR.FED_OSHA_ITA_CASE_DETAIL_2025
), n AS (SELECT t, e, REGEXP_REPLACE(e,'[^0-9]','') d FROM src)
SELECT t, COUNT(*) n_rows, COUNT_IF(NULLIF(TRIM(e),'') IS NOT NULL) nonblank,
  COUNT_IF(LENGTH(d)=9) w9, COUNT_IF(LENGTH(d)=8) w8, COUNT_IF(LENGTH(d) BETWEEN 1 AND 7) w_short, COUNT_IF(LENGTH(d)>9) w_long,
  COUNT_IF(LENGTH(d)>0 AND LPAD(d,9,'0')='000000000') zeros,
  COUNT(DISTINCT IFF(LENGTH(d) BETWEEN 7 AND 9 AND LPAD(d,9,'0')<>'000000000', LPAD(d,9,'0'), NULL)) distinct_ein
FROM n GROUP BY t ORDER BY t;

-- [2]
SELECT FORM_ID_NUMBER, ORG_NAME, EIN, CONTRIBUTOR_NAME, CONTRIBUTOR_STATE, CONTRIBUTOR_EMPLOYER, CONTRIBUTION_AMOUNT, CONTRIBUTION_DATE FROM LIBRARY_MARTS.FINANCE.FED_IRS527_SCHEDULE_A_CONTRIBUTIONS LIMIT 5;

-- [3]
SELECT EIN, HOSPITAL_NAME, FILER_NAME, HOSPITAL_STATE, TAX_YEAR, PERSON_NAME, TITLE, OTHER_COMPENSATION, TOTAL_COMPENSATION FROM LIBRARY_MARTS.HEALTH.HOSPITAL_OFFICER_PAY LIMIT 5;

-- [4]
SELECT EIN, SPONS_DFE_EIN, SPONSOR_DFE_EIN, ADMIN_EIN, PREPARER_EIN, LAST_RPT_SPONS_EIN, SPONSOR_DFE_NAME, SPONS_DFE_MAIL_US_STATE, PLAN_NAME, FORM_YEAR, NET_ASSETS_EOY_AMT FROM LIBRARY_MARTS.ECONOMICS.FED_DOL_FORM5500 LIMIT 5;

-- [5]
SELECT 'A300' t, EIN, COMPANY_NAME, ESTABLISHMENT_NAME, STATE, ANNUAL_AVERAGE_EMPLOYEES::string emp, TOTAL_DEATHS::string deaths, YEAR_FILING_FOR::string yr FROM (SELECT * FROM LIBRARY_MARTS.LABOR.FED_OSHA_ITA_300A_SUMMARY_2023 LIMIT 5)
UNION ALL SELECT 'CD', EIN, COMPANY_NAME, ESTABLISHMENT_NAME, STATE, ANNUAL_AVERAGE_EMPLOYEES::string, INCIDENT_OUTCOME::string, YEAR_FILING_FOR::string FROM (SELECT * FROM LIBRARY_MARTS.LABOR.FED_OSHA_ITA_CASE_DETAIL_2023 LIMIT 5);

-- [6]
-- EIN profile across all 9 EIN tables in my rows: rows, non-blank, widths, zero placeholder, distinct normalized
WITH src AS (
  SELECT 'IRS527' t, EIN::string e FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_IRS527_SCHEDULE_A_CONTRIBUTIONS
  UNION ALL SELECT 'HOP', EIN::string FROM LIBRARY_MARTS.HEALTH.HEALTH__HOSPITAL_OFFICER_PAY
  UNION ALL SELECT 'F5500_EIN', EIN::string FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_DOL_FORM5500
  UNION ALL SELECT 'F5500_SPONS', SPONS_DFE_EIN::string FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_DOL_FORM5500
  UNION ALL SELECT 'A300_2023', EIN::string FROM LIBRARY_MARTS.LABOR.LABOR__FED_OSHA_ITA_300A_SUMMARY_2023
  UNION ALL SELECT 'A300_2024', EIN::string FROM LIBRARY_MARTS.LABOR.LABOR__FED_OSHA_ITA_300A_SUMMARY_2024
  UNION ALL SELECT 'A300_2025', EIN::string FROM LIBRARY_MARTS.LABOR.LABOR__FED_OSHA_ITA_300A_SUMMARY_2025
  UNION ALL SELECT 'CD_2023', EIN::string FROM LIBRARY_MARTS.LABOR.LABOR__FED_OSHA_ITA_CASE_DETAIL_2023
  UNION ALL SELECT 'CD_2024', EIN::string FROM LIBRARY_MARTS.LABOR.LABOR__FED_OSHA_ITA_CASE_DETAIL_2024
  UNION ALL SELECT 'CD_2025', EIN::string FROM LIBRARY_MARTS.LABOR.LABOR__FED_OSHA_ITA_CASE_DETAIL_2025
), n AS (SELECT t, e, REGEXP_REPLACE(e,'[^0-9]','') d FROM src)
SELECT t, COUNT(*) n_rows, COUNT_IF(NULLIF(TRIM(e),'') IS NOT NULL) nonblank,
  COUNT_IF(LENGTH(d)=9) w9, COUNT_IF(LENGTH(d)=8) w8, COUNT_IF(LENGTH(d) BETWEEN 1 AND 7) w_short, COUNT_IF(LENGTH(d)>9) w_long,
  COUNT_IF(LENGTH(d)>0 AND LPAD(d,9,'0')='000000000') zeros,
  COUNT(DISTINCT IFF(LENGTH(d) BETWEEN 7 AND 9 AND LPAD(d,9,'0')<>'000000000', LPAD(d,9,'0'), NULL)) distinct_ein
FROM n GROUP BY t ORDER BY t;

-- [7]
SELECT FORM_ID_NUMBER, ORG_NAME, EIN, CONTRIBUTOR_NAME, CONTRIBUTOR_STATE, CONTRIBUTOR_EMPLOYER, CONTRIBUTION_AMOUNT, CONTRIBUTION_DATE FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_IRS527_SCHEDULE_A_CONTRIBUTIONS LIMIT 5;

-- [8]
SELECT EIN, HOSPITAL_NAME, FILER_NAME, HOSPITAL_STATE, TAX_YEAR, PERSON_NAME, TITLE, OTHER_COMPENSATION, TOTAL_COMPENSATION FROM LIBRARY_MARTS.HEALTH.HEALTH__HOSPITAL_OFFICER_PAY LIMIT 5;

-- [9]
SELECT EIN, SPONS_DFE_EIN, SPONSOR_DFE_EIN, ADMIN_EIN, PREPARER_EIN, LAST_RPT_SPONS_EIN, SPONSOR_DFE_NAME, SPONS_DFE_MAIL_US_STATE, PLAN_NAME, FORM_YEAR, NET_ASSETS_EOY_AMT FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_DOL_FORM5500 LIMIT 5;

-- [10]
SELECT 'A300' t, EIN, COMPANY_NAME, ESTABLISHMENT_NAME, STATE, ANNUAL_AVERAGE_EMPLOYEES::string emp, TOTAL_DEATHS::string deaths, YEAR_FILING_FOR::string yr FROM (SELECT * FROM LIBRARY_MARTS.LABOR.LABOR__FED_OSHA_ITA_300A_SUMMARY_2023 LIMIT 5)
UNION ALL SELECT 'CD', EIN, COMPANY_NAME, ESTABLISHMENT_NAME, STATE, ANNUAL_AVERAGE_EMPLOYEES::string, INCIDENT_OUTCOME::string, YEAR_FILING_FOR::string FROM (SELECT * FROM LIBRARY_MARTS.LABOR.LABOR__FED_OSHA_ITA_CASE_DETAIL_2023 LIMIT 5);

-- [11]
-- EIN overlap, all 18 EIN pairs in one pass: matched EINs, name agreement (Jaro-Winkler>=85 or same first word), state agreement, OSHA deaths on matched EINs
WITH osha AS (
  SELECT 'A300_2023' t, LPAD(REGEXP_REPLACE(EIN,'[^0-9]',''),9,'0') ein, MODE(UPPER(COMPANY_NAME)) nm, MODE(STATE) st, COUNT(*) n, SUM(TRY_TO_NUMBER(TOTAL_DEATHS::string)) deaths, SUM(TRY_TO_NUMBER(ANNUAL_AVERAGE_EMPLOYEES::string)) emp FROM LIBRARY_MARTS.LABOR.LABOR__FED_OSHA_ITA_300A_SUMMARY_2023 GROUP BY 2
  UNION ALL SELECT 'A300_2024', LPAD(REGEXP_REPLACE(EIN,'[^0-9]',''),9,'0'), MODE(UPPER(COMPANY_NAME)), MODE(STATE), COUNT(*), SUM(TRY_TO_NUMBER(TOTAL_DEATHS::string)), SUM(TRY_TO_NUMBER(ANNUAL_AVERAGE_EMPLOYEES::string)) FROM LIBRARY_MARTS.LABOR.LABOR__FED_OSHA_ITA_300A_SUMMARY_2024 GROUP BY 2
  UNION ALL SELECT 'A300_2025', LPAD(REGEXP_REPLACE(EIN,'[^0-9]',''),9,'0'), MODE(UPPER(COMPANY_NAME)), MODE(STATE), COUNT(*), SUM(TRY_TO_NUMBER(TOTAL_DEATHS::string)), SUM(TRY_TO_NUMBER(ANNUAL_AVERAGE_EMPLOYEES::string)) FROM LIBRARY_MARTS.LABOR.LABOR__FED_OSHA_ITA_300A_SUMMARY_2025 GROUP BY 2
  UNION ALL SELECT 'CD_2023', LPAD(REGEXP_REPLACE(EIN,'[^0-9]',''),9,'0'), MODE(UPPER(COMPANY_NAME)), MODE(STATE), COUNT(*), COUNT_IF(DATE_OF_DEATH IS NOT NULL AND TRIM(DATE_OF_DEATH::string)<>''), MAX(TRY_TO_NUMBER(ANNUAL_AVERAGE_EMPLOYEES::string)) FROM LIBRARY_MARTS.LABOR.LABOR__FED_OSHA_ITA_CASE_DETAIL_2023 GROUP BY 2
  UNION ALL SELECT 'CD_2024', LPAD(REGEXP_REPLACE(EIN,'[^0-9]',''),9,'0'), MODE(UPPER(COMPANY_NAME)), MODE(STATE), COUNT(*), COUNT_IF(DATE_OF_DEATH IS NOT NULL AND TRIM(DATE_OF_DEATH::string)<>''), MAX(TRY_TO_NUMBER(ANNUAL_AVERAGE_EMPLOYEES::string)) FROM LIBRARY_MARTS.LABOR.LABOR__FED_OSHA_ITA_CASE_DETAIL_2024 GROUP BY 2
  UNION ALL SELECT 'CD_2025', LPAD(REGEXP_REPLACE(EIN,'[^0-9]',''),9,'0'), MODE(UPPER(COMPANY_NAME)), MODE(STATE), COUNT(*), COUNT_IF(DATE_OF_DEATH IS NOT NULL AND TRIM(DATE_OF_DEATH::string)<>''), MAX(TRY_TO_NUMBER(ANNUAL_AVERAGE_EMPLOYEES::string)) FROM LIBRARY_MARTS.LABOR.LABOR__FED_OSHA_ITA_CASE_DETAIL_2025 GROUP BY 2
), a AS (
  SELECT 'IRS527' s, LPAD(REGEXP_REPLACE(EIN,'[^0-9]',''),9,'0') ein, MODE(UPPER(ORG_NAME)) nm, NULL::string st, SUM(CONTRIBUTION_AMOUNT) amt FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_IRS527_SCHEDULE_A_CONTRIBUTIONS GROUP BY 2
  UNION ALL SELECT 'HOP', LPAD(REGEXP_REPLACE(EIN,'[^0-9]',''),9,'0'), MODE(UPPER(HOSPITAL_NAME)), MODE(HOSPITAL_STATE), SUM(OTHER_COMPENSATION) FROM LIBRARY_MARTS.HEALTH.HEALTH__HOSPITAL_OFFICER_PAY GROUP BY 2
  UNION ALL SELECT 'F5500', LPAD(REGEXP_REPLACE(SPONS_DFE_EIN,'[^0-9]',''),9,'0'), MODE(UPPER(SPONSOR_DFE_NAME)), MODE(SPONS_DFE_MAIL_US_STATE), SUM(TRY_TO_NUMBER(NET_ASSETS_EOY_AMT::string)) FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_DOL_FORM5500 GROUP BY 2
), j AS (
  SELECT a.s, o.t, a.ein, a.nm anm, o.nm onm, a.st ast, o.st ost, o.deaths, o.n, o.emp, a.amt,
    REGEXP_REPLACE(a.nm,'[^A-Z0-9 ]','') an, REGEXP_REPLACE(o.nm,'[^A-Z0-9 ]','') on_
  FROM a JOIN osha o ON a.ein=o.ein WHERE a.ein<>'000000000' AND LENGTH(REGEXP_REPLACE(a.ein,'0',''))>0
)
SELECT s, t, COUNT(*) matched_ein,
  COUNT_IF(JAROWINKLER_SIMILARITY(an,on_)>=85 OR SPLIT_PART(an,' ',1)=SPLIT_PART(on_,' ',1)) name_agree,
  COUNT_IF(ast IS NOT NULL AND ost IS NOT NULL) st_both, COUNT_IF(ast=ost) st_agree,
  SUM(deaths) deaths_on_matched, SUM(n) osha_rows_matched, ROUND(SUM(amt)) a_amt_matched
FROM j GROUP BY 1,2 ORDER BY 1,2;

-- [12]
-- 20-row eyeball sample: hospital officer-pay EIN vs OSHA 300A 2023 company name and state
WITH o AS (SELECT LPAD(REGEXP_REPLACE(EIN,'[^0-9]',''),9,'0') ein, MODE(COMPANY_NAME) cn, MODE(ESTABLISHMENT_NAME) en, MODE(STATE) st FROM LIBRARY_MARTS.LABOR.LABOR__FED_OSHA_ITA_300A_SUMMARY_2023 GROUP BY 1),
h AS (SELECT EIN ein, MODE(HOSPITAL_NAME) hn, MODE(HOSPITAL_STATE) hs FROM LIBRARY_MARTS.HEALTH.HEALTH__HOSPITAL_OFFICER_PAY GROUP BY 1)
SELECT h.ein, hn, hs, cn, en, st FROM h JOIN o ON h.ein=o.ein ORDER BY HASH(h.ein) LIMIT 20;

-- [13]
-- 20-row eyeball sample: Form 5500 sponsor EIN vs OSHA 300A 2023
WITH o AS (SELECT LPAD(REGEXP_REPLACE(EIN,'[^0-9]',''),9,'0') ein, MODE(COMPANY_NAME) cn, MODE(STATE) st FROM LIBRARY_MARTS.LABOR.LABOR__FED_OSHA_ITA_300A_SUMMARY_2023 GROUP BY 1),
f AS (SELECT SPONS_DFE_EIN ein, MODE(SPONSOR_DFE_NAME) fn, MODE(SPONS_DFE_MAIL_US_STATE) fs FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_DOL_FORM5500 GROUP BY 1)
SELECT f.ein, fn, fs, cn, st FROM f JOIN o ON f.ein=o.ein ORDER BY HASH(f.ein) LIMIT 20;

-- [14]
-- Form 5500 fill rates: which money and year columns actually hold values
SELECT COUNT(*) n, COUNT(NET_ASSETS_EOY_AMT) net_assets, COUNT(TOTAL_ASSETS_EOY_AMT) tot_assets, COUNT(TOT_ACTIVE_PARTCP_CNT) active_partcp, COUNT(TOT_PARTCP_BOY_CNT) partcp_boy, COUNT(FORM_YEAR) form_year, MIN(FORM_PLAN_YEAR_BEGIN_DATE) min_py, MAX(FORM_PLAN_YEAR_BEGIN_DATE) max_py, COUNT(DISTINCT BUSINESS_CODE) naics_codes FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_DOL_FORM5500;

-- [15]
-- IRS527 recipient orgs: top 10 by dollars, to show who the EIN belongs to
SELECT EIN, MODE(ORG_NAME) org, COUNT(*) gifts, ROUND(SUM(CONTRIBUTION_AMOUNT)) dollars FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_IRS527_SCHEDULE_A_CONTRIBUTIONS GROUP BY 1 ORDER BY 4 DESC LIMIT 10;

-- [16]
-- Case-detail death markers per year: INCIDENT_OUTCOME values and DATE_OF_DEATH fill
SELECT '2023' y, INCIDENT_OUTCOME::string v, COUNT(*) n, COUNT_IF(NULLIF(TRIM(DATE_OF_DEATH::string),'') IS NOT NULL) dod FROM LIBRARY_MARTS.LABOR.LABOR__FED_OSHA_ITA_CASE_DETAIL_2023 GROUP BY 1,2
UNION ALL SELECT '2024', INCIDENT_OUTCOME::string, COUNT(*), COUNT_IF(NULLIF(TRIM(DATE_OF_DEATH::string),'') IS NOT NULL) FROM LIBRARY_MARTS.LABOR.LABOR__FED_OSHA_ITA_CASE_DETAIL_2024 GROUP BY 1,2
UNION ALL SELECT '2025', INCIDENT_OUTCOME::string, COUNT(*), COUNT_IF(NULLIF(TRIM(DATE_OF_DEATH::string),'') IS NOT NULL) FROM LIBRARY_MARTS.LABOR.LABOR__FED_OSHA_ITA_CASE_DETAIL_2025 GROUP BY 1,2
ORDER BY 1,2;

-- [17]
-- Hospitals: OSHA 300A 2023 injury rate (days-away cases per 100 FTE) on hospital EINs, top 10 with >=1M hours, with top officer pay in the latest tax year
WITH o AS (SELECT LPAD(REGEXP_REPLACE(EIN,'[^0-9]',''),9,'0') ein, COUNT(*) sites, SUM(TRY_TO_NUMBER(TOTAL_DAFW_CASES::string)) dafw, SUM(TRY_TO_NUMBER(TOTAL_INJURIES::string)) inj, SUM(TRY_TO_NUMBER(TOTAL_DEATHS::string)) deaths, SUM(TRY_TO_NUMBER(TOTAL_HOURS_WORKED::string)) hrs, SUM(TRY_TO_NUMBER(ANNUAL_AVERAGE_EMPLOYEES::string)) emp FROM LIBRARY_MARTS.LABOR.LABOR__FED_OSHA_ITA_300A_SUMMARY_2023 GROUP BY 1),
h AS (SELECT EIN ein, MODE(HOSPITAL_NAME) hn, MODE(HOSPITAL_STATE) hs, MAX(TAX_YEAR) ty FROM LIBRARY_MARTS.HEALTH.HEALTH__HOSPITAL_OFFICER_PAY GROUP BY 1),
p AS (SELECT EIN ein, TAX_YEAR ty, MAX(TOTAL_COMPENSATION) top_pay, SUM(TOTAL_COMPENSATION) all_pay FROM LIBRARY_MARTS.HEALTH.HEALTH__HOSPITAL_OFFICER_PAY GROUP BY 1,2)
SELECT h.ein, hn, hs, h.ty, sites, emp, hrs, dafw, inj, deaths, ROUND(dafw*200000/NULLIF(hrs,0),2) dafw_rate, ROUND(inj*200000/NULLIF(hrs,0),2) inj_rate, top_pay, all_pay
FROM h JOIN o ON h.ein=o.ein JOIN p ON p.ein=h.ein AND p.ty=h.ty WHERE hrs>=1000000 ORDER BY dafw_rate DESC LIMIT 10;

-- [18]
-- Hospitals: pooled injury rate for hospital EINs vs all other 300A 2023 EINs in NAICS 622, and matched vs unmatched hospital officer pay
WITH o AS (SELECT LPAD(REGEXP_REPLACE(EIN,'[^0-9]',''),9,'0') ein, MAX(IFF(NAICS_CODE::string LIKE '622%',1,0)) hosp_naics, SUM(TRY_TO_NUMBER(TOTAL_DAFW_CASES::string)) dafw, SUM(TRY_TO_NUMBER(TOTAL_INJURIES::string)) inj, SUM(TRY_TO_NUMBER(TOTAL_HOURS_WORKED::string)) hrs, SUM(TRY_TO_NUMBER(ANNUAL_AVERAGE_EMPLOYEES::string)) emp FROM LIBRARY_MARTS.LABOR.LABOR__FED_OSHA_ITA_300A_SUMMARY_2023 GROUP BY 1),
h AS (SELECT EIN ein, AVG(TOTAL_COMPENSATION) avg_pay, MAX(TOTAL_COMPENSATION) max_pay FROM LIBRARY_MARTS.HEALTH.HEALTH__HOSPITAL_OFFICER_PAY GROUP BY 1)
SELECT 'osha_side' side, IFF(h.ein IS NULL,'unmatched','matched') m, hosp_naics grp, COUNT(*) eins, ROUND(SUM(dafw)*200000/SUM(hrs),2) dafw_rate, ROUND(SUM(inj)*200000/SUM(hrs),2) inj_rate, ROUND(AVG(emp)) avg_emp, NULL avg_pay FROM o LEFT JOIN h ON o.ein=h.ein GROUP BY 1,2,3
UNION ALL SELECT 'hop_side', IFF(o.ein IS NULL,'unmatched','matched'), NULL, COUNT(*), NULL, NULL, NULL, ROUND(AVG(max_pay)) FROM h LEFT JOIN o ON o.ein=h.ein GROUP BY 1,2
ORDER BY 1,2,3;

-- [19]
-- Form 5500 sponsors with OSHA 300A deaths 2023-2025: top 10 by deaths
WITH o AS (
  SELECT LPAD(REGEXP_REPLACE(EIN,'[^0-9]',''),9,'0') ein, YEAR_FILING_FOR::string y, TRY_TO_NUMBER(TOTAL_DEATHS::string) d, COMPANY_NAME cn FROM LIBRARY_MARTS.LABOR.LABOR__FED_OSHA_ITA_300A_SUMMARY_2023
  UNION ALL SELECT LPAD(REGEXP_REPLACE(EIN,'[^0-9]',''),9,'0'), YEAR_FILING_FOR::string, TRY_TO_NUMBER(TOTAL_DEATHS::string), COMPANY_NAME FROM LIBRARY_MARTS.LABOR.LABOR__FED_OSHA_ITA_300A_SUMMARY_2024
  UNION ALL SELECT LPAD(REGEXP_REPLACE(EIN,'[^0-9]',''),9,'0'), YEAR_FILING_FOR::string, TRY_TO_NUMBER(TOTAL_DEATHS::string), COMPANY_NAME FROM LIBRARY_MARTS.LABOR.LABOR__FED_OSHA_ITA_300A_SUMMARY_2025),
f AS (SELECT SPONS_DFE_EIN ein, MODE(SPONSOR_DFE_NAME) fn, COUNT(*) plans, MAX(TRY_TO_NUMBER(TOT_ACTIVE_PARTCP_CNT::string)) partcp FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_DOL_FORM5500 GROUP BY 1)
SELECT f.ein, fn, MODE(cn) osha_name, plans, partcp, SUM(d) deaths_3y, COUNT(DISTINCT y) yrs FROM f JOIN o ON f.ein=o.ein GROUP BY 1,2,4,5 HAVING SUM(d)>0 ORDER BY deaths_3y DESC LIMIT 10;

-- [20]
-- Rosen Hotels, RM Palmer, Estes: 300A TOTAL_DEATHS per year vs case-detail death rows (INCIDENT_OUTCOME=1)
WITH e AS (SELECT column1 ein FROM VALUES ('591536217'),('922513241'),('540492941'))
SELECT '300A' src, YEAR_FILING_FOR::string y, LPAD(REGEXP_REPLACE(EIN,'[^0-9]',''),9,'0') ein, COUNT(*) sites, SUM(TRY_TO_NUMBER(TOTAL_DEATHS::string)) deaths, SUM(TRY_TO_NUMBER(TOTAL_INJURIES::string)) inj, SUM(TRY_TO_NUMBER(TOTAL_OTHER_ILLNESSES::string)) ill FROM (
  SELECT * FROM LIBRARY_MARTS.LABOR.LABOR__FED_OSHA_ITA_300A_SUMMARY_2023 UNION ALL SELECT * FROM LIBRARY_MARTS.LABOR.LABOR__FED_OSHA_ITA_300A_SUMMARY_2024 UNION ALL SELECT * FROM LIBRARY_MARTS.LABOR.LABOR__FED_OSHA_ITA_300A_SUMMARY_2025)
WHERE LPAD(REGEXP_REPLACE(EIN,'[^0-9]',''),9,'0') IN (SELECT ein FROM e) GROUP BY 1,2,3
UNION ALL
SELECT 'CD', y, ein, COUNT(DISTINCT ESTABLISHMENT_ID), COUNT_IF(o='1'), COUNT(*), NULL FROM (
  SELECT YEAR_FILING_FOR::string y, LPAD(REGEXP_REPLACE(EIN,'[^0-9]',''),9,'0') ein, ESTABLISHMENT_ID, INCIDENT_OUTCOME::string o FROM LIBRARY_MARTS.LABOR.LABOR__FED_OSHA_ITA_CASE_DETAIL_2023
  UNION ALL SELECT YEAR_FILING_FOR::string, LPAD(REGEXP_REPLACE(EIN,'[^0-9]',''),9,'0'), ESTABLISHMENT_ID, INCIDENT_OUTCOME::string FROM LIBRARY_MARTS.LABOR.LABOR__FED_OSHA_ITA_CASE_DETAIL_2024
  UNION ALL SELECT YEAR_FILING_FOR::string, LPAD(REGEXP_REPLACE(EIN,'[^0-9]',''),9,'0'), ESTABLISHMENT_ID, INCIDENT_OUTCOME::string FROM LIBRARY_MARTS.LABOR.LABOR__FED_OSHA_ITA_CASE_DETAIL_2025)
WHERE ein IN (SELECT ein FROM e) GROUP BY 1,2,3 ORDER BY 3,2,1;

-- [21]
-- SAM exclusions and SAM excluded providers: rows, UEI fill, distinct UEI, entity vs person, type values, activation range, overlap by SAM_NUMBER
SELECT 'SAM_EXCL' t, COUNT(*) n, COUNT_IF(NULLIF(TRIM(UEI),'') IS NOT NULL) uei_filled, COUNT(DISTINCT NULLIF(TRIM(UEI),'')) uei_distinct, COUNT_IF(LENGTH(TRIM(UEI))=12) uei_12, COUNT_IF(IS_ENTITY_NOT_INDIVIDUAL::string IN ('true','TRUE','1','Y')) entity_rows, COUNT(DISTINCT EXCLUSION_TYPE) types, MIN(ACTIVATION_DATE)::string min_act, MAX(ACTIVATION_DATE)::string max_act FROM LIBRARY_MARTS.PROCUREMENT.PROCUREMENT__FED_SAM_EXCLUSIONS
UNION ALL SELECT 'SAM_PROV', COUNT(*), COUNT_IF(NULLIF(TRIM(UEI),'') IS NOT NULL), COUNT(DISTINCT NULLIF(TRIM(UEI),'')), COUNT_IF(LENGTH(TRIM(UEI))=12), COUNT_IF(IS_ENTITY_NOT_INDIVIDUAL::string IN ('true','TRUE','1','Y')), COUNT(DISTINCT EXCLUSION_TYPE), MIN(ACTIVATION_DATE)::string, MAX(ACTIVATION_DATE)::string FROM LIBRARY_MARTS.HEALTH.HEALTH__SAM_EXCLUDED_PROVIDERS
UNION ALL SELECT 'PROV_in_EXCL_by_SAMNUM', COUNT(*), COUNT_IF(x.SAM_NUMBER IS NOT NULL), COUNT(DISTINCT NULLIF(TRIM(p.UEI),'')), COUNT_IF(NULLIF(TRIM(p.UEI),'') IS NOT NULL AND x.SAM_NUMBER IS NOT NULL), NULL, NULL, NULL, NULL FROM LIBRARY_MARTS.HEALTH.HEALTH__SAM_EXCLUDED_PROVIDERS p LEFT JOIN (SELECT DISTINCT SAM_NUMBER FROM LIBRARY_MARTS.PROCUREMENT.PROCUREMENT__FED_SAM_EXCLUSIONS) x ON p.SAM_NUMBER=x.SAM_NUMBER;

-- [22]
-- SAM exclusions: exclusion type values among rows with a UEI, and a 5-row sample
SELECT EXCLUSION_TYPE, IS_ENTITY_NOT_INDIVIDUAL::string ent, COUNT(*) n, COUNT_IF(NULLIF(TRIM(UEI),'') IS NOT NULL) with_uei, ANY_VALUE(ENTITY_NAME) ex_name, ANY_VALUE(UEI) ex_uei, ANY_VALUE(EXCLUDING_AGENCY) ex_agency FROM LIBRARY_MARTS.PROCUREMENT.PROCUREMENT__FED_SAM_EXCLUSIONS GROUP BY 1,2 ORDER BY 3 DESC LIMIT 20;

-- [23]
-- Rosen Hotels, RM Palmer, Estes: 300A TOTAL_DEATHS per year vs case-detail death rows (INCIDENT_OUTCOME=1)
WITH a AS (
  SELECT '2023' y, EIN, TOTAL_DEATHS::string d, COMPANY_NAME cn, ESTABLISHMENT_NAME en FROM LIBRARY_MARTS.LABOR.LABOR__FED_OSHA_ITA_300A_SUMMARY_2023
  UNION ALL SELECT '2024', EIN, TOTAL_DEATHS::string, COMPANY_NAME, ESTABLISHMENT_NAME FROM LIBRARY_MARTS.LABOR.LABOR__FED_OSHA_ITA_300A_SUMMARY_2024
  UNION ALL SELECT '2025', EIN, TOTAL_DEATHS::string, COMPANY_NAME, ESTABLISHMENT_NAME FROM LIBRARY_MARTS.LABOR.LABOR__FED_OSHA_ITA_300A_SUMMARY_2025),
c AS (
  SELECT '2023' y, EIN, INCIDENT_OUTCOME::string o FROM LIBRARY_MARTS.LABOR.LABOR__FED_OSHA_ITA_CASE_DETAIL_2023
  UNION ALL SELECT '2024', EIN, INCIDENT_OUTCOME::string FROM LIBRARY_MARTS.LABOR.LABOR__FED_OSHA_ITA_CASE_DETAIL_2024
  UNION ALL SELECT '2025', EIN, INCIDENT_OUTCOME::string FROM LIBRARY_MARTS.LABOR.LABOR__FED_OSHA_ITA_CASE_DETAIL_2025)
SELECT '300A' src, y, LPAD(REGEXP_REPLACE(EIN,'[^0-9]',''),9,'0') ein, COUNT(*) sites, SUM(TRY_TO_NUMBER(d)) deaths, MAX_BY(en, TRY_TO_NUMBER(d)) worst_site FROM a WHERE LPAD(REGEXP_REPLACE(EIN,'[^0-9]',''),9,'0') IN ('591536217','922513241','540492941') GROUP BY 1,2,3
UNION ALL SELECT 'CD', y, LPAD(REGEXP_REPLACE(EIN,'[^0-9]',''),9,'0'), COUNT(*), COUNT_IF(o='1'), NULL FROM c WHERE LPAD(REGEXP_REPLACE(EIN,'[^0-9]',''),9,'0') IN ('591536217','922513241','540492941') GROUP BY 1,2,3
ORDER BY 3,2,1;

-- [24]
-- USAspending assistance: rows per fiscal year, to test the 1M-per-year cap trap against today's 128M rows
SELECT ACTION_DATE_FISCAL_YEAR fy, COUNT(*) n, MIN(ACTION_DATE)::string mn, MAX(ACTION_DATE)::string mx FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_USASPENDING_ASSISTANCE_FULL GROUP BY 1 ORDER BY 1;

-- [25]
-- SAM exclusions: current flag and termination fill among UEI rows
SELECT IS_CURRENTLY_EXCLUDED::string cur, COUNT(*) n, COUNT(TERMINATION_DATE) term_filled, ANY_VALUE(TERMINATION_DATE_RAW) raw_ex, COUNT_IF(ACTIVATION_DATE>='2090-01-01') act_2090 FROM LIBRARY_MARTS.PROCUREMENT.PROCUREMENT__FED_SAM_EXCLUSIONS WHERE LENGTH(TRIM(UEI))=12 GROUP BY 1;

-- [26]
-- OSHA 300A TOTAL_DEATHS vs case-detail death rows, per establishment and year: how often the summary claims deaths the case log does not show
WITH a AS (
  SELECT '2023' y, ESTABLISHMENT_ID::string id, TRY_TO_NUMBER(TOTAL_DEATHS::string) d FROM LIBRARY_MARTS.LABOR.LABOR__FED_OSHA_ITA_300A_SUMMARY_2023
  UNION ALL SELECT '2024', ESTABLISHMENT_ID::string, TRY_TO_NUMBER(TOTAL_DEATHS::string) FROM LIBRARY_MARTS.LABOR.LABOR__FED_OSHA_ITA_300A_SUMMARY_2024
  UNION ALL SELECT '2025', ESTABLISHMENT_ID::string, TRY_TO_NUMBER(TOTAL_DEATHS::string) FROM LIBRARY_MARTS.LABOR.LABOR__FED_OSHA_ITA_300A_SUMMARY_2025),
c AS (
  SELECT '2023' y, ESTABLISHMENT_ID::string id, COUNT(*) cases, COUNT_IF(INCIDENT_OUTCOME::string='1') cd FROM LIBRARY_MARTS.LABOR.LABOR__FED_OSHA_ITA_CASE_DETAIL_2023 GROUP BY 1,2
  UNION ALL SELECT '2024', ESTABLISHMENT_ID::string, COUNT(*), COUNT_IF(INCIDENT_OUTCOME::string='1') FROM LIBRARY_MARTS.LABOR.LABOR__FED_OSHA_ITA_CASE_DETAIL_2024 GROUP BY 1,2
  UNION ALL SELECT '2025', ESTABLISHMENT_ID::string, COUNT(*), COUNT_IF(INCIDENT_OUTCOME::string='1') FROM LIBRARY_MARTS.LABOR.LABOR__FED_OSHA_ITA_CASE_DETAIL_2025 GROUP BY 1,2)
SELECT a.y, SUM(a.d) deaths_300a, COUNT_IF(a.d>0) sites_with_deaths, COUNT_IF(a.d>0 AND c.id IS NOT NULL) of_which_have_cases, COUNT_IF(a.d>0 AND c.id IS NOT NULL AND c.cd=0) cases_show_no_death, SUM(IFF(c.id IS NOT NULL, a.d, 0)) deaths_300a_on_sites_with_cases, SUM(c.cd) cd_deaths_joined
FROM a LEFT JOIN c ON a.y=c.y AND a.id=c.id GROUP BY 1 ORDER BY 1;

-- [27]
-- UEI: FED_USASPENDING_CONTRACTS (6.3M) vs SAM exclusion UEIs: matched UEIs, name agreement, dollars inside an exclusion window
WITH x AS (SELECT TRIM(UEI) uei, ACTIVATION_DATE act, COALESCE(TERMINATION_DATE,'2999-12-31'::date) term, UPPER(COALESCE(ENTITY_NAME, FIRST_NAME||' '||LAST_NAME)) nm, EXCLUDING_AGENCY ag FROM LIBRARY_MARTS.PROCUREMENT.PROCUREMENT__FED_SAM_EXCLUSIONS WHERE LENGTH(TRIM(UEI))=12),
xu AS (SELECT uei, MIN(act) act, MODE(nm) nm, LISTAGG(DISTINCT ag, ',') ags FROM x GROUP BY 1),
t AS (SELECT CONTRACT_AWARD_UNIQUE_KEY k, ACTION_DATE::date d, FEDERAL_ACTION_OBLIGATION amt, TRIM(RECIPIENT_UEI) u, UPPER(RECIPIENT_NAME) rn, ROW_NUMBER() OVER (ORDER BY 1) rid FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_USASPENDING_CONTRACTS WHERE TRIM(RECIPIENT_UEI) IN (SELECT uei FROM xu)),
tf AS (SELECT t.*, (SELECT COUNT(*) FROM x WHERE x.uei=t.u AND t.d BETWEEN x.act AND x.term) inwin FROM t),
per AS (SELECT u, ANY_VALUE(rn) rn, COUNT(*) n, SUM(amt) amt, SUM(IFF(inwin>0,amt,0)) amt_in, COUNT_IF(inwin>0) n_in, MAX(d) last_d FROM tf GROUP BY 1)
SELECT 'SUMMARY' u, NULL nm, NULL rn, NULL ags, COUNT(*) n_uei, SUM(n) rows_, ROUND(SUM(amt)) dollars, COUNT_IF(n_in>0) uei_paid_in_window, ROUND(SUM(amt_in)) dollars_in_window, COUNT_IF(JAROWINKLER_SIMILARITY(REGEXP_REPLACE(xu.nm,'[^A-Z0-9 ]',''),REGEXP_REPLACE(per.rn,'[^A-Z0-9 ]',''))>=85) name_agree, (SELECT COUNT(DISTINCT TRIM(RECIPIENT_PARENT_UEI)) FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_USASPENDING_CONTRACTS WHERE TRIM(RECIPIENT_PARENT_UEI) IN (SELECT uei FROM xu)) parent_uei_hits, (SELECT COUNT(DISTINCT TRIM(RECIPIENT_UEI)) FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_USASPENDING_CONTRACTS) a_distinct_uei, MAX(last_d)::string last_d
FROM per JOIN xu ON per.u=xu.uei
UNION ALL
SELECT * FROM (SELECT per.u, xu.nm, per.rn, xu.ags, NULL, n, ROUND(amt), n_in, ROUND(amt_in), JAROWINKLER_SIMILARITY(REGEXP_REPLACE(xu.nm,'[^A-Z0-9 ]',''),REGEXP_REPLACE(per.rn,'[^A-Z0-9 ]','')), xu.act::string, NULL, last_d::string FROM per JOIN xu ON per.u=xu.uei ORDER BY amt_in DESC LIMIT 15);

-- [28]
-- UEI: LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_USASPENDING_CONTRACTS vs EXCL UEIs: matched UEIs, name agreement (JW>=85), dollars inside an exclusion window; summary row then top 15 by in-window dollars
WITH x AS (SELECT TRIM(UEI) uei, ACTIVATION_DATE::date act, COALESCE(TERMINATION_DATE,'2999-12-31'::date) term, UPPER(COALESCE(ENTITY_NAME, FIRST_NAME||' '||LAST_NAME)) nm, EXCLUDING_AGENCY ag FROM LIBRARY_MARTS.PROCUREMENT.PROCUREMENT__FED_SAM_EXCLUSIONS WHERE LENGTH(TRIM(UEI))=12),
xu AS (SELECT uei, MIN(act) act, MODE(nm) nm, LISTAGG(DISTINCT ag, ',') ags FROM x GROUP BY 1),
t AS (SELECT CONTRACT_AWARD_UNIQUE_KEY k, TRY_TO_DATE(ACTION_DATE::string) d, TRY_TO_NUMBER(FEDERAL_ACTION_OBLIGATION::string,38,2) amt, TRIM(RECIPIENT_UEI) u, UPPER(RECIPIENT_NAME) rn, SEQ8() rid FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_USASPENDING_CONTRACTS WHERE TRIM(RECIPIENT_UEI) IN (SELECT uei FROM xu)),
tf AS (SELECT t.rid, ANY_VALUE(t.u) u, ANY_VALUE(t.rn) rn, ANY_VALUE(t.d) d, ANY_VALUE(t.amt) amt, COUNT(x.uei) inwin FROM t LEFT JOIN x ON x.uei=t.u AND t.d BETWEEN x.act AND x.term GROUP BY 1),
per AS (SELECT u, ANY_VALUE(rn) rn, COUNT(*) n, SUM(amt) amt, SUM(IFF(inwin>0,amt,0)) amt_in, COUNT_IF(inwin>0) n_in, MIN(d) first_d, MAX(d) last_d FROM tf GROUP BY 1),
j AS (SELECT per.*, xu.nm, xu.ags, xu.act, JAROWINKLER_SIMILARITY(REGEXP_REPLACE(xu.nm,'[^A-Z0-9 ]',''),REGEXP_REPLACE(per.rn,'[^A-Z0-9 ]','')) jw FROM per JOIN xu ON per.u=xu.uei)
SELECT 'SUMMARY' u, NULL nm, NULL rn, NULL ags, COUNT(*)::string n_uei, SUM(n)::string rows_, ROUND(SUM(amt))::string dollars, COUNT_IF(n_in>0)::string uei_paid_in_window, ROUND(SUM(amt_in))::string dollars_in_window, COUNT_IF(jw>=85)::string name_agree, (SELECT COUNT(DISTINCT TRIM(RECIPIENT_PARENT_UEI)) FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_USASPENDING_CONTRACTS WHERE TRIM(RECIPIENT_PARENT_UEI) IN (SELECT uei FROM xu))::string parent_uei_hits, MIN(first_d)::string first_d, MAX(last_d)::string last_d
FROM j
UNION ALL
SELECT * FROM (SELECT u, nm, rn, ags, act::string, n::string, ROUND(amt)::string, n_in::string, ROUND(amt_in)::string, jw::string, NULL, first_d::string, last_d::string FROM j ORDER BY amt_in DESC NULLS LAST LIMIT 15);

-- [29]
-- UEI: LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_USASPENDING_CONTRACTS_FULL_R2 vs EXCL UEIs: matched UEIs, name agreement (JW>=85), dollars inside an exclusion window; summary row then top 15 by in-window dollars
WITH pv AS (SELECT DISTINCT SAM_NUMBER FROM LIBRARY_MARTS.HEALTH.HEALTH__SAM_EXCLUDED_PROVIDERS),
x AS (SELECT TRIM(UEI) uei, IFF(SAM_NUMBER IN (SELECT SAM_NUMBER FROM pv),1,0) prov, ACTIVATION_DATE::date act, COALESCE(TERMINATION_DATE,'2999-12-31'::date) term, UPPER(COALESCE(ENTITY_NAME, FIRST_NAME||' '||LAST_NAME)) nm, EXCLUDING_AGENCY ag FROM LIBRARY_MARTS.PROCUREMENT.PROCUREMENT__FED_SAM_EXCLUSIONS WHERE LENGTH(TRIM(UEI))=12),
xu AS (SELECT uei, MIN(act) act, MODE(nm) nm, LISTAGG(DISTINCT ag, ',') ags, MAX(prov) prov FROM x GROUP BY 1),
t AS (SELECT CONTRACT_AWARD_UNIQUE_KEY k, TRY_TO_DATE(ACTION_DATE::string) d, TRY_TO_NUMBER(FEDERAL_ACTION_OBLIGATION::string,38,2) amt, TRIM(RECIPIENT_UEI) u, UPPER(RECIPIENT_NAME) rn, SEQ8() rid FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_USASPENDING_CONTRACTS_FULL_R2 WHERE TRIM(RECIPIENT_UEI) IN (SELECT uei FROM xu)),
tf AS (SELECT t.rid, ANY_VALUE(t.u) u, ANY_VALUE(t.rn) rn, ANY_VALUE(t.d) d, ANY_VALUE(t.amt) amt, COUNT(x.uei) inwin FROM t LEFT JOIN x ON x.uei=t.u AND t.d BETWEEN x.act AND x.term GROUP BY 1),
per AS (SELECT u, ANY_VALUE(rn) rn, COUNT(*) n, SUM(amt) amt, SUM(IFF(inwin>0,amt,0)) amt_in, COUNT_IF(inwin>0) n_in, MIN(d) first_d, MAX(d) last_d FROM tf GROUP BY 1),
j AS (SELECT per.*, xu.nm, xu.ags, xu.act, xu.prov, JAROWINKLER_SIMILARITY(REGEXP_REPLACE(xu.nm,'[^A-Z0-9 ]',''),REGEXP_REPLACE(per.rn,'[^A-Z0-9 ]','')) jw FROM per JOIN xu ON per.u=xu.uei)
SELECT 'SUMMARY' u, NULL nm, NULL rn, NULL ags, COUNT(*)::string n_uei, SUM(n)::string rows_, ROUND(SUM(amt))::string dollars, COUNT_IF(n_in>0)::string uei_paid_in_window, ROUND(SUM(amt_in))::string dollars_in_window, COUNT_IF(jw>=85)::string name_agree, COUNT_IF(prov=1)::string prov_uei, COUNT_IF(prov=1 AND n_in>0)::string prov_uei_in_win, ROUND(SUM(IFF(prov=1,amt_in,0)))::string prov_dollars_in_win, (SELECT COUNT(DISTINCT TRIM(RECIPIENT_PARENT_UEI)) FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_USASPENDING_CONTRACTS_FULL_R2 WHERE TRIM(RECIPIENT_PARENT_UEI) IN (SELECT uei FROM xu))::string parent_uei_hits, MIN(first_d)::string first_d, MAX(last_d)::string last_d
FROM j
UNION ALL
SELECT * FROM (SELECT u, nm, rn, ags, act::string, n::string, ROUND(amt)::string, n_in::string, ROUND(amt_in)::string, jw::string, prov::string, NULL, NULL, NULL, first_d::string, last_d::string FROM j ORDER BY amt_in DESC NULLS LAST LIMIT 15);

-- [30]
-- UEI: LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_USASPENDING_CONTRACTS_FULL vs EXCL UEIs: matched UEIs, name agreement (JW>=85), dollars inside an exclusion window; summary row then top 15 by in-window dollars
WITH pv AS (SELECT DISTINCT SAM_NUMBER FROM LIBRARY_MARTS.HEALTH.HEALTH__SAM_EXCLUDED_PROVIDERS),
x AS (SELECT TRIM(UEI) uei, IFF(SAM_NUMBER IN (SELECT SAM_NUMBER FROM pv),1,0) prov, ACTIVATION_DATE::date act, COALESCE(TERMINATION_DATE,'2999-12-31'::date) term, UPPER(COALESCE(ENTITY_NAME, FIRST_NAME||' '||LAST_NAME)) nm, EXCLUDING_AGENCY ag FROM LIBRARY_MARTS.PROCUREMENT.PROCUREMENT__FED_SAM_EXCLUSIONS WHERE LENGTH(TRIM(UEI))=12),
xu AS (SELECT uei, MIN(act) act, MODE(nm) nm, LISTAGG(DISTINCT ag, ',') ags, MAX(prov) prov FROM x GROUP BY 1),
t AS (SELECT CONTRACT_TRANSACTION_UNIQUE_KEY k, TRY_TO_DATE(ACTION_DATE::string) d, TRY_TO_NUMBER(FEDERAL_ACTION_OBLIGATION::string,38,2) amt, TRIM(RECIPIENT_UEI) u, UPPER(RECIPIENT_NAME) rn, SEQ8() rid FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_USASPENDING_CONTRACTS_FULL WHERE TRIM(RECIPIENT_UEI) IN (SELECT uei FROM xu)),
tf AS (SELECT t.rid, ANY_VALUE(t.u) u, ANY_VALUE(t.rn) rn, ANY_VALUE(t.d) d, ANY_VALUE(t.amt) amt, COUNT(x.uei) inwin FROM t LEFT JOIN x ON x.uei=t.u AND t.d BETWEEN x.act AND x.term GROUP BY 1),
per AS (SELECT u, ANY_VALUE(rn) rn, COUNT(*) n, SUM(amt) amt, SUM(IFF(inwin>0,amt,0)) amt_in, SUM(IFF(inwin>0 AND amt>0,amt,0)) pos_in, COUNT_IF(inwin>0) n_in, MIN(d) first_d, MAX(d) last_d FROM tf GROUP BY 1),
j AS (SELECT per.*, xu.nm, xu.ags, xu.act, xu.prov, JAROWINKLER_SIMILARITY(REGEXP_REPLACE(xu.nm,'[^A-Z0-9 ]',''),REGEXP_REPLACE(per.rn,'[^A-Z0-9 ]','')) jw FROM per JOIN xu ON per.u=xu.uei)
SELECT 'SUMMARY' u, NULL nm, NULL rn, NULL ags, COUNT(*)::string n_uei, SUM(n)::string rows_, ROUND(SUM(amt))::string dollars, COUNT_IF(n_in>0)::string uei_paid_in_window, ROUND(SUM(amt_in))::string net_in_window, ROUND(SUM(pos_in))::string gross_pos_in_window, COUNT_IF(jw>=85)::string name_agree, COUNT_IF(prov=1)::string prov_uei, COUNT_IF(prov=1 AND n_in>0)::string prov_uei_in_win, ROUND(SUM(IFF(prov=1,amt_in,0)))::string prov_dollars_in_win, (SELECT COUNT(DISTINCT TRIM(RECIPIENT_PARENT_UEI)) FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_USASPENDING_CONTRACTS_FULL WHERE TRIM(RECIPIENT_PARENT_UEI) IN (SELECT uei FROM xu))::string parent_uei_hits, MIN(first_d)::string first_d, MAX(last_d)::string last_d
FROM j
UNION ALL
SELECT * FROM (SELECT u, nm, rn, ags, act::string, n::string, ROUND(amt)::string, n_in::string, ROUND(amt_in)::string, ROUND(pos_in)::string, jw::string, prov::string, NULL, NULL, NULL, first_d::string, last_d::string FROM j ORDER BY pos_in DESC NULLS LAST LIMIT 15);

-- [31]
-- UEI: LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_USASPENDING_ASSISTANCE_FULL vs EXCL UEIs: matched UEIs, name agreement (JW>=85), dollars inside an exclusion window; summary row then top 15 by in-window dollars
WITH pv AS (SELECT DISTINCT SAM_NUMBER FROM LIBRARY_MARTS.HEALTH.HEALTH__SAM_EXCLUDED_PROVIDERS),
x AS (SELECT TRIM(UEI) uei, IFF(SAM_NUMBER IN (SELECT SAM_NUMBER FROM pv),1,0) prov, ACTIVATION_DATE::date act, COALESCE(TERMINATION_DATE,'2999-12-31'::date) term, UPPER(COALESCE(ENTITY_NAME, FIRST_NAME||' '||LAST_NAME)) nm, EXCLUDING_AGENCY ag FROM LIBRARY_MARTS.PROCUREMENT.PROCUREMENT__FED_SAM_EXCLUSIONS WHERE LENGTH(TRIM(UEI))=12),
xu AS (SELECT uei, MIN(act) act, MODE(nm) nm, LISTAGG(DISTINCT ag, ',') ags, MAX(prov) prov FROM x GROUP BY 1),
t AS (SELECT ASSISTANCE_TRANSACTION_UNIQUE_KEY k, TRY_TO_DATE(ACTION_DATE::string) d, TRY_TO_NUMBER(FEDERAL_ACTION_OBLIGATION::string,38,2) amt, TRIM(RECIPIENT_UEI) u, UPPER(RECIPIENT_NAME) rn, SEQ8() rid FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_USASPENDING_ASSISTANCE_FULL WHERE TRIM(RECIPIENT_UEI) IN (SELECT uei FROM xu)),
tf AS (SELECT t.rid, ANY_VALUE(t.u) u, ANY_VALUE(t.rn) rn, ANY_VALUE(t.d) d, ANY_VALUE(t.amt) amt, COUNT(x.uei) inwin FROM t LEFT JOIN x ON x.uei=t.u AND t.d BETWEEN x.act AND x.term GROUP BY 1),
per AS (SELECT u, ANY_VALUE(rn) rn, COUNT(*) n, SUM(amt) amt, SUM(IFF(inwin>0,amt,0)) amt_in, SUM(IFF(inwin>0 AND amt>0,amt,0)) pos_in, COUNT_IF(inwin>0) n_in, MIN(d) first_d, MAX(d) last_d FROM tf GROUP BY 1),
j AS (SELECT per.*, xu.nm, xu.ags, xu.act, xu.prov, JAROWINKLER_SIMILARITY(REGEXP_REPLACE(xu.nm,'[^A-Z0-9 ]',''),REGEXP_REPLACE(per.rn,'[^A-Z0-9 ]','')) jw FROM per JOIN xu ON per.u=xu.uei)
SELECT 'SUMMARY' u, NULL nm, NULL rn, NULL ags, COUNT(*)::string n_uei, SUM(n)::string rows_, ROUND(SUM(amt))::string dollars, COUNT_IF(n_in>0)::string uei_paid_in_window, ROUND(SUM(amt_in))::string net_in_window, ROUND(SUM(pos_in))::string gross_pos_in_window, COUNT_IF(jw>=85)::string name_agree, COUNT_IF(prov=1)::string prov_uei, COUNT_IF(prov=1 AND n_in>0)::string prov_uei_in_win, ROUND(SUM(IFF(prov=1,amt_in,0)))::string prov_dollars_in_win, (SELECT COUNT(DISTINCT TRIM(RECIPIENT_PARENT_UEI)) FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_USASPENDING_ASSISTANCE_FULL WHERE TRIM(RECIPIENT_PARENT_UEI) IN (SELECT uei FROM xu))::string parent_uei_hits, MIN(first_d)::string first_d, MAX(last_d)::string last_d
FROM j
UNION ALL
SELECT * FROM (SELECT u, nm, rn, ags, act::string, n::string, ROUND(amt)::string, n_in::string, ROUND(amt_in)::string, ROUND(pos_in)::string, jw::string, prov::string, NULL, NULL, NULL, first_d::string, last_d::string FROM j ORDER BY pos_in DESC NULLS LAST LIMIT 15);

-- [32]
-- NIH RePORTER and SBIR: rows, UEI fill/width/distinct, date and amount parse rates, sample values
SELECT 'NIH' t, COUNT(*) n, COUNT_IF(NULLIF(TRIM(ORG_UEI),'') IS NOT NULL) uei_filled, COUNT_IF(LENGTH(TRIM(ORG_UEI))=12) uei12, COUNT(DISTINCT NULLIF(TRIM(ORG_UEI),'')) uei_distinct, COUNT(TRY_TO_DATE(BUDGET_START_DATE::string)) date_ok, ANY_VALUE(BUDGET_START_DATE::string) date_ex, COUNT(TRY_TO_NUMBER(AWARD_AMOUNT::string,38,2)) amt_ok, ANY_VALUE(AWARD_AMOUNT::string) amt_ex, ANY_VALUE(ORG_UEI) uei_ex, MIN(FISCAL_YEAR)::string mn, MAX(FISCAL_YEAR)::string mx FROM LIBRARY_MARTS.SCIENCE_RESEARCH.SCIENCE_RESEARCH__FED_NIH_REPORTER
UNION ALL SELECT 'SBIR', COUNT(*), COUNT_IF(NULLIF(TRIM(UEI),'') IS NOT NULL), COUNT_IF(LENGTH(TRIM(UEI))=12), COUNT(DISTINCT NULLIF(TRIM(UEI),'')), COUNT(TRY_TO_DATE(PROPOSAL_AWARD_DATE::string)), ANY_VALUE(PROPOSAL_AWARD_DATE::string), COUNT(TRY_TO_NUMBER(AWARD_AMOUNT::string,38,2)), ANY_VALUE(AWARD_AMOUNT::string), ANY_VALUE(UEI), MIN(AWARD_YEAR)::string, MAX(AWARD_YEAR)::string FROM LIBRARY_MARTS.SCIENCE_RESEARCH.SCIENCE_RESEARCH__FED_SBIR_STTR_AWARDS;

-- [33]
-- UEI: LIBRARY_MARTS.SCIENCE_RESEARCH.SCIENCE_RESEARCH__FED_NIH_REPORTER vs EXCL UEIs: matched UEIs, name agreement (JW>=85), dollars inside an exclusion window; summary row then top 15 by in-window dollars
WITH pv AS (SELECT DISTINCT SAM_NUMBER FROM LIBRARY_MARTS.HEALTH.HEALTH__SAM_EXCLUDED_PROVIDERS),
x AS (SELECT TRIM(UEI) uei, IFF(SAM_NUMBER IN (SELECT SAM_NUMBER FROM pv),1,0) prov, ACTIVATION_DATE::date act, COALESCE(TERMINATION_DATE,'2999-12-31'::date) term, UPPER(COALESCE(ENTITY_NAME, FIRST_NAME||' '||LAST_NAME)) nm, EXCLUDING_AGENCY ag FROM LIBRARY_MARTS.PROCUREMENT.PROCUREMENT__FED_SAM_EXCLUSIONS WHERE LENGTH(TRIM(UEI))=12),
xu AS (SELECT uei, MIN(act) act, MODE(nm) nm, LISTAGG(DISTINCT ag, ',') ags, MAX(prov) prov FROM x GROUP BY 1),
t AS (SELECT APPL_ID k, TRY_TO_DATE(BUDGET_START_DATE::string) d, TRY_TO_NUMBER(AWARD_AMOUNT::string,38,2) amt, TRIM(ORG_UEI) u, UPPER(ORG_NAME) rn, SEQ8() rid FROM LIBRARY_MARTS.SCIENCE_RESEARCH.SCIENCE_RESEARCH__FED_NIH_REPORTER WHERE TRIM(ORG_UEI) IN (SELECT uei FROM xu)),
tf AS (SELECT t.rid, ANY_VALUE(t.u) u, ANY_VALUE(t.rn) rn, ANY_VALUE(t.d) d, ANY_VALUE(t.amt) amt, COUNT(x.uei) inwin FROM t LEFT JOIN x ON x.uei=t.u AND t.d BETWEEN x.act AND x.term GROUP BY 1),
per AS (SELECT u, ANY_VALUE(rn) rn, COUNT(*) n, SUM(amt) amt, SUM(IFF(inwin>0,amt,0)) amt_in, SUM(IFF(inwin>0 AND amt>0,amt,0)) pos_in, COUNT_IF(inwin>0) n_in, MIN(d) first_d, MAX(d) last_d FROM tf GROUP BY 1),
j AS (SELECT per.*, xu.nm, xu.ags, xu.act, xu.prov, JAROWINKLER_SIMILARITY(REGEXP_REPLACE(xu.nm,'[^A-Z0-9 ]',''),REGEXP_REPLACE(per.rn,'[^A-Z0-9 ]','')) jw FROM per JOIN xu ON per.u=xu.uei)
SELECT 'SUMMARY' u, NULL nm, NULL rn, NULL ags, COUNT(*)::string n_uei, SUM(n)::string rows_, ROUND(SUM(amt))::string dollars, COUNT_IF(n_in>0)::string uei_paid_in_window, ROUND(SUM(amt_in))::string net_in_window, ROUND(SUM(pos_in))::string gross_pos_in_window, COUNT_IF(jw>=85)::string name_agree, COUNT_IF(prov=1)::string prov_uei, COUNT_IF(prov=1 AND n_in>0)::string prov_uei_in_win, ROUND(SUM(IFF(prov=1,amt_in,0)))::string prov_dollars_in_win, NULL::string parent_uei_hits, MIN(first_d)::string first_d, MAX(last_d)::string last_d
FROM j
UNION ALL
SELECT * FROM (SELECT u, nm, rn, ags, act::string, n::string, ROUND(amt)::string, n_in::string, ROUND(amt_in)::string, ROUND(pos_in)::string, jw::string, prov::string, NULL, NULL, NULL, first_d::string, last_d::string FROM j ORDER BY pos_in DESC NULLS LAST LIMIT 15);

-- [34]
-- UEI: LIBRARY_MARTS.SCIENCE_RESEARCH.SCIENCE_RESEARCH__FED_SBIR_STTR_AWARDS vs EXCL UEIs: matched UEIs, name agreement (JW>=85), dollars inside an exclusion window; summary row then top 15 by in-window dollars
WITH pv AS (SELECT DISTINCT SAM_NUMBER FROM LIBRARY_MARTS.HEALTH.HEALTH__SAM_EXCLUDED_PROVIDERS),
x AS (SELECT TRIM(UEI) uei, IFF(SAM_NUMBER IN (SELECT SAM_NUMBER FROM pv),1,0) prov, ACTIVATION_DATE::date act, COALESCE(TERMINATION_DATE,'2999-12-31'::date) term, UPPER(COALESCE(ENTITY_NAME, FIRST_NAME||' '||LAST_NAME)) nm, EXCLUDING_AGENCY ag FROM LIBRARY_MARTS.PROCUREMENT.PROCUREMENT__FED_SAM_EXCLUSIONS WHERE LENGTH(TRIM(UEI))=12),
xu AS (SELECT uei, MIN(act) act, MODE(nm) nm, LISTAGG(DISTINCT ag, ',') ags, MAX(prov) prov FROM x GROUP BY 1),
t AS (SELECT AWARD_RECORD_ID k, TRY_TO_DATE(COALESCE(TRY_TO_DATE(PROPOSAL_AWARD_DATE::string), TRY_TO_DATE(AWARD_YEAR::string||'-01-01'))::string) d, TRY_TO_NUMBER(AWARD_AMOUNT::string,38,2) amt, TRIM(UEI) u, UPPER(COMPANY) rn, SEQ8() rid FROM LIBRARY_MARTS.SCIENCE_RESEARCH.SCIENCE_RESEARCH__FED_SBIR_STTR_AWARDS WHERE TRIM(UEI) IN (SELECT uei FROM xu)),
tf AS (SELECT t.rid, ANY_VALUE(t.u) u, ANY_VALUE(t.rn) rn, ANY_VALUE(t.d) d, ANY_VALUE(t.amt) amt, COUNT(x.uei) inwin FROM t LEFT JOIN x ON x.uei=t.u AND t.d BETWEEN x.act AND x.term GROUP BY 1),
per AS (SELECT u, ANY_VALUE(rn) rn, COUNT(*) n, SUM(amt) amt, SUM(IFF(inwin>0,amt,0)) amt_in, SUM(IFF(inwin>0 AND amt>0,amt,0)) pos_in, COUNT_IF(inwin>0) n_in, MIN(d) first_d, MAX(d) last_d FROM tf GROUP BY 1),
j AS (SELECT per.*, xu.nm, xu.ags, xu.act, xu.prov, JAROWINKLER_SIMILARITY(REGEXP_REPLACE(xu.nm,'[^A-Z0-9 ]',''),REGEXP_REPLACE(per.rn,'[^A-Z0-9 ]','')) jw FROM per JOIN xu ON per.u=xu.uei)
SELECT 'SUMMARY' u, NULL nm, NULL rn, NULL ags, COUNT(*)::string n_uei, SUM(n)::string rows_, ROUND(SUM(amt))::string dollars, COUNT_IF(n_in>0)::string uei_paid_in_window, ROUND(SUM(amt_in))::string net_in_window, ROUND(SUM(pos_in))::string gross_pos_in_window, COUNT_IF(jw>=85)::string name_agree, COUNT_IF(prov=1)::string prov_uei, COUNT_IF(prov=1 AND n_in>0)::string prov_uei_in_win, ROUND(SUM(IFF(prov=1,amt_in,0)))::string prov_dollars_in_win, NULL::string parent_uei_hits, MIN(first_d)::string first_d, MAX(last_d)::string last_d
FROM j
UNION ALL
SELECT * FROM (SELECT u, nm, rn, ags, act::string, n::string, ROUND(amt)::string, n_in::string, ROUND(amt_in)::string, ROUND(pos_in)::string, jw::string, prov::string, NULL, NULL, NULL, first_d::string, last_d::string FROM j ORDER BY pos_in DESC NULLS LAST LIMIT 15);

-- [35]
-- USAF same-day exclusions 2026-07-17: every SAM record that day by USAF (companies and people), to see if the SBIR firms are one cluster
SELECT ACTIVATION_DATE::string act, EXCLUDING_AGENCY, EXCLUSION_TYPE, EXCLUSION_PROGRAM, IS_ENTITY_NOT_INDIVIDUAL::string ent, COALESCE(ENTITY_NAME, FIRST_NAME||' '||LAST_NAME) nm, UEI, CITY, STATE, TERMINATION_DATE_RAW FROM LIBRARY_MARTS.PROCUREMENT.PROCUREMENT__FED_SAM_EXCLUSIONS WHERE EXCLUDING_AGENCY='USAF' AND ACTIVATION_DATE::date BETWEEN '2026-05-01' AND '2026-08-11' ORDER BY 1, 6;

-- [36]
-- SBIR awards to the USAF-excluded firms: address, PI, contact, agency, phase, amount
SELECT UEI, COMPANY, ADDRESS1, CITY, STATE, PI_NAME, CONTACT_NAME, CONTACT_EMAIL, AGENCY, BRANCH, PHASE, AWARD_YEAR, AWARD_AMOUNT FROM LIBRARY_MARTS.SCIENCE_RESEARCH.SCIENCE_RESEARCH__FED_SBIR_STTR_AWARDS WHERE TRIM(UEI) IN ('VT3VHC7U8ZT5','RB4XFCMC9KZ7','EUNHL9KYVJS7','WWGQNYQZ2C73','CDXXNKM674G5','XCA4MTEGBML5') ORDER BY CITY, UEI, AWARD_YEAR;

-- [37]
-- SBIR: every award at 549 Cedar St, Newington CT, any UEI: firms, awards, dollars, agencies, years
SELECT COALESCE(TRIM(UEI),'(none)') uei, MODE(UPPER(COMPANY)) company, COUNT(*) awards, ROUND(SUM(TRY_TO_NUMBER(AWARD_AMOUNT::string,38,2))) dollars, LISTAGG(DISTINCT AGENCY, '; ') agencies, MIN(AWARD_YEAR)::string first_yr, MAX(AWARD_YEAR)::string last_yr
FROM LIBRARY_MARTS.SCIENCE_RESEARCH.SCIENCE_RESEARCH__FED_SBIR_STTR_AWARDS
WHERE UPPER(CITY) LIKE 'NEWINGTON%' AND UPPER(ADDRESS1) LIKE '549 CEDAR%' GROUP BY 1 ORDER BY 4 DESC;

-- [38]
-- Contracts R2: obligations to the 11 Newington UEIs excluded 2026-07-17, before and after the exclusion date
SELECT TRIM(RECIPIENT_UEI) uei, MODE(RECIPIENT_NAME) nm, COUNT(*) actions, ROUND(SUM(FEDERAL_ACTION_OBLIGATION)) dollars, ROUND(SUM(IFF(ACTION_DATE::date>='2026-07-17',FEDERAL_ACTION_OBLIGATION,0))) after_excl, COUNT_IF(ACTION_DATE::date>='2026-07-17') actions_after, MIN(ACTION_DATE)::string first_d, MAX(ACTION_DATE)::string last_d, LISTAGG(DISTINCT AWARDING_AGENCY_NAME, '; ') agencies
FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_USASPENDING_CONTRACTS_FULL_R2
WHERE TRIM(RECIPIENT_UEI) IN ('CDXXNKM674G5','CRJND3N4PUF9','D1SXL4D3SP49','D1Y4XGUJ7RM7','CZZXT6YD6375','CZV2WV13KNW5','VT3VHC7U8ZT5','NUFBQWHHQ3F9','NJY1HNAMS888','EUNHL9KYVJS7','RB4XFCMC9KZ7','WWGQNYQZ2C73') OR (UPPER(RECIPIENT_CITY_NAME)='NEWINGTON' AND RECIPIENT_STATE_CODE='CT' AND UPPER(RECIPIENT_NAME) RLIKE '.*(BRYKA|BEACON IND|NEOSKYE|SKYSTOCKS|SYRNATEC|MYONIKS|FABULOUS).*')
GROUP BY 1 ORDER BY 4 DESC;

-- [39]
-- UEI: LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_USASPENDING_CONTRACTS_FULL_R2 vs EXCL UEIs: matched UEIs, name agreement (JW>=85), dollars inside an exclusion window; summary row then top 15 by in-window dollars
WITH pv AS (SELECT DISTINCT SAM_NUMBER FROM LIBRARY_MARTS.HEALTH.HEALTH__SAM_EXCLUDED_PROVIDERS),
x AS (SELECT TRIM(UEI) uei, IFF(SAM_NUMBER IN (SELECT SAM_NUMBER FROM pv),1,0) prov, ACTIVATION_DATE::date act, COALESCE(TERMINATION_DATE,'2999-12-31'::date) term, UPPER(COALESCE(ENTITY_NAME, FIRST_NAME||' '||LAST_NAME)) nm, EXCLUDING_AGENCY ag FROM LIBRARY_MARTS.PROCUREMENT.PROCUREMENT__FED_SAM_EXCLUSIONS WHERE LENGTH(TRIM(UEI))=12),
xu AS (SELECT uei, MIN(act) act, MODE(nm) nm, LISTAGG(DISTINCT ag, ',') ags, MAX(prov) prov FROM x GROUP BY 1),
t AS (SELECT CONTRACT_AWARD_UNIQUE_KEY k, TRY_TO_DATE(ACTION_DATE::string) d, TRY_TO_NUMBER(FEDERAL_ACTION_OBLIGATION::string,38,2) amt, TRIM(RECIPIENT_UEI) u, UPPER(RECIPIENT_NAME) rn, SEQ8() rid FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_USASPENDING_CONTRACTS_FULL_R2 WHERE TRIM(RECIPIENT_UEI) IN (SELECT uei FROM xu)),
tf AS (SELECT t.rid, ANY_VALUE(t.u) u, ANY_VALUE(t.rn) rn, ANY_VALUE(t.d) d, ANY_VALUE(t.amt) amt, COUNT(x.uei) inwin FROM t LEFT JOIN x ON x.uei=t.u AND t.d BETWEEN x.act AND x.term GROUP BY 1),
per AS (SELECT u, ANY_VALUE(rn) rn, COUNT(*) n, SUM(amt) amt, SUM(IFF(inwin>0,amt,0)) amt_in, SUM(IFF(inwin>0 AND amt>0,amt,0)) pos_in, COUNT_IF(inwin>0) n_in, MIN(d) first_d, MAX(d) last_d FROM tf GROUP BY 1),
j AS (SELECT per.*, xu.nm, xu.ags, xu.act, xu.prov, JAROWINKLER_SIMILARITY(REGEXP_REPLACE(xu.nm,'[^A-Z0-9 ]',''),REGEXP_REPLACE(per.rn,'[^A-Z0-9 ]','')) jw FROM per JOIN xu ON per.u=xu.uei)
SELECT 'SUMMARY' u, NULL nm, NULL rn, NULL ags, COUNT(*)::string n_uei, SUM(n)::string rows_, ROUND(SUM(amt))::string dollars, COUNT_IF(n_in>0)::string uei_paid_in_window, ROUND(SUM(amt_in))::string net_in_window, ROUND(SUM(pos_in))::string gross_pos_in_window, COUNT_IF(jw>=85)::string name_agree, COUNT_IF(prov=1)::string prov_uei, COUNT_IF(prov=1 AND n_in>0)::string prov_uei_in_win, ROUND(SUM(IFF(prov=1,amt_in,0)))::string prov_dollars_in_win, (SELECT COUNT(DISTINCT TRIM(RECIPIENT_PARENT_UEI)) FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_USASPENDING_CONTRACTS_FULL_R2 WHERE TRIM(RECIPIENT_PARENT_UEI) IN (SELECT uei FROM xu))::string parent_uei_hits, MIN(first_d)::string first_d, MAX(last_d)::string last_d
FROM j
UNION ALL
SELECT * FROM (SELECT u, nm, rn, ags, act::string, n::string, ROUND(amt)::string, n_in::string, ROUND(amt_in)::string, ROUND(pos_in)::string, jw::string, prov::string, NULL, NULL, NULL, first_d::string, last_d::string FROM j ORDER BY pos_in DESC NULLS LAST LIMIT 15);

-- [40]
-- ATI Government Solutions (SBA exclusion 2025-10-21): actions by table and fiscal half, FULL vs R2
SELECT 'FULL' src, TRIM(RECIPIENT_UEI) u, IFF(ACTION_DATE::date>='2025-10-21','after','before') w, COUNT(*) n, ROUND(SUM(FEDERAL_ACTION_OBLIGATION)) amt, MIN(ACTION_DATE)::string mn, MAX(ACTION_DATE)::string mx, LISTAGG(DISTINCT AWARDING_AGENCY_NAME,'; ') ag FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_USASPENDING_CONTRACTS_FULL WHERE TRIM(RECIPIENT_UEI)='C1ZLDAS18FJ3' GROUP BY 1,2,3
UNION ALL SELECT 'R2', TRIM(RECIPIENT_UEI), IFF(ACTION_DATE::date>='2025-10-21','after','before'), COUNT(*), ROUND(SUM(FEDERAL_ACTION_OBLIGATION)), MIN(ACTION_DATE)::string, MAX(ACTION_DATE)::string, LISTAGG(DISTINCT AWARDING_AGENCY_NAME,'; ') FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_USASPENDING_CONTRACTS_FULL_R2 WHERE TRIM(RECIPIENT_UEI)='C1ZLDAS18FJ3' OR UPPER(RECIPIENT_NAME) LIKE 'ATI GOVERNMENT SOLUTIONS%' GROUP BY 1,2,3
UNION ALL SELECT 'SAM', UEI, EXCLUSION_TYPE||' / '||COALESCE(EXCLUSION_PROGRAM,''), NULL, NULL, ACTIVATION_DATE::string, TERMINATION_DATE_RAW, EXCLUDING_AGENCY FROM LIBRARY_MARTS.PROCUREMENT.PROCUREMENT__FED_SAM_EXCLUSIONS WHERE UEI='C1ZLDAS18FJ3';
