-- [1] HPSA primary care first look
SELECT HPSA_ID, HPSA_STATUS, HPSA_SCORE, DESIGNATION_TYPE, COMPONENT_TYPE_DESCRIPTION, COMMON_STATE_COUNTY_FIPS_CODE, STATE_COUNTY_FIPS_CODE, DESIGNATION_POPULATION, HPSA_SHORTAGE, (SELECT COUNT(*) FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_HRSA_HPSA_PRIMARY_CARE) n FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_HRSA_HPSA_PRIMARY_CARE LIMIT 5;

-- [2] CSV:dbl COUNTY_DOUBLE_BURDEN all rows
SELECT * FROM LIBRARY_MARTS.JUSTICE.JUSTICE__COUNTY_DOUBLE_BURDEN;

-- [3] ARCOS first look
SELECT TRANSACTION_DATE, BUYER_NAME, BUYER_BUSINESS_ACTIVITY, BUYER_COUNTY_FIPS, REPORTER_COUNTY_FIPS, DOSAGE_UNITS, QUANTITY, TOTAL_MME, TRANSACTION_CODE, (SELECT COUNT(*) FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_DEA_ARCOS) n FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_DEA_ARCOS LIMIT 5;

-- [4] SBA first look
SELECT BORROWER_NAME, BORROWER_CITY, BORROWER_STATE, BORROWER_ZIP, PROJECT_COUNTY, APPROVAL_DATE, PROGRAM, GROSS_APPROVAL_AMOUNT, THIRD_PARTY_DOLLARS, GROSS_CHARGEOFF_AMOUNT, LOAN_STATUS, LOSS_RATE, (SELECT COUNT(*) FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_SBA_LOANS) n FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_SBA_LOANS LIMIT 5;

-- [5] SOD first look
SELECT SURVEY_YEAR, FDIC_CERT, INSTITUTION_NAME, BRANCH_STATE_COUNTY_FIPS, BRANCH_DEPOSITS_THOUSANDS, MAIN_OFFICE_FLAG, BRANCH_DEPOSIT_REPORTING_METHOD, SIMS_ACQUIRED_DATE, (SELECT COUNT(*) FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_FDIC_SOD_BRANCH_DEPOSITS) n FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_FDIC_SOD_BRANCH_DEPOSITS LIMIT 5;

-- [6] R2 first look
SELECT ACTION_DATE, RECIPIENT_ZIP_4_CODE, RECIPIENT_STATE_CODE, PRIMARY_PLACE_OF_PERFORMANCE_STATE_CODE, FEDERAL_ACTION_OBLIGATION, RECIPIENT_NAME, (SELECT COUNT(*) FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_USASPENDING_CONTRACTS_FULL_R2) n FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_USASPENDING_CONTRACTS_FULL_R2 LIMIT 5;

-- [7] FDIC enforcement first look
SELECT ORDER_DATE, ORDER_YEAR, INSTITUTION_NAME, BANK_NAME, BANK_HOLDING_COMPANY, STATE, CERT_NUMBER, CERT_ATTACHED, ORDER_TYPE, ORDER_CATEGORY, CMP_AMOUNT_TOTAL, RESPONDENT_COUNT, BANK_ACTIVE, (SELECT COUNT(*) FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_FDIC_ENFORCEMENT_ORDERS) n FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_FDIC_ENFORCEMENT_ORDERS LIMIT 5;

-- [8] WaPo first look
SELECT ID, VICTIM_NAME, INCIDENT_DATE, CITY, COUNTY, STATE, AGE, RACE, (SELECT COUNT(*) FROM LIBRARY_MARTS.JUSTICE.JUSTICE__XC_WAPO_FATAL_FORCE) n FROM LIBRARY_MARTS.JUSTICE.JUSTICE__XC_WAPO_FATAL_FORCE LIMIT 5;

-- [9] FJC judges first look
SELECT NID, JID, LAST_NAME, FIRST_NAME, MIDDLE_NAME, BIRTH_YEAR, BIRTH_STATE, COURT_NAME_1, COMMISSION_DATE_1, (SELECT COUNT(*) FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_FJC_ARTICLE_III_JUDGES) n FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_FJC_ARTICLE_III_JUDGES LIMIT 5;

-- [10] CL dockets first look
SELECT ID, COURT_ID, DATE_FILED, ASSIGNED_TO_ID, ASSIGNED_TO_STR, NATURE_OF_SUIT, SOURCE, (SELECT COUNT(*) FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_COURTLISTENER_DOCKETS) n FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_COURTLISTENER_DOCKETS LIMIT 5;

-- [11] CL positions first look
SELECT ID, PERSON_ID, COURT_ID, POSITION_TYPE, JOB_TITLE, ORGANIZATION_NAME, DATE_NOMINATED, DATE_JUDICIAL_COMMITTEE_ACTION, JUDICIAL_COMMITTEE_ACTION, DATE_CONFIRMATION, DATE_START, DATE_TERMINATION, (SELECT COUNT(*) FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_COURTLISTENER_POSITIONS) n FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_COURTLISTENER_POSITIONS WHERE DATE_JUDICIAL_COMMITTEE_ACTION IS NOT NULL LIMIT 5;

-- [12] NH penalties first look
SELECT CMS_CERTIFICATION_NUMBER_CCN, PROVIDER_NAME, STATE, PENALTY_DATE, PENALTY_TYPE, FINE_AMOUNT, PAYMENT_DENIAL_START_DATE, PAYMENT_DENIAL_LENGTH_IN_DAYS, PROCESSING_DATE, (SELECT COUNT(*) FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_NURSING_HOME_PENALTIES) n FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_NURSING_HOME_PENALTIES LIMIT 5;

-- [13] CSV:hpsa HPSA primary care by county, status, designation type
SELECT COMMON_STATE_COUNTY_FIPS_CODE fips, HPSA_STATUS st, DESIGNATION_TYPE dt, COUNT(*) n, COUNT(DISTINCT HPSA_ID) ids, MAX(TRY_TO_DOUBLE(HPSA_SCORE::varchar)) mx, AVG(TRY_TO_DOUBLE(HPSA_SCORE::varchar)) av, COUNT(DISTINCT HPSA_SCORE) dscore FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_HRSA_HPSA_PRIMARY_CARE GROUP BY 1,2,3;

-- [14] CSV:arcos ARCOS by buyer county and transaction code
SELECT BUYER_COUNTY_FIPS fips, TRANSACTION_CODE code, COUNT(*) n, SUM(DOSAGE_UNITS) units, SUM(TOTAL_MME) mme, COUNT(DISTINCT BUYER_DEA_NO) buyers, MIN(TRANSACTION_DATE) d1, MAX(TRANSACTION_DATE) d2 FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_DEA_ARCOS GROUP BY 1,2;

-- [15] CSV:mpv MPV all rows, key columns
SELECT MPV_ID, VICTIM_S_NAME, STATE, CITY, COUNTY, ZIPCODE, DATE_OF_INCIDENT_MONTH_DAY_YEAR dt, AGENCY_RESPONSIBLE_FOR_DEATH agency, WAPO_ID_IF_INCLUDED_IN_WAPO_DATABASE wapo_id, NATIVE_AMERICAN_PERCENT_OF_THE_POPULATION_ACS nat_pct, TOTAL_POPULATION_OF_CENSUS_TRACT_2019_ACS_5_YEAR_ESTIMATES tract_pop, VICTIM_S_RACE race, CAUSE_OF_DEATH cause FROM LIBRARY_MARTS.JUSTICE.JUSTICE__XC_MAPPING_POLICE_VIOLENCE;

-- [16] CSV:wapo WaPo all rows, key columns
SELECT ID, VICTIM_NAME, INCIDENT_DATE, CITY, COUNTY, STATE, AGE, RACE, ARMED_WITH, MENTAL_ILLNESS_RELATED, BODY_CAMERA_PRESENT FROM LIBRARY_MARTS.JUSTICE.JUSTICE__XC_WAPO_FATAL_FORCE;

-- [17] CSV:sba SBA by borrower state, zip5, program
SELECT BORROWER_STATE st, LEFT(BORROWER_ZIP::varchar,5) zip5, PROGRAM prog, COUNT(*) n, SUM(GROSS_APPROVAL_AMOUNT) appr, SUM(THIRD_PARTY_DOLLARS) tpd, SUM(GROSS_CHARGEOFF_AMOUNT) co, COUNT_IF(GROSS_CHARGEOFF_AMOUNT>0) n_co, COUNT_IF(LOAN_STATUS ILIKE '%CHG%') n_chgoff_status, MIN(YEAR(APPROVAL_DATE)) y1, MAX(YEAR(APPROVAL_DATE)) y2 FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_SBA_LOANS GROUP BY 1,2,3;

-- [18] SBA loan status values and year span
SELECT LOAN_STATUS, COUNT(*) n, MIN(APPROVAL_DATE) d1, MAX(APPROVAL_DATE) d2, COUNT(THIRD_PARTY_DOLLARS) tpd_nn, COUNT(LOSS_RATE) lr_nn, SUM(GROSS_CHARGEOFF_AMOUNT) co FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_SBA_LOANS GROUP BY 1 ORDER BY 2 DESC;

-- [19] CSV:sod SOD by year and branch county
SELECT SURVEY_YEAR yr, BRANCH_STATE_COUNTY_FIPS fips, COUNT(*) branches, SUM(BRANCH_DEPOSITS_THOUSANDS) dep_k, SUM(IFF(MAIN_OFFICE_FLAG::varchar='1',BRANCH_DEPOSITS_THOUSANDS,0)) main_dep_k, COUNT(DISTINCT FDIC_CERT) banks, MAX_BY(INSTITUTION_NAME, BRANCH_DEPOSITS_THOUSANDS) top_inst, MAX(BRANCH_DEPOSITS_THOUSANDS) top_dep_k FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_FDIC_SOD_BRANCH_DEPOSITS GROUP BY 1,2;

-- [20] CSV:sodcert SOD by FDIC cert and year
SELECT FDIC_CERT cert, SURVEY_YEAR yr, MAX(INSTITUTION_NAME) nm, MAX(INSTITUTION_STATE) st, MAX(INSTITUTION_CITY) city, SUM(BRANCH_DEPOSITS_THOUSANDS) dep_k, COUNT(*) branches FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_FDIC_SOD_BRANCH_DEPOSITS GROUP BY 1,2;

-- [21] CSV:fdicord FDIC enforcement orders all rows
SELECT ORDER_ID, DOCKET_NUMBER, ORDER_DATE, ORDER_YEAR, INSTITUTION_NAME, BANK_NAME, BANK_HOLDING_COMPANY, CITY, STATE, BANK_CITY, BANK_STATE, CERT_NUMBER, CERT_ATTACHED, ORDER_TYPE, CMP_AMOUNT_TOTAL, RESTITUTION_AMOUNT_TOTAL, RESPONDENT_COUNT, RESPONDENTS, BANK_ACTIVE, BANK_END_DATE, TERMINATION_DATE FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_FDIC_ENFORCEMENT_ORDERS;

-- [22] CSV:fjc FJC judges key columns
SELECT NID, JID, LAST_NAME, FIRST_NAME, MIDDLE_NAME, SUFFIX, BIRTH_YEAR, BIRTH_STATE, DEATH_YEAR, COURT_NAME_1, APPOINTING_PRESIDENT_1, COMMISSION_DATE_1, TERMINATION_DATE_1, COURT_NAME_2 FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_FJC_ARTICLE_III_JUDGES;

-- [23] CSV:clj CourtListener judges key columns
SELECT ID, FJC_ID, NAME_FIRST, NAME_MIDDLE, NAME_LAST, NAME_SUFFIX, DATE_DOB, DOB_STATE, IS_ALIAS_OF_ID, FTM_TOTAL_RECEIVED FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_COURTLISTENER_JUDGES;

-- [24] CSV:clpos CourtListener positions key columns
SELECT ID, PERSON_ID, COURT_ID, POSITION_TYPE, JOB_TITLE, ORGANIZATION_NAME, SECTOR, DATE_NOMINATED, DATE_JUDICIAL_COMMITTEE_ACTION, JUDICIAL_COMMITTEE_ACTION, DATE_CONFIRMATION, DATE_START, DATE_TERMINATION, TERMINATION_REASON, HOW_SELECTED, VOTES_YES, VOTES_NO FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_COURTLISTENER_POSITIONS;

-- [25] CSV:clfd CourtListener financial disclosures per person and year
SELECT PERSON_ID, YEAR_COL, COUNT(*) n, MAX(REPORT_TYPE) rt FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_COURTLISTENER_FINANCIAL_DISCLOSURES GROUP BY 1,2;

-- [26] CSV:nhpen NH penalties all rows
SELECT * FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_NURSING_HOME_PENALTIES;

-- [27] CSV:nh NH provider key columns
SELECT CMS_CERTIFICATION_NUMBER_CCN, PROVIDER_NAME, STATE, COUNTY_FIPS, OWNERSHIP_TYPE, CHAIN_NAME, OVERALL_RATING, HEALTH_INSPECTION_RATING, SPECIAL_FOCUS_STATUS, ABUSE_ICON, NUMBER_OF_CERTIFIED_BEDS, NUMBER_OF_FINES, TOTAL_AMOUNT_OF_FINES_IN_DOLLARS, NUMBER_OF_PAYMENT_DENIALS, RATING_CYCLE_1_STANDARD_SURVEY_HEALTH_DATE, PROCESSING_DATE FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_NURSING_HOME;

-- [28] CSV:dock CourtListener dockets by filing year and court
SELECT YEAR(DATE_FILED) yr, COURT_ID, COUNT(*) n, COUNT(ASSIGNED_TO_ID) assigned, COUNT(DISTINCT ASSIGNED_TO_ID) judges FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_COURTLISTENER_DOCKETS GROUP BY 1,2;

-- [29] ARCOS top buyers in the four highest pills-per-person counties
SELECT BUYER_COUNTY_FIPS, BUYER_NAME, BUYER_BUSINESS_ACTIVITY, BUYER_CITY, COUNT(*) n, SUM(DOSAGE_UNITS) units FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_DEA_ARCOS WHERE BUYER_COUNTY_FIPS IN ('45019','20103','51690','54059') AND TRANSACTION_CODE='S' GROUP BY 1,2,3,4 QUALIFY ROW_NUMBER() OVER (PARTITION BY BUYER_COUNTY_FIPS ORDER BY SUM(DOSAGE_UNITS) DESC) <= 3 ORDER BY 1, units DESC;

-- [30] CSV:r2 Contracts R2 by recipient state and ZIP5
SELECT RECIPIENT_STATE_CODE st, LEFT(RECIPIENT_ZIP_4_CODE::varchar,5) zip5, COUNT(*) n, SUM(FEDERAL_ACTION_OBLIGATION) fao, SUM(IFF(LEFT(ACTION_DATE::varchar,4)<'2016',FEDERAL_ACTION_OBLIGATION,0)) fao_early, MAX_BY(RECIPIENT_NAME, FEDERAL_ACTION_OBLIGATION) top_rcpt FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_USASPENDING_CONTRACTS_FULL_R2 GROUP BY 1,2;

-- [31] Assistance top 20 recipient names and UEI-name agreement
WITH n AS (SELECT RECIPIENT_NAME nm, COUNT(*) rows_, COUNT(DISTINCT RECIPIENT_UEI) ueis, COUNT(DISTINCT RECIPIENT_STATE_CODE) states, SUM(FEDERAL_ACTION_OBLIGATION)/1e9 bn FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_USASPENDING_ASSISTANCE_FULL GROUP BY 1),
u AS (SELECT RECIPIENT_UEI, COUNT(DISTINCT RECIPIENT_NAME) names FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_USASPENDING_ASSISTANCE_FULL WHERE RECIPIENT_UEI IS NOT NULL AND RECIPIENT_UEI<>'' GROUP BY 1)
SELECT * FROM (SELECT nm, rows_, ueis, states, bn FROM n ORDER BY rows_ DESC LIMIT 20)
UNION ALL SELECT '__UEI_SUMMARY ueis/one_name_share/max_names', COUNT(*), AVG(IFF(names=1,1,0))*1e6, MAX(names), NULL FROM u
UNION ALL SELECT '__NAMES_TOTAL', COUNT(*), SUM(rows_), NULL, SUM(bn) FROM n;

-- [32] SBA top 20 borrower names
SELECT UPPER(TRIM(BORROWER_NAME)) nm, COUNT(*) n, COUNT(DISTINCT BORROWER_STATE) states, COUNT(DISTINCT BORROWER_CITY) cities, SUM(GROSS_APPROVAL_AMOUNT)/1e6 appr_m, COUNT_IF(GROSS_CHARGEOFF_AMOUNT>0) n_co, MIN(YEAR(APPROVAL_DATE)) y1, MAX(YEAR(APPROVAL_DATE)) y2 FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_SBA_LOANS GROUP BY 1 ORDER BY n DESC LIMIT 20;

-- [33] SBA borrower to IRS BMF on name + state (2+ words), ZIP agreement
WITH s AS (SELECT UPPER(TRIM(BORROWER_NAME)) nm, BORROWER_STATE st, MAX(LPAD(LEFT(BORROWER_ZIP::varchar,5),5,'0')) z, MAX(UPPER(BORROWER_CITY)) city, COUNT(*) n FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_SBA_LOANS WHERE BORROWER_NAME LIKE '% %' GROUP BY 1,2),
b AS (SELECT UPPER(TRIM(ORGANIZATION_NAME)) nm, STATE st, MAX(LEFT(ZIP::varchar,5)) z, MAX(UPPER(CITY)) city, COUNT(DISTINCT EIN) eins FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_IRS_BMF GROUP BY 1,2)
SELECT COUNT(*) sba_name_states, COUNT(b.nm) hit, COUNT_IF(b.z=s.z) zip_agree, COUNT_IF(b.city=s.city) city_agree, SUM(IFF(b.nm IS NOT NULL,s.n,0)) loans_hit, SUM(s.n) loans_all,
 (SELECT LISTAGG(x,'; ') FROM (SELECT s2.nm||' '||s2.st||' zip '||s2.z||'/'||b2.z x FROM s s2 JOIN b b2 ON b2.nm=s2.nm AND b2.st=s2.st ORDER BY s2.n DESC LIMIT 12)) sample
FROM s LEFT JOIN b ON b.nm=s.nm AND b.st=s.st;

-- [34] RERUN fixed alias: SBA borrower to IRS BMF on name + state (2+ words), ZIP agreement
WITH s AS (SELECT UPPER(TRIM(BORROWER_NAME)) nm, BORROWER_STATE st, MAX(LPAD(LEFT(BORROWER_ZIP::varchar,5),5,'0')) z, MAX(UPPER(BORROWER_CITY)) city, COUNT(*) n FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_SBA_LOANS WHERE BORROWER_NAME LIKE '% %' GROUP BY 1,2),
b AS (SELECT UPPER(TRIM(ORGANIZATION_NAME)) nm, STATE st, MAX(LEFT(ZIP::varchar,5)) z, MAX(UPPER(CITY)) city, COUNT(DISTINCT EIN) eins FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_IRS_BMF GROUP BY 1,2)
SELECT COUNT(*) sba_name_states, COUNT(b.nm) hit, COUNT_IF(b.z=s.z) zip_agree, COUNT_IF(b.city=s.city) city_agree, SUM(IFF(b.nm IS NOT NULL,s.n,0)) loans_hit, SUM(s.n) loans_all,
 (SELECT LISTAGG(x,'; ') FROM (SELECT s2.nm||' '||s2.st||' zip '||s2.z||'/'||b2.z x FROM s s2 JOIN b b2 ON b2.nm=s2.nm AND b2.st=s2.st ORDER BY s2.n DESC LIMIT 12)) top_hits
FROM s LEFT JOIN b ON b.nm=s.nm AND b.st=s.st;

-- NOTE (sweep2-d): no other warehouse statements were run.
-- County joins for the contracts/assistance pairs reused sweep-d's saved extracts in the shared scratchpad
-- (d_contracts_pc.csv, d_assist_pc.csv, d_cdc_drug.csv, d_dim.csv from sweep-d statements 8, 9, 12, 13), joined locally in pandas.
-- Statement [6] timed out at 300 s (R2 LIMIT 5 with a COUNT(*) subquery); [33] failed to compile (reserved word) and was rerun as [34].
