-- [1] DIM_COUNTY shape
SELECT * FROM LIBRARY_MARTS.CORE.DIM_COUNTY LIMIT 3;

-- [2] DIM_COUNTY count
SELECT COUNT(*) n, COUNT(DISTINCT 1) x, SUM(POPULATION_2020) pop FROM LIBRARY_MARTS.CORE.DIM_COUNTY;

-- [3] HMDA trio + BULK: state spread (samples?)
SELECT 'HMDA' t, COUNT(*) n, COUNT(DISTINCT STATE_CODE) states, MIN(STATE_CODE) s1, MAX(STATE_CODE) s2, MIN(ACTIVITY_YEAR) y1, MAX(ACTIVITY_YEAR) y2 FROM LIBRARY_MARTS.HOUSING.HOUSING__FED_CFPB_HMDA
UNION ALL SELECT 'HMDA_DC_ONLY', COUNT(*), COUNT(DISTINCT STATE_CODE), MIN(STATE_CODE), MAX(STATE_CODE), MIN(ACTIVITY_YEAR), MAX(ACTIVITY_YEAR) FROM LIBRARY_MARTS.HOUSING.HOUSING__FED_CFPB_HMDA_DC_ONLY
UNION ALL SELECT 'HMDA_LAR', COUNT(*), COUNT(DISTINCT STATE_CODE), MIN(STATE_CODE), MAX(STATE_CODE), MIN(ACTIVITY_YEAR), MAX(ACTIVITY_YEAR) FROM LIBRARY_MARTS.HOUSING.HOUSING__FED_CFPB_HMDA_LAR
UNION ALL SELECT 'BULK', COUNT(*), COUNT(DISTINCT PRIME_AWARD_TRANSACTION_PLACE_OF_PERFORMANCE_COUNTY_FIPS_CODE), MIN(ACTION_DATE)::varchar, MAX(ACTION_DATE)::varchar, COUNT(DISTINCT RECIPIENT_UEI), COUNT(DISTINCT RECIPIENT_NAME) FROM LIBRARY_MARTS.PROCUREMENT.PROCUREMENT__FED_USASPENDING_BULK;

-- [4] CONTRACTS_FULL sample geo cols
SELECT PRIME_AWARD_TRANSACTION_RECIPIENT_COUNTY_FIPS_CODE rc, PRIME_AWARD_TRANSACTION_PLACE_OF_PERFORMANCE_COUNTY_FIPS_CODE pc, RECIPIENT_STATE_CODE, ACTION_DATE, ACTION_DATE_FISCAL_YEAR, FEDERAL_ACTION_OBLIGATION, RECIPIENT_NAME, RECIPIENT_UEI FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_USASPENDING_CONTRACTS_FULL LIMIT 5;

-- [5] ASSISTANCE_FULL sample geo cols
SELECT PRIME_AWARD_TRANSACTION_RECIPIENT_COUNTY_FIPS_CODE rc, PRIME_AWARD_TRANSACTION_PLACE_OF_PERFORMANCE_COUNTY_FIPS_CODE pc, ACTION_DATE, ACTION_DATE_FISCAL_YEAR, FEDERAL_ACTION_OBLIGATION, RECIPIENT_NAME, ASSISTANCE_TYPE_CODE FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_USASPENDING_ASSISTANCE_FULL LIMIT 5;

-- [6] CONTRACTS_FULL by fiscal year + geo column shape
SELECT ACTION_DATE_FISCAL_YEAR fy, COUNT(*) n, SUM(FEDERAL_ACTION_OBLIGATION)/1e9 fao_bn, MIN(ACTION_DATE) d1, MAX(ACTION_DATE) d2,
 COUNT(DISTINCT ACTION_DATE) days,
 AVG(IFF(LENGTH(PRIME_AWARD_TRANSACTION_PLACE_OF_PERFORMANCE_COUNTY_FIPS_CODE)=5,1,0)) pc5,
 AVG(IFF(PRIME_AWARD_TRANSACTION_RECIPIENT_COUNTY_FIPS_CODE IS NULL OR PRIME_AWARD_TRANSACTION_RECIPIENT_COUNTY_FIPS_CODE='',1,0)) rc_null
FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_USASPENDING_CONTRACTS_FULL GROUP BY 1 ORDER BY 1;

-- [7] ASSISTANCE_FULL by fiscal year + geo column shape
SELECT ACTION_DATE_FISCAL_YEAR fy, COUNT(*) n, SUM(FEDERAL_ACTION_OBLIGATION)/1e9 fao_bn, MIN(ACTION_DATE) d1, MAX(ACTION_DATE) d2,
 COUNT(DISTINCT ACTION_DATE) days,
 AVG(IFF(LENGTH(PRIME_AWARD_TRANSACTION_PLACE_OF_PERFORMANCE_COUNTY_FIPS_CODE)=5,1,0)) pc5,
 AVG(IFF(PRIME_AWARD_TRANSACTION_RECIPIENT_COUNTY_FIPS_CODE::varchar LIKE '%.0',1,0)) rc_float
FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_USASPENDING_ASSISTANCE_FULL GROUP BY 1 ORDER BY 1;

-- [8] CSV:contracts_county per place-of-performance county
SELECT PRIME_AWARD_TRANSACTION_PLACE_OF_PERFORMANCE_COUNTY_FIPS_CODE fips, COUNT(*) n, SUM(FEDERAL_ACTION_OBLIGATION) fao,
 SUM(IFF(ACTION_DATE_FISCAL_YEAR<=2015,FEDERAL_ACTION_OBLIGATION,0)) fao_early, SUM(IFF(ACTION_DATE_FISCAL_YEAR>2015,FEDERAL_ACTION_OBLIGATION,0)) fao_late,
 COUNT(DISTINCT RECIPIENT_UEI) ueis, MAX_BY(RECIPIENT_NAME, FEDERAL_ACTION_OBLIGATION) top_rcpt, MAX(FEDERAL_ACTION_OBLIGATION) top_fao
FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_USASPENDING_CONTRACTS_FULL GROUP BY 1;

-- [9] CSV:assist_county per place-of-performance county
SELECT PRIME_AWARD_TRANSACTION_PLACE_OF_PERFORMANCE_COUNTY_FIPS_CODE fips, COUNT(*) n, SUM(FEDERAL_ACTION_OBLIGATION) fao,
 SUM(IFF(ACTION_DATE_FISCAL_YEAR<=2015,FEDERAL_ACTION_OBLIGATION,0)) fao_early, SUM(IFF(ACTION_DATE_FISCAL_YEAR>2015,FEDERAL_ACTION_OBLIGATION,0)) fao_late,
 COUNT(DISTINCT RECIPIENT_NAME) rcpts, MAX_BY(RECIPIENT_NAME, FEDERAL_ACTION_OBLIGATION) top_rcpt, MAX(FEDERAL_ACTION_OBLIGATION) top_fao
FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_USASPENDING_ASSISTANCE_FULL GROUP BY 1;

-- [10] CSV:cdc_injury all rows
SELECT GEOID, NAME, PERIOD, ST_NAME, INTENT, COUNT_SUP, RATE, RATE_M FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CDC_INJURY_VIOLENCE_COUNTY;

-- [11] CSV:hrsa_county shortage rows by county
SELECT COMMON_STATE_COUNTY_FIPS_CODE fips, HPSA_DISCIPLINE_CLASS cls, HPSA_STATUS st, COUNT(*) n, COUNT(DISTINCT HPSA_ID) hpsas, AVG(TRY_TO_DOUBLE(HPSA_SCORE::varchar)) score FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_HRSA_SHORTAGE_AREAS GROUP BY 1,2,3;

-- [12] CSV:cdc_drug all rows
SELECT FIPS, YEAR, STATE, COUNTY, POPULATION, ESTIMATED_AGE_ADJUSTED_DEATH_RATE_11_CATEGORIES_IN_RANGES band FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CDC_DRUG_POISONING_COUNTY;

-- [13] CSV:dim DIM_COUNTY full
SELECT COUNTY_FIPS, STATE_FIPS, COUNTY_NAME, STATE_NAME, POPULATION_2020 FROM LIBRARY_MARTS.CORE.DIM_COUNTY;

-- [14] CSV:hmdah_state HMDA historic by state, year, action
SELECT STATE_CODE, STATE_ABBR, AS_OF_YEAR, ACTION_TAKEN, ACTION_TAKEN_NAME, COUNT(*) n, SUM(TRY_TO_DOUBLE(LOAN_AMOUNT_000S::varchar)) loan_000s, MEDIAN(TRY_TO_DOUBLE(LOAN_AMOUNT_000S::varchar)) med_loan
FROM LIBRARY_MARTS.HOUSING.HOUSING__FED_CFPB_HMDA_HISTORIC GROUP BY 1,2,3,4,5;

-- [15] NPDB first look
SELECT SEQNO, REC_TYPE, ORIG_YEAR, WORK_STATE, LICENSE_STATE, PAYMENT_FLAG, TOTAL_PAYMENT, PAYMENT_NUMBER, NUM_PERSONS, PRACTITIONER_REPORT_SEQ FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_HRSA_NPDB WHERE REC_TYPE IS NOT NULL LIMIT 6;

-- [16] NPDB rec types and payment shape
SELECT REC_TYPE, COUNT(*) n, COUNT(TOTAL_PAYMENT) pay_nn, SUM(IFF(TRY_TO_DOUBLE(REPLACE(REPLACE(TOTAL_PAYMENT::varchar,'$',''),',','')) IS NULL AND TOTAL_PAYMENT IS NOT NULL,1,0)) pay_unparsed,
 MIN(ORIG_YEAR) y1, MAX(ORIG_YEAR) y2, COUNT(DISTINCT WORK_STATE) states FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_HRSA_NPDB GROUP BY 1;

-- [17] ICE stints first look
SELECT STATE, COUNTY, DETENTION_FACILITY, STAY_BOOK_IN_AT, FINAL_ORDER_DATE, INITIAL_BOND_SET_AMOUNT, BOND_POSTED_AMOUNT, DUPLICATE_LIKELY, DUPLICATE_DROP_ROW FROM LIBRARY_MARTS.IMMIGRATION.IMMIGRATION__FED_ICE_DETENTION_STINTS LIMIT 5;

-- [18] FEMA IA first look
SELECT COUNTY, FIPS, CENSUS_GEOID, CENSUS_YEAR, DAMAGED_STATE_ABBREVIATION, DISASTER_NUMBER, APPLIED_DATE, GROSS_INCOME, IHP_AMOUNT, HA_AMOUNT, FLOOD_DAMAGE_AMOUNT FROM LIBRARY_MARTS.HOUSING.HOUSING__FED_FEMA_IA_HOUSING_REGISTRATIONS LIMIT 5;

-- [19] CSV:npdb_state NPDB by work state, record type; dollars parsed from PAYMENT_FLAG
SELECT WORK_STATE, REC_TYPE, COUNT(*) n, COUNT(TOTAL_PAYMENT) total_payment_nn,
 COUNT(TRY_TO_DOUBLE(REPLACE(REPLACE(PAYMENT_FLAG::varchar,'$',''),',',''))) pay_parsed,
 SUM(TRY_TO_DOUBLE(REPLACE(REPLACE(PAYMENT_FLAG::varchar,'$',''),',',''))) pay_sum,
 MEDIAN(TRY_TO_DOUBLE(REPLACE(REPLACE(PAYMENT_FLAG::varchar,'$',''),',',''))) pay_med,
 SUM(IFF(ORIG_YEAR>=2015,1,0)) n_2015on,
 SUM(IFF(ORIG_YEAR>=2015,TRY_TO_DOUBLE(REPLACE(REPLACE(PAYMENT_FLAG::varchar,'$',''),',','')),0)) pay_2015on
FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_HRSA_NPDB GROUP BY 1,2;

-- [20] NPDB PAYMENT_FLAG values sample on P rows
SELECT PAYMENT_FLAG, COUNT(*) n FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_HRSA_NPDB WHERE REC_TYPE IN ('P','M') GROUP BY 1 ORDER BY 2 DESC LIMIT 8;

-- [21] CSV:ice_state ICE stints by state
SELECT STATE, COUNT(*) n, COUNT(DISTINCT PERSON_HASH) persons, SUM(IFF(DUPLICATE_DROP_ROW::varchar ILIKE 'true',1,0)) droprows,
 COUNT(INITIAL_BOND_SET_AMOUNT) bond_nn, MEDIAN(INITIAL_BOND_SET_AMOUNT) bond_med, SUM(INITIAL_BOND_SET_AMOUNT) bond_sum,
 MIN(STAY_BOOK_IN_AT) d1, MAX(STAY_BOOK_IN_AT) d2, COUNT(FINAL_ORDER_DATE) fo_nn
FROM LIBRARY_MARTS.IMMIGRATION.IMMIGRATION__FED_ICE_DETENTION_STINTS GROUP BY 1;

-- [22] ICE stints per year (book-in and final order)
SELECT YEAR(STAY_BOOK_IN_AT) y, COUNT(*) stints, COUNT(DISTINCT PERSON_HASH) persons, COUNT(INITIAL_BOND_SET_AMOUNT) bonds,
 (SELECT COUNT(*) FROM LIBRARY_MARTS.IMMIGRATION.IMMIGRATION__FED_ICE_DETENTION_STINTS s2 WHERE YEAR(s2.FINAL_ORDER_DATE)=YEAR(s.STAY_BOOK_IN_AT)) final_orders_that_year
FROM LIBRARY_MARTS.IMMIGRATION.IMMIGRATION__FED_ICE_DETENTION_STINTS s GROUP BY 1 ORDER BY 1;

-- [23] CSV:fema_county FEMA IA by county
SELECT FIPS, MAX(COUNTY) cname, COUNT(*) n, COUNT(DISTINCT DISASTER_NUMBER) disasters, SUM(IHP_AMOUNT) ihp, SUM(HA_AMOUNT) ha, SUM(FLOOD_DAMAGE_AMOUNT) flood,
 AVG(IFF(TRY_TO_DOUBLE(GROSS_INCOME::varchar)>0,1,0)) inc_pos, MIN(APPLIED_DATE) d1, MAX(APPLIED_DATE) d2
FROM LIBRARY_MARTS.HOUSING.HOUSING__FED_FEMA_IA_HOUSING_REGISTRATIONS GROUP BY 1;

-- [24] FEMA gross income values + tract shape
SELECT GROSS_INCOME, COUNT(*) n, AVG(LENGTH(CENSUS_GEOID)) geolen FROM LIBRARY_MARTS.HOUSING.HOUSING__FED_FEMA_IA_HOUSING_REGISTRATIONS GROUP BY 1 ORDER BY 2 DESC LIMIT 12;

-- [25] HMDA historic top 20 lenders by rows (no name column; agency+respondent id)
SELECT AGENCY_CODE, AGENCY_ABBR, RESPONDENT_ID, COUNT(*) n, SUM(IFF(ACTION_TAKEN=3,1,0))/COUNT(*) deny_share, COUNT(DISTINCT STATE_ABBR) states
FROM LIBRARY_MARTS.HOUSING.HOUSING__FED_CFPB_HMDA_HISTORIC GROUP BY 1,2,3 ORDER BY n DESC LIMIT 20;

-- [26] ARID xref first look
SELECT ARID_2017, RESPONDENT_NAME, LEI_2018, (SELECT COUNT(*) FROM LIBRARY_MARTS.HOUSING.HOUSING__FED_CFPB_HMDA_ARID2017_LEI_XREF) n FROM LIBRARY_MARTS.HOUSING.HOUSING__FED_CFPB_HMDA_ARID2017_LEI_XREF LIMIT 5;

-- [27] CONTRACTS top 20 recipient names, UEIs per name
SELECT RECIPIENT_NAME, COUNT(*) n, COUNT(DISTINCT RECIPIENT_UEI) ueis, COUNT(DISTINCT RECIPIENT_STATE_CODE) states, SUM(FEDERAL_ACTION_OBLIGATION)/1e9 fao_bn
FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_USASPENDING_CONTRACTS_FULL GROUP BY 1 ORDER BY n DESC LIMIT 20;

-- [28] CONTRACTS UEI-name agreement
WITH u AS (SELECT RECIPIENT_UEI, COUNT(DISTINCT RECIPIENT_NAME) names, COUNT(DISTINCT RECIPIENT_STATE_CODE) st FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_USASPENDING_CONTRACTS_FULL WHERE RECIPIENT_UEI IS NOT NULL AND RECIPIENT_UEI<>'' GROUP BY 1)
SELECT COUNT(*) ueis, AVG(IFF(names=1,1,0)) one_name, AVG(IFF(st=1,1,0)) one_state, MAX(names) max_names,
 (SELECT AVG(IFF(RECIPIENT_UEI IS NULL OR RECIPIENT_UEI='',1,0)) FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_USASPENDING_CONTRACTS_FULL) uei_blank FROM u;

-- [29] BULK top 20 names + UEI agreement
SELECT RECIPIENT_NAME, COUNT(*) n, COUNT(DISTINCT RECIPIENT_UEI) ueis, COUNT(DISTINCT RECIPIENT_STATE_CODE) states,
 (SELECT AVG(IFF(c=1,1,0)) FROM (SELECT RECIPIENT_UEI, COUNT(DISTINCT RECIPIENT_NAME) c FROM LIBRARY_MARTS.PROCUREMENT.PROCUREMENT__FED_USASPENDING_BULK GROUP BY 1)) uei_one_name
FROM LIBRARY_MARTS.PROCUREMENT.PROCUREMENT__FED_USASPENDING_BULK GROUP BY 1 ORDER BY n DESC LIMIT 20;

-- [30] FRA top 20 railroad names, codes per name
SELECT RAILROAD_NAME, COUNT(*) n, COUNT(DISTINCT RAILROAD_CODE) codes, MIN(INCIDENT_YEAR) y1, MAX(INCIDENT_YEAR) y2, SUM(TRY_TO_NUMBER(TOTAL_KILLED_FORM_57::varchar)) killed
FROM LIBRARY_MARTS.TRANSPORT.TRANSPORT__FED_FRA_CROSSING_INCIDENTS GROUP BY 1 ORDER BY n DESC LIMIT 20;

-- [31] MPV top repeated victim names, addresses, officers
SELECT 'victim' k, VICTIM_S_NAME v, COUNT(*) n FROM LIBRARY_MARTS.JUSTICE.JUSTICE__XC_MAPPING_POLICE_VIOLENCE GROUP BY 1,2 HAVING COUNT(*)>1
UNION ALL SELECT 'address', STREET_ADDRESS_OF_INCIDENT||' | '||CITY||' '||STATE, COUNT(*) FROM LIBRARY_MARTS.JUSTICE.JUSTICE__XC_MAPPING_POLICE_VIOLENCE GROUP BY 1,2 HAVING COUNT(*)>1
UNION ALL SELECT 'agency', AGENCY_RESPONSIBLE_FOR_DEATH, COUNT(*) FROM LIBRARY_MARTS.JUSTICE.JUSTICE__XC_MAPPING_POLICE_VIOLENCE GROUP BY 1,2 HAVING COUNT(*)>60
UNION ALL SELECT 'officer', NAMES_OF_OFFICERS_INVOLVED, COUNT(*) FROM LIBRARY_MARTS.JUSTICE.JUSTICE__XC_MAPPING_POLICE_VIOLENCE WHERE NAMES_OF_OFFICERS_INVOLVED IS NOT NULL GROUP BY 1,2 HAVING COUNT(*)>1
ORDER BY 1, 3 DESC;

-- [32] CSV:mpv_rep MPV repeats: victims, agencies, officers
SELECT 'victim' k, VICTIM_S_NAME v, STATE st, COUNT(*) n FROM LIBRARY_MARTS.JUSTICE.JUSTICE__XC_MAPPING_POLICE_VIOLENCE GROUP BY 1,2,3 HAVING COUNT(*)>1
UNION ALL SELECT 'victim_any_state', VICTIM_S_NAME, NULL, COUNT(*) FROM LIBRARY_MARTS.JUSTICE.JUSTICE__XC_MAPPING_POLICE_VIOLENCE GROUP BY 1,2,3 HAVING COUNT(*)>1
UNION ALL SELECT 'agency', AGENCY_RESPONSIBLE_FOR_DEATH, STATE, COUNT(*) FROM LIBRARY_MARTS.JUSTICE.JUSTICE__XC_MAPPING_POLICE_VIOLENCE GROUP BY 1,2,3 HAVING COUNT(*)>25
UNION ALL SELECT 'officer', NAMES_OF_OFFICERS_INVOLVED, STATE, COUNT(*) FROM LIBRARY_MARTS.JUSTICE.JUSTICE__XC_MAPPING_POLICE_VIOLENCE WHERE NAMES_OF_OFFICERS_INVOLVED IS NOT NULL AND NAMES_OF_OFFICERS_INVOLVED<>'' GROUP BY 1,2,3 HAVING COUNT(*)>1
UNION ALL SELECT 'officer_nonnull', NULL, NULL, COUNT(*) FROM LIBRARY_MARTS.JUSTICE.JUSTICE__XC_MAPPING_POLICE_VIOLENCE WHERE NAMES_OF_OFFICERS_INVOLVED IS NOT NULL AND NAMES_OF_OFFICERS_INVOLVED<>''
UNION ALL SELECT 'year', YEAR(TRY_TO_DATE(DATE_OF_INCIDENT_MONTH_DAY_YEAR::varchar))::varchar, NULL, COUNT(*) FROM LIBRARY_MARTS.JUSTICE.JUSTICE__XC_MAPPING_POLICE_VIOLENCE GROUP BY 1,2,3;

-- [33] MPV agency -> USAspending assistance recipient (name + state)
WITH a AS (SELECT UPPER(TRIM(AGENCY_RESPONSIBLE_FOR_DEATH)) nm, STATE st, COUNT(*) deaths, MIN(TRY_TO_DATE(DATE_OF_INCIDENT_MONTH_DAY_YEAR::varchar)) first_death
  FROM LIBRARY_MARTS.JUSTICE.JUSTICE__XC_MAPPING_POLICE_VIOLENCE WHERE AGENCY_RESPONSIBLE_FOR_DEATH NOT LIKE '%,%' GROUP BY 1,2),
r AS (SELECT UPPER(TRIM(RECIPIENT_NAME)) nm, RECIPIENT_STATE_CODE st, COUNT(*) n, SUM(FEDERAL_ACTION_OBLIGATION) fao
  FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_USASPENDING_ASSISTANCE_FULL
  WHERE RECIPIENT_NAME ILIKE '%POLICE%' OR RECIPIENT_NAME ILIKE '%SHERIFF%' OR RECIPIENT_NAME ILIKE '%PUBLIC SAFETY%' OR RECIPIENT_NAME ILIKE '%HIGHWAY PATROL%' GROUP BY 1,2)
SELECT COUNT(*) mpv_agencies, SUM(IFF(EXISTS(SELECT 1 FROM r WHERE r.nm=a.nm),1,0)) name_hit,
 SUM(IFF(EXISTS(SELECT 1 FROM r WHERE r.nm=a.nm AND r.st=a.st),1,0)) name_state_hit,
 (SELECT COUNT(*) FROM r) recipient_names,
 (SELECT LISTAGG(x, '; ') FROM (SELECT a2.nm||' '||a2.st||' deaths='||a2.deaths||' grants=$'||ROUND(r2.fao/1e6,1)||'M' x FROM a a2 JOIN r r2 ON r2.nm=a2.nm AND r2.st=a2.st ORDER BY a2.deaths DESC LIMIT 12)) top
FROM a;

-- [34] HMDA respondent -> ARID xref land rate
WITH h AS (SELECT AGENCY_CODE::varchar||REPLACE(RESPONDENT_ID::varchar,'-','') arid, COUNT(*) n FROM LIBRARY_MARTS.HOUSING.HOUSING__FED_CFPB_HMDA_HISTORIC GROUP BY 1),
x AS (SELECT DISTINCT LTRIM(REPLACE(ARID_2017::varchar,'-',''),'0') arid, RESPONDENT_NAME FROM LIBRARY_MARTS.HOUSING.HOUSING__FED_CFPB_HMDA_ARID2017_LEI_XREF)
SELECT COUNT(*) lenders, SUM(IFF(x.arid IS NOT NULL,1,0)) hit, SUM(n) rows_all, SUM(IFF(x.arid IS NOT NULL,n,0)) rows_hit,
 (SELECT LISTAGG(z, '; ') FROM (SELECT h2.arid||'='||COALESCE(x2.RESPONDENT_NAME,'MISS')||' ('||h2.n||')' z FROM h h2 LEFT JOIN x x2 ON LTRIM(h2.arid,'0')=x2.arid ORDER BY h2.n DESC LIMIT 10)) top10
FROM h LEFT JOIN x ON LTRIM(h.arid,'0')=x.arid;

-- [35] FRA crossing -> FRA deaths-by-railroad on name, code agreement; + events per year from DATE
WITH f AS (SELECT RAILROAD_NAME nm, MAX(RAILROAD_CODE) code, COUNT(*) n FROM LIBRARY_MARTS.TRANSPORT.TRANSPORT__FED_FRA_CROSSING_INCIDENTS GROUP BY 1),
d AS (SELECT RAILROAD_NAME nm, MAX(RAILROAD_CODE) code FROM LIBRARY_MARTS.TRANSPORT.TRANSPORT__FED_FRA_RAIL_DEATHS_BY_RAILROAD GROUP BY 1)
SELECT COUNT(*) names, SUM(IFF(d.nm IS NOT NULL,1,0)) name_hit, SUM(IFF(d.code=f.code,1,0)) code_agree, SUM(IFF(d.nm IS NOT NULL,f.n,0))/SUM(f.n) row_share_hit,
 (SELECT LISTAGG(y||':'||c, ' ') WITHIN GROUP (ORDER BY y) FROM (SELECT YEAR(TRY_TO_DATE(DATE::varchar)) y, COUNT(*) c FROM LIBRARY_MARTS.TRANSPORT.TRANSPORT__FED_FRA_CROSSING_INCIDENTS GROUP BY 1)) per_year
FROM f LEFT JOIN d ON UPPER(f.nm)=UPPER(d.nm);

-- [36] FEMA IA duplicate registrations check
SELECT COUNT(*) n, COUNT(DISTINCT REGISTRATION_ID) regs, COUNT(DISTINCT REGISTRATION_ID||'|'||DISASTER_NUMBER) reg_dis, COUNT(DISTINCT _SOURCE_RUN_ID) runs FROM LIBRARY_MARTS.HOUSING.HOUSING__FED_FEMA_IA_HOUSING_REGISTRATIONS;

-- [37] RERUN full text: MPV agency -> USAspending assistance recipient (name + state)
WITH a AS (SELECT UPPER(TRIM(AGENCY_RESPONSIBLE_FOR_DEATH)) nm, STATE st, COUNT(*) deaths, MIN(TRY_TO_DATE(DATE_OF_INCIDENT_MONTH_DAY_YEAR::varchar)) first_death
  FROM LIBRARY_MARTS.JUSTICE.JUSTICE__XC_MAPPING_POLICE_VIOLENCE WHERE AGENCY_RESPONSIBLE_FOR_DEATH NOT LIKE '%,%' GROUP BY 1,2),
r AS (SELECT UPPER(TRIM(RECIPIENT_NAME)) nm, RECIPIENT_STATE_CODE st, COUNT(*) n, SUM(FEDERAL_ACTION_OBLIGATION) fao
  FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_USASPENDING_ASSISTANCE_FULL
  WHERE RECIPIENT_NAME ILIKE '%POLICE%' OR RECIPIENT_NAME ILIKE '%SHERIFF%' OR RECIPIENT_NAME ILIKE '%PUBLIC SAFETY%' OR RECIPIENT_NAME ILIKE '%HIGHWAY PATROL%' GROUP BY 1,2)
SELECT COUNT(*) mpv_agencies, SUM(IFF(EXISTS(SELECT 1 FROM r WHERE r.nm=a.nm),1,0)) name_hit,
 SUM(IFF(EXISTS(SELECT 1 FROM r WHERE r.nm=a.nm AND r.st=a.st),1,0)) name_state_hit,
 (SELECT COUNT(*) FROM r) recipient_names,
 (SELECT LISTAGG(x, '; ') FROM (SELECT a2.nm||' '||a2.st||' deaths='||a2.deaths||' grants=$'||ROUND(r2.fao/1e6,1)||'M' x FROM a a2 JOIN r r2 ON r2.nm=a2.nm AND r2.st=a2.st ORDER BY a2.deaths DESC LIMIT 12)) top
FROM a;

-- [38] RERUN full text: HMDA respondent -> ARID xref land rate
WITH h AS (SELECT AGENCY_CODE::varchar||REPLACE(RESPONDENT_ID::varchar,'-','') arid, COUNT(*) n FROM LIBRARY_MARTS.HOUSING.HOUSING__FED_CFPB_HMDA_HISTORIC GROUP BY 1),
x AS (SELECT DISTINCT LTRIM(REPLACE(ARID_2017::varchar,'-',''),'0') arid, RESPONDENT_NAME FROM LIBRARY_MARTS.HOUSING.HOUSING__FED_CFPB_HMDA_ARID2017_LEI_XREF)
SELECT COUNT(*) lenders, SUM(IFF(x.arid IS NOT NULL,1,0)) hit, SUM(n) rows_all, SUM(IFF(x.arid IS NOT NULL,n,0)) rows_hit,
 (SELECT LISTAGG(z, '; ') FROM (SELECT h2.arid||'='||COALESCE(x2.RESPONDENT_NAME,'MISS')||' ('||h2.n||')' z FROM h h2 LEFT JOIN x x2 ON LTRIM(h2.arid,'0')=x2.arid ORDER BY h2.n DESC LIMIT 10)) top10
FROM h LEFT JOIN x ON LTRIM(h.arid,'0')=x.arid;

-- [39] RERUN full text: FRA crossing -> FRA deaths-by-railroad on name, code agreement; + events per year from DATE
WITH f AS (SELECT RAILROAD_NAME nm, MAX(RAILROAD_CODE) code, COUNT(*) n FROM LIBRARY_MARTS.TRANSPORT.TRANSPORT__FED_FRA_CROSSING_INCIDENTS GROUP BY 1),
d AS (SELECT RAILROAD_NAME nm, MAX(RAILROAD_CODE) code FROM LIBRARY_MARTS.TRANSPORT.TRANSPORT__FED_FRA_RAIL_DEATHS_BY_RAILROAD GROUP BY 1)
SELECT COUNT(*) names, SUM(IFF(d.nm IS NOT NULL,1,0)) name_hit, SUM(IFF(d.code=f.code,1,0)) code_agree, SUM(IFF(d.nm IS NOT NULL,f.n,0))/SUM(f.n) row_share_hit,
 (SELECT LISTAGG(y||':'||c, ' ') WITHIN GROUP (ORDER BY y) FROM (SELECT YEAR(TRY_TO_DATE(DATE::varchar)) y, COUNT(*) c FROM LIBRARY_MARTS.TRANSPORT.TRANSPORT__FED_FRA_CROSSING_INCIDENTS GROUP BY 1)) per_year
FROM f LEFT JOIN d ON UPPER(f.nm)=UPPER(d.nm);

-- [40] ARID xref: how Wells Fargo is keyed
SELECT ARID_2017, RESPONDENT_NAME, LEI_2018 FROM LIBRARY_MARTS.HOUSING.HOUSING__FED_CFPB_HMDA_ARID2017_LEI_XREF WHERE RESPONDENT_NAME ILIKE '%WELLS FARGO%' OR ARID_2017::varchar LIKE '%451965%' LIMIT 10;

-- [41] HMDA respondent -> ARID xref, fixed key (agency || respondent id without leading zeros)
WITH h AS (SELECT AGENCY_CODE::varchar||LTRIM(REPLACE(RESPONDENT_ID::varchar,'-',''),'0') arid, COUNT(*) n FROM LIBRARY_MARTS.HOUSING.HOUSING__FED_CFPB_HMDA_HISTORIC GROUP BY 1),
x AS (SELECT ARID_2017::varchar arid, MAX(RESPONDENT_NAME) RESPONDENT_NAME, COUNT(*) c FROM LIBRARY_MARTS.HOUSING.HOUSING__FED_CFPB_HMDA_ARID2017_LEI_XREF GROUP BY 1)
SELECT COUNT(*) lenders, SUM(IFF(x.arid IS NOT NULL,1,0)) hit, SUM(n) rows_all, SUM(IFF(x.arid IS NOT NULL,n,0)) rows_hit, MAX(x.c) max_xref_dupes,
 (SELECT LISTAGG(z, '; ') FROM (SELECT h2.arid||'='||COALESCE(x2.RESPONDENT_NAME,'MISS')||' ('||h2.n||')' z FROM h h2 LEFT JOIN x x2 ON h2.arid=x2.arid ORDER BY h2.n DESC LIMIT 20)) top20
FROM h LEFT JOIN x ON h.arid=x.arid;

-- [42] CSV:fjc_month FJC IDB linked: cases filed per month
SELECT DATE_TRUNC('month', TRY_TO_DATE(DATE_FILED::varchar)) m, COUNT(*) n, COUNT(DISTINCT NATURE_OF_SUIT) nos, MODE(NATURE_OF_SUIT) top_nos, MODE(DISTRICT_ID) top_district
FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_COURTLISTENER_FJC_IDB_CL_LINKED GROUP BY 1;

-- [43] ICE facility: stints vs detainers per facility code, top 12
WITH s AS (SELECT DETENTION_FACILITY_CODE code, MAX(DETENTION_FACILITY) nm, MAX(STATE) st, COUNT(*) stints, COUNT(FINAL_ORDER_DATE) fo, MIN(FINAL_ORDER_DATE) fo1 FROM LIBRARY_MARTS.IMMIGRATION.IMMIGRATION__FED_ICE_DETENTION_STINTS GROUP BY 1),
d AS (SELECT DETENTION_FACILITY_CODE code, COUNT(*) detainers, MIN(DETAINER_PREPARE_DATE) d1, MAX(DETAINER_PREPARE_DATE) d2 FROM LIBRARY_MARTS.IMMIGRATION.IMMIGRATION__FED_ICE_DETAINERS GROUP BY 1)
SELECT s.code, s.nm, s.st, s.stints, s.fo, d.detainers, d.d1, d.d2,
 (SELECT COUNT(*) FROM s) fac_stints, (SELECT COUNT(*) FROM d) fac_det, (SELECT COUNT(*) FROM s JOIN d USING(code)) fac_both
FROM s LEFT JOIN d ON s.code=d.code ORDER BY s.stints DESC LIMIT 12;

-- [44] FRA top railroad (Union Pacific) -> federal contracts to UNION PACIFIC by FY
SELECT ACTION_DATE_FISCAL_YEAR fy, COUNT(*) n, SUM(FEDERAL_ACTION_OBLIGATION)/1e6 fao_m, LISTAGG(DISTINCT RECIPIENT_NAME, '; ') names
FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_USASPENDING_CONTRACTS_FULL WHERE RECIPIENT_NAME ILIKE 'UNION PACIFIC%' GROUP BY 1 ORDER BY 1;

-- [45] Nursing home: inspection date years + penalties dated after most recent inspection
WITH p AS (SELECT CMS_CERTIFICATION_NUMBER_CCN ccn, PENALTY_DATE, PENALTY_TYPE, TRY_TO_DOUBLE(FINE_AMOUNT::varchar) fine FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_NURSING_HOME_PENALTIES)
SELECT YEAR(n.DATE_OF_MOST_RECENT_HEALTH_INSPECTION) y, COUNT(DISTINCT n.CMS_CERTIFICATION_NUMBER_CCN) homes,
 COUNT(DISTINCT IFF(p.PENALTY_DATE > n.DATE_OF_MOST_RECENT_HEALTH_INSPECTION, n.CMS_CERTIFICATION_NUMBER_CCN, NULL)) homes_pen_after,
 COUNT(DISTINCT IFF(p.PENALTY_DATE <= n.DATE_OF_MOST_RECENT_HEALTH_INSPECTION, n.CMS_CERTIFICATION_NUMBER_CCN, NULL)) homes_pen_before,
 SUM(IFF(p.PENALTY_DATE > n.DATE_OF_MOST_RECENT_HEALTH_INSPECTION, p.fine, 0)) fines_after,
 MIN(p.PENALTY_DATE) p1, MAX(p.PENALTY_DATE) p2, (SELECT COUNT(DISTINCT ccn) FROM p) pen_homes, (SELECT COUNT(*) FROM p WHERE ccn NOT IN (SELECT CMS_CERTIFICATION_NUMBER_CCN FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_NURSING_HOME)) pen_orphans
FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_NURSING_HOME n LEFT JOIN p ON p.ccn=n.CMS_CERTIFICATION_NUMBER_CCN GROUP BY 1 ORDER BY 1;

-- [46] MPV top matched agency (Phoenix PD): deaths by year vs assistance by fiscal year
SELECT 'deaths' k, YEAR(TRY_TO_DATE(DATE_OF_INCIDENT_MONTH_DAY_YEAR::varchar)) y, COUNT(*) v FROM LIBRARY_MARTS.JUSTICE.JUSTICE__XC_MAPPING_POLICE_VIOLENCE WHERE AGENCY_RESPONSIBLE_FOR_DEATH ILIKE 'Phoenix Police Department' GROUP BY 1,2
UNION ALL SELECT 'grants_$', ACTION_DATE_FISCAL_YEAR, ROUND(SUM(FEDERAL_ACTION_OBLIGATION)) FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_USASPENDING_ASSISTANCE_FULL WHERE UPPER(TRIM(RECIPIENT_NAME))='PHOENIX POLICE DEPARTMENT' AND RECIPIENT_STATE_CODE='AZ' GROUP BY 1,2
ORDER BY 1,2;

-- [47] Nursing home: raw inspection-date values (is the event date empty?)
SELECT DATE_OF_MOST_RECENT_HEALTH_INSPECTION d, COUNT(*) n, MIN(RATING_CYCLE_1_STANDARD_SURVEY_HEALTH_DATE::varchar) c1_min, MAX(RATING_CYCLE_1_STANDARD_SURVEY_HEALTH_DATE::varchar) c1_max, COUNT(RATING_CYCLE_1_STANDARD_SURVEY_HEALTH_DATE) c1_nn, MAX(PROCESSING_DATE::varchar) proc
FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_NURSING_HOME GROUP BY 1 ORDER BY 2 DESC LIMIT 5;

-- [48] ICE bond-set share per stay, by state of the facility where the stay ended (stay level, not stint level)
WITH st AS (SELECT STAY_ID, MAX_BY(STATE, BOOK_OUT_AT) end_state, MAX(IFF(INITIAL_BOND_SET_AMOUNT IS NOT NULL,1,0)) bond_set, MAX(IFF(BOND_POSTED_AMOUNT IS NOT NULL,1,0)) bond_posted,
  MEDIAN(INITIAL_BOND_SET_AMOUNT) bond_amt, MAX(IFF(DETENTION_FACILITY ILIKE '%STAGING%' OR DETENTION_FACILITY ILIKE '%HOLD ROOM%',1,0)) staging
  FROM LIBRARY_MARTS.IMMIGRATION.IMMIGRATION__FED_ICE_DETENTION_STINTS WHERE YEAR(STAY_BOOK_IN_AT) BETWEEN 2023 AND 2025 GROUP BY 1)
SELECT end_state, COUNT(*) stays, AVG(bond_set) bond_set_share, AVG(bond_posted) bond_posted_share, MEDIAN(bond_amt) med_bond, AVG(staging) touched_staging
FROM st GROUP BY 1 HAVING COUNT(*)>=5000 ORDER BY bond_set_share;

-- [49] Nursing home: cycle-1 survey date as the event; penalties before/after, top home by fines after
WITH n AS (SELECT CMS_CERTIFICATION_NUMBER_CCN ccn, TRY_TO_DATE(RATING_CYCLE_1_STANDARD_SURVEY_HEALTH_DATE::varchar) sd, OVERALL_RATING, CHAIN_NAME FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_NURSING_HOME),
p AS (SELECT CMS_CERTIFICATION_NUMBER_CCN ccn, TRY_TO_DATE(PENALTY_DATE::varchar) pd, TRY_TO_DOUBLE(FINE_AMOUNT::varchar) fine FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_NURSING_HOME_PENALTIES),
j AS (SELECT n.ccn, n.sd, n.CHAIN_NAME, SUM(IFF(p.pd>n.sd,1,0)) pen_after, SUM(IFF(p.pd<=n.sd,1,0)) pen_before, SUM(IFF(p.pd>n.sd,p.fine,0)) fine_after, MIN(IFF(p.pd>n.sd,p.pd-n.sd,NULL)) lag_days
  FROM n LEFT JOIN p ON p.ccn=n.ccn GROUP BY 1,2,3)
SELECT YEAR(sd) y, COUNT(*) homes, SUM(IFF(pen_after>0,1,0)) homes_after, SUM(IFF(pen_before>0,1,0)) homes_before, SUM(fine_after) fines_after, MEDIAN(lag_days) med_lag,
 (SELECT LISTAGG(z,'; ') FROM (SELECT ccn||' '||COALESCE(CHAIN_NAME,'-')||' $'||ROUND(fine_after)||' n='||pen_after z FROM j ORDER BY fine_after DESC NULLS LAST LIMIT 5)) top5
FROM j GROUP BY 1 ORDER BY 1;

