{{ config(tags=['spine_generated']) }}

-- GRAIN: one row per place (GEOM is unique)
-- SPINE_ENTITY: place  (natural_key: GEOMETRY)
-- Generated by scripts/generate_staging_models.py from SOURCE_REGISTRY -- deterministic,
-- no LLM. Casts kept as landed (TEXT) -- add explicit type casts by hand once each
-- column's real type is confirmed; this generator has no semantic type knowledge.
-- spine_entity 'place' has no connect/ resolver yet (see connect/spine_entity.py) -- no SPINE_ENTITY_ID emitted.
-- landing table's ingestion timestamp is named INGESTED_AT (no leading underscore) rather than the usual _INGESTED_AT -- confirmed via INFORMATION_SCHEMA, not assumed.

with source as (

    select * from {{ source('ripple_raw', 'PORTAL_CKA_WESTERN_PENNSYLV_654E0B3182') }}

),

renamed as (

    select
        "GLOBALID" as globalid,
        "OBJECTID" as objectid,
        "SHAPE__AREA" as shape__area,
        "SHAPE__LENGTH" as shape__length,
        "CORRECTIONLABEL" as correctionlabel,
        "CREATED_DATE" as created_date,
        "CREATED_USER" as created_user,
        "FULL_ZONING_TYPE" as full_zoning_type,
        "LAST_EDITED_DATE" as last_edited_date,
        "LAST_EDITED_USER" as last_edited_user,
        "LEGENDTYPE" as legendtype,
        "MUNICODE" as municode,
        "PERIMETER" as perimeter,
        "PGHDB_SDE_ZONING_AREA" as pghdb_sde_zoning_area,
        "SHAPE_LENG" as shape_leng,
        "STATUS" as status,
        "ZON_NEW" as zon_new,
        "ZONING" as zoning,
        "ZONING_ID" as zoning_id,
        "GEOMETRY" as geometry,
        INGESTED_AT as _loaded_at,
        'https://data.wprdc.org/dataset/zoning' as _source_url

    from source

)

select * from renamed
qualify row_number() over (partition by geometry order by _loaded_at desc) = 1
