{{ config(tags=['spine_generated']) }}

-- GRAIN: one row per record (spine_entity not determined -- no registry hint available) (UNIQUE_ID unique)
-- SPINE_ENTITY: (not determined)  (natural_key: UNIQUE_ID)
-- Generated by scripts/generate_staging_models.py from SOURCE_REGISTRY -- deterministic,
-- no LLM.
-- CASTS: none of 28 columns. landing_column_profile_2026-09-19.tsv found no TEXT column where
-- every filled value parsed as a number, date or boolean.
-- spine_entity not determined (grain/natural_key proven, but no registry hint says what this row is ABOUT) -- no SPINE_ENTITY_ID emitted.
-- landing table's ingestion timestamp is named INGESTED_AT (no leading underscore) rather than the usual _INGESTED_AT -- confirmed via INFORMATION_SCHEMA, not assumed.

with source as (

    select * from {{ source('ripple_raw', 'PORTAL_ARC_OPEN_DATA_DC_E1DD5D3551') }}
    qualify row_number() over (partition by "UNIQUE_ID" order by INGESTED_AT desc) = 1

),

renamed as (

    select
        {{ null_junk('"FID"') }} as fid,
        {{ null_junk('"OBJECTID"') }} as objectid,
        {{ null_junk('"NAME"') }} as name,
        {{ null_junk('"PROPOSED"') }} as proposed,
        {{ null_junk('"CITY"') }} as city,
        {{ null_junk('"STATE"') }} as state,
        {{ null_junk('"ZIP_CODE"') }} as zip_code,
        {{ null_junk('"COUNTRY"') }} as country,
        {{ null_junk('"LATITUDE"') }} as latitude,
        {{ null_junk('"LONGITUDE"') }} as longitude,
        {{ null_junk('"DESC"') }} as desc,
        {{ null_junk('"NUM_LINES"') }} as num_lines,
        {{ null_junk('"FLOWGATE"') }} as flowgate,
        {{ null_junk('"MIN_VOLT"') }} as min_volt,
        {{ null_junk('"MAX_VOLT"') }} as max_volt,
        {{ null_junk('"AVG_LOAD"') }} as avg_load,
        {{ null_junk('"AVG_OUTPUT"') }} as avg_output,
        {{ null_junk('"NAICS_CODE"') }} as naics_code,
        {{ null_junk('"NAICS_DESC"') }} as naics_desc,
        {{ null_junk('"SIC_CODE"') }} as sic_code,
        {{ null_junk('"POSIT_REL"') }} as posit_rel,
        {{ null_junk('"SOURCE"') }} as source,
        {{ null_junk('"SOURCEDATE"') }} as sourcedate,
        {{ null_junk('"UNIQUE_ID"') }} as unique_id,
        {{ null_junk('"FEAT_TYPE"') }} as feat_type,
        {{ null_junk('"IN_DOEE_MG"') }} as in_doee_mg,
        {{ null_junk('"CONSEQUENC"') }} as consequenc,
        {{ null_junk('"GEOMETRY"') }} as geometry,
        INGESTED_AT as _loaded_at,
        'https://opendata.dc.gov/datasets/ea77ed7da37f45ae9ec9447b8e854de4_0' as _source_url

    from source

)

select * from renamed
