{{ config(tags=['spine_generated']) }}

-- GRAIN: one row per organization (EIN+AUDIT_CLOSED_DATE+NAME+AUDIT_TYPE unique)
-- SPINE_ENTITY: organization  (natural_key: UBI_EIN, AUDIT_CLOSED_DATE, RECIPIENT_TYPE, AUDIT_TYPE)
-- Generated by scripts/generate_staging_models.py from SOURCE_REGISTRY -- deterministic,
-- no LLM.
-- CASTS: 1 of 7 columns, from landing_column_profile_2026-09-19.tsv. A column is cast only
-- when every filled value in the sample parsed. try_ casts: a value that does not
-- parse reads NULL. The natural key and join-key columns stay TEXT.
--   audit_received_or_conducted: timestamp
-- spine_entity 'organization' has no connect/ resolver yet (see connect/spine_entity.py) -- no SPINE_ENTITY_ID emitted.
-- landing table's ingestion timestamp is named INGESTED_AT (no leading underscore) rather than the usual _INGESTED_AT -- confirmed via INFORMATION_SCHEMA, not assumed.
-- DEDUPE: registry natural_key (UBI_EIN, AUDIT_CLOSED_DATE, RECIPIENT_TYPE, AUDIT_TYPE) is NOT unique within a load as landed at generation time -- it would collapse 2 of 112 rows. Deduping on the WHOLE ROW instead (exact copies only). A record that changes between loads shows once per version. Find the real key, fix SOURCE_REGISTRY, regenerate.

with source as (

    select * from {{ source('ripple_raw', 'PORTAL_SOC_WASHINGTON_STATE_1A95FB1665') }}
    qualify row_number() over (partition by "AUDIT_CONTROL_NUMBER", "RECIPIENT_NAME", "RECIPIENT_TYPE", "AUDIT_TYPE", "AUDIT_RECEIVED_OR_CONDUCTED", "AUDIT_CLOSED_DATE", "UBI_EIN" order by INGESTED_AT desc) = 1

),

renamed as (

    select
        {{ null_junk('"AUDIT_CONTROL_NUMBER"') }} as audit_control_number,
        {{ null_junk('"RECIPIENT_NAME"') }} as recipient_name,
        {{ null_junk('"RECIPIENT_TYPE"') }} as recipient_type,
        {{ null_junk('"AUDIT_TYPE"') }} as audit_type,
        {{ stg_ts('"AUDIT_RECEIVED_OR_CONDUCTED"') }} as audit_received_or_conducted,
        {{ null_junk('"AUDIT_CLOSED_DATE"') }} as audit_closed_date,
        {{ null_junk('"UBI_EIN"') }} as ubi_ein,
        INGESTED_AT as _loaded_at,
        'https://data.wa.gov/d/ncqf-syud' as _source_url

    from source

)

select * from renamed
