{{ config(tags=['spine_generated']) }}

-- GRAIN: one row per place (GEOM is unique)
-- SPINE_ENTITY: place  (natural_key: GEOMETRY)
-- Generated by scripts/generate_staging_models.py from SOURCE_REGISTRY -- deterministic,
-- no LLM.
-- CASTS: 1 of 6 columns, from landing_column_profile_2026-09-19.tsv. A column is cast only
-- when every filled value in the sample parsed. try_ casts: a value that does not
-- parse reads NULL. The natural key and join-key columns stay TEXT.
--   objectid: ID: whole numbers, over 90% distinct -- stays TEXT, '.0' tail removed
-- spine_entity 'place' has no connect/ resolver yet (see connect/spine_entity.py) -- no SPINE_ENTITY_ID emitted.
-- landing table's ingestion timestamp is named INGESTED_AT (no leading underscore) rather than the usual _INGESTED_AT -- confirmed via INFORMATION_SCHEMA, not assumed.

with source as (

    select * from {{ source('ripple_raw', 'PORTAL_CKA_WPRDC_ALLEGHENY_4F79FA2E0C') }}
    qualify row_number() over (partition by "GEOMETRY" order by INGESTED_AT desc) = 1

),

renamed as (

    select
        {{ null_junk('"AREA_NAME"') }} as area_name,
        {{ stg_id_text('"OBJECTID"') }} as objectid,
        {{ null_junk('"RENEWAL_TYPE"') }} as renewal_type,
        {{ null_junk('"SHAPE_AREA"') }} as shape_area,
        {{ null_junk('"SHAPE_LENGTH"') }} as shape_length,
        {{ null_junk('"GEOMETRY"') }} as geometry,
        INGESTED_AT as _loaded_at,
        'https://data.wprdc.org/dataset/pgh-development-1969-1974' as _source_url

    from source

)

select * from renamed
