-- S01 CDC WONDER: pull all 880 rows
SELECT * FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CDC_WONDER;

-- S02 VA suicide national: pull all 690 rows
SELECT * FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_VA_SUICIDE_NATIONAL;

-- S03 CDC drug poisoning county: pull all 53K rows
SELECT * FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CDC_DRUG_POISONING_COUNTY;

-- S04 Medicare outpatient by provider and service: pull all 116K rows
SELECT * FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_MEDICARE_OUTPATIENT_HOSPITALS_BY_PROVIDER_AND_SERVICE;

-- S05 Hospital general: type, ownership, stars for every CCN
SELECT CCN, FACILITY_NAME, CITY_TOWN, STATE, HOSPITAL_TYPE, HOSPITAL_OWNERSHIP, HOSPITAL_OVERALL_RATING
        FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_HOSPITAL_GENERAL;

-- S06 HCRIS cost-to-charge and outpatient charges by fiscal year, CCNs in the outpatient file, FY2016+
WITH op AS (SELECT DISTINCT RNDRNG_PRVDR_CCN AS CCN FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_MEDICARE_OUTPATIENT_HOSPITALS_BY_PROVIDER_AND_SERVICE)
        SELECT h.PROVIDER_CCN, h.FISCAL_YEAR_BEGIN_DATE, h.FISCAL_YEAR_END_DATE, h.RPT_REC_NUM, h.TYPE_OF_CONTROL, h.PROVIDER_TYPE,
               h.NUMBER_OF_BEDS, h.COST_TO_CHARGE_RATIO, h.OUTPATIENT_TOTAL_CHARGES, h.INPATIENT_TOTAL_CHARGES,
               h.COMBINED_OUTPATIENT_INPATIENT_TOTAL_CHARGES, h.TOTAL_COSTS, h.NET_PATIENT_REVENUE
        FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_HCRIS h JOIN op ON op.CCN = h.PROVIDER_CCN
        WHERE TRY_TO_DATE(h.FISCAL_YEAR_END_DATE::STRING) >= '2016-01-01';

-- S07 POS: first-participation and termination dates for CCNs in the outpatient file (carbon date)
WITH op AS (SELECT DISTINCT RNDRNG_PRVDR_CCN AS CCN FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_MEDICARE_OUTPATIENT_HOSPITALS_BY_PROVIDER_AND_SERVICE)
        SELECT p.CCN, p.FAC_NAME, p.ORGNL_PRTCPTN_DT, p.CRTFCTN_DT, p.TRMNTN_EXPRTN_DT, p.PGM_TRMNTN_CD, p.CHOW_DT
        FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_POS_OTHER p JOIN op ON op.CCN = p.CCN;

-- S08 CDC injury county: all Drug_OD rows (FIPS join target for 2019-2024)
SELECT GEOID, NAME, PERIOD, ST_NAME, INTENT, COUNT_SUP, RATE, RATE_M
        FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CDC_INJURY_VIOLENCE_COUNTY WHERE INTENT = 'Drug_OD';

-- S09 PECOS profile: keys, enrollment-id date parse, flags
SELECT COUNT(*) n, COUNT(DISTINCT NPI) npis, COUNT(DISTINCT ENRLMT_ID) enrl_ids, COUNT(DISTINCT PECOS_ASCT_CNTL_ID) pac_ids,
               COUNT_IF(NPI IS NULL OR TRIM(NPI) = '') npi_blank, COUNT_IF(LENGTH(NPI) <> 10) npi_not10,
               COUNT_IF(LEFT(ENRLMT_ID,1) = 'I') enrl_I, COUNT_IF(LEFT(ENRLMT_ID,1) = 'O') enrl_O,
               COUNT_IF(TRY_TO_DATE(SUBSTR(ENRLMT_ID,2,8),'YYYYMMDD') IS NULL) enrl_date_bad,
               MIN(TRY_TO_DATE(SUBSTR(ENRLMT_ID,2,8),'YYYYMMDD')) enrl_d0, MAX(TRY_TO_DATE(SUBSTR(ENRLMT_ID,2,8),'YYYYMMDD')) enrl_d1,
               COUNT_IF(MULTIPLE_NPI_FLAG = 'Y') multi_y, COUNT(DISTINCT STATE_CD) states,
               COUNT_IF(ORG_NAME IS NOT NULL AND TRIM(ORG_NAME) <> '') org_rows,
               COUNT(DISTINCT _SOURCE_RUN_ID) runs, MIN(_INGESTED_AT)::STRING ing0, MAX(_INGESTED_AT)::STRING ing1
        FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_PECOS_PROVIDER_ENROLLMENT;

-- S10 PECOS profile (retry of S09 without lineage columns): keys, enrollment-id date parse, flags
SELECT COUNT(*) n, COUNT(DISTINCT NPI) npis, COUNT(DISTINCT ENRLMT_ID) enrl_ids, COUNT(DISTINCT PECOS_ASCT_CNTL_ID) pac_ids,
               COUNT_IF(NPI IS NULL OR TRIM(NPI) = '') npi_blank, COUNT_IF(LENGTH(NPI) <> 10) npi_not10,
               COUNT_IF(LEFT(ENRLMT_ID,1) = 'I') enrl_I, COUNT_IF(LEFT(ENRLMT_ID,1) = 'O') enrl_O,
               COUNT_IF(TRY_TO_DATE(SUBSTR(ENRLMT_ID,2,8),'YYYYMMDD') IS NULL) enrl_date_bad,
               MIN(TRY_TO_DATE(SUBSTR(ENRLMT_ID,2,8),'YYYYMMDD')) enrl_d0, MAX(TRY_TO_DATE(SUBSTR(ENRLMT_ID,2,8),'YYYYMMDD')) enrl_d1,
               COUNT_IF(MULTIPLE_NPI_FLAG = 'Y') multi_y, COUNT(DISTINCT STATE_CD) states,
               COUNT_IF(ORG_NAME IS NOT NULL AND TRIM(ORG_NAME) <> '') org_rows
        FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_PECOS_PROVIDER_ENROLLMENT;

-- S11 PECOS: enrollments by provider type, state and enrollment-id year
SELECT PROVIDER_TYPE_CD, PROVIDER_TYPE_DESC, STATE_CD,
               YEAR(TRY_TO_DATE(SUBSTR(ENRLMT_ID,2,8),'YYYYMMDD')) yr, LEFT(ENRLMT_ID,1) kind,
               COUNT(*) n, COUNT(DISTINCT NPI) npis
        FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_PECOS_PROVIDER_ENROLLMENT GROUP BY 1,2,3,4,5;

-- S12 PECOS high-risk org enrollments -> NPPES practice address; addresses stacking 4+ new (2023+) enrollments
WITH p AS (
          SELECT NPI, ENRLMT_ID, PROVIDER_TYPE_CD, PROVIDER_TYPE_DESC, STATE_CD, ORG_NAME,
                 TRY_TO_DATE(SUBSTR(ENRLMT_ID,2,8),'YYYYMMDD') d
          FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_PECOS_PROVIDER_ENROLLMENT
          WHERE LEFT(ENRLMT_ID,1) = 'O' AND (PROVIDER_TYPE_CD LIKE '30-%' OR PROVIDER_TYPE_CD IN ('12-69','00-08','00-06','12-59','12-47','12-A5','12-D6','12-D5','12-63','12-73','53-D1','12-31'))),
        n AS (
          SELECT NPI,
                 UPPER(REGEXP_REPLACE(PROVIDER_FIRST_LINE_BUSINESS_PRACTICE_LOCATION_ADDRESS,'[^A-Za-z0-9]','')) a1,
                 UPPER(TRIM(PROVIDER_SECOND_LINE_BUSINESS_PRACTICE_LOCATION_ADDRESS)) a2,
                 LEFT(PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_POSTAL_CODE,5) z,
                 UPPER(PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_CITY_NAME) city,
                 PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_STATE_NAME st,
                 UPPER(AUTHORIZED_OFFICIAL_LAST_NAME || ', ' || AUTHORIZED_OFFICIAL_FIRST_NAME) ao,
                 PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_TELEPHONE_NUMBER tel
          FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_NPPES WHERE NPI IN (SELECT NPI FROM p))
        SELECT n.a1, n.z, ANY_VALUE(n.city) city, ANY_VALUE(n.st) st,
               COUNT(DISTINCT p.NPI) npis_all,
               COUNT(DISTINCT IFF(p.d >= '2023-01-01', p.NPI, NULL)) npis_new,
               COUNT(DISTINCT IFF(p.d >= '2023-01-01', p.ORG_NAME, NULL)) orgs_new,
               COUNT(DISTINCT IFF(p.d >= '2023-01-01', n.ao, NULL)) officials_new,
               COUNT(DISTINCT IFF(p.d >= '2023-01-01', n.a2, NULL)) suites_new,
               COUNT(DISTINCT IFF(p.d >= '2023-01-01', n.tel, NULL)) phones_new,
               ARRAY_AGG(DISTINCT IFF(p.d >= '2023-01-01', p.PROVIDER_TYPE_DESC, NULL)) types_new,
               ARRAY_SLICE(ARRAY_AGG(DISTINCT IFF(p.d >= '2023-01-01', p.ORG_NAME, NULL)), 0, 12) names_new,
               ARRAY_SLICE(ARRAY_AGG(DISTINCT IFF(p.d >= '2023-01-01', n.ao, NULL)), 0, 12) aos_new,
               ARRAY_SLICE(ARRAY_AGG(DISTINCT IFF(p.d >= '2023-01-01', p.NPI, NULL)), 0, 40) npi_list_new,
               MIN(p.d) d0, MAX(p.d) d1
        FROM p JOIN n ON n.NPI = p.NPI
        GROUP BY n.a1, n.z
        HAVING COUNT(DISTINCT IFF(p.d >= '2023-01-01', p.NPI, NULL)) >= 3
        ORDER BY npis_new DESC;

-- S13 PECOS ambulance suppliers (12-59), every state -> NPPES address/official + Part B by-provider money
WITH p AS (
          SELECT NPI, STATE_CD, ORG_NAME, ENRLMT_ID, TRY_TO_DATE(SUBSTR(ENRLMT_ID,2,8),'YYYYMMDD') d, MULTIPLE_NPI_FLAG
          FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_PECOS_PROVIDER_ENROLLMENT WHERE PROVIDER_TYPE_CD = '12-59'),
        n AS (
          SELECT NPI,
                 UPPER(PROVIDER_FIRST_LINE_BUSINESS_PRACTICE_LOCATION_ADDRESS) addr,
                 UPPER(PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_CITY_NAME) city,
                 LEFT(PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_POSTAL_CODE,5) zip5,
                 UPPER(AUTHORIZED_OFFICIAL_LAST_NAME || ', ' || AUTHORIZED_OFFICIAL_FIRST_NAME) ao,
                 PROVIDER_ENUMERATION_DATE enum_dt
          FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_NPPES WHERE NPI IN (SELECT NPI FROM p)),
        b AS (
          SELECT RNDRNG_NPI, RNDRNG_PRVDR_TYPE, TOT_BENES, TOT_SRVCS, TOT_MDCR_ALOWD_AMT, TOT_MDCR_PYMT_AMT
          FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_MEDICARE_PHYSICIAN_OTHER_PRACTITIONERS_BY_PROVIDER WHERE RNDRNG_NPI IN (SELECT NPI FROM p))
        SELECT p.NPI, p.STATE_CD, p.ORG_NAME, p.ENRLMT_ID, p.d, p.MULTIPLE_NPI_FLAG,
               n.addr, n.city, n.zip5, n.ao, n.enum_dt,
               b.RNDRNG_PRVDR_TYPE, b.TOT_BENES, b.TOT_SRVCS, b.TOT_MDCR_ALOWD_AMT, b.TOT_MDCR_PYMT_AMT
        FROM p LEFT JOIN n ON n.NPI = p.NPI LEFT JOIN b ON b.RNDRNG_NPI = p.NPI;

-- S14 HCRIS FY2023 resident FTEs and beds for outpatient-file CCNs (academic peer group)
WITH op AS (SELECT DISTINCT RNDRNG_PRVDR_CCN AS CCN FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_MEDICARE_OUTPATIENT_HOSPITALS_BY_PROVIDER_AND_SERVICE)
        SELECT h.PROVIDER_CCN, MAX(h.NUMBER_OF_INTERNS_AND_RESIDENTS_FTE) AS residents_fte, MAX(h.NUMBER_OF_BEDS) AS beds
        FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_HCRIS h JOIN op ON op.CCN = h.PROVIDER_CCN
        WHERE YEAR(TRY_TO_DATE(h.FISCAL_YEAR_END_DATE::STRING)) = 2023
        GROUP BY h.PROVIDER_CCN;

