from q import run
M = "LIBRARY_MARTS.HEALTH."
P = f"{M}HEALTH__FED_CMS_PECOS_PROVIDER_ENROLLMENT"
N = f"{M}HEALTH__FED_CMS_NPPES"
B = f"{M}HEALTH__FED_CMS_MEDICARE_PHYSICIAN_OTHER_PRACTITIONERS_BY_PROVIDER"
run("S13", "PECOS ambulance suppliers (12-59), every state -> NPPES address/official + Part B by-provider money",
    f"""WITH p AS (
          SELECT NPI, STATE_CD, ORG_NAME, ENRLMT_ID, TRY_TO_DATE(SUBSTR(ENRLMT_ID,2,8),'YYYYMMDD') d, MULTIPLE_NPI_FLAG
          FROM {P} WHERE PROVIDER_TYPE_CD = '12-59'),
        n AS (
          SELECT NPI,
                 UPPER(PROVIDER_FIRST_LINE_BUSINESS_PRACTICE_LOCATION_ADDRESS) addr,
                 UPPER(PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_CITY_NAME) city,
                 LEFT(PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_POSTAL_CODE,5) zip5,
                 UPPER(AUTHORIZED_OFFICIAL_LAST_NAME || ', ' || AUTHORIZED_OFFICIAL_FIRST_NAME) ao,
                 PROVIDER_ENUMERATION_DATE enum_dt
          FROM {N} WHERE NPI IN (SELECT NPI FROM p)),
        b AS (
          SELECT RNDRNG_NPI, RNDRNG_PRVDR_TYPE, TOT_BENES, TOT_SRVCS, TOT_MDCR_ALOWD_AMT, TOT_MDCR_PYMT_AMT
          FROM {B} WHERE RNDRNG_NPI IN (SELECT NPI FROM p))
        SELECT p.NPI, p.STATE_CD, p.ORG_NAME, p.ENRLMT_ID, p.d, p.MULTIPLE_NPI_FLAG,
               n.addr, n.city, n.zip5, n.ao, n.enum_dt,
               b.RNDRNG_PRVDR_TYPE, b.TOT_BENES, b.TOT_SRVCS, b.TOT_MDCR_ALOWD_AMT, b.TOT_MDCR_PYMT_AMT
        FROM p LEFT JOIN n ON n.NPI = p.NPI LEFT JOIN b ON b.RNDRNG_NPI = p.NPI""")
