from q import run
M = "LIBRARY_MARTS.HEALTH."
OP = f"{M}HEALTH__FED_CMS_MEDICARE_OUTPATIENT_HOSPITALS_BY_PROVIDER_AND_SERVICE"
run("S14", "HCRIS FY2023 resident FTEs and beds for outpatient-file CCNs (academic peer group)",
    f"""WITH op AS (SELECT DISTINCT RNDRNG_PRVDR_CCN AS CCN FROM {OP})
        SELECT h.PROVIDER_CCN, MAX(h.NUMBER_OF_INTERNS_AND_RESIDENTS_FTE) AS residents_fte, MAX(h.NUMBER_OF_BEDS) AS beds
        FROM {M}HEALTH__FED_CMS_HCRIS h JOIN op ON op.CCN = h.PROVIDER_CCN
        WHERE YEAR(TRY_TO_DATE(h.FISCAL_YEAR_END_DATE::STRING)) = 2023
        GROUP BY h.PROVIDER_CCN""")
