{{ config(tags=['spine_generated']) }}

-- GRAIN: one row per place (ZIP+DATE_FILE+LEBA_PUBLICATION_DATE+NAAL_LEBA_PUBLICATION_DATE+ENTITY_LOGICAL_ID+NAAL_LOGICAL_ID+ENTITY_LOGICAL_ID_1+ENTITY_LOGICAL_ID_2+BIRT_LOGICAL_ID+ENTITY_LOGICAL_ID_3+IDEN_LOGICAL_ID+ENTITY_LOGICAL_ID_4+CITI_LOGICAL_ID+ENTITY_LOGICAL_ID_5 unique)
-- SPINE_ENTITY: place  (natural_key: ADDR_ZIPCODE, DATE_FILE, LEBA_PUBLICATION_DATE, NAAL_LEBA_PUBLICATION_DATE, ENTITY_LOGICAL_ID, NAAL_LOGICAL_ID, ENTITY_LOGICAL_ID_1, ENTITY_LOGICAL_ID_2, BIRT_LOGICAL_ID, ENTITY_LOGICAL_ID_3, IDEN_LOGICAL_ID, ENTITY_LOGICAL_ID_4, CITI_LOGICAL_ID, ENTITY_LOGICAL_ID_5)
-- Generated by scripts/generate_staging_models.py from SOURCE_REGISTRY -- deterministic,
-- no LLM. Casts kept as landed (TEXT) -- add explicit type casts by hand once each
-- column's real type is confirmed; this generator has no semantic type knowledge.
-- spine_entity 'place' has no connect/ resolver yet (see connect/spine_entity.py) -- no SPINE_ENTITY_ID emitted.
-- DEDUPE: registry natural_key (ADDR_ZIPCODE, DATE_FILE, LEBA_PUBLICATION_DATE, NAAL_LEBA_PUBLICATION_DATE, ENTITY_LOGICAL_ID, NAAL_LOGICAL_ID, ENTITY_LOGICAL_ID_1, ENTITY_LOGICAL_ID_2, BIRT_LOGICAL_ID, ENTITY_LOGICAL_ID_3, IDEN_LOGICAL_ID, ENTITY_LOGICAL_ID_4, CITI_LOGICAL_ID, ENTITY_LOGICAL_ID_5) is NOT unique within a load as landed at generation time -- it would collapse 490 of 42,347 rows. Deduping on the WHOLE ROW instead (exact copies only). A record that changes between loads shows once per version. Find the real key, fix SOURCE_REGISTRY, regenerate.

with source as (

    select * from {{ source('ripple_raw', 'INTL_EU_SANCTIONS') }}

),

renamed as (

    select
        "DATE_FILE" as date_file,
        "ENTITY_LOGICAL_ID" as entity_logical_id,
        "SUBJECT_TYPE" as subject_type,
        "LEBA_NUMTITLE" as leba_numtitle,
        "LEBA_PUBLICATION_DATE" as leba_publication_date,
        "LEBA_URL" as leba_url,
        "PROGRAMME" as programme,
        "ENTITY_REMARK" as entity_remark,
        "NAAL_LOGICAL_ID" as naal_logical_id,
        "ENTITY_LOGICAL_ID_1" as entity_logical_id_1,
        "NAAL_LEBA_NUMTITLE" as naal_leba_numtitle,
        "NAAL_LEBA_PUBLICATION_DATE" as naal_leba_publication_date,
        "NAAL_LEBA_URL" as naal_leba_url,
        "NAAL_PROGRAMME" as naal_programme,
        "NAAL_LASTNAME" as naal_lastname,
        "NAAL_FIRSTNAME" as naal_firstname,
        "NAAL_MIDDLENAME" as naal_middlename,
        "NAAL_WHOLENAME" as naal_wholename,
        "NAAL_GENDER" as naal_gender,
        "NAAL_TITLE" as naal_title,
        "NAAL_FUNCTION" as naal_function,
        "NAAL_LANGUAGE" as naal_language,
        "ADDR_LOGICAL_ID" as addr_logical_id,
        "ENTITY_LOGICAL_ID_2" as entity_logical_id_2,
        "ADDR_LEBA_NUMTITLE" as addr_leba_numtitle,
        "ADDR_LEBA_PUBLICATION_DATE" as addr_leba_publication_date,
        "ADDR_LEBA_URL" as addr_leba_url,
        "ADDR_PROGRAMME" as addr_programme,
        "ADDR_NUMBER" as addr_number,
        "ADDR_STREET" as addr_street,
        "ADDR_ZIPCODE" as addr_zipcode,
        "ADDR_CITY" as addr_city,
        "ADDR_COUNTRY" as addr_country,
        "ADDR_OTHER" as addr_other,
        "BIRT_LOGICAL_ID" as birt_logical_id,
        "ENTITY_LOGICAL_ID_3" as entity_logical_id_3,
        "BIRT_LEBA_NUMTITLE" as birt_leba_numtitle,
        "BIRT_LEBA_PUBLICATION_DATE" as birt_leba_publication_date,
        "BIRT_LEBA_URL" as birt_leba_url,
        "BIRT_PROGRAMME" as birt_programme,
        "BIRT_DATE" as birt_date,
        "BIRT_PLACE" as birt_place,
        "BIRT_COUNTRY" as birt_country,
        "IDEN_LOGICAL_ID" as iden_logical_id,
        "ENTITY_LOGICAL_ID_4" as entity_logical_id_4,
        "IDEN_LEBA_NUMTITLE" as iden_leba_numtitle,
        "IDEN_LEBA_PUBLICATION_DATE" as iden_leba_publication_date,
        "IDEN_LEBA_URL" as iden_leba_url,
        "IDEN_PROGRAMME" as iden_programme,
        "IDEN_NUMBER" as iden_number,
        "IDEN_COUNTRY" as iden_country,
        "CITI_LOGICAL_ID" as citi_logical_id,
        "ENTITY_LOGICAL_ID_5" as entity_logical_id_5,
        "CITI_LEBA_NUMTITLE" as citi_leba_numtitle,
        "CITI_LEBA_PUBLICATION_DATE" as citi_leba_publication_date,
        "CITI_LEBA_URL" as citi_leba_url,
        "CITI_PROGRAMME" as citi_programme,
        "CITI_COUNTRY" as citi_country,
        "EU_REF_NUM" as eu_ref_num,
        _INGESTED_AT as _loaded_at,
        'https://data.europa.eu/data/datasets/consolidated-list-of-persons-groups-and-entities-subject-to-eu-financial-sanctions?locale=en' as _source_url

    from source

)

select * from renamed
qualify row_number() over (partition by date_file, entity_logical_id, subject_type, leba_numtitle, leba_publication_date, leba_url, programme, entity_remark, naal_logical_id, entity_logical_id_1, naal_leba_numtitle, naal_leba_publication_date, naal_leba_url, naal_programme, naal_lastname, naal_firstname, naal_middlename, naal_wholename, naal_gender, naal_title, naal_function, naal_language, addr_logical_id, entity_logical_id_2, addr_leba_numtitle, addr_leba_publication_date, addr_leba_url, addr_programme, addr_number, addr_street, addr_zipcode, addr_city, addr_country, addr_other, birt_logical_id, entity_logical_id_3, birt_leba_numtitle, birt_leba_publication_date, birt_leba_url, birt_programme, birt_date, birt_place, birt_country, iden_logical_id, entity_logical_id_4, iden_leba_numtitle, iden_leba_publication_date, iden_leba_url, iden_programme, iden_number, iden_country, citi_logical_id, entity_logical_id_5, citi_leba_numtitle, citi_leba_publication_date, citi_leba_url, citi_programme, citi_country, eu_ref_num order by _loaded_at desc) = 1
