{{ config(materialized='view', schema='TIMELINE', alias='POLITICS__TX_LOBBY_FOOD_BEVERAGE') }}

-- GENERATED by scripts/census/gen_time_views.py -- do not hand-edit.
-- Regenerate after any change to reports/time_index/clock_index.csv.
--
-- Canonical clock for POLITICS.POLITICS__TX_LOBBY_FOOD_BEVERAGE.
--   column : ACTIVITYDATE   (DATE)
--   means  : happened -- try_to_date(ACTIVITYDATE,'YYYYMMDD') — the day the meal was bought for the state official; the true event clock.
--   grain  : day
--
-- The original columns pass through untouched; the canonical four sit in front
-- of them. Rule 8 of the datetime standard: the raw column is never overwritten,
-- so a mis-parse is always recoverable.

select
    {{ ripple_event_ts(ripple_window('src."ACTIVITYDATE"::timestamp_ntz')) }} as ripple_ts,
    {{ ripple_grain('day') }} as ripple_grain,
    {{ ripple_clock('happened') }} as ripple_clock,
    'POLITICS.POLITICS__TX_LOBBY_FOOD_BEVERAGE'::varchar as ripple_source,
    src.*
from {{ ref('politics__tx_lobby_food_beverage') }} as src
