{{ config(materialized='view', schema='TIMELINE', alias='POLITICS__CA_LOBBY_CHG_LOG') }}

-- GENERATED by scripts/census/gen_time_views.py -- do not hand-edit.
-- Regenerate after any change to reports/time_index/clock_index.csv.
--
-- Canonical clock for POLITICS.POLITICS__CA_LOBBY_CHG_LOG.
--   column : EFFECT_DT   (DATE)
--   means  : happened -- MM/DD/YYYY date for when the logged attribute change takes effect — the truer real-world clock than log_dt, but I could not verify its fill rate with the wareho
--   grain  : day
--
-- happened cannot be in the future -- if this row's value is, ripple_clock
-- reads 'planned' instead, not 'happened'. See ripple_row_clock in
-- macros/ripple_time.sql.
--
-- The original columns pass through untouched; the canonical four sit in front
-- of them. Rule 8 of the datetime standard: the raw column is never overwritten,
-- so a mis-parse is always recoverable.

select
    {{ ripple_window('src."EFFECT_DT"::timestamp_ntz') }} as ripple_ts,
    {{ ripple_grain('day') }} as ripple_grain,
    {{ ripple_row_clock(ripple_window('src."EFFECT_DT"::timestamp_ntz'), 'happened') }} as ripple_clock,
    'POLITICS.POLITICS__CA_LOBBY_CHG_LOG'::varchar as ripple_source,
    src.*
from {{ ref('politics__ca_lobby_chg_log') }} as src
