{{ config(materialized='view', schema='TIMELINE', alias='POLITICS__FED_MEDSL_SENATE_RETURNS') }}

-- GENERATED by scripts/census/gen_time_views.py -- do not hand-edit.
-- Regenerate after any change to reports/time_index/clock_index.csv.
--
-- Canonical clock for POLITICS.POLITICS__FED_MEDSL_SENATE_RETURNS.
--   column : ELECTION_YEAR   (NUMBER)
--   means  : happened -- Year the Senate election was held; try_to_number(year) integer.
--   grain  : year
--
-- The original columns pass through untouched; the canonical four sit in front
-- of them. Rule 8 of the datetime standard: the raw column is never overwritten,
-- so a mis-parse is always recoverable.

select
    {{ ripple_event_ts(ripple_ts_from_year('src."ELECTION_YEAR"')) }} as ripple_ts,
    {{ ripple_grain('year') }} as ripple_grain,
    {{ ripple_clock('happened') }} as ripple_clock,
    'POLITICS.POLITICS__FED_MEDSL_SENATE_RETURNS'::varchar as ripple_source,
    src.*
from {{ ref('politics__fed_medsl_senate_returns') }} as src
