{{ config(tags=['spine_generated']) }}

-- GRAIN: one row per record (spine_entity not determined -- no registry hint available) (ACTIVITY_ID unique)
-- SPINE_ENTITY: (not determined)  (natural_key: ACTIVITY_ID)
-- Generated by scripts/generate_staging_models.py from SOURCE_REGISTRY -- deterministic,
-- no LLM. Casts kept as landed (TEXT) -- add explicit type casts by hand once each
-- column's real type is confirmed; this generator has no semantic type knowledge.
-- spine_entity not determined (grain/natural_key proven, but no registry hint says what this row is ABOUT) -- no SPINE_ENTITY_ID emitted.

with source as (

    select * from {{ source('ripple_raw', 'FED_EPA_ICIS_FEC_ICIS_FEC_EPA_INSPECTIONS') }}

),

renamed as (

    select
        "REGISTRY_ID" as registry_id,
        "PGM_SYS_ACRNM" as pgm_sys_acrnm,
        "PGM_SYS_ID" as pgm_sys_id,
        "FACILITY_NAME" as facility_name,
        "EPA_REGION_CODE" as epa_region_code,
        "ACTIVITY_ID" as activity_id,
        "ACTIVITY_TYPE_CODE" as activity_type_code,
        "ACTIVITY_TYPE_DESC" as activity_type_desc,
        "COMP_MONITOR_UID" as comp_monitor_uid,
        "COMP_MONITOR_TYPES" as comp_monitor_types,
        "STATUTE_CODE" as statute_code,
        "LAW_SECTION_CODE" as law_section_code,
        "ACTUAL_BEGIN_DATE" as actual_begin_date,
        "ACTUAL_END_DATE" as actual_end_date,
        "AGENCY" as agency,
        "COMP_MONITOR_AGENCY_TYPES" as comp_monitor_agency_types,
        _INGESTED_AT as _loaded_at,
        '' as _source_url

    from source

)

select * from renamed
qualify row_number() over (partition by activity_id order by _loaded_at desc) = 1
