-- FEC bulk vs the three other committee-master tables: is it the same rows as one cycle? (duplicate-load trap check)
WITH b AS (SELECT FEC_CMTE_ID id, UPPER(TRIM(CMTE_NM)) nm, UPPER(TRIM(TRES_NM)) tr, CMTE_FILING_FREQ ff FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_FEC_BULK)
, p AS (SELECT CYCLE, CMTE_ID id, UPPER(TRIM(CMTE_NM)) nm, UPPER(TRIM(TRES_NM)) tr, CMTE_FILING_FREQ ff FROM LIBRARY_MARTS.POLITICS.POLITICS__FEC_COMMITTEE)
, f AS (SELECT CYCLE, FEC_CMTE_ID id, UPPER(TRIM(CMTE_NM)) nm, UPPER(TRIM(TRES_NM)) tr, CMTE_FILING_FREQ ff FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_FEC_BULK_COMMITTEES)
, c AS (SELECT CMTE_ID id, UPPER(TRIM(CMTE_NM)) nm, UPPER(TRIM(TRES_NM)) tr, CMTE_FILING_FREQ ff FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_FEC_COMMITTEES)
SELECT 'POLITICS__FEC_COMMITTEE' other, p.CYCLE::varchar cyc, (SELECT COUNT(*) FROM p p2 WHERE p2.CYCLE = p.CYCLE) other_rows, COUNT(*) id_hits,
       COUNT_IF(EQUAL_NULL(b.nm, p.nm) AND EQUAL_NULL(b.tr, p.tr) AND EQUAL_NULL(b.ff, p.ff)) same_nm_tr_ff
FROM b JOIN p ON b.id = p.id GROUP BY p.CYCLE
UNION ALL
SELECT 'FINANCE__FED_FEC_BULK_COMMITTEES', f.CYCLE::varchar, (SELECT COUNT(*) FROM f f2 WHERE f2.CYCLE = f.CYCLE), COUNT(*),
       COUNT_IF(EQUAL_NULL(b.nm, f.nm) AND EQUAL_NULL(b.tr, f.tr) AND EQUAL_NULL(b.ff, f.ff))
FROM b JOIN f ON b.id = f.id GROUP BY f.CYCLE
UNION ALL
SELECT 'FINANCE__FED_FEC_COMMITTEES', 'n/a', (SELECT COUNT(*) FROM c), COUNT(*),
       COUNT_IF(EQUAL_NULL(b.nm, c.nm) AND EQUAL_NULL(b.tr, c.tr) AND EQUAL_NULL(b.ff, c.ff))
FROM b JOIN c ON b.id = c.id
ORDER BY 1, 2
