-- FEC bulk vs the three other committee-master tables: is it the same rows as one cycle? (duplicate-load trap check)
WITH b AS (SELECT FEC_CMTE_ID id, UPPER(TRIM(CMTE_NM)) nm, UPPER(TRIM(TRES_NM)) tr, CMTE_FILING_FREQ ff FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_FEC_BULK)
, o AS (
  SELECT 'POLITICS__FEC_COMMITTEE' src, CYCLE::varchar cyc, CMTE_ID id, UPPER(TRIM(CMTE_NM)) nm, UPPER(TRIM(TRES_NM)) tr, CMTE_FILING_FREQ ff FROM LIBRARY_MARTS.POLITICS.POLITICS__FEC_COMMITTEE
  UNION ALL SELECT 'FINANCE__FED_FEC_BULK_COMMITTEES', CYCLE::varchar, FEC_CMTE_ID, UPPER(TRIM(CMTE_NM)), UPPER(TRIM(TRES_NM)), CMTE_FILING_FREQ FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_FEC_BULK_COMMITTEES
  UNION ALL SELECT 'FINANCE__FED_FEC_COMMITTEES', 'n/a', CMTE_ID, UPPER(TRIM(CMTE_NM)), UPPER(TRIM(TRES_NM)), CMTE_FILING_FREQ FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_FEC_COMMITTEES)
SELECT o.src, o.cyc, COUNT(*) other_rows, COUNT(b.id) id_hits,
       COUNT_IF(b.id IS NOT NULL AND EQUAL_NULL(b.nm, o.nm) AND EQUAL_NULL(b.tr, o.tr) AND EQUAL_NULL(b.ff, o.ff)) same_nm_tr_ff
FROM o LEFT JOIN b ON b.id = o.id
GROUP BY 1, 2 ORDER BY 1, 2
