-- SEC derivative trades: size, key uniqueness, whole-row duplicates, date junk, code mix, self-reported late flag
WITH t AS (SELECT *, COALESCE(TRY_TO_DATE(TRANS_DATE::varchar, 'DD-MON-YYYY'), TRY_TO_DATE(TRANS_DATE::varchar)) td,
                  HASH(ACCESSION_NUMBER, SECURITY_TITLE, TRANS_DATE, TRANS_CODE, TRANS_SHARES, CONV_EXERCISE_PRICE, TRANS_PRICEPERSHARE, TRANS_ACQUIRED_DISP_CD, EXPIRATION_DATE, UNDLYNG_SEC_SHARES, SHRS_OWND_FOLWNG_TRANS, DIRECT_INDIRECT_OWNERSHIP) h
           FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_INSIDER_DERIV_TRANS)
SELECT COUNT(*) n, COUNT(DISTINCT ACCESSION_NUMBER) filings, COUNT(DISTINCT DERIV_TRANS_SK) sks, COUNT(DISTINCT ACCESSION_NUMBER, DERIV_TRANS_SK) acc_sk,
       COUNT(DISTINCT h) distinct_content,
       COUNT_IF(td IS NULL AND NULLIF(TRIM(TRANS_DATE::varchar),'') IS NOT NULL) date_unparsed, COUNT_IF(NULLIF(TRIM(TRANS_DATE::varchar),'') IS NULL) date_blank,
       MIN(td) d0, MAX(td) d1, COUNT_IF(YEAR(td) < 2000) pre2000, COUNT_IF(td > '2026-09-24') future,
       APPROX_TOP_K(YEAR(td), 12) years, APPROX_TOP_K(TRANS_CODE, 15) codes, APPROX_TOP_K(TRANS_FORM_TYPE, 5) forms,
       APPROX_TOP_K(TRANS_TIMELINESS, 5) timeliness, APPROX_TOP_K(EQUITY_SWAP_INVOLVED, 5) swap
FROM t
