-- SEC deriv: the line-level detail behind the 10 issuers with the most late option-award lines at a 50%+ late rate (read the rows; stock-dividend adjustment or a real award?)
WITH s AS (SELECT ACCESSION_NUMBER, COALESCE(TRY_TO_DATE(FILING_DATE::varchar, 'DD-MON-YYYY'), TRY_TO_DATE(FILING_DATE::varchar)) fd, DOCUMENT_TYPE,
                  TRY_TO_NUMBER(ISSUER_CIK::varchar) cik, ISSUER_NAME, REMARKS
           FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_INSIDER_SUBMISSION
           WHERE TRY_TO_NUMBER(ISSUER_CIK::varchar) IN (318673, 1397047, 1260968, 930775, 1580149, 1045942, 1360565, 894871, 1368637, 87802))
, o AS (SELECT ACCESSION_NUMBER, LISTAGG(DISTINCT OWNER_NAME || ' (' || COALESCE(RELATIONSHIP,'') || ')', '; ') owners
        FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_INSIDER_REPORTINGOWNER WHERE ACCESSION_NUMBER IN (SELECT ACCESSION_NUMBER FROM s) GROUP BY 1)
SELECT s.cik, s.ISSUER_NAME, s.DOCUMENT_TYPE, s.fd, d.ACCESSION_NUMBER,
       COALESCE(TRY_TO_DATE(d.TRANS_DATE::varchar, 'DD-MON-YYYY'), TRY_TO_DATE(d.TRANS_DATE::varchar)) td, d.TRANS_CODE, d.TRANS_TIMELINESS,
       d.SECURITY_TITLE, d.CONV_EXERCISE_PRICE, d.TRANS_SHARES, d.TRANS_PRICEPERSHARE, d.TRANS_ACQUIRED_DISP_CD, d.EXCERCISE_DATE, d.EXPIRATION_DATE,
       d.UNDLYNG_SEC_SHARES, d.SHRS_OWND_FOLWNG_TRANS, o.owners, LEFT(s.REMARKS, 300) remarks
FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_INSIDER_DERIV_TRANS d JOIN s ON s.ACCESSION_NUMBER = d.ACCESSION_NUMBER
LEFT JOIN o ON o.ACCESSION_NUMBER = d.ACCESSION_NUMBER
ORDER BY s.cik, td
