-- SEC deriv: eyeball the option-award lines for 5 repeat-late issuers (Celsius, AgEagle, theMaven, Medicine Man/Schwazze, ESSA): owner, trade date, first filing date, price, shares
WITH s AS (SELECT ACCESSION_NUMBER, COALESCE(TRY_TO_DATE(FILING_DATE::varchar, 'DD-MON-YYYY'), TRY_TO_DATE(FILING_DATE::varchar)) fd, DOCUMENT_TYPE,
                  TRY_TO_NUMBER(ISSUER_CIK::varchar) cik, ISSUER_NAME
           FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_INSIDER_SUBMISSION WHERE TRY_TO_NUMBER(ISSUER_CIK::varchar) IN (1341766, 8504, 894871, 1622879, 1633932))
, o AS (SELECT ACCESSION_NUMBER, MAX(OWNER_NAME) owner, MAX(RELATIONSHIP) rel, MAX(TITLE) title FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_INSIDER_REPORTINGOWNER
        WHERE ACCESSION_NUMBER IN (SELECT ACCESSION_NUMBER FROM s) GROUP BY 1)
SELECT s.cik, s.ISSUER_NAME, o.owner, o.rel, o.title, COALESCE(TRY_TO_DATE(d.TRANS_DATE::varchar, 'DD-MON-YYYY'), TRY_TO_DATE(d.TRANS_DATE::varchar)) td,
       MIN(s.fd) first_fd, COUNT(*) lines, MAX(d.CONV_EXERCISE_PRICE) px, MAX(d.TRANS_SHARES) shares, MAX(d.EXPIRATION_DATE) exp, MAX(d.SECURITY_TITLE) ttl, MAX(d.TRANS_TIMELINESS) timeliness
FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_INSIDER_DERIV_TRANS d JOIN s ON s.ACCESSION_NUMBER = d.ACCESSION_NUMBER LEFT JOIN o ON o.ACCESSION_NUMBER = d.ACCESSION_NUMBER
WHERE d.TRANS_CODE = 'A' AND TRY_TO_DOUBLE(d.CONV_EXERCISE_PRICE::varchar) > 0 AND s.DOCUMENT_TYPE IN ('4','5')
GROUP BY 1, 2, 3, 4, 5, 6 ORDER BY 1, 6
