-- S01 BORME: every row, all 15
SELECT * FROM LIBRARY_MARTS.CORPORATE_REGISTRY.CORPORATE_REGISTRY__INTL_ES_BORME;

-- S02 FHFA NMDB: fill of the statistic columns, period shapes, duplicate keys
SELECT PERIOD_TYPE, COUNT(*) n, COUNT(DISTINCT GEO_CODE) geos, MIN(PERIOD_VALUE) p0, MAX(PERIOD_VALUE) p1,
       COUNT(DISTINCT PERIOD_VALUE) periods, COUNT(DISTINCT GEO_CODE, PERIOD_VALUE) keys,
       COUNT(STATISTIC_VALUE) stat_val_nonnull, COUNT(NULLIF(TRIM(STATISTIC_NAME),'')) stat_name_nonblank,
       COUNT(NULLIF(TRIM(STATISTIC_UNIT),'')) stat_unit_nonblank, COUNT(NULLIF(TRIM(DATASET_FAMILY),'')) fam_nonblank,
       COUNT(NULLIF(TRIM(GEO_TYPE),'')) geotype_nonblank, MIN(RELEASE_DATE) r0, MAX(RELEASE_DATE) r1,
       ARRAY_AGG(DISTINCT GEO_NAME) WITHIN GROUP (ORDER BY GEO_NAME) geo_names
FROM LIBRARY_MARTS.HOUSING.HOUSING__FED_FHFA_NMDB
GROUP BY 1 ORDER BY 1;

-- S03 ICIJ others: by leak, fill of every field, date range, id uniqueness
SELECT SOURCE_LEAK, COUNT(*) n, COUNT(DISTINCT NODE_ID) nodes, COUNT(INCORPORATION_DATE) inc, MIN(INCORPORATION_DATE) inc0, MAX(INCORPORATION_DATE) inc1,
       COUNT(STRUCK_OFF_DATE) struck, COUNT(CLOSED_DATE) closed, COUNT(NULLIF(TRIM(JURISDICTION),'')) jur, COUNT(NULLIF(TRIM(TYPE),'')) typ,
       COUNT(NULLIF(TRIM(COUNTRY_CODES),'')) cc, COUNT_IF(COUNTRY_CODES ILIKE '%USA%') usa, COUNT(NULLIF(TRIM(NOTE),'')) note,
       ARRAY_AGG(DISTINCT VALID_UNTIL) valid_until
FROM LIBRARY_MARTS.CORPORATE_REGISTRY.CORPORATE_REGISTRY__FED_ICIJ_OFFSHORELEAKS_OTHERS
GROUP BY ROLLUP(1) ORDER BY n DESC;

-- S04 ICIJ addresses: by leak, US share, blank names, duplicate address text, notes
SELECT SOURCE_LEAK, COUNT(*) n, COUNT(DISTINCT NODE_ID) nodes, COUNT(DISTINCT UPPER(TRIM(ADDRESS))) addr_text,
       COUNT_IF(COUNTRY_CODES ILIKE '%USA%') usa, COUNT_IF(COUNTRY_CODES = 'USA') usa_only,
       COUNT_IF(NAME IS NULL OR TRIM(NAME) IN ('','None')) name_blank, COUNT_IF(ADDRESS IS NULL OR TRIM(ADDRESS) IN ('','None')) addr_blank,
       COUNT_IF(COUNTRY_CODES IS NULL OR TRIM(COUNTRY_CODES) IN ('','XXX')) cc_blank, COUNT(NULLIF(TRIM(NOTE),'')) note,
       ARRAY_AGG(DISTINCT VALID_UNTIL) valid_until
FROM LIBRARY_MARTS.CORPORATE_REGISTRY.CORPORATE_REGISTRY__FED_ICIJ_OFFSHORELEAKS_ADDRESSES
GROUP BY ROLLUP(1) ORDER BY n DESC;

-- S05 ICIJ relationships: edge types and what sits at each end (address, officer, entity, intermediary, other)
WITH k AS (
  SELECT NODE_ID, 'address' kind FROM LIBRARY_MARTS.CORPORATE_REGISTRY.CORPORATE_REGISTRY__FED_ICIJ_OFFSHORELEAKS_ADDRESSES
  UNION ALL SELECT NODE_ID, 'officer' FROM LIBRARY_MARTS.CORPORATE_REGISTRY.CORPORATE_REGISTRY__FED_ICIJ_OFFSHORELEAKS_OFFICERS
  UNION ALL SELECT NODE_ID, 'entity' FROM LIBRARY_MARTS.CORPORATE_REGISTRY.CORPORATE_REGISTRY__FED_ICIJ_OFFSHORELEAKS_ENTITIES
  UNION ALL SELECT NODE_ID, 'intermediary' FROM LIBRARY_MARTS.CORPORATE_REGISTRY.CORPORATE_REGISTRY__FED_ICIJ_OFFSHORELEAKS_INTERMEDIARIES
  UNION ALL SELECT NODE_ID, 'other' FROM LIBRARY_MARTS.CORPORATE_REGISTRY.CORPORATE_REGISTRY__FED_ICIJ_OFFSHORELEAKS_OTHERS
), kk AS (SELECT NODE_ID, MIN(kind) kind, COUNT(*) dup FROM k GROUP BY 1)
SELECT r.REL_TYPE, s.kind start_kind, e.kind end_kind, COUNT(*) n, COUNT(DISTINCT r.NODE_ID_END) end_nodes,
       COUNT_IF(s.dup > 1 OR e.dup > 1) id_in_two_tables
FROM LIBRARY_MARTS.CORPORATE_REGISTRY.CORPORATE_REGISTRY__FED_ICIJ_OFFSHORELEAKS_RELATIONSHIPS r
LEFT JOIN kk s ON s.NODE_ID = r.NODE_ID_START
LEFT JOIN kk e ON e.NODE_ID = r.NODE_ID_END
GROUP BY 1,2,3 HAVING COUNT(*) >= 200 ORDER BY n DESC;

-- S06 HUD projects: vintage, programs, sentinels, id shape, duplicate codes
SELECT QUARTER, PROGRAM_LABEL, COUNT(*) n, COUNT(DISTINCT CODE) codes, SUM(IFF(TOTAL_UNITS > 0, TOTAL_UNITS, 0)) units,
       COUNT_IF(PCT_OCCUPIED < 0) occ_neg, COUNT_IF(SPENDING_PER_MONTH < 0) spend_neg, COUNT_IF(HH_INCOME < 0) inc_neg,
       COUNT_IF(TRY_TO_NUMBER(MONTHS_WAITING) < 0) wait_neg, COUNT_IF(TRY_TO_NUMBER(MONTHS_WAITING) >= 0) wait_ok,
       COUNT_IF(PCT_REPORTED < 0) rep_neg, MEDIAN(IFF(PCT_REPORTED >= 0, PCT_REPORTED, NULL)) med_rep,
       MEDIAN(IFF(PCT_OCCUPIED >= 0, PCT_OCCUPIED, NULL)) med_occ, MEDIAN(IFF(SPENDING_PER_MONTH >= 0, SPENDING_PER_MONTH, NULL)) med_spend,
       ANY_VALUE(CODE) code_eg, ANY_VALUE(ENTITIES) ent_eg, ARRAY_AGG(DISTINCT SUB_PROGRAM) subs, COUNT(NULLIF(TRIM(STD_ADDR),'')) addr, COUNT(NULLIF(TRIM(STD_ZIP5),'')) zip
FROM LIBRARY_MARTS.HOUSING.HOUSING__FED_HUD_ASSISTED_HOUSING_PROJECTS
GROUP BY 1,2 ORDER BY n DESC;
