-- S07 HUD projects: pull the whole table (35.6K rows) for local peer math
SELECT * FROM LIBRARY_MARTS.HOUSING.HOUSING__FED_HUD_ASSISTED_HOUSING_PROJECTS;

-- S08 HUD housing authorities: status, size, vacancy, money, for the public-housing join
SELECT PARTICIPANT_CODE, FORMAL_PARTICIPANT_NAME, PHAS_DESIGNATION, HA_PROGRAM_TYPE, HA_COMBINED_SIZE_CATEGORY, HA_LOW_RENT_SIZE_CATEGORY,
       TOTAL_UNITS, TOTAL_DWELLING_UNITS, ACC_UNITS, PUBLIC_HOUSING_OCCUPIED, SECTION8_OCCUPIED, TOTAL_OCCUPIED, PCT_OCCUPIED, REGULAR_VACANT,
       PHA_TOTAL_UNITS, NUMBER_REPORTED, PCT_REPORTED, OPERATING_FUND_AMOUNT, OPERATING_FUND_AMOUNT_PREV_YR, CAPITAL_FUND_AMOUNT,
       CAPITAL_FUND_AMOUNT_PREV_YR, SPENDING_PER_MONTH, ANNUAL_EXPENSE_AMOUNT, STD_STATE, STD_CITY, CBSA_CODE, CBSA_NAME, LAST_UPDATED_AT
FROM LIBRARY_MARTS.HOUSING.HOUSING__FED_HUD_PUBLIC_HOUSING_AUTHORITIES;

-- S09 HUD Section 8 contracts: property id, expiry, units, rent-to-FMR, for the project join
SELECT CONTRACT_NUMBER, PROPERTY_ID, PROPERTY_NAME, TRACS_EFFECTIVE_DATE, TRACS_OVERALL_EXPIRATION_DATE, TRACS_CURRENT_EXPIRATION_DATE,
       TRACS_STATUS_NAME, PROGRAM_TYPE_NAME, PROGRAM_TYPE_GROUP_NAME, ASSISTED_UNITS_COUNT, RENT_TO_FMR_RATIO, CONTRACT_TERM_MONTHS_QTY
FROM LIBRARY_MARTS.HOUSING.HOUSING__FED_HUD_MF_SECTION8_CONTRACTS;

-- S10 ICIJ: every node tied to a US address (via registered_address), plus US-coded officers/intermediaries with no US address
WITH us_addr AS (
  SELECT NODE_ID, NULLIF(TRIM(ADDRESS),'') a1, NULLIF(TRIM(NAME),'') a2
  FROM LIBRARY_MARTS.CORPORATE_REGISTRY.CORPORATE_REGISTRY__FED_ICIJ_OFFSHORELEAKS_ADDRESSES
  WHERE COUNTRY_CODES ILIKE '%USA%'
), ra AS (
  SELECT NODE_ID_START, NODE_ID_END FROM LIBRARY_MARTS.CORPORATE_REGISTRY.CORPORATE_REGISTRY__FED_ICIJ_OFFSHORELEAKS_RELATIONSHIPS
  WHERE REL_TYPE = 'registered_address'
), nodes AS (
  SELECT NODE_ID, 'officer' kind, NAME, COUNTRY_CODES, SOURCE_LEAK FROM LIBRARY_MARTS.CORPORATE_REGISTRY.CORPORATE_REGISTRY__FED_ICIJ_OFFSHORELEAKS_OFFICERS
  UNION ALL SELECT NODE_ID, 'entity', NAME, COUNTRY_CODES, SOURCE_LEAK FROM LIBRARY_MARTS.CORPORATE_REGISTRY.CORPORATE_REGISTRY__FED_ICIJ_OFFSHORELEAKS_ENTITIES
  UNION ALL SELECT NODE_ID, 'intermediary', NAME, COUNTRY_CODES, SOURCE_LEAK FROM LIBRARY_MARTS.CORPORATE_REGISTRY.CORPORATE_REGISTRY__FED_ICIJ_OFFSHORELEAKS_INTERMEDIARIES
  UNION ALL SELECT NODE_ID, 'other', NAME, COUNTRY_CODES, SOURCE_LEAK FROM LIBRARY_MARTS.CORPORATE_REGISTRY.CORPORATE_REGISTRY__FED_ICIJ_OFFSHORELEAKS_OTHERS
), via_addr AS (
  SELECT n.NODE_ID, n.kind, n.NAME, n.COUNTRY_CODES, n.SOURCE_LEAK, a.NODE_ID addr_node, COALESCE(a.a1, a.a2) addr_text
  FROM us_addr a JOIN ra ON ra.NODE_ID_END = a.NODE_ID JOIN nodes n ON n.NODE_ID = ra.NODE_ID_START
), via_code AS (
  SELECT n.NODE_ID, n.kind, n.NAME, n.COUNTRY_CODES, n.SOURCE_LEAK, NULL addr_node, NULL addr_text
  FROM nodes n
  WHERE n.COUNTRY_CODES ILIKE '%USA%' AND n.kind IN ('officer','intermediary')
    AND n.NODE_ID NOT IN (SELECT NODE_ID FROM via_addr)
), unlinked AS (
  SELECT NULL NODE_ID, 'address_only' kind, NULL NAME, NULL COUNTRY_CODES, NULL SOURCE_LEAK, a.NODE_ID addr_node, COALESCE(a.a1, a.a2) addr_text
  FROM us_addr a WHERE a.NODE_ID NOT IN (SELECT NODE_ID_END FROM ra)
)
SELECT * FROM via_addr UNION ALL SELECT * FROM via_code UNION ALL SELECT * FROM unlinked;

-- S11 OIG exclusion list (LEIE): names and addresses for the ICIJ match
SELECT LAST_NAME, FIRST_NAME, MIDDLE_NAME, BUSINESS_NAME, GENERAL_CATEGORY, SPECIALTY, EXCLUSION_TYPE, EXCLUSION_DATE, REINSTATEMENT_DATE,
       ADDRESS, CITY, STATE, ZIP, IS_ENTITY_NOT_INDIVIDUAL, NPI
FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_HHS_OIG_LEIE;

-- S12 SAM exclusions: names and places for the ICIJ match
SELECT SAM_NUMBER, ENTITY_NAME, FIRST_NAME, LAST_NAME, CLASSIFICATION, EXCLUSION_TYPE, EXCLUSION_PROGRAM, EXCLUDING_AGENCY,
       ACTIVATION_DATE, TERMINATION_DATE_RAW, CITY, STATE, ZIP, COUNTRY, IS_CURRENTLY_EXCLUDED, IS_ENTITY_NOT_INDIVIDUAL
FROM LIBRARY_MARTS.PROCUREMENT.PROCUREMENT__FED_SAM_EXCLUSIONS;

-- S13 ICIJ others: whole table plus how many edges touch each node
WITH e AS (
  SELECT NODE_ID_START nid, REL_TYPE FROM LIBRARY_MARTS.CORPORATE_REGISTRY.CORPORATE_REGISTRY__FED_ICIJ_OFFSHORELEAKS_RELATIONSHIPS
  UNION ALL SELECT NODE_ID_END, REL_TYPE FROM LIBRARY_MARTS.CORPORATE_REGISTRY.CORPORATE_REGISTRY__FED_ICIJ_OFFSHORELEAKS_RELATIONSHIPS
), c AS (SELECT nid, COUNT(*) edges, LISTAGG(DISTINCT REL_TYPE, '|') rels FROM e GROUP BY 1)
SELECT o.*, c.edges, c.rels
FROM LIBRARY_MARTS.CORPORATE_REGISTRY.CORPORATE_REGISTRY__FED_ICIJ_OFFSHORELEAKS_OTHERS o LEFT JOIN c ON c.nid = o.NODE_ID;

-- S14 FHFA suspended counterparties and FDIC enforcement orders: names for the ICIJ match
SELECT 'FHFA' src, TRIM(COALESCE(FIRST_NAME,'') || ' ' || COALESCE(LAST_NAME,'')) person, COMPANY org, CITY, STATE,
       TO_VARCHAR(EFFECTIVE_DATE) dt, NULL amt, SUSPENSION_ORDER doc
FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_FHFA_SUSPENDED_COUNTERPARTIES
UNION ALL
SELECT 'FDIC', RESPONDENTS, INSTITUTION_NAME, CITY, STATE, TO_VARCHAR(ORDER_DATE), CMP_AMOUNT_TOTAL, DOCUMENT_URL
FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_FDIC_ENFORCEMENT_ORDERS;
