-- S15 ICIJ: the offshore companies behind the 4 people who match the OIG exclusion list on name plus address or ZIP, with edge dates
WITH ids AS (
  SELECT column1 nid FROM VALUES ('240380892'),('240380893'),('240380894'),('116682'),('50374'),('116538'),('43492'),('292103'),('51081'),
                                 ('116734'),('56635'),('59489'),('110260'),('113850'),('171052')
), e AS (
  SELECT r.NODE_ID_START a, r.NODE_ID_END b, r.REL_TYPE, r.LINK, r.STATUS, r.START_DATE, r.END_DATE, r.SOURCE_LEAK
  FROM LIBRARY_MARTS.CORPORATE_REGISTRY.CORPORATE_REGISTRY__FED_ICIJ_OFFSHORELEAKS_RELATIONSHIPS r
  WHERE r.NODE_ID_START IN (SELECT nid FROM ids) OR r.NODE_ID_END IN (SELECT nid FROM ids)
)
SELECT e.a, COALESCE(oa.NAME, ia.NAME, ea.NAME) a_name, e.REL_TYPE, e.LINK, e.STATUS rel_status, e.START_DATE, e.END_DATE,
       e.b, COALESCE(en.NAME, ob.NAME, ib.NAME, ad.ADDRESS) b_name, en.JURISDICTION_DESCRIPTION, en.COMPANY_TYPE, en.INCORPORATION_DATE,
       en.INACTIVATION_DATE, en.STRUCK_OFF_DATE, en.STATUS ent_status, en.SERVICE_PROVIDER, e.SOURCE_LEAK
FROM e
LEFT JOIN LIBRARY_MARTS.CORPORATE_REGISTRY.CORPORATE_REGISTRY__FED_ICIJ_OFFSHORELEAKS_OFFICERS oa ON oa.NODE_ID = e.a
LEFT JOIN LIBRARY_MARTS.CORPORATE_REGISTRY.CORPORATE_REGISTRY__FED_ICIJ_OFFSHORELEAKS_INTERMEDIARIES ia ON ia.NODE_ID = e.a
LEFT JOIN LIBRARY_MARTS.CORPORATE_REGISTRY.CORPORATE_REGISTRY__FED_ICIJ_OFFSHORELEAKS_ENTITIES ea ON ea.NODE_ID = e.a
LEFT JOIN LIBRARY_MARTS.CORPORATE_REGISTRY.CORPORATE_REGISTRY__FED_ICIJ_OFFSHORELEAKS_ENTITIES en ON en.NODE_ID = e.b
LEFT JOIN LIBRARY_MARTS.CORPORATE_REGISTRY.CORPORATE_REGISTRY__FED_ICIJ_OFFSHORELEAKS_OFFICERS ob ON ob.NODE_ID = e.b
LEFT JOIN LIBRARY_MARTS.CORPORATE_REGISTRY.CORPORATE_REGISTRY__FED_ICIJ_OFFSHORELEAKS_INTERMEDIARIES ib ON ib.NODE_ID = e.b
LEFT JOIN LIBRARY_MARTS.CORPORATE_REGISTRY.CORPORATE_REGISTRY__FED_ICIJ_OFFSHORELEAKS_ADDRESSES ad ON ad.NODE_ID = e.b
ORDER BY e.a, e.REL_TYPE, e.b;
