-- S16 ICIJ denominator: people at US addresses, by leak and by the kind of offshore vehicle they sit on (how many hold Cook Islands asset-protection trusts)
WITH us_addr AS (
  SELECT NODE_ID FROM LIBRARY_MARTS.CORPORATE_REGISTRY.CORPORATE_REGISTRY__FED_ICIJ_OFFSHORELEAKS_ADDRESSES WHERE COUNTRY_CODES ILIKE '%USA%'
), ppl AS (
  SELECT DISTINCT r.NODE_ID_START pid
  FROM LIBRARY_MARTS.CORPORATE_REGISTRY.CORPORATE_REGISTRY__FED_ICIJ_OFFSHORELEAKS_RELATIONSHIPS r
  JOIN us_addr a ON a.NODE_ID = r.NODE_ID_END
  WHERE r.REL_TYPE = 'registered_address'
    AND r.NODE_ID_START NOT IN (SELECT NODE_ID FROM LIBRARY_MARTS.CORPORATE_REGISTRY.CORPORATE_REGISTRY__FED_ICIJ_OFFSHORELEAKS_ENTITIES)
), links AS (
  SELECT p.pid, en.NODE_ID eid, en.SOURCE_LEAK, en.JURISDICTION_DESCRIPTION jur, en.COMPANY_TYPE, en.SERVICE_PROVIDER
  FROM ppl p
  JOIN LIBRARY_MARTS.CORPORATE_REGISTRY.CORPORATE_REGISTRY__FED_ICIJ_OFFSHORELEAKS_RELATIONSHIPS r ON r.NODE_ID_START = p.pid AND r.REL_TYPE IN ('officer_of','intermediary_of')
  JOIN LIBRARY_MARTS.CORPORATE_REGISTRY.CORPORATE_REGISTRY__FED_ICIJ_OFFSHORELEAKS_ENTITIES en ON en.NODE_ID = r.NODE_ID_END
)
SELECT SOURCE_LEAK, jur, IFF(COMPANY_TYPE ILIKE '%asset protection%', 'asset protection trust', 'other') vehicle,
       COUNT(DISTINCT pid) people, COUNT(DISTINCT eid) entities, ANY_VALUE(SERVICE_PROVIDER) provider_eg
FROM links
GROUP BY GROUPING SETS ((SOURCE_LEAK, jur, vehicle), (SOURCE_LEAK), ())
HAVING COUNT(DISTINCT pid) >= 20 OR jur IS NULL
ORDER BY people DESC;

-- S17 the two excluded doctors in the ICIJ match: were they paid after exclusion (findings table), by NPI
SELECT 'paid_after' src, NPI, LAST_NAME, FIRST_NAME, EXCLUSION_TYPE, TO_VARCHAR(EXCLUSION_YEAR) excl_year,
       TO_VARCHAR(TOTAL_PAID_AFTER_EXCLUSION) paid, TO_VARCHAR(FIRST_PAID_YEAR) first_paid, TO_VARCHAR(LAST_PAID_YEAR) last_paid
FROM LIBRARY_MARTS.FINDINGS.EXCLUDED_PROVIDER_PAID_AFTER_EXCLUSION
WHERE NPI IN ('1659445690','1639395619') OR UPPER(LAST_NAME) IN ('BRESSI','KAMRAVA','ROIX','GOLDEN');
