{{ config(tags=['spine_generated']) }}

-- GRAIN: one row per organization (DEA_NO+TRANSACTION_DATE+TRANSACTION_CODE+DRUG_CODE+TRANSACTION_ID unique)
-- SPINE_ENTITY: organization  (natural_key: REPORTER_DEA_NO, TRANSACTION_DATE, TRANSACTION_CODE, DRUG_CODE, TRANSACTION_ID)
-- Generated by scripts/generate_staging_models.py from SOURCE_REGISTRY -- deterministic,
-- no LLM. Casts kept as landed (TEXT) -- add explicit type casts by hand once each
-- column's real type is confirmed; this generator has no semantic type knowledge.
-- spine_entity 'organization' has no connect/ resolver yet (see connect/spine_entity.py) -- no SPINE_ENTITY_ID emitted.
-- DEDUPE: registry natural_key (REPORTER_DEA_NO, TRANSACTION_DATE, TRANSACTION_CODE, DRUG_CODE, TRANSACTION_ID) is NOT unique within a load as landed at generation time -- it would collapse 52,953 of 178,598,026 rows. Deduping on the WHOLE ROW instead (exact copies only). A record that changes between loads shows once per version. Find the real key, fix SOURCE_REGISTRY, regenerate.

with source as (

    select * from {{ source('ripple_raw', 'FED_DEA_ARCOS_FULL') }}

),

renamed as (

    select
        "REPORTER_DEA_NO" as reporter_dea_no,
        "REPORTER_BUS_ACT" as reporter_bus_act,
        "REPORTER_NAME" as reporter_name,
        "REPORTER_ADDL_CO_INFO" as reporter_addl_co_info,
        "REPORTER_ADDRESS1" as reporter_address1,
        "REPORTER_ADDRESS2" as reporter_address2,
        "REPORTER_CITY" as reporter_city,
        "REPORTER_STATE" as reporter_state,
        "REPORTER_ZIP" as reporter_zip,
        "REPORTER_COUNTY" as reporter_county,
        "BUYER_DEA_NO" as buyer_dea_no,
        "BUYER_BUS_ACT" as buyer_bus_act,
        "BUYER_NAME" as buyer_name,
        "BUYER_ADDL_CO_INFO" as buyer_addl_co_info,
        "BUYER_ADDRESS1" as buyer_address1,
        "BUYER_ADDRESS2" as buyer_address2,
        "BUYER_CITY" as buyer_city,
        "BUYER_STATE" as buyer_state,
        "BUYER_ZIP" as buyer_zip,
        "BUYER_COUNTY" as buyer_county,
        "TRANSACTION_CODE" as transaction_code,
        "DRUG_CODE" as drug_code,
        "NDC_NO" as ndc_no,
        "DRUG_NAME" as drug_name,
        "QUANTITY" as quantity,
        "UNIT" as unit,
        "ACTION_INDICATOR" as action_indicator,
        "ORDER_FORM_NO" as order_form_no,
        "CORRECTION_NO" as correction_no,
        "STRENGTH" as strength,
        "TRANSACTION_DATE" as transaction_date,
        "CALC_BASE_WT_IN_GM" as calc_base_wt_in_gm,
        "DOSAGE_UNIT" as dosage_unit,
        "TRANSACTION_ID" as transaction_id,
        "PRODUCT_NAME" as product_name,
        "INGREDIENT_NAME" as ingredient_name,
        "MEASURE" as measure,
        "MME_CONVERSION_FACTOR" as mme_conversion_factor,
        "COMBINED_LABELER_NAME" as combined_labeler_name,
        "REVISED_COMPANY_NAME" as revised_company_name,
        "REPORTER_FAMILY" as reporter_family,
        "DOS_STR" as dos_str,
        _INGESTED_AT as _loaded_at,
        '' as _source_url

    from source

)

select * from renamed
qualify row_number() over (partition by reporter_dea_no, reporter_bus_act, reporter_name, reporter_addl_co_info, reporter_address1, reporter_address2, reporter_city, reporter_state, reporter_zip, reporter_county, buyer_dea_no, buyer_bus_act, buyer_name, buyer_addl_co_info, buyer_address1, buyer_address2, buyer_city, buyer_state, buyer_zip, buyer_county, transaction_code, drug_code, ndc_no, drug_name, quantity, unit, action_indicator, order_form_no, correction_no, strength, transaction_date, calc_base_wt_in_gm, dosage_unit, transaction_id, product_name, ingredient_name, measure, mme_conversion_factor, combined_labeler_name, revised_company_name, reporter_family, dos_str order by _loaded_at desc) = 1
