-- S07 Designation timing for the 4 AIS hits (OpenSanctions first-seen, datasets, sanctions text), plus the AIS tanker denominator for the same week
WITH os AS (
  SELECT NAME, ENTITY_TYPE, FIRST_SEEN::string first_seen, LAST_CHANGE::string last_change, LEFT(DATASETS::string, 300) datasets,
         LEFT(SANCTIONS::string, 300) sanctions, LEFT(IDENTIFIERS::string, 200) ids, LEFT(ALIASES::string, 200) aliases
  FROM LIBRARY_MARTS.JUSTICE.JUSTICE__INTL_OPENSANCTIONS_DEFAULT
  WHERE ENTITY_TYPE = 'Vessel'
    AND (IDENTIFIERS::string ILIKE ANY ('%9379698%','%9259317%','%9275660%','%9299563%') OR NAME::string ILIKE ANY ('%9379698%','%9259317%','%9275660%','%9299563%'))
), den AS (
  SELECT COUNT(DISTINCT IFF(VESSEL_TYPE_CODE BETWEEN 80 AND 89 AND IMO_NORMALIZED::string NOT IN ('0000000','0000001') AND IMO_NORMALIZED IS NOT NULL, IMO_NORMALIZED, NULL)) tanker_imos,
         COUNT(DISTINCT IFF(VESSEL_TYPE_CODE BETWEEN 80 AND 89 AND LENGTH_METERS >= 200 AND IMO_NORMALIZED::string NOT IN ('0000000','0000001') AND IMO_NORMALIZED IS NOT NULL, IMO_NORMALIZED, NULL)) big_tanker_imos,
         COUNT(DISTINCT IFF(IMO_NORMALIZED::string NOT IN ('0000000','0000001') AND IMO_NORMALIZED IS NOT NULL, IMO_NORMALIZED, NULL)) all_imos,
         MIN(DATE)::string d0, MAX(DATE)::string d1
  FROM LIBRARY_MARTS.MARITIME.MARITIME__FED_NOAA_AIS
)
SELECT os.*, den.* FROM den LEFT JOIN os ON TRUE;
