-- S01 CDC suicide: profile by unit and split, year range, flags, duplicate keys
SELECT UNIT_NUM, UNIT, STUB_NAME, COUNT(*) n, MIN(YEAR) y0, MAX(YEAR) y1, COUNT(DISTINCT YEAR) years,
       COUNT(DISTINCT STUB_LABEL, AGE, YEAR) keys, COUNT_IF(NULLIF(TRIM(FLAG),'') IS NOT NULL) flagged,
       COUNT_IF(NULLIF(TRIM(ESTIMATE),'') IS NULL) blank_est
FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CDC_SUICIDE_RATES
GROUP BY 1,2,3 ORDER BY 1,3;

-- S02 HPSA: status x designation type, date sentinels, how stale the last update is
SELECT HPSA_STATUS, DESIGNATION_TYPE, COUNT(*) n, COUNT(DISTINCT HPSA_ID) hpsas,
       MIN(DESIGNATION_DATE) d0, MAX(DESIGNATION_DATE) d1, COUNT_IF(DESIGNATION_DATE = '1970-01-01') d1970,
       COUNT(DISTINCT IFF(YEAR(DESIGNATION_DATE) < 1996, HPSA_ID, NULL)) hpsa_pre1996,
       MIN(DESIGNATION_LAST_UPDATE_DATE) u0, MAX(DESIGNATION_LAST_UPDATE_DATE) u1,
       COUNT(DISTINCT IFF(DESIGNATION_LAST_UPDATE_DATE < '2022-01-01', HPSA_ID, NULL)) hpsa_upd_pre2022,
       COUNT_IF(WITHDRAWN_DATE IS NOT NULL) wd, MEDIAN(HPSA_SCORE) med_score, COUNT_IF(HPSA_FTE = 0) fte0
FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_HRSA_HPSA_PRIMARY_CARE
GROUP BY 1,2 ORDER BY 1, n DESC;

-- S03 SAM excluded providers: agency x current, NPI fill, date sentinels, match method
SELECT EXCLUDING_AGENCY, COUNT(*) n, COUNT(DISTINCT SAM_NUMBER) sam_ids, COUNT_IF(IS_CURRENTLY_EXCLUDED) current_,
       COUNT_IF(IS_ENTITY_NOT_INDIVIDUAL) entities,
       COUNT_IF(REGEXP_LIKE(NPI,'^[0-9]{10}$') AND NPI <> '0000000000') npi_ok, COUNT_IF(REGEXP_LIKE(SAM_NPI,'^[0-9]{10}$') AND SAM_NPI <> '0000000000') sam_npi_ok,
       COUNT_IF(ACTIVATION_DATE > '2027-01-01') act_future, MIN(ACTIVATION_DATE) a0, MAX(IFF(ACTIVATION_DATE < '2027-01-01', ACTIVATION_DATE, NULL)) a1_real,
       COUNT_IF(TERMINATION_DATE_RAW ILIKE 'indef%') indefinite, ARRAY_AGG(DISTINCT MATCH_METHOD) methods
FROM LIBRARY_MARTS.HEALTH.HEALTH__SAM_EXCLUDED_PROVIDERS
GROUP BY ROLLUP(1) ORDER BY n DESC;

-- S04 MDS frequency: report dates, facilities, questions, suppression placeholder
SELECT REPORT_DATE, COUNT(*) n, COUNT(DISTINCT CCN) ccns, COUNT(DISTINCT MDS_ITEM_QUESTION_DESCRIPTION) questions,
       COUNT(DISTINCT MDS_ITEM_QUESTION_DESCRIPTION, MDS_ITEM_RESPONSE) q_resp,
       COUNT_IF(TOTAL_RESIDENTS = '_') tot_placeholder, COUNT_IF(OVERALL_PERCENT IS NOT NULL) overall_filled,
       COUNT_IF(LONG_STAY_PERCENT IS NOT NULL) ls_filled, COUNT(DISTINCT CCN, MDS_ITEM_QUESTION_DESCRIPTION, MDS_ITEM_RESPONSE) keys
FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_FACILITY_LEVEL_MINIMUM_DATA_SET_FREQUENCY
GROUP BY 1 ORDER BY 1;

-- S05 MDS frequency: the psych, PASRR, falls, ulcer, restraint items and how filled they are
SELECT MDS_ITEM_QUESTION_DESCRIPTION q, MDS_ITEM_RESPONSE r, COUNT(*) n, COUNT(DISTINCT CCN) ccns,
       COUNT_IF(OVERALL_PERCENT IS NOT NULL) ov_filled, COUNT_IF(LONG_STAY_PERCENT IS NOT NULL) ls_filled,
       MEDIAN(OVERALL_PERCENT) med_ov, MEDIAN(LONG_STAY_PERCENT) med_ls, MAX(TRY_TO_NUMBER(TOTAL_RESIDENTS)) max_tot
FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_FACILITY_LEVEL_MINIMUM_DATA_SET_FREQUENCY
WHERE MDS_ITEM_QUESTION_DESCRIPTION ILIKE ANY ('I6000%','N0415A%','N0450%','A1500%','A1510%','J1800%','M0300%','P0100%','I5700%','I5800%','I5900%','I5950%','I6100%','A0310A%')
GROUP BY 1,2 ORDER BY 1,2;

-- S06 NPPES: entity type x enumeration year, deactivation fill
SELECT ENTITY_TYPE_CODE, YEAR(PROVIDER_ENUMERATION_DATE) y, COUNT(*) n,
       COUNT_IF(NPI_DEACTIVATION_DATE IS NOT NULL) deact, COUNT_IF(NPI_REACTIVATION_DATE IS NOT NULL) react,
       COUNT_IF(NULLIF(TRIM(PROVIDER_FIRST_LINE_BUSINESS_PRACTICE_LOCATION_ADDRESS),'') IS NULL) no_addr,
       COUNT_IF(HEALTHCARE_PROVIDER_TAXONOMY_CODE_1 = '251G00000X') hospice_tx1
FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_NPPES
GROUP BY 1,2 ORDER BY 1,2;
