-- S07 CDC suicide: full extract (6,390 rows) for local growth math
SELECT UNIT_NUM, STUB_NAME, STUB_LABEL, AGE, YEAR, ESTIMATE, FLAG
FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CDC_SUICIDE_RATES;

-- S08 HPSA: one row per shortage area (HPSA_ID), components collapsed
SELECT HPSA_ID, ANY_VALUE(HPSA_NAME) name, COUNT(*) comps, COUNT(DISTINCT HPSA_STATUS) nstat, ANY_VALUE(HPSA_STATUS) status,
       ANY_VALUE(DESIGNATION_TYPE) dtype, ANY_VALUE(PRIMARY_STATE_ABBREVIATION) st, MIN(DESIGNATION_DATE) ddate,
       MAX(DESIGNATION_LAST_UPDATE_DATE) upd, MAX(WITHDRAWN_DATE) wd, MAX(DESIGNATION_POPULATION) pop,
       MAX(PCT_POPULATION_BELOW_POVERTY) pov, MAX(HPSA_SCORE) score, MAX(HPSA_FTE) fte, MAX(HPSA_SHORTAGE) shortage,
       ANY_VALUE(RURAL_STATUS) rural, ANY_VALUE(POPULATION_TYPE) poptype, ANY_VALUE(FORMAL_RATIO) ratio,
       MAX(ESTIMATED_UNDERSERVED_POPULATION) underserved, COUNT(DISTINCT COMMON_STATE_COUNTY_FIPS_CODE) counties,
       ANY_VALUE(COMMON_STATE_COUNTY_FIPS_CODE) fips, ANY_VALUE(COMMON_COUNTY_NAME) county
FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_HRSA_HPSA_PRIMARY_CARE
GROUP BY 1;

-- S09 SAM excluded providers with a 10-digit NPI: does NPPES, Medicare or the OIG list agree on city?
WITH s AS (
  SELECT SAM_NUMBER, NPI, SAM_NPI, EXCLUDING_AGENCY, EXCLUSION_TYPE, EXCLUSION_PROGRAM, CLASSIFICATION, IS_ENTITY_NOT_INDIVIDUAL,
         ENTITY_NAME, FIRST_NAME, LAST_NAME, CITY, STATE, ACTIVATION_DATE, TERMINATION_DATE_RAW, IS_CURRENTLY_EXCLUDED,
         MATCH_METHOD, MATCH_NOTE, NPPES_NAME, TAXONOMY_CODE_1, CREDENTIAL
  FROM LIBRARY_MARTS.HEALTH.HEALTH__SAM_EXCLUDED_PROVIDERS
  WHERE REGEXP_LIKE(NPI, '^[0-9]{10}$') AND NPI <> '0000000000'),
n AS (
  SELECT NPI, ENTITY_TYPE_CODE et, PROVIDER_LAST_NAME_LEGAL_NAME ln, PROVIDER_FIRST_NAME fn, PROVIDER_MIDDLE_NAME mn,
         UPPER(TRIM(PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_CITY_NAME)) pcity, PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_STATE_NAME pst,
         UPPER(TRIM(PROVIDER_BUSINESS_MAILING_ADDRESS_CITY_NAME)) mcity, PROVIDER_BUSINESS_MAILING_ADDRESS_STATE_NAME mst,
         PROVIDER_CREDENTIAL_TEXT cred, HEALTHCARE_PROVIDER_TAXONOMY_CODE_1 tx, PROVIDER_ENUMERATION_DATE en, LAST_UPDATE_DATE lu
  FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_NPPES WHERE NPI IN (SELECT NPI FROM s)),
b AS (
  SELECT RNDRNG_NPI npi, SUM(TOT_MDCR_PYMT_AMT) partb_pay, MAX(UPPER(TRIM(RNDRNG_PRVDR_CITY))) bcity
  FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_MEDICARE_PHYSICIAN_OTHER_PRACTITIONERS_BY_PROVIDER
  WHERE RNDRNG_NPI IN (SELECT NPI FROM s) GROUP BY 1),
d AS (
  SELECT NPI, ARRAY_AGG(DISTINCT DATA_YEAR) dyears, SUM(TRY_TO_NUMBER(TOT_CLMS)) partd_clms,
         SUM(TRY_TO_DOUBLE(NULLIF(LOWER(TOT_DRUG_CST), 'nan'))) partd_cost, SUM(TRY_TO_NUMBER(OPIOID_TOT_CLMS)) opioid_clms,
         MAX(UPPER(TRIM(PRSCRBR_CITY))) dcity
  FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_PART_D_PRESCRIBERS WHERE NPI IN (SELECT NPI FROM s) GROUP BY 1),
l AS (
  SELECT NPI, MIN(EXCLUSION_DATE) leie_date, ANY_VALUE(EXCLUSION_TYPE) leie_type, ANY_VALUE(UPPER(TRIM(CITY))) lcity
  FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_HHS_OIG_LEIE WHERE NPI IN (SELECT NPI FROM s) GROUP BY 1),
l2 AS (
  SELECT UPPER(TRIM(LAST_NAME)) lnm, UPPER(TRIM(FIRST_NAME)) fnm, STATE, MIN(EXCLUSION_DATE) leie_name_date,
         LISTAGG(DISTINCT UPPER(TRIM(CITY)), '/') leie_name_city
  FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_HHS_OIG_LEIE WHERE NULLIF(TRIM(LAST_NAME), '') IS NOT NULL GROUP BY 1,2,3)
SELECT s.*, n.et, n.ln, n.fn, n.mn, n.pcity, n.pst, n.mcity, n.mst, n.cred, n.tx, n.en, n.lu,
       b.partb_pay, b.bcity, d.dyears, d.partd_clms, d.partd_cost, d.opioid_clms, d.dcity,
       l.leie_date, l.leie_type, l.lcity, l2.leie_name_date, l2.leie_name_city,
       IFF(UPPER(TRIM(s.CITY)) IN (n.pcity, n.mcity, b.bcity, d.dcity), 1, 0) city_agree
FROM s LEFT JOIN n ON n.NPI = s.NPI LEFT JOIN b ON b.npi = s.NPI LEFT JOIN d ON d.NPI = s.NPI LEFT JOIN l ON l.NPI = s.NPI
LEFT JOIN l2 ON l2.lnm = UPPER(TRIM(s.LAST_NAME)) AND l2.fnm = UPPER(TRIM(s.FIRST_NAME)) AND l2.STATE = s.STATE;

-- S10 NPPES: every hospice organization NPI (taxonomy slot 1 = 251G00000X), with Medicare enrollment and certification joined
WITH h AS (
  SELECT NPI, PROVIDER_ORGANIZATION_NAME_LEGAL_BUSINESS_NAME org, PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_STATE_NAME st,
         UPPER(TRIM(PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_CITY_NAME)) city, LEFT(PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_POSTAL_CODE, 5) zip5,
         UPPER(TRIM(PROVIDER_FIRST_LINE_BUSINESS_PRACTICE_LOCATION_ADDRESS)) addr, UPPER(TRIM(PROVIDER_SECOND_LINE_BUSINESS_PRACTICE_LOCATION_ADDRESS)) addr2,
         PROVIDER_ENUMERATION_DATE en, LAST_UPDATE_DATE lu, NPI_DEACTIVATION_DATE deact,
         UPPER(TRIM(AUTHORIZED_OFFICIAL_LAST_NAME)) ao_ln, UPPER(TRIM(AUTHORIZED_OFFICIAL_FIRST_NAME)) ao_fn, AUTHORIZED_OFFICIAL_TITLE_OR_POSITION ao_title,
         AUTHORIZED_OFFICIAL_TELEPHONE_NUMBER ao_phone, PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_TELEPHONE_NUMBER phone,
         IS_ORGANIZATION_SUBPART sub, PARENT_ORGANIZATION_LBN parent
  FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_NPPES
  WHERE ENTITY_TYPE_CODE = '2' AND HEALTHCARE_PROVIDER_TAXONOMY_CODE_1 = '251G00000X'),
e AS (
  SELECT NPI, MAX(CCN) ccn, MAX(ENROLLMENT_STATE) est, MAX(INCORPORATION_DATE) inc, COUNT(*) enr_rows
  FROM LIBRARY_MARTS.IMMIGRATION.IMMIGRATION__FED_CMS_HOSPICE_ENROLLMENTS GROUP BY 1),
c AS (
  SELECT CCN, CERTIFICATION_DATE cert, OWNERSHIP_TYPE own FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_HOSPICE)
SELECT h.*, e.ccn, e.est, e.inc, e.enr_rows, c.cert, c.own
FROM h LEFT JOIN e ON e.NPI = h.NPI LEFT JOIN c ON c.CCN = e.ccn;

-- S11 MDS: one row per nursing home, schizophrenia / antipsychotic / dementia counts, joined to star file and survey tags
WITH x AS (
  SELECT CCN, STATE, PROVIDER_NAME, CITY, LEFT(MDS_ITEM_QUESTION_DESCRIPTION, 7) q, MDS_ITEM_RESPONSE r, OVERALL_PERCENT,
         TRY_TO_NUMBER(TOTAL_RESIDENTS) tot, LONG_STAY_PERCENT, SHORT_STAY_PERCENT,
         TRY_TO_NUMBER(LONG_STAY_RESIDENTS) ls_n, TRY_TO_NUMBER(SHORT_STAY_RESIDENTS) ss_n
  FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_FACILITY_LEVEL_MINIMUM_DATA_SET_FREQUENCY
  WHERE MDS_ITEM_QUESTION_DESCRIPTION LIKE ANY ('I6000:%', 'N0415A1:%', 'I5950:%', 'I5900:%', 'I4800:%', 'I4200:%')),
m AS (
  SELECT CCN, ANY_VALUE(STATE) st, ANY_VALUE(PROVIDER_NAME) name, ANY_VALUE(CITY) city,
    MAX(IFF(q = 'I6000: ' AND r = 'Yes', OVERALL_PERCENT, NULL)) sz_pct,
    MAX(IFF(q = 'I6000: ' AND r = 'Yes', tot, NULL)) sz_n,
    MAX(IFF(q = 'I6000: ' AND r = 'No', tot, NULL)) sz_no_n,
    MAX(IFF(q = 'I6000: ' AND r = 'Yes', LONG_STAY_PERCENT, NULL)) sz_ls_pct,
    MAX(IFF(q = 'I6000: ' AND r = 'Yes', SHORT_STAY_PERCENT, NULL)) sz_ss_pct,
    MAX(IFF(q = 'I6000: ' AND r = 'Yes', ls_n, NULL)) sz_ls_n,
    MAX(IFF(q = 'I6000: ' AND r = 'Yes', ss_n, NULL)) sz_ss_n,
    MAX(IFF(q = 'I6000: ' AND r = 'No', ls_n, NULL)) sz_no_ls_n,
    MAX(IFF(q = 'I6000: ' AND r = 'No', ss_n, NULL)) sz_no_ss_n,
    MAX(IFF(q = 'N0415A1' AND r = 'Yes', OVERALL_PERCENT, NULL)) ap_pct,
    MAX(IFF(q = 'N0415A1' AND r = 'Yes', tot, NULL)) ap_n,
    MAX(IFF(q = 'N0415A1' AND r = 'No', tot, NULL)) ap_no_n,
    MAX(IFF(q = 'I5950: ' AND r = 'Yes', tot, NULL)) psy_n,
    MAX(IFF(q = 'I5900: ' AND r = 'Yes', tot, NULL)) bip_n,
    MAX(IFF(q = 'I4800: ' AND r = 'Yes', tot, NULL)) dem_n,
    MAX(IFF(q = 'I4200: ' AND r = 'Yes', tot, NULL)) alz_n,
    MAX(IFF(q = 'I4800: ' AND r = 'Yes', OVERALL_PERCENT, NULL)) dem_pct,
    MAX(IFF(q = 'I4200: ' AND r = 'Yes', OVERALL_PERCENT, NULL)) alz_pct
  FROM x GROUP BY CCN),
df AS (
  SELECT CMS_CERTIFICATION_NUMBER_CCN ccn,
    COUNT_IF(TRY_TO_NUMBER(REGEXP_SUBSTR(DEFICIENCY_TAG_NUMBER, '[0-9]+')) = 641) f641,
    COUNT_IF(TRY_TO_NUMBER(REGEXP_SUBSTR(DEFICIENCY_TAG_NUMBER, '[0-9]+')) = 758) f758,
    COUNT_IF(TRY_TO_NUMBER(REGEXP_SUBSTR(DEFICIENCY_TAG_NUMBER, '[0-9]+')) = 605) f605,
    COUNT(*) all_def, MIN(SURVEY_DATE) s0, MAX(SURVEY_DATE) s1, ANY_VALUE(DEFICIENCY_TAG_NUMBER) tag_sample
  FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_NURSING_HOME_DEFICIENCIES GROUP BY 1)
SELECT m.*, nh.LEGAL_BUSINESS_NAME, nh.CHAIN_NAME, nh.CHAIN_ID, nh.NUMBER_OF_FACILITIES_IN_CHAIN, nh.OWNERSHIP_TYPE,
       nh.NUMBER_OF_CERTIFIED_BEDS, nh.AVERAGE_NUMBER_OF_RESIDENTS_PER_DAY, nh.OVERALL_RATING, nh.QUALITY_MEASURE_RATING,
       nh.TOTAL_AMOUNT_OF_FINES_IN_DOLLARS, nh.NUMBER_OF_FINES, nh.SPECIAL_FOCUS_STATUS, nh.ABUSE_ICON, nh.PROVIDER_RESIDES_IN_HOSPITAL,
       nh.CMS_CERTIFICATION_NUMBER_CCN nh_ccn, df.f641, df.f758, df.f605, df.all_def, df.s0, df.s1, df.tag_sample
FROM m LEFT JOIN LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_NURSING_HOME nh ON nh.CMS_CERTIFICATION_NUMBER_CCN = m.CCN
LEFT JOIN df ON df.ccn = m.CCN;
