-- S12 NPPES hospice verify in SQL: LA-area phone share by period and region, Medicare enrollment by NPI, name-only hits, and the deactivated-row check
WITH h AS (
  SELECT NPI, UPPER(TRIM(PROVIDER_ORGANIZATION_NAME_LEGAL_BUSINESS_NAME)) org,
         PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_STATE_NAME st, YEAR(PROVIDER_ENUMERATION_DATE) y,
         LEFT(REGEXP_REPLACE(PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_TELEPHONE_NUMBER, '[^0-9]', ''), 3) ac1,
         LEFT(REGEXP_REPLACE(AUTHORIZED_OFFICIAL_TELEPHONE_NUMBER, '[^0-9]', ''), 3) ac2
  FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_NPPES
  WHERE ENTITY_TYPE_CODE = '2' AND HEALTHCARE_PROVIDER_TAXONOMY_CODE_1 = '251G00000X'),
f AS (
  SELECT h.*, IFF(ac1 IN ('213','310','323','424','562','626','661','747','818','840')
               OR ac2 IN ('213','310','323','424','562','626','661','747','818','840'), 1, 0) la
  FROM h),
e AS (SELECT DISTINCT NPI FROM LIBRARY_MARTS.IMMIGRATION.IMMIGRATION__FED_CMS_HOSPICE_ENROLLMENTS),
nm AS (
  SELECT UPPER(TRIM(ORGANIZATION_NAME)) nm FROM LIBRARY_MARTS.IMMIGRATION.IMMIGRATION__FED_CMS_HOSPICE_ENROLLMENTS
  UNION SELECT UPPER(TRIM(DOING_BUSINESS_AS_NAME)) FROM LIBRARY_MARTS.IMMIGRATION.IMMIGRATION__FED_CMS_HOSPICE_ENROLLMENTS
  UNION SELECT UPPER(TRIM(FACILITY_NAME)) FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_HOSPICE)
SELECT IFF(st = 'CA', 'CA', 'outside CA') region, IFF(st IN ('AZ','NV'), st, 'other') st2,
       CASE WHEN y <= 2016 THEN '05-16' WHEN y <= 2019 THEN '17-19' WHEN y <= 2021 THEN '20-21' WHEN y <= 2023 THEN '22-23' ELSE '24-26' END per,
       la, COUNT(*) n, COUNT(e.NPI) enrolled_by_npi, COUNT_IF(e.NPI IS NULL AND nm.nm IS NOT NULL) name_only_hit,
       (SELECT COUNT_IF(NULLIF(TRIM(HEALTHCARE_PROVIDER_TAXONOMY_CODE_1), '') IS NOT NULL
                     OR NULLIF(TRIM(PROVIDER_LAST_NAME_LEGAL_NAME), '') IS NOT NULL
                     OR NULLIF(TRIM(PROVIDER_ORGANIZATION_NAME_LEGAL_BUSINESS_NAME), '') IS NOT NULL)
        FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_NPPES WHERE NULLIF(TRIM(ENTITY_TYPE_CODE), '') IS NULL) deact_rows_with_name_or_taxonomy
FROM f LEFT JOIN e ON e.NPI = f.NPI LEFT JOIN nm ON nm.nm = f.org
GROUP BY 1,2,3,4 ORDER BY 1,2,3,4;

-- S13 MDS verify in SQL: Missouri homes by Reliant vs other, schizophrenia band 40%+, stars, abuse icon, fines
WITH sz AS (
  SELECT CCN, MAX(OVERALL_PERCENT) pct, MAX(TRY_TO_NUMBER(TOTAL_RESIDENTS)) n
  FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_FACILITY_LEVEL_MINIMUM_DATA_SET_FREQUENCY
  WHERE MDS_ITEM_QUESTION_DESCRIPTION LIKE 'I6000:%' AND MDS_ITEM_RESPONSE = 'Yes' GROUP BY 1)
SELECT IFF(nh.CHAIN_NAME = 'RELIANT CARE MANAGEMENT', 'Reliant', 'other') grp, IFF(sz.pct >= 40, '40%+', 'under 40 or suppressed') band,
       COUNT(*) homes, COUNT_IF(nh.OVERALL_RATING = 1) one_star, COUNT(nh.OVERALL_RATING) rated, COUNT_IF(nh.ABUSE_ICON = 'Y') abuse_icon,
       COUNT_IF(nh.SPECIAL_FOCUS_STATUS IS NOT NULL) sff_or_cand, SUM(nh.TOTAL_AMOUNT_OF_FINES_IN_DOLLARS) fines,
       MEDIAN(nh.TOTAL_AMOUNT_OF_FINES_IN_DOLLARS) med_fines, SUM(sz.n) sz_residents_unsuppressed,
       SUM(nh.AVERAGE_NUMBER_OF_RESIDENTS_PER_DAY) avg_residents, MIN(nh.CHAIN_AVERAGE_OVERALL_5_STAR_RATING) chain_avg_star
FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_NURSING_HOME nh LEFT JOIN sz ON sz.CCN = nh.CMS_CERTIFICATION_NUMBER_CCN
WHERE nh.STATE = 'MO'
GROUP BY 1,2 ORDER BY 1,2;

-- S14 MDS time check: CMS penalties by year for Reliant vs other Missouri 40%+ schizophrenia homes vs the rest of Missouri
WITH sz AS (
  SELECT CCN, MAX(OVERALL_PERCENT) pct
  FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_FACILITY_LEVEL_MINIMUM_DATA_SET_FREQUENCY
  WHERE MDS_ITEM_QUESTION_DESCRIPTION LIKE 'I6000:%' AND MDS_ITEM_RESPONSE = 'Yes' GROUP BY 1),
g AS (
  SELECT nh.CMS_CERTIFICATION_NUMBER_CCN ccn,
         CASE WHEN nh.CHAIN_NAME = 'RELIANT CARE MANAGEMENT' THEN 'Reliant' WHEN sz.pct >= 40 THEN 'MO other 40%+' ELSE 'MO rest' END grp
  FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_NURSING_HOME nh LEFT JOIN sz ON sz.CCN = nh.CMS_CERTIFICATION_NUMBER_CCN
  WHERE nh.STATE = 'MO'),
gc AS (SELECT grp, COUNT(*) homes_in_group FROM g GROUP BY 1)
SELECT g.grp, gc.homes_in_group, YEAR(p.PENALTY_DATE) y, COUNT(*) penalties,
       COUNT_IF(p.PENALTY_TYPE ILIKE 'fine%') fines_n, SUM(p.FINE_AMOUNT) fine_dollars, COUNT(DISTINCT p.CMS_CERTIFICATION_NUMBER_CCN) homes_penalized
FROM g JOIN gc ON gc.grp = g.grp JOIN LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_NURSING_HOME_PENALTIES p ON p.CMS_CERTIFICATION_NUMBER_CCN = g.ccn
GROUP BY 1,2,3 ORDER BY 1,3;

-- S15 HPSA verify in SQL: active primary-care area HPSAs, CA and FL vs all other, designated vs proposed for withdrawal
WITH h AS (
  SELECT HPSA_ID, ANY_VALUE(HPSA_STATUS) status, ANY_VALUE(PRIMARY_STATE_ABBREVIATION) s, MAX(DESIGNATION_POPULATION) pop,
         MAX(HPSA_SCORE) sc, MAX(HPSA_FTE) fte, MAX(DESIGNATION_LAST_UPDATE_DATE) upd, MIN(DESIGNATION_DATE) ddate,
         MAX(PCT_POPULATION_BELOW_POVERTY) pov, ANY_VALUE(RURAL_STATUS) rural
  FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_HRSA_HPSA_PRIMARY_CARE
  WHERE DESIGNATION_TYPE IN ('Geographic HPSA', 'HPSA Population', 'High Needs Geographic HPSA') GROUP BY 1)
SELECT IFF(s IN ('CA','FL'), s, 'ALL OTHER') s2, status, COUNT(*) n, SUM(pop) pop, MEDIAN(sc) med_score, AVG(sc) avg_score,
       COUNT_IF(sc >= 18) score18plus, COUNT_IF(fte = 0) fte0, COUNT_IF(TO_CHAR(upd, 'YYYY-MM') = '2025-09') upd_sep2025,
       MEDIAN(YEAR(ddate)) med_desig_year, MEDIAN(pov) med_pov, COUNT_IF(rural = 'Rural') rural_n
FROM h WHERE status <> 'Withdrawn'
GROUP BY 1,2 ORDER BY 1,2;

-- S16 SAM trap check: blank agency vs source SAM file, repeated people, LEIE name+state hits
WITH s AS (SELECT * FROM LIBRARY_MARTS.HEALTH.HEALTH__SAM_EXCLUDED_PROVIDERS),
src AS (SELECT SAM_NUMBER, EXCLUDING_AGENCY src_agency FROM LIBRARY_MARTS.PROCUREMENT.PROCUREMENT__FED_SAM_EXCLUSIONS),
l2 AS (
  SELECT DISTINCT UPPER(TRIM(LAST_NAME)) lnm, UPPER(TRIM(FIRST_NAME)) fnm, STATE
  FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_HHS_OIG_LEIE WHERE NULLIF(TRIM(LAST_NAME), '') IS NOT NULL)
SELECT IFF(NULLIF(TRIM(s.EXCLUDING_AGENCY), '') IS NULL, 'blank', 'named') ag, COALESCE(src.src_agency, '(blank in source)') src_agency,
       COUNT(*) n, COUNT(DISTINCT s.SAM_NUMBER) sam_ids,
       COUNT(DISTINCT COALESCE(UPPER(s.ENTITY_NAME),'') || '|' || COALESCE(UPPER(s.FIRST_NAME),'') || '|' || COALESCE(UPPER(s.LAST_NAME),'') || '|' || COALESCE(UPPER(s.CITY),'') || '|' || COALESCE(s.STATE,'')) people,
       COUNT_IF(NOT s.IS_ENTITY_NOT_INDIVIDUAL) individuals, COUNT_IF(l2.lnm IS NOT NULL) leie_name_state_hits,
       COUNT_IF(REGEXP_LIKE(s.NPI, '^[0-9]{10}$') AND s.NPI <> '0000000000') npi_guessed, MODE(s.EXCLUSION_TYPE) top_type
FROM s LEFT JOIN src ON src.SAM_NUMBER = s.SAM_NUMBER
LEFT JOIN l2 ON l2.lnm = UPPER(TRIM(s.LAST_NAME)) AND l2.fnm = UPPER(TRIM(s.FIRST_NAME)) AND l2.STATE = s.STATE
GROUP BY 1,2 ORDER BY 1, n DESC;
