-- S19 Second-field check on the one exclusion-list hit: OIG row for ALMA INIT vs any NPPES person of that name
SELECT 'LEIE' src, l.FIRST_NAME || ' ' || COALESCE(l.MIDDLE_NAME || ' ', '') || l.LAST_NAME who, l.ADDRESS addr, l.CITY city, l.STATE st, l.ZIP zip,
       l.NPI npi, TO_VARCHAR(l.EXCLUSION_DATE) d, l.EXCLUSION_TYPE || ' / ' || COALESCE(l.GENERAL_CATEGORY, '') || ' / ' || COALESCE(l.SPECIALTY, '') info
FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_HHS_OIG_LEIE l
WHERE UPPER(TRIM(l.LAST_NAME)) = 'INIT'
UNION ALL
SELECT 'NPPES person', n.PROVIDER_FIRST_NAME || ' ' || COALESCE(n.PROVIDER_MIDDLE_NAME || ' ', '') || n.PROVIDER_LAST_NAME_LEGAL_NAME,
       n.PROVIDER_FIRST_LINE_BUSINESS_PRACTICE_LOCATION_ADDRESS, n.PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_CITY_NAME,
       n.PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_STATE_NAME, n.PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_POSTAL_CODE, n.NPI,
       TO_VARCHAR(n.PROVIDER_ENUMERATION_DATE), COALESCE(n.PROVIDER_CREDENTIAL_TEXT, '') || ' / ' || COALESCE(n.HEALTHCARE_PROVIDER_TAXONOMY_CODE_1, '')
FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_NPPES n
WHERE n.ENTITY_TYPE_CODE = '1' AND UPPER(TRIM(n.PROVIDER_LAST_NAME_LEGAL_NAME)) = 'INIT' AND UPPER(TRIM(n.PROVIDER_FIRST_NAME)) = 'ALMA'
UNION ALL
SELECT 'NPPES hospice org', n.PROVIDER_ORGANIZATION_NAME_LEGAL_BUSINESS_NAME, n.PROVIDER_FIRST_LINE_BUSINESS_PRACTICE_LOCATION_ADDRESS,
       n.PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_CITY_NAME, n.PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_STATE_NAME,
       n.PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_POSTAL_CODE, n.NPI, TO_VARCHAR(n.PROVIDER_ENUMERATION_DATE) || ' upd ' || TO_VARCHAR(n.LAST_UPDATE_DATE),
       n.AUTHORIZED_OFFICIAL_FIRST_NAME || ' ' || n.AUTHORIZED_OFFICIAL_LAST_NAME || ' ' || COALESCE(n.AUTHORIZED_OFFICIAL_TITLE_OR_POSITION, '') || ' ' || COALESCE(n.AUTHORIZED_OFFICIAL_TELEPHONE_NUMBER, '')
FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_NPPES n
WHERE n.NPI IN ('1922730175', '1558037887');
