-- @geo_all
SELECT * FROM LIBRARY_MARTS.EDUCATION.EDUCATION__FED_GOOGLE_POLADS_GEO_SPEND
-- @adv_all
SELECT * FROM LIBRARY_MARTS.EDUCATION.EDUCATION__FED_GOOGLE_POLADS_ADVERTISER_STATS
-- @idmap_all
SELECT * FROM LIBRARY_MARTS.EDUCATION.EDUCATION__FED_GOOGLE_POLADS_ADVERTISER_ID_MAPPING
-- @neiss_all
SELECT * FROM LIBRARY_MARTS.EDUCATION.EDUCATION__FED_CPSC_NEISS_CODES
-- @cot_all
SELECT * FROM LIBRARY_MARTS.EDUCATION.EDUCATION__FED_CFTC_COT_FINANCIAL
