-- @house_weekly
-- Weekly Google spend for every advertiser that gave Google the U.S. House EIN 53-6002523, or is named as a House office
WITH h AS (
  SELECT ADVERTISER_ID, ADVERTISER_NAME, PUBLIC_IDS_LIST FROM LIBRARY_MARTS.EDUCATION.EDUCATION__FED_GOOGLE_POLADS_ADVERTISER_STATS
  WHERE PUBLIC_IDS_LIST LIKE '%53-6002523%' OR UPPER(ADVERTISER_NAME) LIKE '%HOUSE OF REP%')
SELECT w.ADVERTISER_ID, h.ADVERTISER_NAME, h.PUBLIC_IDS_LIST, w.WEEK_START_DATE, w.SPEND_USD
FROM LIBRARY_MARTS.EDUCATION.EDUCATION__FED_GOOGLE_POLADS_ADVERTISER_WEEKLY_SPEND w JOIN h ON h.ADVERTISER_ID = w.ADVERTISER_ID
-- @house_geo
-- Where (country, state) those same accounts' spend landed
WITH h AS (
  SELECT ADVERTISER_ID, ADVERTISER_NAME, PUBLIC_IDS_LIST FROM LIBRARY_MARTS.EDUCATION.EDUCATION__FED_GOOGLE_POLADS_ADVERTISER_STATS
  WHERE PUBLIC_IDS_LIST LIKE '%53-6002523%' OR UPPER(ADVERTISER_NAME) LIKE '%HOUSE OF REP%')
SELECT g.ADVERTISER_ID, h.ADVERTISER_NAME, g.COUNTRY, g.COUNTRY_SUBDIVISION_PRIMARY, g.SPEND_USD
FROM LIBRARY_MARTS.EDUCATION.EDUCATION__FED_GOOGLE_POLADS_ADVERTISER_GEO_SPEND g JOIN h ON h.ADVERTISER_ID = g.ADVERTISER_ID
