-- @generic_house_creatives
-- Ads run by the generic 'US House of Representatives' account (House EIN): where they were aimed, how many, when
SELECT GEO_TARGETING_INCLUDED, COUNT(*) ads, SUM(TRY_TO_NUMBER(SPEND_RANGE_MIN_USD)) min_usd, SUM(TRY_TO_NUMBER(SPEND_RANGE_MAX_USD)) max_usd,
       MIN(DATE_RANGE_START) first_day, MAX(DATE_RANGE_END) last_day, MIN(AD_URL) sample_url
FROM LIBRARY_MARTS.EDUCATION.EDUCATION__FED_GOOGLE_POLADS_CREATIVE_STATS
WHERE ADVERTISER_ID = 'AR11776064889791971329'
GROUP BY 1 ORDER BY max_usd DESC NULLS LAST
-- @house_members
-- Every House member whose service reached 2018 or later: name, state, district, party
SELECT BIOGUIDE, NAME_FIRST, NAME_LAST, NAME_OFFICIAL_FULL, STATE, DISTRICT, PARTY, TERM_TYPE, TERM_START, TERM_END
FROM LIBRARY_MARTS.POLITICS.POLITICS__FED_CONGRESS_LEGISLATORS
WHERE TERM_END >= '2019-01-03'
-- @house_general_results
-- House general-election results 2016-2024, for winner margin per district and who was on the ballot
SELECT ELECTION_YEAR, STATE_ABBR, DISTRICT, CANDIDATE_NAME, PARTY, CANDIDATE_VOTES, TOTAL_VOTES, STAGE, IS_SPECIAL_ELECTION, IS_WRITEIN
FROM LIBRARY_MARTS.POLITICS.POLITICS__FED_MEDSL_HOUSE_RETURNS
WHERE ELECTION_YEAR >= 2016
