-- @generic_house_creative_rows
-- One row per ad for the generic 'US House of Representatives' account, to date and place each ad
SELECT AD_ID, AD_TYPE, DATE_RANGE_START, DATE_RANGE_END, NUM_OF_DAYS, IMPRESSIONS, SPEND_RANGE_MIN_USD, SPEND_RANGE_MAX_USD,
       GEO_TARGETING_INCLUDED, GEO_TARGETING_EXCLUDED, AGE_TARGETING, GENDER_TARGETING, AD_URL
FROM LIBRARY_MARTS.EDUCATION.EDUCATION__FED_GOOGLE_POLADS_CREATIVE_STATS
WHERE ADVERTISER_ID = 'AR11776064889791971329'
