-- @steel_goldman_ad_rows
-- Ad-level rows (with the public ad link) for the two House-EIN accounts named for one member whose ads aimed at other members' districts
SELECT ADVERTISER_ID, ADVERTISER_NAME, AD_ID, AD_TYPE, DATE_RANGE_START, DATE_RANGE_END, SPEND_RANGE_MIN_USD, SPEND_RANGE_MAX_USD,
       LEFT(GEO_TARGETING_INCLUDED, 200) geo, AD_URL
FROM LIBRARY_MARTS.EDUCATION.EDUCATION__FED_GOOGLE_POLADS_CREATIVE_STATS
WHERE ADVERTISER_ID IN ('AR13522503217748901889', 'AR16196087374160068609')
ORDER BY ADVERTISER_ID, DATE_RANGE_START
