version: 2

sources:
  - name: ripple_raw
    database: LIBRARY_RAW
    schema: LANDING
    tables:
      - name: FED_EPA_EGRID_PLANT_2019

models:
  - name: stg_fed_epa_egrid_plant_2019__all
    description: "EPA eGRID plant file 2019"
    columns:
      - name: ORISPL
        tests:
          - not_null
          - unique
