-- S01 PBGC data: whole table pull (134.5K rows), worked locally
SELECT * FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_PBGC_DATA;

-- S02 Foreign assistance: whole table pull (95.7K rows), worked locally
SELECT * FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_FOREIGNASSISTANCE;

-- S03 USAspending API: whole table pull (300 rows)
SELECT * FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_US_USASPENDING_API;

-- S04 IRS 527 orgs: whole table pull (77.6K rows), worked locally
SELECT * FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_IRS_527_ORGS;

-- S05 Treasury DTS: whole table pull of the working columns (478K rows), worked locally
SELECT RECORD_DATE, ACCOUNT_TYPE, TRANSACTION_TYPE, TRANSACTION_CATG, TRANSACTION_CATG_DESC,
       TRANSACTION_TODAY_AMT, TRANSACTION_MTD_AMT, TRANSACTION_FYTD_AMT, SRC_LINE_NBR, TABLE_NBR, RECORD_FISCAL_YEAR
FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_TREASURY_DTS_DEPOSITS;
