-- S06 Landing check: do the raw PBGC and foreign-aid loads hold a column header or dollar column the mart lost?
SELECT TABLE_NAME, COUNT(*) n_cols, LISTAGG(COLUMN_NAME, ', ') WITHIN GROUP (ORDER BY ORDINAL_POSITION) cols
FROM LIBRARY_RAW.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'LANDING' AND (TABLE_NAME ILIKE '%PBGC_DATA%' OR TABLE_NAME ILIKE '%FOREIGNASSIST%')
GROUP BY 1 ORDER BY 1;

-- S07 USAspending API sample: do its 300 award IDs already sit in the full contract and assistance tables?
WITH api AS (
  SELECT AWARD_ID, IFF(CFDA_NUMBER IS NOT NULL, 'grant', 'contract') kind, AWARD_AMOUNT
  FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_US_USASPENDING_API
), c AS (
  SELECT DISTINCT AWARD_ID_PIID id FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_USASPENDING_CONTRACTS_FULL_R2
  WHERE AWARD_ID_PIID IN (SELECT AWARD_ID FROM api WHERE kind = 'contract')
), a AS (
  SELECT DISTINCT AWARD_ID_FAIN id FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_USASPENDING_ASSISTANCE_FULL
  WHERE AWARD_ID_FAIN IN (SELECT AWARD_ID FROM api WHERE kind = 'grant')
)
SELECT api.kind, COUNT(*) n, COUNT(c.id) in_contracts_r2, COUNT(a.id) in_assistance_full, MIN(AWARD_AMOUNT) min_amt
FROM api LEFT JOIN c ON api.AWARD_ID = c.id LEFT JOIN a ON api.AWARD_ID = a.id
GROUP BY 1;

-- S08 Monthly Treasury Statement: customs duties gross, refunds, net, by month from FY2024 (second source for the DTS CBP outflow)
SELECT RECORD_DATE, RECORD_FISCAL_YEAR, CLASSIFICATION_ID, CLASSIFICATION_DESC, SEQUENCE_NUMBER_CD,
       CURRENT_MONTH_GROSS_RCPT_AMT, CURRENT_MONTH_REFUND_AMT, CURRENT_MONTH_NET_RCPT_AMT,
       CURRENT_FYTD_GROSS_RCPT_AMT, CURRENT_FYTD_REFUND_AMT, CURRENT_FYTD_NET_RCPT_AMT,
       PRIOR_FYTD_REFUND_AMT
FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_TREASURY_MTS_RECEIPTS
WHERE CLASSIFICATION_DESC ILIKE '%customs%' AND RECORD_DATE >= '2023-10-01'
ORDER BY RECORD_DATE, SEQUENCE_NUMBER_CD;
