-- S09 USAspending API sample, redo of S07: CFDA_NUMBER is an empty string, not NULL, on the 200 contracts. Land rate of the contracts in CONTRACTS_FULL_R2
WITH api AS (
  SELECT AWARD_ID, IFF(NULLIF(TRIM(CFDA_NUMBER), '') IS NOT NULL, 'grant', 'contract') kind, AWARD_AMOUNT
  FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_US_USASPENDING_API
), c AS (
  SELECT DISTINCT AWARD_ID_PIID id FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_USASPENDING_CONTRACTS_FULL_R2
  WHERE AWARD_ID_PIID IN (SELECT AWARD_ID FROM api WHERE kind = 'contract')
)
SELECT api.kind, COUNT(*) n, COUNT(c.id) in_contracts_r2, COUNT_IF(CFDA_BLANK) cfda_blank_string
FROM (SELECT api.*, TRUE AS CFDA_BLANK FROM api) api LEFT JOIN c ON api.AWARD_ID = c.id
GROUP BY 1;

-- S10 MTS customs duties, full history: monthly gross, refunds, net, and how far back the table goes
SELECT RECORD_DATE, CLASSIFICATION_DESC, SEQUENCE_NUMBER_CD,
       CURRENT_MONTH_GROSS_RCPT_AMT, CURRENT_MONTH_REFUND_AMT, CURRENT_MONTH_NET_RCPT_AMT, CURRENT_FYTD_NET_RCPT_AMT
FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_TREASURY_MTS_RECEIPTS
WHERE CLASSIFICATION_DESC ILIKE 'customs%'
ORDER BY RECORD_DATE, SEQUENCE_NUMBER_CD;

-- S11 MTS trap test: across every receipt line, is the monthly net blank exactly when refunds exceed gross?
SELECT (CURRENT_MONTH_REFUND_AMT > CURRENT_MONTH_GROSS_RCPT_AMT) refund_gt_gross,
       (CURRENT_MONTH_NET_RCPT_AMT IS NULL) net_blank,
       COUNT(*) n, COUNT(DISTINCT CLASSIFICATION_DESC) lines, MIN(RECORD_DATE) d0, MAX(RECORD_DATE) d1,
       ARRAY_SLICE(ARRAY_AGG(DISTINCT CLASSIFICATION_DESC), 0, 8) examples
FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_TREASURY_MTS_RECEIPTS
WHERE CURRENT_MONTH_GROSS_RCPT_AMT IS NOT NULL AND CURRENT_MONTH_REFUND_AMT IS NOT NULL
GROUP BY 1, 2 ORDER BY 1, 2;
