-- S12 USAspending API sample: which of its 200 big contracts miss CONTRACTS_FULL_R2, and what R2 holds for the ones that land (action-date span, rows)
WITH api AS (
  SELECT AWARD_ID, RECIPIENT_NAME, AWARDING_AGENCY_NAME, START_DATE, END_DATE, LAST_MODIFIED_DATE, AWARD_AMOUNT
  FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_US_USASPENDING_API
  WHERE NULLIF(TRIM(CFDA_NUMBER), '') IS NULL
), c AS (
  SELECT AWARD_ID_PIID id, COUNT(*) r2_rows, MIN(ACTION_DATE) r2_first_action, MAX(ACTION_DATE) r2_last_action,
         SUM(TRY_TO_DOUBLE(FEDERAL_ACTION_OBLIGATION::STRING)) r2_obligated
  FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_USASPENDING_CONTRACTS_FULL_R2
  WHERE AWARD_ID_PIID IN (SELECT AWARD_ID FROM api)
  GROUP BY 1
)
SELECT api.*, c.r2_rows, c.r2_first_action, c.r2_last_action, c.r2_obligated,
       (SELECT MIN(ACTION_DATE) FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_USASPENDING_CONTRACTS_FULL_R2) r2_min_action,
       (SELECT MAX(ACTION_DATE) FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_USASPENDING_CONTRACTS_FULL_R2) r2_max_action
FROM api LEFT JOIN c ON api.AWARD_ID = c.id
ORDER BY c.id IS NULL DESC, api.AWARD_AMOUNT DESC;
