-- S01 NASA open data: read every row except the raw JSON
SELECT API_NAME, MEDIA_TYPE, RESPONSE_DATE, LEFT(TITLE,60) title, LEFT(DESCRIPTION,140) descr, LEFT(REQUEST_URL,90) req
FROM LIBRARY_MARTS.SCIENCE.SCIENCE__FED_NASA_OPEN_DATA ORDER BY API_NAME, RESPONSE_DATE;

-- S02 Ensembl: what the 643 rows are - feature type, chromosome, region, gene name stems
SELECT FEATURE_TYPE, SEQ_REGION_NAME, REGION, COUNT(*) n, COUNT(DISTINCT ID) ids,
       LISTAGG(DISTINCT SPLIT_PART(SYMBOL,'-',1), ',') genes, LISTAGG(DISTINCT BIOTYPE, ',') biotypes,
       COUNT_IF(TAXON_ID IS NOT NULL AND TAXON_ID::STRING NOT IN ('','None')) taxon_filled
FROM LIBRARY_MARTS.SCIENCE.SCIENCE__INTL_EMBL_ENSEMBL GROUP BY 1,2,3 ORDER BY n DESC;

-- S03 OWID AI incidents: all 14 rows
SELECT * FROM LIBRARY_MARTS.SCIENCE.SCIENCE__XC_OWID_AI_INCIDENTS_ANNUAL ORDER BY YEAR;

-- S04 Earthquakes: month by month - rows, distinct IDs, magnitude bands, type, review status, fixed 10 km depth
SELECT DATE_TRUNC('month', TIME)::DATE mo, COUNT(*) n, COUNT(DISTINCT ID) ids,
       COUNT_IF(MAG >= 3) m3, COUNT_IF(MAG >= 4.5) m45, COUNT_IF(MAG >= 6) m6,
       COUNT_IF(TYPE = 'earthquake') eq, COUNT_IF(STATUS = 'reviewed') reviewed, COUNT_IF(DEPTH = 10) d10,
       MIN(TIME) t0, MAX(TIME) t1, MAX(UPDATED) upd_max
FROM LIBRARY_MARTS.SCIENCE.SCIENCE__FED_USGS_EARTHQUAKES GROUP BY 1 ORDER BY 1;

-- S05 Earthquakes: value profile - type, status, network, magtype, the most common depths, lat/lon that do not parse
SELECT 'type' dim, TYPE val, COUNT(*) n FROM LIBRARY_MARTS.SCIENCE.SCIENCE__FED_USGS_EARTHQUAKES GROUP BY 2
UNION ALL SELECT 'status', STATUS, COUNT(*) FROM LIBRARY_MARTS.SCIENCE.SCIENCE__FED_USGS_EARTHQUAKES GROUP BY 2
UNION ALL SELECT 'net', NET, COUNT(*) FROM LIBRARY_MARTS.SCIENCE.SCIENCE__FED_USGS_EARTHQUAKES GROUP BY 2
UNION ALL SELECT 'magtype', MAGTYPE, COUNT(*) FROM LIBRARY_MARTS.SCIENCE.SCIENCE__FED_USGS_EARTHQUAKES GROUP BY 2
UNION ALL SELECT * FROM (SELECT 'depth', TO_VARCHAR(DEPTH), COUNT(*) n FROM LIBRARY_MARTS.SCIENCE.SCIENCE__FED_USGS_EARTHQUAKES GROUP BY 2 ORDER BY n DESC LIMIT 12)
UNION ALL SELECT 'latlon_bad', 'lat or lon not a number', COUNT_IF(TRY_TO_DOUBLE(LATITUDE) IS NULL OR TRY_TO_DOUBLE(LONGITUDE) IS NULL) FROM LIBRARY_MARTS.SCIENCE.SCIENCE__FED_USGS_EARTHQUAKES
UNION ALL SELECT 'dup_id', 'rows minus distinct ID', COUNT(*) - COUNT(DISTINCT ID) FROM LIBRARY_MARTS.SCIENCE.SCIENCE__FED_USGS_EARTHQUAKES
UNION ALL SELECT 'mag_lt_2_5', 'MAG under 2.5', COUNT_IF(MAG < 2.5) FROM LIBRARY_MARTS.SCIENCE.SCIENCE__FED_USGS_EARTHQUAKES
ORDER BY 1, 3 DESC;

-- S06 Earthquakes: lower-48 box, by place suffix (state), oil-field zone, year - counts by magnitude band and who located them
WITH q AS (
  SELECT TRIM(REGEXP_SUBSTR(PLACE, '[^,]+$')) region, YEAR(TIME) yr, MAG, NET, STATUS,
         TRY_TO_DOUBLE(LATITUDE) lat, TRY_TO_DOUBLE(LONGITUDE) lon
  FROM LIBRARY_MARTS.SCIENCE.SCIENCE__FED_USGS_EARTHQUAKES
  WHERE TYPE = 'earthquake' AND TRY_TO_DOUBLE(LATITUDE) BETWEEN 24 AND 50 AND TRY_TO_DOUBLE(LONGITUDE) BETWEEN -125 AND -66)
SELECT region,
       CASE WHEN lat BETWEEN 30.5 AND 33.8 AND lon BETWEEN -105.0 AND -100.5 THEN 'PERMIAN'
            WHEN lat BETWEEN 33.6 AND 37.0 AND lon BETWEEN -99.5 AND -96.0 THEN 'OK_CENTRAL'
            WHEN lat BETWEEN 36.9 AND 37.6 AND lon BETWEEN -98.8 AND -97.0 THEN 'KS_SOUTH'
            WHEN lat BETWEEN 28.0 AND 29.5 AND lon BETWEEN -99.5 AND -97.0 THEN 'EAGLE_FORD'
            WHEN lat BETWEEN 36.9 AND 37.6 AND lon BETWEEN -105.3 AND -104.3 THEN 'RATON'
            ELSE 'OTHER' END zone,
       yr, COUNT(*) n, COUNT_IF(MAG >= 3) m3, COUNT_IF(MAG >= 3.5) m35, COUNT_IF(MAG >= 4) m4, MAX(MAG) max_mag,
       COUNT_IF(NET = 'tx') net_tx, COUNT_IF(NET = 'us') net_us, COUNT_IF(NET = 'ok') net_ok, COUNT_IF(STATUS = 'reviewed') reviewed
FROM q GROUP BY 1,2,3 ORDER BY 1,2,3;

-- S07 NTSB injury: category x injury level - rows, blanks, zeros, sums, events
SELECT INJ_PERSON_CATEGORY, INJURY_LEVEL, COUNT(*) n, COUNT_IF(INJ_PERSON_COUNT IS NULL) blank, COUNT_IF(INJ_PERSON_COUNT = 0) zero,
       SUM(INJ_PERSON_COUNT) people, MAX(INJ_PERSON_COUNT) mx, COUNT(DISTINCT EV_ID) evs
FROM LIBRARY_MARTS.TRANSPORT.TRANSPORT__FED_NTSB_AVIATION_INJURY GROUP BY 1,2 ORDER BY 1,2;

-- S08 NTSB injury: keys, duplicate loads, load runs, change dates, and how many events land in the events and aircraft tables
WITH i AS (SELECT * FROM LIBRARY_MARTS.TRANSPORT.TRANSPORT__FED_NTSB_AVIATION_INJURY),
ie AS (SELECT DISTINCT EV_ID FROM i),
ia AS (SELECT DISTINCT EV_ID, AIRCRAFT_KEY FROM i),
e AS (SELECT DISTINCT EV_ID FROM LIBRARY_MARTS.TRANSPORT.TRANSPORT__FED_NTSB_AVIATION_EVENTS),
a AS (SELECT DISTINCT EV_ID, AIRCRAFT_KEY FROM LIBRARY_MARTS.TRANSPORT.TRANSPORT__FED_NTSB_AVIATION_AIRCRAFT),
m AS (SELECT LCHG_DATE d, COUNT(*) k FROM i GROUP BY 1 ORDER BY k DESC LIMIT 1)
SELECT (SELECT COUNT(*) FROM i) n, (SELECT COUNT(DISTINCT INJURY_RECORD_ID) FROM i) rec_ids,
       (SELECT COUNT(DISTINCT EV_ID, AIRCRAFT_KEY, INJ_PERSON_CATEGORY, INJURY_LEVEL) FROM i) nat_keys,
       (SELECT COUNT(DISTINCT _SOURCE_RUN_ID) FROM i) runs, (SELECT COUNT(DISTINCT _INGESTED_AT) FROM i) ingest_stamps,
       (SELECT COUNT(*) FROM ie) inj_events, (SELECT COUNT(*) FROM e) ev_events,
       (SELECT COUNT(*) FROM ie JOIN e USING (EV_ID)) inj_ev_in_events,
       (SELECT COUNT(*) FROM e WHERE EV_ID NOT IN (SELECT EV_ID FROM ie)) events_without_inj,
       (SELECT COUNT(*) FROM ia) inj_aircraft, (SELECT COUNT(*) FROM ia JOIN a USING (EV_ID, AIRCRAFT_KEY)) inj_ac_in_aircraft,
       (SELECT MIN(LEFT(EV_ID,4)) FROM i) evid_y0, (SELECT MAX(LEFT(EV_ID,4)) FROM i) evid_y1,
       (SELECT MIN(LCHG_DATE) FROM i) lchg0, (SELECT MAX(LCHG_DATE) FROM i) lchg1,
       (SELECT MAX(d) FROM m) lchg_mode, (SELECT MAX(k) FROM m) lchg_mode_n,
       (SELECT COUNT_IF(LCHG_USERID = 'None' OR LCHG_USERID IS NULL) FROM i) userid_none;

-- S09 NTSB injury: does TOTL equal the sum of the other levels, and do the per-person deaths match the events table's death count
WITH p AS (
  SELECT EV_ID, AIRCRAFT_KEY, INJ_PERSON_CATEGORY c,
         SUM(IFF(INJURY_LEVEL <> 'TOTL', COALESCE(INJ_PERSON_COUNT,0), 0)) parts,
         MAX(IFF(INJURY_LEVEL = 'TOTL', INJ_PERSON_COUNT, NULL)) totl, COUNT_IF(INJURY_LEVEL = 'TOTL') has_totl,
         SUM(IFF(INJURY_LEVEL = 'FATL', COALESCE(INJ_PERSON_COUNT,0), 0)) f
  FROM LIBRARY_MARTS.TRANSPORT.TRANSPORT__FED_NTSB_AVIATION_INJURY GROUP BY 1,2,3),
ev AS (SELECT EV_ID, SUM(f) f FROM p GROUP BY 1),
e AS (SELECT EV_ID, TRY_TO_NUMBER(TO_VARCHAR(INJ_TOT_F)) ef, TRY_TO_NUMBER(TO_VARCHAR(INJ_F_GRND)) gf, EV_HIGHEST_INJURY h
      FROM LIBRARY_MARTS.TRANSPORT.TRANSPORT__FED_NTSB_AVIATION_EVENTS)
SELECT 'groups' k, COUNT(*) n, COUNT_IF(has_totl > 0) a, COUNT_IF(totl = parts) b, COUNT_IF(totl <> parts) c, COUNT_IF(has_totl > 0 AND totl IS NULL) d
FROM p
UNION ALL
SELECT 'events', COUNT(*), COUNT_IF(COALESCE(ev.f,0) = COALESCE(e.ef,0)), COUNT_IF(COALESCE(ev.f,0) <> COALESCE(e.ef,0)),
       COUNT_IF(COALESCE(ev.f,0) + COALESCE(e.gf,0) = COALESCE(e.ef,0) AND COALESCE(ev.f,0) <> COALESCE(e.ef,0)), SUM(ev.f) - SUM(e.ef)
FROM ev JOIN e USING (EV_ID);
