-- S10 Earthquakes: every event in the Permian box plus central Oklahoma and south Kansas boxes - event-level extract for local math
SELECT ID, TIME, TRY_TO_DOUBLE(LATITUDE) lat, TRY_TO_DOUBLE(LONGITUDE) lon, DEPTH, MAG, MAGTYPE, NET, STATUS, TYPE, PLACE, UPDATED,
       CASE WHEN TRY_TO_DOUBLE(LATITUDE) BETWEEN 30.5 AND 33.8 AND TRY_TO_DOUBLE(LONGITUDE) BETWEEN -105.0 AND -100.5 THEN 'PERMIAN'
            WHEN TRY_TO_DOUBLE(LATITUDE) BETWEEN 33.6 AND 37.0 AND TRY_TO_DOUBLE(LONGITUDE) BETWEEN -99.5 AND -96.0 THEN 'OK_CENTRAL'
            ELSE 'KS_SOUTH' END zone
FROM LIBRARY_MARTS.SCIENCE.SCIENCE__FED_USGS_EARTHQUAKES
WHERE (TRY_TO_DOUBLE(LATITUDE) BETWEEN 30.5 AND 33.8 AND TRY_TO_DOUBLE(LONGITUDE) BETWEEN -105.0 AND -100.5)
   OR (TRY_TO_DOUBLE(LATITUDE) BETWEEN 33.6 AND 37.0 AND TRY_TO_DOUBLE(LONGITUDE) BETWEEN -99.5 AND -96.0)
   OR (TRY_TO_DOUBLE(LATITUDE) BETWEEN 36.9 AND 37.6 AND TRY_TO_DOUBLE(LONGITUDE) BETWEEN -98.8 AND -97.0)
ORDER BY TIME;

-- S11 NTSB injury: people by kind of flight, aircraft category, year, US or not, person category and injury level (TOTL left out)
WITH ac AS (
  SELECT EV_ID, AIRCRAFT_KEY, ACFT_CATEGORY, FAR_PART, TYPE_FLY,
    CASE WHEN FAR_PART='121' THEN '121 airline'
      WHEN FAR_PART='135' AND AIR_MEDICAL='Y' THEN '135 air medical' WHEN FAR_PART='135' AND SITE_SEEING='Y' THEN '135 air tour'
      WHEN FAR_PART='135' THEN '135 charter/cargo other' WHEN FAR_PART LIKE '091%' AND AIR_MEDICAL='Y' THEN '91 air medical'
      WHEN FAR_PART LIKE '091%' AND SITE_SEEING='Y' THEN '91 air tour (LOA)' WHEN FAR_PART='091K' THEN '91K fractional'
      WHEN FAR_PART='091' AND TYPE_FLY='SKYD' THEN '91 skydiving' WHEN FAR_PART='091' AND TYPE_FLY='INST' THEN '91 instruction'
      WHEN FAR_PART='091' AND HOMEBUILT='Y' THEN '91 homebuilt' WHEN FAR_PART='091' THEN '91 other private' WHEN FAR_PART='137' THEN '137 crop dusting'
      WHEN FAR_PART='133' THEN '133 external load' WHEN FAR_PART='PUBU' THEN 'public use' WHEN FAR_PART='107' THEN '107 drone'
      WHEN FAR_PART='129' THEN '129 foreign airline' ELSE 'other/unknown '||COALESCE(FAR_PART,'null') END grp
  FROM LIBRARY_MARTS.TRANSPORT.TRANSPORT__FED_NTSB_AVIATION_AIRCRAFT),
e AS (SELECT EV_ID, EV_TYPE, YEAR(EV_DATE) yr, IFF(EV_COUNTRY='USA','US','nonUS') ctry FROM LIBRARY_MARTS.TRANSPORT.TRANSPORT__FED_NTSB_AVIATION_EVENTS)
SELECT e.ctry, ac.grp, ac.ACFT_CATEGORY cat, e.yr, i.INJ_PERSON_CATEGORY who, i.INJURY_LEVEL lvl,
       SUM(COALESCE(i.INJ_PERSON_COUNT,0)) people, COUNT(DISTINCT i.EV_ID, i.AIRCRAFT_KEY) aircraft,
       COUNT(DISTINCT IFF(i.INJ_PERSON_COUNT > 0, i.EV_ID||'-'||i.AIRCRAFT_KEY, NULL)) aircraft_with_any
FROM LIBRARY_MARTS.TRANSPORT.TRANSPORT__FED_NTSB_AVIATION_INJURY i
JOIN e ON e.EV_ID = i.EV_ID
LEFT JOIN ac ON ac.EV_ID = i.EV_ID AND ac.AIRCRAFT_KEY = i.AIRCRAFT_KEY
WHERE i.INJURY_LEVEL <> 'TOTL'
GROUP BY 1,2,3,4,5,6 ORDER BY 1,2,3,4,5,6;
