-- S12 NTSB injury: per-aircraft injury pivot for US Part 121 flights, every balloon, and every aircraft with a lap child - extract for local math
WITH i AS (
  SELECT EV_ID, AIRCRAFT_KEY,
    SUM(IFF(INJ_PERSON_CATEGORY='Cabi' AND INJURY_LEVEL='FATL', INJ_PERSON_COUNT, 0)) cabi_f, SUM(IFF(INJ_PERSON_CATEGORY='Cabi' AND INJURY_LEVEL='SERS', INJ_PERSON_COUNT, 0)) cabi_s,
    SUM(IFF(INJ_PERSON_CATEGORY='Cabi' AND INJURY_LEVEL='MINR', INJ_PERSON_COUNT, 0)) cabi_m, SUM(IFF(INJ_PERSON_CATEGORY='Cabi' AND INJURY_LEVEL='NONE', INJ_PERSON_COUNT, 0)) cabi_n,
    SUM(IFF(INJ_PERSON_CATEGORY='Flig' AND INJURY_LEVEL='FATL', INJ_PERSON_COUNT, 0)) flig_f, SUM(IFF(INJ_PERSON_CATEGORY='Flig' AND INJURY_LEVEL='SERS', INJ_PERSON_COUNT, 0)) flig_s,
    SUM(IFF(INJ_PERSON_CATEGORY='Flig' AND INJURY_LEVEL='MINR', INJ_PERSON_COUNT, 0)) flig_m, SUM(IFF(INJ_PERSON_CATEGORY='Flig' AND INJURY_LEVEL='NONE', INJ_PERSON_COUNT, 0)) flig_n,
    SUM(IFF(INJ_PERSON_CATEGORY='Pass' AND INJURY_LEVEL='FATL', INJ_PERSON_COUNT, 0)) pass_f, SUM(IFF(INJ_PERSON_CATEGORY='Pass' AND INJURY_LEVEL='SERS', INJ_PERSON_COUNT, 0)) pass_s,
    SUM(IFF(INJ_PERSON_CATEGORY='Pass' AND INJURY_LEVEL='MINR', INJ_PERSON_COUNT, 0)) pass_m, SUM(IFF(INJ_PERSON_CATEGORY='Pass' AND INJURY_LEVEL='NONE', INJ_PERSON_COUNT, 0)) pass_n,
    SUM(IFF(INJ_PERSON_CATEGORY='LapC' AND INJURY_LEVEL='FATL', INJ_PERSON_COUNT, 0)) lapc_f, SUM(IFF(INJ_PERSON_CATEGORY='LapC' AND INJURY_LEVEL='SERS', INJ_PERSON_COUNT, 0)) lapc_s,
    SUM(IFF(INJ_PERSON_CATEGORY='LapC' AND INJURY_LEVEL='MINR', INJ_PERSON_COUNT, 0)) lapc_m, SUM(IFF(INJ_PERSON_CATEGORY='LapC' AND INJURY_LEVEL='NONE', INJ_PERSON_COUNT, 0)) lapc_n,
    MAX(LCHG_DATE) lchg
  FROM LIBRARY_MARTS.TRANSPORT.TRANSPORT__FED_NTSB_AVIATION_INJURY WHERE INJURY_LEVEL <> 'TOTL' GROUP BY 1,2)
SELECT e.EV_ID, e.NTSB_NO, e.EV_TYPE, e.EV_DATE, e.EV_CITY, e.EV_STATE, e.EV_COUNTRY, e.EV_HIGHEST_INJURY,
       ac.AIRCRAFT_KEY, ac.FAR_PART, ac.ACFT_CATEGORY, ac.ACFT_MAKE, ac.ACFT_MODEL, ac.REGIS_NO, ac.DAMAGE, ac.PHASE_FLT_SPEC,
       ac.OPER_NAME, ac.OWNER_ACFT, ac.OPER_SCHED, ac.OPER_PAX_CARGO, ac.SITE_SEEING, ac.TYPE_FLY, i.*
FROM i
JOIN LIBRARY_MARTS.TRANSPORT.TRANSPORT__FED_NTSB_AVIATION_EVENTS e ON e.EV_ID = i.EV_ID
JOIN LIBRARY_MARTS.TRANSPORT.TRANSPORT__FED_NTSB_AVIATION_AIRCRAFT ac ON ac.EV_ID = i.EV_ID AND ac.AIRCRAFT_KEY = i.AIRCRAFT_KEY
WHERE (ac.FAR_PART = '121' AND e.EV_COUNTRY = 'USA') OR ac.ACFT_CATEGORY = 'BALL'
   OR (i.lapc_f + i.lapc_s + i.lapc_m + i.lapc_n) > 0 OR ac.FAR_PART = '129'
ORDER BY e.EV_DATE;

-- S13 FracFocus: frac jobs by year in the New Mexico and Texas parts of the Delaware Basin, next to the quake clusters (a box count, not a key join)
SELECT YEAR(JOB_START_DATE) yr,
       CASE WHEN LATITUDE BETWEEN 32.1 AND 32.8 AND LONGITUDE BETWEEN -104.8 AND -104.2 THEN 'NM west of 104.2W (Hope-Atoka-Whites City)'
            WHEN LATITUDE BETWEEN 32.0 AND 32.8 AND LONGITUDE BETWEEN -104.2 AND -103.064 THEN 'NM east (Carlsbad-Malaga-Jal)'
            WHEN LATITUDE BETWEEN 30.8 AND 32.0 AND LONGITUDE BETWEEN -104.8 AND -103.0 THEN 'TX Delaware (Culberson-Reeves-Loving-Pecos)'
            ELSE 'other' END area,
       COUNT(DISTINCT DISCLOSURE_ID) jobs, COUNT(DISTINCT API_NUMBER) wells, ROUND(SUM(TOTAL_BASE_WATER_VOLUME)/1e6,1) water_mgal,
       MAX(JOB_START_DATE) last_job
FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_FRACFOCUS_DISCLOSURE_LIST
WHERE LATITUDE BETWEEN 30.8 AND 32.8 AND LONGITUDE BETWEEN -104.8 AND -103.0 AND YEAR(JOB_START_DATE) >= 2010
GROUP BY 1,2 ORDER BY 2,1;
