-- S15 Earthquakes: every event of any type in northwest Louisiana and east Texas (lat 30.5-33.5, lon -95.5 to -91.5), whole catalog
SELECT ID, TIME, TRY_TO_DOUBLE(LATITUDE) lat, TRY_TO_DOUBLE(LONGITUDE) lon, DEPTH, MAG, MAGTYPE, NET, STATUS, TYPE, PLACE, UPDATED,
       NST, GAP, RMS, HORIZONTALERROR, DEPTHERROR, LOCATIONSOURCE, MAGSOURCE
FROM LIBRARY_MARTS.SCIENCE.SCIENCE__FED_USGS_EARTHQUAKES
WHERE TRY_TO_DOUBLE(LATITUDE) BETWEEN 30.5 AND 33.5 AND TRY_TO_DOUBLE(LONGITUDE) BETWEEN -95.5 AND -91.5
ORDER BY TIME;
