-- S16 FracFocus: frack disclosures inside the two new quake boxes (Red River Parish LA; west of Carlsbad NM), by form version and operator - context only, the mart has no job dates
SELECT CASE WHEN LATITUDE BETWEEN 31.8 AND 32.5 AND LONGITUDE BETWEEN -93.55 AND -93.25 THEN 'LA Red River box'
            WHEN LATITUDE BETWEEN 32.1 AND 32.8 AND LONGITUDE BETWEEN -104.8 AND -104.2 THEN 'NM west of Carlsbad box' END box,
       FF_VERSION, OPERATOR_NAME, COUNT(DISTINCT DISCLOSURE_ID) jobs, COUNT(DISTINCT API_NUMBER) wells,
       ROUND(SUM(TOTAL_BASE_WATER_VOLUME)/1e6,1) water_mgal, COUNT_IF(JOB_START_DATE IS NOT NULL) dated,
       LISTAGG(DISTINCT COUNTY_NAME, ',') counties
FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_FRACFOCUS_DISCLOSURE_LIST
WHERE (LATITUDE BETWEEN 31.8 AND 32.5 AND LONGITUDE BETWEEN -93.55 AND -93.25)
   OR (LATITUDE BETWEEN 32.1 AND 32.8 AND LONGITUDE BETWEEN -104.8 AND -104.2)
GROUP BY 1,2,3 ORDER BY 1,2, jobs DESC;
