import pandas as pd, numpy as np
pd.set_option('display.width',260); pd.set_option('display.max_columns',50); pd.set_option('display.max_colwidth',34)
d=pd.read_pickle('s12.pkl')
print('PHASE filled', d.PHASE_FLT_SPEC.notna().sum(), 'of', len(d))
b=d[(d.ACFT_CATEGORY=='BALL')&(d.EV_COUNTRY=='USA')].copy()
b['pass_aboard']=b[['PASS_F','PASS_S','PASS_M','PASS_N']].sum(axis=1)
b['op']=b.OPER_NAME.fillna('').where(~b.OPER_NAME.isin(['None','Pilot','PILOT']),'')
b['op']=b.op.where(b.op!='',b.OWNER_ACFT.fillna(''))
b['opn']=b.op.str.upper().str.replace(r'[^A-Z ]','',regex=True).str.replace(r'\b(INC|LLC|CORP|CORPORATION|CO|COMPANY|DBA|THE|LTD)\b','',regex=True).str.split().str[:3].str.join(' ')
print('US balloon aircraft',len(b),'far',b.FAR_PART.value_counts().to_dict(),'site_seeing',b.SITE_SEEING.value_counts().to_dict())
print('pass aboard',b.pass_aboard.sum(),'pass serious',b.PASS_S.sum(),'pass fatal',b.PASS_F.sum(),'aircraft w pass serious',(b.PASS_S>0).sum(),'median pass aboard',b.pass_aboard.median())
print(b.PASS_S.value_counts().sort_index().to_dict())
o=b.groupby('opn').agg(acc=('EV_ID','size'),acc_pass_s=('PASS_S',lambda s:(s>0).sum()),pass_s=('PASS_S','sum'),pass_f=('PASS_F','sum'),aboard=('pass_aboard','sum'),states=('EV_STATE',lambda s:','.join(sorted(set(s.dropna())))),y0=('yr','min'),y1=('yr','max'))
print(o.sort_values(['acc_pass_s','pass_s'],ascending=False).head(20).to_string())
print(b.EV_STATE.value_counts().head(10).to_dict())
st=b.groupby('EV_STATE').agg(acc=('EV_ID','size'),pass_s=('PASS_S','sum'),aboard=('pass_aboard','sum')).sort_values('acc',ascending=False).head(10); print(st.to_string())
l=d[(d[['LAPC_F','LAPC_S','LAPC_M','LAPC_N']].sum(axis=1)>0)]
print('lap-child aircraft',len(l),'US',(l.EV_COUNTRY=='USA').sum())
print(l[l.LAPC_F+l.LAPC_S>0][['EV_DATE','EV_CITY','EV_STATE','EV_COUNTRY','FAR_PART','ACFT_MAKE','ACFT_MODEL','OPER_NAME','LAPC_F','LAPC_S','LAPC_M','LAPC_N','PASS_F','PASS_S','PASS_M','PASS_N']].to_string())
