{{ config(tags=['spine_generated']) }}

-- GRAIN: one row per place (GEOM is unique)
-- SPINE_ENTITY: place  (natural_key: GEOMETRY)
-- Generated by scripts/generate_staging_models.py from SOURCE_REGISTRY -- deterministic,
-- no LLM.
-- CASTS: 3 of 23 columns, from landing_column_profile_2026-09-19.tsv. A column is cast only
-- when every filled value in the sample parsed. try_ casts: a value that does not
-- parse reads NULL. The natural key and join-key columns stay TEXT.
--   mileage: float
--   objectid: ID: whole numbers, over 90% distinct -- stays TEXT, '.0' tail removed
--   track_num: integer
-- spine_entity 'place' has no connect/ resolver yet (see connect/spine_entity.py) -- no SPINE_ENTITY_ID emitted.
-- landing table's ingestion timestamp is named INGESTED_AT (no leading underscore) rather than the usual _INGESTED_AT -- confirmed via INFORMATION_SCHEMA, not assumed.

with source as (

    select * from {{ source('ripple_raw', 'PORTAL_CKA_WPRDC_ALLEGHENY_B62D63F711') }}
    qualify row_number() over (partition by "GEOMETRY" order by INGESTED_AT desc) = 1

),

renamed as (

    select
        {{ null_junk('"BASE_COLOR"') }} as base_color,
        {{ null_junk('"BLAZE_COLOR_FULL"') }} as blaze_color_full,
        {{ null_junk('"BLAZE_COLOR_SHORT"') }} as blaze_color_short,
        {{ null_junk('"CAP_COLOR"') }} as cap_color,
        {{ null_junk('"CONFIGURATION"') }} as configuration,
        {{ null_junk('"DASH_COLOR"') }} as dash_color,
        {{ null_junk('"DIFFICULTY"') }} as difficulty,
        {{ null_junk('"DOT_COLOR"') }} as dot_color,
        {{ null_junk('"GLOBALID"') }} as globalid,
        {{ null_junk('"IMAGE_LINK"') }} as image_link,
        {{ stg_float('"MILEAGE"') }} as mileage,
        {{ stg_id_text('"OBJECTID"') }} as objectid,
        {{ null_junk('"PARK_NAME"') }} as park_name,
        {{ null_junk('"PARK_NAME_FULL"') }} as park_name_full,
        {{ null_junk('"PARK_NAME_SHORT"') }} as park_name_short,
        {{ null_junk('"SERVICE_ROAD"') }} as service_road,
        {{ null_junk('"SURFACE"') }} as surface,
        {{ null_junk('"TRACK"') }} as track,
        {{ stg_int('"TRACK_NUM"') }} as track_num,
        {{ null_junk('"TRAIL_ID"') }} as trail_id,
        {{ null_junk('"TRAIL_NAME"') }} as trail_name,
        {{ null_junk('"TRAIL_STATUS"') }} as trail_status,
        {{ null_junk('"GEOMETRY"') }} as geometry,
        INGESTED_AT as _loaded_at,
        'https://data.wprdc.org/dataset/allegheny-county-trails-locations' as _source_url

    from source

)

select * from renamed
