-- S01 QCEW profile: year x aggregation level, rows, areas, hidden rows, key repeats, size code, quarter
SELECT YEAR, AGGREGATION_LEVEL_CODE agg, COUNT(*) n, COUNT(DISTINCT AREA_FIPS) areas,
       COUNT(DISTINCT AREA_FIPS, OWNERSHIP_CODE, INDUSTRY_CODE) keys_,
       COUNT_IF(DISCLOSURE_CODE = 'N') hidden, COUNT_IF(ANNUAL_AVG_EMPLOYMENT = 0) emp0,
       SUM(ANNUAL_AVG_EMPLOYMENT) emp, ARRAY_AGG(DISTINCT OWNERSHIP_CODE) owns,
       COUNT(DISTINCT SIZE_CODE) sizes, COUNT(DISTINCT QUARTER) qtrs, MIN(INDUSTRY_CODE) ind0, MAX(INDUSTRY_CODE) ind1
FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_BLS_QCEW
GROUP BY 1,2 ORDER BY 1,2;

-- S02 IRS revocation: date text shapes, reinstatement flag vs date, ranges
SELECT REGEXP_REPLACE(REVOCATION_DATE,'[0-9]','9') rev_shape, REGEXP_REPLACE(COALESCE(REINSTATEMENT_DATE,'<null>'),'[0-9]','9') rein_shape,
       WAS_REINSTATED, COUNT(*) n, COUNT(DISTINCT EIN) eins, MIN(REVOCATION_DATE) r0, MAX(REVOCATION_DATE) r1,
       MIN(REINSTATEMENT_DATE) i0, MAX(REINSTATEMENT_DATE) i1, COUNT_IF(LENGTH(EIN) <> 9) ein_not9, COUNT_IF(EIN = '000000000') ein0,
       MIN(_LOADED_AT) l0, MAX(_LOADED_AT) l1, ANY_VALUE(_SOURCE_URL) src
FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_IRS_REVOCATION
GROUP BY 1,2,3 ORDER BY n DESC;

-- S03 Treasury debt outstanding: the whole table (237 rows)
SELECT * FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_TREASURY_DEBT_OUTSTANDING ORDER BY RECORD_DATE;

-- S04 USAspending toptier agencies: the whole table (111 rows)
SELECT * FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_USASPENDING_TOPTIER_AGENCIES ORDER BY BUDGET_AUTHORITY_AMOUNT DESC NULLS LAST;

-- S05 IRS 990: fill per column, year range, form types, source
SELECT COUNT(*) n, COUNT(DISTINCT EIN) eins, COUNT(ORGANIZATION_NAME) names, COUNT(TAX_PERIOD_BEGIN_DATE) tpb, COUNT(TAX_PERIOD_END_DATE) tpe,
       ARRAY_AGG(DISTINCT FORM_TYPE) forms, MIN(TAX_YEAR) ty0, MAX(TAX_YEAR) ty1, COUNT(GROSS_RECEIPTS_AMT) gross, COUNT(TOTAL_REVENUE_AMT) rev,
       COUNT(TOTAL_EXPENSES_AMT) exp_, COUNT(OFFICER_COMPENSATION_AMT) offc, COUNT(NULLIF(STATE,'')) st, COUNT(NULLIF(ZIP_CODE,'')) zip,
       COUNT(NULLIF(EXEMPTION_CODE,'')) exc, COUNT(DISTINCT _SOURCE_URL) srcs, ANY_VALUE(_SOURCE_URL) src,
       MIN(_LOADED_AT) l0, MAX(_LOADED_AT) l1, ARRAY_AGG(DISTINCT LEFT(EIN,2)) WITHIN GROUP (ORDER BY LEFT(EIN,2)) ein_prefixes
FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_IRS_990;
