-- S06 Toptier time check: federal assistance obligations by awarding agency and fiscal year, Oct-Jun window vs full year, FY2019-FY2026
SELECT AWARDING_AGENCY_CODE code, ANY_VALUE(AWARDING_AGENCY_NAME) agency, ACTION_DATE_FISCAL_YEAR fy,
       SUM(IFF(MONTH(ACTION_DATE) NOT IN (7,8,9), FEDERAL_ACTION_OBLIGATION, 0)) oblig_oct_jun,
       SUM(FEDERAL_ACTION_OBLIGATION) oblig_full,
       COUNT(DISTINCT IFF(MONTH(ACTION_DATE) NOT IN (7,8,9) AND ACTION_TYPE_CODE = 'A', ASSISTANCE_AWARD_UNIQUE_KEY, NULL)) new_awards_oct_jun,
       SUM(IFF(MONTH(ACTION_DATE) NOT IN (7,8,9) AND ACTION_TYPE_CODE = 'A', FEDERAL_ACTION_OBLIGATION, 0)) new_oblig_oct_jun,
       COUNT(*) n, MAX(ACTION_DATE) last_action
FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_USASPENDING_ASSISTANCE_FULL
WHERE ACTION_DATE_FISCAL_YEAR >= 2019
GROUP BY 1,3 ORDER BY 1,3;

-- S07 Toptier time check: contract obligations by awarding agency and fiscal year, Oct-Jun window, FY2019-FY2026 (R2, text dates parsed)
WITH t AS (
  SELECT AWARDING_AGENCY_NAME agency, TRY_TO_DATE(ACTION_DATE) d, TRY_TO_NUMBER(FEDERAL_ACTION_OBLIGATION, 38, 2) amt
  FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_USASPENDING_CONTRACTS_FULL_R2
  WHERE LEFT(ACTION_DATE, 4) >= '2018'
)
SELECT agency, YEAR(DATEADD(month, 3, d)) fy,
       SUM(IFF(MONTH(d) NOT IN (7,8,9), amt, 0)) oblig_oct_jun, SUM(amt) oblig_full, COUNT(*) n,
       COUNT_IF(d IS NULL) bad_date, COUNT_IF(amt IS NULL) bad_amt, MAX(d) last_action
FROM t
GROUP BY 1,2 HAVING fy >= 2019 OR fy IS NULL ORDER BY 1,2;

-- S08 QCEW private jobs by state x industry (4- and 6-digit NAICS) plus state private totals, 2022, for the OSHA coverage join
SELECT AREA_FIPS, AGGREGATION_LEVEL_CODE agg, INDUSTRY_CODE, DISCLOSURE_CODE, ANNUAL_AVG_ESTABLISHMENTS estabs,
       ANNUAL_AVG_EMPLOYMENT emp, AVG_ANNUAL_PAY pay
FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_BLS_QCEW
WHERE OWNERSHIP_CODE = '5' AND AGGREGATION_LEVEL_CODE IN ('51','56','58');

-- S09 OSHA 300A worksite summaries 2023 and 2024, one row per worksite (latest submission), rolled up by state x NAICS x employer type
WITH u AS (
  SELECT '2023' yr, ESTABLISHMENT_ID, STATE, NAICS_CODE, ESTABLISHMENT_TYPE, SIZE, ANNUAL_AVERAGE_EMPLOYEES emp, TOTAL_HOURS_WORKED hrs, TOTAL_DAFW_CASES dafw, TOTAL_DEATHS deaths, CREATED_TIMESTAMP ts
  FROM LIBRARY_MARTS.LABOR.LABOR__FED_OSHA_ITA_300A_SUMMARY_2023
  UNION ALL
  SELECT '2024', ESTABLISHMENT_ID, STATE, NAICS_CODE, ESTABLISHMENT_TYPE, SIZE, ANNUAL_AVERAGE_EMPLOYEES, TOTAL_HOURS_WORKED, TOTAL_DAFW_CASES, TOTAL_DEATHS, CREATED_TIMESTAMP
  FROM LIBRARY_MARTS.LABOR.LABOR__FED_OSHA_ITA_300A_SUMMARY_2024
), d AS (
  SELECT * FROM u QUALIFY ROW_NUMBER() OVER (PARTITION BY yr, ESTABLISHMENT_ID ORDER BY ts DESC NULLS LAST) = 1
)
SELECT yr, UPPER(TRIM(STATE)) st, NAICS_CODE naics, ESTABLISHMENT_TYPE etype, COUNT(*) sites, SUM(emp) emp,
       COUNT_IF(emp >= 20) sites20, SUM(IFF(emp >= 20, emp, 0)) emp20, SUM(hrs) hrs, SUM(dafw) dafw, SUM(deaths) deaths
FROM d GROUP BY 1,2,3,4;

-- S10 QCEW traps: YOY columns, pay consistency, county total vs ownership sum, hidden rows that still count workplaces
WITH c70 AS (SELECT AREA_FIPS, ANNUAL_AVG_EMPLOYMENT emp FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_BLS_QCEW WHERE AGGREGATION_LEVEL_CODE = '70'),
     c71 AS (SELECT AREA_FIPS, SUM(ANNUAL_AVG_EMPLOYMENT) emp, COUNT_IF(DISCLOSURE_CODE = 'N') hid FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_BLS_QCEW WHERE AGGREGATION_LEVEL_CODE = '71' GROUP BY 1),
     q AS (SELECT * FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_BLS_QCEW)
SELECT 'yoy' k, COUNT(*) n, COUNT_IF(YOY_EMPLOYMENT_PCT_CHANGE = 0) v1, COUNT_IF(YOY_EMPLOYMENT_PCT_CHANGE IS NULL) v2,
       COUNT_IF(YOY_EMPLOYMENT_PCT_CHANGE = 0 AND DISCLOSURE_CODE = 'N') v3, COUNT_IF(YOY_WAGES_PCT_CHANGE = 0) v4, NULL v5
FROM q
UNION ALL
SELECT 'hidden_rows', COUNT_IF(DISCLOSURE_CODE = 'N'), COUNT_IF(DISCLOSURE_CODE = 'N' AND ANNUAL_AVG_ESTABLISHMENTS > 0),
       COUNT_IF(DISCLOSURE_CODE = 'N' AND ANNUAL_AVG_EMPLOYMENT > 0), COUNT_IF(DISCLOSURE_CODE = 'N' AND TOTAL_ANNUAL_WAGES > 0),
       COUNT_IF(COALESCE(DISCLOSURE_CODE,'') NOT IN ('N','') ), COUNT_IF(DISCLOSURE_CODE IS NULL)
FROM q
UNION ALL
SELECT 'pay_check', COUNT_IF(ANNUAL_AVG_EMPLOYMENT > 0),
       COUNT_IF(ANNUAL_AVG_EMPLOYMENT > 0 AND ABS(AVG_ANNUAL_PAY - TOTAL_ANNUAL_WAGES / ANNUAL_AVG_EMPLOYMENT) > 2),
       COUNT_IF(ANNUAL_AVG_EMPLOYMENT > 0 AND AVG_ANNUAL_PAY > 1000000), MAX(AVG_ANNUAL_PAY), MAX(ANNUAL_AVG_WEEKLY_WAGE), COUNT_IF(ANNUAL_AVG_EMPLOYMENT > 0 AND AVG_ANNUAL_PAY < 5000)
FROM q
UNION ALL
SELECT 'county_total_vs_owner_sum', COUNT(*), COUNT_IF(c71.emp IS NULL), COUNT_IF(c70.emp = c71.emp), COUNT_IF(c70.emp > c71.emp AND c71.hid > 0),
       COUNT_IF(c70.emp <> c71.emp AND c71.hid = 0), SUM(c70.emp - c71.emp)
FROM c70 LEFT JOIN c71 USING (AREA_FIPS);
