-- S11 Toptier time check, rerun of S07 with casts that accept the real column types: contract obligations by agency and fiscal year, Oct-Jun window
WITH t AS (
  SELECT AWARDING_AGENCY_NAME agency, TRY_TO_DATE(ACTION_DATE::VARCHAR) d, TRY_TO_DOUBLE(FEDERAL_ACTION_OBLIGATION::VARCHAR) amt
  FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_USASPENDING_CONTRACTS_FULL_R2
  WHERE LEFT(ACTION_DATE::VARCHAR, 4) >= '2018'
)
SELECT agency, YEAR(DATEADD(month, 3, d)) fy,
       SUM(IFF(MONTH(d) NOT IN (7,8,9), amt, 0)) oblig_oct_jun, SUM(amt) oblig_full, COUNT(*) n,
       COUNT_IF(d IS NULL) bad_date, COUNT_IF(amt IS NULL) bad_amt, MAX(d) last_action
FROM t
GROUP BY 1,2 HAVING fy >= 2019 OR fy IS NULL ORDER BY 1,2;

-- S12 OSHA 300A 2023 and 2024 again, now with site-level sanity filters (1-50,000 workers, 500-4,500 hours per worker), private employers only
WITH u AS (
  SELECT '2023' yr, ESTABLISHMENT_ID, STATE, NAICS_CODE, ESTABLISHMENT_TYPE, ANNUAL_AVERAGE_EMPLOYEES emp, TOTAL_HOURS_WORKED hrs, TOTAL_DAFW_CASES dafw, CREATED_TIMESTAMP ts
  FROM LIBRARY_MARTS.LABOR.LABOR__FED_OSHA_ITA_300A_SUMMARY_2023
  UNION ALL
  SELECT '2024', ESTABLISHMENT_ID, STATE, NAICS_CODE, ESTABLISHMENT_TYPE, ANNUAL_AVERAGE_EMPLOYEES, TOTAL_HOURS_WORKED, TOTAL_DAFW_CASES, CREATED_TIMESTAMP
  FROM LIBRARY_MARTS.LABOR.LABOR__FED_OSHA_ITA_300A_SUMMARY_2024
), d AS (
  SELECT * FROM u QUALIFY ROW_NUMBER() OVER (PARTITION BY yr, ESTABLISHMENT_ID ORDER BY ts DESC NULLS LAST) = 1
)
SELECT yr, UPPER(TRIM(STATE)) st, NAICS_CODE naics,
       COUNT(*) sites_all, COUNT_IF(emp BETWEEN 1 AND 50000 AND hrs / NULLIF(emp,0) BETWEEN 500 AND 4500) sites_ok,
       SUM(IFF(emp BETWEEN 1 AND 50000 AND hrs / NULLIF(emp,0) BETWEEN 500 AND 4500, emp, 0)) emp_ok,
       SUM(IFF(emp BETWEEN 20 AND 50000 AND hrs / NULLIF(emp,0) BETWEEN 500 AND 4500, emp, 0)) emp20_ok,
       COUNT_IF(emp BETWEEN 20 AND 50000 AND hrs / NULLIF(emp,0) BETWEEN 500 AND 4500) sites20_ok,
       SUM(IFF(emp BETWEEN 1 AND 50000 AND hrs / NULLIF(emp,0) BETWEEN 500 AND 4500, dafw, 0)) dafw_ok
FROM d WHERE ESTABLISHMENT_TYPE = '1'
GROUP BY 1,2,3;
