-- S13 NSF new grants by fiscal year, month and awarding office, FY2022-FY2026 (does the drop survive the Oct-Nov 2025 shutdown and span divisions?)
SELECT ACTION_DATE_FISCAL_YEAR fy, MONTH(ACTION_DATE) mo, AWARDING_OFFICE_NAME office,
       COUNT(DISTINCT IFF(ACTION_TYPE_CODE = 'A', ASSISTANCE_AWARD_UNIQUE_KEY, NULL)) new_awards,
       SUM(IFF(ACTION_TYPE_CODE = 'A', FEDERAL_ACTION_OBLIGATION, 0)) new_oblig,
       SUM(FEDERAL_ACTION_OBLIGATION) all_oblig, SUM(IFF(FEDERAL_ACTION_OBLIGATION < 0, FEDERAL_ACTION_OBLIGATION, 0)) deobligated
FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_USASPENDING_ASSISTANCE_FULL
WHERE AWARDING_AGENCY_CODE = '049' AND ACTION_DATE_FISCAL_YEAR >= 2022
GROUP BY 1,2,3;

-- S14 DHS contracts Oct-Jun: by sub-agency FY2023-FY2026, plus FY2026 top 25 recipients (is the jump a few awards?)
WITH t AS (
  SELECT AWARDING_SUB_AGENCY_NAME sub, RECIPIENT_NAME rcp, CONTRACT_AWARD_UNIQUE_KEY k, TRY_TO_DATE(ACTION_DATE::VARCHAR) d,
         TRY_TO_DOUBLE(FEDERAL_ACTION_OBLIGATION::VARCHAR) amt, PRODUCT_OR_SERVICE_CODE_DESCRIPTION psc
  FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_USASPENDING_CONTRACTS_FULL_R2
  WHERE AWARDING_AGENCY_NAME = 'Department of Homeland Security' AND LEFT(ACTION_DATE::VARCHAR, 4) >= '2022'
), w AS (SELECT *, YEAR(DATEADD(month, 3, d)) fy FROM t WHERE MONTH(d) NOT IN (7,8,9))
SELECT 'sub' kind, fy, sub name_, NULL psc_, SUM(amt) oblig, COUNT(DISTINCT k) awards FROM w WHERE fy >= 2023 GROUP BY 2,3
UNION ALL
SELECT * FROM (
  SELECT 'rcp', fy, rcp || ' | ' || ANY_VALUE(sub), ANY_VALUE(psc), SUM(amt), COUNT(DISTINCT k) FROM w WHERE fy = 2026 GROUP BY 2, rcp ORDER BY 5 DESC LIMIT 25
);

-- S15 OSHA 300A hospital filings (NAICS 622): every VT, NM, HI, WY and TN row, plus rows whose names point at big VT, NM or HI hospitals filed anywhere
WITH u AS (
  SELECT '2023' yr, ESTABLISHMENT_ID, ESTABLISHMENT_NAME, COMPANY_NAME, CITY, STATE, ZIP_CODE, NAICS_CODE, ESTABLISHMENT_TYPE, ANNUAL_AVERAGE_EMPLOYEES emp, TOTAL_HOURS_WORKED hrs
  FROM LIBRARY_MARTS.LABOR.LABOR__FED_OSHA_ITA_300A_SUMMARY_2023
  UNION ALL
  SELECT '2024', ESTABLISHMENT_ID, ESTABLISHMENT_NAME, COMPANY_NAME, CITY, STATE, ZIP_CODE, NAICS_CODE, ESTABLISHMENT_TYPE, ANNUAL_AVERAGE_EMPLOYEES, TOTAL_HOURS_WORKED
  FROM LIBRARY_MARTS.LABOR.LABOR__FED_OSHA_ITA_300A_SUMMARY_2024
)
SELECT yr, UPPER(TRIM(STATE)) st, CITY, ESTABLISHMENT_NAME, COMPANY_NAME, NAICS_CODE, ESTABLISHMENT_TYPE, emp, hrs
FROM u
WHERE (NAICS_CODE LIKE '622%' AND UPPER(TRIM(STATE)) IN ('VT','NM','HI','WY','TN'))
   OR REGEXP_LIKE(UPPER(ESTABLISHMENT_NAME || ' ' || COALESCE(COMPANY_NAME,'')),
      '.*(UNIVERSITY OF VERMONT|UVM |RUTLAND REGIONAL|CENTRAL VERMONT|PRESBYTERIAN HEALTHCARE|PRESBYTERIAN HOSPITAL|LOVELACE|CHRISTUS ST|SAN JUAN REGIONAL|MEMORIAL MEDICAL CENTER.*LAS CRUCES|QUEEN.S MEDICAL|KAPIOLANI|STRAUB|HAWAII PACIFIC HEALTH|PALI MOMI|WILCOX|ADVENTIST HEALTH CASTLE|EASTERN NEW MEXICO|GERALD CHAMPION|MOUNTAIN VIEW REGIONAL|CARLSBAD MEDICAL).*')
ORDER BY st, emp DESC;
