-- S16 Fisher Sand & Gravel DHS contract rows FY2025-FY2026: repeats, ceilings, dates (does $13.35B hold up?)
SELECT CONTRACT_AWARD_UNIQUE_KEY k, AWARD_ID_PIID piid, ACTION_DATE, TRY_TO_DOUBLE(FEDERAL_ACTION_OBLIGATION::VARCHAR) amt,
       TRY_TO_DOUBLE(TOTAL_DOLLARS_OBLIGATED::VARCHAR) award_total, TRY_TO_DOUBLE(CURRENT_TOTAL_VALUE_OF_AWARD::VARCHAR) award_value,
       AWARD_TYPE, PRIMARY_PLACE_OF_PERFORMANCE_STATE_CODE pop_st, LEFT(TRANSACTION_DESCRIPTION, 120) descr, COUNT(*) OVER (PARTITION BY CONTRACT_AWARD_UNIQUE_KEY, ACTION_DATE, FEDERAL_ACTION_OBLIGATION) same_rows
FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_USASPENDING_CONTRACTS_FULL_R2
WHERE AWARDING_AGENCY_NAME = 'Department of Homeland Security' AND RECIPIENT_NAME ILIKE 'FISHER SAND%' AND LEFT(ACTION_DATE::VARCHAR, 4) >= '2024'
ORDER BY ACTION_DATE;

-- S17 OSHA 300A: biggest filers of any industry in VT, NM and HI (catches big hospitals filed under odd names or codes)
WITH u AS (
  SELECT '2023' yr, ESTABLISHMENT_NAME, COMPANY_NAME, CITY, STATE, NAICS_CODE, ESTABLISHMENT_TYPE, ANNUAL_AVERAGE_EMPLOYEES emp
  FROM LIBRARY_MARTS.LABOR.LABOR__FED_OSHA_ITA_300A_SUMMARY_2023
  UNION ALL
  SELECT '2024', ESTABLISHMENT_NAME, COMPANY_NAME, CITY, STATE, NAICS_CODE, ESTABLISHMENT_TYPE, ANNUAL_AVERAGE_EMPLOYEES
  FROM LIBRARY_MARTS.LABOR.LABOR__FED_OSHA_ITA_300A_SUMMARY_2024
)
SELECT yr, UPPER(TRIM(STATE)) st, CITY, ESTABLISHMENT_NAME, COMPANY_NAME, NAICS_CODE, ESTABLISHMENT_TYPE, emp
FROM u
WHERE (UPPER(TRIM(STATE)) = 'VT' AND emp >= 250) OR (UPPER(TRIM(STATE)) IN ('NM','HI') AND emp >= 700)
   OR (UPPER(TRIM(STATE)) IN ('VT','NM','HI') AND REGEXP_LIKE(UPPER(ESTABLISHMENT_NAME || ' ' || COALESCE(COMPANY_NAME,'')), '.*(MEDICAL CENTER|HOSPITAL|HEALTH).*') AND NAICS_CODE NOT LIKE '622%')
ORDER BY st, yr, emp DESC;
