-- S18 IRS revocation vs its near-twin ECONOMICS__FED_IRS_AUTO_REVOCATIONS: EIN overlap, date and reinstatement agreement
WITH a AS (
  SELECT EIN, COUNT(*) n, MAX(TRY_TO_DATE(REVOCATION_DATE)) rd1, MAX(TRY_TO_DATE(REINSTATEMENT_DATE)) ri
  FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_IRS_REVOCATION GROUP BY 1
), b AS (
  SELECT EIN, COUNT(*) n, MAX(REVOCATION_DATE) rd1, MAX(REINSTATEMENT_DATE) ri
  FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_IRS_AUTO_REVOCATIONS GROUP BY 1
)
SELECT COUNT(*) eins, COUNT_IF(a.EIN IS NULL) only_auto, COUNT_IF(b.EIN IS NULL) only_rev, COUNT_IF(a.EIN IS NOT NULL AND b.EIN IS NOT NULL) both_,
       COUNT_IF(a.rd1 = b.rd1) same_last_rev, COUNT_IF(a.ri IS NOT DISTINCT FROM b.ri AND a.EIN IS NOT NULL AND b.EIN IS NOT NULL) same_rein,
       COUNT_IF(a.ri IS NULL AND b.ri IS NOT NULL AND a.EIN IS NOT NULL) rein_only_auto, COUNT_IF(a.ri IS NOT NULL AND b.ri IS NULL AND b.EIN IS NOT NULL) rein_only_rev,
       MIN(IFF(a.EIN IS NULL, b.rd1, NULL)) only_auto_rd_min, MAX(IFF(a.EIN IS NULL, b.rd1, NULL)) only_auto_rd_max,
       COUNT_IF(a.EIN IS NULL AND b.rd1 > '2026-03-15') only_auto_after_mar15,
       MIN(IFF(b.EIN IS NULL, a.rd1, NULL)) only_rev_rd_min, MAX(IFF(b.EIN IS NULL, a.rd1, NULL)) only_rev_rd_max,
       COUNT_IF(a.n <> b.n) diff_rowcount, MAX(b.ri) auto_rein_max, MAX(a.ri) rev_rein_max
FROM a FULL OUTER JOIN b USING (EIN);

-- S19 IRS revocation time series: by revocation month and by posting month, 501(c)(3) share, reinstated share, posting lag
SELECT 'rev_month' kind, DATE_TRUNC('month', TRY_TO_DATE(REVOCATION_DATE)) m, COUNT(*) n, COUNT_IF(EXEMPTION_TYPE = '03') c3,
       COUNT_IF(WAS_REINSTATED) rein, MEDIAN(DATEDIFF(day, TRY_TO_DATE(REVOCATION_DATE), TRY_TO_DATE(REVOCATION_POSTING_DATE))) lag_days
FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_IRS_REVOCATION GROUP BY 1,2
UNION ALL
SELECT 'post_month', DATE_TRUNC('month', TRY_TO_DATE(REVOCATION_POSTING_DATE)), COUNT(*), COUNT_IF(EXEMPTION_TYPE = '03'),
       COUNT_IF(WAS_REINSTATED), MEDIAN(DATEDIFF(day, TRY_TO_DATE(REVOCATION_DATE), TRY_TO_DATE(REVOCATION_POSTING_DATE)))
FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_IRS_REVOCATION GROUP BY 1,2
ORDER BY 1,2;

-- S20 Revoked, never reinstated, yet in today's IRS master file or Publication 78: split by ruling date vs revocation date and later filing
WITH r AS (
  SELECT EIN, MAX(TRY_TO_DATE(REVOCATION_DATE)) rd, BOOLOR_AGG(WAS_REINSTATED) rein, ANY_VALUE(EXEMPTION_TYPE) ex
  FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_IRS_REVOCATION GROUP BY 1
), bmf AS (
  SELECT EIN, MAX(RULING_DATE) rul, MAX(DEDUCTIBILITY_CODE) ded, MAX(REVENUE_AMT) rev, MAX(TAX_PERIOD_MONTH) tp
  FROM LIBRARY_MARTS.CORPORATE_REGISTRY.CORPORATE_REGISTRY__FED_IRS_EO_BMF GROUP BY 1
), p78 AS (SELECT DISTINCT EIN FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_IRS_PUB78_ELIGIBLE_DONEES)
SELECT r.rein, bmf.EIN IS NOT NULL in_bmf, bmf.ded, CASE WHEN bmf.rul IS NULL THEN 'no_ruling' WHEN bmf.rul > r.rd THEN 'ruling_after' ELSE 'ruling_before' END rul_vs,
       p78.EIN IS NOT NULL in_p78, IFF(bmf.tp > r.rd, 'filed_after', 'no') tp_after, COUNT(*) n, SUM(bmf.rev) rev_sum, MEDIAN(bmf.rev) rev_med, COUNT_IF(bmf.rev >= 1000000) rev_1m
FROM r LEFT JOIN bmf USING (EIN) LEFT JOIN p78 USING (EIN)
GROUP BY 1,2,3,4,5,6 ORDER BY n DESC;

-- S21 QCEW pay trap: does AVG_ANNUAL_PAY equal wages / jobs, by aggregation level
SELECT AGGREGATION_LEVEL_CODE agg, COUNT_IF(ANNUAL_AVG_EMPLOYMENT > 0) n,
       COUNT_IF(ANNUAL_AVG_EMPLOYMENT > 0 AND ABS(AVG_ANNUAL_PAY - TOTAL_ANNUAL_WAGES / ANNUAL_AVG_EMPLOYMENT) > 2) off_by_2,
       MEDIAN(IFF(ANNUAL_AVG_EMPLOYMENT > 0, AVG_ANNUAL_PAY / NULLIF(TOTAL_ANNUAL_WAGES / ANNUAL_AVG_EMPLOYMENT, 0), NULL)) med_ratio,
       MEDIAN(IFF(ANNUAL_AVG_EMPLOYMENT > 0, AVG_ANNUAL_PAY / NULLIF(ANNUAL_AVG_WEEKLY_WAGE * 52, 0), NULL)) med_ratio_weekly,
       ANY_VALUE(IFF(ANNUAL_AVG_EMPLOYMENT > 1000, AREA_FIPS || ' ' || INDUSTRY_CODE || ' emp=' || ANNUAL_AVG_EMPLOYMENT || ' wages=' || TOTAL_ANNUAL_WAGES || ' wk=' || ANNUAL_AVG_WEEKLY_WAGE || ' pay=' || AVG_ANNUAL_PAY, NULL)) sample_row
FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_BLS_QCEW
GROUP BY 1 ORDER BY 1;
