-- S22 Revoked, no reinstatement in the file, master-file ruling date BEFORE the revocation, still in Pub 78, filed after: top 25 by revenue, plus revocation-year spread
WITH r AS (
  SELECT EIN, MAX(TRY_TO_DATE(REVOCATION_DATE)) rd, BOOLOR_AGG(WAS_REINSTATED) rein, ANY_VALUE(EXEMPTION_TYPE) ex, ANY_VALUE(LEGAL_NAME) nm, ANY_VALUE(STATE) st
  FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_IRS_REVOCATION GROUP BY 1
), bmf AS (
  SELECT EIN, MAX(RULING_DATE) rul, MAX(DEDUCTIBILITY_CODE) ded, MAX(REVENUE_AMT) rev, MAX(TAX_PERIOD_MONTH) tp, MAX(ORG_NAME) bnm, MAX(STATE) bst, MAX(SUBSECTION_CODE) sub, MAX(GROUP_EXEMPTION_NUM) grp
  FROM LIBRARY_MARTS.CORPORATE_REGISTRY.CORPORATE_REGISTRY__FED_IRS_EO_BMF GROUP BY 1
), p78 AS (SELECT DISTINCT EIN FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_IRS_PUB78_ELIGIBLE_DONEES),
x AS (
  SELECT r.*, bmf.rul, bmf.rev, bmf.tp, bmf.bnm, bmf.bst, bmf.sub, bmf.grp
  FROM r JOIN bmf USING (EIN) JOIN p78 USING (EIN)
  WHERE NOT r.rein AND bmf.rul <= r.rd AND bmf.tp > r.rd AND bmf.ded = '1'
)
SELECT * FROM (SELECT 'top' kind, EIN, nm, bnm, st, ex, sub, grp, rd, rul, tp, rev, NULL n FROM x ORDER BY rev DESC NULLS LAST LIMIT 25)
UNION ALL
SELECT 'year', NULL, NULL, NULL, NULL, NULL, NULL, NULL, DATE_TRUNC('year', rd), NULL, NULL, SUM(rev), COUNT(*) FROM x GROUP BY DATE_TRUNC('year', rd)
UNION ALL
SELECT 'grp', NULL, NULL, NULL, NULL, NULL, NULL, IFF(grp IS NULL OR grp IN ('0000','0'), 'none', 'group'), NULL, NULL, NULL, SUM(rev), COUNT(*) FROM x GROUP BY IFF(grp IS NULL OR grp IN ('0000','0'), 'none', 'group');

-- S23 OSHA 300A filing year 2025: hospital rows in VT, NM, HI, and any row naming the big absent systems
SELECT UPPER(TRIM(STATE)) st, CITY, ESTABLISHMENT_NAME, COMPANY_NAME, NAICS_CODE, ESTABLISHMENT_TYPE, ANNUAL_AVERAGE_EMPLOYEES emp, YEAR_FILING_FOR
FROM LIBRARY_MARTS.LABOR.LABOR__FED_OSHA_ITA_300A_SUMMARY_2025
WHERE (NAICS_CODE LIKE '622%' AND UPPER(TRIM(STATE)) IN ('VT','NM','HI'))
   OR REGEXP_LIKE(UPPER(ESTABLISHMENT_NAME || ' ' || COALESCE(COMPANY_NAME,'')),
      '.*(UNIVERSITY OF VERMONT MED|UVM|RUTLAND REGIONAL|CENTRAL VERMONT MED|PRESBYTERIAN HOSP|PRESBYTERIAN HEALTH|CHRISTUS ST.? VINCENT|SAN JUAN REGIONAL|QUEEN.S MEDICAL|QUEEN.S HEALTH|KAPIOLANI MEDICAL|HAWAII PACIFIC HEALTH|PALI MOMI|STRAUB MEDICAL|STRAUB BENIOFF|WILCOX MEDICAL|GERALD CHAMPION).*')
ORDER BY st, emp DESC;

-- S24 Treasury: debt series vs the debt-to-the-penny table on fiscal year-end dates, and fiscal 2026 so far vs the same window in earlier years
WITH p AS (
  SELECT RECORD_DATE, TOT_PUB_DEBT_OUT_AMT amt, YEAR(DATEADD(month, 3, RECORD_DATE)) fy
  FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_TREASURY_DEBT_TO_PENNY
), last_ AS (SELECT MAX(RECORD_DATE) d FROM p),
w AS (
  SELECT fy, MIN(RECORD_DATE) d0, MAX(IFF(DAYOFYEAR(DATEADD(month, 3, RECORD_DATE)) <= (SELECT DAYOFYEAR(DATEADD(month, 3, d)) FROM last_), RECORD_DATE, NULL)) d1
  FROM p GROUP BY fy
)
SELECT w.fy, w.d0, a.amt amt0, w.d1, b.amt amt1, b.amt - a.amt added_same_window, h.DEBT_OUTSTANDING_AMT hist_fy_end, e.amt penny_fy_end, (SELECT d FROM last_) last_date
FROM w JOIN p a ON a.RECORD_DATE = w.d0 JOIN p b ON b.RECORD_DATE = w.d1
LEFT JOIN LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_TREASURY_DEBT_OUTSTANDING h ON h.RECORD_DATE = DATE_FROM_PARTS(w.fy, 9, 30)
LEFT JOIN p e ON e.RECORD_DATE = DATE_FROM_PARTS(w.fy, 9, 30)
WHERE w.fy >= 2015 ORDER BY w.fy;
