{{ config(tags=['spine_generated']) }}

-- GRAIN: one row per record (spine_entity not determined -- no registry hint available) (ZIP+OUTLET_PERMIT_ISSUE_DATE unique)
-- SPINE_ENTITY: place  (natural_key: OUTLET_ZIP_CODE, OUTLET_PERMIT_ISSUE_DATE)
-- Generated by scripts/generate_staging_models.py from SOURCE_REGISTRY -- deterministic,
-- no LLM. Casts kept as landed (TEXT) -- add explicit type casts by hand once each
-- column's real type is confirmed; this generator has no semantic type knowledge.
-- spine_entity 'place' has no connect/ resolver yet (see connect/spine_entity.py) -- no SPINE_ENTITY_ID emitted.
-- landing table's ingestion timestamp is named INGESTED_AT (no leading underscore) rather than the usual _INGESTED_AT -- confirmed via INFORMATION_SCHEMA, not assumed.

with source as (

    select * from {{ source('ripple_raw', 'PORTAL_SOC_TEXAS_OPEN_DATA_5410A1009F') }}

),

renamed as (

    select
        "TAXPAYER_NUMBER" as taxpayer_number,
        "TAXPAYER_NAME" as taxpayer_name,
        "TAXPAYER_ADDRESS" as taxpayer_address,
        "TAXPAYER_CITY" as taxpayer_city,
        "TAXPAYER_STATE" as taxpayer_state,
        "TAXPAYER_ZIP_CODE" as taxpayer_zip_code,
        "TAXPAYER_COUNTY_CODE" as taxpayer_county_code,
        "TAXPAYER_ORGANIZATION_TYPE" as taxpayer_organization_type,
        "OUTLET_NUMBER" as outlet_number,
        "OUTLET_NAME" as outlet_name,
        "OUTLET_ADDRESS" as outlet_address,
        "OUTLET_CITY" as outlet_city,
        "OUTLET_STATE" as outlet_state,
        "OUTLET_ZIP_CODE" as outlet_zip_code,
        "OUTLET_COUNTY_CODE" as outlet_county_code,
        "OUTLET_NAICS_CODE" as outlet_naics_code,
        "OUTLET_INSIDE_OUTSIDE_CITY_LIMITS_INDICATOR" as outlet_inside_outside_city_limits_indicator,
        "OUTLET_PERMIT_ISSUE_DATE" as outlet_permit_issue_date,
        "OUTLET_FIRST_SALES_DATE" as outlet_first_sales_date,
        INGESTED_AT as _loaded_at,
        'https://data.texas.gov/d/jrea-zgmq' as _source_url

    from source

)

select * from renamed
qualify row_number() over (partition by outlet_zip_code, outlet_permit_issue_date order by _loaded_at desc) = 1
