select table_name, listagg(column_name, ',') within group (order by ordinal_position) cols
from LIBRARY_MARTS.INFORMATION_SCHEMA.COLUMNS
where table_name in ('POLITICS__TX_LOBBY_COVER','EDUCATION__FED_SENATE_LDA_FILINGS','FINANCE__FED_FEC_INDEPENDENT_EXPENDITURES','FINANCE__FED_FEC_INDIV_CONTRIBUTIONS','FINANCE__FED_IRS527_SCHEDULE_A_CONTRIBUTIONS')
group by 1
