select REPORT_INFO_IDENT, FILER_IDENT, FILER_NAME, FORM_TYPE_CD, REPORT_TYPE_CD, APPLICABLE_YEAR, PERIOD_START_DT, PERIOD_END_DT, DUE_DT, FILED_DT, TOTAL_EXPEND_MEDIA,
 count(*) over (partition by PERIOD_START_DT, PERIOD_END_DT) same_period_n, count(*) over () all_n, count(distinct REPORT_INFO_IDENT) over () distinct_ids
from LIBRARY_MARTS.POLITICS.POLITICS__TX_LOBBY_COVER where ltrim(FILER_IDENT,'0')='85404' or FILER_NAME ilike 'abboud%'
order by PERIOD_START_DT, FILED_DT
