select FILING_YEAR, FILING_PERIOD, FILING_TYPE, upper(REGISTRANT_NAME) reg, REGISTRANT_ID, upper(CLIENT_NAME) cli, CLIENT_ID, INCOME, EXPENSES, DT_POSTED, FILING_UUID, TERMINATION_DATE,
 count(*) over (partition by FILING_UUID) uuid_dups
from LIBRARY_MARTS.EDUCATION.EDUCATION__FED_SENATE_LDA_FILINGS
where upper(CLIENT_NAME) like '%LAS VEGAS SANDS%' and FILING_YEAR >= '2021'
order by FILING_YEAR, reg, FILING_PERIOD, DT_POSTED
