-- S01 Closed-end funds: pull whole table (973 rows)
SELECT * FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_CLOSED_END_FUND_INFORMATION;

-- S02 OCC national banks: pull whole table (724 rows)
SELECT * FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_OCC_NATIONAL_BANKS;

-- S03 SEC EDGAR financials: pull whole table (55.6K rows)
SELECT * FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_EDGAR_FINANCIALS;

-- S04 FEC committees dim: pull whole table (44.4K rows)
SELECT * FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_FEC_COMMITTEES_DIM;

-- S05 FEC cand-cmte linkage: pull whole table (30.5K rows)
SELECT * FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_FEC_CAND_CMTE_LINKAGE;

-- S06 FEC PAC summary (join partner for the committees dim): pull whole table (45.7K rows)
SELECT * FROM LIBRARY_MARTS.POLITICS.POLITICS__FED_FEC_PAC_SUMMARY;

-- S07 POLITICS copy of the cand-cmte link (duplicate-table check for S05): pull whole table (16.2K rows)
SELECT * FROM LIBRARY_MARTS.POLITICS.POLITICS__FEC_CAND_CMTE_LINK;

-- S08 FDIC branch deposits, per bank cert across all survey years, only certs on the OCC list (join partner for S02)
WITH occ AS (SELECT DISTINCT TO_VARCHAR(CERT) cert FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_OCC_NATIONAL_BANKS WHERE CERT IS NOT NULL)
SELECT s.FDIC_CERT, MIN(s.SURVEY_YEAR) first_yr, MAX(s.SURVEY_YEAR) last_yr,
       SUM(IFF(s.SURVEY_YEAR = 2025, s.BRANCH_DEPOSITS_THOUSANDS, 0)) dep_2025,
       SUM(IFF(s.SURVEY_YEAR = 2020, s.BRANCH_DEPOSITS_THOUSANDS, 0)) dep_2020,
       COUNT_IF(s.SURVEY_YEAR = 2025) branches_2025,
       MAX(IFF(s.SURVEY_YEAR = 2025, s.INSTITUTION_ASSETS_THOUSANDS, NULL)) assets_2025,
       MAX(IFF(s.SURVEY_YEAR = 2025, s.SPECIALIZATION_GROUP_DESC, NULL)) spec_2025,
       MAX(IFF(s.SURVEY_YEAR = 2025, s.CHARTER_AGENCY, NULL)) chartag_2025,
       MAX(IFF(s.SURVEY_YEAR = 2025, s.HOLDING_COMPANY_NAME, NULL)) hc_2025,
       MIN(IFF(s.MAIN_OFFICE_FLAG IN ('1','Y','true'), s.SIMS_ESTABLISHED_DATE, NULL)) main_est
FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_FDIC_SOD_BRANCH_DEPOSITS s
JOIN occ ON occ.cert = s.FDIC_CERT
GROUP BY 1;
