-- S09 Closed-end funds: pull whole table again, FILING_DATE as text (S01 died on year-0001 dates in the Python driver)
SELECT FILE_NO, CIK, REGISTRANT_NAME, ADDRESS_1, ADDRESS_2, CITY, STATE, ZIP_CODE,
       TO_VARCHAR(FILING_DATE, 'YYYY-MM-DD') AS FILING_DATE_TXT, YEAR(FILING_DATE) AS FILING_YR, FILING_TYPE
FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_CLOSED_END_FUND_INFORMATION;

-- S10 Insider open-market sales (code S) per issuer per day, 2022-10 to 2025-06, only issuers in EDGAR_FINANCIALS (CIK compared as numbers)
WITH iss AS (SELECT DISTINCT TRY_TO_NUMBER(CIK) AS cik FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_EDGAR_FINANCIALS),
s AS (
  SELECT TRY_TO_NUMBER(sub.ISSUER_CIK) AS cik, t.TRANSACTION_DATE AS d, t.ACCESSION_NUMBER AS acc,
         t.SHARES, t.PRICE_PER_SHARE, t.TRANSACTION_VALUE
  FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_INSIDER_NONDERIV_TRANS t
  JOIN LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_INSIDER_SUBMISSION sub ON sub.ACCESSION_NUMBER = t.ACCESSION_NUMBER
  WHERE t.TRANSACTION_CODE = 'S' AND t.TRANSACTION_DATE BETWEEN '2022-10-01' AND '2025-06-30')
SELECT s.cik, s.d, COUNT(*) AS n_trades, COUNT(DISTINCT s.acc) AS n_forms,
       SUM(s.SHARES) AS shares, SUM(s.SHARES * s.PRICE_PER_SHARE) AS val_calc, SUM(s.TRANSACTION_VALUE) AS val_col,
       MAX(s.PRICE_PER_SHARE) AS max_px
FROM s JOIN iss ON iss.cik = s.cik
GROUP BY 1, 2;

-- S11 Insider tables coverage: trades per month (all issuers), how many land on a submission, share that are code S
SELECT DATE_TRUNC('month', t.TRANSACTION_DATE) AS m, COUNT(*) AS trades, COUNT(sub.ACCESSION_NUMBER) AS on_submission,
       COUNT_IF(t.TRANSACTION_CODE = 'S') AS sales, COUNT(DISTINCT sub.ISSUER_CIK) AS issuers
FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_INSIDER_NONDERIV_TRANS t
LEFT JOIN LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_INSIDER_SUBMISSION sub ON sub.ACCESSION_NUMBER = t.ACCESSION_NUMBER
WHERE t.TRANSACTION_DATE BETWEEN '2021-01-01' AND '2026-12-31'
GROUP BY 1 ORDER BY 1;

-- S12 Duplicate-table check: EDGAR_FINANCIALS 2024 quarters vs the four DERA_SUB_2024Qx tables, by accession number
WITH dera AS (
  SELECT '2024q1' q, ADSH FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_DERA_SUB_2024Q1
  UNION ALL SELECT '2024q2', ADSH FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_DERA_SUB_2024Q2
  UNION ALL SELECT '2024q3', ADSH FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_DERA_SUB_2024Q3
  UNION ALL SELECT '2024q4', ADSH FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_DERA_SUB_2024Q4)
SELECT e.SOURCE_FILE, COUNT(*) AS edgar_rows, COUNT(dera.ADSH) AS in_dera, COUNT_IF(dera.q = e.SOURCE_FILE) AS same_quarter
FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_EDGAR_FINANCIALS e
LEFT JOIN dera ON dera.ADSH = e.ADSH
GROUP BY 1 ORDER BY 1;

-- S13 Harm join: EDGAR_FINANCIALS filers whose EIN matches a PBGC-trusteed pension plan sponsor (EIN padded to 9, 000000000 dropped)
WITH e AS (
  SELECT LPAD(REGEXP_REPLACE(EIN, '[^0-9]', ''), 9, '0') AS ein9, MAX(NAME) AS sec_name, MAX(CITYBA) AS sec_city, MAX(STPRBA) AS sec_st,
         MAX(FILED) AS last_filed, COUNT(*) AS filings
  FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_EDGAR_FINANCIALS
  WHERE REGEXP_REPLACE(EIN, '[^0-9]', '') NOT IN ('', '000000000')
  GROUP BY 1)
SELECT e.*, p.CASE_NUMBER, p.SPONSOR_NAME, p.PLAN_NAME, p.CITY AS pbgc_city, p.STATE AS pbgc_st,
       p.DATE_OF_PLAN_TERMINATION, p.DATE_OF_PBGC_TRUSTEESHIP, p.NUMBER_OF_PARICIPANTS_AT_DATE_OF_PLAN_TERMINATION AS participants
FROM e JOIN LIBRARY_MARTS.LABOR.LABOR__FED_PBGC_TRUSTEED_PLANS p
  ON LPAD(REGEXP_REPLACE(p.EIN, '[^0-9]', ''), 9, '0') = e.ein9
ORDER BY p.DATE_OF_PLAN_TERMINATION DESC;
