-- K1 metadata and date columns on the four comparison tables
SELECT TABLE_SCHEMA, TABLE_NAME, LISTAGG(COLUMN_NAME || ':' || DATA_TYPE, ', ') WITHIN GROUP (ORDER BY ORDINAL_POSITION) cols
FROM LIBRARY_MARTS.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME IN ('IMMIGRATION__FED_CMS_HOSPICE_ENROLLMENTS','HEALTH__FED_CMS_HOSPICE','HEALTH__FED_CMS_PECOS_PROVIDER_ENROLLMENT','HEALTH__FED_CMS_POS_OTHER')
  AND (COLUMN_NAME ILIKE '%LOAD%' OR COLUMN_NAME ILIKE '%INGEST%' OR COLUMN_NAME ILIKE '\_%' OR COLUMN_NAME ILIKE '%DATE%' OR COLUMN_NAME ILIKE '%_DT'
       OR COLUMN_NAME IN ('NPI','PRVDR_CTGRY_CD','PGM_TRMNTN_CD','PHNE_NUM','PROVIDER_TYPE_CD','PROVIDER_TYPE_DESC','TELEPHONE_NUMBER','STATE','STATE_CD','ENROLLMENT_STATE','ORG_NAME'))
GROUP BY 1,2
