-- K2 profile: is hospice in POS, does PECOS carry hospices, enrollment file shape, AZ certification and incorporation years
SELECT 'pos_category' src, PRVDR_CTGRY_CD k, COUNT(*) n, COUNT_IF(STATE_CD = 'AZ') az, COUNT_IF(NVL(PGM_TRMNTN_CD, '00') <> '00') termed,
       TO_VARCHAR(MAX(CRTFCTN_DT)) mx1, TO_VARCHAR(MAX(TRMNTN_EXPRTN_DT)) mx2
FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_POS_OTHER GROUP BY 2
UNION ALL
SELECT 'enr_multi_npi_flag', MULTIPLE_NPI_FLAG, COUNT(*), COUNT_IF(ENROLLMENT_STATE = 'AZ'), COUNT(DISTINCT NPI), TO_VARCHAR(MAX(INCORPORATION_DATE)), TO_VARCHAR(COUNT(DISTINCT ENROLLMENT_ID))
FROM LIBRARY_MARTS.IMMIGRATION.IMMIGRATION__FED_CMS_HOSPICE_ENROLLMENTS GROUP BY 2
UNION ALL
SELECT 'pecos_hospice_type', PROVIDER_TYPE_CD || ' ' || PROVIDER_TYPE_DESC, COUNT(*), COUNT_IF(STATE_CD = 'AZ'), COUNT(DISTINCT NPI), NULL, NULL
FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_PECOS_PROVIDER_ENROLLMENT WHERE PROVIDER_TYPE_DESC ILIKE '%HOSPICE%' GROUP BY 2
UNION ALL
SELECT 'cert_az_nv_year', STATE || ' ' || TO_VARCHAR(YEAR(CERTIFICATION_DATE)), COUNT(*), NULL, NULL, TO_VARCHAR(MIN(CERTIFICATION_DATE)), TO_VARCHAR(MAX(CERTIFICATION_DATE))
FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_HOSPICE WHERE STATE IN ('AZ', 'NV') AND CERTIFICATION_DATE >= '2019-01-01' GROUP BY 2
UNION ALL
SELECT 'enr_az_nv_incyear', ENROLLMENT_STATE || ' ' || TO_VARCHAR(YEAR(INCORPORATION_DATE)), COUNT(*), NULL, COUNT(DISTINCT NPI), NULL, NULL
FROM LIBRARY_MARTS.IMMIGRATION.IMMIGRATION__FED_CMS_HOSPICE_ENROLLMENTS WHERE ENROLLMENT_STATE IN ('AZ', 'NV') AND INCORPORATION_DATE >= '2019-01-01' GROUP BY 2
ORDER BY 1, 2
