-- K3 fresh re-derivation: hospice orgs outside CA enumerated 2020-2023 (251G00000X in any slot), with NPI, name+state, phone and address matches to enrollment, PECOS Part A hospice, and certified files
WITH h AS (
  SELECT NPI, PROVIDER_ORGANIZATION_NAME_LEGAL_BUSINESS_NAME org, PROVIDER_OTHER_ORGANIZATION_NAME other_org,
         PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_STATE_NAME st, UPPER(TRIM(PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_CITY_NAME)) city,
         UPPER(TRIM(PROVIDER_FIRST_LINE_BUSINESS_PRACTICE_LOCATION_ADDRESS)) addr, UPPER(TRIM(PROVIDER_SECOND_LINE_BUSINESS_PRACTICE_LOCATION_ADDRESS)) addr2,
         PROVIDER_BUSINESS_MAILING_ADDRESS_STATE_NAME mst, PROVIDER_ENUMERATION_DATE en, LAST_UPDATE_DATE lu,
         UPPER(TRIM(AUTHORIZED_OFFICIAL_FIRST_NAME)) ao_fn, UPPER(TRIM(AUTHORIZED_OFFICIAL_LAST_NAME)) ao_ln,
         REGEXP_REPLACE(PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_TELEPHONE_NUMBER, '[^0-9]', '') ph,
         REGEXP_REPLACE(AUTHORIZED_OFFICIAL_TELEPHONE_NUMBER, '[^0-9]', '') ao_ph,
         IS_ORGANIZATION_SUBPART sub, IFF(HEALTHCARE_PROVIDER_TAXONOMY_CODE_1 = '251G00000X', 1, 0) slot1,
         REGEXP_REPLACE(REGEXP_REPLACE(UPPER(PROVIDER_ORGANIZATION_NAME_LEGAL_BUSINESS_NAME), '[^A-Z0-9]', ''), '(INC|LLC|CORP|CORPORATION|PLLC|PC|LTD|LLP)$', '') nk
  FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_NPPES
  WHERE ENTITY_TYPE_CODE = '2' AND PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_STATE_NAME <> 'CA'
    AND PROVIDER_ENUMERATION_DATE BETWEEN '2020-01-01' AND '2023-12-31'
    AND '251G00000X' IN (HEALTHCARE_PROVIDER_TAXONOMY_CODE_1, HEALTHCARE_PROVIDER_TAXONOMY_CODE_2, HEALTHCARE_PROVIDER_TAXONOMY_CODE_3,
        HEALTHCARE_PROVIDER_TAXONOMY_CODE_4, HEALTHCARE_PROVIDER_TAXONOMY_CODE_5, HEALTHCARE_PROVIDER_TAXONOMY_CODE_6, HEALTHCARE_PROVIDER_TAXONOMY_CODE_7,
        HEALTHCARE_PROVIDER_TAXONOMY_CODE_8, HEALTHCARE_PROVIDER_TAXONOMY_CODE_9, HEALTHCARE_PROVIDER_TAXONOMY_CODE_10)),
enr_npi AS (SELECT NPI, MAX(ENROLLMENT_STATE) enr_st, MAX(CCN) enr_ccn FROM LIBRARY_MARTS.IMMIGRATION.IMMIGRATION__FED_CMS_HOSPICE_ENROLLMENTS GROUP BY 1),
enr_nm AS (
  SELECT k, st, MAX(CCN) ccn FROM (
    SELECT REGEXP_REPLACE(REGEXP_REPLACE(UPPER(ORGANIZATION_NAME), '[^A-Z0-9]', ''), '(INC|LLC|CORP|CORPORATION|PLLC|PC|LTD|LLP)$', '') k, ENROLLMENT_STATE st, CCN
    FROM LIBRARY_MARTS.IMMIGRATION.IMMIGRATION__FED_CMS_HOSPICE_ENROLLMENTS
    UNION ALL
    SELECT REGEXP_REPLACE(REGEXP_REPLACE(UPPER(DOING_BUSINESS_AS_NAME), '[^A-Z0-9]', ''), '(INC|LLC|CORP|CORPORATION|PLLC|PC|LTD|LLP)$', ''), ENROLLMENT_STATE, CCN
    FROM LIBRARY_MARTS.IMMIGRATION.IMMIGRATION__FED_CMS_HOSPICE_ENROLLMENTS WHERE NULLIF(TRIM(DOING_BUSINESS_AS_NAME), '') IS NOT NULL)
  WHERE k <> '' GROUP BY 1, 2),
pec AS (SELECT NPI, MAX(STATE_CD) pec_st FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_PECOS_PROVIDER_ENROLLMENT WHERE PROVIDER_TYPE_CD = '00-08' GROUP BY 1),
pec_nm AS (
  SELECT REGEXP_REPLACE(REGEXP_REPLACE(UPPER(ORG_NAME), '[^A-Z0-9]', ''), '(INC|LLC|CORP|CORPORATION|PLLC|PC|LTD|LLP)$', '') k, STATE_CD st, COUNT(*) n
  FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_PECOS_PROVIDER_ENROLLMENT WHERE PROVIDER_TYPE_CD = '00-08' GROUP BY 1, 2),
cert AS (
  SELECT CCN, STATE st, CERTIFICATION_DATE cd, REGEXP_REPLACE(TELEPHONE_NUMBER, '[^0-9]', '') ph, UPPER(TRIM(ADDRESS_LINE_1)) addr,
         REGEXP_REPLACE(REGEXP_REPLACE(UPPER(FACILITY_NAME), '[^A-Z0-9]', ''), '(INC|LLC|CORP|CORPORATION|PLLC|PC|LTD|LLP)$', '') k
  FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_HOSPICE),
cert_nm AS (SELECT k, st, MAX(CCN) ccn, MAX(cd) cd FROM cert GROUP BY 1, 2),
cert_ph AS (SELECT ph, MAX(CCN) ccn, MAX(cd) cd, MAX(st) st FROM cert WHERE LENGTH(ph) = 10 GROUP BY 1),
cert_ad AS (SELECT addr, st, MAX(CCN) ccn, MAX(cd) cd FROM cert GROUP BY 1, 2)
SELECT h.*, en_.enr_st, en_.enr_ccn, enm.ccn enr_name_ccn, pec.pec_st, pnm.n pec_name_n,
       cn.ccn cert_name_ccn, cn.cd cert_name_cd, cp.ccn cert_ph_ccn, cp.cd cert_ph_cd, cp.st cert_ph_st, ca.ccn cert_addr_ccn, ca.cd cert_addr_cd
FROM h
LEFT JOIN enr_npi en_ ON en_.NPI = h.NPI
LEFT JOIN enr_nm enm ON enm.k = h.nk AND enm.st = h.st
LEFT JOIN pec ON pec.NPI = h.NPI
LEFT JOIN pec_nm pnm ON pnm.k = h.nk AND pnm.st = h.st
LEFT JOIN cert_nm cn ON cn.k = h.nk AND cn.st = h.st
LEFT JOIN cert_ph cp ON cp.ph = h.ph
LEFT JOIN cert_ad ca ON ca.addr = h.addr AND ca.st = h.st
