-- K4 every AZ certified hospice certified 2020 on: is its CCN in the enrollment file, under which NPI, and what NPPES says about that NPI (phones, official, enumeration)
WITH c AS (
  SELECT CCN, FACILITY_NAME, UPPER(TRIM(ADDRESS_LINE_1)) addr, CITY_TOWN, REGEXP_REPLACE(TELEPHONE_NUMBER, '[^0-9]', '') cph, CERTIFICATION_DATE cd, OWNERSHIP_TYPE own
  FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_HOSPICE WHERE STATE = 'AZ' AND CERTIFICATION_DATE >= '2020-01-01'),
e AS (
  SELECT CCN, LISTAGG(DISTINCT NPI, '/') enr_npis, MAX(ORGANIZATION_NAME) enr_org, MAX(INCORPORATION_DATE) inc, COUNT(*) enr_rows
  FROM LIBRARY_MARTS.IMMIGRATION.IMMIGRATION__FED_CMS_HOSPICE_ENROLLMENTS GROUP BY 1),
n AS (
  SELECT NPI, PROVIDER_ENUMERATION_DATE en, UPPER(TRIM(AUTHORIZED_OFFICIAL_FIRST_NAME)) || ' ' || UPPER(TRIM(AUTHORIZED_OFFICIAL_LAST_NAME)) ao,
         REGEXP_REPLACE(PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_TELEPHONE_NUMBER, '[^0-9]', '') nph, REGEXP_REPLACE(AUTHORIZED_OFFICIAL_TELEPHONE_NUMBER, '[^0-9]', '') aoph,
         HEALTHCARE_PROVIDER_TAXONOMY_CODE_1 tx1
  FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_NPPES WHERE PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_STATE_NAME = 'AZ' AND ENTITY_TYPE_CODE = '2')
SELECT c.*, e.enr_npis, e.enr_org, e.inc, e.enr_rows, n.en, n.ao, n.nph, n.aoph, n.tx1
FROM c LEFT JOIN e ON e.CCN = c.CCN LEFT JOIN n ON n.NPI = SPLIT_PART(e.enr_npis, '/', 1)
ORDER BY c.cd
