{{ config(materialized='table', schema='ECONOMICS') }}

-- Source: FAOSTAT Suite of Food Security Indicators (bulk) (279470 rows)
-- Generated by gen_mart_models.py
-- Fixed 2026-09-20: was reading source() with bare try_to_number()/try_to_double()/try_to_date() casts, which silently round decimals or mis-parse dates instead of guarding them. Now reads the already-guarded staging model (stg_intl_fao_faostat_food_security__records) instead -- same columns, same names, same order; every numeric/date cast there is regex-guarded (macros/staging_casts.sql): a value that doesn't parse cleanly reads NULL instead of a silently wrong value.

select
    area_code,
    area_code_m49,
    area,
    item_code,
    item,
    element_code,
    element,
    year_code,
    year,
    unit,
    value,
    flag,
    note
from {{ ref('stg_intl_fao_faostat_food_security__records') }}
