{{ config(materialized='table', schema='ECONOMICS') }}

-- Source: FAOSTAT Suite of Food Security Indicators (bulk) (279470 rows)
-- Generated by gen_mart_models.py

with source as (
    select * from {{ source('ripple_raw', 'INTL_FAO_FAOSTAT_FOOD_SECURITY') }}
)

select
    AREA_CODE as area_code,
    AREA_CODE_M49 as area_code_m49,
    AREA as area,
    ITEM_CODE as item_code,
    ITEM as item,
    ELEMENT_CODE as element_code,
    ELEMENT as element,
    YEAR_CODE as year_code,
    try_to_number("YEAR") as year,
    UNIT as unit,
    try_to_double("VALUE") as value,
    FLAG as flag,
    NOTE as note
from source
