{{ config(materialized='table', schema='ECONOMICS') }}

-- GRAIN: one row per federal contract transaction

with source as (
    select * from {{ source('ripple_raw', 'FED_USASPENDING_CONTRACTS') }}
)

select
    CONTRACT_AWARD_UNIQUE_KEY,
    AWARD_ID_PIID,
    ACTION_DATE,
    PERIOD_OF_PERFORMANCE_START_DATE,
    PERIOD_OF_PERFORMANCE_CURRENT_END_DATE,
    FEDERAL_ACTION_OBLIGATION,
    TOTAL_DOLLARS_OBLIGATED,
    CURRENT_TOTAL_VALUE_OF_AWARD,
    AWARDING_AGENCY_NAME,
    AWARDING_SUB_AGENCY_NAME,
    FUNDING_AGENCY_NAME,
    RECIPIENT_UEI,
    RECIPIENT_DUNS,
    CAGE_CODE,
    RECIPIENT_NAME,
    RECIPIENT_DOING_BUSINESS_AS_NAME,
    RECIPIENT_PARENT_UEI,
    RECIPIENT_PARENT_NAME,
    RECIPIENT_CITY_NAME,
    RECIPIENT_STATE_CODE,
    RECIPIENT_ZIP_4_CODE,
    RECIPIENT_COUNTRY_NAME,
    PRIMARY_PLACE_OF_PERFORMANCE_STATE_CODE,
    PRIMARY_PLACE_OF_PERFORMANCE_CITY_NAME,
    AWARD_TYPE,
    NAICS_CODE,
    NAICS_DESCRIPTION,
    PRODUCT_OR_SERVICE_CODE_DESCRIPTION,
    TRANSACTION_DESCRIPTION,
    HIGHLY_COMPENSATED_OFFICER_1_NAME,
    HIGHLY_COMPENSATED_OFFICER_1_AMOUNT,
    HIGHLY_COMPENSATED_OFFICER_2_NAME,
    HIGHLY_COMPENSATED_OFFICER_2_AMOUNT,
    FOREIGN_OWNED,
    USASPENDING_PERMALINK,
    LAST_MODIFIED_DATE
from source
