{{ config(materialized='table', schema='ECONOMICS') }}

-- Source: FAOSTAT (69 rows)
-- Generated by gen_mart_models.py
-- Fixed 2026-09-20: was reading source() with bare try_to_number()/try_to_double()/try_to_date() casts, which silently round decimals or mis-parse dates instead of guarding them. Now reads the already-guarded staging model (stg_intl_fao_faostat__records) instead -- same columns, same names, same order; every numeric/date cast there is regex-guarded (macros/staging_casts.sql): a value that doesn't parse cleanly reads NULL instead of a silently wrong value.

select
    datasetcode,
    datasetname,
    topic,
    datasetdescription,
    dateupdate,
    filelocation,
    filesize,
    filerows
from {{ ref('stg_intl_fao_faostat__records') }}
