{{ config(materialized='table', schema='ECONOMICS') }}

-- Source: FED_TREASURY_DEBT_OUTSTANDING (237 rows)
-- Generated by scripts/gen_mart_models.py
-- Fixed 2026-09-20: RECORD_DATE was a bare try_to_date() (pure-digit values
-- misread as epoch seconds) and DEBT_OUTSTANDING_AMT a bare try_to_double()
-- (unguarded against a stray 'nan' string parsing to the float NaN). No
-- staging model matches this source: models/staging/fed_treasury_debt_to_penny
-- reads a DIFFERENT landing table (FED_TREASURY_DEBT_TO_PENNY, a daily
-- debt-held-by-public/intragovernmental series, not this fiscal-year/quarter
-- rollup), so wrapped the two bare casts in place instead of swapping to ref().

with source as (
    select * from {{ source('ripple_raw', 'FED_TREASURY_DEBT_OUTSTANDING') }}
)

select
    {{ stg_date('RECORD_DATE') }} as record_date,
    {{ stg_float('DEBT_OUTSTANDING_AMT') }} as debt_outstanding_amt,
    SRC_LINE_NBR as src_line_nbr,
    {{ ripple_num('RECORD_FISCAL_YEAR') }} as record_fiscal_year,
    RECORD_FISCAL_QUARTER as record_fiscal_quarter,
    {{ ripple_num('RECORD_CALENDAR_YEAR') }} as record_calendar_year,
    RECORD_CALENDAR_QUARTER as record_calendar_quarter,
    RECORD_CALENDAR_MONTH as record_calendar_month,
    RECORD_CALENDAR_DAY as record_calendar_day
from source
