{{ config(tags=['spine_generated']) }}

-- GRAIN: one row per record (spine_entity not determined -- no registry hint available) (FAC_ID unique)
-- SPINE_ENTITY: (not determined)  (natural_key: FAC_ID)
-- Generated by scripts/generate_staging_models.py from SOURCE_REGISTRY -- deterministic,
-- no LLM. Casts kept as landed (TEXT) -- add explicit type casts by hand once each
-- column's real type is confirmed; this generator has no semantic type knowledge.
-- spine_entity not determined (grain/natural_key proven, but no registry hint says what this row is ABOUT) -- no SPINE_ENTITY_ID emitted.
-- landing table's ingestion timestamp is named INGESTED_AT (no leading underscore) rather than the usual _INGESTED_AT -- confirmed via INFORMATION_SCHEMA, not assumed.

with source as (

    select * from {{ source('ripple_raw', 'PORTAL_CKA_VIRGINIA_OPEN_DA_1D39BDEC50') }}

),

renamed as (

    select
        "X" as x,
        "Y" as y,
        "OBJECTID" as objectid,
        "FAC_ID" as fac_id,
        "TANK_FAC_ID" as tank_fac_id,
        "CEDS_FAC_ID" as ceds_fac_id,
        "TANK_FAC_NAME" as tank_fac_name,
        "FACILITY_TYPE" as facility_type,
        "REGISTERED_ADDRESS1" as registered_address1,
        "REGISTERED_ADDRESS2" as registered_address2,
        "REGISTERED_CITY" as registered_city,
        "REGISTERED_STATE" as registered_state,
        "REGISTERED_ZIP_CODE" as registered_zip_code,
        "FACILITY_PHONE" as facility_phone,
        "RBIS_INSPECTION_YEAR" as rbis_inspection_year,
        "RBIS_RISK_RANK" as rbis_risk_rank,
        "COUNTY" as county,
        "DEQ_REGION" as deq_region,
        "FACILITY_ACTIVE" as facility_active,
        "FEDERALLY_REGULATED" as federally_regulated,
        "AST_CAPACITY" as ast_capacity,
        "NUMBER_ACTIVE_UST" as number_active_ust,
        "NUMBER_INACTIVE_UST" as number_inactive_ust,
        "NUMBER_ACTIVE_AST" as number_active_ast,
        "NUMBER_INACTIVE_AST" as number_inactive_ast,
        "LATITUDE" as latitude,
        "LONGITUDE" as longitude,
        INGESTED_AT as _loaded_at,
        'https://data.virginia.gov/dataset/registered-petroleum-tank-facilities' as _source_url

    from source

)

select * from renamed
qualify row_number() over (partition by fac_id order by _loaded_at desc) = 1
