{{ config(tags=['spine_generated']) }}

-- GRAIN: one row per place (ZIP+PERMIT_ISSUE_DATE+PERMIT_EXPIRE_DATE+PROJECT_TYPE+PARCEL_ID unique)
-- SPINE_ENTITY: place  (natural_key: ZIP_CODE, PERMIT_ISSUE_DATE, PERMIT_EXPIRE_DATE, PROJECT_TYPE, PARCEL_ID)
-- Generated by scripts/generate_staging_models.py from SOURCE_REGISTRY -- deterministic,
-- no LLM. Casts kept as landed (TEXT) -- add explicit type casts by hand once each
-- column's real type is confirmed; this generator has no semantic type knowledge.
-- spine_entity 'place' has no connect/ resolver yet (see connect/spine_entity.py) -- no SPINE_ENTITY_ID emitted.
-- landing table's ingestion timestamp is named INGESTED_AT (no leading underscore) rather than the usual _INGESTED_AT -- confirmed via INFORMATION_SCHEMA, not assumed.
-- DEDUPE: registry natural_key (ZIP_CODE, PERMIT_ISSUE_DATE, PERMIT_EXPIRE_DATE, PROJECT_TYPE, PARCEL_ID) is NOT unique within a load as landed at generation time -- it would collapse 5 of 427 rows. Deduping on the WHOLE ROW instead (exact copies only). A record that changes between loads shows once per version. Find the real key, fix SOURCE_REGISTRY, regenerate.

with source as (

    select * from {{ source('ripple_raw', 'PORTAL_CKA_WESTERN_PENNSYLV_4FC22C2C30') }}

),

renamed as (

    select
        "PERMIT_NUMBER" as permit_number,
        "FACILITY_NAME" as facility_name,
        "S_ADDRESS" as s_address,
        "CITY" as city,
        "ZIP_CODE" as zip_code,
        "PERMIT_FEE" as permit_fee,
        "PA_LICENSE_NO" as pa_license_no,
        "CONTRACTOR_NAME" as contractor_name,
        "PERMIT_SPECIFICATIONS" as permit_specifications,
        "SQUARE_FEET" as square_feet,
        "IS_BUILDING_OCCUPIED" as is_building_occupied,
        "PERMIT_ISSUE_DATE" as permit_issue_date,
        "PERMIT_EXPIRE_DATE" as permit_expire_date,
        "PROJECT_TYPE" as project_type,
        "STATUS" as status,
        "JOB_COMPLETE" as job_complete,
        "LONGITUDE" as longitude,
        "LATITUDE" as latitude,
        "PARCEL_ID" as parcel_id,
        INGESTED_AT as _loaded_at,
        'https://data.wprdc.org/dataset/allegheny-county-asbestos-permit' as _source_url

    from source

)

select * from renamed
qualify row_number() over (partition by permit_number, facility_name, s_address, city, zip_code, permit_fee, pa_license_no, contractor_name, permit_specifications, square_feet, is_building_occupied, permit_issue_date, permit_expire_date, project_type, status, job_complete, longitude, latitude, parcel_id order by _loaded_at desc) = 1
