-- S01 Debt to the Penny: whole table, one row per day (8.3K rows), for local time math
SELECT RECORD_DATE, TOT_PUB_DEBT_OUT_AMT, DEBT_HELD_PUBLIC_AMT, INTRAGOV_HOLD_AMT, PCT_DEBT_HELD_PUBLIC, PCT_INTRAGOV_HOLD, SRC_LINE_NBR, _SOURCE_RUN_ID
FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_TREASURY_DEBT_TO_PENNY
ORDER BY RECORD_DATE;

-- S02 MTS receipts: whole table (7.5K rows), every line of every monthly statement
SELECT RECORD_DATE, RECORD_FISCAL_YEAR, TABLE_NBR, CLASSIFICATION_ID, PARENT_ID, CLASSIFICATION_DESC, SEQUENCE_LEVEL_NBR, SEQUENCE_NUMBER_CD, DATA_TYPE_CD, RECORD_TYPE_CD, LINE_CODE_NBR, SRC_LINE_NBR,
       CURRENT_MONTH_GROSS_RCPT_AMT, CURRENT_MONTH_REFUND_AMT, CURRENT_MONTH_NET_RCPT_AMT,
       CURRENT_FYTD_GROSS_RCPT_AMT, CURRENT_FYTD_REFUND_AMT, CURRENT_FYTD_NET_RCPT_AMT,
       PRIOR_FYTD_GROSS_RCPT_AMT, PRIOR_FYTD_REFUND_AMT, PRIOR_FYTD_NET_RCPT_AMT
FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_TREASURY_MTS_RECEIPTS
ORDER BY RECORD_DATE, TRY_TO_NUMBER(SRC_LINE_NBR);

-- S03 Average interest rates: whole table (5K rows)
SELECT RECORD_DATE, SECURITY_TYPE_DESC, SECURITY_DESC, AVG_INTEREST_RATE_AMT, SRC_LINE_NBR, AVG_INTEREST_RATE_KEY, _SOURCE_RUN_ID
FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_TREASURY_AVG_INTEREST_RATES
ORDER BY RECORD_DATE, SRC_LINE_NBR;

-- S04 Pub 78: status x state x country profile, EIN shape, blanks, duplicates
SELECT DEDUCTIBILITY_STATUS, STATE, COUNTRY, COUNT(*) n, COUNT(DISTINCT EIN) eins,
       COUNT_IF(NOT REGEXP_LIKE(EIN, '[0-9]{9}')) ein_not9, COUNT_IF(EIN = '000000000') ein_zero,
       COUNT_IF(NULLIF(TRIM(LEGAL_NAME), '') IS NULL) no_name, COUNT_IF(NULLIF(TRIM(CITY), '') IS NULL) no_city
FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_IRS_PUB78_ELIGIBLE_DONEES
GROUP BY 1, 2, 3 ORDER BY n DESC;

-- S05 GLEIF: registration status x entity status, validation, sentinel dates, snapshot date, overdue renewals still ISSUED
WITH g AS (SELECT * FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__INTL_GLEIF),
snap AS (SELECT MAX(REGISTRATION_LASTUPDATEDATE) s FROM g)
SELECT REGISTRATION_REGISTRATIONSTATUS rs, ENTITY_ENTITYSTATUS es, COUNT(*) n, COUNT(DISTINCT LEI) leis,
       COUNT_IF(REGISTRATION_VALIDATIONSOURCES = 'FULLY_CORROBORATED') v_full, COUNT_IF(REGISTRATION_VALIDATIONSOURCES = 'ENTITY_SUPPLIED_ONLY') v_self,
       COUNT_IF(REGISTRATION_VALIDATIONSOURCES = 'PENDING') v_pending,
       MIN(REGISTRATION_INITIALREGISTRATIONDATE) reg0, MAX(REGISTRATION_INITIALREGISTRATIONDATE) reg1, MAX(REGISTRATION_LASTUPDATEDATE) upd1,
       ANY_VALUE(snap.s) snapshot, COUNT_IF(REGISTRATION_NEXTRENEWALDATE < snap.s) renew_overdue,
       COUNT_IF(YEAR(ENTITY_ENTITYCREATIONDATE) < 1600) creat_sentinel, COUNT_IF(ENTITY_ENTITYCREATIONDATE > snap.s) creat_future,
       COUNT_IF(ENTITY_ENTITYCREATIONDATE IS NULL) creat_null, COUNT_IF(CONFORMITYFLAG = 'NON_CONFORMING') nonconf,
       COUNT(DISTINCT REGISTRATION_MANAGINGLOU) lous, COUNT(DISTINCT ENTITY_LEGALADDRESS_COUNTRY) countries
FROM g, snap
GROUP BY GROUPING SETS ((1, 2), ()) ORDER BY n DESC;

-- S06 GLEIF: top legal names by real count (checks the battery's 3.8K top-name counts)
WITH t AS (SELECT ENTITY_LEGALNAME nm, COUNT(*) n, COUNT(DISTINCT ENTITY_LEGALADDRESS_COUNTRY) ctry, ANY_VALUE(ENTITY_LEGALADDRESS_COUNTRY) a_ctry
           FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__INTL_GLEIF GROUP BY 1)
SELECT 'TOP' k, * FROM (SELECT * FROM t ORDER BY n DESC LIMIT 15)
UNION ALL
SELECT 'BATTERY', * FROM t WHERE nm IN ('Alterius non sit B.V.', 'AWARD INTERNATIONAL TRADING L.', 'KAILASH GULATI') OR nm ILIKE 'AWARD INTERNATIONAL TRADING%';

-- S07 GLEIF x OpenSanctions: every sanctioned company target with an LEI-shaped ID, with its GLEIF record (row level)
WITH o AS (
  SELECT ID, NAME, COUNTRIES, SANCTIONS, PROGRAM_IDS, DATASETS, FIRST_SEEN, LAST_SEEN, f.value::string lei
  FROM LIBRARY_MARTS.JUSTICE.JUSTICE__INTL_OPENSANCTIONS_DEFAULT,
       LATERAL FLATTEN(input => REGEXP_SUBSTR_ALL(IDENTIFIERS, '[0-9A-Z]{18}[0-9]{2}')) f
  WHERE ENTITY_TYPE IN ('Company', 'LegalEntity', 'Organization') AND IDENTIFIERS IS NOT NULL
    AND (COALESCE(TRIM(SANCTIONS), '') NOT IN ('', '""', '[]') OR COALESCE(TRIM(PROGRAM_IDS), '') NOT IN ('', '""', '[]')))
SELECT o.lei, o.ID os_id, o.NAME os_name, o.COUNTRIES os_countries, LEFT(o.SANCTIONS, 400) os_sanctions, o.PROGRAM_IDS, o.DATASETS, o.FIRST_SEEN, o.LAST_SEEN,
       g.LEI g_lei, g.ENTITY_LEGALNAME g_name, g.ENTITY_LEGALADDRESS_COUNTRY g_ctry, g.ENTITY_LEGALADDRESS_CITY g_city, g.ENTITY_ENTITYSTATUS g_estatus,
       g.REGISTRATION_REGISTRATIONSTATUS g_rstatus, g.REGISTRATION_MANAGINGLOU g_lou, g.REGISTRATION_INITIALREGISTRATIONDATE g_reg0,
       g.REGISTRATION_LASTUPDATEDATE g_upd, g.REGISTRATION_NEXTRENEWALDATE g_next, g.REGISTRATION_VALIDATIONSOURCES g_valid, g.ENTITY_ENTITYCATEGORY g_cat
FROM o LEFT JOIN LIBRARY_MARTS.ECONOMICS.ECONOMICS__INTL_GLEIF g ON o.lei = g.LEI;

-- S08 GLEIF peer base: country x managing office x registration status, with the office's own name (offices hold LEIs too)
WITH g AS (SELECT ENTITY_LEGALADDRESS_COUNTRY ctry, REGISTRATION_MANAGINGLOU lou, REGISTRATION_REGISTRATIONSTATUS rs,
                  COUNT(*) n, COUNT_IF(REGISTRATION_LASTUPDATEDATE >= '2025-01-01') upd_2025on,
                  COUNT_IF(REGISTRATION_INITIALREGISTRATIONDATE >= '2022-03-01') reg_2022mar_on
           FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__INTL_GLEIF GROUP BY 1, 2, 3)
SELECT g.*, l.ENTITY_LEGALNAME lou_name, l.ENTITY_LEGALADDRESS_COUNTRY lou_ctry
FROM g LEFT JOIN LIBRARY_MARTS.ECONOMICS.ECONOMICS__INTL_GLEIF l ON g.lou = l.LEI
ORDER BY n DESC;
