-- S13 EU consolidated list's own ID lines: LEIs the EU itself printed, joined to GLEIF (official key)
WITH e AS (
  SELECT ENTITY_LOGICAL_ID eu_id, ANY_VALUE(EU_REF_NUM) eu_ref, ANY_VALUE(PROGRAMME) programme, f.value::string lei,
         ANY_VALUE(IDEN_NUMBER) iden, ANY_VALUE(IDEN_LEBA_PUBLICATION_DATE) iden_pub
  FROM LIBRARY_MARTS.JUSTICE.JUSTICE__INTL_EU_SANCTIONS,
       LATERAL FLATTEN(input => REGEXP_SUBSTR_ALL(UPPER(IDEN_NUMBER), '[0-9A-Z]{18}[0-9]{2}')) f
  WHERE IDEN_NUMBER IS NOT NULL
  GROUP BY 1, 4),
n AS (SELECT ENTITY_LOGICAL_ID eu_id, MIN(TRY_TO_DATE(NAAL_LEBA_PUBLICATION_DATE)) first_name_pub, MIN(TRY_TO_DATE(LEBA_PUBLICATION_DATE)) leba_pub,
             MAX(NAAL_WHOLENAME) a_name, ANY_VALUE(DATE_FILE) date_file
      FROM LIBRARY_MARTS.JUSTICE.JUSTICE__INTL_EU_SANCTIONS WHERE ENTITY_LOGICAL_ID IN (SELECT eu_id FROM e) GROUP BY 1)
SELECT e.*, n.first_name_pub, n.leba_pub, n.a_name, n.date_file,
       g.LEI g_lei, g.ENTITY_LEGALNAME g_name, g.ENTITY_LEGALADDRESS_COUNTRY g_ctry, g.REGISTRATION_REGISTRATIONSTATUS g_rstatus,
       g.REGISTRATION_MANAGINGLOU g_lou, g.REGISTRATION_INITIALREGISTRATIONDATE g_reg0, g.REGISTRATION_LASTUPDATEDATE g_upd, g.REGISTRATION_NEXTRENEWALDATE g_next
FROM e LEFT JOIN n ON e.eu_id = n.eu_id LEFT JOIN LIBRARY_MARTS.ECONOMICS.ECONOMICS__INTL_GLEIF g ON e.lei = g.LEI;

-- S14 EU consolidated list: official entries and dates for the renewed names (Iran snapback banks, Coral/2Rivers, Bellatrix, Alghaf, Chinaoil HK, Redwood)
WITH hit AS (
  SELECT DISTINCT ENTITY_LOGICAL_ID FROM LIBRARY_MARTS.JUSTICE.JUSTICE__INTL_EU_SANCTIONS
  WHERE NAAL_WHOLENAME ILIKE ANY ('%Melli Iran%', '%Tejarat%', '%Saderat Iran%', '%Persia International Bank%', '%Iranische Handelsbank%',
                                   '%Coral Energy%', '%2Rivers%', '%Bellatrix Energy%', '%Alghaf Marine%', '%Chinaoil (Hong Kong)%', '%Redwood Global Supply%'))
SELECT ENTITY_LOGICAL_ID, ANY_VALUE(EU_REF_NUM) eu_ref, ANY_VALUE(PROGRAMME) programme, ANY_VALUE(SUBJECT_TYPE) subj,
       LISTAGG(DISTINCT NAAL_WHOLENAME, ' | ') WITHIN GROUP (ORDER BY NAAL_WHOLENAME) names,
       MIN(TRY_TO_DATE(LEBA_PUBLICATION_DATE)) leba_pub_min, MAX(TRY_TO_DATE(LEBA_PUBLICATION_DATE)) leba_pub_max,
       MIN(TRY_TO_DATE(NAAL_LEBA_PUBLICATION_DATE)) name_pub_min, ANY_VALUE(LEBA_NUMTITLE) leba_title,
       LISTAGG(DISTINCT ADDR_CITY || '/' || ADDR_COUNTRY, ' | ') cities, LEFT(ANY_VALUE(ENTITY_REMARK), 300) remark, ANY_VALUE(DATE_FILE) date_file
FROM LIBRARY_MARTS.JUSTICE.JUSTICE__INTL_EU_SANCTIONS
WHERE ENTITY_LOGICAL_ID IN (SELECT ENTITY_LOGICAL_ID FROM hit)
GROUP BY 1 ORDER BY names;

-- S15 Pub 78: what the odd countries hold (AFGHANISTAN 55, GEORGIA 20) next to CANADA
SELECT COUNTRY, DEDUCTIBILITY_STATUS, STATE, CITY, LEGAL_NAME, EIN
FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_IRS_PUB78_ELIGIBLE_DONEES
WHERE COUNTRY IN ('AFGHANISTAN', 'GEORGIA') OR (COUNTRY = 'CANADA' AND UNIFORM(0::float, 1::float, RANDOM(7)) < 0.03)
ORDER BY COUNTRY, CITY;
