-- S16 GLEIF, by managing office: activity in 2026, and how common prepaid multi-year renewals are (the dull explanation for a sanctioned ID staying current)
SELECT REGISTRATION_MANAGINGLOU lou, COUNT(*) n, COUNT_IF(REGISTRATION_REGISTRATIONSTATUS = 'ISSUED') issued,
       MAX(REGISTRATION_LASTUPDATEDATE) upd_max, COUNT_IF(REGISTRATION_LASTUPDATEDATE >= '2026-01-01') upd_2026,
       COUNT_IF(REGISTRATION_INITIALREGISTRATIONDATE >= '2026-01-01') new_2026,
       -- registered Aug-Oct 2025: first anniversary is after the 2026-07-23 snapshot, so a renewal date past reg + 400 days means a multi-year buy or a very early renewal
       COUNT_IF(REGISTRATION_INITIALREGISTRATIONDATE >= '2025-08-01' AND REGISTRATION_INITIALREGISTRATIONDATE < '2025-11-01') reg_aug_oct25,
       COUNT_IF(REGISTRATION_INITIALREGISTRATIONDATE >= '2025-08-01' AND REGISTRATION_INITIALREGISTRATIONDATE < '2025-11-01'
                AND REGISTRATION_NEXTRENEWALDATE > DATEADD(day, 400, REGISTRATION_INITIALREGISTRATIONDATE)) multi_yr,
       COUNT_IF(REGISTRATION_INITIALREGISTRATIONDATE >= '2025-08-01' AND REGISTRATION_INITIALREGISTRATIONDATE < '2025-11-01'
                AND REGISTRATION_NEXTRENEWALDATE > DATEADD(day, 400, REGISTRATION_INITIALREGISTRATIONDATE)
                AND REGISTRATION_LASTUPDATEDATE > DATEADD(day, 30, REGISTRATION_INITIALREGISTRATIONDATE)) multi_yr_upd_later,
       -- ISSUED records whose renewal date sits more than 430 days past the last touch: paid further ahead than a one-year renewal
       COUNT_IF(REGISTRATION_REGISTRATIONSTATUS = 'ISSUED' AND REGISTRATION_NEXTRENEWALDATE > DATEADD(day, 430, REGISTRATION_LASTUPDATEDATE)) issued_paid_ahead
FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__INTL_GLEIF
GROUP BY 1 ORDER BY n DESC;
