{{ config(materialized='table', schema='POLITICS') }}

-- Source: Voteview -- Roll-Call Votes (member-by-vote matrix) (945523 rows)
-- Generated by gen_mart_models.py
-- Fixed 2026-09-20: bare try_to_number()/try_to_double()/try_to_date() casts replaced in place with the project's guarded macros (stg_int/stg_float/stg_date, macros/staging_casts.sql) -- a value that doesn't parse cleanly now reads NULL instead of being silently rounded or misparsed. Kept on source() (not ref()) because neither of the two staging candidates for this source is the guarded full-staging pattern.

with source as (
    select * from {{ source('ripple_raw', 'FED_VOTEVIEW_ROLLCALLS') }}
)

select
    {{ stg_int('"CONGRESS"') }} as congress,
    CHAMBER as chamber,
    ROLLNUMBER as rollnumber,
    ICPSR as icpsr,
    CAST_CODE as cast_code,
    PROB as prob
from source
