{{ config(materialized='view', schema='TIMELINE', alias='ENERGY__FED_EIA860_3_1_GENERATOR') }}

-- GENERATED by scripts/census/gen_time_views.py -- do not hand-edit.
-- Regenerate after any change to reports/time_index/clock_index.csv.
--
-- Canonical clock for ENERGY.ENERGY__FED_EIA860_3_1_GENERATOR.
--   column : OPERATING_YEAR   (NUMBER)
--   means  : happened -- try_to_number() year; schema.yml documents it as the year the generator began operation - the real in-service event and the only broadly-populated clock on the 
--   grain  : year
--
-- happened cannot be in the future -- if this row's value is, ripple_clock
-- reads 'planned' instead, not 'happened'. See ripple_row_clock in
-- macros/ripple_time.sql.
--
-- The original columns pass through untouched; the canonical four sit in front
-- of them. Rule 8 of the datetime standard: the raw column is never overwritten,
-- so a mis-parse is always recoverable.

select
    {{ ripple_ts_from_year('src."OPERATING_YEAR"') }} as ripple_ts,
    {{ ripple_grain('year') }} as ripple_grain,
    {{ ripple_row_clock(ripple_ts_from_year('src."OPERATING_YEAR"'), 'happened') }} as ripple_clock,
    'ENERGY.ENERGY__FED_EIA860_3_1_GENERATOR'::varchar as ripple_source,
    src.*
from {{ ref('energy__fed_eia860_3_1_generator') }} as src
