{{ config(materialized='view', schema='TIMELINE', alias='ENERGY__FED_EIA861_ADVANCED_METERS') }}

-- GENERATED by scripts/census/gen_time_views.py -- do not hand-edit.
-- Regenerate after any change to reports/time_index/clock_index.csv.
--
-- Canonical clock for ENERGY.ENERGY__FED_EIA861_ADVANCED_METERS.
--   column : DATA_YEAR   (NUMBER)
--   means  : happened -- try_to_number(nullif(trim(DATA_YEAR),'.')) - a plain NUMBER year (2024), the survey year the meter counts describe. Year grain, and it is a number not a date: b
--   grain  : year
--
-- The original columns pass through untouched; the canonical four sit in front
-- of them. Rule 8 of the datetime standard: the raw column is never overwritten,
-- so a mis-parse is always recoverable.

select
    {{ ripple_event_ts(ripple_ts_from_year('src."DATA_YEAR"')) }} as ripple_ts,
    {{ ripple_grain('year') }} as ripple_grain,
    {{ ripple_clock('happened') }} as ripple_clock,
    'ENERGY.ENERGY__FED_EIA861_ADVANCED_METERS'::varchar as ripple_source,
    src.*
from {{ ref('energy__fed_eia861_advanced_meters') }} as src
