-- S01 column names and types for the 5 tables plus the partner tables used for joins
SELECT table_schema, table_name, LISTAGG(column_name || ':' || LEFT(data_type,4), ', ') WITHIN GROUP (ORDER BY ordinal_position) cols
FROM LIBRARY_MARTS.INFORMATION_SCHEMA.COLUMNS
WHERE table_name IN ('FINANCE__FED_IRS_SOI','FINANCE__FED_NCUA_FEDERALLY_INSURED_CU_LIST','FINANCE__FED_FDIC_BANK_DATA',
  'FINANCE__FED_EPA_ICIS_FEC_CASE_ENFORCEMENT_CONCLUSION_FACILITIES','FINANCE__FED_SEC_INSIDER_REPORTINGOWNER',
  'FINANCE__FED_SEC_INSIDER_SUBMISSION','ENVIRONMENT__FED_EPA_ECHO','JUSTICE__FED_FDIC_ENFORCEMENT_ORDERS','ECONOMICS__FED_FDIC_FAILED_BANKS',
  'FINANCE__FED_NCUA_CALL_REPORTS_FOICU','FINANCE__FED_SEC_CLOSED_END_FUND_INFORMATION','FINANCE__FED_EPA_ICIS_FEC_CASE_FACILITIES',
  'FINANCE__FED_NCUA_CHARTER_MERGER_EVENTS','FINANCE__FED_SEC_INVESTMENT_COMPANY_SERIES_CLASS')
GROUP BY 1,2 ORDER BY 2
