-- S02 IRS SOI: rows by tax year and income bracket, state-total ZIPs (00000/99999), numeric parse failures, sums
SELECT TAX_YEAR, AGI_STUB, COUNT(*) n, COUNT(DISTINCT ZIP_CODE) zips, COUNT(DISTINCT STATE) states, COUNT(DISTINCT DATASET_NAME) dsn,
       COUNT_IF(ZIP_CODE = '00000') z00000, COUNT_IF(ZIP_CODE = '99999') z99999, COUNT_IF(LENGTH(ZIP_CODE) <> 5) zlen_bad,
       COUNT_IF(TRY_TO_DOUBLE(N_RETURNS) IS NULL) bad_n, SUM(TRY_TO_DOUBLE(N_RETURNS)) ret, SUM(TRY_TO_DOUBLE(WAGES_SALARIES)) wages_k,
       SUM(TRY_TO_DOUBLE(N_EITC)) n_eitc, SUM(TRY_TO_DOUBLE(EITC_AMOUNT)) eitc_k, SUM(TRY_TO_DOUBLE(PREP)) prep, SUM(TRY_TO_DOUBLE(RAL)) ral,
       SUM(TRY_TO_DOUBLE(RAC)) rac, SUM(TRY_TO_DOUBLE(TOTAL_VITA)) vita, SUM(TRY_TO_DOUBLE(ELDERLY)) elderly,
       COUNT(*) - COUNT(DISTINCT ZIP_CODE, STATE, AGI_STUB, TAX_YEAR) dup_keys
FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_IRS_SOI
GROUP BY ROLLUP(1,2) ORDER BY 1,2;

-- S03 NCUA list: capital, profit, lending and growth by charter type and low-income flag; sentinels
SELECT CREDIT_UNION_TYPE, LOW_INCOME_DESIGNATION, COUNT(*) n, COUNT(DISTINCT CHARTER_NUMBER) charters, COUNT(DISTINCT YEAR_AND_QUARTER) qtrs,
       SUM(TOTAL_ASSETS) assets, MEDIAN(TOTAL_ASSETS) med_assets, MEDIAN(MEMBERS) med_members,
       MEDIAN(NET_WORTH_RATIO_EXCLUDES_CECL_TRANSITION_PROVISION) med_nw, MIN(NET_WORTH_RATIO_EXCLUDES_CECL_TRANSITION_PROVISION) min_nw,
       MAX(NET_WORTH_RATIO_EXCLUDES_CECL_TRANSITION_PROVISION) max_nw,
       COUNT_IF(NET_WORTH_RATIO_EXCLUDES_CECL_TRANSITION_PROVISION < 7) nw_lt7, COUNT_IF(NET_WORTH_RATIO_EXCLUDES_CECL_TRANSITION_PROVISION < 6) nw_lt6,
       COUNT_IF(NET_WORTH_RATIO_EXCLUDES_CECL_TRANSITION_PROVISION < 4) nw_lt4, COUNT_IF(NET_WORTH_RATIO_EXCLUDES_CECL_TRANSITION_PROVISION IS NULL) nw_null,
       MEDIAN(RETURN_ON_AVERAGE_ASSETS) med_roa, COUNT_IF(RETURN_ON_AVERAGE_ASSETS < 0) roa_neg, COUNT_IF(LOAN_TO_SHARE_RATIO > 100) lts_gt100,
       COUNT_IF(MEMBERS_4_QUARTER_GROWTH < 0) mem_shrink, MEDIAN(MEMBERS_4_QUARTER_GROWTH) med_mem_g, MEDIAN(TOTAL_LOANS_4_QUARTER_GROWTH) med_loan_g,
       COUNT_IF(TOTAL_ASSETS IS NULL OR TOTAL_ASSETS = 0) assets0, COUNT_IF(MEMBERS IS NULL OR MEMBERS = 0) members0,
       COUNT_IF(TOTAL_LOANS > TOTAL_ASSETS) loans_gt_assets
FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_NCUA_FEDERALLY_INSURED_CU_LIST
GROUP BY ROLLUP(1,2) ORDER BY 1,2;

-- S04 FDIC bank data: open vs closed, report dates, fill, MDI, load runs; is this really a "sample"?
SELECT ACTIVE, COUNT(*) n, COUNT(DISTINCT CERT) certs, COUNT_IF(ASSET IS NULL) asset_null, SUM(ASSET) asset_k, MEDIAN(ASSET) med_asset_k,
       MIN(REPDTE) rep0, MAX(REPDTE) rep1, MODE(REPDTE) rep_mode, COUNT_IF(REPDTE = (SELECT MAX(REPDTE) FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_FDIC_BANK_DATA)) at_latest,
       MIN(ESTYMD) est0, MAX(ESTYMD) est1, MIN(ENDEFYMD) end0, MAX(ENDEFYMD) end1, COUNT_IF(ENDEFYMD IS NULL) end_null,
       COUNT_IF(NULLIF(TRIM(MDI_STATUS_CODE),'') IS NOT NULL AND MDI_STATUS_CODE NOT IN ('0','00')) mdi, COUNT(DISTINCT _SOURCE_RUN_ID) runs,
       MIN(DATEUPDT) upd0, MAX(DATEUPDT) upd1, COUNT_IF(IN_CONSERVATORSHIP = 'Y') conserv, COUNT_IF(INSURANCE_DROPPED_DATE IS NOT NULL) ins_dropped,
       COUNT(DISTINCT STALP) states, COUNT_IF(NETINC < 0) netinc_neg
FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_FDIC_BANK_DATA
GROUP BY ROLLUP(1) ORDER BY 1;

-- S05 FDIC join test: do failed banks and enforcement-order banks land in the bank directory by CERT?
WITH b AS (SELECT DISTINCT TRY_TO_NUMBER(CERT) cert, ACTIVE FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_FDIC_BANK_DATA),
f AS (SELECT TRY_TO_NUMBER(FDIC_CERT) cert, YEAR(FAIL_DATE) y FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_FDIC_FAILED_BANKS WHERE RESOLUTION_TYPE = 'FAILURE'),
e AS (SELECT DISTINCT CERT_NUMBER cert FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_FDIC_ENFORCEMENT_ORDERS WHERE CERT_NUMBER > 0)
SELECT 'failed_all' src, COUNT(*) n, COUNT_IF(cert IS NOT NULL AND cert > 0) with_cert, COUNT_IF(cert IN (SELECT cert FROM b)) landed FROM f
UNION ALL SELECT 'failed_2000_on', COUNT(*), COUNT_IF(cert > 0), COUNT_IF(cert IN (SELECT cert FROM b)) FROM f WHERE y >= 2000
UNION ALL SELECT 'orders_certs', COUNT(*), COUNT(*), COUNT_IF(cert IN (SELECT cert FROM b)) FROM e
UNION ALL SELECT 'orders_certs_active', COUNT(*), COUNT(*), COUNT_IF(cert IN (SELECT cert FROM b WHERE ACTIVE = '1')) FROM e;

-- S06 EPA conclusion-facility bridge: shape of IDs, case-number formats, duplicate rows, blanks
SELECT COUNT(*) n, COUNT(DISTINCT CASE_NUMBER) cases, COUNT(DISTINCT ENF_CONCLUSION_ID) conclusions, COUNT(DISTINCT ACTIVITY_ID) activities,
       COUNT(DISTINCT FACILITY_UIN) uins, COUNT(DISTINCT ICIS_FACILITY_INTEREST_ID) icis_ids,
       COUNT_IF(FACILITY_UIN IS NULL OR FACILITY_UIN IN ('','None')) uin_blank, COUNT_IF(REGEXP_LIKE(FACILITY_UIN, '^110[0-9]{9}$')) uin_ok,
       COUNT_IF(REGEXP_LIKE(CASE_NUMBER, '^[0-9]{2}-[0-9]{4}-[0-9]+$')) case_rr_yyyy, COUNT_IF(REGEXP_LIKE(CASE_NUMBER, '^HQ-[0-9]{4}-[0-9]+$')) case_hq,
       COUNT(*) - COUNT(DISTINCT ACTIVITY_ID, ENF_CONCLUSION_ID, FACILITY_UIN, ICIS_FACILITY_INTEREST_ID) dup_rows,
       COUNT(DISTINCT CASE_NUMBER, ENF_CONCLUSION_ID) case_concl_pairs,
       ARRAY_AGG(DISTINCT REGEXP_REPLACE(CASE_NUMBER, '[0-9]', '9')) WITHIN GROUP (ORDER BY REGEXP_REPLACE(CASE_NUMBER, '[0-9]', '9')) formats
FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_EPA_ICIS_FEC_CASE_ENFORCEMENT_CONCLUSION_FACILITIES;

-- S07 SEC reporting owner: link to submission by accession, filing years, doc types, duplicate owner rows
WITH r AS (SELECT ACCESSION_NUMBER, OWNER_CIK, RELATIONSHIP FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_INSIDER_REPORTINGOWNER),
s AS (SELECT ACCESSION_NUMBER, FILING_DATE, DOCUMENT_TYPE FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_INSIDER_SUBMISSION)
SELECT YEAR(s.FILING_DATE) y, COUNT(*) n, COUNT(DISTINCT r.ACCESSION_NUMBER) filings, COUNT(DISTINCT r.OWNER_CIK) owners,
       COUNT(*) - COUNT(DISTINCT r.ACCESSION_NUMBER, r.OWNER_CIK) dup_owner_rows, COUNT_IF(s.ACCESSION_NUMBER IS NULL) no_sub,
       COUNT_IF(s.DOCUMENT_TYPE = '4') f4, COUNT_IF(s.DOCUMENT_TYPE = '3') f3, COUNT_IF(s.DOCUMENT_TYPE = '5') f5,
       COUNT_IF(s.DOCUMENT_TYPE LIKE '%/A') amend, COUNT_IF(r.RELATIONSHIP ILIKE '%director%') dir_rows
FROM r LEFT JOIN (SELECT * FROM s QUALIFY ROW_NUMBER() OVER (PARTITION BY ACCESSION_NUMBER ORDER BY FILING_DATE) = 1) s USING (ACCESSION_NUMBER)
GROUP BY 1 ORDER BY 1
