-- S08 IRS SOI: what the short ZIP codes are; are state totals mixed in with ZIPs?
SELECT CASE WHEN ZIP_CODE IN ('0','00000') THEN 'zip_0_state_total' WHEN ZIP_CODE = '99999' THEN 'zip_99999_other'
            WHEN LENGTH(ZIP_CODE) = 5 THEN 'zip5' ELSE 'len' || LENGTH(ZIP_CODE) END kind,
       COUNT(*) n, COUNT(DISTINCT STATE) states, SUM(TRY_TO_DOUBLE(N_RETURNS)) ret, SUM(TRY_TO_DOUBLE(WAGES_SALARIES)) wages_k,
       MAX(TRY_TO_DOUBLE(WAGES_SALARIES)) max_wages_k, MIN(ZIP_CODE) z_min, MAX(ZIP_CODE) z_max,
       ARRAY_AGG(DISTINCT STATE) WITHIN GROUP (ORDER BY STATE) st
FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_IRS_SOI
GROUP BY 1 ORDER BY 1;

-- S09 IRS SOI: per-ZIP extract (real ZIPs only), low-income brackets 1-2 vs all, for local peer math
SELECT STATE, LPAD(ZIP_CODE, 5, '0') zip5,
       SUM(TRY_TO_DOUBLE(N_RETURNS)) ret_all, SUM(IFF(AGI_STUB IN ('1','2'), TRY_TO_DOUBLE(N_RETURNS), 0)) ret_low,
       SUM(IFF(AGI_STUB IN ('1','2'), TRY_TO_DOUBLE(RAC), 0)) rac_low, SUM(TRY_TO_DOUBLE(RAC)) rac_all, SUM(TRY_TO_DOUBLE(RAL)) ral_all,
       SUM(IFF(AGI_STUB IN ('1','2'), TRY_TO_DOUBLE(PREP), 0)) prep_low, SUM(IFF(AGI_STUB IN ('1','2'), TRY_TO_DOUBLE(TOTAL_VITA), 0)) vita_low,
       SUM(TRY_TO_DOUBLE(N_EITC)) n_eitc, SUM(TRY_TO_DOUBLE(EITC_AMOUNT)) eitc_k, SUM(TRY_TO_DOUBLE(AGI)) agi_k, SUM(TRY_TO_DOUBLE(WAGES_SALARIES)) wages_k,
       SUM(TRY_TO_DOUBLE(ELDERLY)) elderly
FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_IRS_SOI
WHERE ZIP_CODE NOT IN ('0', '00000', '99999')
GROUP BY 1, 2;

-- S10 NCUA list: full extract joined to the call-report roster (year opened, peer group, MDI) by charter number
SELECT l.*, f.CU_NUMBER f_cu, f.YEAR_OPENED, f.PEER_GROUP, f.ISMDI, f.LIMITED_INC, f.CU_NAME f_name, f.STATE f_state, f.INSURED_DATE f_insured
FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_NCUA_FEDERALLY_INSURED_CU_LIST l
LEFT JOIN LIBRARY_MARTS.FINANCE.FINANCE__FED_NCUA_CALL_REPORTS_FOICU f ON TRY_TO_NUMBER(f.CU_NUMBER) = TRY_TO_NUMBER(l.CHARTER_NUMBER);

-- S11 NCUA merger events: all 27, and whether the merging charter is still on the insured list
SELECT m.*, l.CHARTER_NUMBER still_listed, l.TOTAL_ASSETS listed_assets, l.NET_WORTH_RATIO_EXCLUDES_CECL_TRANSITION_PROVISION listed_nw
FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_NCUA_CHARTER_MERGER_EVENTS m
LEFT JOIN LIBRARY_MARTS.FINANCE.FINANCE__FED_NCUA_FEDERALLY_INSURED_CU_LIST l ON TRY_TO_NUMBER(l.CHARTER_NUMBER) = TRY_TO_NUMBER(m.MERGING_CREDIT_UNION_CHARTER);

-- S12 FDIC: active banks extract with FDIC enforcement orders aggregated by CERT (all time and since 2020)
WITH o AS (
  SELECT CERT_NUMBER cert, COUNT(*) orders_all, COUNT_IF(ORDER_DATE >= '2020-01-01') orders_2020,
         COUNT_IF(ORDER_DATE >= '2020-01-01' AND (ORDER_TYPE ILIKE '%cease%' OR ORDER_TITLE ILIKE '%consent%' OR ORDER_TITLE ILIKE '%cease%')) cd_2020,
         COUNT_IF(ORDER_DATE >= '2020-01-01' AND ORDER_TYPE ILIKE '%civil money%') cmp_2020,
         SUM(IFF(ORDER_DATE >= '2020-01-01', CMP_AMOUNT_TOTAL, 0)) cmp_amt_2020, MAX(ORDER_DATE) last_order,
         LISTAGG(DISTINCT IFF(ORDER_DATE >= '2020-01-01', ORDER_TYPE, NULL), ' | ') types_2020
  FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_FDIC_ENFORCEMENT_ORDERS WHERE CERT_NUMBER > 0 GROUP BY 1)
SELECT b.CERT, b.NAME, b.CITY, b.STALP, b.BKCLASS, b.CHRTAGNT, b.SPECGRP, b.CLCODE, b.ESTYMD, b.ASSET, b.DEP, b.DEPDOM, b.NETINC, b.REPDTE,
       b.OFFICES, b.OFFICES_DOMESTIC, b.MDI_STATUS_CODE, b.MDI_STATUS_DESC, b.HOLDING_COMPANY_NAME, b.FDIC_SUPERVISOR, b.CBSA_METRO_NAME,
       o.orders_all, o.orders_2020, o.cd_2020, o.cmp_2020, o.cmp_amt_2020, o.last_order, o.types_2020
FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_FDIC_BANK_DATA b LEFT JOIN o ON o.cert = TRY_TO_NUMBER(b.CERT)
WHERE b.ACTIVE = '1';

-- S13 EPA bridge: case-number year and prefix; cases, conclusions, facility rows, biggest conclusion per year
WITH t AS (SELECT CASE_NUMBER, ENF_CONCLUSION_ID, FACILITY_UIN, SPLIT_PART(CASE_NUMBER, '-', 1) pre, TRY_TO_NUMBER(SPLIT_PART(CASE_NUMBER, '-', 2)) yr
           FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_EPA_ICIS_FEC_CASE_ENFORCEMENT_CONCLUSION_FACILITIES),
c AS (SELECT yr, pre, ENF_CONCLUSION_ID, COUNT(*) fac FROM t GROUP BY 1, 2, 3)
SELECT yr, COUNT(*) conclusions, SUM(fac) fac_rows, COUNT_IF(pre = 'HQ') hq, COUNT_IF(pre IN ('EF','WF')) ef_wf,
       COUNT_IF(fac = 1) single_site, MAX(fac) max_sites, MEDIAN(fac) med_sites
FROM c GROUP BY 1 ORDER BY 1;

-- S14 EPA bridge: the top facilities by distinct cases, and the conclusions that cover the most sites
SELECT 'top_facility' kind, FACILITY_UIN id, ANY_VALUE(FACILITY_NAME) name, ANY_VALUE(FACILITY_CITY) city, ANY_VALUE(FACILITY_STATE) st,
       COUNT(DISTINCT CASE_NUMBER) cases, COUNT(*) n_rows, MIN(CASE_NUMBER) c_min, MAX(CASE_NUMBER) c_max, COUNT(DISTINCT FACILITY_NAME) names
FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_EPA_ICIS_FEC_CASE_ENFORCEMENT_CONCLUSION_FACILITIES
GROUP BY 2 QUALIFY ROW_NUMBER() OVER (ORDER BY COUNT(DISTINCT CASE_NUMBER) DESC) <= 40
UNION ALL
SELECT 'big_conclusion', ENF_CONCLUSION_ID, ANY_VALUE(FACILITY_NAME), ANY_VALUE(CASE_NUMBER), ANY_VALUE(FACILITY_STATE),
       COUNT(DISTINCT FACILITY_STATE), COUNT(*), MIN(FACILITY_NAME), MAX(FACILITY_NAME), COUNT(DISTINCT FACILITY_NAME)
FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_EPA_ICIS_FEC_CASE_ENFORCEMENT_CONCLUSION_FACILITIES
GROUP BY 2 QUALIFY ROW_NUMBER() OVER (ORDER BY COUNT(*) DESC) <= 20;

-- S15 EPA bridge x ECHO: per-facility case count joined to ECHO status by FRS registry ID (extract for local peer math)
WITH f AS (SELECT FACILITY_UIN, COUNT(DISTINCT CASE_NUMBER) cases, MAX(TRY_TO_NUMBER(SPLIT_PART(CASE_NUMBER, '-', 2))) last_case_yr,
                  MIN(TRY_TO_NUMBER(SPLIT_PART(CASE_NUMBER, '-', 2))) first_case_yr, ANY_VALUE(FACILITY_NAME) name, ANY_VALUE(FACILITY_STATE) st
           FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_EPA_ICIS_FEC_CASE_ENFORCEMENT_CONCLUSION_FACILITIES
           WHERE REGEXP_LIKE(FACILITY_UIN, '^110[0-9]{9}$') GROUP BY 1),
e AS (SELECT FRS_ID, COMPLIANCE_STATUS, QUARTERS_WITH_NONCOMPLIANCE, FORMAL_ACTION_COUNT, TOTAL_PENALTIES, IS_MAJOR_FACILITY, IS_ACTIVE,
             HAS_AIR_PROGRAM, HAS_WATER_PROGRAM, HAS_HAZWASTE_PROGRAM, TOTAL_INSPECTION_COUNT, PCT_MINORITY, FACILITY_NAME e_name, CITY e_city, STATE e_st
      FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ECHO QUALIFY ROW_NUMBER() OVER (PARTITION BY FRS_ID ORDER BY FORMAL_ACTION_COUNT DESC NULLS LAST) = 1)
SELECT f.*, e.* FROM f LEFT JOIN e ON e.FRS_ID = f.FACILITY_UIN;

-- S16 SEC insiders 2024: every (owner, issuer) pair on 2024 filings, with fund flags and the issuer's SIC from DERA 2024 filings
WITH s AS (SELECT ACCESSION_NUMBER, FILING_DATE, DOCUMENT_TYPE, TRY_TO_NUMBER(ISSUER_CIK) icik, ISSUER_NAME, ISSUER_TICKER
           FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_INSIDER_SUBMISSION WHERE FILING_DATE >= '2024-01-01' AND FILING_DATE < '2025-01-01'),
r AS (SELECT ACCESSION_NUMBER, OWNER_CIK, OWNER_NAME, RELATIONSHIP, TITLE, CITY, STATE FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_INSIDER_REPORTINGOWNER),
fund AS (SELECT TRY_TO_NUMBER(CIK) cik FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_CLOSED_END_FUND_INFORMATION
         UNION SELECT TRY_TO_NUMBER(CIK) FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_BUSINESS_DEVELOPMENT_COMPANY_REPORT
         UNION SELECT TRY_TO_NUMBER(CIK_NUMBER) FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_INVESTMENT_COMPANY_SERIES_CLASS),
sic AS (SELECT TRY_TO_NUMBER(CIK) cik, MODE(SIC) sic, MODE(AFS) afs FROM (
          SELECT CIK, SIC, AFS FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_DERA_SUB_2024Q1 UNION ALL SELECT CIK, SIC, AFS FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_DERA_SUB_2024Q2
          UNION ALL SELECT CIK, SIC, AFS FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_DERA_SUB_2024Q3 UNION ALL SELECT CIK, SIC, AFS FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_DERA_SUB_2024Q4) GROUP BY 1)
SELECT r.OWNER_CIK, ANY_VALUE(r.OWNER_NAME) owner_name, s.icik, ANY_VALUE(s.ISSUER_NAME) issuer_name, ANY_VALUE(s.ISSUER_TICKER) ticker,
       LISTAGG(DISTINCT r.RELATIONSHIP, '|') rels, ANY_VALUE(r.TITLE) title, ANY_VALUE(r.STATE) owner_st, COUNT(DISTINCT s.ACCESSION_NUMBER) filings,
       MIN(s.FILING_DATE) d0, MAX(s.FILING_DATE) d1, MAX(IFF(fund.cik IS NOT NULL, 1, 0)) is_fund, ANY_VALUE(sic.sic) sic, ANY_VALUE(sic.afs) afs,
       (SELECT MAX(FILING_DATE) FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_INSIDER_SUBMISSION) max_filing_all
FROM r JOIN s USING (ACCESSION_NUMBER) LEFT JOIN fund ON fund.cik = s.icik LEFT JOIN sic ON sic.cik = s.icik
GROUP BY r.OWNER_CIK, s.icik
