-- S17 NCUA raw call report (FS220) rows for the 4 negative-net-worth credit unions plus Navy Federal as a control
SELECT * FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_NCUA_CALL_REPORTS_FS220
WHERE TRY_TO_NUMBER(CU_NUMBER) IN (8445, 24940, 2796, 24937, 5536);

-- S18 FDIC enforcement orders since 2010, raw, for local classification (bank vs person, termination vs new)
SELECT ORDER_ID, ORDER_DATE, ORDER_YEAR, ORDER_CATEGORY, ORDER_TYPE, ORDER_TITLE, LEFT(RESPONDENTS, 160) respondents, RESPONDENT_COUNT,
       CERT_NUMBER, BANK_COUNT, CMP_AMOUNT_TOTAL, BANK_NAME, INSTITUTION_NAME, BANK_STATE, BANK_ACTIVE
FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_FDIC_ENFORCEMENT_ORDERS
WHERE ORDER_DATE >= '2010-01-01';

-- S19 FDIC bank directory, every institution, minimal columns, to rebuild who was open when
SELECT CERT, NAME, CITY, STALP, ACTIVE, BKCLASS, CHRTAGNT, SPECGRP, ESTYMD, ENDEFYMD, ASSET, REPDTE, NETINC, MDI_STATUS_CODE, MDI_STATUS_DESC,
       OFFICES_DOMESTIC, HOLDING_COMPANY_NAME, INSURANCE_DROPPED_DATE, SUCCESSOR_CERT
FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_FDIC_BANK_DATA;

-- S20 SEC insiders: people filing as Director at 5+ non-fund issuers, by filing year 2016-2024, plus yearly totals
WITH s AS (SELECT ACCESSION_NUMBER, YEAR(FILING_DATE) y, TRY_TO_NUMBER(ISSUER_CIK) icik, ISSUER_NAME
           FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_INSIDER_SUBMISSION WHERE FILING_DATE >= '2016-01-01' AND FILING_DATE < '2025-01-01'),
r AS (SELECT ACCESSION_NUMBER, OWNER_CIK, OWNER_NAME FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_INSIDER_REPORTINGOWNER WHERE RELATIONSHIP ILIKE '%Director%'),
fund AS (SELECT TRY_TO_NUMBER(CIK) cik FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_CLOSED_END_FUND_INFORMATION
         UNION SELECT TRY_TO_NUMBER(CIK) FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_BUSINESS_DEVELOPMENT_COMPANY_REPORT
         UNION SELECT TRY_TO_NUMBER(CIK_NUMBER) FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_INVESTMENT_COMPANY_SERIES_CLASS),
p AS (SELECT s.y, r.OWNER_CIK, ANY_VALUE(r.OWNER_NAME) nm, COUNT(DISTINCT s.icik) n_iss,
             COUNT(DISTINCT IFF(fund.cik IS NULL AND NOT REGEXP_LIKE(s.ISSUER_NAME, '.*(FUND|TRUST|MUNI|INCOME|PORTFOLIO|OPPORTUNIT).*', 'i'), s.icik, NULL)) n_op,
             LISTAGG(DISTINCT IFF(fund.cik IS NULL AND NOT REGEXP_LIKE(s.ISSUER_NAME, '.*(FUND|TRUST|MUNI|INCOME|PORTFOLIO|OPPORTUNIT).*', 'i'), LEFT(s.ISSUER_NAME, 30), NULL), ' | ') iss
      FROM r JOIN s USING (ACCESSION_NUMBER) LEFT JOIN fund ON fund.cik = s.icik GROUP BY 1, 2)
SELECT y, OWNER_CIK, nm, n_iss, n_op, iss FROM p WHERE n_op >= 5
UNION ALL
SELECT y, 'ALL', NULL, COUNT(*), COUNT_IF(n_op >= 5), TO_VARCHAR(COUNT_IF(n_op >= 10)) FROM p GROUP BY y;

-- S21 SEC insiders: filings whose remarks say "director by deputization", per year and owner, plus yearly issuer totals
WITH s AS (SELECT ACCESSION_NUMBER, YEAR(FILING_DATE) y, TRY_TO_NUMBER(ISSUER_CIK) icik
           FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_INSIDER_SUBMISSION
           WHERE (REMARKS ILIKE '%deputiz%' OR REMARKS ILIKE '%deputis%') AND FILING_DATE < '2025-04-01'),
r AS (SELECT ACCESSION_NUMBER, OWNER_CIK, OWNER_NAME, RELATIONSHIP FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_INSIDER_REPORTINGOWNER),
j AS (SELECT s.y, s.icik, s.ACCESSION_NUMBER, r.OWNER_CIK, r.OWNER_NAME, r.RELATIONSHIP FROM s JOIN r USING (ACCESSION_NUMBER))
SELECT y, OWNER_CIK, ANY_VALUE(OWNER_NAME) nm, COUNT(DISTINCT icik) issuers, COUNT(DISTINCT ACCESSION_NUMBER) filings, COUNT_IF(RELATIONSHIP ILIKE '%Director%') dir_rows
FROM j GROUP BY 1, 2 HAVING COUNT(DISTINCT icik) >= 3
UNION ALL
SELECT y, 'ALL', NULL, COUNT(DISTINCT icik), COUNT(DISTINCT ACCESSION_NUMBER), COUNT(DISTINCT OWNER_CIK) FROM j GROUP BY 1;

-- S22 EPA bridge: the placeholder facility ID and the blank-ID rows, by case-number prefix (region) and case year
SELECT COALESCE(NULLIF(FACILITY_UIN, 'None'), 'blank') uin, SPLIT_PART(CASE_NUMBER, '-', 1) pre, COUNT(DISTINCT CASE_NUMBER) cases, COUNT(*) n,
       MIN(TRY_TO_NUMBER(SPLIT_PART(CASE_NUMBER, '-', 2))) y0, MAX(TRY_TO_NUMBER(SPLIT_PART(CASE_NUMBER, '-', 2))) y1,
       COUNT(DISTINCT FACILITY_STATE) states, ANY_VALUE(FACILITY_STATE) any_st, COUNT(DISTINCT FACILITY_NAME) names
FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_EPA_ICIS_FEC_CASE_ENFORCEMENT_CONCLUSION_FACILITIES
WHERE FACILITY_UIN = '110009327022' OR FACILITY_UIN IS NULL OR FACILITY_UIN IN ('', 'None')
GROUP BY 1, 2 ORDER BY 1, 2
