-- S23 FDIC: the 12 new consent orders 2020-2026 against minority-owned (MDI) FDIC-supervised banks, with the order document links
SELECT ORDER_ID, ORDER_DATE, CERT_NUMBER, BANK_NAME, BANK_STATE, ORDER_TITLE, ORDER_TYPE, CMP_AMOUNT_TOTAL, DOCKET_NUMBER, DOCUMENT_URL
FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_FDIC_ENFORCEMENT_ORDERS
WHERE CERT_NUMBER IN (58037, 33708, 13959, 26708, 22460, 10319, 59182, 58816, 59154, 57884) AND ORDER_DATE >= '2020-01-01'
ORDER BY ORDER_DATE;

-- S24 SEC: RA Capital 2024 filings, what the remarks say and how many reporting owners ride on each filing
WITH s AS (SELECT ACCESSION_NUMBER, FILING_DATE, DOCUMENT_TYPE, ISSUER_NAME, REMARKS
           FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_INSIDER_SUBMISSION WHERE FILING_DATE >= '2024-01-01' AND FILING_DATE < '2025-01-01'),
r AS (SELECT ACCESSION_NUMBER, COUNT(*) n_owners, LISTAGG(DISTINCT OWNER_NAME, ' | ') owners, LISTAGG(DISTINCT RELATIONSHIP, ' | ') rels,
             MAX(IFF(OWNER_NAME ILIKE 'RA CAPITAL%' OR OWNER_NAME ILIKE 'Kolchinsky%' OR OWNER_NAME ILIKE 'Shah Rajeev%', 1, 0)) ra
      FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_INSIDER_REPORTINGOWNER GROUP BY 1)
SELECT s.ISSUER_NAME, COUNT(*) filings, MIN(s.FILING_DATE) d0, MAX(s.FILING_DATE) d1, MEDIAN(r.n_owners) med_owners, ANY_VALUE(r.rels) rels,
       ANY_VALUE(r.owners) owners, ANY_VALUE(LEFT(s.REMARKS, 300)) remarks_sample,
       COUNT_IF(s.REMARKS ILIKE '%director%') remarks_say_director
FROM s JOIN r USING (ACCESSION_NUMBER) WHERE r.ra = 1
GROUP BY 1 ORDER BY 2 DESC
