{{ config(tags=['minimal_staging']) }}

-- GRAIN: NOT YET DETERMINED (profiler returned AMBIGUOUS -- needs manual review)
-- This is a passthrough staging view: snake_case rename only, no dedup.
-- Once grain is resolved, replace with a full staging model via generate_staging_models.py.
-- Generated by scripts/generate_minimal_staging.py

with source as (

    select * from {{ source('ripple_raw', 'INTL_AR_DATOSGOB') }}

),

renamed as (

    select
        DATASET_ID as dataset_id,
        DATASET_TITLE as dataset_title,
        C_ORGANIZATION as c_organization,
        RESOURCE_URL as resource_url,
        FORMAT as format,
        LAST_MODIFIED as last_modified,
        LICENSE as license,
        DESCRIPTION as description,
        TAGS as tags,
        SERIE_ID as serie_id,
        SERIE_VALUE as serie_value,
        SERIE_DATE as serie_date,
        PROVINCIA_ID as provincia_id,
        MUNICIPIO_ID as municipio_id,
        DEPARTAMENTO_ID as departamento_id,
        _INGESTED_AT as _loaded_at,
        'https://datos.gob.ar/apis' as _source_url

    from source

)

select * from renamed
