{{ config(materialized='table', schema='INVESTIGATIONS') }}

-- Source: XC_WAYBACK_REPLAY_DOJ_DEEP_PAGES (2542 rows)
-- Generated by gen_mart_models.py

with source as (
    select * from {{ source('ripple_raw', 'XC_WAYBACK_REPLAY_DOJ_DEEP_PAGES') }}
)

select
    RECORD as record
from source
