{{ config(tags=['spine_generated']) }}

-- GRAIN: one row per record (spine_entity not determined -- no registry hint available) (ID unique)
-- SPINE_ENTITY: (not determined)  (natural_key: ID)
-- Generated by scripts/generate_staging_models.py from SOURCE_REGISTRY -- deterministic,
-- no LLM. Casts kept as landed (TEXT) -- add explicit type casts by hand once each
-- column's real type is confirmed; this generator has no semantic type knowledge.
-- spine_entity not determined (grain/natural_key proven, but no registry hint says what this row is ABOUT) -- no SPINE_ENTITY_ID emitted.
-- landing table's ingestion timestamp is named INGESTED_AT (no leading underscore) rather than the usual _INGESTED_AT -- confirmed via INFORMATION_SCHEMA, not assumed.

with source as (

    select * from {{ source('ripple_raw', 'PORTAL_ARC_NEW_MEXICO_OPEN_1B6C7F7FBD') }}

),

renamed as (

    select
        "FID" as fid,
        "OBJECTID" as objectid,
        "ID" as id,
        "NAME" as name,
        "ADDRESS" as address,
        "CITY" as city,
        "STATE" as state,
        "ZIP" as zip,
        "TELEPHONE" as telephone,
        "TYPE" as type,
        "COUNTRY" as country,
        "NAICS_CODE" as naics_code,
        "NAICS_DESC" as naics_desc,
        "SOURCE" as source,
        "SOURCEDATE" as sourcedate,
        "VAL_METHOD" as val_method,
        "VAL_DATE" as val_date,
        "WEBSITE" as website,
        "REGULATED" as regulated,
        "CNTRL_AREA" as cntrl_area,
        "PLAN_AREA" as plan_area,
        "HOLDING_CO" as holding_co,
        "SUMMR_PEAK" as summr_peak,
        "WINTR_PEAK" as wintr_peak,
        "SUMMER_CAP" as summer_cap,
        "WINTER_CAP" as winter_cap,
        "NET_GEN" as net_gen,
        "PURCHASED" as purchased,
        "NET_EX" as net_ex,
        "RETAIL_MWH" as retail_mwh,
        "WSALE_MWH" as wsale_mwh,
        "TOTAL_MWH" as total_mwh,
        "TRANS_MWH" as trans_mwh,
        "CUSTOMERS" as customers,
        "YEAR" as year,
        "SHAPE__ARE" as shape__are,
        "SHAPE__LEN" as shape__len,
        "SHAPE_LENG" as shape_leng,
        "SHAPE_AREA" as shape_area,
        "SHAPE__AREA" as shape__area,
        "SHAPE__LENGTH" as shape__length,
        "GEOMETRY" as geometry,
        INGESTED_AT as _loaded_at,
        'https://data-nmenv.opendata.arcgis.com/datasets/f812e7be7b524edcaffb86158eca1738_0' as _source_url

    from source

)

select * from renamed
qualify row_number() over (partition by id order by _loaded_at desc) = 1
