{{ config(tags=['spine_generated']) }}

-- GRAIN: one row per place (LATLON+BUSINESS_LICENSE_YEAR+DATE_OF_OPENING_IN_ATLANTA+PREVIOUS_YEAR_REPORTED_REVENUE unique)
-- SPINE_ENTITY: place  (natural_key: LONGITUDE, BUSINESS_LICENSE_YEAR, DATE_OF_OPENING_IN_ATLANTA, PREVIOUS_YEAR_REPORTED_REVENUE)
-- Generated by scripts/generate_staging_models.py from SOURCE_REGISTRY -- deterministic,
-- no LLM.
-- CASTS: 4 of 20 columns, from landing_column_profile_2026-09-19.tsv. A column is cast only
-- when every filled value in the sample parsed. try_ casts: a value that does not
-- parse reads NULL. The natural key and join-key columns stay TEXT.
--   objectid: ID: whole numbers, over 90% distinct -- stays TEXT, '.0' tail removed
--   field1: ID: whole numbers, over 90% distinct -- stays TEXT, '.0' tail removed
--   current_year_reported_number_of: integer
--   score: float
-- spine_entity 'place' has no connect/ resolver yet (see connect/spine_entity.py) -- no SPINE_ENTITY_ID emitted.
-- landing table's ingestion timestamp is named INGESTED_AT (no leading underscore) rather than the usual _INGESTED_AT -- confirmed via INFORMATION_SCHEMA, not assumed.
-- DEDUPE: registry natural_key (LONGITUDE, BUSINESS_LICENSE_YEAR, DATE_OF_OPENING_IN_ATLANTA, PREVIOUS_YEAR_REPORTED_REVENUE) is NOT unique within a load as landed at generation time -- it would collapse 129 of 19,297 rows. Deduping on the WHOLE ROW instead (exact copies only). A record that changes between loads shows once per version. Find the real key, fix SOURCE_REGISTRY, regenerate.

with source as (

    select * from {{ source('ripple_raw', 'PORTAL_ARC_ATLANTA_DATAATLA_EAD25CBDC7') }}
    qualify row_number() over (partition by "OBJECTID", "FIELD1", "LICENSENUMBER", "BUSINESS_NAME", "DBA", "ADDRESS", "BUSINESS_LICENSE_YEAR", "NAICS_CODE", "BUSINESS_TYPE___NAICS_CODE_DESC", "TYPE_OF_BUSINESS", "DATE_OF_OPENING_IN_ATLANTA", "PREVIOUS_YEAR_REPORTED_REVENUE", "CURRENT_YEAR_REPORTED_NUMBER_OF", "FULLADDRESS", "LATITUDE", "LONGITUDE", "MATCH", "SCORE", "ADDR_TYPE", "GEOMETRY" order by INGESTED_AT desc) = 1

),

renamed as (

    select
        {{ stg_id_text('"OBJECTID"') }} as objectid,
        {{ stg_id_text('"FIELD1"') }} as field1,
        {{ null_junk('"LICENSENUMBER"') }} as licensenumber,
        {{ null_junk('"BUSINESS_NAME"') }} as business_name,
        {{ null_junk('"DBA"') }} as dba,
        {{ null_junk('"ADDRESS"') }} as address,
        {{ null_junk('"BUSINESS_LICENSE_YEAR"') }} as business_license_year,
        {{ null_junk('"NAICS_CODE"') }} as naics_code,
        {{ null_junk('"BUSINESS_TYPE___NAICS_CODE_DESC"') }} as business_type___naics_code_desc,
        {{ null_junk('"TYPE_OF_BUSINESS"') }} as type_of_business,
        {{ null_junk('"DATE_OF_OPENING_IN_ATLANTA"') }} as date_of_opening_in_atlanta,
        {{ null_junk('"PREVIOUS_YEAR_REPORTED_REVENUE"') }} as previous_year_reported_revenue,
        {{ stg_int('"CURRENT_YEAR_REPORTED_NUMBER_OF"') }} as current_year_reported_number_of,
        {{ null_junk('"FULLADDRESS"') }} as fulladdress,
        {{ null_junk('"LATITUDE"') }} as latitude,
        {{ null_junk('"LONGITUDE"') }} as longitude,
        {{ null_junk('"MATCH"') }} as match,
        {{ stg_float('"SCORE"') }} as score,
        {{ null_junk('"ADDR_TYPE"') }} as addr_type,
        {{ null_junk('"GEOMETRY"') }} as geometry,
        INGESTED_AT as _loaded_at,
        'https://dpcd-coaplangis.opendata.arcgis.com/datasets/1d0c61a466a743e4abe2ceb95c835f11_0' as _source_url

    from source

)

select * from renamed
