{{ config(tags=['spine_generated']) }}

-- GRAIN: one row per place (ZIP+STATUS_DTTM unique)
-- SPINE_ENTITY: place  (natural_key: CONTACT_ZIP, STATUS_DTTM)
-- Generated by scripts/generate_staging_models.py from SOURCE_REGISTRY -- deterministic,
-- no LLM. Casts kept as landed (TEXT) -- add explicit type casts by hand once each
-- column's real type is confirmed; this generator has no semantic type knowledge.
-- spine_entity 'place' has no connect/ resolver yet (see connect/spine_entity.py) -- no SPINE_ENTITY_ID emitted.
-- landing table's ingestion timestamp is named INGESTED_AT (no leading underscore) rather than the usual _INGESTED_AT -- confirmed via INFORMATION_SCHEMA, not assumed.
-- DEDUPE: registry natural_key (CONTACT_ZIP, STATUS_DTTM) is NOT unique within a load as landed at generation time -- it would collapse 43 of 9,999 rows. Deduping on the WHOLE ROW instead (exact copies only). A record that changes between loads shows once per version. Find the real key, fix SOURCE_REGISTRY, regenerate.

with source as (

    select * from {{ source('ripple_raw', 'PORTAL_CKA_ANALYZE_BOSTON_F1B3F76830') }}

),

renamed as (

    select
        "CASE_NO" as case_no,
        "AP_CASE_DEFN_KEY" as ap_case_defn_key,
        "STATUS_DTTM" as status_dttm,
        "STATUS" as status,
        "CODE" as code,
        "VALUE" as value,
        "DESCRIPTION" as description,
        "VIOLATION_STNO" as violation_stno,
        "VIOLATION_STHIGH" as violation_sthigh,
        "VIOLATION_STREET" as violation_street,
        "VIOLATION_SUFFIX" as violation_suffix,
        "VIOLATION_CITY" as violation_city,
        "VIOLATION_STATE" as violation_state,
        "VIOLATION_ZIP" as violation_zip,
        "WARD" as ward,
        "CONTACT_ADDR1" as contact_addr1,
        "CONTACT_ADDR2" as contact_addr2,
        "CONTACT_CITY" as contact_city,
        "CONTACT_STATE" as contact_state,
        "CONTACT_ZIP" as contact_zip,
        "SAM_ID" as sam_id,
        "LATITUDE" as latitude,
        "LONGITUDE" as longitude,
        "LOCATION" as location,
        INGESTED_AT as _loaded_at,
        'https://data.boston.gov/dataset/building-and-property-violations1' as _source_url

    from source

)

select * from renamed
qualify row_number() over (partition by case_no, ap_case_defn_key, status_dttm, status, code, value, description, violation_stno, violation_sthigh, violation_street, violation_suffix, violation_city, violation_state, violation_zip, ward, contact_addr1, contact_addr2, contact_city, contact_state, contact_zip, sam_id, latitude, longitude, location order by _loaded_at desc) = 1
