-- S01 Columns and types for the five tables
SELECT TABLE_NAME, ORDINAL_POSITION, COLUMN_NAME, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH
FROM LIBRARY_MARTS.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'CORE' AND TABLE_NAME IN ('DIM_ZIP_POINT','XWALK_ZCTA_COUNTY','DIM_COUNTY','XWALK_HOSPITAL_CCN_EIN','DIM_DATE')
ORDER BY 1, 2
