-- S15 Connecticut in the ZIP tables: CT ZIPs in the crosswalk vs CT rows in DIM_ZIP_POINT; which dot holds the most ZIPs
SELECT (SELECT COUNT(DISTINCT ZCTA5) FROM LIBRARY_MARTS.CORE.XWALK_ZCTA_COUNTY WHERE STATE_USPS = 'CT') ct_zips_in_xwalk,
       (SELECT COUNT(*) FROM LIBRARY_MARTS.CORE.DIM_ZIP_POINT WHERE STATE_USPS = 'CT' OR STATE_FIPS = '09' OR PRIMARY_COUNTY_FIPS LIKE '09%') ct_rows_in_point,
       (SELECT PRIMARY_COUNTY_FIPS || ' ' || COUNTY_NAME || ' ' || COUNT(*) FROM LIBRARY_MARTS.CORE.DIM_ZIP_POINT GROUP BY PRIMARY_COUNTY_FIPS, COUNTY_NAME ORDER BY COUNT(*) DESC LIMIT 1) biggest_dot
