    with source as (
        select * from {{ source('ripple_raw', 'FED_FEMA_DISASTER_DECLARATIONS') }}
    )

    select
        "FEMADECLARATIONSTRING",
"DISASTERNUMBER",
"STATE",
"DECLARATIONTYPE",
"DECLARATIONDATE",
"FYDECLARED",
"INCIDENTTYPE",
"DECLARATIONTITLE",
"IHPROGRAMDECLARED",
"IAPROGRAMDECLARED",
"PAPROGRAMDECLARED",
"HMPROGRAMDECLARED",
"INCIDENTBEGINDATE",
"INCIDENTENDDATE",
"DISASTERCLOSEOUTDATE",
"TRIBALREQUEST",
"FIPSSTATECODE",
"FIPSCOUNTYCODE",
"PLACECODE",
"DESIGNATEDAREA",
"DECLARATIONREQUESTNUMBER",
"DECLARATIONREQUESTDATE",
"LASTIAFILINGDATE",
"INCIDENTID",
"REGION",
"DESIGNATEDINCIDENTTYPES",
"LASTREFRESH",
"HASH",
"ID" as ID,
_INGESTED_AT,
_SOURCE_RUN_ID
    from source
    qualify row_number() over (
        partition by ID
        order by _INGESTED_AT desc
    ) = 1
