-- Q1 extract: every non-990T index row for revoked (2019 on) EINs whose tax period ends exactly 5/17/29 months before the revocation date, any processing time
WITH r AS (
  SELECT EIN, LEGAL_NAME, STATE, EXEMPTION_TYPE, REVOCATION_DATE d, REVOCATION_POSTING_DATE pd, REINSTATEMENT_DATE rd
  FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_IRS_AUTO_REVOCATIONS WHERE REVOCATION_DATE >= '2019-01-01'),
i AS (
  SELECT EIN, TAX_PERIOD, TRY_TO_DATE(TAX_PERIOD || '01', 'YYYYMMDD') p, SUB_DATE, SUB_DATE_RAW, RETURN_TYPE, OBJECT_ID, DLN, TAXPAYER_NAME
  FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_IRS_990_EFILE_INDEX
  WHERE RETURN_TYPE <> '990T' AND EIN IN (SELECT EIN FROM r))
SELECT r.EIN, r.LEGAL_NAME, r.STATE, r.EXEMPTION_TYPE, r.d, r.pd, r.rd, i.TAX_PERIOD, DATEDIFF(month, i.p, r.d) k,
  i.SUB_DATE, i.SUB_DATE_RAW, i.RETURN_TYPE, i.OBJECT_ID, i.DLN, i.TAXPAYER_NAME
FROM r JOIN i ON i.EIN = r.EIN
WHERE DATEDIFF(month, i.p, r.d) IN (5, 17, 29);

-- Q2 denominators by revocation year: all revocation rows, rows whose EIN e-filed any 990/EZ/PF (builder labels), rows whose EIN e-filed any non-990T label
WITH r AS (SELECT EIN, REVOCATION_DATE d FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_IRS_AUTO_REVOCATIONS WHERE REVOCATION_DATE >= '2019-01-01'),
e1 AS (SELECT DISTINCT EIN FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_IRS_990_EFILE_INDEX WHERE RETURN_TYPE IN ('990','990EZ','990PF') AND EIN IN (SELECT EIN FROM r)),
e2 AS (SELECT DISTINCT EIN FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_IRS_990_EFILE_INDEX WHERE RETURN_TYPE <> '990T' AND EIN IN (SELECT EIN FROM r))
SELECT YEAR(r.d) rev_y, COUNT(*) rows_all, COUNT(DISTINCT r.EIN) eins_all, COUNT(e1.EIN) efiler_builder_labels, COUNT(e2.EIN) efiler_all_labels
FROM r LEFT JOIN e1 ON e1.EIN = r.EIN LEFT JOIN e2 ON e2.EIN = r.EIN
GROUP BY 1 ORDER BY 1;

-- Q3 whole-table DLN checks: form label vs DLN doc code, DLN year digit vs index year, length
SELECT RETURN_TYPE, REGEXP_LIKE(TRIM(SUB_DATE_RAW), '^[0-9]{4}$') year_only, SUBSTR(DLN, 1, 5) dln_prefix, COUNT(*) n,
  COUNT_IF(LENGTH(DLN) <> 14) dln_not14,
  COUNT_IF(MOD(TRY_TO_NUMBER(SUBSTR(DLN, 14, 1)) - MOD(YEAR(SUB_DATE), 10) + 10, 10) = 0) dln_same_year,
  COUNT_IF(MOD(TRY_TO_NUMBER(SUBSTR(DLN, 14, 1)) - MOD(YEAR(SUB_DATE), 10) + 10, 10) = 9) dln_year_before,
  COUNT_IF(MOD(TRY_TO_NUMBER(SUBSTR(DLN, 14, 1)) - MOD(YEAR(SUB_DATE), 10) + 10, 10) = 1) dln_year_after,
  COUNT_IF(TRY_TO_NUMBER(SUBSTR(DLN, 6, 3)) NOT BETWEEN 1 AND 366) jul_bad
FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_IRS_990_EFILE_INDEX
GROUP BY 1, 2, 3 ORDER BY 1, 2, 3;

-- Q4 which LIBRARY_MARTS tables carry an OBJECT_ID column, or are Pub 78 / e-postcard / 990 tables (to find the XML-derived returns)
SELECT TABLE_SCHEMA, TABLE_NAME, LISTAGG(COLUMN_NAME, ',') WITHIN GROUP (ORDER BY ORDINAL_POSITION) cols
FROM LIBRARY_MARTS.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME IN (SELECT TABLE_NAME FROM LIBRARY_MARTS.INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'OBJECT_ID')
   OR TABLE_NAME ILIKE '%PUB78%' OR TABLE_NAME ILIKE '%POSTCARD%' OR TABLE_NAME ILIKE '%990%'
GROUP BY 1, 2 ORDER BY 1, 2;
