{{ config(tags=['spine_generated']) }}

-- GRAIN: one row per record (spine_entity not determined -- no registry hint available) (OPPORTUNITY_ID is unique)
-- SPINE_ENTITY: (not determined)  (natural_key: OPPORTUNITY_ID)
-- Generated by scripts/generate_staging_models.py from SOURCE_REGISTRY -- deterministic,
-- no LLM. Casts kept as landed (TEXT) -- add explicit type casts by hand once each
-- column's real type is confirmed; this generator has no semantic type knowledge.
-- spine_entity not determined (grain/natural_key proven, but no registry hint says what this row is ABOUT) -- no SPINE_ENTITY_ID emitted.

with source as (

    select * from {{ source('ripple_raw', 'FED_GRANTS_GOV') }}

),

renamed as (

    select
        "OPPORTUNITY_ID" as opportunity_id,
        "OPPORTUNITY_NUMBER" as opportunity_number,
        "OPPORTUNITY_TITLE" as opportunity_title,
        "AGENCY_CODE" as agency_code,
        "AGENCY_NAME" as agency_name,
        "OPPORTUNITY_STATUS" as opportunity_status,
        "OPPORTUNITY_CATEGORY" as opportunity_category,
        "FUNDING_INSTRUMENT_TYPE" as funding_instrument_type,
        "CATEGORY_OF_FUNDING_ACTIVITY" as category_of_funding_activity,
        "CFDA_NUMBERS" as cfda_numbers,
        "ELIGIBLE_APPLICANTS" as eligible_applicants,
        "AWARD_CEILING" as award_ceiling,
        "AWARD_FLOOR" as award_floor,
        "ESTIMATED_TOTAL_PROGRAM_FUNDING" as estimated_total_program_funding,
        "EXPECTED_NUMBER_OF_AWARDS" as expected_number_of_awards,
        "POSTED_DATE" as posted_date,
        "CLOSE_DATE" as close_date,
        "LAST_UPDATED_DATE" as last_updated_date,
        "ARCHIVE_DATE" as archive_date,
        "SYNOPSIS_DESC" as synopsis_desc,
        "GRANTOR_CONTACT_EMAIL" as grantor_contact_email,
        "GRANTOR_CONTACT_NAME" as grantor_contact_name,
        "VERSION" as version,
        _INGESTED_AT as _loaded_at,
        'https://www.grants.gov/api/api-guide' as _source_url

    from source

)

select * from renamed
qualify row_number() over (partition by opportunity_id order by _loaded_at desc) = 1
