/* Plain-English table names, shared by the explorer tabs and the pivot. */
(function () {
  const HUMAN = {
    FED_CMS_NPPES: 'Every doctor and clinic in America',
    FED_CMS_MEDICARE_FEE_FOR_SERVICE_PUBLIC_PROVIDER_ENROLLMENT: 'Who bills Medicare',
    FED_CMS_FACILITY_AFFILIATION: 'Which doctors work where',
    FED_CMS_PECOS_PROVIDER_ENROLLMENT: 'Medicare provider enrollment records',
    FED_CMS_PARTD_PRESCRIBER_DRUG: 'What each doctor prescribed, drug by drug',
    FED_CMS_PART_D_PRESCRIBERS: 'Each doctor’s prescribing totals',
    FED_CMS_OPEN_PAYMENTS: 'Drug-industry payments to doctors',
    FED_CMS_OPEN_PAYMENTS_2022: 'Drug-industry payments to doctors, 2022',
    FED_CMS_OPEN_PAYMENTS_2023: 'Drug-industry payments to doctors, 2023',
    FED_CMS_OPEN_PAYMENTS_PROFILE_SUPPLEMENT: 'Profiles behind the industry payments',
    FED_CMS_FISCAL_INTERMEDIARY_SHARED_SYSTEM_ATTENDING_AND_RENDERING: 'Who attended vs who billed each claim',
    FED_CMS_ORDER_AND_REFERRING: 'Who may order tests and refer patients',
    FED_CMS_QUALITY_PAYMENT_PROGRAM_EXPERIENCE: 'Doctor quality-program scores',
    FED_CMS_MEDICARE_DURABLE_MEDICAL_EQUIPMENT_DEVICES_SUPPLIES_BY_REFER: 'Medical equipment orders, by referring doctor',
    FED_CMS_MEDICARE_DURABLE_MEDICAL_EQUIPMENT_DEVICES_SUPPLIES_BY_SUPPL: 'Medical equipment claims, by supplier',
    FED_CMS_MEDICARE_PHYSICIAN_OTHER_PRACTITIONERS_BY_PROVIDER_AND_SERVI: 'What each doctor billed Medicare, by service',
    FED_CMS_MEDICARE_PHYSICIAN_OTHER_PRACTITIONERS_BY_PROVIDER: 'What each doctor billed Medicare, totals',
    FED_CMS_MEDICARE_PROVIDER: 'Medicare provider directory',
    FED_CMS_HOSPITAL_ENROLLMENTS: 'Hospitals enrolled in Medicare',
    FED_CMS_AMBULATORY_SPECIALTY_MODEL_PARTICIPANTS: 'Doctors in the specialty-payment pilot',
    FED_CMS_OPT_OUT_AFFIDAVITS: 'Doctors who opted out of Medicare',
    FED_CMS_MEDICARE_DIALYSIS_FACILITIES: 'Dialysis clinics and their quality',
    FED_CMS_SKILLED_NURSING_FACILITY_ENROLLMENTS: 'Nursing facilities enrolled in Medicare',
    FED_CMS_HOME_HEALTH_AGENCY_ENROLLMENTS: 'Home-health agencies enrolled in Medicare',
    FED_CMS_RURAL_HEALTH_CLINIC_ENROLLMENTS: 'Rural clinics enrolled in Medicare',
    FED_CMS_HOSPICE_ENROLLMENTS: 'Hospices enrolled in Medicare',
    FED_CMS_POS_OTHER: 'Every place Medicare pays for care',
    FED_CMS_NURSING_HOME: 'Nursing homes and their ratings',
    FED_CMS_NURSING_HOME_DEFICIENCIES: 'Nursing-home inspection failures',
    FED_CMS_NURSING_HOME_FIRE_DEFICIENCIES: 'Nursing-home fire-safety failures',
    FED_CMS_NURSING_HOME_PENALTIES: 'Nursing-home fines',
    FED_CMS_FACILITY_LEVEL_MINIMUM_DATA_SET_FREQUENCY: 'Nursing-home resident condition counts',
    FED_CMS_HCRIS: 'Hospital cost reports — the money inside',
    FED_CMS_HOSPITAL_GENERAL: 'Hospital report cards',
    FED_CMS_MEDICARE_INPATIENT_HOSPITALS_BY_PROVIDER_AND_SERVICE: 'Inpatient hospital billing, by service',
    FED_CMS_MEDICARE_INPATIENT_HOSPITALS_BY_PROVIDER: 'Inpatient hospital billing, totals',
    FED_CMS_MEDICARE_OUTPATIENT_HOSPITALS_BY_PROVIDER_AND_SERVICE: 'Outpatient hospital billing, by service',
    FED_CMS_PENDING_INITIAL_LOGGING_AND_TRACKING_PHYSICIANS: 'Doctors waiting on Medicare approval',
    FED_CMS_PENDING_INITIAL_LOGGING_AND_TRACKING_NON_PHYSICIANS: 'Other providers waiting on approval',
    FED_CMS_HOME_HEALTH: 'Home-health agencies and their quality',
    FED_CMS_HOSPICE: 'Hospices and their quality',
    FED_CMS_DIALYSIS: 'Dialysis clinic report cards',
    FED_CMS_IRF: 'Rehab hospitals',
    FED_CMS_LTCH: 'Long-term care hospitals',
    FED_CMS_NADAC: 'What drugs actually cost pharmacies',
    FED_FDA_NDC_DIRECTORY: 'The FDA’s drug directory',
    FED_FDA_GUDID_FULL_DEVICE: 'Every registered medical device',
    FED_HRSA_UDS_SERVICE_DELIVERY_SITES: 'Community health-center sites',
    FED_HHS_OIG_LEIE: 'Providers banned from Medicare',
    FED_NURSINGHOME411: 'Nursing-home ownership, dug up by advocates',
    FED_SEC_EDGAR_FINANCIALS: 'Company financials from SEC filings',
    FED_SEC_EDGAR_COMPANY_TICKERS: 'Company name ↔ ticker ↔ SEC id',
    FED_SEC_EDGAR_INSIDERS: 'Corporate insiders and their trades',
    FED_SEC_INSIDER_REPORTINGOWNER: 'Insider-trading filers',
    FED_SEC_13F_SUBMISSIONS: 'Big investors’ quarterly holdings',
    FED_IRS_BMF: 'IRS business master file',
    FED_IRS_EO_BMF: 'Every nonprofit the IRS knows',
    FED_IRS_990_EFILE_INDEX: 'Nonprofit tax filings, indexed',
    FED_IRS_AUTO_REVOCATIONS: 'Nonprofits that lost tax status automatically',
    FED_IRS_REVOCATION: 'Nonprofits stripped of tax status',
    FED_IRS_PUB78_ELIGIBLE_DONEES: 'Charities you can deduct donations to',
    IRS527_DIRECTORS_OFFICERS: 'Who runs political money groups',
    IRS527_8871_ORGS: 'Political money groups — 527 registrations',
    FED_DOL_FORM5500: 'Company benefit-plan filings',
    FED_DOL_EBSA_FORM5500_SCHEDULE_SB: 'Pension-plan funding details',
    FED_PBGC_TRUSTEED_PENSION_PLANS: 'Failed pension plans the government took over',
    FED_PBGC_TRUSTEED_PLANS: 'Taken-over pension plans, plan level',
    FED_USASPENDING_ASSISTANCE_FULL: 'Every federal grant and loan',
    FED_USASPENDING_CONTRACTS_FULL: 'Every federal contract',
    FED_SAM_EXCLUSIONS_FULL_R2: 'People and firms banned from federal business',
    FED_SAM_ENTITY_PUBLIC: 'Federal business registry — SAM entities',
    FED_FAC_SINGLE_AUDIT: 'Audits of everyone spending federal money',
    FED_PCAOB_FORM_AP_FILINGS: 'Which audit firm signed which company',
    FED_NIH_REPORTER: 'Who got NIH research money',
    XC_EPA_CORPORATE_CROSSWALK: 'Bridge: which company owns which EPA site',
    FED_EPA_ECHO: 'EPA inspections, violations, enforcement',
    FED_EPA_TRI_FACILITY: 'Factories reporting toxic releases',
    FED_EPA_FRS_FRS_FACILITIES: 'EPA’s master facility registry',
    FED_EPA_FRS_FULL: 'EPA facility registry, full dump',
    FED_EPA_FRS_FRS_PROGRAM_LINKS: 'Which EPA programs touch which site',
    FED_EPA_NPDES_NPDES_INSPECTIONS: 'Water-permit inspections',
    FED_EPA_NPDES_NPDES_INFORMAL_ENFORCEMENT_ACTIONS: 'Water-permit warnings',
    FED_EPA_AIR_EMISSIONS_POLL_RPT_COMBINED_EMISSIONS: 'Air pollution, facility by facility',
    FED_FEC_COMMITTEES: 'Campaign committees',
    FED_FEC_CANDIDATES: 'Candidates for federal office',
    FED_FEC_COMMITTEE_TO_CANDIDATE: 'Committee money to candidates',
    FED_FEC_CAND_CMTE_LINKAGE: 'Which committee backs which candidate',
    FED_FEC_BULK_COMMITTEES: 'Campaign committees, bulk file',
    FED_FEC_BULK_CANDIDATES: 'Candidates, bulk file',
    FED_FEC_BULK_LINKAGES: 'Committee↔candidate links, bulk file',
    FED_FEC_BULK_SUMMARY: 'Candidate money totals',
    FED_FEC_LEADERSHIP_PAC: 'Politicians’ own PACs',
    FED_FEC_INDIV_CONTRIBUTIONS: 'Individual campaign donations',
    FED_GOVINFO_BILLSTATUS: 'Every bill in Congress',
    FED_GOVINFO_BILL_COSPONSORS: 'Who co-signed each bill',
    FED_VOTEVIEW_MEMBERS: 'Every member of Congress, ever',
    FED_VOTEVIEW_ROLLCALLS: 'Every roll-call vote',
    FED_CONGRESS_LEGISLATORS: 'Members of Congress, directory',
    FED_CONGRESS_COMMITTEE_MEMBERSHIP: 'Who sits on which committee',
    FED_ICE_DETENTION_STINTS: 'Immigration detention stints',
    FED_ICE_DETENTION_FACILITY_CODES: 'Detention facility codes',
    FED_COURTLISTENER_SCHOOLS: 'Where federal judges went to school',
    INTL_GLEIF: 'Global company registry — who owns whom',
    INTL_ISO_MIC_REGISTRY: 'The world’s stock exchanges',
    FED_CFPB_HMDA_ARID2017_LEI_XREF: 'Bridge: old mortgage-lender ids to LEI',
    FED_CFPB_HMDA: 'Mortgage applications and outcomes',
    FED_CFPB_HMDA_HISTORIC: 'Mortgage lending, pre-2018',
    FED_CFPB_HMDA_LAR: 'Mortgage applications, loan by loan',
    FED_CMS_FEDERALLY_QUALIFIED_HEALTH_CENTER_ENROLLMENTS: 'Community health centers enrolled in Medicare',
    FED_CMS_MEDICARE_DIABETES_PREVENTION_PROGRAM: 'Diabetes-prevention program providers',
    FED_CMS_OPIOID_TREATMENT_PROGRAM_PROVIDERS: 'Opioid-treatment providers',
    FED_CONSOLIDATED_SCREENING_LIST: 'Everyone on a federal watch or sanctions list',
    FED_COURTLISTENER_COURTHOUSES: 'Every federal courthouse',
    FED_COURTLISTENER_COURTS: 'Every federal court',
    FED_COURTLISTENER_DOCKETS: 'Federal court dockets',
    FED_COURTLISTENER_FINANCIAL_DISCLOSURES: 'Judges’ financial disclosures',
    FED_COURTLISTENER_JUDGES: 'Every federal judge',
    FED_COURTLISTENER_JUDGE_EDUCATIONS: 'Where judges studied',
    FED_COURTLISTENER_JUDGE_POLITICAL_AFFILIATIONS: 'Judges’ party affiliations',
    FED_COURTLISTENER_JUDGE_RACES: 'Judges’ demographics',
    FED_COURTLISTENER_ORIGINATING_COURT_INFO: 'Where each appeal came from',
    FED_COURTLISTENER_POSITIONS: 'Every seat a judge has held',
    FED_DOL_FORM5500_FULL: 'Benefit-plan filings, full dump',
    FED_EIA860_1_UTILITY: 'Power utilities',
    FED_EIA860_2_PLANT: 'Power plants',
    FED_EIA860_3_1_GENERATOR: 'Every generator at every plant',
    FED_EIA860_4_OWNER: 'Who owns each power plant',
    FED_EIA861_UTILITY_DATA: 'Utility sales and customers',
    FED_EPA_CAMPD_FACILITY: 'Power-plant emissions monitors',
    FED_EPA_EGRID_PLANT_2022: 'Power-plant emissions profiles, 2022',
    FED_EPA_FRS_FRS_NAICS_CODES: 'What industry each EPA site is in',
    FED_EPA_FRS_FRS_SIC_CODES: 'EPA sites by old industry code',
    FED_EPA_GHGRP_FACILITY: 'Big greenhouse-gas emitters',
    FED_EPA_ICIS_AIR_ICIS_AIR_FACILITIES: 'Air-permit facilities',
    FED_EPA_ICIS_FEC_CASE_ENFORCEMENT_CONCLUSION_FACILITIES: 'Facilities in concluded EPA cases',
    FED_EPA_ICIS_FEC_CASE_FACILITIES: 'Facilities in federal EPA cases',
    FED_EPA_ICIS_FEC_EPA_INFORMAL_ENFORCEMENT_ACTIONS: 'EPA warnings, federal cases',
    FED_EPA_ICIS_FEC_ICIS_FEC_EPA_INSPECTIONS: 'EPA inspections, federal cases',
    FED_EPA_NPDES_ICIS_FACILITIES: 'Water-permit facilities',
    FED_EPA_NPDES_NPDES_CS_VIOLATIONS: 'Sewer-overflow violations',
    FED_EPA_NPDES_NPDES_FORMAL_ENFORCEMENT_ACTIONS: 'Water-permit enforcement actions',
    FED_EPA_NPDES_NPDES_NAICS: 'Water permits by industry',
    FED_EPA_NPDES_NPDES_PS_VIOLATIONS: 'Pretreatment violations',
    FED_EPA_NPDES_NPDES_QNCR_HISTORY: 'Quarterly water-violation history',
    FED_EPA_NPDES_NPDES_SE_VIOLATIONS: 'Single-event water violations',
    FED_EPA_NPDES_NPDES_SICS: 'Water permits by old industry code',
    FED_EPA_SDWA_SDWA_EVENTS_MILESTONES: 'Drinking-water case milestones',
    FED_EPA_SDWA_SDWA_FACILITIES: 'Drinking-water system facilities',
    FED_EPA_SDWA_SDWA_GEOGRAPHIC_AREAS: 'Where each water system serves',
    FED_EPA_SDWA_SDWA_LCR_SAMPLES: 'Lead and copper tap samples',
    FED_EPA_SDWA_SDWA_PN_VIOLATION_ASSOC: 'Public-notice violations, linked',
    FED_EPA_SDWA_SDWA_PUB_WATER_SYSTEMS: 'Every public water system',
    FED_EPA_SDWA_SDWA_SERVICE_AREAS: 'Water-system service areas',
    FED_EPA_SDWA_SDWA_SITE_VISITS: 'Water-system inspections',
    FED_EPA_SDWA_SDWA_VIOLATIONS_ENFORCEMENT: 'Drinking-water violations and enforcement',
    FED_EPA_TRI_BASIC_2023: 'Toxic releases, 2023',
    FED_FAA_AIRCRAFT_REGISTRY: 'Every registered aircraft',
    FED_FDA_GUDID_FULL_IDENTIFIERS: 'Medical-device identifiers',
    FED_FDIC_BANK_DATA: 'Every FDIC-insured bank',
    FED_FDIC_SOD_BRANCH_DEPOSITS: 'Every bank branch and its deposits',
    FED_FEC_PAC_SUMMARY: 'PAC money totals',
    FED_FHFA_FHLB_MEMBERSHIP: 'Home-loan-bank members',
    FED_FMCSA_COMPANY_CENSUS: 'Every trucking company',
    FED_FRA_CASUALTIES: 'Railroad deaths and injuries',
    FED_FRA_EQUIPMENT_ACCIDENTS: 'Train accidents',
    FED_HRSA_UDS_HEALTH_CENTER_INFO: 'Community health-center profiles',
    FED_HUD_FHA_SF_PORTFOLIO_SNAPSHOT: 'FHA-insured mortgages snapshot',
    FED_ICE_DETAINERS: 'Immigration detainer requests',
    FED_IRS_990: 'Nonprofit tax returns',
    FED_IRS_SOI_CHARITIES: 'Charity finances, IRS extracts',
    FED_MSHA_ACCIDENTS: 'Mine accidents',
    FED_MSHA_MINES: 'Every mine',
    FED_MSHA_VIOLATIONS: 'Mine safety violations',
    FED_NCUA_CALL_REPORTS_FOICU: 'Credit-union quarterly reports',
    FED_NCUA_CALL_REPORTS_FS220: 'Credit-union balance sheets',
    FED_NCUA_CHARTER_MERGER_EVENTS: 'Credit-union mergers',
    FED_NCUA_FEDERALLY_INSURED_CU_LIST: 'Every insured credit union',
    FED_NOAA_AIS: 'Ship positions from radio pings',
    FED_NTSB_AVIATION_AIRCRAFT: 'Aircraft in crash investigations',
    FED_OFAC_SDN: 'US sanctions list',
    FED_OYEZ: 'Supreme Court cases, argued and decided',
    FED_SAM_EXCLUSIONS: 'Banned from federal business, older copy',
    FED_SBA_LOANS: 'Small-business loans',
    FED_SBIR_STTR_AWARDS: 'Small-business research awards',
    FED_SCDB: 'Supreme Court decisions database',
    FED_SEC_BUSINESS_DEVELOPMENT_COMPANY_REPORT: 'Business-development company filings',
    FED_SEC_CLOSED_END_FUND_INFORMATION: 'Closed-end funds',
    FED_SEC_INSIDER_SUBMISSION: 'Insider-trade filings, submissions',
    FED_SEC_INVESTMENT_COMPANY_SERIES_CLASS: 'Fund series and share classes',
    FED_SEC_MONEY_MARKET_FUND_INFORMATION: 'Money-market funds',
    FED_USASPENDING_CONTRACTS: 'Federal contracts, recent years',
    FED_USASPENDING_CONTRACTS_FULL_R2: 'Every federal contract, older copy',
    FED_USASPENDING_SUBAWARDS_FULL: 'Who the contractors subcontracted to',
    FED_USCG_NRC_INCIDENTS: 'Spill and pollution reports',
    FED_USCG_NRC_INCIDENT_REPORTS: 'Spill reports, details',
    FED_USCG_VESSEL_DOCUMENTATION: 'Every documented US vessel',
    INTL_GLEIF_RELATIONSHIPS: 'Who owns whom, globally',
    INTL_GLEIF_REPEX: 'Companies that won’t say who owns them',
    INTL_UK_SANCTIONS_LIST: 'UK sanctions list',
    INT_UK_COMPANIES_HOUSE: 'Every UK company',
    IRS527_8872_REPORTS: 'Political-group money reports',
    IRS527_RELATED_ENTITIES: 'Political groups’ related entities',
    UK_COMPANIES_HOUSE_PSC: 'Who really controls each UK company',
  };
  const OSHA_YEARS = ['2023', '2024', '2025'];
  OSHA_YEARS.forEach(y => {
    HUMAN['FED_OSHA_ITA_300A_SUMMARY_' + y] = 'Workplace injury counts, ' + y;
    HUMAN['FED_OSHA_ITA_CASE_DETAIL_' + y] = 'Workplace injury cases, ' + y;
  });
  ['2024Q1','2024Q2','2024Q3','2024Q4','2025Q1','2025Q2','2025Q3','2025Q4','2026Q1'].forEach(q => {
    HUMAN['FED_SEC_DERA_SUB_' + q] = 'SEC filings index, ' + q.slice(0,4) + ' Q' + q.slice(5);
  });
  window.HANDBOOK_HUMAN = HUMAN;
})();
