-- deep3/g04: deep pass 3, 2026-09-24. Python door (connect/db.py), QUERY_TAG 'deep3-2026-09-24'.
-- Every connection first ran: ALTER SESSION SET STATEMENT_TIMEOUT_IN_SECONDS = 300, then ALTER SESSION SET QUERY_TAG = 'deep3-2026-09-24'. Not counted.
-- Read-only: every statement below is a single SELECT or WITH. Runner: reports/coverage_2026-09-24/deep3/g04/run.py (refuses anything else).
-- 30 statements sent, S01-S30. S23 failed to compile (unsupported subquery) and was rewritten as S26. Results: g04/out_Sxx.json.
-- Tables: FISCAL_INTERMEDIARY_SHARED_SYSTEM_ATTENDING_AND_RENDERING (FISS), ORDER_AND_REFERRING (O&R),
--         SKILLED_NURSING_FACILITY_ENROLLMENTS (SNF), CDC_LEADING_CAUSES_STATE (CDC), FEDERALLY_QUALIFIED_HEALTH_CENTER_ENROLLMENTS (FQHC).
-- Join partners read: FED_HHS_OIG_LEIE, FED_CMS_NPPES, FED_CMS_PECOS_PROVIDER_ENROLLMENT, FED_CMS_OPT_OUT_AFFIDAVITS,
--         FED_CMS_MEDICARE_PHYSICIAN_OTHER_PRACTITIONERS_BY_PROVIDER (DY2024), FED_CMS_MEDICARE_DURABLE_MEDICAL_EQUIPMENT_DEVICES_SUPPLIES_BY_REFER (DY2024),
--         FED_CMS_NURSING_HOME, FED_CMS_NURSING_HOME_DEFICIENCIES, FED_HRSA_UDS_SERVICE_DELIVERY_SITES, LIBRARY_RAW.INFORMATION_SCHEMA.TABLES.

