{{ config(materialized='view') }}

/*
  Generated 2026-08-09 (73-source backlog, wave 2d).
  SAMPLE ONLY -- NOT the full dataset. HMDA mortgage loan-level records: a single state-year slice (Washington DC, 2023; 28,301 rows) of a corpus that is ~50 states x 2018-present. Use for shape/testing, never for lending-pattern claims. Full pull needs a state x year loop loader.
  Grain: one row = one reported loan/application (no unique key in the export).
*/

with source as (
    select * from {{ source('ripple_raw', 'FED_CFPB_HMDA') }}
),

renamed as (
    select
        nullif(trim(ACTIVITY_YEAR), '')                            as activity_year,
        nullif(trim(LEI), '')                                      as lei,
        nullif(trim(DERIVED_MSA_MD), '')                           as derived_msa_md,
        nullif(trim(STATE_CODE), '')                               as state_code,
        nullif(trim(COUNTY_CODE), '')                              as county_code,
        nullif(trim(CENSUS_TRACT), '')                             as census_tract,
        nullif(trim(CONFORMING_LOAN_LIMIT), '')                    as conforming_loan_limit,
        nullif(trim(DERIVED_LOAN_PRODUCT_TYPE), '')                as derived_loan_product_type,
        nullif(trim(DERIVED_DWELLING_CATEGORY), '')                as derived_dwelling_category,
        nullif(trim(DERIVED_ETHNICITY), '')                        as derived_ethnicity,
        nullif(trim(DERIVED_RACE), '')                             as derived_race,
        nullif(trim(DERIVED_SEX), '')                              as derived_sex,
        nullif(trim(ACTION_TAKEN), '')                             as action_taken,
        nullif(trim(PURCHASER_TYPE), '')                           as purchaser_type,
        nullif(trim(PREAPPROVAL), '')                              as preapproval,
        nullif(trim(LOAN_TYPE), '')                                as loan_type,
        nullif(trim(LOAN_PURPOSE), '')                             as loan_purpose,
        nullif(trim(LIEN_STATUS), '')                              as lien_status,
        nullif(trim(REVERSE_MORTGAGE), '')                         as reverse_mortgage,
        nullif(trim(OPEN_END_LINE_OF_CREDIT), '')                  as open_end_line_of_credit,
        nullif(trim(BUSINESS_OR_COMMERCIAL_PURPOSE), '')           as business_or_commercial_purpose,
        try_to_number(nullif(trim(LOAN_AMOUNT), ''), 18, 4)        as loan_amount,
        nullif(trim(LOAN_TO_VALUE_RATIO), '')                      as loan_to_value_ratio,
        nullif(trim(INTEREST_RATE), '')                            as interest_rate,
        nullif(trim(RATE_SPREAD), '')                              as rate_spread,
        nullif(trim(HOEPA_STATUS), '')                             as hoepa_status,
        nullif(trim(TOTAL_LOAN_COSTS), '')                         as total_loan_costs,
        nullif(trim(TOTAL_POINTS_AND_FEES), '')                    as total_points_and_fees,
        nullif(trim(ORIGINATION_CHARGES), '')                      as origination_charges,
        nullif(trim(DISCOUNT_POINTS), '')                          as discount_points,
        nullif(trim(LENDER_CREDITS), '')                           as lender_credits,
        nullif(trim(LOAN_TERM), '')                                as loan_term,
        nullif(trim(PREPAYMENT_PENALTY_TERM), '')                  as prepayment_penalty_term,
        nullif(trim(INTRO_RATE_PERIOD), '')                        as intro_rate_period,
        nullif(trim(NEGATIVE_AMORTIZATION), '')                    as negative_amortization,
        nullif(trim(INTEREST_ONLY_PAYMENT), '')                    as interest_only_payment,
        nullif(trim(BALLOON_PAYMENT), '')                          as balloon_payment,
        nullif(trim(OTHER_NONAMORTIZING_FEATURES), '')             as other_nonamortizing_features,
        nullif(trim(PROPERTY_VALUE), '')                           as property_value,
        nullif(trim(CONSTRUCTION_METHOD), '')                      as construction_method,
        nullif(trim(OCCUPANCY_TYPE), '')                           as occupancy_type,
        nullif(trim(MANUFACTURED_HOME_SECURED_PROPERTY_TYPE), '')  as manufactured_home_secured_property_type,
        nullif(trim(MANUFACTURED_HOME_LAND_PROPERTY_INTEREST), '') as manufactured_home_land_property_interest,
        nullif(trim(TOTAL_UNITS), '')                              as total_units,
        nullif(trim(MULTIFAMILY_AFFORDABLE_UNITS), '')             as multifamily_affordable_units,
        try_to_number(nullif(trim(INCOME), ''), 18, 4)             as income,
        nullif(trim(DEBT_TO_INCOME_RATIO), '')                     as debt_to_income_ratio,
        nullif(trim(APPLICANT_CREDIT_SCORE_TYPE), '')              as applicant_credit_score_type,
        nullif(trim(CO_APPLICANT_CREDIT_SCORE_TYPE), '')           as co_applicant_credit_score_type,
        nullif(trim(APPLICANT_ETHNICITY_1), '')                    as applicant_ethnicity_1,
        nullif(trim(APPLICANT_ETHNICITY_2), '')                    as applicant_ethnicity_2,
        nullif(trim(APPLICANT_ETHNICITY_3), '')                    as applicant_ethnicity_3,
        nullif(trim(APPLICANT_ETHNICITY_4), '')                    as applicant_ethnicity_4,
        nullif(trim(APPLICANT_ETHNICITY_5), '')                    as applicant_ethnicity_5,
        nullif(trim(CO_APPLICANT_ETHNICITY_1), '')                 as co_applicant_ethnicity_1,
        nullif(trim(CO_APPLICANT_ETHNICITY_2), '')                 as co_applicant_ethnicity_2,
        nullif(trim(CO_APPLICANT_ETHNICITY_3), '')                 as co_applicant_ethnicity_3,
        nullif(trim(CO_APPLICANT_ETHNICITY_4), '')                 as co_applicant_ethnicity_4,
        nullif(trim(CO_APPLICANT_ETHNICITY_5), '')                 as co_applicant_ethnicity_5,
        nullif(trim(APPLICANT_ETHNICITY_OBSERVED), '')             as applicant_ethnicity_observed,
        nullif(trim(CO_APPLICANT_ETHNICITY_OBSERVED), '')          as co_applicant_ethnicity_observed,
        nullif(trim(APPLICANT_RACE_1), '')                         as applicant_race_1,
        nullif(trim(APPLICANT_RACE_2), '')                         as applicant_race_2,
        nullif(trim(APPLICANT_RACE_3), '')                         as applicant_race_3,
        nullif(trim(APPLICANT_RACE_4), '')                         as applicant_race_4,
        nullif(trim(APPLICANT_RACE_5), '')                         as applicant_race_5,
        nullif(trim(CO_APPLICANT_RACE_1), '')                      as co_applicant_race_1,
        nullif(trim(CO_APPLICANT_RACE_2), '')                      as co_applicant_race_2,
        nullif(trim(CO_APPLICANT_RACE_3), '')                      as co_applicant_race_3,
        nullif(trim(CO_APPLICANT_RACE_4), '')                      as co_applicant_race_4,
        nullif(trim(CO_APPLICANT_RACE_5), '')                      as co_applicant_race_5,
        nullif(trim(APPLICANT_RACE_OBSERVED), '')                  as applicant_race_observed,
        nullif(trim(CO_APPLICANT_RACE_OBSERVED), '')               as co_applicant_race_observed,
        nullif(trim(APPLICANT_SEX), '')                            as applicant_sex,
        nullif(trim(CO_APPLICANT_SEX), '')                         as co_applicant_sex,
        nullif(trim(APPLICANT_SEX_OBSERVED), '')                   as applicant_sex_observed,
        nullif(trim(CO_APPLICANT_SEX_OBSERVED), '')                as co_applicant_sex_observed,
        nullif(trim(APPLICANT_AGE), '')                            as applicant_age,
        nullif(trim(CO_APPLICANT_AGE), '')                         as co_applicant_age,
        nullif(trim(APPLICANT_AGE_ABOVE_62), '')                   as applicant_age_above_62,
        nullif(trim(CO_APPLICANT_AGE_ABOVE_62), '')                as co_applicant_age_above_62,
        nullif(trim(SUBMISSION_OF_APPLICATION), '')                as submission_of_application,
        nullif(trim(INITIALLY_PAYABLE_TO_INSTITUTION), '')         as initially_payable_to_institution,
        nullif(trim(AUS_1), '')                                    as aus_1,
        nullif(trim(AUS_2), '')                                    as aus_2,
        nullif(trim(AUS_3), '')                                    as aus_3,
        nullif(trim(AUS_4), '')                                    as aus_4,
        nullif(trim(AUS_5), '')                                    as aus_5,
        nullif(trim(DENIAL_REASON_1), '')                          as denial_reason_1,
        nullif(trim(DENIAL_REASON_2), '')                          as denial_reason_2,
        nullif(trim(DENIAL_REASON_3), '')                          as denial_reason_3,
        nullif(trim(DENIAL_REASON_4), '')                          as denial_reason_4,
        try_to_number(nullif(trim(TRACT_POPULATION), ''), 18, 4)   as tract_population,
        try_to_number(nullif(trim(TRACT_MINORITY_POPULATION_PERCENT), ''), 18, 4) as tract_minority_population_percent,
        try_to_number(nullif(trim(FFIEC_MSA_MD_MEDIAN_FAMILY_INCOME), ''), 18, 4) as ffiec_msa_md_median_family_income,
        try_to_number(nullif(trim(TRACT_TO_MSA_INCOME_PERCENTAGE), ''), 18, 4) as tract_to_msa_income_percentage,
        try_to_number(nullif(trim(TRACT_OWNER_OCCUPIED_UNITS), ''), 18, 4) as tract_owner_occupied_units,
        try_to_number(nullif(trim(TRACT_ONE_TO_FOUR_FAMILY_HOMES), ''), 18, 4) as tract_one_to_four_family_homes,
        try_to_number(nullif(trim(TRACT_MEDIAN_AGE_OF_HOUSING_UNITS), ''), 18, 4) as tract_median_age_of_housing_units,
        to_timestamp_ntz(_INGESTED_AT, 6)                          as _ingested_at,
        nullif(trim(_SOURCE_RUN_ID), '')                           as _source_run_id
    from source
)

select * from renamed
