{{ config(tags=['spine_generated']) }}

-- GRAIN: one row per record (spine_entity not determined -- no registry hint available) (INVENTORY_ID unique)
-- SPINE_ENTITY: (not determined)  (natural_key: INVENTORY_ID)
-- Generated by scripts/generate_staging_models.py from SOURCE_REGISTRY -- deterministic,
-- no LLM.
-- CASTS: 5 of 33 columns, from landing_column_profile_2026-09-19.tsv. A column is cast only
-- when every filled value in the sample parsed. try_ casts: a value that does not
-- parse reads NULL. The natural key and join-key columns stay TEXT.
--   objectid_1: ID: whole numbers, over 90% distinct -- stays TEXT, '.0' tail removed
--   objectid: ID: whole numbers, over 90% distinct -- stays TEXT, '.0' tail removed
--   latitiude: float
--   creationdate: integer
--   editdate: integer
-- spine_entity not determined (grain/natural_key proven, but no registry hint says what this row is ABOUT) -- no SPINE_ENTITY_ID emitted.
-- landing table's ingestion timestamp is named INGESTED_AT (no leading underscore) rather than the usual _INGESTED_AT -- confirmed via INFORMATION_SCHEMA, not assumed.

with source as (

    select * from {{ source('ripple_raw', 'PORTAL_ARC_ORANGE_COUNTY_OP_43A1FE3FBE') }}
    qualify row_number() over (partition by "INVENTORY_ID" order by INGESTED_AT desc) = 1

),

renamed as (

    select
        {{ stg_id_text('"OBJECTID_1"') }} as objectid_1,
        {{ stg_id_text('"OBJECTID"') }} as objectid,
        {{ null_junk('"FACILITY_T"') }} as facility_t,
        {{ null_junk('"REGION"') }} as region,
        {{ null_junk('"WDID"') }} as wdid,
        {{ null_junk('"BUSINESS_N"') }} as business_n,
        {{ null_junk('"STREET_NUM"') }} as street_num,
        {{ null_junk('"STREET_NAM"') }} as street_nam,
        {{ null_junk('"STREET_TYP"') }} as street_typ,
        {{ null_junk('"CITY"') }} as city,
        {{ null_junk('"ZIP"') }} as zip,
        {{ null_junk('"WATERSHED"') }} as watershed,
        {{ stg_float('"LATITIUDE"') }} as latitiude,
        {{ null_junk('"LONGITUDE"') }} as longitude,
        {{ null_junk('"PRIORITY"') }} as priority,
        {{ null_junk('"INSPECTION"') }} as inspection,
        {{ null_junk('"CONTACT"') }} as contact,
        {{ null_junk('"PHONE_NUMB"') }} as phone_numb,
        {{ null_junk('"WQMP"') }} as wqmp,
        {{ null_junk('"WQMP_NUMBE"') }} as wqmp_numbe,
        {{ null_junk('"INVENTORY_ID"') }} as inventory_id,
        {{ null_junk('"GLOBALID"') }} as globalid,
        {{ null_junk('"CONTACT_EMAIL"') }} as contact_email,
        {{ null_junk('"SIC_DESCRIPTION"') }} as sic_description,
        {{ null_junk('"BUSINESS_LIC_NUMBER"') }} as business_lic_number,
        {{ null_junk('"SIC_CODE"') }} as sic_code,
        {{ null_junk('"FOOD_OWNER"') }} as food_owner,
        {{ null_junk('"BUSINESS_NAME_ORIGINAL"') }} as business_name_original,
        {{ stg_int('"CREATIONDATE"') }} as creationdate,
        {{ null_junk('"CREATOR"') }} as creator,
        {{ stg_int('"EDITDATE"') }} as editdate,
        {{ null_junk('"EDITOR"') }} as editor,
        {{ null_junk('"GEOMETRY"') }} as geometry,
        INGESTED_AT as _loaded_at,
        'https://data-ocpw.opendata.arcgis.com/datasets/4b168e3f9a1144a4979f8c6dd5280691_0' as _source_url

    from source

)

select * from renamed
