{{ config(tags=['spine_generated']) }}

-- GRAIN: one row per place (FIPS+REPORT_DATE unique)
-- SPINE_ENTITY: place  (natural_key: FIPS, REPORT_DATE)
-- Generated by scripts/generate_staging_models.py from SOURCE_REGISTRY -- deterministic,
-- no LLM.
-- CASTS: 3 of 7 columns, from landing_column_profile_2026-09-19.tsv. A column is cast only
-- when every filled value in the sample parsed. try_ casts: a value that does not
-- parse reads NULL. The natural key and join-key columns stay TEXT.
--   total_cases: integer
--   hospitalizations: integer
--   deaths: integer
-- spine_entity 'place' has no connect/ resolver yet (see connect/spine_entity.py) -- no SPINE_ENTITY_ID emitted.
-- landing table's ingestion timestamp is named INGESTED_AT (no leading underscore) rather than the usual _INGESTED_AT -- confirmed via INFORMATION_SCHEMA, not assumed.

with source as (

    select * from {{ source('ripple_raw', 'PORTAL_CKA_VIRGINIA_OPEN_DA_3E67A117FB') }}
    qualify row_number() over (partition by "FIPS", "REPORT_DATE" order by INGESTED_AT desc) = 1

),

renamed as (

    select
        {{ null_junk('"REPORT_DATE"') }} as report_date,
        {{ null_junk('"FIPS"') }} as fips,
        {{ null_junk('"LOCALITY"') }} as locality,
        {{ null_junk('"VDH_HEALTH_DISTRICT"') }} as vdh_health_district,
        {{ stg_int('"TOTAL_CASES"') }} as total_cases,
        {{ stg_int('"HOSPITALIZATIONS"') }} as hospitalizations,
        {{ stg_int('"DEATHS"') }} as deaths,
        INGESTED_AT as _loaded_at,
        'https://data.virginia.gov/dataset/vdh-covid-19-publicusedataset-cases' as _source_url

    from source

)

select * from renamed
