{{ config(tags=['spine_generated']) }}

-- GRAIN: one row per record (spine_entity not determined -- no registry hint available) (ID unique)
-- SPINE_ENTITY: (not determined)  (natural_key: ID)
-- Generated by scripts/generate_staging_models.py from SOURCE_REGISTRY -- deterministic,
-- no LLM.
-- CASTS: 14 of 21 columns, from landing_column_profile_2026-09-19.tsv. A column is cast only
-- when every filled value in the sample parsed. try_ casts: a value that does not
-- parse reads NULL. The natural key and join-key columns stay TEXT.
--   taxyr: integer
--   totalassetsboyamt: ID: whole numbers, over 90% distinct -- stays TEXT, '.0' tail removed
--   totalassetseoyamt: ID: whole numbers, over 90% distinct -- stays TEXT, '.0' tail removed
--   totalliabilitieseoyamt: integer
--   netassetsorfundbalancesboyamt: ID: whole numbers, over 90% distinct -- stays TEXT, '.0' tail removed
--   netassetsorfundbalanceseoyamt: ID: whole numbers, over 90% distinct -- stays TEXT, '.0' tail removed
--   allothercontributionsamt: ID: whole numbers, over 90% distinct -- stays TEXT, '.0' tail removed
--   totalliabilitiesboyamt: integer
--   federatedcampaignsamt: integer
--   membershipduesamt: integer
--   governmentgrantsamt: integer
--   noncashcontributionsamt: integer
--   fundraisingamt: integer
--   relatedorganizationsamt: integer
-- spine_entity not determined (grain/natural_key proven, but no registry hint says what this row is ABOUT) -- no SPINE_ENTITY_ID emitted.
-- landing table's ingestion timestamp is named INGESTED_AT (no leading underscore) rather than the usual _INGESTED_AT -- confirmed via INFORMATION_SCHEMA, not assumed.

with source as (

    select * from {{ source('ripple_raw', 'PORTAL_SOC_COLORADO_INFORMA_F9498D9B7F') }}
    qualify row_number() over (partition by "ID" order by INGESTED_AT desc) = 1

),

renamed as (

    select
        {{ null_junk('"ID"') }} as id,
        {{ stg_int('"TAXYR"') }} as taxyr,
        {{ null_junk('"BUSINESSNAME1"') }} as businessname1,
        {{ null_junk('"EIN"') }} as ein,
        {{ stg_id_text('"TOTALASSETSBOYAMT"') }} as totalassetsboyamt,
        {{ stg_id_text('"TOTALASSETSEOYAMT"') }} as totalassetseoyamt,
        {{ stg_int('"TOTALLIABILITIESEOYAMT"') }} as totalliabilitieseoyamt,
        {{ stg_id_text('"NETASSETSORFUNDBALANCESBOYAMT"') }} as netassetsorfundbalancesboyamt,
        {{ stg_id_text('"NETASSETSORFUNDBALANCESEOYAMT"') }} as netassetsorfundbalanceseoyamt,
        {{ null_junk('"ENGAGEDINEXCESSBENEFITTRANSIND"') }} as engagedinexcessbenefittransind,
        {{ null_junk('"DEDUCTIBLENONCASHCONTRIIND"') }} as deductiblenoncashcontriind,
        {{ null_junk('"MATERIALDIVERSIONORMISUSEIND"') }} as materialdiversionormisuseind,
        {{ stg_id_text('"ALLOTHERCONTRIBUTIONSAMT"') }} as allothercontributionsamt,
        {{ stg_int('"TOTALLIABILITIESBOYAMT"') }} as totalliabilitiesboyamt,
        {{ stg_int('"FEDERATEDCAMPAIGNSAMT"') }} as federatedcampaignsamt,
        {{ stg_int('"MEMBERSHIPDUESAMT"') }} as membershipduesamt,
        {{ stg_int('"GOVERNMENTGRANTSAMT"') }} as governmentgrantsamt,
        {{ stg_int('"NONCASHCONTRIBUTIONSAMT"') }} as noncashcontributionsamt,
        {{ null_junk('"BUSINESSNAME2"') }} as businessname2,
        {{ stg_int('"FUNDRAISINGAMT"') }} as fundraisingamt,
        {{ stg_int('"RELATEDORGANIZATIONSAMT"') }} as relatedorganizationsamt,
        INGESTED_AT as _loaded_at,
        'https://data.colorado.gov/d/ipm7-5rxr' as _source_url

    from source

)

select * from renamed
