{{ config(tags=['spine_generated']) }}

-- GRAIN: one row per place (GEOM is unique)
-- SPINE_ENTITY: place  (natural_key: SHAPE__LENGTH)
-- Generated by scripts/generate_staging_models.py from SOURCE_REGISTRY -- deterministic,
-- no LLM. Casts kept as landed (TEXT) -- add explicit type casts by hand once each
-- column's real type is confirmed; this generator has no semantic type knowledge.
-- spine_entity 'place' has no connect/ resolver yet (see connect/spine_entity.py) -- no SPINE_ENTITY_ID emitted.
-- landing table's ingestion timestamp is named INGESTED_AT (no leading underscore) rather than the usual _INGESTED_AT -- confirmed via INFORMATION_SCHEMA, not assumed.

with source as (

    select * from {{ source('ripple_raw', 'PORTAL_CKA_OPEN_DATA_SA_E078D81651') }}

),

renamed as (

    select
        "OBJECTID" as objectid,
        "MDPID" as mdpid,
        "MDPNAME" as mdpname,
        "AMENDMENTID" as amendmentid,
        "DATE_RECEIVED" as date_received,
        "DATE_ACCEPTED" as date_accepted,
        "VALIDITY" as validity,
        "PLATTEDAREA" as plattedarea,
        "GISRECORDED" as gisrecorded,
        "ENGINEER" as engineer,
        "DEVELOPER" as developer,
        "AQUIFER" as aquifer,
        "COUNCIL_DISTRICT" as council_district,
        "LANDUSE" as landuse,
        "RESIDENTIALLOTS" as residentiallots,
        "TOTALACRES" as totalacres,
        "RESIDENTIALACRES" as residentialacres,
        "MULTIFAMILY_ACREAGE" as multifamily_acreage,
        "COMMERCIAL_ACREAGE" as commercial_acreage,
        "INDUSTRIAL_ACREAGE" as industrial_acreage,
        "SCHOOL_ACREAGE" as school_acreage,
        "PARK_ACREAGE" as park_acreage,
        "AMENITY_ACREAGE" as amenity_acreage,
        "DOCLINK" as doclink,
        "PUDLINK" as pudlink,
        "TIALINK" as tialink,
        "YEAR" as year,
        "COMPLETED" as completed,
        "EXPIRATIONDATE" as expirationdate,
        "MDP_LINK" as mdp_link,
        "GLOBALID" as globalid,
        "SHAPE__AREA" as shape__area,
        "SHAPE__LENGTH" as shape__length,
        INGESTED_AT as _loaded_at,
        'https://data.sanantonio.gov/dataset/master-development-plans-mdp' as _source_url

    from source

)

select * from renamed
qualify row_number() over (partition by shape__length order by _loaded_at desc) = 1
