{{ config(tags=['minimal_staging']) }}

-- GRAIN: NOT YET DETERMINED (profiler returned AMBIGUOUS -- needs manual review)
-- This is a passthrough staging view: snake_case rename only, no dedup.
-- Once grain is resolved, replace with a full staging model via generate_staging_models.py.
-- Generated by scripts/generate_minimal_staging.py

with source as (

    select * from {{ source('ripple_raw', 'FED_CMS_PARTD_PRESCRIBER_DRUG') }}

),

renamed as (

    select
        "Prscrbr_NPI" as prscrbr_npi,
        "Prscrbr_Last_Org_Name" as prscrbr_last_org_name,
        "Prscrbr_First_Name" as prscrbr_first_name,
        "Prscrbr_City" as prscrbr_city,
        "Prscrbr_State_Abrvtn" as prscrbr_state_abrvtn,
        "Prscrbr_State_FIPS" as prscrbr_state_fips,
        "Prscrbr_Type" as prscrbr_type,
        "Prscrbr_Type_Src" as prscrbr_type_src,
        "Brnd_Name" as brnd_name,
        "Gnrc_Name" as gnrc_name,
        "Tot_Clms" as tot_clms,
        "Tot_30day_Fills" as tot_30day_fills,
        "Tot_Day_Suply" as tot_day_suply,
        "Tot_Drug_Cst" as tot_drug_cst,
        "Tot_Benes" as tot_benes,
        "GE65_Sprsn_Flag" as ge65_sprsn_flag,
        "GE65_Tot_Clms" as ge65_tot_clms,
        "GE65_Tot_30day_Fills" as ge65_tot_30day_fills,
        "GE65_Tot_Drug_Cst" as ge65_tot_drug_cst,
        "GE65_Tot_Day_Suply" as ge65_tot_day_suply,
        "GE65_Bene_Sprsn_Flag" as ge65_bene_sprsn_flag,
        "GE65_Tot_Benes" as ge65_tot_benes,
        _INGESTED_AT as _loaded_at,
        'https://data.cms.gov/sites/default/files/2024-05/18f82097-61a6-4889-9941-9a0b6ad7523c/MUP_DPR_RY24_P04_V10_DY22_NPIBN.csv' as _source_url

    from source

)

select * from renamed
