-- S01 EIA-861 tables in the mart: row counts and every column, to find the denominator tables
SELECT c.TABLE_NAME, t.ROW_COUNT, COUNT(*) n_cols,
       LISTAGG(c.COLUMN_NAME || ':' || c.DATA_TYPE, ', ') WITHIN GROUP (ORDER BY c.ORDINAL_POSITION) cols
FROM LIBRARY_MARTS.INFORMATION_SCHEMA.COLUMNS c
JOIN LIBRARY_MARTS.INFORMATION_SCHEMA.TABLES t
  ON t.TABLE_SCHEMA = c.TABLE_SCHEMA AND t.TABLE_NAME = c.TABLE_NAME
WHERE c.TABLE_SCHEMA = 'ENERGY' AND c.TABLE_NAME LIKE 'ENERGY\\_\\_FED\\_EIA%861%'
GROUP BY 1, 2 ORDER BY 1;

-- S02 distribution systems: whole table (1,353 rows)
SELECT * FROM LIBRARY_MARTS.ENERGY.ENERGY__FED_EIA861_DISTRIBUTION_SYSTEMS;

-- S03 utility data: whole table (1,701 rows)
SELECT * FROM LIBRARY_MARTS.ENERGY.ENERGY__FED_EIA861_UTILITY_DATA;

-- S04 dynamic pricing: whole table (857 rows)
SELECT * FROM LIBRARY_MARTS.ENERGY.ENERGY__FED_EIA861_DYNAMIC_PRICING;

-- S05 net metering: whole table (1,004 rows)
SELECT * FROM LIBRARY_MARTS.ENERGY.ENERGY__FED_EIA861_NET_METERING;

-- S06 non-net-metering distributed: whole table (507 rows)
SELECT * FROM LIBRARY_MARTS.ENERGY.ENERGY__FED_EIA861_NON_NET_METERING_DISTRIBUTED;
