-- S10 net metering: Arizona residential solar installations per 1,000 residential customers (join to sales on utility number + state; sales rows Bundled + Delivery only; adjustment rows 99999 dropped)
WITH nm AS (
  SELECT UTILITY_NUMBER, STATE, MAX(UTILITY_NAME) name, LISTAGG(DISTINCT TECHNOLOGY_TYPE, ',') ac_dc,
         SUM(RESIDENTIAL_INSTALLATIONS) res_inst, SUM(RESIDENTIAL_CAPACITY_MW) res_mw
  FROM LIBRARY_MARTS.ENERGY.ENERGY__FED_EIA861_NET_METERING
  WHERE UTILITY_NUMBER <> 99999 GROUP BY 1, 2),
s AS (
  SELECT UTILITY_NUMBER, STATE, SUM(RESIDENTIAL_CUSTOMERS) res_cust
  FROM LIBRARY_MARTS.ENERGY.ENERGY__FED_EIA861_SALES_ULT_CUST
  WHERE SERVICE_TYPE IN ('Bundled', 'Delivery') AND UTILITY_NUMBER <> 99999 GROUP BY 1, 2)
SELECT nm.STATE, nm.name, nm.ac_dc, nm.res_inst, ROUND(nm.res_mw, 1) res_mw, s.res_cust,
       ROUND(1000 * nm.res_inst / NULLIF(s.res_cust, 0), 1) inst_per_1k
FROM nm LEFT JOIN s ON s.UTILITY_NUMBER = nm.UTILITY_NUMBER AND s.STATE = nm.STATE
WHERE nm.STATE = 'AZ' AND s.res_cust >= 10000
ORDER BY inst_per_1k;

-- S11 dynamic pricing: residential enrolled vs residential customers and smart meters, default-TOU utilities, the Evergy Kansas twin, and the suspect reporters
WITH dp AS (
  SELECT UTILITY_NUMBER, STATE, MAX(UTILITY_NAME) name, SUM(RESIDENTIAL_CUSTOMERS_ENROLLED) enrolled,
         MAX(RESIDENTIAL_TIME_OF_USE_PRICING) tou, MAX(RESIDENTIAL_CRITICAL_PEAK_REBATE) cpr
  FROM LIBRARY_MARTS.ENERGY.ENERGY__FED_EIA861_DYNAMIC_PRICING GROUP BY 1, 2),
s AS (
  SELECT UTILITY_NUMBER, STATE, SUM(RESIDENTIAL_CUSTOMERS) res_cust
  FROM LIBRARY_MARTS.ENERGY.ENERGY__FED_EIA861_SALES_ULT_CUST
  WHERE SERVICE_TYPE IN ('Bundled', 'Delivery') GROUP BY 1, 2),
am AS (
  SELECT UTILITY_NUMBER, STATE, SUM(RESIDENTIAL_AMI_METERS) res_ami, SUM(RESIDENTIAL_TOTAL_METERS) res_meters
  FROM LIBRARY_MARTS.ENERGY.ENERGY__FED_EIA861_ADVANCED_METERS GROUP BY 1, 2)
SELECT dp.STATE, dp.name, dp.tou, dp.cpr, dp.enrolled, s.res_cust, ROUND(dp.enrolled / NULLIF(s.res_cust, 0), 3) share_enrolled,
       am.res_ami, am.res_meters
FROM dp LEFT JOIN s ON s.UTILITY_NUMBER = dp.UTILITY_NUMBER AND s.STATE = dp.STATE
LEFT JOIN am ON am.UTILITY_NUMBER = dp.UTILITY_NUMBER AND am.STATE = dp.STATE
WHERE dp.name ILIKE ANY ('Evergy%', 'Union Electric%', 'Public Service Co of Colorado', 'Consumers Energy%', 'Southern California Edison%',
                         'Pacific Gas%', 'San Diego Gas%', 'DTE Electric%', 'Public Service Co of Oklahoma', 'Southwestern Electric Power%')
ORDER BY dp.name, dp.STATE;

-- S12 non-net + net metering: residential solar MW per residential customer, Southern Co. and TVA-area utilities (AL, GA, MS, TN) with 100K+ homes
WITH nm AS (
  SELECT UTILITY_NUMBER, STATE, SUM(RESIDENTIAL_CAPACITY_MW) nm_res_mw, SUM(RESIDENTIAL_INSTALLATIONS) nm_res_inst
  FROM LIBRARY_MARTS.ENERGY.ENERGY__FED_EIA861_NET_METERING WHERE UTILITY_NUMBER <> 99999 GROUP BY 1, 2),
nn AS (
  SELECT UTILITY_NUMBER, STATE, SUM(RESIDENTIAL_CAPACITY_MW_TECH_01) nn_res_pv_mw, SUM(NUMBER_OF_GENERATORS) nn_generators
  FROM LIBRARY_MARTS.ENERGY.ENERGY__FED_EIA861_NON_NET_METERING_DISTRIBUTED WHERE UTILITY_NUMBER <> 99999 GROUP BY 1, 2),
s AS (
  SELECT UTILITY_NUMBER, STATE, MAX(UTILITY_NAME) name, SUM(RESIDENTIAL_CUSTOMERS) res_cust
  FROM LIBRARY_MARTS.ENERGY.ENERGY__FED_EIA861_SALES_ULT_CUST
  WHERE SERVICE_TYPE IN ('Bundled', 'Delivery') AND UTILITY_NUMBER <> 99999 GROUP BY 1, 2)
SELECT s.STATE, s.name, s.res_cust, nm.nm_res_inst, ROUND(nm.nm_res_mw, 3) nm_res_mw, ROUND(nn.nn_res_pv_mw, 3) nn_res_pv_mw, nn.nn_generators,
       ROUND(1e6 * (COALESCE(nm.nm_res_mw, 0) + COALESCE(nn.nn_res_pv_mw, 0)) / s.res_cust, 1) res_solar_watts_per_home
FROM s LEFT JOIN nm ON nm.UTILITY_NUMBER = s.UTILITY_NUMBER AND nm.STATE = s.STATE
LEFT JOIN nn ON nn.UTILITY_NUMBER = s.UTILITY_NUMBER AND nn.STATE = s.STATE
WHERE s.STATE IN ('AL', 'GA', 'MS', 'TN') AND s.res_cust >= 100000
ORDER BY res_solar_watts_per_home;

-- S13 distribution systems: the zero-VVO big utilities, the round-100% reporters, and customers per circuit (join to sales)
WITH s AS (
  SELECT UTILITY_NUMBER, STATE, SUM(TOTAL_CUSTOMERS) cust
  FROM LIBRARY_MARTS.ENERGY.ENERGY__FED_EIA861_SALES_ULT_CUST
  WHERE SERVICE_TYPE IN ('Bundled', 'Delivery') GROUP BY 1, 2)
SELECT d.STATE, d.UTILITY_NAME, d.DISTRIBUTION_CIRCUITS, d.CIRCUITS_WITH_VOLTAGE_OPTIMIZATION,
       ROUND(d.CIRCUITS_WITH_VOLTAGE_OPTIMIZATION / d.DISTRIBUTION_CIRCUITS, 3) vo_share, s.cust,
       ROUND(s.cust / d.DISTRIBUTION_CIRCUITS) cust_per_circuit
FROM LIBRARY_MARTS.ENERGY.ENERGY__FED_EIA861_DISTRIBUTION_SYSTEMS d
LEFT JOIN s ON s.UTILITY_NUMBER = d.UTILITY_NUMBER AND s.STATE = d.STATE
WHERE d.DISTRIBUTION_CIRCUITS >= 1000 OR d.UTILITY_NAME ILIKE 'Northern Indiana%' OR d.UTILITY_NAME ILIKE 'Duke Energy%'
ORDER BY vo_share NULLS LAST, d.DISTRIBUTION_CIRCUITS DESC;

-- S14 trap sweep: filler rows per table (adjustment 99999, withheld 88888, all-null note rows) and the negative sums they carry
SELECT 'NET_METERING' t, COUNT_IF(UTILITY_NUMBER = 99999) adj_rows, COUNT_IF(UTILITY_NUMBER = 88888) withheld, COUNT_IF(UTILITY_NUMBER IS NULL) null_rows,
       ROUND(SUM(IFF(UTILITY_NUMBER = 99999, TOTAL_CAPACITY_MW, 0)), 1) adj_mw, COUNT_IF(TOTAL_CAPACITY_MW < 0 AND UTILITY_NUMBER <> 99999) neg_real
FROM LIBRARY_MARTS.ENERGY.ENERGY__FED_EIA861_NET_METERING
UNION ALL
SELECT 'NON_NET', COUNT_IF(UTILITY_NUMBER = 99999), COUNT_IF(UTILITY_NUMBER = 88888), COUNT_IF(UTILITY_NUMBER IS NULL),
       ROUND(SUM(IFF(UTILITY_NUMBER = 99999, TOTAL_CAPACITY_MW, 0)), 1), COUNT_IF(TOTAL_CAPACITY_MW < 0 AND UTILITY_NUMBER <> 99999)
FROM LIBRARY_MARTS.ENERGY.ENERGY__FED_EIA861_NON_NET_METERING_DISTRIBUTED
UNION ALL
SELECT 'DYNAMIC_PRICING', COUNT_IF(UTILITY_NUMBER = 99999), COUNT_IF(UTILITY_NUMBER = 88888), COUNT_IF(UTILITY_NUMBER IS NULL), NULL, NULL
FROM LIBRARY_MARTS.ENERGY.ENERGY__FED_EIA861_DYNAMIC_PRICING
UNION ALL
SELECT 'DISTRIBUTION_SYSTEMS', COUNT_IF(UTILITY_NUMBER = 99999), COUNT_IF(UTILITY_NUMBER = 88888), COUNT_IF(UTILITY_NUMBER IS NULL), NULL, NULL
FROM LIBRARY_MARTS.ENERGY.ENERGY__FED_EIA861_DISTRIBUTION_SYSTEMS
UNION ALL
SELECT 'UTILITY_DATA', COUNT_IF(UTILITY_NUMBER = 99999), COUNT_IF(UTILITY_NUMBER = 88888), COUNT_IF(UTILITY_NUMBER IS NULL), NULL, NULL
FROM LIBRARY_MARTS.ENERGY.ENERGY__FED_EIA861_UTILITY_DATA;
