-- skeptic-g3, round 2, 2026-09-24. Leads from deep-12. Python door (connect/db.py).
-- Every connection first ran: ALTER SESSION SET STATEMENT_TIMEOUT_IN_SECONDS = 300; ALTER SESSION SET QUERY_TAG = 'skeptic-r2-2026-09-24';
-- Read-only. SELECT/WITH only. Each statement below is headed '-- @@ <id> <purpose>'.
-- Counts: shared metadata 2, FBI_CDE 6, FJC_IDB_CIVIL 5, OPENSANCTIONS 7 (O2 errored: OBJECT_CONSTRUCT(*) not allowed in WHERE; replaced by O2b + O6).

-- ===== file meta
-- @@ M1 columns of the three tables
SELECT TABLE_NAME, LISTAGG(COLUMN_NAME||':'||DATA_TYPE, ', ') WITHIN GROUP (ORDER BY ORDINAL_POSITION) cols
FROM LIBRARY_MARTS.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME IN ('JUSTICE__FED_FBI_CDE','JUSTICE__FED_FJC_IDB_CIVIL','JUSTICE__INTL_OPENSANCTIONS','CORPORATE_REGISTRY__UK_COMPANIES_HOUSE_PSC','CORPORATE_REGISTRY__INTL_UK_COMPANIES_HOUSE')
GROUP BY 1
-- @@ M2 other FBI / crime / homicide / mortality tables
SELECT TABLE_SCHEMA, TABLE_NAME, ROW_COUNT FROM LIBRARY_MARTS.INFORMATION_SCHEMA.TABLES
WHERE TABLE_NAME ILIKE '%FBI%' OR TABLE_NAME ILIKE '%NIBRS%' OR TABLE_NAME ILIKE '%UCR%' OR TABLE_NAME ILIKE '%HOMICIDE%' OR TABLE_NAME ILIKE '%WONDER%' OR TABLE_NAME ILIKE '%MORTAL%' OR TABLE_NAME ILIKE '%FJC%' OR TABLE_NAME ILIKE '%OFAC%' OR TABLE_NAME ILIKE '%SDN%'
ORDER BY 1,2

-- ===== file fbi1
-- @@ F1 NM by year: homicide offenses, clearances, rate; implied covered population = offenses*1e5/rate (homicide and violent-crime)
SELECT YEAR(MONTH_DATE) yr, OFFENSE, COUNT(*) months, SUM(OFFENSES) off, SUM(CLEARANCES) clr, ROUND(SUM(CLEARANCES)/NULLIF(SUM(OFFENSES),0),3) clr_rate,
       ROUND(SUM(OFFENSES)*100000/NULLIF(SUM(OFFENSE_RATE_PER_100K),0)) implied_pop,
       ROUND(MIN(IFF(OFFENSE_RATE_PER_100K>0, OFFENSES*100000/OFFENSE_RATE_PER_100K, NULL))) min_m_pop, ROUND(MAX(IFF(OFFENSE_RATE_PER_100K>0, OFFENSES*100000/OFFENSE_RATE_PER_100K, NULL))) max_m_pop
FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_FBI_CDE
WHERE STATE='NM' AND OFFENSE IN ('homicide','violent-crime') AND MONTH_DATE >= '2012-01-01'
GROUP BY 1,2 ORDER BY 2,1
-- @@ F0 distinct offense labels
SELECT DISTINCT OFFENSE FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_FBI_CDE

-- ===== file fbi2
-- @@ F2 every state: homicide clearance 2015-19 vs 2022-23, and covered-population ratio (offenses*1e5/rate) for violent-crime, late vs early
WITH y AS (
  SELECT STATE, OFFENSE, IFF(YEAR(MONTH_DATE) BETWEEN 2015 AND 2019,'early','late') per, SUM(OFFENSES) off, SUM(CLEARANCES) clr,
         SUM(OFFENSES)*100000/NULLIF(SUM(OFFENSE_RATE_PER_100K),0) pop
  FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_FBI_CDE
  WHERE OFFENSE IN ('homicide','violent-crime') AND (YEAR(MONTH_DATE) BETWEEN 2015 AND 2019 OR YEAR(MONTH_DATE) IN (2022,2023))
  GROUP BY 1,2,3)
SELECT h.STATE, ROUND(h.clr/h.off,3) hom_early, ROUND(h2.clr/h2.off,3) hom_late, h2.off hom_off_late, ROUND(v2.pop/v.pop,3) cov_ratio_late_vs_early,
       ROUND(v.clr/v.off,3) vc_early, ROUND(v2.clr/v2.off,3) vc_late
FROM y h JOIN y h2 ON h2.STATE=h.STATE AND h2.OFFENSE='homicide' AND h2.per='late'
JOIN y v ON v.STATE=h.STATE AND v.OFFENSE='violent-crime' AND v.per='early'
JOIN y v2 ON v2.STATE=h.STATE AND v2.OFFENSE='violent-crime' AND v2.per='late'
WHERE h.OFFENSE='homicide' AND h.per='early'
ORDER BY hom_late
-- @@ F3 NM vs nation, every offense type: clearance rate 2015-19 vs 2022-23
SELECT OFFENSE,
  ROUND(SUM(IFF(STATE='NM' AND YEAR(MONTH_DATE)<=2019, CLEARANCES,0))/NULLIF(SUM(IFF(STATE='NM' AND YEAR(MONTH_DATE)<=2019, OFFENSES,0)),0),3) nm_early,
  ROUND(SUM(IFF(STATE='NM' AND YEAR(MONTH_DATE)>=2022, CLEARANCES,0))/NULLIF(SUM(IFF(STATE='NM' AND YEAR(MONTH_DATE)>=2022, OFFENSES,0)),0),3) nm_late,
  ROUND(SUM(IFF(STATE<>'NM' AND YEAR(MONTH_DATE)<=2019, CLEARANCES,0))/NULLIF(SUM(IFF(STATE<>'NM' AND YEAR(MONTH_DATE)<=2019, OFFENSES,0)),0),3) us_early,
  ROUND(SUM(IFF(STATE<>'NM' AND YEAR(MONTH_DATE)>=2022, CLEARANCES,0))/NULLIF(SUM(IFF(STATE<>'NM' AND YEAR(MONTH_DATE)>=2022, OFFENSES,0)),0),3) us_late
FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_FBI_CDE
WHERE YEAR(MONTH_DATE) BETWEEN 2015 AND 2019 OR YEAR(MONTH_DATE) IN (2022,2023)
GROUP BY 1 ORDER BY 1
-- @@ F4 NM homicide by month 2021-2023: months with offenses but zero clearances
SELECT YEAR(MONTH_DATE) yr, LISTAGG(OFFENSES||'/'||CLEARANCES, ' ') WITHIN GROUP (ORDER BY MONTH_DATE) off_slash_clr, SUM(IFF(CLEARANCES=0 AND OFFENSES>0,1,0)) zero_clr_months
FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_FBI_CDE WHERE STATE='NM' AND OFFENSE='homicide' AND YEAR(MONTH_DATE) BETWEEN 2016 AND 2023 GROUP BY 1 ORDER BY 1

-- ===== file fbi3
-- @@ F5 CDC WONDER sample: can it give NM homicide deaths to test FBI offense coverage?
SELECT * FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CDC_WONDER LIMIT 5

-- ===== file fjc1
-- @@ J1 PR foreclosures (NOS 220) since 2015, one row per case, by plaintiff class: open share, default share among CLOSED cases, other dispositions
WITH c AS (
  SELECT DISTRICT, OFFICE, DOCKET, FILE_DATE, TAPE_YEAR, JURISDICTION, DISPOSITION, JUDGMENT, TERM_DATE, UPPER(TRIM(PLAINTIFF)) p, UPPER(TRIM(DEFENDANT)) d
  FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_FJC_IDB_CIVIL
  WHERE FILE_DATE >= '2015-01-01' AND NATURE_OF_SUIT = '220'
  QUALIFY ROW_NUMBER() OVER (PARTITION BY DISTRICT, OFFICE, DOCKET, FILE_DATE ORDER BY IFF(TAPE_YEAR=2099,0,1) DESC, TAPE_YEAR DESC) = 1
), k AS (
  SELECT c.*, CASE WHEN DISTRICT<>'04' THEN 'Z mainland'
    WHEN p LIKE '%ROOSEVELT%' THEN 'A roosevelt (any spelling)'
    WHEN p LIKE '%CAYMAN%' THEN 'B other cayman'
    WHEN JURISDICTION IN ('1','2') THEN 'C PR US-govt party'
    WHEN JURISDICTION = '4' THEN 'D PR other diversity'
    ELSE 'E PR other juris' END grp,
    TERM_DATE IS NOT NULL AND DISPOSITION IS NOT NULL AND DISPOSITION NOT IN ('-8','') closed
  FROM c)
SELECT grp, COUNT(*) cases, COUNT(DISTINCT d) distinct_defendants, ROUND(AVG(IFF(closed,0,1)),3) open_share,
  ROUND(AVG(IFF(DISPOSITION='4',1,0)),3) default_all, ROUND(SUM(IFF(DISPOSITION='4',1,0))/NULLIF(SUM(IFF(closed,1,0)),0),3) default_of_closed,
  ROUND(SUM(IFF(DISPOSITION='12',1,0))/NULLIF(SUM(IFF(closed,1,0)),0),3) voldis_of_closed,
  ROUND(SUM(IFF(DISPOSITION='13',1,0))/NULLIF(SUM(IFF(closed,1,0)),0),3) settled_of_closed,
  ROUND(SUM(IFF(DISPOSITION IN ('18','16'),1,0))/NULLIF(SUM(IFF(closed,1,0)),0),3) statclose_or_bkstay_of_closed,
  ROUND(SUM(IFF(DISPOSITION='2',1,0))/NULLIF(SUM(IFF(closed,1,0)),0),3) dwop_of_closed,
  MEDIAN(YEAR(FILE_DATE)) med_file_yr, MIN(FILE_DATE) f0, MAX(FILE_DATE) f1
FROM k GROUP BY grp ORDER BY grp
-- @@ J2 PR only: default share among closed cases by filing year, Roosevelt vs other PR diversity plaintiffs vs other PR
WITH c AS (
  SELECT DISTRICT, OFFICE, DOCKET, FILE_DATE, TAPE_YEAR, JURISDICTION, DISPOSITION, TERM_DATE, UPPER(TRIM(PLAINTIFF)) p
  FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_FJC_IDB_CIVIL
  WHERE FILE_DATE >= '2015-01-01' AND NATURE_OF_SUIT = '220' AND DISTRICT = '04'
  QUALIFY ROW_NUMBER() OVER (PARTITION BY DISTRICT, OFFICE, DOCKET, FILE_DATE ORDER BY IFF(TAPE_YEAR=2099,0,1) DESC, TAPE_YEAR DESC) = 1
)
SELECT YEAR(FILE_DATE) yr,
  SUM(IFF(p LIKE '%ROOSEVELT%',1,0)) roos_n, ROUND(SUM(IFF(p LIKE '%ROOSEVELT%' AND DISPOSITION='4',1,0))/NULLIF(SUM(IFF(p LIKE '%ROOSEVELT%' AND TERM_DATE IS NOT NULL,1,0)),0),3) roos_def,
  SUM(IFF(p NOT LIKE '%ROOSEVELT%' AND p NOT LIKE '%CAYMAN%' AND JURISDICTION='4',1,0)) div_n,
  ROUND(SUM(IFF(p NOT LIKE '%ROOSEVELT%' AND p NOT LIKE '%CAYMAN%' AND JURISDICTION='4' AND DISPOSITION='4',1,0))/NULLIF(SUM(IFF(p NOT LIKE '%ROOSEVELT%' AND p NOT LIKE '%CAYMAN%' AND JURISDICTION='4' AND TERM_DATE IS NOT NULL,1,0)),0),3) div_def,
  SUM(IFF(p NOT LIKE '%ROOSEVELT%' AND p NOT LIKE '%CAYMAN%' AND JURISDICTION IN ('1','2'),1,0)) gov_n,
  ROUND(SUM(IFF(p NOT LIKE '%ROOSEVELT%' AND p NOT LIKE '%CAYMAN%' AND JURISDICTION IN ('1','2') AND DISPOSITION='4',1,0))/NULLIF(SUM(IFF(p NOT LIKE '%ROOSEVELT%' AND p NOT LIKE '%CAYMAN%' AND JURISDICTION IN ('1','2') AND TERM_DATE IS NOT NULL,1,0)),0),3) gov_def
FROM c GROUP BY 1 ORDER BY 1
-- @@ J3 PR diversity foreclosure plaintiffs with 40+ cases since 2015: who are Roosevelt's real peers, and their default share of closed cases
WITH c AS (
  SELECT DISTRICT, OFFICE, DOCKET, FILE_DATE, TAPE_YEAR, JURISDICTION, DISPOSITION, TERM_DATE, UPPER(TRIM(PLAINTIFF)) p
  FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_FJC_IDB_CIVIL
  WHERE FILE_DATE >= '2015-01-01' AND NATURE_OF_SUIT = '220' AND DISTRICT = '04'
  QUALIFY ROW_NUMBER() OVER (PARTITION BY DISTRICT, OFFICE, DOCKET, FILE_DATE ORDER BY IFF(TAPE_YEAR=2099,0,1) DESC, TAPE_YEAR DESC) = 1
)
SELECT p, MODE(JURISDICTION) juris, COUNT(*) n, SUM(IFF(TERM_DATE IS NOT NULL,1,0)) closed,
  ROUND(SUM(IFF(DISPOSITION='4',1,0))/NULLIF(SUM(IFF(TERM_DATE IS NOT NULL,1,0)),0),3) def_of_closed,
  ROUND(SUM(IFF(DISPOSITION='12',1,0))/NULLIF(SUM(IFF(TERM_DATE IS NOT NULL,1,0)),0),3) vol_of_closed,
  MIN(YEAR(FILE_DATE)) y0, MAX(YEAR(FILE_DATE)) y1
FROM c GROUP BY p HAVING COUNT(*) >= 30 ORDER BY n DESC

-- ===== file fjc2
-- @@ J4 every Roosevelt-named case since 2005, any case type, one row per case: by filing year, district, case type
WITH c AS (
  SELECT DISTRICT, OFFICE, DOCKET, FILE_DATE, TAPE_YEAR, NATURE_OF_SUIT, JURISDICTION, DISPOSITION, UPPER(TRIM(PLAINTIFF)) p
  FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_FJC_IDB_CIVIL
  WHERE FILE_DATE >= '2005-01-01' AND UPPER(PLAINTIFF) LIKE '%ROOSEVELT%CAYMAN%'
  QUALIFY ROW_NUMBER() OVER (PARTITION BY DISTRICT, OFFICE, DOCKET, FILE_DATE ORDER BY IFF(TAPE_YEAR=2099,0,1) DESC, TAPE_YEAR DESC) = 1
)
SELECT YEAR(FILE_DATE) yr, DISTRICT, NATURE_OF_SUIT, JURISDICTION, COUNT(*) n, ROUND(AVG(IFF(DISPOSITION='4',1,0)),3) def_share
FROM c GROUP BY 1,2,3,4 ORDER BY 1,2,3
-- @@ J5 sample Roosevelt cases filed 2015: defendant, dates, disposition, judgment, amount demanded, tape years the case appears in
SELECT DOCKET, OFFICE, FILE_DATE, TERM_DATE, DISPOSITION, JUDGMENT, NATURE_OF_JUDGMENT, AMOUNT_DEMANDED, LEFT(DEFENDANT,30) def, TERM_JUDGE,
       LISTAGG(DISTINCT TAPE_YEAR, ',') tapes, COUNT(*) row_copies
FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_FJC_IDB_CIVIL
WHERE DISTRICT='04' AND UPPER(PLAINTIFF) LIKE '%ROOSEVELT%CAYMAN%' AND FILE_DATE BETWEEN '2015-03-01' AND '2015-03-20'
GROUP BY 1,2,3,4,5,6,7,8,9,10 ORDER BY FILE_DATE LIMIT 25

-- ===== file os1
-- @@ O1 Ka On Kong and Brendon Luo in OpenSanctions: DOB, countries, addresses, identifiers, sanctions text, dataset, first seen
SELECT ID, NAME, BIRTH_DATE_RAW, COUNTRIES, LEFT(ADDRESSES,300) addr, LEFT(IDENTIFIERS,200) ids, LEFT(SANCTIONS,300) sanc, DATASET, FIRST_SEEN, LEFT(ALIASES,200) aliases
FROM LIBRARY_MARTS.JUSTICE.JUSTICE__INTL_OPENSANCTIONS WHERE UPPER(NAME) LIKE '%KA ON KONG%' OR UPPER(NAME) LIKE '%KONG KA ON%' OR UPPER(NAME) LIKE '%BRENDON LUO%'
-- @@ O2 same people in the OFAC SDN table (independent copy)
SELECT * FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_OFAC_SDN WHERE UPPER(TO_VARCHAR(OBJECT_CONSTRUCT(*))) LIKE '%KONG, KA ON%' OR UPPER(TO_VARCHAR(OBJECT_CONSTRUCT(*))) LIKE '%KA ON KONG%' OR UPPER(TO_VARCHAR(OBJECT_CONSTRUCT(*))) LIKE '%LUO, BRENDON%'
-- @@ O3 every UK PSC row named Ka On Kong: distinct people by DOB, nationality, residence, company count, row copies
SELECT UPPER(NAME) nm, DOB_YEAR, DOB_MONTH, NATIONALITY, COUNTRY_OF_RESIDENCE, COUNT(*) rows_, COUNT(DISTINCT COMPANY_NUMBER) companies, COUNT(DISTINCT PSC_LINK_SELF) psc_links,
       SUM(IFF(CEASED_ON IS NULL,1,0)) open_rows, COUNT(DISTINCT IFF(CEASED_ON IS NULL, COMPANY_NUMBER, NULL)) open_companies, MIN(NOTIFIED_ON) n0, MAX(NOTIFIED_ON) n1,
       LISTAGG(DISTINCT ADDRESS_POSTAL_CODE, ',') postcodes
FROM LIBRARY_MARTS.CORPORATE_REGISTRY.CORPORATE_REGISTRY__UK_COMPANIES_HOUSE_PSC
WHERE UPPER(NAME_SURNAME)='KONG' AND UPPER(NAME_FORENAME) LIKE 'KA%'
GROUP BY 1,2,3,4,5 ORDER BY companies DESC

-- ===== file os2
-- @@ O2b OFAC SDN table columns and row counts of PSC (size before the null test)
SELECT TABLE_NAME, ROW_COUNT, (SELECT LISTAGG(COLUMN_NAME, ',') FROM LIBRARY_MARTS.INFORMATION_SCHEMA.COLUMNS c WHERE c.TABLE_NAME = t.TABLE_NAME AND c.TABLE_SCHEMA = t.TABLE_SCHEMA) cols
FROM LIBRARY_MARTS.INFORMATION_SCHEMA.TABLES t WHERE TABLE_NAME IN ('JUSTICE__FED_OFAC_SDN','CORPORATE_REGISTRY__UK_COMPANIES_HOUSE_PSC') AND TABLE_SCHEMA <> 'TIMELINE'

-- ===== file os3
-- @@ O4 null test: OFAC SDN + UK FCDO people with full DOB vs UK PSC individuals, sorted-token full-name equality + birth year + month; true DOB (shift 0) vs fake DOB (birth year shifted -2,-1,+1,+2). Fake-DOB hits estimate same-name strangers.
WITH os AS (
  SELECT ID, YEAR(BIRTH_DATE) by_, MONTH(BIRTH_DATE) bm,
         ARRAY_TO_STRING(ARRAY_SORT(SPLIT(TRIM(REGEXP_REPLACE(REGEXP_REPLACE(UPPER(NAME),'[^A-Z ]',' '),' +',' ')),' ')),' ') nk,
         DATASET ILIKE '%OFAC Specially%' ofac
  FROM LIBRARY_MARTS.JUSTICE.JUSTICE__INTL_OPENSANCTIONS
  WHERE SCHEMA='Person' AND BIRTH_DATE IS NOT NULL AND LENGTH(BIRTH_DATE_RAW) >= 10 AND (DATASET ILIKE '%OFAC Specially%' OR DATASET ILIKE '%UK FCDO%')
), s AS (SELECT column1 sh FROM VALUES (0),(-2),(-1),(1),(2)),
psc AS (
  SELECT COMPANY_NUMBER, TRY_TO_NUMBER(TO_VARCHAR(DOB_YEAR)) y, TRY_TO_NUMBER(TO_VARCHAR(DOB_MONTH)) m, CEASED_ON,
         ARRAY_TO_STRING(ARRAY_SORT(SPLIT(TRIM(REGEXP_REPLACE(REGEXP_REPLACE(UPPER(COALESCE(NAME_FORENAME,'')||' '||COALESCE(NAME_MIDDLE,'')||' '||COALESCE(NAME_SURNAME,'')),'[^A-Z ]',' '),' +',' ')),' ')),' ') nk
  FROM LIBRARY_MARTS.CORPORATE_REGISTRY.CORPORATE_REGISTRY__UK_COMPANIES_HOUSE_PSC
  WHERE KIND ILIKE 'individual%' AND DOB_YEAR IS NOT NULL
)
SELECT s.sh, COUNT(DISTINCT os.ID) people_matched, COUNT(DISTINCT psc.COMPANY_NUMBER) companies,
       COUNT(DISTINCT IFF(psc.CEASED_ON IS NULL, os.ID, NULL)) people_open_control, COUNT(DISTINCT IFF(psc.CEASED_ON IS NULL, psc.COMPANY_NUMBER, NULL)) companies_open,
       COUNT(DISTINCT IFF(os.ofac, os.ID, NULL)) ofac_people
FROM os CROSS JOIN s JOIN psc ON psc.nk = os.nk AND psc.y = os.by_ + s.sh AND psc.m = os.bm
GROUP BY 1 ORDER BY 1

-- ===== file os4
-- @@ O5 true-DOB strict matches with open control: who, which program, how many open UK companies, PSC nationality, how many active in Companies House
WITH os AS (
  SELECT ID, NAME, LEFT(SANCTIONS,60) sanc, COUNTRIES, YEAR(BIRTH_DATE) by_, MONTH(BIRTH_DATE) bm,
         ARRAY_TO_STRING(ARRAY_SORT(SPLIT(TRIM(REGEXP_REPLACE(REGEXP_REPLACE(UPPER(NAME),'[^A-Z ]',' '),' +',' ')),' ')),' ') nk
  FROM LIBRARY_MARTS.JUSTICE.JUSTICE__INTL_OPENSANCTIONS
  WHERE SCHEMA='Person' AND BIRTH_DATE IS NOT NULL AND LENGTH(BIRTH_DATE_RAW) >= 10 AND (DATASET ILIKE '%OFAC Specially%' OR DATASET ILIKE '%UK FCDO%')
), psc AS (
  SELECT COMPANY_NUMBER, TRY_TO_NUMBER(TO_VARCHAR(DOB_YEAR)) y, TRY_TO_NUMBER(TO_VARCHAR(DOB_MONTH)) m, CEASED_ON, NATIONALITY,
         ARRAY_TO_STRING(ARRAY_SORT(SPLIT(TRIM(REGEXP_REPLACE(REGEXP_REPLACE(UPPER(COALESCE(NAME_FORENAME,'')||' '||COALESCE(NAME_MIDDLE,'')||' '||COALESCE(NAME_SURNAME,'')),'[^A-Z ]',' '),' +',' ')),' ')),' ') nk
  FROM LIBRARY_MARTS.CORPORATE_REGISTRY.CORPORATE_REGISTRY__UK_COMPANIES_HOUSE_PSC
  WHERE KIND ILIKE 'individual%' AND DOB_YEAR IS NOT NULL AND CEASED_ON IS NULL
)
SELECT os.NAME, os.sanc, os.COUNTRIES, COUNT(DISTINCT psc.COMPANY_NUMBER) open_cos, LISTAGG(DISTINCT psc.NATIONALITY, '/') psc_nat,
       COUNT(DISTINCT IFF(u.COMPANY_STATUS ILIKE 'active%', u.COMPANY_NUMBER, NULL)) ch_active, COUNT(DISTINCT u.COMPANY_NUMBER) ch_found
FROM os JOIN psc ON psc.nk = os.nk AND psc.y = os.by_ AND psc.m = os.bm
LEFT JOIN LIBRARY_MARTS.CORPORATE_REGISTRY.CORPORATE_REGISTRY__INTL_UK_COMPANIES_HOUSE u ON u.COMPANY_NUMBER = psc.COMPANY_NUMBER
GROUP BY 1,2,3 ORDER BY open_cos DESC

-- ===== file os5
-- @@ O6 OFAC SDN table: remarks for Kong, Luo, Chen Zhi (linked-to entities, DOB, passport)
SELECT ENT_NUM, SDN_NAME, PROGRAM, LEFT(REMARKS, 600) remarks FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_OFAC_SDN
WHERE UPPER(SDN_NAME) IN ('KONG, KA ON','LUO, BRENDON','CHEN, ZHI') OR UPPER(SDN_NAME) LIKE 'KONG, KA%' OR UPPER(SDN_NAME) LIKE 'LUO, BREND%'

