-- skeptic-g6, round 2, 2026-09-24. Python door (connect/db.py). Read-only: SELECT/WITH only.
-- Every connection first ran: ALTER SESSION SET STATEMENT_TIMEOUT_IN_SECONDS = 300; ALTER SESSION SET QUERY_TAG = 'skeptic-r2-2026-09-24'.
-- 15 statements: 1 metadata, L1 RCRA 2, L2 NPDES 3, L3 SDWA site visits 3, L4 SDWA LALE 6 (g6-L4-2 hit a Snowflake internal error, no data; re-run as L4-2b).

-- [g6-0 metadata: columns of lead tables and any enforcement/case/mine tables]
SELECT table_name, LISTAGG(column_name, ',') WITHIN GROUP (ORDER BY ordinal_position) cols
FROM LIBRARY_MARTS.INFORMATION_SCHEMA.COLUMNS
WHERE table_schema = 'ENVIRONMENT' AND (table_name IN ('ENVIRONMENT__FED_EPA_NPDES_NPDES_FORMAL_ENFORCEMENT_ACTIONS','ENVIRONMENT__FED_EPA_SDWA_SDWA_LCR_SAMPLES','ENVIRONMENT__FED_EPA_SDWA_SDWA_EVENTS_MILESTONES','ENVIRONMENT__FED_EPA_SDWA_SDWA_SITE_VISITS','ENVIRONMENT__FED_EPA_RCRA_EVALUATIONS','ENVIRONMENT__FED_EPA_NPDES_ICIS_FACILITIES','ENVIRONMENT__FED_EPA_ECHO')
  OR table_name ILIKE '%ENFORCE%' OR table_name ILIKE '%CASE%' OR table_name ILIKE '%SMCRA%' OR table_name ILIKE '%MINE%')
GROUP BY 1 ORDER BY 1;

-- [g6-L4-1 SDWA LCR: PB90 units, sign codes, spread, since 2024-10-16]
SELECT UNIT_OF_MEASURE, RESULT_SIGN_CODE, COUNT(*) n, COUNT(DISTINCT PWSID) sys,
  COUNT(DISTINCT SAMPLE_ID) sample_ids, COUNT(DISTINCT PWSID||'|'||SAMPLE_ID) pws_sample_ids,
  MIN(SAMPLE_MEASURE) mn, MEDIAN(SAMPLE_MEASURE) med, APPROX_PERCENTILE(SAMPLE_MEASURE,0.9) p90, MAX(SAMPLE_MEASURE) mx,
  COUNT(DISTINCT IFF(SAMPLE_MEASURE > 0.015, PWSID, NULL)) sys_over_015,
  COUNT(DISTINCT IFF(SAMPLE_MEASURE > 1, PWSID, NULL)) sys_over_1,
  COUNT(DISTINCT IFF(SAMPLE_MEASURE >= 15, PWSID, NULL)) sys_ge_15,
  MIN(SAMPLING_END_DATE) min_end, MAX(SAMPLING_END_DATE) max_end,
  COUNT(DISTINCT LEFT(PWSID,2)) states
FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_SDWA_SDWA_LCR_SAMPLES
WHERE CONTAMINANT_CODE = 'PB90' AND SAMPLING_END_DATE >= '2024-10-16'
GROUP BY ROLLUP(UNIT_OF_MEASURE, RESULT_SIGN_CODE) ORDER BY n DESC;

-- [g6-L4-2 SDWA LCR x LALE: over-limit systems by when the period started and when the result was reported vs the 2024-10-16 rule]
WITH o AS (
  SELECT PWSID, MIN(SAMPLING_START_DATE) min_start, MAX(SAMPLING_END_DATE) max_end,
    MAX(COALESCE(SAR_FIRST_REPORTED_DATE, SAMPLE_FIRST_REPORTED_DATE)) last_rep, MIN(COALESCE(SAR_FIRST_REPORTED_DATE, SAMPLE_FIRST_REPORTED_DATE)) first_rep,
    MAX(IFF(SAMPLING_START_DATE >= '2024-10-16',1,0)) any_start_post,
    MAX(IFF(COALESCE(SAR_FIRST_REPORTED_DATE, SAMPLE_FIRST_REPORTED_DATE) >= '2024-10-16',1,0)) any_rep_post,
    MAX(IFF(SAMPLING_END_DATE > '2026-09-24',1,0)) any_future_end,
    MAX(DATEDIFF(day, SAMPLING_START_DATE, SAMPLING_END_DATE)) max_len
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_SDWA_SDWA_LCR_SAMPLES
  WHERE CONTAMINANT_CODE = 'PB90' AND SAMPLING_END_DATE >= '2024-10-16' AND SAMPLE_MEASURE > 0.015
  GROUP BY 1),
l AS (SELECT PWSID, MIN(EVENT_ACTUAL_DATE) lale_dt, COUNT(*) n FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_SDWA_SDWA_EVENTS_MILESTONES WHERE EVENT_MILESTONE_CODE = 'LALE' GROUP BY 1),
lst AS (SELECT DISTINCT LEFT(PWSID,2) st FROM l),
p AS (SELECT PWSID, COUNT(*) prow, MAX(POPULATION_SERVED_COUNT) pop FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_SDWA_SDWA_PUB_WATER_SYSTEMS GROUP BY 1)
SELECT IFF(LEFT(o.PWSID,2) IN (SELECT st FROM lst),'state logs LALE','state logs none') peer,
  CASE WHEN any_start_post = 1 THEN 'A period starts after rule'
       WHEN any_rep_post = 1 THEN 'B period starts before, reported after rule'
       ELSE 'C reported before rule' END timing,
  COUNT(*) sys, SUM(IFF(l.PWSID IS NOT NULL,1,0)) with_lale, SUM(p.pop) pop, SUM(IFF(p.prow > 1,1,0)) dup_pws_rows,
  SUM(any_future_end) future_end, MEDIAN(max_len) med_period_days, MIN(first_rep) min_rep, MAX(last_rep) max_rep,
  SUM(IFF(l.PWSID IS NOT NULL AND l.lale_dt < '2024-10-16',1,0)) lale_before_rule
FROM o LEFT JOIN l ON l.PWSID = o.PWSID LEFT JOIN p ON p.PWSID = o.PWSID
GROUP BY ROLLUP(1,2) ORDER BY 1,2;

-- [g6-L4-2b (retry of L4-2 after internal error) over-limit systems by timing vs 2024-10-16 rule, LALE row, peer state]
WITH o AS (
  SELECT PWSID, MIN(SAMPLING_START_DATE) min_start, MAX(SAMPLING_END_DATE) max_end,
    MAX(COALESCE(SAR_FIRST_REPORTED_DATE, SAMPLE_FIRST_REPORTED_DATE)) last_rep, MIN(COALESCE(SAR_FIRST_REPORTED_DATE, SAMPLE_FIRST_REPORTED_DATE)) first_rep,
    MAX(IFF(SAMPLING_START_DATE >= '2024-10-16',1,0)) any_start_post,
    MAX(IFF(COALESCE(SAR_FIRST_REPORTED_DATE, SAMPLE_FIRST_REPORTED_DATE) >= '2024-10-16',1,0)) any_rep_post,
    MAX(IFF(SAMPLING_END_DATE > '2026-09-24',1,0)) any_future_end,
    MAX(DATEDIFF(day, SAMPLING_START_DATE, SAMPLING_END_DATE)) max_len
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_SDWA_SDWA_LCR_SAMPLES
  WHERE CONTAMINANT_CODE = 'PB90' AND SAMPLING_END_DATE >= '2024-10-16' AND SAMPLE_MEASURE > 0.015
  GROUP BY 1),
l AS (SELECT PWSID, MIN(EVENT_ACTUAL_DATE) lale_dt, COUNT(*) n FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_SDWA_SDWA_EVENTS_MILESTONES WHERE EVENT_MILESTONE_CODE = 'LALE' GROUP BY 1),
lst AS (SELECT LEFT(PWSID,2) st, COUNT(*) k FROM l GROUP BY 1),
p AS (SELECT PWSID, COUNT(*) prow, MAX(POPULATION_SERVED_COUNT) pop FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_SDWA_SDWA_PUB_WATER_SYSTEMS GROUP BY 1),
x AS (
  SELECT o.*, IFF(lst.st IS NOT NULL,'state logs LALE','state logs none') peer,
    CASE WHEN any_start_post = 1 THEN 'A period starts after rule'
         WHEN any_rep_post = 1 THEN 'B period starts before, reported after'
         ELSE 'C reported before rule' END timing,
    IFF(l.PWSID IS NOT NULL,1,0) has_lale, l.lale_dt, p.pop, p.prow
  FROM o LEFT JOIN l ON l.PWSID = o.PWSID LEFT JOIN p ON p.PWSID = o.PWSID LEFT JOIN lst ON lst.st = LEFT(o.PWSID,2))
SELECT peer, timing, COUNT(*) sys, SUM(has_lale) with_lale, SUM(pop) pop, SUM(IFF(prow > 1,1,0)) dup_pws_rows,
  SUM(any_future_end) future_end, MEDIAN(max_len) med_period_days, MIN(first_rep) min_rep, MAX(last_rep) max_rep,
  SUM(IFF(has_lale = 1 AND lale_dt < '2024-10-16',1,0)) lale_before_rule
FROM x GROUP BY 1,2 ORDER BY 1,2;

-- [g6-L4-3 SDWA LALE coverage by state: systems over 0.015 in periods starting after rule vs LALE rows; LALE dates and first-reported dates]
WITH o AS (
  SELECT PWSID FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_SDWA_SDWA_LCR_SAMPLES
  WHERE CONTAMINANT_CODE = 'PB90' AND SAMPLE_MEASURE > 0.015 AND SAMPLING_START_DATE >= '2024-10-16'
  GROUP BY 1),
l AS (SELECT PWSID, MIN(EVENT_ACTUAL_DATE) lale_dt, MIN(FIRST_REPORTED_DATE) frep, MAX(EVENT_REASON_CODE) rsn, MAX(EVENT_COMMENTS_TEXT) cmt,
        COUNT(EVENT_END_DATE) endf, COUNT(*) n
      FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_SDWA_SDWA_EVENTS_MILESTONES WHERE EVENT_MILESTONE_CODE = 'LALE' GROUP BY 1),
s AS (
  SELECT COALESCE(LEFT(o.PWSID,2), LEFT(l.PWSID,2)) st,
    COUNT(DISTINCT o.PWSID) over_post, COUNT(DISTINCT IFF(o.PWSID IS NOT NULL AND l.PWSID IS NOT NULL, o.PWSID, NULL)) over_post_with_lale,
    COUNT(DISTINCT l.PWSID) lale_sys, COUNT(DISTINCT IFF(l.PWSID IS NOT NULL AND o.PWSID IS NULL, l.PWSID, NULL)) lale_without_post_over,
    MIN(l.lale_dt) min_lale, MAX(l.lale_dt) max_lale, MIN(l.frep) min_frep, MAX(l.frep) max_frep, COUNT(DISTINCT l.lale_dt) lale_dates,
    MAX(l.rsn) rsn, MAX(l.cmt) cmt
  FROM o FULL OUTER JOIN l ON l.PWSID = o.PWSID GROUP BY 1)
SELECT * FROM s ORDER BY lale_sys DESC, over_post DESC LIMIT 45;

-- [g6-L4-4 SDWA: post-rule over-limit systems, LALE yes/no, any LCR or PN violation since 2024-10; largest no-LALE systems in LALE-logging states]
WITH o AS (
  SELECT PWSID, MAX(SAMPLE_MEASURE) pb90, MAX(SAR_FIRST_REPORTED_DATE) rep, MIN(SAMPLING_START_DATE) st_dt, MAX(SAMPLING_END_DATE) end_dt
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_SDWA_SDWA_LCR_SAMPLES
  WHERE CONTAMINANT_CODE = 'PB90' AND SAMPLE_MEASURE > 0.015 AND SAMPLING_START_DATE >= '2024-10-16'
  GROUP BY 1),
l AS (SELECT DISTINCT PWSID FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_SDWA_SDWA_EVENTS_MILESTONES WHERE EVENT_MILESTONE_CODE = 'LALE'),
lst AS (SELECT DISTINCT LEFT(PWSID,2) st FROM l),
v AS (SELECT PWSID, LISTAGG(DISTINCT VIOLATION_CODE||'/'||COALESCE(CONTAMINANT_CODE,'-')||'/'||COALESCE(RULE_CODE,'-'), ' ') codes, COUNT(DISTINCT VIOLATION_ID) nv
      FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_SDWA_SDWA_VIOLATIONS_ENFORCEMENT
      WHERE COMPL_PER_BEGIN_DATE >= '2024-10-01' AND (RULE_FAMILY_CODE = '300' OR RULE_CODE IN ('350','410','420') OR CONTAMINANT_CODE IN ('PB90','5000','7000','1030'))
      GROUP BY 1),
p AS (SELECT PWSID, MAX(PWS_NAME) nm, MAX(POPULATION_SERVED_COUNT) pop, MAX(PWS_TYPE_CODE) t FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_SDWA_SDWA_PUB_WATER_SYSTEMS GROUP BY 1),
x AS (SELECT o.*, p.nm, p.pop, p.t, v.codes, v.nv, IFF(l.PWSID IS NULL,0,1) has_lale, IFF(lst.st IS NULL,0,1) st_logs
      FROM o JOIN p ON p.PWSID = o.PWSID LEFT JOIN l ON l.PWSID = o.PWSID LEFT JOIN v ON v.PWSID = o.PWSID LEFT JOIN lst ON lst.st = LEFT(o.PWSID,2))
SELECT 'SUM' k, st_logs::string||'/'||has_lale::string grp, COUNT(*) sys, SUM(pop) pop, COUNT(v_any) with_lcr_or_pn_viol, NULL nm, NULL pb90, NULL rep, NULL codes
FROM (SELECT x.*, IFF(nv > 0, 1, NULL) v_any FROM x) GROUP BY 2
UNION ALL
SELECT * FROM (SELECT 'TOP', PWSID, 1, pop, nv, nm||' ['||t||']', pb90, rep::string||' '||st_dt::string||'..'||end_dt::string, codes FROM x WHERE st_logs = 1 AND has_lale = 0 ORDER BY pop DESC LIMIT 20)
ORDER BY 1 DESC, 4 DESC;

-- [g6-L4-5 SDWA: post-rule over-limit systems, PN violation (code 75) since rule, recent results, LALE upload lag]
WITH o AS (
  SELECT PWSID, MAX(SAR_FIRST_REPORTED_DATE) rep
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_SDWA_SDWA_LCR_SAMPLES
  WHERE CONTAMINANT_CODE = 'PB90' AND SAMPLE_MEASURE > 0.015 AND SAMPLING_START_DATE >= '2024-10-16'
  GROUP BY 1),
l AS (SELECT DISTINCT PWSID FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_SDWA_SDWA_EVENTS_MILESTONES WHERE EVENT_MILESTONE_CODE = 'LALE'),
lst AS (SELECT DISTINCT LEFT(PWSID,2) st FROM l),
pn AS (SELECT DISTINCT PWSID FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_SDWA_SDWA_VIOLATIONS_ENFORCEMENT
       WHERE VIOLATION_CODE = '75' AND COMPL_PER_BEGIN_DATE >= '2024-10-16'),
lag AS (SELECT MEDIAN(DATEDIFF(day, EVENT_ACTUAL_DATE, FIRST_REPORTED_DATE)) med_lag, APPROX_PERCENTILE(DATEDIFF(day, EVENT_ACTUAL_DATE, FIRST_REPORTED_DATE),0.9) p90_lag
        FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_SDWA_SDWA_EVENTS_MILESTONES WHERE EVENT_MILESTONE_CODE = 'LALE')
SELECT IFF(lst.st IS NULL,'state logs none','state logs LALE') peer, IFF(l.PWSID IS NULL,'no LALE','LALE') lale,
  COUNT(*) sys, SUM(IFF(pn.PWSID IS NOT NULL,1,0)) with_pn_viol_75,
  SUM(IFF(o.rep >= '2026-03-01',1,0)) result_reported_since_2026_03,
  SUM(IFF(pn.PWSID IS NULL AND o.rep < '2026-03-01',1,0)) no_pn_and_older_than_2026_03,
  MAX(lag.med_lag) lale_med_upload_lag_days, MAX(lag.p90_lag) lale_p90_lag_days
FROM o LEFT JOIN l ON l.PWSID = o.PWSID LEFT JOIN lst ON lst.st = LEFT(o.PWSID,2) LEFT JOIN pn ON pn.PWSID = o.PWSID CROSS JOIN lag
GROUP BY 1,2 ORDER BY 1,2;

-- [g6-L3-1 SDWA: big CWS with no SNSV/SNSP/SNSF since 2021-07, by source type/wholesaler and by state, with visit codes since]
WITH sv AS (SELECT PWSID, MAX(IFF(VISIT_REASON_CODE IN ('SNSV','SNSP','SNSF'), VISIT_DATE, NULL)) last_s,
                   LISTAGG(DISTINCT IFF(VISIT_DATE >= '2021-07-01', VISIT_REASON_CODE, NULL), ',') codes_since,
                   COUNT(IFF(VISIT_DATE >= '2021-07-01',1,NULL)) visits_since
            FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_SDWA_SDWA_SITE_VISITS WHERE VISIT_DATE >= '1950-01-01' GROUP BY 1),
pr AS (SELECT PWSID, COUNT(*) prow, COUNT(DISTINCT SUBMISSIONYEARQUARTER) q FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_SDWA_SDWA_PUB_WATER_SYSTEMS GROUP BY 1),
p AS (SELECT PWSID, PWS_NAME, PRIMACY_AGENCY_CODE ag, POPULATION_SERVED_COUNT pop, IS_WHOLESALER_IND wh, PRIMARY_SOURCE_CODE src
      FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_SDWA_SDWA_PUB_WATER_SYSTEMS WHERE PWS_ACTIVITY_CODE='A' AND PWS_TYPE_CODE='CWS' AND POPULATION_SERVED_COUNT >= 10000),
x AS (SELECT p.*, sv.last_s, sv.codes_since, COALESCE(sv.visits_since,0) visits_since, pr.prow
      FROM p LEFT JOIN sv USING (PWSID) LEFT JOIN pr USING (PWSID) WHERE COALESCE(sv.last_s,'1900-01-01') < '2021-07-01')
SELECT 'BYSRC' k, src||' wh='||wh grp, COUNT(*) sys, SUM(pop) pop, SUM(IFF(visits_since = 0,1,0)) no_visit_any_kind, SUM(IFF(last_s IS NULL,1,0)) never_surveyed, MAX(prow)::string maxrows, NULL codes
FROM x GROUP BY 2
UNION ALL
SELECT 'BYST', ag, COUNT(*), SUM(pop), SUM(IFF(visits_since = 0,1,0)), SUM(IFF(last_s IS NULL,1,0)), NULL, LISTAGG(DISTINCT codes_since, ',')
FROM x GROUP BY 2
UNION ALL
SELECT 'ALL', 'all', COUNT(*), SUM(pop), SUM(IFF(visits_since = 0,1,0)), SUM(IFF(last_s IS NULL,1,0)), MAX(prow)::string, NULL FROM x
ORDER BY 1, 4 DESC;

-- [g6-L3-2 SDWA: big CWS surveyed per year by state 2016-2026, last survey date, upload lag (visit to first reported)]
WITH b AS (SELECT PWSID, PRIMACY_AGENCY_CODE ag FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_SDWA_SDWA_PUB_WATER_SYSTEMS
           WHERE PWS_ACTIVITY_CODE='A' AND PWS_TYPE_CODE='CWS' AND POPULATION_SERVED_COUNT >= 10000),
v AS (SELECT s.PWSID, b.ag, YEAR(s.VISIT_DATE) yr, s.VISIT_DATE, s.FIRST_REPORTED_DATE
      FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_SDWA_SDWA_SITE_VISITS s JOIN b ON b.PWSID = s.PWSID
      WHERE s.VISIT_REASON_CODE IN ('SNSV','SNSP','SNSF') AND s.VISIT_DATE BETWEEN '2014-01-01' AND '2026-12-31')
SELECT IFF(ag IN ('CA','NJ','WA','OR','MI','NY','TN','TX'), ag, 'other') grp,
  COUNT(DISTINCT IFF(yr=2016,PWSID,NULL)) s16, COUNT(DISTINCT IFF(yr=2017,PWSID,NULL)) s17, COUNT(DISTINCT IFF(yr=2018,PWSID,NULL)) s18,
  COUNT(DISTINCT IFF(yr=2019,PWSID,NULL)) s19, COUNT(DISTINCT IFF(yr=2020,PWSID,NULL)) s20, COUNT(DISTINCT IFF(yr=2021,PWSID,NULL)) s21,
  COUNT(DISTINCT IFF(yr=2022,PWSID,NULL)) s22, COUNT(DISTINCT IFF(yr=2023,PWSID,NULL)) s23, COUNT(DISTINCT IFF(yr=2024,PWSID,NULL)) s24,
  COUNT(DISTINCT IFF(yr=2025,PWSID,NULL)) s25, COUNT(DISTINCT IFF(yr=2026,PWSID,NULL)) s26,
  MAX(VISIT_DATE) last_visit, MEDIAN(DATEDIFF(day, VISIT_DATE, FIRST_REPORTED_DATE)) med_lag_days,
  APPROX_PERCENTILE(DATEDIFF(day, VISIT_DATE, FIRST_REPORTED_DATE), 0.9) p90_lag_days,
  (SELECT COUNT(*) FROM b b2 WHERE IFF(b2.ag IN ('CA','NJ','WA','OR','MI','NY','TN','TX'), b2.ag, 'other') = IFF(v.ag IN ('CA','NJ','WA','OR','MI','NY','TN','TX'), v.ag, 'other')) big_sys
FROM v GROUP BY 1 ORDER BY 1;

-- [g6-L3-3 SDWA: the 117 by year of last sanitary survey; are they still reporting lead samples (alive check)]
WITH sv AS (SELECT PWSID, MAX(IFF(VISIT_REASON_CODE IN ('SNSV','SNSP','SNSF'), VISIT_DATE, NULL)) last_s, MAX(VISIT_DATE) last_any,
                   MAX(LAST_REPORTED_DATE) last_rep_any
            FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_SDWA_SDWA_SITE_VISITS WHERE VISIT_DATE >= '1950-01-01' GROUP BY 1),
lcr AS (SELECT PWSID, MAX(SAR_FIRST_REPORTED_DATE) lcr_rep FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_SDWA_SDWA_LCR_SAMPLES WHERE SAR_FIRST_REPORTED_DATE >= '2023-01-01' GROUP BY 1),
p AS (SELECT PWSID, PRIMACY_AGENCY_CODE ag, POPULATION_SERVED_COUNT pop, SUBMISSIONYEARQUARTER sq
      FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_SDWA_SDWA_PUB_WATER_SYSTEMS WHERE PWS_ACTIVITY_CODE='A' AND PWS_TYPE_CODE='CWS' AND POPULATION_SERVED_COUNT >= 10000),
x AS (SELECT p.*, sv.last_s, sv.last_any, lcr.lcr_rep FROM p LEFT JOIN sv USING (PWSID) LEFT JOIN lcr USING (PWSID) WHERE COALESCE(sv.last_s,'1900-01-01') < '2021-07-01')
SELECT YEAR(last_s) last_survey_year, COUNT(*) sys, SUM(pop) pop,
  SUM(IFF(ag='CA',1,0)) ca, SUM(IFF(ag='NJ',1,0)) nj, SUM(IFF(ag NOT IN ('CA','NJ'),1,0)) other,
  SUM(IFF(lcr_rep IS NOT NULL,1,0)) lcr_reported_since_2023, MIN(sq) min_sq, MAX(sq) max_sq
FROM x GROUP BY 1 ORDER BY 1;

-- [g6-L1-1 RCRA: EPA CEIs that found violations, paired state CEIs within 730 days, split by same-day, state-before, state-after]
WITH ev AS (
  SELECT ID_NUMBER, ACTIVITY_LOCATION st, EVALUATION_START_DATE dt, EVALUATION_AGENCY ag, MAX(IFF(FOUND_VIOLATION = 'Y',1,0)) y
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_RCRA_EVALUATIONS
  WHERE EVALUATION_TYPE = 'CEI' AND EVALUATION_START_DATE BETWEEN '2013-01-01' AND '2025-12-31'
    AND EVALUATION_AGENCY IN ('S','E') AND FOUND_VIOLATION IN ('Y','N')
  GROUP BY 1,2,3,4),
e AS (SELECT * FROM ev WHERE ag = 'E' AND dt >= '2015-01-01' AND y = 1),
s AS (SELECT * FROM ev WHERE ag = 'S'),
pr AS (
  SELECT e.st, e.ID_NUMBER, e.dt edt, s.dt sdt, s.y sy, DATEDIFF(day, e.dt, s.dt) gap
  FROM e JOIN s ON s.ID_NUMBER = e.ID_NUMBER AND ABS(DATEDIFF(day, s.dt, e.dt)) BETWEEN 0 AND 730)
SELECT IFF(st IN ('IL','NJ','PA','NC','CA','KY','WI'), st, 'other') grp,
  COUNT(DISTINCT ID_NUMBER||edt) epa_found_insp,
  COUNT(IFF(gap = 0,1,NULL)) same_day, ROUND(100*AVG(IFF(gap = 0, sy, NULL)),1) same_day_y,
  COUNT(IFF(gap BETWEEN -730 AND -1,1,NULL)) state_before, ROUND(100*AVG(IFF(gap BETWEEN -730 AND -1, sy, NULL)),1) before_y,
  COUNT(IFF(gap BETWEEN 1 AND 30,1,NULL)) after_1_30, ROUND(100*AVG(IFF(gap BETWEEN 1 AND 30, sy, NULL)),1) after_1_30_y,
  COUNT(IFF(gap BETWEEN 31 AND 730,1,NULL)) after_31_730, ROUND(100*AVG(IFF(gap BETWEEN 31 AND 730, sy, NULL)),1) after_31_730_y,
  COUNT(IFF(gap BETWEEN -30 AND -1,1,NULL)) before_1_30, ROUND(100*AVG(IFF(gap BETWEEN -30 AND -1, sy, NULL)),1) before_1_30_y
FROM pr GROUP BY ROLLUP(1) ORDER BY 1;

-- [g6-L1-2 RCRA: deep's 1-730 day pairs; distinct sites, control (EPA clean), state baseline, EPA enforcement within 1 year]
WITH ev AS (
  SELECT ID_NUMBER, ACTIVITY_LOCATION st, EVALUATION_START_DATE dt, EVALUATION_AGENCY ag, MAX(IFF(FOUND_VIOLATION = 'Y',1,0)) y
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_RCRA_EVALUATIONS
  WHERE EVALUATION_TYPE = 'CEI' AND EVALUATION_START_DATE BETWEEN '2013-01-01' AND '2025-12-31'
    AND EVALUATION_AGENCY IN ('S','E') AND FOUND_VIOLATION IN ('Y','N')
  GROUP BY 1,2,3,4),
e AS (SELECT * FROM ev WHERE ag = 'E' AND dt >= '2015-01-01'),
s AS (SELECT * FROM ev WHERE ag = 'S'),
pr AS (
  SELECT e.st, e.ID_NUMBER, e.dt edt, e.y ey, AVG(s.y) sy, COUNT(*) ns
  FROM e JOIN s ON s.ID_NUMBER = e.ID_NUMBER AND ABS(DATEDIFF(day, s.dt, e.dt)) BETWEEN 1 AND 730
  GROUP BY 1,2,3,4),
enf AS (SELECT ID_NUMBER, ENFORCEMENT_ACTION_DATE edate, ENFORCEMENT_AGENCY eag, ENFORCEMENT_TYPE et FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_RCRA_ENFORCEMENTS
        WHERE ENFORCEMENT_ACTION_DATE >= '2015-01-01'),
pe AS (SELECT pr.*, MAX(IFF(enf.eag = 'E' AND enf.edate BETWEEN pr.edt AND DATEADD(day,365,pr.edt),1,0)) epa_enf_1y,
              MAX(IFF(enf.eag = 'E' AND enf.edate BETWEEN pr.edt AND DATEADD(day,365,pr.edt) AND enf.et >= '200',1,0)) epa_formal_1y
       FROM pr LEFT JOIN enf ON enf.ID_NUMBER = pr.ID_NUMBER GROUP BY 1,2,3,4,5,6),
sb AS (SELECT st, ROUND(100*AVG(y),1) state_base FROM ev WHERE ag = 'S' AND dt >= '2015-01-01' GROUP BY 1),
top AS (SELECT st, ID_NUMBER, COUNT(*) k FROM pr WHERE ey = 1 GROUP BY 1,2)
SELECT COALESCE(pe.st,'ALL') st,
  COUNT(IFF(ey=1,1,NULL)) epa_found, COUNT(DISTINCT IFF(ey=1,pe.ID_NUMBER,NULL)) epa_found_sites,
  ROUND(100*AVG(IFF(ey=1,sy,NULL)),1) state_y_where_epa_found,
  COUNT(IFF(ey=0,1,NULL)) epa_clean, ROUND(100*AVG(IFF(ey=0,sy,NULL)),1) state_y_where_epa_clean,
  MAX(sb.state_base) state_all_cei_base,
  ROUND(100*AVG(IFF(ey=1,epa_enf_1y,NULL)),1) epa_enf_within_1y_pct,
  ROUND(100*AVG(IFF(ey=1,epa_formal_1y,NULL)),1) epa_formal_code200plus_pct,
  (SELECT MAX(k) FROM top WHERE top.st = pe.st) max_insp_one_site
FROM pe LEFT JOIN sb ON sb.st = pe.st
WHERE pe.st IN ('IL','NJ','PA','NC','CA','KY','MD','WI','NE','WA','SC','TX')
GROUP BY ROLLUP(pe.st) ORDER BY state_y_where_epa_found;

-- [g6-L2-1 NPDES WV: mines vs sewer vs other, chronic20, formal actions by agency and era, violations per bad quarter]
WITH q AS (
  SELECT NPDES_ID, COUNT(DISTINCT YEARQTR) qtrs, COUNT(DISTINCT IFF(TRY_TO_NUMBER(NUME90_Q) > 0, YEARQTR, NULL)) eff_q, SUM(TRY_TO_NUMBER(NUME90_Q)) eff_n
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_NPDES_NPDES_QNCR_HISTORY
  WHERE TRY_TO_NUMBER(YEARQTR) BETWEEN 20161 AND 20254 AND LEFT(NPDES_ID,2) = 'WV' GROUP BY 1),
fe AS (
  SELECT NPDES_ID, COUNT(*) fe_all, MAX(SETTLEMENT_ENTERED_DATE) last_fe,
    COUNT(IFF(SETTLEMENT_ENTERED_DATE >= '2016-01-01',1,NULL)) fe_win,
    COUNT(IFF(SETTLEMENT_ENTERED_DATE >= '2016-01-01' AND AGENCY ILIKE 'S%',1,NULL)) fe_win_state,
    COUNT(IFF(SETTLEMENT_ENTERED_DATE >= '2016-01-01' AND AGENCY ILIKE 'E%',1,NULL)) fe_win_epa,
    COUNT(IFF(SETTLEMENT_ENTERED_DATE BETWEEN '2010-01-01' AND '2015-12-31',1,NULL)) fe_1015,
    COUNT(IFF(SETTLEMENT_ENTERED_DATE IS NULL,1,NULL)) fe_null,
    LISTAGG(DISTINCT AGENCY, ',') ags
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_NPDES_NPDES_FORMAL_ENFORCEMENT_ACTIONS WHERE LEFT(NPDES_ID,2) = 'WV' GROUP BY 1),
j AS (
  SELECT q.*, COALESCE(fe.fe_all,0) fe_all, COALESCE(fe.fe_win,0) fe_win, COALESCE(fe.fe_win_state,0) fws, COALESCE(fe.fe_win_epa,0) fwe,
    COALESCE(fe.fe_1015,0) f1015, COALESCE(fe.fe_null,0) fnull, fe.ags, fac.FACILITY_TYPE_CODE ft,
    CASE WHEN fac.FACILITY_NAME ILIKE ANY ('%MINE%','%MINING%','%COAL%','%SURFACE%','%PREP PLANT%','%REFUSE%') THEN 'mine'
         WHEN fac.FACILITY_TYPE_CODE IN ('MWD','CTG','CNG') THEN 'public sewer' ELSE 'other' END kind
  FROM q LEFT JOIN fe ON fe.NPDES_ID = q.NPDES_ID
  LEFT JOIN LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_NPDES_ICIS_FACILITIES fac ON fac.NPDES_ID = q.NPDES_ID
  WHERE q.qtrs >= 36)
SELECT kind, IFF(eff_q >= 20,'chronic20','not') grp, COUNT(*) permits,
  SUM(IFF(fe_win > 0,1,0)) formal_since16, SUM(IFF(fws > 0,1,0)) state_formal_since16, SUM(IFF(fwe > 0,1,0)) epa_formal_since16,
  SUM(IFF(fe_win = 0 AND f1015 > 0,1,0)) only_2010_15_formal, SUM(IFF(fe_all = 0,1,0)) never_formal, SUM(IFF(fe_win = 0 AND fnull > 0,1,0)) null_dated_only,
  ROUND(AVG(eff_n / NULLIF(eff_q,0)),1) viol_per_bad_qtr, LISTAGG(DISTINCT ft, ',') ftypes, LISTAGG(DISTINCT ags, ',') agencies
FROM j GROUP BY 1,2 ORDER BY 1,2;

-- [g6-L2-2 NPDES: the 553 worst and 152 no-formal by state, against each state's own formal and informal action rates]
WITH q AS (
  SELECT NPDES_ID, COUNT(DISTINCT YEARQTR) qtrs, COUNT(DISTINCT IFF(TRY_TO_NUMBER(NUME90_Q) > 0, YEARQTR, NULL)) eff_q
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_NPDES_NPDES_QNCR_HISTORY
  WHERE TRY_TO_NUMBER(YEARQTR) BETWEEN 20161 AND 20254 GROUP BY 1 HAVING COUNT(DISTINCT YEARQTR) >= 36),
fe AS (SELECT NPDES_ID, COUNT(*) fe_all, COUNT(IFF(SETTLEMENT_ENTERED_DATE >= '2016-01-01',1,NULL)) fe_win
       FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_NPDES_NPDES_FORMAL_ENFORCEMENT_ACTIONS GROUP BY 1),
ie AS (SELECT NPDES_ID, COUNT(IFF(ACHIEVED_DATE BETWEEN '2016-01-01' AND '2025-12-31',1,NULL)) ie_win
       FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_NPDES_NPDES_INFORMAL_ENFORCEMENT_ACTIONS GROUP BY 1),
j AS (SELECT q.*, LEFT(q.NPDES_ID,2) st, COALESCE(fe.fe_all,0) fe_all, COALESCE(fe.fe_win,0) fe_win, COALESCE(ie.ie_win,0) ie_win
      FROM q LEFT JOIN fe ON fe.NPDES_ID = q.NPDES_ID LEFT JOIN ie ON ie.NPDES_ID = q.NPDES_ID),
sts AS (SELECT st, COUNT(*) permits36, ROUND(100*AVG(IFF(fe_win > 0,1,0)),1) st_formal_pct_all, ROUND(100*AVG(IFF(ie_win > 0,1,0)),1) st_informal_pct_all,
          ROUND(100*AVG(IFF(eff_q >= 20, IFF(fe_win > 0,1,0), NULL)),1) st_formal_pct_chronic20,
          COUNT(IFF(eff_q >= 36,1,NULL)) worst, COUNT(IFF(eff_q >= 36 AND fe_win = 0,1,NULL)) worst_no_formal,
          COUNT(IFF(eff_q >= 36 AND fe_win = 0 AND ie_win = 0,1,NULL)) worst_no_action
        FROM j GROUP BY 1)
SELECT * FROM sts WHERE worst_no_formal > 0 OR st IN ('WV') 
UNION ALL
SELECT 'ALL', SUM(permits36), NULL, NULL, NULL, SUM(worst), SUM(worst_no_formal), SUM(worst_no_action) FROM sts
ORDER BY worst_no_formal DESC;

-- [g6-L2-3 NPDES WV chronic mines: state-held (reclamation/forfeiture) names, still violating 2024-25, top no-formal list]
WITH q AS (
  SELECT NPDES_ID, COUNT(DISTINCT YEARQTR) qtrs, COUNT(DISTINCT IFF(TRY_TO_NUMBER(NUME90_Q) > 0, YEARQTR, NULL)) eff_q, SUM(TRY_TO_NUMBER(NUME90_Q)) eff_n,
    COUNT(DISTINCT IFF(TRY_TO_NUMBER(YEARQTR) >= 20241 AND TRY_TO_NUMBER(NUME90_Q) > 0, YEARQTR, NULL)) eff_q_24_25
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_NPDES_NPDES_QNCR_HISTORY
  WHERE TRY_TO_NUMBER(YEARQTR) BETWEEN 20161 AND 20254 AND LEFT(NPDES_ID,2) = 'WV' GROUP BY 1 HAVING COUNT(DISTINCT YEARQTR) >= 36),
fe AS (SELECT NPDES_ID, COUNT(IFF(SETTLEMENT_ENTERED_DATE >= '2016-01-01',1,NULL)) fe_win, COUNT(*) fe_all FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_NPDES_NPDES_FORMAL_ENFORCEMENT_ACTIONS WHERE LEFT(NPDES_ID,2)='WV' GROUP BY 1),
j AS (SELECT q.*, COALESCE(fe.fe_win,0) fe_win, COALESCE(fe.fe_all,0) fe_all, fac.FACILITY_NAME nm, fac.CITY, fac.FACILITY_TYPE_CODE ft
      FROM q LEFT JOIN fe ON fe.NPDES_ID = q.NPDES_ID
      JOIN LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_NPDES_ICIS_FACILITIES fac ON fac.NPDES_ID = q.NPDES_ID
      WHERE q.eff_q >= 20 AND fac.FACILITY_NAME ILIKE ANY ('%MINE%','%MINING%','%COAL%','%SURFACE%','%PREP PLANT%','%REFUSE%'))
SELECT 'SUM' k, IFF(nm ILIKE ANY ('%RECLAMATION%','%FORFEIT%','%WVDEP%','%DEP %','%DEPARTMENT OF ENV%'),'state-held name','other') grp,
  COUNT(*) n, SUM(IFF(fe_win = 0,1,0)) no_formal, SUM(IFF(eff_q_24_25 > 0,1,0)) still_violating_24_25, SUM(eff_n) eff_n, NULL nm, NULL ft
FROM j GROUP BY 2
UNION ALL
SELECT * FROM (SELECT 'ROW', NPDES_ID, eff_q, fe_win, eff_q_24_25, eff_n, nm||' / '||CITY, ft FROM j WHERE fe_win = 0 ORDER BY eff_n DESC LIMIT 25)
ORDER BY 1 DESC, 6 DESC;
