{{ config(tags=['spine_generated']) }}

-- GRAIN: one row per facility (CCN is unique)
-- SPINE_ENTITY: facility  (natural_key: CMS_CERTIFICATION_NUMBER_CCN)
-- Generated by scripts/generate_staging_models.py from SOURCE_REGISTRY -- deterministic,
-- no LLM.
-- CASTS: 50 of 71 columns, from landing_column_profile_2026-09-19.tsv. A column is cast only
-- when every filled value in the sample parsed. try_ casts: a value that does not
-- parse reads NULL. The natural key and join-key columns stay TEXT.
--   number_of_certified_beds: integer
--   average_number_of_residents_per_day: float
--   date_first_approved_to_provide_medicare_and_medicaid_services: timestamp
--   chain_id: integer
--   number_of_facilities_in_chain: integer
--   chain_average_overall_5_star_rating: float
--   chain_average_health_inspection_rating: float
--   chain_average_staffing_rating: float
--   chain_average_qm_rating: float
--   overall_rating: integer
--   health_inspection_rating: integer
--   staffing_rating: integer
--   qm_rating: integer
--   reported_nurse_aide_staffing_hours_per_resident_per_day: float
--   expected_nurse_aide_staffing_hours_per_resident_day: float
--   deviation_from_expected_nurse_aide_staffing: float
--   reported_lpn_staffing_hours_per_resident_per_day: float
--   reported_rn_staffing_hours_per_resident_per_day: float
--   expected_rn_staffing_hours_per_resident_per_day: float
--   deviation_from_expected_rn_staffing: float
--   reported_licensed_staffing_hours_per_resident_per_day: float
--   reported_total_nurse_staffing_hours_per_resident_per_day: float
--   expected_total_nurse_staffing_hours_per_resident_day: float
--   deviation_from_expected_total_nurse_hours_per_resident_per_day: float
--   total_number_of_nurse_staff_hours_per_resident_per_day_on_the_weekend: float
--   registered_nurse_hours_per_resident_per_day_on_the_weekend: float
--   reported_physical_therapist_staffing_hours_per_resident_per_day: float
--   total_nursing_staff_turnover: float
--   registered_nurse_turnover: float
--   number_of_administrators_who_have_left_the_nursing_home: integer
--   nursing_case_mix_index: float
--   nursing_case_mix_index_ratio: float
--   rating_cycle_1_standard_survey_health_date: timestamp
--   rating_cycle_1_total_number_of_health_deficiencies: integer
--   rating_cycle_1_number_of_standard_health_deficiencies: integer
--   rating_cycle_1_number_of_complaint_health_deficiencies: integer
--   rating_cycle_1_number_of_health_revisits: integer
--   rating_cycle_2_standard_health_survey_date: timestamp
--   rating_cycle_2_3_total_number_of_health_deficiencies: integer
--   rating_cycle_2_number_of_standard_health_deficiencies: integer
--   rating_cycle_2_3_number_of_complaint_health_deficiencies: integer
--   rating_cycle_2_3_number_of_health_revisits: integer
--   number_of_facility_reported_incidents: integer
--   number_of_substantiated_complaints: integer
--   number_of_fines: integer
--   total_amount_of_fines_in_dollars: integer
--   number_of_payment_denials: integer
--   total_number_of_penalties: integer
--   cms_region_number: integer
--   processing_date: timestamp

with source as (

    select * from {{ source('ripple_raw', 'FED_NURSINGHOME411') }}
    qualify row_number() over (partition by "CMS_CERTIFICATION_NUMBER_CCN" order by _INGESTED_AT desc) = 1

),

renamed as (

    select
        {{ null_junk('"CMS_CERTIFICATION_NUMBER_CCN"') }} as cms_certification_number_ccn,
        {{ null_junk('"STATE"') }} as state,
        {{ null_junk('"PROVIDER_NAME"') }} as provider_name,
        {{ null_junk('"PROVIDER_ADDRESS"') }} as provider_address,
        {{ null_junk('"CITY_TOWN"') }} as city_town,
        {{ null_junk('"COUNTY_PARISH"') }} as county_parish,
        {{ null_junk('"OWNERSHIP_TYPE"') }} as ownership_type,
        {{ null_junk('"OWNERSHIP_TYPE_DETAIL"') }} as ownership_type_detail,
        {{ stg_int('"NUMBER_OF_CERTIFIED_BEDS"') }} as number_of_certified_beds,
        {{ stg_float('"AVERAGE_NUMBER_OF_RESIDENTS_PER_DAY"') }} as average_number_of_residents_per_day,
        {{ null_junk('"PROVIDER_TYPE"') }} as provider_type,
        {{ null_junk('"PROVIDER_RESIDES_IN_HOSPITAL"') }} as provider_resides_in_hospital,
        {{ stg_ts('"DATE_FIRST_APPROVED_TO_PROVIDE_MEDICARE_AND_MEDICAID_SERVICES"') }} as date_first_approved_to_provide_medicare_and_medicaid_services,
        {{ null_junk('"CHAIN_NAME"') }} as chain_name,
        {{ stg_int('"CHAIN_ID"') }} as chain_id,
        {{ stg_int('"NUMBER_OF_FACILITIES_IN_CHAIN"') }} as number_of_facilities_in_chain,
        {{ stg_float('"CHAIN_AVERAGE_OVERALL_5_STAR_RATING"') }} as chain_average_overall_5_star_rating,
        {{ stg_float('"CHAIN_AVERAGE_HEALTH_INSPECTION_RATING"') }} as chain_average_health_inspection_rating,
        {{ stg_float('"CHAIN_AVERAGE_STAFFING_RATING"') }} as chain_average_staffing_rating,
        {{ stg_float('"CHAIN_AVERAGE_QM_RATING"') }} as chain_average_qm_rating,
        {{ null_junk('"CONTINUING_CARE_RETIREMENT_COMMUNITY"') }} as continuing_care_retirement_community,
        {{ null_junk('"SPECIAL_FOCUS_STATUS"') }} as special_focus_status,
        {{ null_junk('"ABUSE_ICON"') }} as abuse_icon,
        {{ null_junk('"PROBLEM_FACILITIES_SFFS_CANDIDATES_ONE_STAR"') }} as problem_facilities_sffs_candidates_one_star,
        {{ null_junk('"MOST_RECENT_HEALTH_INSPECTION_MORE_THAN_2_YEARS_AGO"') }} as most_recent_health_inspection_more_than_2_years_ago,
        {{ null_junk('"PROVIDER_CHANGED_OWNERSHIP_IN_LAST_12_MONTHS"') }} as provider_changed_ownership_in_last_12_months,
        {{ null_junk('"WITH_A_RESIDENT_AND_FAMILY_COUNCIL"') }} as with_a_resident_and_family_council,
        {{ stg_int('"OVERALL_RATING"') }} as overall_rating,
        {{ stg_int('"HEALTH_INSPECTION_RATING"') }} as health_inspection_rating,
        {{ stg_int('"STAFFING_RATING"') }} as staffing_rating,
        {{ stg_int('"QM_RATING"') }} as qm_rating,
        {{ stg_float('"REPORTED_NURSE_AIDE_STAFFING_HOURS_PER_RESIDENT_PER_DAY"') }} as reported_nurse_aide_staffing_hours_per_resident_per_day,
        {{ stg_float('"EXPECTED_NURSE_AIDE_STAFFING_HOURS_PER_RESIDENT_DAY"') }} as expected_nurse_aide_staffing_hours_per_resident_day,
        {{ stg_float('"DEVIATION_FROM_EXPECTED_NURSE_AIDE_STAFFING"') }} as deviation_from_expected_nurse_aide_staffing,
        {{ stg_float('"REPORTED_LPN_STAFFING_HOURS_PER_RESIDENT_PER_DAY"') }} as reported_lpn_staffing_hours_per_resident_per_day,
        {{ stg_float('"REPORTED_RN_STAFFING_HOURS_PER_RESIDENT_PER_DAY"') }} as reported_rn_staffing_hours_per_resident_per_day,
        {{ stg_float('"EXPECTED_RN_STAFFING_HOURS_PER_RESIDENT_PER_DAY"') }} as expected_rn_staffing_hours_per_resident_per_day,
        {{ stg_float('"DEVIATION_FROM_EXPECTED_RN_STAFFING"') }} as deviation_from_expected_rn_staffing,
        {{ stg_float('"REPORTED_LICENSED_STAFFING_HOURS_PER_RESIDENT_PER_DAY"') }} as reported_licensed_staffing_hours_per_resident_per_day,
        {{ stg_float('"REPORTED_TOTAL_NURSE_STAFFING_HOURS_PER_RESIDENT_PER_DAY"') }} as reported_total_nurse_staffing_hours_per_resident_per_day,
        {{ stg_float('"EXPECTED_TOTAL_NURSE_STAFFING_HOURS_PER_RESIDENT_DAY"') }} as expected_total_nurse_staffing_hours_per_resident_day,
        {{ stg_float('"DEVIATION_FROM_EXPECTED_TOTAL_NURSE_HOURS_PER_RESIDENT_PER_DAY"') }} as deviation_from_expected_total_nurse_hours_per_resident_per_day,
        {{ stg_float('"TOTAL_NUMBER_OF_NURSE_STAFF_HOURS_PER_RESIDENT_PER_DAY_ON_THE_WEEKEND"') }} as total_number_of_nurse_staff_hours_per_resident_per_day_on_the_weekend,
        {{ stg_float('"REGISTERED_NURSE_HOURS_PER_RESIDENT_PER_DAY_ON_THE_WEEKEND"') }} as registered_nurse_hours_per_resident_per_day_on_the_weekend,
        {{ stg_float('"REPORTED_PHYSICAL_THERAPIST_STAFFING_HOURS_PER_RESIDENT_PER_DAY"') }} as reported_physical_therapist_staffing_hours_per_resident_per_day,
        {{ stg_float('"TOTAL_NURSING_STAFF_TURNOVER"') }} as total_nursing_staff_turnover,
        {{ stg_float('"REGISTERED_NURSE_TURNOVER"') }} as registered_nurse_turnover,
        {{ stg_int('"NUMBER_OF_ADMINISTRATORS_WHO_HAVE_LEFT_THE_NURSING_HOME"') }} as number_of_administrators_who_have_left_the_nursing_home,
        {{ stg_float('"NURSING_CASE_MIX_INDEX"') }} as nursing_case_mix_index,
        {{ stg_float('"NURSING_CASE_MIX_INDEX_RATIO"') }} as nursing_case_mix_index_ratio,
        {{ stg_ts('"RATING_CYCLE_1_STANDARD_SURVEY_HEALTH_DATE"') }} as rating_cycle_1_standard_survey_health_date,
        {{ stg_int('"RATING_CYCLE_1_TOTAL_NUMBER_OF_HEALTH_DEFICIENCIES"') }} as rating_cycle_1_total_number_of_health_deficiencies,
        {{ stg_int('"RATING_CYCLE_1_NUMBER_OF_STANDARD_HEALTH_DEFICIENCIES"') }} as rating_cycle_1_number_of_standard_health_deficiencies,
        {{ stg_int('"RATING_CYCLE_1_NUMBER_OF_COMPLAINT_HEALTH_DEFICIENCIES"') }} as rating_cycle_1_number_of_complaint_health_deficiencies,
        {{ stg_int('"RATING_CYCLE_1_NUMBER_OF_HEALTH_REVISITS"') }} as rating_cycle_1_number_of_health_revisits,
        {{ stg_ts('"RATING_CYCLE_2_STANDARD_HEALTH_SURVEY_DATE"') }} as rating_cycle_2_standard_health_survey_date,
        {{ stg_int('"RATING_CYCLE_2_3_TOTAL_NUMBER_OF_HEALTH_DEFICIENCIES"') }} as rating_cycle_2_3_total_number_of_health_deficiencies,
        {{ stg_int('"RATING_CYCLE_2_NUMBER_OF_STANDARD_HEALTH_DEFICIENCIES"') }} as rating_cycle_2_number_of_standard_health_deficiencies,
        {{ stg_int('"RATING_CYCLE_2_3_NUMBER_OF_COMPLAINT_HEALTH_DEFICIENCIES"') }} as rating_cycle_2_3_number_of_complaint_health_deficiencies,
        {{ stg_int('"RATING_CYCLE_2_3_NUMBER_OF_HEALTH_REVISITS"') }} as rating_cycle_2_3_number_of_health_revisits,
        {{ stg_int('"NUMBER_OF_FACILITY_REPORTED_INCIDENTS"') }} as number_of_facility_reported_incidents,
        {{ stg_int('"NUMBER_OF_SUBSTANTIATED_COMPLAINTS"') }} as number_of_substantiated_complaints,
        {{ stg_int('"NUMBER_OF_FINES"') }} as number_of_fines,
        {{ stg_int('"TOTAL_AMOUNT_OF_FINES_IN_DOLLARS"') }} as total_amount_of_fines_in_dollars,
        {{ stg_int('"NUMBER_OF_PAYMENT_DENIALS"') }} as number_of_payment_denials,
        {{ stg_int('"TOTAL_NUMBER_OF_PENALTIES"') }} as total_number_of_penalties,
        {{ null_junk('"LOCATION"') }} as location,
        {{ null_junk('"LATITUDE"') }} as latitude,
        {{ null_junk('"LONGITUDE"') }} as longitude,
        {{ stg_int('"CMS_REGION_NUMBER"') }} as cms_region_number,
        {{ stg_ts('"PROCESSING_DATE"') }} as processing_date,
        _INGESTED_AT as _loaded_at,
        'https://nursinghome411.org/data/ratings-info/' as _source_url,
    'ENT_' || LEFT(MD5('CCN' || '|' || (CASE WHEN LENGTH(UPPER(REGEXP_REPLACE(TO_VARCHAR("CMS_CERTIFICATION_NUMBER_CCN"), '[^0-9A-Za-z]', ''))) = 0 OR LENGTH(UPPER(REGEXP_REPLACE(TO_VARCHAR("CMS_CERTIFICATION_NUMBER_CCN"), '[^0-9A-Za-z]', ''))) > 6 OR NOT REGEXP_LIKE(UPPER(REGEXP_REPLACE(TO_VARCHAR("CMS_CERTIFICATION_NUMBER_CCN"), '[^0-9A-Za-z]', '')), '^[0-9]+$') OR LPAD(UPPER(REGEXP_REPLACE(TO_VARCHAR("CMS_CERTIFICATION_NUMBER_CCN"), '[^0-9A-Za-z]', '')), 6, '0') = REPEAT('0', 6) OR (LENGTH(UPPER(REGEXP_REPLACE(TO_VARCHAR("CMS_CERTIFICATION_NUMBER_CCN"), '[^0-9A-Za-z]', ''))) >= 4 AND UPPER(REGEXP_REPLACE(TO_VARCHAR("CMS_CERTIFICATION_NUMBER_CCN"), '[^0-9A-Za-z]', '')) = REPEAT(LEFT(UPPER(REGEXP_REPLACE(TO_VARCHAR("CMS_CERTIFICATION_NUMBER_CCN"), '[^0-9A-Za-z]', '')), 1), LENGTH(UPPER(REGEXP_REPLACE(TO_VARCHAR("CMS_CERTIFICATION_NUMBER_CCN"), '[^0-9A-Za-z]', ''))))) OR LPAD(UPPER(REGEXP_REPLACE(TO_VARCHAR("CMS_CERTIFICATION_NUMBER_CCN"), '[^0-9A-Za-z]', '')), 6, '0') = REPEAT(LEFT(LPAD(UPPER(REGEXP_REPLACE(TO_VARCHAR("CMS_CERTIFICATION_NUMBER_CCN"), '[^0-9A-Za-z]', '')), 6, '0'), 1), 6) OR UPPER(REGEXP_REPLACE(TO_VARCHAR("CMS_CERTIFICATION_NUMBER_CCN"), '[^0-9A-Za-z]', '')) IN ('123456789', '987654321', '1234567890', '0987654321', '12345678', '87654321', '123456', '654321') OR LPAD(UPPER(REGEXP_REPLACE(TO_VARCHAR("CMS_CERTIFICATION_NUMBER_CCN"), '[^0-9A-Za-z]', '')), 6, '0') IN ('123456789', '987654321', '1234567890', '0987654321', '12345678', '87654321', '123456', '654321') THEN NULL ELSE LPAD(UPPER(REGEXP_REPLACE(TO_VARCHAR("CMS_CERTIFICATION_NUMBER_CCN"), '[^0-9A-Za-z]', '')), 6, '0') END)), 16) as spine_entity_id  -- joins LIBRARY_META."CONNECT".ENTITY_GOLDEN.ENTITY_ID

    from source

)

select * from renamed
