{{ config(materialized='view') }}
-- GRAIN: one row = one credit union's FS220 financial statement for the 2026-03 cycle (cu_number unique).
-- PROVENANCE: NCUA Call Report quarterly download, FS220.txt (core financials; ACCT_010 = total assets).
-- Loaded 2026-08-11 to replace the broken FED_NCUA_CALL_REPORTS table (which held a data dictionary).
-- CYCLE_DATE is 'M/D/YYYY H:MI:SS' 24-hour; UPDATE_DATE is 12-hour with AM/PM; explicit formats on
-- purpose -- a bare try_to_date is the epoch-date bug. All ACCT_* columns are numeric strings.

with

source as (
    select * from {{ source('ripple_raw', 'FED_NCUA_CALL_REPORTS_FS220') }}
),

renamed as (

    select
        nullif(trim(CU_NUMBER), '')                                    as cu_number,
        coalesce(
            try_to_timestamp(nullif(trim(CYCLE_DATE), ''), 'MM/DD/YYYY HH24:MI:SS'),
            try_to_timestamp(nullif(trim(CYCLE_DATE), ''), 'MM/DD/YYYY HH12:MI:SS AM')
        )::date                                                        as cycle_date,
        try_to_number(nullif(trim(JOIN_NUMBER), ''))                   as join_number,
        coalesce(
            try_to_timestamp(nullif(trim(UPDATE_DATE), ''), 'MM/DD/YYYY HH12:MI:SS AM'),
            try_to_timestamp(nullif(trim(UPDATE_DATE), ''), 'MM/DD/YYYY HH24:MI:SS')
        )                                                              as update_date,
        try_to_number(nullif(trim(ACCT_007), ''))                      as acct_007,
        try_to_number(nullif(trim(ACCT_008), ''))                      as acct_008,
        try_to_number(nullif(trim(ACCT_009), ''))                      as acct_009,
        try_to_number(nullif(trim(ACCT_010), ''))                      as acct_010,
        try_to_number(nullif(trim(ACCT_011C), ''))                     as acct_011c,
        try_to_number(nullif(trim(ACCT_013), ''))                      as acct_013,
        try_to_number(nullif(trim(ACCT_018), ''))                      as acct_018,
        try_to_number(nullif(trim(ACCT_019), ''))                      as acct_019,
        try_to_number(nullif(trim(ACCT_021B), ''))                     as acct_021b,
        try_to_number(nullif(trim(ACCT_022B), ''))                     as acct_022b,
        try_to_number(nullif(trim(ACCT_023B), ''))                     as acct_023b,
        try_to_number(nullif(trim(ACCT_025A), ''))                     as acct_025a,
        try_to_number(nullif(trim(ACCT_025B), ''))                     as acct_025b,
        try_to_number(nullif(trim(ACCT_031A), ''))                     as acct_031a,
        try_to_number(nullif(trim(ACCT_031B), ''))                     as acct_031b,
        try_to_number(nullif(trim(ACCT_041B), ''))                     as acct_041b,
        try_to_number(nullif(trim(ACCT_042), ''))                      as acct_042,
        try_to_number(nullif(trim(ACCT_058C), ''))                     as acct_058c,
        try_to_number(nullif(trim(ACCT_065), ''))                      as acct_065,
        try_to_number(nullif(trim(ACCT_067), ''))                      as acct_067,
        try_to_number(nullif(trim(ACCT_068), ''))                      as acct_068,
        try_to_number(nullif(trim(ACCT_069), ''))                      as acct_069,
        try_to_number(nullif(trim(ACCT_080), ''))                      as acct_080,
        try_to_number(nullif(trim(ACCT_083), ''))                      as acct_083,
        try_to_number(nullif(trim(ACCT_084), ''))                      as acct_084,
        try_to_number(nullif(trim(ACCT_100), ''))                      as acct_100,
        try_to_number(nullif(trim(ACCT_300), ''))                      as acct_300,
        try_to_number(nullif(trim(ACCT_340), ''))                      as acct_340,
        try_to_number(nullif(trim(ACCT_380), ''))                      as acct_380,
        try_to_number(nullif(trim(ACCT_386), ''))                      as acct_386,
        try_to_number(nullif(trim(ACCT_387), ''))                      as acct_387,
        try_to_number(nullif(trim(ACCT_388), ''))                      as acct_388,
        try_to_number(nullif(trim(ACCT_392), ''))                      as acct_392,
        try_to_number(nullif(trim(ACCT_400), ''))                      as acct_400,
        try_to_number(nullif(trim(ACCT_457), ''))                      as acct_457,
        try_to_number(nullif(trim(ACCT_521), ''))                      as acct_521,
        try_to_number(nullif(trim(ACCT_522), ''))                      as acct_522,
        try_to_number(nullif(trim(ACCT_523), ''))                      as acct_523,
        try_to_number(nullif(trim(ACCT_524), ''))                      as acct_524,
        try_to_number(nullif(trim(ACCT_550), ''))                      as acct_550,
        try_to_number(nullif(trim(ACCT_551), ''))                      as acct_551,
        try_to_number(nullif(trim(ACCT_552), ''))                      as acct_552,
        try_to_number(nullif(trim(ACCT_562), ''))                      as acct_562,
        try_to_number(nullif(trim(ACCT_563), ''))                      as acct_563,
        try_to_number(nullif(trim(ACCT_602), ''))                      as acct_602,
        try_to_number(nullif(trim(ACCT_630), ''))                      as acct_630,
        try_to_number(nullif(trim(ACCT_652A), ''))                     as acct_652a,
        try_to_number(nullif(trim(ACCT_652B1), ''))                    as acct_652b1,
        try_to_number(nullif(trim(ACCT_652B2), ''))                    as acct_652b2,
        try_to_number(nullif(trim(ACCT_655A), ''))                     as acct_655a,
        try_to_number(nullif(trim(ACCT_655B1), ''))                    as acct_655b1,
        try_to_number(nullif(trim(ACCT_655B2), ''))                    as acct_655b2,
        try_to_number(nullif(trim(ACCT_656C), ''))                     as acct_656c,
        try_to_number(nullif(trim(ACCT_657), ''))                      as acct_657,
        try_to_number(nullif(trim(ACCT_658), ''))                      as acct_658,
        try_to_number(nullif(trim(ACCT_662), ''))                      as acct_662,
        try_to_number(nullif(trim(ACCT_668), ''))                      as acct_668,
        try_to_number(nullif(trim(ACCT_671), ''))                      as acct_671,
        try_to_number(nullif(trim(ACCT_672A), ''))                     as acct_672a,
        try_to_number(nullif(trim(ACCT_672B1), ''))                    as acct_672b1,
        try_to_number(nullif(trim(ACCT_672B2), ''))                    as acct_672b2,
        try_to_number(nullif(trim(ACCT_703), ''))                      as acct_703,
        try_to_number(nullif(trim(ACCT_704), ''))                      as acct_704,
        try_to_number(nullif(trim(ACCT_705), ''))                      as acct_705,
        try_to_number(nullif(trim(ACCT_706), ''))                      as acct_706,
        try_to_number(nullif(trim(ACCT_707), ''))                      as acct_707,
        try_to_number(nullif(trim(ACCT_708), ''))                      as acct_708,
        try_to_number(nullif(trim(ACCT_710), ''))                      as acct_710,
        try_to_number(nullif(trim(ACCT_712), ''))                      as acct_712,
        try_to_number(nullif(trim(ACCT_713), ''))                      as acct_713,
        try_to_number(nullif(trim(ACCT_714), ''))                      as acct_714,
        try_to_number(nullif(trim(ACCT_715), ''))                      as acct_715,
        try_to_number(nullif(trim(ACCT_716), ''))                      as acct_716,
        try_to_number(nullif(trim(ACCT_718), ''))                      as acct_718,
        try_to_number(nullif(trim(ACCT_719), ''))                      as acct_719,
        try_to_number(nullif(trim(ACCT_720), ''))                      as acct_720,
        try_to_number(nullif(trim(ACCT_721), ''))                      as acct_721,
        try_to_number(nullif(trim(ACCT_722), ''))                      as acct_722,
        try_to_number(nullif(trim(ACCT_723), ''))                      as acct_723,
        try_to_number(nullif(trim(ACCT_724), ''))                      as acct_724,
        try_to_number(nullif(trim(ACCT_730), ''))                      as acct_730,
        try_to_number(nullif(trim(ACCT_741A), ''))                     as acct_741a,
        try_to_number(nullif(trim(ACCT_741B1), ''))                    as acct_741b1,
        try_to_number(nullif(trim(ACCT_741B2), ''))                    as acct_741b2,
        try_to_number(nullif(trim(ACCT_742A), ''))                     as acct_742a,
        try_to_number(nullif(trim(ACCT_742B1), ''))                    as acct_742b1,
        try_to_number(nullif(trim(ACCT_742B2), ''))                    as acct_742b2,
        try_to_number(nullif(trim(ACCT_746A), ''))                     as acct_746a,
        try_to_number(nullif(trim(ACCT_746B1), ''))                    as acct_746b1,
        try_to_number(nullif(trim(ACCT_746B2), ''))                    as acct_746b2,
        try_to_number(nullif(trim(ACCT_749), ''))                      as acct_749,
        try_to_number(nullif(trim(ACCT_750A), ''))                     as acct_750a,
        try_to_number(nullif(trim(ACCT_750B1), ''))                    as acct_750b1,
        try_to_number(nullif(trim(ACCT_750B2), ''))                    as acct_750b2,
        try_to_number(nullif(trim(ACCT_751), ''))                      as acct_751,
        try_to_number(nullif(trim(ACCT_755), ''))                      as acct_755,
        try_to_number(nullif(trim(ACCT_760C), ''))                     as acct_760c,
        try_to_number(nullif(trim(ACCT_761C), ''))                     as acct_761c,
        try_to_number(nullif(trim(ACCT_771), ''))                      as acct_771,
        try_to_number(nullif(trim(ACCT_775), ''))                      as acct_775,
        try_to_number(nullif(trim(ACCT_794), ''))                      as acct_794,
        try_to_number(nullif(trim(ACCT_798), ''))                      as acct_798,
        try_to_number(nullif(trim(ACCT_799A), ''))                     as acct_799a,
        try_to_number(nullif(trim(ACCT_799B1), ''))                    as acct_799b1,
        try_to_number(nullif(trim(ACCT_799B2), ''))                    as acct_799b2,
        try_to_number(nullif(trim(ACCT_825), ''))                      as acct_825,
        try_to_number(nullif(trim(ACCT_860C), ''))                     as acct_860c,
        try_to_number(nullif(trim(ACCT_880), ''))                      as acct_880,
        try_to_number(nullif(trim(ACCT_902), ''))                      as acct_902,
        try_to_number(nullif(trim(ACCT_906A), ''))                     as acct_906a,
        try_to_number(nullif(trim(ACCT_908A), ''))                     as acct_908a,
        try_to_number(nullif(trim(ACCT_908C), ''))                     as acct_908c,
        try_to_number(nullif(trim(ACCT_911), ''))                      as acct_911,
        try_to_number(nullif(trim(ACCT_931), ''))                      as acct_931,
        try_to_number(nullif(trim(ACCT_940), ''))                      as acct_940,
        try_to_number(nullif(trim(ACCT_959), ''))                      as acct_959,
        try_to_number(nullif(trim(ACCT_960), ''))                      as acct_960,
        try_to_number(nullif(trim(ACCT_968), ''))                      as acct_968,
        try_to_number(nullif(trim(ACCT_973), ''))                      as acct_973,
        try_to_number(nullif(trim(ACCT_975), ''))                      as acct_975,
        try_to_number(nullif(trim(ACCT_976), ''))                      as acct_976,
        try_to_number(nullif(trim(ACCT_991), ''))                      as acct_991,
        try_to_number(nullif(trim(ACCT_965A), ''))                     as acct_965a,
        try_to_number(nullif(trim(ACCT_965B), ''))                     as acct_965b,
        try_to_number(nullif(trim(ACCT_965C), ''))                     as acct_965c,
        try_to_number(nullif(trim(ACCT_965D), ''))                     as acct_965d,
        try_to_number(nullif(trim(ACCT_020A), ''))                     as acct_020a,
        try_to_number(nullif(trim(ACCT_020B), ''))                     as acct_020b,
        try_to_number(nullif(trim(ACCT_024A), ''))                     as acct_024a,
        try_to_number(nullif(trim(ACCT_024B), ''))                     as acct_024b,
        try_to_number(nullif(trim(ACCT_042A), ''))                     as acct_042a,
        try_to_number(nullif(trim(ACCT_090A), ''))                     as acct_090a,
        try_to_number(nullif(trim(ACCT_090B), ''))                     as acct_090b,
        try_to_number(nullif(trim(ACCT_090C), ''))                     as acct_090c,
        try_to_number(nullif(trim(ACCT_090D), ''))                     as acct_090d,
        try_to_number(nullif(trim(ACCT_099A), ''))                     as acct_099a,
        try_to_number(nullif(trim(ACCT_143A), ''))                     as acct_143a,
        try_to_number(nullif(trim(ACCT_143B), ''))                     as acct_143b,
        try_to_number(nullif(trim(ACCT_143C), ''))                     as acct_143c,
        try_to_number(nullif(trim(ACCT_143D), ''))                     as acct_143d,
        try_to_number(nullif(trim(ACCT_400A), ''))                     as acct_400a,
        try_to_number(nullif(trim(ACCT_400B), ''))                     as acct_400b,
        try_to_number(nullif(trim(ACCT_400C), ''))                     as acct_400c,
        try_to_number(nullif(trim(ACCT_400D), ''))                     as acct_400d,
        try_to_number(nullif(trim(ACCT_400F), ''))                     as acct_400f,
        try_to_number(nullif(trim(ACCT_459A), ''))                     as acct_459a,
        try_to_number(nullif(trim(ACCT_463A), ''))                     as acct_463a,
        try_to_number(nullif(trim(ACCT_475A), ''))                     as acct_475a,
        try_to_number(nullif(trim(ACCT_475B), ''))                     as acct_475b,
        try_to_number(nullif(trim(ACCT_475C), ''))                     as acct_475c,
        try_to_number(nullif(trim(ACCT_475D), ''))                     as acct_475d,
        try_to_number(nullif(trim(ACCT_691B), ''))                     as acct_691b,
        try_to_number(nullif(trim(ACCT_691C), ''))                     as acct_691c,
        try_to_number(nullif(trim(ACCT_692), ''))                      as acct_692,
        try_to_number(nullif(trim(ACCT_692A), ''))                     as acct_692a,
        try_to_number(nullif(trim(ACCT_704A), ''))                     as acct_704a,
        try_to_number(nullif(trim(ACCT_704B), ''))                     as acct_704b,
        try_to_number(nullif(trim(ACCT_704C), ''))                     as acct_704c,
        try_to_number(nullif(trim(ACCT_704D), ''))                     as acct_704d,
        try_to_number(nullif(trim(ACCT_704E), ''))                     as acct_704e,
        try_to_number(nullif(trim(ACCT_705A), ''))                     as acct_705a,
        try_to_number(nullif(trim(ACCT_705B), ''))                     as acct_705b,
        try_to_number(nullif(trim(ACCT_708B), ''))                     as acct_708b,
        try_to_number(nullif(trim(ACCT_720A), ''))                     as acct_720a,
        try_to_number(nullif(trim(ACCT_720B), ''))                     as acct_720b,
        try_to_number(nullif(trim(ACCT_720C), ''))                     as acct_720c,
        try_to_number(nullif(trim(ACCT_720D), ''))                     as acct_720d,
        try_to_number(nullif(trim(ACCT_720E), ''))                     as acct_720e,
        try_to_number(nullif(trim(ACCT_721A), ''))                     as acct_721a,
        try_to_number(nullif(trim(ACCT_721B), ''))                     as acct_721b,
        try_to_number(nullif(trim(ACCT_724B), ''))                     as acct_724b,
        try_to_number(nullif(trim(ACCT_733A), ''))                     as acct_733a,
        try_to_number(nullif(trim(ACCT_745C1), ''))                    as acct_745c1,
        try_to_number(nullif(trim(ACCT_745C2), ''))                    as acct_745c2,
        try_to_number(nullif(trim(ACCT_796C1), ''))                    as acct_796c1,
        try_to_number(nullif(trim(ACCT_796C2), ''))                    as acct_796c2,
        try_to_number(nullif(trim(ACCT_797C1), ''))                    as acct_797c1,
        try_to_number(nullif(trim(ACCT_797C2), ''))                    as acct_797c2,
        try_to_number(nullif(trim(ACCT_799C1), ''))                    as acct_799c1,
        try_to_number(nullif(trim(ACCT_799C2), ''))                    as acct_799c2,
        try_to_number(nullif(trim(ACCT_965C1), ''))                    as acct_965c1,
        try_to_number(nullif(trim(ACCT_965C2), ''))                    as acct_965c2,
        try_to_number(nullif(trim(ACCT_088), ''))                      as acct_088,
        try_to_number(nullif(trim(ACCT_799A1), ''))                    as acct_799a1,
        try_to_number(nullif(trim(ACCT_672B), ''))                     as acct_672b,
        try_to_number(nullif(trim(ACCT_672C1), ''))                    as acct_672c1,
        try_to_number(nullif(trim(ACCT_672C2), ''))                    as acct_672c2,
        try_to_number(nullif(trim(ACCT_672D), ''))                     as acct_672d,
        try_to_number(nullif(trim(ACCT_744B), ''))                     as acct_744b,
        try_to_number(nullif(trim(ACCT_744C1), ''))                    as acct_744c1,
        try_to_number(nullif(trim(ACCT_744C2), ''))                    as acct_744c2,
        try_to_number(nullif(trim(ACCT_744D), ''))                     as acct_744d,
        try_to_number(nullif(trim(ACCT_652B), ''))                     as acct_652b,
        try_to_number(nullif(trim(ACCT_652C1), ''))                    as acct_652c1,
        try_to_number(nullif(trim(ACCT_652C2), ''))                    as acct_652c2,
        try_to_number(nullif(trim(ACCT_652D), ''))                     as acct_652d,
        try_to_number(nullif(trim(ACCT_766A), ''))                     as acct_766a,
        try_to_number(nullif(trim(ACCT_766B), ''))                     as acct_766b,
        try_to_number(nullif(trim(ACCT_766C1), ''))                    as acct_766c1,
        try_to_number(nullif(trim(ACCT_766C2), ''))                    as acct_766c2,
        try_to_number(nullif(trim(ACCT_766D), ''))                     as acct_766d,
        try_to_number(nullif(trim(ACCT_766E), ''))                     as acct_766e,
        try_to_number(nullif(trim(ACCT_798A1), ''))                    as acct_798a1,
        try_to_number(nullif(trim(ACCT_798A2), ''))                    as acct_798a2,
        try_to_number(nullif(trim(ACCT_798A3), ''))                    as acct_798a3,
        try_to_number(nullif(trim(ACCT_009A), ''))                     as acct_009a,
        try_to_number(nullif(trim(ACCT_009B), ''))                     as acct_009b,
        try_to_number(nullif(trim(ACCT_009C), ''))                     as acct_009c,
        try_to_number(nullif(trim(ACCT_769A1), ''))                    as acct_769a1,
        try_to_number(nullif(trim(ACCT_769B1), ''))                    as acct_769b1,
        try_to_number(nullif(trim(ACCT_616), ''))                      as acct_616,
        try_to_number(nullif(trim(ACCT_616A), ''))                     as acct_616a,
        try_to_number(nullif(trim(ACCT_704A1), ''))                    as acct_704a1,
        try_to_number(nullif(trim(ACCT_704C1), ''))                    as acct_704c1,
        try_to_number(nullif(trim(ACCT_980), ''))                      as acct_980,
        try_to_number(nullif(trim(ACCT_742C1), ''))                    as acct_742c1,
        try_to_number(nullif(trim(ACCT_742C2), ''))                    as acct_742c2,
        try_to_number(nullif(trim(ACCT_020J), ''))                     as acct_020j,
        try_to_number(nullif(trim(ACCT_020K), ''))                     as acct_020k,
        try_to_number(nullif(trim(ACCT_020L), ''))                     as acct_020l,
        try_to_number(nullif(trim(ACCT_021J), ''))                     as acct_021j,
        try_to_number(nullif(trim(ACCT_021K), ''))                     as acct_021k,
        try_to_number(nullif(trim(ACCT_021L), ''))                     as acct_021l,
        try_to_number(nullif(trim(ACCT_022J), ''))                     as acct_022j,
        try_to_number(nullif(trim(ACCT_022K), ''))                     as acct_022k,
        try_to_number(nullif(trim(ACCT_022L), ''))                     as acct_022l,
        try_to_number(nullif(trim(ACCT_023J), ''))                     as acct_023j,
        try_to_number(nullif(trim(ACCT_023K), ''))                     as acct_023k,
        try_to_number(nullif(trim(ACCT_023L), ''))                     as acct_023l,
        try_to_number(nullif(trim(ACCT_041J), ''))                     as acct_041j,
        try_to_number(nullif(trim(ACCT_041K), ''))                     as acct_041k,
        try_to_number(nullif(trim(ACCT_041L), ''))                     as acct_041l,
        try_to_number(nullif(trim(ACCT_1019), ''))                     as acct_1019,
        try_to_number(nullif(trim(ACCT_1019A), ''))                    as acct_1019a,
        try_to_number(nullif(trim(ACCT_1019B), ''))                    as acct_1019b,
        try_to_number(nullif(trim(ACCT_1019C), ''))                    as acct_1019c,
        try_to_number(nullif(trim(ACCT_1019D), ''))                    as acct_1019d,
        try_to_number(nullif(trim(ACCT_1019E), ''))                    as acct_1019e,
        try_to_number(nullif(trim(ACCT_789A), ''))                     as acct_789a,
        try_to_number(nullif(trim(ACCT_789A1), ''))                    as acct_789a1,
        try_to_number(nullif(trim(ACCT_789B), ''))                     as acct_789b,
        try_to_number(nullif(trim(ACCT_789B1), ''))                    as acct_789b1,
        _INGESTED_AT                                   as _loaded_at,
        _SOURCE_RUN_ID                                 as _source_run_id,
        _SRC_SHA256                                    as _src_sha256

    from source

),

deduped as (

    select *,
        row_number() over (
            partition by cu_number
            order by _loaded_at desc
        ) as _row_num
    from renamed
    where cu_number is not null

)

select * exclude (_row_num) from deduped
where _row_num = 1
