-- [S1] The facility set: both GPC plants + Nebraska operating majors with an Unaddressed HPV status today
WITH f AS (SELECT PGM_SYS_ID, ANY_VALUE(REGISTRY_ID) AS REG, ANY_VALUE(FACILITY_NAME) AS NM, ANY_VALUE(CITY) AS CITY, ANY_VALUE(COUNTY_NAME) AS CNTY, ANY_VALUE(STATE) AS ST,
  ANY_VALUE(NAICS_CODES) AS NAICS, ANY_VALUE(AIR_POLLUTANT_CLASS_CODE) AS CLS, ANY_VALUE(AIR_OPERATING_STATUS_CODE) AS OP, ANY_VALUE(CURRENT_HPV) AS HPV
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_FACILITIES GROUP BY 1)
SELECT IFF(ST='NE','NE15','GPC') AS GRP, * FROM f
WHERE (ST='NE' AND CLS='MAJ' AND OP='OPR' AND HPV ILIKE 'Unaddressed%')
   OR (UPPER(NM) LIKE '%GRAIN PROCESSING%' AND ST IN ('IA','IN'))
ORDER BY 1, ST, NM
