-- [S5] Chart rows: GPC Muscatine IA vs GPC Washington IN, per year 2005-2026: stack-test fail days, all test days, formal actions (state/EPA) and penalty $, informal actions
WITH g AS (SELECT * FROM (VALUES ('IA0000001913900025','Muscatine IA'),('IN0000001802700046','Washington IN')) v(PGM_SYS_ID, PLANT)),
st AS (SELECT PGM_SYS_ID, YEAR(ACTUAL_END_DATE) AS YR, COUNT(DISTINCT IFF(AIR_STACK_TEST_STATUS_CODE='FAI', ACTUAL_END_DATE, NULL)) AS FAIL_DAYS, COUNT(DISTINCT ACTUAL_END_DATE) AS TEST_DAYS, COUNT_IF(AIR_STACK_TEST_STATUS_CODE='FAI') AS FAIL_ROWS
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_STACK_TESTS WHERE PGM_SYS_ID IN (SELECT PGM_SYS_ID FROM g) GROUP BY 1,2),
fa AS (SELECT PGM_SYS_ID, YEAR(SETTLEMENT_ENTERED_DATE) AS YR, COUNT(*) AS FORMAL, COUNT_IF(STATE_EPA_FLAG='S') AS FORMAL_STATE, COUNT_IF(STATE_EPA_FLAG='E') AS FORMAL_EPA, SUM(COALESCE(PENALTY_AMOUNT,0)) AS PENALTY, LISTAGG(DISTINCT ENF_TYPE_DESC, ';') AS FA_TYPES
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_FORMAL_ACTIONS WHERE PGM_SYS_ID IN (SELECT PGM_SYS_ID FROM g) GROUP BY 1,2),
ia AS (SELECT PGM_SYS_ID, YEAR(ACHIEVED_DATE) AS YR, COUNT(*) AS INFORMAL, LISTAGG(DISTINCT ENF_TYPE_DESC, ';') AS IA_TYPES
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_INFORMAL_ACTIONS WHERE PGM_SYS_ID IN (SELECT PGM_SYS_ID FROM g) GROUP BY 1,2),
vh AS (SELECT PGM_SYS_ID, YEAR(COALESCE(HPV_DAYZERO_DATE, EARLIEST_FRV_DETERM_DATE)) AS YR, COUNT(*) AS VIOL, COUNT(HPV_DAYZERO_DATE) AS HPV
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_VIOLATION_HISTORY WHERE PGM_SYS_ID IN (SELECT PGM_SYS_ID FROM g) GROUP BY 1,2),
k AS (SELECT PGM_SYS_ID, YR FROM st UNION SELECT PGM_SYS_ID, YR FROM fa UNION SELECT PGM_SYS_ID, YR FROM ia UNION SELECT PGM_SYS_ID, YR FROM vh)
SELECT g.PLANT, k.YR, st.TEST_DAYS, st.FAIL_DAYS, st.FAIL_ROWS, vh.VIOL, vh.HPV, ia.INFORMAL, fa.FORMAL, fa.FORMAL_STATE, fa.FORMAL_EPA, fa.PENALTY, fa.FA_TYPES, ia.IA_TYPES
FROM k JOIN g USING (PGM_SYS_ID) LEFT JOIN st USING (PGM_SYS_ID, YR) LEFT JOIN fa USING (PGM_SYS_ID, YR) LEFT JOIN ia USING (PGM_SYS_ID, YR) LEFT JOIN vh USING (PGM_SYS_ID, YR)
ORDER BY 1,2
