-- [S9] OSHA: enforcement inspections and ITA 300A injury summaries for Grain Processing Corp, name + city + state (second field: city must be Muscatine or Washington)
SELECT 'INSP' AS SRC, SITE_STATE AS ST, SITE_CITY AS CITY, ESTAB_NAME AS NM, SITE_ADDRESS AS ADDR, TO_VARCHAR(OPEN_DATE) AS D, INSP_TYPE || '/' || INSP_SCOPE || '/' || SAFETY_HLTH AS WHAT, NR_IN_ESTAB::VARCHAR AS N_EMP, NULL AS INJ, NULL AS HOURS
FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_DOL_OSHA_INSPECTIONS
WHERE (UPPER(ESTAB_NAME) LIKE '%GRAIN PROCESSING%' OR UPPER(ESTAB_NAME) LIKE 'GPC%' OR UPPER(ESTAB_NAME) LIKE '%KENT CORP%') AND SITE_STATE IN ('IA','IN')
UNION ALL
SELECT 'ITA_' || YEAR_FILING_FOR::VARCHAR, STATE, CITY, ESTABLISHMENT_NAME || ' / ' || COALESCE(COMPANY_NAME,''), STREET_ADDRESS, EIN, ANNUAL_AVERAGE_EMPLOYEES::VARCHAR, TOTAL_HOURS_WORKED::VARCHAR, TOTAL_DAFW_CASES::VARCHAR || ' DAFW, ' || TOTAL_DJTR_CASES::VARCHAR || ' DJTR, ' || TOTAL_OTHER_CASES::VARCHAR || ' other, ' || TOTAL_DEATHS::VARCHAR || ' deaths, resp ' || TOTAL_RESPIRATORY_CONDITIONS::VARCHAR, NAICS_CODE::VARCHAR
FROM (SELECT * FROM LIBRARY_MARTS.LABOR.LABOR__FED_OSHA_ITA_300A_SUMMARY_2023 UNION ALL SELECT * FROM LIBRARY_MARTS.LABOR.LABOR__FED_OSHA_ITA_300A_SUMMARY_2024 UNION ALL SELECT * FROM LIBRARY_MARTS.LABOR.LABOR__FED_OSHA_ITA_300A_SUMMARY_2025)
WHERE (UPPER(ESTABLISHMENT_NAME) LIKE '%GRAIN PROCESSING%' OR UPPER(COMPANY_NAME) LIKE '%GRAIN PROCESSING%' OR UPPER(COMPANY_NAME) LIKE '%KENT CORP%') AND STATE IN ('IA','IN')
ORDER BY 1,2,6
