-- [S10] Federal contracts (USAspending R2, uncapped) to Grain Processing Corp or Kent Corp / Kent Nutrition, by recipient + parent name; grouped by recipient, state, agency, fiscal year of action
SELECT RECIPIENT_NAME, RECIPIENT_PARENT_NAME, RECIPIENT_UEI, RECIPIENT_CITY_NAME, RECIPIENT_STATE_CODE, AWARDING_SUB_AGENCY_NAME, LEFT(ACTION_DATE,4) AS YR,
  COUNT(*) AS N_ACTIONS, COUNT(DISTINCT CONTRACT_AWARD_UNIQUE_KEY) AS N_AWARDS, SUM(FEDERAL_ACTION_OBLIGATION) AS OBLIG, MIN(ACTION_DATE) AS FIRST_ACT, ANY_VALUE(PRODUCT_OR_SERVICE_CODE_DESCRIPTION) AS PSC
FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_USASPENDING_CONTRACTS_FULL_R2
WHERE UPPER(RECIPIENT_NAME) LIKE '%GRAIN PROCESSING%' OR UPPER(RECIPIENT_PARENT_NAME) LIKE '%GRAIN PROCESSING%'
   OR UPPER(RECIPIENT_NAME) LIKE 'KENT CORP%' OR UPPER(RECIPIENT_PARENT_NAME) LIKE 'KENT CORP%' OR UPPER(RECIPIENT_NAME) LIKE 'KENT NUTRITION%'
GROUP BY 1,2,3,4,5,6,7 ORDER BY 1,7
