-- [S11] Federal assistance (grants, loans, subsidies; USAspending ASSISTANCE_FULL, 128M rows) to Grain Processing Corp or Kent Corp, by name, grouped
SELECT RECIPIENT_NAME, RECIPIENT_PARENT_NAME, RECIPIENT_UEI, RECIPIENT_CITY_NAME, RECIPIENT_STATE_CODE, AWARDING_SUB_AGENCY_NAME, CFDA_NUMBER, CFDA_TITLE, ASSISTANCE_TYPE_DESCRIPTION,
  COUNT(*) AS N_ACTIONS, COUNT(DISTINCT ASSISTANCE_AWARD_UNIQUE_KEY) AS N_AWARDS, SUM(FEDERAL_ACTION_OBLIGATION) AS OBLIG, SUM(FACE_VALUE_OF_LOAN) AS LOAN_FACE, MIN(ACTION_DATE) AS FIRST_ACT, MAX(ACTION_DATE) AS LAST_ACT
FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_USASPENDING_ASSISTANCE_FULL
WHERE UPPER(RECIPIENT_NAME) LIKE '%GRAIN PROCESSING%' OR UPPER(RECIPIENT_PARENT_NAME) LIKE '%GRAIN PROCESSING%'
   OR UPPER(RECIPIENT_NAME) LIKE 'KENT CORP%' OR UPPER(RECIPIENT_PARENT_NAME) LIKE 'KENT CORP%' OR UPPER(RECIPIENT_NAME) LIKE 'KENT NUTRITION%'
GROUP BY 1,2,3,4,5,6,7,8,9 ORDER BY 1,14
