-- [S12] GPC Biofuel Producer Program awards, one row per transaction: award key, dates, amount, place of performance, description
SELECT ASSISTANCE_AWARD_UNIQUE_KEY, AWARD_ID_FAIN, MODIFICATION_NUMBER, ACTION_DATE, FEDERAL_ACTION_OBLIGATION, TOTAL_OBLIGATED_AMOUNT, RECIPIENT_ADDRESS_LINE_1, PRIMARY_PLACE_OF_PERFORMANCE_CITY_NAME AS POP_CITY, PRIMARY_PLACE_OF_PERFORMANCE_STATE_NAME AS POP_ST, PERIOD_OF_PERFORMANCE_START_DATE, TRANSACTION_DESCRIPTION
FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_USASPENDING_ASSISTANCE_FULL
WHERE RECIPIENT_UEI = 'TAR2QK955KK4' OR RECIPIENT_PARENT_UEI = 'TAR2QK955KK4'
ORDER BY ACTION_DATE
