-- [S13] USDA Biofuel Producer Program (CFDA 10.378) grants to Nebraska recipients, and to Iowa/Indiana GPC for reference: by recipient, UEI, city
SELECT RECIPIENT_STATE_CODE AS ST, RECIPIENT_NAME, RECIPIENT_PARENT_NAME, RECIPIENT_UEI, RECIPIENT_CITY_NAME, RECIPIENT_ADDRESS_LINE_1,
  COUNT(DISTINCT ASSISTANCE_AWARD_UNIQUE_KEY) AS N_AWARDS, SUM(FEDERAL_ACTION_OBLIGATION) AS OBLIG, MIN(ACTION_DATE) AS FIRST_ACT
FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_USASPENDING_ASSISTANCE_FULL
WHERE CFDA_NUMBER = '10.378' AND (RECIPIENT_STATE_CODE = 'NE' OR RECIPIENT_UEI = 'TAR2QK955KK4')
GROUP BY 1,2,3,4,5,6 ORDER BY OBLIG DESC
