-- [S16] Peer group: every operating major air source with NAICS 311221 (wet corn milling) nationally: stack-test fail days, violations, HPVs, informal and formal actions and penalties, 2015-2025
WITH f AS (SELECT PGM_SYS_ID, ANY_VALUE(FACILITY_NAME) AS NM, ANY_VALUE(CITY) AS CITY, ANY_VALUE(STATE) AS ST FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_FACILITIES
  GROUP BY 1 HAVING ANY_VALUE(AIR_POLLUTANT_CLASS_CODE)='MAJ' AND ANY_VALUE(AIR_OPERATING_STATUS_CODE)='OPR' AND ANY_VALUE(NAICS_CODES) LIKE '%311221%'),
st AS (SELECT PGM_SYS_ID, COUNT(DISTINCT ACTUAL_END_DATE) AS TEST_DAYS, COUNT(DISTINCT IFF(AIR_STACK_TEST_STATUS_CODE='FAI', ACTUAL_END_DATE, NULL)) AS FAIL_DAYS FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_STACK_TESTS
  WHERE ACTUAL_END_DATE >= '2015-01-01' AND ACTUAL_END_DATE < '2026-01-01' AND PGM_SYS_ID IN (SELECT PGM_SYS_ID FROM f) GROUP BY 1),
v AS (SELECT PGM_SYS_ID, COUNT(*) AS VIOL, COUNT(HPV_DAYZERO_DATE) AS HPV FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_VIOLATION_HISTORY
  WHERE COALESCE(HPV_DAYZERO_DATE, EARLIEST_FRV_DETERM_DATE) >= '2015-01-01' AND COALESCE(HPV_DAYZERO_DATE, EARLIEST_FRV_DETERM_DATE) < '2026-01-01' AND PGM_SYS_ID IN (SELECT PGM_SYS_ID FROM f) GROUP BY 1),
ia AS (SELECT PGM_SYS_ID, COUNT(*) AS INF FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_INFORMAL_ACTIONS WHERE ACHIEVED_DATE >= '2015-01-01' AND ACHIEVED_DATE < '2026-01-01' AND PGM_SYS_ID IN (SELECT PGM_SYS_ID FROM f) GROUP BY 1),
fa AS (SELECT PGM_SYS_ID, COUNT(*) AS FORMAL, SUM(COALESCE(PENALTY_AMOUNT,0)) AS PEN FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_FORMAL_ACTIONS WHERE SETTLEMENT_ENTERED_DATE >= '2015-01-01' AND SETTLEMENT_ENTERED_DATE < '2026-01-01' AND PGM_SYS_ID IN (SELECT PGM_SYS_ID FROM f) GROUP BY 1)
SELECT f.NM, f.CITY, f.ST, COALESCE(TEST_DAYS,0) AS TEST_DAYS, COALESCE(FAIL_DAYS,0) AS FAIL_DAYS, COALESCE(VIOL,0) AS VIOL, COALESCE(HPV,0) AS HPV, COALESCE(INF,0) AS INF, COALESCE(FORMAL,0) AS FORMAL, COALESCE(PEN,0) AS PEN
FROM f LEFT JOIN st USING (PGM_SYS_ID) LEFT JOIN v USING (PGM_SYS_ID) LEFT JOIN ia USING (PGM_SYS_ID) LEFT JOIN fa USING (PGM_SYS_ID)
ORDER BY FAIL_DAYS DESC, VIOL DESC
