-- [S17] TRI 2023 peer group: every facility with primary NAICS 311221 (wet corn milling): air releases (fugitive + stack, lb), acetaldehyde air, carcinogen air, rank
SELECT C_3_FRS_ID AS REG, C_4_FACILITY_NAME AS NM, C_6_CITY AS CITY, C_8_ST AS ST, C_17_STANDARD_PARENT_CO_NAME AS PARENT,
  SUM(COALESCE(TRY_TO_NUMBER(TO_VARCHAR(C_51_5_1_FUGITIVE_AIR),38,4),0) + COALESCE(TRY_TO_NUMBER(TO_VARCHAR(C_52_5_2_STACK_AIR),38,4),0)) AS AIR_LB,
  SUM(IFF(UPPER(C_37_CHEMICAL)='ACETALDEHYDE', COALESCE(TRY_TO_NUMBER(TO_VARCHAR(C_51_5_1_FUGITIVE_AIR),38,4),0) + COALESCE(TRY_TO_NUMBER(TO_VARCHAR(C_52_5_2_STACK_AIR),38,4),0), 0)) AS ACETALD_LB,
  SUM(IFF(UPPER(C_46_CARCINOGEN) IN ('YES','Y','TRUE'), COALESCE(TRY_TO_NUMBER(TO_VARCHAR(C_51_5_1_FUGITIVE_AIR),38,4),0) + COALESCE(TRY_TO_NUMBER(TO_VARCHAR(C_52_5_2_STACK_AIR),38,4),0), 0)) AS CARCIN_AIR_LB,
  COUNT(*) AS N_CHEM, MAX(C_50_UNIT_OF_MEASURE) AS UNIT_MAX, MIN(C_50_UNIT_OF_MEASURE) AS UNIT_MIN
FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_TRI_BASIC_2023
WHERE TO_VARCHAR(C_30_PRIMARY_NAICS) LIKE '311221%'
GROUP BY 1,2,3,4,5 ORDER BY AIR_LB DESC
