-- [S18] Why no EIS (National Emissions Inventory) rows for GPC Muscatine? Look for any EIS or other registry record in Muscatine IA under a GPC-like name
SELECT TO_VARCHAR(REGISTRY_ID) AS REG, PGM_SYS_ACRNM, PGM_SYS_ID, PRIMARY_NAME, LOCATION_ADDRESS, CITY_NAME, STATE_CODE
FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_FRS_FRS_PROGRAM_LINKS
WHERE STATE_CODE = 'IA' AND UPPER(CITY_NAME) = 'MUSCATINE' AND (UPPER(PRIMARY_NAME) LIKE '%GRAIN PROC%' OR UPPER(PRIMARY_NAME) LIKE 'GPC%' OR UPPER(PRIMARY_NAME) LIKE '%KENT%' OR UPPER(LOCATION_ADDRESS) LIKE '1600 OREGON%')
ORDER BY 1,2
