-- [S20] Peer trend: TRI air pounds per year for operating major ethanol plants (NAICS 325193) nationally, split: the NE unaddressed ethanol plants, other Nebraska, Iowa, all other states. Join ICIS-Air facilities to combined emissions on REGISTRY_ID
WITH f AS (SELECT TO_VARCHAR(ANY_VALUE(REGISTRY_ID)) AS REG, ANY_VALUE(STATE) AS ST, ANY_VALUE(CURRENT_HPV) AS HPV FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_FACILITIES
  GROUP BY PGM_SYS_ID HAVING ANY_VALUE(AIR_POLLUTANT_CLASS_CODE)='MAJ' AND ANY_VALUE(AIR_OPERATING_STATUS_CODE)='OPR' AND ANY_VALUE(NAICS_CODES) LIKE '%325193%'),
g AS (SELECT REG, MAX(CASE WHEN ST='NE' AND HPV ILIKE 'Unaddressed%' THEN 'NE_UNADDR' WHEN ST='NE' THEN 'NE_OTHER' WHEN ST='IA' THEN 'IA' ELSE 'OTHER' END) AS GRP FROM f WHERE REG IS NOT NULL GROUP BY 1)
SELECT g.GRP, e.REPORTING_YEAR, COUNT(DISTINCT g.REG) AS PLANTS, SUM(e.ANNUAL_EMISSION) AS TRI_AIR_LB
FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_AIR_EMISSIONS_POLL_RPT_COMBINED_EMISSIONS e JOIN g ON TO_VARCHAR(e.REGISTRY_ID) = g.REG
WHERE e.PGM_SYS_ACRNM = 'TRIS' GROUP BY 1,2 ORDER BY 1,2
