-- [S21] Neighbourhood peer check: ECHO PCT_MINORITY (EPA's figure for people near the site) for active major air facilities in IA, IN, NE: median and quartiles, next to county population from DIM_COUNTY for Muscatine and Daviess
SELECT 'ECHO_MAJOR_AIR' AS SRC, STATE AS ST, COUNT(*) AS N, MEDIAN(PCT_MINORITY) AS MED, PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY PCT_MINORITY) AS P75, PERCENTILE_CONT(0.9) WITHIN GROUP (ORDER BY PCT_MINORITY) AS P90
FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ECHO
WHERE STATE IN ('IA','IN','NE') AND HAS_AIR_PROGRAM AND IS_MAJOR_FACILITY AND IS_ACTIVE AND PCT_MINORITY IS NOT NULL AND POPULATION_DENSITY > 0
GROUP BY 1,2
UNION ALL
SELECT 'DIM_COUNTY', COUNTY_NAME || ', ' || STATE_NAME, POPULATION_2020, NULL, NULL, NULL FROM LIBRARY_MARTS.CORE.DIM_COUNTY WHERE COUNTY_FIPS IN ('19139','18027')
