-- [S22] Water side for the two GPC plants: quarters by HLRNC code and effluent exceedance counts per year since 2015 (EPA quarterly noncompliance history)
SELECT NPDES_ID, LEFT(YEARQTR,4) AS YR, LISTAGG(COALESCE(NULLIF(TRIM(HLRNC),''),'_'), '') WITHIN GROUP (ORDER BY YEARQTR) AS QTR_CODES, SUM(TRY_TO_NUMBER(NUME90_Q)) AS EFFLUENT_EXCEED, SUM(TRY_TO_NUMBER(NUMCVDT)) AS SCHED_VIOL
FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_NPDES_NPDES_QNCR_HISTORY
WHERE NPDES_ID IN ('IA0003441','IN0059641') AND LEFT(YEARQTR,4) >= '2015'
GROUP BY 1,2 ORDER BY 1,2
