{{ config(tags=['spine_generated']) }}

-- GRAIN: one row per organization (EIN is unique)
-- SPINE_ENTITY: organization  (natural_key: EIN)
-- Generated by scripts/generate_staging_models.py from SOURCE_REGISTRY -- deterministic,
-- no LLM. Casts kept as landed (TEXT) -- add explicit type casts by hand once each
-- column's real type is confirmed; this generator has no semantic type knowledge.

with source as (

    select * from {{ source('ripple_raw', 'FED_IRS_990') }}

),

renamed as (

    select
        "EIN" as ein,
        "ORGANIZATIONNAME" as organizationname,
        "TAXPERIODBEGINDT" as taxperiodbegindt,
        "TAXPERIODENDDT" as taxperiodenddt,
        "FORMTYPE" as formtype,
        "RETURNTS" as returnts,
        "TAXYR" as taxyr,
        "GROSSRECEIPTSAMT" as grossreceiptsamt,
        "TOTALASSETSEOYAMT" as totalassetseoyamt,
        "TOTALLIABILITIESEOYAMT" as totalliabilitieseoyamt,
        "TOTALREVENUEAMT" as totalrevenueamt,
        "TOTALEXPENSESAMT" as totalexpensesamt,
        "OFFICERCOMPENSATIONAMT" as officercompensationamt,
        "USADDRESS_ZIPCD" as usaddress_zipcd,
        "USADDRESS_STATEABBREVIATIONCD" as usaddress_stateabbreviationcd,
        "EXEMPTIONCD" as exemptioncd,
        "OBJECTID" as objectid,
        "RETURNID" as returnid,
        _INGESTED_AT as _loaded_at,
        'https://www.irs.gov/charities-non-profits/form-990-series-downloads' as _source_url,
    'ENT_' || LEFT(MD5('EIN' || '|' || (CASE WHEN LENGTH(UPPER(REGEXP_REPLACE(TO_VARCHAR("EIN"), '[^0-9A-Za-z]', ''))) = 0 OR LENGTH(UPPER(REGEXP_REPLACE(TO_VARCHAR("EIN"), '[^0-9A-Za-z]', ''))) > 9 OR NOT REGEXP_LIKE(UPPER(REGEXP_REPLACE(TO_VARCHAR("EIN"), '[^0-9A-Za-z]', '')), '^[0-9]+$') OR LPAD(UPPER(REGEXP_REPLACE(TO_VARCHAR("EIN"), '[^0-9A-Za-z]', '')), 9, '0') = REPEAT('0', 9) OR (LENGTH(UPPER(REGEXP_REPLACE(TO_VARCHAR("EIN"), '[^0-9A-Za-z]', ''))) >= 4 AND UPPER(REGEXP_REPLACE(TO_VARCHAR("EIN"), '[^0-9A-Za-z]', '')) = REPEAT(LEFT(UPPER(REGEXP_REPLACE(TO_VARCHAR("EIN"), '[^0-9A-Za-z]', '')), 1), LENGTH(UPPER(REGEXP_REPLACE(TO_VARCHAR("EIN"), '[^0-9A-Za-z]', ''))))) OR LPAD(UPPER(REGEXP_REPLACE(TO_VARCHAR("EIN"), '[^0-9A-Za-z]', '')), 9, '0') = REPEAT(LEFT(LPAD(UPPER(REGEXP_REPLACE(TO_VARCHAR("EIN"), '[^0-9A-Za-z]', '')), 9, '0'), 1), 9) OR UPPER(REGEXP_REPLACE(TO_VARCHAR("EIN"), '[^0-9A-Za-z]', '')) IN ('123456789', '987654321', '1234567890', '0987654321', '12345678', '87654321', '123456', '654321') OR LPAD(UPPER(REGEXP_REPLACE(TO_VARCHAR("EIN"), '[^0-9A-Za-z]', '')), 9, '0') IN ('123456789', '987654321', '1234567890', '0987654321', '12345678', '87654321', '123456', '654321') THEN NULL ELSE LPAD(UPPER(REGEXP_REPLACE(TO_VARCHAR("EIN"), '[^0-9A-Za-z]', '')), 9, '0') END)), 16) as spine_entity_id  -- joins LIBRARY_META."CONNECT".ENTITY_GOLDEN.ENTITY_ID

    from source

)

select * from renamed
qualify row_number() over (partition by ein order by _loaded_at desc) = 1
