{{ config(tags=['spine_generated']) }}

-- GRAIN: one row per place (LATLON is unique)
-- SPINE_ENTITY: place  (natural_key: LONGITUDE)
-- Generated by scripts/generate_staging_models.py from SOURCE_REGISTRY -- deterministic,
-- no LLM.
-- CASTS: 3 of 10 columns, from landing_column_profile_2026-09-19.tsv. A column is cast only
-- when every filled value in the sample parsed. try_ casts: a value that does not
-- parse reads NULL. The natural key and join-key columns stay TEXT.
--   total_docks: integer
--   point_x: float
--   point_y: float
-- spine_entity 'place' has no connect/ resolver yet (see connect/spine_entity.py) -- no SPINE_ENTITY_ID emitted.
-- landing table's ingestion timestamp is named INGESTED_AT (no leading underscore) rather than the usual _INGESTED_AT -- confirmed via INFORMATION_SCHEMA, not assumed.
-- DEDUPE: registry natural_key (LONGITUDE) is NOT unique within a load as landed at generation time -- it would collapse 2 of 572 rows. Deduping on the WHOLE ROW instead (exact copies only). A record that changes between loads shows once per version. Find the real key, fix SOURCE_REGISTRY, regenerate.

with source as (

    select * from {{ source('ripple_raw', 'PORTAL_CKA_ANALYZE_BOSTON_899BB82358') }}
    qualify row_number() over (partition by "NUMBER", "NAME", "LATITUDE", "LONGITUDE", "DISTRICT", "PUBLIC", "TOTAL_DOCKS", "SHAPE_WKT", "POINT_X", "POINT_Y" order by INGESTED_AT desc) = 1

),

renamed as (

    select
        {{ null_junk('"NUMBER"') }} as number,
        {{ null_junk('"NAME"') }} as name,
        {{ null_junk('"LATITUDE"') }} as latitude,
        {{ null_junk('"LONGITUDE"') }} as longitude,
        {{ null_junk('"DISTRICT"') }} as district,
        {{ null_junk('"PUBLIC"') }} as public,
        {{ stg_int('"TOTAL_DOCKS"') }} as total_docks,
        {{ null_junk('"SHAPE_WKT"') }} as shape_wkt,
        {{ stg_float('"POINT_X"') }} as point_x,
        {{ stg_float('"POINT_Y"') }} as point_y,
        INGESTED_AT as _loaded_at,
        'https://data.boston.gov/dataset/blue-bike-stations' as _source_url

    from source

)

select * from renamed
