{{ config(tags=['spine_generated']) }}

-- GRAIN: one row per place (LATLON is unique)
-- SPINE_ENTITY: place  (natural_key: LONGITUDE)
-- Generated by scripts/generate_staging_models.py from SOURCE_REGISTRY -- deterministic,
-- no LLM. Casts kept as landed (TEXT) -- add explicit type casts by hand once each
-- column's real type is confirmed; this generator has no semantic type knowledge.
-- spine_entity 'place' has no connect/ resolver yet (see connect/spine_entity.py) -- no SPINE_ENTITY_ID emitted.
-- landing table's ingestion timestamp is named INGESTED_AT (no leading underscore) rather than the usual _INGESTED_AT -- confirmed via INFORMATION_SCHEMA, not assumed.

with source as (

    select * from {{ source('ripple_raw', 'PORTAL_CKA_ANALYZE_BOSTON_899BB82358') }}

),

renamed as (

    select
        "NUMBER" as number,
        "NAME" as name,
        "LATITUDE" as latitude,
        "LONGITUDE" as longitude,
        "DISTRICT" as district,
        "PUBLIC" as public,
        "TOTAL_DOCKS" as total_docks,
        "SHAPE_WKT" as shape_wkt,
        "POINT_X" as point_x,
        "POINT_Y" as point_y,
        INGESTED_AT as _loaded_at,
        'https://data.boston.gov/dataset/blue-bike-stations' as _source_url

    from source

)

select * from renamed
qualify row_number() over (partition by longitude order by _loaded_at desc) = 1
