-- @fs220_all
select * from LIBRARY_MARTS.FINANCE.FINANCE__FED_NCUA_CALL_REPORTS_FS220;

-- @foicu_all
select * from LIBRARY_MARTS.FINANCE.FINANCE__FED_NCUA_CALL_REPORTS_FOICU;

-- @culist_all
select * from LIBRARY_MARTS.FINANCE.FINANCE__FED_NCUA_FEDERALLY_INSURED_CU_LIST;

-- @ncua_mergers_all
select * from LIBRARY_MARTS.FINANCE.FINANCE__FED_NCUA_CHARTER_MERGER_EVENTS;

-- @mmf_all
select * from LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_MONEY_MARKET_FUND_INFORMATION;

-- @icisair_fac_all
select * from LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_FACILITIES;
