{{ config(tags=['spine_generated']) }}

-- GRAIN: one row per place (COUNTRY is unique)
-- SPINE_ENTITY: place  (natural_key: COUNTRY_SUBDIVISION_SECONDARY)
-- Generated by scripts/generate_staging_models.py from SOURCE_REGISTRY -- deterministic,
-- no LLM.
-- CASTS: 20 of 23 columns, from landing_column_profile_2026-09-19.tsv. A column is cast only
-- when every filled value in the sample parsed. try_ casts: a value that does not
-- parse reads NULL. The natural key and join-key columns stay TEXT.
--   spend_usd: integer
--   spend_eur: integer
--   spend_inr: integer
--   spend_bgn: integer
--   spend_czk: integer
--   spend_dkk: integer
--   spend_huf: integer
--   spend_pln: integer
--   spend_ron: integer
--   spend_sek: integer
--   spend_gbp: integer
--   spend_nzd: integer
--   spend_ils: integer
--   spend_aud: integer
--   spend_twd: integer
--   spend_brl: integer
--   spend_ars: integer
--   spend_zar: integer
--   spend_clp: integer
--   spend_mxn: integer
-- spine_entity 'place' has no connect/ resolver yet (see connect/spine_entity.py) -- no SPINE_ENTITY_ID emitted.
-- landing table's ingestion timestamp is named INGESTED_AT (no leading underscore) rather than the usual _INGESTED_AT -- confirmed via INFORMATION_SCHEMA, not assumed.

with source as (

    select * from {{ source('ripple_raw', 'FED_GOOGLE_POLADS_GEO_SPEND') }}
    qualify row_number() over (partition by "COUNTRY_SUBDIVISION_SECONDARY" order by INGESTED_AT desc) = 1

),

renamed as (

    select
        {{ null_junk('"COUNTRY"') }} as country,
        {{ null_junk('"COUNTRY_SUBDIVISION_PRIMARY"') }} as country_subdivision_primary,
        {{ null_junk('"COUNTRY_SUBDIVISION_SECONDARY"') }} as country_subdivision_secondary,
        {{ stg_int('"SPEND_USD"') }} as spend_usd,
        {{ stg_int('"SPEND_EUR"') }} as spend_eur,
        {{ stg_int('"SPEND_INR"') }} as spend_inr,
        {{ stg_int('"SPEND_BGN"') }} as spend_bgn,
        {{ stg_int('"SPEND_CZK"') }} as spend_czk,
        {{ stg_int('"SPEND_DKK"') }} as spend_dkk,
        {{ stg_int('"SPEND_HUF"') }} as spend_huf,
        {{ stg_int('"SPEND_PLN"') }} as spend_pln,
        {{ stg_int('"SPEND_RON"') }} as spend_ron,
        {{ stg_int('"SPEND_SEK"') }} as spend_sek,
        {{ stg_int('"SPEND_GBP"') }} as spend_gbp,
        {{ stg_int('"SPEND_NZD"') }} as spend_nzd,
        {{ stg_int('"SPEND_ILS"') }} as spend_ils,
        {{ stg_int('"SPEND_AUD"') }} as spend_aud,
        {{ stg_int('"SPEND_TWD"') }} as spend_twd,
        {{ stg_int('"SPEND_BRL"') }} as spend_brl,
        {{ stg_int('"SPEND_ARS"') }} as spend_ars,
        {{ stg_int('"SPEND_ZAR"') }} as spend_zar,
        {{ stg_int('"SPEND_CLP"') }} as spend_clp,
        {{ stg_int('"SPEND_MXN"') }} as spend_mxn,
        INGESTED_AT as _loaded_at,
        '' as _source_url

    from source

)

select * from renamed
