-- S01 MO registry: profile, persons vs rows, compliance, tier, state, load runs, address notes
SELECT COUNT(*) n, COUNT(DISTINCT REGISTRANT_NAME, DATE_OF_BIRTH) persons, COUNT(DISTINCT REGISTRANT_NAME) names,
       COUNT(DISTINCT REGISTRANT_NAME, DATE_OF_BIRTH, OFFENSE) person_offense, 
       COUNT(DISTINCT REGISTRANT_NAME, DATE_OF_BIRTH, ADDRESS) person_addr,
       COUNT_IF(IS_COMPLIANT) comp_t, COUNT_IF(NOT IS_COMPLIANT) comp_f, COUNT_IF(IS_COMPLIANT IS NULL) comp_null,
       ARRAY_AGG(DISTINCT TIER) tiers, COUNT(DISTINCT STATE) states, COUNT_IF(STATE <> 'MO') not_mo,
       COUNT(DISTINCT COUNTY) counties, COUNT(DISTINCT ZIP) zips, COUNT(DISTINCT _SOURCE_RUN_ID) runs,
       MIN(_INGESTED_AT) i0, MAX(_INGESTED_AT) i1, COUNT_IF(DATE_OF_BIRTH IS NULL) dob_null,
       COUNT_IF(ADDRESS ILIKE '%UNKNOWN%') addr_unknown, COUNT_IF(ADDRESS ILIKE '%INCARC%') addr_incarc,
       COUNT_IF(ADDRESS ILIKE '%MOVED%' OR ADDRESS ILIKE '%OUT OF STATE%') addr_moved, COUNT_IF(ADDRESS ILIKE '%HOMELESS%' OR ADDRESS ILIKE '%TRANSIENT%') addr_homeless,
       COUNT_IF(NULLIF(TRIM(ADDRESS),'') IS NULL) addr_blank, COUNT_IF(OFFENSE_COUNT IS NULL) oc_null,
       COUNT_IF(DATEDIFF(year, DATE_OF_BIRTH, '2026-09-24') >= 90) age90
FROM LIBRARY_MARTS.JUSTICE.JUSTICE__STATE_MO_SEX_OFFENDER_REGISTRY;

-- S02 MO registry: addresses with the most distinct persons, with compliance and tier mix
SELECT UPPER(TRIM(ADDRESS)) addr, UPPER(TRIM(CITY)) city, ZIP, COUNTY, COUNT(DISTINCT REGISTRANT_NAME, DATE_OF_BIRTH) persons, COUNT(*) n_rows,
       COUNT(DISTINCT IFF(NOT IS_COMPLIANT, REGISTRANT_NAME||DATE_OF_BIRTH, NULL)) noncomp_persons,
       MEDIAN(DATEDIFF(year, DATE_OF_BIRTH, '2026-09-24')) med_age, ARRAY_AGG(DISTINCT TIER) tiers
FROM LIBRARY_MARTS.JUSTICE.JUSTICE__STATE_MO_SEX_OFFENDER_REGISTRY
GROUP BY 1,2,3,4 ORDER BY persons DESC LIMIT 60;

-- S03 CourtListener race codes: the whole lookup
SELECT * FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_COURTLISTENER_RACE_CODES ORDER BY ID;

-- S04 CourtListener courthouses: confirm it is a one-row-per-court dimension; fill rates
SELECT COUNT(*) n, COUNT(DISTINCT ID) ids, COUNT(DISTINCT COURT_ID) court_ids, COUNT_IF(NULLIF(TRIM(ADDRESS1),'') IS NOT NULL) addr1,
       COUNT_IF(NULLIF(TRIM(CITY),'') IS NOT NULL) city, COUNT_IF(NULLIF(TRIM(STATE),'') IS NOT NULL) state, COUNT_IF(NULLIF(TRIM(ZIP_CODE),'') IS NOT NULL) zip,
       COUNT_IF(NULLIF(TRIM(COUNTY),'') IS NOT NULL) county, COUNT_IF(COURT_SEAT = 't') seat_t,
       (SELECT COUNT(*) FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_COURTLISTENER_COURTS) courts_rows,
       COUNT(DISTINCT IFF(COURT_ID IN (SELECT ID FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_COURTLISTENER_COURTS), COURT_ID, NULL)) court_ids_in_courts
FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_COURTLISTENER_COURTHOUSES;

-- S05 DOJ FCA settlements: every row
SELECT * FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_DOJ_FCA_SETTLEMENTS ORDER BY SETTLEMENT_DATE;

-- S06 SCDB: grain, duplicates, constant columns, and the unconstitutional flag vs its code
SELECT DECLARATION_UNCONSTITUTIONAL, IS_UNCONSTITUTIONAL_DECLARATION, COUNT(*) n, COUNT(DISTINCT CASE_ID) cases,
       COUNT(DISTINCT VOTE_ID) vote_ids, COUNT(DISTINCT CASE_ISSUES_ID, JUSTICE_CODE) issue_justice, COUNT(DISTINCT DOCKET_ID) dockets,
       ARRAY_AGG(DISTINCT SPLIT_VOTE) split_vals, MIN(TERM) t0, MAX(TERM) t1, MAX(DATE_DECISION) d1, COUNT(DISTINCT _SOURCE_RUN_ID) runs,
       COUNT_IF(IS_PETITIONER_WINNING) pw_t, COUNT_IF(PARTY_WINNING = 1) pw_code1, COUNT_IF(IS_PRECEDENT_ALTERED) prec_t, COUNT_IF(PRECEDENT_ALTERATION = 1) prec_code1
FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_SCDB
GROUP BY ROLLUP(1,2) ORDER BY 1,2;
