-- S07 MO registry: full extract for local person-level, county and address work
SELECT REGISTRANT_NAME, ADDRESS, CITY, STATE, ZIP, COUNTY, OFFENSE, OFFENSE_COUNT, IS_COMPLIANT, TIER, DATE_OF_BIRTH
FROM LIBRARY_MARTS.JUSTICE.JUSTICE__STATE_MO_SEX_OFFENDER_REGISTRY;

-- S08 CMS nursing homes: every Missouri row, all columns, for the address join
SELECT * FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_NURSING_HOME WHERE STATE = 'MO';

-- S09 CMS nursing-home deficiencies, Missouri, per home: all, abuse tags F600-F610, harm level G+, complaint-driven
SELECT CMS_CERTIFICATION_NUMBER_CCN ccn, COUNT(*) n_def,
       COUNT_IF(DEFICIENCY_TAG_NUMBER IN ('0600','0602','0603','0604','0605','0606','0607','0608','0609','0610')) abuse_tags,
       COUNT_IF(SCOPE_SEVERITY_CODE >= 'G') harm_g_plus,
       COUNT_IF(SCOPE_SEVERITY_CODE >= 'G' AND DEFICIENCY_TAG_NUMBER IN ('0600','0602','0603','0604','0605','0606','0607','0608','0609','0610')) abuse_harm,
       COUNT_IF(DEFICIENCY_TAG_NUMBER = '0600') f600, COUNT_IF(COMPLAINT_DEFICIENCY = 'Y') complaint_def,
       MIN(SURVEY_DATE) s0, MAX(SURVEY_DATE) s1, COUNT(DISTINCT PROCESSING_DATE) proc_dates
FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_NURSING_HOME_DEFICIENCIES
WHERE STATE = 'MO'
GROUP BY 1;

-- S10 SCDB: one row per case, the case-level codes
SELECT CASE_ID, ANY_VALUE(DOCKET) docket, ANY_VALUE(CASE_NAME) case_name, ANY_VALUE(TERM) term, ANY_VALUE(DATE_DECISION) date_decision,
       ANY_VALUE(DATE_ARGUMENT) date_argument, ANY_VALUE(CHIEF_JUSTICE) chief, ANY_VALUE(COURT) court,
       ANY_VALUE(DECISION_TYPE_CODE) decision_type, ANY_VALUE(PETITIONER_CODE) pet, ANY_VALUE(PETITIONER_STATE_CODE) pet_state,
       ANY_VALUE(RESPONDENT_CODE) res, ANY_VALUE(RESPONDENT_STATE_CODE) res_state, ANY_VALUE(JURISDICTION_CODE) juris,
       ANY_VALUE(CASE_ORIGIN_CODE) origin, ANY_VALUE(CASE_ORIGIN_STATE_CODE) origin_state, ANY_VALUE(CASE_SOURCE_CODE) source,
       ANY_VALUE(CASE_SOURCE_STATE_CODE) source_state, ANY_VALUE(LC_DISAGREEMENT) lc_disagree, ANY_VALUE(CERT_REASON_CODE) cert_reason,
       ANY_VALUE(LC_DISPOSITION_CODE) lc_disp, ANY_VALUE(LC_DISPOSITION_DIRECTION_CODE) lc_dir, ANY_VALUE(DECLARATION_UNCONSTITUTIONAL) decl_uncon,
       ANY_VALUE(CASE_DISPOSITION_CODE) case_disp, ANY_VALUE(PARTY_WINNING) party_winning, ANY_VALUE(PRECEDENT_ALTERATION) prec_alt,
       ANY_VALUE(DECISION_DIRECTION_CODE) dec_dir, ANY_VALUE(ISSUE_CODE) issue, ANY_VALUE(ISSUE_AREA_CODE) issue_area,
       ANY_VALUE(LAW_TYPE_CODE) law_type, ANY_VALUE(MAJ_OPIN_WRITER_CODE) writer, ANY_VALUE(MAJ_OPIN_ASSIGNER_CODE) assigner,
       ANY_VALUE(MAJ_VOTES) maj_votes, ANY_VALUE(MIN_VOTES) min_votes, ANY_VALUE(US_CITATION) us_cite,
       COUNT(*) n_rows, COUNT(DISTINCT MAJ_VOTES, MIN_VOTES, PARTY_WINNING, DECISION_DIRECTION_CODE, TERM) n_variants
FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_SCDB
GROUP BY CASE_ID;

-- S11 SCDB: every justice vote, slim columns
SELECT CASE_ID, JUSTICE_CODE, JUSTICE_NAME, VOTE_CODE, OPINION_CODE, DIRECTION_CODE, MAJORITY_CODE, FIRST_AGREEMENT_CODE
FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_SCDB;
