SELECT TABLE_NAME, LISTAGG(COLUMN_NAME || ':' || DATA_TYPE, ', ') WITHIN GROUP (ORDER BY ORDINAL_POSITION) cols
FROM LIBRARY_MARTS.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'FINANCE' AND TABLE_NAME LIKE 'FINANCE__FED_SEC_13F%'
GROUP BY 1 ORDER BY 1
