WITH l AS (
  SELECT ACCESSION_NUMBER a, CUSIP, TRY_TO_DOUBLE(VALUE_COL) v, SSHPRNAMT sh
  FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_13F_SUBMISSION
  WHERE SSHPRNAMTTYPE = 'SH' AND NULLIF(TRIM(PUTCALL), '') IS NULL AND SSHPRNAMT > 0 AND TRY_TO_DOUBLE(VALUE_COL) > 0
), m AS (
  SELECT CUSIP, MEDIAN(v / sh) mp FROM l GROUP BY 1 HAVING COUNT(*) >= 20
), j AS (
  SELECT l.a, l.v, l.sh, (l.v / l.sh) / m.mp r FROM l JOIN m ON m.CUSIP = l.CUSIP
), x AS (
  SELECT a, COUNT(*) lines, COUNT_IF(r < 1/300) low, COUNT_IF(r > 300) high, SUM(v) v,
         SUM(IFF(r < 1/300, v, 0)) v_low, SUM(IFF(r > 300, v, 0)) v_high, MAX(IFF(r < 1/300, v, NULL)) max_low_v,
         MEDIAN(r) med_r, MEDIAN(IFF(r < 1/300, r, NULL)) med_r_low,
         COUNT_IF(r BETWEEN 0.0005 AND 0.002) near_k
  FROM j GROUP BY 1
), s AS (
  SELECT ACCESSION_NUMBER a, COUNT(*) s_n, ANY_VALUE(SUBMISSIONTYPE) st, ANY_VALUE(PERIODOFREPORT) per, ANY_VALUE(FILING_DATE) fd, ANY_VALUE(TRY_TO_NUMBER(CIK)) cik
  FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_13F_SUBMISSIONS WHERE ACCESSION_NUMBER IN (SELECT a FROM x) GROUP BY 1
), f AS (
  SELECT ACCESSION_NUMBER a, COUNT(*) f_n, ANY_VALUE(AMENDMENTTYPE) amt, ANY_VALUE(AMENDMENTNO) amn, ANY_VALUE(REPORTTYPE) rt, ANY_VALUE(FILINGMANAGER_NAME) nm
  FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_13F_FILERS WHERE ACCESSION_NUMBER IN (SELECT a FROM x) GROUP BY 1
)
SELECT x.*, s.s_n, s.st, s.per, s.fd, s.cik, f.f_n, f.amt, f.amn, f.rt, f.nm,
       (SELECT COUNT(*) FROM x) n_checked, (SELECT SUM(v) FROM x) v_all,
       (SELECT COUNT(*) FROM x JOIN s ON s.a = x.a WHERE s.st = '13F-HR' AND s.per = '31-MAR-2026') n_q1_orig_checked
FROM x LEFT JOIN s ON s.a = x.a LEFT JOIN f ON f.a = x.a
WHERE x.low > 0 OR x.high > 0
