WITH a AS (
  SELECT COUNT(*) n, COUNT(DISTINCT ACCESSION_NUMBER) acc,
         HASH_AGG(ACCESSION_NUMBER, INFOTABLE_SK, NAMEOFISSUER, TITLEOFCLASS, CUSIP, FIGI, VALUE_COL, SSHPRNAMT, SSHPRNAMTTYPE, PUTCALL, INVESTMENTDISCRETION, OTHERMANAGER, VOTING_AUTH_SOLE, VOTING_AUTH_SHARED, VOTING_AUTH_NONE) h_full,
         HASH_AGG(ACCESSION_NUMBER, CUSIP, VALUE_COL, SSHPRNAMT, SSHPRNAMTTYPE, PUTCALL) h_core
  FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_13F_SUBMISSION
), b AS (
  SELECT COUNT(*) n, COUNT(DISTINCT ACCESSION_NUMBER) acc,
         HASH_AGG(ACCESSION_NUMBER, INFOTABLE_SK, NAMEOFISSUER, TITLEOFCLASS, CUSIP, FIGI, VALUE_COL, SSHPRNAMT, SSHPRNAMTTYPE, PUTCALL, INVESTMENTDISCRETION, OTHERMANAGER, VOTING_AUTH_SOLE, VOTING_AUTH_SHARED, VOTING_AUTH_NONE) h_full,
         HASH_AGG(ACCESSION_NUMBER, CUSIP, VALUE_COL, SSHPRNAMT, SSHPRNAMTTYPE, PUTCALL) h_core,
         COUNT_IF(VALUE_USD <> TRY_TO_DOUBLE(VALUE_COL)) usd_ne_col, COUNT(DISTINCT VALUE_UNIT) units
  FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_13F_HOLDINGS WHERE SRC_FILE = '01mar2026-31may2026_form13f.zip'
)
SELECT 'SUBMISSION' t, a.n, a.acc, a.h_full, a.h_core, NULL usd_ne_col, NULL units FROM a
UNION ALL SELECT 'HOLDINGS_mar-may2026', b.n, b.acc, b.h_full, b.h_core, b.usd_ne_col, b.units FROM b
