WITH a AS (SELECT * FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_13F_SUBMISSION),
     b AS (SELECT * FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_13F_HOLDINGS WHERE SRC_FILE = '01mar2026-31may2026_form13f.zip')
SELECT 'SUBMISSION' t,
  HASH_AGG(ACCESSION_NUMBER) acc, HASH_AGG(INFOTABLE_SK) sk, HASH_AGG(NAMEOFISSUER) nm, HASH_AGG(TITLEOFCLASS) tc, HASH_AGG(CUSIP) cu, HASH_AGG(FIGI) fg,
  HASH_AGG(VALUE_COL) vc, HASH_AGG(SSHPRNAMT) sh, HASH_AGG(SSHPRNAMTTYPE) sht, HASH_AGG(PUTCALL) pc, HASH_AGG(INVESTMENTDISCRETION) inv, HASH_AGG(OTHERMANAGER) om,
  HASH_AGG(VOTING_AUTH_SOLE) vs, HASH_AGG(ACCESSION_NUMBER, INFOTABLE_SK) acc_sk, HASH_AGG(ACCESSION_NUMBER, CUSIP) acc_cu, HASH_AGG(ACCESSION_NUMBER, VALUE_COL) acc_v,
  COUNT_IF(PUTCALL IS NULL) pc_null, COUNT_IF(PUTCALL = '') pc_empty, COUNT_IF(FIGI IS NULL) fg_null, COUNT_IF(OTHERMANAGER IS NULL) om_null, SUM(SSHPRNAMT) sh_sum
FROM a
UNION ALL
SELECT 'HOLDINGS',
  HASH_AGG(ACCESSION_NUMBER), HASH_AGG(INFOTABLE_SK), HASH_AGG(NAMEOFISSUER), HASH_AGG(TITLEOFCLASS), HASH_AGG(CUSIP), HASH_AGG(FIGI),
  HASH_AGG(VALUE_COL), HASH_AGG(SSHPRNAMT), HASH_AGG(SSHPRNAMTTYPE), HASH_AGG(PUTCALL), HASH_AGG(INVESTMENTDISCRETION), HASH_AGG(OTHERMANAGER),
  HASH_AGG(VOTING_AUTH_SOLE), HASH_AGG(ACCESSION_NUMBER, INFOTABLE_SK), HASH_AGG(ACCESSION_NUMBER, CUSIP), HASH_AGG(ACCESSION_NUMBER, VALUE_COL),
  COUNT_IF(PUTCALL IS NULL), COUNT_IF(PUTCALL = ''), COUNT_IF(FIGI IS NULL), COUNT_IF(OTHERMANAGER IS NULL), SUM(SSHPRNAMT)
FROM b
