WITH l AS (
  SELECT ACCESSION_NUMBER a, CUSIP, TRY_TO_DOUBLE(VALUE_COL) v, SSHPRNAMT sh
  FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_13F_SUBMISSION
  WHERE SSHPRNAMTTYPE = 'SH' AND NULLIF(TRIM(PUTCALL), '') IS NULL AND SSHPRNAMT > 0 AND TRY_TO_DOUBLE(VALUE_COL) > 0
), m AS (SELECT CUSIP, MEDIAN(v / sh) mp FROM l GROUP BY 1 HAVING COUNT(*) >= 20),
x AS (SELECT l.a, COUNT(*) lines, COUNT_IF(l.v / l.sh < m.mp / 300) low FROM l JOIN m ON m.CUSIP = l.CUSIP GROUP BY 1),
t AS (SELECT ACCESSION_NUMBER a, SUM(TRY_TO_DOUBLE(VALUE_COL)) tot, COUNT(*) n FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_13F_SUBMISSION GROUP BY 1),
s AS (SELECT ACCESSION_NUMBER a, ANY_VALUE(SUBMISSIONTYPE) st, ANY_VALUE(PERIODOFREPORT) per FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_13F_SUBMISSIONS GROUP BY 1)
SELECT CASE WHEN x.a IS NULL THEN 'not_checked' WHEN x.low >= 0.5 * x.lines THEN 'flagged' ELSE 'clean' END grp,
       (s.st = '13F-HR' AND s.per = '31-MAR-2026') q1_orig,
       COUNT(*) filings, COUNT_IF(t.tot < 1e8) under_100m, COUNT_IF(t.tot < 1e7) under_10m, COUNT_IF(t.tot < 1e6) under_1m,
       MEDIAN(t.tot) med_tot, MEDIAN(t.n) med_lines, SUM(t.tot) sum_tot
FROM t LEFT JOIN x ON x.a = t.a LEFT JOIN s ON s.a = t.a
GROUP BY 1, 2 ORDER BY 1, 2
