WITH l AS (
  SELECT ACCESSION_NUMBER a, CUSIP, TRY_TO_DOUBLE(VALUE_COL) v, SSHPRNAMT sh
  FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_13F_SUBMISSION
  WHERE SSHPRNAMTTYPE = 'SH' AND NULLIF(TRIM(PUTCALL), '') IS NULL AND SSHPRNAMT > 0 AND TRY_TO_DOUBLE(VALUE_COL) > 0
), m AS (SELECT CUSIP, MEDIAN(v / sh) mp FROM l GROUP BY 1 HAVING COUNT(*) >= 20),
x AS (SELECT l.a, COUNT(*) lines, COUNT_IF(l.v / l.sh < m.mp / 300) low FROM l JOIN m ON m.CUSIP = l.CUSIP GROUP BY 1),
s AS (SELECT ACCESSION_NUMBER a, ANY_VALUE(TRY_TO_NUMBER(CIK)) cik FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_13F_SUBMISSIONS GROUP BY 1)
SELECT (TRY_TO_NUMBER(SPLIT_PART(x.a, '-', 1)) = s.cik) self_filed, SPLIT_PART(x.a, '-', 1) agent,
       COUNT(*) filings, COUNT_IF(x.low >= 0.5 * x.lines) flagged
FROM x LEFT JOIN s ON s.a = x.a
GROUP BY 1, 2 HAVING COUNT(*) >= 40 OR COUNT_IF(x.low >= 0.5 * x.lines) >= 5
ORDER BY flagged DESC
