
-- K01 [4 rows, 1.4s, qid 01c74c01-040b-a029-0026-eed30133bcee]
SELECT TABLE_NAME, LISTAGG(COLUMN_NAME || ':' || DATA_TYPE, ', ') WITHIN GROUP (ORDER BY ORDINAL_POSITION) cols
FROM LIBRARY_MARTS.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'FINANCE' AND TABLE_NAME LIKE 'FINANCE__FED_SEC_13F%'
GROUP BY 1 ORDER BY 1;

-- K02 [669 rows, 6.3s, qid 01c74c02-040b-a5bb-0026-eed30133fb62]
WITH l AS (
  SELECT ACCESSION_NUMBER a, CUSIP, TRY_TO_DOUBLE(VALUE_COL) v, SSHPRNAMT sh
  FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_13F_SUBMISSION
  WHERE SSHPRNAMTTYPE = 'SH' AND NULLIF(TRIM(PUTCALL), '') IS NULL AND SSHPRNAMT > 0 AND TRY_TO_DOUBLE(VALUE_COL) > 0
), m AS (
  SELECT CUSIP, MEDIAN(v / sh) mp FROM l GROUP BY 1 HAVING COUNT(*) >= 20
), j AS (
  SELECT l.a, l.v, l.sh, (l.v / l.sh) / m.mp r FROM l JOIN m ON m.CUSIP = l.CUSIP
), x AS (
  SELECT a, COUNT(*) lines, COUNT_IF(r < 1/300) low, COUNT_IF(r > 300) high, SUM(v) v,
         SUM(IFF(r < 1/300, v, 0)) v_low, SUM(IFF(r > 300, v, 0)) v_high, MAX(IFF(r < 1/300, v, NULL)) max_low_v,
         MEDIAN(r) med_r, MEDIAN(IFF(r < 1/300, r, NULL)) med_r_low,
         COUNT_IF(r BETWEEN 0.0005 AND 0.002) near_k
  FROM j GROUP BY 1
), s AS (
  SELECT ACCESSION_NUMBER a, COUNT(*) s_n, ANY_VALUE(SUBMISSIONTYPE) st, ANY_VALUE(PERIODOFREPORT) per, ANY_VALUE(FILING_DATE) fd, ANY_VALUE(TRY_TO_NUMBER(CIK)) cik
  FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_13F_SUBMISSIONS WHERE ACCESSION_NUMBER IN (SELECT a FROM x) GROUP BY 1
), f AS (
  SELECT ACCESSION_NUMBER a, COUNT(*) f_n, ANY_VALUE(AMENDMENTTYPE) amt, ANY_VALUE(AMENDMENTNO) amn, ANY_VALUE(REPORTTYPE) rt, ANY_VALUE(FILINGMANAGER_NAME) nm
  FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_13F_FILERS WHERE ACCESSION_NUMBER IN (SELECT a FROM x) GROUP BY 1
)
SELECT x.*, s.s_n, s.st, s.per, s.fd, s.cik, f.f_n, f.amt, f.amn, f.rt, f.nm,
       (SELECT COUNT(*) FROM x) n_checked, (SELECT SUM(v) FROM x) v_all,
       (SELECT COUNT(*) FROM x JOIN s ON s.a = x.a WHERE s.st = '13F-HR' AND s.per = '31-MAR-2026') n_q1_orig_checked
FROM x LEFT JOIN s ON s.a = x.a LEFT JOIN f ON f.a = x.a
WHERE x.low > 0 OR x.high > 0;

-- K03 [5170 rows, 12.1s, qid 01c74c03-040b-a6f8-0026-eed30134812e]
WITH l AS (
  SELECT SRC_FILE w, ACCESSION_NUMBER a, CUSIP, VALUE_USD v, SSHPRNAMT sh
  FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_13F_HOLDINGS
  WHERE VALUE_UNIT = 'dollars' AND SSHPRNAMTTYPE = 'SH' AND NULLIF(TRIM(PUTCALL), '') IS NULL AND SSHPRNAMT > 0 AND VALUE_USD > 0
), m AS (
  SELECT w, CUSIP, MEDIAN(v / sh) mp FROM l GROUP BY 1, 2 HAVING COUNT(*) >= 20
), x AS (
  SELECT l.w, l.a, COUNT(*) lines, COUNT_IF(l.v / l.sh < m.mp / 300) low, SUM(l.v) v,
         MEDIAN(IFF(l.v / l.sh < m.mp / 300, (l.v / l.sh) / m.mp, NULL)) med_r_low
  FROM l JOIN m ON m.w = l.w AND m.CUSIP = l.CUSIP GROUP BY 1, 2
), s AS (
  SELECT ACCESSION_NUMBER a, COUNT(*) s_n, ANY_VALUE(SUBMISSIONTYPE) st, ANY_VALUE(PERIODOFREPORT) per, ANY_VALUE(TRY_TO_NUMBER(CIK)) cik
  FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_13F_SUBMISSIONS GROUP BY 1
), xs AS (
  SELECT x.*, s.s_n, s.st, s.per, s.cik, COUNT(*) OVER (PARTITION BY x.a) n_windows,
         COUNT(*) OVER (PARTITION BY x.w) w_checked, COUNT_IF(s.st = '13F-HR') OVER (PARTITION BY x.w) w_hr_checked
  FROM x LEFT JOIN s ON s.a = x.a
)
SELECT * FROM xs WHERE low >= 0.5 * lines OR cik = 80255;

-- K04 [2 rows, 1.9s, qid 01c74c04-040b-a911-0026-eed301344ace]
WITH a AS (
  SELECT COUNT(*) n, COUNT(DISTINCT ACCESSION_NUMBER) acc,
         HASH_AGG(ACCESSION_NUMBER, INFOTABLE_SK, NAMEOFISSUER, TITLEOFCLASS, CUSIP, FIGI, VALUE_COL, SSHPRNAMT, SSHPRNAMTTYPE, PUTCALL, INVESTMENTDISCRETION, OTHERMANAGER, VOTING_AUTH_SOLE, VOTING_AUTH_SHARED, VOTING_AUTH_NONE) h_full,
         HASH_AGG(ACCESSION_NUMBER, CUSIP, VALUE_COL, SSHPRNAMT, SSHPRNAMTTYPE, PUTCALL) h_core
  FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_13F_SUBMISSION
), b AS (
  SELECT COUNT(*) n, COUNT(DISTINCT ACCESSION_NUMBER) acc,
         HASH_AGG(ACCESSION_NUMBER, INFOTABLE_SK, NAMEOFISSUER, TITLEOFCLASS, CUSIP, FIGI, VALUE_COL, SSHPRNAMT, SSHPRNAMTTYPE, PUTCALL, INVESTMENTDISCRETION, OTHERMANAGER, VOTING_AUTH_SOLE, VOTING_AUTH_SHARED, VOTING_AUTH_NONE) h_full,
         HASH_AGG(ACCESSION_NUMBER, CUSIP, VALUE_COL, SSHPRNAMT, SSHPRNAMTTYPE, PUTCALL) h_core,
         COUNT_IF(VALUE_USD <> TRY_TO_DOUBLE(VALUE_COL)) usd_ne_col, COUNT(DISTINCT VALUE_UNIT) units
  FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_13F_HOLDINGS WHERE SRC_FILE = '01mar2026-31may2026_form13f.zip'
)
SELECT 'SUBMISSION' t, a.n, a.acc, a.h_full, a.h_core, NULL usd_ne_col, NULL units FROM a
UNION ALL SELECT 'HOLDINGS_mar-may2026', b.n, b.acc, b.h_full, b.h_core, b.usd_ne_col, b.units FROM b;

-- K05 [2 rows, 1.1s, qid 01c74c04-040b-a028-0026-eed30133dc46]
WITH a AS (SELECT * FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_13F_SUBMISSION),
     b AS (SELECT * FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_13F_HOLDINGS WHERE SRC_FILE = '01mar2026-31may2026_form13f.zip')
SELECT 'SUBMISSION' t,
  HASH_AGG(ACCESSION_NUMBER) acc, HASH_AGG(INFOTABLE_SK) sk, HASH_AGG(NAMEOFISSUER) nm, HASH_AGG(TITLEOFCLASS) tc, HASH_AGG(CUSIP) cu, HASH_AGG(FIGI) fg,
  HASH_AGG(VALUE_COL) vc, HASH_AGG(SSHPRNAMT) sh, HASH_AGG(SSHPRNAMTTYPE) sht, HASH_AGG(PUTCALL) pc, HASH_AGG(INVESTMENTDISCRETION) inv, HASH_AGG(OTHERMANAGER) om,
  HASH_AGG(VOTING_AUTH_SOLE) vs, HASH_AGG(ACCESSION_NUMBER, INFOTABLE_SK) acc_sk, HASH_AGG(ACCESSION_NUMBER, CUSIP) acc_cu, HASH_AGG(ACCESSION_NUMBER, VALUE_COL) acc_v,
  COUNT_IF(PUTCALL IS NULL) pc_null, COUNT_IF(PUTCALL = '') pc_empty, COUNT_IF(FIGI IS NULL) fg_null, COUNT_IF(OTHERMANAGER IS NULL) om_null, SUM(SSHPRNAMT) sh_sum
FROM a
UNION ALL
SELECT 'HOLDINGS',
  HASH_AGG(ACCESSION_NUMBER), HASH_AGG(INFOTABLE_SK), HASH_AGG(NAMEOFISSUER), HASH_AGG(TITLEOFCLASS), HASH_AGG(CUSIP), HASH_AGG(FIGI),
  HASH_AGG(VALUE_COL), HASH_AGG(SSHPRNAMT), HASH_AGG(SSHPRNAMTTYPE), HASH_AGG(PUTCALL), HASH_AGG(INVESTMENTDISCRETION), HASH_AGG(OTHERMANAGER),
  HASH_AGG(VOTING_AUTH_SOLE), HASH_AGG(ACCESSION_NUMBER, INFOTABLE_SK), HASH_AGG(ACCESSION_NUMBER, CUSIP), HASH_AGG(ACCESSION_NUMBER, VALUE_COL),
  COUNT_IF(PUTCALL IS NULL), COUNT_IF(PUTCALL = ''), COUNT_IF(FIGI IS NULL), COUNT_IF(OTHERMANAGER IS NULL), SUM(SSHPRNAMT)
FROM b;

-- K06 [6 rows, 2.4s, qid 01c74c06-040b-a770-0026-eed3013471be]
WITH l AS (
  SELECT ACCESSION_NUMBER a, CUSIP, TRY_TO_DOUBLE(VALUE_COL) v, SSHPRNAMT sh
  FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_13F_SUBMISSION
  WHERE SSHPRNAMTTYPE = 'SH' AND NULLIF(TRIM(PUTCALL), '') IS NULL AND SSHPRNAMT > 0 AND TRY_TO_DOUBLE(VALUE_COL) > 0
), m AS (SELECT CUSIP, MEDIAN(v / sh) mp FROM l GROUP BY 1 HAVING COUNT(*) >= 20),
x AS (SELECT l.a, COUNT(*) lines, COUNT_IF(l.v / l.sh < m.mp / 300) low FROM l JOIN m ON m.CUSIP = l.CUSIP GROUP BY 1),
t AS (SELECT ACCESSION_NUMBER a, SUM(TRY_TO_DOUBLE(VALUE_COL)) tot, COUNT(*) n FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_13F_SUBMISSION GROUP BY 1),
s AS (SELECT ACCESSION_NUMBER a, ANY_VALUE(SUBMISSIONTYPE) st, ANY_VALUE(PERIODOFREPORT) per FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_13F_SUBMISSIONS GROUP BY 1)
SELECT CASE WHEN x.a IS NULL THEN 'not_checked' WHEN x.low >= 0.5 * x.lines THEN 'flagged' ELSE 'clean' END grp,
       (s.st = '13F-HR' AND s.per = '31-MAR-2026') q1_orig,
       COUNT(*) filings, COUNT_IF(t.tot < 1e8) under_100m, COUNT_IF(t.tot < 1e7) under_10m, COUNT_IF(t.tot < 1e6) under_1m,
       MEDIAN(t.tot) med_tot, MEDIAN(t.n) med_lines, SUM(t.tot) sum_tot
FROM t LEFT JOIN x ON x.a = t.a LEFT JOIN s ON s.a = t.a
GROUP BY 1, 2 ORDER BY 1, 2;

-- K07 [21 rows, 3.1s, qid 01c74c07-040b-a07c-0026-eed30133ecbe]
WITH l AS (
  SELECT ACCESSION_NUMBER a, CUSIP, TRY_TO_DOUBLE(VALUE_COL) v, SSHPRNAMT sh
  FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_13F_SUBMISSION
  WHERE SSHPRNAMTTYPE = 'SH' AND NULLIF(TRIM(PUTCALL), '') IS NULL AND SSHPRNAMT > 0 AND TRY_TO_DOUBLE(VALUE_COL) > 0
), m AS (SELECT CUSIP, MEDIAN(v / sh) mp FROM l GROUP BY 1 HAVING COUNT(*) >= 20),
x AS (SELECT l.a, COUNT(*) lines, COUNT_IF(l.v / l.sh < m.mp / 300) low FROM l JOIN m ON m.CUSIP = l.CUSIP GROUP BY 1),
s AS (SELECT ACCESSION_NUMBER a, ANY_VALUE(TRY_TO_NUMBER(CIK)) cik FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_13F_SUBMISSIONS GROUP BY 1)
SELECT (TRY_TO_NUMBER(SPLIT_PART(x.a, '-', 1)) = s.cik) self_filed, SPLIT_PART(x.a, '-', 1) agent,
       COUNT(*) filings, COUNT_IF(x.low >= 0.5 * x.lines) flagged
FROM x LEFT JOIN s ON s.a = x.a
GROUP BY 1, 2 HAVING COUNT(*) >= 40 OR COUNT_IF(x.low >= 0.5 * x.lines) >= 5
ORDER BY flagged DESC;
