{{ config(materialized='view') }}

/*
  Generated 2026-08-09 (73-source backlog, wave 2c) from live-verified specs.
  NTSB aviation accident database, aircraft table: one row per aircraft involved in an event (ev_id + aircraft_key unique). Registration, make/model, owner/operator, certification.
  Grain: one row = one aircraft in one event.
*/

with source as (
    select * from {{ source('ripple_raw', 'FED_NTSB_AVIATION_AIRCRAFT') }}
),

renamed as (
    select
        nullif(trim(EV_ID), '')                                    as ev_id,
        nullif(trim(AIRCRAFT_KEY), '')                             as aircraft_key,
        nullif(trim(REGIS_NO), '')                                 as regis_no,
        nullif(trim(NTSB_NO), '')                                  as ntsb_no,
        nullif(trim(ACFT_MISSING), '')                             as acft_missing,
        nullif(trim(FAR_PART), '')                                 as far_part,
        nullif(trim(FLT_PLAN_FILED), '')                           as flt_plan_filed,
        nullif(trim(FLIGHT_PLAN_ACTIVATED), '')                    as flight_plan_activated,
        nullif(trim(DAMAGE), '')                                   as damage,
        nullif(trim(ACFT_FIRE), '')                                as acft_fire,
        nullif(trim(ACFT_EXPL), '')                                as acft_expl,
        nullif(trim(ACFT_MAKE), '')                                as acft_make,
        nullif(trim(ACFT_MODEL), '')                               as acft_model,
        nullif(trim(ACFT_SERIES), '')                              as acft_series,
        nullif(trim(ACFT_SERIAL_NO), '')                           as acft_serial_no,
        nullif(trim(CERT_MAX_GR_WT), '')                           as cert_max_gr_wt,
        nullif(trim(ACFT_CATEGORY), '')                            as acft_category,
        nullif(trim(ACFT_REG_CLS), '')                             as acft_reg_cls,
        nullif(trim(HOMEBUILT), '')                                as homebuilt,
        nullif(trim(FC_SEATS), '')                                 as fc_seats,
        nullif(trim(CC_SEATS), '')                                 as cc_seats,
        nullif(trim(PAX_SEATS), '')                                as pax_seats,
        nullif(trim(TOTAL_SEATS), '')                              as total_seats,
        nullif(trim(NUM_ENG), '')                                  as num_eng,
        nullif(trim(FIXED_RETRACTABLE), '')                        as fixed_retractable,
        nullif(trim(TYPE_LAST_INSP), '')                           as type_last_insp,
        try_to_date(left(nullif(trim(DATE_LAST_INSP), ''), 10))    as date_last_insp,
        nullif(trim(AFM_HRS_LAST_INSP), '')                        as afm_hrs_last_insp,
        nullif(trim(AFM_HRS), '')                                  as afm_hrs,
        nullif(trim(ELT_INSTALL), '')                              as elt_install,
        nullif(trim(ELT_OPER), '')                                 as elt_oper,
        nullif(trim(ELT_AIDED_LOC_EV), '')                         as elt_aided_loc_ev,
        nullif(trim(ELT_TYPE), '')                                 as elt_type,
        nullif(trim(OWNER_ACFT), '')                               as owner_acft,
        nullif(trim(OWNER_STREET), '')                             as owner_street,
        nullif(trim(OWNER_CITY), '')                               as owner_city,
        nullif(trim(OWNER_STATE), '')                              as owner_state,
        nullif(trim(OWNER_COUNTRY), '')                            as owner_country,
        nullif(trim(OWNER_ZIP), '')                                as owner_zip,
        nullif(trim(OPER_INDIVIDUAL_NAME), '')                     as oper_individual_name,
        nullif(trim(OPER_NAME), '')                                as oper_name,
        nullif(trim(OPER_SAME), '')                                as oper_same,
        nullif(trim(OPER_DBA), '')                                 as oper_dba,
        nullif(trim(OPER_ADDR_SAME), '')                           as oper_addr_same,
        nullif(trim(OPER_STREET), '')                              as oper_street,
        nullif(trim(OPER_CITY), '')                                as oper_city,
        nullif(trim(OPER_STATE), '')                               as oper_state,
        nullif(trim(OPER_COUNTRY), '')                             as oper_country,
        nullif(trim(OPER_ZIP), '')                                 as oper_zip,
        nullif(trim(OPER_CODE), '')                                as oper_code,
        nullif(trim(CERTS_HELD), '')                               as certs_held,
        nullif(trim(OPRTNG_CERT), '')                              as oprtng_cert,
        nullif(trim(OPER_CERT), '')                                as oper_cert,
        nullif(trim(OPER_CERT_NUM), '')                            as oper_cert_num,
        nullif(trim(OPER_SCHED), '')                               as oper_sched,
        nullif(trim(OPER_DOM_INT), '')                             as oper_dom_int,
        nullif(trim(OPER_PAX_CARGO), '')                           as oper_pax_cargo,
        nullif(trim(TYPE_FLY), '')                                 as type_fly,
        nullif(trim(SECOND_PILOT), '')                             as second_pilot,
        nullif(trim(DPRT_PT_SAME_EV), '')                          as dprt_pt_same_ev,
        nullif(trim(DPRT_APT_ID), '')                              as dprt_apt_id,
        nullif(trim(DPRT_CITY), '')                                as dprt_city,
        nullif(trim(DPRT_STATE), '')                               as dprt_state,
        nullif(trim(DPRT_COUNTRY), '')                             as dprt_country,
        nullif(trim(DPRT_TIME), '')                                as dprt_time,
        nullif(trim(DPRT_TIMEZN), '')                              as dprt_timezn,
        nullif(trim(DEST_SAME_LOCAL), '')                          as dest_same_local,
        nullif(trim(DEST_APT_ID), '')                              as dest_apt_id,
        nullif(trim(DEST_CITY), '')                                as dest_city,
        nullif(trim(DEST_STATE), '')                               as dest_state,
        nullif(trim(DEST_COUNTRY), '')                             as dest_country,
        nullif(trim(PHASE_FLT_SPEC), '')                           as phase_flt_spec,
        nullif(trim(REPORT_TO_ICAO), '')                           as report_to_icao,
        nullif(trim(EVACUATION), '')                               as evacuation,
        try_to_date(left(nullif(trim(LCHG_DATE), ''), 10))         as lchg_date,
        nullif(trim(LCHG_USERID), '')                              as lchg_userid,
        nullif(trim(AFM_HRS_SINCE), '')                            as afm_hrs_since,
        nullif(trim(RWY_NUM), '')                                  as rwy_num,
        nullif(trim(RWY_LEN), '')                                  as rwy_len,
        nullif(trim(RWY_WIDTH), '')                                as rwy_width,
        nullif(trim(SITE_SEEING), '')                              as site_seeing,
        nullif(trim(AIR_MEDICAL), '')                              as air_medical,
        nullif(trim(MED_TYPE_FLIGHT), '')                          as med_type_flight,
        nullif(trim(ACFT_YEAR), '')                                as acft_year,
        nullif(trim(FUEL_ON_BOARD), '')                            as fuel_on_board,
        nullif(trim(COMMERCIAL_SPACE_FLIGHT), '')                  as commercial_space_flight,
        nullif(trim(UNMANNED), '')                                 as unmanned,
        nullif(trim(IFR_EQUIPPED_CERT), '')                        as ifr_equipped_cert,
        nullif(trim(ELT_MOUNTED_AIRCRAFT), '')                     as elt_mounted_aircraft,
        nullif(trim(ELT_CONNECTED_ANTENNA), '')                    as elt_connected_antenna,
        nullif(trim(ELT_MANUFACTURER), '')                         as elt_manufacturer,
        nullif(trim(ELT_MODEL), '')                                as elt_model,
        nullif(trim(ELT_REASON_OTHER), '')                         as elt_reason_other,
        to_timestamp_ntz(INGESTED_AT, 6)                           as _ingested_at,
        nullif(trim(SOURCE_RUN_ID), '')                            as _source_run_id
    from source
)

select * from renamed
