SELECT TABLE_SCHEMA, TABLE_NAME, LISTAGG(COLUMN_NAME || ':' || DATA_TYPE, ', ') WITHIN GROUP (ORDER BY ORDINAL_POSITION) cols
FROM LIBRARY_MARTS.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME ILIKE '%UK_COMPAN%' OR TABLE_NAME ILIKE '%COMPANIES_HOUSE%' OR (COLUMN_NAME ILIKE '%COMPANY_NUMBER%' OR COLUMN_NAME ILIKE '%COMPANIES_HOUSE%' OR COLUMN_NAME ILIKE 'CRN')
GROUP BY 1,2 ORDER BY 1,2
