WITH p AS (SELECT * FROM LIBRARY_MARTS.CORPORATE_REGISTRY.CORPORATE_REGISTRY__UK_COMPANIES_HOUSE_PSC),
live AS (
  SELECT COMPANY_NUMBER, INCORPORATION_DATE d
  FROM LIBRARY_MARTS.CORPORATE_REGISTRY.CORPORATE_REGISTRY__INTL_UK_COMPANIES_HOUSE
  WHERE INCORPORATION_DATE BETWEEN '2025-09-01' AND '2026-06-30' AND COMPANY_NUMBER RLIKE '[0-9]{8}'),
pc AS (SELECT DISTINCT COMPANY_NUMBER FROM p)
SELECT * FROM (
  SELECT 'load' k, COALESCE(_SOURCE_RUN_ID,'null') v, COUNT(*) n, COUNT(DISTINCT COMPANY_NUMBER) k2,
         MIN(_INGESTED_AT)::string a, MAX(_INGESTED_AT)::string b FROM p GROUP BY 1,2
  UNION ALL SELECT 'kind', KIND, COUNT(*), COUNT(DISTINCT COMPANY_NUMBER), MIN(NOTIFIED_ON)::string, MAX(NOTIFIED_ON)::string FROM p GROUP BY 1,2
  UNION ALL SELECT 'numeric_max', 'max numeric company number / max notified <= 2026-09-24', COUNT(*), MAX(TRY_TO_NUMBER(IFF(COMPANY_NUMBER RLIKE '[0-9]{8}', COMPANY_NUMBER, NULL))), MAX(IFF(NOTIFIED_ON <= '2026-09-24', NOTIFIED_ON, NULL))::string, COUNT_IF(NOTIFIED_ON > '2026-07-27')::string FROM p
  UNION ALL SELECT 'notified_month', TO_CHAR(DATE_TRUNC('month', NOTIFIED_ON), 'YYYY-MM'), COUNT(*), COUNT(DISTINCT COMPANY_NUMBER), NULL, NULL FROM p WHERE NOTIFIED_ON >= '2025-09-01' GROUP BY 1,2
  UNION ALL SELECT 'live_in_psc_by_week', TO_CHAR(DATE_TRUNC('week', live.d), 'YYYY-MM-DD'), COUNT(*), COUNT(pc.COMPANY_NUMBER), NULL, NULL
    FROM live LEFT JOIN pc USING (COMPANY_NUMBER) GROUP BY 1,2
) ORDER BY k, v
