WITH nums AS (SELECT 16858919 + ROW_NUMBER() OVER (ORDER BY SEQ4()) - 1 n FROM TABLE(GENERATOR(ROWCOUNT => 65644))),
live AS (SELECT TRY_TO_NUMBER(REGEXP_REPLACE(COMPANY_NUMBER, '[^0-9]', '')) n, COMPANY_NUMBER raw, INCORPORATION_DATE d
         FROM LIBRARY_MARTS.CORPORATE_REGISTRY.CORPORATE_REGISTRY__INTL_UK_COMPANIES_HOUSE
         WHERE TRY_TO_NUMBER(REGEXP_REPLACE(COMPANY_NUMBER, '[^0-9]', '')) BETWEEN 16858919 AND 16924562),
psc AS (SELECT DISTINCT TRY_TO_NUMBER(REGEXP_REPLACE(COMPANY_NUMBER, '[^0-9]', '')) n
        FROM LIBRARY_MARTS.CORPORATE_REGISTRY.CORPORATE_REGISTRY__UK_COMPANIES_HOUSE_PSC
        WHERE TRY_TO_NUMBER(REGEXP_REPLACE(COMPANY_NUMBER, '[^0-9]', '')) BETWEEN 16858919 AND 16924562),
h AS (SELECT n FROM nums WHERE n NOT IN (SELECT n FROM live WHERE n IS NOT NULL) AND n NOT IN (SELECT n FROM psc WHERE n IS NOT NULL)),
hd AS (SELECT h.n, (SELECT MAX(d) FROM live WHERE live.n < h.n) d_before FROM h)
SELECT * FROM (
  SELECT 'fmt_live' k, IFF(raw RLIKE '[0-9]{8}', 'clean8', 'odd:' || raw) v, COUNT(*) n, NULL::string d FROM live GROUP BY 1,2
  UNION ALL SELECT 'holes_total', 'window 16858919-16924562', COUNT(*), NULL FROM h
  UNION ALL SELECT 'sample', LPAD(n::string, 8, '0'), 1, d_before::string FROM hd
    QUALIFY ROW_NUMBER() OVER (ORDER BY HASH(n)) <= 40
) ORDER BY k, v
