WITH live AS (
  SELECT TRY_TO_NUMBER(COMPANY_NUMBER) n, INCORPORATION_DATE d
  FROM LIBRARY_MARTS.CORPORATE_REGISTRY.CORPORATE_REGISTRY__INTL_UK_COMPANIES_HOUSE
  WHERE COMPANY_NUMBER RLIKE '[0-9]{8}' AND TRY_TO_NUMBER(COMPANY_NUMBER) BETWEEN 16000242 AND 16223570),
pscn AS (
  SELECT DISTINCT TRY_TO_NUMBER(COMPANY_NUMBER) n
  FROM LIBRARY_MARTS.CORPORATE_REGISTRY.CORPORATE_REGISTRY__UK_COMPANIES_HOUSE_PSC
  WHERE COMPANY_NUMBER RLIKE '[0-9]{8}' AND TRY_TO_NUMBER(COMPANY_NUMBER) BETWEEN 16000242 AND 16223570),
allp AS (SELECT n, 1 is_live FROM live UNION ALL SELECT n, 0 FROM pscn WHERE n NOT IN (SELECT n FROM live)),
dr AS (SELECT d, MIN(n) lo, MAX(n) hi FROM live GROUP BY d),
j AS (SELECT dr.d, dr.lo, dr.hi, a.n, a.is_live FROM allp a JOIN dr ON a.n BETWEEN dr.lo AND dr.hi),
daily AS (SELECT d, MAX(hi) - MIN(lo) + 1 numbers, SUM(is_live) live, COUNT_IF(is_live = 0) psc_only, MAX(hi) - MIN(lo) + 1 - COUNT(*) holes FROM j GROUP BY d),
mon AS (
  SELECT DATE_TRUNC('month', INCORPORATION_DATE) m, MIN(TRY_TO_NUMBER(COMPANY_NUMBER)) lo, MAX(TRY_TO_NUMBER(COMPANY_NUMBER)) hi, COUNT(*) live
  FROM LIBRARY_MARTS.CORPORATE_REGISTRY.CORPORATE_REGISTRY__INTL_UK_COMPANIES_HOUSE
  WHERE COMPANY_NUMBER RLIKE '[0-9]{8}' AND INCORPORATION_DATE BETWEEN '2023-01-01' AND '2026-06-30'
    AND TRY_TO_NUMBER(COMPANY_NUMBER) > 14000000
  GROUP BY 1)
SELECT 'win2024' k,
       CASE WHEN d BETWEEN '2024-10-07' AND '2024-11-17' THEN 'a_pre_7oct_17nov'
            WHEN d BETWEEN '2024-11-18' AND '2024-12-22' THEN 'b_post_18nov_22dec'
            WHEN d BETWEEN '2025-01-06' AND '2025-02-02' THEN 'c_jan_6jan_2feb' ELSE 'x' END v,
       SUM(numbers) numbers, SUM(live) live, SUM(psc_only) psc_only, SUM(holes) holes, COUNT(*) days
FROM daily GROUP BY 1,2
UNION ALL
SELECT 'month', TO_CHAR(m, 'YYYY-MM'), hi - lo + 1, live, lo, hi, NULL FROM mon
ORDER BY 1, 2
