{{ config(materialized='view', schema='TIMELINE', alias='JUSTICE__XC_MAPPING_POLICE_VIOLENCE') }}

-- GENERATED by scripts/census/gen_time_views.py -- do not hand-edit.
-- Regenerate after any change to reports/time_index/clock_index.csv.
--
-- Canonical clock for JUSTICE.JUSTICE__XC_MAPPING_POLICE_VIOLENCE.
--   column : DATE_OF_INCIDENT_MONTH_DAY_YEAR   (DATE)
--   means  : happened -- try_to_date(DATE_OF_INCIDENT_MONTH_DAY_YEAR) -- the day the killing occurred.
--   grain  : day
--
-- The original columns pass through untouched; the canonical four sit in front
-- of them. Rule 8 of the datetime standard: the raw column is never overwritten,
-- so a mis-parse is always recoverable.

select
    {{ ripple_event_ts(ripple_window('src."DATE_OF_INCIDENT_MONTH_DAY_YEAR"::timestamp_ntz')) }} as ripple_ts,
    {{ ripple_grain('day') }} as ripple_grain,
    {{ ripple_clock('happened') }} as ripple_clock,
    'JUSTICE.JUSTICE__XC_MAPPING_POLICE_VIOLENCE'::varchar as ripple_source,
    src.*
from {{ ref('justice__xc_mapping_police_violence') }} as src
