{{ config(materialized='view', schema='TIMELINE', alias='JUSTICE__FED_COURTLISTENER_DOCKETS') }}

-- GENERATED by scripts/census/gen_time_views.py -- do not hand-edit.
-- Regenerate after any change to reports/time_index/clock_index.csv.
--
-- Canonical clock for JUSTICE.JUSTICE__FED_COURTLISTENER_DOCKETS.
--   column : DATE_ARGUED   (DATE)
--   means  : happened -- try_to_date(DATE_ARGUED): the day oral argument actually took place.
--   grain  : day
--
-- The original columns pass through untouched; the canonical four sit in front
-- of them. Rule 8 of the datetime standard: the raw column is never overwritten,
-- so a mis-parse is always recoverable.

select
    {{ ripple_event_ts(ripple_window('src."DATE_ARGUED"::timestamp_ntz')) }} as ripple_ts,
    {{ ripple_grain('day') }} as ripple_grain,
    {{ ripple_clock('happened') }} as ripple_clock,
    'JUSTICE.JUSTICE__FED_COURTLISTENER_DOCKETS'::varchar as ripple_source,
    src.*
from {{ ref('justice__fed_courtlistener_dockets') }} as src
