{{ config(materialized='view', schema='TIMELINE', alias='JUSTICE__FED_CISA_KEV') }}

-- GENERATED by scripts/census/gen_time_views.py -- do not hand-edit.
-- Regenerate after any change to reports/time_index/clock_index.csv.
--
-- Canonical clock for JUSTICE.JUSTICE__FED_CISA_KEV.
--   column : DATE_ADDED   (DATE)
--   means  : decided -- try_to_date(DATE_ADDED): the date CISA added the vulnerability to the Known Exploited Vulnerabilities catalog -- an agency designation act.
--   grain  : day
--
-- decided cannot be in the future -- if this row's value is, ripple_clock
-- reads 'planned' instead, not 'decided'. See ripple_row_clock in
-- macros/ripple_time.sql.
--
-- The original columns pass through untouched; the canonical four sit in front
-- of them. Rule 8 of the datetime standard: the raw column is never overwritten,
-- so a mis-parse is always recoverable.

select
    {{ ripple_window('src."DATE_ADDED"::timestamp_ntz') }} as ripple_ts,
    {{ ripple_grain('day') }} as ripple_grain,
    {{ ripple_row_clock(ripple_window('src."DATE_ADDED"::timestamp_ntz'), 'decided') }} as ripple_clock,
    'JUSTICE.JUSTICE__FED_CISA_KEV'::varchar as ripple_source,
    src.*
from {{ ref('justice__fed_cisa_kev') }} as src
