{{ config(materialized='view', schema='TIMELINE', alias='JUSTICE__FED_FBI_NICS_CHECKS') }}

-- GENERATED by scripts/census/gen_time_views.py -- do not hand-edit.
-- Regenerate after any change to reports/time_index/clock_index.csv.
--
-- Canonical clock for JUSTICE.JUSTICE__FED_FBI_NICS_CHECKS.
--   column : MONTH   (TEXT)
--   means  : happened -- "MONTH" is a raw text passthrough (no cast in either the mart or the minimal staging view); the file is a state x month panel of background checks, so it marks 
--   grain  : month
--
-- The original columns pass through untouched; the canonical four sit in front
-- of them. Rule 8 of the datetime standard: the raw column is never overwritten,
-- so a mis-parse is always recoverable.

select
    {{ ripple_event_ts(ripple_ts_from_yyyymm('src."MONTH"')) }} as ripple_ts,
    {{ ripple_grain('month') }} as ripple_grain,
    {{ ripple_clock('happened') }} as ripple_clock,
    'JUSTICE.JUSTICE__FED_FBI_NICS_CHECKS'::varchar as ripple_source,
    src.*
from {{ ref('justice__fed_fbi_nics_checks') }} as src
