{{ config(materialized='view', schema='TIMELINE', alias='JUSTICE__FED_COURTLISTENER_JUDGES') }}

-- GENERATED by scripts/census/gen_time_views.py -- do not hand-edit.
-- Regenerate after any change to reports/time_index/clock_index.csv.
--
-- Canonical clock for JUSTICE.JUSTICE__FED_COURTLISTENER_JUDGES.
--   column : DATE_DOB   (DATE)
--   means  : happened -- try_to_date(DATE_DOB): the judge's date of birth -- the only real-world event on a person row, so it is the timeline anchor for this table.
--   grain  : day
--
-- happened cannot be in the future -- if this row's value is, ripple_clock
-- reads 'planned' instead, not 'happened'. See ripple_row_clock in
-- macros/ripple_time.sql.
--
-- The original columns pass through untouched; the canonical four sit in front
-- of them. Rule 8 of the datetime standard: the raw column is never overwritten,
-- so a mis-parse is always recoverable.

select
    {{ ripple_window('src."DATE_DOB"::timestamp_ntz') }} as ripple_ts,
    {{ ripple_grain('day') }} as ripple_grain,
    {{ ripple_row_clock(ripple_window('src."DATE_DOB"::timestamp_ntz'), 'happened') }} as ripple_clock,
    'JUSTICE.JUSTICE__FED_COURTLISTENER_JUDGES'::varchar as ripple_source,
    src.*
from {{ ref('justice__fed_courtlistener_judges') }} as src
