{{ config(tags=['spine_generated']) }}

-- GRAIN: one row per place (LATLON is unique)
-- SPINE_ENTITY: place  (natural_key: LATITUDE)
-- Generated by scripts/generate_staging_models.py from SOURCE_REGISTRY -- deterministic,
-- no LLM. Casts kept as landed (TEXT) -- add explicit type casts by hand once each
-- column's real type is confirmed; this generator has no semantic type knowledge.
-- spine_entity 'place' has no connect/ resolver yet (see connect/spine_entity.py) -- no SPINE_ENTITY_ID emitted.
-- landing table's ingestion timestamp is named INGESTED_AT (no leading underscore) rather than the usual _INGESTED_AT -- confirmed via INFORMATION_SCHEMA, not assumed.

with source as (

    select * from {{ source('ripple_raw', 'PORTAL_ARC_VERMONT_OPEN_GEO_62F10327D4') }}

),

renamed as (

    select
        "VTAOE_ID" as vtaoe_id,
        "SCHOOL" as school,
        "ADDRESS" as address,
        "GRADES" as grades,
        "ENROLLMENT" as enrollment,
        "ENROLLMENTYEAR" as enrollmentyear,
        "ENROLLMENTCAT" as enrollmentcat,
        "ENROLLMENTFY13_K_12" as enrollmentfy13_k_12,
        "CHANGEPERCENT2013_2023" as changepercent2013_2023,
        "PCB_TESTING_STATUS" as pcb_testing_status,
        "PCB_NGM3" as pcb_ngm3,
        "PCB_CAT" as pcb_cat,
        "YEAR_BUILT_MAIN" as year_built_main,
        "CONDITION_INDEX_5YEAR" as condition_index_5year,
        "OTHER_BUILDINGS" as other_buildings,
        "NCES_SCHOOL_ID" as nces_school_id,
        "NCES_DISTRICT_ID" as nces_district_id,
        "DISTRICT_ID" as district_id,
        "DISTRICT" as district,
        "COUNTY" as county,
        "VTAOE_SUID" as vtaoe_suid,
        "SU_NAME" as su_name,
        "PUBLICPRIVATE" as publicprivate,
        "MAPID" as mapid,
        "TYPE" as type,
        "STATUS" as status,
        "LONGITUDE" as longitude,
        "LATITUDE" as latitude,
        "TOWNNAME" as townname,
        "TOWNNAMEMC" as townnamemc,
        "TOWNGEOID" as towngeoid,
        "FID" as fid,
        "GEOMETRY" as geometry,
        INGESTED_AT as _loaded_at,
        'https://geodata.vermont.gov/datasets/bd6b675967da4a7ca56876f4f2745184_0' as _source_url

    from source

)

select * from renamed
qualify row_number() over (partition by latitude order by _loaded_at desc) = 1
