-- NPPES: every Texas organization NPI with a hospice taxonomy (251G00000X) in slots 1-5, with authorized official and practice address/phone
select NPI, PROVIDER_ORGANIZATION_NAME_LEGAL_BUSINESS_NAME lbn, PROVIDER_OTHER_ORGANIZATION_NAME dba,
  PROVIDER_FIRST_LINE_BUSINESS_PRACTICE_LOCATION_ADDRESS a1, PROVIDER_SECOND_LINE_BUSINESS_PRACTICE_LOCATION_ADDRESS a2,
  PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_CITY_NAME city, left(PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_POSTAL_CODE,5) zip,
  regexp_replace(PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_TELEPHONE_NUMBER,'[^0-9]','') ph,
  PROVIDER_FIRST_LINE_BUSINESS_MAILING_ADDRESS m1, PROVIDER_ENUMERATION_DATE enum_dt, NPI_DEACTIVATION_DATE deact_dt, LAST_UPDATE_DATE upd,
  upper(trim(AUTHORIZED_OFFICIAL_FIRST_NAME)) ao_first, upper(trim(AUTHORIZED_OFFICIAL_MIDDLE_NAME)) ao_mid, upper(trim(AUTHORIZED_OFFICIAL_LAST_NAME)) ao_last,
  AUTHORIZED_OFFICIAL_TITLE_OR_POSITION ao_title, regexp_replace(AUTHORIZED_OFFICIAL_TELEPHONE_NUMBER,'[^0-9]','') ao_ph,
  IS_ORGANIZATION_SUBPART sub, PARENT_ORGANIZATION_LBN parent
from LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_NPPES
where ENTITY_TYPE_CODE in ('2','2.0') and PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_STATE_NAME='TX'
  and '251G00000X' in (HEALTHCARE_PROVIDER_TAXONOMY_CODE_1, HEALTHCARE_PROVIDER_TAXONOMY_CODE_2, HEALTHCARE_PROVIDER_TAXONOMY_CODE_3, HEALTHCARE_PROVIDER_TAXONOMY_CODE_4, HEALTHCARE_PROVIDER_TAXONOMY_CODE_5)
