-- NPPES national: every organization NPI with hospice taxonomy 251G00000X in slots 1-5 (peer group for "one official, many hospices, one building")
select NPI, PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_STATE_NAME st, upper(trim(PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_CITY_NAME)) city,
  upper(PROVIDER_FIRST_LINE_BUSINESS_PRACTICE_LOCATION_ADDRESS) a1, upper(coalesce(PROVIDER_SECOND_LINE_BUSINESS_PRACTICE_LOCATION_ADDRESS,'')) a2,
  regexp_replace(PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_TELEPHONE_NUMBER,'[^0-9]','') ph,
  PROVIDER_ORGANIZATION_NAME_LEGAL_BUSINESS_NAME lbn, PROVIDER_ENUMERATION_DATE enum_dt, NPI_DEACTIVATION_DATE deact_dt,
  upper(trim(AUTHORIZED_OFFICIAL_FIRST_NAME)) ao_first, upper(trim(AUTHORIZED_OFFICIAL_LAST_NAME)) ao_last, IS_ORGANIZATION_SUBPART sub
from LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_NPPES
where ENTITY_TYPE_CODE in ('2','2.0')
  and '251G00000X' in (HEALTHCARE_PROVIDER_TAXONOMY_CODE_1, HEALTHCARE_PROVIDER_TAXONOMY_CODE_2, HEALTHCARE_PROVIDER_TAXONOMY_CODE_3, HEALTHCARE_PROVIDER_TAXONOMY_CODE_4, HEALTHCARE_PROVIDER_TAXONOMY_CODE_5)
