-- (rerun 2: Snowflake string needs \\b for a regex word boundary; rerun 1: 150K table uses unseparated column names) federal money by name: PPP loans (both tables) and USAspending assistance to Texas recipients whose normalized name equals a cluster legal/brand name (83 keys); city shown for the second-field check
with k(nk) as (select * from values ('ABIBHOSPICECARE'),('ABOVEBEYONDHOSPICE'),('ACACIAHOSPICE'),('ADVANCEDHOLISTICPALLIATIVECARE'),('ALDERHOSPICE'),('ALLFAITHHOSPICECARE'),('ALTAVITAHOSPICE'),('AMAZINGLYGRACEHOSPICE'),('ANCHOREDBYGRACEHOSPICECARE'),('ARIELHOSPICE'),('ARMSOFCOMPASSIONHOSPICECARE'),('ASHHOSPICE'),('BALSAMHOSPICE'),('BEXARHOSPICE'),('BIRCHHOSPICE'),('BLUEROSEHOSPICEANDPALLIATIVECARE'),('BRIGHTLIGHTINFUSIONHHANDPALLIATIVECARE'),('BUTTERFLYHOSPICEPALLATIVECARE'),('CELESTIALHOSPICE'),('CFHCNO12'),('CFHCNO13'),('CFHCNO14'),('CFHCNO15'),('CFHCNO17'),('CFHCNO18'),('CFHCNO19'),('CFHCNO20'),('CFHCNO21'),('CFHCNO22'),('CFHCNO23'),('CFHCNO4'),('CFHCNO7'),('CHARTERHEALTHCAREOFSANANTONIO'),('CHESTNUTHOSPICE'),('COMMUNITYFIRSTHOSPICECAREOFSANANTONIO'),('COMPASSIONHOSPICEOFTEXAS'),('CYPRESSHOSPICE'),('DISTINGUISHEDHOSPICE'),('DIVINECOMFORTCAREHOSPICE'),('DIVINEENCOUNTERHOSPICE'),('ELMHOSPICE'),('EVERGREENHOSPICE'),('FAMILYFIRSTHOSPICE'),('FOURPILLARSHOSPICE'),('GENISAHOSPICEINTEGRATIVECARE'),('HARMONYHOSPICE'),('HARMONYHOSPICECARE'),('HARRISCOUNTYHOSPICE'),('HEARTSOULHOSPICE'),('HFCHNO4'),('HICKORYHOSPICE'),('HONEYBEEHOSPICE'),('HOUSTONFIRSTHOSPICEANDPALLIATIVECARE'),('JP2DHEALTHSYSTEMS'),('JUNIPERHOSPICE'),('LOVINGHANDSHOSPICE'),('LOVINGTOUCHHOSPICE'),('MAPLEHOSPICE'),('MIDTOWNHOSPICE'),('NESTHOMEHOSPICE'),('NESTHOMEHOSPICEANDPALLIATIVECARE'),('NEWDAWNHOSPICE'),('NIGHTINGALEHOSPICECAREOFTEXAS'),('OLIVETREEHOSPICE'),('ORIGINSHOSPICE'),('PINEHOSPICE'),('PINNACLEHOSPICESERVICES'),('PRIDEHOSPICECARE'),('REDWOODHOSPICE'),('ROWANHOSPICE'),('SIGNATUREHOSPICEPALLIATIVECARE'),('SOUTHERNSKYHOSPICE'),('SPECIALTYHOSPICE'),('SPRUCEHOSPICE'),('SYCAMOREHOSPICE'),('TEXASHEALTHCARESOLUTIONS'),('TEXASHEROESHOSPICE'),('TIMELESSMOMENTSHOSPICE'),('TREASUREDMOMENTSHOSPICE'),('WESLEYHEALTHCARE'),('WILLOWTREEHOSPICE'),('WILMINGTONHOSPICE'),('YELLOWROSEHOSPICECARE')),
ppp as (select 'PPP' src, BORROWER_NAME nm, BORROWER_CITY city, DATE_APPROVED dt, CURRENT_APPROVAL_AMOUNT amt, JOBS_REPORTED jobs,
   regexp_replace(regexp_replace(upper(BORROWER_NAME),'\\b(INC|LLC|L L C|CORP|CORPORATION|CO|COMPANY|PLLC|LTD|THE)\\b',''),'[^A-Z0-9]','') nk
  from LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_SBA_PPP where BORROWER_STATE='TX'
  union all
  select 'PPP150K', BORROWERNAME, BORROWERCITY, DATEAPPROVED, CURRENTAPPROVALAMOUNT, JOBSREPORTED,
   regexp_replace(regexp_replace(upper(BORROWERNAME),'\\b(INC|LLC|L L C|CORP|CORPORATION|CO|COMPANY|PLLC|LTD|THE)\\b',''),'[^A-Z0-9]','')
  from LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_SBA_PPP_LOANS_150K_PLUS where BORROWERSTATE='TX'),
usa as (select 'USASPENDING' src, RECIPIENT_NAME nm, RECIPIENT_CITY_NAME city, min(ACTION_DATE) dt, sum(FEDERAL_ACTION_OBLIGATION) amt, listagg(distinct CFDA_NUMBER, ',') jobs,
   regexp_replace(regexp_replace(upper(RECIPIENT_NAME),'\\b(INC|LLC|L L C|CORP|CORPORATION|CO|COMPANY|PLLC|LTD|THE)\\b',''),'[^A-Z0-9]','') nk
  from LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_USASPENDING_ASSISTANCE_FULL where RECIPIENT_STATE_CODE='TX' and (RECIPIENT_NAME ilike '%HOSPICE%' or RECIPIENT_NAME ilike '%CFHC%' or RECIPIENT_NAME ilike '%HEALTH%')
  group by 1,2,3,7)
select src, nm, city, dt, amt, jobs from ppp where nk in (select nk from k)
union all
select src, nm, city, dt::string, amt, jobs from usa where nk in (select nk from k)
union all
select 'CONTROL ppp TX hospice-named rows', null, null, null, count(*), null from ppp where nm ilike '%HOSPICE%'
union all
select 'CONTROL usaspending TX hospice-named recipients', null, null, null, count(*), null from usa where nm ilike '%HOSPICE%'
order by 1,2