-- NPPES, any taxonomy, any state: every organization NPI whose authorized official is one of the six core cluster officials (first+last), to see their footprint beyond hospice
select upper(trim(AUTHORIZED_OFFICIAL_FIRST_NAME))||' '||upper(trim(AUTHORIZED_OFFICIAL_LAST_NAME)) ao, NPI, PROVIDER_ORGANIZATION_NAME_LEGAL_BUSINESS_NAME lbn,
  HEALTHCARE_PROVIDER_TAXONOMY_CODE_1 tax1, PROVIDER_FIRST_LINE_BUSINESS_PRACTICE_LOCATION_ADDRESS a1, PROVIDER_SECOND_LINE_BUSINESS_PRACTICE_LOCATION_ADDRESS a2,
  PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_CITY_NAME city, PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_STATE_NAME st,
  regexp_replace(PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_TELEPHONE_NUMBER,'[^0-9]','') ph, PROVIDER_ENUMERATION_DATE enum_dt, NPI_DEACTIVATION_DATE deact, AUTHORIZED_OFFICIAL_TITLE_OR_POSITION title
from LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_NPPES
where ENTITY_TYPE_CODE in ('2','2.0') and (upper(trim(AUTHORIZED_OFFICIAL_FIRST_NAME)), upper(trim(AUTHORIZED_OFFICIAL_LAST_NAME))) in
  (('BENJAMIN','ARISE'),('ADEBAYO','OSHINUGA'),('ADEJUMOKE','OSHINUGA'),('JENNIFER','ROY'),('TRACY','GLEASON'),('ANN','LOZANO'),('JOHN','PRICE'))
order by ao, enum_dt
