{{ config(tags=['minimal_staging']) }}

-- GRAIN: NOT YET DETERMINED (profiler returned AMBIGUOUS -- needs manual review)
-- This is a passthrough staging view: snake_case rename only, no dedup.
-- Once grain is resolved, replace with a full staging model via generate_staging_models.py.
-- Generated by scripts/generate_minimal_staging.py

with source as (

    select * from {{ source('ripple_raw', 'INTL_EU_SOCTA_EUROPOL') }}

),

renamed as (

    select
        REPORT_TITLE as report_title,
        REPORT_TYPE as report_type,
        PUBLISH_DATE as publish_date,
        UPDATE_DATE as update_date,
        REPORT_YEAR as report_year,
        LANGUAGE as language,
        FILE_FORMAT as file_format,
        FILE_SIZE_MB as file_size_mb,
        DOWNLOAD_URL as download_url,
        DOCUMENT_VARIANT as document_variant,
        ISBN as isbn,
        DOI as doi,
        SERIAL_NUMBER as serial_number,
        PUBLISHER as publisher,
        GEOGRAPHIC_SCOPE as geographic_scope,
        SOURCE_URL as source_url,
        _INGESTED_AT as _loaded_at,
        'https://www.europol.europa.eu/publication-events/main-reports/changing-dna-of-serious-and-organised-crime' as _source_url

    from source

)

select * from renamed
