SELECT TABLE_NAME, LISTAGG(COLUMN_NAME, ', ') WITHIN GROUP (ORDER BY ORDINAL_POSITION) FROM LIBRARY_MARTS.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA='ENVIRONMENT' AND TABLE_NAME LIKE 'ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_%' GROUP BY 1
