SELECT PGM_SYS_ID, COUNT(*) N_ROWS, ANY_VALUE(FACILITY_NAME) NM, ANY_VALUE(CITY) CITY, ANY_VALUE(STATE) ST,
 LISTAGG(DISTINCT NAICS_CODES,'/') NAICS, LISTAGG(DISTINCT SIC_CODES,'/') SIC, LISTAGG(DISTINCT AIR_POLLUTANT_CLASS_CODE,'/') CLS, LISTAGG(DISTINCT AIR_OPERATING_STATUS_CODE,'/') OP
FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_FACILITIES
WHERE NAICS_CODES LIKE '%311221%' OR SIC_CODES LIKE '%2046%' OR UPPER(FACILITY_NAME) LIKE '%PENFORD%' OR UPPER(FACILITY_NAME) LIKE '%TATE & LYLE%' OR UPPER(FACILITY_NAME) LIKE '%INGREDION%' OR UPPER(FACILITY_NAME) LIKE '%CORN PROC%' OR UPPER(FACILITY_NAME) LIKE '%CORN MILL%'
GROUP BY 1 ORDER BY ST, NM
