SELECT PGM_SYS_ID, AGENCY_TYPE_DESC, ENF_RESPONSE_POLICY_CODE, PROGRAM_DESCS, POLLUTANT_DESCS, EARLIEST_FRV_DETERM_DATE, HPV_DAYZERO_DATE, HPV_RESOLVED_DATE
FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_VIOLATION_HISTORY
WHERE PGM_SYS_ID IN ('IA0000001913900025','IN0000001802700046') AND COALESCE(HPV_DAYZERO_DATE,EARLIEST_FRV_DETERM_DATE) >= '2015-01-01'
ORDER BY 1, COALESCE(HPV_DAYZERO_DATE,EARLIEST_FRV_DETERM_DATE)
