WITH v AS (SELECT PGM_SYS_ID, ACTIVITY_ID, ENF_RESPONSE_POLICY_CODE POL, POLLUTANT_DESCS, PROGRAM_DESCS, EARLIEST_FRV_DETERM_DATE FRV, HPV_DAYZERO_DATE DZ, HPV_RESOLVED_DATE RES
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_VIOLATION_HISTORY
  WHERE PGM_SYS_ID IN ('IA0000001913900025','IN0000001802700046') AND COALESCE(HPV_DAYZERO_DATE,EARLIEST_FRV_DETERM_DATE) BETWEEN '2015-01-01' AND '2025-12-31'),
s AS (SELECT DISTINCT PGM_SYS_ID, ACTUAL_END_DATE D FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_STACK_TESTS
  WHERE PGM_SYS_ID IN ('IA0000001913900025','IN0000001802700046') AND AIR_STACK_TEST_STATUS_CODE='FAI' AND ACTUAL_END_DATE >= '2014-06-01'),
vm AS (SELECT v.PGM_SYS_ID, v.ACTIVITY_ID, v.POL, MAX(IFF(s.D IS NOT NULL,1,0)) HAS_FAIL FROM v LEFT JOIN s ON s.PGM_SYS_ID=v.PGM_SYS_ID AND s.D BETWEEN DATEADD(day,-180,v.FRV) AND DATEADD(day,5,v.FRV) GROUP BY 1,2,3),
sm AS (SELECT s.PGM_SYS_ID, s.D, MAX(IFF(v.FRV IS NOT NULL,1,0)) HAS_VIOL FROM s LEFT JOIN v ON s.PGM_SYS_ID=v.PGM_SYS_ID AND v.FRV BETWEEN DATEADD(day,-5,s.D) AND DATEADD(day,180,s.D) WHERE s.D BETWEEN '2015-01-01' AND '2025-12-31' GROUP BY 1,2)
SELECT 'viol' K, PGM_SYS_ID, POL, COUNT(*) N, SUM(HAS_FAIL) WITH_FAIL_WITHIN_180D FROM vm GROUP BY 1,2,3
UNION ALL SELECT 'failday', PGM_SYS_ID, NULL, COUNT(*), SUM(HAS_VIOL) FROM sm GROUP BY 1,2,3
ORDER BY 2,1,3
