WITH fa AS (SELECT f.PGM_SYS_ID, x.FACILITY_NAME, f.ENF_IDENTIFIER, f.ENF_TYPE_DESC, f.ACTIVITY_TYPE_DESC, f.STATE_EPA_FLAG, f.SETTLEMENT_ENTERED_DATE D, f.PENALTY_AMOUNT
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_FORMAL_ACTIONS f JOIN LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_FACILITIES x USING (PGM_SYS_ID)
  WHERE x.STATE='IN' AND x.NAICS_CODES LIKE '%311221%' AND x.AIR_POLLUTANT_CLASS_CODE='MAJ' AND f.SETTLEMENT_ENTERED_DATE BETWEEN '2015-01-01' AND '2025-12-31'),
v AS (SELECT PGM_SYS_ID, HPV_RESOLVED_DATE R, POLLUTANT_DESCS P, PROGRAM_DESCS PG, ENF_RESPONSE_POLICY_CODE POL FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_VIOLATION_HISTORY WHERE PGM_SYS_ID IN (SELECT PGM_SYS_ID FROM fa)),
s AS (SELECT PGM_SYS_ID, ACTUAL_END_DATE D FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_STACK_TESTS WHERE AIR_STACK_TEST_STATUS_CODE='FAI' AND PGM_SYS_ID IN (SELECT PGM_SYS_ID FROM fa))
SELECT fa.FACILITY_NAME, fa.ENF_IDENTIFIER, fa.ENF_TYPE_DESC, fa.STATE_EPA_FLAG, fa.D, fa.PENALTY_AMOUNT,
  (SELECT LISTAGG(DISTINCT POL||':'||P||' ['||PG||']',' | ') FROM v WHERE v.PGM_SYS_ID=fa.PGM_SYS_ID AND v.R BETWEEN DATEADD(day,-30,fa.D) AND DATEADD(day,30,fa.D)) RESOLVED_NEAR,
  (SELECT COUNT(DISTINCT D) FROM s WHERE s.PGM_SYS_ID=fa.PGM_SYS_ID AND s.D BETWEEN DATEADD(day,-730,fa.D) AND fa.D) FAILDAYS_2Y_BEFORE
FROM fa ORDER BY 1,5
