SELECT f.PGM_SYS_ID, f.STREET_ADDRESS, f.CITY, LISTAGG(DISTINCT s.PROGRAM_CODE||'-'||s.AIR_PROGRAM_SUBPART_CODE||' '||LEFT(s.AIR_PROGRAM_SUBPART_DESC,40),' | ') SUBPARTS
FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_FACILITIES f LEFT JOIN LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_PROGRAM_SUBPARTS s USING(PGM_SYS_ID)
WHERE f.PGM_SYS_ID IN ('IA0000001913900025','IN0000001802700046') GROUP BY 1,2,3
