{{ config(tags=['spine_generated']) }}

-- GRAIN: one row per place (ZIP+DEATH_DATE_AND_TIME unique)
-- SPINE_ENTITY: place  (natural_key: DECEDENT_ZIP, DEATH_DATE_AND_TIME)
-- Generated by scripts/generate_staging_models.py from SOURCE_REGISTRY -- deterministic,
-- no LLM. Casts kept as landed (TEXT) -- add explicit type casts by hand once each
-- column's real type is confirmed; this generator has no semantic type knowledge.
-- spine_entity 'place' has no connect/ resolver yet (see connect/spine_entity.py) -- no SPINE_ENTITY_ID emitted.
-- landing table's ingestion timestamp is named INGESTED_AT (no leading underscore) rather than the usual _INGESTED_AT -- confirmed via INFORMATION_SCHEMA, not assumed.
-- DEDUPE: registry natural_key (DECEDENT_ZIP, DEATH_DATE_AND_TIME) is NOT unique within a load as landed at generation time -- it would collapse 37 of 7,723 rows. Deduping on the WHOLE ROW instead (exact copies only). A record that changes between loads shows once per version. Find the real key, fix SOURCE_REGISTRY, regenerate.

with source as (

    select * from {{ source('ripple_raw', 'PORTAL_CKA_WPRDC_ALLEGHENY_A4E9CE945B') }}

),

renamed as (

    select
        "DEATH_DATE_AND_TIME" as death_date_and_time,
        "MANNER_OF_DEATH" as manner_of_death,
        "AGE" as age,
        "SEX" as sex,
        "RACE" as race,
        "CASE_DISPO" as case_dispo,
        "COMBINED_OD1" as combined_od1,
        "COMBINED_OD2" as combined_od2,
        "COMBINED_OD3" as combined_od3,
        "COMBINED_OD4" as combined_od4,
        "COMBINED_OD5" as combined_od5,
        "COMBINED_OD6" as combined_od6,
        "COMBINED_OD7" as combined_od7,
        "COMBINED_OD8" as combined_od8,
        "COMBINED_OD9" as combined_od9,
        "COMBINED_OD10" as combined_od10,
        "INCIDENT_ZIP" as incident_zip,
        "DECEDENT_ZIP" as decedent_zip,
        "CASE_YEAR" as case_year,
        INGESTED_AT as _loaded_at,
        'https://data.wprdc.org/dataset/allegheny-county-fatal-accidental-overdoses' as _source_url

    from source

)

select * from renamed
qualify row_number() over (partition by death_date_and_time, manner_of_death, age, sex, race, case_dispo, combined_od1, combined_od2, combined_od3, combined_od4, combined_od5, combined_od6, combined_od7, combined_od8, combined_od9, combined_od10, incident_zip, decedent_zip, case_year order by _loaded_at desc) = 1
