{{ config(tags=['spine_generated']) }}

-- GRAIN: one row per record (spine_entity not determined -- no registry hint available) (PRP_REPORT_ID unique)
-- SPINE_ENTITY: (not determined)  (natural_key: PRP_REPORT_ID)
-- Generated by scripts/generate_staging_models.py from SOURCE_REGISTRY -- deterministic,
-- no LLM. Casts kept as landed (TEXT) -- add explicit type casts by hand once each
-- column's real type is confirmed; this generator has no semantic type knowledge.
-- spine_entity not determined (grain/natural_key proven, but no registry hint says what this row is ABOUT) -- no SPINE_ENTITY_ID emitted.
-- landing table's ingestion timestamp is named INGESTED_AT (no leading underscore) rather than the usual _INGESTED_AT -- confirmed via INFORMATION_SCHEMA, not assumed.

with source as (

    select * from {{ source('ripple_raw', 'PORTAL_CKA_VIRGINIA_OPEN_DA_E4498C978C') }}

),

renamed as (

    select
        "X" as x,
        "Y" as y,
        "OBJECTID" as objectid,
        "REFERENCE_POINT" as reference_point,
        "PRP_REPORT_ID" as prp_report_id,
        "PRP_REPORT_RECEIVED_DATE_TIME" as prp_report_received_date_time,
        "PRP_INCIDENT_DATE_TIME" as prp_incident_date_time,
        "PRP_INCIDENT_CLOSURE_DATE" as prp_incident_closure_date,
        "RSC_STATUS_DESCRIPTION" as rsc_status_description,
        "SRC_STATUS_REASON_DESC" as src_status_reason_desc,
        "PRP_SITE_NAME" as prp_site_name,
        "PRP_SITE_ADDRESS1" as prp_site_address1,
        "PRP_SITE_ADDRESS2" as prp_site_address2,
        "PRP_SITE_CITY" as prp_site_city,
        "PRP_SITE_STATE" as prp_site_state,
        "PRP_SITE_ZIP_CODE" as prp_site_zip_code,
        "PRP_ASSIGNED_STAFF_PROGRAM_ID" as prp_assigned_staff_program_id,
        "DATA_DISCLAIMER" as data_disclaimer,
        INGESTED_AT as _loaded_at,
        'https://data.virginia.gov/dataset/prep-reports1' as _source_url

    from source

)

select * from renamed
qualify row_number() over (partition by prp_report_id order by _loaded_at desc) = 1
