{{ config(tags=['spine_generated']) }}

-- GRAIN: one row per place (GEOM is unique)
-- SPINE_ENTITY: place  (natural_key: DATASPATIAL_WKB)
-- Generated by scripts/generate_staging_models.py from SOURCE_REGISTRY -- deterministic,
-- no LLM.
-- CASTS: 7 of 19 columns, from landing_column_profile_2026-09-19.tsv. A column is cast only
-- when every filled value in the sample parsed. try_ casts: a value that does not
-- parse reads NULL. The natural key and join-key columns stay TEXT.
--   fld_ar_id: ID: whole numbers, over 90% distinct -- stays TEXT, '.0' tail removed
--   velocity: integer
--   depth: integer
--   dep_revert: integer
--   objectid: ID: whole numbers, over 90% distinct -- stays TEXT, '.0' tail removed
--   static_bfe: integer
--   bfe_revert: integer
-- spine_entity 'place' has no connect/ resolver yet (see connect/spine_entity.py) -- no SPINE_ENTITY_ID emitted.
-- landing table's ingestion timestamp is named INGESTED_AT (no leading underscore) rather than the usual _INGESTED_AT -- confirmed via INFORMATION_SCHEMA, not assumed.

with source as (

    select * from {{ source('ripple_raw', 'PORTAL_CKA_WESTERN_PENNSYLV_F25943DE2B') }}
    qualify row_number() over (partition by "DATASPATIAL_WKB" order by INGESTED_AT desc) = 1

),

renamed as (

    select
        {{ null_junk('"VEL_UNIT"') }} as vel_unit,
        {{ null_junk('"V_DATUM"') }} as v_datum,
        {{ stg_id_text('"FLD_AR_ID"') }} as fld_ar_id,
        {{ null_junk('"GLOBALID"') }} as globalid,
        {{ stg_int('"VELOCITY"') }} as velocity,
        {{ stg_int('"DEPTH"') }} as depth,
        {{ null_junk('"AR_REVERT"') }} as ar_revert,
        {{ null_junk('"SOURCE_CIT"') }} as source_cit,
        {{ null_junk('"FLD_ZONE"') }} as fld_zone,
        {{ stg_int('"DEP_REVERT"') }} as dep_revert,
        {{ null_junk('"SHAPE__AREA"') }} as shape__area,
        {{ null_junk('"SFHA_TF"') }} as sfha_tf,
        {{ stg_id_text('"OBJECTID"') }} as objectid,
        {{ null_junk('"LEN_UNIT"') }} as len_unit,
        {{ stg_int('"STATIC_BFE"') }} as static_bfe,
        {{ null_junk('"SHAPE__LENGTH"') }} as shape__length,
        {{ stg_int('"BFE_REVERT"') }} as bfe_revert,
        {{ null_junk('"FLOODWAY"') }} as floodway,
        {{ null_junk('"DATASPATIAL_WKB"') }} as dataspatial_wkb,
        INGESTED_AT as _loaded_at,
        'https://data.wprdc.org/dataset/2014-fema-flood-zones' as _source_url

    from source

)

select * from renamed
