{{ config(tags=['spine_generated']) }}

-- GRAIN: one row per place (GEOM is unique)
-- SPINE_ENTITY: place  (natural_key: DATASPATIAL_WKB)
-- Generated by scripts/generate_staging_models.py from SOURCE_REGISTRY -- deterministic,
-- no LLM. Casts kept as landed (TEXT) -- add explicit type casts by hand once each
-- column's real type is confirmed; this generator has no semantic type knowledge.
-- spine_entity 'place' has no connect/ resolver yet (see connect/spine_entity.py) -- no SPINE_ENTITY_ID emitted.
-- landing table's ingestion timestamp is named INGESTED_AT (no leading underscore) rather than the usual _INGESTED_AT -- confirmed via INFORMATION_SCHEMA, not assumed.

with source as (

    select * from {{ source('ripple_raw', 'PORTAL_CKA_WESTERN_PENNSYLV_F25943DE2B') }}

),

renamed as (

    select
        "VEL_UNIT" as vel_unit,
        "V_DATUM" as v_datum,
        "FLD_AR_ID" as fld_ar_id,
        "GLOBALID" as globalid,
        "VELOCITY" as velocity,
        "DEPTH" as depth,
        "AR_REVERT" as ar_revert,
        "SOURCE_CIT" as source_cit,
        "FLD_ZONE" as fld_zone,
        "DEP_REVERT" as dep_revert,
        "SHAPE__AREA" as shape__area,
        "SFHA_TF" as sfha_tf,
        "OBJECTID" as objectid,
        "LEN_UNIT" as len_unit,
        "STATIC_BFE" as static_bfe,
        "SHAPE__LENGTH" as shape__length,
        "BFE_REVERT" as bfe_revert,
        "FLOODWAY" as floodway,
        "DATASPATIAL_WKB" as dataspatial_wkb,
        INGESTED_AT as _loaded_at,
        'https://data.wprdc.org/dataset/2014-fema-flood-zones' as _source_url

    from source

)

select * from renamed
qualify row_number() over (partition by dataspatial_wkb order by _loaded_at desc) = 1
