{{ config(tags=['spine_generated']) }}

-- GRAIN: one row per place (GEOM is unique)
-- SPINE_ENTITY: place  (natural_key: SHAPE_LENGTH)
-- Generated by scripts/generate_staging_models.py from SOURCE_REGISTRY -- deterministic,
-- no LLM.
-- CASTS: 8 of 15 columns, from landing_column_profile_2026-09-19.tsv. A column is cast only
-- when every filled value in the sample parsed. try_ casts: a value that does not
-- parse reads NULL. The natural key and join-key columns stay TEXT.
--   objectid: ID: whole numbers, over 90% distinct -- stays TEXT, '.0' tail removed
--   district_1: integer
--   ward_1: integer
--   municode_1: integer
--   mwd_nopa_1: ID: whole numbers, over 90% distinct -- stays TEXT, '.0' tail removed
--   opa_muni_1: integer
--   mwd_pad_1: ID: whole numbers, over 90% distinct -- stays TEXT, '.0' tail removed
--   pseudonu_5: ID: whole numbers, over 90% distinct -- stays TEXT, '.0' tail removed
-- spine_entity 'place' has no connect/ resolver yet (see connect/spine_entity.py) -- no SPINE_ENTITY_ID emitted.
-- landing table's ingestion timestamp is named INGESTED_AT (no leading underscore) rather than the usual _INGESTED_AT -- confirmed via INFORMATION_SCHEMA, not assumed.

with source as (

    select * from {{ source('ripple_raw', 'PORTAL_CKA_WESTERN_PENNSYLV_4C0F4E6C6C') }}
    qualify row_number() over (partition by "SHAPE_LENGTH" order by INGESTED_AT desc) = 1

),

renamed as (

    select
        {{ stg_id_text('"OBJECTID"') }} as objectid,
        {{ null_junk('"NAME"') }} as name,
        {{ null_junk('"TYPE"') }} as type,
        {{ null_junk('"LABEL"') }} as label,
        {{ stg_int('"DISTRICT_1"') }} as district_1,
        {{ stg_int('"WARD_1"') }} as ward_1,
        {{ stg_int('"MUNICODE_1"') }} as municode_1,
        {{ stg_id_text('"MWD_NOPA_1"') }} as mwd_nopa_1,
        {{ stg_int('"OPA_MUNI_1"') }} as opa_muni_1,
        {{ stg_id_text('"MWD_PAD_1"') }} as mwd_pad_1,
        {{ null_junk('"PSEUD4_12"') }} as pseud4_12,
        {{ stg_id_text('"PSEUDONU_5"') }} as pseudonu_5,
        {{ null_junk('"MUNI_WAR_1"') }} as muni_war_1,
        {{ null_junk('"SHAPE_AREA"') }} as shape_area,
        {{ null_junk('"SHAPE_LENGTH"') }} as shape_length,
        INGESTED_AT as _loaded_at,
        'https://data.wprdc.org/dataset/allegheny-county-voting-district-boundaries-ward-district-labels' as _source_url

    from source

)

select * from renamed
