{{ config(materialized='view') }}

/*
  Generated 2026-08-09 (73-source backlog, wave 2c) from live-verified specs.
  HUD Picture of Subsidized Households: assisted-housing units and tenant profiles by project/program/geography. NEGATIVE values are HUD suppression/N-A sentinels (kept as published -- filter value >= 0 for analysis).
  Grain: one row = one quarter x summary-level x program x code (verified unique).
*/

with source as (
    select * from {{ source('ripple_raw', 'FED_HUD_ASSISTED_HOUSING_PROJECTS') }}
),

renamed as (
    select
        nullif(trim(QUARTER), '')                                  as quarter,
        nullif(trim(GSL), '')                                      as gsl,
        nullif(trim(STATES), '')                                   as states,
        nullif(trim(ENTITIES), '')                                 as entities,
        nullif(trim(SUMLEVEL), '')                                 as sumlevel,
        nullif(trim(PROGRAM_LABEL), '')                            as program_label,
        nullif(trim(PROGRAM), '')                                  as program,
        nullif(trim(SUB_PROGRAM), '')                              as sub_program,
        nullif(trim(NAME), '')                                     as name,
        nullif(trim(CODE), '')                                     as code,
        try_to_number(nullif(trim(TOTAL_UNITS), ''), 18, 4)        as total_units,
        try_to_number(nullif(trim(TOTAL_OCCUPIED), ''), 18, 4)     as total_occupied,
        try_to_number(nullif(trim(PCT_OCCUPIED), ''), 18, 4)       as pct_occupied,
        try_to_number(nullif(trim(NUMBER_REPORTED), ''), 18, 4)    as number_reported,
        try_to_number(nullif(trim(PCT_REPORTED), ''), 18, 4)       as pct_reported,
        try_to_number(nullif(trim(MONTHS_SINCE_REPORT), ''), 18, 4) as months_since_report,
        nullif(trim(PCT_MOVEIN), '')                               as pct_movein,
        try_to_number(nullif(trim(PEOPLE_PER_UNIT), ''), 18, 4)    as people_per_unit,
        try_to_number(nullif(trim(PEOPLE_TOTAL), ''), 18, 4)       as people_total,
        try_to_number(nullif(trim(RENT_PER_MONTH), ''), 18, 4)     as rent_per_month,
        try_to_number(nullif(trim(SPENDING_PER_MONTH), ''), 18, 4) as spending_per_month,
        try_to_number(nullif(trim(HH_INCOME), ''), 18, 4)          as hh_income,
        try_to_number(nullif(trim(PERSON_INCOME), ''), 18, 4)      as person_income,
        nullif(trim(PCT_NOINCOME), '')                             as pct_noincome,
        nullif(trim(PCT_LT5K), '')                                 as pct_lt5k,
        nullif(trim(PCT_5K_LT10K), '')                             as pct_5k_lt10k,
        nullif(trim(PCT_10K_LT15K), '')                            as pct_10k_lt15k,
        nullif(trim(PCT_15K_LT20K), '')                            as pct_15k_lt20k,
        nullif(trim(PCT_20K_LT25K), '')                            as pct_20k_lt25k,
        nullif(trim(PCT_25K_LT30K), '')                            as pct_25k_lt30k,
        nullif(trim(PCT_30K_LT40K), '')                            as pct_30k_lt40k,
        nullif(trim(PCT_GE40K), '')                                as pct_ge40k,
        nullif(trim(PCT_WAGE_MAJOR), '')                           as pct_wage_major,
        nullif(trim(PCT_WELFARE_MAJOR), '')                        as pct_welfare_major,
        nullif(trim(PCT_OTHER_MAJOR), '')                          as pct_other_major,
        nullif(trim(PCT_MEDIAN), '')                               as pct_median,
        nullif(trim(PCT_LT80_MEDIAN), '')                          as pct_lt80_median,
        nullif(trim(PCT_LT50_MEDIAN), '')                          as pct_lt50_median,
        nullif(trim(PCT_LT30_MEDIAN), '')                          as pct_lt30_median,
        nullif(trim(PCT_2ADULTS), '')                              as pct_2adults,
        nullif(trim(PCT_1ADULT), '')                               as pct_1adult,
        nullif(trim(PCT_CHLDRN0_5), '')                            as pct_chldrn0_5,
        nullif(trim(PCT_CHLDRN6_12), '')                           as pct_chldrn6_12,
        nullif(trim(PCT_CHLDRN13_17), '')                          as pct_chldrn13_17,
        nullif(trim(PCT_0CHLDRN), '')                              as pct_0chldrn,
        nullif(trim(PCT_FEMALE_HEAD), '')                          as pct_female_head,
        nullif(trim(PCT_FEMALE_HEAD_CHILD), '')                    as pct_female_head_child,
        nullif(trim(PCT_FEMALE_HEAD_CHILD0_5), '')                 as pct_female_head_child0_5,
        nullif(trim(PCT_DISABLED_HEAD), '')                        as pct_disabled_head,
        nullif(trim(PCT_DISABLED_LT62), '')                        as pct_disabled_lt62,
        nullif(trim(PCT_DISABLED_GE62), '')                        as pct_disabled_ge62,
        nullif(trim(PCT_DISABLED_MBR), '')                         as pct_disabled_mbr,
        nullif(trim(PCT_DISABLED_ALL), '')                         as pct_disabled_all,
        nullif(trim(PCT_LT62_HEAD), '')                            as pct_lt62_head,
        nullif(trim(PCT_LT24_HEAD), '')                            as pct_lt24_head,
        nullif(trim(PCT_AGE25_50), '')                             as pct_age25_50,
        nullif(trim(PCT_AGE51_61), '')                             as pct_age51_61,
        nullif(trim(PCT_AGE62PLUS), '')                            as pct_age62plus,
        nullif(trim(PCT_AGE85PLUS), '')                            as pct_age85plus,
        nullif(trim(PCT_MINORITY), '')                             as pct_minority,
        nullif(trim(PCT_BLACK_NONHSP), '')                         as pct_black_nonhsp,
        nullif(trim(PCT_NATIVE_AMERICAN_NONHSP), '')               as pct_native_american_nonhsp,
        nullif(trim(PCT_ASIAN_PACIFIC_NONHSP), '')                 as pct_asian_pacific_nonhsp,
        nullif(trim(PCT_WHITE_NOTHSP), '')                         as pct_white_nothsp,
        nullif(trim(PCT_BLACK_HSP), '')                            as pct_black_hsp,
        nullif(trim(PCT_WHT_HSP), '')                              as pct_wht_hsp,
        nullif(trim(PCT_OTH_HSP), '')                              as pct_oth_hsp,
        nullif(trim(PCT_HISPANIC), '')                             as pct_hispanic,
        nullif(trim(PCT_MULTI), '')                                as pct_multi,
        try_to_number(nullif(trim(MONTHS_WAITING), ''), 18, 4)     as months_waiting,
        try_to_number(nullif(trim(MONTHS_FROM_MOVEIN), ''), 18, 4) as months_from_movein,
        nullif(trim(PCT_UTILITY_ALLOW), '')                        as pct_utility_allow,
        nullif(trim(AVE_UTIL_ALLOW), '')                           as ave_util_allow,
        nullif(trim(PCT_BED1), '')                                 as pct_bed1,
        nullif(trim(PCT_BED2), '')                                 as pct_bed2,
        nullif(trim(PCT_BED3), '')                                 as pct_bed3,
        nullif(trim(PCT_OVERHOUSED), '')                           as pct_overhoused,
        nullif(trim(TPOVERTY), '')                                 as tpoverty,
        nullif(trim(TMINORITY), '')                                as tminority,
        nullif(trim(TPCT_OWNSFD), '')                              as tpct_ownsfd,
        nullif(trim(FEDHSE), '')                                   as fedhse,
        nullif(trim(CBSA), '')                                     as cbsa,
        nullif(trim(PLACE), '')                                    as place,
        try_to_number(nullif(trim(LATITUDE), ''), 18, 4)           as latitude,
        try_to_number(nullif(trim(LONGITUDE), ''), 18, 4)          as longitude,
        nullif(trim(STATE), '')                                    as state,
        nullif(trim(PHA_TOTAL_UNITS), '')                          as pha_total_units,
        nullif(trim(HA_SIZE), '')                                  as ha_size,
        nullif(trim(STD_ADDR), '')                                 as std_addr,
        nullif(trim(STD_CITY), '')                                 as std_city,
        nullif(trim(STD_ZIP5), '')                                 as std_zip5,
        nullif(trim(STCTYTRT), '')                                 as stctytrt,
        to_timestamp_ntz(_INGESTED_AT, 6)                          as _ingested_at,
        nullif(trim(_SOURCE_RUN_ID), '')                           as _source_run_id
    from source
)

select * from renamed
