{{ config(tags=['spine_generated']) }}

-- GRAIN: one row per record (spine_entity not determined -- no registry hint available) (NPDES_VIOLATION_ID unique)
-- SPINE_ENTITY: (not determined)  (natural_key: NPDES_VIOLATION_ID)
-- Generated by scripts/generate_staging_models.py from SOURCE_REGISTRY -- deterministic,
-- no LLM. Casts kept as landed (TEXT) -- add explicit type casts by hand once each
-- column's real type is confirmed; this generator has no semantic type knowledge.
-- spine_entity not determined (grain/natural_key proven, but no registry hint says what this row is ABOUT) -- no SPINE_ENTITY_ID emitted.
-- DEDUPE: registry natural_key (NPDES_VIOLATION_ID) is NOT unique within a load as landed at generation time -- it would collapse 33 of 305,478 rows. Deduping on the WHOLE ROW instead (exact copies only). A record that changes between loads shows once per version. Find the real key, fix SOURCE_REGISTRY, regenerate.

with source as (

    select * from {{ source('ripple_raw', 'FED_EPA_NPDES_NPDES_SE_VIOLATIONS') }}

),

renamed as (

    select
        "NPDES_ID" as npdes_id,
        "NPDES_VIOLATION_ID" as npdes_violation_id,
        "VIOLATION_TYPE_CODE" as violation_type_code,
        "VIOLATION_CODE" as violation_code,
        "VIOLATION_DESC" as violation_desc,
        "SINGLE_EVENT_VIOLATION_DATE" as single_event_violation_date,
        "SINGLE_EVENT_END_DATE" as single_event_end_date,
        "SINGLE_EVENT_VIOLATION_COMMENT" as single_event_violation_comment,
        "SINGLE_EVENT_AGENCY_TYPE_CODE" as single_event_agency_type_code,
        "RNC_DETECTION_CODE" as rnc_detection_code,
        "RNC_DETECTION_DESC" as rnc_detection_desc,
        "RNC_DETECTION_DATE" as rnc_detection_date,
        "RNC_RESOLUTION_CODE" as rnc_resolution_code,
        "RNC_RESOLUTION_DESC" as rnc_resolution_desc,
        "RNC_RESOLUTION_DATE" as rnc_resolution_date,
        _INGESTED_AT as _loaded_at,
        '' as _source_url

    from source

)

select * from renamed
qualify row_number() over (partition by npdes_id, npdes_violation_id, violation_type_code, violation_code, violation_desc, single_event_violation_date, single_event_end_date, single_event_violation_comment, single_event_agency_type_code, rnc_detection_code, rnc_detection_desc, rnc_detection_date, rnc_resolution_code, rnc_resolution_desc, rnc_resolution_date order by _loaded_at desc) = 1
