{{ config(tags=['spine_generated']) }}

-- GRAIN: one row per record (spine_entity not determined -- no registry hint available) (INFOUSA_ID unique)
-- SPINE_ENTITY: (not determined)  (natural_key: INFOUSA_ID)
-- Generated by scripts/generate_staging_models.py from SOURCE_REGISTRY -- deterministic,
-- no LLM.
-- CASTS: 58 of 222 columns, from landing_column_profile_2026-09-19.tsv. A column is cast only
-- when every filled value in the sample parsed. try_ casts: a value that does not
-- parse reads NULL. The natural key and join-key columns stay TEXT.
--   objectid_1: ID: whole numbers, over 90% distinct -- stays TEXT, '.0' tail removed
--   primary_zip4: integer
--   primary_state_code: integer
--   county_code: integer
--   cbsa_code: integer
--   metro_micro_indicator: integer
--   csa_code: integer
--   census_tract: integer
--   census_block_group: integer
--   secondary_state_code: integer
--   secondary_zip4: integer
--   phone: ID: whole numbers, over 90% distinct -- stays TEXT, '.0' tail removed
--   fax_number: ID: whole numbers, over 90% distinct -- stays TEXT, '.0' tail removed
--   actual_location_employment_size: integer
--   actual_corporate_employment_siz: integer
--   actual_location_sales_volume: integer
--   actual_corporate_sales_volume: ID: whole numbers, over 90% distinct -- stays TEXT, '.0' tail removed
--   infousa_subsidiary_id: integer
--   infousa_parent_id: integer
--   site_number: ID: whole numbers, over 90% distinct -- stays TEXT, '.0' tail removed
--   hq_branch_code: integer
--   individual_firm_code: integer
--   year_first_appeared_in_yellow_p: integer
--   year_established: integer
--   yellow_page_code: integer
--   transaction_date: integer
--   actual_credit_score: integer
--   population_code: integer
--   square_footage_code: integer
--   radial_distance_from_target_ele: integer
--   actnumbus_multitenant_location: integer
--   building_num_multi_tenant: integer
--   tertiary_zip10: integer
--   white_collar_percentage: integer
--   white_collar_indicator: integer
--   production_date: date, YYYYMMDD
--   obsolescence_date: date
--   production_date1: date
--   govsegcd: integer
--   franchise_specialty_code_1: integer
--   franchise_specialty_code_2: integer
--   franchise_specialty_code_3: integer
--   franchise_specialty_code_4: integer
--   naics6: integer
--   objectid: ID: whole numbers, over 90% distinct -- stays TEXT, '.0' tail removed
--   join_count: integer
--   target_fid: ID: whole numbers, over 90% distinct -- stays TEXT, '.0' tail removed
--   deed_date: date
--   deed_acres: float
--   bldg_val: integer
--   land_val: integer
--   total_value_assd: integer
--   heatedarea: integer
--   year_built: integer
--   totsalprice: integer
--   sale_date: integer
--   totstructs: integer
--   totunits: integer
-- spine_entity not determined (grain/natural_key proven, but no registry hint says what this row is ABOUT) -- no SPINE_ENTITY_ID emitted.
-- landing table's ingestion timestamp is named INGESTED_AT (no leading underscore) rather than the usual _INGESTED_AT -- confirmed via INFORMATION_SCHEMA, not assumed.

with source as (

    select * from {{ source('ripple_raw', 'PORTAL_ARC_OPEN_DATA_RALEIG_8EE851C810') }}
    qualify row_number() over (partition by "INFOUSA_ID" order by INGESTED_AT desc) = 1

),

renamed as (

    select
        {{ stg_id_text('"OBJECTID_1"') }} as objectid_1,
        {{ null_junk('"CONTACT_NAME"') }} as contact_name,
        {{ null_junk('"COMPANY_NAME"') }} as company_name,
        {{ null_junk('"PRIMARY_ADDRESS"') }} as primary_address,
        {{ null_junk('"PRIMARY_CITY"') }} as primary_city,
        {{ null_junk('"PRIMARY_STATE"') }} as primary_state,
        {{ null_junk('"PRIMARY_ZIP_CODE"') }} as primary_zip_code,
        {{ stg_int('"PRIMARY_ZIP4"') }} as primary_zip4,
        {{ null_junk('"PRIMARY_ZIP10"') }} as primary_zip10,
        {{ null_junk('"PRIMARY_CARRIER_ROUTE_CODE"') }} as primary_carrier_route_code,
        {{ stg_int('"PRIMARY_STATE_CODE"') }} as primary_state_code,
        {{ stg_int('"COUNTY_CODE"') }} as county_code,
        {{ null_junk('"COUNTY_NAME"') }} as county_name,
        {{ null_junk('"MSA_CODE"') }} as msa_code,
        {{ null_junk('"MSA_DESC"') }} as msa_desc,
        {{ stg_int('"CBSA_CODE"') }} as cbsa_code,
        {{ null_junk('"CBSA_DESCR"') }} as cbsa_descr,
        {{ stg_int('"METRO_MICRO_INDICATOR"') }} as metro_micro_indicator,
        {{ stg_int('"CSA_CODE"') }} as csa_code,
        {{ null_junk('"CSA_DESCR"') }} as csa_descr,
        {{ stg_int('"CENSUS_TRACT"') }} as census_tract,
        {{ stg_int('"CENSUS_BLOCK_GROUP"') }} as census_block_group,
        {{ null_junk('"LATITUDE"') }} as latitude,
        {{ null_junk('"LONGITUDE"') }} as longitude,
        {{ null_junk('"MATCH_LEVEL_CODE"') }} as match_level_code,
        {{ null_junk('"SECONDARY_ADDRESS"') }} as secondary_address,
        {{ null_junk('"SECONDARY_CITY"') }} as secondary_city,
        {{ null_junk('"SECONDARY_STATE"') }} as secondary_state,
        {{ stg_int('"SECONDARY_STATE_CODE"') }} as secondary_state_code,
        {{ null_junk('"SECONDARY_ZIP_CODE"') }} as secondary_zip_code,
        {{ stg_int('"SECONDARY_ZIP4"') }} as secondary_zip4,
        {{ null_junk('"SECONDARY_ZIP10"') }} as secondary_zip10,
        {{ null_junk('"SECONDARY_CARRIER_ROUTE_CODE"') }} as secondary_carrier_route_code,
        {{ stg_id_text('"PHONE"') }} as phone,
        {{ stg_id_text('"FAX_NUMBER"') }} as fax_number,
        {{ null_junk('"TOLL_FREE_NUMBER"') }} as toll_free_number,
        {{ null_junk('"WEB_SITE"') }} as web_site,
        {{ null_junk('"SELECTED_SIC_CODE"') }} as selected_sic_code,
        {{ null_junk('"SELECTED_SIC_DESC"') }} as selected_sic_desc,
        {{ null_junk('"FILLER_1"') }} as filler_1,
        {{ null_junk('"FRANCHISE_SPECIALTY_DESC_1"') }} as franchise_specialty_desc_1,
        {{ null_junk('"FILLER_2"') }} as filler_2,
        {{ null_junk('"FRANCHISE_SPECIALTY_DESC_2"') }} as franchise_specialty_desc_2,
        {{ null_junk('"FILLER_3"') }} as filler_3,
        {{ null_junk('"FRANCHISE_SPECIALTY_DESC_3"') }} as franchise_specialty_desc_3,
        {{ null_junk('"FILLER_4"') }} as filler_4,
        {{ null_junk('"FRANCHISE_SPECIALTY_DESC_4"') }} as franchise_specialty_desc_4,
        {{ null_junk('"FILLER_5"') }} as filler_5,
        {{ null_junk('"FRANCHISE_SPECIALTY_DESC_5"') }} as franchise_specialty_desc_5,
        {{ null_junk('"FILLER_6"') }} as filler_6,
        {{ null_junk('"FRANCHISE_SPECIALTY_DESC_6"') }} as franchise_specialty_desc_6,
        {{ null_junk('"TRUE_FRANCHISE"') }} as true_franchise,
        {{ null_junk('"INDUSTRY_SPECIFIC_CODE"') }} as industry_specific_code,
        {{ null_junk('"INDUSTRY_SPECIFIC_DESCRIPTION"') }} as industry_specific_description,
        {{ null_junk('"PRIMARY_SIC_CODE"') }} as primary_sic_code,
        {{ null_junk('"PRIMARY_SIC_DESC"') }} as primary_sic_desc,
        {{ null_junk('"SECONDARY_SIC_CODE_1"') }} as secondary_sic_code_1,
        {{ null_junk('"SECONDARY_SIC_DESC_1"') }} as secondary_sic_desc_1,
        {{ null_junk('"SECONDARY_SIC_CODE_2"') }} as secondary_sic_code_2,
        {{ null_junk('"SECONDARY_SIC_DESC_2"') }} as secondary_sic_desc_2,
        {{ null_junk('"SECONDARY_SIC_CODE_3"') }} as secondary_sic_code_3,
        {{ null_junk('"SECONDARY_SIC_DESC_3"') }} as secondary_sic_desc_3,
        {{ null_junk('"SECONDARY_SIC_CODE_4"') }} as secondary_sic_code_4,
        {{ null_junk('"SECONDARY_SIC_DESCRIPTION_4"') }} as secondary_sic_description_4,
        {{ null_junk('"NAICS_CODE"') }} as naics_code,
        {{ null_junk('"NAICS_DESC"') }} as naics_desc,
        {{ null_junk('"LOCATION_EMPLOYMENT_SIZE_CODE"') }} as location_employment_size_code,
        {{ null_junk('"LOCATION_EMPLOYMENT_SIZE_DESC"') }} as location_employment_size_desc,
        {{ stg_int('"ACTUAL_LOCATION_EMPLOYMENT_SIZE"') }} as actual_location_employment_size,
        {{ null_junk('"CORPORATE_EMPLOYMENT_SIZE_CODE"') }} as corporate_employment_size_code,
        {{ null_junk('"CORPORATE_EMPLOYMENT_SIZE_DESC"') }} as corporate_employment_size_desc,
        {{ stg_int('"ACTUAL_CORPORATE_EMPLOYMENT_SIZ"') }} as actual_corporate_employment_siz,
        {{ null_junk('"MODELED_EMPLOYMENT_SIZE"') }} as modeled_employment_size,
        {{ null_junk('"LOCATION_SALES_VOLUME_CODE"') }} as location_sales_volume_code,
        {{ null_junk('"LOCATION_SALES_VOLUME_DESC"') }} as location_sales_volume_desc,
        {{ stg_int('"ACTUAL_LOCATION_SALES_VOLUME"') }} as actual_location_sales_volume,
        {{ null_junk('"CORPORATE_SALES_VOLUME_CODE"') }} as corporate_sales_volume_code,
        {{ null_junk('"CORPORATE_SALES_VOLUME_DESC"') }} as corporate_sales_volume_desc,
        {{ stg_id_text('"ACTUAL_CORPORATE_SALES_VOLUME"') }} as actual_corporate_sales_volume,
        {{ null_junk('"ASSET_SIZE"') }} as asset_size,
        {{ null_junk('"LAST_NAME"') }} as last_name,
        {{ null_junk('"FIRST_NAME"') }} as first_name,
        {{ null_junk('"SALUTATION"') }} as salutation,
        {{ null_junk('"GENDER"') }} as gender,
        {{ null_junk('"PROFESSIONAL_TITLE"') }} as professional_title,
        {{ null_junk('"TITLE_CODE"') }} as title_code,
        {{ null_junk('"TITLE_DESC"') }} as title_desc,
        {{ null_junk('"CONTACT_ETHNIC_CODE"') }} as contact_ethnic_code,
        {{ null_junk('"CONTACT_ETHNIC_DESCRIPTION"') }} as contact_ethnic_description,
        {{ null_junk('"KEY_CODE"') }} as key_code,
        {{ null_junk('"TITLE_ADDRESS"') }} as title_address,
        {{ null_junk('"INFOUSA_ID"') }} as infousa_id,
        {{ stg_int('"INFOUSA_SUBSIDIARY_ID"') }} as infousa_subsidiary_id,
        {{ stg_int('"INFOUSA_PARENT_ID"') }} as infousa_parent_id,
        {{ stg_id_text('"SITE_NUMBER"') }} as site_number,
        {{ stg_int('"HQ_BRANCH_CODE"') }} as hq_branch_code,
        {{ null_junk('"HQ_BRANCH_DESC"') }} as hq_branch_desc,
        {{ null_junk('"PUBLIC_COMPANY_INDICATOR_CODE"') }} as public_company_indicator_code,
        {{ null_junk('"STOCK_EXCHANGE_CODE"') }} as stock_exchange_code,
        {{ null_junk('"STOCK_EXCHANGE_DESC"') }} as stock_exchange_desc,
        {{ null_junk('"STOCK_TICKER_SYMBOL"') }} as stock_ticker_symbol,
        {{ null_junk('"PUBLIC_FILING_INDICATOR"') }} as public_filing_indicator,
        {{ null_junk('"FORTUNE_RANKING"') }} as fortune_ranking,
        {{ stg_int('"INDIVIDUAL_FIRM_CODE"') }} as individual_firm_code,
        {{ null_junk('"INDIVIDUAL_FIRM_DESC"') }} as individual_firm_desc,
        {{ null_junk('"YEAR_SIC_ADDED"') }} as year_sic_added,
        {{ stg_int('"YEAR_FIRST_APPEARED_IN_YELLOW_P"') }} as year_first_appeared_in_yellow_p,
        {{ stg_int('"YEAR_ESTABLISHED"') }} as year_established,
        {{ stg_int('"YELLOW_PAGE_CODE"') }} as yellow_page_code,
        {{ stg_int('"TRANSACTION_DATE"') }} as transaction_date,
        {{ null_junk('"CURRENT_TRANSACTION_CODE"') }} as current_transaction_code,
        {{ null_junk('"FILLER"') }} as filler,
        {{ null_junk('"CALL_STATUS_CODE"') }} as call_status_code,
        {{ null_junk('"CALL_STATUS_DESC"') }} as call_status_desc,
        {{ null_junk('"CREDIT_SCORE_CODE"') }} as credit_score_code,
        {{ null_junk('"CREDIT_SCORE_DESC"') }} as credit_score_desc,
        {{ stg_int('"ACTUAL_CREDIT_SCORE"') }} as actual_credit_score,
        {{ null_junk('"AD_SIZE_CODE"') }} as ad_size_code,
        {{ null_junk('"AD_SIZE_DESC"') }} as ad_size_desc,
        {{ null_junk('"OFFICE_SIZE_CODE"') }} as office_size_code,
        {{ null_junk('"OFFICE_SIZE_DESC"') }} as office_size_desc,
        {{ stg_int('"POPULATION_CODE"') }} as population_code,
        {{ null_junk('"POPULATION_DESC"') }} as population_desc,
        {{ null_junk('"WORK_AT_HOME_BUSINESS"') }} as work_at_home_business,
        {{ null_junk('"OWN_LEASE_CODE"') }} as own_lease_code,
        {{ stg_int('"SQUARE_FOOTAGE_CODE"') }} as square_footage_code,
        {{ null_junk('"SQUARE_FOOTAGE_DESC"') }} as square_footage_desc,
        {{ stg_int('"RADIAL_DISTANCE_FROM_TARGET_ELE"') }} as radial_distance_from_target_ele,
        {{ stg_int('"ACTNUMBUS_MULTITENANT_LOCATION"') }} as actnumbus_multitenant_location,
        {{ null_junk('"MULTITENANT_CODE"') }} as multitenant_code,
        {{ null_junk('"MULTITENANT_DESC"') }} as multitenant_desc,
        {{ stg_int('"BUILDING_NUM_MULTI_TENANT"') }} as building_num_multi_tenant,
        {{ null_junk('"FLEET_CODE"') }} as fleet_code,
        {{ null_junk('"FLEET_DESCRIPTION"') }} as fleet_description,
        {{ null_junk('"AFFLUENT_NEIGHBORHOOD_LOCATION"') }} as affluent_neighborhood_location,
        {{ null_junk('"BIG_BUSINESS"') }} as big_business,
        {{ null_junk('"FEMALE_OWNER_EXEC"') }} as female_owner_exec,
        {{ null_junk('"BUSINESS_SIZE_CHANGE"') }} as business_size_change,
        {{ null_junk('"HIGHINCOMEEXEC"') }} as highincomeexec,
        {{ null_junk('"HIGHTECHBUSINESS"') }} as hightechbusiness,
        {{ null_junk('"MEDIUM_SIZE_BUSINESS_ENTREPRENE"') }} as medium_size_business_entreprene,
        {{ null_junk('"SMALL_BUSINESS_ENTREPRENEUR"') }} as small_business_entrepreneur,
        {{ null_junk('"DELIVERY_POINT_BAR_CODE"') }} as delivery_point_bar_code,
        {{ null_junk('"PRESORT_ENDORSEMENT_LINE"') }} as presort_endorsement_line,
        {{ null_junk('"PRESORT_BAG_NUMBER"') }} as presort_bag_number,
        {{ null_junk('"PRESORT_BUNDLE_NUMBER"') }} as presort_bundle_number,
        {{ null_junk('"PRESORT_LINE_OF_TRAVEL"') }} as presort_line_of_travel,
        {{ null_junk('"TERTIARY_ADDRESS"') }} as tertiary_address,
        {{ null_junk('"TERTIARY_CITY"') }} as tertiary_city,
        {{ null_junk('"TERTIARY_STATE"') }} as tertiary_state,
        {{ null_junk('"TERTIARY_ZIP_CODE"') }} as tertiary_zip_code,
        {{ null_junk('"TERTIARY_ZIP4"') }} as tertiary_zip4,
        {{ stg_int('"TERTIARY_ZIP10"') }} as tertiary_zip10,
        {{ null_junk('"TERTIARY_CARRIER_ROUTE_CODE"') }} as tertiary_carrier_route_code,
        {{ stg_int('"WHITE_COLLAR_PERCENTAGE"') }} as white_collar_percentage,
        {{ stg_int('"WHITE_COLLAR_INDICATOR"') }} as white_collar_indicator,
        {{ stg_date('"PRODUCTION_DATE"', 'YYYYMMDD') }} as production_date,
        {{ null_junk('"SEQUENCE_NUMBER"') }} as sequence_number,
        {{ stg_date('"OBSOLESCENCE_DATE"') }} as obsolescence_date,
        {{ stg_date('"PRODUCTION_DATE1"') }} as production_date1,
        {{ null_junk('"SOURCE"') }} as source,
        {{ null_junk('"BOOKNO"') }} as bookno,
        {{ stg_int('"GOVSEGCD"') }} as govsegcd,
        {{ null_junk('"FORGNPAR"') }} as forgnpar,
        {{ null_junk('"IMPEXPCD"') }} as impexpcd,
        {{ stg_int('"FRANCHISE_SPECIALTY_CODE_1"') }} as franchise_specialty_code_1,
        {{ stg_int('"FRANCHISE_SPECIALTY_CODE_2"') }} as franchise_specialty_code_2,
        {{ stg_int('"FRANCHISE_SPECIALTY_CODE_3"') }} as franchise_specialty_code_3,
        {{ stg_int('"FRANCHISE_SPECIALTY_CODE_4"') }} as franchise_specialty_code_4,
        {{ null_junk('"FRANCHISE_SPECIALTY_CODE_5"') }} as franchise_specialty_code_5,
        {{ null_junk('"FRANCHISE_SPECIALTY_CODE_6"') }} as franchise_specialty_code_6,
        {{ null_junk('"END_OF_RECORD_MARKER"') }} as end_of_record_marker,
        {{ stg_int('"NAICS6"') }} as naics6,
        {{ null_junk('"SECTOR"') }} as sector,
        {{ null_junk('"TFIELD"') }} as tfield,
        {{ null_junk('"TFIELD1"') }} as tfield1,
        {{ null_junk('"TFIELD2"') }} as tfield2,
        {{ null_junk('"DFIELD"') }} as dfield,
        {{ null_junk('"FFIELD"') }} as ffield,
        {{ null_junk('"FFIELD1"') }} as ffield1,
        {{ null_junk('"IFIELD"') }} as ifield,
        {{ null_junk('"IFIELD1"') }} as ifield1,
        {{ null_junk('"STATUS"') }} as status,
        {{ null_junk('"STATUS1"') }} as status1,
        {{ null_junk('"STATUS2"') }} as status2,
        {{ null_junk('"STATUS3"') }} as status3,
        {{ stg_id_text('"OBJECTID"') }} as objectid,
        {{ stg_int('"JOIN_COUNT"') }} as join_count,
        {{ stg_id_text('"TARGET_FID"') }} as target_fid,
        {{ null_junk('"PIN_NUM"') }} as pin_num,
        {{ null_junk('"REID"') }} as reid,
        {{ null_junk('"MAP_NAME"') }} as map_name,
        {{ null_junk('"OWNER"') }} as owner,
        {{ null_junk('"ADDR1"') }} as addr1,
        {{ null_junk('"ADDR2"') }} as addr2,
        {{ null_junk('"ADDR3"') }} as addr3,
        {{ null_junk('"DEED_BOOK"') }} as deed_book,
        {{ null_junk('"DEED_PAGE"') }} as deed_page,
        {{ stg_date('"DEED_DATE"') }} as deed_date,
        {{ stg_float('"DEED_ACRES"') }} as deed_acres,
        {{ stg_int('"BLDG_VAL"') }} as bldg_val,
        {{ stg_int('"LAND_VAL"') }} as land_val,
        {{ stg_int('"TOTAL_VALUE_ASSD"') }} as total_value_assd,
        {{ null_junk('"BILLING_CLASS_DECODE"') }} as billing_class_decode,
        {{ null_junk('"PROPDESC"') }} as propdesc,
        {{ stg_int('"HEATEDAREA"') }} as heatedarea,
        {{ null_junk('"SITE_ADDRESS"') }} as site_address,
        {{ null_junk('"FULL_STREET_NAME"') }} as full_street_name,
        {{ null_junk('"CITY_DECODE"') }} as city_decode,
        {{ null_junk('"PLANNING_JURISDICTION"') }} as planning_jurisdiction,
        {{ null_junk('"TOWNSHIP_DECODE"') }} as township_decode,
        {{ stg_int('"YEAR_BUILT"') }} as year_built,
        {{ stg_int('"TOTSALPRICE"') }} as totsalprice,
        {{ stg_int('"SALE_DATE"') }} as sale_date,
        {{ null_junk('"TYPE_USE_DECODE"') }} as type_use_decode,
        {{ null_junk('"DESIGN_STYLE_DECODE"') }} as design_style_decode,
        {{ null_junk('"LAND_CLASS_DECODE"') }} as land_class_decode,
        {{ null_junk('"EXEMPTDESC"') }} as exemptdesc,
        {{ null_junk('"EXEMPTSTAT"') }} as exemptstat,
        {{ stg_int('"TOTSTRUCTS"') }} as totstructs,
        {{ stg_int('"TOTUNITS"') }} as totunits,
        {{ null_junk('"OLD_PARCEL_NUMBER"') }} as old_parcel_number,
        INGESTED_AT as _loaded_at,
        'https://data.raleighnc.gov/datasets/26de85c6ab1c4915bb9594a56ae419fb_28' as _source_url

    from source

)

select * from renamed
