{{ config(tags=['spine_generated']) }}

-- GRAIN: one row per place (GEOM is unique)
-- SPINE_ENTITY: place  (natural_key: GEOMETRY)
-- Generated by scripts/generate_staging_models.py from SOURCE_REGISTRY -- deterministic,
-- no LLM. Casts kept as landed (TEXT) -- add explicit type casts by hand once each
-- column's real type is confirmed; this generator has no semantic type knowledge.
-- spine_entity 'place' has no connect/ resolver yet (see connect/spine_entity.py) -- no SPINE_ENTITY_ID emitted.
-- landing table's ingestion timestamp is named INGESTED_AT (no leading underscore) rather than the usual _INGESTED_AT -- confirmed via INFORMATION_SCHEMA, not assumed.

with source as (

    select * from {{ source('ripple_raw', 'PORTAL_ARC_FORT_WORTH_OPEN_2259070522') }}

),

renamed as (

    select
        "FID" as fid,
        "EMPNAME" as empname,
        "EMPADDR" as empaddr,
        "EMPLOYEES" as employees,
        "NAICS" as naics,
        "STARTDATE" as startdate,
        "LASTEDITED" as lastedited,
        "CITY" as city,
        "EMPID" as empid,
        "MAILADDR" as mailaddr,
        "MAILCITY" as mailcity,
        "MAILZIP" as mailzip,
        "SOURCEDATE" as sourcedate,
        "FEATURENAM" as featurenam,
        "ACTIVITYSE" as activityse,
        "TOP20RF" as top20rf,
        "GEOMETRY" as geometry,
        INGESTED_AT as _loaded_at,
        'https://data.fortworthtexas.gov/datasets/ab17d8de3b4d4a1595fc11a405a14455_0' as _source_url

    from source

)

select * from renamed
qualify row_number() over (partition by geometry order by _loaded_at desc) = 1
