-- S01 column names and types for the 5 tables plus the join partners
SELECT table_schema, table_name, LISTAGG(column_name || ':' || data_type, ', ') WITHIN GROUP (ORDER BY ordinal_position) cols
FROM LIBRARY_MARTS.INFORMATION_SCHEMA.COLUMNS
WHERE table_name IN ('POLITICS__VOTEVIEW_ROLLCALLS','POLITICS__FEC_CAND_CMTE_LINK','POLITICS__INTL_OWID_MILSPEND','POLITICS__XC_OWID_CPI',
  'POLITICS__FED_DOJ_EPSTEIN_LIBRARY','POLITICS__FED_VOTEVIEW_ROLLCALL_META','POLITICS__FEC_COMMITTEE','FINANCE__FED_FEC_CAND_CMTE_LINKAGE',
  'POLITICS__FEC_CANDIDATE','POLITICS__INTL_FREEDOMHOUSE','POLITICS__FEC_CANDIDATE_SUMMARY')
GROUP BY 1,2 ORDER BY 1,2
