{{ config(tags=['spine_generated']) }}

-- GRAIN: one row per place (GEOM is unique)
-- SPINE_ENTITY: place  (natural_key: SHAPE__LENGTH)
-- Generated by scripts/generate_staging_models.py from SOURCE_REGISTRY -- deterministic,
-- no LLM.
-- CASTS: 3 of 16 columns, from landing_column_profile_2026-09-19.tsv. A column is cast only
-- when every filled value in the sample parsed. try_ casts: a value that does not
-- parse reads NULL. The natural key and join-key columns stay TEXT.
--   objectid: ID: whole numbers, over 90% distinct -- stays TEXT, '.0' tail removed
--   district: integer
--   district2: integer
-- spine_entity 'place' has no connect/ resolver yet (see connect/spine_entity.py) -- no SPINE_ENTITY_ID emitted.
-- landing table's ingestion timestamp is named INGESTED_AT (no leading underscore) rather than the usual _INGESTED_AT -- confirmed via INFORMATION_SCHEMA, not assumed.

with source as (

    select * from {{ source('ripple_raw', 'PORTAL_CKA_OPEN_DATA_SA_D06A042788') }}
    qualify row_number() over (partition by "SHAPE__LENGTH" order by INGESTED_AT desc) = 1

),

renamed as (

    select
        {{ stg_id_text('"OBJECTID"') }} as objectid,
        {{ null_junk('"SZ_CARTID"') }} as sz_cartid,
        {{ null_junk('"ZONETYPE"') }} as zonetype,
        {{ null_junk('"WARNINGTYPE"') }} as warningtype,
        {{ null_junk('"BEACONASSEMBLY"') }} as beaconassembly,
        {{ null_junk('"SCHOOLNAME"') }} as schoolname,
        {{ null_junk('"ADJACENTSCHOOLS"') }} as adjacentschools,
        {{ null_junk('"MSAG_NAME"') }} as msag_name,
        {{ null_junk('"JURISDICTION"') }} as jurisdiction,
        {{ stg_int('"DISTRICT"') }} as district,
        {{ stg_int('"DISTRICT2"') }} as district2,
        {{ null_junk('"REGULATORY"') }} as regulatory,
        {{ null_junk('"MAINTENANCERESPONSIBILITY"') }} as maintenanceresponsibility,
        {{ null_junk('"STATUS"') }} as status,
        {{ null_junk('"SHAPE__AREA"') }} as shape__area,
        {{ null_junk('"SHAPE__LENGTH"') }} as shape__length,
        INGESTED_AT as _loaded_at,
        'https://data.sanantonio.gov/dataset/school-zones' as _source_url

    from source

)

select * from renamed
