{{ config(tags=['spine_generated']) }}

-- GRAIN: one row per place (LATLON is unique)
-- SPINE_ENTITY: place  (natural_key: LATITUDE)
-- Generated by scripts/generate_staging_models.py from SOURCE_REGISTRY -- deterministic,
-- no LLM. Casts kept as landed (TEXT) -- add explicit type casts by hand once each
-- column's real type is confirmed; this generator has no semantic type knowledge.
-- spine_entity 'place' has no connect/ resolver yet (see connect/spine_entity.py) -- no SPINE_ENTITY_ID emitted.
-- landing table's ingestion timestamp is named INGESTED_AT (no leading underscore) rather than the usual _INGESTED_AT -- confirmed via INFORMATION_SCHEMA, not assumed.

with source as (

    select * from {{ source('ripple_raw', 'PORTAL_CKA_ANALYZE_BOSTON_BBE261ACCB') }}

),

renamed as (

    select
        "OBJECTID_1" as objectid_1,
        "ANCILLARYR" as ancillaryr,
        "ENABLED" as enabled,
        "FEATURE_ID" as feature_id,
        "PLACEMENT" as placement,
        "PLACEMENT1" as placement1,
        "UPDATE_ID" as update_id,
        "UPDATE_DAT" as update_dat,
        "SYNCH_FLAG" as synch_flag,
        "SYMBOL_ROT" as symbol_rot,
        "FACILITY_I" as facility_i,
        "SUBTYPE_CO" as subtype_co,
        "SERVICE_AR" as service_ar,
        "INSTALL_DA" as install_da,
        "HYDRANT_MA" as hydrant_ma,
        "OWNER_CODE" as owner_code,
        "METERED_FL" as metered_fl,
        "ADDRESS_NU" as address_nu,
        "STREET_FEA" as street_fea,
        "CROSS_STRE" as cross_stre,
        "LOC_SOURCE" as loc_source,
        "MANUFACTUR" as manufactur,
        "HYDRANT_MO" as hydrant_mo,
        "LONGITUDE" as longitude,
        "LATITUDE" as latitude,
        "SHAPE_WKT" as shape_wkt,
        "POINT_X" as point_x,
        "POINT_Y" as point_y,
        INGESTED_AT as _loaded_at,
        'https://data.boston.gov/dataset/fire-hydrants' as _source_url

    from source

)

select * from renamed
qualify row_number() over (partition by latitude order by _loaded_at desc) = 1
