{{ config(tags=['spine_generated']) }}

-- GRAIN: one row per place (LATLON is unique)
-- SPINE_ENTITY: place  (natural_key: LATITUDE)
-- Generated by scripts/generate_staging_models.py from SOURCE_REGISTRY -- deterministic,
-- no LLM.
-- CASTS: 12 of 28 columns, from landing_column_profile_2026-09-19.tsv. A column is cast only
-- when every filled value in the sample parsed. try_ casts: a value that does not
-- parse reads NULL. The natural key and join-key columns stay TEXT.
--   ancillaryr: integer
--   enabled: integer
--   feature_id: ID: whole numbers, over 90% distinct -- stays TEXT, '.0' tail removed
--   placement1: timestamp
--   update_dat: timestamp
--   symbol_rot: float
--   subtype_co: integer
--   install_da: timestamp
--   cross_stre: integer
--   manufactur: integer
--   point_x: float
--   point_y: float
-- spine_entity 'place' has no connect/ resolver yet (see connect/spine_entity.py) -- no SPINE_ENTITY_ID emitted.
-- landing table's ingestion timestamp is named INGESTED_AT (no leading underscore) rather than the usual _INGESTED_AT -- confirmed via INFORMATION_SCHEMA, not assumed.
-- DEDUPE: registry natural_key (LATITUDE) is NOT unique within a load as landed at generation time -- it would collapse 3 of 13,747 rows. Deduping on the WHOLE ROW instead (exact copies only). A record that changes between loads shows once per version. Find the real key, fix SOURCE_REGISTRY, regenerate.

with source as (

    select * from {{ source('ripple_raw', 'PORTAL_CKA_ANALYZE_BOSTON_BBE261ACCB') }}
    qualify row_number() over (partition by "OBJECTID_1", "ANCILLARYR", "ENABLED", "FEATURE_ID", "PLACEMENT", "PLACEMENT1", "UPDATE_ID", "UPDATE_DAT", "SYNCH_FLAG", "SYMBOL_ROT", "FACILITY_I", "SUBTYPE_CO", "SERVICE_AR", "INSTALL_DA", "HYDRANT_MA", "OWNER_CODE", "METERED_FL", "ADDRESS_NU", "STREET_FEA", "CROSS_STRE", "LOC_SOURCE", "MANUFACTUR", "HYDRANT_MO", "LONGITUDE", "LATITUDE", "SHAPE_WKT", "POINT_X", "POINT_Y" order by INGESTED_AT desc) = 1

),

renamed as (

    select
        {{ null_junk('"OBJECTID_1"') }} as objectid_1,
        {{ stg_int('"ANCILLARYR"') }} as ancillaryr,
        {{ stg_int('"ENABLED"') }} as enabled,
        {{ stg_id_text('"FEATURE_ID"') }} as feature_id,
        {{ null_junk('"PLACEMENT"') }} as placement,
        {{ stg_ts('"PLACEMENT1"') }} as placement1,
        {{ null_junk('"UPDATE_ID"') }} as update_id,
        {{ stg_ts('"UPDATE_DAT"') }} as update_dat,
        {{ null_junk('"SYNCH_FLAG"') }} as synch_flag,
        {{ stg_float('"SYMBOL_ROT"') }} as symbol_rot,
        {{ null_junk('"FACILITY_I"') }} as facility_i,
        {{ stg_int('"SUBTYPE_CO"') }} as subtype_co,
        {{ null_junk('"SERVICE_AR"') }} as service_ar,
        {{ stg_ts('"INSTALL_DA"') }} as install_da,
        {{ null_junk('"HYDRANT_MA"') }} as hydrant_ma,
        {{ null_junk('"OWNER_CODE"') }} as owner_code,
        {{ null_junk('"METERED_FL"') }} as metered_fl,
        {{ null_junk('"ADDRESS_NU"') }} as address_nu,
        {{ null_junk('"STREET_FEA"') }} as street_fea,
        {{ stg_int('"CROSS_STRE"') }} as cross_stre,
        {{ null_junk('"LOC_SOURCE"') }} as loc_source,
        {{ stg_int('"MANUFACTUR"') }} as manufactur,
        {{ null_junk('"HYDRANT_MO"') }} as hydrant_mo,
        {{ null_junk('"LONGITUDE"') }} as longitude,
        {{ null_junk('"LATITUDE"') }} as latitude,
        {{ null_junk('"SHAPE_WKT"') }} as shape_wkt,
        {{ stg_float('"POINT_X"') }} as point_x,
        {{ stg_float('"POINT_Y"') }} as point_y,
        INGESTED_AT as _loaded_at,
        'https://data.boston.gov/dataset/fire-hydrants' as _source_url

    from source

)

select * from renamed
