-- S01 column types for my 5 tables and the sibling tables I may join
SELECT TABLE_NAME, LISTAGG(COLUMN_NAME || ':' || DATA_TYPE, ', ') WITHIN GROUP (ORDER BY ORDINAL_POSITION) cols
FROM LIBRARY_MARTS.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'ENVIRONMENT' AND TABLE_NAME IN (
 'ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_POLLUTANTS','ENVIRONMENT__FED_WQP_MONITORING_STATIONS','ENVIRONMENT__INTL_GLOBAL_WITNESS_DEFENDERS',
 'ENVIRONMENT__FED_EPA_NPDES_NPDES_INFORMAL_ENFORCEMENT_ACTIONS','ENVIRONMENT__FED_EPA_SDWA_SDWA_PN_VIOLATION_ASSOC',
 'ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_FACILITIES','ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_VIOLATION_HISTORY','ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_FORMAL_ACTIONS',
 'ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_STACK_TESTS','ENVIRONMENT__FED_EPA_NPDES_NPDES_FORMAL_ENFORCEMENT_ACTIONS','ENVIRONMENT__FED_EPA_NPDES_ICIS_FACILITIES',
 'ENVIRONMENT__FED_EPA_NPDES_NPDES_QNCR_HISTORY','ENVIRONMENT__FED_EPA_SDWA_SDWA_VIOLATIONS_ENFORCEMENT','ENVIRONMENT__FED_EPA_SDWA_SDWA_PUB_WATER_SYSTEMS')
GROUP BY 1 ORDER BY 1;

-- S02 WQP stations: the whole table (5.8K rows), profiled locally
SELECT * FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_WQP_MONITORING_STATIONS;

-- S03 Global Witness defenders: the whole table (232 rows), read locally
SELECT * FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__INTL_GLOBAL_WITNESS_DEFENDERS;
