-- S25 NPDES: date the Missouri blank-date letters by activity ID. Part A: national ID range per achieved half-year (state rows, 2018 on). Part B: Missouri blank-date rows by ID band and type
SELECT 'A_national' part, TO_CHAR(DATE_TRUNC('quarter', ACHIEVED_DATE), 'YYYY-MM') k, COUNT(*) n,
       APPROX_PERCENTILE(TRY_TO_NUMBER(ACTIVITY_ID), 0.1) p10, APPROX_PERCENTILE(TRY_TO_NUMBER(ACTIVITY_ID), 0.5) p50, APPROX_PERCENTILE(TRY_TO_NUMBER(ACTIVITY_ID), 0.9) p90
FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_NPDES_NPDES_INFORMAL_ENFORCEMENT_ACTIONS
WHERE AGENCY = 'State' AND ACHIEVED_DATE BETWEEN '2018-01-01' AND CURRENT_DATE
GROUP BY 1,2
UNION ALL
SELECT 'B_MO_null', FLOOR(TRY_TO_NUMBER(ACTIVITY_ID) / 1e6)::string || ' | ' || ENF_TYPE_CODE, COUNT(*), MIN(TRY_TO_NUMBER(ACTIVITY_ID)), MEDIAN(TRY_TO_NUMBER(ACTIVITY_ID)), MAX(TRY_TO_NUMBER(ACTIVITY_ID))
FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_NPDES_NPDES_INFORMAL_ENFORCEMENT_ACTIONS
WHERE LEFT(NPDES_ID,2) = 'MO' AND AGENCY = 'State' AND ACHIEVED_DATE IS NULL
GROUP BY 1,2
ORDER BY 1,2;
