-- S26 NPDES Missouri: every state letter/notice counted by year, using the achieved date when present and, when blank, the year implied by its activity ID (the latest national quarter whose median ID is at or below it)
WITH nat AS (
  SELECT DATE_TRUNC('quarter', ACHIEVED_DATE) q, MEDIAN(TRY_TO_NUMBER(ACTIVITY_ID)) p50
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_NPDES_NPDES_INFORMAL_ENFORCEMENT_ACTIONS
  WHERE AGENCY = 'State' AND ACHIEVED_DATE BETWEEN '2016-01-01' AND CURRENT_DATE GROUP BY 1),
mo AS (
  SELECT DISTINCT ACTIVITY_ID, TRY_TO_NUMBER(ACTIVITY_ID) id, ACHIEVED_DATE, ENF_TYPE_CODE
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_NPDES_NPDES_INFORMAL_ENFORCEMENT_ACTIONS
  WHERE LEFT(NPDES_ID,2) = 'MO' AND AGENCY = 'State' AND (ACHIEVED_DATE IS NULL OR ACHIEVED_DATE >= '2016-01-01')),
nul AS (
  SELECT mo.ACTIVITY_ID, MAX(nat.q) implied_q FROM mo JOIN nat ON nat.p50 <= mo.id WHERE mo.ACHIEVED_DATE IS NULL GROUP BY 1)
SELECT YEAR(COALESCE(mo.ACHIEVED_DATE, nul.implied_q)) y, COUNT_IF(mo.ACHIEVED_DATE IS NOT NULL) dated, COUNT_IF(mo.ACHIEVED_DATE IS NULL) blank_date,
       COUNT_IF(mo.ACHIEVED_DATE IS NULL AND nul.ACTIVITY_ID IS NULL) blank_unplaced, COUNT(*) total
FROM mo LEFT JOIN nul ON nul.ACTIVITY_ID = mo.ACTIVITY_ID
GROUP BY 1 ORDER BY 1;
