-- S04 ICIS-Air pollutants: shape by FACIL-vs-real row and class; duplicate pairs; CAS and SRS fill
SELECT (POLLUTANT_DESC = 'FACIL') is_facil_row, AIR_POLLUTANT_CLASS_CODE cls, ANY_VALUE(AIR_POLLUTANT_CLASS_DESC) cls_desc,
       COUNT(*) n, COUNT(DISTINCT PGM_SYS_ID) facilities, COUNT(DISTINCT PGM_SYS_ID || '|' || POLLUTANT_CODE) fac_pollutant_pairs,
       COUNT(DISTINCT POLLUTANT_CODE) pollutant_codes,
       COUNT_IF(NULLIF(TRIM(CHEMICAL_ABSTRACT_SERVICE_NMBR),'') IS NOT NULL) cas_filled,
       COUNT_IF(NULLIF(TRIM(SRS_ID),'') IS NOT NULL) srs_filled
FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_POLLUTANTS
GROUP BY 1,2 ORDER BY 1,4 DESC;

-- S05 ICIS-Air pollutants vs facilities: coverage, FACIL-row class vs facility class, major-for-a-pollutant on a non-major facility
WITH p AS (
  SELECT PGM_SYS_ID, MAX(IFF(POLLUTANT_DESC='FACIL', AIR_POLLUTANT_CLASS_CODE, NULL)) facil_cls,
         COUNT_IF(POLLUTANT_DESC <> 'FACIL') n_poll,
         MAX(IFF(POLLUTANT_DESC <> 'FACIL' AND AIR_POLLUTANT_CLASS_CODE = 'MAJ', 1, 0)) any_maj,
         MAX(IFF(POLLUTANT_DESC <> 'FACIL' AND AIR_POLLUTANT_CLASS_CODE = 'SMI', 1, 0)) any_smi
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_POLLUTANTS GROUP BY 1),
f AS (
  SELECT PGM_SYS_ID, ANY_VALUE(AIR_POLLUTANT_CLASS_CODE) fcls, ANY_VALUE(AIR_OPERATING_STATUS_CODE) st, COUNT(*) frows
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_FACILITIES GROUP BY 1)
SELECT f.fcls, p.facil_cls, (p.PGM_SYS_ID IS NULL) no_pollutant_rows, (f.PGM_SYS_ID IS NULL) no_facility_row,
       COUNT(*) n, COUNT_IF(f.st = 'OPR') operating, SUM(p.any_maj) any_maj_pollutant, SUM(p.any_smi) any_smi_pollutant,
       MEDIAN(p.n_poll) med_pollutants, SUM(IFF(f.frows > 1, 1, 0)) dup_facility_rows
FROM f FULL OUTER JOIN p ON f.PGM_SYS_ID = p.PGM_SYS_ID
GROUP BY 1,2,3,4 ORDER BY n DESC;

-- S06 ICIS-Air pollutants: top 150 pollutants by facility count, with class split and CAS
SELECT POLLUTANT_CODE, POLLUTANT_DESC, MAX(CHEMICAL_ABSTRACT_SERVICE_NMBR) cas, COUNT(*) n, COUNT(DISTINCT PGM_SYS_ID) facilities,
       COUNT_IF(AIR_POLLUTANT_CLASS_CODE = 'MAJ') maj, COUNT_IF(AIR_POLLUTANT_CLASS_CODE = 'SMI') smi, COUNT_IF(AIR_POLLUTANT_CLASS_CODE = 'MIN') mnr
FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_POLLUTANTS
GROUP BY 1,2 ORDER BY facilities DESC LIMIT 150;

-- S07 NPDES informal: shape by agency, type, official flag; date sentinels; registry fill
SELECT AGENCY, ENF_TYPE_CODE, ENF_TYPE_DESC, OFFICIAL_FLG, COUNT(*) n, COUNT(DISTINCT ACTIVITY_ID) acts, COUNT(DISTINCT NPDES_ID) permits,
       COUNT_IF(NULLIF(TRIM(REGISTRY_ID),'') IS NULL) no_registry, MIN(ACHIEVED_DATE) d0, MAX(ACHIEVED_DATE) d1,
       COUNT_IF(ACHIEVED_DATE < '1990-01-01') pre1990, COUNT_IF(ACHIEVED_DATE > CURRENT_DATE) future, COUNT_IF(ACHIEVED_DATE IS NULL) nulldate
FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_NPDES_NPDES_INFORMAL_ENFORCEMENT_ACTIONS
GROUP BY 1,2,3,4 ORDER BY n DESC;

-- S08 NPDES informal: permit-state x agency x month extract, 1990 to today (time series, local)
SELECT LEFT(NPDES_ID, 2) st, AGENCY, DATE_TRUNC('month', ACHIEVED_DATE) ym, COUNT(*) n, COUNT(DISTINCT ACTIVITY_ID) acts, COUNT(DISTINCT NPDES_ID) permits
FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_NPDES_NPDES_INFORMAL_ENFORCEMENT_ACTIONS
WHERE ACHIEVED_DATE BETWEEN '1990-01-01' AND CURRENT_DATE
GROUP BY 1,2,3;

-- S09 SDWA PN assoc: shape, duplicate links, ID uniqueness, date ranges, code spread
SELECT COUNT(*) n, COUNT(DISTINCT PWSID) systems, COUNT(DISTINCT PWSID || '|' || PN_VIOLATION_ID) pn_viols,
       COUNT(DISTINCT PWSID || '|' || RELATED_VIOLATION_ID) related_viols,
       COUNT(DISTINCT PWSID || '|' || PN_VIOLATION_ID || '|' || RELATED_VIOLATION_ID) distinct_links,
       COUNT(DISTINCT PN_VIOLATION_ID) pn_ids_no_pwsid, COUNT(DISTINCT SUBMISSIONYEARQUARTER) releases,
       MIN(COMPL_PER_BEGIN_DATE) cb0, MAX(COMPL_PER_BEGIN_DATE) cb1, MIN(NON_COMPL_PER_BEGIN_DATE) nb0, MAX(NON_COMPL_PER_BEGIN_DATE) nb1,
       MIN(FIRST_REPORTED_DATE) fr0, MAX(FIRST_REPORTED_DATE) fr1, COUNT_IF(COMPL_PER_END_DATE IS NULL) open_end,
       COUNT(DISTINCT VIOLATION_CODE) vcodes, COUNT(DISTINCT CONTAMINANT_CODE) ccodes,
       COUNT_IF(COMPL_PER_BEGIN_DATE >= '2015-01-01') since2015
FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_SDWA_SDWA_PN_VIOLATION_ASSOC;
