-- S10 NPDES dull-explanation test: do state inspections, formal actions and effluent-violation permits also stop where informal letters stop? state x quarter, 2021 on
WITH i AS (
  SELECT LEFT(NPDES_ID,2) st, 'inspection' src, STATE_EPA_FLAG who, YEAR(d)*10 + QUARTER(d) yq, COUNT(DISTINCT ACTIVITY_ID) n, COUNT(DISTINCT NPDES_ID) permits
  FROM (SELECT NPDES_ID, ACTIVITY_ID, STATE_EPA_FLAG, TRY_TO_DATE(ACTUAL_END_DATE::string) d FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_NPDES_NPDES_INSPECTIONS)
  WHERE d BETWEEN '2021-01-01' AND CURRENT_DATE GROUP BY 1,2,3,4),
f AS (
  SELECT LEFT(NPDES_ID,2) st, 'formal' src, AGENCY who, YEAR(SETTLEMENT_ENTERED_DATE)*10 + QUARTER(SETTLEMENT_ENTERED_DATE) yq, COUNT(DISTINCT ACTIVITY_ID) n, COUNT(DISTINCT NPDES_ID) permits
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_NPDES_NPDES_FORMAL_ENFORCEMENT_ACTIONS
  WHERE SETTLEMENT_ENTERED_DATE BETWEEN '2021-01-01' AND CURRENT_DATE GROUP BY 1,2,3,4),
q AS (
  SELECT LEFT(NPDES_ID,2) st, 'qncr_eff_viol' src, 'all' who, TRY_TO_NUMBER(YEARQTR) yq, COUNT(DISTINCT IFF(TRY_TO_NUMBER(NUME90_Q) > 0, NPDES_ID, NULL)) n, COUNT(DISTINCT NPDES_ID) permits
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_NPDES_NPDES_QNCR_HISTORY
  WHERE TRY_TO_NUMBER(YEARQTR) BETWEEN 20211 AND 20263 GROUP BY 1,2,3,4)
SELECT * FROM i UNION ALL SELECT * FROM f UNION ALL SELECT * FROM q;

-- S11 ICIS-Air: every operating facility with class, HPV status, carcinogen flags from the pollutants table, violations and formal actions since 2020 (extract; peer math local)
WITH p AS (
  SELECT PGM_SYS_ID,
    LISTAGG(DISTINCT CASE WHEN CHEMICAL_ABSTRACT_SERVICE_NMBR = '75218' THEN 'EtO' WHEN CHEMICAL_ABSTRACT_SERVICE_NMBR = '126998' THEN 'chloroprene'
      WHEN CHEMICAL_ABSTRACT_SERVICE_NMBR = '106990' THEN 'butadiene' WHEN CHEMICAL_ABSTRACT_SERVICE_NMBR = '75014' THEN 'vinylchloride'
      WHEN CHEMICAL_ABSTRACT_SERVICE_NMBR IN ('18540299','1333820') THEN 'hexchrome' WHEN CHEMICAL_ABSTRACT_SERVICE_NMBR = '71432' THEN 'benzene'
      WHEN CHEMICAL_ABSTRACT_SERVICE_NMBR = '50000' THEN 'formaldehyde' END, ',') tox,
    LISTAGG(DISTINCT IFF(AIR_POLLUTANT_CLASS_CODE = 'MAJ' AND CHEMICAL_ABSTRACT_SERVICE_NMBR IN ('75218','126998','106990','75014','18540299','1333820','71432','50000'), CHEMICAL_ABSTRACT_SERVICE_NMBR, NULL), ',') tox_major_cas,
    COUNT_IF(POLLUTANT_DESC <> 'FACIL') n_poll
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_POLLUTANTS GROUP BY 1),
v AS (
  SELECT PGM_SYS_ID, COUNT(DISTINCT IFF(HPV_DAYZERO_DATE >= '2020-01-01', ACTIVITY_ID, NULL)) hpv20,
         COUNT(DISTINCT IFF(EARLIEST_FRV_DETERM_DATE >= '2020-01-01', ACTIVITY_ID, NULL)) frv20,
         COUNT(DISTINCT IFF(HPV_DAYZERO_DATE >= '2020-01-01' AND HPV_RESOLVED_DATE IS NULL, ACTIVITY_ID, NULL)) hpv20_open
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_VIOLATION_HISTORY GROUP BY 1),
fa AS (
  SELECT PGM_SYS_ID, COUNT(DISTINCT IFF(SETTLEMENT_ENTERED_DATE >= '2020-01-01', ACTIVITY_ID, NULL)) formal20,
         SUM(IFF(SETTLEMENT_ENTERED_DATE >= '2020-01-01', PENALTY_AMOUNT, 0)) pen20, COUNT(DISTINCT ACTIVITY_ID) formal_ever
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_FORMAL_ACTIONS GROUP BY 1)
SELECT f.PGM_SYS_ID, f.REGISTRY_ID, f.STATE, f.AIR_POLLUTANT_CLASS_CODE cls, f.CURRENT_HPV, f.FACILITY_NAME, f.CITY, f.NAICS_CODES,
       p.tox, p.tox_major_cas, p.n_poll, v.hpv20, v.frv20, v.hpv20_open, fa.formal20, fa.pen20, fa.formal_ever
FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_FACILITIES f
LEFT JOIN p ON p.PGM_SYS_ID = f.PGM_SYS_ID
LEFT JOIN v ON v.PGM_SYS_ID = f.PGM_SYS_ID
LEFT JOIN fa ON fa.PGM_SYS_ID = f.PGM_SYS_ID
WHERE f.AIR_OPERATING_STATUS_CODE = 'OPR';

-- S12 SDWA PN assoc joined to the deduped violations table on PWSID + ID, both sides: what the PN side is, what the related side is, whether the row's code/date belong to the related violation
WITH v AS (
  SELECT PWSID, VIOLATION_ID, ANY_VALUE(VIOLATION_CODE) vc, ANY_VALUE(IS_HEALTH_BASED_IND) hb, ANY_VALUE(PUBLIC_NOTIFICATION_TIER) tier,
         ANY_VALUE(VIOLATION_CATEGORY_CODE) cat, ANY_VALUE(COMPL_PER_BEGIN_DATE) b, ANY_VALUE(CONTAMINANT_CODE) cc
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_SDWA_SDWA_VIOLATIONS_ENFORCEMENT WHERE VIOLATION_ID IS NOT NULL GROUP BY 1,2)
SELECT vp.vc pn_code, vr.cat rel_cat, vr.hb rel_hb, vr.tier rel_tier, (a.VIOLATION_CODE = vr.vc) code_eq_rel, (a.VIOLATION_CODE = vp.vc) code_eq_pn,
       COUNT(*) n, COUNT_IF(vp.PWSID IS NULL) pn_miss, COUNT_IF(vr.PWSID IS NULL) rel_miss,
       COUNT_IF(a.COMPL_PER_BEGIN_DATE = vr.b) date_eq_rel, COUNT_IF(a.COMPL_PER_BEGIN_DATE = vp.b) date_eq_pn, COUNT_IF(a.CONTAMINANT_CODE = vr.cc) cc_eq_rel
FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_SDWA_SDWA_PN_VIOLATION_ASSOC a
LEFT JOIN v vp ON vp.PWSID = a.PWSID AND vp.VIOLATION_ID = a.PN_VIOLATION_ID
LEFT JOIN v vr ON vr.PWSID = a.PWSID AND vr.VIOLATION_ID = a.RELATED_VIOLATION_ID
GROUP BY 1,2,3,4,5,6 ORDER BY n DESC;
