-- S13 NPDES: Missouri/NY/AR letter types by year, and Missouri state inspection outcomes by year (does MO still find violations it no longer writes letters about?)
SELECT 'informal' part, LEFT(NPDES_ID,2) st, YEAR(ACHIEVED_DATE) y, ENF_TYPE_CODE || ' | ' || ENF_TYPE_DESC k, COUNT(DISTINCT ACTIVITY_ID) n, COUNT(DISTINCT NPDES_ID) permits
FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_NPDES_NPDES_INFORMAL_ENFORCEMENT_ACTIONS
WHERE LEFT(NPDES_ID,2) IN ('MO','NY','AR') AND AGENCY = 'State' AND ACHIEVED_DATE BETWEEN '2018-01-01' AND CURRENT_DATE
GROUP BY 1,2,3,4
UNION ALL
SELECT 'inspection', LEFT(NPDES_ID,2), YEAR(TRY_TO_DATE(ACTUAL_END_DATE::string)), COALESCE(ACTIVITY_OUTCOME_CODE,'') || ' | ' || COALESCE(ACTIVITY_OUTCOME_DESC,'') || ' | ' || COALESCE(COMP_MONITOR_TYPE_CODE,''),
       COUNT(DISTINCT ACTIVITY_ID), COUNT(DISTINCT NPDES_ID)
FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_NPDES_NPDES_INSPECTIONS
WHERE LEFT(NPDES_ID,2) = 'MO' AND STATE_EPA_FLAG = 'S' AND TRY_TO_DATE(ACTUAL_END_DATE::string) BETWEEN '2018-01-01' AND CURRENT_DATE
GROUP BY 1,2,3,4;
