-- S14 SDWA: per water system, health-based violations begun 2015 on (deduped on PWSID + VIOLATION_ID), how many carry a failure-to-notify (PN code 75) link, acute tier-1 subset, open PN status; with name, type, population
WITH v AS (
  SELECT PWSID, VIOLATION_ID, ANY_VALUE(VIOLATION_CODE) vc, ANY_VALUE(IS_HEALTH_BASED_IND) hb, ANY_VALUE(PUBLIC_NOTIFICATION_TIER) tier,
         ANY_VALUE(COMPL_PER_BEGIN_DATE) b, ANY_VALUE(VIOLATION_STATUS) status, ANY_VALUE(CONTAMINANT_CODE) cc
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_SDWA_SDWA_VIOLATIONS_ENFORCEMENT WHERE VIOLATION_ID IS NOT NULL GROUP BY 1,2),
a AS (SELECT DISTINCT PWSID, PN_VIOLATION_ID, RELATED_VIOLATION_ID FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_SDWA_SDWA_PN_VIOLATION_ASSOC),
rel AS (
  SELECT a.PWSID, a.RELATED_VIOLATION_ID vid, MAX(IFF(vp.status = 'Unaddressed', 1, 0)) pn_unaddr, MIN(vp.b) pn_begin
  FROM a LEFT JOIN v vp ON vp.PWSID = a.PWSID AND vp.VIOLATION_ID = a.PN_VIOLATION_ID GROUP BY 1,2),
hb AS (
  SELECT v.*, IFF(rel.vid IS NOT NULL, 1, 0) has_pn, COALESCE(rel.pn_unaddr, 0) pn_unaddr
  FROM v LEFT JOIN rel ON rel.PWSID = v.PWSID AND rel.vid = v.VIOLATION_ID
  WHERE v.hb = 'Y' AND v.b BETWEEN '2015-01-01' AND CURRENT_DATE),
sys AS (
  SELECT PWSID, COUNT(*) hb_n, SUM(has_pn) hb_pn, COUNT_IF(vc = '5200') c5200, SUM(IFF(vc = '5200', has_pn, 0)) c5200_pn,
         COUNT_IF(tier = '1') t1_n, SUM(IFF(tier = '1', has_pn, 0)) t1_pn, SUM(IFF(tier = '1', pn_unaddr, 0)) t1_pn_unaddr,
         LISTAGG(DISTINCT IFF(tier = '1' AND has_pn = 1, vc || ':' || cc, NULL), ',') t1_pn_codes,
         MIN(IFF(tier = '1' AND has_pn = 1, b, NULL)) t1_pn_first, MAX(IFF(tier = '1' AND has_pn = 1, b, NULL)) t1_pn_last
  FROM hb GROUP BY 1),
p AS (
  SELECT PWSID, ANY_VALUE(PWS_NAME) pws_name, ANY_VALUE(STATE_CODE) state_code, ANY_VALUE(PRIMACY_AGENCY_CODE) primacy, ANY_VALUE(PWS_TYPE_CODE) pws_type,
         ANY_VALUE(PWS_ACTIVITY_CODE) activity, MAX(POPULATION_SERVED_COUNT) pop, ANY_VALUE(CITY_NAME) city, ANY_VALUE(OWNER_TYPE_CODE) owner, COUNT(*) prow
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_SDWA_SDWA_PUB_WATER_SYSTEMS GROUP BY 1)
SELECT sys.*, p.pws_name, p.state_code, p.primacy, p.pws_type, p.activity, p.pop, p.city, p.owner, p.prow
FROM sys LEFT JOIN p ON p.PWSID = sys.PWSID;

-- S15 SDWA time: links by primacy prefix x year of the related violation x related category x tier, plus health-based violation denominators by the same cut
WITH v AS (
  SELECT PWSID, VIOLATION_ID, ANY_VALUE(VIOLATION_CATEGORY_CODE) cat, ANY_VALUE(IS_HEALTH_BASED_IND) hb, ANY_VALUE(PUBLIC_NOTIFICATION_TIER) tier,
         ANY_VALUE(COMPL_PER_BEGIN_DATE) b, ANY_VALUE(VIOLATION_CODE) vc
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_SDWA_SDWA_VIOLATIONS_ENFORCEMENT WHERE VIOLATION_ID IS NOT NULL GROUP BY 1,2),
a AS (SELECT DISTINCT PWSID, PN_VIOLATION_ID, RELATED_VIOLATION_ID, VIOLATION_CODE, COMPL_PER_BEGIN_DATE FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_SDWA_SDWA_PN_VIOLATION_ASSOC)
SELECT 'links' part, LEFT(a.PWSID,2) st, YEAR(a.COMPL_PER_BEGIN_DATE) y, COALESCE(vr.cat,'?') cat, COALESCE(vr.tier,'?') tier,
       COUNT(*) n, COUNT(DISTINCT a.PWSID || '|' || a.PN_VIOLATION_ID) pn_viols, COUNT(DISTINCT a.PWSID) systems
FROM a LEFT JOIN v vr ON vr.PWSID = a.PWSID AND vr.VIOLATION_ID = a.RELATED_VIOLATION_ID
GROUP BY 1,2,3,4,5
UNION ALL
SELECT 'hb_viols', LEFT(PWSID,2), YEAR(b), cat, tier, COUNT(*), COUNT_IF(vc = '5200'), COUNT(DISTINCT PWSID)
FROM v WHERE hb = 'Y' AND b BETWEEN '2005-01-01' AND CURRENT_DATE GROUP BY 1,2,3,4,5
UNION ALL
SELECT 'pn75_all', LEFT(PWSID,2), YEAR(b), 'PN', COALESCE(tier,'?'), COUNT(*), 0, COUNT(DISTINCT PWSID)
FROM v WHERE vc = '75' AND b BETWEEN '2005-01-01' AND CURRENT_DATE GROUP BY 1,2,3,4,5;
