-- S16 SDWA nitrate (contaminant 1040) health-based violations begun 2015 on, per system: count, how many carry a PN link, tier-1 count, years, measured level, open status
WITH v AS (
  SELECT PWSID, VIOLATION_ID, ANY_VALUE(VIOLATION_CODE) vc, ANY_VALUE(PUBLIC_NOTIFICATION_TIER) tier, ANY_VALUE(COMPL_PER_BEGIN_DATE) b,
         ANY_VALUE(VIOLATION_STATUS) status, ANY_VALUE(VIOL_MEASURE) m, ANY_VALUE(FEDERAL_MCL) fmcl, ANY_VALUE(UNIT_OF_MEASURE) u
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_SDWA_SDWA_VIOLATIONS_ENFORCEMENT
  WHERE VIOLATION_ID IS NOT NULL AND CONTAMINANT_CODE = '1040' AND IS_HEALTH_BASED_IND = 'Y' GROUP BY 1,2),
a AS (SELECT DISTINCT PWSID, RELATED_VIOLATION_ID FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_SDWA_SDWA_PN_VIOLATION_ASSOC)
SELECT v.PWSID, COUNT(*) n, COUNT_IF(a.PWSID IS NOT NULL) n_pn, COUNT_IF(v.tier = '1') t1, COUNT(DISTINCT YEAR(v.b)) years, MIN(v.b) first_b, MAX(v.b) last_b,
       MEDIAN(TRY_TO_DOUBLE(v.m)) med_level, MAX(TRY_TO_DOUBLE(v.m)) max_level, ANY_VALUE(v.fmcl) fmcl, ANY_VALUE(v.u) unit,
       COUNT_IF(v.status = 'Unaddressed') unaddr, LISTAGG(DISTINCT v.vc, ',') codes
FROM v LEFT JOIN a ON a.PWSID = v.PWSID AND a.RELATED_VIOLATION_ID = v.VIOLATION_ID
WHERE v.b BETWEEN '2015-01-01' AND CURRENT_DATE
GROUP BY 1;

-- S17 SDWA eyeball: every tier-1 violation since 2015 at Yuma AZ and three West Texas nitrate systems, with measured level, MCL, status, enforcement codes, and linked PN violations
WITH e AS (
  SELECT PWSID, VIOLATION_ID, ANY_VALUE(VIOLATION_CODE) vc, ANY_VALUE(CONTAMINANT_CODE) cc, ANY_VALUE(PUBLIC_NOTIFICATION_TIER) tier, ANY_VALUE(COMPL_PER_BEGIN_DATE) b,
         ANY_VALUE(VIOL_MEASURE) m, ANY_VALUE(FEDERAL_MCL) fmcl, ANY_VALUE(STATE_MCL) smcl, ANY_VALUE(UNIT_OF_MEASURE) u, ANY_VALUE(VIOLATION_STATUS) status,
         ANY_VALUE(FACILITY_ID) fac, LISTAGG(DISTINCT ENFORCEMENT_ACTION_TYPE_CODE || '@' || ENFORCEMENT_DATE::string, ' ') enf
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_SDWA_SDWA_VIOLATIONS_ENFORCEMENT
  WHERE PWSID IN ('AZ0414024','TX1650077','TX0480011','TX1520080') GROUP BY 1,2),
a AS (SELECT DISTINCT PWSID, PN_VIOLATION_ID, RELATED_VIOLATION_ID FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_SDWA_SDWA_PN_VIOLATION_ASSOC
      WHERE PWSID IN ('AZ0414024','TX1650077','TX0480011','TX1520080'))
SELECT e.PWSID, e.VIOLATION_ID, e.vc, e.cc, e.tier, e.b, e.m, e.fmcl, e.smcl, e.u, e.status, e.fac, e.enf,
       LISTAGG(DISTINCT p.VIOLATION_ID || ':' || p.status || ':' || p.b::string || ':' || COALESCE(p.enf,''), ' || ') pn
FROM e LEFT JOIN a ON a.PWSID = e.PWSID AND a.RELATED_VIOLATION_ID = e.VIOLATION_ID
LEFT JOIN e p ON p.PWSID = a.PWSID AND p.VIOLATION_ID = a.PN_VIOLATION_ID
WHERE e.tier = '1' AND e.b >= '2015-01-01'
GROUP BY 1,2,3,4,5,6,7,8,9,10,11,12,13 ORDER BY 1, 6;

-- S18 ICIS-Air informal actions by state x year x agency flag, 2016 on: does Missouri's air side drop the way its water letters did?
SELECT LEFT(PGM_SYS_ID, 2) st, STATE_EPA_FLAG who, YEAR(ACHIEVED_DATE) y, COUNT(DISTINCT ACTIVITY_ID) n, COUNT(DISTINCT PGM_SYS_ID) facilities
FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_INFORMAL_ACTIONS
WHERE ACHIEVED_DATE BETWEEN '2016-01-01' AND CURRENT_DATE
GROUP BY 1,2,3;
