-- S19 NPDES same-violation cohort: permits with effluent violations in 2+ quarters of a year, and the share that got any state informal action, or any formal action, that same year; every state, 2018-2025
WITH q AS (
  SELECT NPDES_ID, LEFT(NPDES_ID,2) st, TRY_TO_NUMBER(LEFT(YEARQTR,4)) y, COUNT_IF(TRY_TO_NUMBER(NUME90_Q) > 0) vq
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_NPDES_NPDES_QNCR_HISTORY
  WHERE TRY_TO_NUMBER(YEARQTR) BETWEEN 20181 AND 20254 GROUP BY 1,2,3),
i AS (
  SELECT DISTINCT NPDES_ID, YEAR(ACHIEVED_DATE) y FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_NPDES_NPDES_INFORMAL_ENFORCEMENT_ACTIONS
  WHERE AGENCY = 'State' AND ACHIEVED_DATE BETWEEN '2018-01-01' AND '2025-12-31'),
f AS (
  SELECT DISTINCT NPDES_ID, YEAR(SETTLEMENT_ENTERED_DATE) y FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_NPDES_NPDES_FORMAL_ENFORCEMENT_ACTIONS
  WHERE SETTLEMENT_ENTERED_DATE BETWEEN '2018-01-01' AND '2025-12-31')
SELECT q.st, q.y, COUNT(*) permits_2plus_viol_q, COUNT(i.NPDES_ID) got_state_letter, COUNT(f.NPDES_ID) got_formal,
       COUNT_IF(i.NPDES_ID IS NULL AND f.NPDES_ID IS NULL) got_neither, MEDIAN(q.vq) med_viol_q
FROM q LEFT JOIN i ON i.NPDES_ID = q.NPDES_ID AND i.y = q.y LEFT JOIN f ON f.NPDES_ID = q.NPDES_ID AND f.y = q.y
WHERE q.vq >= 2 GROUP BY 1,2;

-- S20 SDWA peer for Yuma: every acute chlorine dioxide MRDL violation (code 13) since 2015, per system, with PN link count
WITH v AS (
  SELECT PWSID, VIOLATION_ID, ANY_VALUE(COMPL_PER_BEGIN_DATE) b, ANY_VALUE(CONTAMINANT_CODE) cc, ANY_VALUE(VIOL_MEASURE) m
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_SDWA_SDWA_VIOLATIONS_ENFORCEMENT
  WHERE VIOLATION_ID IS NOT NULL AND VIOLATION_CODE = '13' GROUP BY 1,2),
a AS (SELECT DISTINCT PWSID, RELATED_VIOLATION_ID FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_SDWA_SDWA_PN_VIOLATION_ASSOC)
SELECT v.PWSID, LISTAGG(DISTINCT v.cc, ',') cc, COUNT(*) n, COUNT_IF(a.PWSID IS NOT NULL) n_pn, MIN(v.b) first_b, MAX(v.b) last_b, MAX(TRY_TO_DOUBLE(v.m)) max_m
FROM v LEFT JOIN a ON a.PWSID = v.PWSID AND a.RELATED_VIOLATION_ID = v.VIOLATION_ID
WHERE v.b BETWEEN '2015-01-01' AND CURRENT_DATE GROUP BY 1 ORDER BY n DESC;
