-- S22 ICIS-Air eyeball: LANXESS Charleston SC (EtO-regulated major, 3 open HPVs since 2020, no formal action since 2020): its violations, informal and formal actions, and its pollutant rows
SELECT 'violation' part, ACTIVITY_ID id, HPV_DAYZERO_DATE::string d1, HPV_RESOLVED_DATE::string d2, AGENCY_TYPE_DESC || ' | ' || COALESCE(ENF_RESPONSE_POLICY_CODE,'') || ' | ' || COALESCE(PROGRAM_DESCS,'') || ' | ' || COALESCE(POLLUTANT_DESCS,'') detail
FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_VIOLATION_HISTORY WHERE PGM_SYS_ID = 'SC00005600011'
UNION ALL
SELECT 'informal', ACTIVITY_ID, ACHIEVED_DATE::string, NULL, STATE_EPA_FLAG || ' | ' || ENF_TYPE_DESC
FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_INFORMAL_ACTIONS WHERE PGM_SYS_ID = 'SC00005600011'
UNION ALL
SELECT 'formal', ACTIVITY_ID, SETTLEMENT_ENTERED_DATE::string, PENALTY_AMOUNT::string, STATE_EPA_FLAG || ' | ' || ENF_TYPE_DESC
FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_FORMAL_ACTIONS WHERE PGM_SYS_ID = 'SC00005600011'
UNION ALL
SELECT 'pollutant', POLLUTANT_CODE, CHEMICAL_ABSTRACT_SERVICE_NMBR, AIR_POLLUTANT_CLASS_CODE, POLLUTANT_DESC
FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_POLLUTANTS WHERE PGM_SYS_ID = 'SC00005600011'
ORDER BY 1, 3;
