{{ config(tags=['spine_generated']) }}

-- GRAIN: one row per place (GEOM is unique)
-- SPINE_ENTITY: place  (natural_key: GEOMETRY)
-- Generated by scripts/generate_staging_models.py from SOURCE_REGISTRY -- deterministic,
-- no LLM.
-- CASTS: 15 of 36 columns, from landing_column_profile_2026-09-19.tsv. A column is cast only
-- when every filled value in the sample parsed. try_ casts: a value that does not
-- parse reads NULL. The natural key and join-key columns stay TEXT.
--   featurecod: integer
--   fid: ID: whole numbers, over 90% distinct -- stays TEXT, '.0' tail removed
--   hleft: integer
--   hrgt: integer
--   lleft: integer
--   lrgt: integer
--   mcdl: integer
--   mcdr: integer
--   no_lanes: integer
--   systemid: integer
--   unique_id: integer
--   update_yea: integer
--   userid: integer
--   zipl: integer
--   zipr: integer
-- spine_entity 'place' has no connect/ resolver yet (see connect/spine_entity.py) -- no SPINE_ENTITY_ID emitted.
-- landing table's ingestion timestamp is named INGESTED_AT (no leading underscore) rather than the usual _INGESTED_AT -- confirmed via INFORMATION_SCHEMA, not assumed.
-- DEDUPE: registry natural_key (GEOMETRY) is NOT unique within a load as landed at generation time -- it would collapse 24 of 2,929 rows. Deduping on the WHOLE ROW instead (exact copies only). A record that changes between loads shows once per version. Find the real key, fix SOURCE_REGISTRY, regenerate.

with source as (

    select * from {{ source('ripple_raw', 'PORTAL_CKA_WPRDC_ALLEGHENY_4E7D1F0FEA') }}
    qualify row_number() over (partition by "ALTERNATEN", "BELTWAY", "CFCC", "CREATEDBY", "CREATEDON", "FEATURECOD", "FID", "FROMSTREET", "GDTLINK", "HLEFT", "HRGT", "LLEFT", "LRGT", "MAJORRD", "MCDL", "MCDR", "MODIFIEDBY", "MODIFIEDON", "NAME", "NO_LANES", "ONEWAY", "OWNER", "PREFIX", "ROUTE_NO", "STREETNAME", "SUFFIX", "SYSTEMID", "SHAPE_LENG", "TOSTREET", "TYPE", "UNIQUE_ID", "UPDATE_YEA", "USERID", "ZIPL", "ZIPR", "GEOMETRY" order by INGESTED_AT desc) = 1

),

renamed as (

    select
        {{ null_junk('"ALTERNATEN"') }} as alternaten,
        {{ null_junk('"BELTWAY"') }} as beltway,
        {{ null_junk('"CFCC"') }} as cfcc,
        {{ null_junk('"CREATEDBY"') }} as createdby,
        {{ null_junk('"CREATEDON"') }} as createdon,
        {{ stg_int('"FEATURECOD"') }} as featurecod,
        {{ stg_id_text('"FID"') }} as fid,
        {{ null_junk('"FROMSTREET"') }} as fromstreet,
        {{ null_junk('"GDTLINK"') }} as gdtlink,
        {{ stg_int('"HLEFT"') }} as hleft,
        {{ stg_int('"HRGT"') }} as hrgt,
        {{ stg_int('"LLEFT"') }} as lleft,
        {{ stg_int('"LRGT"') }} as lrgt,
        {{ null_junk('"MAJORRD"') }} as majorrd,
        {{ stg_int('"MCDL"') }} as mcdl,
        {{ stg_int('"MCDR"') }} as mcdr,
        {{ null_junk('"MODIFIEDBY"') }} as modifiedby,
        {{ null_junk('"MODIFIEDON"') }} as modifiedon,
        {{ null_junk('"NAME"') }} as name,
        {{ stg_int('"NO_LANES"') }} as no_lanes,
        {{ null_junk('"ONEWAY"') }} as oneway,
        {{ null_junk('"OWNER"') }} as owner,
        {{ null_junk('"PREFIX"') }} as prefix,
        {{ null_junk('"ROUTE_NO"') }} as route_no,
        {{ null_junk('"STREETNAME"') }} as streetname,
        {{ null_junk('"SUFFIX"') }} as suffix,
        {{ stg_int('"SYSTEMID"') }} as systemid,
        {{ null_junk('"SHAPE_LENG"') }} as shape_leng,
        {{ null_junk('"TOSTREET"') }} as tostreet,
        {{ null_junk('"TYPE"') }} as type,
        {{ stg_int('"UNIQUE_ID"') }} as unique_id,
        {{ stg_int('"UPDATE_YEA"') }} as update_yea,
        {{ stg_int('"USERID"') }} as userid,
        {{ stg_int('"ZIPL"') }} as zipl,
        {{ stg_int('"ZIPR"') }} as zipr,
        {{ null_junk('"GEOMETRY"') }} as geometry,
        INGESTED_AT as _loaded_at,
        'https://data.wprdc.org/dataset/allegheny-county-beltway-system-street-centerlines' as _source_url

    from source

)

select * from renamed
