-- q04 ITIS vernaculars: lookup check. By language: rows, species IDs, name IDs, approved flag, update-date range, duplicate name rows
SELECT LANGUAGE, COUNT(*) n, COUNT(DISTINCT TSN) tsns, COUNT(DISTINCT VERN_ID) vern_ids,
       COUNT(DISTINCT ITIS_VERNACULARS_KEY) keys, COUNT(DISTINCT TSN, VERNACULAR_NAME) tsn_name_pairs,
       COUNT_IF(APPROVED_IND = 'Y') appr_y, COUNT_IF(APPROVED_IND = 'N') appr_n, COUNT_IF(APPROVED_IND NOT IN ('Y','N') OR APPROVED_IND IS NULL) appr_other,
       MIN(UPDATE_DATE) u0, MAX(UPDATE_DATE) u1, COUNT(DISTINCT _SOURCE_RUN_ID) runs, COUNT(DISTINCT _SRC_SHA256) files
FROM LIBRARY_MARTS.REFERENCE.REFERENCE__FED_ITIS_VERNACULARS
GROUP BY ROLLUP(LANGUAGE) ORDER BY n DESC
