-- q05 GNIS all names: shape. Official vs variant, features, citation ids, date sentinels, load runs
SELECT FEATURE_NAME_OFFICIAL, COUNT(*) n, COUNT(DISTINCT FEATURE_ID) features, COUNT(DISTINCT NAME_CITATION_ID) cit_ids,
       COUNT(DISTINCT FEATURE_ID, FEATURE_NAME) feat_names,
       MIN(PUBLICATION_DATE) p0, MAX(PUBLICATION_DATE) p1, COUNT_IF(PUBLICATION_DATE IS NULL) p_null,
       COUNT_IF(TO_CHAR(PUBLICATION_DATE,'MM-DD') = '12-31') p_dec31, COUNT_IF(TO_CHAR(PUBLICATION_DATE,'MM-DD') = '01-01') p_jan1,
       MIN(DATE_CREATED) c0, MAX(DATE_CREATED) c1, COUNT_IF(DATE_CREATED IS NULL) c_null,
       COUNT_IF(ENDING_DATE IS NOT NULL) end_filled,
       COUNT(DISTINCT SOURCE_RUN_ID) runs, COUNT(DISTINCT SRC_SHA256) files, MIN(INGESTED_AT) i0, MAX(INGESTED_AT) i1
FROM LIBRARY_MARTS.REFERENCE.REFERENCE__FED_USGS_GNIS_ALL_NAMES
GROUP BY ROLLUP(FEATURE_NAME_OFFICIAL) ORDER BY n DESC
