-- q07 GNIS time: official and variant rows by DATE_CREATED year, plus publication-date year for variants (is the variant half frozen?)
SELECT FEATURE_NAME_OFFICIAL, YEAR(DATE_CREATED) yr, COUNT(*) n, COUNT(DISTINCT FEATURE_ID) features,
       COUNT_IF(DATE_CREATED = PUBLICATION_DATE) created_eq_pub
FROM LIBRARY_MARTS.REFERENCE.REFERENCE__FED_USGS_GNIS_ALL_NAMES
WHERE DATE_CREATED IS NULL OR YEAR(DATE_CREATED) >= 1990 OR FEATURE_NAME_OFFICIAL = 'Official'
GROUP BY 1,2 ORDER BY 1,2
