-- q08 GNIS chain: features that carry a slur as a VARIANT name. What is their OFFICIAL name now, and when was that official citation published?
WITH v AS (
  SELECT DISTINCT FEATURE_ID,
         CASE WHEN REGEXP_LIKE(UPPER(FEATURE_NAME), '(^|[^A-Z])SQUAW.*') AND NOT REGEXP_LIKE(UPPER(FEATURE_NAME), '(^|[^A-Z])SQUAWK.*') THEN 'SQUAW'
              WHEN REGEXP_LIKE(UPPER(FEATURE_NAME), '(^|[^A-Z])NIGGER.*') THEN 'NIGGER'
              WHEN REGEXP_LIKE(UPPER(FEATURE_NAME), '(^|[^A-Z])JAPS?([^A-Z].*|$)') THEN 'JAP'
              WHEN REGEXP_LIKE(UPPER(FEATURE_NAME), '(^|[^A-Z])NEGRO.*') THEN 'NEGRO' END term
  FROM LIBRARY_MARTS.REFERENCE.REFERENCE__FED_USGS_GNIS_ALL_NAMES
  WHERE FEATURE_NAME_OFFICIAL = 'Variant'
), o AS (
  SELECT FEATURE_ID, FEATURE_NAME, PUBLICATION_DATE, DATE_CREATED, SOURCE_ORIGINATOR, CITATION
  FROM LIBRARY_MARTS.REFERENCE.REFERENCE__FED_USGS_GNIS_ALL_NAMES WHERE FEATURE_NAME_OFFICIAL = 'Official'
)
SELECT v.term,
       CASE WHEN o.FEATURE_ID IS NULL THEN 'no official row'
            WHEN REGEXP_LIKE(UPPER(o.FEATURE_NAME), '(^|[^A-Z])(SQUAW|NIGGER|JAPS?[^A-Z]|JAPS?$).*') AND NOT REGEXP_LIKE(UPPER(o.FEATURE_NAME), '.*SQUAWK.*') THEN 'official still has a slur'
            WHEN REGEXP_LIKE(UPPER(o.FEATURE_NAME), '(^|[^A-Z])NEGRO.*') THEN 'official has NEGRO'
            WHEN REGEXP_LIKE(UPPER(o.FEATURE_NAME), '(^|[^A-Z])JAPANESE.*') THEN 'official has JAPANESE'
            ELSE 'official is something else' END bucket,
       COUNT(*) features,
       COUNT_IF(YEAR(o.PUBLICATION_DATE) = 2022) off_pub_2022, COUNT_IF(YEAR(o.PUBLICATION_DATE) = 2023) off_pub_2023,
       COUNT_IF(YEAR(o.PUBLICATION_DATE) < 2021) off_pub_pre2021, COUNT_IF(o.PUBLICATION_DATE IS NULL) off_pub_null,
       MODE(o.SOURCE_ORIGINATOR) top_originator, MODE(o.CITATION) top_citation,
       ARRAY_SLICE(ARRAY_AGG(o.FEATURE_NAME) WITHIN GROUP (ORDER BY o.FEATURE_ID), 0, 8) official_names
FROM v LEFT JOIN o ON o.FEATURE_ID = v.FEATURE_ID
WHERE v.term IS NOT NULL
GROUP BY 1,2 ORDER BY 1, features DESC
