-- q11 Is there a GNIS table with state/county/feature class anywhere (marts or landing) to give GNIS a peer group?
SELECT TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, ROW_COUNT FROM LIBRARY_MARTS.INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME ILIKE '%GNIS%'
UNION ALL
SELECT TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, ROW_COUNT FROM LIBRARY_RAW.INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME ILIKE '%GNIS%'
