    with source as (
        select * from {{ source('ripple_raw', 'FED_CMS_PARTB_PROVIDER_SERVICE_DY2016') }}
    )

    select
        "NPI",
"RNDRNG_PRVDR_LAST_ORG_NAME",
"RNDRNG_PRVDR_FIRST_NAME",
"RNDRNG_PRVDR_MI",
"RNDRNG_PRVDR_CRDNTLS",
"RNDRNG_PRVDR_ENT_CD",
"RNDRNG_PRVDR_ST1",
"RNDRNG_PRVDR_ST2",
"RNDRNG_PRVDR_CITY",
"RNDRNG_PRVDR_STATE_ABRVTN",
"RNDRNG_PRVDR_STATE_FIPS",
"RNDRNG_PRVDR_ZIP5",
"RNDRNG_PRVDR_RUCA",
"RNDRNG_PRVDR_RUCA_DESC",
"RNDRNG_PRVDR_CNTRY",
"RNDRNG_PRVDR_TYPE",
"RNDRNG_PRVDR_MDCR_PRTCPTG_IND",
"HCPCS_CD",
"HCPCS_DESC",
"HCPCS_DRUG_IND",
"PLACE_OF_SRVC",
"TOT_BENES",
"TOT_SRVCS",
"TOT_BENE_DAY_SRVCS",
"AVG_SBMTD_CHRG",
"AVG_MDCR_ALOWD_AMT",
"AVG_MDCR_PYMT_AMT",
"AVG_MDCR_STDZD_AMT",
_INGESTED_AT,
_SOURCE_RUN_ID
    from source
    qualify row_number() over (
        partition by "NPI"
        order by _INGESTED_AT desc
    ) = 1
