{{ config(tags=['spine_generated']) }}

-- GRAIN: one row per record (spine_entity not determined -- no registry hint available) (FIPS+DATE unique)
-- SPINE_ENTITY: place  (natural_key: FIPS, DATE)
-- Generated by scripts/generate_staging_models.py from SOURCE_REGISTRY -- deterministic,
-- no LLM. Casts kept as landed (TEXT) -- add explicit type casts by hand once each
-- column's real type is confirmed; this generator has no semantic type knowledge.
-- spine_entity 'place' has no connect/ resolver yet (see connect/spine_entity.py) -- no SPINE_ENTITY_ID emitted.
-- landing table's ingestion timestamp is named INGESTED_AT (no leading underscore) rather than the usual _INGESTED_AT -- confirmed via INFORMATION_SCHEMA, not assumed.

with source as (

    select * from {{ source('ripple_raw', 'PORTAL_CKA_INDIANA_DATA_HUB_FE00D42ACC') }}

),

renamed as (

    select
        "DATE" as date,
        "COUNTY" as county,
        "REGION" as region,
        "FIPS" as fips,
        "SINGLE_DOSE_ADMINISTERED" as single_dose_administered,
        "ALL_DOSES_ADMINISTERED" as all_doses_administered,
        "FULLY_VACCINATED" as fully_vaccinated,
        "BOOSTER_DOSE_ADMINISTERED" as booster_dose_administered,
        "SECOND_BOOSTER_DOSE_ADMINISTERED" as second_booster_dose_administered,
        "CURRENT_AS_OF" as current_as_of,
        INGESTED_AT as _loaded_at,
        'https://hub.mph.in.gov/dataset/covid-19-vaccinations-by-date' as _source_url

    from source

)

select * from renamed
qualify row_number() over (partition by fips, date order by _loaded_at desc) = 1
