{{ config(tags=['spine_generated']) }}

-- GRAIN: one row per place (FIPS+DATE unique)
-- SPINE_ENTITY: place  (natural_key: FIPS, DATE)
-- Generated by scripts/generate_staging_models.py from SOURCE_REGISTRY -- deterministic,
-- no LLM. Casts kept as landed (TEXT) -- add explicit type casts by hand once each
-- column's real type is confirmed; this generator has no semantic type knowledge.
-- spine_entity 'place' has no connect/ resolver yet (see connect/spine_entity.py) -- no SPINE_ENTITY_ID emitted.
-- landing table's ingestion timestamp is named INGESTED_AT (no leading underscore) rather than the usual _INGESTED_AT -- confirmed via INFORMATION_SCHEMA, not assumed.
-- DEDUPE: registry natural_key (FIPS, DATE) is NOT unique within a load as landed at generation time -- it would collapse 134,129 of 216,533 rows. Deduping on the WHOLE ROW instead (exact copies only). A record that changes between loads shows once per version. Find the real key, fix SOURCE_REGISTRY, regenerate.

with source as (

    select * from {{ source('ripple_raw', 'PORTAL_CKA_INDIANA_DATA_HUB_FE00D42ACC') }}

),

renamed as (

    select
        "DATE" as date,
        "COUNTY" as county,
        "REGION" as region,
        "FIPS" as fips,
        "SINGLE_DOSE_ADMINISTERED" as single_dose_administered,
        "ALL_DOSES_ADMINISTERED" as all_doses_administered,
        "FULLY_VACCINATED" as fully_vaccinated,
        "BOOSTER_DOSE_ADMINISTERED" as booster_dose_administered,
        "SECOND_BOOSTER_DOSE_ADMINISTERED" as second_booster_dose_administered,
        "CURRENT_AS_OF" as current_as_of,
        "FIELD_NAME" as field_name,
        "FIELD_DESCRIPTION" as field_description,
        "NEW_FIRST_DOSE_ADMINISTERED" as new_first_dose_administered,
        "NEW_SECOND_DOSE_ADMINISTERED" as new_second_dose_administered,
        "NEW_SINGLE_DOSE_ADMINISTERED" as new_single_dose_administered,
        "NEW_ALL_DOSES_ADMINISTERED" as new_all_doses_administered,
        "NEW_FULLY_VACCINATED" as new_fully_vaccinated,
        "NEW_BOOSTER_DOSE_ADMINISTERED" as new_booster_dose_administered,
        "NEW_SECOND_BOOSTER_DOSE_ADMINISTERED" as new_second_booster_dose_administered,
        "FIRST_DOSE_ADMINISTERED" as first_dose_administered,
        "SECOND_DOSE_ADMINISTERED" as second_dose_administered,
        INGESTED_AT as _loaded_at,
        'https://hub.mph.in.gov/dataset/covid-19-vaccinations-by-date' as _source_url

    from source

)

select * from renamed
qualify row_number() over (partition by date, county, region, fips, single_dose_administered, all_doses_administered, fully_vaccinated, booster_dose_administered, second_booster_dose_administered, current_as_of, field_name, field_description, new_first_dose_administered, new_second_dose_administered, new_single_dose_administered, new_all_doses_administered, new_fully_vaccinated, new_booster_dose_administered, new_second_booster_dose_administered, first_dose_administered, second_dose_administered order by _loaded_at desc) = 1
