{{ config(materialized='view', schema='TIMELINE', alias='SCIENCE__FED_NSF_AWARDS') }}

-- GENERATED by scripts/census/gen_time_views.py -- do not hand-edit.
-- Regenerate after any change to reports/time_index/clock_index.csv.
--
-- Canonical clock for SCIENCE.SCIENCE__FED_NSF_AWARDS.
--   column : AWARD_DATE   (DATE)
--   means  : decided -- try_to_date(AWARD_DATE) — when NSF granted the award; an authority acting, and the best anchor on a 125-row sample table.
--   grain  : day
--
-- decided cannot be in the future -- if this row's value is, ripple_clock
-- reads 'planned' instead, not 'decided'. See ripple_row_clock in
-- macros/ripple_time.sql.
--
-- The original columns pass through untouched; the canonical four sit in front
-- of them. Rule 8 of the datetime standard: the raw column is never overwritten,
-- so a mis-parse is always recoverable.

select
    {{ ripple_window('src."AWARD_DATE"::timestamp_ntz') }} as ripple_ts,
    {{ ripple_grain('day') }} as ripple_grain,
    {{ ripple_row_clock(ripple_window('src."AWARD_DATE"::timestamp_ntz'), 'decided') }} as ripple_clock,
    'SCIENCE.SCIENCE__FED_NSF_AWARDS'::varchar as ripple_source,
    src.*
from {{ ref('science__fed_nsf_awards') }} as src
