-- S01 BOP statistics: all 50 rows, to see what the scrape actually holds
SELECT REPORT_DATE, CATEGORY, METRIC_NAME, METRIC_VALUE, METRIC_UNIT, FACILITY_TYPE, STATE_FIPS, SOURCE_URL
FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_BOP_STATISTICS
ORDER BY METRIC_VALUE DESC NULLS LAST, METRIC_NAME;

-- S02 CourtListener schools: lookup check, alias rows, EIN widths, and whether judge-education rows point at alias IDs
WITH s AS (SELECT * FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_COURTLISTENER_SCHOOLS),
     e AS (SELECT SCHOOL_ID, COUNT(*) n FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_COURTLISTENER_JUDGE_EDUCATIONS GROUP BY 1)
SELECT COUNT(*) rows_, COUNT(DISTINCT s.ID) ids, COUNT(DISTINCT UPPER(TRIM(s.NAME))) names,
       COUNT_IF(NULLIF(TRIM(s.IS_ALIAS_OF_ID),'') IS NOT NULL) alias_rows,
       COUNT_IF(NULLIF(TRIM(s.EIN),'') IS NULL OR s.EIN = 'None') ein_blank,
       COUNT_IF(LENGTH(REGEXP_REPLACE(s.EIN,'[^0-9]','')) = 9) ein_9,
       COUNT_IF(LENGTH(REGEXP_REPLACE(s.EIN,'[^0-9]','')) BETWEEN 1 AND 8) ein_short,
       COUNT_IF(s.EIN = '000000000') ein_zero,
       COUNT(DISTINCT IFF(LENGTH(REGEXP_REPLACE(s.EIN,'[^0-9]',''))=9, s.EIN, NULL)) ein_distinct9,
       SUM(e.n) edu_rows_landing, SUM(IFF(NULLIF(TRIM(s.IS_ALIAS_OF_ID),'') IS NOT NULL, e.n, 0)) edu_rows_on_alias_ids,
       (SELECT COUNT(*) FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_COURTLISTENER_JUDGE_EDUCATIONS) edu_rows_total,
       MIN(s.DATE_CREATED) c0, MAX(s.DATE_CREATED) c1, MAX(s.DATE_MODIFIED) m1
FROM s LEFT JOIN e ON e.SCHOOL_ID = s.ID;

-- S03 OWID terrorism: row types (country code, OWID_ aggregate, blank-code region), year span, duplicate keys, 1993 hole, text values
SELECT CASE WHEN NULLIF(TRIM(CODE),'') IS NULL THEN 'blank' WHEN CODE LIKE 'OWID_%' THEN 'owid' ELSE 'iso3' END kind,
       COUNT(*) n, COUNT(DISTINCT ENTITY) ents, MIN(YEAR) y0, MAX(YEAR) y1, COUNT(DISTINCT YEAR) yrs,
       COUNT(*) - COUNT(DISTINCT ENTITY, YEAR) dup_keys,
       COUNT_IF(YEAR = '1993') rows_1993, SUM(IFF(YEAR='1993', TRY_TO_NUMBER(FATALITIES), 0)) deaths_1993,
       SUM(IFF(YEAR='1992', TRY_TO_NUMBER(FATALITIES), 0)) deaths_1992, SUM(IFF(YEAR='1994', TRY_TO_NUMBER(FATALITIES), 0)) deaths_1994,
       COUNT_IF(TRY_TO_DOUBLE(FATALITIES) IS NULL) nonnum, COUNT_IF(TRY_TO_DOUBLE(FATALITIES) <> ROUND(TRY_TO_DOUBLE(FATALITIES))) fractional,
       ARRAY_AGG(DISTINCT IFF(NULLIF(TRIM(CODE),'') IS NULL OR CODE LIKE 'OWID_%', ENTITY, NULL)) agg_names,
       COUNT(DISTINCT WORLD_REGION_ACCORDING_TO_OWID) regions
FROM LIBRARY_MARTS.JUSTICE.JUSTICE__XC_OWID_TERRORISM_DEATHS
GROUP BY 1 ORDER BY 1;

-- S04 OWID homicide: same profile, plus the battery's repeated values 0 and 6.7583313
SELECT CASE WHEN NULLIF(TRIM(CODE),'') IS NULL THEN 'blank' WHEN CODE LIKE 'OWID_%' THEN 'owid' ELSE 'iso3' END kind,
       COUNT(*) n, COUNT(DISTINCT ENTITY) ents, MIN(YEAR) y0, MAX(YEAR) y1, COUNT(DISTINCT YEAR) yrs,
       COUNT(*) - COUNT(DISTINCT ENTITY, YEAR) dup_keys,
       COUNT_IF(TRY_TO_DOUBLE(HOMICIDE_RATE_PER_100_000_POPULATION) IS NULL) nonnum,
       COUNT_IF(TRY_TO_DOUBLE(HOMICIDE_RATE_PER_100_000_POPULATION) = 0) zeros,
       COUNT(DISTINCT IFF(TRY_TO_DOUBLE(HOMICIDE_RATE_PER_100_000_POPULATION) = 0, ENTITY, NULL)) zero_ents,
       COUNT_IF(HOMICIDE_RATE_PER_100_000_POPULATION LIKE '6.7583313%') v67583,
       ARRAY_AGG(DISTINCT IFF(HOMICIDE_RATE_PER_100_000_POPULATION LIKE '6.7583313%', ENTITY || ':' || YEAR, NULL)) v67583_where,
       ARRAY_AGG(DISTINCT IFF(NULLIF(TRIM(CODE),'') IS NULL OR CODE LIKE 'OWID_%', ENTITY, NULL)) agg_names
FROM LIBRARY_MARTS.JUSTICE.JUSTICE__XC_OWID_HOMICIDE
GROUP BY 1 ORDER BY 1;

-- S05 CISA KEV: duplicates, date span, ransomware flag values, fix-window lengths, CVE age at listing
SELECT YEAR(DATE_ADDED) yr_added, COUNT(*) n, COUNT(DISTINCT CVE_ID) cves,
       COUNT_IF(KNOWN_RANSOMWARE_CAMPAIGN_USE = 'Known') rw_known, COUNT_IF(KNOWN_RANSOMWARE_CAMPAIGN_USE NOT IN ('Known','Unknown') OR KNOWN_RANSOMWARE_CAMPAIGN_USE IS NULL) rw_other,
       MEDIAN(DATEDIFF('day', DATE_ADDED, DUE_DATE)) med_window, MIN(DATEDIFF('day', DATE_ADDED, DUE_DATE)) min_window, MAX(DATEDIFF('day', DATE_ADDED, DUE_DATE)) max_window,
       COUNT_IF(DATEDIFF('day', DATE_ADDED, DUE_DATE) < 14) under14, COUNT_IF(DATEDIFF('day', DATE_ADDED, DUE_DATE) > 21) over21,
       COUNT_IF(YEAR(DATE_ADDED) - TRY_TO_NUMBER(SPLIT_PART(CVE_ID,'-',2)) >= 5) cve_5yr_old,
       COUNT_IF(NULLIF(TRIM(CWES),'') IS NULL) cwe_blank, COUNT(DISTINCT VENDOR_PROJECT) vendors,
       MIN(DATE_ADDED) d0, MAX(DATE_ADDED) d1
FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_CISA_KEV
GROUP BY ROLLUP(1) ORDER BY 1;
