-- S06 OWID terrorism: full extract (10,481 rows) for local time and peer math
SELECT ENTITY, CODE, YEAR, FATALITIES, WORLD_REGION_ACCORDING_TO_OWID
FROM LIBRARY_MARTS.JUSTICE.JUSTICE__XC_OWID_TERRORISM_DEATHS;

-- S07 OWID homicide: full extract (4,912 rows) for local time and peer math
SELECT ENTITY, CODE, YEAR, HOMICIDE_RATE_PER_100_000_POPULATION, WORLD_REGION_ACCORDING_TO_OWID
FROM LIBRARY_MARTS.JUSTICE.JUSTICE__XC_OWID_HOMICIDE;

-- S08 CISA KEV: full extract (1,674 rows) for vendor peer, deadline and ransomware-flag math
SELECT CVE_ID, VENDOR_PROJECT, PRODUCT, VULNERABILITY_NAME, DATE_ADDED, DUE_DATE, KNOWN_RANSOMWARE_CAMPAIGN_USE,
       REQUIRED_ACTION, CWES, SHORT_DESCRIPTION, NOTES
FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_CISA_KEV;

-- S09 CourtListener schools: full extract (6,011 rows) to eyeball shared EINs and aliases
SELECT ID, NAME, EIN, IS_ALIAS_OF_ID, DATE_CREATED, DATE_MODIFIED
FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_COURTLISTENER_SCHOOLS;
