-- S10 USAspending contracts R2 x KEV edge vendors: every FY2020+ contract action whose description or recipient names Ivanti/Pulse, Fortinet, Citrix/NetScaler, Palo Alto Networks or SonicWall
WITH x AS (
  SELECT CONTRACT_AWARD_UNIQUE_KEY, AWARD_ID_PIID, ACTION_DATE, FEDERAL_ACTION_OBLIGATION, AWARDING_AGENCY_NAME, AWARDING_SUB_AGENCY_NAME,
         RECIPIENT_NAME, RECIPIENT_PARENT_NAME, PRODUCT_OR_SERVICE_CODE_DESCRIPTION, TRANSACTION_DESCRIPTION, _LOADED_AT,
         UPPER(COALESCE(TRANSACTION_DESCRIPTION,'') || ' | ' || COALESCE(RECIPIENT_NAME,'') || ' | ' || COALESCE(RECIPIENT_PARENT_NAME,'')) d
  FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_USASPENDING_CONTRACTS_FULL_R2
  WHERE ACTION_DATE >= '2019-10-01'
)
SELECT CASE WHEN REGEXP_INSTR(d, 'IVANTI|PULSE ?SECURE|PULSE CONNECT|CONNECT SECURE') > 0 THEN 'IVANTI'
            WHEN REGEXP_INSTR(d, 'FORTINET|FORTIGATE|FORTIANALYZER|FORTIMANAGER|FORTIWEB|FORTICLIENT|FORTIAUTHENTICATOR') > 0 THEN 'FORTINET'
            WHEN REGEXP_INSTR(d, 'CITRIX|NETSCALER') > 0 THEN 'CITRIX'
            WHEN REGEXP_INSTR(d, 'PALO ALTO NETWORKS|PALOALTO NETWORKS|GLOBALPROTECT|GLOBAL PROTECT|PAN-OS|PRISMA ACCESS|CORTEX XDR') > 0 THEN 'PALOALTO'
            WHEN REGEXP_INSTR(d, 'SONICWALL|SONIC WALL') > 0 THEN 'SONICWALL' END tag,
       REGEXP_INSTR(d, 'PULSE ?SECURE|PULSE CONNECT|CONNECT SECURE|PULSE VPN|IVANTI VPN|ICS ') > 0 AS vpn_word,
       CONTRACT_AWARD_UNIQUE_KEY, AWARD_ID_PIID, ACTION_DATE, FEDERAL_ACTION_OBLIGATION, AWARDING_AGENCY_NAME, AWARDING_SUB_AGENCY_NAME,
       RECIPIENT_NAME, RECIPIENT_PARENT_NAME, PRODUCT_OR_SERVICE_CODE_DESCRIPTION, LEFT(TRANSACTION_DESCRIPTION, 300) descr, _LOADED_AT
FROM x
WHERE REGEXP_INSTR(d, 'IVANTI|PULSE ?SECURE|PULSE CONNECT|CONNECT SECURE|FORTINET|FORTIGATE|FORTIANALYZER|FORTIMANAGER|FORTIWEB|FORTICLIENT|FORTIAUTHENTICATOR|CITRIX|NETSCALER|PALO ALTO NETWORKS|PALOALTO NETWORKS|GLOBALPROTECT|GLOBAL PROTECT|PAN-OS|PRISMA ACCESS|CORTEX XDR|SONICWALL|SONIC WALL') > 0;
