{{ config(materialized='view') }}

/*
  Hand-built 2026-08-09 for the dead-source rebuild sprint (fed_fra_equipment_accidents).
  Grain: one row = one railroad's report of a rail equipment accident (Form 54); the same accident may appear once per involved railroad
  REPORT_KEY is NOT unique (197,234 distinct over 224,941 rows; content differs across duplicates -- multi-railroad and amended filings). Kept as landed: dedup here would silently discard 27k reports. Aggregate carefully in marts.
*/

with source as (
    select * from {{ source('ripple_raw', 'FED_FRA_EQUIPMENT_ACCIDENTS') }}
),

renamed as (
    select
        nullif(trim("REPORTING_RAILROAD_CODE"), '') as reporting_railroad_code,
        nullif(trim("REPORTING_RAILROAD_NAME"), '') as reporting_railroad_name,
        nullif(trim("YEAR"), '') as year,
        nullif(trim("ACCIDENT_NUMBER"), '') as accident_number,
        nullif(trim("PDF_LINK"), '') as pdf_link,
        nullif(trim("ACCIDENT_YEAR"), '') as accident_year,
        nullif(trim("ACCIDENT_MONTH"), '') as accident_month,
        nullif(trim("OTHER_RAILROAD_CODE"), '') as other_railroad_code,
        nullif(trim("OTHER_RAILROAD_NAME"), '') as other_railroad_name,
        nullif(trim("OTHER_ACCIDENT_NUMBER"), '') as other_accident_number,
        nullif(trim("OTHER_ACCIDENT_YEAR"), '') as other_accident_year,
        nullif(trim("OTHER_ACCIDENT_MONTH"), '') as other_accident_month,
        nullif(trim("MAINTENANCE_RAILROAD_CODE"), '') as maintenance_railroad_code,
        nullif(trim("MAINTENANCE_RAILROAD_NAME"), '') as maintenance_railroad_name,
        nullif(trim("MAINTENANCE_ACCIDENT_NUMBER"), '') as maintenance_accident_number,
        nullif(trim("MAINTENANCE_ACCIDENT_YEAR"), '') as maintenance_accident_year,
        nullif(trim("MAINTENANCE_ACCIDENT_MONTH"), '') as maintenance_accident_month,
        nullif(trim("GRADE_CROSSING_ID"), '') as grade_crossing_id,
        nullif(trim("DAY"), '') as day,
        try_to_date(trim("DATE"), 'MM/DD/YYYY') as date,
        nullif(trim("TIME"), '') as time,
        nullif(trim("ACCIDENT_TYPE_CODE"), '') as accident_type_code,
        nullif(trim("ACCIDENT_TYPE"), '') as accident_type,
        try_to_number(replace(trim("HAZMAT_CARS"), ',', '')) as hazmat_cars,
        try_to_number(replace(trim("HAZMAT_CARS_DAMAGED"), ',', '')) as hazmat_cars_damaged,
        try_to_number(replace(trim("HAZMAT_RELEASED_CARS"), ',', '')) as hazmat_released_cars,
        try_to_number(replace(trim("PERSONS_EVACUATED"), ',', '')) as persons_evacuated,
        nullif(trim("SUBDIVISION"), '') as subdivision,
        nullif(trim("DIVISION_CODE"), '') as division_code,
        nullif(trim("DIVISION"), '') as division,
        nullif(trim("STATION"), '') as station,
        nullif(trim("MILEPOST"), '') as milepost,
        nullif(trim("STATE_CODE"), '') as state_code,
        nullif(trim("STATE_ABBREVIATION"), '') as state_abbreviation,
        nullif(trim("STATE_NAME"), '') as state_name,
        nullif(trim("COUNTY_CODE"), '') as county_code,
        nullif(trim("COUNTY_NAME"), '') as county_name,
        nullif(trim("DISTRICT"), '') as district,
        try_to_number(replace(trim("TEMPERATURE"), ',', '')) as temperature,
        nullif(trim("VISIBILITY_CODE"), '') as visibility_code,
        nullif(trim("VISIBILITY"), '') as visibility,
        nullif(trim("WEATHER_CONDITION_CODE"), '') as weather_condition_code,
        nullif(trim("WEATHER_CONDITION"), '') as weather_condition,
        nullif(trim("TRACK_TYPE_CODE"), '') as track_type_code,
        nullif(trim("TRACK_TYPE"), '') as track_type,
        nullif(trim("TRACK_NAME"), '') as track_name,
        nullif(trim("TRACK_CLASS"), '') as track_class,
        nullif(trim("TRACK_DENSITY"), '') as track_density,
        nullif(trim("TRAIN_DIRECTION_CODE"), '') as train_direction_code,
        nullif(trim("TRAIN_DIRECTION"), '') as train_direction,
        nullif(trim("EQUIPMENT_TYPE_CODE"), '') as equipment_type_code,
        nullif(trim("EQUIPMENT_TYPE"), '') as equipment_type,
        nullif(trim("EQUIPMENT_ATTENDED"), '') as equipment_attended,
        nullif(trim("TRAIN_NUMBER"), '') as train_number,
        try_to_number(replace(trim("TRAIN_SPEED"), ',', '')) as train_speed,
        nullif(trim("RECORDED_ESTIMATED_SPEED"), '') as recorded_estimated_speed,
        try_to_number(replace(trim("MAXIMUM_SPEED"), ',', '')) as maximum_speed,
        try_to_number(replace(trim("GROSS_TONNAGE"), ',', '')) as gross_tonnage,
        nullif(trim("SIGNALIZATION_CODE"), '') as signalization_code,
        nullif(trim("SIGNALIZATION"), '') as signalization,
        nullif(trim("METHOD_OF_OPERATION_CODE"), '') as method_of_operation_code,
        nullif(trim("METHOD_OF_OPERATION"), '') as method_of_operation,
        nullif(trim("ADJUNCT_CODE_1"), '') as adjunct_code_1,
        nullif(trim("ADJUNCT_NAME_1"), '') as adjunct_name_1,
        nullif(trim("ADJUNCT_CODE_2"), '') as adjunct_code_2,
        nullif(trim("ADJUNCT_NAME_2"), '') as adjunct_name_2,
        nullif(trim("ADJUNCT_CODE_3"), '') as adjunct_code_3,
        nullif(trim("ADJUNCT_NAME_3"), '') as adjunct_name_3,
        nullif(trim("REMOTE_CONTROL_LOCOMOTIVE_CODE"), '') as remote_control_locomotive_code,
        nullif(trim("REMOTE_CONTROL_LOCOMOTIVE"), '') as remote_control_locomotive,
        nullif(trim("FIRST_CAR_INITIALS"), '') as first_car_initials,
        nullif(trim("FIRST_CAR_NUMBER"), '') as first_car_number,
        nullif(trim("FIRST_CAR_POSITION"), '') as first_car_position,
        nullif(trim("FIRST_CAR_LOADED"), '') as first_car_loaded,
        nullif(trim("CAUSING_CAR_INITIALS"), '') as causing_car_initials,
        nullif(trim("CAUSING_CAR_NUMBER"), '') as causing_car_number,
        nullif(trim("CAUSING_CAR_POSITION"), '') as causing_car_position,
        nullif(trim("CAUSING_CAR_LOADED"), '') as causing_car_loaded,
        nullif(trim("POSITIVE_ALCOHOL_TESTS"), '') as positive_alcohol_tests,
        nullif(trim("POSITIVE_DRUG_TESTS"), '') as positive_drug_tests,
        nullif(trim("PASSENGERS_TRANSPORTED"), '') as passengers_transported,
        nullif(trim("HEAD_END_LOCOMOTIVES"), '') as head_end_locomotives,
        nullif(trim("MID_TRAIN_MANUAL_LOCOMOTIVES"), '') as mid_train_manual_locomotives,
        nullif(trim("MID_TRAIN_REMOTE_LOCOMOTIVES"), '') as mid_train_remote_locomotives,
        nullif(trim("REAR_END_MANUAL_LOCOMOTIVES"), '') as rear_end_manual_locomotives,
        nullif(trim("REAR_END_REMOTE_LOCOMOTIVES"), '') as rear_end_remote_locomotives,
        nullif(trim("DERAILED_HEAD_END_LOCOMOTIVES"), '') as derailed_head_end_locomotives,
        nullif(trim("DERAILED_MID_TRAIN_MANUAL_LOCOMOTIVES"), '') as derailed_mid_train_manual_locomotives,
        nullif(trim("DERAILED_MID_TRAIN_REMOTE_LOCOMOTIVES"), '') as derailed_mid_train_remote_locomotives,
        nullif(trim("DERAILED_REAR_END_MANUAL_LOCOMOTIVES"), '') as derailed_rear_end_manual_locomotives,
        nullif(trim("DERAILED_REAR_END_REMOTE_LOCOMOTIVES"), '') as derailed_rear_end_remote_locomotives,
        nullif(trim("LOADED_FREIGHT_CARS"), '') as loaded_freight_cars,
        nullif(trim("LOADED_PASSENGER_CARS"), '') as loaded_passenger_cars,
        nullif(trim("EMPTY_FREIGHT_CARS"), '') as empty_freight_cars,
        nullif(trim("EMPTY_PASSENGER_CARS"), '') as empty_passenger_cars,
        nullif(trim("CABOOSES"), '') as cabooses,
        nullif(trim("DERAILED_LOADED_FREIGHT_CARS"), '') as derailed_loaded_freight_cars,
        nullif(trim("DERAILED_LOADED_PASSENGER_CARS"), '') as derailed_loaded_passenger_cars,
        nullif(trim("DERAILED_EMPTY_FREIGHT_CARS"), '') as derailed_empty_freight_cars,
        nullif(trim("DERAILED_EMPTY_PASSENGER_CARS"), '') as derailed_empty_passenger_cars,
        nullif(trim("DERAILED_CABOOSES"), '') as derailed_cabooses,
        try_to_number(replace(trim("EQUIPMENT_DAMAGE_COST"), ',', '')) as equipment_damage_cost,
        try_to_number(replace(trim("TRACK_DAMAGE_COST"), ',', '')) as track_damage_cost,
        try_to_number(replace(trim("TOTAL_DAMAGE_COST"), ',', '')) as total_damage_cost,
        nullif(trim("PRIMARY_ACCIDENT_CAUSE_CODE"), '') as primary_accident_cause_code,
        nullif(trim("PRIMARY_ACCIDENT_CAUSE"), '') as primary_accident_cause,
        nullif(trim("CONTRIBUTING_ACCIDENT_CAUSE_CODE"), '') as contributing_accident_cause_code,
        nullif(trim("CONTRIBUTING_ACCIDENT_CAUSE"), '') as contributing_accident_cause,
        nullif(trim("ACCIDENT_CAUSE_CODE"), '') as accident_cause_code,
        nullif(trim("ACCIDENT_CAUSE"), '') as accident_cause,
        nullif(trim("ENGINEERS_ON_DUTY"), '') as engineers_on_duty,
        nullif(trim("FIREMEN_ON_DUTY"), '') as firemen_on_duty,
        nullif(trim("CONDUCTORS_ON_DUTY"), '') as conductors_on_duty,
        nullif(trim("BRAKEMEN_ON_DUTY"), '') as brakemen_on_duty,
        nullif(trim("HOURS_ENGINEERS_ON_DUTY"), '') as hours_engineers_on_duty,
        nullif(trim("MINUTES_ENGINEERS_ON_DUTY"), '') as minutes_engineers_on_duty,
        nullif(trim("HOURS_CONDUCTORS_ON_DUTY"), '') as hours_conductors_on_duty,
        nullif(trim("MINUTES_CONDUCTORS_ON_DUTY"), '') as minutes_conductors_on_duty,
        try_to_number(replace(trim("RAILROAD_EMPLOYEES_KILLED"), ',', '')) as railroad_employees_killed,
        try_to_number(replace(trim("RAILROAD_EMPLOYEES_INJURED"), ',', '')) as railroad_employees_injured,
        try_to_number(replace(trim("PASSENGERS_KILLED"), ',', '')) as passengers_killed,
        try_to_number(replace(trim("PASSENGERS_INJURED"), ',', '')) as passengers_injured,
        try_to_number(replace(trim("OTHERS_KILLED"), ',', '')) as others_killed,
        try_to_number(replace(trim("OTHERS_INJURED"), ',', '')) as others_injured,
        nullif(trim("REPORTING_RAILROAD_FATALITIES_FOR_55A"), '') as reporting_railroad_fatalities_for_55a,
        nullif(trim("REPORTING_RAILROAD_INJURIES_FOR_55A"), '') as reporting_railroad_injuries_for_55a,
        try_to_number(replace(trim("TOTAL_PERSONS_KILLED"), ',', '')) as total_persons_killed,
        try_to_number(replace(trim("TOTAL_PERSONS_INJURED"), ',', '')) as total_persons_injured,
        nullif(trim("TOTAL_KILLED_FORM_54"), '') as total_killed_form_54,
        nullif(trim("TOTAL_INJURED_FORM_54"), '') as total_injured_form_54,
        nullif(trim("SPECIAL_STUDY_1"), '') as special_study_1,
        nullif(trim("SPECIAL_STUDY_2"), '') as special_study_2,
        try_to_double(replace(trim("LATITUDE"), ',', '')) as latitude,
        try_to_double(replace(trim("LONGITUDE"), ',', '')) as longitude,
        nullif(trim("NARRATIVE"), '') as narrative,
        nullif(trim("JOINT_TRACK_TYPE"), '') as joint_track_type,
        nullif(trim("JOINT_TRACK_CLASS"), '') as joint_track_class,
        nullif(trim("CLASS_CODE"), '') as class_code,
        nullif(trim("CLASS"), '') as class,
        nullif(trim("JOINT_CD"), '') as joint_cd,
        nullif(trim("INCIDENT_KEY"), '') as incident_key,
        nullif(trim("REPORT_KEY"), '') as report_key,
        nullif(trim("REPORTING_RAILROAD_CLASS"), '') as reporting_railroad_class,
        nullif(trim("REPORTING_RAILROAD_SMT_GROUPING"), '') as reporting_railroad_smt_grouping,
        nullif(trim("REPORTING_PARENT_RAILROAD_CODE"), '') as reporting_parent_railroad_code,
        nullif(trim("REPORTING_PARENT_RAILROAD_NAME"), '') as reporting_parent_railroad_name,
        nullif(trim("REPORTING_RAILROAD_HOLDING_COMPANY"), '') as reporting_railroad_holding_company,
        nullif(trim("REPORTING_RAILROAD_INDIVIDUAL_CLASS"), '') as reporting_railroad_individual_class,
        nullif(trim("REPORTING_RAILROAD_PASSENGER"), '') as reporting_railroad_passenger,
        nullif(trim("REPORTING_RAILROAD_COMMUTER"), '') as reporting_railroad_commuter,
        nullif(trim("REPORTING_RAILROAD_SWITCHING_TERMINAL"), '') as reporting_railroad_switching_terminal,
        nullif(trim("REPORTING_RAILROAD_TOURIST"), '') as reporting_railroad_tourist,
        nullif(trim("REPORTING_RAILROAD_FREIGHT"), '') as reporting_railroad_freight,
        nullif(trim("REPORTING_RAILROAD_SHORT_LINE"), '') as reporting_railroad_short_line,
        nullif(trim("LOCATION"), '') as location,
        to_timestamp_ntz(_INGESTED_AT, 6) as _ingested_at,
        nullif(trim(_SOURCE_RUN_ID), '') as _source_run_id
    from source
)

select * from renamed
