-- Miss test: search Form AP by ISSUER NAME (any CIK, any row version) for the no-audit-on-file companies, in case the audit sits under a wrong or blank CIK
with names as (select column1 k, column2 pat from values
  ('GOLD ROCK','%GOLD ROCK HOLD%'),('BRAVO','%BRAVO MULTI%'),('PHOTOZOU','%PHOTOZOU%'),('MIDNIGHT','%MIDNIGHT GAMING%'),
  ('FRANKSPEECH','%FRANKSPEECH%'),('INTERNET SCI','%INTERNET SCIENCES%'),('GEX','%GEX MANAGEMENT%'),('PHI','PHI GROUP%'),
  ('MCX','%MCX TECH%'),('COLLECTIVE','%COLLECTIVE AUDIENCE%'),('RESONATE','%RESONATE BLENDS%'),('DOGECOIN','%DOGECOIN CASH%'),
  ('AMERICANN','%AMERICANN%'),('FCCC','FCCC%'),('INNOVATIVE DESIGNS','%INNOVATIVE DESIGNS%'),('NFINITI','%NFINITI%'),
  ('IRONSTONE','%IRONSTONE PROP%'),('SCANTECH','%SCANTECH%'),('MOVEIX','%MOVEIX%'),('NEXT-CHEMX','%NEXT%CHEMX%'),('MADISON TECH','%MADISON TECHNOLOGIES%'),
  ('CAN B','CAN B%'),('VNUE','VNUE%'))
select n.k, a.ISSUER_NAME, a.ISSUER_CIK, a.ISSUER_CIK_NONE, a.FIRM_NAME, a.FISCAL_PERIOD_END_DATE, a.AUDIT_REPORT_DATE, a.LATEST_FORM_AP_FILING, a.IS_MULTIPLE_AUDIT_PERIOD, a.AUDIT_PERIOD_INFORMATION
from names n left join LIBRARY_MARTS.FINANCE.FINANCE__FED_PCAOB_FORM_AP_FILINGS a on upper(a.ISSUER_NAME) like n.pat and a.FISCAL_PERIOD_END_DATE >= '2023-06-01'
order by n.k, a.FISCAL_PERIOD_END_DATE
