{{ config(tags=['spine_generated']) }}

-- GRAIN: one row per event (EVENT_ID unique)
-- SPINE_ENTITY: event  (natural_key: EVENT_ID)
-- Generated by scripts/generate_staging_models.py from SOURCE_REGISTRY -- deterministic,
-- no LLM. Casts kept as landed (TEXT) -- add explicit type casts by hand once each
-- column's real type is confirmed; this generator has no semantic type knowledge.
-- spine_entity 'event' has no connect/ resolver yet (see connect/spine_entity.py) -- no SPINE_ENTITY_ID emitted.
-- landing table's ingestion timestamp is named INGESTED_AT (no leading underscore) rather than the usual _INGESTED_AT -- confirmed via INFORMATION_SCHEMA, not assumed.

with source as (

    select * from {{ source('ripple_raw', 'FED_NOAA_STORM_EVENTS') }}

),

renamed as (

    select
        "BEGIN_YEARMONTH" as begin_yearmonth,
        "BEGIN_DAY" as begin_day,
        "BEGIN_TIME" as begin_time,
        "END_YEARMONTH" as end_yearmonth,
        "END_DAY" as end_day,
        "END_TIME" as end_time,
        "EPISODE_ID" as episode_id,
        "EVENT_ID" as event_id,
        "STATE" as state,
        "STATE_FIPS" as state_fips,
        "YEAR" as year,
        "MONTH_NAME" as month_name,
        "EVENT_TYPE" as event_type,
        "CZ_TYPE" as cz_type,
        "CZ_FIPS" as cz_fips,
        "CZ_NAME" as cz_name,
        "WFO" as wfo,
        "BEGIN_DATE_TIME" as begin_date_time,
        "CZ_TIMEZONE" as cz_timezone,
        "END_DATE_TIME" as end_date_time,
        "INJURIES_DIRECT" as injuries_direct,
        "INJURIES_INDIRECT" as injuries_indirect,
        "DEATHS_DIRECT" as deaths_direct,
        "DEATHS_INDIRECT" as deaths_indirect,
        "DAMAGE_PROPERTY" as damage_property,
        "DAMAGE_CROPS" as damage_crops,
        "SOURCE" as source,
        "MAGNITUDE" as magnitude,
        "MAGNITUDE_TYPE" as magnitude_type,
        "FLOOD_CAUSE" as flood_cause,
        "CATEGORY" as category,
        "TOR_F_SCALE" as tor_f_scale,
        "TOR_LENGTH" as tor_length,
        "TOR_WIDTH" as tor_width,
        "TOR_OTHER_WFO" as tor_other_wfo,
        "TOR_OTHER_CZ_STATE" as tor_other_cz_state,
        "TOR_OTHER_CZ_FIPS" as tor_other_cz_fips,
        "TOR_OTHER_CZ_NAME" as tor_other_cz_name,
        "BEGIN_RANGE" as begin_range,
        "BEGIN_AZIMUTH" as begin_azimuth,
        "BEGIN_LOCATION" as begin_location,
        "END_RANGE" as end_range,
        "END_AZIMUTH" as end_azimuth,
        "END_LOCATION" as end_location,
        "BEGIN_LAT" as begin_lat,
        "BEGIN_LON" as begin_lon,
        "END_LAT" as end_lat,
        "END_LON" as end_lon,
        "EPISODE_NARRATIVE" as episode_narrative,
        "EVENT_NARRATIVE" as event_narrative,
        "DATA_SOURCE" as data_source,
        INGESTED_AT as _loaded_at,
        'https://www.ncei.noaa.gov/pub/data/swdi/stormevents/csvfiles/StormEvents_details-ftp_v1.0_d2025_c20260526.csv.gz' as _source_url

    from source

)

select * from renamed
qualify row_number() over (partition by event_id order by _loaded_at desc) = 1
