{{ config(tags=['spine_generated']) }}

-- GRAIN: one row per place (GEOM is unique)
-- SPINE_ENTITY: place  (natural_key: SHAPE__LENGTH)
-- Generated by scripts/generate_staging_models.py from SOURCE_REGISTRY -- deterministic,
-- no LLM. Casts kept as landed (TEXT) -- add explicit type casts by hand once each
-- column's real type is confirmed; this generator has no semantic type knowledge.
-- spine_entity 'place' has no connect/ resolver yet (see connect/spine_entity.py) -- no SPINE_ENTITY_ID emitted.
-- landing table's ingestion timestamp is named INGESTED_AT (no leading underscore) rather than the usual _INGESTED_AT -- confirmed via INFORMATION_SCHEMA, not assumed.

with source as (

    select * from {{ source('ripple_raw', 'PORTAL_CKA_CALIFORNIA_OPEN_CB7C3747FC') }}

),

renamed as (

    select
        "OBJECTID" as objectid,
        "CO" as co,
        "COUNTY" as county,
        "CITY" as city,
        "COPRI" as copri,
        "CDTFA_ID" as cdtfa_id,
        "CREATED_USER" as created_user,
        "CREATED_DATE" as created_date,
        "LAST_EDITED_USER" as last_edited_user,
        "LAST_EDITED_DATE" as last_edited_date,
        "GLOBALID" as globalid,
        "SHAPE__AREA" as shape__area,
        "SHAPE__LENGTH" as shape__length,
        INGESTED_AT as _loaded_at,
        'https://data.ca.gov/dataset/boe-citycounty' as _source_url

    from source

)

select * from renamed
qualify row_number() over (partition by shape__length order by _loaded_at desc) = 1
