{{ config(tags=['spine_generated']) }}

-- GRAIN: one row per place (GEOM is unique)
-- SPINE_ENTITY: place  (natural_key: SHAPE_LENGTH)
-- Generated by scripts/generate_staging_models.py from SOURCE_REGISTRY -- deterministic,
-- no LLM.
-- CASTS: 4 of 14 columns, from landing_column_profile_2026-09-19.tsv. A column is cast only
-- when every filled value in the sample parsed. try_ casts: a value that does not
-- parse reads NULL. The natural key and join-key columns stay TEXT.
--   objectid: ID: whole numbers, over 90% distinct -- stays TEXT, '.0' tail removed
--   facilityid: ID: whole numbers, over 90% distinct -- stays TEXT, '.0' tail removed
--   intid: ID: whole numbers, over 90% distinct -- stays TEXT, '.0' tail removed
--   projectyear: integer
-- spine_entity 'place' has no connect/ resolver yet (see connect/spine_entity.py) -- no SPINE_ENTITY_ID emitted.
-- landing table's ingestion timestamp is named INGESTED_AT (no leading underscore) rather than the usual _INGESTED_AT -- confirmed via INFORMATION_SCHEMA, not assumed.
-- DEDUPE: registry natural_key (SHAPE_LENGTH) is NOT unique within a load as landed at generation time -- it would collapse 14 of 3,591 rows. Deduping on the WHOLE ROW instead (exact copies only). A record that changes between loads shows once per version. Find the real key, fix SOURCE_REGISTRY, regenerate.

with source as (

    select * from {{ source('ripple_raw', 'PORTAL_CKA_SAN_JOSE_OPEN_DA_9BCCE40A0F') }}
    qualify row_number() over (partition by "OBJECTID", "FACILITYID", "INTID", "SALESFORCEID", "STREETNAME", "STREETTO", "STREETFROM", "EXPIRATION", "PROJECT", "PROJECTYEAR", "CREATIONDATE", "LASTUPDATE", "NOTES", "SHAPE_LENGTH" order by INGESTED_AT desc) = 1

),

renamed as (

    select
        {{ stg_id_text('"OBJECTID"') }} as objectid,
        {{ stg_id_text('"FACILITYID"') }} as facilityid,
        {{ stg_id_text('"INTID"') }} as intid,
        {{ null_junk('"SALESFORCEID"') }} as salesforceid,
        {{ null_junk('"STREETNAME"') }} as streetname,
        {{ null_junk('"STREETTO"') }} as streetto,
        {{ null_junk('"STREETFROM"') }} as streetfrom,
        {{ null_junk('"EXPIRATION"') }} as expiration,
        {{ null_junk('"PROJECT"') }} as project,
        {{ stg_int('"PROJECTYEAR"') }} as projectyear,
        {{ null_junk('"CREATIONDATE"') }} as creationdate,
        {{ null_junk('"LASTUPDATE"') }} as lastupdate,
        {{ null_junk('"NOTES"') }} as notes,
        {{ null_junk('"SHAPE_LENGTH"') }} as shape_length,
        INGESTED_AT as _loaded_at,
        'https://data.sanjoseca.gov/dataset/paving-moratorium-streets' as _source_url

    from source

)

select * from renamed
