{{ config(tags=['minimal_staging']) }}

-- GRAIN: NOT YET DETERMINED (profiler returned AMBIGUOUS -- needs manual review)
-- This is a passthrough staging view: snake_case rename only, no dedup.
-- Once grain is resolved, replace with a full staging model via generate_staging_models.py.
-- Generated by scripts/generate_minimal_staging.py

with source as (

    select * from {{ source('ripple_raw', 'FED_VOTEVIEW_ROLLCALLS') }}

),

renamed as (

    select
        CONGRESS as congress,
        CHAMBER as chamber,
        ROLLNUMBER as rollnumber,
        ICPSR as icpsr,
        CAST_CODE as cast_code,
        PROB as prob,
        _INGESTED_AT as _loaded_at,
        'https://voteview.com/static/data/out/votes/HSall_votes.csv' as _source_url

    from source

)

select * from renamed
