{{ config(tags=['spine_generated']) }}

-- GRAIN: one row per place (GEOM is unique)
-- SPINE_ENTITY: place  (natural_key: SHAPE_WKT)
-- Generated by scripts/generate_staging_models.py from SOURCE_REGISTRY -- deterministic,
-- no LLM.
-- CASTS: 5 of 18 columns, from landing_column_profile_2026-09-19.tsv. A column is cast only
-- when every filled value in the sample parsed. try_ casts: a value that does not
-- parse reads NULL. The natural key and join-key columns stay TEXT.
--   objectid_1: ID: whole numbers, over 90% distinct -- stays TEXT, '.0' tail removed
--   spaces: integer
--   maxspaces: integer
--   point_x: float
--   point_y: float
-- spine_entity 'place' has no connect/ resolver yet (see connect/spine_entity.py) -- no SPINE_ENTITY_ID emitted.
-- landing table's ingestion timestamp is named INGESTED_AT (no leading underscore) rather than the usual _INGESTED_AT -- confirmed via INFORMATION_SCHEMA, not assumed.

with source as (

    select * from {{ source('ripple_raw', 'PORTAL_CKA_ANALYZE_BOSTON_97789AB639') }}
    qualify row_number() over (partition by "SHAPE_WKT" order by INGESTED_AT desc) = 1

),

renamed as (

    select
        {{ stg_id_text('"OBJECTID_1"') }} as objectid_1,
        {{ stg_int('"SPACES"') }} as spaces,
        {{ null_junk('"FEE"') }} as fee,
        {{ null_junk('"COMMENTS"') }} as comments,
        {{ null_junk('"PHONE"') }} as phone,
        {{ null_junk('"NAME"') }} as name,
        {{ null_junk('"ADDRESS"') }} as address,
        {{ null_junk('"NEIGHBORHO"') }} as neighborho,
        {{ stg_int('"MAXSPACES"') }} as maxspaces,
        {{ null_junk('"HOURS"') }} as hours,
        {{ null_junk('"GLOBALID"') }} as globalid,
        {{ null_junk('"CREATIONDATE"') }} as creationdate,
        {{ null_junk('"CREATOR"') }} as creator,
        {{ null_junk('"EDITDATE"') }} as editdate,
        {{ null_junk('"EDITOR"') }} as editor,
        {{ null_junk('"SHAPE_WKT"') }} as shape_wkt,
        {{ stg_float('"POINT_X"') }} as point_x,
        {{ stg_float('"POINT_Y"') }} as point_y,
        INGESTED_AT as _loaded_at,
        'https://data.boston.gov/dataset/snow-emergency-parking' as _source_url

    from source

)

select * from renamed
