{{ config(tags=['spine_generated']) }}

-- GRAIN: one row per record (spine_entity not determined -- no registry hint available) (ID unique)
-- SPINE_ENTITY: (not determined)  (natural_key: ID)
-- Generated by scripts/generate_staging_models.py from SOURCE_REGISTRY -- deterministic,
-- no LLM.
-- CASTS: 11 of 15 columns, from landing_column_profile_2026-09-19.tsv. A column is cast only
-- when every filled value in the sample parsed. try_ casts: a value that does not
-- parse reads NULL. The natural key and join-key columns stay TEXT.
--   taxyr: integer
--   cycontributionsgrantsamt: integer
--   cyprogramservicerevenueamt: integer
--   pyinvestmentincomeamt: integer
--   cyinvestmentincomeamt: integer
--   pyotherrevenueamt: integer
--   cyotherrevenueamt: integer
--   pytotalrevenueamt: ID: whole numbers, over 90% distinct -- stays TEXT, '.0' tail removed
--   cytotalrevenueamt: ID: whole numbers, over 90% distinct -- stays TEXT, '.0' tail removed
--   pycontributionsgrantsamt: ID: whole numbers, over 90% distinct -- stays TEXT, '.0' tail removed
--   pyprogramservicerevenueamt: integer
-- spine_entity not determined (grain/natural_key proven, but no registry hint says what this row is ABOUT) -- no SPINE_ENTITY_ID emitted.
-- landing table's ingestion timestamp is named INGESTED_AT (no leading underscore) rather than the usual _INGESTED_AT -- confirmed via INFORMATION_SCHEMA, not assumed.

with source as (

    select * from {{ source('ripple_raw', 'PORTAL_SOC_COLORADO_INFORMA_239FBA8B76') }}
    qualify row_number() over (partition by "ID" order by INGESTED_AT desc) = 1

),

renamed as (

    select
        {{ null_junk('"ID"') }} as id,
        {{ stg_int('"TAXYR"') }} as taxyr,
        {{ null_junk('"BUSINESSNAME1"') }} as businessname1,
        {{ null_junk('"EIN"') }} as ein,
        {{ stg_int('"CYCONTRIBUTIONSGRANTSAMT"') }} as cycontributionsgrantsamt,
        {{ stg_int('"CYPROGRAMSERVICEREVENUEAMT"') }} as cyprogramservicerevenueamt,
        {{ stg_int('"PYINVESTMENTINCOMEAMT"') }} as pyinvestmentincomeamt,
        {{ stg_int('"CYINVESTMENTINCOMEAMT"') }} as cyinvestmentincomeamt,
        {{ stg_int('"PYOTHERREVENUEAMT"') }} as pyotherrevenueamt,
        {{ stg_int('"CYOTHERREVENUEAMT"') }} as cyotherrevenueamt,
        {{ stg_id_text('"PYTOTALREVENUEAMT"') }} as pytotalrevenueamt,
        {{ stg_id_text('"CYTOTALREVENUEAMT"') }} as cytotalrevenueamt,
        {{ stg_id_text('"PYCONTRIBUTIONSGRANTSAMT"') }} as pycontributionsgrantsamt,
        {{ stg_int('"PYPROGRAMSERVICEREVENUEAMT"') }} as pyprogramservicerevenueamt,
        {{ null_junk('"BUSINESSNAME2"') }} as businessname2,
        INGESTED_AT as _loaded_at,
        'https://data.colorado.gov/d/k26c-fz5q' as _source_url

    from source

)

select * from renamed
