{{ config(materialized='view', schema='LANDING_CLEAN', alias='CA_LOBBY_COVER') }}

-- GENERATED by scripts/gen_landing_date_views.py -- do not hand-edit.
-- Regenerate after any change to reports/recon/date_cast_inventory_*.csv or
-- reports/recon/date_derive_rules_*.csv.
--
-- Clean date/time columns for LIBRARY_RAW.LANDING.CA_LOBBY_COVER, from the
-- 2026-09-03 warehouse-wide date/time inventory. Every original column
-- passes through untouched via source.*; the clean columns sit beside them.
-- See macros/landing_date_casts.sql for how each is built, and
-- macros/ripple_time.sql for the separate mart-level canonical-clock standard
-- this does not replace.

select
    source.*,
    {{ landing_parse_date('"RPT_DATE"', 'us', 'TEXT') }} as rpt_date_clean_ts,
    {{ landing_parse_date('"FROM_DATE"', 'us', 'TEXT') }} as from_date_clean_ts,
    {{ landing_parse_date('"THRU_DATE"', 'us', 'TEXT') }} as thru_date_clean_ts,
    {{ landing_parse_date('"CUM_BEG_DT"', 'us', 'TEXT') }} as cum_beg_dt_clean_ts,
    {{ landing_parse_date('"SIG_DATE"', 'us', 'TEXT') }} as sig_date_clean_ts,
    {{ landing_parse_audit_epoch('"INGESTED_AT"') }} as ingested_at_clean_ts
from {{ source('ripple_raw', 'CA_LOBBY_COVER') }} as source
