{{ config(materialized='view', schema='LANDING_CLEAN', alias='FED_USCG_VESSEL_DOCUMENTATION') }}

-- GENERATED by scripts/gen_landing_date_views.py -- do not hand-edit.
-- Regenerate after any change to reports/recon/date_cast_inventory_*.csv or
-- reports/recon/date_derive_rules_*.csv.
--
-- Clean date/time columns for LIBRARY_RAW.LANDING.FED_USCG_VESSEL_DOCUMENTATION, from the
-- 2026-09-03 warehouse-wide date/time inventory. Every original column
-- passes through untouched via source.*; the clean columns sit beside them.
-- See macros/landing_date_casts.sql for how each is built, and
-- macros/ripple_time.sql for the separate mart-level canonical-clock standard
-- this does not replace.

select
    source.*,
    {{ landing_parse_date('"COD_ISSUE_DATE"', 'iso', 'TEXT') }} as cod_issue_date_clean_ts,
    {{ landing_parse_date('"COD_EXPIRE_DATE"', 'iso', 'TEXT') }} as cod_expire_date_clean_ts
from {{ source('ripple_raw', 'FED_USCG_VESSEL_DOCUMENTATION') }} as source
