{{ config(materialized='view', schema='LANDING_CLEAN', alias='PORTAL_SOC_CAMBRIDGE_OPEN_D_8A1152140C') }}

-- GENERATED by scripts/gen_landing_date_views.py -- do not hand-edit.
-- Regenerate after any change to reports/recon/date_cast_inventory_*.csv or
-- reports/recon/date_derive_rules_*.csv.
--
-- Clean date/time columns for LIBRARY_RAW.LANDING.PORTAL_SOC_CAMBRIDGE_OPEN_D_8A1152140C, from the
-- 2026-09-03 warehouse-wide date/time inventory. Every original column
-- passes through untouched via source.*; the clean columns sit beside them.
-- See macros/landing_date_casts.sql for how each is built, and
-- macros/ripple_time.sql for the separate mart-level canonical-clock standard
-- this does not replace.

select
    source.*,
    {{ landing_parse_date('"APPLICANT_SUBMIT_DATE"', 'iso', 'TEXT') }} as applicant_submit_date_clean_ts,
    {{ landing_parse_date('"VARIANCE_HEARING_DEADLINE"', 'iso', 'TEXT') }} as variance_hearing_deadline_clean_ts,
    {{ landing_parse_date('"VARIANCE_DECISION_DEADLINE"', 'iso', 'TEXT') }} as variance_decision_deadline_clean_ts,
    {{ landing_parse_date('"ISSUE_DATE"', 'iso', 'TEXT') }} as issue_date_clean_ts,
    {{ landing_parse_date('"ATTEST_DATE"', 'iso', 'TEXT') }} as attest_date_clean_ts,
    {{ landing_parse_date('"MAIL_NOTICES_OF_HEARING_LETTER"', 'us', 'TEXT') }} as mail_notices_of_hearing_letter_clean_ts,
    {{ landing_parse_date('"PREPARE_AGENDA_REPORT"', 'us', 'TEXT') }} as prepare_agenda_report_clean_ts,
    {{ landing_parse_date('"APPLICATION_STAMPED_BY_CITY_CLERK"', 'us', 'TEXT') }} as application_stamped_by_city_clerk_clean_ts,
    {{ landing_parse_date('"APPLICATION_SIGNED_BY_OWNER"', 'us', 'TEXT') }} as application_signed_by_owner_clean_ts,
    {{ landing_parse_date('"SUMMARIZE_REQUEST"', 'us', 'TEXT') }} as summarize_request_clean_ts,
    {{ landing_parse_date('"DECISION_MAILED_TO_PETITIONER"', 'us', 'TEXT') }} as decision_mailed_to_petitioner_clean_ts,
    {{ landing_parse_date('"DECISION_STAMPED_BY_CITY_CLERK"', 'us', 'TEXT') }} as decision_stamped_by_city_clerk_clean_ts,
    {{ landing_parse_date('"LAW_DEPARTMENT_REVIEW"', 'us', 'TEXT') }} as law_department_review_clean_ts,
    {{ landing_parse_date('"MAIL_NOTICE_TO_ABUTTERS"', 'us', 'TEXT') }} as mail_notice_to_abutters_clean_ts,
    {{ landing_parse_date('"PREPARE_DECISION"', 'us', 'TEXT') }} as prepare_decision_clean_ts,
    {{ landing_parse_date('"TRANSCRIPT_RECEIVED"', 'us', 'TEXT') }} as transcript_received_clean_ts,
    {{ landing_parse_date('"SPECIAL_PERMIT_HEARING_DEADLINE"', 'iso', 'TEXT') }} as special_permit_hearing_deadline_clean_ts,
    {{ landing_parse_date('"SPECIAL_PERMIT_DECISION_DEADLINE"', 'iso', 'TEXT') }} as special_permit_decision_deadline_clean_ts,
    {{ landing_parse_date('"DECISION_RECORDED_AT_REGISTRY"', 'us', 'TEXT') }} as decision_recorded_at_registry_clean_ts,
    {{ landing_parse_date('"WAIVER"', 'us', 'TEXT') }} as waiver_clean_ts,
    {{ landing_parse_date('"EXTENSION_END_DATE"', 'iso', 'TEXT') }} as extension_end_date_clean_ts,
    {{ landing_parse_date('"EXTENSION_START_DATE"', 'iso', 'TEXT') }} as extension_start_date_clean_ts,
    {{ landing_parse_date('"COURT_APPEAL"', 'us', 'TEXT') }} as court_appeal_clean_ts,
    {{ landing_parse_date('"APPEAL_DECISION_DEADLINE"', 'iso', 'TEXT') }} as appeal_decision_deadline_clean_ts,
    {{ landing_parse_date('"APPEAL_HEARING_DEADLINE"', 'iso', 'TEXT') }} as appeal_hearing_deadline_clean_ts,
    {{ landing_parse_date('"INGESTED_AT"', 'iso', 'TEXT') }} as ingested_at_clean_ts
from {{ source('ripple_raw', 'PORTAL_SOC_CAMBRIDGE_OPEN_D_8A1152140C') }} as source
