{{ config(materialized='view', schema='LANDING_CLEAN', alias='PORTAL_CKA_WPRDC_ALLEGHENY_DA448E7083') }}

-- GENERATED by scripts/gen_landing_date_views.py -- do not hand-edit.
-- Regenerate after any change to reports/recon/date_cast_inventory_*.csv or
-- reports/recon/date_derive_rules_*.csv.
--
-- Clean date/time columns for LIBRARY_RAW.LANDING.PORTAL_CKA_WPRDC_ALLEGHENY_DA448E7083, from the
-- 2026-09-03 warehouse-wide date/time inventory. Every original column
-- passes through untouched via source.*; the clean columns sit beside them.
-- See macros/landing_date_casts.sql for how each is built, and
-- macros/ripple_time.sql for the separate mart-level canonical-clock standard
-- this does not replace.

select
    source.*,
    {{ landing_parse_date('"INSPECTION_DATE"', 'iso', 'TEXT') }} as inspection_date_clean_ts,
    {{ landing_parse_date('"INSPECTION_END"', 'iso', 'TEXT') }} as inspection_end_clean_ts,
    {{ landing_parse_date('"ABATED_DATE"', 'iso', 'TEXT') }} as abated_date_clean_ts,
    {{ landing_parse_date('"INGESTED_AT"', 'iso', 'TEXT') }} as ingested_at_clean_ts
from {{ source('ripple_raw', 'PORTAL_CKA_WPRDC_ALLEGHENY_DA448E7083') }} as source
