{{ config(materialized='view', schema='LANDING_CLEAN', alias='FED_FHFA_SUSPENDED_COUNTERPARTY_PROGRAM') }}

-- GENERATED by scripts/gen_landing_date_views.py -- do not hand-edit.
-- Regenerate after any change to reports/recon/date_cast_inventory_*.csv or
-- reports/recon/date_derive_rules_*.csv.
--
-- Clean date/time columns for LIBRARY_RAW.LANDING.FED_FHFA_SUSPENDED_COUNTERPARTY_PROGRAM, from the
-- 2026-09-03 warehouse-wide date/time inventory. Every original column
-- passes through untouched via source.*; the clean columns sit beside them.
-- See macros/landing_date_casts.sql for how each is built, and
-- macros/ripple_time.sql for the separate mart-level canonical-clock standard
-- this does not replace.

select
    source.*,
    {{ landing_parse_date('"EFFECTIVE_DATESORT_ASCENDING"', 'us', 'TEXT') }} as effective_datesort_ascending_clean_ts,
    {{ landing_parse_date('"SUSPENSION_END_DATE"', 'us', 'TEXT') }} as suspension_end_date_clean_ts,
    {{ landing_parse_audit_epoch('"_INGESTED_AT"') }} as ingested_at_clean_ts
from {{ source('ripple_raw', 'FED_FHFA_SUSPENDED_COUNTERPARTY_PROGRAM') }} as source
