{{ config(materialized='view', schema='LANDING_CLEAN', alias='FED_FEMA_NFIP_COMMUNITY_STATUS_BOOK_FULL_R2') }}

-- GENERATED by scripts/gen_landing_date_views.py -- do not hand-edit.
-- Regenerate after any change to reports/recon/date_cast_inventory_*.csv or
-- reports/recon/date_derive_rules_*.csv.
--
-- Clean date/time columns for LIBRARY_RAW.LANDING.FED_FEMA_NFIP_COMMUNITY_STATUS_BOOK_FULL_R2, from the
-- 2026-09-03 warehouse-wide date/time inventory. Every original column
-- passes through untouched via source.*; the clean columns sit beside them.
-- See macros/landing_date_casts.sql for how each is built, and
-- macros/ripple_time.sql for the separate mart-level canonical-clock standard
-- this does not replace.

select
    source.*,
    {{ landing_parse_date('"INITIALFLOODHAZARDBOUNDARYMAP"', 'iso', 'TEXT') }} as initialfloodhazardboundarymap_clean_ts,
    {{ landing_parse_date('"INITIALFLOODINSURANCERATEMAP"', 'iso', 'TEXT') }} as initialfloodinsuranceratemap_clean_ts,
    {{ landing_parse_date('"CURRENTLYEFFECTIVEMAPDATE"', 'us', 'TEXT') }} as currentlyeffectivemapdate_clean_ts,
    {{ landing_parse_date('"REGULAREMERGENCYPROGRAMDATE"', 'us', 'TEXT') }} as regularemergencyprogramdate_clean_ts,
    {{ landing_parse_date('"ORIGINALENTRYDATE"', 'iso', 'TEXT') }} as originalentrydate_clean_ts,
    {{ landing_parse_date('"CLASSRATINGEFFECTIVEDATE"', 'iso', 'TEXT') }} as classratingeffectivedate_clean_ts,
    {{ landing_parse_date('"LASTREFRESH"', 'iso', 'TEXT') }} as lastrefresh_clean_ts
from {{ source('ripple_raw', 'FED_FEMA_NFIP_COMMUNITY_STATUS_BOOK_FULL_R2') }} as source
