{{ config(materialized='view', schema='LANDING_CLEAN', alias='FED_EPA_SDWA_SDWA_PUB_WATER_SYSTEMS') }}

-- GENERATED by scripts/gen_landing_date_views.py -- do not hand-edit.
-- Regenerate after any change to reports/recon/date_cast_inventory_*.csv or
-- reports/recon/date_derive_rules_*.csv.
--
-- Clean date/time columns for LIBRARY_RAW.LANDING.FED_EPA_SDWA_SDWA_PUB_WATER_SYSTEMS, from the
-- 2026-09-03 warehouse-wide date/time inventory. Every original column
-- passes through untouched via source.*; the clean columns sit beside them.
-- See macros/landing_date_casts.sql for how each is built, and
-- macros/ripple_time.sql for the separate mart-level canonical-clock standard
-- this does not replace.

select
    source.*,
    {{ landing_parse_date('"PWS_DEACTIVATION_DATE"', 'us', 'TEXT') }} as pws_deactivation_date_clean_ts,
    {{ landing_parse_date('"FIRST_REPORTED_DATE"', 'us', 'TEXT') }} as first_reported_date_clean_ts,
    {{ landing_parse_date('"LAST_REPORTED_DATE"', 'us', 'TEXT') }} as last_reported_date_clean_ts,
    {{ landing_parse_date('"SOURCE_PROTECTION_BEGIN_DATE"', 'us', 'TEXT') }} as source_protection_begin_date_clean_ts,
    {{ landing_parse_date('"OUTSTANDING_PERFORM_BEGIN_DATE"', 'us', 'TEXT') }} as outstanding_perform_begin_date_clean_ts,
    {{ landing_parse_date('"REDUCED_MONITORING_BEGIN_DATE"', 'us', 'TEXT') }} as reduced_monitoring_begin_date_clean_ts,
    {{ landing_parse_date('"REDUCED_MONITORING_END_DATE"', 'us', 'TEXT') }} as reduced_monitoring_end_date_clean_ts,
    {{ landing_parse_audit_epoch('"_INGESTED_AT"') }} as ingested_at_clean_ts
from {{ source('ripple_raw', 'FED_EPA_SDWA_SDWA_PUB_WATER_SYSTEMS') }} as source
