{{ config(materialized='view', schema='LANDING_CLEAN', alias='FED_USGS_GNIS_ALL_NAMES') }}

-- GENERATED by scripts/gen_landing_date_views.py -- do not hand-edit.
-- Regenerate after any change to reports/recon/date_cast_inventory_*.csv or
-- reports/recon/date_derive_rules_*.csv.
--
-- Clean date/time columns for LIBRARY_RAW.LANDING.FED_USGS_GNIS_ALL_NAMES, from the
-- 2026-09-03 warehouse-wide date/time inventory. Every original column
-- passes through untouched via source.*; the clean columns sit beside them.
-- See macros/landing_date_casts.sql for how each is built, and
-- macros/ripple_time.sql for the separate mart-level canonical-clock standard
-- this does not replace.

select
    source.*,
    {{ landing_parse_date('"PUBLICATIONDATE"', 'us', 'TEXT') }} as publicationdate_clean_ts,
    {{ landing_parse_date('"ENDING_DATE"', 'us', 'TEXT') }} as ending_date_clean_ts,
    {{ landing_parse_date('"DATE_CREATED"', 'us', 'TEXT') }} as date_created_clean_ts,
    {{ landing_parse_audit_epoch('"INGESTED_AT"') }} as ingested_at_clean_ts
from {{ source('ripple_raw', 'FED_USGS_GNIS_ALL_NAMES') }} as source
