{{ config(materialized='view', schema='LANDING_CLEAN', alias='FED_DOL_EBSA_FORM5500_SCHEDULE_SB') }}

-- GENERATED by scripts/gen_landing_date_views.py -- do not hand-edit.
-- Regenerate after any change to reports/recon/date_cast_inventory_*.csv or
-- reports/recon/date_derive_rules_*.csv.
--
-- Clean date/time columns for LIBRARY_RAW.LANDING.FED_DOL_EBSA_FORM5500_SCHEDULE_SB, from the
-- 2026-09-03 warehouse-wide date/time inventory. Every original column
-- passes through untouched via source.*; the clean columns sit beside them.
-- See macros/landing_date_casts.sql for how each is built, and
-- macros/ripple_time.sql for the separate mart-level canonical-clock standard
-- this does not replace.

select
    source.*,
    {{ landing_parse_date('"SB_PLAN_YEAR_BEGIN_DATE"', 'iso', 'TEXT') }} as sb_plan_year_begin_date_clean_ts,
    {{ landing_parse_date('"SB_TAX_PRD"', 'iso', 'TEXT') }} as sb_tax_prd_clean_ts,
    {{ landing_parse_date('"SB_VALUE_DATE"', 'iso', 'TEXT') }} as sb_value_date_clean_ts,
    {{ landing_parse_date('"SB_SIGNATURE_DATE"', 'iso', 'TEXT') }} as sb_signature_date_clean_ts,
    {{ landing_parse_date('"SB_WVR_APPROVED_LTR_DATE"', 'iso', 'TEXT') }} as sb_wvr_approved_ltr_date_clean_ts,
    {{ landing_parse_audit_epoch('"INGESTED_AT"') }} as ingested_at_clean_ts
from {{ source('ripple_raw', 'FED_DOL_EBSA_FORM5500_SCHEDULE_SB') }} as source
