{{ config(materialized='view', schema='LANDING_CLEAN', alias='PORTAL_SOC_TEXAS_OPEN_DATA_354E3ABF4F') }}

-- GENERATED by scripts/gen_landing_date_views.py -- do not hand-edit.
-- Regenerate after any change to reports/recon/date_cast_inventory_*.csv or
-- reports/recon/date_derive_rules_*.csv.
--
-- Clean date/time columns for LIBRARY_RAW.LANDING.PORTAL_SOC_TEXAS_OPEN_DATA_354E3ABF4F, from the
-- 2026-09-03 warehouse-wide date/time inventory. Every original column
-- passes through untouched via source.*; the clean columns sit beside them.
-- See macros/landing_date_casts.sql for how each is built, and
-- macros/ripple_time.sql for the separate mart-level canonical-clock standard
-- this does not replace.

select
    source.*,
    {{ landing_parse_date('"NOR_REGISTRATION_DATE"', 'iso', 'TEXT') }} as nor_registration_date_clean_ts,
    {{ landing_parse_date('"NOR_AMEND_DATE"', 'iso', 'TEXT') }} as nor_amend_date_clean_ts,
    {{ landing_parse_date('"NOR_REG_STATUS_CHG_DATE"', 'iso', 'TEXT') }} as nor_reg_status_chg_date_clean_ts,
    {{ landing_parse_date('"HEALTHCARE_FAC_OPTIN_DATE"', 'us', 'TEXT') }} as healthcare_fac_optin_date_clean_ts,
    {{ landing_parse_date('"INGESTED_AT"', 'iso', 'TEXT') }} as ingested_at_clean_ts
from {{ source('ripple_raw', 'PORTAL_SOC_TEXAS_OPEN_DATA_354E3ABF4F') }} as source
