{{ config(materialized='view', schema='LANDING_CLEAN', alias='FED_ICE_DETAINERS') }}

-- GENERATED by scripts/gen_landing_date_views.py -- do not hand-edit.
-- Regenerate after any change to reports/recon/date_cast_inventory_*.csv or
-- reports/recon/date_derive_rules_*.csv.
--
-- Clean date/time columns for LIBRARY_RAW.LANDING.FED_ICE_DETAINERS, from the
-- 2026-09-03 warehouse-wide date/time inventory. Every original column
-- passes through untouched via source.*; the clean columns sit beside them.
-- See macros/landing_date_casts.sql for how each is built, and
-- macros/ripple_time.sql for the separate mart-level canonical-clock standard
-- this does not replace.

select
    source.*,
    {{ landing_parse_date('"DETAINER_PREPARE_DATE"', 'iso', 'TEXT') }} as detainer_prepare_date_clean_ts,
    {{ landing_parse_date('"DEPARTED_DATE"', 'iso', 'TEXT') }} as departed_date_clean_ts,
    {{ landing_parse_date('"MSC_CHARGE_DATE"', 'iso', 'TEXT') }} as msc_charge_date_clean_ts,
    {{ landing_parse_date('"MSC_CONVICTION_DATE"', 'iso', 'TEXT') }} as msc_conviction_date_clean_ts,
    {{ landing_parse_date('"FINAL_ORDER_DATE"', 'iso', 'TEXT') }} as final_order_date_clean_ts,
    {{ landing_parse_date('"APPREHENSION_DATE"', 'iso', 'TEXT') }} as apprehension_date_clean_ts,
    {{ landing_parse_date('"ENTRY_DATE"', 'iso', 'TEXT') }} as entry_date_clean_ts,
    {{ landing_parse_audit_epoch('"INGESTED_AT"') }} as ingested_at_clean_ts
from {{ source('ripple_raw', 'FED_ICE_DETAINERS') }} as source
