{{ config(tags=['spine_generated']) }}

-- GRAIN: one row per organization (EIN is unique)
-- SPINE_ENTITY: organization  (natural_key: EIN)
-- Generated by scripts/generate_staging_models.py from SOURCE_REGISTRY -- deterministic,
-- no LLM.
-- CASTS: 3 of 11 columns, from landing_column_profile_2026-09-19.tsv. A column is cast only
-- when every filled value in the sample parsed. try_ casts: a value that does not
-- parse reads NULL. The natural key and join-key columns stay TEXT.
--   pn: integer
--   plan_year: integer
--   final_close_date: timestamp
-- landing table's ingestion timestamp is named INGESTED_AT (no leading underscore) rather than the usual _INGESTED_AT -- confirmed via INFORMATION_SCHEMA, not assumed.

with source as (

    select * from {{ source('ripple_raw', 'PORTAL_SOC_UTAH_OPEN_DATA_P_F87FB2BFB7') }}
    qualify row_number() over (partition by "EIN" order by INGESTED_AT desc) = 1

),

renamed as (

    select
        {{ null_junk('"CASE_TYPE"') }} as case_type,
        {{ null_junk('"EIN"') }} as ein,
        {{ stg_int('"PN"') }} as pn,
        {{ stg_int('"PLAN_YEAR"') }} as plan_year,
        {{ null_junk('"PLAN_NAME"') }} as plan_name,
        {{ null_junk('"PLAN_ADMIN"') }} as plan_admin,
        {{ null_junk('"PLAN_ADMIN_STATE"') }} as plan_admin_state,
        {{ null_junk('"PLAN_ADMIN_ZIP_CODE"') }} as plan_admin_zip_code,
        {{ null_junk('"FINAL_CLOSE_REASON"') }} as final_close_reason,
        {{ stg_ts('"FINAL_CLOSE_DATE"') }} as final_close_date,
        {{ null_junk('"PENALTY_AMOUNT"') }} as penalty_amount,
        INGESTED_AT as _loaded_at,
        'https://opendata.utah.gov/d/nzzk-vhxi' as _source_url,
    'ENT_' || LEFT(MD5('EIN' || '|' || (CASE WHEN LENGTH(UPPER(REGEXP_REPLACE(TO_VARCHAR("EIN"), '[^0-9A-Za-z]', ''))) = 0 OR LENGTH(UPPER(REGEXP_REPLACE(TO_VARCHAR("EIN"), '[^0-9A-Za-z]', ''))) > 9 OR NOT REGEXP_LIKE(UPPER(REGEXP_REPLACE(TO_VARCHAR("EIN"), '[^0-9A-Za-z]', '')), '^[0-9]+$') OR LPAD(UPPER(REGEXP_REPLACE(TO_VARCHAR("EIN"), '[^0-9A-Za-z]', '')), 9, '0') = REPEAT('0', 9) OR (LENGTH(UPPER(REGEXP_REPLACE(TO_VARCHAR("EIN"), '[^0-9A-Za-z]', ''))) >= 4 AND UPPER(REGEXP_REPLACE(TO_VARCHAR("EIN"), '[^0-9A-Za-z]', '')) = REPEAT(LEFT(UPPER(REGEXP_REPLACE(TO_VARCHAR("EIN"), '[^0-9A-Za-z]', '')), 1), LENGTH(UPPER(REGEXP_REPLACE(TO_VARCHAR("EIN"), '[^0-9A-Za-z]', ''))))) OR LPAD(UPPER(REGEXP_REPLACE(TO_VARCHAR("EIN"), '[^0-9A-Za-z]', '')), 9, '0') = REPEAT(LEFT(LPAD(UPPER(REGEXP_REPLACE(TO_VARCHAR("EIN"), '[^0-9A-Za-z]', '')), 9, '0'), 1), 9) OR UPPER(REGEXP_REPLACE(TO_VARCHAR("EIN"), '[^0-9A-Za-z]', '')) IN ('123456789', '987654321', '1234567890', '0987654321', '12345678', '87654321', '123456', '654321') OR LPAD(UPPER(REGEXP_REPLACE(TO_VARCHAR("EIN"), '[^0-9A-Za-z]', '')), 9, '0') IN ('123456789', '987654321', '1234567890', '0987654321', '12345678', '87654321', '123456', '654321') THEN NULL ELSE LPAD(UPPER(REGEXP_REPLACE(TO_VARCHAR("EIN"), '[^0-9A-Za-z]', '')), 9, '0') END)), 16) as spine_entity_id  -- joins LIBRARY_META."CONNECT".ENTITY_GOLDEN.ENTITY_ID

    from source

)

select * from renamed
