{{ config(tags=['spine_generated']) }}

-- GRAIN: one row per record (spine_entity not determined -- no registry hint available) (PGM_SYS_ID+ACTIVITY_ID unique)
-- SPINE_ENTITY: (not determined)  (natural_key: PGM_SYS_ID, ACTIVITY_ID)
-- Generated by scripts/generate_staging_models.py from SOURCE_REGISTRY -- deterministic,
-- no LLM. Casts kept as landed (TEXT) -- add explicit type casts by hand once each
-- column's real type is confirmed; this generator has no semantic type knowledge.
-- spine_entity not determined (grain/natural_key proven, but no registry hint says what this row is ABOUT) -- no SPINE_ENTITY_ID emitted.

with source as (

    select * from {{ source('ripple_raw', 'FED_EPA_ICIS_AIR_ICIS_AIR_VIOLATION_HISTORY') }}

),

renamed as (

    select
        "PGM_SYS_ID" as pgm_sys_id,
        "ACTIVITY_ID" as activity_id,
        "AGENCY_TYPE_DESC" as agency_type_desc,
        "STATE_CODE" as state_code,
        "AIR_LCON_CODE" as air_lcon_code,
        "COMP_DETERMINATION_UID" as comp_determination_uid,
        "ENF_RESPONSE_POLICY_CODE" as enf_response_policy_code,
        "PROGRAM_CODES" as program_codes,
        "PROGRAM_DESCS" as program_descs,
        "POLLUTANT_CODES" as pollutant_codes,
        "POLLUTANT_DESCS" as pollutant_descs,
        "EARLIEST_FRV_DETERM_DATE" as earliest_frv_determ_date,
        "HPV_DAYZERO_DATE" as hpv_dayzero_date,
        "HPV_RESOLVED_DATE" as hpv_resolved_date,
        "DSCV_PATHWAY_DATE" as dscv_pathway_date,
        "NFTC_PATHWAY_DATE" as nftc_pathway_date,
        _INGESTED_AT as _loaded_at,
        '' as _source_url

    from source

)

select * from renamed
qualify row_number() over (partition by pgm_sys_id, activity_id order by _loaded_at desc) = 1
