-- EE: shape, key uniqueness, adjustment rows, lifetime-vs-first-year equality, sector sums vs total, and the 15 biggest spenders
with t as (select * from LIBRARY_MARTS.ENERGY.ENERGY__FED_EIA861_ENERGY_EFFICIENCY),
p as (select 'profile' k, count(*)::text a, count(distinct UTILITY_NUMBER)::text b, count(distinct UTILITY_NUMBER||'|'||STATE)::text c,
  count(distinct STATE)::text d, listagg(distinct DATA_YEAR,'|') e, count_if(UTILITY_NUMBER=99999 or UTILITY_NAME ilike '%adjust%')::text f,
  count_if(TOTAL_LIFE_CYCLE_CUSTOMER_INCENTIVES_THOUSAND_DOLLARS=TOTAL_INCREMENTAL_CUSTOMER_INCENTIVES_THOUSAND_DOLLARS)::text||' of '||count(TOTAL_INCREMENTAL_CUSTOMER_INCENTIVES_THOUSAND_DOLLARS)::text g,
  count_if(TOTAL_LIFE_CYCLE_ALL_OTHER_COSTS_THOUSAND_DOLLARS=TOTAL_INCREMENTAL_ALL_OTHER_COSTS_THOUSAND_DOLLARS)::text||' of '||count(TOTAL_INCREMENTAL_ALL_OTHER_COSTS_THOUSAND_DOLLARS)::text h,
  count_if(abs(coalesce(RESIDENTIAL_INCREMENTAL_CUSTOMER_INCENTIVES_THOUSAND_DOLLARS,0)+coalesce(COMMERCIAL_INCREMENTAL_CUSTOMER_INCENTIVES_THOUSAND_DOLLARS,0)+coalesce(INDUSTRIAL_INCREMENTAL_CUSTOMER_INCENTIVES_THOUSAND_DOLLARS,0)+coalesce(TRANSPORTATION_INCREMENTAL_CUSTOMER_INCENTIVES_THOUSAND_DOLLARS,0)-coalesce(TOTAL_INCREMENTAL_CUSTOMER_INCENTIVES_THOUSAND_DOLLARS,0))>1)::text i,
  count_if(coalesce(TOTAL_INCREMENTAL_ENERGY_SAVINGS_MWH,0)=0 and coalesce(TOTAL_INCREMENTAL_CUSTOMER_INCENTIVES_THOUSAND_DOLLARS,0)+coalesce(TOTAL_INCREMENTAL_ALL_OTHER_COSTS_THOUSAND_DOLLARS,0)>0)::text j,
  count_if(coalesce(TOTAL_INCREMENTAL_ENERGY_SAVINGS_MWH,0)>0 and coalesce(TOTAL_INCREMENTAL_CUSTOMER_INCENTIVES_THOUSAND_DOLLARS,0)+coalesce(TOTAL_INCREMENTAL_ALL_OTHER_COSTS_THOUSAND_DOLLARS,0)=0)::text l,
  sum(TOTAL_INCREMENTAL_CUSTOMER_INCENTIVES_THOUSAND_DOLLARS)::text m, sum(TOTAL_INCREMENTAL_ALL_OTHER_COSTS_THOUSAND_DOLLARS)::text n2, sum(TOTAL_INCREMENTAL_ENERGY_SAVINGS_MWH)::text o
 from t),
top as (select 'top' k, UTILITY_NAME a, STATE b, UTILITY_NUMBER::text c, RESIDENTIAL_INCREMENTAL_CUSTOMER_INCENTIVES_THOUSAND_DOLLARS::text d, TOTAL_INCREMENTAL_CUSTOMER_INCENTIVES_THOUSAND_DOLLARS::text e,
  TOTAL_INCREMENTAL_ALL_OTHER_COSTS_THOUSAND_DOLLARS::text f, RESIDENTIAL_INCREMENTAL_ENERGY_SAVINGS_MWH::text g, TOTAL_INCREMENTAL_ENERGY_SAVINGS_MWH::text h, TOTAL_LIFE_CYCLE_ENERGY_SAVINGS_MWH::text i,
  RESIDENTIAL_LIFE_CYCLE_CUSTOMER_INCENTIVES_THOUSAND_DOLLARS::text j, RESIDENTIAL_WEIGHTED_AVERAGE_LIFE_YEARS::text l, WEBSITE m, TOTAL_INCREMENTAL_PEAK_DEMAND_SAVINGS_MW::text n2, BA_CODE o
 from t order by coalesce(TOTAL_INCREMENTAL_CUSTOMER_INCENTIVES_THOUSAND_DOLLARS,0)+coalesce(TOTAL_INCREMENTAL_ALL_OTHER_COSTS_THOUSAND_DOLLARS,0) desc limit 15)
select * from p union all select * from top
