{{ config(tags=['spine_generated']) }}

-- GRAIN: one row per record (spine_entity not determined -- no registry hint available) (ID is unique)
-- SPINE_ENTITY: (not determined)  (natural_key: ID)
-- Generated by scripts/generate_staging_models.py from SOURCE_REGISTRY -- deterministic,
-- no LLM.
-- CASTS: 11 of 23 columns, from landing_column_profile_2026-09-19.tsv. A column is cast only
-- when every filled value in the sample parsed. try_ casts: a value that does not
-- parse reads NULL. The natural key and join-key columns stay TEXT.
--   date: timestamp
--   value: float
--   custom_number_1: integer
--   custom_number_2: integer
--   custom_number_3: integer
--   custom_date_1: timestamp
--   custom_date_2: timestamp
--   custom_date_3: timestamp
--   last_update: timestamp
--   last_update_cot: timestamp
--   last_update_ogi: timestamp
-- spine_entity not determined (grain/natural_key proven, but no registry hint says what this row is ABOUT) -- no SPINE_ENTITY_ID emitted.
-- landing table's ingestion timestamp is named INGESTED_AT (no leading underscore) rather than the usual _INGESTED_AT -- confirmed via INFORMATION_SCHEMA, not assumed.

with source as (

    select * from {{ source('ripple_raw', 'PORTAL_CKA_TAMPA_OPEN_DATA_7B31B708C9') }}
    qualify row_number() over (partition by "ID" order by INGESTED_AT desc) = 1

),

renamed as (

    select
        {{ null_junk('"ID"') }} as id,
        {{ null_junk('"ORGANZIATION"') }} as organziation,
        {{ null_junk('"CHARTNAME"') }} as chartname,
        {{ null_junk('"DESCRIPTION"') }} as description,
        {{ null_junk('"CATEGORY"') }} as category,
        {{ null_junk('"SUMMARY"') }} as summary,
        {{ null_junk('"PERIOD"') }} as period,
        {{ stg_ts('"DATE"') }} as date,
        {{ null_junk('"DATA_TYPE"') }} as data_type,
        {{ stg_float('"VALUE"') }} as value,
        {{ null_junk('"AUTOMATION"') }} as automation,
        {{ null_junk('"CUSTOM_TEXT_1"') }} as custom_text_1,
        {{ null_junk('"CUSTOM_TEXT_2"') }} as custom_text_2,
        {{ null_junk('"CUSTOM_TEXT_3"') }} as custom_text_3,
        {{ stg_int('"CUSTOM_NUMBER_1"') }} as custom_number_1,
        {{ stg_int('"CUSTOM_NUMBER_2"') }} as custom_number_2,
        {{ stg_int('"CUSTOM_NUMBER_3"') }} as custom_number_3,
        {{ stg_ts('"CUSTOM_DATE_1"') }} as custom_date_1,
        {{ stg_ts('"CUSTOM_DATE_2"') }} as custom_date_2,
        {{ stg_ts('"CUSTOM_DATE_3"') }} as custom_date_3,
        {{ stg_ts('"LAST_UPDATE"') }} as last_update,
        {{ stg_ts('"LAST_UPDATE_COT"') }} as last_update_cot,
        {{ stg_ts('"LAST_UPDATE_OGI"') }} as last_update_ogi,
        INGESTED_AT as _loaded_at,
        'https://opendata.tampa.gov/dataset/housing-and-community-development-dataset' as _source_url

    from source

)

select * from renamed
