{{ config(tags=['spine_generated']) }}

-- GRAIN: one row per asset (PATENT is unique)
-- SPINE_ENTITY: asset  (natural_key: PATENT_NUMBER)
-- Generated by scripts/generate_staging_models.py from SOURCE_REGISTRY -- deterministic,
-- no LLM. Casts kept as landed (TEXT) -- add explicit type casts by hand once each
-- column's real type is confirmed; this generator has no semantic type knowledge.
-- spine_entity 'asset' has no connect/ resolver yet (see connect/spine_entity.py) -- no SPINE_ENTITY_ID emitted.
-- landing table's ingestion timestamp is named INGESTED_AT (no leading underscore) rather than the usual _INGESTED_AT -- confirmed via INFORMATION_SCHEMA, not assumed.

with source as (

    select * from {{ source('ripple_raw', 'PORTAL_SOC_NEW_YORK_STATE_O_49CD8C5B65') }}

),

renamed as (

    select
        "PATENT_NUMBER" as patent_number,
        "STATUS" as status,
        "ISSUE_DATE" as issue_date,
        "COUNTRY" as country,
        "PATENT_TITLE" as patent_title,
        "PATENT_ASSIGNEE_OWNER" as patent_assignee_owner,
        INGESTED_AT as _loaded_at,
        'https://data.ny.gov/d/jhdq-vgnr' as _source_url

    from source

)

select * from renamed
qualify row_number() over (partition by patent_number order by _loaded_at desc) = 1
