{{ config(tags=['spine_generated']) }}

-- GRAIN: one row per place (GEOM is unique)
-- SPINE_ENTITY: place  (natural_key: DATASPATIAL_WKB)
-- Generated by scripts/generate_staging_models.py from SOURCE_REGISTRY -- deterministic,
-- no LLM. Casts kept as landed (TEXT) -- add explicit type casts by hand once each
-- column's real type is confirmed; this generator has no semantic type knowledge.
-- spine_entity 'place' has no connect/ resolver yet (see connect/spine_entity.py) -- no SPINE_ENTITY_ID emitted.
-- landing table's ingestion timestamp is named INGESTED_AT (no leading underscore) rather than the usual _INGESTED_AT -- confirmed via INFORMATION_SCHEMA, not assumed.

with source as (

    select * from {{ source('ripple_raw', 'PORTAL_CKA_WESTERN_PENNSYLV_E91E8047AA') }}

),

renamed as (

    select
        "SHAPE_LENG" as shape_leng,
        "OBJECTID" as objectid,
        "TYPE" as type,
        "STATUS" as status,
        "SHAPE_AREA" as shape_area,
        "DATASPATIAL_WKB" as dataspatial_wkb,
        INGESTED_AT as _loaded_at,
        'https://data.wprdc.org/dataset/allegheny-county-greenways' as _source_url

    from source

)

select * from renamed
qualify row_number() over (partition by dataspatial_wkb order by _loaded_at desc) = 1
