{{ config(tags=['spine_generated']) }}

-- GRAIN: one row per place (GEOM is unique)
-- SPINE_ENTITY: place  (natural_key: SHAPE_LENGTH)
-- Generated by scripts/generate_staging_models.py from SOURCE_REGISTRY -- deterministic,
-- no LLM. Casts kept as landed (TEXT) -- add explicit type casts by hand once each
-- column's real type is confirmed; this generator has no semantic type knowledge.
-- spine_entity 'place' has no connect/ resolver yet (see connect/spine_entity.py) -- no SPINE_ENTITY_ID emitted.
-- landing table's ingestion timestamp is named INGESTED_AT (no leading underscore) rather than the usual _INGESTED_AT -- confirmed via INFORMATION_SCHEMA, not assumed.

with source as (

    select * from {{ source('ripple_raw', 'PORTAL_CKA_SAN_JOSE_OPEN_DA_D8576CBEB1') }}

),

renamed as (

    select
        "ZONEID" as zoneid,
        "ZONENAME" as zonename,
        "ZONETYPE" as zonetype,
        "STATUS" as status,
        "STICKERLIMIT" as stickerlimit,
        "HANGERLIMIT" as hangerlimit,
        "EXPIRATIONDATE" as expirationdate,
        "STREETNAME" as streetname,
        "SHAPE_LENGTH" as shape_length,
        "OBJECTID" as objectid,
        "FACILITYID" as facilityid,
        "INTID" as intid,
        "RESIDENTIALID" as residentialid,
        "ZONEAPPLICATION" as zoneapplication,
        "ALTERNATEZONEID" as alternatezoneid,
        "CREATIONDATE" as creationdate,
        "LASTUPDATE" as lastupdate,
        "NOTES" as notes,
        INGESTED_AT as _loaded_at,
        'https://data.sanjoseca.gov/dataset/residential-parking-permit-rpp-zones' as _source_url

    from source

)

select * from renamed
qualify row_number() over (partition by shape_length order by _loaded_at desc) = 1
