{{ config(tags=['minimal_staging']) }}

-- GRAIN: NOT YET DETERMINED (profiler returned AMBIGUOUS -- needs manual review)
-- This is a passthrough staging view: snake_case rename only, no dedup.
-- Once grain is resolved, replace with a full staging model via generate_staging_models.py.
-- Generated by scripts/generate_minimal_staging.py

with source as (

    select * from {{ source('ripple_raw', 'FED_HUD_DATA') }}

),

renamed as (

    select
        DATASET_NAME as dataset_name,
        DATASET_URL as dataset_url,
        DESCRIPTION as description,
        FIPS as fips,
        ZIP as zip,
        EIN as ein,
        YEAR as year,
        VALUE as value,
        _INGESTED_AT as _loaded_at,
        'https://www.huduser.gov/portal/datasets/pdrdatas.html' as _source_url

    from source

)

select * from renamed
