{{ config(tags=['spine_generated']) }}

-- GRAIN: one row per record (spine_entity not determined -- no registry hint available) (ZIP+NOR_REGISTRATION_DATE unique)
-- SPINE_ENTITY: (not determined)  (natural_key: SITE_ZIP_CD, NOR_REGISTRATION_DATE)
-- Generated by scripts/generate_staging_models.py from SOURCE_REGISTRY -- deterministic,
-- no LLM. Casts kept as landed (TEXT) -- add explicit type casts by hand once each
-- column's real type is confirmed; this generator has no semantic type knowledge.
-- spine_entity not determined (grain/natural_key proven, but no registry hint says what this row is ABOUT) -- no SPINE_ENTITY_ID emitted.
-- landing table's ingestion timestamp is named INGESTED_AT (no leading underscore) rather than the usual _INGESTED_AT -- confirmed via INFORMATION_SCHEMA, not assumed.

with source as (

    select * from {{ source('ripple_raw', 'PORTAL_SOC_TEXAS_OPEN_DATA_354E3ABF4F') }}

),

renamed as (

    select
        "SWR_NUM_TXT" as swr_num_txt,
        "RN_NUM_TXT" as rn_num_txt,
        "EPA_ID_NUM" as epa_id_num,
        "FACILITY_SITE_NAME" as facility_site_name,
        "FACILITY_STATUS" as facility_status,
        "PHYS_LOC_DESC_TXT" as phys_loc_desc_txt,
        "SITE_DELIV_TXT" as site_deliv_txt,
        "SITE_CITY_NAME" as site_city_name,
        "SITE_COUNTY_NAME" as site_county_name,
        "SITE_USPS_STATE_CD" as site_usps_state_cd,
        "SITE_ZIP_CD" as site_zip_cd,
        "SITE_COUNTRY_NAME" as site_country_name,
        "TCEQ_REGION_NUM" as tceq_region_num,
        "LAT_DEC_COORD_NUM" as lat_dec_coord_num,
        "LONG_DEC_COORD_NUM" as long_dec_coord_num,
        "PRIMARY_NAICS_CODE" as primary_naics_code,
        "LAND_TYP_CD" as land_typ_cd,
        "NOR_REGISTRATION_DATE" as nor_registration_date,
        "NOR_AMEND_DATE" as nor_amend_date,
        "NOR_REG_STATUS_CHG_DATE" as nor_reg_status_chg_date,
        "STEERS_FLG" as steers_flg,
        "SITE_CLASS_GENERATOR" as site_class_generator,
        "SITE_CLASS_REV_DIST" as site_class_rev_dist,
        "AWS_REQD_FLG" as aws_reqd_flg,
        "SITE_CLASS_RECEIVER" as site_class_receiver,
        "MWRS_REQD_FLG" as mwrs_reqd_flg,
        "SITE_CLASS_TRANSPORTER" as site_class_transporter,
        "TRANSPORT_FOR_HIRE" as transport_for_hire,
        "TRANSPORT_OWNED_WASTE" as transport_owned_waste,
        "TRANSPORT_IND_CLASS1" as transport_ind_class1,
        "TRANSPORT_HW" as transport_hw,
        "SITE_CLASS_TRANSFER" as site_class_transfer,
        "REG_HEALTHCARE_PROV" as reg_healthcare_prov,
        "SITE_CLASS_RECYCLER" as site_class_recycler,
        "HW_GENERATOR_CLASS" as hw_generator_class,
        "GENR_TYP_CD" as genr_typ_cd,
        "RCVR_FAC_CAT_CD" as rcvr_fac_cat_cd,
        "RCRA_PERMIT_NUM" as rcra_permit_num,
        "HW_PERMIT_STATUS" as hw_permit_status,
        "IW_PMT_NUM_TXT" as iw_pmt_num_txt,
        "HEALTHCARE_FAC_OPTIN_DATE" as healthcare_fac_optin_date,
        "MW_PMT_NUM_TXT" as mw_pmt_num_txt,
        "REV_DIST_BEGIN_DATE" as rev_dist_begin_date,
        "REV_DIST_END_DATE" as rev_dist_end_date,
        "HEALTHCARE_FAC_WITHDRAW_DATE" as healthcare_fac_withdraw_date,
        INGESTED_AT as _loaded_at,
        'https://data.texas.gov/d/v287-9kbw' as _source_url

    from source

)

select * from renamed
qualify row_number() over (partition by site_zip_cd, nor_registration_date order by _loaded_at desc) = 1
