{{ config(tags=['spine_generated']) }}

-- GRAIN: one row per organization (UEI+ACTION_DATE+PERIOD_OF_PERFORMANCE_START_DATE+PERIOD_OF_PERFORMANCE_CURRENT_END_DATE+AWARD_ID_PIID unique)
-- SPINE_ENTITY: organization  (natural_key: RECIPIENT_UEI, ACTION_DATE, PERIOD_OF_PERFORMANCE_START_DATE, PERIOD_OF_PERFORMANCE_CURRENT_END_DATE, AWARD_ID_PIID)
-- Generated by scripts/generate_staging_models.py from SOURCE_REGISTRY -- deterministic,
-- no LLM.
-- CASTS: 6 of 36 columns, from landing_column_profile_2026-09-19.tsv. A column is cast only
-- when every filled value in the sample parsed. try_ casts: a value that does not
-- parse reads NULL. The natural key and join-key columns stay TEXT.
--   federal_action_obligation: float
--   total_dollars_obligated: float
--   current_total_value_of_award: float
--   highly_compensated_officer_1_amount: integer
--   highly_compensated_officer_2_amount: integer
--   last_modified_date: timestamp
-- spine_entity 'organization' has no connect/ resolver yet (see connect/spine_entity.py) -- no SPINE_ENTITY_ID emitted.
-- DEDUPE: registry natural_key (RECIPIENT_UEI, ACTION_DATE, PERIOD_OF_PERFORMANCE_START_DATE, PERIOD_OF_PERFORMANCE_CURRENT_END_DATE, AWARD_ID_PIID) is NOT unique within a load as landed at generation time -- it would collapse 26,500 of 6,325,622 rows. Deduping on the WHOLE ROW instead (exact copies only). A record that changes between loads shows once per version. Find the real key, fix SOURCE_REGISTRY, regenerate.

with source as (

    select * from {{ source('ripple_raw', 'FED_USASPENDING_CONTRACTS') }}
    qualify row_number() over (partition by "CONTRACT_AWARD_UNIQUE_KEY", "AWARD_ID_PIID", "ACTION_DATE", "PERIOD_OF_PERFORMANCE_START_DATE", "PERIOD_OF_PERFORMANCE_CURRENT_END_DATE", "FEDERAL_ACTION_OBLIGATION", "TOTAL_DOLLARS_OBLIGATED", "CURRENT_TOTAL_VALUE_OF_AWARD", "AWARDING_AGENCY_NAME", "AWARDING_SUB_AGENCY_NAME", "FUNDING_AGENCY_NAME", "RECIPIENT_UEI", "RECIPIENT_DUNS", "CAGE_CODE", "RECIPIENT_NAME", "RECIPIENT_DOING_BUSINESS_AS_NAME", "RECIPIENT_PARENT_UEI", "RECIPIENT_PARENT_NAME", "RECIPIENT_CITY_NAME", "RECIPIENT_STATE_CODE", "RECIPIENT_ZIP_4_CODE", "RECIPIENT_COUNTRY_NAME", "PRIMARY_PLACE_OF_PERFORMANCE_STATE_CODE", "PRIMARY_PLACE_OF_PERFORMANCE_CITY_NAME", "AWARD_TYPE", "NAICS_CODE", "NAICS_DESCRIPTION", "PRODUCT_OR_SERVICE_CODE_DESCRIPTION", "TRANSACTION_DESCRIPTION", "HIGHLY_COMPENSATED_OFFICER_1_NAME", "HIGHLY_COMPENSATED_OFFICER_1_AMOUNT", "HIGHLY_COMPENSATED_OFFICER_2_NAME", "HIGHLY_COMPENSATED_OFFICER_2_AMOUNT", "FOREIGN_OWNED", "USASPENDING_PERMALINK", "LAST_MODIFIED_DATE" order by _INGESTED_AT desc) = 1

),

renamed as (

    select
        {{ null_junk('"CONTRACT_AWARD_UNIQUE_KEY"') }} as contract_award_unique_key,
        {{ null_junk('"AWARD_ID_PIID"') }} as award_id_piid,
        {{ null_junk('"ACTION_DATE"') }} as action_date,
        {{ null_junk('"PERIOD_OF_PERFORMANCE_START_DATE"') }} as period_of_performance_start_date,
        {{ null_junk('"PERIOD_OF_PERFORMANCE_CURRENT_END_DATE"') }} as period_of_performance_current_end_date,
        {{ stg_float('"FEDERAL_ACTION_OBLIGATION"') }} as federal_action_obligation,
        {{ stg_float('"TOTAL_DOLLARS_OBLIGATED"') }} as total_dollars_obligated,
        {{ stg_float('"CURRENT_TOTAL_VALUE_OF_AWARD"') }} as current_total_value_of_award,
        {{ null_junk('"AWARDING_AGENCY_NAME"') }} as awarding_agency_name,
        {{ null_junk('"AWARDING_SUB_AGENCY_NAME"') }} as awarding_sub_agency_name,
        {{ null_junk('"FUNDING_AGENCY_NAME"') }} as funding_agency_name,
        {{ null_junk('"RECIPIENT_UEI"') }} as recipient_uei,
        {{ null_junk('"RECIPIENT_DUNS"') }} as recipient_duns,
        {{ null_junk('"CAGE_CODE"') }} as cage_code,
        {{ null_junk('"RECIPIENT_NAME"') }} as recipient_name,
        {{ null_junk('"RECIPIENT_DOING_BUSINESS_AS_NAME"') }} as recipient_doing_business_as_name,
        {{ null_junk('"RECIPIENT_PARENT_UEI"') }} as recipient_parent_uei,
        {{ null_junk('"RECIPIENT_PARENT_NAME"') }} as recipient_parent_name,
        {{ null_junk('"RECIPIENT_CITY_NAME"') }} as recipient_city_name,
        {{ null_junk('"RECIPIENT_STATE_CODE"') }} as recipient_state_code,
        {{ null_junk('"RECIPIENT_ZIP_4_CODE"') }} as recipient_zip_4_code,
        {{ null_junk('"RECIPIENT_COUNTRY_NAME"') }} as recipient_country_name,
        {{ null_junk('"PRIMARY_PLACE_OF_PERFORMANCE_STATE_CODE"') }} as primary_place_of_performance_state_code,
        {{ null_junk('"PRIMARY_PLACE_OF_PERFORMANCE_CITY_NAME"') }} as primary_place_of_performance_city_name,
        {{ null_junk('"AWARD_TYPE"') }} as award_type,
        {{ null_junk('"NAICS_CODE"') }} as naics_code,
        {{ null_junk('"NAICS_DESCRIPTION"') }} as naics_description,
        {{ null_junk('"PRODUCT_OR_SERVICE_CODE_DESCRIPTION"') }} as product_or_service_code_description,
        {{ null_junk('"TRANSACTION_DESCRIPTION"') }} as transaction_description,
        {{ null_junk('"HIGHLY_COMPENSATED_OFFICER_1_NAME"') }} as highly_compensated_officer_1_name,
        {{ stg_int('"HIGHLY_COMPENSATED_OFFICER_1_AMOUNT"') }} as highly_compensated_officer_1_amount,
        {{ null_junk('"HIGHLY_COMPENSATED_OFFICER_2_NAME"') }} as highly_compensated_officer_2_name,
        {{ stg_int('"HIGHLY_COMPENSATED_OFFICER_2_AMOUNT"') }} as highly_compensated_officer_2_amount,
        {{ null_junk('"FOREIGN_OWNED"') }} as foreign_owned,
        {{ null_junk('"USASPENDING_PERMALINK"') }} as usaspending_permalink,
        {{ stg_ts('"LAST_MODIFIED_DATE"') }} as last_modified_date,
        _INGESTED_AT as _loaded_at,
        'https://www.usaspending.gov/download_center/award_data_archive' as _source_url

    from source

)

select * from renamed
