-- EDGAR insiders: does it overlap the other SEC insider tables (dupe/coverage check), and do its CIKs look padded
WITH e AS (SELECT ACCESSION_NUMBER a, DOCUMENT_TYPE dt FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_EDGAR_INSIDERS)
SELECT
  (SELECT COUNT(*) FROM e) e_rows,
  (SELECT COUNT(*) FROM e WHERE a IN (SELECT ACCESSION_NUMBER FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_INSIDER_SUBMISSION)) in_submission,
  (SELECT COUNT(*) FROM e WHERE a IN (SELECT ACCESSION_NUMBER FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_INSIDER_REPORTINGOWNER)) in_owner,
  (SELECT COUNT(*) FROM e WHERE a IN (SELECT ACCESSION_NUMBER FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_INSIDER_NONDERIV_TRANS)) in_nonderiv,
  (SELECT COUNT(*) FROM e WHERE a IN (SELECT ACCESSION_NUMBER FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_INSIDER_DERIV_TRANS)) in_deriv,
  (SELECT MAX(FILING_DATE) FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_INSIDER_SUBMISSION) sub_max_filed,
  (SELECT COUNT(*) FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_INSIDER_SUBMISSION WHERE FILING_DATE >= '2026-01-01') sub_2026_rows
