-- Universe of annual-report filers (10-K domestic, 20-F / 40-F foreign private issuers) from DERA SUB 2025Q1-2026Q1, with exchange tickers attached
WITH f AS (
  SELECT CIK, NAME, COUNTRYBA, COUNTRYINC, FORM, FILED FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_DERA_SUB_2025Q1 WHERE FORM IN ('10-K','20-F','40-F')
  UNION ALL SELECT CIK, NAME, COUNTRYBA, COUNTRYINC, FORM, FILED FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_DERA_SUB_2025Q2 WHERE FORM IN ('10-K','20-F','40-F')
  UNION ALL SELECT CIK, NAME, COUNTRYBA, COUNTRYINC, FORM, FILED FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_DERA_SUB_2025Q3 WHERE FORM IN ('10-K','20-F','40-F')
  UNION ALL SELECT CIK, NAME, COUNTRYBA, COUNTRYINC, FORM, FILED FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_DERA_SUB_2025Q4 WHERE FORM IN ('10-K','20-F','40-F')
  UNION ALL SELECT CIK, NAME, COUNTRYBA, COUNTRYINC, FORM, FILED FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_DERA_SUB_2026Q1 WHERE FORM IN ('10-K','20-F','40-F')
), g AS (
  SELECT TRY_TO_NUMBER(CIK) cikn, MAX(NAME) name, MAX(COUNTRYBA) countryba, MAX(COUNTRYINC) countryinc,
         LISTAGG(DISTINCT FORM, ',') forms, MAX(FILED) last_filed, COUNT(*) n_filings
  FROM f GROUP BY 1
), t AS (
  SELECT CIK, LISTAGG(DISTINCT TICKER, ',') tickers, LISTAGG(DISTINCT EXCHANGE, ',') exchanges
  FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_EDGAR_COMPANY_TICKERS_EXCHANGE GROUP BY 1
)
SELECT g.*, t.tickers, t.exchanges FROM g LEFT JOIN t ON t.CIK = g.cikn
