-- Size proxy for the peer test: SEC filer status (AFS: 1-LAF large accelerated ... 5-SML) per 20-F/40-F filer, latest filing wins; plus when the ticker list was loaded
WITH f AS (
  SELECT CIK, AFS, FORM, FILED FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_DERA_SUB_2025Q1 WHERE FORM IN ('20-F','40-F')
  UNION ALL SELECT CIK, AFS, FORM, FILED FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_DERA_SUB_2025Q2 WHERE FORM IN ('20-F','40-F')
  UNION ALL SELECT CIK, AFS, FORM, FILED FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_DERA_SUB_2025Q3 WHERE FORM IN ('20-F','40-F')
  UNION ALL SELECT CIK, AFS, FORM, FILED FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_DERA_SUB_2025Q4 WHERE FORM IN ('20-F','40-F')
  UNION ALL SELECT CIK, AFS, FORM, FILED FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_DERA_SUB_2026Q1 WHERE FORM IN ('20-F','40-F')
)
SELECT TRY_TO_NUMBER(CIK) cikn, MAX_BY(AFS, FILED) afs,
       (SELECT TO_TIMESTAMP(MAX(_LOADED_AT)::NUMBER, 6) FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_EDGAR_COMPANY_TICKERS_EXCHANGE) tickers_loaded
FROM f GROUP BY 1
