{{ config(materialized='view', schema='TIMELINE', alias='LABOR__FED_DOL_EBSA_FORM5500_SCHEDULE_SB') }}

-- GENERATED by scripts/census/gen_time_views.py -- do not hand-edit.
-- Regenerate after any change to reports/time_index/clock_index.csv.
--
-- Canonical clock for LABOR.LABOR__FED_DOL_EBSA_FORM5500_SCHEDULE_SB.
--   column : SB_SIGNATURE_DATE   (DATE)
--   means  : reported -- try_to_date(trim(SB_SIGNATURE_DATE),'YYYY-MM-DD'): the date the enrolled actuary signed and certified the schedule to DOL/IRS, always at or after the plan year 
--   grain  : day
--
-- The original columns pass through untouched; the canonical four sit in front
-- of them. Rule 8 of the datetime standard: the raw column is never overwritten,
-- so a mis-parse is always recoverable.

select
    {{ ripple_event_ts(ripple_window('src."SB_SIGNATURE_DATE"::timestamp_ntz')) }} as ripple_ts,
    {{ ripple_grain('day') }} as ripple_grain,
    {{ ripple_clock('reported') }} as ripple_clock,
    'LABOR.LABOR__FED_DOL_EBSA_FORM5500_SCHEDULE_SB'::varchar as ripple_source,
    src.*
from {{ ref('labor__fed_dol_ebsa_form5500_schedule_sb') }} as src
