-- CFTC: the impossible rows. Top-4/top-8 trader share of open interest over 100 percent, and net above gross.
select MARKET_AND_EXCHANGE_NAMES, AS_OF_DATE_IN_FORM_YYYY_MM_DD d, OPEN_INTEREST_ALL oi, TRADERS_TOTAL_ALL traders,
  CONCENTRATION_GROSS_LT_4_TDR_LONG_ALL g4l, CONCENTRATION_GROSS_LT_4_TDR_SHORT_ALL g4s,
  CONCENTRATION_GROSS_LT_8_TDR_LONG_ALL g8l, CONCENTRATION_GROSS_LT_8_TDR_SHORT_ALL g8s,
  CONCENTRATION_NET_LT_4_TDR_LONG_ALL n4l, CONCENTRATION_NET_LT_4_TDR_SHORT_ALL n4s,
  OF_OI_TOTAL_REPORTABLE_LONG_ALL pct_rept_long, OF_OI_TOTAL_REPORTABLE_SHORT_ALL pct_rept_short
from LIBRARY_MARTS.EDUCATION.EDUCATION__FED_CFTC_COT_FUTURES
where greatest(CONCENTRATION_GROSS_LT_4_TDR_SHORT_ALL, CONCENTRATION_GROSS_LT_4_TDR_LONG_ALL, CONCENTRATION_GROSS_LT_8_TDR_SHORT_ALL, CONCENTRATION_GROSS_LT_8_TDR_LONG_ALL,
               CONCENTRATION_NET_LT_8_TDR_SHORT_ALL, CONCENTRATION_NET_LT_8_TDR_LONG_ALL) > 100
   or CONCENTRATION_GROSS_LT_4_TDR_SHORT_ALL < CONCENTRATION_NET_LT_4_TDR_SHORT_ALL
order by d
