{{ config(tags=['spine_generated']) }}

-- GRAIN: one row per record (spine_entity not determined -- no registry hint available) (ANIMAL_LAB_ID is unique)
-- SPINE_ENTITY: (not determined)  (natural_key: ANIMAL_LAB_ID)
-- Generated by scripts/generate_staging_models.py from SOURCE_REGISTRY -- deterministic,
-- no LLM.
-- CASTS: 6 of 21 columns, from landing_column_profile_2026-09-19.tsv. A column is cast only
-- when every filled value in the sample parsed. try_ casts: a value that does not
-- parse reads NULL. The natural key and join-key columns stay TEXT.
--   objectid: ID: whole numbers, over 90% distinct -- stays TEXT, '.0' tail removed
--   event: integer
--   date: date
--   year: integer
--   x: float
--   y: float
-- spine_entity not determined (grain/natural_key proven, but no registry hint says what this row is ABOUT) -- no SPINE_ENTITY_ID emitted.
-- landing table's ingestion timestamp is named INGESTED_AT (no leading underscore) rather than the usual _INGESTED_AT -- confirmed via INFORMATION_SCHEMA, not assumed.
-- DEDUPE: registry natural_key (ANIMAL_LAB_ID) is NOT unique within a load as landed at generation time -- it would collapse 12 of 864 rows. Deduping on the WHOLE ROW instead (exact copies only). A record that changes between loads shows once per version. Find the real key, fix SOURCE_REGISTRY, regenerate.

with source as (

    select * from {{ source('ripple_raw', 'PORTAL_CKA_ISRAEL_NATIONAL_EE52E94997') }}
    qualify row_number() over (partition by "OBJECTID", "ANIMAL_LAB_ID", "EVENT", "DATE", "LINKTOTEST", "OPENLINK", "LINKTOMRE", "LINKMOREOPEN", "YEAR", "SPECIESNAMEENG", "REGIONENG", "REGIONHEB", "SPECIESNAMEHEB", "SPECIES", "SETTLEMENTHEB", "SETTLEMENTENG", "LOCATIONNOTSETTLEMENTENG", "LOCATIONNOTSETTLEMENTHEB", "GLOBALID", "X", "Y" order by INGESTED_AT desc) = 1

),

renamed as (

    select
        {{ stg_id_text('"OBJECTID"') }} as objectid,
        {{ null_junk('"ANIMAL_LAB_ID"') }} as animal_lab_id,
        {{ stg_int('"EVENT"') }} as event,
        {{ stg_date('"DATE"') }} as date,
        {{ null_junk('"LINKTOTEST"') }} as linktotest,
        {{ null_junk('"OPENLINK"') }} as openlink,
        {{ null_junk('"LINKTOMRE"') }} as linktomre,
        {{ null_junk('"LINKMOREOPEN"') }} as linkmoreopen,
        {{ stg_int('"YEAR"') }} as year,
        {{ null_junk('"SPECIESNAMEENG"') }} as speciesnameeng,
        {{ null_junk('"REGIONENG"') }} as regioneng,
        {{ null_junk('"REGIONHEB"') }} as regionheb,
        {{ null_junk('"SPECIESNAMEHEB"') }} as speciesnameheb,
        {{ null_junk('"SPECIES"') }} as species,
        {{ null_junk('"SETTLEMENTHEB"') }} as settlementheb,
        {{ null_junk('"SETTLEMENTENG"') }} as settlementeng,
        {{ null_junk('"LOCATIONNOTSETTLEMENTENG"') }} as locationnotsettlementeng,
        {{ null_junk('"LOCATIONNOTSETTLEMENTHEB"') }} as locationnotsettlementheb,
        {{ null_junk('"GLOBALID"') }} as globalid,
        {{ stg_float('"X"') }} as x,
        {{ stg_float('"Y"') }} as y,
        INGESTED_AT as _loaded_at,
        'https://data.gov.il/dataset/rabies-occurrence' as _source_url

    from source

)

select * from renamed
