{{ config(tags=['spine_generated']) }}

-- GRAIN: one row per place (GEOM is unique)
-- SPINE_ENTITY: place  (natural_key: GEOMETRY)
-- Generated by scripts/generate_staging_models.py from SOURCE_REGISTRY -- deterministic,
-- no LLM. Casts kept as landed (TEXT) -- add explicit type casts by hand once each
-- column's real type is confirmed; this generator has no semantic type knowledge.
-- spine_entity 'place' has no connect/ resolver yet (see connect/spine_entity.py) -- no SPINE_ENTITY_ID emitted.
-- landing table's ingestion timestamp is named INGESTED_AT (no leading underscore) rather than the usual _INGESTED_AT -- confirmed via INFORMATION_SCHEMA, not assumed.

with source as (

    select * from {{ source('ripple_raw', 'PORTAL_CKA_WESTERN_PENNSYLV_F66E0E22DA') }}

),

renamed as (

    select
        "ACRES" as acres,
        "APP_DATE" as app_date,
        "APP_SORT" as app_sort,
        "DSCHRG_PTS" as dschrg_pts,
        "FEATURE_ID" as feature_id,
        "LANDUSE" as landuse,
        "MAX_NONSTR" as max_nonstr,
        "POSTIMPERV" as postimperv,
        "PREIMPERV" as preimperv,
        "STATUS" as status,
        "MUNICIPALI" as municipali,
        "GEOMETRY" as geometry,
        INGESTED_AT as _loaded_at,
        'https://data.wprdc.org/dataset/applications-for-development-accd' as _source_url

    from source

)

select * from renamed
qualify row_number() over (partition by geometry order by _loaded_at desc) = 1
