{{ config(tags=['spine_generated']) }}

-- GRAIN: one row per organization (EIN is unique)
-- SPINE_ENTITY: organization  (natural_key: EIN)
-- Generated by scripts/generate_staging_models.py from SOURCE_REGISTRY -- deterministic,
-- no LLM.
-- CASTS: 10 of 28 columns, from landing_column_profile_2026-09-19.tsv. A column is cast only
-- when every filled value in the sample parsed. try_ casts: a value that does not
-- parse reads NULL. The natural key and join-key columns stay TEXT.
--   affiliation: integer
--   classification: integer
--   deductibility: integer
--   tax_period: integer
--   asset_cd: integer
--   income_cd: integer
--   pf_filing_req_cd: integer
--   asset_amt: integer
--   income_amt: integer
--   revenue_amt: integer

with source as (

    select * from {{ source('ripple_raw', 'FED_IRS_SOI_CHARITIES') }}
    qualify row_number() over (partition by "EIN" order by _INGESTED_AT desc) = 1

),

renamed as (

    select
        {{ null_junk('"EIN"') }} as ein,
        {{ null_junk('"NAME"') }} as name,
        {{ null_junk('"ICO"') }} as ico,
        {{ null_junk('"STREET"') }} as street,
        {{ null_junk('"CITY"') }} as city,
        {{ null_junk('"STATE"') }} as state,
        {{ null_junk('"ZIP"') }} as zip,
        {{ null_junk('"C_GROUP"') }} as c_group,
        {{ null_junk('"SUBSECTION"') }} as subsection,
        {{ stg_int('"AFFILIATION"') }} as affiliation,
        {{ stg_int('"CLASSIFICATION"') }} as classification,
        {{ null_junk('"RULING"') }} as ruling,
        {{ stg_int('"DEDUCTIBILITY"') }} as deductibility,
        {{ null_junk('"FOUNDATION"') }} as foundation,
        {{ null_junk('"ACTIVITY"') }} as activity,
        {{ null_junk('"C_ORGANIZATION"') }} as c_organization,
        {{ null_junk('"STATUS"') }} as status,
        {{ stg_int('"TAX_PERIOD"') }} as tax_period,
        {{ stg_int('"ASSET_CD"') }} as asset_cd,
        {{ stg_int('"INCOME_CD"') }} as income_cd,
        {{ null_junk('"FILING_REQ_CD"') }} as filing_req_cd,
        {{ stg_int('"PF_FILING_REQ_CD"') }} as pf_filing_req_cd,
        {{ null_junk('"ACCT_PD"') }} as acct_pd,
        {{ stg_int('"ASSET_AMT"') }} as asset_amt,
        {{ stg_int('"INCOME_AMT"') }} as income_amt,
        {{ stg_int('"REVENUE_AMT"') }} as revenue_amt,
        {{ null_junk('"NTEE_CD"') }} as ntee_cd,
        {{ null_junk('"SORT_NAME"') }} as sort_name,
        _INGESTED_AT as _loaded_at,
        '' as _source_url,
    'ENT_' || LEFT(MD5('EIN' || '|' || (CASE WHEN LENGTH(UPPER(REGEXP_REPLACE(TO_VARCHAR("EIN"), '[^0-9A-Za-z]', ''))) = 0 OR LENGTH(UPPER(REGEXP_REPLACE(TO_VARCHAR("EIN"), '[^0-9A-Za-z]', ''))) > 9 OR NOT REGEXP_LIKE(UPPER(REGEXP_REPLACE(TO_VARCHAR("EIN"), '[^0-9A-Za-z]', '')), '^[0-9]+$') OR LPAD(UPPER(REGEXP_REPLACE(TO_VARCHAR("EIN"), '[^0-9A-Za-z]', '')), 9, '0') = REPEAT('0', 9) OR (LENGTH(UPPER(REGEXP_REPLACE(TO_VARCHAR("EIN"), '[^0-9A-Za-z]', ''))) >= 4 AND UPPER(REGEXP_REPLACE(TO_VARCHAR("EIN"), '[^0-9A-Za-z]', '')) = REPEAT(LEFT(UPPER(REGEXP_REPLACE(TO_VARCHAR("EIN"), '[^0-9A-Za-z]', '')), 1), LENGTH(UPPER(REGEXP_REPLACE(TO_VARCHAR("EIN"), '[^0-9A-Za-z]', ''))))) OR LPAD(UPPER(REGEXP_REPLACE(TO_VARCHAR("EIN"), '[^0-9A-Za-z]', '')), 9, '0') = REPEAT(LEFT(LPAD(UPPER(REGEXP_REPLACE(TO_VARCHAR("EIN"), '[^0-9A-Za-z]', '')), 9, '0'), 1), 9) OR UPPER(REGEXP_REPLACE(TO_VARCHAR("EIN"), '[^0-9A-Za-z]', '')) IN ('123456789', '987654321', '1234567890', '0987654321', '12345678', '87654321', '123456', '654321') OR LPAD(UPPER(REGEXP_REPLACE(TO_VARCHAR("EIN"), '[^0-9A-Za-z]', '')), 9, '0') IN ('123456789', '987654321', '1234567890', '0987654321', '12345678', '87654321', '123456', '654321') THEN NULL ELSE LPAD(UPPER(REGEXP_REPLACE(TO_VARCHAR("EIN"), '[^0-9A-Za-z]', '')), 9, '0') END)), 16) as spine_entity_id  -- joins LIBRARY_META."CONNECT".ENTITY_GOLDEN.ENTITY_ID

    from source

)

select * from renamed
