{{ config(tags=['spine_generated']) }}

-- GRAIN: one row per record (spine_entity not determined -- no registry hint available) (EIN+ACTIVE_DATE+APPOINTMENT_TYPE+NAIC_ID unique)
-- SPINE_ENTITY: organization  (natural_key: EIN, ACTIVE_DATE, APPOINTMENT_TYPE, NAIC_ID)
-- Generated by scripts/generate_staging_models.py from SOURCE_REGISTRY -- deterministic,
-- no LLM. Casts kept as landed (TEXT) -- add explicit type casts by hand once each
-- column's real type is confirmed; this generator has no semantic type knowledge.
-- spine_entity 'organization' has no connect/ resolver yet (see connect/spine_entity.py) -- no SPINE_ENTITY_ID emitted.
-- landing table's ingestion timestamp is named INGESTED_AT (no leading underscore) rather than the usual _INGESTED_AT -- confirmed via INFORMATION_SCHEMA, not assumed.

with source as (

    select * from {{ source('ripple_raw', 'PORTAL_SOC_TEXAS_OPEN_DATA_6F798A64FA') }}

),

renamed as (

    select
        "NAIC_ID" as naic_id,
        "COMPANY" as company,
        "ACTIVE_DATE" as active_date,
        "APPOINTMENT_TYPE" as appointment_type,
        "NPN" as npn,
        "EIN" as ein,
        "AGENCY_NAME" as agency_name,
        "CITY" as city,
        "STATE" as state,
        "ZIP" as zip,
        INGESTED_AT as _loaded_at,
        'https://data.texas.gov/d/avjc-7u2m' as _source_url

    from source

)

select * from renamed
qualify row_number() over (partition by ein, active_date, appointment_type, naic_id order by _loaded_at desc) = 1
