{{ config(tags=['spine_generated']) }}

-- GRAIN: one row per place (LATLON is unique)
-- SPINE_ENTITY: place  (natural_key: LONGITUDE)
-- Generated by scripts/generate_staging_models.py from SOURCE_REGISTRY -- deterministic,
-- no LLM. Casts kept as landed (TEXT) -- add explicit type casts by hand once each
-- column's real type is confirmed; this generator has no semantic type knowledge.
-- spine_entity 'place' has no connect/ resolver yet (see connect/spine_entity.py) -- no SPINE_ENTITY_ID emitted.
-- landing table's ingestion timestamp is named INGESTED_AT (no leading underscore) rather than the usual _INGESTED_AT -- confirmed via INFORMATION_SCHEMA, not assumed.

with source as (

    select * from {{ source('ripple_raw', 'PORTAL_CKA_WESTERN_PENNSYLV_26625D455C') }}

),

renamed as (

    select
        "ID" as id,
        "NAME" as name,
        "ADDRESS_NUMBER" as address_number,
        "STREET" as street,
        "CITY" as city,
        "HOURS_OF_OPERATION" as hours_of_operation,
        "NOTES" as notes,
        "PHONE_NUMBER" as phone_number,
        "WEBSITE" as website,
        "MANAGED_BY_CITY" as managed_by_city,
        "ACCEPTS_ALKALINE_BATTERIES" as accepts_alkaline_batteries,
        "ACCEPTS_AUTOMOTIVE_BATTERIES" as accepts_automotive_batteries,
        "ACCEPTS_CFL_LIGHTBULBS" as accepts_cfl_lightbulbs,
        "ACCEPTS_CLOTHING" as accepts_clothing,
        "ACCEPTS_COLLECTIBLES" as accepts_collectibles,
        "ACCEPTS_COMPUTERS_AND_PERIPHERALS" as accepts_computers_and_peripherals,
        "ACCEPTS_CONSTRUCTION_AND_DEMOLITION_WASTE" as accepts_construction_and_demolition_waste,
        "ACCEPTS_FLUORESCENT_TUBE_LIGHTBULBS" as accepts_fluorescent_tube_lightbulbs,
        "ACCEPTS_FREON_APPLIANCES" as accepts_freon_appliances,
        "ACCEPTS_HOUSEHOLD_CHEMICALS_AND_WASTE" as accepts_household_chemicals_and_waste,
        "ACCEPTS_HOUSEHOLD_RECYCLABLES" as accepts_household_recyclables,
        "ACCEPTS_PLASTIC_BAGS_AND_FILMS" as accepts_plastic_bags_and_films,
        "ACCEPTS_PRESCRIPTION_MEDICATION" as accepts_prescription_medication,
        "ACCEPTS_PROPANE_TANKS" as accepts_propane_tanks,
        "ACCEPTS_RECHARGEABLE_BATTERIES" as accepts_rechargeable_batteries,
        "ACCEPTS_SCRAP_METAL" as accepts_scrap_metal,
        "ACCEPTS_SMALL_BUSINESS_RECYCLABLES" as accepts_small_business_recyclables,
        "ACCEPTS_TIRES" as accepts_tires,
        "ACCEPTS_TVS_AND_MONITORS" as accepts_tvs_and_monitors,
        "ACCEPTS_YARD_DEBRIS" as accepts_yard_debris,
        "ACCEPTS_CELL_PHONES" as accepts_cell_phones,
        "ACCEPTS_GENERAL_ELECTRONICS" as accepts_general_electronics,
        "ACCEPTS_INK_AND_TONER" as accepts_ink_and_toner,
        "ACCEPTS_MOTOR_OIL" as accepts_motor_oil,
        "INACTIVE" as inactive,
        "NEIGHBORHOOD" as neighborhood,
        "COUNCIL_DISTRICT" as council_district,
        "WARD" as ward,
        "TRACT" as tract,
        "PUBLIC_WORKS_DIVISION" as public_works_division,
        "PLI_DIVISION" as pli_division,
        "POLICE_ZONE" as police_zone,
        "FIRE_ZONE" as fire_zone,
        "LATITUDE" as latitude,
        "LONGITUDE" as longitude,
        INGESTED_AT as _loaded_at,
        'https://data.wprdc.org/dataset/waste-recovery-locations' as _source_url

    from source

)

select * from renamed
qualify row_number() over (partition by longitude order by _loaded_at desc) = 1
