{{ config(tags=['spine_generated']) }}

-- GRAIN: one row per place (ZIP is unique)
-- SPINE_ENTITY: place  (natural_key: ZIP)
-- Generated by scripts/generate_staging_models.py from SOURCE_REGISTRY -- deterministic,
-- no LLM.
-- CASTS: none of 25 columns. landing_column_profile_2026-09-19.tsv found no TEXT column where
-- every filled value parsed as a number, date or boolean.
-- spine_entity 'place' has no connect/ resolver yet (see connect/spine_entity.py) -- no SPINE_ENTITY_ID emitted.
-- landing table's ingestion timestamp is named INGESTED_AT (no leading underscore) rather than the usual _INGESTED_AT -- confirmed via INFORMATION_SCHEMA, not assumed.

with source as (

    select * from {{ source('ripple_raw', 'PORTAL_ARC_LA_COUNTY_OPEN_D_464355F6D4') }}
    qualify row_number() over (partition by "ZIP" order by INGESTED_AT desc) = 1

),

renamed as (

    select
        {{ null_junk('"OBJECTID"') }} as objectid,
        {{ null_junk('"LOCNUM"') }} as locnum,
        {{ null_junk('"CONAME"') }} as coname,
        {{ null_junk('"STREET"') }} as street,
        {{ null_junk('"CITY"') }} as city,
        {{ null_junk('"STATE"') }} as state,
        {{ null_junk('"STATE_NAME"') }} as state_name,
        {{ null_junk('"ZIP"') }} as zip,
        {{ null_junk('"ZIP4"') }} as zip4,
        {{ null_junk('"NAICS"') }} as naics,
        {{ null_junk('"SIC"') }} as sic,
        {{ null_junk('"SALESVOL"') }} as salesvol,
        {{ null_junk('"HDBRCH"') }} as hdbrch,
        {{ null_junk('"ULTNUM"') }} as ultnum,
        {{ null_junk('"PUBPRV"') }} as pubprv,
        {{ null_junk('"EMPNUM"') }} as empnum,
        {{ null_junk('"FRNCOD"') }} as frncod,
        {{ null_junk('"ISCODE"') }} as iscode,
        {{ null_junk('"SQFTCODE"') }} as sqftcode,
        {{ null_junk('"LOC_NAME"') }} as loc_name,
        {{ null_junk('"STATUS"') }} as status,
        {{ null_junk('"SCORE"') }} as score,
        {{ null_junk('"SOURCE"') }} as source,
        {{ null_junk('"REC_TYPE"') }} as rec_type,
        {{ null_junk('"GEOMETRY"') }} as geometry,
        INGESTED_AT as _loaded_at,
        'https://data.lacounty.gov/datasets/3234831de59f44f6abda51e2df78ae24_6' as _source_url

    from source

)

select * from renamed
