{{ config(tags=['minimal_staging']) }}

-- GRAIN: NOT YET DETERMINED (profiler returned AMBIGUOUS -- needs manual review)
-- This is a passthrough staging view: snake_case rename only, no dedup.
-- Once grain is resolved, replace with a full staging model via generate_staging_models.py.
-- Generated by scripts/generate_minimal_staging.py

with source as (

    select * from {{ source('ripple_raw', 'FED_IRS_990_EFILE_INDEX') }}

),

renamed as (

    select
        RETURN_ID as return_id,
        FILING_TYPE as filing_type,
        EIN as ein,
        TAX_PERIOD as tax_period,
        SUB_DATE as sub_date,
        TAXPAYER_NAME as taxpayer_name,
        RETURN_TYPE as return_type,
        DLN as dln,
        OBJECT_ID as object_id,
        _INGESTED_AT as _loaded_at,
        '' as _source_url

    from source

)

select * from renamed
