-- @sub_other6_quarters
select '2024Q1' q, ADSH, CIK, NAME, SIC, FORM, AFS, FYE, PERIOD, FILED, COUNTRYBA, STPRBA, CITYBA, ZIPBA, BAS1, BAPH, COUNTRYINC, STPRINC, EIN, FORMER, CHANGED, PREVRPT from LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_DERA_SUB_2024Q1
union all
select '2024Q2' q, ADSH, CIK, NAME, SIC, FORM, AFS, FYE, PERIOD, FILED, COUNTRYBA, STPRBA, CITYBA, ZIPBA, BAS1, BAPH, COUNTRYINC, STPRINC, EIN, FORMER, CHANGED, PREVRPT from LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_DERA_SUB_2024Q2
union all
select '2024Q3' q, ADSH, CIK, NAME, SIC, FORM, AFS, FYE, PERIOD, FILED, COUNTRYBA, STPRBA, CITYBA, ZIPBA, BAS1, BAPH, COUNTRYINC, STPRINC, EIN, FORMER, CHANGED, PREVRPT from LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_DERA_SUB_2024Q3
union all
select '2024Q4' q, ADSH, CIK, NAME, SIC, FORM, AFS, FYE, PERIOD, FILED, COUNTRYBA, STPRBA, CITYBA, ZIPBA, BAS1, BAPH, COUNTRYINC, STPRINC, EIN, FORMER, CHANGED, PREVRPT from LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_DERA_SUB_2024Q4
union all
select '2025Q1' q, ADSH, CIK, NAME, SIC, FORM, AFS, FYE, PERIOD, FILED, COUNTRYBA, STPRBA, CITYBA, ZIPBA, BAS1, BAPH, COUNTRYINC, STPRINC, EIN, FORMER, CHANGED, PREVRPT from LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_DERA_SUB_2025Q1
union all
select '2025Q2' q, ADSH, CIK, NAME, SIC, FORM, AFS, FYE, PERIOD, FILED, COUNTRYBA, STPRBA, CITYBA, ZIPBA, BAS1, BAPH, COUNTRYINC, STPRINC, EIN, FORMER, CHANGED, PREVRPT from LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_DERA_SUB_2025Q2
-- @edgar_financials_vs_sub
select source_file, count(*) n, count(distinct adsh) adsh, min(filed) min_filed, max(filed) max_filed from LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_EDGAR_FINANCIALS group by 1 order by 1
-- @insider_sub_coverage
select to_char(try_to_date(filing_date::string), 'YYYY-MM') ym, count(*) n, count(distinct issuer_cik) issuers, min(filing_date) mn, max(filing_date) mx
from LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_INSIDER_SUBMISSION group by 1 order by 1
