-- S01 Column names and types for the 5 tables
SELECT TABLE_NAME, LISTAGG(COLUMN_NAME || ':' || DATA_TYPE, ', ') WITHIN GROUP (ORDER BY ORDINAL_POSITION) cols
FROM LIBRARY_MARTS.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'FINANCE' AND TABLE_NAME IN ('FINANCE__FED_OCC_THRIFTS','FINANCE__FED_SEC_BUSINESS_DEVELOPMENT_COMPANY_REPORT','FINANCE__FED_FEC_LEADERSHIP_PAC','FINANCE__FED_SEC_EDGAR_COMPANY_TICKERS_EXCHANGE','FINANCE__FED_SEC_DERA_SUB_2024Q1','FINANCE__FED_FDIC_BANK_DATA','FINANCE__FED_SEC_DERA_SUB_2025Q1','FINANCE__FED_SEC_DERA_SUB_2026Q1')
GROUP BY 1 ORDER BY 1
