-- S02 OCC thrifts: junk rows, ID fill, load runs, and land rate on FDIC bank data by CERT
WITH t AS (SELECT * FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_OCC_THRIFTS),
f AS (SELECT TRY_TO_NUMBER(CERT) cert, MAX(NAME) fname, MAX(ACTIVE) active, MAX(ASSET) asset, MAX(CHRTAGNT) chrt, MAX(BKCLASS) bkclass, MAX(REPDTE) repdte
      FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_FDIC_BANK_DATA GROUP BY 1)
SELECT COUNT(*) n, COUNT_IF(NOT REGEXP_LIKE(t.CHARTER_NO,'^[0-9]+$')) charter_bad,
       COUNT_IF(t.NAME IS NULL OR t.NAME IN ('None','')) name_bad, COUNT(DISTINCT t.NAME) names,
       COUNT(DISTINCT t.RSSD) rssd_d, COUNT(t.RSSD) rssd_fill, COUNT(DISTINCT t.CERT) cert_d, COUNT(t.CERT) cert_fill,
       COUNT(DISTINCT t._SOURCE_RUN_ID) runs, COUNT(DISTINCT t._SRC_SHA256) shas,
       COUNT(f.cert) land_fdic, COUNT_IF(f.active = '1') fdic_active, ARRAY_AGG(DISTINCT f.bkclass) bkclass, ARRAY_AGG(DISTINCT f.chrt) chrt,
       SUM(f.asset) fdic_asset_sum, MEDIAN(f.asset) fdic_asset_med, MAX(f.repdte) repdte,
       ARRAY_AGG(IFF(NOT REGEXP_LIKE(t.CHARTER_NO,'^[0-9]+$') OR t.NAME IS NULL OR t.NAME IN ('None','') OR t.RSSD IS NULL,
             OBJECT_CONSTRUCT('ch', t.CHARTER_NO, 'nm', t.NAME, 'st', t.STATE, 'cert', t.CERT, 'rssd', t.RSSD), NULL)) odd_rows,
       ARRAY_AGG(DISTINCT t.STATE) states
FROM t LEFT JOIN f ON f.cert = t.CERT;

-- S03 BDC report: what the FILING_DATE years are, CIK width, file-number prefix, by year
SELECT YEAR(FILING_DATE) y, COUNT(*) n, MIN(FILING_DATE) d0, MAX(FILING_DATE) d1, COUNT(DISTINCT CIK) ciks,
       COUNT_IF(LENGTH(CIK) = 10) cik10, ARRAY_AGG(DISTINCT LEFT(FILE_NO, 4)) file_prefix, ARRAY_AGG(DISTINCT FILING_TYPE) forms,
       COUNT(DISTINCT REGISTRANT_NAME) names
FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_BUSINESS_DEVELOPMENT_COMPANY_REPORT
GROUP BY 1 ORDER BY 1;

-- S04 "Leadership PAC" table: committee type x designation, distinct IDs, linkage-ID uniqueness
SELECT CMTE_TP, CMTE_DSGN, COUNT(*) n, COUNT(DISTINCT FEC_COMMITTEE_ID) cmtes, COUNT(DISTINCT FEC_CANDIDATE_ID) cands,
       COUNT(DISTINCT LINKAGE_ID) links, MIN(CAND_ELECTION_YR) y0, MAX(CAND_ELECTION_YR) y1, ARRAY_AGG(DISTINCT FEC_ELECTION_YR) cycles
FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_FEC_LEADERSHIP_PAC
GROUP BY 1,2 ORDER BY n DESC;

-- S05 Is it the FEC linkage file? LINKAGE_ID land rate on the linkage tables, and designation-D committees in the committee dim
WITH lp AS (SELECT * FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_FEC_LEADERSHIP_PAC),
lk AS (SELECT DISTINCT LINKAGE_ID FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_FEC_CAND_CMTE_LINKAGE),
lk2 AS (SELECT DISTINCT LINKAGE_ID FROM LIBRARY_MARTS.POLITICS.POLITICS__FEC_CAND_CMTE_LINK),
dim AS (SELECT CMTE_ID, MAX(CMTE_DSGN) dsgn, MAX(CMTE_TP) tp FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_FEC_COMMITTEES_DIM GROUP BY 1)
SELECT COUNT(*) n,
       COUNT_IF(lp.LINKAGE_ID IN (SELECT LINKAGE_ID FROM lk)) in_fin_linkage,
       COUNT_IF(lp.LINKAGE_ID IN (SELECT LINKAGE_ID FROM lk2)) in_pol_link,
       COUNT(dim.CMTE_ID) cmte_in_dim, COUNT_IF(dim.dsgn = 'D') dim_says_leadership,
       (SELECT COUNT(*) FROM dim WHERE dsgn = 'D') dim_leadership_total,
       (SELECT COUNT(*) FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_FEC_CAND_CMTE_LINKAGE WHERE FEC_ELECTION_YR = '2024') fin_linkage_2024_rows
FROM lp LEFT JOIN dim ON dim.CMTE_ID = lp.FEC_COMMITTEE_ID;

-- S06 Ticker table: how many copies each CIK-ticker pair has, and whether copies differ
WITH g AS (SELECT CIK_TICKER, COUNT(*) c, COUNT(DISTINCT _SOURCE_RUN_ID) runs, COUNT(DISTINCT _LOADED_AT) loads, COUNT(DISTINCT EXCHANGE) ex,
                  COUNT(DISTINCT COMPANY_NAME) nms, ANY_VALUE(COMPANY_NAME) nm, ANY_VALUE(EXCHANGE) exch
           FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_EDGAR_COMPANY_TICKERS_EXCHANGE GROUP BY 1)
SELECT c copies, COUNT(*) pairs, SUM(c) rows_, MAX(runs) max_runs, MAX(loads) max_loads, MAX(ex) max_ex, MAX(nms) max_names,
       ARRAY_SLICE(ARRAY_AGG(nm || ' [' || exch || ']') WITHIN GROUP (ORDER BY nm), 0, 12) sample
FROM g GROUP BY 1 ORDER BY 1;

-- S07 DERA SUB 2024Q1: rows vs distinct ADSH, by form, filing lag, amended flag, filer size
WITH t AS (SELECT *, COUNT(*) OVER (PARTITION BY ADSH) adsh_n FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_DERA_SUB_2024Q1)
SELECT FORM, COUNT(*) n, COUNT(DISTINCT ADSH) adsh_d, MAX(adsh_n) max_copies, COUNT(DISTINCT CIK) ciks, MIN(FILED) f0, MAX(FILED) f1,
       COUNT_IF(PREVRPT = '1') prevrpt1, COUNT_IF(AFS LIKE '1%') laf, COUNT_IF(AFS LIKE '2%') acc, COUNT_IF(AFS LIKE '4%') non, COUNT_IF(NULLIF(TRIM(AFS),'') IS NULL) afs_blank,
       MEDIAN(DATEDIFF(day, TRY_TO_DATE(PERIOD,'YYYYMMDD'), TRY_TO_DATE(FILED,'YYYYMMDD'))) med_lag,
       COUNT_IF(DATEDIFF(day, TRY_TO_DATE(PERIOD,'YYYYMMDD'), TRY_TO_DATE(FILED,'YYYYMMDD')) > 365) lag_over_1y,
       COUNT_IF(EIN = '000000000' OR NULLIF(TRIM(EIN),'') IS NULL) ein_blank
FROM t GROUP BY 1 ORDER BY n DESC;

-- S08 All nine DERA SUB quarters: rows, distinct filings, filed-date range, 10-K counts
SELECT '2024Q1' q, COUNT(*) n, COUNT(DISTINCT ADSH) adsh, COUNT(DISTINCT CIK) ciks, MIN(FILED) f0, MAX(FILED) f1, COUNT_IF(FORM='10-K') k10, COUNT_IF(FORM='10-Q') q10, COUNT_IF(FORM='10-K/A') k10a FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_DERA_SUB_2024Q1
UNION ALL SELECT '2024Q2', COUNT(*), COUNT(DISTINCT ADSH), COUNT(DISTINCT CIK), MIN(FILED), MAX(FILED), COUNT_IF(FORM='10-K'), COUNT_IF(FORM='10-Q'), COUNT_IF(FORM='10-K/A') FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_DERA_SUB_2024Q2
UNION ALL SELECT '2024Q3', COUNT(*), COUNT(DISTINCT ADSH), COUNT(DISTINCT CIK), MIN(FILED), MAX(FILED), COUNT_IF(FORM='10-K'), COUNT_IF(FORM='10-Q'), COUNT_IF(FORM='10-K/A') FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_DERA_SUB_2024Q3
UNION ALL SELECT '2024Q4', COUNT(*), COUNT(DISTINCT ADSH), COUNT(DISTINCT CIK), MIN(FILED), MAX(FILED), COUNT_IF(FORM='10-K'), COUNT_IF(FORM='10-Q'), COUNT_IF(FORM='10-K/A') FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_DERA_SUB_2024Q4
UNION ALL SELECT '2025Q1', COUNT(*), COUNT(DISTINCT ADSH), COUNT(DISTINCT CIK), MIN(FILED), MAX(FILED), COUNT_IF(FORM='10-K'), COUNT_IF(FORM='10-Q'), COUNT_IF(FORM='10-K/A') FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_DERA_SUB_2025Q1
UNION ALL SELECT '2025Q2', COUNT(*), COUNT(DISTINCT ADSH), COUNT(DISTINCT CIK), MIN(FILED), MAX(FILED), COUNT_IF(FORM='10-K'), COUNT_IF(FORM='10-Q'), COUNT_IF(FORM='10-K/A') FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_DERA_SUB_2025Q2
UNION ALL SELECT '2025Q3', COUNT(*), COUNT(DISTINCT ADSH), COUNT(DISTINCT CIK), MIN(FILED), MAX(FILED), COUNT_IF(FORM='10-K'), COUNT_IF(FORM='10-Q'), COUNT_IF(FORM='10-K/A') FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_DERA_SUB_2025Q3
UNION ALL SELECT '2025Q4', COUNT(*), COUNT(DISTINCT ADSH), COUNT(DISTINCT CIK), MIN(FILED), MAX(FILED), COUNT_IF(FORM='10-K'), COUNT_IF(FORM='10-Q'), COUNT_IF(FORM='10-K/A') FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_DERA_SUB_2025Q4
UNION ALL SELECT '2026Q1', COUNT(*), COUNT(DISTINCT ADSH), COUNT(DISTINCT CIK), MIN(FILED), MAX(FILED), COUNT_IF(FORM='10-K'), COUNT_IF(FORM='10-Q'), COUNT_IF(FORM='10-K/A') FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_DERA_SUB_2026Q1
ORDER BY 1;
