-- S09 BDC report (retry of S03): FILING_DATE as text, year prefix, CIK width, file-number prefix
SELECT LEFT(TO_VARCHAR(FILING_DATE), 4) y, COUNT(*) n, MIN(TO_VARCHAR(FILING_DATE)) d0, MAX(TO_VARCHAR(FILING_DATE)) d1, COUNT(DISTINCT CIK) ciks,
       COUNT_IF(LENGTH(CIK) = 10) cik10, ARRAY_AGG(DISTINCT LEFT(FILE_NO, 4)) file_prefix, ARRAY_AGG(DISTINCT FILING_TYPE) forms,
       COUNT(DISTINCT REGISTRANT_NAME) names, ANY_VALUE(REGISTRANT_NAME) eg
FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_BUSINESS_DEVELOPMENT_COMPANY_REPORT
GROUP BY 1 ORDER BY 1;

-- S10 Ticker table (retry of S06): copies per CIK-ticker pair, and whether copies differ
WITH g AS (SELECT CIK_TICKER, COUNT(*) c, COUNT(DISTINCT _SOURCE_RUN_ID) runs, COUNT(DISTINCT _LOADED_AT) loads, COUNT(DISTINCT EXCHANGE) ex,
                  COUNT(DISTINCT COMPANY_NAME) nms, ANY_VALUE(COMPANY_NAME) nm, ANY_VALUE(EXCHANGE) exch
           FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_EDGAR_COMPANY_TICKERS_EXCHANGE GROUP BY 1)
SELECT c AS copies, COUNT(*) pairs, SUM(c) rows_, MAX(runs) max_runs, MAX(loads) max_loads, MAX(ex) max_ex, MAX(nms) max_names,
       ARRAY_SLICE(ARRAY_AGG(nm || ' [' || exch || ']') WITHIN GROUP (ORDER BY nm), 0, 12) eg
FROM g GROUP BY 1 ORDER BY 1;

-- S11 OCC thrifts: the ones FDIC marks closed, and the biggest by FDIC assets (thousands of dollars)
WITH f AS (SELECT TRY_TO_NUMBER(CERT) cert, MAX(NAME) fname, MAX(ACTIVE) active, MAX(ASSET) asset, MAX(ENDEFYMD) ended, MAX(SUCCESSOR_CERT) succ
           FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_FDIC_BANK_DATA GROUP BY 1)
SELECT t.NAME, t.CITY, t.STATE, t.CERT, f.fname, f.active, f.asset, f.ended, f.succ
FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_OCC_THRIFTS t JOIN f ON f.cert = t.CERT
QUALIFY f.active <> '1' OR ROW_NUMBER() OVER (ORDER BY f.asset DESC NULLS LAST) <= 8
ORDER BY f.asset DESC NULLS LAST;

-- S12 Leadership PACs (designation D) in the FEC PAC summary, by cycle: how much of their spending goes to other candidates and committees
WITH p AS (SELECT *, YEAR(COVERAGE_END_DATE) + MOD(YEAR(COVERAGE_END_DATE), 2) cyc,
                  (COALESCE(CONTRIBUTIONS_TO_OTHER_COMMITTEES,0) + COALESCE(INDEPENDENT_EXPENDITURES,0) + COALESCE(TRANSFERS_TO_AFFILIATES,0)) to_others
           FROM LIBRARY_MARTS.POLITICS.POLITICS__FED_FEC_PAC_SUMMARY
           WHERE COMMITTEE_DESIGNATION = 'D' AND COVERAGE_END_DATE IS NOT NULL)
SELECT cyc, COUNT(*) n, COUNT(DISTINCT CMTE_ID) cmtes, ROUND(SUM(TOTAL_DISBURSEMENTS)/1e6,1) disb_m, ROUND(SUM(to_others)/1e6,1) to_others_m,
       COUNT_IF(TOTAL_DISBURSEMENTS >= 250000) n_250k,
       MEDIAN(IFF(TOTAL_DISBURSEMENTS >= 250000, to_others / TOTAL_DISBURSEMENTS, NULL)) med_share_250k,
       COUNT_IF(TOTAL_DISBURSEMENTS >= 250000 AND to_others / TOTAL_DISBURSEMENTS < 0.10) n_250k_under10,
       ROUND(SUM(IFF(TOTAL_DISBURSEMENTS >= 250000 AND to_others / TOTAL_DISBURSEMENTS < 0.10, TOTAL_DISBURSEMENTS, 0))/1e6,1) disb_m_under10,
       MEDIAN(IFF(TOTAL_DISBURSEMENTS >= 250000, PCT_DISBURSED_TO_OTHERS, NULL)) med_pct_col,
       CORR(IFF(TOTAL_DISBURSEMENTS >= 250000, to_others / TOTAL_DISBURSEMENTS, NULL), IFF(TOTAL_DISBURSEMENTS >= 250000, PCT_DISBURSED_TO_OTHERS, NULL)) corr_mine_vs_col,
       COUNT(DISTINCT _SOURCE_RUN_ID) runs
FROM p GROUP BY 1 ORDER BY 1;

-- S13 2024 leadership PACs with $250K+ spending: share to others, their 2018-2022 shares, sponsor from the committee dim, flag if in the LEADERSHIP_PAC table
WITH p AS (SELECT CMTE_ID, COMMITTEE_NAME, COMMITTEE_TYPE, YEAR(COVERAGE_END_DATE) + MOD(YEAR(COVERAGE_END_DATE), 2) cyc, TOTAL_RECEIPTS, TOTAL_DISBURSEMENTS,
                  (COALESCE(CONTRIBUTIONS_TO_OTHER_COMMITTEES,0) + COALESCE(INDEPENDENT_EXPENDITURES,0) + COALESCE(TRANSFERS_TO_AFFILIATES,0)) to_others,
                  CONTRIBUTIONS_TO_OTHER_COMMITTEES c_oth, CASH_CLOSE_OF_PERIOD cash_close
           FROM LIBRARY_MARTS.POLITICS.POLITICS__FED_FEC_PAC_SUMMARY
           WHERE COMMITTEE_DESIGNATION = 'D' AND COVERAGE_END_DATE IS NOT NULL),
hist AS (SELECT CMTE_ID, OBJECT_AGG(cyc::STRING, ROUND(to_others / NULLIF(TOTAL_DISBURSEMENTS,0), 3)::VARIANT) share_by_cycle,
                OBJECT_AGG(cyc::STRING, ROUND(TOTAL_DISBURSEMENTS/1e3)::VARIANT) disb_k_by_cycle
         FROM p WHERE cyc BETWEEN 2018 AND 2022 GROUP BY 1),
dim AS (SELECT CMTE_ID, MAX(CAND_ID) cand_id, MAX(CONNECTED_ORG_NM) org, MAX(CMTE_ST) st FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_FEC_COMMITTEES_DIM GROUP BY 1),
lp AS (SELECT DISTINCT FEC_COMMITTEE_ID, FEC_CANDIDATE_ID FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_FEC_LEADERSHIP_PAC WHERE CMTE_DSGN = 'D')
SELECT p.CMTE_ID, p.COMMITTEE_NAME, p.COMMITTEE_TYPE, dim.st, dim.cand_id, dim.org, lp.FEC_CANDIDATE_ID lp_cand,
       ROUND(p.TOTAL_RECEIPTS/1e3) rcpt_k, ROUND(p.TOTAL_DISBURSEMENTS/1e3) disb_k, ROUND(p.to_others/1e3) to_others_k,
       ROUND(p.to_others / p.TOTAL_DISBURSEMENTS, 3) share, ROUND(p.cash_close/1e3) cash_close_k, hist.share_by_cycle, hist.disb_k_by_cycle
FROM p LEFT JOIN hist ON hist.CMTE_ID = p.CMTE_ID LEFT JOIN dim ON dim.CMTE_ID = p.CMTE_ID LEFT JOIN lp ON lp.FEC_COMMITTEE_ID = p.CMTE_ID
WHERE p.cyc = 2024 AND p.TOTAL_DISBURSEMENTS >= 250000
ORDER BY share, p.TOTAL_DISBURSEMENTS DESC;

-- S14 DERA SUB, all nine quarters: original 10-K and 10-Q filed past the deadline plus the NT extension plus 3 days, by quarter and filer size
WITH s AS (
  SELECT '2024Q1' q, * FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_DERA_SUB_2024Q1 UNION ALL
  SELECT '2024Q2', * FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_DERA_SUB_2024Q2 UNION ALL
  SELECT '2024Q3', * FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_DERA_SUB_2024Q3 UNION ALL
  SELECT '2024Q4', * FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_DERA_SUB_2024Q4 UNION ALL
  SELECT '2025Q1', * FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_DERA_SUB_2025Q1 UNION ALL
  SELECT '2025Q2', * FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_DERA_SUB_2025Q2 UNION ALL
  SELECT '2025Q3', * FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_DERA_SUB_2025Q3 UNION ALL
  SELECT '2025Q4', * FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_DERA_SUB_2025Q4 UNION ALL
  SELECT '2026Q1', * FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_DERA_SUB_2026Q1),
l AS (SELECT q, FORM, LEFT(AFS,1) afs1, DATEDIFF(day, TRY_TO_DATE(PERIOD,'YYYYMMDD'), TRY_TO_DATE(FILED,'YYYYMMDD')) lag,
             IFF(FORM = '10-K', IFF(LEFT(AFS,1) = '1', 60, IFF(LEFT(AFS,1) IN ('2','3'), 75, 90)) + 15,
                                IFF(LEFT(AFS,1) IN ('1','2','3'), 40, 45) + 5) + 3 allowed
      FROM s WHERE FORM IN ('10-K','10-Q'))
SELECT q, FORM, afs1, COUNT(*) n, COUNT_IF(lag > allowed) late, ROUND(COUNT_IF(lag > allowed) / COUNT(*) * 100, 2) late_pct,
       COUNT_IF(lag > allowed + 90) late_90plus, COUNT_IF(lag > 365) over_1y, COUNT_IF(lag IS NULL) no_lag, MEDIAN(lag) med_lag
FROM l GROUP BY 1,2,3 ORDER BY 2,3,1;
