{{ config(tags=['spine_generated']) }}

-- GRAIN: one row per place (GEOM is unique)
-- SPINE_ENTITY: place  (natural_key: DATASPATIAL_WKB)
-- Generated by scripts/generate_staging_models.py from SOURCE_REGISTRY -- deterministic,
-- no LLM.
-- CASTS: 3 of 6 columns, from landing_column_profile_2026-09-19.tsv. A column is cast only
-- when every filled value in the sample parsed. try_ casts: a value that does not
-- parse reads NULL. The natural key and join-key columns stay TEXT.
--   featurecod: integer
--   fid: ID: whole numbers, over 90% distinct -- stays TEXT, '.0' tail removed
--   update_yea: integer
-- spine_entity 'place' has no connect/ resolver yet (see connect/spine_entity.py) -- no SPINE_ENTITY_ID emitted.
-- landing table's ingestion timestamp is named INGESTED_AT (no leading underscore) rather than the usual _INGESTED_AT -- confirmed via INFORMATION_SCHEMA, not assumed.

with source as (

    select * from {{ source('ripple_raw', 'PORTAL_CKA_WESTERN_PENNSYLV_82D49E467F') }}
    qualify row_number() over (partition by "DATASPATIAL_WKB" order by INGESTED_AT desc) = 1

),

renamed as (

    select
        {{ null_junk('"SHAPE_LEN"') }} as shape_len,
        {{ stg_int('"FEATURECOD"') }} as featurecod,
        {{ stg_id_text('"FID"') }} as fid,
        {{ null_junk('"SHAPE_AREA"') }} as shape_area,
        {{ stg_int('"UPDATE_YEA"') }} as update_yea,
        {{ null_junk('"DATASPATIAL_WKB"') }} as dataspatial_wkb,
        INGESTED_AT as _loaded_at,
        'https://data.wprdc.org/dataset/allegheny-county-hydrology-areas' as _source_url

    from source

)

select * from renamed
