P = "LIBRARY_MARTS.HEALTH."
POS = P + "HEALTH__FED_CMS_POS_OTHER"
QUERIES = [
("pos_code05_06_since_2015", f"""
select PRVDR_CTGRY_CD cat, PRVDR_CTGRY_SBTYP_CD sub, PGM_TRMNTN_CD code, TRMNTN_EXPRTN_DT ended, FAC_NAME, CITY_NAME, STATE_CD,
 CHOW_CNT, CHOW_DT, ORGNL_PRTCPTN_DT joined, GNRL_CNTL_TYPE_CD ctl, BED_CNT
from {POS} where PGM_TRMNTN_CD in ('05','06') and TRMNTN_EXPRTN_DT>='2015-01-01'
order by TRMNTN_EXPRTN_DT desc"""),
]
