-- @emp_firms_all
select * from LIBRARY_MARTS.POLITICS.POLITICS__CA_LOBBY_EMPLOYER_FIRMS
-- @irs8871_all
select * from LIBRARY_MARTS.POLITICS.POLITICS__IRS527_8871_ORGS
-- @scotus_all
select * from LIBRARY_MARTS.POLITICS.POLITICS__JUDGE_IDEOLOGY_SCOTUS
-- @firm_emp_all
select * from LIBRARY_MARTS.POLITICS.POLITICS__CA_LOBBY_FIRM_EMPLOYER
-- @fec_cand_all
select * from LIBRARY_MARTS.POLITICS.POLITICS__FEC_CANDIDATE
-- @fec_cand_summary_all
select * from LIBRARY_MARTS.POLITICS.POLITICS__FEC_CANDIDATE_SUMMARY
