{{ config(materialized='view', schema='TIMELINE', alias='REFERENCE__FED_ITIS_KINGDOMS') }}

-- GENERATED by scripts/census/gen_time_views.py -- do not hand-edit.
-- Regenerate after any change to reports/time_index/clock_index.csv.
--
-- Canonical clock for REFERENCE.REFERENCE__FED_ITIS_KINGDOMS.
--   column : UPDATE_DATE   (DATE)
--   means  : reported -- the ITIS UPDATE_DATE pattern on a 7-row lookup of the kingdoms of life: the curator edit date, the table's only clock and of essentially no timeline value at th
--   grain  : day
--
-- reported cannot be in the future -- if this row's value is, ripple_clock
-- reads 'planned' instead, not 'reported'. See ripple_row_clock in
-- macros/ripple_time.sql.
--
-- The original columns pass through untouched; the canonical four sit in front
-- of them. Rule 8 of the datetime standard: the raw column is never overwritten,
-- so a mis-parse is always recoverable.

select
    {{ ripple_window('src."UPDATE_DATE"::timestamp_ntz') }} as ripple_ts,
    {{ ripple_grain('day') }} as ripple_grain,
    {{ ripple_row_clock(ripple_window('src."UPDATE_DATE"::timestamp_ntz'), 'reported') }} as ripple_clock,
    'REFERENCE.REFERENCE__FED_ITIS_KINGDOMS'::varchar as ripple_source,
    src.*
from {{ ref('reference__fed_itis_kingdoms') }} as src
