-- @fjc_appt_all
select * from LIBRARY_MARTS.POLITICS.POLITICS__FJC_APPOINTMENT
-- @freedomhouse_all
select * from LIBRARY_MARTS.POLITICS.POLITICS__INTL_FREEDOMHOUSE
-- @cannabis_all
select * from LIBRARY_MARTS.POLITICS.POLITICS__ST_CANNABIS_POLICY_BUNDLES
-- @voteview_meta_all
select * from LIBRARY_MARTS.POLITICS.POLITICS__FED_VOTEVIEW_ROLLCALL_META
-- @irs527_related_all
select * from LIBRARY_MARTS.POLITICS.POLITICS__IRS527_RELATED_ENTITIES
