-- @bmf_liberty_group_or_addresses
select EIN, ORG_NAME, IN_CARE_OF, STREET, CITY, STATE, SUBSECTION_CODE, NTEE_CODE, RULING_DATE, REVENUE_AMT, ASSET_AMT, TAX_PERIOD_YYYYMM
from LIBRARY_MARTS.CORPORATE_REGISTRY.CORPORATE_REGISTRY__FED_IRS_EO_BMF
where regexp_replace(upper(ORG_NAME),'[^A-Z ]','') in ('LIBERTY GROUP INC','LIBERTY GROUP','THE LIBERTY GROUP','THE LIBERTY GROUP INC','AMERICAN LIBERTY GROUP','AMERICAN LIBERTY GROUP INC')
   or regexp_replace(upper(STREET),'[^A-Z0-9]','') like '11403RDST%'
   or upper(IN_CARE_OF) like '%MCCAULEY%'
order by ORG_NAME
