-- S01 column types for my five tables and the two revocation tables (information schema)
SELECT TABLE_NAME, COLUMN_NAME, DATA_TYPE, ORDINAL_POSITION
FROM LIBRARY_MARTS.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'ECONOMICS'
  AND TABLE_NAME IN ('ECONOMICS__XC_WIKIPEDIA_LARGEST_US_COMPANIES','ECONOMICS__FED_IRS_990_EFILE_INDEX','ECONOMICS__FED_US_SEC_EDGAR',
                     'ECONOMICS__FED_GRANTS_GOV','ECONOMICS__FED_IRS_FATCA_FFI_LIST','ECONOMICS__FED_IRS_REVOCATION','ECONOMICS__FED_IRS_AUTO_REVOCATIONS')
ORDER BY TABLE_NAME, ORDINAL_POSITION;

-- S02 Wikipedia 100 largest companies: pull all 100 rows (tiny lookup)
SELECT * FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__XC_WIKIPEDIA_LARGEST_US_COMPANIES;
