-- S03 Grants.gov: fill count of every column, distinct IDs, date range (confirm it is a 100-row API sample)
SELECT COUNT(*) n, COUNT(DISTINCT OPPORTUNITY_ID) ids, COUNT(DISTINCT OPPORTUNITY_NUMBER) opp_nums, COUNT(DISTINCT AGENCY_CODE) agency_codes,
  COUNT_IF(NULLIF(TRIM(OPPORTUNITY_TITLE),'') IS NOT NULL) f_title, COUNT_IF(NULLIF(TRIM(AGENCY_NAME),'') IS NOT NULL) f_agency_name,
  COUNT_IF(NULLIF(TRIM(OPPORTUNITY_STATUS),'') IS NOT NULL) f_status, COUNT_IF(NULLIF(TRIM(OPPORTUNITY_CATEGORY),'') IS NOT NULL) f_cat,
  COUNT_IF(NULLIF(TRIM(FUNDING_INSTRUMENT_TYPE),'') IS NOT NULL) f_instr, COUNT_IF(NULLIF(TRIM(CATEGORY_OF_FUNDING_ACTIVITY),'') IS NOT NULL) f_activity,
  COUNT_IF(NULLIF(TRIM(CFDA_NUMBERS),'') IS NOT NULL AND CFDA_NUMBERS <> '[]') f_cfda, COUNT_IF(NULLIF(TRIM(ELIGIBLE_APPLICANTS),'') IS NOT NULL) f_elig,
  COUNT_IF(NULLIF(TRIM(AWARD_CEILING),'') IS NOT NULL) f_ceiling, COUNT_IF(NULLIF(TRIM(AWARD_FLOOR),'') IS NOT NULL) f_floor,
  COUNT_IF(NULLIF(TRIM(ESTIMATED_TOTAL_PROGRAM_FUNDING),'') IS NOT NULL) f_total, COUNT_IF(NULLIF(TRIM(EXPECTED_NUMBER_OF_AWARDS),'') IS NOT NULL) f_nawards,
  COUNT_IF(NULLIF(TRIM(LAST_UPDATED_DATE),'') IS NOT NULL) f_upd, COUNT_IF(NULLIF(TRIM(ARCHIVE_DATE),'') IS NOT NULL) f_arch,
  COUNT_IF(NULLIF(TRIM(SYNOPSIS_DESC),'') IS NOT NULL) f_syn, COUNT_IF(NULLIF(TRIM(GRANTOR_CONTACT_EMAIL),'') IS NOT NULL) f_email,
  COUNT_IF(NULLIF(TRIM(GRANTOR_CONTACT_NAME),'') IS NOT NULL) f_cname, COUNT_IF(NULLIF(TRIM(VERSION),'') IS NOT NULL) f_ver,
  COUNT_IF(CLOSE_DATE IS NOT NULL) f_close, MIN(POSTED_DATE) p0, MAX(POSTED_DATE) p1, MIN(CLOSE_DATE) c0, MAX(CLOSE_DATE) c1
FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_GRANTS_GOV;

-- S04 SEC EDGAR (US): per company, rows, accessions, date span, forms, flags, and the recent window
SELECT CIK, ANY_VALUE(ENTITY_NAME) nm, ANY_VALUE(TICKER) tk, COUNT(*) n, COUNT(DISTINCT ACCESSION_NUMBER) acc,
  MIN(FILED_AT) f0, MAX(FILED_AT) f1, COUNT(DISTINCT FORM_TYPE) forms, COUNT(DISTINCT EIN) eins, ANY_VALUE(SIC_CODE) sic,
  COUNT_IF(FORM_TYPE = '424B2') f424b2, COUNT_IF(FORM_TYPE = '8-K') f8k, COUNT_IF(FORM_TYPE IN ('10-K','10-Q')) fkq, COUNT_IF(FORM_TYPE = '4') f4,
  COUNT_IF(FORM_TYPE = 'FWP') ffwp, COUNT_IF(IS_REGISTRATION_OR_PROSPECTUS) reg, COUNT_IF(IS_ANNUAL_REPORT) ann, COUNT_IF(IS_QUARTERLY_REPORT) qtr,
  COUNT_IF(FILED_AT >= '2025-01-01') since2025, COUNT(DISTINCT _SOURCE_RUN_ID) runs, COUNT(DISTINCT BUSINESS_ADDRESS) addrs
FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_US_SEC_EDGAR
GROUP BY CIK ORDER BY n DESC;

-- S05 990 e-file index: by index year and date format; ids, blanks, form mix, EIN width, tax-period span
SELECT YEAR(SUB_DATE) sub_y, REGEXP_LIKE(TRIM(SUB_DATE_RAW), '^[0-9]{4}$') year_only, COUNT(*) n,
  COUNT(DISTINCT OBJECT_ID) objs, COUNT(DISTINCT DLN) dlns, COUNT_IF(NULLIF(TRIM(RETURN_ID),'') IS NULL) rid_blank,
  COUNT(DISTINCT EIN) eins, COUNT_IF(LENGTH(EIN) <> 9) ein_not9, COUNT_IF(EIN = '000000000') ein_zero,
  COUNT_IF(RETURN_TYPE = '990') r990, COUNT_IF(RETURN_TYPE = '990EZ') r990ez, COUNT_IF(RETURN_TYPE = '990PF') r990pf,
  COUNT_IF(RETURN_TYPE = '990T') r990t, COUNT_IF(RETURN_TYPE NOT IN ('990','990EZ','990PF','990T')) r_other,
  MIN(TAX_PERIOD) tp0, MAX(TAX_PERIOD) tp1, COUNT_IF(MONTH(SUB_DATE) = 1 AND DAY(SUB_DATE) = 1) jan1
FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_IRS_990_EFILE_INDEX
GROUP BY 1, 2 ORDER BY 1, 2;

-- S06 the two auto-revocation tables: size, distinct EINs, date span, reinstated share, revocations by year
SELECT 'AUTO_REVOCATIONS' t, YEAR(REVOCATION_DATE) rev_y, COUNT(*) n, COUNT(DISTINCT EIN) eins, COUNT_IF(REINSTATEMENT_DATE IS NOT NULL) reinst,
  COUNT_IF(REINSTATEMENT_DATE = REVOCATION_DATE) reinst_same_day, MIN(REVOCATION_POSTING_DATE) post0, MAX(REVOCATION_POSTING_DATE) post1,
  COUNT_IF(LENGTH(EIN) <> 9) ein_not9
FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_IRS_AUTO_REVOCATIONS GROUP BY 2
UNION ALL
SELECT 'REVOCATION', YEAR(TRY_TO_DATE(REVOCATION_DATE)), COUNT(*), COUNT(DISTINCT EIN), COUNT_IF(NULLIF(TRIM(REINSTATEMENT_DATE),'') IS NOT NULL),
  COUNT_IF(REINSTATEMENT_DATE = REVOCATION_DATE), MIN(TRY_TO_DATE(REVOCATION_POSTING_DATE)), MAX(TRY_TO_DATE(REVOCATION_POSTING_DATE)),
  COUNT_IF(LENGTH(EIN) <> 9)
FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_IRS_REVOCATION GROUP BY 2
ORDER BY 1, 2;

-- S07 FATCA FFI list: pull all rows (516K x 3 text columns) for local work
SELECT GIIN, FINM, COUNTRYNM FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_IRS_FATCA_FFI_LIST;
