-- S12 detail for the S10 hits: every e-filed index row (all return types) for revoked EINs (2019 on) that have a 990/990EZ/990PF
-- for a tax period ending 5-40 months before the revocation date, submitted before it (earlier calendar year, or full timestamp earlier)
WITH r AS (
  SELECT EIN, LEGAL_NAME, CITY, STATE, EXEMPTION_TYPE, REVOCATION_DATE d, REVOCATION_POSTING_DATE pd, REINSTATEMENT_DATE rd
  FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_IRS_AUTO_REVOCATIONS WHERE REVOCATION_DATE >= '2019-01-01'),
i AS (
  SELECT EIN, TAX_PERIOD, TRY_TO_DATE(TAX_PERIOD || '01', 'YYYYMMDD') p, SUB_DATE, SUB_DATE_RAW, REGEXP_LIKE(TRIM(SUB_DATE_RAW), '^[0-9]{4}$') yo,
         RETURN_TYPE, OBJECT_ID, RETURN_ID, DLN, TAXPAYER_NAME
  FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_IRS_990_EFILE_INDEX WHERE EIN IN (SELECT EIN FROM r)),
h AS (
  SELECT DISTINCT r.EIN FROM r JOIN i ON i.EIN = r.EIN
  WHERE i.RETURN_TYPE IN ('990','990EZ','990PF') AND i.p BETWEEN DATEADD(month, -40, r.d) AND DATEADD(month, -5, r.d)
    AND (YEAR(i.SUB_DATE) < YEAR(r.d) OR (NOT i.yo AND i.SUB_DATE < r.d)))
SELECT r.EIN, r.LEGAL_NAME, r.CITY, r.STATE, r.EXEMPTION_TYPE, r.d, r.pd, r.rd, i.TAX_PERIOD, i.SUB_DATE, i.SUB_DATE_RAW, i.RETURN_TYPE,
  i.OBJECT_ID, i.RETURN_ID, i.DLN, i.TAXPAYER_NAME
FROM h JOIN r ON r.EIN = h.EIN JOIN i ON i.EIN = h.EIN
ORDER BY r.EIN, i.TAX_PERIOD, i.SUB_DATE;
