{{ config(tags=['spine_generated']) }}

-- GRAIN: one row per place (ZIP+SEGMENT_ID unique)
-- SPINE_ENTITY: place  (natural_key: ZIP_R, SEGMENT_ID)
-- Generated by scripts/generate_staging_models.py from SOURCE_REGISTRY -- deterministic,
-- no LLM.
-- CASTS: 13 of 38 columns, from landing_column_profile_2026-09-19.tsv. A column is cast only
-- when every filled value in the sample parsed. try_ casts: a value that does not
-- parse reads NULL. The natural key and join-key columns stay TEXT.
--   l_f_add: integer
--   l_t_add: integer
--   r_f_add: integer
--   r_t_add: integer
--   speedlimit: integer
--   f_zlev: integer
--   t_zlev: integer
--   ft_cost: float
--   tf_cost: float
--   county00_l: integer
--   county00_r: integer
--   mcd00_l: integer
--   mcd00_r: integer
-- spine_entity 'place' has no connect/ resolver yet (see connect/spine_entity.py) -- no SPINE_ENTITY_ID emitted.
-- landing table's ingestion timestamp is named INGESTED_AT (no leading underscore) rather than the usual _INGESTED_AT -- confirmed via INFORMATION_SCHEMA, not assumed.

with source as (

    select * from {{ source('ripple_raw', 'PORTAL_CKA_ANALYZE_BOSTON_DD269D0A1D') }}
    qualify row_number() over (partition by "ZIP_R", "SEGMENT_ID" order by INGESTED_AT desc) = 1

),

renamed as (

    select
        {{ null_junk('"SEGMENT_ID"') }} as segment_id,
        {{ stg_int('"L_F_ADD"') }} as l_f_add,
        {{ stg_int('"L_T_ADD"') }} as l_t_add,
        {{ stg_int('"R_F_ADD"') }} as r_f_add,
        {{ stg_int('"R_T_ADD"') }} as r_t_add,
        {{ null_junk('"STREET_ID"') }} as street_id,
        {{ null_junk('"PRE_DIR"') }} as pre_dir,
        {{ null_junk('"ST_NAME"') }} as st_name,
        {{ null_junk('"ST_TYPE"') }} as st_type,
        {{ null_junk('"SUF_DIR"') }} as suf_dir,
        {{ null_junk('"ALTERNATE_NAME"') }} as alternate_name,
        {{ null_junk('"CFCC"') }} as cfcc,
        {{ stg_int('"SPEEDLIMIT"') }} as speedlimit,
        {{ null_junk('"ONEWAY"') }} as oneway,
        {{ stg_int('"F_ZLEV"') }} as f_zlev,
        {{ stg_int('"T_ZLEV"') }} as t_zlev,
        {{ stg_float('"FT_COST"') }} as ft_cost,
        {{ stg_float('"TF_COST"') }} as tf_cost,
        {{ null_junk('"FT_DIR"') }} as ft_dir,
        {{ null_junk('"TF_DIR"') }} as tf_dir,
        {{ null_junk('"SHIELD"') }} as shield,
        {{ null_junk('"HWY_NUM"') }} as hwy_num,
        {{ null_junk('"MUN_L"') }} as mun_l,
        {{ null_junk('"MUN_R"') }} as mun_r,
        {{ null_junk('"NBHD_L"') }} as nbhd_l,
        {{ null_junk('"NBHD_R"') }} as nbhd_r,
        {{ null_junk('"STATE00_L"') }} as state00_l,
        {{ null_junk('"STATE00_R"') }} as state00_r,
        {{ stg_int('"COUNTY00_L"') }} as county00_l,
        {{ stg_int('"COUNTY00_R"') }} as county00_r,
        {{ stg_int('"MCD00_L"') }} as mcd00_l,
        {{ stg_int('"MCD00_R"') }} as mcd00_r,
        {{ null_junk('"ZIP_L"') }} as zip_l,
        {{ null_junk('"ZIP_R"') }} as zip_r,
        {{ null_junk('"OWNERSHIP"') }} as ownership,
        {{ null_junk('"ROUTE_ID"') }} as route_id,
        {{ null_junk('"SHAPE_LENGTH"') }} as shape_length,
        {{ null_junk('"SHAPE_WKT"') }} as shape_wkt,
        INGESTED_AT as _loaded_at,
        'https://data.boston.gov/dataset/boston-street-segments-sam-system' as _source_url

    from source

)

select * from renamed
