{{ config(tags=['spine_generated']) }}

-- GRAIN: one row per record (spine_entity not determined -- no registry hint available) (ID unique)
-- SPINE_ENTITY: (not determined)  (natural_key: ID)
-- Generated by scripts/generate_staging_models.py from SOURCE_REGISTRY -- deterministic,
-- no LLM. Casts kept as landed (TEXT) -- add explicit type casts by hand once each
-- column's real type is confirmed; this generator has no semantic type knowledge.
-- spine_entity not determined (grain/natural_key proven, but no registry hint says what this row is ABOUT) -- no SPINE_ENTITY_ID emitted.
-- landing table's ingestion timestamp is named INGESTED_AT (no leading underscore) rather than the usual _INGESTED_AT -- confirmed via INFORMATION_SCHEMA, not assumed.

with source as (

    select * from {{ source('ripple_raw', 'PORTAL_SOC_CONNECTICUT_OPEN_88B075D7AF') }}

),

renamed as (

    select
        "ID" as id,
        "NAME" as name,
        "STATUS" as status,
        "ACCOUNTNUMBER" as accountnumber,
        "DATE_REGISTRATION" as date_registration,
        "MAILING_ADDRESS" as mailing_address,
        "WOMAN_OWNED_ORGANIZATION" as woman_owned_organization,
        "VETERAN_OWNED_ORGANIZATION" as veteran_owned_organization,
        "MINORITY_OWNED_ORGANIZATION" as minority_owned_organization,
        "ORG_OWNED_BY_PERSON_S_WITH" as org_owned_by_person_s_with,
        "ORGANIZATION_IS_LGBTQI_OWNED" as organization_is_lgbtqi_owned,
        "CREATE_DT" as create_dt,
        "BUSINESS_TYPE" as business_type,
        "ANNUAL_REPORT_DUE_DATE" as annual_report_due_date,
        "CITIZENSHIP" as citizenship,
        "COUNTRY_FORMATION" as country_formation,
        "STATE_OR_TERRITORY_FORMATION" as state_or_territory_formation,
        "BUSINESS_EMAIL_ADDRESS" as business_email_address,
        "FORMATION_PLACE" as formation_place,
        "CATEGORY_SURVEY_EMAIL_ADDRESS" as category_survey_email_address,
        "NAICS_CODE" as naics_code,
        "TOTAL_AUTHORIZED_SHARES" as total_authorized_shares,
        "BILLINGSTREET" as billingstreet,
        "BILLING_UNIT" as billing_unit,
        "BILLINGCITY" as billingcity,
        "BILLINGCOUNTRY" as billingcountry,
        "BILLINGPOSTALCODE" as billingpostalcode,
        "BILLINGSTATE" as billingstate,
        "DISSOLUTION_DATE" as dissolution_date,
        "REASON_FOR_ADMINISTRATIVE" as reason_for_administrative,
        "BEGAN_TRANSACTING_IN_CT" as began_transacting_in_ct,
        "BUSINESS_NAME_IN_STATE_COUNTRY" as business_name_in_state_country,
        "SUB_STATUS" as sub_status,
        "MAILING_INTERNATIONAL_ADDRESS" as mailing_international_address,
        "DATE_OF_ORGANIZATION_MEETING" as date_of_organization_meeting,
        INGESTED_AT as _loaded_at,
        'https://data.ct.gov/d/n7gp-d28j' as _source_url

    from source

)

select * from renamed
qualify row_number() over (partition by id order by _loaded_at desc) = 1
