-- S01 Leiden Russian ops: every row (150), to read and tally locally
SELECT * FROM LIBRARY_MARTS.INVESTIGATIONS.INVESTIGATIONS__INTL_LEIDEN_RUSSIAN_OPS_EUROPE
;

-- S02 Wayback DOJ deep pages: every row (2,542), to diff link sets across captures locally
SELECT * FROM LIBRARY_MARTS.INVESTIGATIONS.INVESTIGATIONS__XC_WAYBACK_REPLAY_DOJ_DEEP_PAGES
;

-- S03 bioRxiv/medRxiv: every row (432)
SELECT * FROM LIBRARY_MARTS.SCIENCE_RESEARCH.SCIENCE_RESEARCH__XC_BIORXIV_MEDRXIV
;

-- S04 USAspending subawards sample: every row (5,000) with RECORD_JSON, to unpack prime award and UEIs locally
SELECT * FROM LIBRARY_MARTS.PROCUREMENT.PROCUREMENT__FED_USASPENDING_SUBAWARDS
;

-- S05 Ecuador SERCOP: every row (132,995), working columns only (constants and party lists left out)
SELECT OCID, RECORD_ID, RECORD_DATE, BUYER_ID, BUYER_NAME, TENDER_ID, TENDER_TITLE, TENDER_STATUS,
       TENDER_PROCUREMENT_METHOD, TENDER_VALUE_AMOUNT, AWARD_ID, AWARD_DATE, AWARD_STATUS, AWARD_VALUE_AMOUNT,
       SUPPLIER_ID, SUPPLIER_NAME, CONTRACT_ID, CONTRACT_DATE_SIGNED, CONTRACT_VALUE_AMOUNT, PLANNING_BUDGET_AMOUNT,
       LANGUAGE, TENDER_DATE_PUBLISHED, PARTIES_ROLES, ARRAY_SIZE(SPLIT(PARTIES_ID, '|')) N_PARTIES,
       _SOURCE_RUN_ID, _INGESTED_AT
FROM LIBRARY_MARTS.PROCUREMENT.PROCUREMENT__INTL_EC_SERCOP
;
