-- S09 Wayback CDX table: what URL shapes it holds (digits collapsed to #), since S06 matched nothing
SELECT REGEXP_REPLACE(LOWER(ORIGINAL_URL), '[0-9]+', '#') shape, COUNT(*) n, COUNT(DISTINCT ORIGINAL_URL) urls,
       ANY_VALUE(ORIGINAL_URL) ex, ANY_VALUE(URLKEY) ex_key, MIN(CAPTURED_AT) t0, MAX(CAPTURED_AT) t1
FROM LIBRARY_MARTS.OPEN_DATA.OPEN_DATA__XC_WAYBACK_DOJ_EPSTEIN
GROUP BY 1 ORDER BY 2 DESC LIMIT 60
;
