-- S01 All five tables: column names, types, order (spot the header-eaten record and text-typed money)
SELECT TABLE_SCHEMA, TABLE_NAME, ORDINAL_POSITION, COLUMN_NAME, DATA_TYPE
FROM LIBRARY_MARTS.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME IN ('ENERGY__FED_EIA_861_BALANCING_AUTHORITY','ENERGY__FED_EIA860_6_1_ENVIROASSOC','ENERGY__FED_EIA861_FRAME','ENERGY__FED_EIA861_MERGERS','EDUCATION__FED_GOOGLE_POLADS_ADVERTISER_GEO_SPEND')
ORDER BY TABLE_NAME, ORDINAL_POSITION

-- S02 Mergers: read all 4 rows
SELECT * FROM LIBRARY_MARTS.ENERGY.ENERGY__FED_EIA861_MERGERS
