-- S03 Balancing authority: confirm it is a lookup (one row per authority-state, one year)
SELECT COUNT(*) n, COUNT(DISTINCT BA_ID) ba_ids, COUNT(DISTINCT BA_CODE) ba_codes, COUNT(DISTINCT BA_ID, STATE) ba_state_pairs,
       COUNT(DISTINCT STATE) states, MIN(DATA_YEAR) y0, MAX(DATA_YEAR) y1, COUNT(DISTINCT _SOURCE_RUN_ID) runs,
       COUNT_IF(BA_CODE IS NULL OR TRIM(BA_CODE)='') blank_code
FROM LIBRARY_MARTS.ENERGY.ENERGY__FED_EIA_861_BALANCING_AUTHORITY

-- S04 Enviro association: confirm it is a boiler-to-generator link list; STEAM_PLANT_TYPE is a 1-4 code, not an amount; land rate in the plant table
WITH a AS (SELECT * FROM LIBRARY_MARTS.ENERGY.ENERGY__FED_EIA860_6_1_ENVIROASSOC),
p AS (SELECT DISTINCT PLANT_CODE FROM LIBRARY_MARTS.ENERGY.ENERGY__FED_EIA860_2_PLANT)
SELECT COUNT(*) n, COUNT(DISTINCT a.PLANT_CODE) plants, COUNT(DISTINCT a.PLANT_CODE, BOILER_ID, GENERATOR_ID) links,
       COUNT(DISTINCT a.PLANT_CODE, BOILER_ID) boilers, COUNT(DISTINCT a.PLANT_CODE, GENERATOR_ID) gens,
       COUNT_IF(STEAM_PLANT_TYPE=1) t1, COUNT_IF(STEAM_PLANT_TYPE=2) t2, COUNT_IF(STEAM_PLANT_TYPE=3) t3, COUNT_IF(STEAM_PLANT_TYPE=4) t4,
       COUNT(DISTINCT UTILITY_ID) utils, COUNT(DISTINCT _SOURCE_RUN_ID) runs,
       COUNT(DISTINCT IFF(p.PLANT_CODE IS NOT NULL, a.PLANT_CODE, NULL)) plants_in_plant_table
FROM a LEFT JOIN p ON a.PLANT_CODE = p.PLANT_CODE

-- S05 Frame: confirm it is the survey roster; ownership mix; which schedule flags carry X; land rate in the long-form and short-form data tables
WITH f AS (SELECT * FROM LIBRARY_MARTS.ENERGY.ENERGY__FED_EIA861_FRAME),
u AS (SELECT DISTINCT UTILITY_NUMBER FROM LIBRARY_MARTS.ENERGY.ENERGY__FED_EIA861_UTILITY_DATA),
s AS (SELECT DISTINCT UTILITY_NUMBER FROM LIBRARY_MARTS.ENERGY.ENERGY__FED_EIA861_SHORT_FORM)
SELECT COUNT(*) n, COUNT(DISTINCT f.UTILITY_NUMBER) utils, COUNT_IF(f.UTILITY_NUMBER=99999) n99999, MIN(DATA_YEAR) y0, MAX(DATA_YEAR) y1,
       COUNT_IF(SHORT_FORM='Y') short_y, COUNT_IF(SCHEDULE_FLAG_01='X') f01, COUNT_IF(SCHEDULE_FLAG_02='X') f02, COUNT_IF(SCHEDULE_FLAG_03='X') f03,
       COUNT_IF(SCHEDULE_FLAG_04='X') f04, COUNT_IF(SCHEDULE_FLAG_05='X') f05, COUNT_IF(SCHEDULE_FLAG_06='X') f06, COUNT_IF(SCHEDULE_FLAG_07='X') f07,
       COUNT_IF(SCHEDULE_FLAG_08='X') f08, COUNT_IF(SCHEDULE_FLAG_09='X') f09, COUNT_IF(SCHEDULE_FLAG_10='X') f10, COUNT_IF(SCHEDULE_FLAG_11='X') f11,
       COUNT_IF(SCHEDULE_FLAG_12='X') f12, COUNT_IF(SCHEDULE_FLAG_13='X') f13, COUNT_IF(SCHEDULE_FLAG_14='X') f14, COUNT_IF(SCHEDULE_FLAG_15='X') f15,
       COUNT(DISTINCT u.UTILITY_NUMBER) in_long_form, COUNT(DISTINCT s.UTILITY_NUMBER) in_short_form,
       COUNT_IF(u.UTILITY_NUMBER IS NULL AND s.UTILITY_NUMBER IS NULL) in_neither,
       COUNT_IF(SHORT_FORM='Y' AND s.UTILITY_NUMBER IS NULL) short_flag_not_in_short
FROM f LEFT JOIN u ON f.UTILITY_NUMBER=u.UTILITY_NUMBER LEFT JOIN s ON f.UTILITY_NUMBER=s.UTILITY_NUMBER

-- S06 Frame and mergers landing tables: raw column names (did the loader eat a data row as the header?) and landing row counts
SELECT c.TABLE_NAME, c.ORDINAL_POSITION, c.COLUMN_NAME, t.ROW_COUNT
FROM LIBRARY_RAW.INFORMATION_SCHEMA.COLUMNS c JOIN LIBRARY_RAW.INFORMATION_SCHEMA.TABLES t ON c.TABLE_SCHEMA=t.TABLE_SCHEMA AND c.TABLE_NAME=t.TABLE_NAME
WHERE c.TABLE_SCHEMA='LANDING' AND c.TABLE_NAME IN ('FED_EIA861_FRAME','FED_EIA861_MERGERS')
ORDER BY 1,2

-- S07 Google geo spend: profile. Grain, full-row duplicates, spend as numbers, rounding, non-USD columns
SELECT COUNT(*) n, COUNT(DISTINCT ADVERTISER_ID) adv_ids, COUNT(DISTINCT ADVERTISER_NAME) adv_names,
       COUNT(DISTINCT ADVERTISER_ID, COUNTRY, COUNTRY_SUBDIVISION_PRIMARY) id_geo_keys, COUNT(DISTINCT HASH(*)) distinct_rows,
       COUNT(DISTINCT COUNTRY_SUBDIVISION_PRIMARY) subs, COUNT_IF(COUNTRY_SUBDIVISION_PRIMARY IS NULL OR TRIM(COUNTRY_SUBDIVISION_PRIMARY)='') sub_blank,
       COUNT_IF(TRY_TO_NUMBER(SPEND_USD) IS NULL) usd_not_num, SUM(TRY_TO_NUMBER(SPEND_USD)) usd_sum, MAX(TRY_TO_NUMBER(SPEND_USD)) usd_max,
       COUNT_IF(TRY_TO_NUMBER(SPEND_USD)=0) usd_0, COUNT_IF(MOD(TRY_TO_NUMBER(SPEND_USD),100)<>0) usd_not_x100,
       COUNT_IF(COALESCE(SPEND_EUR,'0') NOT IN ('0','')) eur_nz, COUNT_IF(COALESCE(SPEND_GBP,'0') NOT IN ('0','')) gbp_nz,
       COUNT_IF(COALESCE(SPEND_INR,'0') NOT IN ('0','')) inr_nz, COUNT_IF(COALESCE(SPEND_AUD,'0') NOT IN ('0','')) aud_nz,
       COUNT_IF(COALESCE(SPEND_BRL,'0') NOT IN ('0','')) brl_nz, COUNT_IF(COALESCE(SPEND_MXN,'0') NOT IN ('0','')) mxn_nz
FROM LIBRARY_MARTS.EDUCATION.EDUCATION__FED_GOOGLE_POLADS_ADVERTISER_GEO_SPEND

-- S08 Google geo spend: rows per advertiser-state key, and whether the repeats carry different spend
WITH k AS (SELECT ADVERTISER_ID, COUNTRY_SUBDIVISION_PRIMARY sub, COUNT(*) n, COUNT(DISTINCT SPEND_USD) dv, SUM(TRY_TO_NUMBER(SPEND_USD)) s
           FROM LIBRARY_MARTS.EDUCATION.EDUCATION__FED_GOOGLE_POLADS_ADVERTISER_GEO_SPEND GROUP BY 1,2)
SELECT n rows_per_key, COUNT(*) keys, COUNT_IF(dv>1) keys_with_diff_spend, SUM(s) usd, COUNT(DISTINCT ADVERTISER_ID) advs
FROM k GROUP BY n ORDER BY n
