-- S09 Google geo spend: extract every advertiser-place row (id, country, state, USD) for local peer math
SELECT ADVERTISER_ID, COUNTRY, COUNTRY_SUBDIVISION_PRIMARY sub, TRY_TO_NUMBER(SPEND_USD) usd
FROM LIBRARY_MARTS.EDUCATION.EDUCATION__FED_GOOGLE_POLADS_ADVERTISER_GEO_SPEND

-- S10 Google advertiser stats (sibling table): names, regions, all-place total USD, ad count, the IDs each buyer gave Google (FEC ID lives here)
SELECT ADVERTISER_ID, ADVERTISER_NAME, REGIONS, TRY_TO_NUMBER(SPEND_USD::STRING) usd_total, TOTAL_CREATIVES, PUBLIC_IDS_LIST
FROM LIBRARY_MARTS.EDUCATION.EDUCATION__FED_GOOGLE_POLADS_ADVERTISER_STATS

-- S11 Google geo spend: advertiser id to name as the geo table spells it
SELECT ADVERTISER_ID, ANY_VALUE(ADVERTISER_NAME) nm, COUNT(DISTINCT ADVERTISER_NAME) names
FROM LIBRARY_MARTS.EDUCATION.EDUCATION__FED_GOOGLE_POLADS_ADVERTISER_GEO_SPEND GROUP BY 1

-- S12 FEC committees (one clean line each) for every FEC committee ID the Google buyers listed
WITH ids AS (SELECT DISTINCT f.value::STRING cmte
             FROM LIBRARY_MARTS.EDUCATION.EDUCATION__FED_GOOGLE_POLADS_ADVERTISER_STATS s,
                  LATERAL FLATTEN(input => REGEXP_SUBSTR_ALL(s.PUBLIC_IDS_LIST, 'C[0-9]{8}')) f)
SELECT ids.cmte, d.CMTE_NM, d.CMTE_ST, d.CMTE_CITY, d.CMTE_TP, d.CMTE_DSGN, d.CMTE_PTY_AFFILIATION, d.CAND_ID, d.CYCLE, d.IS_AMBIGUOUS, d.SRC
FROM ids LEFT JOIN LIBRARY_MARTS.FINANCE.FINANCE__FED_FEC_COMMITTEES_DIM d ON d.CMTE_ID = ids.cmte

-- S13 FEC candidates behind those committees: office, office state, district, incumbent flag, party, by election year
WITH ids AS (SELECT DISTINCT f.value::STRING cmte
             FROM LIBRARY_MARTS.EDUCATION.EDUCATION__FED_GOOGLE_POLADS_ADVERTISER_STATS s,
                  LATERAL FLATTEN(input => REGEXP_SUBSTR_ALL(s.PUBLIC_IDS_LIST, 'C[0-9]{8}')) f),
c AS (SELECT DISTINCT d.CAND_ID FROM ids JOIN LIBRARY_MARTS.FINANCE.FINANCE__FED_FEC_COMMITTEES_DIM d ON d.CMTE_ID = ids.cmte WHERE d.CAND_ID IS NOT NULL AND TRIM(d.CAND_ID)<>'')
SELECT k.CAND_ID, k.CAND_NAME, k.CAND_ELECTION_YR, k.CAND_OFFICE, k.CAND_OFFICE_ST, k.CAND_OFFICE_DISTRICT, k.CAND_ICI, k.CAND_PTY_AFFILIATION, k.CAND_STATUS, k.CAND_PCC, k.CAND_ST
FROM c JOIN LIBRARY_MARTS.FINANCE.FINANCE__FED_FEC_CANDIDATES k ON k.CAND_ID = c.CAND_ID

-- S14 State population, 2020 census, summed from the county master list
SELECT STATE_NAME, SUM(POPULATION_2020) pop, COUNT(*) counties FROM LIBRARY_MARTS.CORE.DIM_COUNTY GROUP BY 1 ORDER BY 1
