-- S15 Weekly Google political spend for every account verified with the U.S. House's own EIN (53-6002523), i.e. members' official offices
WITH o AS (SELECT ADVERTISER_ID FROM LIBRARY_MARTS.EDUCATION.EDUCATION__FED_GOOGLE_POLADS_ADVERTISER_STATS WHERE PUBLIC_IDS_LIST ILIKE '%53-6002523%')
SELECT w.ADVERTISER_ID, w.ADVERTISER_NAME, w.WEEK_START_DATE, w.ELECTION_CYCLE, TRY_TO_NUMBER(w.SPEND_USD::STRING) usd
FROM LIBRARY_MARTS.EDUCATION.EDUCATION__FED_GOOGLE_POLADS_ADVERTISER_WEEKLY_SPEND w JOIN o ON o.ADVERTISER_ID = w.ADVERTISER_ID

-- S16 Every ad those official-office accounts ran: dates, spend range, impressions, where it was aimed
WITH o AS (SELECT ADVERTISER_ID FROM LIBRARY_MARTS.EDUCATION.EDUCATION__FED_GOOGLE_POLADS_ADVERTISER_STATS WHERE PUBLIC_IDS_LIST ILIKE '%53-6002523%')
SELECT c.ADVERTISER_ID, c.AD_ID, c.AD_TYPE, c.DATE_RANGE_START, c.DATE_RANGE_END, c.NUM_OF_DAYS, c.IMPRESSIONS,
       c.SPEND_RANGE_MIN_USD, c.SPEND_RANGE_MAX_USD, c.GEO_TARGETING_INCLUDED, c.GEO_TARGETING_EXCLUDED, c.AD_URL
FROM LIBRARY_MARTS.EDUCATION.EDUCATION__FED_GOOGLE_POLADS_CREATIVE_STATS c JOIN o ON o.ADVERTISER_ID = c.ADVERTISER_ID
