-- S17 Voteview House members, 115th-119th Congress: who held each district (to check the name on each official ad account against the district its ads aimed at)
SELECT CONGRESS, STATE_ABBREV, DISTRICT_CODE, BIONAME, BIOGUIDE_ID, PARTY_CODE, OCCUPANCY
FROM LIBRARY_MARTS.POLITICS.POLITICS__FED_VOTEVIEW_MEMBERS
WHERE CHAMBER = 'House' AND CONGRESS BETWEEN 115 AND 119

-- S18 FEC candidate records for the members whose official accounts spent inside 60 days of a general election, plus Gomez (CA-34): on the ballot that year?
SELECT CAND_ID, CAND_NAME, CAND_ELECTION_YR, CAND_OFFICE, CAND_OFFICE_ST, CAND_OFFICE_DISTRICT, CAND_ICI, CAND_STATUS, CAND_PCC
FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_FEC_CANDIDATES
WHERE CAND_OFFICE = 'H' AND (CAND_NAME ILIKE 'CUELLAR%' OR CAND_NAME ILIKE 'MCCARTHY, KEVIN%' OR CAND_NAME ILIKE 'OLSON, PETE%'
   OR CAND_NAME ILIKE 'HOLLINGSWORTH%' OR CAND_NAME ILIKE 'GOMEZ, JIMMY%' OR CAND_NAME ILIKE 'STEEL, MICHELLE%' OR CAND_NAME ILIKE 'GOLDMAN, DAN%')
ORDER BY CAND_NAME, CAND_ELECTION_YR
