-- All columns of the 5 tables, with type and the table row counts
select c.TABLE_NAME, c.ORDINAL_POSITION, c.COLUMN_NAME, c.DATA_TYPE, t.ROW_COUNT, t.BYTES, t.LAST_ALTERED::date la
from LIBRARY_MARTS.INFORMATION_SCHEMA.COLUMNS c
join LIBRARY_MARTS.INFORMATION_SCHEMA.TABLES t on t.TABLE_SCHEMA=c.TABLE_SCHEMA and t.TABLE_NAME=c.TABLE_NAME
where c.TABLE_SCHEMA='IMMIGRATION' and c.TABLE_NAME in ('IMMIGRATION__FED_DHS_YEARBOOK','IMMIGRATION__FED_ICE_STATISTICS','IMMIGRATION__FED_USCIS_DATA','IMMIGRATION__FED_EOIR_CASE_DATA','IMMIGRATION__XC_OWID_REFUGEES')
order by 1,2
