import pandas as pd, numpy as np
pd.set_option('display.width',250); pd.set_option('display.max_columns',40); pd.set_option('display.max_rows',200)
t=pd.read_pickle('t.pkl')
d=t[t.ACTIVITY_ID.duplicated(keep=False)].sort_values('ACTIVITY_ID')
print('rows in dup activity groups', len(d), 'groups', d.ACTIVITY_ID.nunique())
print(d.head(12))
g=d.groupby('ACTIVITY_ID').agg(n=('PGM_SYS_ID','size'),pg=('PGM_SYS_ID','nunique'),dt=('ACTUAL_END_DATE','nunique'),fl=('FACILITY_RPT_DEVIATION_FLAG',lambda s:s.fillna('_').nunique()))
print(g.describe()); print((g.pg==g.n).mean(), (g.dt==1).mean(), (g.fl==1).mean())
fac=pd.read_csv('q06.csv',dtype=str)
print('fac rows', len(fac), 'unique pgm', fac.PGM_SYS_ID.nunique())
t2=t.merge(fac[['PGM_SYS_ID','STATE','AIR_POLLUTANT_CLASS_CODE','AIR_OPERATING_STATUS_CODE']],on='PGM_SYS_ID',how='left')
print('land in facilities', t2.STATE.notna().mean())
print('prefix==state', (t2.st==t2.STATE).mean())
t2['blank']=t2.FACILITY_RPT_DEVIATION_FLAG.isna()
r=t2[(t2.yr>=2020)&(t2.yr<=2025)]
s=r.groupby('STATE').agg(n=('blank','size'),blank=('blank','mean'),y=('FACILITY_RPT_DEVIATION_FLAG',lambda s:(s=='Y').sum()),nn=('FACILITY_RPT_DEVIATION_FLAG',lambda s:(s=='N').sum()),fac=('PGM_SYS_ID','nunique'))
s['y_rate']=s.y/(s.y+s.nn)
print(s.sort_values('n',ascending=False).round(3).to_string())
t2.to_pickle('t2.pkl')
