-- GHGRP emission: the whole table, slim, for local peer and time math (346,683 rows)
select EMISSION_RECORD_ID, FACILITY_ID, REPORTING_YEAR, SECTOR_ID, SUBSECTOR_ID, GAS_ID, CO2E_EMISSION
from LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_GHGRP_EMISSION
