-- GHGRP facility: every facility-year, slim, for names, industry, place and reporting status (136,005 rows)
select FACILITY_ID, REPORTING_YEAR, to_varchar(FRS_ID) FRS, FACILITY_NAME, PARENT_COMPANY, CITY, STATE, ZIP, COUNTY_FIPS, NAICS_CODE,
  FACILITY_TYPES, REPORTED_SUBPARTS, REPORTING_STATUS
from LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_GHGRP_FACILITY
