-- Title V certifications: the whole table, slim (499,113 rows), plus load lineage
select PGM_SYS_ID, ACTIVITY_ID, COMP_MONITOR_TYPE_CODE, STATE_EPA_FLAG, ACTUAL_END_DATE, FACILITY_RPT_DEVIATION_FLAG, _SOURCE_RUN_ID
from LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_TITLEV_CERTS
