-- ICIS-Air facilities: slim, for state, name, size class and status (279,728 rows)
select PGM_SYS_ID, to_varchar(REGISTRY_ID) REGISTRY_ID, FACILITY_NAME, CITY, STATE, ZIP_CODE, AIR_POLLUTANT_CLASS_CODE, AIR_OPERATING_STATUS_CODE,
  NAICS_CODES, SIC_CODES, FACILITY_TYPE_CODE, CURRENT_HPV, LOCAL_CONTROL_REGION_CODE
from LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_FACILITIES
