-- ICIS-Air programs: every facility's air programs, with status and dates (457,581 rows)
select PGM_SYS_ID, PROGRAM_CODE, AIR_OPERATING_STATUS_CODE, BEGIN_DATE, UPDATED_DATE
from LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_PROGRAMS
