-- ICIS-Air violation history: slim (102,037 rows)
select PGM_SYS_ID, ACTIVITY_ID, AGENCY_TYPE_DESC, STATE_CODE, ENF_RESPONSE_POLICY_CODE, PROGRAM_CODES, POLLUTANT_DESCS,
  EARLIEST_FRV_DETERM_DATE, HPV_DAYZERO_DATE, HPV_RESOLVED_DATE
from LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_VIOLATION_HISTORY
