-- ICIS-Air formal actions: slim (106,009 rows)
select PGM_SYS_ID, ACTIVITY_ID, ENF_IDENTIFIER, ACTIVITY_TYPE_CODE, STATE_EPA_FLAG, ENF_TYPE_CODE, SETTLEMENT_ENTERED_DATE, PENALTY_AMOUNT
from LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_FORMAL_ACTIONS
