-- ICIS-Air informal actions: slim (175,736 rows)
select PGM_SYS_ID, ACTIVITY_ID, STATE_EPA_FLAG, ENF_TYPE_CODE, ACHIEVED_DATE
from LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_INFORMAL_ACTIONS
