{{ config(tags=['spine_generated']) }}

-- GRAIN: one row per record (spine_entity not determined -- no registry hint available) (ID unique)
-- SPINE_ENTITY: (not determined)  (natural_key: ID)
-- Generated by scripts/generate_staging_models.py from SOURCE_REGISTRY -- deterministic,
-- no LLM.
-- CASTS: 8 of 61 columns, from landing_column_profile_2026-09-19.tsv. A column is cast only
-- when every filled value in the sample parsed. try_ casts: a value that does not
-- parse reads NULL. The natural key and join-key columns stay TEXT.
--   x: float
--   y: float
--   parcel_ida: integer
--   fid: ID: whole numbers, over 90% distinct -- stays TEXT, '.0' tail removed
--   addnumber: integer
--   elevation: integer
--   x2: float
--   y2: float
-- spine_entity not determined (grain/natural_key proven, but no registry hint says what this row is ABOUT) -- no SPINE_ENTITY_ID emitted.
-- landing table's ingestion timestamp is named INGESTED_AT (no leading underscore) rather than the usual _INGESTED_AT -- confirmed via INFORMATION_SCHEMA, not assumed.
-- DEDUPE: registry natural_key (ID) is NOT unique within a load as landed at generation time -- it would collapse 17,644 of 33,780 rows. Deduping on the WHOLE ROW instead (exact copies only). A record that changes between loads shows once per version. Find the real key, fix SOURCE_REGISTRY, regenerate.

with source as (

    select * from {{ source('ripple_raw', 'PORTAL_CKA_VIRGINIA_OPEN_DA_039AACD655') }}
    qualify row_number() over (partition by "X", "Y", "LABEL_FLD", "PARCEL_IDA", "ADD_ALIAS", "ADDRESS", "CITY", "FID", "DA_ID", "REGSOURCE", "DATEUPDATE", "EFFDATE", "EXPIREDATE", "SITEUNIQID", "COUNTRY", "STATE", "COUNTY", "ADDCODE", "ADDDATAURI", "INCORMUN", "UNINCORCOM", "NEIGHCOM", "ADDNUMPRE", "ADDNUMBER", "ADDNUMSUF", "STNPREMOD", "STNPREDIR", "STNPRETYP", "STNPTYSEP", "STNAME", "STNPOSTYP", "STNPOSDIR", "STNPOSMOD", "ESN", "MSAGCOM", "POSTALCOMN", "POSTALCODE", "ZIPPLUS4", "BUILDING", "FLOOR", "UNIT", "ROOM", "SEAT", "ADDLOCINFO", "COMPLANDN", "MILEPOST", "PLACETYPE", "PLMETHOD", "LONGITUDE", "LATITUDE", "ELEVATION", "LEGSTNPDIR", "LEGSTNAME", "LEGSTNPOTY", "LEGSTPODIR", "EXCEPTION", "ID", "STNUMBER", "STRUCTURE", "X2", "Y2" order by INGESTED_AT desc) = 1

),

renamed as (

    select
        {{ stg_float('"X"') }} as x,
        {{ stg_float('"Y"') }} as y,
        {{ null_junk('"LABEL_FLD"') }} as label_fld,
        {{ stg_int('"PARCEL_IDA"') }} as parcel_ida,
        {{ null_junk('"ADD_ALIAS"') }} as add_alias,
        {{ null_junk('"ADDRESS"') }} as address,
        {{ null_junk('"CITY"') }} as city,
        {{ stg_id_text('"FID"') }} as fid,
        {{ null_junk('"DA_ID"') }} as da_id,
        {{ null_junk('"REGSOURCE"') }} as regsource,
        {{ null_junk('"DATEUPDATE"') }} as dateupdate,
        {{ null_junk('"EFFDATE"') }} as effdate,
        {{ null_junk('"EXPIREDATE"') }} as expiredate,
        {{ null_junk('"SITEUNIQID"') }} as siteuniqid,
        {{ null_junk('"COUNTRY"') }} as country,
        {{ null_junk('"STATE"') }} as state,
        {{ null_junk('"COUNTY"') }} as county,
        {{ null_junk('"ADDCODE"') }} as addcode,
        {{ null_junk('"ADDDATAURI"') }} as adddatauri,
        {{ null_junk('"INCORMUN"') }} as incormun,
        {{ null_junk('"UNINCORCOM"') }} as unincorcom,
        {{ null_junk('"NEIGHCOM"') }} as neighcom,
        {{ null_junk('"ADDNUMPRE"') }} as addnumpre,
        {{ stg_int('"ADDNUMBER"') }} as addnumber,
        {{ null_junk('"ADDNUMSUF"') }} as addnumsuf,
        {{ null_junk('"STNPREMOD"') }} as stnpremod,
        {{ null_junk('"STNPREDIR"') }} as stnpredir,
        {{ null_junk('"STNPRETYP"') }} as stnpretyp,
        {{ null_junk('"STNPTYSEP"') }} as stnptysep,
        {{ null_junk('"STNAME"') }} as stname,
        {{ null_junk('"STNPOSTYP"') }} as stnpostyp,
        {{ null_junk('"STNPOSDIR"') }} as stnposdir,
        {{ null_junk('"STNPOSMOD"') }} as stnposmod,
        {{ null_junk('"ESN"') }} as esn,
        {{ null_junk('"MSAGCOM"') }} as msagcom,
        {{ null_junk('"POSTALCOMN"') }} as postalcomn,
        {{ null_junk('"POSTALCODE"') }} as postalcode,
        {{ null_junk('"ZIPPLUS4"') }} as zipplus4,
        {{ null_junk('"BUILDING"') }} as building,
        {{ null_junk('"FLOOR"') }} as floor,
        {{ null_junk('"UNIT"') }} as unit,
        {{ null_junk('"ROOM"') }} as room,
        {{ null_junk('"SEAT"') }} as seat,
        {{ null_junk('"ADDLOCINFO"') }} as addlocinfo,
        {{ null_junk('"COMPLANDN"') }} as complandn,
        {{ null_junk('"MILEPOST"') }} as milepost,
        {{ null_junk('"PLACETYPE"') }} as placetype,
        {{ null_junk('"PLMETHOD"') }} as plmethod,
        {{ null_junk('"LONGITUDE"') }} as longitude,
        {{ null_junk('"LATITUDE"') }} as latitude,
        {{ stg_int('"ELEVATION"') }} as elevation,
        {{ null_junk('"LEGSTNPDIR"') }} as legstnpdir,
        {{ null_junk('"LEGSTNAME"') }} as legstname,
        {{ null_junk('"LEGSTNPOTY"') }} as legstnpoty,
        {{ null_junk('"LEGSTPODIR"') }} as legstpodir,
        {{ null_junk('"EXCEPTION"') }} as exception,
        {{ null_junk('"ID"') }} as id,
        {{ null_junk('"STNUMBER"') }} as stnumber,
        {{ null_junk('"STRUCTURE"') }} as structure,
        {{ stg_float('"X2"') }} as x2,
        {{ stg_float('"Y2"') }} as y2,
        INGESTED_AT as _loaded_at,
        'https://data.virginia.gov/dataset/addresses2' as _source_url

    from source

)

select * from renamed
