-- Eyeball the 11 still-ISSUED foreign subsidiaries: the ownership link records themselves, plus registry numbers (Sistema Asia vs the SDN's 201218988Z)
with k as (select column1 lei from values ('5299007PQV6X4DPL9Y20'),('K80PJMCDA9MAE5C8IO91'),('213800FXBZXOXNXKWP95'),('391200PKEUF3Y2NUMW25'),
   ('72450024EGZK2K8NAG02'),('724500LG1GUKJ5TOIW61'),('724500UTYUSS56QEBB66'),('724500IVNQ6LF8OFIO42'),('7872006AZAFVTVIQ3G32'),
   ('254900YJTZ2JT3ZSZS32'),('253400QD4JHES5PGDR15'))
select k.lei, g.ENTITY_LEGALNAME, g.ENTITY_LEGALADDRESS_CITY, g.ENTITY_REGISTRATIONAUTHORITY_REGISTRATIONAUTHORITYENTITYID reg_no,
  g.ENTITY_ENTITYSTATUS, g.REGISTRATION_INITIALREGISTRATIONDATE::text first_reg, g.REGISTRATION_VALIDATIONSOURCES,
  r.RELATIONSHIP_RELATIONSHIPTYPE, r.RELATIONSHIP_RELATIONSHIPSTATUS, r.REGISTRATION_REGISTRATIONSTATUS rel_rst,
  r.REGISTRATION_LASTUPDATEDATE::text rel_lupd, r.REGISTRATION_VALIDATIONSOURCES rel_valid, r.RELATIONSHIP_QUANTIFIERS_1_QUANTIFIERAMOUNT pct,
  r.RELATIONSHIP_PERIOD_1_STARTDATE::text p1_start, r.RELATIONSHIP_ENDNODE_NODEID parent
from k left join LIBRARY_MARTS.ECONOMICS.ECONOMICS__INTL_GLEIF g on g.LEI = k.lei
left join LIBRARY_MARTS.ECONOMICS.ECONOMICS__INTL_GLEIF_RELATIONSHIPS r on r.RELATIONSHIP_STARTNODE_NODEID = k.lei
order by 1, r.RELATIONSHIP_RELATIONSHIPTYPE
