{{ config(materialized='view', schema='JUSTICE') }}

-- Source: FED_COURTLISTENER_DOCKETS (71677647 rows)
-- Generated by scripts/gen_mart_models.py
--
-- Materialized as a VIEW: this is a straight passthrough of a 71,677,647-row
-- landing table, so a physical copy would pay twice for the same bytes without
-- precomputing any join, filter, or aggregation.

with source as (
    select * from {{ source('ripple_raw', 'FED_COURTLISTENER_DOCKETS') }}
)

select
    ID as id,
    try_to_date(DATE_CREATED) as date_created,
    try_to_date(DATE_MODIFIED) as date_modified,
    SOURCE as source,
    APPEAL_FROM_STR as appeal_from_str,
    ASSIGNED_TO_STR as assigned_to_str,
    REFERRED_TO_STR as referred_to_str,
    PANEL_STR as panel_str,
    try_to_date(DATE_LAST_INDEX) as date_last_index,
    try_to_date(DATE_CERT_GRANTED) as date_cert_granted,
    try_to_date(DATE_CERT_DENIED) as date_cert_denied,
    try_to_date(DATE_ARGUED) as date_argued,
    try_to_date(DATE_REARGUED) as date_reargued,
    try_to_date(DATE_REARGUMENT_DENIED) as date_reargument_denied,
    try_to_date(DATE_FILED) as date_filed,
    try_to_date(DATE_TERMINATED) as date_terminated,
    try_to_date(DATE_LAST_FILING) as date_last_filing,
    CASE_NAME_SHORT as case_name_short,
    CASE_NAME as case_name,
    CASE_NAME_FULL as case_name_full,
    SLUG as slug,
    DOCKET_NUMBER as docket_number,
    DOCKET_NUMBER_CORE as docket_number_core,
    PACER_CASE_ID as pacer_case_id,
    CAUSE as cause,
    NATURE_OF_SUIT as nature_of_suit,
    JURY_DEMAND as jury_demand,
    JURISDICTION_TYPE as jurisdiction_type,
    APPELLATE_FEE_STATUS as appellate_fee_status,
    APPELLATE_CASE_TYPE_INFORMATION as appellate_case_type_information,
    MDL_STATUS as mdl_status,
    FILEPATH_LOCAL as filepath_local,
    FILEPATH_IA as filepath_ia,
    FILEPATH_IA_JSON as filepath_ia_json,
    try_to_number(IA_UPLOAD_FAILURE_COUNT) as ia_upload_failure_count,
    IA_NEEDS_UPLOAD as ia_needs_upload,
    try_to_date(IA_DATE_FIRST_CHANGE) as ia_date_first_change,
    try_to_number(VIEW_COUNT) as view_count,
    try_to_date(DATE_BLOCKED) as date_blocked,
    BLOCKED as blocked,
    APPEAL_FROM_ID as appeal_from_id,
    ASSIGNED_TO_ID as assigned_to_id,
    COURT_ID as court_id,
    IDB_DATA_ID as idb_data_id,
    ORIGINATING_COURT_INFORMATION_ID as originating_court_information_id,
    REFERRED_TO_ID as referred_to_id,
    FEDERAL_DN_CASE_TYPE as federal_dn_case_type,
    FEDERAL_DN_OFFICE_CODE as federal_dn_office_code,
    FEDERAL_DN_JUDGE_INITIALS_ASSIGNED as federal_dn_judge_initials_assigned,
    FEDERAL_DN_JUDGE_INITIALS_REFERRED as federal_dn_judge_initials_referred,
    FEDERAL_DEFENDANT_NUMBER as federal_defendant_number,
    PARENT_DOCKET_ID as parent_docket_id,
    DOCKET_NUMBER_RAW as docket_number_raw,
    DOCKET_NUMBER_SOURCE as docket_number_source
from source
