{{ config(materialized='table', schema='JUSTICE') }}

-- Source: FED_COURTLISTENER_SCHOOLS (6011 rows)
-- Generated by scripts/gen_mart_models.py
-- Fixed 2026-09-20: bare try_to_date() casts replaced in place with the
-- project's guarded stg_date macro (macros/staging_casts.sql) -- a value that
-- doesn't parse cleanly now reads NULL instead of a silent epoch-seconds
-- misread. No matching staging model exists for this landing table, so kept
-- on source().

with source as (
    select * from {{ source('ripple_raw', 'FED_COURTLISTENER_SCHOOLS') }}
)

select
    ID as id,
    {{ stg_date('DATE_CREATED') }} as date_created,
    {{ stg_date('DATE_MODIFIED') }} as date_modified,
    NAME as name,
    EIN as ein,
    IS_ALIAS_OF_ID as is_alias_of_id
from source
