{{ config(materialized='table', schema='JUSTICE') }}

-- Source: FED_COURTLISTENER_DISCLOSURE_AGREEMENTS (10007 rows)
-- Generated by scripts/gen_mart_models.py
-- Fixed 2026-09-20: DATE_CREATED/DATE_MODIFIED were bare try_to_date() casts,
-- replaced in place with the guarded stg_date macro (macros/staging_casts.sql)
-- -- a value that doesn't parse cleanly now reads NULL instead of a silent
-- epoch-seconds misread. DATE_RAW below is untouched: already known bad (see
-- comment) and deliberately kept as text. No matching staging model exists
-- for this landing table, so kept on source().

with source as (
    select * from {{ source('ripple_raw', 'FED_COURTLISTENER_DISCLOSURE_AGREEMENTS') }}
)

select
    ID as id,
    {{ stg_date('DATE_CREATED') }} as date_created,
    {{ stg_date('DATE_MODIFIED') }} as date_modified,
    -- BUG FIXED 2026-08-18 (epoch-1970 investigation): DATE_RAW is
    -- CourtListener's as-extracted OCR text off scanned financial-disclosure
    -- PDFs (confirmed live samples: 'See VIII', "'84-presnt", '1987-2002',
    -- '2.10/74', bare years like '2003') -- not a clean date. Same generator
    -- miss repeated across the whole CourtListener disclosure family. A bare
    -- try_to_date() epoch-mangled 6,016 of 10,007 rows (60%). Pass through as
    -- text; it was never meant to be parsed.
    DATE_RAW as date_raw,
    PARTIES_AND_TERMS as parties_and_terms,
    REDACTED as redacted,
    FINANCIAL_DISCLOSURE_ID as financial_disclosure_id
from source
