{{ config(materialized='table', schema='JUSTICE') }}

-- Source: FED_COURTLISTENER_DISCLOSURE_GIFTS (2025 rows)
-- Generated by scripts/gen_mart_models.py

with source as (
    select * from {{ source('ripple_raw', 'FED_COURTLISTENER_DISCLOSURE_GIFTS') }}
)

select
    ID as id,
    try_to_date(DATE_CREATED) as date_created,
    try_to_date(DATE_MODIFIED) as date_modified,
    SOURCE as source,
    DESCRIPTION as description,
    "VALUE" as value_col,
    REDACTED as redacted,
    FINANCIAL_DISCLOSURE_ID as financial_disclosure_id
from source
