{{ config(materialized='table', schema='JUSTICE') }}

-- Source: FATF Consolidated Assessment Ratings (200 rows)
-- Generated by gen_mart_models.py

with source as (
    select * from {{ source('ripple_raw', 'INTL_FATF_RATINGS') }}
)

select
    COUNTRY as country,
    FATF_RECOMMENDATION as fatf_recommendation,
    RATING as rating,
    EVALUATION_ROUND as evaluation_round,
    EVALUATION_YEAR as evaluation_year,
    DIMENSION as dimension,
    ASSESSMENT_BODY as assessment_body
from source
