{{ config(materialized='table', schema='JUSTICE') }}

-- Source: FED_COURTLISTENER_FINANCIAL_DISCLOSURES (66287 rows)
-- Generated by scripts/gen_mart_models.py

-- DEDUP (2026-08-11 verification): ID is the real primary key (66,286 distinct
-- vs 66,287 landing rows). Confirm query showed a SINGLE load run, so this is
-- single-load duplication, not appends; latest ingest per ID is kept.
-- (This landing's metadata columns are INGESTED_AT/SOURCE_RUN_ID, no underscore.)
with source as (
    select * from {{ source('ripple_raw', 'FED_COURTLISTENER_FINANCIAL_DISCLOSURES') }}
    qualify row_number() over (partition by ID order by INGESTED_AT desc,
             -- tie-breakers 2026-09-18: the row's own values, so the same row wins every run
             DATE_CREATED nulls last, DATE_MODIFIED nulls last, "YEAR" nulls last,
             DOWNLOAD_FILEPATH nulls last, FILEPATH nulls last, THUMBNAIL nulls last,
             THUMBNAIL_STATUS nulls last, PAGE_COUNT nulls last, SHA1 nulls last, REPORT_TYPE nulls last,
             IS_AMENDED nulls last, ADDENDUM_CONTENT_RAW nulls last, ADDENDUM_REDACTED nulls last,
             HAS_BEEN_EXTRACTED nulls last, PERSON_ID nulls last
) = 1
)

select
    ID as id,
    try_to_date(DATE_CREATED) as date_created,
    try_to_date(DATE_MODIFIED) as date_modified,
    try_to_number("YEAR") as year_col,
    DOWNLOAD_FILEPATH as download_filepath,
    FILEPATH as filepath,
    THUMBNAIL as thumbnail,
    THUMBNAIL_STATUS as thumbnail_status,
    try_to_number(PAGE_COUNT) as page_count,
    SHA1 as sha1,
    REPORT_TYPE as report_type,
    IS_AMENDED as is_amended,
    ADDENDUM_CONTENT_RAW as addendum_content_raw,
    ADDENDUM_REDACTED as addendum_redacted,
    HAS_BEEN_EXTRACTED as has_been_extracted,
    PERSON_ID as person_id
from source
