{{ config(materialized='table', schema='JUSTICE') }}

-- Source: FED_COURTLISTENER_DISCLOSURE_NON_INVESTMENT_INCOME (15302 rows)
-- Generated by scripts/gen_mart_models.py

with source as (
    select * from {{ source('ripple_raw', 'FED_COURTLISTENER_DISCLOSURE_NON_INVESTMENT_INCOME') }}
)

select
    ID as id,
    try_to_date(DATE_CREATED) as date_created,
    try_to_date(DATE_MODIFIED) as date_modified,
    try_to_date(DATE_RAW) as date_raw,
    SOURCE_TYPE as source_type,
    try_to_double(INCOME_AMOUNT) as income_amount,
    REDACTED as redacted,
    FINANCIAL_DISCLOSURE_ID as financial_disclosure_id
from source
