{{ config(tags=['spine_generated']) }}

-- GRAIN: one row per filing (AMEND_ID+ENTITY_ID+FILING_ID+TRAN_ID unique)
-- SPINE_ENTITY: filing  (natural_key: AMEND_ID, ENTITY_ID, FILING_ID, TRAN_ID)
-- Generated by scripts/generate_staging_models.py from SOURCE_REGISTRY -- deterministic,
-- no LLM.
-- CASTS: 1 of 13 columns, from landing_column_profile_2026-09-19.tsv. A column is cast only
-- when every filled value in the sample parsed. try_ casts: a value that does not
-- parse reads NULL. The natural key and join-key columns stay TEXT.
--   line_item: integer
-- spine_entity 'filing' has no connect/ resolver yet (see connect/spine_entity.py) -- no SPINE_ENTITY_ID emitted.
-- landing table's ingestion timestamp is named INGESTED_AT (no leading underscore) rather than the usual _INGESTED_AT -- confirmed via INFORMATION_SCHEMA, not assumed.

with source as (

    select * from {{ source('ripple_raw', 'CA_LOBBY_COVER2') }}
    qualify row_number() over (partition by "AMEND_ID", "ENTITY_ID", "FILING_ID", "TRAN_ID" order by INGESTED_AT desc) = 1

),

renamed as (

    select
        {{ null_junk('"AMEND_ID"') }} as amend_id,
        {{ null_junk('"ENTITY_CD"') }} as entity_cd,
        {{ null_junk('"ENTITY_ID"') }} as entity_id,
        {{ null_junk('"ENTY_NAMF"') }} as enty_namf,
        {{ null_junk('"ENTY_NAML"') }} as enty_naml,
        {{ null_junk('"ENTY_NAMS"') }} as enty_nams,
        {{ null_junk('"ENTY_NAMT"') }} as enty_namt,
        {{ null_junk('"ENTY_TITLE"') }} as enty_title,
        {{ null_junk('"FILING_ID"') }} as filing_id,
        {{ null_junk('"FORM_TYPE"') }} as form_type,
        {{ stg_int('"LINE_ITEM"') }} as line_item,
        {{ null_junk('"REC_TYPE"') }} as rec_type,
        {{ null_junk('"TRAN_ID"') }} as tran_id,
        INGESTED_AT as _loaded_at,
        'https://www.sos.ca.gov/campaign-lobbying/cal-access-resources/raw-data-campaign-finance-and-lobbying-activity' as _source_url

    from source

)

select * from renamed
