{{ config(tags=['minimal_staging']) }}

-- GRAIN: NOT YET DETERMINED (profiler returned AMBIGUOUS -- needs manual review)
-- This is a passthrough staging view: snake_case rename only, no dedup.
-- Once grain is resolved, replace with a full staging model via generate_staging_models.py.
-- Generated by scripts/generate_minimal_staging.py

with source as (

    select * from {{ source('ripple_raw', 'FED_DOT_BTS') }}

),

renamed as (

    select
        DATABASE_NAME as database_name,
        DESCRIPTION as description,
        PROFILE_URL as profile_url,
        MODE as mode,
        SUBJECT as subject,
        YEAR as year,
        MONTH as month,
        CARRIER_CODE as carrier_code,
        ORIGIN as origin,
        DEST as dest,
        STATE_FIPS as state_fips,
        COUNTY_FIPS as county_fips,
        _INGESTED_AT as _loaded_at,
        'https://www.transtats.bts.gov/DataIndex.asp' as _source_url

    from source

)

select * from renamed
