"""Curated brand-dictionary pass: verified pattern -> LEI pairs only. No DDL."""
import sys
sys.path.insert(0, r"c:\Code\Ripple_v6")
from scripts._snowflake_conn import connect

L = "LIBRARY_RAW.LANDING"
NORM = "TRIM(REGEXP_REPLACE(REGEXP_REPLACE(UPPER({c}), '[^A-Z0-9 ]', ' '), ' +', ' '))"

# (facility-name pattern, LEI, legal name) — every LEI verified by name lookup this session
DICT = [
 ("CON EDISON%","54930033SBW53OO8T749","CONSOLIDATED EDISON, INC."),
 ("CONSOLIDATED EDISON%","54930033SBW53OO8T749","CONSOLIDATED EDISON, INC."),
 ("CVS %","549300EJG376EN5NQE29","CVS HEALTH CORPORATION"),
 ("VERIZON %","2S72QS2UO2OESLG6Y829","VERIZON COMMUNICATIONS INC."),
 ("AT T %","549300Z40J86GGSTL398","AT&T INC."),
 ("NEW CINGULAR%","549300Z40J86GGSTL398","AT&T INC."),
 ("PACIFIC BELL%","549300Z40J86GGSTL398","AT&T INC."),
 ("DOLLAR GENERAL%","OPX52SQVOZI8IVSWYU66","DOLLAR GENERAL CORPORATION"),
 ("7 ELEVEN%","549300K23JPL0SS3LB18","7-Eleven, Inc."),
 ("DOLLAR TREE%","549300PMSTQITB1WHR43","DOLLAR TREE, INC."),
 ("FAMILY DOLLAR%","549300PMSTQITB1WHR43","DOLLAR TREE, INC."),
 ("CIRCLE K%","549300TM4PEF0BWPGP66","CIRCLE K STORES INC."),
 ("RITE AID%","529900W353T1JY1DKT44","Rite Aid Corporation"),
 ("SUNOCO%","54930001NJU8E40NQ561","SUNOCO LP"),
 ("PG E %","1HNPXZSMMB7HMBMVBS46","PACIFIC GAS AND ELECTRIC COMPANY"),
 ("PACIFIC GAS AND ELECTRIC%","1HNPXZSMMB7HMBMVBS46","PACIFIC GAS AND ELECTRIC COMPANY"),
 ("SHERWIN WILLIAMS%","Z15BMIOX8DDH0X2OBP21","THE SHERWIN-WILLIAMS COMPANY"),
 ("WALMART%","Y87794H0US1R65VBXU25","WALMART INC."),
 ("WAL MART%","Y87794H0US1R65VBXU25","WALMART INC."),
 ("HOME DEPOT%","549300FEMQDH6Q0NT330","HOME DEPOT U.S.A., INC."),
 ("EXXON%","549300NCY2P2FLJT9D42","EXXONMOBIL OIL CORPORATION"),
 ("MOBIL OIL%","549300NCY2P2FLJT9D42","EXXONMOBIL OIL CORPORATION"),
 ("TARGET STORE%","8WDDFXB5T1Z6J0XC1L66","Target Corporation"),
 ("O REILLY%","549300K2RLMQL149Q332","O'Reilly Automotive, Inc."),
 ("SHELL OIL%","549300UYFI41EIQ10304","SHELL USA, INC."),
 ("SHELL SERVICE%","549300UYFI41EIQ10304","SHELL USA, INC."),
 ("CHEVRON%","VA8TZDWPEZYU430RZ444","Chevron U.S.A. Inc."),
 ("WALGREEN%","E1OI0SEUGJMPPTKRDD35","WALGREEN CO."),
 ("KROGER%","6CPEOKI6OYJ13Q6O7870","THE KROGER CO."),
 ("SAFEWAY%","549300NKZ6VCN5P3K723","Safeway Inc."),
 ("COSTCO%","29DX7H14B9S6O3FD6V18","COSTCO WHOLESALE CORPORATION"),
 ("LOWE S %","WAFCR4OKGSC504WU3E95","Lowe's Companies, Inc."),
 ("MARATHON PETROLEUM%","LXLW0PTYO5MW106BXC85","MARATHON PETROLEUM COMPANY LP"),
 ("VALERO%","549300XTO5VR8SKV1V74","VALERO ENERGY CORPORATION"),
 ("PHILLIPS 66%","5493005JBO5YSIGK1814","PHILLIPS 66"),
 ("DUKE ENERGY%","I1BZKREC126H0VB1BL91","DUKE ENERGY CORPORATION"),
 ("UNION PACIFIC%","549300E5Y4M86FFRWP82","UNION PACIFIC RAILROAD COMPANY"),
 ("CSX %","549300JVQR4N1MMP3Q88","CSX Corporation"),
 ("NORFOLK SOUTHERN%","54930036C8MWP850MI84","Norfolk Southern Corporation"),
 ("MCDONALD S%","UE2136O97NLB5BYP9H04","MCDONALD'S CORPORATION"),
 ("BP PRODUCTS%","549300YYMNSW7KWZH127","BP PRODUCTS NORTH AMERICA INC."),
 ("BP AMOCO%","549300YYMNSW7KWZH127","BP PRODUCTS NORTH AMERICA INC."),
 ("AUTOZONE%","GA3JGKJ41LJKXDN23E90","AutoZone, Inc."),
 ("TRACTOR SUPPLY%","549300OJ9VZHZRO6I137","TRACTOR SUPPLY COMPANY"),
 ("WASTE MANAGEMENT%","549300YX8JIID70NFS41","WASTE MANAGEMENT, INC."),
 ("REPUBLIC SERVICES%","NKNQHM6BLECKVOQP7O46","REPUBLIC SERVICES, INC."),
 ("KINDER MORGAN%","549300WR7IX8XE0TBO16","KINDER MORGAN, INC."),
 ("ENTERPRISE PRODUCTS%","K4CDIF4M54DJZ6TB4Q48","ENTERPRISE PRODUCTS PARTNERS L.P."),
 ("DOMINION ENERGY%","ILUL7B6Z54MRYCF6H308","Dominion Energy, Inc."),
 ("AMERICAN ELECTRIC POWER%","1B4S6S7G0TW5EE83BO58","AMERICAN ELECTRIC POWER COMPANY, INC."),
 ("EXELON%","3SOUA6IRML7435B56G12","EXELON CORPORATION"),
 ("XCEL ENERGY%","LGJNMI9GH8XIDG5RCM61","Xcel Energy Inc."),
 ("SOUTHERN CALIFORNIA EDISON%","9R1Z5I36FERIBVKW4P77","SOUTHERN CALIFORNIA EDISON COMPANY"),
 ("COMMONWEALTH EDISON%","D8YOXB8L2ZDC8P7Q0771","COMMONWEALTH EDISON COMPANY"),
 ("FLORIDA POWER%","A89MY1K3YLIGJMYWVX50","FLORIDA POWER & LIGHT COMPANY"),
 ("GEORGIA POWER%","D981X4Z4RWS7PDMJUZ03","GEORGIA POWER COMPANY"),
 ("DTE ENERGY%","549300IX8SD6XXD71I78","DTE ENERGY COMPANY"),
 ("CONSUMERS ENERGY%","7NKTFWJ1G6MELP9TU740","CONSUMERS ENERGY COMPANY"),
 ("AMEREN%","XRZQ5S7HYJFPHJ78L959","AMEREN CORPORATION"),
 ("ENTERGY%","4XM3TW50JULSLG8BNC79","ENTERGY CORPORATION"),
 ("FIRSTENERGY%","549300SVYJS666PQJH88","FIRSTENERGY CORP."),
 ("PUBLIC SERVICE ELECTRIC%","549300RUHPVD434XUK18","PUBLIC SERVICE ELECTRIC AND GAS COMPANY"),
 ("PSE G%","549300RUHPVD434XUK18","PUBLIC SERVICE ELECTRIC AND GAS COMPANY"),
 ("APPALACHIAN POWER%","3SCHO1ABYYIG382BEI70","Appalachian Power Company"),
 ("NOBLE ENERGY%","02VFQXG2D1LR5ZH3K186","NOBLE ENERGY, INC."),
 ("NEXTERA%","254900RHL9MEUS5NKX63","NextEra Energy, Inc."),
 ("VERIZON WIRELESS%","2S72QS2UO2OESLG6Y829","VERIZON COMMUNICATIONS INC."),
]

vals = ",\n".join("('%s','%s','%s')" % (p, lei, name.replace("'", "''")) for p, lei, name in DICT)

UPDATE = f"""
UPDATE {L}.XC_EPA_CORPORATE_CROSSWALK x
SET MATCHED_LEI = m.LEI, MATCHED_LEGAL_NAME = m.LEGAL_NAME,
    MATCH_METHOD = 'brand', MATCH_CONFIDENCE = 0.85,
    PARENT_LEGAL_NAME = m.LEGAL_NAME,
    REVIEW_FLAG = FALSE, _SOURCE_RUN_ID = 'xc-v2-cur'
FROM (
  SELECT EPA_REGISTRY_ID, LEI, LEGAL_NAME FROM (
    SELECT f.REGISTRY_ID AS EPA_REGISTRY_ID, d.LEI, d.LEGAL_NAME,
           ROW_NUMBER() OVER (PARTITION BY f.REGISTRY_ID ORDER BY LENGTH(d.PAT) DESC) AS RN
    FROM {L}.FED_EPA_FRS_FULL f
    JOIN (SELECT column1 AS PAT, column2 AS LEI, column3 AS LEGAL_NAME FROM VALUES {vals}) d
      ON {NORM.format(c='f.PRIMARY_NAME')} LIKE d.PAT
  ) WHERE RN = 1
) m
WHERE x.EPA_REGISTRY_ID = m.EPA_REGISTRY_ID AND x.MATCHED_LEI IS NULL
"""

FILL_PARENT = f"""
UPDATE {L}.XC_EPA_CORPORATE_CROSSWALK x
SET ULTIMATE_PARENT_LEI = pn.PARENT_LEI,
    PARENT_LEGAL_NAME = COALESCE(pn.PARENT_LEGAL_NAME, x.PARENT_LEGAL_NAME)
FROM (
  SELECT CHILD_LEI, PARENT_LEI, PARENT_LEGAL_NAME FROM (
    SELECT r.RELATIONSHIP_STARTNODE_NODEID AS CHILD_LEI,
           r.RELATIONSHIP_ENDNODE_NODEID AS PARENT_LEI,
           g."Entity.LegalName" AS PARENT_LEGAL_NAME,
           ROW_NUMBER() OVER (PARTITION BY r.RELATIONSHIP_STARTNODE_NODEID
                              ORDER BY r.RELATIONSHIP_PERIOD_1_STARTDATE DESC NULLS LAST) AS RN
    FROM {L}.INTL_GLEIF_RELATIONSHIPS r
    LEFT JOIN {L}.INTL_GLEIF g ON g."LEI" = r.RELATIONSHIP_ENDNODE_NODEID
    WHERE r.RELATIONSHIP_RELATIONSHIPTYPE = 'IS_ULTIMATELY_CONSOLIDATED_BY'
      AND r.RELATIONSHIP_RELATIONSHIPSTATUS = 'ACTIVE'
  ) WHERE RN = 1
) pn
WHERE x._SOURCE_RUN_ID = 'xc-v2-cur' AND x.MATCHED_LEI = pn.CHILD_LEI
"""

FILL_CIK = f"""
UPDATE {L}.XC_EPA_CORPORATE_CROSSWALK x
SET PARENT_CIK = ed.CIK
FROM (
  SELECT {NORM.format(c='TITLE')} AS NAME_NORM, MIN(CIK_STR) AS CIK
  FROM {L}.FED_SEC_EDGAR_COMPANY_TICKERS
  GROUP BY 1 HAVING COUNT(DISTINCT CIK_STR) = 1
) ed
WHERE x._SOURCE_RUN_ID = 'xc-v2-cur' AND x.PARENT_CIK IS NULL
  AND ed.NAME_NORM = {NORM.format(c='COALESCE(x.PARENT_LEGAL_NAME, x.MATCHED_LEGAL_NAME)')}
"""

conn = connect(); cur = conn.cursor()
cur.execute(UPDATE); print("brand rows matched:", cur.rowcount)
cur.execute(FILL_PARENT); print("parents filled:", cur.rowcount)
cur.execute(FILL_CIK); print("ciks filled:", cur.rowcount)
cur.execute(f"""SELECT COUNT(*), COUNT(MATCHED_LEI), COUNT(ULTIMATE_PARENT_LEI), COUNT(PARENT_CIK)
FROM {L}.XC_EPA_CORPORATE_CROSSWALK""")
t, lei, up, cik = cur.fetchone()
print(f"facilities={t:,} lei_matched={lei:,} ({lei/t:.1%}) ult_parent={up:,} cik={cik:,}")
cur.execute(f"""SELECT MATCHED_LEGAL_NAME, COUNT(*) FROM {L}.XC_EPA_CORPORATE_CROSSWALK
WHERE _SOURCE_RUN_ID='xc-v2-cur' GROUP BY 1 ORDER BY 2 DESC LIMIT 15""")
for r in cur.fetchall(): print("  ", r[0], "|", r[1])
conn.close()
