-- HHA eyeball: the one HHA NPI that matched the OIG exclusion list, both names side by side
select h.NPI, h.ORGANIZATION_NAME, h.DOING_BUSINESS_AS_NAME, h.CITY, h.STATE, h.ENROLLMENT_ID, l.BUSINESS_NAME, l.LAST_NAME, l.FIRST_NAME, l.GENERAL_CATEGORY, l.SPECIALTY,
  l.EXCLUSION_TYPE, l.EXCLUSION_DATE, l.CITY lcity, l.STATE lstate
from LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_HOME_HEALTH_AGENCY_ENROLLMENTS h
join LIBRARY_MARTS.HEALTH.HEALTH__FED_HHS_OIG_LEIE l on trim(l.NPI)=trim(h.NPI) and l.NPI_IS_REAL
