{{ config(tags=['spine_generated']) }}

-- GRAIN: one row per place (ZIP+VAL_DATE unique)
-- SPINE_ENTITY: place  (natural_key: ZIP, VAL_DATE)
-- Generated by scripts/generate_staging_models.py from SOURCE_REGISTRY -- deterministic,
-- no LLM.
-- CASTS: 12 of 33 columns, from landing_column_profile_2026-09-19.tsv. A column is cast only
-- when every filled value in the sample parsed. try_ casts: a value that does not
-- parse reads NULL. The natural key and join-key columns stay TEXT.
--   objectid: ID: whole numbers, over 90% distinct -- stays TEXT, '.0' tail removed
--   ncesid: ID: whole numbers, over 90% distinct -- stays TEXT, '.0' tail removed
--   zip4: ID: whole numbers, over 90% distinct -- stays TEXT, '.0' tail removed
--   type: integer
--   status: integer
--   population: ID: whole numbers, over 90% distinct -- stays TEXT, '.0' tail removed
--   countyfips: integer
--   source_dat: integer
--   enrollment: ID: whole numbers, over 90% distinct -- stays TEXT, '.0' tail removed
--   end_grade: integer
--   districtid: integer
--   ft_teacher: integer
-- spine_entity 'place' has no connect/ resolver yet (see connect/spine_entity.py) -- no SPINE_ENTITY_ID emitted.
-- landing table's ingestion timestamp is named INGESTED_AT (no leading underscore) rather than the usual _INGESTED_AT -- confirmed via INFORMATION_SCHEMA, not assumed.
-- DEDUPE: registry natural_key (ZIP, VAL_DATE) is NOT unique within a load as landed at generation time -- it would collapse 1 of 55 rows. Deduping on the WHOLE ROW instead (exact copies only). A record that changes between loads shows once per version. Find the real key, fix SOURCE_REGISTRY, regenerate.

with source as (

    select * from {{ source('ripple_raw', 'PORTAL_ARC_HARRIS_COUNTY_OP_1966AC023B') }}
    qualify row_number() over (partition by "OBJECTID", "NCESID", "NAME", "ADDRESS", "CITY", "STATE", "ZIP", "ZIP4", "TELEPHONE", "TYPE", "STATUS", "POPULATION", "COUNTY", "COUNTYFIPS", "COUNTRY", "LATITUDE", "LONGITUDE", "NAICS_CODE", "NAICS_DESC", "SOURCE", "SOURCE_DAT", "VAL_METHOD", "VAL_DATE", "WEBSITE", "LEVEL", "ENROLLMENT", "ST_GRADE", "END_GRADE", "DISTRICTID", "FT_TEACHER", "SHELTER_ID", "VAILD", "GEOMETRY" order by INGESTED_AT desc) = 1

),

renamed as (

    select
        {{ stg_id_text('"OBJECTID"') }} as objectid,
        {{ stg_id_text('"NCESID"') }} as ncesid,
        {{ null_junk('"NAME"') }} as name,
        {{ null_junk('"ADDRESS"') }} as address,
        {{ null_junk('"CITY"') }} as city,
        {{ null_junk('"STATE"') }} as state,
        {{ null_junk('"ZIP"') }} as zip,
        {{ stg_id_text('"ZIP4"') }} as zip4,
        {{ null_junk('"TELEPHONE"') }} as telephone,
        {{ stg_int('"TYPE"') }} as type,
        {{ stg_int('"STATUS"') }} as status,
        {{ stg_id_text('"POPULATION"') }} as population,
        {{ null_junk('"COUNTY"') }} as county,
        {{ stg_int('"COUNTYFIPS"') }} as countyfips,
        {{ null_junk('"COUNTRY"') }} as country,
        {{ null_junk('"LATITUDE"') }} as latitude,
        {{ null_junk('"LONGITUDE"') }} as longitude,
        {{ null_junk('"NAICS_CODE"') }} as naics_code,
        {{ null_junk('"NAICS_DESC"') }} as naics_desc,
        {{ null_junk('"SOURCE"') }} as source,
        {{ stg_int('"SOURCE_DAT"') }} as source_dat,
        {{ null_junk('"VAL_METHOD"') }} as val_method,
        {{ null_junk('"VAL_DATE"') }} as val_date,
        {{ null_junk('"WEBSITE"') }} as website,
        {{ null_junk('"LEVEL"') }} as level,
        {{ stg_id_text('"ENROLLMENT"') }} as enrollment,
        {{ null_junk('"ST_GRADE"') }} as st_grade,
        {{ stg_int('"END_GRADE"') }} as end_grade,
        {{ stg_int('"DISTRICTID"') }} as districtid,
        {{ stg_int('"FT_TEACHER"') }} as ft_teacher,
        {{ null_junk('"SHELTER_ID"') }} as shelter_id,
        {{ null_junk('"VAILD"') }} as vaild,
        {{ null_junk('"GEOMETRY"') }} as geometry,
        INGESTED_AT as _loaded_at,
        'https://geo-harriscounty.opendata.arcgis.com/datasets/6bb905559d7e41db86cacee9aabefa8d_0' as _source_url

    from source

)

select * from renamed
