"""Skeptic runner, read-only. SELECT/WITH only. Tag deep3-skeptic-2026-09-24."""
import csv, sys, re
from pathlib import Path
HERE = Path(__file__).resolve().parent
REPO = HERE.parents[4]
sys.path.insert(0, str(REPO))
from connect import db

R2 = "LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_USASPENDING_CONTRACTS_FULL_R2"
KEYS6 = ["CONT_AWD_HC102824F1207_9700_N6600119A0120_9700","CONT_AWD_HC108423F0136_9700_NNG15SD80B_8000",
         "CONT_AWD_HC108424F0217_9700_NNG15SD80B_8000","CONT_AWD_HC108425F0061_9700_NNG15SD80B_8000",
         "CONT_AWD_HC108425F0096_9700_NNG15SD80B_8000","CONT_AWD_HC108425F0287_9700_N6600119A0120_9700"]
inlist = ",".join("'%s'" % k for k in KEYS6)
Q = {
 "K1": "SELECT * FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_CISA_KEV",
 "K2": f"SELECT * FROM {R2} WHERE CONTRACT_AWARD_UNIQUE_KEY IN ({inlist}) ORDER BY CONTRACT_AWARD_UNIQUE_KEY, ACTION_DATE",
 "K3": f"""WITH x AS (SELECT CONTRACT_AWARD_UNIQUE_KEY, AWARD_ID_PIID, ACTION_DATE, FEDERAL_ACTION_OBLIGATION, AWARDING_AGENCY_NAME,
        AWARDING_SUB_AGENCY_NAME, RECIPIENT_NAME, PRODUCT_OR_SERVICE_CODE_DESCRIPTION, TRANSACTION_DESCRIPTION,
        PERIOD_OF_PERFORMANCE_START_DATE, PERIOD_OF_PERFORMANCE_CURRENT_END_DATE,
        UPPER(COALESCE(TRANSACTION_DESCRIPTION,'')||' | '||COALESCE(RECIPIENT_NAME,'')) d FROM {R2})
     SELECT CONTRACT_AWARD_UNIQUE_KEY, AWARD_ID_PIID, ACTION_DATE, FEDERAL_ACTION_OBLIGATION, AWARDING_AGENCY_NAME,
        AWARDING_SUB_AGENCY_NAME, RECIPIENT_NAME, PRODUCT_OR_SERVICE_CODE_DESCRIPTION, LEFT(TRANSACTION_DESCRIPTION,250) DESCR,
        PERIOD_OF_PERFORMANCE_START_DATE, PERIOD_OF_PERFORMANCE_CURRENT_END_DATE
     FROM x WHERE REGEXP_INSTR(d,'MOBILE ?IRON|EPMM|ENDPOINT MANAGER MOBILE|MI-UEM|MI-EMG') > 0
        OR (AWARDING_SUB_AGENCY_NAME ILIKE '%Defense Information Systems%'
            AND REGEXP_INSTR(d,'IVANTI|UEM|UNIFIED ENDPOINT|ENDPOINT MANAGEMENT|MOBILE DEVICE MANAGEMENT|MDM|WORKSPACE ONE|AIRWATCH|OMNISSA|INTUNE|MOBILITY UNCLASSIFIED|DMUC|DOD MOBILITY|MOBILITY CLASSIFIED') > 0)""",
 "K4": f"""SELECT LEFT(ACTION_DATE,7) mo, IFF(AWARDING_AGENCY_NAME='Department of Defense','DoD','other') ag,
        COUNT(*) n, COUNT(DISTINCT ACTION_DATE) days, MAX(ACTION_DATE) dmax, MAX(_LOADED_AT) loaded
     FROM {R2} WHERE ACTION_DATE >= '2025-01-01' GROUP BY 1,2 ORDER BY 1,2""",
 "K5": f"""SELECT CONTRACT_AWARD_UNIQUE_KEY, AWARD_ID_PIID, ACTION_DATE, FEDERAL_ACTION_OBLIGATION, AWARDING_SUB_AGENCY_NAME, RECIPIENT_NAME,
        PRODUCT_OR_SERVICE_CODE_DESCRIPTION, LEFT(TRANSACTION_DESCRIPTION,300) DESCR, PERIOD_OF_PERFORMANCE_START_DATE, PERIOD_OF_PERFORMANCE_CURRENT_END_DATE
     FROM {R2} WHERE AWARD_ID_PIID IN ('HC108425F0324','HC108422F0117','HC102824F0391','HC102825F1301','HC102824F0225','HC108420F0288','HC108425F0370')
     ORDER BY AWARD_ID_PIID, ACTION_DATE""",
}
want = sys.argv[1:] or list(Q)
c = db.connect(); cur = c.cursor()
cur.execute("ALTER SESSION SET STATEMENT_TIMEOUT_IN_SECONDS = 300")
cur.execute("ALTER SESSION SET QUERY_TAG = 'deep3-skeptic-2026-09-24'")
for k in want:
    sql = Q[k]
    assert re.match(r"\s*(SELECT|WITH)\b", sql, re.I) and ";" not in sql
    try:
        cur.execute(sql); cols = [d[0] for d in cur.description]; rows = cur.fetchall()
        with open(HERE / f"{k}.csv", "w", newline="", encoding="utf-8") as fh:
            w = csv.writer(fh); w.writerow(cols); w.writerows(rows)
        print(k, len(rows), "rows", cols[:40])
    except Exception as e:
        print(k, "ERROR", e)
c.close()
