-- deep-2 (coverage round 2, 2026-09-24) SQL log. Python door, read-only. Numbered to match [n] tags in deep-2.md.
-- 26 queries. Each of the 7 connections also ran the two required session lines first:
--   ALTER SESSION SET STATEMENT_TIMEOUT_IN_SECONDS = 300; ALTER SESSION SET QUERY_TAG = 'coverage-r2-2026-09-24';
-- Bucket, peer and median math ran in Python (pandas) on the rows these queries returned; no extra SQL.

-- [1] ECHO: row count + 5-row sample
SELECT t.*, COUNT(*) OVER () AS N_ROWS FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ECHO t LIMIT 5;

-- [2] STACK TESTS: row count + 5-row sample
SELECT t.*, COUNT(*) OVER () AS N_ROWS FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_STACK_TESTS t LIMIT 5;

-- [3] FCES_PCES: row count + 5-row sample
SELECT t.*, COUNT(*) OVER () AS N_ROWS FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_FCES_PCES t LIMIT 5;

-- [4] AIR EMISSIONS COMBINED: row count + 5-row sample
SELECT t.*, COUNT(*) OVER () AS N_ROWS FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_AIR_EMISSIONS_POLL_RPT_COMBINED_EMISSIONS t LIMIT 5;

-- [5] EGRID 2022: row count + 5-row sample (selected columns)
SELECT PLANT_NAME, UTILITY_NAME, PLANT_STATE_ABBREVIATION, DOE_EIA_ORIS_PLANT_OR_FACILITY_CODE, PLANT_PRIMARY_FUEL_CATEGORY, PLANT_ANNUAL_NET_GENERATION_MWH, PLANT_ANNUAL_CO2_EMISSIONS_TONS, PLANT_ANNUAL_CO2_TOTAL_OUTPUT_EMISSION_RATE_LB_MWH, PLANT_ANNUAL_SO2_TOTAL_OUTPUT_EMISSION_RATE_LB_MWH, PLANT_FIPS_STATE_CODE, PLANT_FIPS_COUNTY_CODE, DATA_YEAR, COUNT(*) OVER () AS N_ROWS FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_EGRID_PLANT_2022 LIMIT 5;

-- [6] ECHO: shape by compliance status and major flag; 12-of-12 quarter rows and zero formal action
SELECT COMPLIANCE_STATUS, IS_MAJOR_FACILITY, IS_ACTIVE, COUNT(*) AS N,
  COUNT_IF(QUARTERS_WITH_NONCOMPLIANCE >= 12) AS Q12,
  COUNT_IF(QUARTERS_WITH_NONCOMPLIANCE >= 12 AND FORMAL_ACTION_COUNT = 0) AS Q12_NO_FORMAL,
  COUNT_IF(QUARTERS_WITH_NONCOMPLIANCE >= 12 AND HAS_AIR_PROGRAM) AS Q12_AIR,
  COUNT_IF(QUARTERS_WITH_NONCOMPLIANCE >= 12 AND HAS_WATER_PROGRAM) AS Q12_WATER,
  COUNT_IF(QUARTERS_WITH_NONCOMPLIANCE >= 12 AND HAS_HAZWASTE_PROGRAM) AS Q12_RCRA,
  COUNT_IF(FORMAL_ACTION_COUNT > 0) AS ANY_FORMAL,
  COUNT_IF(LAST_PENALTY_AMT_ALLOCATED > 0) AS ANY_PEN_ALLOC,
  MAX(QUARTERS_WITH_NONCOMPLIANCE) AS MAX_Q, MAX(FORMAL_ACTION_COUNT) AS MAX_FA
FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ECHO
GROUP BY 1,2,3 ORDER BY N DESC;

-- [7] ECHO: what the 3-year history string looks like on 12-of-12 rows (letter codes)
SELECT THREE_YR_COMPLIANCE_HISTORY, COUNT(*) AS N, COUNT_IF(FORMAL_ACTION_COUNT = 0) AS NO_FORMAL,
  COUNT_IF(HAS_WATER_PROGRAM) AS WATER, COUNT_IF(HAS_AIR_PROGRAM) AS AIR, COUNT_IF(HAS_HAZWASTE_PROGRAM) AS RCRA, COUNT_IF(IS_MAJOR_FACILITY) AS MAJOR
FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ECHO
WHERE QUARTERS_WITH_NONCOMPLIANCE >= 12
GROUP BY 1 ORDER BY N DESC LIMIT 25;

-- [8] STACK TESTS: result by era, date range, facility count, pollutant fill
SELECT AIR_STACK_TEST_STATUS_DESC,
  CASE WHEN ACTUAL_END_DATE < '1990-01-01' THEN 'pre1990' WHEN ACTUAL_END_DATE < '2015-01-01' THEN '1990-2014' ELSE '2015+' END AS ERA,
  COUNT(*) AS N, COUNT(DISTINCT PGM_SYS_ID) AS FACILITIES, MIN(ACTUAL_END_DATE) AS MIN_D, MAX(ACTUAL_END_DATE) AS MAX_D,
  COUNT_IF(POLLUTANT_CODES IS NULL OR POLLUTANT_CODES = '') AS NO_POLLUTANT, COUNT_IF(POLLUTANT_CODES = 'FACIL') AS FACIL,
  COUNT_IF(STATE_EPA_FLAG = 'E') AS BY_EPA
FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_STACK_TESTS
GROUP BY 1,2 ORDER BY 2,3 DESC;

-- [9] FCES_PCES: evaluation types, date range, facility counts
SELECT COMP_MONITOR_TYPE_CODE, COMP_MONITOR_TYPE_DESC, COUNT(*) AS N, COUNT(DISTINCT PGM_SYS_ID) AS FACILITIES,
  MIN(ACTUAL_END_DATE) AS MIN_D, MAX(ACTUAL_END_DATE) AS MAX_D, COUNT_IF(ACTUAL_END_DATE >= '2020-01-01') AS SINCE_2020,
  COUNT_IF(ACTUAL_END_DATE < '1970-01-01') AS BAD_DATE
FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_FCES_PCES
GROUP BY 1,2 ORDER BY N DESC;

-- [10] AIR EMISSIONS: program x year grid, facilities, zero rows
SELECT PGM_SYS_ACRNM, REPORTING_YEAR, COUNT(*) AS N, COUNT(DISTINCT REGISTRY_ID) AS FACILITIES,
  COUNT_IF(TRY_TO_DOUBLE(ANNUAL_EMISSION) = 0) AS ZERO_ROWS, COUNT_IF(TRY_TO_DOUBLE(ANNUAL_EMISSION) IS NULL) AS NONNUM,
  COUNT(DISTINCT POLLUTANT_NAME) AS POLLUTANTS
FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_AIR_EMISSIONS_POLL_RPT_COMBINED_EMISSIONS
GROUP BY 1,2 ORDER BY 1,2;

-- [11] AIR EMISSIONS: ethylene oxide and benzene spellings per program
SELECT PGM_SYS_ACRNM, POLLUTANT_NAME, UNIT_OF_MEASURE, COUNT(*) AS N, COUNT(DISTINCT REGISTRY_ID) AS FACILITIES, MIN(REPORTING_YEAR) AS Y0, MAX(REPORTING_YEAR) AS Y1
FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_AIR_EMISSIONS_POLL_RPT_COMBINED_EMISSIONS
WHERE UPPER(POLLUTANT_NAME) LIKE '%ETHYLENE OXIDE%' OR UPPER(POLLUTANT_NAME) LIKE '%BENZENE%' OR UPPER(POLLUTANT_NAME) LIKE '%OXIRANE%'
GROUP BY 1,2,3 ORDER BY N DESC LIMIT 30;

-- [12] ECHO: every facility whose 3-year history shows significant violation (S) in at least the first 11 of 12 quarters, with enforcement counts and the ICIS-Air HPV status as a second field
WITH ia AS (
  SELECT TO_VARCHAR(REGISTRY_ID) AS REG, LISTAGG(DISTINCT CURRENT_HPV, '; ') AS ICIS_HPV, LISTAGG(DISTINCT AIR_POLLUTANT_CLASS_CODE, ';') AS AIR_CLASS
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_FACILITIES
  WHERE REGISTRY_ID IS NOT NULL GROUP BY 1)
SELECT e.FRS_ID, e.FACILITY_NAME, e.CITY, e.STATE, e.IS_ACTIVE, e.IS_MAJOR_FACILITY, e.COMPLIANCE_STATUS,
  e.QUARTERS_WITH_NONCOMPLIANCE, e.THREE_YR_COMPLIANCE_HISTORY, e.HAS_AIR_PROGRAM, e.HAS_WATER_PROGRAM, e.HAS_HAZWASTE_PROGRAM,
  e.HAS_DRINKING_WATER_PROGRAM, e.TOTAL_INSPECTION_COUNT, e.DATE_LAST_INSPECTION, e.INFORMAL_ACTION_COUNT, e.FORMAL_ACTION_COUNT,
  e.DATE_LAST_FORMAL_ACTION, e.LAST_PENALTY_AMT_ALLOCATED, e.LAST_PENALTY_AMT, e.DATE_LAST_PENALTY, e.PCT_MINORITY, e.POPULATION_DENSITY,
  ia.ICIS_HPV, ia.AIR_CLASS
FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ECHO e
LEFT JOIN ia ON ia.REG = TO_VARCHAR(e.FRS_ID)
WHERE e.THREE_YR_COMPLIANCE_HISTORY LIKE 'SSSSSSSSSSS%';

-- [13] STACK TESTS: every facility with a failed test 2015+, its retest passes, and its ICIS-Air enforcement since 2015
WITH st AS (
  SELECT PGM_SYS_ID, ACTIVITY_ID, ACTUAL_END_DATE AS D, COALESCE(POLLUTANT_CODES, '') AS POL, AIR_STACK_TEST_STATUS_CODE AS S
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_STACK_TESTS
  WHERE ACTUAL_END_DATE >= '2015-01-01' AND ACTUAL_END_DATE < '2027-01-01'),
fails AS (SELECT * FROM st WHERE S = 'FAI'),
retest AS (
  SELECT f.ACTIVITY_ID, f.POL FROM fails f JOIN st p
    ON p.PGM_SYS_ID = f.PGM_SYS_ID AND p.POL = f.POL AND p.S = 'PSS' AND p.D > f.D AND p.D <= DATEADD(day, 180, f.D)
  GROUP BY 1, 2),
fac AS (
  SELECT st.PGM_SYS_ID,
    COUNT_IF(S = 'FAI') AS FAIL_ROWS, COUNT(DISTINCT CASE WHEN S = 'FAI' THEN st.ACTIVITY_ID END) AS FAIL_TESTS,
    COUNT(DISTINCT CASE WHEN S IN ('FAI','PSS') THEN st.ACTIVITY_ID END) AS PF_TESTS,
    COUNT_IF(S = 'FAI' AND r.ACTIVITY_ID IS NOT NULL) AS FAIL_ROWS_RETEST_PASSED_180D,
    COUNT(DISTINCT CASE WHEN S = 'FAI' THEN YEAR(D) END) AS FAIL_YEARS,
    MIN(CASE WHEN S = 'FAI' THEN D END) AS FIRST_FAIL, MAX(CASE WHEN S = 'FAI' THEN D END) AS LAST_FAIL,
    LISTAGG(DISTINCT CASE WHEN S = 'FAI' THEN st.POL END, ' | ') WITHIN GROUP (ORDER BY CASE WHEN S = 'FAI' THEN st.POL END) AS FAIL_POLS
  FROM st LEFT JOIN retest r ON r.ACTIVITY_ID = st.ACTIVITY_ID AND r.POL = st.POL
  GROUP BY 1 HAVING COUNT_IF(S = 'FAI') > 0),
fa AS (
  SELECT PGM_SYS_ID, COUNT(*) AS FORMAL_2015, SUM(TRY_TO_DOUBLE(TO_VARCHAR(PENALTY_AMOUNT))) AS PEN_2015,
    MAX(SETTLEMENT_ENTERED_DATE) AS LAST_SETTLE
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_FORMAL_ACTIONS
  WHERE SETTLEMENT_ENTERED_DATE >= '2015-01-01' AND SETTLEMENT_ENTERED_DATE < '2027-01-01' GROUP BY 1),
fa_all AS (
  SELECT PGM_SYS_ID, COUNT(*) AS FORMAL_ANY, COUNT_IF(SETTLEMENT_ENTERED_DATE IS NULL) AS FORMAL_NODATE
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_FORMAL_ACTIONS GROUP BY 1),
inf AS (
  SELECT PGM_SYS_ID, COUNT(*) AS INFORMAL_2015
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_INFORMAL_ACTIONS
  WHERE ACHIEVED_DATE >= '2015-01-01' AND ACHIEVED_DATE < '2027-01-01' GROUP BY 1),
vh AS (
  SELECT PGM_SYS_ID, COUNT(*) AS VIOL_2015, COUNT_IF(ENF_RESPONSE_POLICY_CODE = 'HPV') AS HPV_2015
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_VIOLATION_HISTORY
  WHERE COALESCE(EARLIEST_FRV_DETERM_DATE, HPV_DAYZERO_DATE) >= '2015-01-01' GROUP BY 1),
f AS (
  SELECT PGM_SYS_ID, ANY_VALUE(REGISTRY_ID) AS REGISTRY_ID, ANY_VALUE(FACILITY_NAME) AS FACILITY_NAME, ANY_VALUE(CITY) AS CITY,
    ANY_VALUE(STATE) AS STATE, ANY_VALUE(AIR_POLLUTANT_CLASS_CODE) AS CLS, ANY_VALUE(AIR_OPERATING_STATUS_CODE) AS OPSTAT,
    ANY_VALUE(CURRENT_HPV) AS CURRENT_HPV, ANY_VALUE(NAICS_CODES) AS NAICS, COUNT(*) AS F_ROWS
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_FACILITIES GROUP BY 1)
SELECT fac.*, f.REGISTRY_ID, f.FACILITY_NAME, f.CITY, f.STATE, f.CLS, f.OPSTAT, f.CURRENT_HPV, f.NAICS, f.F_ROWS,
  COALESCE(fa.FORMAL_2015, 0) AS FORMAL_2015, COALESCE(fa.PEN_2015, 0) AS PEN_2015, fa.LAST_SETTLE,
  COALESCE(fa_all.FORMAL_ANY, 0) AS FORMAL_ANY, COALESCE(fa_all.FORMAL_NODATE, 0) AS FORMAL_NODATE,
  COALESCE(inf.INFORMAL_2015, 0) AS INFORMAL_2015, COALESCE(vh.VIOL_2015, 0) AS VIOL_2015, COALESCE(vh.HPV_2015, 0) AS HPV_2015
FROM fac LEFT JOIN f USING (PGM_SYS_ID) LEFT JOIN fa USING (PGM_SYS_ID) LEFT JOIN fa_all USING (PGM_SYS_ID)
LEFT JOIN inf USING (PGM_SYS_ID) LEFT JOIN vh USING (PGM_SYS_ID)
ORDER BY fac.FAIL_TESTS DESC;

-- [14] FCES_PCES: every ICIS-Air major source, last full evaluation (FCE on/off-site), last any evaluation, and its 2023 GHG size
WITH fce AS (
  SELECT PGM_SYS_ID, MAX(ACTUAL_END_DATE) AS LAST_FCE, MIN(ACTUAL_END_DATE) AS FIRST_FCE, COUNT(*) AS N_FCE,
    COUNT_IF(ACTUAL_END_DATE >= '2021-01-01') AS FCE_SINCE_2021
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_FCES_PCES
  WHERE COMP_MONITOR_TYPE_CODE IN ('FOO', 'FFO') AND ACTUAL_END_DATE >= '1970-01-01' AND ACTUAL_END_DATE < '2027-01-01' GROUP BY 1),
anyev AS (
  SELECT PGM_SYS_ID, MAX(ACTUAL_END_DATE) AS LAST_ANY_EVAL, COUNT(*) AS N_EVAL
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_FCES_PCES
  WHERE ACTUAL_END_DATE >= '1970-01-01' AND ACTUAL_END_DATE < '2027-01-01' GROUP BY 1),
f AS (
  SELECT PGM_SYS_ID, ANY_VALUE(REGISTRY_ID) AS REGISTRY_ID, ANY_VALUE(FACILITY_NAME) AS FACILITY_NAME, ANY_VALUE(CITY) AS CITY,
    ANY_VALUE(STATE) AS STATE, ANY_VALUE(AIR_POLLUTANT_CLASS_CODE) AS CLS, ANY_VALUE(AIR_OPERATING_STATUS_CODE) AS OPSTAT,
    ANY_VALUE(CURRENT_HPV) AS CURRENT_HPV, ANY_VALUE(NAICS_CODES) AS NAICS, ANY_VALUE(LOCAL_CONTROL_REGION_NAME) AS LOCAL_AGENCY
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_FACILITIES GROUP BY 1),
ghg AS (
  SELECT TO_VARCHAR(REGISTRY_ID) AS REG, SUM(TRY_TO_DOUBLE(ANNUAL_EMISSION)) AS GHG_SUM_2023, MAX(TRY_TO_DOUBLE(ANNUAL_EMISSION)) AS GHG_MAX_2023,
    MAX_BY(POLLUTANT_NAME, TRY_TO_DOUBLE(ANNUAL_EMISSION)) AS GHG_MAX_POL
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_AIR_EMISSIONS_POLL_RPT_COMBINED_EMISSIONS
  WHERE PGM_SYS_ACRNM = 'E-GGRT' AND REPORTING_YEAR = 2023 GROUP BY 1)
SELECT f.*, fce.LAST_FCE, fce.FIRST_FCE, fce.N_FCE, fce.FCE_SINCE_2021, anyev.LAST_ANY_EVAL, anyev.N_EVAL,
  ghg.GHG_SUM_2023, ghg.GHG_MAX_2023, ghg.GHG_MAX_POL
FROM f LEFT JOIN fce USING (PGM_SYS_ID) LEFT JOIN anyev USING (PGM_SYS_ID) LEFT JOIN ghg ON ghg.REG = TO_VARCHAR(f.REGISTRY_ID)
WHERE f.CLS = 'MAJ';

-- [15] ICIS-Air join land rates: stack-test and evaluation facility IDs found in the ICIS-Air facility table; class and status mix
WITH ids AS (
  SELECT 'STACK' AS SRC, PGM_SYS_ID FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_STACK_TESTS GROUP BY 1, 2
  UNION ALL
  SELECT 'FCES', PGM_SYS_ID FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_FCES_PCES GROUP BY 1, 2),
f AS (SELECT PGM_SYS_ID, ANY_VALUE(AIR_POLLUTANT_CLASS_CODE) AS CLS, ANY_VALUE(AIR_OPERATING_STATUS_CODE) AS OPSTAT, COUNT(*) AS N
      FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_FACILITIES GROUP BY 1)
SELECT ids.SRC, f.CLS, f.OPSTAT, COUNT(*) AS IDS, COUNT_IF(f.PGM_SYS_ID IS NULL) AS NOT_FOUND, MAX(f.N) AS MAX_DUP
FROM ids LEFT JOIN f USING (PGM_SYS_ID) GROUP BY 1, 2, 3 ORDER BY 1, 4 DESC;

-- [16] AIR EMISSIONS: TRI vs EIS on the same facility, pollutant and year (2017 and 2020, the only overlap years)
WITH t AS (
  SELECT TO_VARCHAR(REGISTRY_ID) AS REG, REPORTING_YEAR AS Y, UPPER(POLLUTANT_NAME) AS POL, SUM(TRY_TO_DOUBLE(ANNUAL_EMISSION)) AS V
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_AIR_EMISSIONS_POLL_RPT_COMBINED_EMISSIONS
  WHERE PGM_SYS_ACRNM = 'TRIS' AND REPORTING_YEAR IN (2017, 2020) AND UNIT_OF_MEASURE = 'Pounds' GROUP BY 1, 2, 3),
e AS (
  SELECT TO_VARCHAR(REGISTRY_ID) AS REG, REPORTING_YEAR AS Y, UPPER(POLLUTANT_NAME) AS POL, SUM(TRY_TO_DOUBLE(ANNUAL_EMISSION)) AS EV
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_AIR_EMISSIONS_POLL_RPT_COMBINED_EMISSIONS
  WHERE PGM_SYS_ACRNM = 'EIS' AND REPORTING_YEAR IN (2017, 2020) AND UNIT_OF_MEASURE = 'Pounds' GROUP BY 1, 2, 3),
tr AS (SELECT POL, COUNT(*) AS TRI_ROWS, COUNT(DISTINCT REG) AS TRI_FACS FROM t GROUP BY 1),
p AS (SELECT t.REG, t.Y, t.POL, t.V, e.EV FROM t JOIN e ON e.REG = t.REG AND e.Y = t.Y AND e.POL = t.POL)
SELECT p.POL, ANY_VALUE(tr.TRI_ROWS) AS TRI_ROWS, ANY_VALUE(tr.TRI_FACS) AS TRI_FACS, COUNT(*) AS PAIRS,
  COUNT_IF(V > 0 AND EV > 0) AS BOTH_POS,
  COUNT_IF(V > 0 AND EV > 0 AND V / EV >= 10) AS TRI_10X_HIGHER, COUNT_IF(V > 0 AND EV > 0 AND EV / V >= 10) AS EIS_10X_HIGHER,
  COUNT_IF(V = 0 AND EV > 0) AS TRI_ZERO_EIS_POS, COUNT_IF(EV = 0 AND V > 0) AS EIS_ZERO_TRI_POS,
  SUM(V) AS TRI_LB, SUM(EV) AS EIS_LB, MEDIAN(CASE WHEN V > 0 AND EV > 0 THEN V / EV END) AS MED_TRI_OVER_EIS
FROM p JOIN tr ON tr.POL = p.POL GROUP BY p.POL ORDER BY PAIRS DESC;

-- [17] AIR EMISSIONS: ethylene oxide, every facility-year in TRI and EIS, with the ECHO name, state and nearby % minority
WITH x AS (
  SELECT TO_VARCHAR(REGISTRY_ID) AS REG, PGM_SYS_ACRNM AS PGM, REPORTING_YEAR AS Y, SUM(TRY_TO_DOUBLE(ANNUAL_EMISSION)) AS LB, COUNT(*) AS N
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_AIR_EMISSIONS_POLL_RPT_COMBINED_EMISSIONS
  WHERE UPPER(POLLUTANT_NAME) = 'ETHYLENE OXIDE' GROUP BY 1, 2, 3)
SELECT x.*, e.FACILITY_NAME, e.CITY, e.STATE, e.PCT_MINORITY, e.POPULATION_DENSITY
FROM x LEFT JOIN LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ECHO e ON TO_VARCHAR(e.FRS_ID) = x.REG;

-- [18] EGRID: every plant with numeric fields, the CAMD-to-registry link from the combined emissions table, and ECHO nearby % minority
WITH g AS (
  SELECT PLANT_NAME, UTILITY_NAME, PLANT_STATE_ABBREVIATION AS ST, TRY_TO_NUMBER(DOE_EIA_ORIS_PLANT_OR_FACILITY_CODE) AS ORIS,
    PLANT_PRIMARY_FUEL_CATEGORY AS FUEL, PLANT_PRIMARY_FUEL AS FUEL_CODE, PLANT_LEVEL_SECTOR AS SECTOR,
    TRY_TO_DOUBLE(PLANT_ANNUAL_NET_GENERATION_MWH) AS GEN, TRY_TO_DOUBLE(PLANT_ANNUAL_CO2_EMISSIONS_TONS) AS CO2_T,
    TRY_TO_DOUBLE(PLANT_ANNUAL_CO2_TOTAL_OUTPUT_EMISSION_RATE_LB_MWH) AS CO2_RATE,
    TRY_TO_DOUBLE(PLANT_ANNUAL_SO2_TOTAL_OUTPUT_EMISSION_RATE_LB_MWH) AS SO2_RATE,
    TRY_TO_DOUBLE(PLANT_ANNUAL_NOX_TOTAL_OUTPUT_EMISSION_RATE_LB_MWH) AS NOX_RATE,
    TRY_TO_DOUBLE(PLANT_ANNUAL_SO2_EMISSIONS_TONS) AS SO2_T, TRY_TO_DOUBLE(PLANT_ANNUAL_NOX_EMISSIONS_TONS) AS NOX_T,
    TRY_TO_DOUBLE(PLANT_CAPACITY_FACTOR) AS CF, TRY_TO_DOUBLE(PLANT_NAMEPLATE_CAPACITY_MW) AS MW,
    TRY_TO_DOUBLE(PLANT_COAL_GENERATION_PERCENT_RESOURCE_MIX) AS COAL_SHARE,
    PLANT_FIPS_STATE_CODE || PLANT_FIPS_COUNTY_CODE AS FIPS5, PLANT_COUNTY_NAME AS COUNTY,
    COMBINED_HEAT_AND_POWER_CHP_PLANT_ADJUSTMENT_FLAG AS CHP_FLAG
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_EGRID_PLANT_2022 WHERE PLANT_NAME <> 'PNAME'),
c AS (
  SELECT TRY_TO_NUMBER(PGM_SYS_ID) AS ORIS, MIN(TO_VARCHAR(REGISTRY_ID)) AS REG, COUNT(DISTINCT REGISTRY_ID) AS NREG
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_AIR_EMISSIONS_POLL_RPT_COMBINED_EMISSIONS
  WHERE PGM_SYS_ACRNM = 'CAMDBS' GROUP BY 1),
e AS (
  SELECT TO_VARCHAR(FRS_ID) AS REG, STATE, FACILITY_NAME, PCT_MINORITY, POPULATION_DENSITY
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ECHO WHERE TO_VARCHAR(FRS_ID) IN (SELECT REG FROM c))
SELECT g.*, c.REG, c.NREG, e.STATE AS ECHO_STATE, e.FACILITY_NAME AS ECHO_NAME, e.PCT_MINORITY, e.POPULATION_DENSITY
FROM g LEFT JOIN c ON c.ORIS = g.ORIS LEFT JOIN e ON e.REG = c.REG;

-- [19] ICIS-Air state roll-up since 2015: operating majors, formal and informal actions, stack tests, HPV violations and how many got resolved
WITH f AS (
  SELECT PGM_SYS_ID, ANY_VALUE(STATE) AS ST, ANY_VALUE(AIR_POLLUTANT_CLASS_CODE) AS CLS, ANY_VALUE(AIR_OPERATING_STATUS_CODE) AS OP
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_FACILITIES GROUP BY 1),
maj AS (SELECT ST, COUNT_IF(CLS = 'MAJ' AND OP = 'OPR') AS OPR_MAJORS, COUNT_IF(OP = 'OPR') AS OPR_ALL FROM f GROUP BY 1),
fa AS (
  SELECT f.ST, COUNT_IF(a.SETTLEMENT_ENTERED_DATE >= '2015-01-01' AND a.SETTLEMENT_ENTERED_DATE < '2027-01-01') AS FORMAL_15,
    COUNT_IF(a.SETTLEMENT_ENTERED_DATE IS NULL) AS FORMAL_NODATE, COUNT(*) AS FORMAL_ALL,
    SUM(CASE WHEN a.SETTLEMENT_ENTERED_DATE >= '2015-01-01' THEN TRY_TO_DOUBLE(TO_VARCHAR(a.PENALTY_AMOUNT)) END) AS PEN_15,
    COUNT_IF(a.SETTLEMENT_ENTERED_DATE >= '2015-01-01' AND a.STATE_EPA_FLAG = 'E') AS FORMAL_15_BY_EPA
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_FORMAL_ACTIONS a JOIN f USING (PGM_SYS_ID) GROUP BY 1),
ia AS (
  SELECT f.ST, COUNT(*) AS INFORMAL_15
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_INFORMAL_ACTIONS i JOIN f USING (PGM_SYS_ID)
  WHERE i.ACHIEVED_DATE >= '2015-01-01' AND i.ACHIEVED_DATE < '2027-01-01' GROUP BY 1),
stk AS (
  SELECT f.ST, COUNT_IF(s.AIR_STACK_TEST_STATUS_CODE = 'PSS') AS ST_PASS, COUNT_IF(s.AIR_STACK_TEST_STATUS_CODE = 'FAI') AS ST_FAIL
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_STACK_TESTS s JOIN f USING (PGM_SYS_ID)
  WHERE s.ACTUAL_END_DATE >= '2015-01-01' AND s.ACTUAL_END_DATE < '2027-01-01' GROUP BY 1),
vh AS (
  SELECT f.ST,
    COUNT_IF(v.ENF_RESPONSE_POLICY_CODE = 'HPV') AS HPV_15,
    COUNT_IF(v.ENF_RESPONSE_POLICY_CODE = 'HPV' AND v.HPV_RESOLVED_DATE IS NOT NULL) AS HPV_15_RESOLVED,
    COUNT_IF(v.ENF_RESPONSE_POLICY_CODE = 'HPV' AND v.HPV_RESOLVED_DATE IS NULL AND TRY_TO_DATE(TO_VARCHAR(v.HPV_DAYZERO_DATE)) < '2023-07-01') AS HPV_OPEN_3Y,
    MEDIAN(CASE WHEN v.ENF_RESPONSE_POLICY_CODE = 'HPV' THEN DATEDIFF(day, TRY_TO_DATE(TO_VARCHAR(v.HPV_DAYZERO_DATE)), TRY_TO_DATE(TO_VARCHAR(v.HPV_RESOLVED_DATE))) END) AS HPV_MED_DAYS_TO_RESOLVE,
    COUNT_IF(v.ENF_RESPONSE_POLICY_CODE = 'FRV') AS FRV_15
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_VIOLATION_HISTORY v JOIN f USING (PGM_SYS_ID)
  WHERE TRY_TO_DATE(TO_VARCHAR(COALESCE(v.HPV_DAYZERO_DATE, v.EARLIEST_FRV_DETERM_DATE))) >= '2015-01-01' GROUP BY 1)
SELECT maj.ST, maj.OPR_MAJORS, maj.OPR_ALL, fa.FORMAL_15, fa.FORMAL_15_BY_EPA, fa.PEN_15, fa.FORMAL_NODATE, fa.FORMAL_ALL, ia.INFORMAL_15,
  stk.ST_PASS, stk.ST_FAIL, vh.HPV_15, vh.HPV_15_RESOLVED, vh.HPV_OPEN_3Y, vh.HPV_MED_DAYS_TO_RESOLVE, vh.FRV_15
FROM maj LEFT JOIN fa USING (ST) LEFT JOIN ia USING (ST) LEFT JOIN stk USING (ST) LEFT JOIN vh USING (ST)
WHERE maj.OPR_MAJORS > 0 ORDER BY maj.OPR_MAJORS DESC;

-- [20] FCES_PCES: are the stale majors alive? last stack test, informal, formal, violation, emissions report year (2021+) and ECHO status for every operating major
WITH f AS (
  SELECT PGM_SYS_ID, ANY_VALUE(REGISTRY_ID) AS REGISTRY_ID, ANY_VALUE(STATE) AS ST
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_FACILITIES
  GROUP BY 1 HAVING ANY_VALUE(AIR_POLLUTANT_CLASS_CODE) = 'MAJ' AND ANY_VALUE(AIR_OPERATING_STATUS_CODE) = 'OPR'),
stk AS (SELECT PGM_SYS_ID, MAX(ACTUAL_END_DATE) AS LAST_STACK FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_STACK_TESTS WHERE ACTUAL_END_DATE < '2027-01-01' GROUP BY 1),
inf AS (SELECT PGM_SYS_ID, MAX(ACHIEVED_DATE) AS LAST_INFORMAL FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_INFORMAL_ACTIONS WHERE ACHIEVED_DATE < '2027-01-01' GROUP BY 1),
fa AS (SELECT PGM_SYS_ID, MAX(SETTLEMENT_ENTERED_DATE) AS LAST_FORMAL FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_FORMAL_ACTIONS WHERE SETTLEMENT_ENTERED_DATE < '2027-01-01' GROUP BY 1),
vh AS (SELECT PGM_SYS_ID, MAX(TRY_TO_DATE(TO_VARCHAR(COALESCE(HPV_DAYZERO_DATE, EARLIEST_FRV_DETERM_DATE)))) AS LAST_VIOL FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_VIOLATION_HISTORY GROUP BY 1),
em AS (
  SELECT TO_VARCHAR(REGISTRY_ID) AS REG, MAX(REPORTING_YEAR) AS LAST_EMIS_YEAR, LISTAGG(DISTINCT PGM_SYS_ACRNM, ',') AS EMIS_PROGS
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_AIR_EMISSIONS_POLL_RPT_COMBINED_EMISSIONS WHERE REPORTING_YEAR >= 2021 GROUP BY 1),
ec AS (
  SELECT TO_VARCHAR(FRS_ID) AS REG, IS_ACTIVE, DATE_LAST_INSPECTION, COMPLIANCE_STATUS
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ECHO WHERE TO_VARCHAR(FRS_ID) IN (SELECT TO_VARCHAR(REGISTRY_ID) FROM f))
SELECT f.PGM_SYS_ID, f.ST, f.REGISTRY_ID, stk.LAST_STACK, inf.LAST_INFORMAL, fa.LAST_FORMAL, vh.LAST_VIOL, em.LAST_EMIS_YEAR, em.EMIS_PROGS,
  ec.IS_ACTIVE, ec.DATE_LAST_INSPECTION, ec.COMPLIANCE_STATUS
FROM f LEFT JOIN stk USING (PGM_SYS_ID) LEFT JOIN inf USING (PGM_SYS_ID) LEFT JOIN fa USING (PGM_SYS_ID) LEFT JOIN vh USING (PGM_SYS_ID)
LEFT JOIN em ON em.REG = TO_VARCHAR(f.REGISTRY_ID) LEFT JOIN ec ON ec.REG = TO_VARCHAR(f.REGISTRY_ID);

-- [21] ECHO: top 20 facilities by this facility's share of its latest penalty (LAST_PENALTY_AMT_ALLOCATED), with the case size
SELECT FRS_ID, FACILITY_NAME, CITY, STATE, IS_ACTIVE, LAST_PENALTY_AMT_ALLOCATED, LAST_PENALTY_AMT, LAST_PENALTY_SHARED_FACILITY_N, DATE_LAST_PENALTY,
  TOTAL_PENALTIES, HAS_AIR_PROGRAM, HAS_WATER_PROGRAM, HAS_HAZWASTE_PROGRAM
FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ECHO
WHERE LAST_PENALTY_AMT_ALLOCATED > 0
ORDER BY LAST_PENALTY_AMT_ALLOCATED DESC LIMIT 20;

-- [22] ICIS-Air: every Nebraska HPV (high priority violation) found since 2015, with facility, pollutant, rule, day-zero and resolved dates
WITH f AS (
  SELECT PGM_SYS_ID, ANY_VALUE(FACILITY_NAME) AS FACILITY_NAME, ANY_VALUE(CITY) AS CITY, ANY_VALUE(NAICS_CODES) AS NAICS,
    ANY_VALUE(AIR_POLLUTANT_CLASS_CODE) AS CLS, ANY_VALUE(AIR_OPERATING_STATUS_CODE) AS OP, ANY_VALUE(CURRENT_HPV) AS CURRENT_HPV, ANY_VALUE(STATE) AS ST
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_FACILITIES GROUP BY 1)
SELECT f.FACILITY_NAME, f.CITY, f.NAICS, f.CLS, f.OP, f.CURRENT_HPV, v.PGM_SYS_ID, v.AGENCY_TYPE_DESC, v.PROGRAM_DESCS, v.POLLUTANT_DESCS,
  v.HPV_DAYZERO_DATE, v.HPV_RESOLVED_DATE, v.EARLIEST_FRV_DETERM_DATE, v.DSCV_PATHWAY_DATE, v.NFTC_PATHWAY_DATE
FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_VIOLATION_HISTORY v JOIN f USING (PGM_SYS_ID)
WHERE f.ST = 'NE' AND v.ENF_RESPONSE_POLICY_CODE = 'HPV'
  AND TRY_TO_DATE(TO_VARCHAR(COALESCE(v.HPV_DAYZERO_DATE, v.EARLIEST_FRV_DETERM_DATE))) >= '2015-01-01'
ORDER BY f.FACILITY_NAME, v.HPV_DAYZERO_DATE;

-- [23] FCES_PCES: full evaluations (FCE on/off-site) per year 2012-2025 at facilities in TX, CA, NE, IA and all states
WITH f AS (SELECT PGM_SYS_ID, ANY_VALUE(STATE) AS ST, ANY_VALUE(AIR_POLLUTANT_CLASS_CODE) AS CLS
           FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_FACILITIES GROUP BY 1)
SELECT YEAR(e.ACTUAL_END_DATE) AS YR,
  COUNT_IF(f.ST = 'TX') AS TX_FCE, COUNT_IF(f.ST = 'TX' AND f.CLS = 'MAJ') AS TX_MAJ_FCE,
  COUNT_IF(f.ST = 'CA' AND f.CLS = 'MAJ') AS CA_MAJ_FCE, COUNT_IF(f.ST = 'NE' AND f.CLS = 'MAJ') AS NE_MAJ_FCE,
  COUNT_IF(f.ST = 'IA' AND f.CLS = 'MAJ') AS IA_MAJ_FCE, COUNT_IF(f.CLS = 'MAJ') AS ALL_MAJ_FCE, COUNT(*) AS ALL_FCE
FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_FCES_PCES e JOIN f USING (PGM_SYS_ID)
WHERE e.COMP_MONITOR_TYPE_CODE IN ('FOO', 'FFO') AND e.ACTUAL_END_DATE >= '2012-01-01' AND e.ACTUAL_END_DATE < '2026-01-01'
GROUP BY 1 ORDER BY 1;

-- [24] TRI_BASIC_2023 cross-check: top ethylene oxide air releasers in 2023, fugitive vs stack, against the combined table's 2023 figure
SELECT C_3_FRS_ID, C_4_FACILITY_NAME, C_6_CITY, C_8_ST, C_17_STANDARD_PARENT_CO_NAME, C_37_CHEMICAL, C_50_UNIT_OF_MEASURE,
  C_51_5_1_FUGITIVE_AIR, C_52_5_2_STACK_AIR, C_65_ON_SITE_RELEASE_TOTAL, C_49_FORM_TYPE
FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_TRI_BASIC_2023
WHERE UPPER(C_37_CHEMICAL) = 'ETHYLENE OXIDE'
ORDER BY TRY_TO_DOUBLE(TO_VARCHAR(C_51_5_1_FUGITIVE_AIR)) + TRY_TO_DOUBLE(TO_VARCHAR(C_52_5_2_STACK_AIR)) DESC NULLS LAST
LIMIT 8;

-- [25] EGRID: do the impossible CO2-per-MWh gas plants have a replacement plant under a new ID with the generation?
SELECT PLANT_NAME, UTILITY_NAME, PLANT_STATE_ABBREVIATION AS ST, DOE_EIA_ORIS_PLANT_OR_FACILITY_CODE AS ORIS, PLANT_PRIMARY_FUEL_CATEGORY AS FUEL,
  TRY_TO_DOUBLE(PLANT_NAMEPLATE_CAPACITY_MW) AS MW, TRY_TO_DOUBLE(PLANT_ANNUAL_NET_GENERATION_MWH) AS GEN,
  TRY_TO_DOUBLE(PLANT_ANNUAL_CO2_EMISSIONS_TONS) AS CO2_T, TRY_TO_DOUBLE(PLANT_ANNUAL_CO2_TOTAL_OUTPUT_EMISSION_RATE_LB_MWH) AS CO2_RATE,
  TRY_TO_DOUBLE(PLANT_ANNUAL_HEAT_INPUT_FROM_COMBUSTION_MMBTU) AS HEAT_IN, PLANT_UNADJUSTED_ANNUAL_CO2_EMISSIONS_SOURCE AS CO2_SRC
FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_EGRID_PLANT_2022
WHERE UPPER(PLANT_NAME) LIKE '%HUNTINGTON BEACH%' OR UPPER(PLANT_NAME) LIKE '%ALAMITOS%' OR UPPER(PLANT_NAME) LIKE '%LAUDERDALE%'
   OR UPPER(PLANT_NAME) LIKE '%DANIA%' OR UPPER(PLANT_NAME) LIKE '%GLEASON%' OR UPPER(PLANT_NAME) LIKE '%ANTELOPE%'
ORDER BY PLANT_NAME;

-- [26] ICIS-Air formal actions by settlement year, 2000-2025: Nebraska and Iowa state vs EPA, and all states
WITH f AS (SELECT PGM_SYS_ID, ANY_VALUE(STATE) AS ST FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_FACILITIES GROUP BY 1)
SELECT YEAR(a.SETTLEMENT_ENTERED_DATE) AS YR,
  COUNT_IF(f.ST = 'NE' AND a.STATE_EPA_FLAG <> 'E') AS NE_STATE, COUNT_IF(f.ST = 'NE' AND a.STATE_EPA_FLAG = 'E') AS NE_EPA,
  COUNT_IF(f.ST = 'IA' AND a.STATE_EPA_FLAG <> 'E') AS IA_STATE, COUNT_IF(f.ST = 'IA' AND a.STATE_EPA_FLAG = 'E') AS IA_EPA,
  COUNT_IF(a.STATE_EPA_FLAG <> 'E') AS ALL_STATE_LOCAL, COUNT(*) AS ALL_FORMAL
FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_FORMAL_ACTIONS a JOIN f USING (PGM_SYS_ID)
WHERE a.SETTLEMENT_ENTERED_DATE >= '2000-01-01' AND a.SETTLEMENT_ENTERED_DATE < '2026-01-01'
GROUP BY 1 ORDER BY 1;
