-- deep2/deep-4, coverage round 2, 2026-09-24. Read-only. Python door (connect/db.py).
-- Every connection first ran: ALTER SESSION SET STATEMENT_TIMEOUT_IN_SECONDS = 300; ALTER SESSION SET QUERY_TAG = 'coverage-r2-2026-09-24'.
-- [1] metadata: columns and schemas for my 5 tables plus join partners (INFORMATION_SCHEMA.COLUMNS, table_name IN (...) OR LIKE '%FRACFOCUS%' OR LIKE '%RCRA%')
-- [2] a five-query block sent as one text by mistake; it failed to compile and returned nothing. Counted anyway.

-- [3] RCRA VIOSNC: count, distinct sites, month span, flag combos, site-month uniqueness
SELECT VIO_FLAG, SNC_FLAG, COUNT(*) AS n, COUNT(DISTINCT ID_NUMBER) AS sites, MIN(YRMONTH) AS first_m, MAX(YRMONTH) AS last_m,
       COUNT(DISTINCT ID_NUMBER||'|'||YRMONTH) AS site_months
FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_RCRA_VIOSNC_HISTORY
GROUP BY ROLLUP(VIO_FLAG, SNC_FLAG) ORDER BY 1,2;

-- [4] RCRA VIOSNC: sample
SELECT * FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_RCRA_VIOSNC_HISTORY LIMIT 5;

-- [5] RCRA VIOSNC: rows and sites per year, Y and SNC share
SELECT LEFT(YRMONTH,4) AS yr, COUNT(*) AS n, COUNT(DISTINCT ID_NUMBER) AS sites, COUNT(DISTINCT YRMONTH) AS months,
       ROUND(AVG(IFF(VIO_FLAG='Y',1,0)),3) AS y_share, ROUND(AVG(IFF(SNC_FLAG='Y',1,0)),3) AS snc_share
FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_RCRA_VIOSNC_HISTORY GROUP BY 1 ORDER BY 1;

-- [6] SDWA events: count, systems, codes
SELECT EVENT_MILESTONE_CODE, EVENT_REASON_CODE, COUNT(*) AS n, COUNT(DISTINCT PWSID) AS systems,
       MIN(EVENT_ACTUAL_DATE) AS min_act, MAX(EVENT_ACTUAL_DATE) AS max_act, COUNT(EVENT_ACTUAL_DATE) AS act_filled,
       COUNT(EVENT_END_DATE) AS end_filled, ANY_VALUE(EVENT_COMMENTS_TEXT) AS a_comment
FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_SDWA_SDWA_EVENTS_MILESTONES
GROUP BY ROLLUP(EVENT_MILESTONE_CODE, EVENT_REASON_CODE) ORDER BY n DESC;

-- [7] SDWA events: sample
SELECT * FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_SDWA_SDWA_EVENTS_MILESTONES WHERE EVENT_MILESTONE_CODE='LSLI' LIMIT 5;

-- [8] RCRA VIOSNC: unbroken Y-month runs per site; by state, sites open now (run reaches 202606 or later) and how many of those are 10y+ and 20y+ long
WITH y AS (
  SELECT ID_NUMBER, ACTIVITY_LOCATION AS st, TO_NUMBER(LEFT(YRMONTH,4))*12 + TO_NUMBER(SUBSTR(YRMONTH,5,2)) AS mi, SNC_FLAG
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_RCRA_VIOSNC_HISTORY WHERE VIO_FLAG = 'Y'),
g AS (SELECT y.*, mi - ROW_NUMBER() OVER (PARTITION BY ID_NUMBER ORDER BY mi) AS grp FROM y),
s AS (SELECT ID_NUMBER, ANY_VALUE(st) AS st, grp, MIN(mi) AS s_mi, MAX(mi) AS e_mi, COUNT(*) AS len, SUM(IFF(SNC_FLAG='Y',1,0)) AS snc FROM g GROUP BY ID_NUMBER, grp)
SELECT st, COUNT(DISTINCT ID_NUMBER) AS sites_ever,
       COUNT(DISTINCT IFF(e_mi >= 2026*12+6, ID_NUMBER, NULL)) AS open_now,
       COUNT(DISTINCT IFF(e_mi >= 2026*12+6 AND len >= 120, ID_NUMBER, NULL)) AS open_10y,
       COUNT(DISTINCT IFF(e_mi >= 2026*12+6 AND len >= 240, ID_NUMBER, NULL)) AS open_20y,
       COUNT(DISTINCT IFF(e_mi >= 2026*12+6 AND snc >= 120, ID_NUMBER, NULL)) AS open_snc_10y,
       ROUND(COUNT(DISTINCT IFF(e_mi >= 2026*12+6 AND len >= 120, ID_NUMBER, NULL)) / NULLIF(COUNT(DISTINCT IFF(e_mi >= 2026*12+6, ID_NUMBER, NULL)),0), 3) AS share_open_10y,
       MAX(len) AS max_run_months
FROM s GROUP BY ROLLUP(st) ORDER BY open_now DESC NULLS FIRST;

-- [9] RCRA VIOSNC: runs of 10y+; how many, and do their end months bunch up (a bulk close-out would say paperwork)
WITH y AS (
  SELECT ID_NUMBER, TO_NUMBER(LEFT(YRMONTH,4))*12 + TO_NUMBER(SUBSTR(YRMONTH,5,2)) AS mi
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_RCRA_VIOSNC_HISTORY WHERE VIO_FLAG = 'Y'),
g AS (SELECT y.*, mi - ROW_NUMBER() OVER (PARTITION BY ID_NUMBER ORDER BY mi) AS grp FROM y),
s AS (SELECT ID_NUMBER, grp, MIN(mi) AS s_mi, MAX(mi) AS e_mi, COUNT(*) AS len FROM g GROUP BY ID_NUMBER, grp HAVING COUNT(*) >= 120)
SELECT FLOOR((e_mi-1)/12) AS end_year, MOD(e_mi-1,12)+1 AS end_month, COUNT(*) AS runs_10y, SUM(IFF(len>=240,1,0)) AS runs_20y,
       SUM(COUNT(*)) OVER () AS all_runs_10y
FROM s GROUP BY 1,2 ORDER BY runs_10y DESC LIMIT 15;

-- [10] RCRA VIOSNC: the 25 longest runs ever, with facility name, the violations behind them, and inspections during the run
WITH y AS (
  SELECT ID_NUMBER, ACTIVITY_LOCATION AS st, TO_NUMBER(LEFT(YRMONTH,4))*12 + TO_NUMBER(SUBSTR(YRMONTH,5,2)) AS mi, SNC_FLAG
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_RCRA_VIOSNC_HISTORY WHERE VIO_FLAG = 'Y'),
g AS (SELECT y.*, mi - ROW_NUMBER() OVER (PARTITION BY ID_NUMBER ORDER BY mi) AS grp FROM y),
s AS (SELECT ID_NUMBER, ANY_VALUE(st) AS st, MIN(mi) AS s_mi, MAX(mi) AS e_mi, COUNT(*) AS len, SUM(IFF(SNC_FLAG='Y',1,0)) AS snc
      FROM g GROUP BY ID_NUMBER, grp QUALIFY ROW_NUMBER() OVER (ORDER BY COUNT(*) DESC) <= 25),
f AS (SELECT ID_NUMBER, ANY_VALUE(FACILITY_NAME) AS name, ANY_VALUE(CITY_NAME) AS city, ANY_VALUE(HREPORT_UNIVERSE_RECORD) AS universe, COUNT(*) AS fac_rows
      FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_RCRA_FACILITIES WHERE ID_NUMBER IN (SELECT ID_NUMBER FROM s) GROUP BY 1),
v AS (SELECT ID_NUMBER, COUNT(*) AS viols, SUM(IFF(ACTUAL_RTC_DATE IS NULL,1,0)) AS viols_open, MIN(DATE_VIOLATION_DETERMINED) AS first_viol, MAX(DATE_VIOLATION_DETERMINED) AS last_viol, MAX(ACTUAL_RTC_DATE) AS last_rtc
      FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_RCRA_VIOLATIONS WHERE ID_NUMBER IN (SELECT ID_NUMBER FROM s) GROUP BY 1),
e AS (SELECT ID_NUMBER, COUNT(*) AS evals, MAX(EVALUATION_START_DATE) AS last_eval, SUM(IFF(FOUND_VIOLATION='N',1,0)) AS evals_clean
      FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_RCRA_EVALUATIONS WHERE ID_NUMBER IN (SELECT ID_NUMBER FROM s) GROUP BY 1)
SELECT s.ID_NUMBER, s.st, f.name, f.city, f.universe, f.fac_rows,
       FLOOR((s.s_mi-1)/12)||'-'||LPAD(MOD(s.s_mi-1,12)+1,2,'0') AS run_start, FLOOR((s.e_mi-1)/12)||'-'||LPAD(MOD(s.e_mi-1,12)+1,2,'0') AS run_end, s.len, s.snc,
       v.viols, v.viols_open, v.first_viol, v.last_viol, v.last_rtc, e.evals, e.evals_clean, e.last_eval
FROM s LEFT JOIN f USING (ID_NUMBER) LEFT JOIN v USING (ID_NUMBER) LEFT JOIN e USING (ID_NUMBER) ORDER BY s.len DESC;

-- [11] RCRA VIOSNC: for every 10y+ run, does it end the month a violation got its return-to-compliance date keyed in, and how old was the newest violation found inside the run
WITH y AS (
  SELECT ID_NUMBER, TO_NUMBER(LEFT(YRMONTH,4))*12 + TO_NUMBER(SUBSTR(YRMONTH,5,2)) AS mi
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_RCRA_VIOSNC_HISTORY WHERE VIO_FLAG = 'Y'),
g AS (SELECT y.*, mi - ROW_NUMBER() OVER (PARTITION BY ID_NUMBER ORDER BY mi) AS grp FROM y),
s AS (SELECT ID_NUMBER, grp, MIN(mi) AS s_mi, MAX(mi) AS e_mi, COUNT(*) AS len FROM g GROUP BY ID_NUMBER, grp HAVING COUNT(*) >= 120),
v AS (SELECT ID_NUMBER, YEAR(DATE_VIOLATION_DETERMINED)*12+MONTH(DATE_VIOLATION_DETERMINED) AS det_mi, YEAR(ACTUAL_RTC_DATE)*12+MONTH(ACTUAL_RTC_DATE) AS rtc_mi
      FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_RCRA_VIOLATIONS WHERE ID_NUMBER IN (SELECT ID_NUMBER FROM s)),
r AS (SELECT s.ID_NUMBER, s.grp, s.e_mi, s.len,
             MAX(IFF(v.rtc_mi BETWEEN s.e_mi AND s.e_mi+1, 1, 0)) AS ends_on_rtc,
             MAX(IFF(v.det_mi BETWEEN s.s_mi-24 AND s.e_mi, v.det_mi, NULL)) AS last_det_in_run
      FROM s LEFT JOIN v ON v.ID_NUMBER = s.ID_NUMBER GROUP BY 1,2,3,4)
SELECT COUNT(*) AS runs_10y, SUM(ends_on_rtc) AS end_on_rtc_month, ROUND(AVG(ends_on_rtc),3) AS share_end_on_rtc,
       MEDIAN((e_mi - last_det_in_run)/12) AS median_years_last_find_to_run_end,
       SUM(IFF((e_mi - last_det_in_run) >= 120,1,0)) AS runs_last_find_10y_before_end,
       SUM(IFF(e_mi >= 2025*12+1,1,0)) AS runs_ending_2025_on, SUM(IFF(e_mi >= 2025*12+1 AND len>=240,1,0)) AS runs20y_ending_2025_on,
       SUM(IFF(last_det_in_run IS NULL,1,0)) AS runs_no_violation_row
FROM r;

-- [12] SDWA PWS: count by activity and type, with people served
SELECT PWS_ACTIVITY_CODE, PWS_TYPE_CODE, COUNT(*) AS n, COUNT(DISTINCT PWSID) AS pwsids, SUM(POPULATION_SERVED_COUNT) AS pop, MEDIAN(POPULATION_SERVED_COUNT) AS med_pop,
       SUM(IFF(IS_WHOLESALER_IND='Y',1,0)) AS wholesalers, MAX(SUBMISSIONYEARQUARTER) AS q
FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_SDWA_SDWA_PUB_WATER_SYSTEMS GROUP BY ROLLUP(PWS_ACTIVITY_CODE, PWS_TYPE_CODE) ORDER BY 1,2;

-- [13] SDWA PWS: sample
SELECT PWSID, PWS_NAME, PWS_ACTIVITY_CODE, PWS_TYPE_CODE, OWNER_TYPE_CODE, POPULATION_SERVED_COUNT, SERVICE_CONNECTIONS_COUNT, PRIMARY_SOURCE_CODE, IS_WHOLESALER_IND, STATE_CODE, PRIMACY_AGENCY_CODE, ORG_NAME
FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_SDWA_SDWA_PUB_WATER_SYSTEMS LIMIT 5;

-- [14] SDWA PWS: active community systems by owner type, count and people served, with and without wholesalers
SELECT OWNER_TYPE_CODE, COUNT(*) AS systems, SUM(POPULATION_SERVED_COUNT) AS pop, SUM(IFF(IS_WHOLESALER_IND='Y',0,POPULATION_SERVED_COUNT)) AS pop_no_wholesale,
       MEDIAN(POPULATION_SERVED_COUNT) AS med_pop, SUM(IFF(POPULATION_SERVED_COUNT>=10000,1,0)) AS sys_10k_plus, SUM(IFF(POPULATION_SERVED_COUNT>=100000,1,0)) AS sys_100k_plus
FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_SDWA_SDWA_PUB_WATER_SYSTEMS WHERE PWS_ACTIVITY_CODE='A' AND PWS_TYPE_CODE='CWS'
GROUP BY ROLLUP(OWNER_TYPE_CODE) ORDER BY pop DESC;

-- [15] SDWA events x PWS: active community + non-transient systems by primacy agency, share with any LSLI row and any PFAS row, by count and by people
WITH ev AS (SELECT PWSID, MAX(IFF(EVENT_MILESTONE_CODE='LSLI',1,0)) AS has_lsli, MAX(IFF(EVENT_MILESTONE_CODE='PFAS',1,0)) AS has_pfas
            FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_SDWA_SDWA_EVENTS_MILESTONES GROUP BY 1),
p AS (SELECT PWSID, PRIMACY_AGENCY_CODE AS ag, PWS_TYPE_CODE, POPULATION_SERVED_COUNT AS pop FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_SDWA_SDWA_PUB_WATER_SYSTEMS
      WHERE PWS_ACTIVITY_CODE='A' AND PWS_TYPE_CODE IN ('CWS','NTNCWS'))
SELECT ag, COUNT(*) AS systems, SUM(COALESCE(has_lsli,0)) AS with_lsli, ROUND(AVG(COALESCE(has_lsli,0)),3) AS lsli_share,
       ROUND(SUM(IFF(has_lsli=1,pop,0))/NULLIF(SUM(pop),0),3) AS lsli_pop_share, ROUND(AVG(COALESCE(has_pfas,0)),3) AS pfas_share,
       SUM(pop) AS pop
FROM p LEFT JOIN ev USING (PWSID) GROUP BY ROLLUP(ag) ORDER BY systems DESC NULLS FIRST;

-- [16] SDWA events x PWS: lead action-level exceedance Tier 1 notice events (LALE), by state, with people served, and the largest systems
WITH l AS (SELECT PWSID, MIN(EVENT_ACTUAL_DATE) AS first_ale, COUNT(*) AS n_ev FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_SDWA_SDWA_EVENTS_MILESTONES WHERE EVENT_MILESTONE_CODE='LALE' GROUP BY 1),
p AS (SELECT PWSID, PWS_NAME, PRIMACY_AGENCY_CODE AS ag, PWS_TYPE_CODE, PWS_ACTIVITY_CODE, POPULATION_SERVED_COUNT AS pop FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_SDWA_SDWA_PUB_WATER_SYSTEMS)
SELECT 'STATE' AS kind, ag AS k, COUNT(*) AS systems, SUM(pop) AS pop, SUM(IFF(p.PWSID IS NULL,1,0)) AS no_pws_match, NULL AS name, MIN(first_ale) AS first_ale, NULL AS type
FROM l LEFT JOIN p USING (PWSID) GROUP BY ag
UNION ALL
SELECT 'TOP', PWSID, 1, pop, 0, PWS_NAME, first_ale, PWS_TYPE_CODE||'/'||PWS_ACTIVITY_CODE FROM l JOIN p USING (PWSID) QUALIFY ROW_NUMBER() OVER (ORDER BY pop DESC) <= 12
ORDER BY kind, systems DESC, pop DESC;

-- [17] SDWA violations: flag values and ID fill in the 2021+ window
SELECT IS_HEALTH_BASED_IND, VIOLATION_CATEGORY_CODE, COUNT(*) AS n_rows, COUNT(DISTINCT PWSID||'|'||VIOLATION_ID) AS viols, COUNT(VIOLATION_ID) AS id_filled
FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_SDWA_SDWA_VIOLATIONS_ENFORCEMENT WHERE COMPL_PER_BEGIN_DATE >= '2021-01-01'
GROUP BY ROLLUP(IS_HEALTH_BASED_IND, VIOLATION_CATEGORY_CODE) ORDER BY 1,2;

-- [18] SDWA PWS x violations: active community systems, owner type within size band, share with a health-based violation 2021+ and violations per system
WITH v AS (SELECT PWSID, COUNT(DISTINCT VIOLATION_ID) AS hb FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_SDWA_SDWA_VIOLATIONS_ENFORCEMENT
           WHERE IS_HEALTH_BASED_IND='Y' AND COMPL_PER_BEGIN_DATE >= '2021-01-01' AND VIOLATION_ID IS NOT NULL GROUP BY 1),
p AS (SELECT PWSID, OWNER_TYPE_CODE AS own, POPULATION_SERVED_COUNT AS pop,
             CASE WHEN POPULATION_SERVED_COUNT <= 500 THEN '1 <=500' WHEN POPULATION_SERVED_COUNT <= 3300 THEN '2 501-3.3K' WHEN POPULATION_SERVED_COUNT <= 10000 THEN '3 3.3K-10K'
                  WHEN POPULATION_SERVED_COUNT <= 100000 THEN '4 10K-100K' ELSE '5 100K+' END AS band
      FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_SDWA_SDWA_PUB_WATER_SYSTEMS WHERE PWS_ACTIVITY_CODE='A' AND PWS_TYPE_CODE='CWS' AND OWNER_TYPE_CODE IN ('L','P'))
SELECT band, own, COUNT(*) AS systems, SUM(pop) AS pop, ROUND(AVG(IFF(v.hb>0,1,0)),3) AS share_with_hb, ROUND(AVG(COALESCE(v.hb,0)),2) AS hb_per_system,
       SUM(IFF(v.hb>0,pop,0)) AS pop_in_hb_systems
FROM p LEFT JOIN v USING (PWSID) GROUP BY 1,2 ORDER BY 1,2;

-- [19] SDWA events x LCR samples: do LALE systems show a lead 90th percentile over 0.015 mg/L since mid-2024; and how many systems over 0.015 have no LALE row (peer: same states)
WITH pb AS (SELECT PWSID, MAX(SAMPLE_MEASURE) AS max_pb90, MAX(SAMPLING_END_DATE) AS last_end
            FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_SDWA_SDWA_LCR_SAMPLES
            WHERE CONTAMINANT_CODE='PB90' AND SAMPLING_END_DATE >= '2024-07-01' GROUP BY 1),
l AS (SELECT DISTINCT PWSID FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_SDWA_SDWA_EVENTS_MILESTONES WHERE EVENT_MILESTONE_CODE='LALE'),
lst AS (SELECT DISTINCT LEFT(PWSID,2) AS st FROM l),
a AS (SELECT COALESCE(pb.PWSID, l.PWSID) AS PWSID, pb.max_pb90, IFF(l.PWSID IS NOT NULL,1,0) AS has_lale FROM pb FULL OUTER JOIN l ON pb.PWSID = l.PWSID)
SELECT CASE WHEN LEFT(PWSID,2) IN (SELECT st FROM lst) THEN 'state has LALE rows' ELSE 'state has none' END AS peer,
       SUM(has_lale) AS lale_systems, SUM(IFF(has_lale=1 AND max_pb90 IS NULL,1,0)) AS lale_no_pb90_since_2024h2,
       SUM(IFF(has_lale=1 AND max_pb90 > 0.015,1,0)) AS lale_pb90_over_015,
       SUM(IFF(max_pb90 > 0.015,1,0)) AS systems_pb90_over_015, SUM(IFF(max_pb90 > 0.015 AND has_lale=0,1,0)) AS over_015_no_lale,
       SUM(IFF(max_pb90 IS NOT NULL,1,0)) AS systems_with_pb90
FROM a GROUP BY 1;

-- [20] SDWA site visits: count by reason, 1900 placeholders, date span, recent share
SELECT VISIT_REASON_CODE, COUNT(*) AS n, COUNT(DISTINCT PWSID) AS systems, SUM(IFF(VISIT_DATE < '1950-01-01',1,0)) AS pre1950,
       MIN(IFF(VISIT_DATE >= '1950-01-01', VISIT_DATE, NULL)) AS first_real, MAX(VISIT_DATE) AS last_date, SUM(IFF(VISIT_DATE >= '2021-07-01',1,0)) AS since_2021h2,
       COUNT(DISTINCT PWSID||'|'||VISIT_ID) AS pwsid_visit_ids
FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_SDWA_SDWA_SITE_VISITS GROUP BY ROLLUP(VISIT_REASON_CODE) ORDER BY n DESC;

-- [21] SDWA site visits: sample of sanitary surveys
SELECT PWSID, VISIT_ID, VISIT_DATE, AGENCY_TYPE_CODE, VISIT_REASON_CODE, MANAGEMENT_OPS_EVAL_CODE, SOURCE_WATER_EVAL_CODE, TREATMENT_EVAL_CODE, DISTRIBUTION_EVAL_CODE, COMPLIANCE_EVAL_CODE, VISIT_COMMENTS
FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_SDWA_SDWA_SITE_VISITS WHERE VISIT_REASON_CODE='SNSV' LIMIT 5;

-- [22] SDWA site visits: grade letters across the nine graded parts, sanitary surveys since 2021-07
SELECT part, grade, COUNT(*) AS n FROM (
  SELECT * FROM (SELECT MANAGEMENT_OPS_EVAL_CODE, SOURCE_WATER_EVAL_CODE, SECURITY_EVAL_CODE, PUMPS_EVAL_CODE, OTHER_EVAL_CODE, COMPLIANCE_EVAL_CODE,
                        DATA_VERIFICATION_EVAL_CODE, TREATMENT_EVAL_CODE, FINISHED_WATER_STOR_EVAL_CODE, DISTRIBUTION_EVAL_CODE, FINANCIAL_EVAL_CODE
                 FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_SDWA_SDWA_SITE_VISITS WHERE VISIT_REASON_CODE='SNSV' AND VISIT_DATE >= '2021-07-01')
  UNPIVOT (grade FOR part IN (MANAGEMENT_OPS_EVAL_CODE, SOURCE_WATER_EVAL_CODE, SECURITY_EVAL_CODE, PUMPS_EVAL_CODE, OTHER_EVAL_CODE, COMPLIANCE_EVAL_CODE,
                              DATA_VERIFICATION_EVAL_CODE, TREATMENT_EVAL_CODE, FINISHED_WATER_STOR_EVAL_CODE, DISTRIBUTION_EVAL_CODE, FINANCIAL_EVAL_CODE)))
GROUP BY ROLLUP(grade, part) HAVING part IS NULL OR grade IN ('S','D','M','R') ORDER BY grade, n DESC;

-- [23] SDWA site visits x PWS: active community systems by primacy agency, share with a sanitary survey in the last 5 years (since 2021-07-01), share never surveyed, people in systems with no survey in 5 years
WITH sv AS (SELECT PWSID, MAX(VISIT_DATE) AS last_snsv FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_SDWA_SDWA_SITE_VISITS
            WHERE VISIT_REASON_CODE='SNSV' AND VISIT_DATE >= '1950-01-01' GROUP BY 1),
p AS (SELECT PWSID, PRIMACY_AGENCY_CODE AS ag, POPULATION_SERVED_COUNT AS pop FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_SDWA_SDWA_PUB_WATER_SYSTEMS
      WHERE PWS_ACTIVITY_CODE='A' AND PWS_TYPE_CODE='CWS')
SELECT ag, COUNT(*) AS cws, ROUND(AVG(IFF(last_snsv >= '2021-07-01',1,0)),3) AS share_5y, ROUND(AVG(IFF(last_snsv >= '2023-07-01',1,0)),3) AS share_3y,
       ROUND(AVG(IFF(last_snsv IS NULL,1,0)),3) AS share_never, SUM(IFF(COALESCE(last_snsv,'1900-01-01') < '2021-07-01', pop, 0)) AS pop_no_survey_5y,
       SUM(IFF(COALESCE(last_snsv,'1900-01-01') < '2021-07-01' AND pop >= 10000, 1, 0)) AS big_no_survey_5y, SUM(pop) AS pop
FROM p LEFT JOIN sv USING (PWSID) GROUP BY ROLLUP(ag) ORDER BY pop_no_survey_5y DESC NULLS FIRST;

-- [24] SDWA site visits x PWS: largest active community systems with no sanitary survey since 2021-07-01, with their last survey, last visit of any kind, wholesaler and owner flags
WITH sv AS (SELECT PWSID, MAX(IFF(VISIT_REASON_CODE='SNSV', VISIT_DATE, NULL)) AS last_snsv, MAX(VISIT_DATE) AS last_any,
                   MAX_BY(VISIT_REASON_CODE, VISIT_DATE) AS last_any_code, COUNT(IFF(VISIT_REASON_CODE='SNSV',1,NULL)) AS n_snsv
            FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_SDWA_SDWA_SITE_VISITS WHERE VISIT_DATE >= '1950-01-01' GROUP BY 1),
p AS (SELECT PWSID, PWS_NAME, PRIMACY_AGENCY_CODE AS ag, POPULATION_SERVED_COUNT AS pop, OWNER_TYPE_CODE AS own, IS_WHOLESALER_IND AS wh, PRIMARY_SOURCE_CODE AS src
      FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_SDWA_SDWA_PUB_WATER_SYSTEMS WHERE PWS_ACTIVITY_CODE='A' AND PWS_TYPE_CODE='CWS' AND POPULATION_SERVED_COUNT >= 10000)
SELECT p.PWSID, p.PWS_NAME, p.ag, p.pop, p.own, p.wh, p.src, sv.last_snsv, sv.n_snsv, sv.last_any, sv.last_any_code
FROM p LEFT JOIN sv USING (PWSID)
WHERE COALESCE(sv.last_snsv,'1900-01-01') < '2021-07-01'
ORDER BY p.pop DESC LIMIT 30;

-- [25] SDWA site visits x PWS: counting partial and follow-up surveys too (SNSV, SNSP, SNSF), active community systems over 10K people with none since 2021-07-01 (5y) and none since 2023-07-01 (3y, the federal clock for community systems), by state
WITH sv AS (SELECT PWSID, MAX(VISIT_DATE) AS last_s FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_SDWA_SDWA_SITE_VISITS
            WHERE VISIT_REASON_CODE IN ('SNSV','SNSP','SNSF') AND VISIT_DATE >= '1950-01-01' GROUP BY 1),
p AS (SELECT PWSID, PRIMACY_AGENCY_CODE AS ag, POPULATION_SERVED_COUNT AS pop, IS_WHOLESALER_IND AS wh FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_SDWA_SDWA_PUB_WATER_SYSTEMS
      WHERE PWS_ACTIVITY_CODE='A' AND PWS_TYPE_CODE='CWS' AND POPULATION_SERVED_COUNT >= 10000)
SELECT ag, COUNT(*) AS big_cws, SUM(IFF(COALESCE(last_s,'1900-01-01') < '2021-07-01',1,0)) AS none_5y, SUM(IFF(COALESCE(last_s,'1900-01-01') < '2021-07-01',pop,0)) AS pop_none_5y,
       SUM(IFF(COALESCE(last_s,'1900-01-01') < '2021-07-01' AND wh='N',pop,0)) AS pop_none_5y_retail,
       SUM(IFF(COALESCE(last_s,'1900-01-01') < '2023-07-01',1,0)) AS none_3y, SUM(IFF(COALESCE(last_s,'1900-01-01') < '2023-07-01',pop,0)) AS pop_none_3y,
       ROUND(AVG(IFF(COALESCE(last_s,'1900-01-01') < '2023-07-01',1,0)),3) AS share_none_3y
FROM p LEFT JOIN sv USING (PWSID) GROUP BY ROLLUP(ag) ORDER BY pop_none_5y DESC NULLS FIRST LIMIT 16;

-- [26] FracFocus list: count, distinct disclosures and wells, water volume fill and outliers, by form version
SELECT FF_VERSION, COUNT(*) AS n, COUNT(DISTINCT DISCLOSURE_ID) AS disclosures, COUNT(DISTINCT API_NUMBER) AS wells,
       COUNT(TOTAL_BASE_WATER_VOLUME) AS water_filled, SUM(IFF(TOTAL_BASE_WATER_VOLUME = 0,1,0)) AS water_zero,
       MEDIAN(NULLIF(TOTAL_BASE_WATER_VOLUME,0)) AS med_water_gal, SUM(IFF(TOTAL_BASE_WATER_VOLUME > 50000000,1,0)) AS over_50m, SUM(IFF(TOTAL_BASE_WATER_VOLUME > 100000000,1,0)) AS over_100m,
       SUM(IFF(TOTAL_BASE_WATER_VOLUME BETWEEN 1 AND 10000,1,0)) AS under_10k_gal, COUNT(DISTINCT STATE_NAME) AS states, MIN(_SRC_FILE) AS a_file, COUNT(DISTINCT _SRC_FILE) AS files
FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_FRACFOCUS_DISCLOSURE_LIST GROUP BY ROLLUP(FF_VERSION) ORDER BY 1;

-- [27] FracFocus list: sample
SELECT DISCLOSURE_ID, API_NUMBER, STATE_NAME, COUNTY_NAME, OPERATOR_NAME, WELL_NAME, FF_VERSION, TVD, TOTAL_BASE_WATER_VOLUME, TOTAL_BASE_NON_WATER_VOLUME, _SRC_FILE
FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_FRACFOCUS_DISCLOSURE_LIST LIMIT 5;

-- [28] FracFocus water source x list: what the water-type labels are, and how many list disclosures land in the water source table
WITH l AS (SELECT DISTINCT DISCLOSURE_ID FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_FRACFOCUS_DISCLOSURE_LIST),
w AS (SELECT DISCLOSURE_ID, DESCRIPTION, PERCENT FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_FRACFOCUS_WATER_SOURCE)
SELECT COALESCE(DESCRIPTION,'<ALL>') AS description, COUNT(*) AS n_rows, COUNT(DISTINCT w.DISCLOSURE_ID) AS disclosures,
       COUNT(DISTINCT IFF(l.DISCLOSURE_ID IS NOT NULL, w.DISCLOSURE_ID, NULL)) AS in_list, (SELECT COUNT(*) FROM l) AS list_disclosures,
       MEDIAN(TRY_TO_DOUBLE(PERCENT::STRING)) AS med_pct
FROM w LEFT JOIN l ON l.DISCLOSURE_ID = w.DISCLOSURE_ID GROUP BY ROLLUP(DESCRIPTION) ORDER BY n_rows DESC LIMIT 20;

-- [29] FracFocus list: top 15 counties by total base water (jobs over 100M gallons dropped as likely typos), with median per job overall and on form v4 only
SELECT STATE_NAME, INITCAP(COUNTY_NAME) AS county, COUNT(*) AS jobs, ROUND(SUM(TOTAL_BASE_WATER_VOLUME)/1e9,1) AS bn_gal,
       ROUND(MEDIAN(TOTAL_BASE_WATER_VOLUME)/1e6,1) AS med_mgal, ROUND(MEDIAN(IFF(FF_VERSION='4',TOTAL_BASE_WATER_VOLUME,NULL))/1e6,1) AS med_mgal_v4,
       SUM(IFF(FF_VERSION='4',1,0)) AS jobs_v4, ROUND(SUM(TOTAL_BASE_WATER_VOLUME)/SUM(SUM(TOTAL_BASE_WATER_VOLUME)) OVER (),3) AS share_of_all
FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_FRACFOCUS_DISCLOSURE_LIST
WHERE TOTAL_BASE_WATER_VOLUME > 0 AND TOTAL_BASE_WATER_VOLUME <= 100000000
GROUP BY 1,2 QUALIFY ROW_NUMBER() OVER (ORDER BY SUM(TOTAL_BASE_WATER_VOLUME) DESC) <= 15 ORDER BY bn_gal DESC;

-- [30] FracFocus list: Permian operators (Delaware + Midland basin counties), form v4 jobs only so the era lines up; median gallons per job vs the basin median, operators with 150+ v4 jobs
WITH j AS (SELECT UPPER(OPERATOR_NAME) AS op, TOTAL_BASE_WATER_VOLUME AS w, TVD
           FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_FRACFOCUS_DISCLOSURE_LIST
           WHERE FF_VERSION='4' AND TOTAL_BASE_WATER_VOLUME > 0 AND TOTAL_BASE_WATER_VOLUME <= 100000000
             AND ((STATE_NAME ILIKE 'texas' AND UPPER(COUNTY_NAME) IN ('REEVES','LOVING','WARD','CULBERSON','PECOS','WINKLER','MIDLAND','MARTIN','HOWARD','UPTON','REAGAN','GLASSCOCK','ANDREWS','ECTOR','CRANE','BORDEN','DAWSON','IRION','CROCKETT'))
               OR (STATE_NAME ILIKE 'new mexico' AND UPPER(COUNTY_NAME) IN ('LEA','EDDY'))))
SELECT op, COUNT(*) AS jobs_v4, ROUND(SUM(w)/1e9,2) AS bn_gal, ROUND(MEDIAN(w)/1e6,1) AS med_mgal, ROUND(MEDIAN(w)/(SELECT MEDIAN(w) FROM j),2) AS x_basin_median,
       ROUND(MEDIAN(TVD)) AS med_tvd, (SELECT COUNT(*) FROM j) AS basin_jobs, ROUND((SELECT MEDIAN(w) FROM j)/1e6,1) AS basin_med_mgal
FROM j GROUP BY op HAVING COUNT(*) >= 150 ORDER BY med_mgal DESC;

-- [31] SDWA site visits x PWS: active community systems whose sanitary surveys since 2016 graded any part S (significant deficiency) on 2+ separate surveys; totals, then the largest 15
WITH s AS (SELECT PWSID, COUNT(DISTINCT VISIT_DATE) AS surveys, COUNT(DISTINCT IFF('S' IN (MANAGEMENT_OPS_EVAL_CODE, SOURCE_WATER_EVAL_CODE, SECURITY_EVAL_CODE, PUMPS_EVAL_CODE, OTHER_EVAL_CODE,
                        COMPLIANCE_EVAL_CODE, DATA_VERIFICATION_EVAL_CODE, TREATMENT_EVAL_CODE, FINISHED_WATER_STOR_EVAL_CODE, DISTRIBUTION_EVAL_CODE, FINANCIAL_EVAL_CODE), VISIT_DATE, NULL)) AS s_surveys,
                  MAX(IFF('S' IN (MANAGEMENT_OPS_EVAL_CODE, SOURCE_WATER_EVAL_CODE, TREATMENT_EVAL_CODE, FINISHED_WATER_STOR_EVAL_CODE, DISTRIBUTION_EVAL_CODE, DATA_VERIFICATION_EVAL_CODE, COMPLIANCE_EVAL_CODE, PUMPS_EVAL_CODE, OTHER_EVAL_CODE, SECURITY_EVAL_CODE, FINANCIAL_EVAL_CODE), VISIT_DATE, NULL)) AS last_s
           FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_SDWA_SDWA_SITE_VISITS WHERE VISIT_REASON_CODE IN ('SNSV','SNSP') AND VISIT_DATE >= '2016-01-01' GROUP BY 1),
p AS (SELECT PWSID, PWS_NAME, PRIMACY_AGENCY_CODE AS ag, POPULATION_SERVED_COUNT AS pop, OWNER_TYPE_CODE AS own FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_SDWA_SDWA_PUB_WATER_SYSTEMS
      WHERE PWS_ACTIVITY_CODE='A' AND PWS_TYPE_CODE='CWS'),
j AS (SELECT * FROM p JOIN s USING (PWSID))
SELECT 'TOTAL' AS kind, NULL AS PWSID, 'surveyed CWS: '||COUNT(*)||'; with 1+ S survey: '||SUM(IFF(s_surveys>=1,1,0))||'; 2+: '||SUM(IFF(s_surveys>=2,1,0))||'; 3+: '||SUM(IFF(s_surveys>=3,1,0)) AS name,
       NULL AS ag, SUM(IFF(s_surveys>=2,pop,0)) AS pop, NULL AS own, NULL AS surveys, SUM(IFF(s_surveys>=2 AND pop>=10000,1,0)) AS s_surveys, NULL AS last_s FROM j
UNION ALL
SELECT * FROM (SELECT 'TOP', PWSID, PWS_NAME, ag, pop, own, surveys, s_surveys, last_s FROM j WHERE s_surveys >= 2 ORDER BY pop DESC LIMIT 15)
ORDER BY kind DESC, pop DESC;

-- [32] SDWA events x LCR samples x PWS: systems with a lead 90th percentile over 0.015 mg/L in a sampling period ending on/after 2024-10-16 (when the Tier 1 notice rule began), split by whether a LALE row exists, with people served
WITH pb AS (SELECT PWSID, MAX(SAMPLE_MEASURE) AS max_pb90 FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_SDWA_SDWA_LCR_SAMPLES
            WHERE CONTAMINANT_CODE='PB90' AND SAMPLING_END_DATE >= '2024-10-16' GROUP BY 1 HAVING MAX(SAMPLE_MEASURE) > 0.015),
l AS (SELECT DISTINCT PWSID FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_SDWA_SDWA_EVENTS_MILESTONES WHERE EVENT_MILESTONE_CODE='LALE'),
lst AS (SELECT DISTINCT LEFT(PWSID,2) AS st FROM l),
p AS (SELECT PWSID, POPULATION_SERVED_COUNT AS pop, PWS_TYPE_CODE AS t FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_SDWA_SDWA_PUB_WATER_SYSTEMS)
SELECT IFF(LEFT(pb.PWSID,2) IN (SELECT st FROM lst),'state has LALE rows','state has none') AS peer, IFF(l.PWSID IS NOT NULL,'LALE row','no LALE row') AS lale,
       COUNT(*) AS systems, SUM(p.pop) AS pop, SUM(IFF(p.t='CWS',1,0)) AS cws, MAX(p.pop) AS max_pop, SUM(IFF(p.PWSID IS NULL,1,0)) AS no_pws_match
FROM pb LEFT JOIN l ON l.PWSID = pb.PWSID LEFT JOIN p ON p.PWSID = pb.PWSID GROUP BY 1,2 ORDER BY 1,2;

-- [33] SDWA site visits x PWS: clean list, largest active community systems with no full, partial or follow-up sanitary survey (SNSV, SNSP, SNSF) since 2021-07-01
WITH sv AS (SELECT PWSID, MAX(IFF(VISIT_REASON_CODE IN ('SNSV','SNSP','SNSF'), VISIT_DATE, NULL)) AS last_s, MAX(VISIT_DATE) AS last_any, MAX_BY(VISIT_REASON_CODE, VISIT_DATE) AS last_any_code
            FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_SDWA_SDWA_SITE_VISITS WHERE VISIT_DATE >= '1950-01-01' GROUP BY 1),
p AS (SELECT PWSID, PWS_NAME, PRIMACY_AGENCY_CODE AS ag, POPULATION_SERVED_COUNT AS pop, OWNER_TYPE_CODE AS own, IS_WHOLESALER_IND AS wh
      FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_SDWA_SDWA_PUB_WATER_SYSTEMS WHERE PWS_ACTIVITY_CODE='A' AND PWS_TYPE_CODE='CWS' AND POPULATION_SERVED_COUNT >= 10000)
SELECT p.PWSID, p.PWS_NAME, p.ag, p.pop, p.own, p.wh, sv.last_s, sv.last_any, sv.last_any_code
FROM p LEFT JOIN sv USING (PWSID) WHERE COALESCE(sv.last_s,'1900-01-01') < '2021-07-01' ORDER BY p.pop DESC LIMIT 20;

