-- deep-3, coverage round 2, 2026-09-24. Door: Python (connect/db.py). Read-only.
-- Every connection first ran the two session settings: statement timeout 300s, query tag 'coverage-r2-2026-09-24'.

-- [1] Row counts, distinct ids, date ranges, all five tables
SELECT table_schema, table_name, row_count
FROM LIBRARY_MARTS.INFORMATION_SCHEMA.TABLES
WHERE table_name IN ('FCT_LIBRARY_SNAPSHOT')
   OR table_name ILIKE '%FEC%' OR table_name ILIKE '%FEMA%' OR table_name ILIKE '%PHMSA%'
   OR table_name ILIKE '%ECHO%' OR table_name ILIKE '%EPSTEIN%' OR table_name ILIKE '%ICIS%'
   OR table_name ILIKE '%LIBRARY_SNAP%' OR table_name ILIKE '%DISASTER%'
ORDER BY 1, 2;
-- NOTE on [1]: a scratch-file name collision with another agent ran their read-only schema listing instead of mine. Counted against my budget; no use to this report.

-- [2] COUNT(*), distinct ids, date ranges, all five tables
SELECT 'CS' t, COUNT(*) n, COUNT(DISTINCT NPDES_ID) ids, COUNT(DISTINCT NPDES_VIOLATION_ID) vids, MIN(SCHEDULE_DATE)::string mn, MAX(SCHEDULE_DATE)::string mx FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_NPDES_NPDES_CS_VIOLATIONS
UNION ALL SELECT 'PS', COUNT(*), COUNT(DISTINCT NPDES_ID), COUNT(DISTINCT NPDES_VIOLATION_ID), MIN(SCHEDULE_DATE)::string, MAX(SCHEDULE_DATE)::string FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_NPDES_NPDES_PS_VIOLATIONS
UNION ALL SELECT 'SE', COUNT(*), COUNT(DISTINCT NPDES_ID), COUNT(DISTINCT NPDES_VIOLATION_ID), MIN(SINGLE_EVENT_VIOLATION_DATE)::string, MAX(SINGLE_EVENT_VIOLATION_DATE)::string FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_NPDES_NPDES_SE_VIOLATIONS
UNION ALL SELECT 'QNCR', COUNT(*), COUNT(DISTINCT NPDES_ID), COUNT(DISTINCT NPDES_ID||YEARQTR), MIN(YEARQTR)::string, MAX(YEARQTR)::string FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_NPDES_NPDES_QNCR_HISTORY
UNION ALL SELECT 'RCRA', COUNT(*), COUNT(DISTINCT ID_NUMBER), COUNT(DISTINCT EVALUATION_RECORD_ID), MIN(EVALUATION_START_DATE)::string, MAX(EVALUATION_START_DATE)::string FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_RCRA_EVALUATIONS;

-- [3] LIMIT 5 sample of every column, all five tables
(SELECT 'CS' t, OBJECT_CONSTRUCT(*)::string r FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_NPDES_NPDES_CS_VIOLATIONS LIMIT 5)
UNION ALL (SELECT 'PS', OBJECT_CONSTRUCT(*)::string FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_NPDES_NPDES_PS_VIOLATIONS LIMIT 5)
UNION ALL (SELECT 'SE', OBJECT_CONSTRUCT(*)::string FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_NPDES_NPDES_SE_VIOLATIONS LIMIT 5)
UNION ALL (SELECT 'QNCR', OBJECT_CONSTRUCT(*)::string FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_NPDES_NPDES_QNCR_HISTORY LIMIT 5)
UNION ALL (SELECT 'RCRA', OBJECT_CONSTRUCT(*)::string FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_RCRA_EVALUATIONS LIMIT 5);

-- [4] CS and PS: value profile of coded columns, event-id repeats, states
WITH cs AS (SELECT * FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_NPDES_NPDES_CS_VIOLATIONS),
ps AS (SELECT * FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_NPDES_NPDES_PS_VIOLATIONS),
p AS (
  SELECT 'CS' tb, 'vcode' col, VIOLATION_CODE||' | '||VIOLATION_DESC v, COUNT(*) n FROM cs GROUP BY 3
  UNION ALL SELECT 'CS','event', SCHEDULE_EVENT_CODE||' | '||SCHEDULE_EVENT_DESC, COUNT(*) FROM cs GROUP BY 3
  UNION ALL SELECT 'CS','rnc_det', RNC_DETECTION_CODE||' | '||RNC_DETECTION_DESC, COUNT(*) FROM cs GROUP BY 3
  UNION ALL SELECT 'CS','rnc_res', RNC_RESOLUTION_CODE||' | '||RNC_RESOLUTION_DESC, COUNT(*) FROM cs GROUP BY 3
  UNION ALL SELECT 'CS','actual_null', IFF(ACTUAL_DATE IS NULL,'null','filled'), COUNT(*) FROM cs GROUP BY 3
  UNION ALL SELECT 'CS','sched_nmbr', COMP_SCHEDULE_NMBR::string, COUNT(*) FROM cs GROUP BY 3
  UNION ALL SELECT 'CS','state', LEFT(NPDES_ID,2), COUNT(*) FROM cs GROUP BY 3
  UNION ALL SELECT 'CS','events_per_eventid', c::string, COUNT(*) FROM (SELECT COMP_SCHEDULE_EVENT_ID, COUNT(*) c FROM cs GROUP BY 1) GROUP BY 3
  UNION ALL SELECT 'PS','vcode', VIOLATION_CODE||' | '||VIOLATION_DESC, COUNT(*) FROM ps GROUP BY 3
  UNION ALL SELECT 'PS','event', SCHEDULE_EVENT_CODE||' | '||SCHEDULE_EVENT_DESC, COUNT(*) FROM ps GROUP BY 3
  UNION ALL SELECT 'PS','rnc_det', RNC_DETECTION_CODE||' | '||RNC_DETECTION_DESC, COUNT(*) FROM ps GROUP BY 3
  UNION ALL SELECT 'PS','rnc_res', RNC_RESOLUTION_CODE||' | '||RNC_RESOLUTION_DESC, COUNT(*) FROM ps GROUP BY 3
  UNION ALL SELECT 'PS','actual_null', IFF(ACTUAL_DATE IS NULL,'null','filled'), COUNT(*) FROM ps GROUP BY 3
  UNION ALL SELECT 'PS','state', LEFT(NPDES_ID,2), COUNT(*) FROM ps GROUP BY 3
  UNION ALL SELECT 'PS','events_per_eventid', c::string, COUNT(*) FROM (SELECT PERM_SCHEDULE_EVENT_ID, COUNT(*) c FROM ps GROUP BY 1) GROUP BY 3
)
SELECT tb, col, v, n FROM p QUALIFY ROW_NUMBER() OVER (PARTITION BY tb, col ORDER BY n DESC) <= 14 ORDER BY tb, col, n DESC;

-- [5] SE, QNCR, RCRA: value profile; QNCR letter vs any-violation share; RCRA hit rate by agency and type; RCRA duplicate check
WITH se AS (SELECT * FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_NPDES_NPDES_SE_VIOLATIONS),
q AS (SELECT HLRNC, YEARQTR,
        IFF(TRY_TO_NUMBER(NUME90_Q)>0 OR TRY_TO_NUMBER(NUMCVDT)>0 OR TRY_TO_NUMBER(NUMSVCD)>0 OR TRY_TO_NUMBER(NUMPSCH)>0 OR TRY_TO_NUMBER(NUMD8090_Q)>0,1,0) anyv,
        IFF(TRY_TO_NUMBER(NUME90_Q) IS NULL OR TRY_TO_NUMBER(NUMD8090_Q) IS NULL,1,0) nonnum
      FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_NPDES_NPDES_QNCR_HISTORY),
r AS (SELECT * FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_RCRA_EVALUATIONS),
p AS (
  SELECT 'SE' tb, 'vcode' col, VIOLATION_CODE||' | '||VIOLATION_DESC v, COUNT(*) n, NULL x FROM se GROUP BY 3
  UNION ALL SELECT 'SE','agency', SINGLE_EVENT_AGENCY_TYPE_CODE, COUNT(*), NULL FROM se GROUP BY 3
  UNION ALL SELECT 'SE','rnc_det', RNC_DETECTION_CODE||' | '||RNC_DETECTION_DESC, COUNT(*), NULL FROM se GROUP BY 3
  UNION ALL SELECT 'SE','rnc_res', RNC_RESOLUTION_CODE||' | '||RNC_RESOLUTION_DESC, COUNT(*), NULL FROM se GROUP BY 3
  UNION ALL SELECT 'SE','state', LEFT(NPDES_ID,2), COUNT(*), NULL FROM se GROUP BY 3
  UNION ALL SELECT 'SE','year', YEAR(SINGLE_EVENT_VIOLATION_DATE)::string, COUNT(*), NULL FROM se GROUP BY 3
  UNION ALL SELECT 'SE','comment', IFF(NULLIF(TRIM(SINGLE_EVENT_VIOLATION_COMMENT),'') IS NULL,'blank','filled'), COUNT(*), NULL FROM se GROUP BY 3
  UNION ALL SELECT 'QN','hlrnc', HLRNC, COUNT(*), ROUND(AVG(anyv),3) FROM q GROUP BY 3
  UNION ALL SELECT 'QN','future_qtr', IFF(YEARQTR::int > 20263,'after 2026Q3','ok'), COUNT(*), ROUND(AVG(anyv),3) FROM q GROUP BY 3
  UNION ALL SELECT 'QN','nonnumeric', nonnum::string, COUNT(*), NULL FROM q GROUP BY 3
  UNION ALL SELECT 'QN','year', LEFT(YEARQTR,4), COUNT(*), ROUND(AVG(anyv),3) FROM q GROUP BY 3
  UNION ALL SELECT 'RC','agency', EVALUATION_AGENCY, COUNT(*), ROUND(AVG(IFF(FOUND_VIOLATION='Y',1,0)),3) FROM r GROUP BY 3
  UNION ALL SELECT 'RC','found', FOUND_VIOLATION, COUNT(*), NULL FROM r GROUP BY 3
  UNION ALL SELECT 'RC','etype', EVALUATION_TYPE||' | '||EVALUATION_DESC, COUNT(*), ROUND(AVG(IFF(FOUND_VIOLATION='Y',1,0)),3) FROM r GROUP BY 3
  UNION ALL SELECT 'RC','baddate', IFF(YEAR(EVALUATION_START_DATE)<1980,'pre-1980','ok'), COUNT(*), NULL FROM r GROUP BY 3
  UNION ALL SELECT 'RC','dupes', c::string, COUNT(*), NULL FROM (SELECT ID_NUMBER, EVALUATION_START_DATE, EVALUATION_TYPE, EVALUATION_AGENCY, COUNT(*) c FROM r GROUP BY 1,2,3,4) GROUP BY 3
)
SELECT tb, col, v, n, x FROM p QUALIFY ROW_NUMBER() OVER (PARTITION BY tb, col ORDER BY IFF(col='year', TRY_TO_NUMBER(v), n) DESC) <= IFF(col='year', 60, 16) ORDER BY tb, col, IFF(col='year', TRY_TO_NUMBER(v), n) DESC;

-- [6] CS: never-met milestones per permit (dedup by event id), still-alive permits, names, formal actions
WITH ev AS (
  SELECT NPDES_ID, COMP_SCHEDULE_EVENT_ID, MAX(SCHEDULE_EVENT_CODE) code, MIN(SCHEDULE_DATE) due, MAX(ACTUAL_DATE) done
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_NPDES_NPDES_CS_VIOLATIONS GROUP BY 1,2),
f AS (
  SELECT NPDES_ID, COUNT(*) ms, SUM(IFF(done IS NULL,1,0)) unmet,
    SUM(IFF(done IS NULL AND code IN ('CS015','CS016','CS017','CS031','CS022'),1,0)) unmet_work,
    SUM(IFF(done IS NULL AND code = 'CS001',1,0)) unmet_pay,
    MIN(IFF(done IS NULL, due, NULL)) oldest_unmet,
    MAX(due) last_due
  FROM ev GROUP BY 1),
qa AS (
  SELECT NPDES_ID, MAX(TRY_TO_NUMBER(YEARQTR)) lastq,
    SUM(IFF(TRY_TO_NUMBER(YEARQTR) BETWEEN 20211 AND 20254 AND TRY_TO_NUMBER(NUME90_Q) > 0,1,0)) eff_q_21_25
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_NPDES_NPDES_QNCR_HISTORY
  WHERE TRY_TO_NUMBER(YEARQTR) <= 20263 GROUP BY 1),
fe AS (
  SELECT NPDES_ID, COUNT(*) acts, SUM(COALESCE(FED_PENALTY_ASSESSED_AMT,0) + COALESCE(STATE_LOCAL_PENALTY_AMT,0)) pen
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_NPDES_NPDES_FORMAL_ENFORCEMENT_ACTIONS GROUP BY 1),
j AS (
  SELECT f.*, fac.FACILITY_NAME, fac.CITY, fac.FACILITY_TYPE_CODE ftype, qa.lastq, qa.eff_q_21_25, fe.acts, fe.pen,
    IFF(fac.NPDES_ID IS NULL,0,1) in_fac, IFF(fe.NPDES_ID IS NULL,0,1) in_fe, IFF(qa.lastq >= 20251,1,0) alive
  FROM f
  LEFT JOIN LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_NPDES_ICIS_FACILITIES fac ON fac.NPDES_ID = f.NPDES_ID
  LEFT JOIN qa ON qa.NPDES_ID = f.NPDES_ID
  LEFT JOIN fe ON fe.NPDES_ID = f.NPDES_ID)
SELECT * FROM (
  SELECT 0 k, 'TOTAL' NPDES_ID, SUM(ms) ms, SUM(unmet) unmet, SUM(unmet_work) unmet_work, SUM(unmet_pay) unmet_pay,
    MIN(oldest_unmet) oldest_unmet, COUNT(*)::string last_due,
    'permits, in_fac=' || SUM(in_fac) || ' in_fe=' || SUM(in_fe) || ' alive=' || SUM(alive) FACILITY_NAME,
    'unmet on alive=' || SUM(IFF(alive=1, unmet, 0)) || ' work on alive=' || SUM(IFF(alive=1, unmet_work, 0)) || ' pay on alive=' || SUM(IFF(alive=1, unmet_pay, 0)) CITY,
    NULL ftype, NULL lastq, NULL eff_q_21_25, NULL acts, NULL pen
  FROM j
  UNION ALL
  SELECT * FROM (SELECT 1, NPDES_ID, ms, unmet, unmet_work, unmet_pay, oldest_unmet, last_due::string, FACILITY_NAME, CITY, ftype, lastq, eff_q_21_25, acts, pen
    FROM j WHERE alive = 1 ORDER BY unmet_work DESC, unmet DESC LIMIT 25)
) ORDER BY k, unmet_work DESC, unmet DESC;

-- [7] PS: never-met permit milestones due 2016-2025H1, work vs paperwork by keyword, top alive permits on work
WITH ev AS (
  SELECT NPDES_ID, PERM_SCHEDULE_EVENT_ID, MAX(SCHEDULE_EVENT_CODE) code, MAX(SCHEDULE_EVENT_DESC) d, MIN(SCHEDULE_DATE) due, MAX(ACTUAL_DATE) done
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_NPDES_NPDES_PS_VIOLATIONS GROUP BY 1,2),
c AS (
  SELECT *, IFF(REGEXP_LIKE(UPPER(d), '.*(CONSTRUCT|ACHIEVE FINAL|FINAL COMPLIANCE|ATTAIN|UPGRADE|INSTALL|ELIMINAT|COMPLETE REQUIRED WORK|COMMENCE REQUIRED WORK|IMPLEMENT).*'), 'work', 'paper') cls
  FROM ev WHERE due BETWEEN '2016-01-01' AND '2025-06-30'),
qa AS (
  SELECT NPDES_ID, MAX(TRY_TO_NUMBER(YEARQTR)) lastq
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_NPDES_NPDES_QNCR_HISTORY WHERE TRY_TO_NUMBER(YEARQTR) <= 20263 GROUP BY 1),
ca AS (SELECT c.*, IFF(qa.lastq >= 20251, 1, 0) alive FROM c LEFT JOIN qa ON qa.NPDES_ID = c.NPDES_ID),
descs AS (
  SELECT 'A_desc' part, cls || ' | ' || d label, COUNT(*) n, SUM(IFF(done IS NULL,1,0)) unmet, SUM(IFF(done IS NULL AND alive=1,1,0)) unmet_alive, NULL nm, NULL ft
  FROM ca GROUP BY 1,2 QUALIFY ROW_NUMBER() OVER (ORDER BY SUM(IFF(done IS NULL,1,0)) DESC) <= 25
  OR (cls = 'work' AND ROW_NUMBER() OVER (PARTITION BY cls ORDER BY SUM(IFF(done IS NULL,1,0)) DESC) <= 12)),
tot AS (
  SELECT 'B_total' part, cls label, COUNT(*) n, SUM(IFF(done IS NULL,1,0)) unmet, SUM(IFF(done IS NULL AND alive=1,1,0)) unmet_alive, COUNT(DISTINCT IFF(done IS NULL AND alive=1, NPDES_ID, NULL))::string nm, NULL ft
  FROM ca GROUP BY 1,2),
tops AS (
  SELECT 'C_permit' part, ca.NPDES_ID label, COUNT(*) n, SUM(IFF(done IS NULL,1,0)) unmet, MIN(IFF(done IS NULL, due, NULL))::string unmet_alive, MAX(fac.FACILITY_NAME) || ' / ' || MAX(fac.CITY) nm, MAX(fac.FACILITY_TYPE_CODE) ft
  FROM ca LEFT JOIN LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_NPDES_ICIS_FACILITIES fac ON fac.NPDES_ID = ca.NPDES_ID
  WHERE cls = 'work' AND alive = 1 GROUP BY 1,2 QUALIFY ROW_NUMBER() OVER (ORDER BY SUM(IFF(done IS NULL,1,0)) DESC) <= 20)
SELECT part, label, n, unmet, unmet_alive::string unmet_alive, nm, ft FROM descs
UNION ALL SELECT part, label, n, unmet, unmet_alive::string, nm, ft FROM tot
UNION ALL SELECT * FROM tops
ORDER BY part, unmet DESC;

-- [8] PS retry: never-met permit milestones due 2016-2025H1, work vs paperwork, top alive permits on work
WITH ev AS (
  SELECT NPDES_ID, PERM_SCHEDULE_EVENT_ID, MAX(SCHEDULE_EVENT_CODE) code, MAX(SCHEDULE_EVENT_DESC) d, MIN(SCHEDULE_DATE) due, MAX(ACTUAL_DATE) done
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_NPDES_NPDES_PS_VIOLATIONS GROUP BY 1,2),
c AS (
  SELECT *, IFF(REGEXP_LIKE(UPPER(d), '.*(CONSTRUCT|ACHIEVE FINAL|FINAL COMPLIANCE|ATTAIN|UPGRADE|INSTALL|ELIMINAT|COMPLETE REQUIRED WORK|COMMENCE REQUIRED WORK|IMPLEMENT).*'), 'work', 'paper') cls
  FROM ev WHERE due BETWEEN '2016-01-01' AND '2025-06-30'),
qa AS (
  SELECT NPDES_ID, MAX(TRY_TO_NUMBER(YEARQTR)) lastq
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_NPDES_NPDES_QNCR_HISTORY WHERE TRY_TO_NUMBER(YEARQTR) <= 20263 GROUP BY 1),
ca AS (SELECT c.*, IFF(qa.lastq >= 20251, 1, 0) alive FROM c LEFT JOIN qa ON qa.NPDES_ID = c.NPDES_ID),
descs AS (
  SELECT 'A_desc' part, cls || ' | ' || d label, COUNT(*) n, SUM(IFF(done IS NULL,1,0)) unmet, SUM(IFF(done IS NULL AND alive=1,1,0)) unmet_alive, NULL nm, NULL ft
  FROM ca GROUP BY cls, d QUALIFY ROW_NUMBER() OVER (ORDER BY SUM(IFF(done IS NULL,1,0)) DESC) <= 25
  OR (cls = 'work' AND ROW_NUMBER() OVER (PARTITION BY cls ORDER BY SUM(IFF(done IS NULL,1,0)) DESC) <= 12)),
tot AS (
  SELECT 'B_total' part, cls label, COUNT(*) n, SUM(IFF(done IS NULL,1,0)) unmet, SUM(IFF(done IS NULL AND alive=1,1,0)) unmet_alive, COUNT(DISTINCT IFF(done IS NULL AND alive=1, NPDES_ID, NULL))::string nm, NULL ft
  FROM ca GROUP BY 1,2),
tops AS (
  SELECT 'C_permit' part, ca.NPDES_ID label, COUNT(*) n, SUM(IFF(done IS NULL,1,0)) unmet, MIN(IFF(done IS NULL, due, NULL))::string unmet_alive, MAX(fac.FACILITY_NAME) || ' / ' || MAX(fac.CITY) nm, MAX(fac.FACILITY_TYPE_CODE) ft
  FROM ca LEFT JOIN LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_NPDES_ICIS_FACILITIES fac ON fac.NPDES_ID = ca.NPDES_ID
  WHERE cls = 'work' AND alive = 1 GROUP BY 1,2 QUALIFY ROW_NUMBER() OVER (ORDER BY SUM(IFF(done IS NULL,1,0)) DESC) <= 20)
SELECT part, label, n, unmet, unmet_alive::string unmet_alive, nm, ft FROM descs
UNION ALL SELECT part, label, n, unmet, unmet_alive::string, nm, ft FROM tot
UNION ALL SELECT * FROM tops
ORDER BY part, unmet DESC;

-- [9] SE: top permits by single events since 2015, SSO and bypass counts, dup check, names, formal actions since 2015, rank within facility type
WITH se AS (
  SELECT NPDES_ID, SINGLE_EVENT_VIOLATION_DATE dt, VIOLATION_CODE, VIOLATION_DESC,
    IFF(VIOLATION_DESC ILIKE '%SSO%' OR VIOLATION_DESC ILIKE '%overflow%' OR VIOLATION_DESC ILIKE '%CSO%', 1, 0) sso,
    IFF(VIOLATION_DESC ILIKE '%bypass%', 1, 0) byp,
    SINGLE_EVENT_AGENCY_TYPE_CODE ag
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_NPDES_NPDES_SE_VIOLATIONS
  WHERE SINGLE_EVENT_VIOLATION_DATE >= '2015-01-01'),
p AS (
  SELECT NPDES_ID, COUNT(*) n, COUNT(DISTINCT dt, VIOLATION_CODE) n_dt_code, SUM(sso) sso, SUM(byp) byp,
    COUNT(DISTINCT YEAR(dt)) yrs, MIN(dt) first_dt, MAX(dt) last_dt,
    MAX_BY(VIOLATION_DESC, 1) any_desc, MODE(VIOLATION_CODE) top_code, MODE(ag) top_ag
  FROM se GROUP BY 1),
fe AS (
  SELECT NPDES_ID, COUNT(*) acts, SUM(COALESCE(FED_PENALTY_ASSESSED_AMT,0) + COALESCE(STATE_LOCAL_PENALTY_AMT,0)) pen, MAX(SETTLEMENT_ENTERED_DATE) last_act
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_NPDES_NPDES_FORMAL_ENFORCEMENT_ACTIONS
  WHERE SETTLEMENT_ENTERED_DATE >= '2015-01-01' GROUP BY 1),
j AS (
  SELECT p.*, fac.FACILITY_NAME, fac.CITY, fac.FACILITY_TYPE_CODE ft, fe.acts, fe.pen, fe.last_act,
    RANK() OVER (PARTITION BY fac.FACILITY_TYPE_CODE ORDER BY p.n DESC) rk_in_type,
    COUNT(*) OVER (PARTITION BY fac.FACILITY_TYPE_CODE) peers,
    MEDIAN(p.n) OVER (PARTITION BY fac.FACILITY_TYPE_CODE) peer_median
  FROM p
  LEFT JOIN LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_NPDES_ICIS_FACILITIES fac ON fac.NPDES_ID = p.NPDES_ID
  LEFT JOIN fe ON fe.NPDES_ID = p.NPDES_ID)
SELECT 'TOTAL' NPDES_ID, SUM(n) n, SUM(n_dt_code) n_dt_code, SUM(sso) sso, SUM(byp) byp, COUNT(*) yrs, NULL first_dt, NULL last_dt,
  'permits with fac name=' || COUNT(FACILITY_NAME) || ', with formal action since 2015=' || COUNT(acts) FACILITY_NAME,
  'SSO events at permits w/ formal action=' || SUM(IFF(acts IS NOT NULL, sso, 0)) CITY, NULL ft, NULL acts, NULL pen, NULL last_act, NULL rk_in_type, NULL peers, NULL peer_median, NULL top_code
FROM j
UNION ALL
SELECT * FROM (SELECT NPDES_ID, n, n_dt_code, sso, byp, yrs, first_dt, last_dt, FACILITY_NAME, CITY, ft, acts, pen, last_act, rk_in_type, peers, peer_median, top_code
  FROM j ORDER BY n DESC LIMIT 25);

-- [10] QNCR: permits with 36+ of 40 quarters 2016-2025, bucketed by effluent-violation quarters vs formal/informal action share; chronic with no formal action
WITH q AS (
  SELECT NPDES_ID, COUNT(DISTINCT YEARQTR) qtrs,
    COUNT(DISTINCT IFF(TRY_TO_NUMBER(NUME90_Q) > 0, YEARQTR, NULL)) eff_q,
    SUM(TRY_TO_NUMBER(NUME90_Q)) eff_n,
    COUNT(DISTINCT IFF(TRY_TO_NUMBER(NUME90_Q) > 0 OR TRY_TO_NUMBER(NUMCVDT) > 0 OR TRY_TO_NUMBER(NUMSVCD) > 0 OR TRY_TO_NUMBER(NUMPSCH) > 0 OR TRY_TO_NUMBER(NUMD8090_Q) > 0, YEARQTR, NULL)) any_q,
    COUNT(DISTINCT IFF(HLRNC IN ('S','E','X','T'), YEARQTR, NULL)) sext_q
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_NPDES_NPDES_QNCR_HISTORY
  WHERE TRY_TO_NUMBER(YEARQTR) BETWEEN 20161 AND 20254 GROUP BY 1),
fe AS (
  SELECT NPDES_ID, COUNT(*) fe_all, COUNT(IFF(SETTLEMENT_ENTERED_DATE >= '2016-01-01', 1, NULL)) fe_win,
    SUM(IFF(SETTLEMENT_ENTERED_DATE >= '2016-01-01', COALESCE(FED_PENALTY_ASSESSED_AMT,0) + COALESCE(STATE_LOCAL_PENALTY_AMT,0), 0)) pen_win
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_NPDES_NPDES_FORMAL_ENFORCEMENT_ACTIONS GROUP BY 1),
ie AS (
  SELECT NPDES_ID, COUNT(IFF(ACHIEVED_DATE BETWEEN '2016-01-01' AND '2025-12-31', 1, NULL)) ie_win
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_NPDES_NPDES_INFORMAL_ENFORCEMENT_ACTIONS GROUP BY 1),
j AS (
  SELECT q.*, COALESCE(fe.fe_all,0) fe_all, COALESCE(fe.fe_win,0) fe_win, COALESCE(fe.pen_win,0) pen_win, COALESCE(ie.ie_win,0) ie_win,
    fac.FACILITY_NAME, fac.CITY, fac.FACILITY_TYPE_CODE ft,
    CASE WHEN eff_q = 0 THEN '0' WHEN eff_q < 10 THEN '01-09' WHEN eff_q < 20 THEN '10-19' WHEN eff_q < 30 THEN '20-29' WHEN eff_q < 36 THEN '30-35' ELSE '36-40' END bkt
  FROM q LEFT JOIN fe ON fe.NPDES_ID = q.NPDES_ID LEFT JOIN ie ON ie.NPDES_ID = q.NPDES_ID
  LEFT JOIN LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_NPDES_ICIS_FACILITIES fac ON fac.NPDES_ID = q.NPDES_ID
  WHERE q.qtrs >= 36)
SELECT 'A_bucket' part, bkt label, COUNT(*) permits, ROUND(AVG(IFF(fe_win > 0,1,0)),3) sh_formal, ROUND(AVG(IFF(ie_win > 0,1,0)),3) sh_informal,
  SUM(IFF(fe_win = 0 AND ie_win = 0,1,0)) no_action, ROUND(AVG(sext_q),1) avg_sext_q, SUM(IFF(ft = 'POT' OR ft = 'MWD' OR ft = 'CTG' OR ft = 'CNG',1,0))::string muni_types, NULL nm, NULL c
FROM j GROUP BY 2
UNION ALL
SELECT * FROM (SELECT 'B_chronic_no_formal', NPDES_ID, eff_q, eff_n, ie_win, fe_all, sext_q, ft, FACILITY_NAME, CITY
  FROM j WHERE eff_q >= 36 AND fe_win = 0 ORDER BY eff_n DESC LIMIT 25)
ORDER BY 1, 2;

-- [11] QNCR: chronic permits vs null-dated formal actions; operator roll-up by name prefix
WITH q AS (
  SELECT NPDES_ID, COUNT(DISTINCT YEARQTR) qtrs,
    COUNT(DISTINCT IFF(TRY_TO_NUMBER(NUME90_Q) > 0, YEARQTR, NULL)) eff_q,
    SUM(TRY_TO_NUMBER(NUME90_Q)) eff_n
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_NPDES_NPDES_QNCR_HISTORY
  WHERE TRY_TO_NUMBER(YEARQTR) BETWEEN 20161 AND 20254 GROUP BY 1),
fe AS (
  SELECT NPDES_ID, COUNT(*) fe_all, COUNT(IFF(SETTLEMENT_ENTERED_DATE >= '2016-01-01', 1, NULL)) fe_win,
    COUNT(IFF(SETTLEMENT_ENTERED_DATE IS NULL, 1, NULL)) fe_nulldate
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_NPDES_NPDES_FORMAL_ENFORCEMENT_ACTIONS GROUP BY 1),
ie AS (
  SELECT NPDES_ID, COUNT(IFF(ACHIEVED_DATE BETWEEN '2016-01-01' AND '2025-12-31', 1, NULL)) ie_win
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_NPDES_NPDES_INFORMAL_ENFORCEMENT_ACTIONS GROUP BY 1),
j AS (
  SELECT q.*, COALESCE(fe.fe_all,0) fe_all, COALESCE(fe.fe_win,0) fe_win, COALESCE(fe.fe_nulldate,0) fe_nulldate, COALESCE(ie.ie_win,0) ie_win,
    fac.FACILITY_NAME, TRIM(SPLIT_PART(fac.FACILITY_NAME, ' - ', 1)) op
  FROM q LEFT JOIN fe ON fe.NPDES_ID = q.NPDES_ID LEFT JOIN ie ON ie.NPDES_ID = q.NPDES_ID
  LEFT JOIN LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_NPDES_ICIS_FACILITIES fac ON fac.NPDES_ID = q.NPDES_ID
  WHERE q.qtrs >= 36)
SELECT 'A_chronic36' part, 'all' label, COUNT(*) n, SUM(IFF(fe_win = 0,1,0)) no_formal_win, SUM(IFF(fe_win = 0 AND fe_nulldate > 0,1,0)) of_which_nulldate_action,
  SUM(IFF(fe_all = 0,1,0)) never_formal, SUM(IFF(fe_all = 0 AND ie_win = 0,1,0)) never_formal_no_informal, SUM(eff_n) eff_n
FROM j WHERE eff_q >= 36
UNION ALL
SELECT * FROM (
  SELECT 'B_operator', op, COUNT(*) permits, SUM(IFF(eff_q >= 20,1,0)) chronic20, SUM(IFF(eff_q >= 20 AND fe_win = 0,1,0)) chronic20_no_formal,
    SUM(IFF(fe_win > 0,1,0)) with_formal, ROUND(AVG(eff_q),1) avg_eff_q, SUM(eff_n)
  FROM j WHERE FACILITY_NAME LIKE '% - %' GROUP BY op HAVING COUNT(*) >= 5 AND SUM(IFF(eff_q >= 20,1,0)) >= 4
  ORDER BY chronic20 DESC LIMIT 20)
ORDER BY 1, 4 DESC;

-- [12] QNCR: Utility Operating Company family by year 2016-2025; peer chronic share by state and facility type
WITH fac AS (
  SELECT NPDES_ID, FACILITY_NAME, FACILITY_TYPE_CODE ft, LEFT(NPDES_ID,2) st,
    CASE WHEN FACILITY_NAME ILIKE '%UTILITY OPERATING COMPANY%' THEN TRIM(SPLIT_PART(FACILITY_NAME, ' - ', 1))
         WHEN FACILITY_NAME ILIKE 'NATIONAL WATER INFRASTRUCTURE%' THEN 'NATIONAL WATER INFRASTRUCTURE, LLC' END op
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_NPDES_ICIS_FACILITIES),
qq AS (
  SELECT q.NPDES_ID, LEFT(q.YEARQTR,4) yr, TRY_TO_NUMBER(q.NUME90_Q) e
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_NPDES_NPDES_QNCR_HISTORY q
  WHERE TRY_TO_NUMBER(q.YEARQTR) BETWEEN 20161 AND 20254),
per AS (
  SELECT qq.NPDES_ID, COUNT(*) qtrs, COUNT(IFF(e > 0,1,NULL)) eff_q, MAX(f.op) op, MAX(f.ft) ft, MAX(f.st) st
  FROM qq JOIN fac f ON f.NPDES_ID = qq.NPDES_ID GROUP BY 1)
SELECT 'A_family_year' part, f.op || ' [' || f.st || ']' label, qq.yr k, COUNT(DISTINCT qq.NPDES_ID) permits,
  COUNT(DISTINCT IFF(qq.e > 0, qq.NPDES_ID, NULL)) permits_w_eff, SUM(qq.e) eff_n
FROM qq JOIN fac f ON f.NPDES_ID = qq.NPDES_ID WHERE f.op IS NOT NULL
GROUP BY 1,2,3 HAVING COUNT(DISTINCT qq.NPDES_ID) >= 3
UNION ALL
SELECT 'B_peers_' || st, IFF(op IS NULL, 'others', op) || ' ft=' || COALESCE(ft,'?'), 'n / chronic20 / share', COUNT(*), SUM(IFF(eff_q >= 20,1,0)), ROUND(100 * AVG(IFF(eff_q >= 20,1,0)),1)
FROM per WHERE qtrs >= 36 AND st IN ('LA','MO','TX','KY','TN','MS','AR','NC','SC') AND (op IS NOT NULL OR ft IN ('POF','MWD','CTG','CNG'))
GROUP BY 1,2 HAVING COUNT(*) >= 3
ORDER BY 1, 2, 3;

-- [13] QNCR: National Water Infrastructure LLC permits by prefix: first quarter seen, violation quarters 2016-23 vs 2024-25, formal and informal actions
WITH nwi AS (
  SELECT NPDES_ID, FACILITY_NAME, FACILITY_TYPE_CODE ft
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_NPDES_ICIS_FACILITIES
  WHERE FACILITY_NAME ILIKE 'NATIONAL WATER INFRASTRUCTURE%'),
q AS (
  SELECT q.NPDES_ID, MIN(TRY_TO_NUMBER(YEARQTR)) firstq, MAX(TRY_TO_NUMBER(YEARQTR)) lastq,
    COUNT(IFF(TRY_TO_NUMBER(YEARQTR) BETWEEN 20161 AND 20234, 1, NULL)) q16_23,
    COUNT(IFF(TRY_TO_NUMBER(YEARQTR) BETWEEN 20161 AND 20234 AND TRY_TO_NUMBER(NUME90_Q) > 0, 1, NULL)) e16_23,
    COUNT(IFF(TRY_TO_NUMBER(YEARQTR) BETWEEN 20241 AND 20254, 1, NULL)) q24_25,
    COUNT(IFF(TRY_TO_NUMBER(YEARQTR) BETWEEN 20241 AND 20254 AND TRY_TO_NUMBER(NUME90_Q) > 0, 1, NULL)) e24_25,
    COUNT(IFF(TRY_TO_NUMBER(YEARQTR) BETWEEN 20241 AND 20254 AND TRY_TO_NUMBER(NUMD8090_Q) > 0, 1, NULL)) late24_25
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_NPDES_NPDES_QNCR_HISTORY q JOIN nwi ON nwi.NPDES_ID = q.NPDES_ID GROUP BY 1),
fe AS (
  SELECT f.NPDES_ID, COUNT(*) fe_all, COUNT(IFF(SETTLEMENT_ENTERED_DATE >= '2020-01-01',1,NULL)) fe_20, SUM(COALESCE(FED_PENALTY_ASSESSED_AMT,0) + COALESCE(STATE_LOCAL_PENALTY_AMT,0)) pen
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_NPDES_NPDES_FORMAL_ENFORCEMENT_ACTIONS f JOIN nwi ON nwi.NPDES_ID = f.NPDES_ID GROUP BY 1),
ie AS (
  SELECT i.NPDES_ID, COUNT(IFF(ACHIEVED_DATE >= '2020-01-01',1,NULL)) ie_20
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_NPDES_NPDES_INFORMAL_ENFORCEMENT_ACTIONS i JOIN nwi ON nwi.NPDES_ID = i.NPDES_ID GROUP BY 1)
SELECT LEFT(nwi.NPDES_ID,3) prefix, COALESCE(nwi.ft,'?') ft, COUNT(*) permits, COUNT(q.NPDES_ID) in_qncr,
  MIN(q.firstq) min_first, MEDIAN(q.firstq) med_first, SUM(q.q16_23) q16_23, SUM(q.e16_23) e16_23, SUM(q.q24_25) q24_25, SUM(q.e24_25) e24_25, SUM(q.late24_25) late24_25,
  COUNT(IFF(COALESCE(fe.fe_all,0) > 0,1,NULL)) w_formal_ever, SUM(COALESCE(fe.fe_20,0)) formal_since20, SUM(COALESCE(fe.pen,0)) pen_all, SUM(COALESCE(ie.ie_20,0)) informal_since20,
  ANY_VALUE(nwi.FACILITY_NAME) sample_name
FROM nwi LEFT JOIN q ON q.NPDES_ID = nwi.NPDES_ID LEFT JOIN fe ON fe.NPDES_ID = nwi.NPDES_ID LEFT JOIN ie ON ie.NPDES_ID = nwi.NPDES_ID
GROUP BY 1,2 ORDER BY permits DESC;

-- [14] SE sewer-overflow events by year (DeKalb, Atlanta, GA, FL, US, states reporting); NWI formal actions by case id, repeated-penalty check
WITH se AS (
  SELECT NPDES_ID, YEAR(SINGLE_EVENT_VIOLATION_DATE) yr
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_NPDES_NPDES_SE_VIOLATIONS
  WHERE (VIOLATION_DESC ILIKE '%SSO%' OR VIOLATION_DESC ILIKE '%overflow%' OR VIOLATION_DESC ILIKE '%CSO%')
    AND SINGLE_EVENT_VIOLATION_DATE BETWEEN '2012-01-01' AND '2025-12-31'),
a AS (
  SELECT 'A_sso_by_year' part, yr::string k,
    COUNT(IFF(NPDES_ID = 'GA0024147',1,NULL))::string c1, COUNT(IFF(NPDES_ID = 'GA0039012',1,NULL))::string c2,
    COUNT(IFF(LEFT(NPDES_ID,2) = 'GA',1,NULL))::string c3, COUNT(IFF(LEFT(NPDES_ID,2) = 'FL',1,NULL))::string c4,
    COUNT(*)::string c5, COUNT(DISTINCT LEFT(NPDES_ID,2))::string c6
  FROM se GROUP BY yr),
nwi AS (
  SELECT NPDES_ID FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_NPDES_ICIS_FACILITIES
  WHERE FACILITY_NAME ILIKE 'NATIONAL WATER INFRASTRUCTURE%'),
b AS (
  SELECT 'B_nwi_enf' part, f.ENF_IDENTIFIER k, COUNT(*)::string c1, COUNT(DISTINCT f.NPDES_ID)::string c2,
    MIN(COALESCE(f.FED_PENALTY_ASSESSED_AMT,0) + COALESCE(f.STATE_LOCAL_PENALTY_AMT,0))::string c3,
    MAX(COALESCE(f.FED_PENALTY_ASSESSED_AMT,0) + COALESCE(f.STATE_LOCAL_PENALTY_AMT,0))::string c4,
    MAX(f.SETTLEMENT_ENTERED_DATE)::string c5, MAX(f.ENF_TYPE_DESC || ' / ' || f.AGENCY) c6
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_NPDES_NPDES_FORMAL_ENFORCEMENT_ACTIONS f JOIN nwi ON nwi.NPDES_ID = f.NPDES_ID
  GROUP BY 2 QUALIFY ROW_NUMBER() OVER (ORDER BY SUM(COALESCE(f.FED_PENALTY_ASSESSED_AMT,0) + COALESCE(f.STATE_LOCAL_PENALTY_AMT,0)) DESC) <= 10)
SELECT * FROM a UNION ALL SELECT * FROM b ORDER BY 1, 2;

-- [15] RCRA: deduped CEI inspections 2015-2025, violation-found % by state, state vs EPA, all and large generators only
WITH ev AS (
  SELECT ID_NUMBER, ACTIVITY_LOCATION st, EVALUATION_START_DATE dt, EVALUATION_AGENCY ag,
    MAX(IFF(FOUND_VIOLATION = 'Y',1,0)) y, MAX(IFF(FOUND_VIOLATION IN ('Y','N'),1,0)) known
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_RCRA_EVALUATIONS
  WHERE EVALUATION_TYPE = 'CEI' AND EVALUATION_START_DATE BETWEEN '2015-01-01' AND '2025-12-31' AND EVALUATION_AGENCY IN ('S','E')
  GROUP BY 1,2,3,4),
fac AS (
  SELECT ID_NUMBER, COUNT(*) dup, MAX(IFF(HREPORT_UNIVERSE_RECORD ILIKE 'LQG%',1,0)) lqg
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_RCRA_FACILITIES GROUP BY 1),
j AS (SELECT ev.*, COALESCE(fac.lqg,0) lqg, IFF(fac.ID_NUMBER IS NULL,0,1) in_fac FROM ev LEFT JOIN fac ON fac.ID_NUMBER = ev.ID_NUMBER WHERE known = 1)
SELECT COALESCE(st,'ALL') st,
  COUNT(IFF(ag='S',1,NULL)) s_n, ROUND(100*AVG(IFF(ag='S',y,NULL)),1) s_pct,
  COUNT(IFF(ag='E',1,NULL)) e_n, ROUND(100*AVG(IFF(ag='E',y,NULL)),1) e_pct,
  COUNT(IFF(ag='S' AND lqg=1,1,NULL)) s_lqg_n, ROUND(100*AVG(IFF(ag='S' AND lqg=1,y,NULL)),1) s_lqg_pct,
  COUNT(IFF(ag='E' AND lqg=1,1,NULL)) e_lqg_n, ROUND(100*AVG(IFF(ag='E' AND lqg=1,y,NULL)),1) e_lqg_pct,
  ROUND(100*AVG(in_fac),1) pct_in_fac
FROM j GROUP BY ROLLUP(st) ORDER BY s_n DESC;

-- [16] RCRA: CEI flag vs violations table - share of Y and N inspections with a same-agency violation logged at the site within 60 days
WITH ev AS (
  SELECT ID_NUMBER, ACTIVITY_LOCATION st, EVALUATION_START_DATE dt, EVALUATION_AGENCY ag,
    MAX(IFF(FOUND_VIOLATION = 'Y',1,0)) y
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_RCRA_EVALUATIONS
  WHERE EVALUATION_TYPE = 'CEI' AND EVALUATION_START_DATE BETWEEN '2015-01-01' AND '2025-12-31'
    AND EVALUATION_AGENCY IN ('S','E') AND FOUND_VIOLATION IN ('Y','N')
  GROUP BY 1,2,3,4),
vd AS (
  SELECT ID_NUMBER, DATE_VIOLATION_DETERMINED vdt, VIOL_DETERMINED_BY_AGENCY vag, COUNT(*) nv
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_RCRA_VIOLATIONS
  WHERE DATE_VIOLATION_DETERMINED BETWEEN '2015-01-01' AND '2026-03-31'
  GROUP BY 1,2,3),
m AS (
  SELECT ev.ID_NUMBER, ev.st, ev.dt, ev.ag, ev.y,
    MAX(IFF(vd.vag = ev.ag, 1, 0)) v60_same, MAX(IFF(vd.ID_NUMBER IS NOT NULL, 1, 0)) v60_any, SUM(IFF(vd.vag = ev.ag, vd.nv, 0)) nv_same
  FROM ev LEFT JOIN vd ON vd.ID_NUMBER = ev.ID_NUMBER AND vd.vdt BETWEEN ev.dt AND DATEADD(day, 60, ev.dt)
  GROUP BY 1,2,3,4,5)
SELECT COALESCE(st,'ALL') st, ag,
  COUNT(*) n, ROUND(100*AVG(y),1) flag_y_pct,
  ROUND(100*AVG(IFF(y=1, v60_same, NULL)),1) y_with_viol_pct,
  ROUND(100*AVG(IFF(y=0, v60_same, NULL)),1) n_with_viol_pct,
  ROUND(100*AVG(v60_same),1) viol60_pct,
  ROUND(AVG(IFF(y=1, nv_same, NULL)),1) viols_per_y
FROM m
GROUP BY ROLLUP(ag, st) HAVING ag IS NOT NULL AND (GROUPING(st) = 1 OR st IN ('KY','NC','IL','PA','MD','CA','SD','NJ','NV','WV','WI','WA','SC','NH','TX','FL','TN','OH'))
ORDER BY ag DESC, flag_y_pct;

-- [17] RCRA: same-site test - EPA CEIs 2015-2025 paired with state CEIs at the same site within 2 years; hit rates side by side
WITH ev AS (
  SELECT ID_NUMBER, ACTIVITY_LOCATION st, EVALUATION_START_DATE dt, EVALUATION_AGENCY ag,
    MAX(IFF(FOUND_VIOLATION = 'Y',1,0)) y
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_RCRA_EVALUATIONS
  WHERE EVALUATION_TYPE = 'CEI' AND EVALUATION_START_DATE BETWEEN '2013-01-01' AND '2025-12-31'
    AND EVALUATION_AGENCY IN ('S','E') AND FOUND_VIOLATION IN ('Y','N')
  GROUP BY 1,2,3,4),
e AS (SELECT * FROM ev WHERE ag = 'E' AND dt >= '2015-01-01'),
s AS (SELECT * FROM ev WHERE ag = 'S'),
pr AS (
  SELECT e.st, e.ID_NUMBER, e.dt edt, e.y ey, AVG(s.y) sy, COUNT(*) ns
  FROM e JOIN s ON s.ID_NUMBER = e.ID_NUMBER AND ABS(DATEDIFF(day, s.dt, e.dt)) BETWEEN 1 AND 730
  GROUP BY 1,2,3,4)
SELECT COALESCE(st,'ALL') st, COUNT(*) epa_insp_paired, ROUND(100*AVG(ey),1) epa_hit_pct, ROUND(100*AVG(sy),1) state_hit_pct_same_sites,
  COUNT(IFF(ey = 1,1,NULL)) epa_found, ROUND(100*AVG(IFF(ey = 1, sy, NULL)),1) state_hit_pct_where_epa_found,
  ROUND(100*AVG(IFF(ey = 0, sy, NULL)),1) state_hit_pct_where_epa_clean, SUM(ns) state_insp
FROM pr GROUP BY ROLLUP(st) HAVING COUNT(*) >= 15 ORDER BY state_hit_pct_where_epa_found NULLS LAST;

-- [18] RCRA: same-site test tightened to 180 days; example sites where EPA found violations and state inspection found none
WITH ev AS (
  SELECT ID_NUMBER, ACTIVITY_LOCATION st, EVALUATION_START_DATE dt, EVALUATION_AGENCY ag,
    MAX(IFF(FOUND_VIOLATION = 'Y',1,0)) y
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_RCRA_EVALUATIONS
  WHERE EVALUATION_TYPE = 'CEI' AND EVALUATION_START_DATE BETWEEN '2014-06-01' AND '2025-12-31'
    AND EVALUATION_AGENCY IN ('S','E') AND FOUND_VIOLATION IN ('Y','N')
  GROUP BY 1,2,3,4),
e AS (SELECT * FROM ev WHERE ag = 'E' AND dt >= '2015-01-01'),
s AS (SELECT * FROM ev WHERE ag = 'S'),
pr AS (
  SELECT e.st, e.ID_NUMBER, e.dt edt, e.y ey, AVG(s.y) sy, COUNT(*) ns, MIN(s.dt) sdt
  FROM e JOIN s ON s.ID_NUMBER = e.ID_NUMBER AND ABS(DATEDIFF(day, s.dt, e.dt)) BETWEEN 1 AND 180
  GROUP BY 1,2,3,4),
fac AS (
  SELECT ID_NUMBER, ANY_VALUE(FACILITY_NAME) nm, ANY_VALUE(CITY_NAME) city, MAX(HREPORT_UNIVERSE_RECORD) univ
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_RCRA_FACILITIES GROUP BY 1),
a AS (
  SELECT 'A_rates_180d' part, COALESCE(st,'ALL') k, COUNT(*)::string c1, ROUND(100*AVG(ey),1)::string c2,
    COUNT(IFF(ey = 1,1,NULL))::string c3, ROUND(100*AVG(IFF(ey = 1, sy, NULL)),1)::string c4, ROUND(100*AVG(IFF(ey = 0, sy, NULL)),1)::string c5, NULL c6
  FROM pr GROUP BY ROLLUP(st) HAVING COUNT(*) >= 10),
b AS (
  SELECT 'B_examples' part, pr.st || ' ' || pr.ID_NUMBER k, pr.edt::string c1, pr.sdt::string c2, pr.ns::string c3,
    fac.nm c4, fac.city c5, fac.univ c6
  FROM pr LEFT JOIN fac ON fac.ID_NUMBER = pr.ID_NUMBER
  WHERE pr.ey = 1 AND pr.sy = 0 AND pr.st IN ('IL','PA','NJ','NC','KY','CA')
  QUALIFY ROW_NUMBER() OVER (PARTITION BY pr.st ORDER BY pr.edt DESC) <= 3)
SELECT * FROM a UNION ALL SELECT * FROM b ORDER BY 1, 2;

-- [19] CS: 'pay civil penalty' milestones never marked done, by state; overall unmet share by state as the peer baseline
WITH ev AS (
  SELECT NPDES_ID, COMP_SCHEDULE_EVENT_ID, MAX(SCHEDULE_EVENT_CODE) code, MIN(SCHEDULE_DATE) due, MAX(ACTUAL_DATE) done,
    MAX(RNC_RESOLUTION_CODE) res
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_NPDES_NPDES_CS_VIOLATIONS GROUP BY 1,2),
qa AS (
  SELECT NPDES_ID, MAX(TRY_TO_NUMBER(YEARQTR)) lastq
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_NPDES_NPDES_QNCR_HISTORY WHERE TRY_TO_NUMBER(YEARQTR) <= 20263 GROUP BY 1),
x AS (
  SELECT ev.*, LEFT(ev.NPDES_ID,2) st, IFF(qa.lastq >= 20251,1,0) alive
  FROM ev LEFT JOIN qa ON qa.NPDES_ID = ev.NPDES_ID)
SELECT COALESCE(st,'ALL') st,
  COUNT(IFF(code = 'CS001',1,NULL)) pay_ms, COUNT(IFF(code = 'CS001' AND done IS NULL,1,NULL)) pay_unmet,
  ROUND(100*AVG(IFF(code = 'CS001', IFF(done IS NULL,1,0), NULL)),1) pay_unmet_pct,
  COUNT(IFF(code = 'CS001' AND done IS NULL AND alive = 1 AND due >= '2016-01-01',1,NULL)) pay_unmet_alive_since16,
  COUNT(IFF(code = 'CS001' AND done IS NULL AND res = '1',1,NULL)) pay_unmet_flag_unresolved,
  COUNT(*) all_ms, ROUND(100*AVG(IFF(done IS NULL,1,0)),1) all_unmet_pct
FROM x GROUP BY ROLLUP(st) HAVING COUNT(IFF(code = 'CS001',1,NULL)) >= 20 OR st IS NULL
ORDER BY pay_unmet DESC;

-- [20] QNCR: mines vs public sewer vs other in 7 coal and industrial states - chronic count and formal/informal action rates 2016-2025
WITH q AS (
  SELECT NPDES_ID, COUNT(DISTINCT YEARQTR) qtrs, COUNT(DISTINCT IFF(TRY_TO_NUMBER(NUME90_Q) > 0, YEARQTR, NULL)) eff_q
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_NPDES_NPDES_QNCR_HISTORY
  WHERE TRY_TO_NUMBER(YEARQTR) BETWEEN 20161 AND 20254 AND LEFT(NPDES_ID,2) IN ('WV','KY','PA','VA','MO','OH','AL')
  GROUP BY 1),
fe AS (
  SELECT NPDES_ID, COUNT(IFF(SETTLEMENT_ENTERED_DATE >= '2016-01-01',1,NULL)) fe_win
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_NPDES_NPDES_FORMAL_ENFORCEMENT_ACTIONS GROUP BY 1),
ie AS (
  SELECT NPDES_ID, COUNT(IFF(ACHIEVED_DATE BETWEEN '2016-01-01' AND '2025-12-31',1,NULL)) ie_win
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_NPDES_NPDES_INFORMAL_ENFORCEMENT_ACTIONS GROUP BY 1),
j AS (
  SELECT q.*, LEFT(q.NPDES_ID,2) st, COALESCE(fe.fe_win,0) fe_win, COALESCE(ie.ie_win,0) ie_win,
    CASE WHEN fac.FACILITY_NAME ILIKE ANY ('%MINE%','%MINING%','%COAL%','%SURFACE%','%PREP PLANT%','%REFUSE%') THEN 'mine'
         WHEN fac.FACILITY_TYPE_CODE IN ('MWD','CTG','CNG') THEN 'public sewer'
         ELSE 'other' END kind
  FROM q LEFT JOIN fe ON fe.NPDES_ID = q.NPDES_ID LEFT JOIN ie ON ie.NPDES_ID = q.NPDES_ID
  LEFT JOIN LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_NPDES_ICIS_FACILITIES fac ON fac.NPDES_ID = q.NPDES_ID
  WHERE q.qtrs >= 36)
SELECT st, kind, COUNT(*) permits, SUM(IFF(eff_q >= 20,1,0)) chronic20,
  ROUND(100*AVG(IFF(fe_win > 0,1,0)),1) formal_pct_all,
  ROUND(100*AVG(IFF(eff_q >= 20, IFF(fe_win > 0,1,0), NULL)),1) formal_pct_chronic,
  ROUND(100*AVG(IFF(eff_q >= 20, IFF(ie_win > 0,1,0), NULL)),1) informal_pct_chronic,
  SUM(IFF(eff_q >= 20 AND fe_win = 0 AND ie_win = 0,1,0)) chronic_no_action
FROM j GROUP BY 1,2 HAVING COUNT(*) >= 10 ORDER BY 1,2;

-- NOTE on [7]: failed at compile time (GROUP BY on a label while QUALIFY used the class column). Fixed and re-run as [8]. Counted against budget.
-- Total: 20 statements of 35. Two of them ([1] wrong file, [7] compile error) returned nothing useful.
