-- deep2/deep-1: coverage round 2 hand-queries, 2026-09-24
-- Tables: ECONOMICS__INTL_GLEIF_REPEX, EDUCATION__FED_ED_COLLEGE_SCORECARD_INSTITUTION,
--         EDUCATION__FED_GOOGLE_POLADS_CREATIVE_STATS, ENERGY__FED_EIA861_RELIABILITY, ENERGY__FED_EIA861_SALES_ULT_CUST
-- Door: Python (connect/db.py). Every connection first ran:
--   ALTER SESSION SET STATEMENT_TIMEOUT_IN_SECONDS = 300;
--   ALTER SESSION SET QUERY_TAG = 'coverage-r2-2026-09-24';
-- Read-only: SELECT / WITH only. 30 numbered statements of the 35 budget (Q1 counted but its results were lost).

-- Q1: (lost) first batch went through a shared runner another agent had overwritten; it may have run as one statement. Counted against budget, results not seen.

-- Q2: row counts, all five tables
SELECT 'REPEX' t, COUNT(*) n FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__INTL_GLEIF_REPEX
UNION ALL SELECT 'SCORECARD', COUNT(*) FROM LIBRARY_MARTS.EDUCATION.EDUCATION__FED_ED_COLLEGE_SCORECARD_INSTITUTION
UNION ALL SELECT 'POLADS_CREATIVE', COUNT(*) FROM LIBRARY_MARTS.EDUCATION.EDUCATION__FED_GOOGLE_POLADS_CREATIVE_STATS
UNION ALL SELECT 'EIA_RELIABILITY', COUNT(*) FROM LIBRARY_MARTS.ENERGY.ENERGY__FED_EIA861_RELIABILITY
UNION ALL SELECT 'EIA_SALES', COUNT(*) FROM LIBRARY_MARTS.ENERGY.ENERGY__FED_EIA861_SALES_ULT_CUST;

-- Q3: sample REPEX
SELECT LEI, EXCEPTION_CATEGORY, EXCEPTION_REASON_1, EXCEPTION_REASON_2, EXCEPTION_REFERENCE_1 FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__INTL_GLEIF_REPEX LIMIT 5;

-- Q4: sample SCORECARD
SELECT INSTITUTION_NAME, STATE, CONTROL_CODE, PREDOMINANT_DEGREE_CODE, UNDERGRAD_ENROLLMENT, DEBT_MEDIAN, DEBT_MEDIAN_COMPLETERS, EARNINGS_MEDIAN_6YR, EARNINGS_MEDIAN_10YR, CURRENTLY_OPERATING, OPEID6 FROM LIBRARY_MARTS.EDUCATION.EDUCATION__FED_ED_COLLEGE_SCORECARD_INSTITUTION LIMIT 5;

-- Q5: sample POLADS_CREATIVE
SELECT REGIONS, ADVERTISER_ID, ADVERTISER_NAME, AD_TYPE, DATE_RANGE_START, DATE_RANGE_END, IMPRESSIONS, AGE_TARGETING, GENDER_TARGETING, GEO_TARGETING_INCLUDED, SPEND_RANGE_MIN_USD, SPEND_RANGE_MAX_USD FROM LIBRARY_MARTS.EDUCATION.EDUCATION__FED_GOOGLE_POLADS_CREATIVE_STATS LIMIT 5;

-- Q6: sample EIA_RELIABILITY
SELECT DATA_YEAR, UTILITY_NUMBER, UTILITY_NAME, STATE, OWNERSHIP, IEEE_SAIDI_WITH_MED_MINUTES, IEEE_SAIDI_WITHOUT_MED_MINUTES, IEEE_SAIFI_WITH_MED, IEEE_SAIFI_WITHOUT_MED, IEEE_NUMBER_OF_CUSTOMERS, OTHER_SAIDI_WITH_MED_MINUTES FROM LIBRARY_MARTS.ENERGY.ENERGY__FED_EIA861_RELIABILITY LIMIT 5;

-- Q7: sample EIA_SALES
SELECT DATA_YEAR, UTILITY_NUMBER, UTILITY_NAME, PART, SERVICE_TYPE, DATA_TYPE, STATE, OWNERSHIP, RESIDENTIAL_REVENUES_THOUSAND_DOLLARS, RESIDENTIAL_SALES_MWH, RESIDENTIAL_CUSTOMERS, TOTAL_CUSTOMERS FROM LIBRARY_MARTS.ENERGY.ENERGY__FED_EIA861_SALES_ULT_CUST LIMIT 5;

-- Q8: RELIABILITY profile by ownership and Helene states; zeros, impossible rows (without > with), OTHER-only rows
WITH b AS (
  SELECT *, IFF(STATE IN ('GA','NC','SC','FL','TN','VA'),'HELENE6','REST') AS zone
  FROM LIBRARY_MARTS.ENERGY.ENERGY__FED_EIA861_RELIABILITY)
SELECT 'own:'||COALESCE(OWNERSHIP,'?') grp, COUNT(*) n, COUNT(IEEE_SAIDI_WITH_MED_MINUTES) with_filled, COUNT(IEEE_SAIDI_WITHOUT_MED_MINUTES) wo_filled,
  COUNT_IF(IEEE_SAIDI_WITH_MED_MINUTES IS NULL AND OTHER_SAIDI_WITH_MED_MINUTES IS NOT NULL) other_only,
  COUNT_IF(IEEE_SAIDI_WITH_MED_MINUTES = 0) with_zero,
  COUNT_IF(IEEE_SAIDI_WITHOUT_MED_MINUTES > IEEE_SAIDI_WITH_MED_MINUTES) wo_gt_with,
  MEDIAN(IEEE_SAIDI_WITH_MED_MINUTES) med_with, MEDIAN(IEEE_SAIDI_WITHOUT_MED_MINUTES) med_wo,
  APPROX_PERCENTILE(IEEE_SAIDI_WITHOUT_MED_MINUTES,0.9) p90_wo,
  SUM(IEEE_NUMBER_OF_CUSTOMERS) cust,
  SUM(IEEE_SAIDI_WITH_MED_MINUTES*IEEE_NUMBER_OF_CUSTOMERS)/NULLIF(SUM(IFF(IEEE_SAIDI_WITH_MED_MINUTES IS NOT NULL,IEEE_NUMBER_OF_CUSTOMERS,0)),0) custwt_with,
  SUM(IEEE_SAIDI_WITHOUT_MED_MINUTES*IEEE_NUMBER_OF_CUSTOMERS)/NULLIF(SUM(IFF(IEEE_SAIDI_WITHOUT_MED_MINUTES IS NOT NULL,IEEE_NUMBER_OF_CUSTOMERS,0)),0) custwt_wo
FROM b GROUP BY 1
UNION ALL
SELECT 'zone:'||zone, COUNT(*), COUNT(IEEE_SAIDI_WITH_MED_MINUTES), COUNT(IEEE_SAIDI_WITHOUT_MED_MINUTES),
  COUNT_IF(IEEE_SAIDI_WITH_MED_MINUTES IS NULL AND OTHER_SAIDI_WITH_MED_MINUTES IS NOT NULL), COUNT_IF(IEEE_SAIDI_WITH_MED_MINUTES = 0),
  COUNT_IF(IEEE_SAIDI_WITHOUT_MED_MINUTES > IEEE_SAIDI_WITH_MED_MINUTES),
  MEDIAN(IEEE_SAIDI_WITH_MED_MINUTES), MEDIAN(IEEE_SAIDI_WITHOUT_MED_MINUTES), APPROX_PERCENTILE(IEEE_SAIDI_WITHOUT_MED_MINUTES,0.9),
  SUM(IEEE_NUMBER_OF_CUSTOMERS),
  SUM(IEEE_SAIDI_WITH_MED_MINUTES*IEEE_NUMBER_OF_CUSTOMERS)/NULLIF(SUM(IFF(IEEE_SAIDI_WITH_MED_MINUTES IS NOT NULL,IEEE_NUMBER_OF_CUSTOMERS,0)),0),
  SUM(IEEE_SAIDI_WITHOUT_MED_MINUTES*IEEE_NUMBER_OF_CUSTOMERS)/NULLIF(SUM(IFF(IEEE_SAIDI_WITHOUT_MED_MINUTES IS NOT NULL,IEEE_NUMBER_OF_CUSTOMERS,0)),0)
FROM b GROUP BY 1
ORDER BY 1;

-- Q9: RELIABILITY top 20 by SAIDI with major events (1,000+ customers) and top 25 by SAIDI without major events (10,000+ customers), each against its state and ownership peers
WITH b AS (
  SELECT UTILITY_NUMBER, UTILITY_NAME, STATE, OWNERSHIP, IEEE_NUMBER_OF_CUSTOMERS cust,
    IEEE_SAIDI_WITH_MED_MINUTES w, IEEE_SAIDI_WITHOUT_MED_MINUTES wo, IEEE_SAIFI_WITHOUT_MED saifi_wo, IEEE_CAIDI_WITHOUT_MED_MINUTES caidi_wo,
    IEEE_OUTAGES_RECORDED_AUTOMATICALLY auto_rec,
    MEDIAN(IEEE_SAIDI_WITHOUT_MED_MINUTES) OVER (PARTITION BY STATE) st_med_wo,
    MEDIAN(IEEE_SAIDI_WITH_MED_MINUTES) OVER (PARTITION BY STATE) st_med_w,
    COUNT(IEEE_SAIDI_WITHOUT_MED_MINUTES) OVER (PARTITION BY STATE) st_n,
    MEDIAN(IEEE_SAIDI_WITHOUT_MED_MINUTES) OVER (PARTITION BY OWNERSHIP) own_med_wo
  FROM LIBRARY_MARTS.ENERGY.ENERGY__FED_EIA861_RELIABILITY WHERE IEEE_SAIDI_WITH_MED_MINUTES IS NOT NULL),
r AS (SELECT *, RANK() OVER (ORDER BY IFF(cust>=1000,w,NULL) DESC NULLS LAST) rk_w,
  RANK() OVER (ORDER BY IFF(cust>=10000,wo,NULL) DESC NULLS LAST) rk_wo FROM b)
SELECT IFF(rk_w<=20,'W'||rk_w,'') rank_with, IFF(rk_wo<=25,'WO'||rk_wo,'') rank_wo, UTILITY_NAME, STATE, OWNERSHIP, cust, w, wo, ROUND(w-wo) med_part,
  st_med_w, st_med_wo, st_n, ROUND(wo/NULLIF(st_med_wo,0),1) x_state_wo, own_med_wo, saifi_wo, caidi_wo, auto_rec
FROM r WHERE rk_w<=20 OR rk_wo<=25 ORDER BY rk_wo, rk_w;

-- Q10: SALES profile by PART x SERVICE_TYPE x DATA_TYPE: rows, rows with home customers, home revenue and MWh, adjustment rows, negative rows
SELECT PART, SERVICE_TYPE, DATA_TYPE, COUNT(*) n, COUNT_IF(RESIDENTIAL_CUSTOMERS>0) res_rows, SUM(RESIDENTIAL_CUSTOMERS) res_cust,
  ROUND(SUM(RESIDENTIAL_REVENUES_THOUSAND_DOLLARS)/1000) res_rev_musd, ROUND(SUM(RESIDENTIAL_SALES_MWH)/1e6,1) res_twh,
  ROUND(SUM(RESIDENTIAL_REVENUES_THOUSAND_DOLLARS)*100/NULLIF(SUM(RESIDENTIAL_SALES_MWH),0),2) cents_kwh,
  COUNT_IF(UTILITY_NAME ILIKE 'adjust%' OR UTILITY_NUMBER=99999) adj_rows,
  COUNT_IF(RESIDENTIAL_REVENUES_THOUSAND_DOLLARS<0 OR RESIDENTIAL_SALES_MWH<0) neg_rows,
  COUNT(DISTINCT UTILITY_NUMBER) utils, COUNT(DISTINCT DATA_YEAR) yrs
FROM LIBRARY_MARTS.ENERGY.ENERGY__FED_EIA861_SALES_ULT_CUST GROUP BY 1,2,3 ORDER BY 1,2,3;

-- Q11: SALES home price per kWh, full-service (Part A, Bundled, reported rows only), 10K+ home customers, against state peers (Part A utilities with 1K+ home customers)
WITH b AS (
  SELECT UTILITY_NUMBER, UTILITY_NAME, STATE, OWNERSHIP, RESIDENTIAL_CUSTOMERS rc, RESIDENTIAL_SALES_MWH mwh, RESIDENTIAL_REVENUES_THOUSAND_DOLLARS rev_k,
    RESIDENTIAL_REVENUES_THOUSAND_DOLLARS*100/NULLIF(RESIDENTIAL_SALES_MWH,0) cents,
    RESIDENTIAL_REVENUES_THOUSAND_DOLLARS*1000/NULLIF(RESIDENTIAL_CUSTOMERS,0)/12 bill_mo,
    RESIDENTIAL_SALES_MWH*1000/NULLIF(RESIDENTIAL_CUSTOMERS,0)/12 kwh_mo
  FROM LIBRARY_MARTS.ENERGY.ENERGY__FED_EIA861_SALES_ULT_CUST
  WHERE PART='A' AND SERVICE_TYPE='Bundled' AND DATA_TYPE='O' AND RESIDENTIAL_CUSTOMERS>=1000 AND RESIDENTIAL_SALES_MWH>0),
s AS (SELECT *, MEDIAN(cents) OVER (PARTITION BY STATE) st_med, COUNT(*) OVER (PARTITION BY STATE) st_n,
  MEDIAN(bill_mo) OVER (PARTITION BY STATE) st_bill,
  MEDIAN(cents) OVER (PARTITION BY STATE, OWNERSHIP) st_own_med, COUNT(*) OVER (PARTITION BY STATE, OWNERSHIP) st_own_n FROM b)
SELECT UTILITY_NAME, STATE, OWNERSHIP, rc, ROUND(cents,1) cents, ROUND(st_med,1) st_med, st_n, ROUND(cents/st_med,2) x_state,
  ROUND(st_own_med,1) st_own_med, st_own_n, ROUND(bill_mo) bill_mo, ROUND(st_bill) st_bill, ROUND(kwh_mo) kwh_mo, ROUND(rev_k/1000,1) rev_musd
FROM s WHERE rc>=10000 ORDER BY cents/st_med DESC LIMIT 30;

-- Q12: SALES how many 10K+ utilities sit 1.3x / 1.5x over their state median, by ownership; and the extra dollars they bill above the state-median price
WITH b AS (
  SELECT UTILITY_NAME, STATE, OWNERSHIP, RESIDENTIAL_CUSTOMERS rc, RESIDENTIAL_SALES_MWH mwh, RESIDENTIAL_REVENUES_THOUSAND_DOLLARS rev_k,
    RESIDENTIAL_REVENUES_THOUSAND_DOLLARS*100/NULLIF(RESIDENTIAL_SALES_MWH,0) cents
  FROM LIBRARY_MARTS.ENERGY.ENERGY__FED_EIA861_SALES_ULT_CUST
  WHERE PART='A' AND SERVICE_TYPE='Bundled' AND DATA_TYPE='O' AND RESIDENTIAL_CUSTOMERS>=1000 AND RESIDENTIAL_SALES_MWH>0),
s AS (SELECT *, MEDIAN(cents) OVER (PARTITION BY STATE) st_med FROM b)
SELECT OWNERSHIP, COUNT(*) n10k, SUM(rc) home_cust, COUNT_IF(cents>=1.3*st_med) n_13x, COUNT_IF(cents>=1.5*st_med) n_15x,
  SUM(IFF(cents>=1.3*st_med, rc, 0)) cust_13x,
  ROUND(SUM(IFF(cents>=1.3*st_med, rev_k*1000 - mwh*st_med*10, 0))/1e6,1) extra_musd_13x,
  ROUND(MEDIAN(cents/st_med),3) med_ratio
FROM s WHERE rc>=10000 GROUP BY ROLLUP(OWNERSHIP) ORDER BY n10k DESC;

-- Q13: SCORECARD profile by ownership (CONTROL_CODE) x main award (PREDOMINANT_DEGREE_CODE): filled, min values, operating, enrollment
SELECT CONTROL_CODE ctl, PREDOMINANT_DEGREE_CODE deg, COUNT(*) n, COUNT_IF(CURRENTLY_OPERATING=1) open_n,
  COUNT(DEBT_MEDIAN_COMPLETERS) debt_c_filled, COUNT(EARNINGS_MEDIAN_10YR) earn10_filled, COUNT(EARNINGS_MEDIAN_6YR) earn6_filled,
  MIN(DEBT_MEDIAN_COMPLETERS) debt_min, MAX(DEBT_MEDIAN_COMPLETERS) debt_max, MIN(EARNINGS_MEDIAN_10YR) e10_min, MAX(EARNINGS_MEDIAN_10YR) e10_max,
  COUNT_IF(UNDERGRAD_ENROLLMENT>500) enr500, SUM(UNDERGRAD_ENROLLMENT) ug,
  MEDIAN(EARNINGS_MEDIAN_10YR) med_e10, MEDIAN(DEBT_MEDIAN_COMPLETERS) med_debt_c,
  ROUND(MEDIAN(DEBT_MEDIAN_COMPLETERS/NULLIF(EARNINGS_MEDIAN_10YR,0)),3) med_ratio,
  COUNT_IF(UNDERGRAD_ENROLLMENT>500 AND EARNINGS_MEDIAN_10YR<30000 AND DEBT_MEDIAN_COMPLETERS>20000) flag_n,
  SUM(IFF(UNDERGRAD_ENROLLMENT>500 AND EARNINGS_MEDIAN_10YR<30000 AND DEBT_MEDIAN_COMPLETERS>20000, UNDERGRAD_ENROLLMENT,0)) flag_ug
FROM LIBRARY_MARTS.EDUCATION.EDUCATION__FED_ED_COLLEGE_SCORECARD_INSTITUTION
GROUP BY ROLLUP(CONTROL_CODE, PREDOMINANT_DEGREE_CODE) ORDER BY 1,2;

-- Q14: SCORECARD top 25 open schools with 500+ undergrads by completer debt / 10-year earnings, with each school's peer median (same ownership and main award)
WITH b AS (
  SELECT INSTITUTION_NAME, STATE, CONTROL_CODE ctl, PREDOMINANT_DEGREE_CODE deg, UNDERGRAD_ENROLLMENT ug, DEBT_MEDIAN_COMPLETERS debt_c, EARNINGS_MEDIAN_10YR e10,
    PCT_PELL, PCT_FEDERAL_LOAN, REPAYMENT_RATE_3YR rep3, DEFAULT_RATE_2YR def2, OPEID6,
    DEBT_MEDIAN_COMPLETERS/NULLIF(EARNINGS_MEDIAN_10YR,0) ratio,
    MEDIAN(DEBT_MEDIAN_COMPLETERS/NULLIF(EARNINGS_MEDIAN_10YR,0)) OVER (PARTITION BY CONTROL_CODE, PREDOMINANT_DEGREE_CODE) peer_ratio,
    MEDIAN(EARNINGS_MEDIAN_10YR) OVER (PARTITION BY CONTROL_CODE, PREDOMINANT_DEGREE_CODE) peer_e10
  FROM LIBRARY_MARTS.EDUCATION.EDUCATION__FED_ED_COLLEGE_SCORECARD_INSTITUTION WHERE CURRENTLY_OPERATING=1)
SELECT INSTITUTION_NAME, STATE, ctl, deg, ug, debt_c, e10, ROUND(ratio,2) ratio, ROUND(peer_ratio,2) peer_ratio, peer_e10, PCT_PELL, PCT_FEDERAL_LOAN, rep3, def2
FROM b WHERE ug>500 AND ratio IS NOT NULL ORDER BY ratio DESC LIMIT 25;

-- Q15: SCORECARD schools whose former students earn under $30K ten years out, by ownership, and the biggest name families among them (first two words of the name)
WITH b AS (
  SELECT CONTROL_CODE ctl, PREDOMINANT_DEGREE_CODE deg, UNDERGRAD_ENROLLMENT ug, EARNINGS_MEDIAN_10YR e10, DEBT_MEDIAN_COMPLETERS debt_c,
    REGEXP_SUBSTR(UPPER(INSTITUTION_NAME), '^[A-Z&\'-]+( [A-Z&\'-]+)?') fam
  FROM LIBRARY_MARTS.EDUCATION.EDUCATION__FED_ED_COLLEGE_SCORECARD_INSTITUTION WHERE CURRENTLY_OPERATING=1 AND EARNINGS_MEDIAN_10YR IS NOT NULL)
SELECT 'ctl '||ctl AS grp, COUNT(*) schools_w_earn, COUNT_IF(e10<30000) under30k, ROUND(COUNT_IF(e10<30000)/COUNT(*),3) share_under30k,
  SUM(IFF(e10<30000,ug,0)) ug_under30k, MEDIAN(IFF(e10<30000,debt_c,NULL)) med_debt_under30k
FROM b GROUP BY ctl
UNION ALL
SELECT * FROM (
SELECT 'fam '||fam, COUNT(*), COUNT_IF(e10<30000), ROUND(COUNT_IF(e10<30000)/COUNT(*),3), SUM(IFF(e10<30000,ug,0)), MEDIAN(IFF(e10<30000,debt_c,NULL))
FROM b WHERE ctl=3 GROUP BY fam HAVING COUNT_IF(e10<30000)>=8 ORDER BY 3 DESC LIMIT 15);

-- Q16: POLADS creative US vs rest by start year: ads, advertisers, spend-range sums, top range, blank ranges, age/gender/ZIP targeting shares
SELECT IFF(REGIONS='US','US','nonUS:'||IFF(REGIONS LIKE '%,%','multi','single')) reg, YEAR(DATE_RANGE_START) yr, COUNT(*) ads, COUNT(DISTINCT ADVERTISER_ID) advs,
  ROUND(SUM(SPEND_RANGE_MIN_USD)/1e6,1) min_musd, ROUND(SUM(SPEND_RANGE_MAX_USD)/1e6,1) max_musd, MAX(SPEND_RANGE_MIN_USD) top_min, MAX(SPEND_RANGE_MAX_USD) top_max,
  COUNT_IF(SPEND_RANGE_MAX_USD IS NULL) max_null, COUNT_IF(SPEND_RANGE_MAX_USD=100) in_0_100,
  ROUND(COUNT_IF(AGE_TARGETING IS NOT NULL AND AGE_TARGETING <> '')/COUNT(*),3) age_filled,
  ROUND(COUNT_IF(GENDER_TARGETING IN ('Male','Female'))/COUNT(*),3) one_gender,
  ROUND(COUNT_IF(REGEXP_LIKE(GEO_TARGETING_INCLUDED, '.*\b[0-9]{5}\b.*'))/COUNT(*),3) zip_geo
FROM LIBRARY_MARTS.EDUCATION.EDUCATION__FED_GOOGLE_POLADS_CREATIVE_STATS
GROUP BY 1,2 HAVING COUNT(*)>2000 ORDER BY 1,2;

-- Q17: POLADS advertiser stats sample: US top 8 by exact spend, the ID list format and region format
SELECT ADVERTISER_ID, ADVERTISER_NAME, REGIONS, SPEND_USD, TOTAL_CREATIVES, PUBLIC_IDS_LIST FROM LIBRARY_MARTS.EDUCATION.EDUCATION__FED_GOOGLE_POLADS_ADVERTISER_STATS
WHERE REGIONS ILIKE '%US%' ORDER BY TRY_TO_NUMBER(SPEND_USD::STRING) DESC NULLS LAST LIMIT 8;

-- Q18: POLADS US advertisers by the ID they gave Google (FEC ID vs EIN only vs other), exact spend, and exact-name land rate in the FEC committee list; then top 20 spenders with no FEC ID
WITH a AS (
  SELECT ADVERTISER_ID, ADVERTISER_NAME, TRY_TO_NUMBER(SPEND_USD::STRING) spend, PUBLIC_IDS_LIST ids,
    CASE WHEN PUBLIC_IDS_LIST ILIKE '%FEC ID%' THEN 'FEC' WHEN PUBLIC_IDS_LIST ILIKE '%EIN ID%' THEN 'EIN_ONLY'
         WHEN PUBLIC_IDS_LIST IS NULL OR TRIM(PUBLIC_IDS_LIST)='' THEN 'BLANK' ELSE 'OTHER' END idtype,
    REGEXP_REPLACE(UPPER(ADVERTISER_NAME),'[^A-Z0-9]','') nk
  FROM LIBRARY_MARTS.EDUCATION.EDUCATION__FED_GOOGLE_POLADS_ADVERTISER_STATS WHERE REGIONS='US'),
f AS (SELECT DISTINCT REGEXP_REPLACE(UPPER(CMTE_NM),'[^A-Z0-9]','') nk FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_FEC_COMMITTEES_DIM WHERE CMTE_NM IS NOT NULL),
j AS (SELECT a.*, IFF(f.nk IS NOT NULL,1,0) name_in_fec FROM a LEFT JOIN f ON a.nk=f.nk)
SELECT 'TYPE '||idtype grp, NULL name, COUNT(*) advs, ROUND(SUM(spend)/1e6,1) spend_musd, COUNT_IF(spend>=1000000) advs_1m, ROUND(AVG(name_in_fec),3) name_land, NULL ids FROM j GROUP BY idtype
UNION ALL
SELECT * FROM (SELECT 'TOP_NOFEC', ADVERTISER_NAME, NULL, ROUND(spend/1e6,2), NULL, name_in_fec, LEFT(ids,40) FROM j WHERE idtype<>'FEC' ORDER BY spend DESC NULLS LAST LIMIT 22);

-- Q19: POLADS US ads started 2024: share of spend-range midpoint on one-gender ads, ZIP-targeted ads, narrow-age ads; top advertisers by one-gender midpoint spend
WITH u AS (
  SELECT ADVERTISER_NAME, (SPEND_RANGE_MIN_USD+SPEND_RANGE_MAX_USD)/2 mid,
    IFF(GENDER_TARGETING IN ('Male','Female'),1,0) one_g,
    IFF(REGEXP_COUNT(GEO_TARGETING_INCLUDED, '(^|,)[0-9]{5}(,|$)')>0,1,0) zip_t,
    IFF(AGE_TARGETING IS NOT NULL AND AGE_TARGETING<>'' AND REGEXP_COUNT(AGE_TARGETING, ',')<=1,1,0) narrow_age
  FROM LIBRARY_MARTS.EDUCATION.EDUCATION__FED_GOOGLE_POLADS_CREATIVE_STATS
  WHERE REGIONS='US' AND DATE_RANGE_START BETWEEN '2024-01-01' AND '2024-12-31')
SELECT 'ALL' grp, NULL adv, COUNT(*) ads, ROUND(SUM(mid)/1e6,1) mid_musd, ROUND(SUM(mid*one_g)/SUM(mid),3) one_g_share, ROUND(SUM(mid*zip_t)/SUM(mid),3) zip_share, ROUND(SUM(mid*narrow_age)/SUM(mid),3) narrow_age_share, SUM(zip_t) zip_ads FROM u
UNION ALL
SELECT * FROM (SELECT 'TOP_ONE_GENDER', ADVERTISER_NAME, SUM(one_g), ROUND(SUM(mid*one_g)/1e6,2), ROUND(SUM(mid*one_g)/SUM(mid),3), ROUND(SUM(mid*zip_t)/SUM(mid),3), ROUND(SUM(mid*narrow_age)/SUM(mid),3), SUM(zip_t)
  FROM u GROUP BY ADVERTISER_NAME ORDER BY SUM(mid*one_g) DESC LIMIT 12);

-- Q20: REPEX reason codes by which parent (direct / ultimate), distinct LEIs, and land rate of those LEIs in the main GLEIF register
WITH r AS (SELECT EXCEPTION_CATEGORY cat, EXCEPTION_REASON_1 rsn, LEI FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__INTL_GLEIF_REPEX),
g AS (SELECT DISTINCT LEI FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__INTL_GLEIF)
SELECT LEFT(cat,8) cat, rsn, COUNT(*) n, COUNT(DISTINCT r.LEI) leis, COUNT(DISTINCT g.LEI) leis_in_gleif
FROM r LEFT JOIN g ON r.LEI=g.LEI GROUP BY ROLLUP(LEFT(cat,8), rsn) ORDER BY 1, 3 DESC;

-- Q21: REPEX ultimate-parent reason shares by legal-address country and by managing registration office (LOU); denominator = every LEI in GLEIF for that group; groups with 10K+ LEIs
WITH r AS (SELECT LEI, MAX(EXCEPTION_REASON_1) rsn FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__INTL_GLEIF_REPEX WHERE EXCEPTION_CATEGORY LIKE 'ULTIMATE%' GROUP BY LEI),
g AS (SELECT LEI, ENTITY_LEGALADDRESS_COUNTRY ctry, REGISTRATION_MANAGINGLOU lou, REGISTRATION_REGISTRATIONSTATUS st FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__INTL_GLEIF),
j AS (SELECT g.*, r.rsn, IFF(r.rsn IN ('NON_PUBLIC','CONSENT_NOT_OBTAINED','BINDING_LEGAL_COMMITMENTS','DETRIMENT_NOT_EXCLUDED','DISCLOSURE_DETRIMENTAL','LEGAL_OBSTACLES'),1,0) np FROM g LEFT JOIN r ON g.LEI=r.LEI),
agg AS (
  SELECT IFF(GROUPING(ctry)=0,'CTRY','LOU') lvl, COALESCE(ctry, lou) k, COUNT(*) leis, COUNT_IF(st='ISSUED') issued,
    ROUND(AVG(np),4) np_share, SUM(np) np_n, ROUND(AVG(IFF(rsn='NO_LEI',1,0)),4) nolei_share, ROUND(AVG(IFF(rsn='NATURAL_PERSONS',1,0)),3) natp_share,
    ROUND(AVG(IFF(rsn='NO_KNOWN_PERSON',1,0)),3) nokp_share, ROUND(AVG(IFF(rsn IS NULL,1,0)),3) no_exception_share
  FROM j GROUP BY GROUPING SETS ((ctry),(lou)) HAVING COUNT(*)>=10000)
SELECT a.lvl, a.k, LEFT(n.ENTITY_LEGALNAME,40) lou_name, a.leis, a.issued, a.np_share, a.np_n, a.nolei_share, a.natp_share, a.nokp_share, a.no_exception_share
FROM agg a LEFT JOIN LIBRARY_MARTS.ECONOMICS.ECONOMICS__INTL_GLEIF n ON a.lvl='LOU' AND a.k=n.LEI
ORDER BY a.lvl, a.np_share DESC;

-- Q22: REPEX US legal-address LEIs only: refuse-to-name share by managing office x entity category x current status (does the rate follow the office or the entity?)
WITH r AS (SELECT LEI, MAX(EXCEPTION_REASON_1) rsn FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__INTL_GLEIF_REPEX WHERE EXCEPTION_CATEGORY LIKE 'ULTIMATE%' GROUP BY LEI),
g AS (SELECT LEI, REGISTRATION_MANAGINGLOU lou, ENTITY_ENTITYCATEGORY cat, IFF(REGISTRATION_REGISTRATIONSTATUS='ISSUED','ISSUED','OTHER') st
      FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__INTL_GLEIF WHERE ENTITY_LEGALADDRESS_COUNTRY='US'),
j AS (SELECT g.*, IFF(r.rsn IN ('NON_PUBLIC','CONSENT_NOT_OBTAINED','BINDING_LEGAL_COMMITMENTS','DETRIMENT_NOT_EXCLUDED','DISCLOSURE_DETRIMENTAL','LEGAL_OBSTACLES'),1,0) np,
        IFF(r.rsn='NO_LEI',1,0) nolei, r.rsn FROM g LEFT JOIN r ON g.LEI=r.LEI)
SELECT IFF(lou='5493001KJTIIGC8Y1R12','BLOOMBERG','OTHER_LOU') lou_grp, COALESCE(cat,'?') cat, st, COUNT(*) leis, SUM(np) np_n, ROUND(AVG(np),4) np_share, ROUND(AVG(nolei),4) nolei_share,
  ROUND(AVG(IFF(rsn IS NULL,1,0)),3) no_exc_share
FROM j GROUP BY 1,2,3 HAVING COUNT(*)>=500 ORDER BY 1,2,3;

-- Q23: REPEX US legal-address LEIs refusing to name the ultimate parent: top registered first address lines, with the refuse share at that line vs all LEIs on that line
WITH r AS (SELECT LEI, MAX(EXCEPTION_REASON_1) rsn FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__INTL_GLEIF_REPEX WHERE EXCEPTION_CATEGORY LIKE 'ULTIMATE%' GROUP BY LEI),
g AS (SELECT LEI, UPPER(TRIM(ENTITY_LEGALADDRESS_FIRSTADDRESSLINE)) addr, ENTITY_LEGALADDRESS_CITY city, ENTITY_ENTITYCATEGORY cat
      FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__INTL_GLEIF WHERE ENTITY_LEGALADDRESS_COUNTRY='US'),
j AS (SELECT g.*, IFF(r.rsn IN ('NON_PUBLIC','CONSENT_NOT_OBTAINED','BINDING_LEGAL_COMMITMENTS','DETRIMENT_NOT_EXCLUDED','DISCLOSURE_DETRIMENTAL','LEGAL_OBSTACLES'),1,0) np FROM g LEFT JOIN r ON g.LEI=r.LEI)
SELECT addr, ANY_VALUE(city) city, COUNT(*) leis_at_addr, SUM(np) np_n, ROUND(AVG(np),3) np_share, ROUND(SUM(np)/40088,3) share_of_us_np,
  COUNT_IF(np=1 AND cat='FUND') np_funds
FROM j GROUP BY addr ORDER BY np_n DESC LIMIT 15;

-- Q24: REPEX x OpenSanctions: targets carrying an LEI-shaped ID, land rate in GLEIF, name agreement, and their ultimate-parent exception reasons, sanctioned vs other watch lists
WITH o AS (
  SELECT ID, NAME, IFF(COALESCE(TRIM(SANCTIONS),'') NOT IN ('','""','[]') OR COALESCE(TRIM(PROGRAM_IDS),'') NOT IN ('','""','[]'),'SANCTIONED','OTHER_LIST') lst, f.value::string lei
  FROM LIBRARY_MARTS.JUSTICE.JUSTICE__INTL_OPENSANCTIONS_DEFAULT,
       LATERAL FLATTEN(input => REGEXP_SUBSTR_ALL(IDENTIFIERS, '[0-9A-Z]{18}[0-9]{2}')) f
  WHERE ENTITY_TYPE IN ('Company','LegalEntity','Organization') AND IDENTIFIERS IS NOT NULL),
od AS (SELECT lst, lei, ANY_VALUE(NAME) oname, COUNT(DISTINCT ID) targets FROM o GROUP BY lst, lei),
r AS (SELECT LEI, MAX(EXCEPTION_REASON_1) rsn FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__INTL_GLEIF_REPEX WHERE EXCEPTION_CATEGORY LIKE 'ULTIMATE%' GROUP BY LEI),
j AS (SELECT od.*, g.LEI glei, g.ENTITY_LEGALNAME gname, g.ENTITY_LEGALADDRESS_COUNTRY ctry, r.rsn,
        IFF(LEFT(REGEXP_REPLACE(UPPER(od.oname),'[^A-Z0-9]',''),5)=LEFT(REGEXP_REPLACE(UPPER(g.ENTITY_LEGALNAME),'[^A-Z0-9]',''),5),1,0) name5
      FROM od LEFT JOIN LIBRARY_MARTS.ECONOMICS.ECONOMICS__INTL_GLEIF g ON od.lei=g.LEI LEFT JOIN r ON od.lei=r.LEI)
SELECT lst, COUNT(*) lei_shaped, COUNT(glei) in_gleif, SUM(IFF(glei IS NOT NULL,name5,0)) name5_agree,
  COUNT_IF(rsn IN ('NON_PUBLIC','CONSENT_NOT_OBTAINED','BINDING_LEGAL_COMMITMENTS','DETRIMENT_NOT_EXCLUDED','DISCLOSURE_DETRIMENTAL','LEGAL_OBSTACLES')) np,
  COUNT_IF(rsn='NO_LEI') no_lei, COUNT_IF(rsn='NATURAL_PERSONS') natp, COUNT_IF(rsn='NO_KNOWN_PERSON') nokp, COUNT_IF(rsn='NON_CONSOLIDATING') noncons,
  COUNT_IF(glei IS NOT NULL AND rsn IS NULL) no_exception, COUNT_IF(glei IS NOT NULL AND ctry='RU') ru, COUNT_IF(glei IS NOT NULL AND ctry='US') us
FROM j GROUP BY lst ORDER BY lst;

-- Q25: SALES x RELIABILITY join on utility number + state: land rate, and full-service utilities (10K+ homes) that are both 1.2x+ their state's median price and 2x+ their state's median outage minutes without major events
WITH s AS (
  SELECT UTILITY_NUMBER un, STATE, UTILITY_NAME, OWNERSHIP, RESIDENTIAL_CUSTOMERS rc, RESIDENTIAL_REVENUES_THOUSAND_DOLLARS*100/NULLIF(RESIDENTIAL_SALES_MWH,0) cents
  FROM LIBRARY_MARTS.ENERGY.ENERGY__FED_EIA861_SALES_ULT_CUST
  WHERE PART='A' AND SERVICE_TYPE='Bundled' AND DATA_TYPE='O' AND RESIDENTIAL_CUSTOMERS>=1000 AND RESIDENTIAL_SALES_MWH>0),
rl AS (SELECT UTILITY_NUMBER un, STATE, IEEE_SAIDI_WITHOUT_MED_MINUTES wo, IEEE_SAIDI_WITH_MED_MINUTES w FROM LIBRARY_MARTS.ENERGY.ENERGY__FED_EIA861_RELIABILITY WHERE IEEE_SAIDI_WITHOUT_MED_MINUTES IS NOT NULL),
j AS (SELECT s.*, rl.wo, rl.w FROM s LEFT JOIN rl ON s.un=rl.un AND s.STATE=rl.STATE),
k AS (SELECT *, cents/MEDIAN(cents) OVER (PARTITION BY STATE) px, wo/MEDIAN(wo) OVER (PARTITION BY STATE) ox FROM j)
SELECT 'SUMMARY' grp, NULL UTILITY_NAME, NULL STATE, NULL OWNERSHIP, COUNT(*) n, COUNT(wo) landed, ROUND(CORR(px,ox),3) corr_px_ox, NULL cents, NULL px, NULL wo, NULL ox FROM k
UNION ALL
SELECT * FROM (SELECT 'BOTH', UTILITY_NAME, STATE, OWNERSHIP, rc, NULL, NULL, ROUND(cents,1), ROUND(px,2), ROUND(wo), ROUND(ox,1) FROM k WHERE rc>=10000 AND px>=1.2 AND ox>=2 ORDER BY px*ox DESC LIMIT 20);

-- Q26: REPEX current (ISSUED) LEIs only: refuse-to-name share of the ultimate parent by legal-address country, 5K+ current LEIs, top 15 plus a few peers
WITH r AS (SELECT LEI, MAX(EXCEPTION_REASON_1) rsn FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__INTL_GLEIF_REPEX WHERE EXCEPTION_CATEGORY LIKE 'ULTIMATE%' GROUP BY LEI),
g AS (SELECT LEI, ENTITY_LEGALADDRESS_COUNTRY ctry FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__INTL_GLEIF WHERE REGISTRATION_REGISTRATIONSTATUS='ISSUED'),
j AS (SELECT g.ctry, r.rsn, IFF(r.rsn IN ('NON_PUBLIC','CONSENT_NOT_OBTAINED','BINDING_LEGAL_COMMITMENTS','DETRIMENT_NOT_EXCLUDED','DISCLOSURE_DETRIMENTAL','LEGAL_OBSTACLES'),1,0) np FROM g LEFT JOIN r ON g.LEI=r.LEI),
a AS (SELECT ctry, COUNT(*) issued, SUM(np) np_n, ROUND(AVG(np),4) np_share, ROUND(AVG(IFF(rsn='NO_LEI',1,0)),4) nolei_share,
        COUNT_IF(rsn='NON_PUBLIC') legacy_np, RANK() OVER (ORDER BY AVG(np) DESC) rk FROM j GROUP BY ctry HAVING COUNT(*)>=5000)
SELECT * FROM a WHERE rk<=15 OR ctry IN ('GB','DE','KY','VG','LU','IE','CH','NL') ORDER BY rk;

-- Q27: SCORECARD repeats: campuses vs distinct parent IDs (OPEID6) vs distinct earnings+debt pairs among open schools with 10-year earnings under $30K, by ownership; and Empire Beauty / Strayer / Paul Mitchell
WITH b AS (SELECT CONTROL_CODE ctl, OPEID6, INSTITUTION_NAME nm, EARNINGS_MEDIAN_10YR e10, DEBT_MEDIAN_COMPLETERS debt_c, UNDERGRAD_ENROLLMENT ug
  FROM LIBRARY_MARTS.EDUCATION.EDUCATION__FED_ED_COLLEGE_SCORECARD_INSTITUTION WHERE CURRENTLY_OPERATING=1 AND EARNINGS_MEDIAN_10YR IS NOT NULL)
SELECT 'ctl '||ctl grp, COUNT(*) campuses, COUNT(DISTINCT OPEID6) parents, COUNT(DISTINCT e10||'|'||COALESCE(debt_c::STRING,'')) distinct_pairs, SUM(ug) ug
FROM b WHERE e10<30000 GROUP BY ctl
UNION ALL
SELECT fam, COUNT(*), COUNT(DISTINCT OPEID6), COUNT(DISTINCT e10||'|'||COALESCE(debt_c::STRING,'')), SUM(ug) FROM (
  SELECT *, CASE WHEN nm ILIKE 'Empire Beauty%' THEN 'EMPIRE BEAUTY' WHEN nm ILIKE 'Strayer%' THEN 'STRAYER' WHEN nm ILIKE 'Paul Mitchell%' THEN 'PAUL MITCHELL' END fam FROM b) WHERE fam IS NOT NULL GROUP BY fam;

-- Q28: REPEX who the current US refuse-to-name LEIs are: legal jurisdiction, legal form, registered since, last updated, validation level, managing office
WITH r AS (SELECT LEI FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__INTL_GLEIF_REPEX WHERE EXCEPTION_CATEGORY LIKE 'ULTIMATE%'
             AND EXCEPTION_REASON_1 IN ('NON_PUBLIC','CONSENT_NOT_OBTAINED','BINDING_LEGAL_COMMITMENTS','DETRIMENT_NOT_EXCLUDED','DISCLOSURE_DETRIMENTAL','LEGAL_OBSTACLES')),
g AS (SELECT g.* FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__INTL_GLEIF g JOIN r ON g.LEI=r.LEI
      WHERE g.ENTITY_LEGALADDRESS_COUNTRY='US' AND g.REGISTRATION_REGISTRATIONSTATUS='ISSUED')
SELECT 'jurisdiction' dim, ENTITY_LEGALJURISDICTION v, COUNT(*) n FROM g GROUP BY 2 QUALIFY RANK() OVER (ORDER BY COUNT(*) DESC)<=5
UNION ALL SELECT 'legal_form', COALESCE(ENTITY_LEGALFORM_OTHERLEGALFORM, ENTITY_LEGALFORM_ENTITYLEGALFORMCODE), COUNT(*) FROM g GROUP BY 2 QUALIFY RANK() OVER (ORDER BY COUNT(*) DESC)<=6
UNION ALL SELECT 'first_registered', LEFT(REGISTRATION_INITIALREGISTRATIONDATE::STRING,4), COUNT(*) FROM g GROUP BY 2 QUALIFY RANK() OVER (ORDER BY COUNT(*) DESC)<=6
UNION ALL SELECT 'last_updated', LEFT(REGISTRATION_LASTUPDATEDATE::STRING,4), COUNT(*) FROM g GROUP BY 2 QUALIFY RANK() OVER (ORDER BY COUNT(*) DESC)<=4
UNION ALL SELECT 'validation', REGISTRATION_VALIDATIONSOURCES, COUNT(*) FROM g GROUP BY 2
UNION ALL SELECT 'name_word', w, COUNT(*) FROM (SELECT REGEXP_SUBSTR(UPPER(ENTITY_LEGALNAME),'(TRUST|FUND|HOLDINGS?|CAPITAL|PARTNERS|BANK|REIT|CLO|MASTER|OPPORTUNIT(Y|IES)|REAL ESTATE|PROPERT(Y|IES)|ENERGY|CRYPTO|DIGITAL)') w FROM g) GROUP BY 2 QUALIFY RANK() OVER (ORDER BY COUNT(*) DESC)<=10
UNION ALL SELECT 'lou', REGISTRATION_MANAGINGLOU, COUNT(*) FROM g GROUP BY 2 QUALIFY RANK() OVER (ORDER BY COUNT(*) DESC)<=3;

-- Q29: POLADS US advertisers with no FEC ID: exact spend split by what the name says they are (state candidate, ballot measure, company, other/nonprofit) - name keyword buckets, rough
WITH a AS (
  SELECT ADVERTISER_NAME nm, TRY_TO_NUMBER(SPEND_USD::STRING) spend, PUBLIC_IDS_LIST ids
  FROM LIBRARY_MARTS.EDUCATION.EDUCATION__FED_GOOGLE_POLADS_ADVERTISER_STATS WHERE REGIONS='US' AND COALESCE(PUBLIC_IDS_LIST,'') NOT ILIKE '%FEC ID%'),
c AS (SELECT *, CASE
   WHEN REGEXP_LIKE(UPPER(nm), '.*(YES ON|NO ON|BALLOT|MEASURE|PROPOSITION|PROP [0-9]|AMENDMENT).*') THEN 'ballot measure'
   WHEN REGEXP_LIKE(UPPER(nm), '.*(FOR GOVERNOR|FOR MAYOR|FOR ATTORNEY GENERAL|FOR STATE|FOR SENATE|FOR ASSEMBLY|FOR DELEGATE|FOR JUDGE|FOR JUSTICE|FOR SHERIFF|FOR COUNCIL|FOR DISTRICT|FOR SUPERVISOR|FOR COMMISSIONER|FOR TREASURER|FOR AUDITOR|FOR SECRETARY|FOR CONTROLLER|FOR HOUSE|FOR CONGRESS|FOR PRESIDENT| 20[0-9][0-9]).*') THEN 'candidate-named'
   WHEN REGEXP_LIKE(UPPER(nm), '.*( LLC| INC\.?$| CORP| CORPORATION| CO\.?$| LTD| L\.L\.C).*') AND NOT REGEXP_LIKE(UPPER(nm), '.*(ACTION|FUND|PAC|COMMITTEE|FOUNDATION|AMERICANS|CITIZENS|COALITION|PROJECT|ALLIANCE|ASSOCIATION|COUNCIL|NETWORK|INSTITUTE|VOTERS|LEAGUE|UNION).*') THEN 'company-named'
   WHEN REGEXP_LIKE(UPPER(nm), '.*(ACTION|FUND|PAC|FOUNDATION|AMERICANS|CITIZENS|COALITION|PROJECT|ALLIANCE|ASSOCIATION|COUNCIL|NETWORK|INSTITUTE|VOTERS|LEAGUE|UNION|COMMITTEE).*') THEN 'group-named'
   ELSE 'other' END bucket FROM a)
SELECT bucket, COUNT(*) advs, ROUND(SUM(spend)/1e6,1) spend_musd, COUNT_IF(spend>=1000000) advs_1m,
  LISTAGG(IFF(spend>=4000000, LEFT(nm,32), NULL), '; ') WITHIN GROUP (ORDER BY spend DESC) top_names
FROM c GROUP BY bucket ORDER BY spend_musd DESC;

-- Q30: REPEX current (ISSUED) LEIs: refuse-to-name share, Bloomberg-managed vs every other office, in the same country (does the office explain the country ranking?)
WITH r AS (SELECT LEI FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__INTL_GLEIF_REPEX WHERE EXCEPTION_CATEGORY LIKE 'ULTIMATE%'
             AND EXCEPTION_REASON_1 IN ('NON_PUBLIC','CONSENT_NOT_OBTAINED','BINDING_LEGAL_COMMITMENTS','DETRIMENT_NOT_EXCLUDED','DISCLOSURE_DETRIMENTAL','LEGAL_OBSTACLES')),
g AS (SELECT g.LEI, g.ENTITY_LEGALADDRESS_COUNTRY ctry, IFF(g.REGISTRATION_MANAGINGLOU='5493001KJTIIGC8Y1R12','BLOOMBERG','OTHER') lou, IFF(r.LEI IS NOT NULL,1,0) np
      FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__INTL_GLEIF g LEFT JOIN r ON g.LEI=r.LEI WHERE g.REGISTRATION_REGISTRATIONSTATUS='ISSUED')
SELECT ctry, lou, COUNT(*) issued, SUM(np) np_n, ROUND(AVG(np),4) np_share
FROM g WHERE ctry IN ('US','HK','SG','VG','KY','JE','GB','LU','CA','IE') GROUP BY ctry, lou HAVING COUNT(*)>=300 ORDER BY ctry, lou;

