-- deep2 group 5: coverage round 2 hand-queries, 2026-09-24. Query tag coverage-r2-2026-09-24.
-- Tables: NOAA storm events, PHMSA flagged gas incidents, Epstein file snapshot, ICIS-FEC EPA inspections, FEC bulk committees.
-- Every connection first ran: ALTER SESSION SET STATEMENT_TIMEOUT_IN_SECONDS = 300; ALTER SESSION SET QUERY_TAG = 'coverage-r2-2026-09-24'.
-- Numbered statements are the SELECT/WITH budget (cap 35). 27 used, including [2], which failed at compile
--   (ORDER BY TRY_TO_NUMBER(3) on a number) and was rerun as [3] with a numeric count column.
-- Python door only (connect/db.py). Read-only. Results saved to a private scratchpad folder, not the repo.

-- [1] partner tables lookup
SELECT table_schema, table_name, row_count
FROM LIBRARY_MARTS.INFORMATION_SCHEMA.TABLES
WHERE table_name IN ('FCT_LIBRARY_SNAPSHOT')
   OR table_name ILIKE '%FEC%' OR table_name ILIKE '%FEMA%' OR table_name ILIKE '%PHMSA%'
   OR table_name ILIKE '%ECHO%' OR table_name ILIKE '%EPSTEIN%' OR table_name ILIKE '%ICIS%'
   OR table_name ILIKE '%LIBRARY_SNAP%' OR table_name ILIKE '%DISASTER%'
ORDER BY 1, 2;

-- [2] FEC committees: shape, repeated names, treasurer and address clusters (FAILED at compile: ORDER BY TRY_TO_NUMBER(3); rerun as [3])

-- [3] FEC committees: shape, repeated names, treasurer and address clusters
WITH t AS (SELECT * FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_FEC_BULK_COMMITTEES)
SELECT 'shape' k, 'rows / distinct ids / distinct names / cycles' v, COUNT(*) n, COUNT(DISTINCT FEC_CMTE_ID) n2, COUNT(DISTINCT CMTE_NM)::string x,
       LISTAGG(DISTINCT CYCLE, ',')::string y
FROM t
UNION ALL
SELECT 'name_rep', CMTE_NM, COUNT(*), COUNT(DISTINCT FEC_CMTE_ID), MIN(FEC_CMTE_ID)||' .. '||MAX(FEC_CMTE_ID), LISTAGG(DISTINCT TRES_NM, ';')
FROM t GROUP BY CMTE_NM HAVING COUNT(*) > 20
UNION ALL
SELECT 'tres', TRES_NM, COUNT(*), COUNT(DISTINCT CMTE_NM), LISTAGG(DISTINCT CMTE_TP, ','), LISTAGG(DISTINCT CMTE_DSGN, ',')
FROM t GROUP BY TRES_NM HAVING COUNT(*) >= 60
UNION ALL
SELECT 'addr', CMTE_ST1||' | '||CMTE_CITY||' '||CMTE_ST, COUNT(*), COUNT(DISTINCT TRES_NM), LISTAGG(DISTINCT CMTE_TP, ','), LEFT(LISTAGG(DISTINCT TRES_NM, ';'), 150)
FROM t GROUP BY CMTE_ST1, CMTE_CITY, CMTE_ST HAVING COUNT(*) >= 60
ORDER BY 1, 3 DESC;

-- [4] FEC committees: LIMIT 5 sample, plus Woodbend Dr and Datwyler PAC rows
SELECT * FROM (
(SELECT 'sample' k, FEC_CMTE_ID, CMTE_NM, TRES_NM, CMTE_ST1, CMTE_CITY, CMTE_ST, CMTE_DSGN, CMTE_TP, CMTE_PTY_AFFILIATION, CMTE_FILING_FREQ, CONNECTED_ORG_NM, FEC_CAND_ID, CYCLE
 FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_FEC_BULK_COMMITTEES LIMIT 5)
UNION ALL
(SELECT 'woodbend', FEC_CMTE_ID, CMTE_NM, TRES_NM, CMTE_ST1, CMTE_CITY, CMTE_ST, CMTE_DSGN, CMTE_TP, CMTE_PTY_AFFILIATION, CMTE_FILING_FREQ, CONNECTED_ORG_NM, FEC_CAND_ID, CYCLE
 FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_FEC_BULK_COMMITTEES WHERE CMTE_ST1 ILIKE '1742 WOODBEND%' ORDER BY FEC_CMTE_ID LIMIT 25)
UNION ALL
(SELECT 'datwyler', FEC_CMTE_ID, CMTE_NM, TRES_NM, CMTE_ST1, CMTE_CITY, CMTE_ST, CMTE_DSGN, CMTE_TP, CMTE_PTY_AFFILIATION, CMTE_FILING_FREQ, CONNECTED_ORG_NM, FEC_CAND_ID, CYCLE
 FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_FEC_BULK_COMMITTEES WHERE TRES_NM ILIKE '%DATWYLER%' AND CMTE_TP IN ('N','Q','O','V','W') ORDER BY FEC_CMTE_ID LIMIT 20)
);

-- [5] FEC: PAC summary years; treasurer clusters joined to 2026-cycle PAC money by designation
WITH yrs AS (
  SELECT 'ps_year' grp, YEAR(COVERAGE_END_DATE)::string dsgn, COUNT(*) n_cmte, COUNT(DISTINCT CMTE_ID) n_landed,
         SUM(TOTAL_RECEIPTS) receipts, SUM(INDIVIDUAL_CONTRIBUTIONS) indiv, SUM(CONTRIBUTIONS_TO_OTHER_COMMITTEES) to_cmtes,
         SUM(INDEPENDENT_EXPENDITURES) ie, SUM(TRANSFERS_TO_AFFILIATES) xfer_out, SUM(TOTAL_DISBURSEMENTS) disb
  FROM LIBRARY_MARTS.POLITICS.POLITICS__FED_FEC_PAC_SUMMARY GROUP BY 2
), ps AS (
  SELECT * FROM LIBRARY_MARTS.POLITICS.POLITICS__FED_FEC_PAC_SUMMARY
  WHERE COVERAGE_END_DATE >= '2025-01-01'
  QUALIFY ROW_NUMBER() OVER (PARTITION BY CMTE_ID ORDER BY COVERAGE_END_DATE DESC) = 1
), c AS (
  SELECT FEC_CMTE_ID, CMTE_DSGN,
    CASE WHEN TRES_NM ILIKE '%DATWYLER%' OR TRES_NM ILIKE '%DAWTYLER%' THEN 'DATWYLER'
         WHEN TRES_NM IN ('KILGORE, PAUL','LISKER, LISA','PETTERSON, JAY','HOBBS, CABELL','CURTIS, ELIZABETH','CRATE, BRADLEY T.','MARSTON, CHRIS','BOLES, JASON D') THEN TRES_NM
         ELSE 'all other committees' END grp
  FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_FEC_BULK_COMMITTEES
  WHERE CMTE_TP IN ('N','Q','O','V','W')
)
SELECT * FROM yrs
UNION ALL
SELECT c.grp, c.CMTE_DSGN, COUNT(*), COUNT(ps.CMTE_ID), SUM(ps.TOTAL_RECEIPTS), SUM(ps.INDIVIDUAL_CONTRIBUTIONS), SUM(ps.CONTRIBUTIONS_TO_OTHER_COMMITTEES),
       SUM(ps.INDEPENDENT_EXPENDITURES), SUM(ps.TRANSFERS_TO_AFFILIATES), SUM(ps.TOTAL_DISBURSEMENTS)
FROM c LEFT JOIN ps ON ps.CMTE_ID = c.FEC_CMTE_ID
GROUP BY 1, 2
ORDER BY 1, 2;

-- [6] FEC: clusters vs peers on 2024-cycle PAC money; lowest political-share U PACs with 1M+ from individuals
WITH ps AS (
  SELECT * FROM LIBRARY_MARTS.POLITICS.POLITICS__FED_FEC_PAC_SUMMARY
  WHERE COVERAGE_END_DATE >= '2023-01-01' AND COVERAGE_END_DATE < '2025-01-01'
  QUALIFY ROW_NUMBER() OVER (PARTITION BY CMTE_ID ORDER BY COVERAGE_END_DATE DESC) = 1
), c AS (
  SELECT FEC_CMTE_ID, CMTE_NM, TRES_NM, CMTE_DSGN, CMTE_TP,
    CASE WHEN TRES_NM ILIKE '%DATWYLER%' OR TRES_NM ILIKE '%DAWTYLER%' THEN 'DATWYLER'
         WHEN TRES_NM IN ('KILGORE, PAUL','LISKER, LISA','PETTERSON, JAY','HOBBS, CABELL','CURTIS, ELIZABETH','CRATE, BRADLEY T.','MARSTON, CHRIS','BOLES, JASON D') THEN 'top-8 other treasurers'
         ELSE 'all other committees' END grp
  FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_FEC_BULK_COMMITTEES
  WHERE CMTE_TP IN ('N','Q','O','V','W')
), j AS (
  SELECT c.*, ps.CMTE_ID landed, ps.TOTAL_RECEIPTS rec, ps.INDIVIDUAL_CONTRIBUTIONS indiv, ps.CONTRIBUTIONS_TO_OTHER_COMMITTEES to_c,
         ps.INDEPENDENT_EXPENDITURES ie, ps.TRANSFERS_TO_AFFILIATES xf, ps.TOTAL_DISBURSEMENTS disb, ps.COMMITTEE_NAME ps_name,
         (COALESCE(ps.CONTRIBUTIONS_TO_OTHER_COMMITTEES,0)+COALESCE(ps.INDEPENDENT_EXPENDITURES,0))/NULLIF(ps.TOTAL_DISBURSEMENTS,0) pol_share
  FROM c LEFT JOIN ps ON ps.CMTE_ID = c.FEC_CMTE_ID
)
SELECT 'cluster' k, grp||' | '||CMTE_DSGN name, NULL tres, COUNT(*) n, COUNT(landed) landed, ROUND(SUM(rec)) rec, ROUND(SUM(indiv)) indiv,
       ROUND(SUM(to_c)) to_c, ROUND(SUM(ie)) ie, ROUND(SUM(xf)) xf, ROUND(SUM(disb)) disb,
       ROUND((SUM(to_c)+SUM(ie))/NULLIF(SUM(disb),0),3) pol_share_dollar,
       ROUND(MEDIAN(IFF(indiv >= 100000, pol_share, NULL)),3) med_share_100k, COUNT(IFF(indiv >= 100000, 1, NULL)) n_100k,
       COUNT(IFF(indiv >= 100000 AND pol_share < 0.05, 1, NULL)) n_100k_under5pct
FROM j WHERE CMTE_DSGN IN ('U','D') GROUP BY 1, 2
UNION ALL
SELECT * FROM (
  SELECT 'lowshare', FEC_CMTE_ID||' '||CMTE_NM, TRES_NM, 1, 1, ROUND(rec), ROUND(indiv), ROUND(to_c), ROUND(ie), ROUND(xf), ROUND(disb), ROUND(pol_share,3), NULL, NULL, NULL
  FROM j WHERE landed IS NOT NULL AND CMTE_DSGN = 'U' AND indiv >= 1000000 AND disb > 0
  ORDER BY pol_share ASC LIMIT 30)
ORDER BY 1, 7 DESC;

-- [7] NOAA: COUNT and shape; deaths by event type, 1996-2009 vs 2010+
WITH t AS (SELECT * FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_NOAA_STORM_EVENTS)
SELECT 'shape' k, 'rows / distinct event ids / years / sources' et, COUNT(*) n, COUNT(DISTINCT EVENT_ID) n2,
       MIN(YEAR)||'-'||MAX(YEAR) d1, COUNT(DISTINCT YEAR)::string d2, LISTAGG(DISTINCT DATA_SOURCE, ',') d3,
       SUM(DEATHS_DIRECT) dd, SUM(DEATHS_INDIRECT) di, SUM(INJURIES_DIRECT) inj, COUNT(IFF(DAMAGE_PROPERTY IS NULL OR DAMAGE_PROPERTY = '', 1, NULL)) dmg_blank
FROM t
UNION ALL
SELECT 'type', EVENT_TYPE, COUNT(*), COUNT(IFF(YEAR >= 2010, 1, NULL)),
       SUM(IFF(YEAR BETWEEN 1996 AND 2009, DEATHS_DIRECT, 0))::string, SUM(IFF(YEAR >= 2010, DEATHS_DIRECT, 0))::string,
       SUM(IFF(YEAR >= 2010, DEATHS_INDIRECT, 0))::string, SUM(IFF(YEAR < 1996, DEATHS_DIRECT, 0)),
       MAX(IFF(YEAR >= 2010, DEATHS_DIRECT, 0)), SUM(IFF(YEAR >= 2010, INJURIES_DIRECT, 0)),
       COUNT(IFF(YEAR >= 2010 AND CZ_TYPE = 'Z', 1, NULL))
FROM t GROUP BY EVENT_TYPE
HAVING SUM(DEATHS_DIRECT) >= 100
ORDER BY 1, TRY_TO_NUMBER(d2) DESC NULLS LAST;

-- [8] NOAA: LIMIT 5 sample; top places 2010+ by direct deaths per hazard family
SELECT * FROM (
(SELECT 'sample' k, STATE||' | '||CZ_TYPE||' | '||CZ_NAME place, EVENT_TYPE fam, YEAR::string yrs, EVENT_ID::string n_events,
        DEATHS_DIRECT::string deaths_d, DEATHS_INDIRECT::string deaths_i, DAMAGE_PROPERTY dmg, LEFT(EVENT_NARRATIVE, 120) note
 FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_NOAA_STORM_EVENTS LIMIT 5)
UNION ALL
(SELECT 'place', STATE||' | '||CZ_TYPE||' | '||CZ_NAME,
        CASE WHEN EVENT_TYPE IN ('Heat','Excessive Heat') THEN 'heat' WHEN EVENT_TYPE = 'Tornado' THEN 'tornado'
             WHEN EVENT_TYPE IN ('Flash Flood','Flood','Coastal Flood','Debris Flow','Heavy Rain') THEN 'flood' ELSE 'other' END fam,
        MIN(YEAR)||'-'||MAX(YEAR), COUNT(*)::string, SUM(DEATHS_DIRECT)::string, SUM(DEATHS_INDIRECT)::string,
        COUNT(DISTINCT IFF(DEATHS_DIRECT > 0, YEAR, NULL))::string || ' death-years', MAX(DEATHS_DIRECT)::string || ' max one row'
 FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_NOAA_STORM_EVENTS
 WHERE YEAR >= 2010
 GROUP BY 1, 2, 3
 QUALIFY ROW_NUMBER() OVER (PARTITION BY fam ORDER BY SUM(DEATHS_DIRECT) DESC) <= 8)
) ORDER BY k, fam, TRY_TO_NUMBER(deaths_d) DESC;

-- [9] NOAA: per year, heat deaths by logging office (Phoenix, Las Vegas) vs Texas/California; parsed property damage
WITH t AS (
  SELECT YEAR, WFO, STATE, EVENT_TYPE, DEATHS_DIRECT, DEATHS_INDIRECT,
         TRY_TO_DOUBLE(REGEXP_SUBSTR(DAMAGE_PROPERTY, '^[0-9.]+')) *
           CASE UPPER(RIGHT(TRIM(DAMAGE_PROPERTY), 1)) WHEN 'K' THEN 1e3 WHEN 'M' THEN 1e6 WHEN 'B' THEN 1e9 ELSE 1 END AS dmg
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_NOAA_STORM_EVENTS
)
SELECT YEAR,
  SUM(IFF(EVENT_TYPE IN ('Heat','Excessive Heat'), DEATHS_DIRECT, 0)) heat_us,
  SUM(IFF(EVENT_TYPE IN ('Heat','Excessive Heat') AND WFO = 'PSR', DEATHS_DIRECT, 0)) heat_phoenix_wfo,
  SUM(IFF(EVENT_TYPE IN ('Heat','Excessive Heat') AND WFO = 'VEF', DEATHS_DIRECT, 0)) heat_lasvegas_wfo,
  SUM(IFF(EVENT_TYPE IN ('Heat','Excessive Heat') AND STATE = 'TEXAS', DEATHS_DIRECT, 0)) heat_texas,
  SUM(IFF(EVENT_TYPE IN ('Heat','Excessive Heat') AND STATE = 'CALIFORNIA', DEATHS_DIRECT, 0)) heat_calif,
  COUNT(DISTINCT IFF(EVENT_TYPE IN ('Heat','Excessive Heat') AND DEATHS_DIRECT > 0, WFO, NULL)) wfos_logging_heat_deaths,
  COUNT(DISTINCT WFO) wfos_total,
  SUM(IFF(EVENT_TYPE = 'Tornado', DEATHS_DIRECT, 0)) tornado_us,
  COUNT(*) events, COUNT(IFF(dmg > 0, 1, NULL)) events_with_dmg,
  ROUND(SUM(dmg)/1e9, 2) dmg_bn_nominal, ROUND(MAX(dmg)/1e9, 2) max_row_bn,
  ROUND(MEDIAN(IFF(dmg > 0, dmg, NULL))) median_dmg_when_dmg
FROM t GROUP BY YEAR ORDER BY YEAR;

-- [10] NOAA: Phoenix office heat rows 2017+, where the death counts come from
SELECT YEAR, COUNT(*) heat_rows, COUNT(IFF(DEATHS_DIRECT > 0, 1, NULL)) rows_w_deaths, SUM(DEATHS_DIRECT) dd, SUM(DEATHS_INDIRECT) di,
       MAX(BEGIN_YEARMONTH) last_month,
       MAX_BY(CZ_NAME, DEATHS_DIRECT) top_zone, MAX(DEATHS_DIRECT) top_row_deaths,
       LEFT(MAX_BY(EVENT_NARRATIVE, DEATHS_DIRECT), 420) top_row_event_note,
       LEFT(MAX_BY(EPISODE_NARRATIVE, DEATHS_DIRECT), 300) top_row_episode_note
FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_NOAA_STORM_EVENTS
WHERE WFO = 'PSR' AND EVENT_TYPE IN ('Heat','Excessive Heat') AND YEAR >= 2017
GROUP BY YEAR ORDER BY YEAR;

-- [11] PHMSA: COUNT and shape, LIMIT 5 sample, duplicate report numbers, top release rows
WITH t AS (SELECT * FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_PHMSA_FLAGGED_INCIDENTS)
SELECT * FROM (
SELECT 'shape' k,
  COUNT(*)||' rows; '||COUNT(DISTINCT REPORT_NUMBER)||' report nos; '||COUNT(DISTINCT PHMSA_OPERATOR_ID)||' operator ids; '||COUNT(DISTINCT OPERATOR_NAME)||' names; '||COUNT(DISTINCT _SOURCE_RUN_ID)||' runs' a,
  MIN(INCIDENT_YEAR)||'-'||MAX(INCIDENT_YEAR)||'; recv '||MIN(REPORT_RECEIVED_DATE)||' to '||MAX(REPORT_RECEIVED_DATE) b,
  LISTAGG(DISTINCT REPORT_TYPE, ' / ') c,
  LISTAGG(DISTINCT COMMODITY_RELEASED_TYPE, ' / ') d,
  'unint sum '||ROUND(SUM(TRY_TO_DOUBLE(UNINTENTIONAL_RELEASE_VOLUME::string)))||'; null '||COUNT(IFF(UNINTENTIONAL_RELEASE_VOLUME IS NULL,1,NULL))||'; deaths '||SUM(TOTAL_FATALITIES)||'; inj '||SUM(TOTAL_INJURIES) e,
  LISTAGG(DISTINCT STATUS_WHEN_IDENTIFIED, ' / ') f
FROM t
UNION ALL
(SELECT 'sample', REPORT_NUMBER||' | '||SUPPLEMENTAL_NUMBER||' | '||REPORT_TYPE, OPERATOR_NAME||' | '||PHMSA_OPERATOR_ID||' | '||INCIDENT_YEAR,
   COMMODITY_RELEASED_TYPE||' | '||COALESCE(COMMODITY_DETAILS,''), 'unint '||UNINTENTIONAL_RELEASE_VOLUME||' | int '||INTENTIONAL_RELEASE_VOLUME,
   'fat '||TOTAL_FATALITIES||' inj '||TOTAL_INJURIES||' | '||LOCATION_LATITUDE||','||LOCATION_LONGITUDE, STATUS_WHEN_IDENTIFIED||' | shut '||SHUTDOWN_DUE_ACCIDENT_IND
 FROM t LIMIT 5)
UNION ALL
SELECT 'dup_report', REPORT_NUMBER, COUNT(*)::string, NULL, NULL, NULL, NULL FROM t GROUP BY REPORT_NUMBER HAVING COUNT(*) > 1
UNION ALL
(SELECT 'top_volume', REPORT_NUMBER||' | '||INCIDENT_YEAR||' | '||LOCAL_DATETIME, OPERATOR_NAME, COMMODITY_RELEASED_TYPE||' | '||COALESCE(COMMODITY_DETAILS,''),
   'unint '||UNINTENTIONAL_RELEASE_VOLUME||' | int '||INTENTIONAL_RELEASE_VOLUME, 'fat '||TOTAL_FATALITIES||' inj '||TOTAL_INJURIES||' | '||LOCATION_LATITUDE||','||LOCATION_LONGITUDE, STATUS_WHEN_IDENTIFIED
 FROM t ORDER BY TRY_TO_DOUBLE(UNINTENTIONAL_RELEASE_VOLUME::string) DESC NULLS LAST LIMIT 8)
) ORDER BY k;

-- [12] PHMSA: operators ranked by unintentional release volume, incident count, deaths
WITH t AS (
  SELECT *, TRY_TO_DOUBLE(UNINTENTIONAL_RELEASE_VOLUME::string) uv
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_PHMSA_FLAGGED_INCIDENTS
), op AS (
  SELECT PHMSA_OPERATOR_ID, MAX_BY(OPERATOR_NAME, REPORT_RECEIVED_DATE) name, COUNT(*) incidents,
         COUNT(DISTINCT INCIDENT_YEAR) yrs, ROUND(SUM(uv)) mcf, ROUND(MAX(uv)) max_mcf,
         SUM(TOTAL_FATALITIES) deaths, SUM(TOTAL_INJURIES) inj,
         COUNT(IFF(uv >= 10000, 1, NULL)) n_10k_mcf,
         COUNT(IFF(INCIDENT_YEAR >= 2023, 1, NULL)) n_2023plus,
         ROUND(SUM(IFF(INCIDENT_YEAR >= 2023, uv, 0))) mcf_2023plus
  FROM t GROUP BY PHMSA_OPERATOR_ID
), tot AS (SELECT SUM(mcf) all_mcf, SUM(incidents) all_inc, MEDIAN(incidents) med_inc, MEDIAN(mcf) med_mcf FROM op)
SELECT op.*, ROUND(mcf / all_mcf, 3) share_mcf, all_inc, med_inc, med_mcf,
       RANK() OVER (ORDER BY incidents DESC) rank_by_count
FROM op, tot
QUALIFY RANK() OVER (ORDER BY mcf DESC) <= 15 OR RANK() OVER (ORDER BY incidents DESC) <= 8 OR deaths > 0
ORDER BY mcf DESC;

-- [13] PHMSA: Sea Robin rows 2022+, check for double reports
SELECT REPORT_NUMBER, SUPPLEMENTAL_NUMBER, REPORT_TYPE, NRC_REPORT_NUMBER, LOCAL_DATETIME, REPORT_RECEIVED_DATE,
       UNINTENTIONAL_RELEASE_VOLUME, INTENTIONAL_RELEASE_VOLUME, LOCATION_LATITUDE, LOCATION_LONGITUDE,
       STATUS_WHEN_IDENTIFIED, SHUTDOWN_DUE_ACCIDENT_IND, OPERATOR_NAME, OPERATOR_CITY, OPERATOR_STATE
FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_PHMSA_FLAGGED_INCIDENTS
WHERE PHMSA_OPERATOR_ID = 18152 AND INCIDENT_YEAR >= 2022
ORDER BY LOCAL_DATETIME;

-- [14] Epstein snapshot: COUNT and shape, LIMIT 5 sample, last-seen days, per-dataset not-seen counts
WITH t AS (SELECT * FROM LIBRARY_MARTS.EPSTEIN.FCT_LIBRARY_SNAPSHOT),
m AS (SELECT MAX(LAST_OBSERVED_AT) mx FROM t)
SELECT * FROM (
SELECT 'shape' k, COUNT(*)||' rows; '||COUNT(DISTINCT FILE_URL)||' urls; '||COUNT(DISTINCT DATASET_NAME)||' datasets; '||COUNT(DISTINCT EFTA_FILE_NUMBER)||' efta' a,
       MIN(FIRST_OBSERVED_AT)||' .. '||MAX(FIRST_OBSERVED_AT) b, MIN(LAST_OBSERVED_AT)||' .. '||MAX(LAST_OBSERVED_AT) c,
       LISTAGG(DISTINCT OBSERVED_BY, ' / ') d, SUM(OBSERVATIONS)::string e
FROM t
UNION ALL
(SELECT 'sample', DATASET_NAME||' | '||FILE_URL, FIRST_OBSERVED_AT::string, LAST_OBSERVED_AT::string, OBSERVED_BY, OBSERVATIONS||' obs; '||SOURCES_OBSERVING||' src; '||EFTA_FILE_NUMBER FROM t LIMIT 5)
UNION ALL
SELECT 'last_seen_day', TO_DATE(LAST_OBSERVED_AT)::string, COUNT(*)::string, LISTAGG(DISTINCT OBSERVED_BY, ' / '), LISTAGG(DISTINCT DATASET_NAME, ' / '),
       MIN(FIRST_OBSERVED_AT)||' .. '||MAX(FIRST_OBSERVED_AT)
FROM t GROUP BY TO_DATE(LAST_OBSERVED_AT)
UNION ALL
SELECT 'by_dataset', DATASET_NAME, COUNT(*)::string, COUNT(IFF(TO_DATE(LAST_OBSERVED_AT) < (SELECT TO_DATE(mx) FROM m), 1, NULL))::string || ' not seen on last day',
       LISTAGG(DISTINCT OBSERVED_BY, ' / '), MIN(FIRST_OBSERVED_AT)||' .. '||MAX(LAST_OBSERVED_AT)
FROM t GROUP BY DATASET_NAME
) ORDER BY k, a;

-- [15] Epstein snapshot: the 94 files not seen on the last crawl; renamed? wayback status? on DOJ page table?
WITH t AS (SELECT * FROM LIBRARY_MARTS.EPSTEIN.FCT_LIBRARY_SNAPSHOT),
mx AS (SELECT TO_DATE(MAX(LAST_OBSERVED_AT)) d FROM t),
gone AS (SELECT t.* FROM t, mx WHERE TO_DATE(t.LAST_OBSERVED_AT) < mx.d),
still AS (SELECT t.EFTA_FILE_NUMBER, t.FILE_URL FROM t, mx WHERE TO_DATE(t.LAST_OBSERVED_AT) = mx.d),
wb AS (
  SELECT w.ORIGINAL_URL, COUNT(*) caps, MIN(w.CAPTURED_AT) first_cap, MAX(w.CAPTURED_AT) last_cap,
         MAX_BY(w.STATUS_CODE, w.CAPTURED_AT) last_status,
         LISTAGG(DISTINCT w.STATUS_CODE, ',') statuses,
         COUNT(DISTINCT w.CONTENT_DIGEST) digests
  FROM LIBRARY_MARTS.OPEN_DATA.OPEN_DATA__XC_WAYBACK_DOJ_EPSTEIN w
  WHERE w.ORIGINAL_URL IN (SELECT FILE_URL FROM gone)
     OR REPLACE(w.ORIGINAL_URL, 'http://', 'https://') IN (SELECT FILE_URL FROM gone)
  GROUP BY 1
),
lib AS (SELECT DISTINCT COALESCE(RESOLVED_URL, HREF) u, FETCHED_AT_UTC FROM LIBRARY_MARTS.POLITICS.POLITICS__FED_DOJ_EPSTEIN_LIBRARY)
SELECT g.DATASET_NAME, g.FILE_URL, g.EFTA_FILE_NUMBER, TO_DATE(g.FIRST_OBSERVED_AT) first_seen, TO_DATE(g.LAST_OBSERVED_AT) last_seen, g.OBSERVATIONS,
       (SELECT COUNT(*) FROM still s WHERE s.EFTA_FILE_NUMBER = g.EFTA_FILE_NUMBER) same_efta_still_live,
       (SELECT MIN(s.FILE_URL) FROM still s WHERE s.EFTA_FILE_NUMBER = g.EFTA_FILE_NUMBER) live_url_same_efta,
       wb.caps, wb.first_cap, wb.last_cap, wb.last_status, wb.statuses, wb.digests,
       (SELECT COUNT(*) FROM lib WHERE lib.u = g.FILE_URL) on_doj_page_table
FROM gone g LEFT JOIN wb ON REPLACE(wb.ORIGINAL_URL, 'http://', 'https://') = g.FILE_URL
ORDER BY g.LAST_OBSERVED_AT, g.FILE_URL;

-- [16] Epstein snapshot: fixed URL-path join to Wayback captures; recaptured after last seen? status codes
WITH t AS (SELECT *, LOWER(REPLACE(REGEXP_REPLACE(FILE_URL, '^https?://(www\\.)?justice\\.gov', ''), ' ', '%20')) k FROM LIBRARY_MARTS.EPSTEIN.FCT_LIBRARY_SNAPSHOT),
mx AS (SELECT TO_DATE(MAX(LAST_OBSERVED_AT)) d FROM t),
w AS (
  SELECT LOWER(REPLACE(REGEXP_REPLACE(ORIGINAL_URL, '^https?://(www\\.)?justice\\.gov(:80|:443)?', ''), ' ', '%20')) k, CAPTURED_AT, STATUS_CODE, CONTENT_DIGEST, URLKEY, ORIGINAL_URL
  FROM LIBRARY_MARTS.OPEN_DATA.OPEN_DATA__XC_WAYBACK_DOJ_EPSTEIN
  WHERE ORIGINAL_URL ILIKE '%/epstein/files/%'
),
j AS (
  SELECT IFF(TO_DATE(t.LAST_OBSERVED_AT) < mx.d, 'not seen on last crawl', 'seen on last crawl') grp,
         IFF(t.FILE_URL ILIKE '%.zip', 'zip', 'pdf') kind, t.FILE_URL, t.LAST_OBSERVED_AT,
         COUNT(w.k) caps, MAX(w.CAPTURED_AT) last_cap,
         COUNT(IFF(w.CAPTURED_AT > t.LAST_OBSERVED_AT, 1, NULL)) caps_after_last_seen,
         MAX_BY(w.STATUS_CODE, w.CAPTURED_AT) last_status,
         LISTAGG(DISTINCT IFF(w.CAPTURED_AT > t.LAST_OBSERVED_AT, w.STATUS_CODE, NULL), ',') statuses_after
  FROM t CROSS JOIN mx LEFT JOIN w ON w.k = t.k
  GROUP BY 1, 2, 3, 4
)
SELECT grp, kind, COUNT(*) files, COUNT(IFF(caps > 0, 1, NULL)) landed_in_wayback, SUM(caps) caps,
       COUNT(IFF(caps_after_last_seen > 0, 1, NULL)) files_recaptured_after,
       LISTAGG(DISTINCT last_status, ',') last_statuses, LISTAGG(DISTINCT statuses_after, ',') statuses_after, MAX(last_cap)::string last_cap
FROM j GROUP BY 1, 2
UNION ALL
SELECT * FROM (SELECT 'format', URLKEY, NULL, NULL, NULL, NULL, STATUS_CODE::string, ORIGINAL_URL, CAPTURED_AT::string FROM w WHERE ORIGINAL_URL ILIKE '%EFTA0000061%' LIMIT 4)
UNION ALL
SELECT 'wayback_total', MIN(CAPTURED_AT)::string||' .. '||MAX(CAPTURED_AT)::string, COUNT(*), COUNT(DISTINCT k), NULL, NULL, LISTAGG(DISTINCT STATUS_CODE, ','), NULL, NULL FROM w;

-- [17] ICIS-FEC inspections: COUNT and shape, LIMIT 5 sample, statute mix, top registry ids
WITH t AS (SELECT * FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_EPA_ICIS_FEC_ICIS_FEC_EPA_INSPECTIONS)
SELECT * FROM (
SELECT 'shape' k, COUNT(*)||' rows; '||COUNT(DISTINCT ACTIVITY_ID)||' activity ids; '||COUNT(DISTINCT COMP_MONITOR_UID)||' cm uids; '||COUNT(DISTINCT REGISTRY_ID)||' registry ids; null reg '||COUNT(IFF(REGISTRY_ID IS NULL,1,NULL)) a,
  MIN(ACTUAL_BEGIN_DATE)||' .. '||MAX(ACTUAL_BEGIN_DATE)||'; before 1990: '||COUNT(IFF(ACTUAL_BEGIN_DATE < '1990-01-01',1,NULL))||'; null: '||COUNT(IFF(ACTUAL_BEGIN_DATE IS NULL,1,NULL)) b,
  LISTAGG(DISTINCT COMP_MONITOR_AGENCY_TYPES, ' / ') c, LISTAGG(DISTINCT ACTIVITY_TYPE_CODE, ',') d, COUNT(DISTINCT STATUTE_CODE)::string e
FROM t
UNION ALL
(SELECT 'sample', REGISTRY_ID||' | '||PGM_SYS_ACRNM||' | '||PGM_SYS_ID||' | '||FACILITY_NAME, EPA_REGION_CODE||' | '||ACTIVITY_TYPE_CODE||' | '||ACTUAL_BEGIN_DATE||' | '||ACTUAL_END_DATE,
   COMP_MONITOR_TYPES, STATUTE_CODE||' '||LAW_SECTION_CODE, COMP_MONITOR_AGENCY_TYPES||' | '||AGENCY FROM t LIMIT 5)
UNION ALL
SELECT 'statute', STATUTE_CODE, COUNT(*)::string, COUNT(IFF(ACTUAL_BEGIN_DATE >= '2015-01-01',1,NULL))::string, LISTAGG(DISTINCT COMP_MONITOR_AGENCY_TYPES, ' / '), NULL
FROM t GROUP BY STATUTE_CODE
UNION ALL
(SELECT 'top_reg', REGISTRY_ID||' | '||MAX(FACILITY_NAME), COUNT(*)::string, LISTAGG(DISTINCT STATUTE_CODE, ','), LEFT(LISTAGG(DISTINCT COMP_MONITOR_TYPES, ','),120), MIN(ACTUAL_BEGIN_DATE)||' .. '||MAX(ACTUAL_BEGIN_DATE)
 FROM t GROUP BY REGISTRY_ID ORDER BY COUNT(*) DESC LIMIT 8)
) ORDER BY k, TRY_TO_NUMBER(b) DESC NULLS LAST;

-- [18] ICIS-FEC inspections: January-June counts 2019-2026 by region, statute, agency and import vs rest
WITH t AS (
  SELECT LPAD(TRIM(EPA_REGION_CODE), 2, '0') region, STATUTE_CODE, YEAR(ACTUAL_BEGIN_DATE) y,
         IFF(COMP_MONITOR_AGENCY_TYPES ILIKE '%U.S. EPA%' OR COMP_MONITOR_AGENCY_TYPES ILIKE '%EPA Contractor%', 'EPA', 'not EPA') who,
         COMP_MONITOR_TYPES
  FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_EPA_ICIS_FEC_ICIS_FEC_EPA_INSPECTIONS
  WHERE ACTIVITY_TYPE_CODE = 'INS' AND MONTH(ACTUAL_BEGIN_DATE) BETWEEN 1 AND 6 AND YEAR(ACTUAL_BEGIN_DATE) BETWEEN 2019 AND 2026
)
SELECT 'region' dim, region v,
  COUNT(IFF(y=2019,1,NULL)) h1_19, COUNT(IFF(y=2020,1,NULL)) h1_20, COUNT(IFF(y=2021,1,NULL)) h1_21, COUNT(IFF(y=2022,1,NULL)) h1_22,
  COUNT(IFF(y=2023,1,NULL)) h1_23, COUNT(IFF(y=2024,1,NULL)) h1_24, COUNT(IFF(y=2025,1,NULL)) h1_25, COUNT(IFF(y=2026,1,NULL)) h1_26
FROM t GROUP BY 2
UNION ALL
SELECT 'statute', STATUTE_CODE,
  COUNT(IFF(y=2019,1,NULL)), COUNT(IFF(y=2020,1,NULL)), COUNT(IFF(y=2021,1,NULL)), COUNT(IFF(y=2022,1,NULL)),
  COUNT(IFF(y=2023,1,NULL)), COUNT(IFF(y=2024,1,NULL)), COUNT(IFF(y=2025,1,NULL)), COUNT(IFF(y=2026,1,NULL))
FROM t GROUP BY 2
UNION ALL
SELECT 'who', who,
  COUNT(IFF(y=2019,1,NULL)), COUNT(IFF(y=2020,1,NULL)), COUNT(IFF(y=2021,1,NULL)), COUNT(IFF(y=2022,1,NULL)),
  COUNT(IFF(y=2023,1,NULL)), COUNT(IFF(y=2024,1,NULL)), COUNT(IFF(y=2025,1,NULL)), COUNT(IFF(y=2026,1,NULL))
FROM t GROUP BY 2
UNION ALL
SELECT 'type_import_vs_rest', IFF(COMP_MONITOR_TYPES ILIKE '%Import%', 'import checks', 'everything else'),
  COUNT(IFF(y=2019,1,NULL)), COUNT(IFF(y=2020,1,NULL)), COUNT(IFF(y=2021,1,NULL)), COUNT(IFF(y=2022,1,NULL)),
  COUNT(IFF(y=2023,1,NULL)), COUNT(IFF(y=2024,1,NULL)), COUNT(IFF(y=2025,1,NULL)), COUNT(IFF(y=2026,1,NULL))
FROM t GROUP BY 2
ORDER BY 1, 2;

-- [19] ICIS-FEC: on-site inspections since 2015 per facility joined to enforcement cases and informal actions, by region
WITH ins AS (
  SELECT REGISTRY_ID, LPAD(TRIM(MAX(EPA_REGION_CODE)), 2, '0') region, MAX(FACILITY_NAME) name, COUNT(*) n_ins,
         LISTAGG(DISTINCT STATUTE_CODE, ',') statutes, MIN(ACTUAL_BEGIN_DATE) first_ins, MAX(ACTUAL_BEGIN_DATE) last_ins
  FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_EPA_ICIS_FEC_ICIS_FEC_EPA_INSPECTIONS
  WHERE ACTIVITY_TYPE_CODE = 'INS' AND ACTUAL_BEGIN_DATE >= '2015-01-01' AND REGISTRY_ID IS NOT NULL
    AND COALESCE(COMP_MONITOR_TYPES, '') NOT ILIKE '%Import%' AND COALESCE(COMP_MONITOR_TYPES, '') NOT ILIKE '%Desk Audit%'
  GROUP BY REGISTRY_ID
), cs AS (
  SELECT REGISTRY_ID, COUNT(DISTINCT CASE_NUMBER) n_cases FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_EPA_ICIS_FEC_CASE_FACILITIES
  WHERE REGISTRY_ID IS NOT NULL GROUP BY 1
), inf AS (
  SELECT REGISTRY_ID, COUNT(*) n_inf FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_EPA_ICIS_FEC_EPA_INFORMAL_ENFORCEMENT_ACTIONS
  WHERE REGISTRY_ID IS NOT NULL GROUP BY 1
), j AS (
  SELECT ins.*, COALESCE(n_cases, 0) n_cases, COALESCE(n_inf, 0) n_inf FROM ins LEFT JOIN cs USING (REGISTRY_ID) LEFT JOIN inf USING (REGISTRY_ID)
)
SELECT * FROM (
SELECT 'region' k, region v, COUNT(*) fac_any, COUNT(IFF(n_ins >= 5, 1, NULL)) fac_5plus,
       ROUND(AVG(IFF(n_cases > 0, 1, 0)), 3) share_any_case_all,
       ROUND(AVG(IFF(n_ins >= 5, IFF(n_cases > 0, 1, 0), NULL)), 3) share_case_5plus,
       ROUND(AVG(IFF(n_ins >= 5, IFF(n_cases = 0 AND n_inf = 0, 1, 0), NULL)), 3) share_neither_5plus,
       NULL::string statutes, NULL::string span
FROM j GROUP BY region
UNION ALL
SELECT 'ALL', 'nation', COUNT(*), COUNT(IFF(n_ins >= 5, 1, NULL)), ROUND(AVG(IFF(n_cases > 0, 1, 0)), 3),
       ROUND(AVG(IFF(n_ins >= 5, IFF(n_cases > 0, 1, 0), NULL)), 3), ROUND(AVG(IFF(n_ins >= 5, IFF(n_cases = 0 AND n_inf = 0, 1, 0), NULL)), 3), NULL, NULL
FROM j
UNION ALL
(SELECT 'top_no_action', REGISTRY_ID||' | '||name||' | R'||region, n_ins, n_cases, n_inf, NULL, NULL, statutes, first_ins||' .. '||last_ins
 FROM j WHERE n_cases = 0 AND n_inf = 0 ORDER BY n_ins DESC LIMIT 12)
) ORDER BY k, v;

-- [20] NOAA: every heat-named event type 2022+, check for a renamed type and the Phoenix cutoff month
SELECT EVENT_TYPE, YEAR, COUNT(*) rows_all, SUM(DEATHS_DIRECT) dd_all, SUM(DEATHS_INDIRECT) di_all,
       COUNT(IFF(WFO = 'PSR', 1, NULL)) rows_psr, SUM(IFF(WFO = 'PSR', DEATHS_DIRECT, 0)) dd_psr,
       SUM(IFF(WFO = 'VEF', DEATHS_DIRECT, 0)) dd_vef,
       MIN(BEGIN_YEARMONTH) first_month, MAX(BEGIN_YEARMONTH) last_month,
       MAX(IFF(WFO = 'PSR', BEGIN_YEARMONTH, NULL)) psr_last_month,
       (SELECT MAX(BEGIN_YEARMONTH) FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_NOAA_STORM_EVENTS) table_last_month,
       (SELECT MAX(BEGIN_YEARMONTH) FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_NOAA_STORM_EVENTS WHERE WFO = 'PSR') psr_any_type_last_month
FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_NOAA_STORM_EVENTS
WHERE EVENT_TYPE ILIKE '%heat%' AND YEAR >= 2022
GROUP BY 1, 2 ORDER BY 1, 2;

-- [21] FEC: Datwyler unauthorized and leadership PACs with 100K+ from individuals, 2024 cycle money
WITH ps AS (
  SELECT * FROM LIBRARY_MARTS.POLITICS.POLITICS__FED_FEC_PAC_SUMMARY
  WHERE COVERAGE_END_DATE >= '2023-01-01' AND COVERAGE_END_DATE < '2025-01-01'
  QUALIFY ROW_NUMBER() OVER (PARTITION BY CMTE_ID ORDER BY COVERAGE_END_DATE DESC) = 1
)
SELECT c.FEC_CMTE_ID, c.CMTE_NM, c.CMTE_DSGN, c.CMTE_TP, c.CMTE_ST1||' '||c.CMTE_CITY addr, c.CONNECTED_ORG_NM,
       ps.COMMITTEE_NAME ps_name, ROUND(ps.TOTAL_RECEIPTS) rec, ROUND(ps.INDIVIDUAL_CONTRIBUTIONS) indiv,
       ROUND(ps.CONTRIBUTIONS_TO_OTHER_COMMITTEES) to_cmtes, ROUND(ps.INDEPENDENT_EXPENDITURES) ie,
       ROUND(ps.TRANSFERS_TO_AFFILIATES) xfer_aff, ROUND(ps.TOTAL_DISBURSEMENTS) disb,
       ROUND((COALESCE(ps.CONTRIBUTIONS_TO_OTHER_COMMITTEES,0)+COALESCE(ps.INDEPENDENT_EXPENDITURES,0))/NULLIF(ps.TOTAL_DISBURSEMENTS,0), 3) pol_share,
       ps.PCT_DISBURSED_TO_OTHERS, ps.COVERAGE_END_DATE
FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_FEC_BULK_COMMITTEES c
JOIN ps ON ps.CMTE_ID = c.FEC_CMTE_ID
WHERE (c.TRES_NM ILIKE '%DATWYLER%' OR c.TRES_NM ILIKE '%DAWTYLER%') AND c.CMTE_DSGN IN ('U','D') AND ps.INDIVIDUAL_CONTRIBUTIONS >= 100000
ORDER BY pol_share;

-- [22] Epstein snapshot: EFTA ranges seen vs not seen; land rate in DOJ library page table
WITH t AS (SELECT *, TO_DATE(LAST_OBSERVED_AT) = (SELECT TO_DATE(MAX(LAST_OBSERVED_AT)) FROM LIBRARY_MARTS.EPSTEIN.FCT_LIBRARY_SNAPSHOT) seen_last
           FROM LIBRARY_MARTS.EPSTEIN.FCT_LIBRARY_SNAPSHOT),
lib AS (SELECT * FROM LIBRARY_MARTS.POLITICS.POLITICS__FED_DOJ_EPSTEIN_LIBRARY)
SELECT 'efta_range' k, DATASET_NAME||' | seen_last='||seen_last v, COUNT(*)::string n, MIN(TRY_TO_NUMBER(EFTA_FILE_NUMBER))::string lo, MAX(TRY_TO_NUMBER(EFTA_FILE_NUMBER))::string hi,
       MIN(FIRST_OBSERVED_AT)::string f, MAX(LAST_OBSERVED_AT)::string l
FROM t WHERE DATASET_NAME IN ('DataSet%201', 'DataSet%203', 'DataSet%2012', 'DataSet%2011') GROUP BY 1, 2
UNION ALL
SELECT 'lib_land', 'snapshot urls found in DOJ library page table', COUNT(*)::string,
       COUNT(IFF(EXISTS (SELECT 1 FROM lib WHERE lib.HREF = t.FILE_URL OR lib.RESOLVED_URL = t.FILE_URL), 1, NULL))::string, NULL, NULL, NULL
FROM t
UNION ALL
SELECT 'lib_shape', COUNT(*)||' rows; '||COUNT(DISTINCT PAGE_URL)||' pages; '||COUNT(IFF(HREF ILIKE '%/epstein/files/%',1,NULL))||' file links', MIN(FETCHED_AT_UTC)::string, MAX(FETCHED_AT_UTC)::string,
       LEFT(LISTAGG(DISTINCT PAGE_URL, ' ; '), 200), NULL, NULL
FROM lib
UNION ALL
SELECT * FROM (SELECT 'lib_sample', HREF, RESOLVED_URL, LEFT(LINK_TEXT, 80), PAGE_URL, FETCHED_AT_UTC::string, NULL FROM lib WHERE HREF ILIKE '%DataSet%' LIMIT 4)
ORDER BY 1, 2;

-- [23] Lookup: any independent heat-death, mortality or pipeline-mileage table to check against
SELECT table_schema, table_name, row_count
FROM LIBRARY_MARTS.INFORMATION_SCHEMA.TABLES
WHERE (table_name ILIKE '%HEAT%' OR table_name ILIKE '%WONDER%' OR table_name ILIKE '%MORTAL%' OR table_name ILIKE '%DEATH%'
   OR table_name ILIKE '%NVSS%' OR table_name ILIKE '%PHMSA%' OR table_name ILIKE '%PIPELINE%' OR table_name ILIKE '%FEMA%DECLAR%')
  AND table_schema <> 'TIMELINE'
ORDER BY 1, 2;

-- [24] PHMSA: gas released per year with Sea Robin's part; 2023+ roll-up by operator street address
WITH t AS (
  SELECT *, TRY_TO_DOUBLE(UNINTENTIONAL_RELEASE_VOLUME::string) uv
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_PHMSA_FLAGGED_INCIDENTS
)
SELECT * FROM (
SELECT 'year' k, INCIDENT_YEAR::string v, COUNT(*) incidents, ROUND(SUM(uv)) mcf, ROUND(MEDIAN(uv)) med_mcf,
       ROUND(SUM(IFF(PHMSA_OPERATOR_ID = 18152, uv, 0))) sea_robin_mcf, SUM(TOTAL_FATALITIES)::string deaths, NULL names
FROM t GROUP BY INCIDENT_YEAR
UNION ALL
(SELECT 'addr_2023plus', UPPER(OPERATOR_STREET_ADDRESS)||' | '||OPERATOR_CITY, COUNT(*), ROUND(SUM(uv)), ROUND(MEDIAN(uv)),
        COUNT(DISTINCT PHMSA_OPERATOR_ID), ROUND(SUM(uv) / (SELECT SUM(uv) FROM t WHERE INCIDENT_YEAR >= 2023), 3)::string,
        LEFT(LISTAGG(DISTINCT OPERATOR_NAME, '; '), 220)
 FROM t WHERE INCIDENT_YEAR >= 2023 GROUP BY 2 ORDER BY 4 DESC LIMIT 8)
) ORDER BY k, v;

-- [25] NOAA: Phoenix office summer months 2023-2025, any events at all; FEMA IA registrations and IHP dollars by incident type 2010+
SELECT * FROM (
SELECT 'psr_month' k, BEGIN_YEARMONTH::string v, COUNT(*) n,
       COUNT(IFF(EVENT_TYPE IN ('Heat','Excessive Heat'), 1, NULL)) n2, SUM(DEATHS_DIRECT) n3,
       LEFT(LISTAGG(DISTINCT EVENT_TYPE, ', '), 150) note
FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_NOAA_STORM_EVENTS
WHERE WFO = 'PSR' AND BEGIN_YEARMONTH IN (202306, 202307, 202308, 202309, 202406, 202407, 202408, 202409, 202506, 202507, 202508, 202509)
GROUP BY BEGIN_YEARMONTH
UNION ALL
SELECT 'fema_ia_2010plus', INCIDENT_TYPE_CODE, COUNT(*), COUNT(DISTINCT DISASTER_NUMBER),
       ROUND(SUM(IFF(LOWER(TO_VARCHAR(IHP_AMOUNT)) IN ('nan', ''), NULL, TRY_TO_DOUBLE(TO_VARCHAR(IHP_AMOUNT)))) / 1e6),
       MIN(LEFT(TO_VARCHAR(DECLARATION_DATE), 10))||' .. '||MAX(LEFT(TO_VARCHAR(DECLARATION_DATE), 10))
FROM LIBRARY_MARTS.HOUSING.HOUSING__FED_FEMA_IA_HOUSING_REGISTRATIONS
WHERE LEFT(TO_VARCHAR(DECLARATION_DATE), 4) >= '2010'
GROUP BY INCIDENT_TYPE_CODE
) ORDER BY k, n DESC;

-- [26] PHMSA: same operator, same release volume on more than one report (double-report check), table-wide
WITH t AS (
  SELECT *, TRY_TO_DOUBLE(UNINTENTIONAL_RELEASE_VOLUME::string) uv, TRY_TO_DOUBLE(INTENTIONAL_RELEASE_VOLUME::string) iv
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_PHMSA_FLAGGED_INCIDENTS
)
SELECT 'same_unintentional_volume' k, PHMSA_OPERATOR_ID, MAX(OPERATOR_NAME) name, uv vol, COUNT(*) reports,
       LISTAGG(REPORT_NUMBER||'@'||TO_DATE(LOCAL_DATETIME), ', ') reps, COUNT(DISTINCT NRC_REPORT_NUMBER) nrc_ids
FROM t WHERE uv >= 10000 GROUP BY PHMSA_OPERATOR_ID, uv HAVING COUNT(*) > 1
UNION ALL
SELECT 'same_intentional_volume', PHMSA_OPERATOR_ID, MAX(OPERATOR_NAME), iv, COUNT(*),
       LISTAGG(REPORT_NUMBER||'@'||TO_DATE(LOCAL_DATETIME), ', '), COUNT(DISTINCT NRC_REPORT_NUMBER)
FROM t WHERE iv >= 10000 GROUP BY PHMSA_OPERATOR_ID, iv HAVING COUNT(*) > 1
ORDER BY 1, 4 DESC;

-- [27] ICIS-FEC: within one law at a time, share of inspected facilities with any enforcement, by region (peer check)
WITH ins AS (
  SELECT REGISTRY_ID, STATUTE_CODE, LPAD(TRIM(MAX(EPA_REGION_CODE)), 2, '0') region, COUNT(*) n_ins
  FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_EPA_ICIS_FEC_ICIS_FEC_EPA_INSPECTIONS
  WHERE ACTIVITY_TYPE_CODE = 'INS' AND ACTUAL_BEGIN_DATE >= '2015-01-01' AND REGISTRY_ID IS NOT NULL
    AND COALESCE(COMP_MONITOR_TYPES, '') NOT ILIKE '%Import%' AND COALESCE(COMP_MONITOR_TYPES, '') NOT ILIKE '%Desk Audit%'
    AND COALESCE(COMP_MONITOR_TYPES, '') NOT ILIKE '%Motor Vehicle%'
    AND STATUTE_CODE IN ('RCRA', 'TSCA', 'CAA', 'CWA')
  GROUP BY REGISTRY_ID, STATUTE_CODE
), cs AS (
  SELECT REGISTRY_ID, COUNT(DISTINCT CASE_NUMBER) n_cases FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_EPA_ICIS_FEC_CASE_FACILITIES
  WHERE REGISTRY_ID IS NOT NULL GROUP BY 1
), inf AS (
  SELECT REGISTRY_ID, COUNT(*) n_inf FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_EPA_ICIS_FEC_EPA_INFORMAL_ENFORCEMENT_ACTIONS
  WHERE REGISTRY_ID IS NOT NULL GROUP BY 1
), j AS (
  SELECT ins.*, COALESCE(n_cases, 0) n_cases, COALESCE(n_inf, 0) n_inf FROM ins LEFT JOIN cs USING (REGISTRY_ID) LEFT JOIN inf USING (REGISTRY_ID)
)
SELECT STATUTE_CODE, region, COUNT(*) fac, COUNT(IFF(n_ins >= 2, 1, NULL)) fac_2plus,
       ROUND(AVG(IFF(n_cases > 0 OR n_inf > 0, 1, 0)), 3) share_any_action,
       ROUND(AVG(IFF(n_ins >= 2, IFF(n_cases = 0 AND n_inf = 0, 1, 0), NULL)), 3) share_no_action_2plus
FROM j GROUP BY 1, 2 HAVING COUNT(*) >= 100
ORDER BY 1, 2;
