-- deep-11, coverage round 2, 2026-09-24. Door: Python (connect/db.py). Read-only.
-- Every connection first ran the two session settings: statement timeout 300s, query tag 'coverage-r2-2026-09-24'.

-- [1] counts_all_five
SELECT 'WAYBACK_DOJ_LISTING' t, COUNT(*) n FROM LIBRARY_MARTS.INVESTIGATIONS.INVESTIGATIONS__XC_WAYBACK_REPLAY_DOJ_LISTING
UNION ALL SELECT 'DOUBLE_BURDEN', COUNT(*) FROM LIBRARY_MARTS.JUSTICE.JUSTICE__COUNTY_DOUBLE_BURDEN
UNION ALL SELECT 'CSL', COUNT(*) FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_CONSOLIDATED_SCREENING_LIST
UNION ALL SELECT 'GIFTS', COUNT(*) FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_COURTLISTENER_DISCLOSURE_GIFTS
UNION ALL SELECT 'POSITIONS', COUNT(*) FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_COURTLISTENER_DISCLOSURE_POSITIONS;

-- [2] sample_wayback
SELECT * FROM LIBRARY_MARTS.INVESTIGATIONS.INVESTIGATIONS__XC_WAYBACK_REPLAY_DOJ_LISTING LIMIT 5;

-- [3] sample_double_burden
SELECT * FROM LIBRARY_MARTS.JUSTICE.JUSTICE__COUNTY_DOUBLE_BURDEN LIMIT 5;

-- [4] sample_csl
SELECT * FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_CONSOLIDATED_SCREENING_LIST LIMIT 5;

-- [5] sample_gifts
SELECT * FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_COURTLISTENER_DISCLOSURE_GIFTS LIMIT 5;

-- [6] sample_positions
SELECT * FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_COURTLISTENER_DISCLOSURE_POSITIONS LIMIT 5;

-- [7] wayback_pages_vanished_hrefs
WITH w AS (
  SELECT PAGE_URL, CAPTURE_TIMESTAMP_RAW ts, HREF, LINK_TEXT
  FROM LIBRARY_MARTS.INVESTIGATIONS.INVESTIGATIONS__XC_WAYBACK_REPLAY_DOJ_LISTING
  WHERE HREF NOT ILIKE '%sharer%' AND HREF NOT ILIKE '%twitter.com%' AND HREF NOT ILIKE '%x.com/%' AND HREF NOT ILIKE '%linkedin%' AND HREF NOT ILIKE 'mailto:%'
),
pg AS (SELECT PAGE_URL, COUNT(DISTINCT ts) caps, MIN(ts) first_ts, MAX(ts) last_ts, COUNT(DISTINCT PAGE_URL||ts) x FROM w GROUP BY 1),
h AS (SELECT PAGE_URL, HREF, MIN(ts) h_first, MAX(ts) h_last, COUNT(DISTINCT ts) h_caps FROM w GROUP BY 1, 2)
SELECT pg.PAGE_URL, pg.caps, pg.first_ts, pg.last_ts, COUNT(*) hrefs_ever,
  COUNT_IF(h.h_last = pg.last_ts) hrefs_in_last,
  COUNT_IF(h.h_last < pg.last_ts) hrefs_vanished,
  COUNT_IF(h.h_first > pg.first_ts) hrefs_added_later,
  COUNT_IF(h.h_last < pg.last_ts AND h.HREF ILIKE '%/dl%') vanished_dl_files,
  COUNT_IF(h.h_last < pg.last_ts AND (h.HREF ILIKE '%.pdf%' OR h.HREF ILIKE '%/media/%' OR h.HREF ILIKE '%dataset%' OR h.HREF ILIKE '%data-set%' OR h.HREF ILIKE '%.zip%')) vanished_filelike
FROM pg JOIN h ON h.PAGE_URL = pg.PAGE_URL
GROUP BY 1, 2, 3, 4 ORDER BY caps DESC;

-- [8] wayback_vanished_by_kind
WITH w AS (
  SELECT PAGE_URL, CAPTURE_TIMESTAMP_RAW ts, HREF, LINK_TEXT
  FROM LIBRARY_MARTS.INVESTIGATIONS.INVESTIGATIONS__XC_WAYBACK_REPLAY_DOJ_LISTING
  WHERE HREF NOT ILIKE '%sharer%' AND HREF NOT ILIKE '%twitter.com%' AND HREF NOT ILIKE '%linkedin%' AND HREF NOT ILIKE 'mailto:%'
),
pg AS (SELECT PAGE_URL, MAX(ts) last_ts FROM w GROUP BY 1),
caps AS (SELECT DISTINCT PAGE_URL, ts FROM w),
h AS (SELECT PAGE_URL, HREF, ANY_VALUE(LINK_TEXT) txt, MIN(ts) h_first, MAX(ts) h_last, COUNT(DISTINCT ts) h_caps FROM w GROUP BY 1, 2),
anywhere AS (SELECT HREF, MAX(ts) last_any FROM w GROUP BY 1),
txt_last AS (SELECT DISTINCT w.PAGE_URL, w.LINK_TEXT FROM w JOIN pg ON pg.PAGE_URL = w.PAGE_URL AND w.ts = pg.last_ts),
v AS (
  SELECT h.*, pg.last_ts,
    (SELECT COUNT(*) FROM caps c WHERE c.PAGE_URL = h.PAGE_URL AND c.ts BETWEEN h.h_first AND h.h_last) caps_in_window,
    a.last_any,
    IFF(t.LINK_TEXT IS NOT NULL, 1, 0) same_text_still_on_page,
    CASE WHEN h.HREF ILIKE '%.pdf' THEN 'pdf' WHEN h.HREF ILIKE '%.zip%' THEN 'zip' WHEN h.HREF ILIKE '%?page=%' THEN 'pager'
         WHEN h.HREF ILIKE '%/media/%' THEN 'media' WHEN h.HREF ILIKE '/epstein%' THEN 'epstein nav' ELSE 'other' END kind
  FROM h JOIN pg ON pg.PAGE_URL = h.PAGE_URL
  LEFT JOIN anywhere a ON a.HREF = h.HREF
  LEFT JOIN txt_last t ON t.PAGE_URL = h.PAGE_URL AND t.LINK_TEXT = h.txt
  WHERE h.h_last < pg.last_ts
)
SELECT kind, COUNT(*) vanished, COUNT_IF(last_any = (SELECT MAX(last_ts) FROM pg) OR last_any >= '20260526000000') seen_elsewhere_late,
  COUNT_IF(same_text_still_on_page = 1) same_text_on_page_now, COUNT_IF(h_caps < caps_in_window) flickered,
  MIN(h_last) min_last, MAX(h_last) max_last, ANY_VALUE(HREF) ex_href, ANY_VALUE(txt) ex_text
FROM v GROUP BY 1 ORDER BY 2 DESC;

-- [9] wayback_vanished_detail
WITH w AS (
  SELECT PAGE_URL, CAPTURE_TIMESTAMP_RAW ts, HREF, LINK_TEXT
  FROM LIBRARY_MARTS.INVESTIGATIONS.INVESTIGATIONS__XC_WAYBACK_REPLAY_DOJ_LISTING
  WHERE HREF NOT ILIKE '%sharer%' AND HREF NOT ILIKE '%twitter.com%' AND HREF NOT ILIKE '%linkedin%' AND HREF NOT ILIKE 'mailto:%'
),
pg AS (SELECT PAGE_URL, MAX(ts) last_ts, COUNT(DISTINCT ts) caps FROM w GROUP BY 1),
h AS (SELECT PAGE_URL, HREF, ANY_VALUE(LINK_TEXT) txt, MIN(ts) h_first, MAX(ts) h_last, COUNT(DISTINCT ts) h_caps FROM w GROUP BY 1, 2),
txt_last AS (SELECT DISTINCT w.PAGE_URL, w.LINK_TEXT FROM w JOIN pg ON pg.PAGE_URL = w.PAGE_URL AND w.ts = pg.last_ts),
nxt AS (
  SELECT h.PAGE_URL, h.HREF, MIN(c.ts) next_cap FROM h JOIN (SELECT DISTINCT PAGE_URL, ts FROM w) c ON c.PAGE_URL = h.PAGE_URL AND c.ts > h.h_last GROUP BY 1, 2
),
v AS (
  SELECT h.*, n.next_cap,
    CASE WHEN h.HREF ILIKE '%.pdf' THEN 'pdf' WHEN h.HREF ILIKE '%.zip%' THEN 'zip' WHEN h.HREF ILIKE '%?page=%' THEN 'pager'
         WHEN h.HREF ILIKE '%/media/%' THEN 'media' WHEN h.HREF ILIKE '/epstein%' THEN 'epstein nav' ELSE 'other' END kind
  FROM h JOIN pg ON pg.PAGE_URL = h.PAGE_URL
  LEFT JOIN txt_last t ON t.PAGE_URL = h.PAGE_URL AND t.LINK_TEXT = h.txt
  LEFT JOIN nxt n ON n.PAGE_URL = h.PAGE_URL AND n.HREF = h.HREF
  WHERE h.h_last < pg.last_ts AND t.LINK_TEXT IS NULL AND h.HREF NOT ILIKE '%?page=%'
)
SELECT REPLACE(PAGE_URL, 'https://www.justice.gov/epstein/doj-disclosures', '') pg, kind, COUNT(*) n, MIN(h_first) first_seen, MAX(h_last) last_seen, MIN(next_cap) gone_by,
  SUM(h_caps) caps_sum, LISTAGG(DISTINCT LEFT(txt, 45), ' || ') WITHIN GROUP (ORDER BY LEFT(txt, 45)) texts
FROM v GROUP BY 1, 2 ORDER BY 2, 1;

-- [10] wayback_did_vanished_items_move
WITH k AS (
  SELECT * FROM VALUES ('flight log', '%flight log%'), ('masseuse list', '%masseuse%'), ('contact book', '%contact book%'), ('evidence list', '%evidence list%'),
    ('BOP video hour', '%2019.08.1%'), ('BOP video hour', '%2019.08.09%'), ('BOP video any', '%video%'), ('OIG memo 23-085', '%23-085%'), ('OPR report', '%professional responsib%'),
    ('zip download', '%.zip%'), ('zip download', '%download all%'), ('court records', '%court record%'), ('Farmer v Indyke', '%farmer v%'), ('Bondi letter', '%bondi%')
  AS t(item, pat)
),
u AS (
  SELECT 'LISTING' src, PAGE_URL, CAPTURE_TIMESTAMP_RAW ts, HREF, LINK_TEXT FROM LIBRARY_MARTS.INVESTIGATIONS.INVESTIGATIONS__XC_WAYBACK_REPLAY_DOJ_LISTING
  UNION ALL
  SELECT 'DEEP', PAGE_URL, CAPTURE_TIMESTAMP_RAW, HREF, LINK_TEXT FROM LIBRARY_MARTS.INVESTIGATIONS.INVESTIGATIONS__XC_WAYBACK_REPLAY_DOJ_DEEP_PAGES
)
SELECT k.item, u.src, COUNT(*) rows_, COUNT(DISTINCT u.PAGE_URL) pages, MIN(u.ts) first_ts, MAX(u.ts) last_ts,
  COUNT_IF(u.ts >= '20260210000000') rows_after_feb10,
  LISTAGG(DISTINCT IFF(u.ts >= '20260210000000', REPLACE(u.PAGE_URL, 'https://www.justice.gov', '') || ' -> ' || LEFT(u.HREF, 70), NULL), ' || ') late_where
FROM u JOIN k ON (u.LINK_TEXT ILIKE k.pat OR u.HREF ILIKE k.pat)
GROUP BY 1, 2 ORDER BY 1, 2;

-- [11] wayback_main_page_newest_capture_links
WITH w AS (SELECT * FROM LIBRARY_MARTS.INVESTIGATIONS.INVESTIGATIONS__XC_WAYBACK_REPLAY_DOJ_LISTING WHERE PAGE_URL = 'https://www.justice.gov/epstein/doj-disclosures'),
lastcap AS (SELECT MAX(CAPTURE_TIMESTAMP_RAW) ts FROM w)
SELECT LEFT(HREF, 90) href, LEFT(LINK_TEXT, 60) txt, (SELECT MIN(CAPTURE_TIMESTAMP_RAW) FROM w w2 WHERE w2.HREF = w.HREF) first_seen
FROM w, lastcap WHERE w.CAPTURE_TIMESTAMP_RAW = lastcap.ts AND HREF NOT ILIKE '%sharer%' AND HREF NOT ILIKE '%twitter%' AND HREF NOT ILIKE '%linkedin%'
ORDER BY first_seen, href;

-- [12] dbl_burden_by_jail_year
SELECT CASE WHEN JAIL_RATE_YEAR IS NULL THEN 'null' WHEN JAIL_RATE_YEAR < 2015 THEN 'pre-2015' WHEN JAIL_RATE_YEAR < 2019 THEN '2015-18' ELSE TO_VARCHAR(JAIL_RATE_YEAR) END yr,
  COUNT(*) counties, COUNT_IF(DOUBLE_BURDEN) dbl, COUNT_IF(IS_JAIL_TOP_DECILE) jail_top, COUNT_IF(IS_OVERDOSE_TOP_DECILE) od_top,
  MEDIAN(JAIL_RATE) med_rate, MAX(JAIL_RATE) max_rate, MEDIAN(JAIL_POPULATION) med_pop, COUNT_IF(JAIL_POPULATION < 1) pop_under_1,
  COUNT_IF(JAIL_RATE > 2000) rate_over_2000, MIN(IFF(IS_JAIL_TOP_DECILE, JAIL_RATE, NULL)) jail_top_cutoff,
  COUNT(DISTINCT OVERDOSE_RATE_BAND) od_bands, MIN(IFF(IS_OVERDOSE_TOP_DECILE, OVERDOSE_METRIC, NULL)) od_top_min_metric,
  COUNT_IF(OVERDOSE_RATE_BAND IS NULL) od_null
FROM LIBRARY_MARTS.JUSTICE.JUSTICE__COUNTY_DOUBLE_BURDEN
GROUP BY ROLLUP(1) ORDER BY 1;

-- [13] dbl_burden_flagged_list
SELECT STATE_ABBR st, COUNTY_NAME, FIPS, OVERDOSE_RATE_BAND od_band, ROUND(JAIL_RATE) jail_rate, JAIL_RATE_YEAR yr, ROUND(JAIL_POPULATION, 1) jail_pop,
  ROUND(JAIL_POPULATION / NULLIF(JAIL_RATE, 0) * 100000) implied_base_pop, ROUND(BLACK_JAIL_RATE) blk, ROUND(WHITE_JAIL_RATE) wht
FROM LIBRARY_MARTS.JUSTICE.JUSTICE__COUNTY_DOUBLE_BURDEN
WHERE DOUBLE_BURDEN
ORDER BY st, jail_rate DESC;

-- [14] dbl_burden_vs_otp_clinics
WITH otp AS (
  SELECT NPI, LEFT(REGEXP_REPLACE(ZIP, '[^0-9]', ''), 5) zip5 FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_OPIOID_TREATMENT_PROGRAM_PROVIDERS
),
xw AS (SELECT DISTINCT LPAD(ZCTA5, 5, '0') zcta, LPAD(COUNTY_FIPS, 5, '0') fips FROM LIBRARY_MARTS.CORE.XWALK_ZCTA_COUNTY),
landed AS (SELECT o.NPI, o.zip5, x.fips FROM otp o LEFT JOIN xw x ON x.zcta = o.zip5),
per_county AS (SELECT fips, COUNT(DISTINCT NPI) otps FROM landed WHERE fips IS NOT NULL GROUP BY 1),
c AS (
  SELECT d.*, COALESCE(p.otps, 0) otps,
    CASE WHEN DOUBLE_BURDEN THEN '1 double burden' WHEN IS_OVERDOSE_TOP_DECILE THEN '2 overdose top only' WHEN IS_JAIL_TOP_DECILE THEN '3 jail top only' ELSE '4 rest' END grp
  FROM LIBRARY_MARTS.JUSTICE.JUSTICE__COUNTY_DOUBLE_BURDEN d LEFT JOIN per_county p ON p.fips = LPAD(d.FIPS, 5, '0')
)
SELECT grp, COUNT(*) counties, COUNT_IF(otps > 0) with_otp, ROUND(COUNT_IF(otps > 0) / COUNT(*), 3) share_with_otp, SUM(otps) otp_sites,
  ROUND(SUM(JAIL_POPULATION / NULLIF(JAIL_RATE, 0) * 100000)) base_pop_sum,
  ROUND(SUM(otps) / NULLIF(SUM(JAIL_POPULATION / NULLIF(JAIL_RATE, 0) * 100000), 0) * 100000, 2) otps_per_100k_base,
  (SELECT COUNT(*) FROM otp) otp_rows, (SELECT COUNT(DISTINCT NPI) FROM landed WHERE fips IS NOT NULL) otp_npis_landed, (SELECT COUNT(DISTINCT NPI) FROM otp) otp_npis
FROM c GROUP BY 1 ORDER BY 1;

-- [15] csl_profile_lists
SELECT LEFT(SOURCE_LIST, 45) list, COALESCE(NULLIF(ENTITY_TYPE, ''), '(blank)') etype, COUNT(*) n, COUNT(DISTINCT ENTRY_ID) ids,
  COUNT_IF(START_DATE IS NOT NULL) has_start, MIN(START_DATE) s0, MAX(START_DATE) s1,
  COUNT_IF(REGEXP_LIKE(ADDRESSES, '.*(, | )(US|USA|United States)\s*$') OR ADDRESSES ILIKE '%United States%') us_addr,
  COUNT_IF(NULLIF(ALT_NAMES, '') IS NOT NULL) has_alt, ANY_VALUE(LEFT(ADDRESSES, 50)) ex_addr
FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_CONSOLIDATED_SCREENING_LIST
GROUP BY 1, 2 ORDER BY n DESC;

-- [16] csl_name_match_r2_contracts
WITH csl_raw AS (
  SELECT ENTRY_ID, LEFT(SOURCE_LIST, 30) list, COALESCE(NULLIF(ENTITY_TYPE, ''), '(blank)') etype, START_DATE, NAME, ADDRESSES, NAME nm FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_CONSOLIDATED_SCREENING_LIST
  WHERE COALESCE(ENTITY_TYPE, '') NOT IN ('Individual', 'Vessel', 'Aircraft')
  UNION
  SELECT ENTRY_ID, LEFT(SOURCE_LIST, 30), COALESCE(NULLIF(ENTITY_TYPE, ''), '(blank)'), START_DATE, NAME, ADDRESSES, TRIM(s.VALUE) FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_CONSOLIDATED_SCREENING_LIST, LATERAL SPLIT_TO_TABLE(ALT_NAMES, ';') s
  WHERE COALESCE(ENTITY_TYPE, '') NOT IN ('Individual', 'Vessel', 'Aircraft') AND NULLIF(TRIM(s.VALUE), '') IS NOT NULL
),
csl AS (
  SELECT *, TRIM(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(' ' || REGEXP_REPLACE(UPPER(nm), '[^A-Z0-9 ]', ' ') || ' ',
     ' (LLC|L L C|LTD|LIMITED|INC|INCORPORATED|CO|CORP|CORPORATION|COMPANY|JSC|OJSC|PJSC|OOO|ZAO|GMBH|SA|AG|PLC|LLP|THE|OF) ', ' '),
     ' (LLC|L L C|LTD|LIMITED|INC|INCORPORATED|CO|CORP|CORPORATION|COMPANY|JSC|OJSC|PJSC|OOO|ZAO|GMBH|SA|AG|PLC|LLP|THE|OF) ', ' '), '\s+', ' ')) k
  FROM csl_raw
),
csl_k AS (SELECT * FROM csl WHERE ARRAY_SIZE(SPLIT(k, ' ')) >= 2 AND LENGTH(k) >= 8),
r2 AS (
  SELECT RECIPIENT_NAME, SUM(FEDERAL_ACTION_OBLIGATION) usd, COUNT(*) actions, MIN(ACTION_DATE) d0, MAX(ACTION_DATE) d1,
    ANY_VALUE(RECIPIENT_COUNTRY_NAME) ctry, ANY_VALUE(RECIPIENT_STATE_CODE) st, ANY_VALUE(RECIPIENT_UEI) uei, ANY_VALUE(AWARDING_AGENCY_NAME) agency
  FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_USASPENDING_CONTRACTS_FULL_R2 GROUP BY 1
),
r2k AS (
  SELECT *, TRIM(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(' ' || REGEXP_REPLACE(UPPER(RECIPIENT_NAME), '[^A-Z0-9 ]', ' ') || ' ',
     ' (LLC|L L C|LTD|LIMITED|INC|INCORPORATED|CO|CORP|CORPORATION|COMPANY|JSC|OJSC|PJSC|OOO|ZAO|GMBH|SA|AG|PLC|LLP|THE|OF) ', ' '),
     ' (LLC|L L C|LTD|LIMITED|INC|INCORPORATED|CO|CORP|CORPORATION|COMPANY|JSC|OJSC|PJSC|OOO|ZAO|GMBH|SA|AG|PLC|LLP|THE|OF) ', ' '), '\s+', ' ')) k
  FROM r2
)
SELECT c.list, c.etype, c.ENTRY_ID, LEFT(c.NAME, 45) csl_name, c.START_DATE, LEFT(c.ADDRESSES, 40) csl_addr, LEFT(r.RECIPIENT_NAME, 45) recipient, r.ctry, r.st,
  ROUND(r.usd) usd, r.actions, r.d0, r.d1, LEFT(r.agency, 30) agency, r.uei, (SELECT COUNT(DISTINCT RECIPIENT_NAME) FROM r2) r2_names, (SELECT COUNT(DISTINCT ENTRY_ID) FROM csl_k) csl_entries_keyed
FROM csl_k c JOIN r2k r ON r.k = c.k
QUALIFY ROW_NUMBER() OVER (PARTITION BY c.ENTRY_ID, r.RECIPIENT_NAME ORDER BY c.nm) = 1
ORDER BY r.usd DESC NULLS LAST;

-- [17] csl_name_match_r2_lean
WITH csl_raw AS (
  SELECT ENTRY_ID, LEFT(SOURCE_LIST, 30) list, START_DATE, NAME, ADDRESSES, NAME nm FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_CONSOLIDATED_SCREENING_LIST
  WHERE COALESCE(ENTITY_TYPE, '') NOT IN ('Individual', 'Vessel', 'Aircraft')
  UNION
  SELECT ENTRY_ID, LEFT(SOURCE_LIST, 30), START_DATE, NAME, ADDRESSES, TRIM(s.VALUE) FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_CONSOLIDATED_SCREENING_LIST, LATERAL SPLIT_TO_TABLE(ALT_NAMES, ';') s
  WHERE COALESCE(ENTITY_TYPE, '') NOT IN ('Individual', 'Vessel', 'Aircraft') AND NULLIF(TRIM(s.VALUE), '') IS NOT NULL
),
csl_k AS (
  SELECT * FROM (
    SELECT *, TRIM(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(' ' || REGEXP_REPLACE(UPPER(nm), '[^A-Z0-9 ]', ' ') || ' ',
       ' (LLC|L L C|LTD|LIMITED|INC|INCORPORATED|CO|CORP|CORPORATION|COMPANY|JSC|OJSC|PJSC|OOO|ZAO|GMBH|SA|AG|PLC|LLP|THE|OF) ', ' '),
       ' (LLC|L L C|LTD|LIMITED|INC|INCORPORATED|CO|CORP|CORPORATION|COMPANY|JSC|OJSC|PJSC|OOO|ZAO|GMBH|SA|AG|PLC|LLP|THE|OF) ', ' '), '\s+', ' ')) k
    FROM csl_raw) WHERE ARRAY_SIZE(SPLIT(k, ' ')) >= 2 AND LENGTH(k) >= 8
),
r2 AS (
  SELECT RECIPIENT_NAME, SUM(FEDERAL_ACTION_OBLIGATION) usd, COUNT(*) actions, MIN(ACTION_DATE) d0, MAX(ACTION_DATE) d1
  FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_USASPENDING_CONTRACTS_FULL_R2 GROUP BY 1
),
r2k AS (
  SELECT *, TRIM(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(' ' || REGEXP_REPLACE(UPPER(RECIPIENT_NAME), '[^A-Z0-9 ]', ' ') || ' ',
     ' (LLC|L L C|LTD|LIMITED|INC|INCORPORATED|CO|CORP|CORPORATION|COMPANY|JSC|OJSC|PJSC|OOO|ZAO|GMBH|SA|AG|PLC|LLP|THE|OF) ', ' '),
     ' (LLC|L L C|LTD|LIMITED|INC|INCORPORATED|CO|CORP|CORPORATION|COMPANY|JSC|OJSC|PJSC|OOO|ZAO|GMBH|SA|AG|PLC|LLP|THE|OF) ', ' '), '\s+', ' ')) k
  FROM r2
)
SELECT DISTINCT c.list, c.ENTRY_ID, LEFT(c.NAME, 45) csl_name, c.START_DATE, LEFT(c.ADDRESSES, 45) csl_addr, LEFT(r.RECIPIENT_NAME, 45) recipient,
  ROUND(r.usd) usd, r.actions, r.d0, r.d1
FROM csl_k c JOIN r2k r ON r.k = c.k
ORDER BY usd DESC NULLS LAST;

-- [18] csl_us_parties_contracts_in_window
WITH csl_raw AS (
  SELECT ENTRY_ID, LEFT(SOURCE_LIST, 12) list, START_DATE, END_DATE, NAME, ADDRESSES, NAME nm FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_CONSOLIDATED_SCREENING_LIST
  WHERE COALESCE(ENTITY_TYPE, '') NOT IN ('Individual', 'Vessel', 'Aircraft')
  UNION
  SELECT ENTRY_ID, LEFT(SOURCE_LIST, 12), START_DATE, END_DATE, NAME, ADDRESSES, TRIM(s.VALUE) FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_CONSOLIDATED_SCREENING_LIST, LATERAL SPLIT_TO_TABLE(ALT_NAMES, ';') s
  WHERE COALESCE(ENTITY_TYPE, '') NOT IN ('Individual', 'Vessel', 'Aircraft') AND NULLIF(TRIM(s.VALUE), '') IS NOT NULL
),
csl_k AS (
  SELECT * FROM (
    SELECT *, TRIM(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(' ' || REGEXP_REPLACE(UPPER(nm), '[^A-Z0-9 ]', ' ') || ' ',
       ' (LLC|L L C|LTD|LIMITED|INC|INCORPORATED|CO|CORP|CORPORATION|COMPANY|JSC|OJSC|PJSC|OOO|ZAO|GMBH|SA|AG|PLC|LLP|THE|OF) ', ' '),
       ' (LLC|L L C|LTD|LIMITED|INC|INCORPORATED|CO|CORP|CORPORATION|COMPANY|JSC|OJSC|PJSC|OOO|ZAO|GMBH|SA|AG|PLC|LLP|THE|OF) ', ' '), '\s+', ' ')) k
    FROM csl_raw) WHERE ARRAY_SIZE(SPLIT(k, ' ')) >= 2 AND LENGTH(k) >= 8
),
names AS (
  SELECT DISTINCT RECIPIENT_NAME, TRIM(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(' ' || REGEXP_REPLACE(UPPER(RECIPIENT_NAME), '[^A-Z0-9 ]', ' ') || ' ',
     ' (LLC|L L C|LTD|LIMITED|INC|INCORPORATED|CO|CORP|CORPORATION|COMPANY|JSC|OJSC|PJSC|OOO|ZAO|GMBH|SA|AG|PLC|LLP|THE|OF) ', ' '),
     ' (LLC|L L C|LTD|LIMITED|INC|INCORPORATED|CO|CORP|CORPORATION|COMPANY|JSC|OJSC|PJSC|OOO|ZAO|GMBH|SA|AG|PLC|LLP|THE|OF) ', ' '), '\s+', ' ')) k
  FROM (SELECT DISTINCT RECIPIENT_NAME FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_USASPENDING_CONTRACTS_FULL_R2)
),
m AS (SELECT DISTINCT c.*, n.RECIPIENT_NAME FROM csl_k c JOIN names n ON n.k = c.k),
rows_ AS (
  SELECT r.RECIPIENT_NAME, r.RECIPIENT_STATE_CODE st, r.RECIPIENT_CITY_NAME city, r.RECIPIENT_COUNTRY_NAME ctry, r.ACTION_DATE, r.FEDERAL_ACTION_OBLIGATION usd, r.AWARDING_AGENCY_NAME ag, r.RECIPIENT_UEI uei
  FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_USASPENDING_CONTRACTS_FULL_R2 r WHERE r.RECIPIENT_NAME IN (SELECT RECIPIENT_NAME FROM m)
)
SELECT m.list, LEFT(m.NAME, 34) csl_name, m.START_DATE, m.END_DATE, LEFT(m.ADDRESSES, 38) csl_addr, LEFT(m.RECIPIENT_NAME, 34) recipient,
  LISTAGG(DISTINCT r.st, ',') r_states, ANY_VALUE(r.city) r_city, ANY_VALUE(LEFT(r.ctry, 14)) r_ctry,
  BOOLOR_AGG(m.ADDRESSES ILIKE '% ' || r.st || ' %' AND m.ADDRESSES ILIKE '%US%' AND r.city IS NOT NULL AND m.ADDRESSES ILIKE '%' || r.city || '%') city_state_agree,
  ROUND(SUM(r.usd)) usd_all, ROUND(SUM(IFF(r.ACTION_DATE >= m.START_DATE AND (m.END_DATE IS NULL OR r.ACTION_DATE <= m.END_DATE), r.usd, 0))) usd_in_listing_window,
  COUNT_IF(r.ACTION_DATE >= m.START_DATE AND (m.END_DATE IS NULL OR r.ACTION_DATE <= m.END_DATE)) actions_in_window,
  MIN(IFF(r.ACTION_DATE >= m.START_DATE, r.ACTION_DATE, NULL)) first_after, MAX(r.ACTION_DATE) last_action, ANY_VALUE(LEFT(r.ag, 25)) agency
FROM m JOIN rows_ r ON r.RECIPIENT_NAME = m.RECIPIENT_NAME
WHERE m.list IN ('Denied Perso', 'ITAR Debarre') OR m.ADDRESSES ILIKE '% US' OR m.ADDRESSES ILIKE '% US;%'
GROUP BY 1, 2, 3, 4, 5, 6 ORDER BY city_state_agree DESC, usd_in_listing_window DESC NULLS LAST;

-- [19] csl_foreign_exact_matches_detail
WITH c AS (
  SELECT ENTRY_ID, NAME, PROGRAMS, LEFT(ADDRESSES, 40) addr, LEFT(REMARKS, 80) remarks, LEFT(IDENTIFIER_DOCUMENTS, 70) ids
  FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_CONSOLIDATED_SCREENING_LIST
  WHERE ENTRY_ID IN ('44257', '44599', '55921', '57507', '50147', '35799', '51663', '47926')
),
r AS (
  SELECT RECIPIENT_NAME, RECIPIENT_COUNTRY_NAME ctry, RECIPIENT_CITY_NAME city, AWARDING_AGENCY_NAME ag, AWARDING_SUB_AGENCY_NAME sub, ACTION_DATE, FEDERAL_ACTION_OBLIGATION usd,
    TRANSACTION_DESCRIPTION td, PRIMARY_PLACE_OF_PERFORMANCE_CITY_NAME pop_city, RECIPIENT_UEI
  FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_USASPENDING_CONTRACTS_FULL_R2
  WHERE RECIPIENT_NAME IN ('NAI LOGISTICS B.V.', 'FIDELIS LOGISTIC AND SUPPLY SERVICES', 'GEOTECH ENGINEERING LIMITED', 'ATLAS INTERNATIONAL TRADING CORPORATION',
    'GARDEN CITY HOTEL LLC', 'SKYLINE AVIATION LLC', 'INTERSTATE BANK', 'ECHELON TECHNOLOGIES, CORP.')
)
SELECT r.RECIPIENT_NAME, c.ENTRY_ID, c.PROGRAMS, c.addr, c.remarks, c.ids, LISTAGG(DISTINCT LEFT(r.ctry, 20), ',') r_ctry, LISTAGG(DISTINCT LEFT(r.city, 20), ',') r_city,
  ANY_VALUE(LEFT(r.sub, 30)) sub_agency, MIN(r.ACTION_DATE) d0, MAX(r.ACTION_DATE) d1, ROUND(SUM(r.usd)) usd, COUNT(*) actions, ANY_VALUE(LEFT(r.td, 60)) what, COUNT(DISTINCT r.RECIPIENT_UEI) ueis
FROM r JOIN c ON UPPER(REGEXP_REPLACE(c.NAME, '[^A-Za-z]', '')) = UPPER(REGEXP_REPLACE(r.RECIPIENT_NAME, '[^A-Za-z]', ''))
  OR (c.ENTRY_ID = '57507' AND r.RECIPIENT_NAME ILIKE 'ATLAS INTERNATIONAL%') OR (c.ENTRY_ID = '50147' AND r.RECIPIENT_NAME ILIKE 'GARDEN CITY%')
  OR (c.ENTRY_ID = '35799' AND r.RECIPIENT_NAME ILIKE 'SKYLINE%') OR (c.ENTRY_ID = '47926' AND r.RECIPIENT_NAME ILIKE 'ECHELON%')
GROUP BY 1, 2, 3, 4, 5, 6 ORDER BY usd DESC;

-- [20] csl_rahmani_network_contracts_by_year
SELECT RECIPIENT_NAME, IFF(ACTION_DATE >= '2022-12-09', 'on/after 2022-12-09', 'before') period, YEAR(ACTION_DATE) yr, COUNT(*) actions,
  ROUND(SUM(FEDERAL_ACTION_OBLIGATION)) usd, COUNT_IF(FEDERAL_ACTION_OBLIGATION > 0) pos_actions, ROUND(SUM(IFF(FEDERAL_ACTION_OBLIGATION > 0, FEDERAL_ACTION_OBLIGATION, 0))) pos_usd,
  COUNT(DISTINCT AWARD_ID_PIID) awards, MAX(ACTION_DATE) last_d, ANY_VALUE(LEFT(PRODUCT_OR_SERVICE_CODE_DESCRIPTION, 40)) psc, ANY_VALUE(LEFT(TRANSACTION_DESCRIPTION, 50)) td,
  ANY_VALUE(RECIPIENT_PARENT_NAME) parent
FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_USASPENDING_CONTRACTS_FULL_R2
WHERE RECIPIENT_NAME IN ('NAI LOGISTICS B.V.', 'FIDELIS LOGISTIC AND SUPPLY SERVICES') OR RECIPIENT_NAME ILIKE 'NAI LOGISTIC%' OR RECIPIENT_PARENT_NAME ILIKE 'NAI LOGISTIC%'
GROUP BY 1, 2, 3 ORDER BY 1, 3;

-- [21] csl_rahmani_network_contracts_by_year_retry
SELECT RECIPIENT_NAME, IFF(ACTION_DATE >= '2022-12-09', 'on/after 2022-12-09', 'before') period, LEFT(ACTION_DATE, 4) yr, COUNT(*) actions,
  ROUND(SUM(FEDERAL_ACTION_OBLIGATION)) usd, COUNT_IF(FEDERAL_ACTION_OBLIGATION > 0) pos_actions, ROUND(SUM(IFF(FEDERAL_ACTION_OBLIGATION > 0, FEDERAL_ACTION_OBLIGATION, 0))) pos_usd,
  COUNT(DISTINCT AWARD_ID_PIID) awards, MAX(ACTION_DATE) last_d, ANY_VALUE(LEFT(PRODUCT_OR_SERVICE_CODE_DESCRIPTION, 40)) psc, ANY_VALUE(LEFT(TRANSACTION_DESCRIPTION, 50)) td,
  ANY_VALUE(RECIPIENT_PARENT_NAME) parent
FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_USASPENDING_CONTRACTS_FULL_R2
WHERE RECIPIENT_NAME IN ('NAI LOGISTICS B.V.', 'FIDELIS LOGISTIC AND SUPPLY SERVICES') OR RECIPIENT_NAME ILIKE 'NAI LOGISTIC%' OR RECIPIENT_PARENT_NAME ILIKE 'NAI LOGISTIC%'
GROUP BY 1, 2, 3 ORDER BY 1, 3;

-- [22] csl_rahmani_in_sam_exclusions
SELECT 'match' k, ENTITY_NAME, FIRST_NAME, LAST_NAME, EXCLUDING_AGENCY, EXCLUSION_PROGRAM, ACTIVATION_DATE, TERMINATION_DATE, COUNTRY, UEI, CAGE_CODE, IS_CURRENTLY_EXCLUDED
FROM LIBRARY_MARTS.PROCUREMENT.PROCUREMENT__FED_SAM_EXCLUSIONS
WHERE ENTITY_NAME ILIKE '%NAI LOGISTIC%' OR ENTITY_NAME ILIKE '%FIDELIS LOGISTIC%' OR LAST_NAME ILIKE 'RAHMANI' OR ENTITY_NAME ILIKE '%RAHMANI%'
UNION ALL
SELECT 'treasury rows', NULL, NULL, NULL, EXCLUDING_AGENCY, NULL, MIN(ACTIVATION_DATE), MAX(ACTIVATION_DATE), NULL, NULL, NULL, COUNT(*)::VARCHAR
FROM LIBRARY_MARTS.PROCUREMENT.PROCUREMENT__FED_SAM_EXCLUSIONS WHERE EXCLUDING_AGENCY ILIKE '%TREAS%' GROUP BY EXCLUDING_AGENCY;

-- [23] csl_rahmani_in_sam_exclusions_retry
SELECT 'match' k, ENTITY_NAME, FIRST_NAME, LAST_NAME, EXCLUDING_AGENCY, EXCLUSION_PROGRAM, ACTIVATION_DATE, TERMINATION_DATE, COUNTRY, UEI, CAGE_CODE, IS_CURRENTLY_EXCLUDED::VARCHAR
FROM LIBRARY_MARTS.PROCUREMENT.PROCUREMENT__FED_SAM_EXCLUSIONS
WHERE ENTITY_NAME ILIKE '%NAI LOGISTIC%' OR ENTITY_NAME ILIKE '%FIDELIS LOGISTIC%' OR LAST_NAME ILIKE 'RAHMANI' OR ENTITY_NAME ILIKE '%RAHMANI%'
UNION ALL
SELECT 'treasury rows', NULL, NULL, NULL, EXCLUDING_AGENCY, NULL, MIN(ACTIVATION_DATE), MAX(ACTIVATION_DATE), NULL, NULL, NULL, COUNT(*)::VARCHAR
FROM LIBRARY_MARTS.PROCUREMENT.PROCUREMENT__FED_SAM_EXCLUSIONS WHERE EXCLUDING_AGENCY ILIKE '%TREAS%' GROUP BY EXCLUDING_AGENCY;

-- [24] csl_nai_uei_and_post_exclusion_actions
SELECT RECIPIENT_UEI, RECIPIENT_UEI = 'P8ATG76DP1Y3' uei_matches_sam_exclusion, RECIPIENT_COUNTRY_NAME, COUNT(*) actions,
  COUNT_IF(ACTION_DATE >= '2023-01-01') actions_2023, COUNT_IF(ACTION_DATE >= '2023-12-11') actions_after_sam_exclusion,
  ROUND(SUM(IFF(ACTION_DATE >= '2023-12-11', FEDERAL_ACTION_OBLIGATION, 0)), 2) usd_after_sam_exclusion,
  LISTAGG(DISTINCT IFF(ACTION_DATE >= '2023-12-01', ACTION_DATE || ' ' || FEDERAL_ACTION_OBLIGATION || ' ' || LEFT(AWARD_ID_PIID, 20), NULL), ' | ') dec_2023_actions,
  LISTAGG(DISTINCT LEFT(AWARDING_OFFICE_NAME_X, 1), '') x
FROM (SELECT *, AWARDING_SUB_AGENCY_NAME AWARDING_OFFICE_NAME_X FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_USASPENDING_CONTRACTS_FULL_R2 WHERE RECIPIENT_NAME = 'NAI LOGISTICS B.V.')
GROUP BY 1, 2, 3;

-- [25] gifts_by_kind
WITH fd AS (
  SELECT ID, PERSON_ID, TRY_TO_NUMBER(YEAR_COL::VARCHAR) yr FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_COURTLISTENER_FINANCIAL_DISCLOSURES
  QUALIFY ROW_NUMBER() OVER (PARTITION BY ID ORDER BY DATE_MODIFIED DESC) = 1
),
g AS (
  SELECT x.*, fd.PERSON_ID, fd.yr, TRY_TO_NUMBER(REGEXP_REPLACE(x.VALUE_COL, '[^0-9.]', ''), 12, 2) usd,
    CASE WHEN SOURCE ILIKE ANY ('%bar %', '%bar', '%bar council%', '%inn of court%', '%judges assoc%', '%judicial%', '%law school%', '%university%', '%college%', '%federalist%', '%american constitution%', '%aspen%') THEN 'bar/law school/judicial/university'
         WHEN SOURCE ILIKE ANY ('%club%', '%country%', '%golf%') THEN 'club membership'
         WHEN SOURCE ILIKE ANY ('%llp%', '%p.c.%', '%law firm%', '%& %', '%pllc%') THEN 'law-firm-like'
         WHEN NULLIF(TRIM(SOURCE), '') IS NULL OR SOURCE ILIKE ANY ('exempt', 'none%', 'n/a%') THEN 'blank/exempt/none'
         ELSE 'other' END kind
  FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_COURTLISTENER_DISCLOSURE_GIFTS x LEFT JOIN fd ON fd.ID = x.FINANCIAL_DISCLOSURE_ID
)
SELECT kind, COUNT(*) gifts, COUNT(DISTINCT PERSON_ID) judges, COUNT_IF(PERSON_ID IS NULL) no_judge, COUNT_IF(usd IS NOT NULL) valued, ROUND(SUM(usd)) usd_sum, MEDIAN(usd) med, MAX(usd) max_usd,
  MIN(IFF(yr BETWEEN 1990 AND 2030, yr, NULL)) y0, MAX(IFF(yr BETWEEN 1990 AND 2030, yr, NULL)) y1, COUNT_IF(REDACTED = 't') redacted,
  ANY_VALUE(LEFT(SOURCE, 30) || ' / ' || LEFT(DESCRIPTION, 30) || ' / ' || COALESCE(VALUE_COL, '')) ex
FROM g GROUP BY ROLLUP(kind) ORDER BY gifts DESC;

-- [26] gifts_source_as_party_same_judge
WITH fd AS (
  SELECT ID, PERSON_ID, TRY_TO_NUMBER(YEAR_COL::VARCHAR) yr FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_COURTLISTENER_FINANCIAL_DISCLOSURES
  WHERE PERSON_ID IS NOT NULL QUALIFY ROW_NUMBER() OVER (PARTITION BY ID ORDER BY DATE_MODIFIED DESC) = 1
),
g AS (
  SELECT DISTINCT fd.PERSON_ID, fd.yr, x.SOURCE, LEFT(x.DESCRIPTION, 40) descr, x.VALUE_COL,
    TRIM(REGEXP_REPLACE(REGEXP_REPLACE(' ' || REGEXP_REPLACE(UPPER(x.SOURCE), '[^A-Z0-9 ]', ' ') || ' ', ' (THE|INC|LLP|LLC|CORP|CO|LTD|PC|P C) ', ' '), '\s+', ' ')) src
  FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_COURTLISTENER_DISCLOSURE_GIFTS x JOIN fd ON fd.ID = x.FINANCIAL_DISCLOSURE_ID
  WHERE fd.yr BETWEEN 2000 AND 2023
),
gk AS (SELECT * FROM g WHERE ARRAY_SIZE(SPLIT(src, ' ')) >= 2 AND LENGTH(src) >= 8),
judges AS (SELECT DISTINCT PERSON_ID FROM gk),
dk AS (
  SELECT k.ID docket_id, k.ASSIGNED_TO_ID, TRY_TO_NUMBER(LEFT(k.DATE_FILED::VARCHAR, 4)) fy, k.CASE_NAME, k.COURT_ID, k.NATURE_OF_SUIT,
    ' ' || TRIM(REGEXP_REPLACE(REGEXP_REPLACE(UPPER(k.CASE_NAME), '[^A-Z0-9 ]', ' '), '\s+', ' ')) || ' ' cn
  FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_COURTLISTENER_DOCKETS k JOIN judges j ON j.PERSON_ID = k.ASSIGNED_TO_ID
),
hits AS (
  SELECT gk.PERSON_ID, gk.SOURCE, gk.descr, gk.VALUE_COL, gk.yr, dk.docket_id, dk.fy, dk.CASE_NAME, dk.COURT_ID, dk.NATURE_OF_SUIT
  FROM gk JOIN dk ON dk.ASSIGNED_TO_ID = gk.PERSON_ID AND dk.fy BETWEEN gk.yr - 1 AND gk.yr + 2 AND POSITION(' ' || gk.src || ' ' IN dk.cn) > 0
)
SELECT j.NAME_FIRST || ' ' || j.NAME_LAST judge, LEFT(h.SOURCE, 40) source, LEFT(ANY_VALUE(h.descr), 35) gift, ANY_VALUE(h.VALUE_COL) val, MIN(h.yr) gift_yr,
  COUNT(DISTINCT h.docket_id) dockets, MIN(h.fy) fy0, MAX(h.fy) fy1, LISTAGG(DISTINCT h.COURT_ID, ',') courts, LEFT(ANY_VALUE(h.CASE_NAME), 70) case_ex, LEFT(ANY_VALUE(h.NATURE_OF_SUIT), 30) nos,
  (SELECT COUNT(*) FROM gk) gift_pairs_tested, (SELECT COUNT(DISTINCT PERSON_ID) FROM gk) judges_tested, (SELECT COUNT(*) FROM dk) dockets_scanned
FROM hits h LEFT JOIN LIBRARY_MARTS.JUSTICE.JUSTICE__FED_COURTLISTENER_JUDGES j ON j.ID = h.PERSON_ID
GROUP BY 1, 2 ORDER BY dockets DESC;

-- [27] positions_by_kind
WITH fd AS (
  SELECT ID, PERSON_ID, TRY_TO_NUMBER(YEAR_COL::VARCHAR) yr FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_COURTLISTENER_FINANCIAL_DISCLOSURES
  QUALIFY ROW_NUMBER() OVER (PARTITION BY ID ORDER BY DATE_MODIFIED DESC) = 1
),
p AS (
  SELECT x.*, fd.PERSON_ID, fd.yr,
    CASE WHEN ORGANIZATION_NAME ILIKE ANY ('%trust #%', '%trust no%', 'trust%', '%family trust%', '%revocable%', '%irrevocable%', '%estate of%', '%living trust%') THEN 'family trust/estate'
         WHEN ORGANIZATION_NAME ILIKE ANY ('%bar %', '%bar', '%inn of court%', '%judges assoc%', '%judicial%', '%federal judges%', '%american law institute%', '%law institute%') THEN 'bar/judicial'
         WHEN ORGANIZATION_NAME ILIKE ANY ('%university%', '%college%', '%school%', '%academy%') THEN 'university/school'
         WHEN ORGANIZATION_NAME ILIKE ANY ('%church%', '%synagogue%', '%temple%', '%parish%', '%diocese%', '%congregation%', '%ministr%') THEN 'religious'
         WHEN ORGANIZATION_NAME ILIKE ANY ('%hospital%', '%medical%', '%health%', '%clinic%') THEN 'hospital/health'
         WHEN ORGANIZATION_NAME ILIKE ANY ('%inc%', '%llc%', '%corp%', '%company%', '%l.p.%', '%partners%', '% lp', '%ltd%', '%bank%') THEN 'company-like'
         WHEN NULLIF(TRIM(ORGANIZATION_NAME), '') IS NULL OR ORGANIZATION_NAME ILIKE ANY ('none', 'n/a', 'na') THEN 'blank/none'
         ELSE 'other nonprofit/civic' END kind,
    POSITION ILIKE ANY ('%trustee%', '%director%', '%board%', '%officer%', '%president%', '%treasurer%', '%secretary%', '%chair%', '%manager%', '%partner%', '%governor%') AS fiduciary_role
  FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_COURTLISTENER_DISCLOSURE_POSITIONS x LEFT JOIN fd ON fd.ID = x.FINANCIAL_DISCLOSURE_ID
)
SELECT kind, COUNT(*) positions, COUNT(DISTINCT PERSON_ID) judges, COUNT_IF(PERSON_ID IS NULL) no_judge, COUNT_IF(fiduciary_role) fiduciary_rows,
  MIN(IFF(yr BETWEEN 1990 AND 2030, yr, NULL)) y0, MAX(IFF(yr BETWEEN 1990 AND 2030, yr, NULL)) y1, COUNT_IF(REDACTED = 't') redacted,
  COUNT(DISTINCT ORGANIZATION_NAME) orgs, ANY_VALUE(LEFT(POSITION, 25) || ' / ' || LEFT(ORGANIZATION_NAME, 40)) ex
FROM p GROUP BY ROLLUP(kind) ORDER BY positions DESC;

-- [28] positions_org_as_party_same_judge
WITH fd AS (
  SELECT ID, PERSON_ID, TRY_TO_NUMBER(YEAR_COL::VARCHAR) yr FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_COURTLISTENER_FINANCIAL_DISCLOSURES
  WHERE PERSON_ID IS NOT NULL QUALIFY ROW_NUMBER() OVER (PARTITION BY ID ORDER BY DATE_MODIFIED DESC) = 1
),
p AS (
  SELECT DISTINCT fd.PERSON_ID, fd.yr, x.POSITION, x.ORGANIZATION_NAME,
    TRIM(REGEXP_REPLACE(REGEXP_REPLACE(' ' || REGEXP_REPLACE(UPPER(x.ORGANIZATION_NAME), '[^A-Z0-9 ]', ' ') || ' ', ' (THE|INC|LLP|LLC|CORP|CO|LTD|PC|P C) ', ' '), '\s+', ' ')) org
  FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_COURTLISTENER_DISCLOSURE_POSITIONS x JOIN fd ON fd.ID = x.FINANCIAL_DISCLOSURE_ID
  WHERE fd.yr BETWEEN 2000 AND 2023
    AND x.POSITION ILIKE ANY ('%trustee%', '%director%', '%board%', '%officer%', '%president%', '%treasurer%', '%secretary%', '%chair%', '%manager%', '%partner%', '%governor%')
    AND NOT x.ORGANIZATION_NAME ILIKE ANY ('%trust #%', '%trust no%', 'trust%', '%family trust%', '%revocable%', '%irrevocable%', '%estate of%', '%living trust%',
      '%bar %', '%bar', '%inn of court%', '%judges assoc%', '%judicial%', '%federal judges%', '%law institute%')
),
pk AS (SELECT * FROM p WHERE ARRAY_SIZE(SPLIT(org, ' ')) >= 2 AND LENGTH(org) >= 10 AND org NOT IN ('UNITED STATES', 'STATE OF', 'UNITED STATES OF AMERICA')),
judges AS (SELECT DISTINCT PERSON_ID FROM pk),
dk AS (
  SELECT k.ID docket_id, k.ASSIGNED_TO_ID, TRY_TO_NUMBER(LEFT(k.DATE_FILED::VARCHAR, 4)) fy, k.CASE_NAME, k.COURT_ID, k.NATURE_OF_SUIT, k.DATE_TERMINATED,
    ' ' || TRIM(REGEXP_REPLACE(REGEXP_REPLACE(UPPER(k.CASE_NAME), '[^A-Z0-9 ]', ' '), '\s+', ' ')) || ' ' cn
  FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_COURTLISTENER_DOCKETS k JOIN judges j ON j.PERSON_ID = k.ASSIGNED_TO_ID
  WHERE k.DATE_FILED >= '1999-01-01'
),
hits AS (
  SELECT pk.PERSON_ID, pk.ORGANIZATION_NAME, pk.POSITION, pk.yr, dk.docket_id, dk.fy, dk.CASE_NAME, dk.COURT_ID, dk.NATURE_OF_SUIT
  FROM pk JOIN dk ON dk.ASSIGNED_TO_ID = pk.PERSON_ID AND dk.fy BETWEEN pk.yr - 1 AND pk.yr + 1 AND POSITION(' ' || pk.org || ' ' IN dk.cn) > 0
)
SELECT j.NAME_FIRST || ' ' || j.NAME_LAST judge, LEFT(h.ORGANIZATION_NAME, 40) org, LEFT(ANY_VALUE(h.POSITION), 25) pos, MIN(h.yr) pos_yr0, MAX(h.yr) pos_yr1,
  COUNT(DISTINCT h.docket_id) dockets, MIN(h.fy) fy0, MAX(h.fy) fy1, LISTAGG(DISTINCT h.COURT_ID, ',') courts, LEFT(ANY_VALUE(h.CASE_NAME), 75) case_ex, LEFT(ANY_VALUE(h.NATURE_OF_SUIT), 28) nos,
  (SELECT COUNT(*) FROM pk) pos_pairs_tested, (SELECT COUNT(DISTINCT PERSON_ID) FROM pk) judges_tested, (SELECT COUNT(*) FROM dk) dockets_scanned
FROM hits h LEFT JOIN LIBRARY_MARTS.JUSTICE.JUSTICE__FED_COURTLISTENER_JUDGES j ON j.ID = h.PERSON_ID
GROUP BY 1, 2 ORDER BY dockets DESC;

-- [29] positions_org_as_party_loose_key
WITH fd AS (
  SELECT ID, PERSON_ID, TRY_TO_NUMBER(YEAR_COL::VARCHAR) yr FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_COURTLISTENER_FINANCIAL_DISCLOSURES
  WHERE PERSON_ID IS NOT NULL QUALIFY ROW_NUMBER() OVER (PARTITION BY ID ORDER BY DATE_MODIFIED DESC) = 1
),
p0 AS (
  SELECT DISTINCT fd.PERSON_ID, fd.yr, x.POSITION, x.ORGANIZATION_NAME, TRIM(s.VALUE) piece
  FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_COURTLISTENER_DISCLOSURE_POSITIONS x JOIN fd ON fd.ID = x.FINANCIAL_DISCLOSURE_ID,
    LATERAL SPLIT_TO_TABLE(REGEXP_REPLACE(x.ORGANIZATION_NAME, '[;,()/]', '|'), '|') s
  WHERE fd.yr BETWEEN 2000 AND 2023
    AND x.POSITION ILIKE ANY ('%trustee%', '%director%', '%board of%', '%officer%', '%governor%', '%treasurer%', '%regent%', 'board member%', 'member, board%')
    AND NOT x.POSITION ILIKE ANY ('%advisory%', '%honorary%', '%emeritus%')
    AND NOT x.ORGANIZATION_NAME ILIKE ANY ('%trust #%', '%trust no%', 'trust%', '%family trust%', '%revocable%', '%irrevocable%', '%estate of%', '%living trust%',
      '%bar %', '%bar', '%inn of court%', '%judges assoc%', '%judicial%', '%federal judges%', '%law institute%')
),
p AS (
  SELECT *, TRIM(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(' ' || REGEXP_REPLACE(UPPER(piece), '[^A-Z0-9 ]', ' ') || ' ',
      '^ (BOARD OF (TRUSTEES|DIRECTORS|VISITORS|GOVERNORS|REGENTS)( OF)?|TRUSTEES OF) ', ' '), ' (THE|INC|LLP|LLC|CORP|CO|LTD|PC|P C) ', ' '), '\s+', ' ')) org
  FROM p0
),
pk AS (SELECT * FROM p WHERE ARRAY_SIZE(SPLIT(org, ' ')) >= 2 AND LENGTH(org) >= 10
  AND org NOT IN ('UNITED STATES', 'UNITED STATES OF AMERICA', 'UNITED WAY', 'BOY SCOUTS OF AMERICA', 'BOARD OF TRUSTEES', 'BOARD OF DIRECTORS', 'NEW YORK', 'NEW JERSEY', 'SOUTH CAROLINA', 'NORTH CAROLINA')
  AND NOT org ILIKE ANY ('STATE OF %', 'CITY OF %', 'COUNTY OF %', 'COMMONWEALTH OF %')),
judges AS (SELECT DISTINCT PERSON_ID FROM pk),
dk AS (
  SELECT k.ID docket_id, k.ASSIGNED_TO_ID, TRY_TO_NUMBER(LEFT(k.DATE_FILED::VARCHAR, 4)) fy, k.CASE_NAME, k.COURT_ID, k.NATURE_OF_SUIT,
    ' ' || TRIM(REGEXP_REPLACE(REGEXP_REPLACE(UPPER(k.CASE_NAME), '[^A-Z0-9 ]', ' '), '\s+', ' ')) || ' ' cn
  FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_COURTLISTENER_DOCKETS k JOIN judges j ON j.PERSON_ID = k.ASSIGNED_TO_ID
  WHERE k.DATE_FILED >= '1999-01-01'
),
hits AS (
  SELECT pk.PERSON_ID, pk.ORGANIZATION_NAME, pk.org, pk.POSITION, pk.yr, dk.docket_id, dk.fy, dk.CASE_NAME, dk.COURT_ID, dk.NATURE_OF_SUIT
  FROM pk JOIN dk ON dk.ASSIGNED_TO_ID = pk.PERSON_ID AND dk.fy BETWEEN pk.yr - 1 AND pk.yr + 1 AND POSITION(' ' || pk.org || ' ' IN dk.cn) > 0
)
SELECT j.NAME_FIRST || ' ' || j.NAME_LAST judge, LEFT(h.org, 34) org_key, LEFT(ANY_VALUE(h.ORGANIZATION_NAME), 40) org_raw, LEFT(ANY_VALUE(h.POSITION), 22) pos, MIN(h.yr) y0, MAX(h.yr) y1,
  COUNT(DISTINCT h.docket_id) dockets, MIN(h.fy) fy0, MAX(h.fy) fy1, LISTAGG(DISTINCT h.COURT_ID, ',') courts, LEFT(ANY_VALUE(h.CASE_NAME), 70) case_ex, LEFT(ANY_VALUE(h.NATURE_OF_SUIT), 26) nos,
  (SELECT COUNT(*) FROM pk) pos_pairs_tested, (SELECT COUNT(DISTINCT PERSON_ID) FROM pk) judges_tested, (SELECT COUNT(*) FROM dk) dockets_scanned
FROM hits h LEFT JOIN LIBRARY_MARTS.JUSTICE.JUSTICE__FED_COURTLISTENER_JUDGES j ON j.ID = h.PERSON_ID
GROUP BY 1, 2 ORDER BY dockets DESC;

-- [30] dbl_burden_vs_samhsa_grant_dollars
WITH s AS (
  SELECT
    CASE WHEN LENGTH(REGEXP_REPLACE(PRIME_AWARD_TRANSACTION_PLACE_OF_PERFORMANCE_COUNTY_FIPS_CODE, '[^0-9]', '')) = 5 THEN REGEXP_REPLACE(PRIME_AWARD_TRANSACTION_PLACE_OF_PERFORMANCE_COUNTY_FIPS_CODE, '[^0-9]', '')
         WHEN NULLIF(PRIME_AWARD_TRANSACTION_PLACE_OF_PERFORMANCE_COUNTY_FIPS_CODE, '') IS NOT NULL THEN LPAD(REGEXP_REPLACE(PRIME_AWARD_TRANSACTION_PLACE_OF_PERFORMANCE_STATE_FIPS_CODE, '[^0-9]', ''), 2, '0') || LPAD(REGEXP_REPLACE(PRIME_AWARD_TRANSACTION_PLACE_OF_PERFORMANCE_COUNTY_FIPS_CODE, '[^0-9]', ''), 3, '0') END pop_fips,
    CASE WHEN LENGTH(REGEXP_REPLACE(PRIME_AWARD_TRANSACTION_RECIPIENT_COUNTY_FIPS_CODE, '[^0-9]', '')) = 5 THEN REGEXP_REPLACE(PRIME_AWARD_TRANSACTION_RECIPIENT_COUNTY_FIPS_CODE, '[^0-9]', '')
         WHEN NULLIF(PRIME_AWARD_TRANSACTION_RECIPIENT_COUNTY_FIPS_CODE, '') IS NOT NULL THEN LPAD(REGEXP_REPLACE(PRIME_AWARD_TRANSACTION_RECIPIENT_STATE_FIPS_CODE, '[^0-9]', ''), 2, '0') || LPAD(REGEXP_REPLACE(PRIME_AWARD_TRANSACTION_RECIPIENT_COUNTY_FIPS_CODE, '[^0-9]', ''), 3, '0') END rcp_fips,
    FEDERAL_ACTION_OBLIGATION usd
  FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_USASPENDING_ASSISTANCE_FULL
  WHERE AWARDING_SUB_AGENCY_NAME ILIKE '%Substance Abuse%' AND ACTION_DATE_FISCAL_YEAR BETWEEN 2019 AND 2025
),
tot AS (SELECT SUM(usd) all_usd, SUM(IFF(pop_fips IS NOT NULL, usd, 0)) pop_fips_usd FROM s),
bycounty AS (SELECT pop_fips fips, SUM(usd) usd FROM s WHERE pop_fips IS NOT NULL GROUP BY 1),
c AS (
  SELECT d.*, COALESCE(b.usd, 0) samhsa_usd, b.fips IS NOT NULL got_any,
    CASE WHEN DOUBLE_BURDEN THEN '1 double burden' WHEN IS_OVERDOSE_TOP_DECILE THEN '2 overdose top only' WHEN IS_JAIL_TOP_DECILE THEN '3 jail top only' ELSE '4 rest' END grp
  FROM LIBRARY_MARTS.JUSTICE.JUSTICE__COUNTY_DOUBLE_BURDEN d LEFT JOIN bycounty b ON b.fips = LPAD(d.FIPS, 5, '0')
)
SELECT grp, COUNT(*) counties, COUNT_IF(got_any) counties_with_samhsa_pop, ROUND(SUM(samhsa_usd) / 1e6, 1) samhsa_musd,
  ROUND(SUM(samhsa_usd) / NULLIF(SUM(JAIL_POPULATION / NULLIF(JAIL_RATE, 0) * 100000), 0), 2) usd_per_base_person,
  ROUND(MEDIAN(samhsa_usd / NULLIF(JAIL_POPULATION / NULLIF(JAIL_RATE, 0) * 100000, 0)), 2) median_county_usd_per_person,
  ROUND(ANY_VALUE(t.all_usd) / 1e6) samhsa_all_musd_fy19_25, ROUND(ANY_VALUE(t.pop_fips_usd) / 1e6) with_pop_county_musd,
  ROUND((SELECT SUM(usd) FROM bycounty WHERE fips IN (SELECT LPAD(FIPS, 5, '0') FROM LIBRARY_MARTS.JUSTICE.JUSTICE__COUNTY_DOUBLE_BURDEN)) / 1e6) landed_on_table_musd
FROM c, tot t GROUP BY 1 ORDER BY 1;

-- [31] dbl_burden_size_matched_samhsa_otp
WITH s AS (
  SELECT CASE WHEN LENGTH(REGEXP_REPLACE(PRIME_AWARD_TRANSACTION_PLACE_OF_PERFORMANCE_COUNTY_FIPS_CODE, '[^0-9]', '')) = 5 THEN REGEXP_REPLACE(PRIME_AWARD_TRANSACTION_PLACE_OF_PERFORMANCE_COUNTY_FIPS_CODE, '[^0-9]', '')
         WHEN NULLIF(PRIME_AWARD_TRANSACTION_PLACE_OF_PERFORMANCE_COUNTY_FIPS_CODE, '') IS NOT NULL THEN LPAD(REGEXP_REPLACE(PRIME_AWARD_TRANSACTION_PLACE_OF_PERFORMANCE_STATE_FIPS_CODE, '[^0-9]', ''), 2, '0') || LPAD(REGEXP_REPLACE(PRIME_AWARD_TRANSACTION_PLACE_OF_PERFORMANCE_COUNTY_FIPS_CODE, '[^0-9]', ''), 3, '0') END fips,
    FEDERAL_ACTION_OBLIGATION usd
  FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_USASPENDING_ASSISTANCE_FULL
  WHERE AWARDING_SUB_AGENCY_NAME ILIKE '%Substance Abuse%' AND ACTION_DATE_FISCAL_YEAR BETWEEN 2019 AND 2025
),
b AS (SELECT fips, SUM(usd) usd FROM s WHERE fips IS NOT NULL GROUP BY 1),
otp AS (SELECT DISTINCT LEFT(REGEXP_REPLACE(ZIP, '[^0-9]', ''), 5) zip5 FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_OPIOID_TREATMENT_PROGRAM_PROVIDERS),
otp_c AS (SELECT DISTINCT LPAD(x.COUNTY_FIPS, 5, '0') fips FROM otp JOIN LIBRARY_MARTS.CORE.XWALK_ZCTA_COUNTY x ON LPAD(x.ZCTA5, 5, '0') = otp.zip5),
c AS (
  SELECT d.*, JAIL_POPULATION / NULLIF(JAIL_RATE, 0) * 100000 base_pop, COALESCE(b.usd, 0) usd, o.fips IS NOT NULL has_otp,
    CASE WHEN DOUBLE_BURDEN THEN '1 double burden' WHEN IS_OVERDOSE_TOP_DECILE THEN '2 overdose top only' WHEN IS_JAIL_TOP_DECILE THEN '3 jail top only' ELSE '4 rest' END grp
  FROM LIBRARY_MARTS.JUSTICE.JUSTICE__COUNTY_DOUBLE_BURDEN d LEFT JOIN b ON b.fips = LPAD(d.FIPS, 5, '0') LEFT JOIN otp_c o ON o.fips = LPAD(d.FIPS, 5, '0')
)
SELECT grp, COUNT(*) small_counties, ROUND(AVG(base_pop)) avg_base_pop, COUNT_IF(usd > 0) with_samhsa, ROUND(COUNT_IF(usd > 0) / COUNT(*), 3) share_with_samhsa,
  ROUND(SUM(usd) / NULLIF(SUM(base_pop), 0), 2) usd_per_base_person, ROUND(COUNT_IF(has_otp) / COUNT(*), 3) share_with_otp
FROM c WHERE base_pop BETWEEN 800 AND 40000 GROUP BY 1 ORDER BY 1;

-- [32] csl_ofac_sam_exclusions_vs_contract_recipients
WITH ex AS (
  SELECT ENTITY_NAME, UEI ex_uei, COUNTRY, MIN(ACTIVATION_DATE) act,
    TRIM(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(' ' || REGEXP_REPLACE(UPPER(ENTITY_NAME), '[^A-Z0-9 ]', ' ') || ' ',
      ' (LLC|L L C|LTD|LIMITED|INC|INCORPORATED|CO|CORP|CORPORATION|COMPANY|JSC|OJSC|PJSC|OOO|ZAO|GMBH|SA|AG|PLC|LLP|THE|OF|BV|B V) ', ' '),
      ' (LLC|L L C|LTD|LIMITED|INC|INCORPORATED|CO|CORP|CORPORATION|COMPANY|JSC|OJSC|PJSC|OOO|ZAO|GMBH|SA|AG|PLC|LLP|THE|OF|BV|B V) ', ' '), '\s+', ' ')) k
  FROM LIBRARY_MARTS.PROCUREMENT.PROCUREMENT__FED_SAM_EXCLUSIONS
  WHERE EXCLUDING_AGENCY = 'OFAC' AND NULLIF(TRIM(ENTITY_NAME), '') IS NOT NULL
  GROUP BY 1, 2, 3
),
exk AS (SELECT * FROM ex WHERE ARRAY_SIZE(SPLIT(k, ' ')) >= 2 AND LENGTH(k) >= 8),
names AS (
  SELECT RECIPIENT_NAME, TRIM(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(' ' || REGEXP_REPLACE(UPPER(RECIPIENT_NAME), '[^A-Z0-9 ]', ' ') || ' ',
      ' (LLC|L L C|LTD|LIMITED|INC|INCORPORATED|CO|CORP|CORPORATION|COMPANY|JSC|OJSC|PJSC|OOO|ZAO|GMBH|SA|AG|PLC|LLP|THE|OF|BV|B V) ', ' '),
      ' (LLC|L L C|LTD|LIMITED|INC|INCORPORATED|CO|CORP|CORPORATION|COMPANY|JSC|OJSC|PJSC|OOO|ZAO|GMBH|SA|AG|PLC|LLP|THE|OF|BV|B V) ', ' '), '\s+', ' ')) k
  FROM (SELECT DISTINCT RECIPIENT_NAME FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_USASPENDING_CONTRACTS_FULL_R2)
),
m AS (SELECT DISTINCT e.ENTITY_NAME, e.ex_uei, e.COUNTRY, e.act, n.RECIPIENT_NAME FROM exk e JOIN names n ON n.k = e.k),
r AS (
  SELECT RECIPIENT_NAME, RECIPIENT_UEI, RECIPIENT_COUNTRY_NAME, ACTION_DATE, FEDERAL_ACTION_OBLIGATION usd FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_USASPENDING_CONTRACTS_FULL_R2
  WHERE RECIPIENT_NAME IN (SELECT RECIPIENT_NAME FROM m)
)
SELECT LEFT(m.ENTITY_NAME, 40) excluded_name, m.COUNTRY ex_ctry, m.act sam_activation, LEFT(m.RECIPIENT_NAME, 40) recipient, LISTAGG(DISTINCT LEFT(r.RECIPIENT_COUNTRY_NAME, 14), ',') r_ctry,
  BOOLOR_AGG(r.RECIPIENT_UEI = m.ex_uei) uei_equal, COUNT(*) actions, ROUND(SUM(r.usd)) usd_all, MIN(r.ACTION_DATE) d0, MAX(r.ACTION_DATE) d1,
  COUNT_IF(r.ACTION_DATE >= m.act) actions_after_exclusion, ROUND(SUM(IFF(r.ACTION_DATE >= m.act, r.usd, 0))) usd_after_exclusion,
  (SELECT COUNT(*) FROM exk) ofac_entities_keyed
FROM m JOIN r ON r.RECIPIENT_NAME = m.RECIPIENT_NAME
GROUP BY 1, 2, 3, 4 ORDER BY actions_after_exclusion DESC, usd_all DESC;

-- Notes on failed statements (counted against the budget of 35; 32 used):
-- [16] hit the 300s statement timeout (ANY_VALUE columns plus scalar subqueries over 93M rows); [17] is the lean rerun.
-- [20] failed to compile: ACTION_DATE in CONTRACTS_FULL_R2 is text, YEAR() rejects it; [21] is the rerun with LEFT(ACTION_DATE, 4).
-- [22] failed: IS_CURRENTLY_EXCLUDED is boolean and the UNION branch carried a text count; [23] is the rerun with a cast.
