-- which FEC / 527 / charity / FTC / court tables exist, with row counts
SELECT TABLE_SCHEMA, TABLE_NAME, ROW_COUNT FROM LIBRARY_MARTS.INFORMATION_SCHEMA.TABLES
WHERE TABLE_NAME ILIKE ANY ('%FEC%','%527%','%FTC%','%CHARIT%','%990%','%BMF%','%PUB78%','%TELEMARK%','%DNC%','%OPEX%','%DISB%','%SOLICIT%')
ORDER BY 1,2
