-- FEC committees tied to the 19: (a) look-alike name core, (b) treasurer surname from the 19's custodians/officers, (c) street address from the 19's 8872s. all three committee files unioned.
WITH c AS (
  SELECT CMTE_ID, CMTE_NM, TRES_NM, CMTE_ST1, CMTE_CITY, CMTE_ST, CMTE_ZIP, CMTE_TP, CMTE_DSGN, 'fin' src FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_FEC_COMMITTEES
  UNION ALL SELECT FEC_CMTE_ID, CMTE_NM, TRES_NM, CMTE_ST1, CMTE_CITY, CMTE_ST, CMTE_ZIP, CMTE_TP, CMTE_DSGN, 'bulk' FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_FEC_BULK_COMMITTEES
  UNION ALL SELECT CMTE_ID, CMTE_NM, TRES_NM, NULL, CMTE_CITY, CMTE_ST, CMTE_ZIP, CMTE_TP, CMTE_DSGN, 'pol'||CYCLE FROM LIBRARY_MARTS.POLITICS.POLITICS__FEC_COMMITTEE),
n AS (SELECT CMTE_ID, ANY_VALUE(CMTE_NM) nm, LISTAGG(DISTINCT UPPER(TRES_NM),' / ') tres, LISTAGG(DISTINCT UPPER(COALESCE(CMTE_ST1,''))||', '||UPPER(CMTE_CITY)||' '||CMTE_ST,' / ') addr,
   ANY_VALUE(CMTE_TP) tp, LISTAGG(DISTINCT src,',') srcs,
   ' '||REGEXP_REPLACE(UPPER(ANY_VALUE(CMTE_NM)),'[^A-Z0-9]+',' ')||' ' nn FROM c GROUP BY CMTE_ID),
cores AS (SELECT column1 core FROM VALUES ('AMERICAN POLICE OFFICERS ALLIANCE'),('FIREFIGHTERS AND EMS FUND'),('FIREFIGHTERS SUPPORT FUND'),('NATIONAL POLICE SUPPORT FUND'),('COMMITTEE FOR POLICE OFFICERS DEFENSE'),
  ('AMERICAN VETERANS HONOR FUND'),('AMERICAN BREAST CANCER COALITION'),('NATIONAL COMMITTEE FOR VOLUNTEER FIREFIGHTERS'),('NATIONAL COALITION FOR DISABLED VETERANS'),('VETERANS ACTION NETWORK'),
  ('VETERANS IN DEFENSE OF LIBERTY'),('NATIONAL CANCER ALLIANCE'),('POSC'),('AMERICAN COALITION FOR POLICE'),('UNITED FIREFIGHTERS SUPPORT'),('AMERICAN ALLIANCE FOR MILITARY VETERANS'),('AVSC'),('VF2024'),
  ('NATIONAL POLICE SHERIFFS COALITION'),('UNITED HEALTH PAC'),('AMERICAN ALLIANCE FOR PUBLIC SAFETY'),('CONSTITUTIONAL POLICING SUPPORT'),('POLICE OFFICERS DEFENSE ALLIANCE'),('REAL DEMOCRACY FUND'),('AMCC PAC'),('UCVF PAC'),('CANCER RECOVERY ACTION')),
sur AS (SELECT column1 s FROM VALUES ('SKYLES'),('STUEBS'),('STEUBS'),('QUAYE'),('PORTER, NILE'),('PORTER, JANE'),('LAMERS'),('EYLER'),('FORSYTHE'),('GREENLEE'),('GRAGERT'),('PULCIANI'),('PULSIANI'),('NIZICK'),
  ('CURRAN, DAN'),('MAGILL'),('GUTMANN'),('MAICHLE'),('FRANKOVIS'),('MAJCEN'),('FOTIS'),('SECHER'),('HOWELL, JAMES'),('PHILLIPS, MARK'),('DAVIS, BILL'),('DAVIS, WILLIAM'),('DAVIS, DAVID'),('JOHNS, KYLE'),('MEYER, RYAN'),('LEWIS, SIMON')),
adr AS (SELECT column1 a FROM VALUES ('2301 SUN VALLEY'),('200 S EXECUTIVE'),('14497 POTOMAC MILLS'),('9480 MAIN ST'),('5801 LEESBURG PIKE'),('1104 W'),('110 COLISEUM'),('1 EAST ERIE'),('1 E ERIE'),('2000 COLORADO BLVD'),
  ('1 WASHINGTON MALL'),('900 COMMONWEALTH'),('10521 JUDICIAL'),('4250 FAIRFAX'),('5680 KING CENTRE'),('1101 WILSON'),('1655 FORT MYER'),('2800 EISENHOWER'),('301 S MCDOWELL'),('4301 50TH'),('4210 ELECTRIC'),
  ('7345 W'),('3804 WILSON'),('7400 BEAUMONT'),('4650 S'),('177 HUNTINGTON'),('3540 TORINGDON'),('2010 CORPORATE RIDGE'),('2331 MILL'))
SELECT n.CMTE_ID, n.nm, n.tp, n.tres, n.addr, n.srcs,
  (SELECT LISTAGG(core,'|') FROM cores WHERE n.nn LIKE '% '||core||' %') name_hit,
  (SELECT LISTAGG(s,'|') FROM sur WHERE n.tres LIKE '%'||s||'%') tres_hit,
  (SELECT LISTAGG(a,'|') FROM adr WHERE n.addr LIKE '%'||a||'%') addr_hit
FROM n
WHERE EXISTS (SELECT 1 FROM cores WHERE n.nn LIKE '% '||core||' %')
   OR (EXISTS (SELECT 1 FROM sur WHERE n.tres LIKE '%'||s||'%') AND REGEXP_LIKE(n.nn,'.*(POLICE|SHERIFF|FIRE|VETERAN|CANCER|HEALTH|MILITARY|TROOPER|LAW ENFORCEMENT|FIRST RESPONDER|SAFETY|DISABLED|BREAST).*'))
   OR EXISTS (SELECT 1 FROM adr WHERE n.addr LIKE '%'||a||'%' AND REGEXP_LIKE(n.nn,'.*(POLICE|SHERIFF|FIRE|VETERAN|CANCER|HEALTH|MILITARY|TROOPER|LAW ENFORCEMENT|FIRST RESPONDER|SAFETY|DISABLED|BREAST).*'))
ORDER BY n.nm
