-- the vendors, groups and FEC twins in FTC cases, CFPB complaints, CourtListener dockets and FJC civil cases (name patterns, multi-word only)
WITH p AS (SELECT column1 pat FROM VALUES ('%BF TELECOM%'),('%BF-TELECOM%'),('%BFTELECOM%'),('%RESIDENTIAL PROGRAMS%'),('%CAMPAIGN CALLING%'),('%ONE VOICE SOLUTIONS%'),('%POLITICAL RESPONSE LLC%'),
  ('%OPTICAL MARKETING%'),('%PUBLIC SUPPORT SERVICES%'),('%GRASSROOTS FUND GROUP%'),('%NORTH AMERICAN FULFILLMENT%'),('%PROSPEAKING%'),('%CAPITAL VENDOR MANAGEMENT%'),('%ACTION COMMITTEE MARKETING%'),
  ('%UNIQ TECHNOLOGIES%'),('%VENDOR SYSTEMS LLC%'),('%SIMPLE DATA LLC%'),('%AMERICAN LIBERTY GROUP%'),('%ADVANCED CREATIVE MEDIA%'),('%EMERGENT MARKETING%'),
  ('%POLICE OFFICERS ALLIANCE%'),('%NATIONAL POLICE SUPPORT FUND%'),('%FIREFIGHTERS SUPPORT FUND%'),('%POLICE OFFICERS DEFENSE%'),('%VETERANS HONOR FUND%'),('%BREAST CANCER COALITION%'),
  ('%VOLUNTEER FIREFIGHTERS%'),('%DISABLED VETERANS PAC%'),('%NATIONAL CANCER ALLIANCE%'),('%LAW ENFORCEMENT FOR A SAFER AMERICA%'),('%HONORING AMERICAN LAW ENFORCEMENT%'),('%COALITION FOR AMERICAN VETERANS%'),
  ('%CRISIS RELIEF PAC%'),('%DISABLED CHILDREN PAC%'),('%POLICE COALITION OF AMERICA%'),('%DATWYLER%'),('%PLISHKA%'),('%AMERICAN WOUNDED VETERANS%'))
SELECT 'ftc' src, ACTION_NAME nm, DATE_FILED::string d, DOCUMENT_URL x FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_FTC_DATASETS WHERE UPPER(ACTION_NAME) LIKE ANY (SELECT pat FROM p)
UNION ALL SELECT 'cfpb', COMPANY, MIN(DATE_RECEIVED)::string, COUNT(*)::string FROM LIBRARY_MARTS.CONSUMER_PROTECTION.CONSUMER_PROTECTION__FED_CFPB_COMPLAINTS WHERE UPPER(COMPANY) LIKE ANY (SELECT pat FROM p) GROUP BY COMPANY
UNION ALL SELECT 'courtlistener', CASE_NAME, DATE_FILED::string, COURT_ID||' '||DOCKET_NUMBER||' nos='||COALESCE(NATURE_OF_SUIT,'') FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_COURTLISTENER_DOCKETS WHERE UPPER(CASE_NAME) LIKE ANY (SELECT pat FROM p)
UNION ALL SELECT 'fjc_civil', PLAINTIFF||' v. '||DEFENDANT, FILE_DATE::string, DISTRICT||' '||DOCKET||' nos='||NATURE_OF_SUIT||' disp='||COALESCE(DISPOSITION::string,'') FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_FJC_IDB_CIVIL
  WHERE UPPER(PLAINTIFF) LIKE ANY (SELECT pat FROM p) OR UPPER(DEFENDANT) LIKE ANY (SELECT pat FROM p)
ORDER BY 1,3
