-- tax-exempt orgs "in care of" the 19's custodians/officers or the FEC twins' treasurers (IRS master file IN_CARE_OF, distinctive names), plus Pub 78 deductibility for any hit
WITH nm AS (SELECT column1 pat FROM VALUES ('%PLISHKA%'),('%DATWYLER%'),('%RICHARD%LEAGUE%'),('%KEVITT%'),('%STEFANIDES%'),('%CAPPLEMAN%'),('%MCGRAIN%'),
  ('%PULCIANI%'),('%NIZICK%'),('%MATTHEW GREENLEE%'),('%GRAGERT%'),('%JULIE FORSYTHE%'),('%SKYLES%'),('%STUEBS%'),('%QUAYE%'),('%NILE%PORTER%'),('%LAMERS%'),('%BERT%EYLER%'),('%FOTIS%'),('%MAGILL%'),('%DAN CURRAN%'),('%JUDITH%SECHER%'),('%MAJCEN%'),('%MAICHLE%'),('%FRANKOVIS%')),
b AS (SELECT EIN, ORG_NAME, IN_CARE_OF, STREET, CITY, STATE, SUBSECTION_CODE, NTEE_CODE, RULING_DATE, REVENUE_AMT, ASSET_AMT, TAX_PERIOD_YYYYMM
  FROM LIBRARY_MARTS.CORPORATE_REGISTRY.CORPORATE_REGISTRY__FED_IRS_EO_BMF WHERE UPPER(IN_CARE_OF) LIKE ANY (SELECT pat FROM nm))
SELECT b.*, p.DEDUCTIBILITY_STATUS pub78 FROM b LEFT JOIN LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_IRS_PUB78_ELIGIBLE_DONEES p ON p.EIN = b.EIN
ORDER BY REVENUE_AMT DESC NULLS LAST
