-- S01 WPA slave narratives: pull all 100 rows (tiny table, profile locally)
SELECT * FROM LIBRARY_MARTS.HISTORY.HISTORY__FED_WPA_SLAVE_NARRATIVES;

-- S02 Densho DDR: pull all 25 rows
SELECT * FROM LIBRARY_MARTS.HISTORY.HISTORY__FED_DENSHO_DDR;

-- S03 DocSouth: pull all 144 rows
SELECT * FROM LIBRARY_MARTS.HISTORY.HISTORY__FED_DOCSOUTH;

-- S04 NARA AAD: pull all 554 rows
SELECT * FROM LIBRARY_MARTS.GOVERNMENT_RECORDS.GOVERNMENT_RECORDS__FED_NARA_AAD;

-- S05 USAspending TAS filter tree: pull all 92 rows
SELECT * FROM LIBRARY_MARTS.GOVERNMENT_RECORDS.GOVERNMENT_RECORDS__FED_USASPENDING_TAS_FILTER_TREE;
