-- S06 Sibling tables: is there a fuller copy of any of the five, in landing or marts? (row counts from the catalog)
SELECT 'RAW' db, TABLE_SCHEMA, TABLE_NAME, ROW_COUNT, LAST_ALTERED
FROM LIBRARY_RAW.INFORMATION_SCHEMA.TABLES
WHERE TABLE_NAME RLIKE '.*(WPA|SLAVE|DENSHO|DOCSOUTH|NARA|_AAD|_LOC_|LIBRARY_OF_CONGRESS|TAS_|FEDERAL_ACCOUNT|FILTER_TREE|BUDGETARY|TOPTIER).*'
UNION ALL
SELECT 'MARTS', TABLE_SCHEMA, TABLE_NAME, ROW_COUNT, LAST_ALTERED
FROM LIBRARY_MARTS.INFORMATION_SCHEMA.TABLES
WHERE TABLE_NAME RLIKE '.*(WPA|SLAVE|DENSHO|DOCSOUTH|NARA|_AAD|_LOC_|LIBRARY_OF_CONGRESS|TAS_|FEDERAL_ACCOUNT|FILTER_TREE|BUDGETARY|TOPTIER).*'
ORDER BY 1, 3;

-- S07 TAS join test: which mart columns could carry a 3- or 4-digit agency code (CGAC / FREC / toptier) to join NODE_ID
SELECT TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME, DATA_TYPE
FROM LIBRARY_MARTS.INFORMATION_SCHEMA.COLUMNS
WHERE COLUMN_NAME RLIKE '.*(TOPTIER|CGAC|FREC|AGENCY_IDENTIFIER|AGENCY_CODE|AGENCY_ID).*'
  AND TABLE_SCHEMA <> 'INFORMATION_SCHEMA'
ORDER BY 1, 2, 3;
