-- FJC appeals: eyeball 16 detention-habeas appeals docketed January 2026, spread across circuits
select CIRCUIT, DOCKET, REOPEN, DOCKET_DATE, APPEAL_TYPE, US_APPELLANT, US_APPELLEE, APPELLANT, APPELLEE,
  DISTRICT_COURT, DISTRICT_OFFICE, DISTRICT_DOCKET, DISTRICT_DOCKET_DATE, APPEAL_DATE, PRO_SE_FILED, FILING_FEE_STATUS,
  TAPE_YEAR, OUTCOME, DISPOSITION, JUDGMENT_DATE
from LIBRARY_MARTS.JUSTICE.JUSTICE__FED_FJC_IDB_APPELLATE
where NATURE_OF_SUIT::string='463' and try_to_date(DOCKET_DATE::string) between '2026-01-01' and '2026-01-31'
qualify row_number() over (partition by CIRCUIT order by DOCKET) <= 2
order by CIRCUIT, DOCKET
