{{ config(materialized='view', schema='TIMELINE', alias='ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_PROGRAMS') }}

-- GENERATED by scripts/census/gen_time_views.py -- do not hand-edit.
-- Regenerate after any change to reports/time_index/clock_index.csv.
--
-- Canonical clock for ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_PROGRAMS.
--   column : UPDATED_DATE   (DATE)
--   means  : reported -- try_to_date(UPDATED_DATE): when the ICIS-Air program record was last maintained in EPA's system. Record housekeeping - census max 2028-10-29 and 109 epoch-1970 
--   grain  : day
--
-- The original columns pass through untouched; the canonical four sit in front
-- of them. Rule 8 of the datetime standard: the raw column is never overwritten,
-- so a mis-parse is always recoverable.

select
    {{ ripple_event_ts(ripple_window('src."UPDATED_DATE"::timestamp_ntz')) }} as ripple_ts,
    {{ ripple_grain('day') }} as ripple_grain,
    {{ ripple_clock('reported') }} as ripple_clock,
    'ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_PROGRAMS'::varchar as ripple_source,
    src.*
from {{ ref('environment__fed_epa_icis_air_icis_air_programs') }} as src
