{{ config(materialized='view', schema='TIMELINE', alias='ENVIRONMENT__FED_USCG_NRC_INCIDENT_REPORTS') }}

-- GENERATED by scripts/census/gen_time_views.py -- do not hand-edit.
-- Regenerate after any change to reports/time_index/clock_index.csv.
--
-- Canonical clock for ENVIRONMENT.ENVIRONMENT__FED_USCG_NRC_INCIDENT_REPORTS.
--   column : DATE_TIME_RECEIVED   (TIMESTAMP_NTZ)
--   means  : reported -- try_to_timestamp(trim(DATE_TIME_RECEIVED)): the moment the National Response Center took the call. It is a report-receipt clock, not the spill itself, though NR
--   grain  : day
--
-- The original columns pass through untouched; the canonical four sit in front
-- of them. Rule 8 of the datetime standard: the raw column is never overwritten,
-- so a mis-parse is always recoverable.

select
    {{ ripple_event_ts(ripple_window('src."DATE_TIME_RECEIVED"::timestamp_ntz')) }} as ripple_ts,
    {{ ripple_grain('day') }} as ripple_grain,
    {{ ripple_clock('reported') }} as ripple_clock,
    'ENVIRONMENT.ENVIRONMENT__FED_USCG_NRC_INCIDENT_REPORTS'::varchar as ripple_source,
    src.*
from {{ ref('environment__fed_uscg_nrc_incident_reports') }} as src
