{{ config(materialized='view', schema='TIMELINE', alias='ENVIRONMENT__FED_USGS_ORPHANED_OIL_GAS_WELLS') }}

-- GENERATED by scripts/census/gen_time_views.py -- do not hand-edit.
-- Regenerate after any change to reports/time_index/clock_index.csv.
--
-- Canonical clock for ENVIRONMENT.ENVIRONMENT__FED_USGS_ORPHANED_OIL_GAS_WELLS.
--   column : DATA_FILE_DATE   (DATE)
--   means  : reported -- try_to_date(trim(DATA_FILE_DATE),'MM/DD/YYYY'): the date of the state agency's data file the well record came from. It is file vintage - the table carries no dr
--   grain  : day
--
-- reported cannot be in the future -- if this row's value is, ripple_clock
-- reads 'planned' instead, not 'reported'. See ripple_row_clock in
-- macros/ripple_time.sql.
--
-- The original columns pass through untouched; the canonical four sit in front
-- of them. Rule 8 of the datetime standard: the raw column is never overwritten,
-- so a mis-parse is always recoverable.

select
    {{ ripple_window('src."DATA_FILE_DATE"::timestamp_ntz') }} as ripple_ts,
    {{ ripple_grain('day') }} as ripple_grain,
    {{ ripple_row_clock(ripple_window('src."DATA_FILE_DATE"::timestamp_ntz'), 'reported') }} as ripple_clock,
    'ENVIRONMENT.ENVIRONMENT__FED_USGS_ORPHANED_OIL_GAS_WELLS'::varchar as ripple_source,
    src.*
from {{ ref('environment__fed_usgs_orphaned_oil_gas_wells') }} as src
