SELECT TABLE_SCHEMA, TABLE_NAME, LISTAGG(COLUMN_NAME, ',') WITHIN GROUP (ORDER BY ORDINAL_POSITION) cols
FROM LIBRARY_MARTS.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME IN ('POLITICS__IRS527_8872_REPORTS','FINANCE__FED_IRS527_SCHEDULE_A_CONTRIBUTIONS','FINANCE__FED_FEC_INDIV_CONTRIBUTIONS','POLITICS__FED_FEC_PAC_SUMMARY')
GROUP BY 1,2
