SELECT TABLE_NAME, LISTAGG(COLUMN_NAME, ',') WITHIN GROUP (ORDER BY ORDINAL_POSITION) cols
FROM LIBRARY_MARTS.INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='FINANCE' AND TABLE_NAME IN ('FINANCE__FED_FEC_INDEPENDENT_EXPENDITURES','FINANCE__FED_FEC_COMMITTEE_TO_CANDIDATE') GROUP BY 1
