-- the FEC twins' independent expenditures (Schedule E, has payee): who got the "politics" money? one row per SPE_ID+TRAN_ID, latest file
WITH ie AS (SELECT SPE_ID, SPE_NAM, UPPER(TRIM(PAY)) pay, UPPER(TRIM(PUR)) pur, EXP_AMO, EXP_DATE, CAND_NAME, SUP_OPP, TRAN_ID, FILE_NUM, IS_SUPERSEDED,
   ROW_NUMBER() OVER (PARTITION BY SPE_ID, TRAN_ID ORDER BY FILE_NUM DESC) rn
  FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_FEC_INDEPENDENT_EXPENDITURES
  WHERE SPE_ID IN ('C00570093','C00715433','C00709113','C00710160','C00650168','C00784496','C00755694','C00681825','C00570416','C00758938','C00712885','C00710178','C00699801')),
d AS (SELECT * FROM ie WHERE rn=1 AND COALESCE(IS_SUPERSEDED::string,'false') NOT IN ('true','TRUE','1','Y'))
SELECT 'by_payee' k, LEFT(pay,40) pay, LEFT(ANY_VALUE(pur),50) pur, COUNT(DISTINCT SPE_ID) pacs, COUNT(*) rows_, ROUND(SUM(EXP_AMO)/1e6,3) m, MIN(EXP_DATE) d0, MAX(EXP_DATE) d1
FROM d GROUP BY pay
UNION ALL SELECT 'total', NULL, NULL, COUNT(DISTINCT SPE_ID), COUNT(*), ROUND(SUM(EXP_AMO)/1e6,3), MIN(EXP_DATE), MAX(EXP_DATE) FROM d
UNION ALL SELECT 'raw_all_rows', NULL, NULL, COUNT(DISTINCT SPE_ID), COUNT(*), ROUND(SUM(EXP_AMO)/1e6,3), MIN(EXP_DATE), MAX(EXP_DATE) FROM ie
ORDER BY k DESC, m DESC LIMIT 40
