-- which twin paid which IE vendor; flag payees that are also one of the 527-side vendors (same normalization as builder's Q5)
WITH ie AS (SELECT SPE_ID, SPE_NAM, UPPER(TRIM(PAY)) pay, UPPER(TRIM(PUR)) pur, EXP_AMO, TRAN_ID, FILE_NUM, IS_SUPERSEDED, CAN_OFFICE, CAND_NAME,
   ROW_NUMBER() OVER (PARTITION BY SPE_ID, TRAN_ID ORDER BY FILE_NUM DESC) rn
  FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_FEC_INDEPENDENT_EXPENDITURES
  WHERE SPE_ID IN ('C00570093','C00715433','C00709113','C00710160','C00650168','C00784496','C00755694','C00681825','C00570416','C00758938','C00712885','C00710178','C00699801')),
d AS (SELECT *, REGEXP_REPLACE(REGEXP_REPLACE(pay,'[^A-Z0-9]',''),'(LLC|INC|CORP|CORPORATION|CO|LTD|LP)$','') v FROM ie WHERE rn=1 AND COALESCE(IS_SUPERSEDED::string,'false') NOT IN ('true','TRUE','1','Y'))
SELECT SPE_ID, ANY_VALUE(SPE_NAM) pac, LEFT(pay,35) pay,
  IFF(v IN ('RESIDENTIALPROGRAMS','BFTELECOM','CAMPAIGNCALLING','AMERICANLIBERTYGROUP','SIMPLEDATA','UNITEDSUPPORT','ONEVOICESOLUTIONS','NORTHAMERICANFULFILLMENT','NORTHAMERICANFULFILMENT','POLITICALRESPONSE','GSI','PROSPEAKING','OPTICALMARKETING','PUBLICSUPPORTSERVICES','GRASSROOTSFUNDGROUP','POLITICALFUNDRAISINGGROUP','CAPITALVENDORMANAGEMENT','POLITICALMARKETINGSERVICES','EMERGENTMARKETING','ACTIONCOMMITTEEMARKETING','UNIQTECHNOLOGIES','VENDORSYSTEMS','THEFUNDRAISINGGROUP','ADVANCEDCREATIVEMEDIA','GCI','CAMPAIGNMARKETING','AMERICANMARKETINGSERVICES'),'Y','') in527vendors,
  ROUND(SUM(EXP_AMO)/1e6,3) m, COUNT(*) rows_, COUNT(DISTINCT CAND_NAME) cands, LEFT(ANY_VALUE(CAND_NAME),25) a_cand
FROM d WHERE pay IN ('CLOUD DATA SERVICES','WIRED4DATA','STANDARD DATA SERVICES LLC','LAV SERVICES LLC','RIDGE INNOVATIVE','EYP CONSULTANTS LLC','THE BOWLINE GROUP LLC','LIVE TRANSFERS AND DONOR CREATION LLC')
   OR v IN ('RESIDENTIALPROGRAMS','BFTELECOM','CAMPAIGNCALLING','SIMPLEDATA','UNITEDSUPPORT','ONEVOICESOLUTIONS','NORTHAMERICANFULFILLMENT','NORTHAMERICANFULFILMENT','POLITICALRESPONSE','GSI','PROSPEAKING','OPTICALMARKETING','PUBLICSUPPORTSERVICES','GRASSROOTSFUNDGROUP','POLITICALFUNDRAISINGGROUP','CAPITALVENDORMANAGEMENT','POLITICALMARKETINGSERVICES','EMERGENTMARKETING','ACTIONCOMMITTEEMARKETING','UNIQTECHNOLOGIES','VENDORSYSTEMS','THEFUNDRAISINGGROUP','ADVANCEDCREATIVEMEDIA','GCI','CAMPAIGNMARKETING','AMERICANMARKETINGSERVICES')
GROUP BY SPE_ID, pay, v ORDER BY SPE_ID, m DESC
