{{ config(tags=['spine_generated']) }}

-- GRAIN: one row per place (GEOM is unique)
-- SPINE_ENTITY: place  (natural_key: SHAPE_AREA)
-- Generated by scripts/generate_staging_models.py from SOURCE_REGISTRY -- deterministic,
-- no LLM.
-- CASTS: 3 of 23 columns, from landing_column_profile_2026-09-19.tsv. A column is cast only
-- when every filled value in the sample parsed. try_ casts: a value that does not
-- parse reads NULL. The natural key and join-key columns stay TEXT.
--   objectid: ID: whole numbers, over 90% distinct -- stays TEXT, '.0' tail removed
--   watershed_id: ID: whole numbers, over 90% distinct -- stays TEXT, '.0' tail removed
--   priority: integer
-- spine_entity 'place' has no connect/ resolver yet (see connect/spine_entity.py) -- no SPINE_ENTITY_ID emitted.
-- landing table's ingestion timestamp is named INGESTED_AT (no leading underscore) rather than the usual _INGESTED_AT -- confirmed via INFORMATION_SCHEMA, not assumed.
-- DEDUPE: registry natural_key (SHAPE_AREA) is NOT unique within a load as landed at generation time -- it would collapse 2 of 356 rows. Deduping on the WHOLE ROW instead (exact copies only). A record that changes between loads shows once per version. Find the real key, fix SOURCE_REGISTRY, regenerate.

with source as (

    select * from {{ source('ripple_raw', 'PORTAL_CKA_VIRGINIA_OPEN_DA_F4FC6168EA') }}
    qualify row_number() over (partition by "OBJECTID", "IP_NAME", "INSERTED_BY", "INSERTED_DATE", "CHANGED_BY", "CHANGED_DATE", "GLOBALID", "WATERSHED_ID", "WATERSHED_NAME", "REPORT_NUMBER", "REPORT_NAME", "EPA_APPROVED_DATE", "COMPLETE_REPORT_LINK", "REGION", "REPORT_STATUS", "WATERSHED_STATUS", "POLLUTANTS", "SUCC_STORY_TYPES", "SHAPE_LENGTH", "SHAPE_AREA", "PRIORITY", "ELIGIBLE_319H", "DATA_DISCLAIMER" order by INGESTED_AT desc) = 1

),

renamed as (

    select
        {{ stg_id_text('"OBJECTID"') }} as objectid,
        {{ null_junk('"IP_NAME"') }} as ip_name,
        {{ null_junk('"INSERTED_BY"') }} as inserted_by,
        {{ null_junk('"INSERTED_DATE"') }} as inserted_date,
        {{ null_junk('"CHANGED_BY"') }} as changed_by,
        {{ null_junk('"CHANGED_DATE"') }} as changed_date,
        {{ null_junk('"GLOBALID"') }} as globalid,
        {{ stg_id_text('"WATERSHED_ID"') }} as watershed_id,
        {{ null_junk('"WATERSHED_NAME"') }} as watershed_name,
        {{ null_junk('"REPORT_NUMBER"') }} as report_number,
        {{ null_junk('"REPORT_NAME"') }} as report_name,
        {{ null_junk('"EPA_APPROVED_DATE"') }} as epa_approved_date,
        {{ null_junk('"COMPLETE_REPORT_LINK"') }} as complete_report_link,
        {{ null_junk('"REGION"') }} as region,
        {{ null_junk('"REPORT_STATUS"') }} as report_status,
        {{ null_junk('"WATERSHED_STATUS"') }} as watershed_status,
        {{ null_junk('"POLLUTANTS"') }} as pollutants,
        {{ null_junk('"SUCC_STORY_TYPES"') }} as succ_story_types,
        {{ null_junk('"SHAPE_LENGTH"') }} as shape_length,
        {{ null_junk('"SHAPE_AREA"') }} as shape_area,
        {{ stg_int('"PRIORITY"') }} as priority,
        {{ null_junk('"ELIGIBLE_319H"') }} as eligible_319h,
        {{ null_junk('"DATA_DISCLAIMER"') }} as data_disclaimer,
        INGESTED_AT as _loaded_at,
        'https://data.virginia.gov/dataset/implementation-watersheds-ip' as _source_url

    from source

)

select * from renamed
