-- OWNER join check: owner rows -> 2024 generator table (MW, fuel) -> eGRID 2022 plant (CO2). Land rate and owned MW by fuel.
WITH o AS (SELECT * FROM LIBRARY_MARTS.ENERGY.ENERGY__FED_EIA860_4_OWNER),
g AS (SELECT PLANT_CODE, GENERATOR_ID, NAMEPLATE_CAPACITY_MW mw, ENERGY_SOURCE_1 f FROM LIBRARY_MARTS.ENERGY.ENERGY__FED_EIA860_3_1_GENERATOR),
e AS (SELECT TRY_TO_NUMBER(TO_VARCHAR(DOE_EIA_ORIS_PLANT_OR_FACILITY_CODE)) pc, COUNT(*) n, MAX(PLANT_ANNUAL_CO2_EMISSIONS_TONS) co2
      FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_EGRID_PLANT_2022 GROUP BY 1)
SELECT o.STATUS IN ('OP','SB','OA','OS') operable,
       CASE WHEN g.f IN ('BIT','SUB','LIG','ANT','RC','WC','SGC') THEN 'coal' WHEN g.f='NG' THEN 'gas' WHEN g.f='NUC' THEN 'nuclear'
            WHEN g.f='SUN' THEN 'solar' WHEN g.f='WND' THEN 'wind' WHEN g.f='WAT' THEN 'hydro' WHEN g.f IS NULL THEN 'no_gen_match' ELSE 'other:'||g.f END fuel,
       COUNT(*) owner_rows, COUNT(DISTINCT o.PLANT_CODE) plants, COUNT(DISTINCT o.OWNERSHIP_ID) owners,
       ROUND(SUM(o.PERCENT_OWNED*g.mw)) owned_mw, ROUND(SUM(IFF(o.OWNERSHIP_ID<>o.UTILITY_ID, o.PERCENT_OWNED*g.mw, 0))) owned_mw_nonoperator,
       SUM(IFF(e.pc IS NULL,1,0)) rows_no_egrid, MAX(e.n) max_egrid_dupes
FROM o LEFT JOIN g ON g.PLANT_CODE=o.PLANT_CODE AND g.GENERATOR_ID=o.GENERATOR_ID
LEFT JOIN e ON e.pc=o.PLANT_CODE
GROUP BY 1,2 ORDER BY 1 DESC, owned_mw DESC NULLS LAST
