-- CS join check: is FACILITY_NUMBER an EIA plant code? Pull each CS facility's 2024 generator-table capacity, tech and first/last online date
WITH cs AS (SELECT DISTINCT FACILITY_NUMBER FROM LIBRARY_MARTS.ENERGY.ENERGY__FED_EIA861_SALES_ULT_CUST_CS)
SELECT cs.FACILITY_NUMBER, COUNT(g.GENERATOR_ID) gens, ROUND(SUM(g.NAMEPLATE_CAPACITY_MW),3) mw,
       MIN(g.OPERATING_YEAR*100+g.OPERATING_MONTH) first_online, MAX(g.OPERATING_YEAR*100+g.OPERATING_MONTH) last_online,
       LISTAGG(DISTINCT g.TECHNOLOGY, '; ') tech, MAX(g.PLANT_NAME) plant_name, MAX(g.STATE) plant_state, MAX(g.UTILITY_NAME) operator
FROM cs LEFT JOIN LIBRARY_MARTS.ENERGY.ENERGY__FED_EIA860_3_1_GENERATOR g ON g.PLANT_CODE = cs.FACILITY_NUMBER
GROUP BY 1
