-- time check: does any other year of EIA-861 / EIA-860 exist in the warehouse (landing or marts)?
SELECT 'LANDING' db, TABLE_SCHEMA, TABLE_NAME, ROW_COUNT FROM LIBRARY_RAW.INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME ILIKE '%EIA%86%' OR TABLE_NAME ILIKE '%EIA_861%' OR TABLE_NAME ILIKE '%EIA861%'
UNION ALL
SELECT 'MARTS', TABLE_SCHEMA, TABLE_NAME, ROW_COUNT FROM LIBRARY_MARTS.INFORMATION_SCHEMA.TABLES WHERE (TABLE_NAME ILIKE '%EIA%86%') AND TABLE_NAME NOT ILIKE 'ENERGY__FED_EIA86%'
