-- Holly Springs corroboration: meters and AMI-metered energy vs customers and billed MWh, for every MS/TN/AL/KY/GA municipal utility
SELECT UTILITY_NUMBER, UTILITY_NAME, STATE, OWNERSHIP, SHORT_FORM, TOTAL_TOTAL_METERS, TOTAL_AMI_METERS, TOTAL_AMR_METERS, TOTAL_NON_AMR_AMI_METERS,
       RESIDENTIAL_TOTAL_METERS, COMMERCIAL_TOTAL_METERS, TOTAL_ENERGY_SERVED_AMI_MWH
FROM LIBRARY_MARTS.ENERGY.ENERGY__FED_EIA861_ADVANCED_METERS
WHERE STATE IN ('MS','TN','AL','KY','GA') AND OWNERSHIP ILIKE 'Municipal%'
