-- column names of the 2023 generator file in landing, to line it up with 2024
SELECT COLUMN_NAME, DATA_TYPE, ORDINAL_POSITION FROM LIBRARY_RAW.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA='LANDING' AND TABLE_NAME='FED_EIA860_GENERATOR_Y2023' ORDER BY ORDINAL_POSITION
