-- OWNER time check: every coal unit >=100 MW operable in the 2023 EIA-860 file, its planned retirement year in 2023 vs 2024, and its 2024 owner count
WITH y23 AS (SELECT TRY_TO_NUMBER(PLANT_CODE) pc, TRIM(GENERATOR_ID) gid, MAX(PLANT_NAME) plant_name, MAX(STATE) st, MAX(UTILITY_NAME) operator,
                    MAX(TRY_TO_DOUBLE(NAMEPLATE_CAPACITY_MW)) mw23, MAX(TRY_TO_NUMBER(PLANNED_RETIREMENT_YEAR)) ry23, MAX(TRY_TO_NUMBER(OPERATING_YEAR)) oy,
                    COUNT(*) n23
             FROM LIBRARY_RAW.LANDING.FED_EIA860_GENERATOR_Y2023
             WHERE SHEET_NAME ILIKE 'Operable%' AND ENERGY_SOURCE_1 IN ('BIT','SUB','LIG','ANT','RC','WC','SGC')
               AND TRY_TO_DOUBLE(NAMEPLATE_CAPACITY_MW) >= 100
             GROUP BY 1,2),
g24 AS (SELECT PLANT_CODE, GENERATOR_ID, PLANNED_RETIREMENT_YEAR ry24, STATUS st24, ENERGY_SOURCE_1 f24
        FROM LIBRARY_MARTS.ENERGY.ENERGY__FED_EIA860_3_1_GENERATOR),
own AS (SELECT PLANT_CODE, GENERATOR_ID, COUNT(*) n_own, SUM(IFF(OWNERSHIP_ID<>UTILITY_ID,1,0)) nonop_owners
        FROM LIBRARY_MARTS.ENERGY.ENERGY__FED_EIA860_4_OWNER GROUP BY 1,2)
SELECT y23.pc, y23.gid, y23.plant_name, y23.st, y23.operator, y23.mw23, y23.oy, y23.ry23, g24.ry24, g24.st24, g24.f24, y23.n23,
       COALESCE(own.n_own,0) n_own, COALESCE(own.nonop_owners,0) nonop_owners
FROM y23 LEFT JOIN g24 ON g24.PLANT_CODE=y23.pc AND g24.GENERATOR_ID=y23.gid
LEFT JOIN own ON own.PLANT_CODE=y23.pc AND own.GENERATOR_ID=y23.gid
