-- OWNER whole table (5,495 rows) for address and filler checks, analyzed locally
SELECT PLANT_CODE, GENERATOR_ID, OWNERSHIP_ID, UTILITY_ID, UTILITY_NAME, PLANT_NAME, STATE, STATUS, OWNER_NAME, OWNER_STREET_ADDRESS, OWNER_CITY, OWNER_STATE, OWNER_ZIP, PERCENT_OWNED FROM LIBRARY_MARTS.ENERGY.ENERGY__FED_EIA860_4_OWNER
