{{ config(tags=['spine_generated']) }}

-- GRAIN: one row per place (GEOM is unique)
-- SPINE_ENTITY: place  (natural_key: SHAPE_AREA)
-- Generated by scripts/generate_staging_models.py from SOURCE_REGISTRY -- deterministic,
-- no LLM.
-- CASTS: 5 of 25 columns, from landing_column_profile_2026-09-19.tsv. A column is cast only
-- when every filled value in the sample parsed. try_ casts: a value that does not
-- parse reads NULL. The natural key and join-key columns stay TEXT.
--   objectid: ID: whole numbers, over 90% distinct -- stays TEXT, '.0' tail removed
--   facilityid: ID: whole numbers, over 90% distinct -- stays TEXT, '.0' tail removed
--   intid: ID: whole numbers, over 90% distinct -- stays TEXT, '.0' tail removed
--   areasqft: float
--   councildistrict: integer
-- spine_entity 'place' has no connect/ resolver yet (see connect/spine_entity.py) -- no SPINE_ENTITY_ID emitted.
-- landing table's ingestion timestamp is named INGESTED_AT (no leading underscore) rather than the usual _INGESTED_AT -- confirmed via INFORMATION_SCHEMA, not assumed.

with source as (

    select * from {{ source('ripple_raw', 'PORTAL_CKA_SAN_JOSE_OPEN_DA_8BC8CD595B') }}
    qualify row_number() over (partition by "SHAPE_AREA" order by INGESTED_AT desc) = 1

),

renamed as (

    select
        {{ stg_id_text('"OBJECTID"') }} as objectid,
        {{ stg_id_text('"FACILITYID"') }} as facilityid,
        {{ stg_id_text('"INTID"') }} as intid,
        {{ null_junk('"SALESFORCEID"') }} as salesforceid,
        {{ null_junk('"PARCELID"') }} as parcelid,
        {{ null_junk('"TYPEOFWORK"') }} as typeofwork,
        {{ null_junk('"LOCATION"') }} as location,
        {{ null_junk('"PARCELTYPE"') }} as parceltype,
        {{ stg_float('"AREASQFT"') }} as areasqft,
        {{ null_junk('"CURRENTDATE"') }} as currentdate,
        {{ null_junk('"LASTWORKDATE"') }} as lastworkdate,
        {{ null_junk('"LASTINSPECTIONDATE"') }} as lastinspectiondate,
        {{ null_junk('"CREATIONDATE"') }} as creationdate,
        {{ null_junk('"LASTUPDATE"') }} as lastupdate,
        {{ null_junk('"NOTES"') }} as notes,
        {{ null_junk('"DATETHREEMO"') }} as datethreemo,
        {{ null_junk('"DATEONEYR"') }} as dateoneyr,
        {{ null_junk('"SHAPE_LENGTH"') }} as shape_length,
        {{ null_junk('"SHAPE_AREA"') }} as shape_area,
        {{ null_junk('"DATETWOMONTHS"') }} as datetwomonths,
        {{ null_junk('"WILDFIRERISK"') }} as wildfirerisk,
        {{ null_junk('"GEOMETRYNOTES"') }} as geometrynotes,
        {{ null_junk('"CORRIDORGROUP"') }} as corridorgroup,
        {{ null_junk('"SUBCORRIDORGROUP"') }} as subcorridorgroup,
        {{ stg_int('"COUNCILDISTRICT"') }} as councildistrict,
        INGESTED_AT as _loaded_at,
        'https://data.sanjoseca.gov/dataset/weed-abatement-lots' as _source_url

    from source

)

select * from renamed
