{{ config(tags=['spine_generated']) }}

-- GRAIN: one row per record (spine_entity not determined -- no registry hint available) (ET_ID unique)
-- SPINE_ENTITY: (not determined)  (natural_key: ET_ID)
-- Generated by scripts/generate_staging_models.py from SOURCE_REGISTRY -- deterministic,
-- no LLM.
-- CASTS: 8 of 12 columns, from landing_column_profile_2026-09-19.tsv. A column is cast only
-- when every filled value in the sample parsed. try_ casts: a value that does not
-- parse reads NULL. The natural key and join-key columns stay TEXT.
--   x: float
--   y: float
--   fid: ID: whole numbers, over 90% distinct -- stays TEXT, '.0' tail removed
--   facilityid: ID: whole numbers, over 90% distinct -- stays TEXT, '.0' tail removed
--   et_idp: ID: whole numbers, over 90% distinct -- stays TEXT, '.0' tail removed
--   et_x: float
--   et_y: float
--   et_angle: float
-- spine_entity not determined (grain/natural_key proven, but no registry hint says what this row is ABOUT) -- no SPINE_ENTITY_ID emitted.
-- landing table's ingestion timestamp is named INGESTED_AT (no leading underscore) rather than the usual _INGESTED_AT -- confirmed via INFORMATION_SCHEMA, not assumed.

with source as (

    select * from {{ source('ripple_raw', 'PORTAL_CKA_WPRDC_ALLEGHENY_415F1FE712') }}
    qualify row_number() over (partition by "ET_ID" order by INGESTED_AT desc) = 1

),

renamed as (

    select
        {{ stg_float('"X"') }} as x,
        {{ stg_float('"Y"') }} as y,
        {{ stg_id_text('"FID"') }} as fid,
        {{ null_junk('"BRIDGE_COD"') }} as bridge_cod,
        {{ null_junk('"BRBIDGE_NA"') }} as brbidge_na,
        {{ stg_id_text('"FACILITYID"') }} as facilityid,
        {{ null_junk('"SHAPE_LENG"') }} as shape_leng,
        {{ null_junk('"ET_ID"') }} as et_id,
        {{ stg_id_text('"ET_IDP"') }} as et_idp,
        {{ stg_float('"ET_X"') }} as et_x,
        {{ stg_float('"ET_Y"') }} as et_y,
        {{ stg_float('"ET_ANGLE"') }} as et_angle,
        INGESTED_AT as _loaded_at,
        'https://data.wprdc.org/dataset/allegheny-county-owned-bridges-points' as _source_url

    from source

)

select * from renamed
