{{ config(tags=['spine_generated']) }}

-- GRAIN: one row per place (GEOM is unique)
-- SPINE_ENTITY: place  (natural_key: SHAPE_AREA)
-- Generated by scripts/generate_staging_models.py from SOURCE_REGISTRY -- deterministic,
-- no LLM.
-- CASTS: 8 of 20 columns, from landing_column_profile_2026-09-19.tsv. A column is cast only
-- when every filled value in the sample parsed. try_ casts: a value that does not
-- parse reads NULL. The natural key and join-key columns stay TEXT.
--   objectid: ID: whole numbers, over 90% distinct -- stays TEXT, '.0' tail removed
--   facilityid: ID: whole numbers, over 90% distinct -- stays TEXT, '.0' tail removed
--   intid: ID: whole numbers, over 90% distinct -- stays TEXT, '.0' tail removed
--   projectlevel: integer
--   ordinanceno: integer
--   projectlength: ID: whole numbers, over 90% distinct -- stays TEXT, '.0' tail removed
--   calclength: ID: whole numbers, over 90% distinct -- stays TEXT, '.0' tail removed
--   equityscore: float
-- spine_entity 'place' has no connect/ resolver yet (see connect/spine_entity.py) -- no SPINE_ENTITY_ID emitted.
-- landing table's ingestion timestamp is named INGESTED_AT (no leading underscore) rather than the usual _INGESTED_AT -- confirmed via INFORMATION_SCHEMA, not assumed.

with source as (

    select * from {{ source('ripple_raw', 'PORTAL_CKA_SAN_JOSE_OPEN_DA_17DD46EA4D') }}
    qualify row_number() over (partition by "SHAPE_AREA" order by INGESTED_AT desc) = 1

),

renamed as (

    select
        {{ stg_id_text('"OBJECTID"') }} as objectid,
        {{ stg_id_text('"FACILITYID"') }} as facilityid,
        {{ stg_id_text('"INTID"') }} as intid,
        {{ null_junk('"PROJECTYPE"') }} as projectype,
        {{ stg_int('"PROJECTLEVEL"') }} as projectlevel,
        {{ stg_int('"ORDINANCENO"') }} as ordinanceno,
        {{ null_junk('"LEGISLATIONDATE"') }} as legislationdate,
        {{ null_junk('"STREETNAME"') }} as streetname,
        {{ null_junk('"DISTRICT"') }} as district,
        {{ null_junk('"PROJECTRULE"') }} as projectrule,
        {{ null_junk('"LASTUPDATE"') }} as lastupdate,
        {{ null_junk('"NOTES"') }} as notes,
        {{ stg_id_text('"PROJECTLENGTH"') }} as projectlength,
        {{ stg_id_text('"CALCLENGTH"') }} as calclength,
        {{ null_junk('"DESIGNATION"') }} as designation,
        {{ null_junk('"SHAPE_LENGTH"') }} as shape_length,
        {{ null_junk('"SHAPE_AREA"') }} as shape_area,
        {{ stg_float('"EQUITYSCORE"') }} as equityscore,
        {{ null_junk('"REFNO"') }} as refno,
        {{ null_junk('"CREATIONDATE"') }} as creationdate,
        INGESTED_AT as _loaded_at,
        'https://data.sanjoseca.gov/dataset/underground-districts' as _source_url

    from source

)

select * from renamed
