-- deep3/g00: deep pass 3, 2026-09-24. Python door (connect/db.py), read-only SELECT/WITH only, QUERY_TAG 'deep3-2026-09-24'.
-- Every connection first ran: ALTER SESSION SET STATEMENT_TIMEOUT_IN_SECONDS = 300; ALTER SESSION SET QUERY_TAG = 'deep3-2026-09-24'. Those two are not counted.
-- Tables: HEALTH__FED_CMS_NPPES, HEALTH__FED_HRSA_HPSA_PRIMARY_CARE, HEALTH__SAM_EXCLUDED_PROVIDERS, HEALTH__FED_CDC_SUICIDE_RATES, HEALTH__FED_CMS_FACILITY_LEVEL_MINIMUM_DATA_SET_FREQUENCY.
-- 19 statements (S01-S19), all below, in run order. S07-S11 are extracts; the peer, time and chain math on them ran locally in pandas (g00/ scratch).
-- Outputs: g00/out_Sxx.txt and g00/out_Sxx.csv.

-- S01 CDC suicide: profile by unit and split, year range, flags, duplicate keys
SELECT UNIT_NUM, UNIT, STUB_NAME, COUNT(*) n, MIN(YEAR) y0, MAX(YEAR) y1, COUNT(DISTINCT YEAR) years,
       COUNT(DISTINCT STUB_LABEL, AGE, YEAR) keys, COUNT_IF(NULLIF(TRIM(FLAG),'') IS NOT NULL) flagged,
       COUNT_IF(NULLIF(TRIM(ESTIMATE),'') IS NULL) blank_est
FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CDC_SUICIDE_RATES
GROUP BY 1,2,3 ORDER BY 1,3;

-- S02 HPSA: status x designation type, date sentinels, how stale the last update is
SELECT HPSA_STATUS, DESIGNATION_TYPE, COUNT(*) n, COUNT(DISTINCT HPSA_ID) hpsas,
       MIN(DESIGNATION_DATE) d0, MAX(DESIGNATION_DATE) d1, COUNT_IF(DESIGNATION_DATE = '1970-01-01') d1970,
       COUNT(DISTINCT IFF(YEAR(DESIGNATION_DATE) < 1996, HPSA_ID, NULL)) hpsa_pre1996,
       MIN(DESIGNATION_LAST_UPDATE_DATE) u0, MAX(DESIGNATION_LAST_UPDATE_DATE) u1,
       COUNT(DISTINCT IFF(DESIGNATION_LAST_UPDATE_DATE < '2022-01-01', HPSA_ID, NULL)) hpsa_upd_pre2022,
       COUNT_IF(WITHDRAWN_DATE IS NOT NULL) wd, MEDIAN(HPSA_SCORE) med_score, COUNT_IF(HPSA_FTE = 0) fte0
FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_HRSA_HPSA_PRIMARY_CARE
GROUP BY 1,2 ORDER BY 1, n DESC;

-- S03 SAM excluded providers: agency x current, NPI fill, date sentinels, match method
SELECT EXCLUDING_AGENCY, COUNT(*) n, COUNT(DISTINCT SAM_NUMBER) sam_ids, COUNT_IF(IS_CURRENTLY_EXCLUDED) current_,
       COUNT_IF(IS_ENTITY_NOT_INDIVIDUAL) entities,
       COUNT_IF(REGEXP_LIKE(NPI,'^[0-9]{10}$') AND NPI <> '0000000000') npi_ok, COUNT_IF(REGEXP_LIKE(SAM_NPI,'^[0-9]{10}$') AND SAM_NPI <> '0000000000') sam_npi_ok,
       COUNT_IF(ACTIVATION_DATE > '2027-01-01') act_future, MIN(ACTIVATION_DATE) a0, MAX(IFF(ACTIVATION_DATE < '2027-01-01', ACTIVATION_DATE, NULL)) a1_real,
       COUNT_IF(TERMINATION_DATE_RAW ILIKE 'indef%') indefinite, ARRAY_AGG(DISTINCT MATCH_METHOD) methods
FROM LIBRARY_MARTS.HEALTH.HEALTH__SAM_EXCLUDED_PROVIDERS
GROUP BY ROLLUP(1) ORDER BY n DESC;

-- S04 MDS frequency: report dates, facilities, questions, suppression placeholder
SELECT REPORT_DATE, COUNT(*) n, COUNT(DISTINCT CCN) ccns, COUNT(DISTINCT MDS_ITEM_QUESTION_DESCRIPTION) questions,
       COUNT(DISTINCT MDS_ITEM_QUESTION_DESCRIPTION, MDS_ITEM_RESPONSE) q_resp,
       COUNT_IF(TOTAL_RESIDENTS = '_') tot_placeholder, COUNT_IF(OVERALL_PERCENT IS NOT NULL) overall_filled,
       COUNT_IF(LONG_STAY_PERCENT IS NOT NULL) ls_filled, COUNT(DISTINCT CCN, MDS_ITEM_QUESTION_DESCRIPTION, MDS_ITEM_RESPONSE) keys
FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_FACILITY_LEVEL_MINIMUM_DATA_SET_FREQUENCY
GROUP BY 1 ORDER BY 1;

-- S05 MDS frequency: the psych, PASRR, falls, ulcer, restraint items and how filled they are
SELECT MDS_ITEM_QUESTION_DESCRIPTION q, MDS_ITEM_RESPONSE r, COUNT(*) n, COUNT(DISTINCT CCN) ccns,
       COUNT_IF(OVERALL_PERCENT IS NOT NULL) ov_filled, COUNT_IF(LONG_STAY_PERCENT IS NOT NULL) ls_filled,
       MEDIAN(OVERALL_PERCENT) med_ov, MEDIAN(LONG_STAY_PERCENT) med_ls, MAX(TRY_TO_NUMBER(TOTAL_RESIDENTS)) max_tot
FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_FACILITY_LEVEL_MINIMUM_DATA_SET_FREQUENCY
WHERE MDS_ITEM_QUESTION_DESCRIPTION ILIKE ANY ('I6000%','N0415A%','N0450%','A1500%','A1510%','J1800%','M0300%','P0100%','I5700%','I5800%','I5900%','I5950%','I6100%','A0310A%')
GROUP BY 1,2 ORDER BY 1,2;

-- S06 NPPES: entity type x enumeration year, deactivation fill
SELECT ENTITY_TYPE_CODE, YEAR(PROVIDER_ENUMERATION_DATE) y, COUNT(*) n,
       COUNT_IF(NPI_DEACTIVATION_DATE IS NOT NULL) deact, COUNT_IF(NPI_REACTIVATION_DATE IS NOT NULL) react,
       COUNT_IF(NULLIF(TRIM(PROVIDER_FIRST_LINE_BUSINESS_PRACTICE_LOCATION_ADDRESS),'') IS NULL) no_addr,
       COUNT_IF(HEALTHCARE_PROVIDER_TAXONOMY_CODE_1 = '251G00000X') hospice_tx1
FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_NPPES
GROUP BY 1,2 ORDER BY 1,2;

-- S07 CDC suicide: full extract (6,390 rows) for local growth math
SELECT UNIT_NUM, STUB_NAME, STUB_LABEL, AGE, YEAR, ESTIMATE, FLAG
FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CDC_SUICIDE_RATES;

-- S08 HPSA: one row per shortage area (HPSA_ID), components collapsed
SELECT HPSA_ID, ANY_VALUE(HPSA_NAME) name, COUNT(*) comps, COUNT(DISTINCT HPSA_STATUS) nstat, ANY_VALUE(HPSA_STATUS) status,
       ANY_VALUE(DESIGNATION_TYPE) dtype, ANY_VALUE(PRIMARY_STATE_ABBREVIATION) st, MIN(DESIGNATION_DATE) ddate,
       MAX(DESIGNATION_LAST_UPDATE_DATE) upd, MAX(WITHDRAWN_DATE) wd, MAX(DESIGNATION_POPULATION) pop,
       MAX(PCT_POPULATION_BELOW_POVERTY) pov, MAX(HPSA_SCORE) score, MAX(HPSA_FTE) fte, MAX(HPSA_SHORTAGE) shortage,
       ANY_VALUE(RURAL_STATUS) rural, ANY_VALUE(POPULATION_TYPE) poptype, ANY_VALUE(FORMAL_RATIO) ratio,
       MAX(ESTIMATED_UNDERSERVED_POPULATION) underserved, COUNT(DISTINCT COMMON_STATE_COUNTY_FIPS_CODE) counties,
       ANY_VALUE(COMMON_STATE_COUNTY_FIPS_CODE) fips, ANY_VALUE(COMMON_COUNTY_NAME) county
FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_HRSA_HPSA_PRIMARY_CARE
GROUP BY 1;

-- S09 SAM excluded providers with a 10-digit NPI: does NPPES, Medicare or the OIG list agree on city?
WITH s AS (
  SELECT SAM_NUMBER, NPI, SAM_NPI, EXCLUDING_AGENCY, EXCLUSION_TYPE, EXCLUSION_PROGRAM, CLASSIFICATION, IS_ENTITY_NOT_INDIVIDUAL,
         ENTITY_NAME, FIRST_NAME, LAST_NAME, CITY, STATE, ACTIVATION_DATE, TERMINATION_DATE_RAW, IS_CURRENTLY_EXCLUDED,
         MATCH_METHOD, MATCH_NOTE, NPPES_NAME, TAXONOMY_CODE_1, CREDENTIAL
  FROM LIBRARY_MARTS.HEALTH.HEALTH__SAM_EXCLUDED_PROVIDERS
  WHERE REGEXP_LIKE(NPI, '^[0-9]{10}$') AND NPI <> '0000000000'),
n AS (
  SELECT NPI, ENTITY_TYPE_CODE et, PROVIDER_LAST_NAME_LEGAL_NAME ln, PROVIDER_FIRST_NAME fn, PROVIDER_MIDDLE_NAME mn,
         UPPER(TRIM(PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_CITY_NAME)) pcity, PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_STATE_NAME pst,
         UPPER(TRIM(PROVIDER_BUSINESS_MAILING_ADDRESS_CITY_NAME)) mcity, PROVIDER_BUSINESS_MAILING_ADDRESS_STATE_NAME mst,
         PROVIDER_CREDENTIAL_TEXT cred, HEALTHCARE_PROVIDER_TAXONOMY_CODE_1 tx, PROVIDER_ENUMERATION_DATE en, LAST_UPDATE_DATE lu
  FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_NPPES WHERE NPI IN (SELECT NPI FROM s)),
b AS (
  SELECT RNDRNG_NPI npi, SUM(TOT_MDCR_PYMT_AMT) partb_pay, MAX(UPPER(TRIM(RNDRNG_PRVDR_CITY))) bcity
  FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_MEDICARE_PHYSICIAN_OTHER_PRACTITIONERS_BY_PROVIDER
  WHERE RNDRNG_NPI IN (SELECT NPI FROM s) GROUP BY 1),
d AS (
  SELECT NPI, ARRAY_AGG(DISTINCT DATA_YEAR) dyears, SUM(TRY_TO_NUMBER(TOT_CLMS)) partd_clms,
         SUM(TRY_TO_DOUBLE(NULLIF(LOWER(TOT_DRUG_CST), 'nan'))) partd_cost, SUM(TRY_TO_NUMBER(OPIOID_TOT_CLMS)) opioid_clms,
         MAX(UPPER(TRIM(PRSCRBR_CITY))) dcity
  FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_PART_D_PRESCRIBERS WHERE NPI IN (SELECT NPI FROM s) GROUP BY 1),
l AS (
  SELECT NPI, MIN(EXCLUSION_DATE) leie_date, ANY_VALUE(EXCLUSION_TYPE) leie_type, ANY_VALUE(UPPER(TRIM(CITY))) lcity
  FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_HHS_OIG_LEIE WHERE NPI IN (SELECT NPI FROM s) GROUP BY 1),
l2 AS (
  SELECT UPPER(TRIM(LAST_NAME)) lnm, UPPER(TRIM(FIRST_NAME)) fnm, STATE, MIN(EXCLUSION_DATE) leie_name_date,
         LISTAGG(DISTINCT UPPER(TRIM(CITY)), '/') leie_name_city
  FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_HHS_OIG_LEIE WHERE NULLIF(TRIM(LAST_NAME), '') IS NOT NULL GROUP BY 1,2,3)
SELECT s.*, n.et, n.ln, n.fn, n.mn, n.pcity, n.pst, n.mcity, n.mst, n.cred, n.tx, n.en, n.lu,
       b.partb_pay, b.bcity, d.dyears, d.partd_clms, d.partd_cost, d.opioid_clms, d.dcity,
       l.leie_date, l.leie_type, l.lcity, l2.leie_name_date, l2.leie_name_city,
       IFF(UPPER(TRIM(s.CITY)) IN (n.pcity, n.mcity, b.bcity, d.dcity), 1, 0) city_agree
FROM s LEFT JOIN n ON n.NPI = s.NPI LEFT JOIN b ON b.npi = s.NPI LEFT JOIN d ON d.NPI = s.NPI LEFT JOIN l ON l.NPI = s.NPI
LEFT JOIN l2 ON l2.lnm = UPPER(TRIM(s.LAST_NAME)) AND l2.fnm = UPPER(TRIM(s.FIRST_NAME)) AND l2.STATE = s.STATE;

-- S10 NPPES: every hospice organization NPI (taxonomy slot 1 = 251G00000X), with Medicare enrollment and certification joined
WITH h AS (
  SELECT NPI, PROVIDER_ORGANIZATION_NAME_LEGAL_BUSINESS_NAME org, PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_STATE_NAME st,
         UPPER(TRIM(PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_CITY_NAME)) city, LEFT(PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_POSTAL_CODE, 5) zip5,
         UPPER(TRIM(PROVIDER_FIRST_LINE_BUSINESS_PRACTICE_LOCATION_ADDRESS)) addr, UPPER(TRIM(PROVIDER_SECOND_LINE_BUSINESS_PRACTICE_LOCATION_ADDRESS)) addr2,
         PROVIDER_ENUMERATION_DATE en, LAST_UPDATE_DATE lu, NPI_DEACTIVATION_DATE deact,
         UPPER(TRIM(AUTHORIZED_OFFICIAL_LAST_NAME)) ao_ln, UPPER(TRIM(AUTHORIZED_OFFICIAL_FIRST_NAME)) ao_fn, AUTHORIZED_OFFICIAL_TITLE_OR_POSITION ao_title,
         AUTHORIZED_OFFICIAL_TELEPHONE_NUMBER ao_phone, PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_TELEPHONE_NUMBER phone,
         IS_ORGANIZATION_SUBPART sub, PARENT_ORGANIZATION_LBN parent
  FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_NPPES
  WHERE ENTITY_TYPE_CODE = '2' AND HEALTHCARE_PROVIDER_TAXONOMY_CODE_1 = '251G00000X'),
e AS (
  SELECT NPI, MAX(CCN) ccn, MAX(ENROLLMENT_STATE) est, MAX(INCORPORATION_DATE) inc, COUNT(*) enr_rows
  FROM LIBRARY_MARTS.IMMIGRATION.IMMIGRATION__FED_CMS_HOSPICE_ENROLLMENTS GROUP BY 1),
c AS (
  SELECT CCN, CERTIFICATION_DATE cert, OWNERSHIP_TYPE own FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_HOSPICE)
SELECT h.*, e.ccn, e.est, e.inc, e.enr_rows, c.cert, c.own
FROM h LEFT JOIN e ON e.NPI = h.NPI LEFT JOIN c ON c.CCN = e.ccn;

-- S11 MDS: one row per nursing home, schizophrenia / antipsychotic / dementia counts, joined to star file and survey tags
WITH x AS (
  SELECT CCN, STATE, PROVIDER_NAME, CITY, LEFT(MDS_ITEM_QUESTION_DESCRIPTION, 7) q, MDS_ITEM_RESPONSE r, OVERALL_PERCENT,
         TRY_TO_NUMBER(TOTAL_RESIDENTS) tot, LONG_STAY_PERCENT, SHORT_STAY_PERCENT,
         TRY_TO_NUMBER(LONG_STAY_RESIDENTS) ls_n, TRY_TO_NUMBER(SHORT_STAY_RESIDENTS) ss_n
  FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_FACILITY_LEVEL_MINIMUM_DATA_SET_FREQUENCY
  WHERE MDS_ITEM_QUESTION_DESCRIPTION LIKE ANY ('I6000:%', 'N0415A1:%', 'I5950:%', 'I5900:%', 'I4800:%', 'I4200:%')),
m AS (
  SELECT CCN, ANY_VALUE(STATE) st, ANY_VALUE(PROVIDER_NAME) name, ANY_VALUE(CITY) city,
    MAX(IFF(q = 'I6000: ' AND r = 'Yes', OVERALL_PERCENT, NULL)) sz_pct,
    MAX(IFF(q = 'I6000: ' AND r = 'Yes', tot, NULL)) sz_n,
    MAX(IFF(q = 'I6000: ' AND r = 'No', tot, NULL)) sz_no_n,
    MAX(IFF(q = 'I6000: ' AND r = 'Yes', LONG_STAY_PERCENT, NULL)) sz_ls_pct,
    MAX(IFF(q = 'I6000: ' AND r = 'Yes', SHORT_STAY_PERCENT, NULL)) sz_ss_pct,
    MAX(IFF(q = 'I6000: ' AND r = 'Yes', ls_n, NULL)) sz_ls_n,
    MAX(IFF(q = 'I6000: ' AND r = 'Yes', ss_n, NULL)) sz_ss_n,
    MAX(IFF(q = 'I6000: ' AND r = 'No', ls_n, NULL)) sz_no_ls_n,
    MAX(IFF(q = 'I6000: ' AND r = 'No', ss_n, NULL)) sz_no_ss_n,
    MAX(IFF(q = 'N0415A1' AND r = 'Yes', OVERALL_PERCENT, NULL)) ap_pct,
    MAX(IFF(q = 'N0415A1' AND r = 'Yes', tot, NULL)) ap_n,
    MAX(IFF(q = 'N0415A1' AND r = 'No', tot, NULL)) ap_no_n,
    MAX(IFF(q = 'I5950: ' AND r = 'Yes', tot, NULL)) psy_n,
    MAX(IFF(q = 'I5900: ' AND r = 'Yes', tot, NULL)) bip_n,
    MAX(IFF(q = 'I4800: ' AND r = 'Yes', tot, NULL)) dem_n,
    MAX(IFF(q = 'I4200: ' AND r = 'Yes', tot, NULL)) alz_n,
    MAX(IFF(q = 'I4800: ' AND r = 'Yes', OVERALL_PERCENT, NULL)) dem_pct,
    MAX(IFF(q = 'I4200: ' AND r = 'Yes', OVERALL_PERCENT, NULL)) alz_pct
  FROM x GROUP BY CCN),
df AS (
  SELECT CMS_CERTIFICATION_NUMBER_CCN ccn,
    COUNT_IF(TRY_TO_NUMBER(REGEXP_SUBSTR(DEFICIENCY_TAG_NUMBER, '[0-9]+')) = 641) f641,
    COUNT_IF(TRY_TO_NUMBER(REGEXP_SUBSTR(DEFICIENCY_TAG_NUMBER, '[0-9]+')) = 758) f758,
    COUNT_IF(TRY_TO_NUMBER(REGEXP_SUBSTR(DEFICIENCY_TAG_NUMBER, '[0-9]+')) = 605) f605,
    COUNT(*) all_def, MIN(SURVEY_DATE) s0, MAX(SURVEY_DATE) s1, ANY_VALUE(DEFICIENCY_TAG_NUMBER) tag_sample
  FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_NURSING_HOME_DEFICIENCIES GROUP BY 1)
SELECT m.*, nh.LEGAL_BUSINESS_NAME, nh.CHAIN_NAME, nh.CHAIN_ID, nh.NUMBER_OF_FACILITIES_IN_CHAIN, nh.OWNERSHIP_TYPE,
       nh.NUMBER_OF_CERTIFIED_BEDS, nh.AVERAGE_NUMBER_OF_RESIDENTS_PER_DAY, nh.OVERALL_RATING, nh.QUALITY_MEASURE_RATING,
       nh.TOTAL_AMOUNT_OF_FINES_IN_DOLLARS, nh.NUMBER_OF_FINES, nh.SPECIAL_FOCUS_STATUS, nh.ABUSE_ICON, nh.PROVIDER_RESIDES_IN_HOSPITAL,
       nh.CMS_CERTIFICATION_NUMBER_CCN nh_ccn, df.f641, df.f758, df.f605, df.all_def, df.s0, df.s1, df.tag_sample
FROM m LEFT JOIN LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_NURSING_HOME nh ON nh.CMS_CERTIFICATION_NUMBER_CCN = m.CCN
LEFT JOIN df ON df.ccn = m.CCN;

-- S12 NPPES hospice verify in SQL: LA-area phone share by period and region, Medicare enrollment by NPI, name-only hits, and the deactivated-row check
WITH h AS (
  SELECT NPI, UPPER(TRIM(PROVIDER_ORGANIZATION_NAME_LEGAL_BUSINESS_NAME)) org,
         PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_STATE_NAME st, YEAR(PROVIDER_ENUMERATION_DATE) y,
         LEFT(REGEXP_REPLACE(PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_TELEPHONE_NUMBER, '[^0-9]', ''), 3) ac1,
         LEFT(REGEXP_REPLACE(AUTHORIZED_OFFICIAL_TELEPHONE_NUMBER, '[^0-9]', ''), 3) ac2
  FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_NPPES
  WHERE ENTITY_TYPE_CODE = '2' AND HEALTHCARE_PROVIDER_TAXONOMY_CODE_1 = '251G00000X'),
f AS (
  SELECT h.*, IFF(ac1 IN ('213','310','323','424','562','626','661','747','818','840')
               OR ac2 IN ('213','310','323','424','562','626','661','747','818','840'), 1, 0) la
  FROM h),
e AS (SELECT DISTINCT NPI FROM LIBRARY_MARTS.IMMIGRATION.IMMIGRATION__FED_CMS_HOSPICE_ENROLLMENTS),
nm AS (
  SELECT UPPER(TRIM(ORGANIZATION_NAME)) nm FROM LIBRARY_MARTS.IMMIGRATION.IMMIGRATION__FED_CMS_HOSPICE_ENROLLMENTS
  UNION SELECT UPPER(TRIM(DOING_BUSINESS_AS_NAME)) FROM LIBRARY_MARTS.IMMIGRATION.IMMIGRATION__FED_CMS_HOSPICE_ENROLLMENTS
  UNION SELECT UPPER(TRIM(FACILITY_NAME)) FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_HOSPICE)
SELECT IFF(st = 'CA', 'CA', 'outside CA') region, IFF(st IN ('AZ','NV'), st, 'other') st2,
       CASE WHEN y <= 2016 THEN '05-16' WHEN y <= 2019 THEN '17-19' WHEN y <= 2021 THEN '20-21' WHEN y <= 2023 THEN '22-23' ELSE '24-26' END per,
       la, COUNT(*) n, COUNT(e.NPI) enrolled_by_npi, COUNT_IF(e.NPI IS NULL AND nm.nm IS NOT NULL) name_only_hit,
       (SELECT COUNT_IF(NULLIF(TRIM(HEALTHCARE_PROVIDER_TAXONOMY_CODE_1), '') IS NOT NULL
                     OR NULLIF(TRIM(PROVIDER_LAST_NAME_LEGAL_NAME), '') IS NOT NULL
                     OR NULLIF(TRIM(PROVIDER_ORGANIZATION_NAME_LEGAL_BUSINESS_NAME), '') IS NOT NULL)
        FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_NPPES WHERE NULLIF(TRIM(ENTITY_TYPE_CODE), '') IS NULL) deact_rows_with_name_or_taxonomy
FROM f LEFT JOIN e ON e.NPI = f.NPI LEFT JOIN nm ON nm.nm = f.org
GROUP BY 1,2,3,4 ORDER BY 1,2,3,4;

-- S13 MDS verify in SQL: Missouri homes by Reliant vs other, schizophrenia band 40%+, stars, abuse icon, fines
WITH sz AS (
  SELECT CCN, MAX(OVERALL_PERCENT) pct, MAX(TRY_TO_NUMBER(TOTAL_RESIDENTS)) n
  FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_FACILITY_LEVEL_MINIMUM_DATA_SET_FREQUENCY
  WHERE MDS_ITEM_QUESTION_DESCRIPTION LIKE 'I6000:%' AND MDS_ITEM_RESPONSE = 'Yes' GROUP BY 1)
SELECT IFF(nh.CHAIN_NAME = 'RELIANT CARE MANAGEMENT', 'Reliant', 'other') grp, IFF(sz.pct >= 40, '40%+', 'under 40 or suppressed') band,
       COUNT(*) homes, COUNT_IF(nh.OVERALL_RATING = 1) one_star, COUNT(nh.OVERALL_RATING) rated, COUNT_IF(nh.ABUSE_ICON = 'Y') abuse_icon,
       COUNT_IF(nh.SPECIAL_FOCUS_STATUS IS NOT NULL) sff_or_cand, SUM(nh.TOTAL_AMOUNT_OF_FINES_IN_DOLLARS) fines,
       MEDIAN(nh.TOTAL_AMOUNT_OF_FINES_IN_DOLLARS) med_fines, SUM(sz.n) sz_residents_unsuppressed,
       SUM(nh.AVERAGE_NUMBER_OF_RESIDENTS_PER_DAY) avg_residents, MIN(nh.CHAIN_AVERAGE_OVERALL_5_STAR_RATING) chain_avg_star
FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_NURSING_HOME nh LEFT JOIN sz ON sz.CCN = nh.CMS_CERTIFICATION_NUMBER_CCN
WHERE nh.STATE = 'MO'
GROUP BY 1,2 ORDER BY 1,2;

-- S14 MDS time check: CMS penalties by year for Reliant vs other Missouri 40%+ schizophrenia homes vs the rest of Missouri
WITH sz AS (
  SELECT CCN, MAX(OVERALL_PERCENT) pct
  FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_FACILITY_LEVEL_MINIMUM_DATA_SET_FREQUENCY
  WHERE MDS_ITEM_QUESTION_DESCRIPTION LIKE 'I6000:%' AND MDS_ITEM_RESPONSE = 'Yes' GROUP BY 1),
g AS (
  SELECT nh.CMS_CERTIFICATION_NUMBER_CCN ccn,
         CASE WHEN nh.CHAIN_NAME = 'RELIANT CARE MANAGEMENT' THEN 'Reliant' WHEN sz.pct >= 40 THEN 'MO other 40%+' ELSE 'MO rest' END grp
  FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_NURSING_HOME nh LEFT JOIN sz ON sz.CCN = nh.CMS_CERTIFICATION_NUMBER_CCN
  WHERE nh.STATE = 'MO'),
gc AS (SELECT grp, COUNT(*) homes_in_group FROM g GROUP BY 1)
SELECT g.grp, gc.homes_in_group, YEAR(p.PENALTY_DATE) y, COUNT(*) penalties,
       COUNT_IF(p.PENALTY_TYPE ILIKE 'fine%') fines_n, SUM(p.FINE_AMOUNT) fine_dollars, COUNT(DISTINCT p.CMS_CERTIFICATION_NUMBER_CCN) homes_penalized
FROM g JOIN gc ON gc.grp = g.grp JOIN LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_NURSING_HOME_PENALTIES p ON p.CMS_CERTIFICATION_NUMBER_CCN = g.ccn
GROUP BY 1,2,3 ORDER BY 1,3;

-- S15 HPSA verify in SQL: active primary-care area HPSAs, CA and FL vs all other, designated vs proposed for withdrawal
WITH h AS (
  SELECT HPSA_ID, ANY_VALUE(HPSA_STATUS) status, ANY_VALUE(PRIMARY_STATE_ABBREVIATION) s, MAX(DESIGNATION_POPULATION) pop,
         MAX(HPSA_SCORE) sc, MAX(HPSA_FTE) fte, MAX(DESIGNATION_LAST_UPDATE_DATE) upd, MIN(DESIGNATION_DATE) ddate,
         MAX(PCT_POPULATION_BELOW_POVERTY) pov, ANY_VALUE(RURAL_STATUS) rural
  FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_HRSA_HPSA_PRIMARY_CARE
  WHERE DESIGNATION_TYPE IN ('Geographic HPSA', 'HPSA Population', 'High Needs Geographic HPSA') GROUP BY 1)
SELECT IFF(s IN ('CA','FL'), s, 'ALL OTHER') s2, status, COUNT(*) n, SUM(pop) pop, MEDIAN(sc) med_score, AVG(sc) avg_score,
       COUNT_IF(sc >= 18) score18plus, COUNT_IF(fte = 0) fte0, COUNT_IF(TO_CHAR(upd, 'YYYY-MM') = '2025-09') upd_sep2025,
       MEDIAN(YEAR(ddate)) med_desig_year, MEDIAN(pov) med_pov, COUNT_IF(rural = 'Rural') rural_n
FROM h WHERE status <> 'Withdrawn'
GROUP BY 1,2 ORDER BY 1,2;

-- S16 SAM trap check: blank agency vs source SAM file, repeated people, LEIE name+state hits
WITH s AS (SELECT * FROM LIBRARY_MARTS.HEALTH.HEALTH__SAM_EXCLUDED_PROVIDERS),
src AS (SELECT SAM_NUMBER, EXCLUDING_AGENCY src_agency FROM LIBRARY_MARTS.PROCUREMENT.PROCUREMENT__FED_SAM_EXCLUSIONS),
l2 AS (
  SELECT DISTINCT UPPER(TRIM(LAST_NAME)) lnm, UPPER(TRIM(FIRST_NAME)) fnm, STATE
  FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_HHS_OIG_LEIE WHERE NULLIF(TRIM(LAST_NAME), '') IS NOT NULL)
SELECT IFF(NULLIF(TRIM(s.EXCLUDING_AGENCY), '') IS NULL, 'blank', 'named') ag, COALESCE(src.src_agency, '(blank in source)') src_agency,
       COUNT(*) n, COUNT(DISTINCT s.SAM_NUMBER) sam_ids,
       COUNT(DISTINCT COALESCE(UPPER(s.ENTITY_NAME),'') || '|' || COALESCE(UPPER(s.FIRST_NAME),'') || '|' || COALESCE(UPPER(s.LAST_NAME),'') || '|' || COALESCE(UPPER(s.CITY),'') || '|' || COALESCE(s.STATE,'')) people,
       COUNT_IF(NOT s.IS_ENTITY_NOT_INDIVIDUAL) individuals, COUNT_IF(l2.lnm IS NOT NULL) leie_name_state_hits,
       COUNT_IF(REGEXP_LIKE(s.NPI, '^[0-9]{10}$') AND s.NPI <> '0000000000') npi_guessed, MODE(s.EXCLUSION_TYPE) top_type
FROM s LEFT JOIN src ON src.SAM_NUMBER = s.SAM_NUMBER
LEFT JOIN l2 ON l2.lnm = UPPER(TRIM(s.LAST_NAME)) AND l2.fnm = UPPER(TRIM(s.FIRST_NAME)) AND l2.STATE = s.STATE
GROUP BY 1,2 ORDER BY 1, n DESC;

-- S17 Hospice: do the 126 officials or 179 NPIs behind LA-phone hospices outside California appear on the OIG or SAM exclusion lists?
WITH ao(fn, ln) AS (SELECT * FROM VALUES
    ('ACHOT','MKRTCHIAN'),
    ('AGNES','DALDUMYAN'),
    ('AGNES','TAN'),
    ('AILEEN','BRAWNER'),
    ('ALBERT','HAMBARDZUMYAN'),
    ('ALDRIN','PAGALA'),
    ('ALMA','INIT'),
    ('ANABELLE','ABELLA'),
    ('ANAHIT','MARKARYAN'),
    ('ANDRANIK','SAMSONYAN'),
    ('ANDY','KECHEJIAN'),
    ('ANNA','TOVMASYAN'),
    ('ANNA','VARDANYAN'),
    ('ARA','ADAMYAN'),
    ('ARAM','AVAGYAN'),
    ('ARBI','NAZARIAN'),
    ('ARMAN','NAZARYAN'),
    ('ARMAN','VARDANYAN'),
    ('ARMEN','APOYAN'),
    ('ARMEN','GEVORGYAN'),
    ('ARMEN','HOVSEPYAN'),
    ('ARMINE','EDIGARYAN'),
    ('ARMINE','PETROSIAN'),
    ('ARSEN','KAZARYAN'),
    ('ARTUR','BALAYAN'),
    ('ARTUR','NAZARYAN'),
    ('ARTYOM','MANUKYAN'),
    ('BENJAMIN','CABRERA'),
    ('BENJAMIN','OCARIZA'),
    ('BRAXTON','MCGREGOR'),
    ('CHRISTOPHER','DOAN'),
    ('DOMINGO','BACCAY'),
    ('EDGAR','GRIGORYAN'),
    ('EDITA','HOVHANNISYAN'),
    ('EDITHA','SWANSER'),
    ('EDWIN HORMOZI','BORASHAN'),
    ('EKATERINA','APOYAN'),
    ('EMMA','ALEKSANYAN'),
    ('EMMALYN','ALCANTARA'),
    ('ERICA','PAHUA'),
    ('FILOMENO','ALCAIDE'),
    ('GAGIK','SINDOYAN'),
    ('GAYANE','AROUTIOUNIAN'),
    ('GAYANE','PETROSYAN'),
    ('GEORGE','HAMBARTSUMYAN'),
    ('GEORGE','KRBOYAN'),
    ('GEVORG','NALBANDIAN'),
    ('GEVORK','NALBANDIAN'),
    ('GRIGOR','GRIGORIAN'),
    ('HAKOB','SARGSYAN'),
    ('HAROUT','BARGHOUTIAN'),
    ('HASMIK','NIKOGHOSYAN'),
    ('HASMIK JASMINE','MINASYAN'),
    ('HAYK','MANUKYAN'),
    ('HERBERT','RELAMPAGOS'),
    ('HIELDEEN','BONSALL'),
    ('IKECHUKWU','AGU'),
    ('IRENA','PALOYAN'),
    ('JAN','FLORES'),
    ('JERRY','BORDELEAU'),
    ('JOAN MAY','COOK'),
    ('JOANNE','WILSON'),
    ('JOHN','GEISS'),
    ('JONATHAN','GARCIA'),
    ('JULIE','KHUDAGULYAN'),
    ('KAMAL','SAKKAY'),
    ('KATERYNA','MOSKALENKO'),
    ('KHACHATUR','ZADIKYAN'),
    ('KHATUN','KARAMUSYAN'),
    ('LAMBERTO','VALIENTE JR'),
    ('LARRY','FLOWERS'),
    ('LILI','ARAKELIAN'),
    ('LILIT','SEDRAKYAN'),
    ('LOURDES','URQUIA'),
    ('LOUSIK','AIRAPETIAN'),
    ('LUIZA','PETROSYAN'),
    ('MAIS','MELIKIAN'),
    ('MANIFA','MELIKIAN'),
    ('MARIA VISITACION','TESRO'),
    ('MARILOU','LARDIZABAL'),
    ('MARINA','KUSHNIROVICH'),
    ('MARINE','KHACHATRYAN'),
    ('MARINE','MINASYAN'),
    ('MARTIN','PEREZ'),
    ('MARVYN','ABELLA'),
    ('MELINE','ZOGRABYAN'),
    ('MERI','GALSTYAN'),
    ('MIHRAN','TELALYAN'),
    ('NADEZHDA','EDRIVANOVA'),
    ('NELLI','PRAZYAN'),
    ('NELSON','FONTANILLA'),
    ('NOEL','SULLIVAN'),
    ('NORA','AMRANYAN'),
    ('NORAYR','GASPARYAN'),
    ('NVARD','CHUKULYAN'),
    ('NVART','ZOGRABYAN'),
    ('OVSEP','DZHIGARSZYAN'),
    ('PAOLA','ABARCA'),
    ('PATRICK','BAGUMYAN'),
    ('PAUL','MARTINEZ'),
    ('PAULINE ANNE','MIRANDA'),
    ('PETER JEORGE','TEODORO'),
    ('RAYMND','OBIAMALU'),
    ('REGINA','STERIN'),
    ('RONI','EAPEN'),
    ('SAM','SANASAR'),
    ('SARKIS','CHOLAKYAN'),
    ('SARKIS','PETROSYAN'),
    ('SERGEY','HARUTYUNYAN'),
    ('SEROB RUBENI','YEGHIAZARYAN'),
    ('SEVAK','HOVHANNISYAN'),
    ('SHAHEN','MURADYAN'),
    ('SHEILA','ANTOLIN'),
    ('SHELLYDALE','GRAY'),
    ('SHERRY','CACANINDIN'),
    ('SONIA','ANCHETA'),
    ('SVETIK','HARUTYUNYAN'),
    ('TAMARA','HOVHANNISYAN'),
    ('TERESITA','CALAGUI'),
    ('TERRI','WARREN'),
    ('THOMAS','ZGAMBO'),
    ('TIGRANUSH','MALYAN'),
    ('VAHAN','SETYAN'),
    ('VAHAN','ZARGARYAN'),
    ('VARDAN','KIRAKOSYAN'),
    ('VAUGHN','DANAO')),
np(npi) AS (SELECT * FROM VALUES ('1003498569'),('1003512468'),('1013595230'),('1013648583'),('1033780994'),('1043005432'),('1043802523'),('1043968977'),('1053066829'),('1053097758'),('1073113981'),('1073220158'),('1083354021'),('1083354567'),('1093334880'),('1093455586'),('1104557032'),('1114505062'),('1114679180'),('1124799366'),('1124809595'),('1134705395'),('1134869464'),('1134879091'),('1134896475'),('1144905506'),('1144951286'),('1144951609'),('1144951690'),('1154096824'),('1154942217'),('1174286843'),('1174354963'),('1184378986'),('1194576389'),('1205533494'),('1215677265'),('1215682091'),('1215737861'),('1215785621'),('1225784747'),('1235860792'),('1235879271'),('1255082111'),('1265182158'),('1275133142'),('1275288961'),('1275420580'),('1275485294'),('1285225847'),('1285249979'),('1295494862'),('1306586417'),('1316678865'),('1326619271'),('1326631656'),('1346986361'),('1356035158'),('1356919153'),('1356939854'),('1366111270'),('1366173825'),('1386301364'),('1386376069'),('1396498085'),('1407461643'),('1407546534'),('1427658392'),('1447132774'),('1447901301'),('1457005837'),('1457073488'),('1457948937'),('1467100941'),('1467110858'),('1477140671'),('1477259836'),('1477284941'),('1487545117'),('1497401921'),('1497428288'),('1497486963'),('1497503809'),('1508514092'),('1528713393'),('1528757242'),('1538809587'),('1568053122'),('1568103802'),('1568111201'),('1568112142'),('1568117349'),('1568242584'),('1568278844'),('1568299469'),('1578218343'),('1578218566'),('1588255103'),('1588317275'),('1609685361'),('1619617164'),('1629725726'),('1629752258'),('1639770043'),('1639891674'),('1649863085'),('1649910670'),('1649925413'),('1659039725'),('1659181725'),('1669132072'),('1679220800'),('1689289373'),('1689337297'),('1689343162'),('1699380386'),('1699406140'),('1699442939'),('1699466730'),('1700539541'),('1710860515'),('1720737844'),('1730778333'),('1730787607'),('1730839978'),('1740927946'),('1750103883'),('1760113237'),('1760132633'),('1760135453'),('1760135503'),('1760139992'),('1760165773'),('1760183602'),('1760218077'),('1770175093'),('1780315242'),('1780332221'),('1790376341'),('1790407617'),('1801525746'),('1801527387'),('1801541677'),('1811693542'),('1821810847'),('1831834571'),('1831844612'),('1841051430'),('1841922523'),('1841961331'),('1841996584'),('1851000624'),('1851047492'),('1851095459'),('1861147647'),('1871241398'),('1871248658'),('1881327328'),('1881334894'),('1891467148'),('1922715606'),('1922730175'),('1922975440'),('1932791761'),('1932854718'),('1932871191'),('1942923958'),('1942931415'),('1942974449'),('1952094062'),('1962156745'),('1972258747'),('1972322725'),('1982330338'),('1992370944'),('1992411763'),('1992445498'),('1992450225'),('1992674667')),
og(org) AS (SELECT * FROM VALUES ('5 STAR HOSPICE AND PALLIATIVE CARE INC'),('AAA CARE HOSPICE INC'),('ABC HOSPICE AND PALLIATIVE CARE INC'),('ACCESS AZ HOSPICE & PALLIATIVE CARE, LLC'),('AGAPE HOSPICE OF NEVADA INC'),('AGL HOSPICE INC'),('ALA HOSPICE CARE, INC.'),('ALGA HOSPICE CARE INC'),('ALL HEARTS HOSPICE CARE'),('ALL HEARTS HOSPICE CARE LLC'),('ALL TIME HOSPICE CARE INC'),('ALLEVIATE CARE HOSPICE INC'),('ALPHA PALLIATIVE HEALTH SERVICES , LLC'),('AMAYA HOSPICE LLC'),('AMBASSADORE HEALTH CARE HOUSTON, INC.'),('AMBASSADORE HOSPICE OF RENO, LLC.'),('AMERICADE PALLIATIVE HEALTH SERVICES, LLC'),('AMERICAN HOSPICE PROVIDER CORPORATION'),('ANA HOSPICE CARE INC'),('ANGELS TOUCH HOSPICE AND PALLIATIVE CARE LLC'),('ANGELS TOUCH HOSPICE INC'),('APOLLO HOSPICE & PALLIATIVE CARE INC.'),('ARM CARE HOSPICE INC'),('ASAP HOSPICE AND PALLIATIVE CARE INC'),('ASPIRE HEALTH INC'),('AURORA HOSPICE INC'),('AURORA HOSPICE, LLC.'),('AUTUMN LIGHT HOSPICE CARE LLC'),('AVA HOSPICE CARE INC'),('AVRA HOSPICE CARE INC'),('AZ HOSPICE INC.'),('BEST CARE HOSPICE INC'),('BLUE RIBBON HOSPICE INC'),('BLUE WINGS HOSPICE INC'),('BPR HEALTH INC'),('BRIGHT STAR HOSPICE CARE INC'),('BUTTERFLIES HOSPICE INC'),('CAPITAL HEALTH HOSPICE INC'),('CARE FROM THE HEART HOSPICE INC'),('CARE R US HOSPICE AND PALLIATIVE CARE INC.'),('CIRCLE OF CARE HOSPICE LLC'),('CLEAR SOLUTIONS HOSPICE INC'),('COLORADO HOSPICE AND PALLIATIVE CARE LLC'),('COMFORTING HANDS HOSPICE'),('COMMUNITY CARE HOSPICE'),('COMMUNITY CARE HOSPICE INC'),('COMMUNITY HOSPICE, INC.'),('CP LUBBOCK TX HOSPICE LLC'),('CP MEDFORD OR HOSPICE, LLC'),('DDD HOSPICE INC'),('DESERT BREEZE HOSPICE'),('DIGNITY CARE HOSPICE INC'),('DOVE OF PEACE HOSPICE CARE CORP.'),('EAST COAST HOSPICE INC.'),('ELDERCARE HEALTHCARE SERVICES LLC'),('ELITE HOSPICE SERVICES INC.'),('EMELITA HOSPICE CARE INC'),('ETERNITY PALLIATIVE CARE LLC'),('EVERLAST HOSPICE CARE SERVICES INC'),('FAMILY CHOICE PALLIATIVE & HOSPICE CARE, LLC'),('FAMILY COMFORT CARE LLC'),('FAMILY FIRST HOSPICE INC'),('FIRST COMFORT HOSPICE INC'),('FIRST LIGHT HOSPICE CARE INC'),('FIRST WAY HOSPICE CARE INC'),('FULL HEARTS HOSPICE CARE LLC'),('GEISS MED HOSPICE AZ LLC'),('GENTLE HANDS HOSPICE INC.'),('GENTLE HANDS HOSPICE, P.C.'),('GOLDEN HARMONY CARE SERVICES, INC.'),('GOLDEN HEART HOSPICE INC'),('GOLDEN HOSPICE CARE INC'),('GOLDEN PHOENIX HOSPICE CARE LLC'),('GOLDEN ROSE HOSPICE INC'),('GOLDEN TOUCH HOSPICE INC'),('GOLDEN YEARS HOSPICE INC'),('GROM HOSPICE INC'),('GUIDING LIGHT HOSPICE CARE INC'),('HARVEST PALLIATIVE HOSPICE CARE INC'),('HAVE FAITH HOSPICE SERVICES INC'),('HEALING ANGELS HOSPICE CARE INC'),('HEAVEN N SOUL HOSPICE INC'),('HEAVENLY ANGEL HOSPICE LLC'),('HELPING ANGELS HOSPICE INC'),('HOLDING HANDS HOSPICE CARE INC'),('HOME LIFE HOSPICE CARE INC'),('HOPEFUL PALLIATIVE AND HOSPICE CARE INC'),('HOSPICE AND PALLIATIVE CARE OF NEVADA INC'),('HOSPICE AT HEART TO HEART INC'),('HOSPICE OF BOISE INC'),('HOSPICE OF IDAHO INC'),('HOSPICE OF PHOENIX INC'),('INFINITE PEACE HOSPICE LLC'),('JA HOSPICE INC'),('KIND HEARTS HOSPICE, INC.'),('KINDORA HOSPICE INC'),('LAKEWOOD HOSPICE AND PALLIATIVE CARE INC'),('LAS VEGAS HOSPICE & PALLIATIVE CARE, P.C.'),('LEGEND HOSPICE INC'),('LIFE''S TREASURES HOSPICE CARE PLLC'),('LS HOSPICE CARE INC'),('LUMINOUS HOSPICE CARE INC'),('LV HOSPICE AND PALLIATIVE CARE INC'),('MAJESTIC HOSPICE, INC.'),('MARIPOSA HOSPICE LLC'),('MAV HOSPICE CARE INC'),('MD CARE HOSPICE INC'),('MD CHOICE HOSPICE CARE INC'),('MD CHOICE HOSPICE INC'),('MD CHOICE HOSPICE OF ALASKA INC'),('MEDEX HOSPICE INC'),('MIRACLE HOSPICE CARE, INC.'),('MND HEALTH SERVICES INC'),('NEW BEGINNINGS HOSPICE INC.'),('NEW HAVEN HOSPICE LLC'),('NEW HOPE HOSPICE'),('NEW HOPE HOSPICE CARE INC'),('NIKO HEALTHCARE SERVICES, LLC'),('NM HEALTH SERVICES INC'),('NP HOSPICE CARE INC'),('NURSES CARE HOSPICE LLC'),('OAK HOSPICE CARE, INC.'),('OASIS CARE SERVICES, INC.'),('OXNARD HOSPICE INC'),('PAHUA HEALTH INC'),('PEACE OF MIND HOSPICE CARE INC'),('PEACEFUL TRANSITION HOSPICE INC'),('PHOENIX HEART HOSPICE LLC'),('PLATINUM PALLIATIVE HOSPICE CARE INC'),('PLEASANT CARE HOSPICE INC'),('POCONO MOUNTAINS PALLIATIVE HOSPICE & HOMEHEALTH CARE INC'),('PRECIOUS CARE HOSPICE INC.'),('PRIME HEALTHCARE HOME CARE AND HOSPICE, LLC'),('PRIME HEALTHCARE HOSPICE AND PALLIATIVE CARE LLC'),('PURE TOUCH HOSPICE CARE INC'),('S AND L HOSPICE CARE INC'),('SAINT CARE HOSPICE INC'),('SANTA CLARA HOSPICE INC'),('SENIOR SAFE HOSPICE INC'),('SERENITY HOSPICE SERVICES INC'),('SERENITY OF HOPE SERVICES, INC.'),('SHAHEN HOSPICE CARE SERVICES INC'),('SILVER CREEK HOSPICE LLC'),('SILVER LINING HOSPICE & PALLIATIVE CARE INC.'),('SINGLE STOP PALLIATIVE HOSPICE INC'),('SOURCEONE HOSPICE & PALLIATIVE CARE, LLC'),('SOUTHERN COMFORT HOSPICE CARE INC'),('SPARKS HOSPICE CARE LLC'),('SPRING VALLEY HOSPICE'),('ST. RITA HOSPICE INC'),('STAR HOSPICE INC'),('SUN GARDEN HOSPICE LLC'),('SUPREME CARE HOSPICE INC'),('THOUSAND OAKS HOSPICE CARE INC'),('THOUSAND OAKS HOSPICE OF TEXAS INC'),('TRIFINITY HOSPICE'),('TRIFINITY HOSPICE AND PALLIATIVE CARE LLC'),('TZ HOLDINGS LLC'),('UNIQUE CARE HOSPICE INC'),('URGENT CARE HOSPICE'),('VICTORIA HOSPICE CARE INC'),('VIDA CARE HOSPICE LLC'),('VOYAGER HOSPICE INC'),('WARM SPRINGS CARE SERVICES, INC.'),('WE CARE HOSPICE INC'),('WE CARE PALLIATIVE AND HOSPICE INC'),('WELL CARE HOSPICE INC'),('WINTERHAVEN HOSPICE, LLC'),('WITH LOVE HOSPICE INC'),('YNA HOSPICE INC'),('ZA HOSPICE INC'),('ZENITH HOSPICE CARE INC'),('ZION HOSPICE'),('ZION HOSPICE AND PALLIATIVE CARE LLC'),('ZOGRABI HEALTH SERVICES INC'))
SELECT 'LEIE person' src, l.FIRST_NAME || ' ' || l.LAST_NAME who, l.CITY, l.STATE, TO_VARCHAR(l.EXCLUSION_DATE) d, l.EXCLUSION_TYPE t, l.GENERAL_CATEGORY || ' / ' || COALESCE(l.SPECIALTY,'') extra
FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_HHS_OIG_LEIE l JOIN ao ON UPPER(TRIM(l.FIRST_NAME)) = ao.fn AND UPPER(TRIM(l.LAST_NAME)) = ao.ln
UNION ALL
SELECT 'LEIE npi or org', COALESCE(l.BUSINESS_NAME, l.LAST_NAME), l.CITY, l.STATE, TO_VARCHAR(l.EXCLUSION_DATE), l.EXCLUSION_TYPE, l.NPI
FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_HHS_OIG_LEIE l
WHERE l.NPI IN (SELECT npi FROM np) OR UPPER(TRIM(l.BUSINESS_NAME)) IN (SELECT org FROM og)
UNION ALL
SELECT 'SAM person', s.FIRST_NAME || ' ' || s.LAST_NAME, s.CITY, s.STATE, TO_VARCHAR(s.ACTIVATION_DATE), s.EXCLUSION_TYPE, s.EXCLUDING_AGENCY
FROM LIBRARY_MARTS.PROCUREMENT.PROCUREMENT__FED_SAM_EXCLUSIONS s JOIN ao ON UPPER(TRIM(s.FIRST_NAME)) = ao.fn AND UPPER(TRIM(s.LAST_NAME)) = ao.ln
UNION ALL
SELECT 'SAM org', s.ENTITY_NAME, s.CITY, s.STATE, TO_VARCHAR(s.ACTIVATION_DATE), s.EXCLUSION_TYPE, s.EXCLUDING_AGENCY
FROM LIBRARY_MARTS.PROCUREMENT.PROCUREMENT__FED_SAM_EXCLUSIONS s WHERE UPPER(TRIM(s.ENTITY_NAME)) IN (SELECT org FROM og);

-- S18 MDS harm check: abuse and neglect citations (F600 F602 F607 F609 F610) per home, Reliant vs other Missouri 40%+ schizophrenia homes vs the rest
WITH sz AS (
  SELECT CCN, MAX(OVERALL_PERCENT) pct
  FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_FACILITY_LEVEL_MINIMUM_DATA_SET_FREQUENCY
  WHERE MDS_ITEM_QUESTION_DESCRIPTION LIKE 'I6000:%' AND MDS_ITEM_RESPONSE = 'Yes' GROUP BY 1),
g AS (
  SELECT nh.CMS_CERTIFICATION_NUMBER_CCN ccn,
         CASE WHEN nh.CHAIN_NAME = 'RELIANT CARE MANAGEMENT' THEN 'Reliant' WHEN sz.pct >= 40 THEN 'MO other 40%+' ELSE 'MO rest' END grp
  FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_NURSING_HOME nh LEFT JOIN sz ON sz.CCN = nh.CMS_CERTIFICATION_NUMBER_CCN
  WHERE nh.STATE = 'MO'),
d AS (
  SELECT CMS_CERTIFICATION_NUMBER_CCN ccn, TRY_TO_NUMBER(REGEXP_SUBSTR(DEFICIENCY_TAG_NUMBER, '[0-9]+')) tag, SCOPE_SEVERITY_CODE ss, SURVEY_DATE
  FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_NURSING_HOME_DEFICIENCIES WHERE STATE = 'MO')
SELECT g.grp, COUNT(DISTINCT g.ccn) homes, COUNT(d.ccn) all_citations,
       COUNT_IF(d.tag IN (600, 602, 607, 609, 610)) abuse_neglect_cites,
       COUNT_IF(d.tag IN (600, 602, 607, 609, 610) AND d.ss IN ('G','H','I','J','K','L')) abuse_harm_or_jeopardy,
       COUNT_IF(d.ss IN ('J','K','L')) immediate_jeopardy_all_tags,
       COUNT(DISTINCT IFF(d.tag IN (600, 602, 607, 609, 610), d.ccn, NULL)) homes_with_abuse_cite,
       MIN(d.SURVEY_DATE) s0, MAX(d.SURVEY_DATE) s1
FROM g LEFT JOIN d ON d.ccn = g.ccn
GROUP BY 1 ORDER BY 1;

-- S19 Second-field check on the one exclusion-list hit: OIG row for ALMA INIT vs any NPPES person of that name
SELECT 'LEIE' src, l.FIRST_NAME || ' ' || COALESCE(l.MIDDLE_NAME || ' ', '') || l.LAST_NAME who, l.ADDRESS addr, l.CITY city, l.STATE st, l.ZIP zip,
       l.NPI npi, TO_VARCHAR(l.EXCLUSION_DATE) d, l.EXCLUSION_TYPE || ' / ' || COALESCE(l.GENERAL_CATEGORY, '') || ' / ' || COALESCE(l.SPECIALTY, '') info
FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_HHS_OIG_LEIE l
WHERE UPPER(TRIM(l.LAST_NAME)) = 'INIT'
UNION ALL
SELECT 'NPPES person', n.PROVIDER_FIRST_NAME || ' ' || COALESCE(n.PROVIDER_MIDDLE_NAME || ' ', '') || n.PROVIDER_LAST_NAME_LEGAL_NAME,
       n.PROVIDER_FIRST_LINE_BUSINESS_PRACTICE_LOCATION_ADDRESS, n.PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_CITY_NAME,
       n.PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_STATE_NAME, n.PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_POSTAL_CODE, n.NPI,
       TO_VARCHAR(n.PROVIDER_ENUMERATION_DATE), COALESCE(n.PROVIDER_CREDENTIAL_TEXT, '') || ' / ' || COALESCE(n.HEALTHCARE_PROVIDER_TAXONOMY_CODE_1, '')
FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_NPPES n
WHERE n.ENTITY_TYPE_CODE = '1' AND UPPER(TRIM(n.PROVIDER_LAST_NAME_LEGAL_NAME)) = 'INIT' AND UPPER(TRIM(n.PROVIDER_FIRST_NAME)) = 'ALMA'
UNION ALL
SELECT 'NPPES hospice org', n.PROVIDER_ORGANIZATION_NAME_LEGAL_BUSINESS_NAME, n.PROVIDER_FIRST_LINE_BUSINESS_PRACTICE_LOCATION_ADDRESS,
       n.PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_CITY_NAME, n.PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_STATE_NAME,
       n.PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_POSTAL_CODE, n.NPI, TO_VARCHAR(n.PROVIDER_ENUMERATION_DATE) || ' upd ' || TO_VARCHAR(n.LAST_UPDATE_DATE),
       n.AUTHORIZED_OFFICIAL_FIRST_NAME || ' ' || n.AUTHORIZED_OFFICIAL_LAST_NAME || ' ' || COALESCE(n.AUTHORIZED_OFFICIAL_TITLE_OR_POSITION, '') || ' ' || COALESCE(n.AUTHORIZED_OFFICIAL_TELEPHONE_NUMBER, '')
FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_NPPES n
WHERE n.NPI IN ('1922730175', '1558037887');
