-- deep3/g10: deep pass 3 hand-queries, 2026-09-24
-- Tables: HEALTH__FED_CMS_LTCH, HEALTH__FED_CMS_MARKETPLACE_PLAN_ATTRIBUTES_PUF, HEALTH__XC_OWID_LIFE_EXPECTANCY,
--         HEALTH__FED_CDC_ANXIETY_DEPRESSION, HEALTH__FED_CDC_HEALTH_INSURANCE
-- Door: Python (connect/db.py). Every connection first ran:
--   ALTER SESSION SET STATEMENT_TIMEOUT_IN_SECONDS = 300;
--   ALTER SESSION SET QUERY_TAG = 'deep3-2026-09-24';
-- Read-only: SELECT / WITH only. Numbered statements below count against the 35 budget.

-- Q1: [save:ltch] LTCH, whole table (311 rows), pulled once and analysed locally
SELECT * FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_LTCH;

-- Q2: [save:owid] OWID life expectancy, whole table (21.6K rows)
SELECT ENTITY, CODE, YEAR, LIFE_EXPECTANCY FROM LIBRARY_MARTS.HEALTH.HEALTH__XC_OWID_LIFE_EXPECTANCY;

-- Q3: [save:anx] CDC Pulse anxiety/depression, whole table (16.8K rows)
SELECT * FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CDC_ANXIETY_DEPRESSION;

-- Q4: [save:ins] CDC Pulse health insurance, whole table (16.1K rows)
SELECT * FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CDC_HEALTH_INSURANCE;

-- Q5: [save:mkt] 2026 marketplace plan attributes, 22.1K rows, the cost-sharing and identity columns
SELECT BUSINESSYEAR, STATECODE, ISSUERID, ISSUERMARKETPLACEMARKETINGNAME, SOURCENAME, IMPORTDATE, MARKETCOVERAGE, DENTALONLYPLAN,
       STANDARDCOMPONENTID, PLANMARKETINGNAME, HIOSPRODUCTID, NETWORKID, SERVICEAREAID, FORMULARYID, ISNEWPLAN, PLANTYPE, METALLEVEL,
       DESIGNTYPE, UNIQUEPLANDESIGN, QHPNONQHPTYPEID, ISREFERRALREQUIREDFORSPECIALIST, PLANLEVELEXCLUSIONS, CHILDONLYOFFERING,
       EHBPERCENTTOTALPREMIUM, PLANEFFECTIVEDATE, PLANEXPIRATIONDATE, OUTOFCOUNTRYCOVERAGE, OUTOFSERVICEAREACOVERAGE, NATIONALNETWORK,
       PLANID, PLANVARIANTMARKETINGNAME, CSRVARIATIONTYPE, ISSUERACTUARIALVALUE, AVCALCULATOROUTPUTNUMBER,
       MEDICALDRUGDEDUCTIBLESINTEGRATED, MEDICALDRUGMAXIMUMOUTOFPOCKETINTEGRATED, MULTIPLEINNETWORKTIERS,
       SBCHAVINGABABYDEDUCTIBLE, SBCHAVINGABABYCOPAYMENT, SBCHAVINGABABYCOINSURANCE, SBCHAVINGABABYLIMIT,
       SBCHAVINGDIABETESDEDUCTIBLE, SBCHAVINGDIABETESCOPAYMENT, SBCHAVINGDIABETESCOINSURANCE, SBCHAVINGDIABETESLIMIT,
       SBCHAVINGSIMPLEFRACTUREDEDUCTIBLE, SBCHAVINGSIMPLEFRACTURECOPAYMENT, SBCHAVINGSIMPLEFRACTURECOINSURANCE,
       SPECIALTYDRUGMAXIMUMCOINSURANCE, ISHSAELIGIBLE, CHILDONLYPLANID,
       MEHBINNTIER1_INDIVIDUALMOOP, TEHBINNTIER1_INDIVIDUALMOOP, TEHBINNTIER1_FAMILYPERGROUPMOOP, TEHBINNTIER1_FAMILYPERPERSONMOOP,
       TEHBOUTOFNETINDIVIDUALMOOP, TEHBCOMBINNOONINDIVIDUALMOOP,
       MEHBDEDINNTIER1_INDIVIDUAL, MEHBDEDINNTIER1_FAMILYPERGROUP, MEHBDEDINNTIER1_COINSURANCE,
       DEHBDEDINNTIER1_INDIVIDUAL, DEHBDEDINNTIER1_FAMILYPERGROUP,
       TEHBDEDINNTIER1_INDIVIDUAL, TEHBDEDINNTIER1_FAMILYPERGROUP, TEHBDEDINNTIER1_FAMILYPERPERSON, TEHBDEDINNTIER1_COINSURANCE,
       TEHBDEDOUTOFNETINDIVIDUAL
FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_MARKETPLACE_PLAN_ATTRIBUTES_PUF;

-- Q6: [save:hcris_ltch] every Medicare cost report filed under an LTCH CCN (HCRIS type LTCH, or CCN digits 3-6 in 2000-2299, or on today's LTCH list)
SELECT PROVIDER_CCN, RPT_REC_NUM, HOSPITAL_NAME, CITY, STATE_CODE, CCN_FACILITY_TYPE, PROVIDER_TYPE, TYPE_OF_CONTROL,
       FISCAL_YEAR_BEGIN_DATE, FISCAL_YEAR_END_DATE, SOURCE_FILE_YEAR, FISCAL_YEAR_LENGTH_DAYS,
       NUMBER_OF_BEDS, TOTAL_BED_DAYS_AVAILABLE, TOTAL_DAYS_TITLE_XVIII, TOTAL_DAYS_TITLE_XIX, TOTAL_DAYS_ALL,
       TOTAL_DISCHARGES_TITLE_XVIII, TOTAL_DISCHARGES_TITLE_XIX, TOTAL_DISCHARGES_ALL, OCCUPANCY_RATE, FTE_EMPLOYEES_ON_PAYROLL,
       COST_OF_CHARITY_CARE, TOTAL_BAD_DEBT_EXPENSE, TOTAL_SALARIES_FROM_WORKSHEET_A, CONTRACT_LABOR_DIRECT_PATIENT_CARE, TOTAL_COSTS,
       INPATIENT_TOTAL_CHARGES, COST_TO_CHARGE_RATIO, TOTAL_ASSETS, TOTAL_FUND_BALANCES, CASH_ON_HAND_AND_IN_BANKS,
       TOTAL_PATIENT_REVENUE, NET_PATIENT_REVENUE, TOTAL_OPERATING_EXPENSE, NET_INCOME_FROM_SERVICE_TO_PATIENTS, TOTAL_OTHER_INCOME,
       TOTAL_INCOME, NET_INCOME, NET_MARGIN_RATIO, OUTLIER_PAYMENTS_FOR_DISCHARGES, NET_REVENUE_FROM_MEDICAID
FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_HCRIS
WHERE CCN_FACILITY_TYPE = 'LTCH'
   OR SUBSTR(PROVIDER_CCN, 3, 4) BETWEEN '2000' AND '2299'
   OR PROVIDER_CCN IN (SELECT CCN FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_LTCH);

-- Q7: [save:pos_ltch] Medicare provider-of-services roster rows under LTCH CCNs, including terminated ones
SELECT CCN, FAC_NAME, ST_ADR, CITY_NAME, STATE_CD, ZIP_CD, PRVDR_CTGRY_CD, PRVDR_CTGRY_SBTYP_CD, CRTFCTN_DT, ORGNL_PRTCPTN_DT,
       PGM_TRMNTN_CD, TRMNTN_EXPRTN_DT, CHOW_CNT, CHOW_DT, CHOW_PRIOR_DT, GNRL_CNTL_TYPE_CD, BED_CNT, CRTFD_BED_CNT,
       SKLTN_REC_SW, CROSS_REF_PROVIDER_NUMBER, CMPLNC_STUS_CD
FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_POS_OTHER
WHERE SUBSTR(CCN, 3, 4) BETWEEN '2000' AND '2299'
   OR CCN IN (SELECT CCN FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_LTCH);

-- Q8: [save:enr_ltch] Medicare enrollment rows for today's LTCH CCNs: the legal owner name, to check the brand-name chain grouping with a second field
SELECT CCN, ENROLLMENT_ID, ASSOCIATE_ID, ORGANIZATION_NAME, DOING_BUSINESS_AS_NAME, INCORPORATION_STATE, ORGANIZATION_TYPE_STRUCTURE,
       PROPRIETARY_NONPROFIT, CITY, STATE, SUBGROUP_LONG_TERM
FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_HOSPITAL_ENROLLMENTS
WHERE CCN IN (SELECT CCN FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_LTCH);

-- Local analysis of the pulled rows (no further SQL): scripts in g10/
--   ltch_an.py .. ltch_an5.py  LTCH x HCRIS x POS: closures, same-hospital panel, Kindred vs peers
--   mkt_an.py                  marketplace deductibles, out-of-pocket cap, state and issuer medians
--   ins_an.py                  Pulse uninsured, Jan-Mar vs Aug-Oct windows, 2022 placebo
-- Total: 8 statements of the 35 budget.
