-- deep3/g14: deep pass 3 hand-queries, 2026-09-24
-- Tables: POLITICS__CA_LOBBY_CHG_LOG, POLITICS__MEMBER_BILL_RECORD, POLITICS__MEMBER_VOTING_RECORD,
--         POLITICS__FED_FEC_API, POLITICS__CA_LOBBY_FIRM
-- Door: Python (connect/db.py). Every connection first ran:
--   ALTER SESSION SET STATEMENT_TIMEOUT_IN_SECONDS = 300;
--   ALTER SESSION SET QUERY_TAG = 'deep3-2026-09-24';
-- Read-only: SELECT / WITH only. Numbered statements below count against the 35 budget.

-- Q1: [save:vote] member voting record, whole table (1,105 rows)
SELECT * FROM LIBRARY_MARTS.POLITICS.POLITICS__MEMBER_VOTING_RECORD;

-- Q2: [save:bill] member bill record, whole table (1,104 rows)
SELECT * FROM LIBRARY_MARTS.POLITICS.POLITICS__MEMBER_BILL_RECORD;

-- Q3: [save:fec] FEC API sample, whole table (500 rows)
SELECT * FROM LIBRARY_MARTS.POLITICS.POLITICS__FED_FEC_API;

-- Q4: [save:firm] CA lobbying firm totals, whole table (256 rows)
SELECT * FROM LIBRARY_MARTS.POLITICS.POLITICS__CA_LOBBY_FIRM;

-- Q5: [save:chg] CA lobbying registration change log, whole table (85.8K rows)
SELECT * FROM LIBRARY_MARTS.POLITICS.POLITICS__CA_LOBBY_CHG_LOG;

-- Q6: [save:fecid] member-to-FEC-candidate-ID bridge, whole table
SELECT * FROM LIBRARY_MARTS.POLITICS.POLITICS__MEMBER_FEC_ID;

-- Q7: [save:fcand] FEC Senate and President candidates, 2024 and 2026 cycles, with money raised
SELECT c.CAND_ID, c.CYCLE, c.CAND_NAME, c.INCUMBENT_CHALLENGER, c.CAND_STATUS, c.CAND_ELECTION_YR, c.PARTY, c.OFFICE, c.OFFICE_STATE,
       s.TTL_RECEIPTS, s.TTL_DISB, s.COVERAGE_END_DATE
FROM LIBRARY_MARTS.POLITICS.POLITICS__FEC_CANDIDATE c
LEFT JOIN LIBRARY_MARTS.POLITICS.POLITICS__FEC_CANDIDATE_SUMMARY s ON s.CAND_ID = c.CAND_ID AND s.CYCLE = c.CYCLE
WHERE c.OFFICE IN ('S','P');

-- Q8: [save:vvmonth] Voteview individual votes rolled to member-month: votes, not-voting, present, code-0, unmatched dates
WITH r AS (
  SELECT CONGRESS, UPPER(CHAMBER) AS CH, TRY_TO_NUMBER(TO_VARCHAR(ROLLNUMBER)) AS RN,
         DATE_TRUNC('month', TRY_TO_DATE(LEFT(TO_VARCHAR(VOTE_DATE),10))) AS MON
  FROM LIBRARY_MARTS.POLITICS.POLITICS__VOTEVIEW_ROLLCALLS
  WHERE CONGRESS IN (118,119)
)
SELECT v.CONGRESS, UPPER(v.CHAMBER) AS CH, v.ICPSR, r.MON,
       COUNT(*) AS N, SUM(IFF(v.CAST_CODE IN (9), 1, 0)) AS NV, SUM(IFF(v.CAST_CODE IN (7,8), 1, 0)) AS PRES,
       SUM(IFF(v.CAST_CODE = 0, 1, 0)) AS C0, SUM(IFF(r.RN IS NULL, 1, 0)) AS NO_RC
FROM LIBRARY_MARTS.POLITICS.POLITICS__VOTEVIEW_VOTES v
LEFT JOIN r ON r.CONGRESS = v.CONGRESS AND r.CH = UPPER(v.CHAMBER) AND r.RN = TRY_TO_NUMBER(TO_VARCHAR(v.ROLLNUMBER))
GROUP BY 1,2,3,4;

-- Q9: bills, 118th Congress: how "advanced past committee" lines up with the latest stage, House vs Senate bills
SELECT BILL_TYPE, LATEST_STAGE, ADVANCED_PAST_COMMITTEE, COUNT(*) AS N,
       SUM(IFF(SPONSOR_BIOGUIDE = 'B001302', 1, 0)) AS BIGGS
FROM LIBRARY_MARTS.POLITICS.POLITICS__BILLS
WHERE CONGRESS = 118 AND BILL_TYPE IN ('HR','S')
GROUP BY 1,2,3 ORDER BY 1,2,3;

-- Q10: bills flagged advanced but stuck at committee_action: the top latest-action texts, 118th House bills
SELECT LEFT(LATEST_ACTION_TEXT, 90) AS ACT, COUNT(*) AS N, SUM(IFF(SPONSOR_BIOGUIDE = 'B001302', 1, 0)) AS BIGGS
FROM LIBRARY_MARTS.POLITICS.POLITICS__BILLS
WHERE CONGRESS = 118 AND BILL_TYPE = 'HR' AND ADVANCED_PAST_COMMITTEE = TRUE
GROUP BY 1 ORDER BY 2 DESC LIMIT 25;

-- Q11: 118th Congress bills flagged "advanced past committee": what the latest action actually was, House vs Senate bills
SELECT BILL_TYPE,
       CASE WHEN LATEST_ACTION_TEXT ILIKE 'Referred to the Subcommittee%' THEN '1 sent to a subcommittee, nothing after'
            WHEN LATEST_ACTION_TEXT ILIKE 'Subcommittee Hearings Held%' THEN '2 subcommittee hearing'
            WHEN LATEST_STAGE = 'committee_action' THEN '3 other committee action'
            WHEN LATEST_STAGE = 'reached_floor' THEN '4 reached floor'
            ELSE '5 ' || LATEST_STAGE END AS WHAT,
       COUNT(*) AS N, SUM(IFF(SPONSOR_BIOGUIDE = 'B001302', 1, 0)) AS BIGGS
FROM LIBRARY_MARTS.POLITICS.POLITICS__BILLS
WHERE CONGRESS = 118 AND BILL_TYPE IN ('HR','S') AND ADVANCED_PAST_COMMITTEE = TRUE
GROUP BY 1, 2 ORDER BY 1, 2;

-- Q12: Andy Biggs's 118th-Congress bills (B001302): first five words of the title, count, first and last introduced date
SELECT REGEXP_SUBSTR(TITLE, '^(\S+\s+){0,4}\S+') AS FIRST_WORDS, COUNT(*) AS N,
       MIN(INTRODUCED_DATE) AS FIRST_DT, MAX(INTRODUCED_DATE) AS LAST_DT, MAX(N_COSPONSORS) AS MAX_COSP,
       ANY_VALUE(LEFT(TITLE, 140)) AS EXAMPLE
FROM LIBRARY_MARTS.POLITICS.POLITICS__BILLS
WHERE CONGRESS = 118 AND SPONSOR_BIOGUIDE = 'B001302'
GROUP BY 1 ORDER BY 2 DESC LIMIT 20;

-- Q13: CA lobbying firms (2001 session table) vs their own filings in the cover table: did the firms with $0 in Q1-Q2 2002 file for those quarters?
WITH f AS (
  SELECT FIRM_ID, IFF(QTR_5 = 0 AND QTR_6 = 0 AND QTR_7 > 0, 'Q1-Q2 2002 zero', 'other') AS GRP
  FROM LIBRARY_MARTS.POLITICS.POLITICS__CA_LOBBY_FIRM
), c AS (
  SELECT TRY_TO_NUMBER(TO_VARCHAR(FILER_ID)) AS FID, FORM_TYPE, FILING_ID,
         COALESCE(TRY_TO_DATE(LEFT(TO_VARCHAR(FROM_DATE), 10)),
                  TRY_TO_DATE(SPLIT_PART(TO_VARCHAR(FROM_DATE), ' ', 1), 'MM/DD/YYYY')) AS FD
  FROM LIBRARY_MARTS.POLITICS.POLITICS__CA_LOBBY_COVER
)
SELECT f.GRP, c.FORM_TYPE, YEAR(c.FD) || '-Q' || QUARTER(c.FD) AS QTR,
       COUNT(DISTINCT f.FIRM_ID) AS FIRMS, COUNT(DISTINCT c.FILING_ID) AS FILINGS,
       (SELECT COUNT(*) FROM f f2 WHERE f2.GRP = f.GRP) AS GRP_SIZE
FROM f JOIN c ON c.FID = f.FIRM_ID
WHERE YEAR(c.FD) BETWEEN 2001 AND 2002
GROUP BY 1, 2, 3 ORDER BY 1, 2, 3;

-- Q14: Andy Biggs's 118th-Congress bills: second source (GovInfo bill status) vs the Congress.gov bills table, count by bill type
SELECT 'govinfo' AS SRC, BILL_TYPE, COUNT(*) AS N, COUNT(DISTINCT BILL_NUMBER) AS NUMS, MIN(INTRODUCED_DATE) AS FIRST_DT, MAX(INTRODUCED_DATE) AS LAST_DT
FROM LIBRARY_MARTS.POLITICS.POLITICS__FED_GOVINFO_BILLSTATUS
WHERE CONGRESS = 118 AND SPONSOR_BIOGUIDE = 'B001302' GROUP BY 1, 2
UNION ALL
SELECT 'bills', BILL_TYPE, COUNT(*), COUNT(DISTINCT BILL_NUMBER), MIN(INTRODUCED_DATE)::VARCHAR, MAX(INTRODUCED_DATE)::VARCHAR
FROM LIBRARY_MARTS.POLITICS.POLITICS__BILLS
WHERE CONGRESS = 118 AND SPONSOR_BIOGUIDE = 'B001302' GROUP BY 1, 2;

-- Q15: Andy Biggs's 118th-Congress bills: introduced month and the most common title openings
SELECT TO_CHAR(TRY_TO_DATE(LEFT(TO_VARCHAR(INTRODUCED_DATE), 10)), 'YYYY-MM') AS MON, COUNT(*) AS N,
       COUNT(DISTINCT LEFT(TITLE, 25)) AS TITLE_OPENINGS, ANY_VALUE(LEFT(TITLE, 110)) AS EXAMPLE
FROM LIBRARY_MARTS.POLITICS.POLITICS__BILLS
WHERE CONGRESS = 118 AND SPONSOR_BIOGUIDE = 'B001302'
GROUP BY 1 ORDER BY 1;

-- End of warehouse statements: 15 used of 35.
-- Local analysis (no SQL) in g14/: runners.py, runners2.py (FEC name+state match, reviewed by eye),
--   vote_an.py (peer medians), month_an.py (Voteview rebuild check + monthly), month_an2.py, month_an3.py (windows).
-- Statement use by table: MEMBER_VOTING_RECORD Q1 Q6 Q7 Q8 (4); MEMBER_BILL_RECORD Q2 Q9 Q10 Q11 Q12 Q14 Q15 (7);
--   FED_FEC_API Q3 (1); CA_LOBBY_FIRM Q4 Q13 (2); CA_LOBBY_CHG_LOG Q5 (1).
