-- deep3/g24: deep pass 3, 2026-09-24. Python door (connect/db.py), read-only SELECT/WITH only, QUERY_TAG 'deep3-2026-09-24'.
-- Every connection first ran: ALTER SESSION SET STATEMENT_TIMEOUT_IN_SECONDS = 300; ALTER SESSION SET QUERY_TAG = 'deep3-2026-09-24'. Those two are not counted.
-- Tables: FINANCE__FED_IRS_SOI, FINANCE__FED_NCUA_FEDERALLY_INSURED_CU_LIST, FINANCE__FED_FDIC_BANK_DATA,
--         FINANCE__FED_EPA_ICIS_FEC_CASE_ENFORCEMENT_CONCLUSION_FACILITIES, FINANCE__FED_SEC_INSIDER_REPORTINGOWNER.
-- Partner tables read: NCUA FOICU, NCUA FS220, NCUA merger events, FDIC enforcement orders, FDIC failed banks, EPA ECHO,
--         SEC insider submission, SEC closed-end fund / BDC / investment-company lists, SEC DERA SUB 2024 Q1-Q4.
-- 24 statements (S01-S24), all below, in run order (batches b1-b5). S09, S10, S12, S15, S16, S18, S19 are extracts;
-- the peer, time and join math on them ran locally in pandas (scripts and outputs in g24/).

-- ===== batch b1 =====
-- S01 column names and types for the 5 tables plus the partner tables used for joins
SELECT table_schema, table_name, LISTAGG(column_name || ':' || LEFT(data_type,4), ', ') WITHIN GROUP (ORDER BY ordinal_position) cols
FROM LIBRARY_MARTS.INFORMATION_SCHEMA.COLUMNS
WHERE table_name IN ('FINANCE__FED_IRS_SOI','FINANCE__FED_NCUA_FEDERALLY_INSURED_CU_LIST','FINANCE__FED_FDIC_BANK_DATA',
  'FINANCE__FED_EPA_ICIS_FEC_CASE_ENFORCEMENT_CONCLUSION_FACILITIES','FINANCE__FED_SEC_INSIDER_REPORTINGOWNER',
  'FINANCE__FED_SEC_INSIDER_SUBMISSION','ENVIRONMENT__FED_EPA_ECHO','JUSTICE__FED_FDIC_ENFORCEMENT_ORDERS','ECONOMICS__FED_FDIC_FAILED_BANKS',
  'FINANCE__FED_NCUA_CALL_REPORTS_FOICU','FINANCE__FED_SEC_CLOSED_END_FUND_INFORMATION','FINANCE__FED_EPA_ICIS_FEC_CASE_FACILITIES',
  'FINANCE__FED_NCUA_CHARTER_MERGER_EVENTS','FINANCE__FED_SEC_INVESTMENT_COMPANY_SERIES_CLASS')
GROUP BY 1,2 ORDER BY 2
;

-- ===== batch b2 =====
-- S02 IRS SOI: rows by tax year and income bracket, state-total ZIPs (00000/99999), numeric parse failures, sums
SELECT TAX_YEAR, AGI_STUB, COUNT(*) n, COUNT(DISTINCT ZIP_CODE) zips, COUNT(DISTINCT STATE) states, COUNT(DISTINCT DATASET_NAME) dsn,
       COUNT_IF(ZIP_CODE = '00000') z00000, COUNT_IF(ZIP_CODE = '99999') z99999, COUNT_IF(LENGTH(ZIP_CODE) <> 5) zlen_bad,
       COUNT_IF(TRY_TO_DOUBLE(N_RETURNS) IS NULL) bad_n, SUM(TRY_TO_DOUBLE(N_RETURNS)) ret, SUM(TRY_TO_DOUBLE(WAGES_SALARIES)) wages_k,
       SUM(TRY_TO_DOUBLE(N_EITC)) n_eitc, SUM(TRY_TO_DOUBLE(EITC_AMOUNT)) eitc_k, SUM(TRY_TO_DOUBLE(PREP)) prep, SUM(TRY_TO_DOUBLE(RAL)) ral,
       SUM(TRY_TO_DOUBLE(RAC)) rac, SUM(TRY_TO_DOUBLE(TOTAL_VITA)) vita, SUM(TRY_TO_DOUBLE(ELDERLY)) elderly,
       COUNT(*) - COUNT(DISTINCT ZIP_CODE, STATE, AGI_STUB, TAX_YEAR) dup_keys
FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_IRS_SOI
GROUP BY ROLLUP(1,2) ORDER BY 1,2;

-- S03 NCUA list: capital, profit, lending and growth by charter type and low-income flag; sentinels
SELECT CREDIT_UNION_TYPE, LOW_INCOME_DESIGNATION, COUNT(*) n, COUNT(DISTINCT CHARTER_NUMBER) charters, COUNT(DISTINCT YEAR_AND_QUARTER) qtrs,
       SUM(TOTAL_ASSETS) assets, MEDIAN(TOTAL_ASSETS) med_assets, MEDIAN(MEMBERS) med_members,
       MEDIAN(NET_WORTH_RATIO_EXCLUDES_CECL_TRANSITION_PROVISION) med_nw, MIN(NET_WORTH_RATIO_EXCLUDES_CECL_TRANSITION_PROVISION) min_nw,
       MAX(NET_WORTH_RATIO_EXCLUDES_CECL_TRANSITION_PROVISION) max_nw,
       COUNT_IF(NET_WORTH_RATIO_EXCLUDES_CECL_TRANSITION_PROVISION < 7) nw_lt7, COUNT_IF(NET_WORTH_RATIO_EXCLUDES_CECL_TRANSITION_PROVISION < 6) nw_lt6,
       COUNT_IF(NET_WORTH_RATIO_EXCLUDES_CECL_TRANSITION_PROVISION < 4) nw_lt4, COUNT_IF(NET_WORTH_RATIO_EXCLUDES_CECL_TRANSITION_PROVISION IS NULL) nw_null,
       MEDIAN(RETURN_ON_AVERAGE_ASSETS) med_roa, COUNT_IF(RETURN_ON_AVERAGE_ASSETS < 0) roa_neg, COUNT_IF(LOAN_TO_SHARE_RATIO > 100) lts_gt100,
       COUNT_IF(MEMBERS_4_QUARTER_GROWTH < 0) mem_shrink, MEDIAN(MEMBERS_4_QUARTER_GROWTH) med_mem_g, MEDIAN(TOTAL_LOANS_4_QUARTER_GROWTH) med_loan_g,
       COUNT_IF(TOTAL_ASSETS IS NULL OR TOTAL_ASSETS = 0) assets0, COUNT_IF(MEMBERS IS NULL OR MEMBERS = 0) members0,
       COUNT_IF(TOTAL_LOANS > TOTAL_ASSETS) loans_gt_assets
FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_NCUA_FEDERALLY_INSURED_CU_LIST
GROUP BY ROLLUP(1,2) ORDER BY 1,2;

-- S04 FDIC bank data: open vs closed, report dates, fill, MDI, load runs; is this really a "sample"?
SELECT ACTIVE, COUNT(*) n, COUNT(DISTINCT CERT) certs, COUNT_IF(ASSET IS NULL) asset_null, SUM(ASSET) asset_k, MEDIAN(ASSET) med_asset_k,
       MIN(REPDTE) rep0, MAX(REPDTE) rep1, MODE(REPDTE) rep_mode, COUNT_IF(REPDTE = (SELECT MAX(REPDTE) FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_FDIC_BANK_DATA)) at_latest,
       MIN(ESTYMD) est0, MAX(ESTYMD) est1, MIN(ENDEFYMD) end0, MAX(ENDEFYMD) end1, COUNT_IF(ENDEFYMD IS NULL) end_null,
       COUNT_IF(NULLIF(TRIM(MDI_STATUS_CODE),'') IS NOT NULL AND MDI_STATUS_CODE NOT IN ('0','00')) mdi, COUNT(DISTINCT _SOURCE_RUN_ID) runs,
       MIN(DATEUPDT) upd0, MAX(DATEUPDT) upd1, COUNT_IF(IN_CONSERVATORSHIP = 'Y') conserv, COUNT_IF(INSURANCE_DROPPED_DATE IS NOT NULL) ins_dropped,
       COUNT(DISTINCT STALP) states, COUNT_IF(NETINC < 0) netinc_neg
FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_FDIC_BANK_DATA
GROUP BY ROLLUP(1) ORDER BY 1;

-- S05 FDIC join test: do failed banks and enforcement-order banks land in the bank directory by CERT?
WITH b AS (SELECT DISTINCT TRY_TO_NUMBER(CERT) cert, ACTIVE FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_FDIC_BANK_DATA),
f AS (SELECT TRY_TO_NUMBER(FDIC_CERT) cert, YEAR(FAIL_DATE) y FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_FDIC_FAILED_BANKS WHERE RESOLUTION_TYPE = 'FAILURE'),
e AS (SELECT DISTINCT CERT_NUMBER cert FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_FDIC_ENFORCEMENT_ORDERS WHERE CERT_NUMBER > 0)
SELECT 'failed_all' src, COUNT(*) n, COUNT_IF(cert IS NOT NULL AND cert > 0) with_cert, COUNT_IF(cert IN (SELECT cert FROM b)) landed FROM f
UNION ALL SELECT 'failed_2000_on', COUNT(*), COUNT_IF(cert > 0), COUNT_IF(cert IN (SELECT cert FROM b)) FROM f WHERE y >= 2000
UNION ALL SELECT 'orders_certs', COUNT(*), COUNT(*), COUNT_IF(cert IN (SELECT cert FROM b)) FROM e
UNION ALL SELECT 'orders_certs_active', COUNT(*), COUNT(*), COUNT_IF(cert IN (SELECT cert FROM b WHERE ACTIVE = '1')) FROM e;

-- S06 EPA conclusion-facility bridge: shape of IDs, case-number formats, duplicate rows, blanks
SELECT COUNT(*) n, COUNT(DISTINCT CASE_NUMBER) cases, COUNT(DISTINCT ENF_CONCLUSION_ID) conclusions, COUNT(DISTINCT ACTIVITY_ID) activities,
       COUNT(DISTINCT FACILITY_UIN) uins, COUNT(DISTINCT ICIS_FACILITY_INTEREST_ID) icis_ids,
       COUNT_IF(FACILITY_UIN IS NULL OR FACILITY_UIN IN ('','None')) uin_blank, COUNT_IF(REGEXP_LIKE(FACILITY_UIN, '^110[0-9]{9}$')) uin_ok,
       COUNT_IF(REGEXP_LIKE(CASE_NUMBER, '^[0-9]{2}-[0-9]{4}-[0-9]+$')) case_rr_yyyy, COUNT_IF(REGEXP_LIKE(CASE_NUMBER, '^HQ-[0-9]{4}-[0-9]+$')) case_hq,
       COUNT(*) - COUNT(DISTINCT ACTIVITY_ID, ENF_CONCLUSION_ID, FACILITY_UIN, ICIS_FACILITY_INTEREST_ID) dup_rows,
       COUNT(DISTINCT CASE_NUMBER, ENF_CONCLUSION_ID) case_concl_pairs,
       ARRAY_AGG(DISTINCT REGEXP_REPLACE(CASE_NUMBER, '[0-9]', '9')) WITHIN GROUP (ORDER BY REGEXP_REPLACE(CASE_NUMBER, '[0-9]', '9')) formats
FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_EPA_ICIS_FEC_CASE_ENFORCEMENT_CONCLUSION_FACILITIES;

-- S07 SEC reporting owner: link to submission by accession, filing years, doc types, duplicate owner rows
WITH r AS (SELECT ACCESSION_NUMBER, OWNER_CIK, RELATIONSHIP FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_INSIDER_REPORTINGOWNER),
s AS (SELECT ACCESSION_NUMBER, FILING_DATE, DOCUMENT_TYPE FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_INSIDER_SUBMISSION)
SELECT YEAR(s.FILING_DATE) y, COUNT(*) n, COUNT(DISTINCT r.ACCESSION_NUMBER) filings, COUNT(DISTINCT r.OWNER_CIK) owners,
       COUNT(*) - COUNT(DISTINCT r.ACCESSION_NUMBER, r.OWNER_CIK) dup_owner_rows, COUNT_IF(s.ACCESSION_NUMBER IS NULL) no_sub,
       COUNT_IF(s.DOCUMENT_TYPE = '4') f4, COUNT_IF(s.DOCUMENT_TYPE = '3') f3, COUNT_IF(s.DOCUMENT_TYPE = '5') f5,
       COUNT_IF(s.DOCUMENT_TYPE LIKE '%/A') amend, COUNT_IF(r.RELATIONSHIP ILIKE '%director%') dir_rows
FROM r LEFT JOIN (SELECT * FROM s QUALIFY ROW_NUMBER() OVER (PARTITION BY ACCESSION_NUMBER ORDER BY FILING_DATE) = 1) s USING (ACCESSION_NUMBER)
GROUP BY 1 ORDER BY 1
;

-- ===== batch b3 =====
-- S08 IRS SOI: what the short ZIP codes are; are state totals mixed in with ZIPs?
SELECT CASE WHEN ZIP_CODE IN ('0','00000') THEN 'zip_0_state_total' WHEN ZIP_CODE = '99999' THEN 'zip_99999_other'
            WHEN LENGTH(ZIP_CODE) = 5 THEN 'zip5' ELSE 'len' || LENGTH(ZIP_CODE) END kind,
       COUNT(*) n, COUNT(DISTINCT STATE) states, SUM(TRY_TO_DOUBLE(N_RETURNS)) ret, SUM(TRY_TO_DOUBLE(WAGES_SALARIES)) wages_k,
       MAX(TRY_TO_DOUBLE(WAGES_SALARIES)) max_wages_k, MIN(ZIP_CODE) z_min, MAX(ZIP_CODE) z_max,
       ARRAY_AGG(DISTINCT STATE) WITHIN GROUP (ORDER BY STATE) st
FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_IRS_SOI
GROUP BY 1 ORDER BY 1;

-- S09 IRS SOI: per-ZIP extract (real ZIPs only), low-income brackets 1-2 vs all, for local peer math
SELECT STATE, LPAD(ZIP_CODE, 5, '0') zip5,
       SUM(TRY_TO_DOUBLE(N_RETURNS)) ret_all, SUM(IFF(AGI_STUB IN ('1','2'), TRY_TO_DOUBLE(N_RETURNS), 0)) ret_low,
       SUM(IFF(AGI_STUB IN ('1','2'), TRY_TO_DOUBLE(RAC), 0)) rac_low, SUM(TRY_TO_DOUBLE(RAC)) rac_all, SUM(TRY_TO_DOUBLE(RAL)) ral_all,
       SUM(IFF(AGI_STUB IN ('1','2'), TRY_TO_DOUBLE(PREP), 0)) prep_low, SUM(IFF(AGI_STUB IN ('1','2'), TRY_TO_DOUBLE(TOTAL_VITA), 0)) vita_low,
       SUM(TRY_TO_DOUBLE(N_EITC)) n_eitc, SUM(TRY_TO_DOUBLE(EITC_AMOUNT)) eitc_k, SUM(TRY_TO_DOUBLE(AGI)) agi_k, SUM(TRY_TO_DOUBLE(WAGES_SALARIES)) wages_k,
       SUM(TRY_TO_DOUBLE(ELDERLY)) elderly
FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_IRS_SOI
WHERE ZIP_CODE NOT IN ('0', '00000', '99999')
GROUP BY 1, 2;

-- S10 NCUA list: full extract joined to the call-report roster (year opened, peer group, MDI) by charter number
SELECT l.*, f.CU_NUMBER f_cu, f.YEAR_OPENED, f.PEER_GROUP, f.ISMDI, f.LIMITED_INC, f.CU_NAME f_name, f.STATE f_state, f.INSURED_DATE f_insured
FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_NCUA_FEDERALLY_INSURED_CU_LIST l
LEFT JOIN LIBRARY_MARTS.FINANCE.FINANCE__FED_NCUA_CALL_REPORTS_FOICU f ON TRY_TO_NUMBER(f.CU_NUMBER) = TRY_TO_NUMBER(l.CHARTER_NUMBER);

-- S11 NCUA merger events: all 27, and whether the merging charter is still on the insured list
SELECT m.*, l.CHARTER_NUMBER still_listed, l.TOTAL_ASSETS listed_assets, l.NET_WORTH_RATIO_EXCLUDES_CECL_TRANSITION_PROVISION listed_nw
FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_NCUA_CHARTER_MERGER_EVENTS m
LEFT JOIN LIBRARY_MARTS.FINANCE.FINANCE__FED_NCUA_FEDERALLY_INSURED_CU_LIST l ON TRY_TO_NUMBER(l.CHARTER_NUMBER) = TRY_TO_NUMBER(m.MERGING_CREDIT_UNION_CHARTER);

-- S12 FDIC: active banks extract with FDIC enforcement orders aggregated by CERT (all time and since 2020)
WITH o AS (
  SELECT CERT_NUMBER cert, COUNT(*) orders_all, COUNT_IF(ORDER_DATE >= '2020-01-01') orders_2020,
         COUNT_IF(ORDER_DATE >= '2020-01-01' AND (ORDER_TYPE ILIKE '%cease%' OR ORDER_TITLE ILIKE '%consent%' OR ORDER_TITLE ILIKE '%cease%')) cd_2020,
         COUNT_IF(ORDER_DATE >= '2020-01-01' AND ORDER_TYPE ILIKE '%civil money%') cmp_2020,
         SUM(IFF(ORDER_DATE >= '2020-01-01', CMP_AMOUNT_TOTAL, 0)) cmp_amt_2020, MAX(ORDER_DATE) last_order,
         LISTAGG(DISTINCT IFF(ORDER_DATE >= '2020-01-01', ORDER_TYPE, NULL), ' | ') types_2020
  FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_FDIC_ENFORCEMENT_ORDERS WHERE CERT_NUMBER > 0 GROUP BY 1)
SELECT b.CERT, b.NAME, b.CITY, b.STALP, b.BKCLASS, b.CHRTAGNT, b.SPECGRP, b.CLCODE, b.ESTYMD, b.ASSET, b.DEP, b.DEPDOM, b.NETINC, b.REPDTE,
       b.OFFICES, b.OFFICES_DOMESTIC, b.MDI_STATUS_CODE, b.MDI_STATUS_DESC, b.HOLDING_COMPANY_NAME, b.FDIC_SUPERVISOR, b.CBSA_METRO_NAME,
       o.orders_all, o.orders_2020, o.cd_2020, o.cmp_2020, o.cmp_amt_2020, o.last_order, o.types_2020
FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_FDIC_BANK_DATA b LEFT JOIN o ON o.cert = TRY_TO_NUMBER(b.CERT)
WHERE b.ACTIVE = '1';

-- S13 EPA bridge: case-number year and prefix; cases, conclusions, facility rows, biggest conclusion per year
WITH t AS (SELECT CASE_NUMBER, ENF_CONCLUSION_ID, FACILITY_UIN, SPLIT_PART(CASE_NUMBER, '-', 1) pre, TRY_TO_NUMBER(SPLIT_PART(CASE_NUMBER, '-', 2)) yr
           FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_EPA_ICIS_FEC_CASE_ENFORCEMENT_CONCLUSION_FACILITIES),
c AS (SELECT yr, pre, ENF_CONCLUSION_ID, COUNT(*) fac FROM t GROUP BY 1, 2, 3)
SELECT yr, COUNT(*) conclusions, SUM(fac) fac_rows, COUNT_IF(pre = 'HQ') hq, COUNT_IF(pre IN ('EF','WF')) ef_wf,
       COUNT_IF(fac = 1) single_site, MAX(fac) max_sites, MEDIAN(fac) med_sites
FROM c GROUP BY 1 ORDER BY 1;

-- S14 EPA bridge: the top facilities by distinct cases, and the conclusions that cover the most sites
SELECT 'top_facility' kind, FACILITY_UIN id, ANY_VALUE(FACILITY_NAME) name, ANY_VALUE(FACILITY_CITY) city, ANY_VALUE(FACILITY_STATE) st,
       COUNT(DISTINCT CASE_NUMBER) cases, COUNT(*) n_rows, MIN(CASE_NUMBER) c_min, MAX(CASE_NUMBER) c_max, COUNT(DISTINCT FACILITY_NAME) names
FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_EPA_ICIS_FEC_CASE_ENFORCEMENT_CONCLUSION_FACILITIES
GROUP BY 2 QUALIFY ROW_NUMBER() OVER (ORDER BY COUNT(DISTINCT CASE_NUMBER) DESC) <= 40
UNION ALL
SELECT 'big_conclusion', ENF_CONCLUSION_ID, ANY_VALUE(FACILITY_NAME), ANY_VALUE(CASE_NUMBER), ANY_VALUE(FACILITY_STATE),
       COUNT(DISTINCT FACILITY_STATE), COUNT(*), MIN(FACILITY_NAME), MAX(FACILITY_NAME), COUNT(DISTINCT FACILITY_NAME)
FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_EPA_ICIS_FEC_CASE_ENFORCEMENT_CONCLUSION_FACILITIES
GROUP BY 2 QUALIFY ROW_NUMBER() OVER (ORDER BY COUNT(*) DESC) <= 20;

-- S15 EPA bridge x ECHO: per-facility case count joined to ECHO status by FRS registry ID (extract for local peer math)
WITH f AS (SELECT FACILITY_UIN, COUNT(DISTINCT CASE_NUMBER) cases, MAX(TRY_TO_NUMBER(SPLIT_PART(CASE_NUMBER, '-', 2))) last_case_yr,
                  MIN(TRY_TO_NUMBER(SPLIT_PART(CASE_NUMBER, '-', 2))) first_case_yr, ANY_VALUE(FACILITY_NAME) name, ANY_VALUE(FACILITY_STATE) st
           FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_EPA_ICIS_FEC_CASE_ENFORCEMENT_CONCLUSION_FACILITIES
           WHERE REGEXP_LIKE(FACILITY_UIN, '^110[0-9]{9}$') GROUP BY 1),
e AS (SELECT FRS_ID, COMPLIANCE_STATUS, QUARTERS_WITH_NONCOMPLIANCE, FORMAL_ACTION_COUNT, TOTAL_PENALTIES, IS_MAJOR_FACILITY, IS_ACTIVE,
             HAS_AIR_PROGRAM, HAS_WATER_PROGRAM, HAS_HAZWASTE_PROGRAM, TOTAL_INSPECTION_COUNT, PCT_MINORITY, FACILITY_NAME e_name, CITY e_city, STATE e_st
      FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ECHO QUALIFY ROW_NUMBER() OVER (PARTITION BY FRS_ID ORDER BY FORMAL_ACTION_COUNT DESC NULLS LAST) = 1)
SELECT f.*, e.* FROM f LEFT JOIN e ON e.FRS_ID = f.FACILITY_UIN;

-- S16 SEC insiders 2024: every (owner, issuer) pair on 2024 filings, with fund flags and the issuer's SIC from DERA 2024 filings
WITH s AS (SELECT ACCESSION_NUMBER, FILING_DATE, DOCUMENT_TYPE, TRY_TO_NUMBER(ISSUER_CIK) icik, ISSUER_NAME, ISSUER_TICKER
           FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_INSIDER_SUBMISSION WHERE FILING_DATE >= '2024-01-01' AND FILING_DATE < '2025-01-01'),
r AS (SELECT ACCESSION_NUMBER, OWNER_CIK, OWNER_NAME, RELATIONSHIP, TITLE, CITY, STATE FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_INSIDER_REPORTINGOWNER),
fund AS (SELECT TRY_TO_NUMBER(CIK) cik FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_CLOSED_END_FUND_INFORMATION
         UNION SELECT TRY_TO_NUMBER(CIK) FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_BUSINESS_DEVELOPMENT_COMPANY_REPORT
         UNION SELECT TRY_TO_NUMBER(CIK_NUMBER) FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_INVESTMENT_COMPANY_SERIES_CLASS),
sic AS (SELECT TRY_TO_NUMBER(CIK) cik, MODE(SIC) sic, MODE(AFS) afs FROM (
          SELECT CIK, SIC, AFS FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_DERA_SUB_2024Q1 UNION ALL SELECT CIK, SIC, AFS FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_DERA_SUB_2024Q2
          UNION ALL SELECT CIK, SIC, AFS FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_DERA_SUB_2024Q3 UNION ALL SELECT CIK, SIC, AFS FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_DERA_SUB_2024Q4) GROUP BY 1)
SELECT r.OWNER_CIK, ANY_VALUE(r.OWNER_NAME) owner_name, s.icik, ANY_VALUE(s.ISSUER_NAME) issuer_name, ANY_VALUE(s.ISSUER_TICKER) ticker,
       LISTAGG(DISTINCT r.RELATIONSHIP, '|') rels, ANY_VALUE(r.TITLE) title, ANY_VALUE(r.STATE) owner_st, COUNT(DISTINCT s.ACCESSION_NUMBER) filings,
       MIN(s.FILING_DATE) d0, MAX(s.FILING_DATE) d1, MAX(IFF(fund.cik IS NOT NULL, 1, 0)) is_fund, ANY_VALUE(sic.sic) sic, ANY_VALUE(sic.afs) afs,
       (SELECT MAX(FILING_DATE) FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_INSIDER_SUBMISSION) max_filing_all
FROM r JOIN s USING (ACCESSION_NUMBER) LEFT JOIN fund ON fund.cik = s.icik LEFT JOIN sic ON sic.cik = s.icik
GROUP BY r.OWNER_CIK, s.icik
;

-- ===== batch b4 =====
-- S17 NCUA raw call report (FS220) rows for the 4 negative-net-worth credit unions plus Navy Federal as a control
SELECT * FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_NCUA_CALL_REPORTS_FS220
WHERE TRY_TO_NUMBER(CU_NUMBER) IN (8445, 24940, 2796, 24937, 5536);

-- S18 FDIC enforcement orders since 2010, raw, for local classification (bank vs person, termination vs new)
SELECT ORDER_ID, ORDER_DATE, ORDER_YEAR, ORDER_CATEGORY, ORDER_TYPE, ORDER_TITLE, LEFT(RESPONDENTS, 160) respondents, RESPONDENT_COUNT,
       CERT_NUMBER, BANK_COUNT, CMP_AMOUNT_TOTAL, BANK_NAME, INSTITUTION_NAME, BANK_STATE, BANK_ACTIVE
FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_FDIC_ENFORCEMENT_ORDERS
WHERE ORDER_DATE >= '2010-01-01';

-- S19 FDIC bank directory, every institution, minimal columns, to rebuild who was open when
SELECT CERT, NAME, CITY, STALP, ACTIVE, BKCLASS, CHRTAGNT, SPECGRP, ESTYMD, ENDEFYMD, ASSET, REPDTE, NETINC, MDI_STATUS_CODE, MDI_STATUS_DESC,
       OFFICES_DOMESTIC, HOLDING_COMPANY_NAME, INSURANCE_DROPPED_DATE, SUCCESSOR_CERT
FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_FDIC_BANK_DATA;

-- S20 SEC insiders: people filing as Director at 5+ non-fund issuers, by filing year 2016-2024, plus yearly totals
WITH s AS (SELECT ACCESSION_NUMBER, YEAR(FILING_DATE) y, TRY_TO_NUMBER(ISSUER_CIK) icik, ISSUER_NAME
           FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_INSIDER_SUBMISSION WHERE FILING_DATE >= '2016-01-01' AND FILING_DATE < '2025-01-01'),
r AS (SELECT ACCESSION_NUMBER, OWNER_CIK, OWNER_NAME FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_INSIDER_REPORTINGOWNER WHERE RELATIONSHIP ILIKE '%Director%'),
fund AS (SELECT TRY_TO_NUMBER(CIK) cik FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_CLOSED_END_FUND_INFORMATION
         UNION SELECT TRY_TO_NUMBER(CIK) FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_BUSINESS_DEVELOPMENT_COMPANY_REPORT
         UNION SELECT TRY_TO_NUMBER(CIK_NUMBER) FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_INVESTMENT_COMPANY_SERIES_CLASS),
p AS (SELECT s.y, r.OWNER_CIK, ANY_VALUE(r.OWNER_NAME) nm, COUNT(DISTINCT s.icik) n_iss,
             COUNT(DISTINCT IFF(fund.cik IS NULL AND NOT REGEXP_LIKE(s.ISSUER_NAME, '.*(FUND|TRUST|MUNI|INCOME|PORTFOLIO|OPPORTUNIT).*', 'i'), s.icik, NULL)) n_op,
             LISTAGG(DISTINCT IFF(fund.cik IS NULL AND NOT REGEXP_LIKE(s.ISSUER_NAME, '.*(FUND|TRUST|MUNI|INCOME|PORTFOLIO|OPPORTUNIT).*', 'i'), LEFT(s.ISSUER_NAME, 30), NULL), ' | ') iss
      FROM r JOIN s USING (ACCESSION_NUMBER) LEFT JOIN fund ON fund.cik = s.icik GROUP BY 1, 2)
SELECT y, OWNER_CIK, nm, n_iss, n_op, iss FROM p WHERE n_op >= 5
UNION ALL
SELECT y, 'ALL', NULL, COUNT(*), COUNT_IF(n_op >= 5), TO_VARCHAR(COUNT_IF(n_op >= 10)) FROM p GROUP BY y;

-- S21 SEC insiders: filings whose remarks say "director by deputization", per year and owner, plus yearly issuer totals
WITH s AS (SELECT ACCESSION_NUMBER, YEAR(FILING_DATE) y, TRY_TO_NUMBER(ISSUER_CIK) icik
           FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_INSIDER_SUBMISSION
           WHERE (REMARKS ILIKE '%deputiz%' OR REMARKS ILIKE '%deputis%') AND FILING_DATE < '2025-04-01'),
r AS (SELECT ACCESSION_NUMBER, OWNER_CIK, OWNER_NAME, RELATIONSHIP FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_INSIDER_REPORTINGOWNER),
j AS (SELECT s.y, s.icik, s.ACCESSION_NUMBER, r.OWNER_CIK, r.OWNER_NAME, r.RELATIONSHIP FROM s JOIN r USING (ACCESSION_NUMBER))
SELECT y, OWNER_CIK, ANY_VALUE(OWNER_NAME) nm, COUNT(DISTINCT icik) issuers, COUNT(DISTINCT ACCESSION_NUMBER) filings, COUNT_IF(RELATIONSHIP ILIKE '%Director%') dir_rows
FROM j GROUP BY 1, 2 HAVING COUNT(DISTINCT icik) >= 3
UNION ALL
SELECT y, 'ALL', NULL, COUNT(DISTINCT icik), COUNT(DISTINCT ACCESSION_NUMBER), COUNT(DISTINCT OWNER_CIK) FROM j GROUP BY 1;

-- S22 EPA bridge: the placeholder facility ID and the blank-ID rows, by case-number prefix (region) and case year
SELECT COALESCE(NULLIF(FACILITY_UIN, 'None'), 'blank') uin, SPLIT_PART(CASE_NUMBER, '-', 1) pre, COUNT(DISTINCT CASE_NUMBER) cases, COUNT(*) n,
       MIN(TRY_TO_NUMBER(SPLIT_PART(CASE_NUMBER, '-', 2))) y0, MAX(TRY_TO_NUMBER(SPLIT_PART(CASE_NUMBER, '-', 2))) y1,
       COUNT(DISTINCT FACILITY_STATE) states, ANY_VALUE(FACILITY_STATE) any_st, COUNT(DISTINCT FACILITY_NAME) names
FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_EPA_ICIS_FEC_CASE_ENFORCEMENT_CONCLUSION_FACILITIES
WHERE FACILITY_UIN = '110009327022' OR FACILITY_UIN IS NULL OR FACILITY_UIN IN ('', 'None')
GROUP BY 1, 2 ORDER BY 1, 2
;

-- ===== batch b5 =====
-- S23 FDIC: the 12 new consent orders 2020-2026 against minority-owned (MDI) FDIC-supervised banks, with the order document links
SELECT ORDER_ID, ORDER_DATE, CERT_NUMBER, BANK_NAME, BANK_STATE, ORDER_TITLE, ORDER_TYPE, CMP_AMOUNT_TOTAL, DOCKET_NUMBER, DOCUMENT_URL
FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_FDIC_ENFORCEMENT_ORDERS
WHERE CERT_NUMBER IN (58037, 33708, 13959, 26708, 22460, 10319, 59182, 58816, 59154, 57884) AND ORDER_DATE >= '2020-01-01'
ORDER BY ORDER_DATE;

-- S24 SEC: RA Capital 2024 filings, what the remarks say and how many reporting owners ride on each filing
WITH s AS (SELECT ACCESSION_NUMBER, FILING_DATE, DOCUMENT_TYPE, ISSUER_NAME, REMARKS
           FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_INSIDER_SUBMISSION WHERE FILING_DATE >= '2024-01-01' AND FILING_DATE < '2025-01-01'),
r AS (SELECT ACCESSION_NUMBER, COUNT(*) n_owners, LISTAGG(DISTINCT OWNER_NAME, ' | ') owners, LISTAGG(DISTINCT RELATIONSHIP, ' | ') rels,
             MAX(IFF(OWNER_NAME ILIKE 'RA CAPITAL%' OR OWNER_NAME ILIKE 'Kolchinsky%' OR OWNER_NAME ILIKE 'Shah Rajeev%', 1, 0)) ra
      FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_SEC_INSIDER_REPORTINGOWNER GROUP BY 1)
SELECT s.ISSUER_NAME, COUNT(*) filings, MIN(s.FILING_DATE) d0, MAX(s.FILING_DATE) d1, MEDIAN(r.n_owners) med_owners, ANY_VALUE(r.rels) rels,
       ANY_VALUE(r.owners) owners, ANY_VALUE(LEFT(s.REMARKS, 300)) remarks_sample,
       COUNT_IF(s.REMARKS ILIKE '%director%') remarks_say_director
FROM s JOIN r USING (ACCESSION_NUMBER) WHERE r.ra = 1
GROUP BY 1 ORDER BY 2 DESC
;

