-- deep3/g34: deep pass 3, 2026-09-24. Python door (connect/db.py), read-only SELECT/WITH only, QUERY_TAG 'deep3-2026-09-24'.
-- Every connection first ran: ALTER SESSION SET STATEMENT_TIMEOUT_IN_SECONDS = 300; ALTER SESSION SET QUERY_TAG = 'deep3-2026-09-24'. Those two are not counted.
-- Tables: ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_POLLUTANTS, ENVIRONMENT__FED_WQP_MONITORING_STATIONS, ENVIRONMENT__INTL_GLOBAL_WITNESS_DEFENDERS,
--         ENVIRONMENT__FED_EPA_NPDES_NPDES_INFORMAL_ENFORCEMENT_ACTIONS, ENVIRONMENT__FED_EPA_SDWA_SDWA_PN_VIOLATION_ASSOC.
-- 26 statements (S01-S26), all below, in run order. S02, S03, S08, S11, S14, S16 are extracts; peer, time and cohort math on them ran locally in pandas (g34/ scratch).
-- One batch (b6) was refused by the runner before connecting, because a LISTAGG separator held a semicolon; nothing ran; fixed and rerun. Not counted.
-- Outputs: g34/out_Sxx.txt and g34/out_Sxx.csv.

-- S01 column types for my 5 tables and the sibling tables I may join
SELECT TABLE_NAME, LISTAGG(COLUMN_NAME || ':' || DATA_TYPE, ', ') WITHIN GROUP (ORDER BY ORDINAL_POSITION) cols
FROM LIBRARY_MARTS.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'ENVIRONMENT' AND TABLE_NAME IN (
 'ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_POLLUTANTS','ENVIRONMENT__FED_WQP_MONITORING_STATIONS','ENVIRONMENT__INTL_GLOBAL_WITNESS_DEFENDERS',
 'ENVIRONMENT__FED_EPA_NPDES_NPDES_INFORMAL_ENFORCEMENT_ACTIONS','ENVIRONMENT__FED_EPA_SDWA_SDWA_PN_VIOLATION_ASSOC',
 'ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_FACILITIES','ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_VIOLATION_HISTORY','ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_FORMAL_ACTIONS',
 'ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_STACK_TESTS','ENVIRONMENT__FED_EPA_NPDES_NPDES_FORMAL_ENFORCEMENT_ACTIONS','ENVIRONMENT__FED_EPA_NPDES_ICIS_FACILITIES',
 'ENVIRONMENT__FED_EPA_NPDES_NPDES_QNCR_HISTORY','ENVIRONMENT__FED_EPA_SDWA_SDWA_VIOLATIONS_ENFORCEMENT','ENVIRONMENT__FED_EPA_SDWA_SDWA_PUB_WATER_SYSTEMS')
GROUP BY 1 ORDER BY 1;

-- S02 WQP stations: the whole table (5.8K rows), profiled locally
SELECT * FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_WQP_MONITORING_STATIONS;

-- S03 Global Witness defenders: the whole table (232 rows), read locally
SELECT * FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__INTL_GLOBAL_WITNESS_DEFENDERS;

-- S04 ICIS-Air pollutants: shape by FACIL-vs-real row and class; duplicate pairs; CAS and SRS fill
SELECT (POLLUTANT_DESC = 'FACIL') is_facil_row, AIR_POLLUTANT_CLASS_CODE cls, ANY_VALUE(AIR_POLLUTANT_CLASS_DESC) cls_desc,
       COUNT(*) n, COUNT(DISTINCT PGM_SYS_ID) facilities, COUNT(DISTINCT PGM_SYS_ID || '|' || POLLUTANT_CODE) fac_pollutant_pairs,
       COUNT(DISTINCT POLLUTANT_CODE) pollutant_codes,
       COUNT_IF(NULLIF(TRIM(CHEMICAL_ABSTRACT_SERVICE_NMBR),'') IS NOT NULL) cas_filled,
       COUNT_IF(NULLIF(TRIM(SRS_ID),'') IS NOT NULL) srs_filled
FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_POLLUTANTS
GROUP BY 1,2 ORDER BY 1,4 DESC;

-- S05 ICIS-Air pollutants vs facilities: coverage, FACIL-row class vs facility class, major-for-a-pollutant on a non-major facility
WITH p AS (
  SELECT PGM_SYS_ID, MAX(IFF(POLLUTANT_DESC='FACIL', AIR_POLLUTANT_CLASS_CODE, NULL)) facil_cls,
         COUNT_IF(POLLUTANT_DESC <> 'FACIL') n_poll,
         MAX(IFF(POLLUTANT_DESC <> 'FACIL' AND AIR_POLLUTANT_CLASS_CODE = 'MAJ', 1, 0)) any_maj,
         MAX(IFF(POLLUTANT_DESC <> 'FACIL' AND AIR_POLLUTANT_CLASS_CODE = 'SMI', 1, 0)) any_smi
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_POLLUTANTS GROUP BY 1),
f AS (
  SELECT PGM_SYS_ID, ANY_VALUE(AIR_POLLUTANT_CLASS_CODE) fcls, ANY_VALUE(AIR_OPERATING_STATUS_CODE) st, COUNT(*) frows
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_FACILITIES GROUP BY 1)
SELECT f.fcls, p.facil_cls, (p.PGM_SYS_ID IS NULL) no_pollutant_rows, (f.PGM_SYS_ID IS NULL) no_facility_row,
       COUNT(*) n, COUNT_IF(f.st = 'OPR') operating, SUM(p.any_maj) any_maj_pollutant, SUM(p.any_smi) any_smi_pollutant,
       MEDIAN(p.n_poll) med_pollutants, SUM(IFF(f.frows > 1, 1, 0)) dup_facility_rows
FROM f FULL OUTER JOIN p ON f.PGM_SYS_ID = p.PGM_SYS_ID
GROUP BY 1,2,3,4 ORDER BY n DESC;

-- S06 ICIS-Air pollutants: top 150 pollutants by facility count, with class split and CAS
SELECT POLLUTANT_CODE, POLLUTANT_DESC, MAX(CHEMICAL_ABSTRACT_SERVICE_NMBR) cas, COUNT(*) n, COUNT(DISTINCT PGM_SYS_ID) facilities,
       COUNT_IF(AIR_POLLUTANT_CLASS_CODE = 'MAJ') maj, COUNT_IF(AIR_POLLUTANT_CLASS_CODE = 'SMI') smi, COUNT_IF(AIR_POLLUTANT_CLASS_CODE = 'MIN') mnr
FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_POLLUTANTS
GROUP BY 1,2 ORDER BY facilities DESC LIMIT 150;

-- S07 NPDES informal: shape by agency, type, official flag; date sentinels; registry fill
SELECT AGENCY, ENF_TYPE_CODE, ENF_TYPE_DESC, OFFICIAL_FLG, COUNT(*) n, COUNT(DISTINCT ACTIVITY_ID) acts, COUNT(DISTINCT NPDES_ID) permits,
       COUNT_IF(NULLIF(TRIM(REGISTRY_ID),'') IS NULL) no_registry, MIN(ACHIEVED_DATE) d0, MAX(ACHIEVED_DATE) d1,
       COUNT_IF(ACHIEVED_DATE < '1990-01-01') pre1990, COUNT_IF(ACHIEVED_DATE > CURRENT_DATE) future, COUNT_IF(ACHIEVED_DATE IS NULL) nulldate
FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_NPDES_NPDES_INFORMAL_ENFORCEMENT_ACTIONS
GROUP BY 1,2,3,4 ORDER BY n DESC;

-- S08 NPDES informal: permit-state x agency x month extract, 1990 to today (time series, local)
SELECT LEFT(NPDES_ID, 2) st, AGENCY, DATE_TRUNC('month', ACHIEVED_DATE) ym, COUNT(*) n, COUNT(DISTINCT ACTIVITY_ID) acts, COUNT(DISTINCT NPDES_ID) permits
FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_NPDES_NPDES_INFORMAL_ENFORCEMENT_ACTIONS
WHERE ACHIEVED_DATE BETWEEN '1990-01-01' AND CURRENT_DATE
GROUP BY 1,2,3;

-- S09 SDWA PN assoc: shape, duplicate links, ID uniqueness, date ranges, code spread
SELECT COUNT(*) n, COUNT(DISTINCT PWSID) systems, COUNT(DISTINCT PWSID || '|' || PN_VIOLATION_ID) pn_viols,
       COUNT(DISTINCT PWSID || '|' || RELATED_VIOLATION_ID) related_viols,
       COUNT(DISTINCT PWSID || '|' || PN_VIOLATION_ID || '|' || RELATED_VIOLATION_ID) distinct_links,
       COUNT(DISTINCT PN_VIOLATION_ID) pn_ids_no_pwsid, COUNT(DISTINCT SUBMISSIONYEARQUARTER) releases,
       MIN(COMPL_PER_BEGIN_DATE) cb0, MAX(COMPL_PER_BEGIN_DATE) cb1, MIN(NON_COMPL_PER_BEGIN_DATE) nb0, MAX(NON_COMPL_PER_BEGIN_DATE) nb1,
       MIN(FIRST_REPORTED_DATE) fr0, MAX(FIRST_REPORTED_DATE) fr1, COUNT_IF(COMPL_PER_END_DATE IS NULL) open_end,
       COUNT(DISTINCT VIOLATION_CODE) vcodes, COUNT(DISTINCT CONTAMINANT_CODE) ccodes,
       COUNT_IF(COMPL_PER_BEGIN_DATE >= '2015-01-01') since2015
FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_SDWA_SDWA_PN_VIOLATION_ASSOC;

-- S10 NPDES dull-explanation test: do state inspections, formal actions and effluent-violation permits also stop where informal letters stop? state x quarter, 2021 on
WITH i AS (
  SELECT LEFT(NPDES_ID,2) st, 'inspection' src, STATE_EPA_FLAG who, YEAR(d)*10 + QUARTER(d) yq, COUNT(DISTINCT ACTIVITY_ID) n, COUNT(DISTINCT NPDES_ID) permits
  FROM (SELECT NPDES_ID, ACTIVITY_ID, STATE_EPA_FLAG, TRY_TO_DATE(ACTUAL_END_DATE::string) d FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_NPDES_NPDES_INSPECTIONS)
  WHERE d BETWEEN '2021-01-01' AND CURRENT_DATE GROUP BY 1,2,3,4),
f AS (
  SELECT LEFT(NPDES_ID,2) st, 'formal' src, AGENCY who, YEAR(SETTLEMENT_ENTERED_DATE)*10 + QUARTER(SETTLEMENT_ENTERED_DATE) yq, COUNT(DISTINCT ACTIVITY_ID) n, COUNT(DISTINCT NPDES_ID) permits
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_NPDES_NPDES_FORMAL_ENFORCEMENT_ACTIONS
  WHERE SETTLEMENT_ENTERED_DATE BETWEEN '2021-01-01' AND CURRENT_DATE GROUP BY 1,2,3,4),
q AS (
  SELECT LEFT(NPDES_ID,2) st, 'qncr_eff_viol' src, 'all' who, TRY_TO_NUMBER(YEARQTR) yq, COUNT(DISTINCT IFF(TRY_TO_NUMBER(NUME90_Q) > 0, NPDES_ID, NULL)) n, COUNT(DISTINCT NPDES_ID) permits
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_NPDES_NPDES_QNCR_HISTORY
  WHERE TRY_TO_NUMBER(YEARQTR) BETWEEN 20211 AND 20263 GROUP BY 1,2,3,4)
SELECT * FROM i UNION ALL SELECT * FROM f UNION ALL SELECT * FROM q;

-- S11 ICIS-Air: every operating facility with class, HPV status, carcinogen flags from the pollutants table, violations and formal actions since 2020 (extract; peer math local)
WITH p AS (
  SELECT PGM_SYS_ID,
    LISTAGG(DISTINCT CASE WHEN CHEMICAL_ABSTRACT_SERVICE_NMBR = '75218' THEN 'EtO' WHEN CHEMICAL_ABSTRACT_SERVICE_NMBR = '126998' THEN 'chloroprene'
      WHEN CHEMICAL_ABSTRACT_SERVICE_NMBR = '106990' THEN 'butadiene' WHEN CHEMICAL_ABSTRACT_SERVICE_NMBR = '75014' THEN 'vinylchloride'
      WHEN CHEMICAL_ABSTRACT_SERVICE_NMBR IN ('18540299','1333820') THEN 'hexchrome' WHEN CHEMICAL_ABSTRACT_SERVICE_NMBR = '71432' THEN 'benzene'
      WHEN CHEMICAL_ABSTRACT_SERVICE_NMBR = '50000' THEN 'formaldehyde' END, ',') tox,
    LISTAGG(DISTINCT IFF(AIR_POLLUTANT_CLASS_CODE = 'MAJ' AND CHEMICAL_ABSTRACT_SERVICE_NMBR IN ('75218','126998','106990','75014','18540299','1333820','71432','50000'), CHEMICAL_ABSTRACT_SERVICE_NMBR, NULL), ',') tox_major_cas,
    COUNT_IF(POLLUTANT_DESC <> 'FACIL') n_poll
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_POLLUTANTS GROUP BY 1),
v AS (
  SELECT PGM_SYS_ID, COUNT(DISTINCT IFF(HPV_DAYZERO_DATE >= '2020-01-01', ACTIVITY_ID, NULL)) hpv20,
         COUNT(DISTINCT IFF(EARLIEST_FRV_DETERM_DATE >= '2020-01-01', ACTIVITY_ID, NULL)) frv20,
         COUNT(DISTINCT IFF(HPV_DAYZERO_DATE >= '2020-01-01' AND HPV_RESOLVED_DATE IS NULL, ACTIVITY_ID, NULL)) hpv20_open
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_VIOLATION_HISTORY GROUP BY 1),
fa AS (
  SELECT PGM_SYS_ID, COUNT(DISTINCT IFF(SETTLEMENT_ENTERED_DATE >= '2020-01-01', ACTIVITY_ID, NULL)) formal20,
         SUM(IFF(SETTLEMENT_ENTERED_DATE >= '2020-01-01', PENALTY_AMOUNT, 0)) pen20, COUNT(DISTINCT ACTIVITY_ID) formal_ever
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_FORMAL_ACTIONS GROUP BY 1)
SELECT f.PGM_SYS_ID, f.REGISTRY_ID, f.STATE, f.AIR_POLLUTANT_CLASS_CODE cls, f.CURRENT_HPV, f.FACILITY_NAME, f.CITY, f.NAICS_CODES,
       p.tox, p.tox_major_cas, p.n_poll, v.hpv20, v.frv20, v.hpv20_open, fa.formal20, fa.pen20, fa.formal_ever
FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_FACILITIES f
LEFT JOIN p ON p.PGM_SYS_ID = f.PGM_SYS_ID
LEFT JOIN v ON v.PGM_SYS_ID = f.PGM_SYS_ID
LEFT JOIN fa ON fa.PGM_SYS_ID = f.PGM_SYS_ID
WHERE f.AIR_OPERATING_STATUS_CODE = 'OPR';

-- S12 SDWA PN assoc joined to the deduped violations table on PWSID + ID, both sides: what the PN side is, what the related side is, whether the row's code/date belong to the related violation
WITH v AS (
  SELECT PWSID, VIOLATION_ID, ANY_VALUE(VIOLATION_CODE) vc, ANY_VALUE(IS_HEALTH_BASED_IND) hb, ANY_VALUE(PUBLIC_NOTIFICATION_TIER) tier,
         ANY_VALUE(VIOLATION_CATEGORY_CODE) cat, ANY_VALUE(COMPL_PER_BEGIN_DATE) b, ANY_VALUE(CONTAMINANT_CODE) cc
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_SDWA_SDWA_VIOLATIONS_ENFORCEMENT WHERE VIOLATION_ID IS NOT NULL GROUP BY 1,2)
SELECT vp.vc pn_code, vr.cat rel_cat, vr.hb rel_hb, vr.tier rel_tier, (a.VIOLATION_CODE = vr.vc) code_eq_rel, (a.VIOLATION_CODE = vp.vc) code_eq_pn,
       COUNT(*) n, COUNT_IF(vp.PWSID IS NULL) pn_miss, COUNT_IF(vr.PWSID IS NULL) rel_miss,
       COUNT_IF(a.COMPL_PER_BEGIN_DATE = vr.b) date_eq_rel, COUNT_IF(a.COMPL_PER_BEGIN_DATE = vp.b) date_eq_pn, COUNT_IF(a.CONTAMINANT_CODE = vr.cc) cc_eq_rel
FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_SDWA_SDWA_PN_VIOLATION_ASSOC a
LEFT JOIN v vp ON vp.PWSID = a.PWSID AND vp.VIOLATION_ID = a.PN_VIOLATION_ID
LEFT JOIN v vr ON vr.PWSID = a.PWSID AND vr.VIOLATION_ID = a.RELATED_VIOLATION_ID
GROUP BY 1,2,3,4,5,6 ORDER BY n DESC;

-- S13 NPDES: Missouri/NY/AR letter types by year, and Missouri state inspection outcomes by year (does MO still find violations it no longer writes letters about?)
SELECT 'informal' part, LEFT(NPDES_ID,2) st, YEAR(ACHIEVED_DATE) y, ENF_TYPE_CODE || ' | ' || ENF_TYPE_DESC k, COUNT(DISTINCT ACTIVITY_ID) n, COUNT(DISTINCT NPDES_ID) permits
FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_NPDES_NPDES_INFORMAL_ENFORCEMENT_ACTIONS
WHERE LEFT(NPDES_ID,2) IN ('MO','NY','AR') AND AGENCY = 'State' AND ACHIEVED_DATE BETWEEN '2018-01-01' AND CURRENT_DATE
GROUP BY 1,2,3,4
UNION ALL
SELECT 'inspection', LEFT(NPDES_ID,2), YEAR(TRY_TO_DATE(ACTUAL_END_DATE::string)), COALESCE(ACTIVITY_OUTCOME_CODE,'') || ' | ' || COALESCE(ACTIVITY_OUTCOME_DESC,'') || ' | ' || COALESCE(COMP_MONITOR_TYPE_CODE,''),
       COUNT(DISTINCT ACTIVITY_ID), COUNT(DISTINCT NPDES_ID)
FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_NPDES_NPDES_INSPECTIONS
WHERE LEFT(NPDES_ID,2) = 'MO' AND STATE_EPA_FLAG = 'S' AND TRY_TO_DATE(ACTUAL_END_DATE::string) BETWEEN '2018-01-01' AND CURRENT_DATE
GROUP BY 1,2,3,4;

-- S14 SDWA: per water system, health-based violations begun 2015 on (deduped on PWSID + VIOLATION_ID), how many carry a failure-to-notify (PN code 75) link, acute tier-1 subset, open PN status; with name, type, population
WITH v AS (
  SELECT PWSID, VIOLATION_ID, ANY_VALUE(VIOLATION_CODE) vc, ANY_VALUE(IS_HEALTH_BASED_IND) hb, ANY_VALUE(PUBLIC_NOTIFICATION_TIER) tier,
         ANY_VALUE(COMPL_PER_BEGIN_DATE) b, ANY_VALUE(VIOLATION_STATUS) status, ANY_VALUE(CONTAMINANT_CODE) cc
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_SDWA_SDWA_VIOLATIONS_ENFORCEMENT WHERE VIOLATION_ID IS NOT NULL GROUP BY 1,2),
a AS (SELECT DISTINCT PWSID, PN_VIOLATION_ID, RELATED_VIOLATION_ID FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_SDWA_SDWA_PN_VIOLATION_ASSOC),
rel AS (
  SELECT a.PWSID, a.RELATED_VIOLATION_ID vid, MAX(IFF(vp.status = 'Unaddressed', 1, 0)) pn_unaddr, MIN(vp.b) pn_begin
  FROM a LEFT JOIN v vp ON vp.PWSID = a.PWSID AND vp.VIOLATION_ID = a.PN_VIOLATION_ID GROUP BY 1,2),
hb AS (
  SELECT v.*, IFF(rel.vid IS NOT NULL, 1, 0) has_pn, COALESCE(rel.pn_unaddr, 0) pn_unaddr
  FROM v LEFT JOIN rel ON rel.PWSID = v.PWSID AND rel.vid = v.VIOLATION_ID
  WHERE v.hb = 'Y' AND v.b BETWEEN '2015-01-01' AND CURRENT_DATE),
sys AS (
  SELECT PWSID, COUNT(*) hb_n, SUM(has_pn) hb_pn, COUNT_IF(vc = '5200') c5200, SUM(IFF(vc = '5200', has_pn, 0)) c5200_pn,
         COUNT_IF(tier = '1') t1_n, SUM(IFF(tier = '1', has_pn, 0)) t1_pn, SUM(IFF(tier = '1', pn_unaddr, 0)) t1_pn_unaddr,
         LISTAGG(DISTINCT IFF(tier = '1' AND has_pn = 1, vc || ':' || cc, NULL), ',') t1_pn_codes,
         MIN(IFF(tier = '1' AND has_pn = 1, b, NULL)) t1_pn_first, MAX(IFF(tier = '1' AND has_pn = 1, b, NULL)) t1_pn_last
  FROM hb GROUP BY 1),
p AS (
  SELECT PWSID, ANY_VALUE(PWS_NAME) pws_name, ANY_VALUE(STATE_CODE) state_code, ANY_VALUE(PRIMACY_AGENCY_CODE) primacy, ANY_VALUE(PWS_TYPE_CODE) pws_type,
         ANY_VALUE(PWS_ACTIVITY_CODE) activity, MAX(POPULATION_SERVED_COUNT) pop, ANY_VALUE(CITY_NAME) city, ANY_VALUE(OWNER_TYPE_CODE) owner, COUNT(*) prow
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_SDWA_SDWA_PUB_WATER_SYSTEMS GROUP BY 1)
SELECT sys.*, p.pws_name, p.state_code, p.primacy, p.pws_type, p.activity, p.pop, p.city, p.owner, p.prow
FROM sys LEFT JOIN p ON p.PWSID = sys.PWSID;

-- S15 SDWA time: links by primacy prefix x year of the related violation x related category x tier, plus health-based violation denominators by the same cut
WITH v AS (
  SELECT PWSID, VIOLATION_ID, ANY_VALUE(VIOLATION_CATEGORY_CODE) cat, ANY_VALUE(IS_HEALTH_BASED_IND) hb, ANY_VALUE(PUBLIC_NOTIFICATION_TIER) tier,
         ANY_VALUE(COMPL_PER_BEGIN_DATE) b, ANY_VALUE(VIOLATION_CODE) vc
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_SDWA_SDWA_VIOLATIONS_ENFORCEMENT WHERE VIOLATION_ID IS NOT NULL GROUP BY 1,2),
a AS (SELECT DISTINCT PWSID, PN_VIOLATION_ID, RELATED_VIOLATION_ID, VIOLATION_CODE, COMPL_PER_BEGIN_DATE FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_SDWA_SDWA_PN_VIOLATION_ASSOC)
SELECT 'links' part, LEFT(a.PWSID,2) st, YEAR(a.COMPL_PER_BEGIN_DATE) y, COALESCE(vr.cat,'?') cat, COALESCE(vr.tier,'?') tier,
       COUNT(*) n, COUNT(DISTINCT a.PWSID || '|' || a.PN_VIOLATION_ID) pn_viols, COUNT(DISTINCT a.PWSID) systems
FROM a LEFT JOIN v vr ON vr.PWSID = a.PWSID AND vr.VIOLATION_ID = a.RELATED_VIOLATION_ID
GROUP BY 1,2,3,4,5
UNION ALL
SELECT 'hb_viols', LEFT(PWSID,2), YEAR(b), cat, tier, COUNT(*), COUNT_IF(vc = '5200'), COUNT(DISTINCT PWSID)
FROM v WHERE hb = 'Y' AND b BETWEEN '2005-01-01' AND CURRENT_DATE GROUP BY 1,2,3,4,5
UNION ALL
SELECT 'pn75_all', LEFT(PWSID,2), YEAR(b), 'PN', COALESCE(tier,'?'), COUNT(*), 0, COUNT(DISTINCT PWSID)
FROM v WHERE vc = '75' AND b BETWEEN '2005-01-01' AND CURRENT_DATE GROUP BY 1,2,3,4,5;

-- S16 SDWA nitrate (contaminant 1040) health-based violations begun 2015 on, per system: count, how many carry a PN link, tier-1 count, years, measured level, open status
WITH v AS (
  SELECT PWSID, VIOLATION_ID, ANY_VALUE(VIOLATION_CODE) vc, ANY_VALUE(PUBLIC_NOTIFICATION_TIER) tier, ANY_VALUE(COMPL_PER_BEGIN_DATE) b,
         ANY_VALUE(VIOLATION_STATUS) status, ANY_VALUE(VIOL_MEASURE) m, ANY_VALUE(FEDERAL_MCL) fmcl, ANY_VALUE(UNIT_OF_MEASURE) u
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_SDWA_SDWA_VIOLATIONS_ENFORCEMENT
  WHERE VIOLATION_ID IS NOT NULL AND CONTAMINANT_CODE = '1040' AND IS_HEALTH_BASED_IND = 'Y' GROUP BY 1,2),
a AS (SELECT DISTINCT PWSID, RELATED_VIOLATION_ID FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_SDWA_SDWA_PN_VIOLATION_ASSOC)
SELECT v.PWSID, COUNT(*) n, COUNT_IF(a.PWSID IS NOT NULL) n_pn, COUNT_IF(v.tier = '1') t1, COUNT(DISTINCT YEAR(v.b)) years, MIN(v.b) first_b, MAX(v.b) last_b,
       MEDIAN(TRY_TO_DOUBLE(v.m)) med_level, MAX(TRY_TO_DOUBLE(v.m)) max_level, ANY_VALUE(v.fmcl) fmcl, ANY_VALUE(v.u) unit,
       COUNT_IF(v.status = 'Unaddressed') unaddr, LISTAGG(DISTINCT v.vc, ',') codes
FROM v LEFT JOIN a ON a.PWSID = v.PWSID AND a.RELATED_VIOLATION_ID = v.VIOLATION_ID
WHERE v.b BETWEEN '2015-01-01' AND CURRENT_DATE
GROUP BY 1;

-- S17 SDWA eyeball: every tier-1 violation since 2015 at Yuma AZ and three West Texas nitrate systems, with measured level, MCL, status, enforcement codes, and linked PN violations
WITH e AS (
  SELECT PWSID, VIOLATION_ID, ANY_VALUE(VIOLATION_CODE) vc, ANY_VALUE(CONTAMINANT_CODE) cc, ANY_VALUE(PUBLIC_NOTIFICATION_TIER) tier, ANY_VALUE(COMPL_PER_BEGIN_DATE) b,
         ANY_VALUE(VIOL_MEASURE) m, ANY_VALUE(FEDERAL_MCL) fmcl, ANY_VALUE(STATE_MCL) smcl, ANY_VALUE(UNIT_OF_MEASURE) u, ANY_VALUE(VIOLATION_STATUS) status,
         ANY_VALUE(FACILITY_ID) fac, LISTAGG(DISTINCT ENFORCEMENT_ACTION_TYPE_CODE || '@' || ENFORCEMENT_DATE::string, ' ') enf
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_SDWA_SDWA_VIOLATIONS_ENFORCEMENT
  WHERE PWSID IN ('AZ0414024','TX1650077','TX0480011','TX1520080') GROUP BY 1,2),
a AS (SELECT DISTINCT PWSID, PN_VIOLATION_ID, RELATED_VIOLATION_ID FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_SDWA_SDWA_PN_VIOLATION_ASSOC
      WHERE PWSID IN ('AZ0414024','TX1650077','TX0480011','TX1520080'))
SELECT e.PWSID, e.VIOLATION_ID, e.vc, e.cc, e.tier, e.b, e.m, e.fmcl, e.smcl, e.u, e.status, e.fac, e.enf,
       LISTAGG(DISTINCT p.VIOLATION_ID || ':' || p.status || ':' || p.b::string || ':' || COALESCE(p.enf,''), ' || ') pn
FROM e LEFT JOIN a ON a.PWSID = e.PWSID AND a.RELATED_VIOLATION_ID = e.VIOLATION_ID
LEFT JOIN e p ON p.PWSID = a.PWSID AND p.VIOLATION_ID = a.PN_VIOLATION_ID
WHERE e.tier = '1' AND e.b >= '2015-01-01'
GROUP BY 1,2,3,4,5,6,7,8,9,10,11,12,13 ORDER BY 1, 6;

-- S18 ICIS-Air informal actions by state x year x agency flag, 2016 on: does Missouri's air side drop the way its water letters did?
SELECT LEFT(PGM_SYS_ID, 2) st, STATE_EPA_FLAG who, YEAR(ACHIEVED_DATE) y, COUNT(DISTINCT ACTIVITY_ID) n, COUNT(DISTINCT PGM_SYS_ID) facilities
FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_INFORMAL_ACTIONS
WHERE ACHIEVED_DATE BETWEEN '2016-01-01' AND CURRENT_DATE
GROUP BY 1,2,3;

-- S19 NPDES same-violation cohort: permits with effluent violations in 2+ quarters of a year, and the share that got any state informal action, or any formal action, that same year; every state, 2018-2025
WITH q AS (
  SELECT NPDES_ID, LEFT(NPDES_ID,2) st, TRY_TO_NUMBER(LEFT(YEARQTR,4)) y, COUNT_IF(TRY_TO_NUMBER(NUME90_Q) > 0) vq
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_NPDES_NPDES_QNCR_HISTORY
  WHERE TRY_TO_NUMBER(YEARQTR) BETWEEN 20181 AND 20254 GROUP BY 1,2,3),
i AS (
  SELECT DISTINCT NPDES_ID, YEAR(ACHIEVED_DATE) y FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_NPDES_NPDES_INFORMAL_ENFORCEMENT_ACTIONS
  WHERE AGENCY = 'State' AND ACHIEVED_DATE BETWEEN '2018-01-01' AND '2025-12-31'),
f AS (
  SELECT DISTINCT NPDES_ID, YEAR(SETTLEMENT_ENTERED_DATE) y FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_NPDES_NPDES_FORMAL_ENFORCEMENT_ACTIONS
  WHERE SETTLEMENT_ENTERED_DATE BETWEEN '2018-01-01' AND '2025-12-31')
SELECT q.st, q.y, COUNT(*) permits_2plus_viol_q, COUNT(i.NPDES_ID) got_state_letter, COUNT(f.NPDES_ID) got_formal,
       COUNT_IF(i.NPDES_ID IS NULL AND f.NPDES_ID IS NULL) got_neither, MEDIAN(q.vq) med_viol_q
FROM q LEFT JOIN i ON i.NPDES_ID = q.NPDES_ID AND i.y = q.y LEFT JOIN f ON f.NPDES_ID = q.NPDES_ID AND f.y = q.y
WHERE q.vq >= 2 GROUP BY 1,2;

-- S20 SDWA peer for Yuma: every acute chlorine dioxide MRDL violation (code 13) since 2015, per system, with PN link count
WITH v AS (
  SELECT PWSID, VIOLATION_ID, ANY_VALUE(COMPL_PER_BEGIN_DATE) b, ANY_VALUE(CONTAMINANT_CODE) cc, ANY_VALUE(VIOL_MEASURE) m
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_SDWA_SDWA_VIOLATIONS_ENFORCEMENT
  WHERE VIOLATION_ID IS NOT NULL AND VIOLATION_CODE = '13' GROUP BY 1,2),
a AS (SELECT DISTINCT PWSID, RELATED_VIOLATION_ID FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_SDWA_SDWA_PN_VIOLATION_ASSOC)
SELECT v.PWSID, LISTAGG(DISTINCT v.cc, ',') cc, COUNT(*) n, COUNT_IF(a.PWSID IS NOT NULL) n_pn, MIN(v.b) first_b, MAX(v.b) last_b, MAX(TRY_TO_DOUBLE(v.m)) max_m
FROM v LEFT JOIN a ON a.PWSID = v.PWSID AND a.RELATED_VIOLATION_ID = v.VIOLATION_ID
WHERE v.b BETWEEN '2015-01-01' AND CURRENT_DATE GROUP BY 1 ORDER BY n DESC;

-- S21 NPDES Missouri eyeball: permits with effluent violations in 6+ of 8 quarters in 2020-21 or in 2024-25, their state letters and formal actions in each window, and names
WITH q AS (
  SELECT NPDES_ID,
         COUNT_IF(TRY_TO_NUMBER(NUME90_Q) > 0 AND TRY_TO_NUMBER(YEARQTR) BETWEEN 20201 AND 20214) vq_2021,
         COUNT_IF(TRY_TO_NUMBER(NUME90_Q) > 0 AND TRY_TO_NUMBER(YEARQTR) BETWEEN 20241 AND 20254) vq_2425,
         SUM(IFF(TRY_TO_NUMBER(YEARQTR) BETWEEN 20241 AND 20254, TRY_TO_NUMBER(NUME90_Q), 0)) nviol_2425
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_NPDES_NPDES_QNCR_HISTORY WHERE LEFT(NPDES_ID,2) = 'MO' GROUP BY 1),
i AS (
  SELECT NPDES_ID, COUNT_IF(ACHIEVED_DATE BETWEEN '2020-01-01' AND '2021-12-31') inf_2021, COUNT_IF(ACHIEVED_DATE BETWEEN '2024-01-01' AND '2025-12-31') inf_2425,
         MAX(IFF(ACHIEVED_DATE <= CURRENT_DATE, ACHIEVED_DATE, NULL)) last_inf
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_NPDES_NPDES_INFORMAL_ENFORCEMENT_ACTIONS WHERE LEFT(NPDES_ID,2) = 'MO' GROUP BY 1),
f AS (
  SELECT NPDES_ID, COUNT_IF(SETTLEMENT_ENTERED_DATE BETWEEN '2020-01-01' AND '2021-12-31') fo_2021, COUNT_IF(SETTLEMENT_ENTERED_DATE BETWEEN '2024-01-01' AND '2025-12-31') fo_2425,
         MAX(SETTLEMENT_ENTERED_DATE) last_formal
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_NPDES_NPDES_FORMAL_ENFORCEMENT_ACTIONS WHERE LEFT(NPDES_ID,2) = 'MO' GROUP BY 1),
fac AS (
  SELECT NPDES_ID, ANY_VALUE(FACILITY_NAME) facility_name, ANY_VALUE(CITY) city, ANY_VALUE(FACILITY_TYPE_CODE) ftype
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_NPDES_ICIS_FACILITIES WHERE LEFT(NPDES_ID,2) = 'MO' GROUP BY 1)
SELECT q.*, COALESCE(i.inf_2021,0) inf_2021, COALESCE(i.inf_2425,0) inf_2425, i.last_inf, COALESCE(f.fo_2021,0) fo_2021, COALESCE(f.fo_2425,0) fo_2425, f.last_formal,
       fac.facility_name, fac.city, fac.ftype
FROM q LEFT JOIN i ON i.NPDES_ID = q.NPDES_ID LEFT JOIN f ON f.NPDES_ID = q.NPDES_ID LEFT JOIN fac ON fac.NPDES_ID = q.NPDES_ID
WHERE q.vq_2021 >= 6 OR q.vq_2425 >= 6
ORDER BY q.vq_2425 DESC, q.nviol_2425 DESC;

-- S22 ICIS-Air eyeball: LANXESS Charleston SC (EtO-regulated major, 3 open HPVs since 2020, no formal action since 2020): its violations, informal and formal actions, and its pollutant rows
SELECT 'violation' part, ACTIVITY_ID id, HPV_DAYZERO_DATE::string d1, HPV_RESOLVED_DATE::string d2, AGENCY_TYPE_DESC || ' | ' || COALESCE(ENF_RESPONSE_POLICY_CODE,'') || ' | ' || COALESCE(PROGRAM_DESCS,'') || ' | ' || COALESCE(POLLUTANT_DESCS,'') detail
FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_VIOLATION_HISTORY WHERE PGM_SYS_ID = 'SC00005600011'
UNION ALL
SELECT 'informal', ACTIVITY_ID, ACHIEVED_DATE::string, NULL, STATE_EPA_FLAG || ' | ' || ENF_TYPE_DESC
FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_INFORMAL_ACTIONS WHERE PGM_SYS_ID = 'SC00005600011'
UNION ALL
SELECT 'formal', ACTIVITY_ID, SETTLEMENT_ENTERED_DATE::string, PENALTY_AMOUNT::string, STATE_EPA_FLAG || ' | ' || ENF_TYPE_DESC
FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_FORMAL_ACTIONS WHERE PGM_SYS_ID = 'SC00005600011'
UNION ALL
SELECT 'pollutant', POLLUTANT_CODE, CHEMICAL_ABSTRACT_SERVICE_NMBR, AIR_POLLUTANT_CLASS_CODE, POLLUTANT_DESC
FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_POLLUTANTS WHERE PGM_SYS_ID = 'SC00005600011'
ORDER BY 1, 3;

-- S23 SDWA PN assoc trap check: the systems with the most link rows, and how many distinct PN violations and related violations sit behind them
SELECT PWSID, COUNT(*) links, COUNT(DISTINCT PN_VIOLATION_ID) pn_viols, COUNT(DISTINCT RELATED_VIOLATION_ID) related_viols,
       MIN(COMPL_PER_BEGIN_DATE) b0, MAX(COMPL_PER_BEGIN_DATE) b1, LISTAGG(DISTINCT VIOLATION_CODE, ',') codes,
       MAX(cnt_per_pn) max_related_per_pn
FROM (SELECT a.*, COUNT(*) OVER (PARTITION BY PWSID, PN_VIOLATION_ID) cnt_per_pn FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_SDWA_SDWA_PN_VIOLATION_ASSOC a)
GROUP BY 1 ORDER BY links DESC LIMIT 25;

-- S24 NPDES dull-explanation test: are the "missing" recent letters in MO, CA, IA, AR sitting in the table with blank or junk dates? Date bucket x state, with activity-ID ranges (IDs rise over time)
SELECT LEFT(NPDES_ID,2) st, AGENCY,
       CASE WHEN ACHIEVED_DATE IS NULL THEN 'null' WHEN ACHIEVED_DATE < '1990-01-01' THEN 'pre1990' WHEN ACHIEVED_DATE > CURRENT_DATE THEN 'future'
            WHEN ACHIEVED_DATE < '2023-01-01' THEN '1990-2022' ELSE '2023+' END bucket,
       COUNT(*) n, MIN(TRY_TO_NUMBER(ACTIVITY_ID)) id_min, MAX(TRY_TO_NUMBER(ACTIVITY_ID)) id_max,
       COUNT_IF(TRY_TO_NUMBER(ACTIVITY_ID) >= 3604000000) id_ge_3604e6
FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_NPDES_NPDES_INFORMAL_ENFORCEMENT_ACTIONS
WHERE LEFT(NPDES_ID,2) IN ('MO','CA','IA','AR')
GROUP BY 1,2,3 ORDER BY 1,2,3;

-- S25 NPDES: date the Missouri blank-date letters by activity ID. Part A: national ID range per achieved half-year (state rows, 2018 on). Part B: Missouri blank-date rows by ID band and type
SELECT 'A_national' part, TO_CHAR(DATE_TRUNC('quarter', ACHIEVED_DATE), 'YYYY-MM') k, COUNT(*) n,
       APPROX_PERCENTILE(TRY_TO_NUMBER(ACTIVITY_ID), 0.1) p10, APPROX_PERCENTILE(TRY_TO_NUMBER(ACTIVITY_ID), 0.5) p50, APPROX_PERCENTILE(TRY_TO_NUMBER(ACTIVITY_ID), 0.9) p90
FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_NPDES_NPDES_INFORMAL_ENFORCEMENT_ACTIONS
WHERE AGENCY = 'State' AND ACHIEVED_DATE BETWEEN '2018-01-01' AND CURRENT_DATE
GROUP BY 1,2
UNION ALL
SELECT 'B_MO_null', FLOOR(TRY_TO_NUMBER(ACTIVITY_ID) / 1e6)::string || ' | ' || ENF_TYPE_CODE, COUNT(*), MIN(TRY_TO_NUMBER(ACTIVITY_ID)), MEDIAN(TRY_TO_NUMBER(ACTIVITY_ID)), MAX(TRY_TO_NUMBER(ACTIVITY_ID))
FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_NPDES_NPDES_INFORMAL_ENFORCEMENT_ACTIONS
WHERE LEFT(NPDES_ID,2) = 'MO' AND AGENCY = 'State' AND ACHIEVED_DATE IS NULL
GROUP BY 1,2
ORDER BY 1,2;

-- S26 NPDES Missouri: every state letter/notice counted by year, using the achieved date when present and, when blank, the year implied by its activity ID (the latest national quarter whose median ID is at or below it)
WITH nat AS (
  SELECT DATE_TRUNC('quarter', ACHIEVED_DATE) q, MEDIAN(TRY_TO_NUMBER(ACTIVITY_ID)) p50
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_NPDES_NPDES_INFORMAL_ENFORCEMENT_ACTIONS
  WHERE AGENCY = 'State' AND ACHIEVED_DATE BETWEEN '2016-01-01' AND CURRENT_DATE GROUP BY 1),
mo AS (
  SELECT DISTINCT ACTIVITY_ID, TRY_TO_NUMBER(ACTIVITY_ID) id, ACHIEVED_DATE, ENF_TYPE_CODE
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_NPDES_NPDES_INFORMAL_ENFORCEMENT_ACTIONS
  WHERE LEFT(NPDES_ID,2) = 'MO' AND AGENCY = 'State' AND (ACHIEVED_DATE IS NULL OR ACHIEVED_DATE >= '2016-01-01')),
nul AS (
  SELECT mo.ACTIVITY_ID, MAX(nat.q) implied_q FROM mo JOIN nat ON nat.p50 <= mo.id WHERE mo.ACHIEVED_DATE IS NULL GROUP BY 1)
SELECT YEAR(COALESCE(mo.ACHIEVED_DATE, nul.implied_q)) y, COUNT_IF(mo.ACHIEVED_DATE IS NOT NULL) dated, COUNT_IF(mo.ACHIEVED_DATE IS NULL) blank_date,
       COUNT_IF(mo.ACHIEVED_DATE IS NULL AND nul.ACTIVITY_ID IS NULL) blank_unplaced, COUNT(*) total
FROM mo LEFT JOIN nul ON nul.ACTIVITY_ID = mo.ACTIVITY_ID
GROUP BY 1 ORDER BY 1;

