-- deep3/g35: deep pass 3, 2026-09-24. Python door (connect/db.py), read-only SELECT/WITH only, QUERY_TAG 'deep3-2026-09-24'.
-- Every connection first ran: ALTER SESSION SET STATEMENT_TIMEOUT_IN_SECONDS = 300; ALTER SESSION SET QUERY_TAG = 'deep3-2026-09-24'. Those two are not counted.
-- Tables: ENVIRONMENT__FED_EPA_GHGRP_FACILITY, ENVIRONMENT__FED_EPA_SUPERFUND_SITE_BOUNDARIES, ENVIRONMENT__FED_USGS_MINERALS, ENVIRONMENT__INTL_GEM_HAZARD, ENVIRONMENT__FED_EPA_FRS_FACILITIES.
-- Joined for checks: ENVIRONMENT__FED_EPA_GHGRP_EMISSION, ENVIRONMENT__FED_EPA_AIR_EMISSIONS_POLL_RPT_COMBINED_EMISSIONS, ENVIRONMENT__FED_EPA_ECHO, ENVIRONMENT__FED_EPA_ICIS_AIR_* (facilities, violation history, FCEs/PCEs, formal actions).
-- 21 statements (S01-S21), all below, in run order. S06 failed at compile (no _SOURCE_RUN_ID column) and was rerun as S09; it still counts.
-- S11-S14 and S16 are extracts; the cohort, peer and time math ran locally in pandas (g35/ghg1-7.py, sf.py, fed.py).
-- Outputs: g35/out_Sxx.txt and g35/out_Sxx.csv.

-- S01 GEM hazard: whole table, confirm it is a lookup
SELECT * FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__INTL_GEM_HAZARD ORDER BY 1;

-- S02 GHGRP facility: year x reporting status, facilities, duplicate facility-years, FRS fill, suppliers
SELECT REPORTING_YEAR, REPORTING_STATUS, COUNT(*) n, COUNT(DISTINCT FACILITY_ID) fac,
       COUNT_IF(FRS_ID IS NULL) frs_null, COUNT(DISTINCT FRS_ID) frs_ids,
       COUNT_IF(FACILITY_TYPES ILIKE '%supplier%') supplier_rows,
       COUNT_IF(NULLIF(TRIM(PARENT_COMPANY),'') IS NULL) parent_blank
FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_GHGRP_FACILITY
GROUP BY 1,2 ORDER BY 1,2;

-- S03 GHGRP facility: facility types and status over all years, with the codes that say why they stopped
SELECT FACILITY_TYPES, REPORTING_STATUS, COUNT(*) n, COUNT(DISTINCT FACILITY_ID) fac,
       MIN(REPORTING_YEAR) y0, MAX(REPORTING_YEAR) y1, COUNT_IF(CEMS_USED = 'Y') cems_y,
       COUNT(DISTINCT FACILITY_ID, REPORTING_YEAR) fac_years
FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_GHGRP_FACILITY
GROUP BY 1,2 ORDER BY n DESC;

-- S04 GHGRP emission: year x gas, rows, facilities, duplicate keys, CO2e sum
SELECT REPORTING_YEAR, GAS_ID, COUNT(*) n, COUNT(DISTINCT FACILITY_ID) fac,
       COUNT(DISTINCT FACILITY_ID, SECTOR_ID, SUBSECTOR_ID) keys_fss,
       COUNT_IF(CO2E_EMISSION IS NULL) co2e_null, SUM(CO2E_EMISSION) co2e, MAX(CO2E_EMISSION) co2e_max,
       COUNT(DISTINCT SECTOR_ID) sectors, COUNT(DISTINCT _SOURCE_RUN_ID) runs
FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_GHGRP_EMISSION
GROUP BY 1,2 ORDER BY 1,2;

-- S05 Superfund boundaries: units x NPL status x program, sites, area, dates, federal flag
SELECT GIS_AREA_UNITS, NPL_STATUS_CODE, EPA_PROGRAM, COUNT(*) n, COUNT(DISTINCT EPA_ID) sites,
       COUNT_IF(FEDERAL_FACILITY_CODE IN ('Y','Yes')) fed, SUM(GIS_AREA) area, MEDIAN(GIS_AREA) med_area, MAX(GIS_AREA) max_area,
       COUNT_IF(GIS_AREA = 0 OR GIS_AREA IS NULL) area0, MIN(LAST_CHANGE_AT) lc0, MAX(LAST_CHANGE_AT) lc1,
       MIN(ORIGINALLY_CREATED_AT) oc0, MAX(ORIGINALLY_CREATED_AT) oc1, COUNT(DISTINCT SITE_FEATURE_TYPE) ftypes
FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_SUPERFUND_SITE_BOUNDARIES
GROUP BY 1,2,3 ORDER BY n DESC;

-- S06 USGS minerals: by development status, fill of the columns said to be empty, ID uniqueness, coordinates, newest years  [FAILED: invalid identifier _SOURCE_RUN_ID; rerun as S09]
SELECT DEV_STAT, COUNT(*) n, COUNT(DISTINCT DEP_ID) dep_ids, COUNT(DISTINCT MRDS_ID) mrds_ids, COUNT_IF(MRDS_ID IS NOT NULL) mrds_filled,
       COUNT_IF(NULLIF(TRIM(DATA_SOURCE_NOTES::STRING),'') IS NOT NULL) notes_filled, COUNT_IF(COMMODITY IS NOT NULL) commodity_filled,
       COUNT_IF(PRODUCTION_QUANTITY IS NOT NULL) prod_filled, COUNT_IF(NULLIF(TRIM(STATE::STRING),'') IS NOT NULL) state_filled,
       COUNT_IF(NULLIF(TRIM(FIPS::STRING),'') IS NOT NULL) fips_filled, COUNT_IF(NULLIF(TRIM(YEAR::STRING),'') IS NOT NULL) year_filled,
       COUNT_IF(LATITUDE IS NULL OR LATITUDE::STRING IN ('0','0.0','None')) lat_bad,
       MAX(TRY_TO_NUMBER(YR_LST_PRD::STRING)) max_last_prod, MAX(TRY_TO_NUMBER(DISC_YR::STRING)) max_disc,
       MAX(TRY_TO_NUMBER(YR_FST_PRD::STRING)) max_first_prod, COUNT(DISTINCT _SOURCE_RUN_ID) runs
FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_USGS_MINERALS
GROUP BY 1 ORDER BY n DESC;

-- S07 FRS facilities: by create year, flags, federal fields, tribal, coordinates, site types
SELECT YEAR(CREATE_DATE) cy, COUNT(*) n, COUNT_IF(IS_FEDERAL_FACILITY) is_fed_true, COUNT_IF(IS_ON_TRIBAL_LAND) is_trib_true,
       COUNT_IF(NULLIF(TRIM(FEDERAL_FACILITY_CODE),'') IS NOT NULL) fed_code_filled, COUNT_IF(NULLIF(TRIM(FEDERAL_AGENCY),'') IS NOT NULL) fed_agency_filled,
       COUNT_IF(TRIBAL_LAND_CODE = 'Yes') trib_yes, COUNT_IF(LATITUDE IS NULL) lat_null,
       COUNT_IF(PROGRAM_SYSTEM_ACRONYMS ILIKE '%SEMS:%') sems, COUNT_IF(PROGRAM_SYSTEM_ACRONYMS ILIKE '%E-GGRT:%') ggrt,
       COUNT_IF(SITE_TYPE = 'BROWNFIELDS SITE') brownfields, MIN(UPDATE_DATE) u0, MAX(UPDATE_DATE) u1
FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_FRS_FACILITIES
GROUP BY 1 ORDER BY 1;

-- S08 Combined air emissions: program x year, rows, facilities, GHG rows
SELECT PGM_SYS_ACRNM, REPORTING_YEAR, COUNT(*) n, COUNT(DISTINCT REGISTRY_ID) regs, COUNT_IF(NEI_TYPE = 'GHG') ghg_rows,
       COUNT(DISTINCT IFF(NEI_TYPE = 'GHG', POLLUTANT_NAME, NULL)) ghg_pollutants, ANY_VALUE(IFF(NEI_TYPE='GHG', POLLUTANT_NAME || ' / ' || UNIT_OF_MEASURE, NULL)) ghg_example
FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_AIR_EMISSIONS_POLL_RPT_COMBINED_EMISSIONS
GROUP BY 1,2 ORDER BY 1,2;

-- S09 USGS minerals: by development status, fill of the columns said to be empty, ID uniqueness, coordinates, newest years (S06 rerun without the missing run-id column)
SELECT DEV_STAT, COUNT(*) n, COUNT(DISTINCT DEP_ID) dep_ids, COUNT(DISTINCT MRDS_ID) mrds_ids, COUNT_IF(MRDS_ID IS NOT NULL) mrds_filled,
       COUNT_IF(NULLIF(TRIM(DATA_SOURCE_NOTES::STRING),'') IS NOT NULL) notes_filled, COUNT_IF(COMMODITY IS NOT NULL) commodity_filled,
       COUNT_IF(PRODUCTION_QUANTITY IS NOT NULL) prod_filled, COUNT_IF(NULLIF(TRIM(STATE::STRING),'') IS NOT NULL) state_filled,
       COUNT_IF(NULLIF(TRIM(FIPS::STRING),'') IS NOT NULL) fips_filled, COUNT_IF(NULLIF(TRIM(YEAR::STRING),'') IS NOT NULL) year_filled,
       COUNT_IF(LATITUDE IS NULL OR LATITUDE::STRING IN ('0','0.0','None')) lat_bad,
       MAX(TRY_TO_NUMBER(YR_LST_PRD::STRING)) max_last_prod, MAX(TRY_TO_NUMBER(DISC_YR::STRING)) max_disc,
       MAX(TRY_TO_NUMBER(YR_FST_PRD::STRING)) max_first_prod,
       COUNT_IF(TRY_TO_NUMBER(YR_LST_PRD::STRING) >= 2000) last_prod_2000plus,
       COUNT_IF(COUNTRY = 'United States') us_rows, ANY_VALUE(COM_TYPE) com_type_ex
FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_USGS_MINERALS
GROUP BY 1 ORDER BY n DESC;

-- S10 GHGRP emission x facility type, 2022: which sector and gas ids belong to suppliers vs direct emitters
WITH f AS (
  SELECT FACILITY_ID, REPORTING_YEAR, FACILITY_TYPES
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_GHGRP_FACILITY
  WHERE NULLIF(TRIM(REPORTING_STATUS),'') IS NULL
)
SELECT e.SECTOR_ID, e.GAS_ID,
       CASE WHEN f.FACILITY_ID IS NULL THEN 'no_facility_row'
            WHEN f.FACILITY_TYPES = 'Supplier' THEN 'supplier_only'
            WHEN f.FACILITY_TYPES ILIKE '%Supplier%' THEN 'supplier_mixed'
            ELSE 'no_supplier' END cls,
       COUNT(*) n, COUNT(DISTINCT e.FACILITY_ID) fac, COUNT(DISTINCT e.SUBSECTOR_ID) subsectors,
       ROUND(SUM(e.CO2E_EMISSION)) co2e, ANY_VALUE(f.FACILITY_TYPES) type_ex
FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_GHGRP_EMISSION e
LEFT JOIN f ON f.FACILITY_ID = e.FACILITY_ID AND f.REPORTING_YEAR = e.REPORTING_YEAR
WHERE e.REPORTING_YEAR = 2022
GROUP BY 1,2,3 ORDER BY 1,2,3;

-- S11 GHGRP facility: slim extract of every facility-year (136K rows) for local cohort math
SELECT FACILITY_ID, REPORTING_YEAR yr, NULLIF(TRIM(REPORTING_STATUS),'') status, NULLIF(TRIM(TO_VARCHAR(FRS_ID)),'') frs,
       FACILITY_NAME, PARENT_COMPANY, CITY, STATE, ZIP, COUNTY_FIPS, NAICS_CODE, FACILITY_TYPES, REPORTED_SUBPARTS, REPORTED_INDUSTRY_TYPES
FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_GHGRP_FACILITY;

-- S12 GHGRP emission: direct emissions per facility-year (drops supplier sectors 9-13,16,17 and biogenic gas 8), plus supplier and biogenic side totals
SELECT FACILITY_ID, REPORTING_YEAR yr,
       SUM(IFF(SECTOR_ID NOT IN (9,10,11,12,13,16,17) AND COALESCE(GAS_ID,0) <> 8, CO2E_EMISSION, 0)) direct_t,
       SUM(IFF(SECTOR_ID IN (9,10,11,12,13,16,17), CO2E_EMISSION, 0)) supplier_t,
       SUM(IFF(GAS_ID = 8, CO2E_EMISSION, 0)) biogenic_t,
       LISTAGG(DISTINCT SECTOR_ID, ',') WITHIN GROUP (ORDER BY SECTOR_ID) sectors, COUNT(*) n
FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_GHGRP_EMISSION
GROUP BY 1,2;

-- S13 Combined air emissions for every GHGRP registry ID: per program and year, rows and CO2 amount (the other programs that show a plant still running)
WITH ids AS (
  SELECT DISTINCT TO_VARCHAR(FRS_ID) frs FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_GHGRP_FACILITY WHERE FRS_ID IS NOT NULL
)
SELECT TO_VARCHAR(c.REGISTRY_ID) reg, c.PGM_SYS_ACRNM pgm, c.REPORTING_YEAR::INT yr, COUNT(*) n,
       SUM(IFF(c.POLLUTANT_NAME ILIKE '%carbon dioxide%', c.ANNUAL_EMISSION, NULL)) co2_amt,
       ANY_VALUE(IFF(c.POLLUTANT_NAME ILIKE '%carbon dioxide%', c.UNIT_OF_MEASURE, NULL)) co2_unit,
       ANY_VALUE(IFF(c.POLLUTANT_NAME ILIKE '%carbon dioxide%', c.POLLUTANT_NAME, NULL)) co2_name
FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_AIR_EMISSIONS_POLL_RPT_COMBINED_EMISSIONS c
JOIN ids ON ids.frs = TO_VARCHAR(c.REGISTRY_ID)
GROUP BY 1,2,3;

-- S14 ECHO for every GHGRP registry ID: active flag, compliance, inspections, enforcement, penalties, program flags
WITH ids AS (
  SELECT DISTINCT TO_VARCHAR(FRS_ID) frs FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_GHGRP_FACILITY WHERE FRS_ID IS NOT NULL
)
SELECT TO_VARCHAR(e.FRS_ID) frs, COUNT(*) echo_rows, ANY_VALUE(e.FACILITY_NAME) echo_name, MAX(e.IS_ACTIVE::INT) is_active,
       ANY_VALUE(e.COMPLIANCE_STATUS) compliance, MAX(e.QUARTERS_WITH_NONCOMPLIANCE) qnc, MAX(e.TOTAL_INSPECTION_COUNT) insp,
       MAX(e.DATE_LAST_INSPECTION) last_insp, MAX(e.FORMAL_ACTION_COUNT) formal, MAX(e.DATE_LAST_FORMAL_ACTION) last_formal,
       MAX(e.TOTAL_PENALTIES) penalties, MAX(e.HAS_AIR_PROGRAM::INT) air, MAX(e.HAS_GREENHOUSE_GAS_PROGRAM::INT) ghg_prog,
       MAX(e.HAS_TOXIC_RELEASE_PROGRAM::INT) tri_prog, MAX(e.IS_MAJOR_FACILITY::INT) major, MAX(e.PCT_MINORITY) pct_minority
FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ECHO e
JOIN ids ON ids.frs = TO_VARCHAR(e.FRS_ID)
GROUP BY 1;

-- S15 Combined air emissions for the 17 landfills EPA flags "stopped reporting, unknown reason": every program-year, methane and CO2
SELECT TO_VARCHAR(REGISTRY_ID) reg, PGM_SYS_ACRNM pgm, REPORTING_YEAR::INT yr, COUNT(*) n,
       SUM(IFF(POLLUTANT_NAME ILIKE '%methane%', ANNUAL_EMISSION, NULL)) ch4, ANY_VALUE(IFF(POLLUTANT_NAME ILIKE '%methane%', UNIT_OF_MEASURE, NULL)) ch4_unit,
       SUM(IFF(POLLUTANT_NAME ILIKE '%carbon dioxide%', ANNUAL_EMISSION, NULL)) co2, ANY_VALUE(IFF(POLLUTANT_NAME ILIKE '%carbon dioxide%', UNIT_OF_MEASURE, NULL)) co2_unit
FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_AIR_EMISSIONS_POLL_RPT_COMBINED_EMISSIONS
WHERE TO_VARCHAR(REGISTRY_ID) IN ('110012168652','110006297499','110012694012','110009076338','110043790412','110071161064','110031168983','110040514397','110002524803','110071160106','110071159935','110070931010','110043786105','110054620665','110060832407','110043972779','110071161639')
GROUP BY 1,2,3 ORDER BY 1,2,3;

-- S16 Superfund boundaries: one row per site, area converted to acres (square miles x 640; "Miles" kept apart), features, federal flag, dates, region
SELECT EPA_ID, ANY_VALUE(SITE_NAME) site, ANY_VALUE(STATE_CODE) st, ANY_VALUE(EPA_REGION_CODE) region, LISTAGG(DISTINCT NPL_STATUS_CODE, ',') npl,
       MAX(IFF(FEDERAL_FACILITY_CODE IN ('Y','Yes'), 1, 0)) fed, COUNT(*) features, LISTAGG(DISTINCT EPA_PROGRAM, ',') programs,
       LISTAGG(DISTINCT GIS_AREA_UNITS, ',') units, LISTAGG(DISTINCT SITE_FEATURE_TYPE, ' | ') ftypes,
       SUM(CASE WHEN UPPER(GIS_AREA_UNITS) = 'ACRES' THEN GIS_AREA WHEN UPPER(GIS_AREA_UNITS) = 'SQUARE MILES' THEN GIS_AREA * 640 END) acres_sum,
       MAX(CASE WHEN UPPER(GIS_AREA_UNITS) = 'ACRES' THEN GIS_AREA WHEN UPPER(GIS_AREA_UNITS) = 'SQUARE MILES' THEN GIS_AREA * 640 END) acres_max,
       SUM(IFF(UPPER(GIS_AREA_UNITS) = 'MILES', GIS_AREA, NULL)) miles_sum, MIN(ORIGINALLY_CREATED_AT) created, MAX(LAST_CHANGE_AT) changed,
       ANY_VALUE(SITE_FEATURE_SOURCE) src, ANY_VALUE(SITE_CONTACT_NAME) contact
FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_SUPERFUND_SITE_BOUNDARIES
GROUP BY 1;

-- S17 Superfund EPA_ID -> FRS: do the site IDs land in the FRS program list (SEMS entries)? land rate plus the ID format on both sides
WITH s AS (SELECT DISTINCT EPA_ID FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_SUPERFUND_SITE_BOUNDARIES),
f AS (
  SELECT TO_VARCHAR(REGISTRY_ID) reg, v.value::STRING sid
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_FRS_FACILITIES,
       LATERAL FLATTEN(input => REGEXP_SUBSTR_ALL(PROGRAM_SYSTEM_ACRONYMS, 'SEMS:([A-Z0-9]+)', 1, 1, 'e')) v
  WHERE PROGRAM_SYSTEM_ACRONYMS ILIKE '%SEMS:%'
)
SELECT (SELECT COUNT(*) FROM s) sites, (SELECT COUNT(DISTINCT sid) FROM f) frs_sems_ids, (SELECT COUNT(DISTINCT reg) FROM f) frs_regs,
       COUNT(DISTINCT s.EPA_ID) landed, COUNT(DISTINCT f.reg) landed_regs,
       (SELECT LISTAGG(sid, ',') FROM (SELECT sid FROM f LIMIT 5)) frs_sid_sample,
       (SELECT LISTAGG(EPA_ID, ',') FROM (SELECT EPA_ID FROM s LIMIT 5)) sf_id_sample
FROM s JOIN f ON f.sid = s.EPA_ID;

-- S18 FRS facilities: same cleaned name + address + 5-digit ZIP on more than one registry ID
WITH k AS (
  SELECT REGISTRY_ID, UPPER(REGEXP_REPLACE(FACILITY_NAME,'[^A-Za-z0-9]','')) nk, UPPER(REGEXP_REPLACE(ADDRESS,'[^A-Za-z0-9]','')) ak,
         LEFT(TRIM(POSTAL_CODE),5) z, FACILITY_NAME, ADDRESS, CITY, STATE_CODE
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_FRS_FACILITIES
  WHERE LENGTH(REGEXP_REPLACE(ADDRESS,'[^A-Za-z0-9]','')) > 5 AND UPPER(ADDRESS) NOT LIKE '%UNKNOWN%' AND LENGTH(TRIM(POSTAL_CODE)) >= 5 AND LEFT(TRIM(POSTAL_CODE),5) <> '00000'
), g AS (
  SELECT nk, ak, z, COUNT(*) n, ANY_VALUE(FACILITY_NAME || ' | ' || ADDRESS || ' | ' || CITY || ' ' || STATE_CODE) ex
  FROM k GROUP BY 1,2,3 HAVING COUNT(*) > 1
)
SELECT LEAST(n,10) nb, COUNT(*) grps, SUM(n) ids, MAX_BY(ex, n) biggest, MAX(n) max_n, (SELECT COUNT(*) FROM k) eligible_rows
FROM g GROUP BY 1 ORDER BY 1;

-- S19 Federal vs non-federal: FRS federal agency joined to ECHO active facilities, by department and program mix, chronic noncompliance and enforcement
WITH f AS (
  SELECT TO_VARCHAR(REGISTRY_ID) reg, MAX(NULLIF(TRIM(FEDERAL_AGENCY),'')) agency
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_FRS_FACILITIES GROUP BY 1
), e AS (
  SELECT TO_VARCHAR(FRS_ID) frs, IS_MAJOR_FACILITY maj, HAS_AIR_PROGRAM air, HAS_WATER_PROGRAM wat, HAS_HAZWASTE_PROGRAM rcra,
         QUARTERS_WITH_NONCOMPLIANCE qnc, COMPLIANCE_STATUS cs, FORMAL_ACTION_COUNT fa, TOTAL_PENALTIES pen, TOTAL_INSPECTION_COUNT insp
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ECHO WHERE IS_ACTIVE
)
SELECT COALESCE(TRIM(SPLIT_PART(f.agency, ':', 1)), IFF(f.reg IS NULL, '(no FRS row)', '(not federal)')) dept,
       e.maj, e.air, e.wat, e.rcra, COUNT(*) n, COUNT_IF(e.qnc >= 8) chronic8, COUNT_IF(e.qnc >= 1) any_nc,
       COUNT_IF(e.cs ILIKE '%significant%') snc_label, SUM(e.fa) formal, COUNT_IF(e.fa > 0) with_formal, SUM(e.pen) penalties, SUM(e.insp) insp
FROM e LEFT JOIN f ON f.reg = e.frs
GROUP BY 1,2,3,4,5;

-- S20 USGS minerals: same site name at the same rounded point on more than one record (merged-source duplicates), by development status
WITH k AS (
  SELECT DEP_ID, UPPER(TRIM(SITE_NAME)) nm, ROUND(TRY_TO_DOUBLE(LATITUDE::STRING),3) la, ROUND(TRY_TO_DOUBLE(LONGITUDE::STRING),3) lo, DEV_STAT, MRDS_ID, MAS_ID
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_USGS_MINERALS
), g AS (
  SELECT nm, la, lo, COUNT(*) n, COUNT(DISTINCT DEV_STAT) stats, COUNT_IF(MRDS_ID IS NOT NULL) with_mrds, COUNT_IF(MAS_ID IS NOT NULL) with_mas
  FROM k WHERE la IS NOT NULL GROUP BY 1,2,3 HAVING COUNT(*) > 1
)
SELECT LEAST(n,5) nb, COUNT(*) grps, SUM(n) recs, COUNT_IF(stats > 1) conflicting_status, SUM(with_mrds) mrds, SUM(with_mas) mas,
       MAX_BY(nm || ' @ ' || la || ',' || lo, n) biggest, MAX(n) max_n
FROM g GROUP BY 1 ORDER BY 1;

-- S21 The 17 flagged landfills through the FRS hub: FRS programs, ICIS-Air permit status, air violations, inspections and formal actions, before vs after they went quiet
WITH ids AS (
  SELECT column1 reg FROM VALUES ('110012168652'),('110006297499'),('110012694012'),('110009076338'),('110043790412'),('110071161064'),('110031168983'),('110040514397'),('110002524803'),('110071160106'),('110071159935'),('110070931010'),('110043786105'),('110054620665'),('110060832407'),('110043972779'),('110071161639')
), fr AS (
  SELECT TO_VARCHAR(REGISTRY_ID) reg, ANY_VALUE(FACILITY_NAME) frs_name, ANY_VALUE(SITE_TYPE) site_type, ANY_VALUE(LEFT(PROGRAM_SYSTEM_ACRONYMS, 250)) progs, MAX(UPDATE_DATE) frs_upd
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_FRS_FACILITIES WHERE TO_VARCHAR(REGISTRY_ID) IN (SELECT reg FROM ids) GROUP BY 1
), a AS (
  SELECT TO_VARCHAR(REGISTRY_ID) reg, PGM_SYS_ID, AIR_OPERATING_STATUS_DESC op_status, AIR_POLLUTANT_CLASS_DESC air_class, CURRENT_HPV
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_FACILITIES WHERE TO_VARCHAR(REGISTRY_ID) IN (SELECT reg FROM ids)
), v AS (
  SELECT PGM_SYS_ID, COUNT(*) viol, MIN(COALESCE(TRY_TO_DATE(EARLIEST_FRV_DETERM_DATE::STRING), TRY_TO_DATE(EARLIEST_FRV_DETERM_DATE::STRING,'MM/DD/YYYY'))) first_viol,
         MAX(COALESCE(TRY_TO_DATE(EARLIEST_FRV_DETERM_DATE::STRING), TRY_TO_DATE(EARLIEST_FRV_DETERM_DATE::STRING,'MM/DD/YYYY'))) last_viol,
         LEFT(LISTAGG(DISTINCT POLLUTANT_DESCS, ' | '), 150) polls, LEFT(LISTAGG(DISTINCT AGENCY_TYPE_DESC, ' | '), 60) agency
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_VIOLATION_HISTORY WHERE PGM_SYS_ID IN (SELECT PGM_SYS_ID FROM a) GROUP BY 1
), i AS (
  SELECT PGM_SYS_ID, COUNT(*) evals, MAX(ACTUAL_END_DATE) last_eval
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_FCES_PCES WHERE PGM_SYS_ID IN (SELECT PGM_SYS_ID FROM a) GROUP BY 1
), fa AS (
  SELECT PGM_SYS_ID, COUNT(*) fa_n, MAX(SETTLEMENT_ENTERED_DATE) last_fa, SUM(TRY_TO_NUMBER(PENALTY_AMOUNT::STRING)) fa_pen
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_FORMAL_ACTIONS WHERE PGM_SYS_ID IN (SELECT PGM_SYS_ID FROM a) GROUP BY 1
)
SELECT ids.reg, fr.frs_name, fr.site_type, fr.frs_upd, a.PGM_SYS_ID, a.op_status, a.air_class, a.CURRENT_HPV,
       v.viol, v.first_viol, v.last_viol, v.agency, v.polls, i.evals, i.last_eval, fa.fa_n, fa.last_fa, fa.fa_pen, fr.progs
FROM ids LEFT JOIN fr ON fr.reg = ids.reg LEFT JOIN a ON a.reg = ids.reg
LEFT JOIN v ON v.PGM_SYS_ID = a.PGM_SYS_ID LEFT JOIN i ON i.PGM_SYS_ID = a.PGM_SYS_ID LEFT JOIN fa ON fa.PGM_SYS_ID = a.PGM_SYS_ID
ORDER BY 1;

