-- deep3/g44: deep pass 3, 2026-09-24. Python door (connect/db.py), read-only SELECT/WITH only.
-- Every connection first ran: ALTER SESSION SET STATEMENT_TIMEOUT_IN_SECONDS = 300; ALTER SESSION SET QUERY_TAG = 'deep3-2026-09-24'. Not counted.
-- Tables: REFERENCE__CENSUS_CB_COUNTY, REFERENCE__FED_ITIS_GEOGRAPHIC_DIV, REFERENCE__FED_ITIS_NODC_IDS,
--         REFERENCE__FED_ITIS_STRIPPEDAUTHOR, REFERENCE__FED_ITIS_SYNONYM_LINKS (all LIBRARY_MARTS.REFERENCE).
-- Raw results: g44/rNN_<label>.json

-- [S01] county_shape  (ERRORED on fetch: _INGESTED_AT reads as year 56,643,299 and the Python connector cannot convert it. Rerun as S04 with ::VARCHAR.)
WITH t AS (SELECT * FROM LIBRARY_MARTS.REFERENCE.REFERENCE__CENSUS_CB_COUNTY)
SELECT COUNT(*) n, COUNT(DISTINCT GEOID) geoid_nd, COUNT(DISTINCT GEOIDFQ) geoidfq_nd, COUNT(DISTINCT COUNTYNS) ns_nd,
       COUNT_IF(LENGTH(GEOID::VARCHAR) <> 5) geoid_not5, COUNT_IF(GEOID::VARCHAR <> STATEFP::VARCHAR || COUNTYFP::VARCHAR) geoid_ne_parts,
       COUNT(DISTINCT STATEFP) states, COUNT_IF(TRY_TO_NUMBER(STATEFP::VARCHAR) >= 60) territory_rows, COUNT_IF(STATEFP::VARCHAR = '72') pr_rows,
       COUNT_IF(STATEFP::VARCHAR = '09') ct_rows,
       (SELECT ARRAY_AGG(GEOID || ' ' || NAMELSAD) WITHIN GROUP (ORDER BY GEOID) FROM t WHERE STATEFP::VARCHAR = '09') ct_list,
       (SELECT OBJECT_AGG(COALESCE(VINTAGE::VARCHAR, '(null)'), c) FROM (SELECT VINTAGE, COUNT(*) c FROM t GROUP BY 1)) by_vintage,
       (SELECT OBJECT_AGG(COALESCE(LSAD::VARCHAR, '(null)'), c) FROM (SELECT LSAD, COUNT(*) c FROM t GROUP BY 1)) by_lsad,
       COUNT(DISTINCT _SOURCE_RUN_ID) runs, COUNT(DISTINCT _SRC_SHA256) files, MIN(_INGESTED_AT) i0, MAX(_INGESTED_AT) i1,
       COUNT_IF(TRY_TO_NUMBER(ALAND::VARCHAR) IS NULL) aland_bad, COUNT_IF(TRY_TO_NUMBER(ALAND::VARCHAR) = 0) aland_zero,
       COUNT_IF(GEOMETRY IS NULL) geom_null,
       (SELECT MAX(c) FROM (SELECT COUNT(*) c FROM t GROUP BY COUNTYNS)) max_rows_per_ns,
       (SELECT MAX(c) FROM (SELECT COUNT(*) c FROM t GROUP BY GEOID)) max_rows_per_geoid,
       COUNT_IF(COUNTYNS::VARCHAR = '01804502') rows_battery_top_ns,
       (SELECT ARRAY_AGG(GEOID || ' ' || NAMELSAD || ' ' || STUSPS) FROM (SELECT * FROM t WHERE COUNTYNS::VARCHAR = '01804502' LIMIT 5)) battery_ns_rows
FROM t;

-- [S02] county_vs_dim_county
WITH cb AS (SELECT GEOID::VARCHAR g, NAMELSAD nm FROM LIBRARY_MARTS.REFERENCE.REFERENCE__CENSUS_CB_COUNTY),
dc0 AS (SELECT TRY_TO_NUMBER(COUNTY_FIPS::VARCHAR) cf, TRY_TO_NUMBER(STATE_FIPS::VARCHAR) sf, COUNTY_NAME nm, VINTAGE v FROM LIBRARY_MARTS.CORE.DIM_COUNTY),
dc AS (SELECT CASE WHEN cf >= 1000 THEN LPAD(cf::VARCHAR, 5, '0') ELSE LPAD(sf::VARCHAR, 2, '0') || LPAD(cf::VARCHAR, 3, '0') END g, nm, v FROM dc0)
SELECT (SELECT COUNT(*) FROM dc) dc_n, (SELECT COUNT(DISTINCT g) FROM dc) dc_nd,
       (SELECT ARRAY_AGG(DISTINCT v) FROM dc) dc_vintages,
       (SELECT COUNT(*) FROM cb WHERE g IN (SELECT g FROM dc WHERE g IS NOT NULL)) cb_land,
       (SELECT COUNT(*) FROM cb WHERE g NOT IN (SELECT g FROM dc WHERE g IS NOT NULL)) cb_only_n,
       (SELECT ARRAY_AGG(g || ' ' || nm) FROM (SELECT g, nm FROM cb WHERE g NOT IN (SELECT g FROM dc WHERE g IS NOT NULL) ORDER BY g LIMIT 40)) cb_only_sample,
       (SELECT COUNT(*) FROM dc WHERE g NOT IN (SELECT g FROM cb)) dc_only_n,
       (SELECT ARRAY_AGG(g || ' ' || nm) FROM (SELECT g, nm FROM dc WHERE g NOT IN (SELECT g FROM cb) ORDER BY g LIMIT 40)) dc_only_sample;

-- [S03] county_ct_codes_across_tables
WITH cb AS (SELECT GEOID::VARCHAR g FROM LIBRARY_MARTS.REFERENCE.REFERENCE__CENSUS_CB_COUNTY),
a AS (SELECT DISTINCT LPAD(TRY_TO_NUMBER(FIPS::VARCHAR)::VARCHAR, 5, '0') g FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CDC_DRUG_POISONING_COUNTY WHERE TRY_TO_NUMBER(FIPS::VARCHAR) >= 1000),
b AS (SELECT DISTINCT LPAD(TRY_TO_NUMBER(GEOID::VARCHAR)::VARCHAR, 5, '0') g FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CDC_INJURY_VIOLENCE_COUNTY WHERE TRY_TO_NUMBER(GEOID::VARCHAR) >= 1000),
j AS (SELECT DISTINCT LPAD(TRY_TO_NUMBER(FIPS::VARCHAR)::VARCHAR, 5, '0') g FROM LIBRARY_MARTS.JUSTICE.JUSTICE__COUNTY_DOUBLE_BURDEN WHERE TRY_TO_NUMBER(FIPS::VARCHAR) >= 1000)
SELECT 'cdc_drug_poisoning' src, COUNT(*) keys, COUNT_IF(g IN (SELECT g FROM cb)) land_in_cb, COUNT_IF(g LIKE '090%') ct_old_counties, COUNT_IF(g LIKE '091%') ct_new_regions FROM a
UNION ALL SELECT 'cdc_injury_violence', COUNT(*), COUNT_IF(g IN (SELECT g FROM cb)), COUNT_IF(g LIKE '090%'), COUNT_IF(g LIKE '091%') FROM b
UNION ALL SELECT 'justice_double_burden', COUNT(*), COUNT_IF(g IN (SELECT g FROM cb)), COUNT_IF(g LIKE '090%'), COUNT_IF(g LIKE '091%') FROM j
UNION ALL SELECT 'cb_county_itself', COUNT(*), COUNT(*), COUNT_IF(g LIKE '090%'), COUNT_IF(g LIKE '091%') FROM cb;

-- [S04] county_shape_rerun
WITH t AS (SELECT * FROM LIBRARY_MARTS.REFERENCE.REFERENCE__CENSUS_CB_COUNTY)
SELECT COUNT(*) n, COUNT(DISTINCT GEOID) geoid_nd, COUNT(DISTINCT GEOIDFQ) geoidfq_nd, COUNT(DISTINCT COUNTYNS) ns_nd,
       COUNT_IF(LENGTH(GEOID::VARCHAR) <> 5) geoid_not5, COUNT_IF(GEOID::VARCHAR <> STATEFP::VARCHAR || COUNTYFP::VARCHAR) geoid_ne_parts,
       COUNT(DISTINCT STATEFP) states, COUNT_IF(TRY_TO_NUMBER(STATEFP::VARCHAR) >= 60) territory_rows, COUNT_IF(STATEFP::VARCHAR = '72') pr_rows,
       COUNT_IF(STATEFP::VARCHAR = '09') ct_rows,
       (SELECT ARRAY_AGG(GEOID || ' ' || NAMELSAD) WITHIN GROUP (ORDER BY GEOID) FROM t WHERE STATEFP::VARCHAR = '09') ct_list,
       (SELECT OBJECT_AGG(COALESCE(VINTAGE::VARCHAR, '(null)'), c) FROM (SELECT VINTAGE, COUNT(*) c FROM t GROUP BY 1)) by_vintage,
       (SELECT OBJECT_AGG(COALESCE(LSAD::VARCHAR, '(null)'), c) FROM (SELECT LSAD, COUNT(*) c FROM t GROUP BY 1)) by_lsad,
       COUNT(DISTINCT _SOURCE_RUN_ID) runs, COUNT(DISTINCT _SRC_SHA256) files,
       MIN(_INGESTED_AT)::VARCHAR i0, MAX(_INGESTED_AT)::VARCHAR i1, SYSTEM$TYPEOF(MIN(_INGESTED_AT)) i_type,
       COUNT_IF(TRY_TO_NUMBER(ALAND::VARCHAR) IS NULL) aland_bad, COUNT_IF(TRY_TO_NUMBER(ALAND::VARCHAR) = 0) aland_zero,
       COUNT_IF(GEOMETRY IS NULL) geom_null,
       (SELECT MAX(c) FROM (SELECT COUNT(*) c FROM t GROUP BY COUNTYNS)) max_rows_per_ns,
       (SELECT MAX(c) FROM (SELECT COUNT(*) c FROM t GROUP BY GEOID)) max_rows_per_geoid,
       COUNT_IF(COUNTYNS::VARCHAR = '01804502') rows_battery_top_ns,
       (SELECT ARRAY_AGG(GEOID || ' ' || NAMELSAD || ' ' || STUSPS) FROM (SELECT * FROM t WHERE COUNTYNS::VARCHAR = '01804502' LIMIT 5)) battery_ns_rows
FROM t;

-- [S05] county_misses_other_tables
WITH cb AS (SELECT GEOID::VARCHAR g FROM LIBRARY_MARTS.REFERENCE.REFERENCE__CENSUS_CB_COUNTY),
a AS (SELECT DISTINCT LPAD(TRY_TO_NUMBER(FIPS::VARCHAR)::VARCHAR, 5, '0') g, COUNTY nm FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CDC_DRUG_POISONING_COUNTY WHERE TRY_TO_NUMBER(FIPS::VARCHAR) >= 1000),
b AS (SELECT DISTINCT LPAD(TRY_TO_NUMBER(GEOID::VARCHAR)::VARCHAR, 5, '0') g, NAME nm FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CDC_INJURY_VIOLENCE_COUNTY WHERE TRY_TO_NUMBER(GEOID::VARCHAR) >= 1000)
SELECT 'cdc_drug_poisoning' src, g, nm FROM a WHERE g NOT IN (SELECT g FROM cb)
UNION ALL SELECT 'cdc_injury_violence', g, nm FROM b WHERE g NOT IN (SELECT g FROM cb)
ORDER BY 1, 2;

-- [S06] geodiv_shape
WITH t AS (SELECT * FROM LIBRARY_MARTS.REFERENCE.REFERENCE__FED_ITIS_GEOGRAPHIC_DIV)
SELECT COUNT(*) n, COUNT(DISTINCT TSN) tsn_nd, COUNT(DISTINCT ITIS_GEOGRAPHIC_DIV_KEY) key_nd, COUNT(DISTINCT TSN, GEOGRAPHIC_VALUE) pair_nd,
       (SELECT OBJECT_AGG(COALESCE(GEOGRAPHIC_VALUE, '(null)'), c) FROM (SELECT GEOGRAPHIC_VALUE, COUNT(*) c FROM t GROUP BY 1)) by_region,
       COUNT_IF(LEFT(UPDATE_DATE::VARCHAR, 10) = '1900-01-01') d1900, MIN(UPDATE_DATE)::VARCHAR d0, MAX(UPDATE_DATE)::VARCHAR d1,
       (SELECT OBJECT_AGG(y, c) FROM (SELECT LEFT(UPDATE_DATE::VARCHAR, 4) y, COUNT(*) c FROM t GROUP BY 1)) by_year,
       COUNT(DISTINCT _SOURCE_RUN_ID) runs, COUNT(DISTINCT _SRC_SHA256) files,
       (SELECT MAX(c) FROM (SELECT COUNT(*) c FROM t GROUP BY TSN)) max_regions_per_tsn,
       (SELECT MEDIAN(c) FROM (SELECT COUNT(*) c FROM t GROUP BY TSN)) med_regions_per_tsn
FROM t;

-- [S07] geodiv_join_taxonomic_units
WITH g AS (SELECT TSN, LEFT(UPDATE_DATE::VARCHAR, 10) = '1900-01-01' d1900 FROM LIBRARY_MARTS.REFERENCE.REFERENCE__FED_ITIS_GEOGRAPHIC_DIV),
tu AS (SELECT TSN, NAME_USAGE, RANK_ID FROM LIBRARY_MARTS.REFERENCE.REFERENCE__FED_ITIS_TAXONOMIC_UNITS)
SELECT g.d1900, COALESCE(tu.NAME_USAGE::VARCHAR, '(no taxon row)') usage, COUNT(*) n, COUNT(DISTINCT g.TSN) tsns,
       COUNT_IF(tu.RANK_ID = 220) species_rank_rows
FROM g LEFT JOIN tu ON g.TSN = tu.TSN GROUP BY 1, 2 ORDER BY 1, 3 DESC;

-- [S08] geodiv_coverage_by_kingdom
WITH g AS (SELECT DISTINCT TSN FROM LIBRARY_MARTS.REFERENCE.REFERENCE__FED_ITIS_GEOGRAPHIC_DIV),
tu AS (SELECT TSN, KINGDOM_ID FROM LIBRARY_MARTS.REFERENCE.REFERENCE__FED_ITIS_TAXONOMIC_UNITS WHERE RANK_ID = 220 AND NAME_USAGE IN ('valid', 'accepted')),
k AS (SELECT KINGDOM_ID, KINGDOM_NAME FROM LIBRARY_MARTS.REFERENCE.REFERENCE__FED_ITIS_KINGDOMS)
SELECT tu.KINGDOM_ID, MAX(k.KINGDOM_NAME) kingdom, COUNT(*) accepted_species, COUNT_IF(g.TSN IS NOT NULL) with_region,
       ROUND(100 * COUNT_IF(g.TSN IS NOT NULL) / COUNT(*), 1) pct
FROM tu LEFT JOIN g ON tu.TSN = g.TSN LEFT JOIN k ON tu.KINGDOM_ID = k.KINGDOM_ID
GROUP BY 1 ORDER BY 3 DESC;

-- [S09] nodc_shape
WITH t AS (SELECT * FROM LIBRARY_MARTS.REFERENCE.REFERENCE__FED_ITIS_NODC_IDS)
SELECT COUNT(*) n, COUNT(DISTINCT TSN) tsn_nd, COUNT(DISTINCT NODC_ID) nodc_nd, COUNT(DISTINCT ITIS_NODC_IDS_KEY) key_nd,
       MIN(TSN) tsn0, MAX(TSN) tsn1, MAX(TSN) - MIN(TSN) + 1 - COUNT(DISTINCT TSN) tsn_gaps,
       (SELECT MAX(c) FROM (SELECT COUNT(*) c FROM t GROUP BY TSN)) max_per_tsn,
       (SELECT MAX(c) FROM (SELECT COUNT(*) c FROM t GROUP BY NODC_ID)) max_per_nodc,
       MIN(LENGTH(NODC_ID::VARCHAR)) len0, MAX(LENGTH(NODC_ID::VARCHAR)) len1, SYSTEM$TYPEOF(MIN(NODC_ID)) nodc_type,
       (SELECT OBJECT_AGG(ym, c) FROM (SELECT LEFT(UPDATE_DATE::VARCHAR, 7) ym, COUNT(*) c FROM t GROUP BY 1)) by_month,
       COUNT(DISTINCT _SOURCE_RUN_ID) runs,
       (SELECT ARRAY_AGG(NODC_ID || '|' || TSN || '|' || UPDATE_DATE::VARCHAR) WITHIN GROUP (ORDER BY TSN) FROM (SELECT * FROM t ORDER BY TSN LIMIT 8)) first_rows
FROM t;

-- [S10] nodc_join_taxonomic_units
WITH t AS (SELECT TSN, NODC_ID FROM LIBRARY_MARTS.REFERENCE.REFERENCE__FED_ITIS_NODC_IDS),
tu AS (SELECT TSN, NAME_USAGE, COMPLETE_NAME, RANK_ID FROM LIBRARY_MARTS.REFERENCE.REFERENCE__FED_ITIS_TAXONOMIC_UNITS),
s AS (SELECT COALESCE(tu.NAME_USAGE::VARCHAR, '(no taxon row)') usage, COUNT(*) n FROM t LEFT JOIN tu ON t.TSN = tu.TSN GROUP BY 1),
e AS (SELECT t.NODC_ID::VARCHAR || ' -> ' || t.TSN || ' ' || COALESCE(tu.COMPLETE_NAME, '?') || ' [' || COALESCE(tu.NAME_USAGE, '?') || ']' r
      FROM t LEFT JOIN tu ON t.TSN = tu.TSN WHERE MOD(t.TSN, 20011) = 7 LIMIT 8)
SELECT 'usage' kind, usage label, n FROM s
UNION ALL SELECT 'eyeball', r, NULL FROM e
ORDER BY 1 DESC, 3 DESC;

-- [S11] strippedauthor_shape
WITH t AS (SELECT * FROM LIBRARY_MARTS.REFERENCE.REFERENCE__FED_ITIS_STRIPPEDAUTHOR),
l AS (SELECT TAXON_AUTHOR_ID, SHORT_AUTHOR FROM LIBRARY_MARTS.REFERENCE.REFERENCE__FED_ITIS_TAXON_AUTHORS_LKP)
SELECT COUNT(*) n, COUNT(DISTINCT TAXON_AUTHOR_ID) id_nd, COUNT(DISTINCT SHORT_AUTHOR) sa_nd,
       (SELECT MAX(c) FROM (SELECT COUNT(*) c FROM t GROUP BY TAXON_AUTHOR_ID)) max_per_id,
       (SELECT ARRAY_AGG(s || ' : ' || c) WITHIN GROUP (ORDER BY c DESC) FROM (SELECT SHORT_AUTHOR s, COUNT(*) c FROM t GROUP BY 1 ORDER BY 2 DESC LIMIT 6)) top_short,
       COUNT_IF(SHORT_AUTHOR = 'Schmid-Egger 2022') rows_battery_top,
       COUNT_IF(TAXON_AUTHOR_ID = 0) id0, COUNT_IF(NULLIF(TRIM(SHORT_AUTHOR), '') IS NULL) sa_blank,
       COUNT(DISTINCT _SOURCE_RUN_ID) runs, COUNT(DISTINCT _SRC_SHA256) files,
       (SELECT COUNT(*) FROM l) lkp_n, (SELECT COUNT(DISTINCT TAXON_AUTHOR_ID) FROM l) lkp_id_nd,
       COUNT_IF(TAXON_AUTHOR_ID IN (SELECT TAXON_AUTHOR_ID FROM l)) land_in_lkp,
       (SELECT COUNT(*) FROM t s WHERE EXISTS (SELECT 1 FROM l WHERE l.TAXON_AUTHOR_ID = s.TAXON_AUTHOR_ID AND l.SHORT_AUTHOR = s.SHORT_AUTHOR)) same_text_as_lkp,
       (SELECT COUNT(DISTINCT TAXON_AUTHOR_ID) FROM LIBRARY_MARTS.REFERENCE.REFERENCE__FED_ITIS_TAXONOMIC_UNITS WHERE TAXON_AUTHOR_ID <> 0) tu_author_ids,
       (SELECT COUNT(DISTINCT TAXON_AUTHOR_ID) FROM LIBRARY_MARTS.REFERENCE.REFERENCE__FED_ITIS_TAXONOMIC_UNITS WHERE TAXON_AUTHOR_ID <> 0 AND TAXON_AUTHOR_ID IN (SELECT TAXON_AUTHOR_ID FROM t)) tu_author_ids_in_sa,
       (SELECT ARRAY_AGG(TAXON_AUTHOR_ID || ' | ' || SHORT_AUTHOR) FROM (SELECT * FROM t WHERE MOD(TAXON_AUTHOR_ID, 9973) = 11 LIMIT 8)) eyeball
FROM t;

-- [S12] synonym_shape
WITH t AS (SELECT * FROM LIBRARY_MARTS.REFERENCE.REFERENCE__FED_ITIS_SYNONYM_LINKS)
SELECT COUNT(*) n, COUNT(DISTINCT TSN) tsn_nd, COUNT(DISTINCT TSN_ACCEPTED) acc_nd, COUNT(DISTINCT ITIS_SYNONYM_LINKS_KEY) key_nd,
       COUNT_IF(TSN = TSN_ACCEPTED) self_links,
       (SELECT COUNT(*) FROM (SELECT TSN FROM t GROUP BY 1 HAVING COUNT(DISTINCT TSN_ACCEPTED) > 1)) tsn_multi_acc,
       COUNT_IF(TSN_ACCEPTED IN (SELECT TSN FROM t)) chained_rows,
       (SELECT MEDIAN(c) FROM (SELECT COUNT(*) c FROM t GROUP BY TSN_ACCEPTED)) med_syn_per_acc,
       (SELECT ARRAY_AGG(a || ' : ' || c) WITHIN GROUP (ORDER BY c DESC) FROM (SELECT TSN_ACCEPTED a, COUNT(*) c FROM t GROUP BY 1 ORDER BY 2 DESC LIMIT 6)) top_acc,
       COUNT_IF(LEFT(UPDATE_DATE::VARCHAR, 10) = '1900-01-01') d1900, MIN(UPDATE_DATE)::VARCHAR d0, MAX(UPDATE_DATE)::VARCHAR d1,
       (SELECT OBJECT_AGG(y, c) FROM (SELECT LEFT(UPDATE_DATE::VARCHAR, 4) y, COUNT(*) c FROM t GROUP BY 1)) by_year,
       COUNT(DISTINCT _SOURCE_RUN_ID) runs
FROM t;

-- [S13] synonym_join_taxonomic_units
WITH s AS (SELECT TSN, TSN_ACCEPTED FROM LIBRARY_MARTS.REFERENCE.REFERENCE__FED_ITIS_SYNONYM_LINKS),
tu AS (SELECT TSN, NAME_USAGE, COMPLETE_NAME FROM LIBRARY_MARTS.REFERENCE.REFERENCE__FED_ITIS_TAXONOMIC_UNITS),
top5 AS (SELECT TSN_ACCEPTED, COUNT(*) c FROM s GROUP BY 1 ORDER BY 2 DESC LIMIT 5)
SELECT 'synonym side' side, COALESCE(tu.NAME_USAGE::VARCHAR, '(no taxon row)') label, COUNT(*) n FROM s LEFT JOIN tu ON s.TSN = tu.TSN GROUP BY 1, 2
UNION ALL SELECT 'accepted side', COALESCE(tu.NAME_USAGE::VARCHAR, '(no taxon row)'), COUNT(*) FROM s LEFT JOIN tu ON s.TSN_ACCEPTED = tu.TSN GROUP BY 1, 2
UNION ALL SELECT 'unaccepted names with no link', tu.NAME_USAGE::VARCHAR, COUNT(*) FROM tu WHERE tu.NAME_USAGE IN ('invalid', 'not accepted') AND tu.TSN NOT IN (SELECT TSN FROM s) GROUP BY 1, 2
UNION ALL SELECT 'top accepted', COALESCE(tu.COMPLETE_NAME, '?') || ' (' || top5.TSN_ACCEPTED || ')', top5.c FROM top5 LEFT JOIN tu ON top5.TSN_ACCEPTED = tu.TSN
ORDER BY 1, 3 DESC;

-- [S14] nodc_code_reuse
WITH t AS (SELECT TSN, NODC_ID FROM LIBRARY_MARTS.REFERENCE.REFERENCE__FED_ITIS_NODC_IDS),
tu AS (SELECT TSN, NAME_USAGE, COMPLETE_NAME FROM LIBRARY_MARTS.REFERENCE.REFERENCE__FED_ITIS_TAXONOMIC_UNITS),
m AS (SELECT NODC_ID FROM t GROUP BY 1 HAVING COUNT(*) > 1),
j AS (SELECT t.NODC_ID, t.TSN, tu.NAME_USAGE u, tu.COMPLETE_NAME nm FROM t JOIN m ON t.NODC_ID = m.NODC_ID LEFT JOIN tu ON t.TSN = tu.TSN),
per AS (SELECT NODC_ID, COUNT(*) c, COUNT_IF(u IN ('valid', 'accepted')) n_ok FROM j GROUP BY 1),
top1 AS (SELECT NODC_ID FROM per ORDER BY c DESC, NODC_ID LIMIT 1)
SELECT 'codes with >1 TSN' k, COUNT(*)::VARCHAR v FROM per
UNION ALL SELECT 'rows on those codes', SUM(c)::VARCHAR FROM per
UNION ALL SELECT 'codes with exactly 1 accepted TSN', COUNT_IF(n_ok = 1)::VARCHAR FROM per
UNION ALL SELECT 'codes with 0 accepted TSN', COUNT_IF(n_ok = 0)::VARCHAR FROM per
UNION ALL SELECT 'codes with 2+ accepted TSN', COUNT_IF(n_ok >= 2)::VARCHAR FROM per
UNION ALL SELECT 'top code ' || MAX(j.NODC_ID), LISTAGG(j.nm || ' [' || j.u || ']', '; ') WITHIN GROUP (ORDER BY j.u DESC, j.nm) FROM j JOIN top1 ON j.NODC_ID = top1.NODC_ID;

-- [S15] county_ct_impact
WITH ct_old AS (SELECT column1 g FROM VALUES ('09001'), ('09003'), ('09005'), ('09007'), ('09009'), ('09011'), ('09013'), ('09015')),
dp AS (SELECT LPAD(TRY_TO_NUMBER(FIPS::VARCHAR)::VARCHAR, 5, '0') g, YEAR y FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CDC_DRUG_POISONING_COUNTY),
iv AS (SELECT LPAD(TRY_TO_NUMBER(GEOID::VARCHAR)::VARCHAR, 5, '0') g, PERIOD p FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CDC_INJURY_VIOLENCE_COUNTY)
SELECT 'dim_county CT population_2020' k, SUM(POPULATION_2020)::VARCHAR v FROM LIBRARY_MARTS.CORE.DIM_COUNTY WHERE LPAD(TRY_TO_NUMBER(STATE_FIPS::VARCHAR)::VARCHAR, 2, '0') = '09'
UNION ALL SELECT 'dim_county CT rows', COUNT(*)::VARCHAR FROM LIBRARY_MARTS.CORE.DIM_COUNTY WHERE LPAD(TRY_TO_NUMBER(STATE_FIPS::VARCHAR)::VARCHAR, 2, '0') = '09'
UNION ALL SELECT 'drug_poisoning CT old-code rows', COUNT(*)::VARCHAR FROM dp WHERE g IN (SELECT g FROM ct_old)
UNION ALL SELECT 'drug_poisoning CT years', MIN(y)::VARCHAR || '-' || MAX(y)::VARCHAR FROM dp WHERE g IN (SELECT g FROM ct_old)
UNION ALL SELECT 'drug_poisoning rows off-map (no CB match, county-level)', COUNT(*)::VARCHAR FROM dp WHERE TRY_TO_NUMBER(g) >= 1000 AND g NOT IN (SELECT GEOID::VARCHAR FROM LIBRARY_MARTS.REFERENCE.REFERENCE__CENSUS_CB_COUNTY)
UNION ALL SELECT 'drug_poisoning county-level rows', COUNT(*)::VARCHAR FROM dp WHERE TRY_TO_NUMBER(g) >= 1000
UNION ALL SELECT 'injury CT old-code rows', COUNT(*)::VARCHAR FROM iv WHERE g IN (SELECT g FROM ct_old)
UNION ALL SELECT 'injury CT periods', COUNT(DISTINCT p)::VARCHAR FROM iv WHERE g IN (SELECT g FROM ct_old);
