-- deep3/g50: deep pass 3, 2026-09-24. Python door (connect/db.py), read-only SELECT/WITH only, QUERY_TAG 'deep3-2026-09-24'.
-- Every connection first ran: ALTER SESSION SET STATEMENT_TIMEOUT_IN_SECONDS = 300; ALTER SESSION SET QUERY_TAG = 'deep3-2026-09-24'. Those two are not counted.
-- Tables: JUSTICE__STATE_MO_SEX_OFFENDER_REGISTRY, JUSTICE__FED_COURTLISTENER_COURTHOUSES, JUSTICE__FED_COURTLISTENER_RACE_CODES,
--         JUSTICE__FED_DOJ_FCA_SETTLEMENTS, JUSTICE__FED_SCDB.
-- 13 statements (S01-S13), all below, in run order (4 connections: b1 = S01-S06, b2 = S07-S11, b3 = S12, b4 = S13).
-- S07, S08, S10, S11 are extracts. The address join, peer groups, chain shares, term windows and petition ratios ran locally in pandas (g50/ scratch).
-- Outputs: g50/out_Sxx.txt and g50/out_Sxx.csv.

-- S01 MO registry: profile, persons vs rows, compliance, tier, state, load runs, address notes
SELECT COUNT(*) n, COUNT(DISTINCT REGISTRANT_NAME, DATE_OF_BIRTH) persons, COUNT(DISTINCT REGISTRANT_NAME) names,
       COUNT(DISTINCT REGISTRANT_NAME, DATE_OF_BIRTH, OFFENSE) person_offense, 
       COUNT(DISTINCT REGISTRANT_NAME, DATE_OF_BIRTH, ADDRESS) person_addr,
       COUNT_IF(IS_COMPLIANT) comp_t, COUNT_IF(NOT IS_COMPLIANT) comp_f, COUNT_IF(IS_COMPLIANT IS NULL) comp_null,
       ARRAY_AGG(DISTINCT TIER) tiers, COUNT(DISTINCT STATE) states, COUNT_IF(STATE <> 'MO') not_mo,
       COUNT(DISTINCT COUNTY) counties, COUNT(DISTINCT ZIP) zips, COUNT(DISTINCT _SOURCE_RUN_ID) runs,
       MIN(_INGESTED_AT) i0, MAX(_INGESTED_AT) i1, COUNT_IF(DATE_OF_BIRTH IS NULL) dob_null,
       COUNT_IF(ADDRESS ILIKE '%UNKNOWN%') addr_unknown, COUNT_IF(ADDRESS ILIKE '%INCARC%') addr_incarc,
       COUNT_IF(ADDRESS ILIKE '%MOVED%' OR ADDRESS ILIKE '%OUT OF STATE%') addr_moved, COUNT_IF(ADDRESS ILIKE '%HOMELESS%' OR ADDRESS ILIKE '%TRANSIENT%') addr_homeless,
       COUNT_IF(NULLIF(TRIM(ADDRESS),'') IS NULL) addr_blank, COUNT_IF(OFFENSE_COUNT IS NULL) oc_null,
       COUNT_IF(DATEDIFF(year, DATE_OF_BIRTH, '2026-09-24') >= 90) age90
FROM LIBRARY_MARTS.JUSTICE.JUSTICE__STATE_MO_SEX_OFFENDER_REGISTRY;

-- S02 MO registry: addresses with the most distinct persons, with compliance and tier mix
SELECT UPPER(TRIM(ADDRESS)) addr, UPPER(TRIM(CITY)) city, ZIP, COUNTY, COUNT(DISTINCT REGISTRANT_NAME, DATE_OF_BIRTH) persons, COUNT(*) n_rows,
       COUNT(DISTINCT IFF(NOT IS_COMPLIANT, REGISTRANT_NAME||DATE_OF_BIRTH, NULL)) noncomp_persons,
       MEDIAN(DATEDIFF(year, DATE_OF_BIRTH, '2026-09-24')) med_age, ARRAY_AGG(DISTINCT TIER) tiers
FROM LIBRARY_MARTS.JUSTICE.JUSTICE__STATE_MO_SEX_OFFENDER_REGISTRY
GROUP BY 1,2,3,4 ORDER BY persons DESC LIMIT 60;

-- S03 CourtListener race codes: the whole lookup
SELECT * FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_COURTLISTENER_RACE_CODES ORDER BY ID;

-- S04 CourtListener courthouses: confirm it is a one-row-per-court dimension; fill rates
SELECT COUNT(*) n, COUNT(DISTINCT ID) ids, COUNT(DISTINCT COURT_ID) court_ids, COUNT_IF(NULLIF(TRIM(ADDRESS1),'') IS NOT NULL) addr1,
       COUNT_IF(NULLIF(TRIM(CITY),'') IS NOT NULL) city, COUNT_IF(NULLIF(TRIM(STATE),'') IS NOT NULL) state, COUNT_IF(NULLIF(TRIM(ZIP_CODE),'') IS NOT NULL) zip,
       COUNT_IF(NULLIF(TRIM(COUNTY),'') IS NOT NULL) county, COUNT_IF(COURT_SEAT = 't') seat_t,
       (SELECT COUNT(*) FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_COURTLISTENER_COURTS) courts_rows,
       COUNT(DISTINCT IFF(COURT_ID IN (SELECT ID FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_COURTLISTENER_COURTS), COURT_ID, NULL)) court_ids_in_courts
FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_COURTLISTENER_COURTHOUSES;

-- S05 DOJ FCA settlements: every row
SELECT * FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_DOJ_FCA_SETTLEMENTS ORDER BY SETTLEMENT_DATE;

-- S06 SCDB: grain, duplicates, constant columns, and the unconstitutional flag vs its code
SELECT DECLARATION_UNCONSTITUTIONAL, IS_UNCONSTITUTIONAL_DECLARATION, COUNT(*) n, COUNT(DISTINCT CASE_ID) cases,
       COUNT(DISTINCT VOTE_ID) vote_ids, COUNT(DISTINCT CASE_ISSUES_ID, JUSTICE_CODE) issue_justice, COUNT(DISTINCT DOCKET_ID) dockets,
       ARRAY_AGG(DISTINCT SPLIT_VOTE) split_vals, MIN(TERM) t0, MAX(TERM) t1, MAX(DATE_DECISION) d1, COUNT(DISTINCT _SOURCE_RUN_ID) runs,
       COUNT_IF(IS_PETITIONER_WINNING) pw_t, COUNT_IF(PARTY_WINNING = 1) pw_code1, COUNT_IF(IS_PRECEDENT_ALTERED) prec_t, COUNT_IF(PRECEDENT_ALTERATION = 1) prec_code1
FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_SCDB
GROUP BY ROLLUP(1,2) ORDER BY 1,2;

-- S07 MO registry: full extract for local person-level, county and address work
SELECT REGISTRANT_NAME, ADDRESS, CITY, STATE, ZIP, COUNTY, OFFENSE, OFFENSE_COUNT, IS_COMPLIANT, TIER, DATE_OF_BIRTH
FROM LIBRARY_MARTS.JUSTICE.JUSTICE__STATE_MO_SEX_OFFENDER_REGISTRY;

-- S08 CMS nursing homes: every Missouri row, all columns, for the address join
SELECT * FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_NURSING_HOME WHERE STATE = 'MO';

-- S09 CMS nursing-home deficiencies, Missouri, per home: all, abuse tags F600-F610, harm level G+, complaint-driven
SELECT CMS_CERTIFICATION_NUMBER_CCN ccn, COUNT(*) n_def,
       COUNT_IF(DEFICIENCY_TAG_NUMBER IN ('0600','0602','0603','0604','0605','0606','0607','0608','0609','0610')) abuse_tags,
       COUNT_IF(SCOPE_SEVERITY_CODE >= 'G') harm_g_plus,
       COUNT_IF(SCOPE_SEVERITY_CODE >= 'G' AND DEFICIENCY_TAG_NUMBER IN ('0600','0602','0603','0604','0605','0606','0607','0608','0609','0610')) abuse_harm,
       COUNT_IF(DEFICIENCY_TAG_NUMBER = '0600') f600, COUNT_IF(COMPLAINT_DEFICIENCY = 'Y') complaint_def,
       MIN(SURVEY_DATE) s0, MAX(SURVEY_DATE) s1, COUNT(DISTINCT PROCESSING_DATE) proc_dates
FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_NURSING_HOME_DEFICIENCIES
WHERE STATE = 'MO'
GROUP BY 1;

-- S10 SCDB: one row per case, the case-level codes
SELECT CASE_ID, ANY_VALUE(DOCKET) docket, ANY_VALUE(CASE_NAME) case_name, ANY_VALUE(TERM) term, ANY_VALUE(DATE_DECISION) date_decision,
       ANY_VALUE(DATE_ARGUMENT) date_argument, ANY_VALUE(CHIEF_JUSTICE) chief, ANY_VALUE(COURT) court,
       ANY_VALUE(DECISION_TYPE_CODE) decision_type, ANY_VALUE(PETITIONER_CODE) pet, ANY_VALUE(PETITIONER_STATE_CODE) pet_state,
       ANY_VALUE(RESPONDENT_CODE) res, ANY_VALUE(RESPONDENT_STATE_CODE) res_state, ANY_VALUE(JURISDICTION_CODE) juris,
       ANY_VALUE(CASE_ORIGIN_CODE) origin, ANY_VALUE(CASE_ORIGIN_STATE_CODE) origin_state, ANY_VALUE(CASE_SOURCE_CODE) source,
       ANY_VALUE(CASE_SOURCE_STATE_CODE) source_state, ANY_VALUE(LC_DISAGREEMENT) lc_disagree, ANY_VALUE(CERT_REASON_CODE) cert_reason,
       ANY_VALUE(LC_DISPOSITION_CODE) lc_disp, ANY_VALUE(LC_DISPOSITION_DIRECTION_CODE) lc_dir, ANY_VALUE(DECLARATION_UNCONSTITUTIONAL) decl_uncon,
       ANY_VALUE(CASE_DISPOSITION_CODE) case_disp, ANY_VALUE(PARTY_WINNING) party_winning, ANY_VALUE(PRECEDENT_ALTERATION) prec_alt,
       ANY_VALUE(DECISION_DIRECTION_CODE) dec_dir, ANY_VALUE(ISSUE_CODE) issue, ANY_VALUE(ISSUE_AREA_CODE) issue_area,
       ANY_VALUE(LAW_TYPE_CODE) law_type, ANY_VALUE(MAJ_OPIN_WRITER_CODE) writer, ANY_VALUE(MAJ_OPIN_ASSIGNER_CODE) assigner,
       ANY_VALUE(MAJ_VOTES) maj_votes, ANY_VALUE(MIN_VOTES) min_votes, ANY_VALUE(US_CITATION) us_cite,
       COUNT(*) n_rows, COUNT(DISTINCT MAJ_VOTES, MIN_VOTES, PARTY_WINNING, DECISION_DIRECTION_CODE, TERM) n_variants
FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_SCDB
GROUP BY CASE_ID;

-- S11 SCDB: every justice vote, slim columns
SELECT CASE_ID, JUSTICE_CODE, JUSTICE_NAME, VOTE_CODE, OPINION_CODE, DIRECTION_CODE, MAJORITY_CODE, FIRST_AGREEMENT_CODE
FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_SCDB;

-- S12 MDS: Missouri homes, share of residents coded with schizophrenia (I6000 Yes), to test whether registrant placement just tracks psychiatric specialization
SELECT CCN, MAX(OVERALL_PERCENT) sz_pct, MAX(TRY_TO_NUMBER(TOTAL_RESIDENTS)) sz_n, ANY_VALUE(PROVIDER_NAME) name
FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_FACILITY_LEVEL_MINIMUM_DATA_SET_FREQUENCY
WHERE STATE = 'MO' AND MDS_ITEM_QUESTION_DESCRIPTION LIKE 'I6000:%' AND MDS_ITEM_RESPONSE = 'Yes'
GROUP BY 1;

-- S13 CourtListener Supreme Court dockets by filing year and the kind of court appealed from (state vs federal), with cert grants and denials: tests whether state-court petitions fell or only grants did
WITH d AS (
  SELECT YEAR(TRY_TO_DATE(DATE_FILED::string)) y, NULLIF(TRIM(APPEAL_FROM_ID),'') af,
         NULLIF(TRIM(DATE_CERT_GRANTED::string),'') g, NULLIF(TRIM(DATE_CERT_DENIED::string),'') dn
  FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_COURTLISTENER_DOCKETS
  WHERE COURT_ID = 'scotus')
SELECT d.y, CASE WHEN d.af IS NULL THEN 'blank' WHEN c.JURISDICTION LIKE 'S%' THEN 'state' WHEN c.JURISDICTION LIKE 'F%' THEN 'federal' ELSE 'other:'||COALESCE(c.JURISDICTION,'?') END kind,
       COUNT(*) n, COUNT(d.g) granted, COUNT(d.dn) denied
FROM d LEFT JOIN LIBRARY_MARTS.JUSTICE.JUSTICE__FED_COURTLISTENER_COURTS c ON c.ID = d.af
WHERE d.y >= 2000 OR d.y IS NULL
GROUP BY 1,2 ORDER BY 1,2;
