-- deep3/g55: deep pass 3, 2026-09-24. Python door (connect/db.py), read-only SELECT/WITH only, QUERY_TAG 'deep3-2026-09-24'.
-- Every connection first ran: ALTER SESSION SET STATEMENT_TIMEOUT_IN_SECONDS = 300; ALTER SESSION SET QUERY_TAG = 'deep3-2026-09-24'. Those two are not counted.
-- Tables: ECONOMICS__FED_PBGC_DATA, ECONOMICS__FED_FOREIGNASSISTANCE, ECONOMICS__FED_US_USASPENDING_API,
--         ECONOMICS__FED_TREASURY_DTS_DEPOSITS, ECONOMICS__FED_IRS_527_ORGS.
-- 13 statements (S01-S13), all below, in run order. S12 timed out at 300s and still counts.
-- S01-S05 pulled the five tables whole; the time, peer and trap math ran locally (g55/analyze.py, output in g55/analyze_out.txt).
-- Outputs: g55/out_Sxx.txt and g55/out_Sxx.csv.
-- Known misfires: S07 read all 300 rows as grants (CFDA_NUMBER is '' on contracts, not NULL); S09 redoes it.
--                 S12 timed out (R2 ACTION_DATE is text, full-table MIN/MAX); S13 redoes it without that.

-- S01 PBGC data: whole table pull (134.5K rows), worked locally
SELECT * FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_PBGC_DATA;

-- S02 Foreign assistance: whole table pull (95.7K rows), worked locally
SELECT * FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_FOREIGNASSISTANCE;

-- S03 USAspending API: whole table pull (300 rows)
SELECT * FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_US_USASPENDING_API;

-- S04 IRS 527 orgs: whole table pull (77.6K rows), worked locally
SELECT * FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_IRS_527_ORGS;

-- S05 Treasury DTS: whole table pull of the working columns (478K rows), worked locally
SELECT RECORD_DATE, ACCOUNT_TYPE, TRANSACTION_TYPE, TRANSACTION_CATG, TRANSACTION_CATG_DESC,
       TRANSACTION_TODAY_AMT, TRANSACTION_MTD_AMT, TRANSACTION_FYTD_AMT, SRC_LINE_NBR, TABLE_NBR, RECORD_FISCAL_YEAR
FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_TREASURY_DTS_DEPOSITS;

-- S06 Landing check: do the raw PBGC and foreign-aid loads hold a column header or dollar column the mart lost?
SELECT TABLE_NAME, COUNT(*) n_cols, LISTAGG(COLUMN_NAME, ', ') WITHIN GROUP (ORDER BY ORDINAL_POSITION) cols
FROM LIBRARY_RAW.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'LANDING' AND (TABLE_NAME ILIKE '%PBGC_DATA%' OR TABLE_NAME ILIKE '%FOREIGNASSIST%')
GROUP BY 1 ORDER BY 1;

-- S07 USAspending API sample: do its 300 award IDs already sit in the full contract and assistance tables?
WITH api AS (
  SELECT AWARD_ID, IFF(CFDA_NUMBER IS NOT NULL, 'grant', 'contract') kind, AWARD_AMOUNT
  FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_US_USASPENDING_API
), c AS (
  SELECT DISTINCT AWARD_ID_PIID id FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_USASPENDING_CONTRACTS_FULL_R2
  WHERE AWARD_ID_PIID IN (SELECT AWARD_ID FROM api WHERE kind = 'contract')
), a AS (
  SELECT DISTINCT AWARD_ID_FAIN id FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_USASPENDING_ASSISTANCE_FULL
  WHERE AWARD_ID_FAIN IN (SELECT AWARD_ID FROM api WHERE kind = 'grant')
)
SELECT api.kind, COUNT(*) n, COUNT(c.id) in_contracts_r2, COUNT(a.id) in_assistance_full, MIN(AWARD_AMOUNT) min_amt
FROM api LEFT JOIN c ON api.AWARD_ID = c.id LEFT JOIN a ON api.AWARD_ID = a.id
GROUP BY 1;

-- S08 Monthly Treasury Statement: customs duties gross, refunds, net, by month from FY2024 (second source for the DTS CBP outflow)
SELECT RECORD_DATE, RECORD_FISCAL_YEAR, CLASSIFICATION_ID, CLASSIFICATION_DESC, SEQUENCE_NUMBER_CD,
       CURRENT_MONTH_GROSS_RCPT_AMT, CURRENT_MONTH_REFUND_AMT, CURRENT_MONTH_NET_RCPT_AMT,
       CURRENT_FYTD_GROSS_RCPT_AMT, CURRENT_FYTD_REFUND_AMT, CURRENT_FYTD_NET_RCPT_AMT,
       PRIOR_FYTD_REFUND_AMT
FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_TREASURY_MTS_RECEIPTS
WHERE CLASSIFICATION_DESC ILIKE '%customs%' AND RECORD_DATE >= '2023-10-01'
ORDER BY RECORD_DATE, SEQUENCE_NUMBER_CD;

-- S09 USAspending API sample, redo of S07: CFDA_NUMBER is an empty string, not NULL, on the 200 contracts. Land rate of the contracts in CONTRACTS_FULL_R2
WITH api AS (
  SELECT AWARD_ID, IFF(NULLIF(TRIM(CFDA_NUMBER), '') IS NOT NULL, 'grant', 'contract') kind, AWARD_AMOUNT
  FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_US_USASPENDING_API
), c AS (
  SELECT DISTINCT AWARD_ID_PIID id FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_USASPENDING_CONTRACTS_FULL_R2
  WHERE AWARD_ID_PIID IN (SELECT AWARD_ID FROM api WHERE kind = 'contract')
)
SELECT api.kind, COUNT(*) n, COUNT(c.id) in_contracts_r2, COUNT_IF(CFDA_BLANK) cfda_blank_string
FROM (SELECT api.*, TRUE AS CFDA_BLANK FROM api) api LEFT JOIN c ON api.AWARD_ID = c.id
GROUP BY 1;

-- S10 MTS customs duties, full history: monthly gross, refunds, net, and how far back the table goes
SELECT RECORD_DATE, CLASSIFICATION_DESC, SEQUENCE_NUMBER_CD,
       CURRENT_MONTH_GROSS_RCPT_AMT, CURRENT_MONTH_REFUND_AMT, CURRENT_MONTH_NET_RCPT_AMT, CURRENT_FYTD_NET_RCPT_AMT
FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_TREASURY_MTS_RECEIPTS
WHERE CLASSIFICATION_DESC ILIKE 'customs%'
ORDER BY RECORD_DATE, SEQUENCE_NUMBER_CD;

-- S11 MTS trap test: across every receipt line, is the monthly net blank exactly when refunds exceed gross?
SELECT (CURRENT_MONTH_REFUND_AMT > CURRENT_MONTH_GROSS_RCPT_AMT) refund_gt_gross,
       (CURRENT_MONTH_NET_RCPT_AMT IS NULL) net_blank,
       COUNT(*) n, COUNT(DISTINCT CLASSIFICATION_DESC) lines, MIN(RECORD_DATE) d0, MAX(RECORD_DATE) d1,
       ARRAY_SLICE(ARRAY_AGG(DISTINCT CLASSIFICATION_DESC), 0, 8) examples
FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_TREASURY_MTS_RECEIPTS
WHERE CURRENT_MONTH_GROSS_RCPT_AMT IS NOT NULL AND CURRENT_MONTH_REFUND_AMT IS NOT NULL
GROUP BY 1, 2 ORDER BY 1, 2;

-- S12 USAspending API sample: which of its 200 big contracts miss CONTRACTS_FULL_R2, and what R2 holds for the ones that land (action-date span, rows)
WITH api AS (
  SELECT AWARD_ID, RECIPIENT_NAME, AWARDING_AGENCY_NAME, START_DATE, END_DATE, LAST_MODIFIED_DATE, AWARD_AMOUNT
  FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_US_USASPENDING_API
  WHERE NULLIF(TRIM(CFDA_NUMBER), '') IS NULL
), c AS (
  SELECT AWARD_ID_PIID id, COUNT(*) r2_rows, MIN(ACTION_DATE) r2_first_action, MAX(ACTION_DATE) r2_last_action,
         SUM(TRY_TO_DOUBLE(FEDERAL_ACTION_OBLIGATION::STRING)) r2_obligated
  FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_USASPENDING_CONTRACTS_FULL_R2
  WHERE AWARD_ID_PIID IN (SELECT AWARD_ID FROM api)
  GROUP BY 1
)
SELECT api.*, c.r2_rows, c.r2_first_action, c.r2_last_action, c.r2_obligated,
       (SELECT MIN(ACTION_DATE) FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_USASPENDING_CONTRACTS_FULL_R2) r2_min_action,
       (SELECT MAX(ACTION_DATE) FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_USASPENDING_CONTRACTS_FULL_R2) r2_max_action
FROM api LEFT JOIN c ON api.AWARD_ID = c.id
ORDER BY c.id IS NULL DESC, api.AWARD_AMOUNT DESC;

-- S13 Redo of S12 without the full-table MIN/MAX (ACTION_DATE is text; S12 timed out at 300s). Which of the 200 contracts miss R2
WITH api AS (
  SELECT AWARD_ID, RECIPIENT_NAME, AWARDING_AGENCY_NAME, START_DATE, END_DATE, LAST_MODIFIED_DATE, AWARD_AMOUNT
  FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_US_USASPENDING_API
  WHERE NULLIF(TRIM(CFDA_NUMBER), '') IS NULL
), c AS (
  SELECT AWARD_ID_PIID id, COUNT(*) r2_rows, MIN(ACTION_DATE) r2_first_action, MAX(ACTION_DATE) r2_last_action
  FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_USASPENDING_CONTRACTS_FULL_R2
  WHERE AWARD_ID_PIID IN (SELECT AWARD_ID FROM api)
  GROUP BY 1
)
SELECT api.*, c.r2_rows, c.r2_first_action, c.r2_last_action
FROM api LEFT JOIN c ON api.AWARD_ID = c.id
ORDER BY c.id IS NULL DESC, api.AWARD_AMOUNT DESC;

