-- deep3/g57: deep pass 3, 2026-09-24. Python door (connect/db.py), read-only SELECT/WITH only, QUERY_TAG 'deep3-2026-09-24'.
-- Every connection first ran: ALTER SESSION SET STATEMENT_TIMEOUT_IN_SECONDS = 300; ALTER SESSION SET QUERY_TAG = 'deep3-2026-09-24'. Those two are not counted.
-- Tables: ECONOMICS__FED_BLS_QCEW, ECONOMICS__FED_IRS_990, ECONOMICS__FED_TREASURY_DEBT_OUTSTANDING, ECONOMICS__FED_IRS_REVOCATION, ECONOMICS__FED_USASPENDING_TOPTIER_AGENCIES.
-- 24 statements (S01-S24), all below, in run order. S07 failed on a cast (FEDERAL_ACTION_OBLIGATION is FLOAT, not text) and still counts; S11 is its rerun.
-- Peer, time and join math on the extracts ran locally in pandas (g57/cov.py, cov2.py, cov3.py). Outputs: g57/out_Sxx.txt and .csv.

-- S01 QCEW profile: year x aggregation level, rows, areas, hidden rows, key repeats, size code, quarter
SELECT YEAR, AGGREGATION_LEVEL_CODE agg, COUNT(*) n, COUNT(DISTINCT AREA_FIPS) areas,
       COUNT(DISTINCT AREA_FIPS, OWNERSHIP_CODE, INDUSTRY_CODE) keys_,
       COUNT_IF(DISCLOSURE_CODE = 'N') hidden, COUNT_IF(ANNUAL_AVG_EMPLOYMENT = 0) emp0,
       SUM(ANNUAL_AVG_EMPLOYMENT) emp, ARRAY_AGG(DISTINCT OWNERSHIP_CODE) owns,
       COUNT(DISTINCT SIZE_CODE) sizes, COUNT(DISTINCT QUARTER) qtrs, MIN(INDUSTRY_CODE) ind0, MAX(INDUSTRY_CODE) ind1
FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_BLS_QCEW
GROUP BY 1,2 ORDER BY 1,2;

-- S02 IRS revocation: date text shapes, reinstatement flag vs date, ranges
SELECT REGEXP_REPLACE(REVOCATION_DATE,'[0-9]','9') rev_shape, REGEXP_REPLACE(COALESCE(REINSTATEMENT_DATE,'<null>'),'[0-9]','9') rein_shape,
       WAS_REINSTATED, COUNT(*) n, COUNT(DISTINCT EIN) eins, MIN(REVOCATION_DATE) r0, MAX(REVOCATION_DATE) r1,
       MIN(REINSTATEMENT_DATE) i0, MAX(REINSTATEMENT_DATE) i1, COUNT_IF(LENGTH(EIN) <> 9) ein_not9, COUNT_IF(EIN = '000000000') ein0,
       MIN(_LOADED_AT) l0, MAX(_LOADED_AT) l1, ANY_VALUE(_SOURCE_URL) src
FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_IRS_REVOCATION
GROUP BY 1,2,3 ORDER BY n DESC;

-- S03 Treasury debt outstanding: the whole table (237 rows)
SELECT * FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_TREASURY_DEBT_OUTSTANDING ORDER BY RECORD_DATE;

-- S04 USAspending toptier agencies: the whole table (111 rows)
SELECT * FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_USASPENDING_TOPTIER_AGENCIES ORDER BY BUDGET_AUTHORITY_AMOUNT DESC NULLS LAST;

-- S05 IRS 990: fill per column, year range, form types, source
SELECT COUNT(*) n, COUNT(DISTINCT EIN) eins, COUNT(ORGANIZATION_NAME) names, COUNT(TAX_PERIOD_BEGIN_DATE) tpb, COUNT(TAX_PERIOD_END_DATE) tpe,
       ARRAY_AGG(DISTINCT FORM_TYPE) forms, MIN(TAX_YEAR) ty0, MAX(TAX_YEAR) ty1, COUNT(GROSS_RECEIPTS_AMT) gross, COUNT(TOTAL_REVENUE_AMT) rev,
       COUNT(TOTAL_EXPENSES_AMT) exp_, COUNT(OFFICER_COMPENSATION_AMT) offc, COUNT(NULLIF(STATE,'')) st, COUNT(NULLIF(ZIP_CODE,'')) zip,
       COUNT(NULLIF(EXEMPTION_CODE,'')) exc, COUNT(DISTINCT _SOURCE_URL) srcs, ANY_VALUE(_SOURCE_URL) src,
       MIN(_LOADED_AT) l0, MAX(_LOADED_AT) l1, ARRAY_AGG(DISTINCT LEFT(EIN,2)) WITHIN GROUP (ORDER BY LEFT(EIN,2)) ein_prefixes
FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_IRS_990;

-- S06 Toptier time check: federal assistance obligations by awarding agency and fiscal year, Oct-Jun window vs full year, FY2019-FY2026
SELECT AWARDING_AGENCY_CODE code, ANY_VALUE(AWARDING_AGENCY_NAME) agency, ACTION_DATE_FISCAL_YEAR fy,
       SUM(IFF(MONTH(ACTION_DATE) NOT IN (7,8,9), FEDERAL_ACTION_OBLIGATION, 0)) oblig_oct_jun,
       SUM(FEDERAL_ACTION_OBLIGATION) oblig_full,
       COUNT(DISTINCT IFF(MONTH(ACTION_DATE) NOT IN (7,8,9) AND ACTION_TYPE_CODE = 'A', ASSISTANCE_AWARD_UNIQUE_KEY, NULL)) new_awards_oct_jun,
       SUM(IFF(MONTH(ACTION_DATE) NOT IN (7,8,9) AND ACTION_TYPE_CODE = 'A', FEDERAL_ACTION_OBLIGATION, 0)) new_oblig_oct_jun,
       COUNT(*) n, MAX(ACTION_DATE) last_action
FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_USASPENDING_ASSISTANCE_FULL
WHERE ACTION_DATE_FISCAL_YEAR >= 2019
GROUP BY 1,3 ORDER BY 1,3;

-- S07 Toptier time check: contract obligations by awarding agency and fiscal year, Oct-Jun window, FY2019-FY2026 (R2, text dates parsed)
WITH t AS (
  SELECT AWARDING_AGENCY_NAME agency, TRY_TO_DATE(ACTION_DATE) d, TRY_TO_NUMBER(FEDERAL_ACTION_OBLIGATION, 38, 2) amt
  FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_USASPENDING_CONTRACTS_FULL_R2
  WHERE LEFT(ACTION_DATE, 4) >= '2018'
)
SELECT agency, YEAR(DATEADD(month, 3, d)) fy,
       SUM(IFF(MONTH(d) NOT IN (7,8,9), amt, 0)) oblig_oct_jun, SUM(amt) oblig_full, COUNT(*) n,
       COUNT_IF(d IS NULL) bad_date, COUNT_IF(amt IS NULL) bad_amt, MAX(d) last_action
FROM t
GROUP BY 1,2 HAVING fy >= 2019 OR fy IS NULL ORDER BY 1,2;

-- S08 QCEW private jobs by state x industry (4- and 6-digit NAICS) plus state private totals, 2022, for the OSHA coverage join
SELECT AREA_FIPS, AGGREGATION_LEVEL_CODE agg, INDUSTRY_CODE, DISCLOSURE_CODE, ANNUAL_AVG_ESTABLISHMENTS estabs,
       ANNUAL_AVG_EMPLOYMENT emp, AVG_ANNUAL_PAY pay
FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_BLS_QCEW
WHERE OWNERSHIP_CODE = '5' AND AGGREGATION_LEVEL_CODE IN ('51','56','58');

-- S09 OSHA 300A worksite summaries 2023 and 2024, one row per worksite (latest submission), rolled up by state x NAICS x employer type
WITH u AS (
  SELECT '2023' yr, ESTABLISHMENT_ID, STATE, NAICS_CODE, ESTABLISHMENT_TYPE, SIZE, ANNUAL_AVERAGE_EMPLOYEES emp, TOTAL_HOURS_WORKED hrs, TOTAL_DAFW_CASES dafw, TOTAL_DEATHS deaths, CREATED_TIMESTAMP ts
  FROM LIBRARY_MARTS.LABOR.LABOR__FED_OSHA_ITA_300A_SUMMARY_2023
  UNION ALL
  SELECT '2024', ESTABLISHMENT_ID, STATE, NAICS_CODE, ESTABLISHMENT_TYPE, SIZE, ANNUAL_AVERAGE_EMPLOYEES, TOTAL_HOURS_WORKED, TOTAL_DAFW_CASES, TOTAL_DEATHS, CREATED_TIMESTAMP
  FROM LIBRARY_MARTS.LABOR.LABOR__FED_OSHA_ITA_300A_SUMMARY_2024
), d AS (
  SELECT * FROM u QUALIFY ROW_NUMBER() OVER (PARTITION BY yr, ESTABLISHMENT_ID ORDER BY ts DESC NULLS LAST) = 1
)
SELECT yr, UPPER(TRIM(STATE)) st, NAICS_CODE naics, ESTABLISHMENT_TYPE etype, COUNT(*) sites, SUM(emp) emp,
       COUNT_IF(emp >= 20) sites20, SUM(IFF(emp >= 20, emp, 0)) emp20, SUM(hrs) hrs, SUM(dafw) dafw, SUM(deaths) deaths
FROM d GROUP BY 1,2,3,4;

-- S10 QCEW traps: YOY columns, pay consistency, county total vs ownership sum, hidden rows that still count workplaces
WITH c70 AS (SELECT AREA_FIPS, ANNUAL_AVG_EMPLOYMENT emp FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_BLS_QCEW WHERE AGGREGATION_LEVEL_CODE = '70'),
     c71 AS (SELECT AREA_FIPS, SUM(ANNUAL_AVG_EMPLOYMENT) emp, COUNT_IF(DISCLOSURE_CODE = 'N') hid FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_BLS_QCEW WHERE AGGREGATION_LEVEL_CODE = '71' GROUP BY 1),
     q AS (SELECT * FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_BLS_QCEW)
SELECT 'yoy' k, COUNT(*) n, COUNT_IF(YOY_EMPLOYMENT_PCT_CHANGE = 0) v1, COUNT_IF(YOY_EMPLOYMENT_PCT_CHANGE IS NULL) v2,
       COUNT_IF(YOY_EMPLOYMENT_PCT_CHANGE = 0 AND DISCLOSURE_CODE = 'N') v3, COUNT_IF(YOY_WAGES_PCT_CHANGE = 0) v4, NULL v5
FROM q
UNION ALL
SELECT 'hidden_rows', COUNT_IF(DISCLOSURE_CODE = 'N'), COUNT_IF(DISCLOSURE_CODE = 'N' AND ANNUAL_AVG_ESTABLISHMENTS > 0),
       COUNT_IF(DISCLOSURE_CODE = 'N' AND ANNUAL_AVG_EMPLOYMENT > 0), COUNT_IF(DISCLOSURE_CODE = 'N' AND TOTAL_ANNUAL_WAGES > 0),
       COUNT_IF(COALESCE(DISCLOSURE_CODE,'') NOT IN ('N','') ), COUNT_IF(DISCLOSURE_CODE IS NULL)
FROM q
UNION ALL
SELECT 'pay_check', COUNT_IF(ANNUAL_AVG_EMPLOYMENT > 0),
       COUNT_IF(ANNUAL_AVG_EMPLOYMENT > 0 AND ABS(AVG_ANNUAL_PAY - TOTAL_ANNUAL_WAGES / ANNUAL_AVG_EMPLOYMENT) > 2),
       COUNT_IF(ANNUAL_AVG_EMPLOYMENT > 0 AND AVG_ANNUAL_PAY > 1000000), MAX(AVG_ANNUAL_PAY), MAX(ANNUAL_AVG_WEEKLY_WAGE), COUNT_IF(ANNUAL_AVG_EMPLOYMENT > 0 AND AVG_ANNUAL_PAY < 5000)
FROM q
UNION ALL
SELECT 'county_total_vs_owner_sum', COUNT(*), COUNT_IF(c71.emp IS NULL), COUNT_IF(c70.emp = c71.emp), COUNT_IF(c70.emp > c71.emp AND c71.hid > 0),
       COUNT_IF(c70.emp <> c71.emp AND c71.hid = 0), SUM(c70.emp - c71.emp)
FROM c70 LEFT JOIN c71 USING (AREA_FIPS);

-- S11 Toptier time check, rerun of S07 with casts that accept the real column types: contract obligations by agency and fiscal year, Oct-Jun window
WITH t AS (
  SELECT AWARDING_AGENCY_NAME agency, TRY_TO_DATE(ACTION_DATE::VARCHAR) d, TRY_TO_DOUBLE(FEDERAL_ACTION_OBLIGATION::VARCHAR) amt
  FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_USASPENDING_CONTRACTS_FULL_R2
  WHERE LEFT(ACTION_DATE::VARCHAR, 4) >= '2018'
)
SELECT agency, YEAR(DATEADD(month, 3, d)) fy,
       SUM(IFF(MONTH(d) NOT IN (7,8,9), amt, 0)) oblig_oct_jun, SUM(amt) oblig_full, COUNT(*) n,
       COUNT_IF(d IS NULL) bad_date, COUNT_IF(amt IS NULL) bad_amt, MAX(d) last_action
FROM t
GROUP BY 1,2 HAVING fy >= 2019 OR fy IS NULL ORDER BY 1,2;

-- S12 OSHA 300A 2023 and 2024 again, now with site-level sanity filters (1-50,000 workers, 500-4,500 hours per worker), private employers only
WITH u AS (
  SELECT '2023' yr, ESTABLISHMENT_ID, STATE, NAICS_CODE, ESTABLISHMENT_TYPE, ANNUAL_AVERAGE_EMPLOYEES emp, TOTAL_HOURS_WORKED hrs, TOTAL_DAFW_CASES dafw, CREATED_TIMESTAMP ts
  FROM LIBRARY_MARTS.LABOR.LABOR__FED_OSHA_ITA_300A_SUMMARY_2023
  UNION ALL
  SELECT '2024', ESTABLISHMENT_ID, STATE, NAICS_CODE, ESTABLISHMENT_TYPE, ANNUAL_AVERAGE_EMPLOYEES, TOTAL_HOURS_WORKED, TOTAL_DAFW_CASES, CREATED_TIMESTAMP
  FROM LIBRARY_MARTS.LABOR.LABOR__FED_OSHA_ITA_300A_SUMMARY_2024
), d AS (
  SELECT * FROM u QUALIFY ROW_NUMBER() OVER (PARTITION BY yr, ESTABLISHMENT_ID ORDER BY ts DESC NULLS LAST) = 1
)
SELECT yr, UPPER(TRIM(STATE)) st, NAICS_CODE naics,
       COUNT(*) sites_all, COUNT_IF(emp BETWEEN 1 AND 50000 AND hrs / NULLIF(emp,0) BETWEEN 500 AND 4500) sites_ok,
       SUM(IFF(emp BETWEEN 1 AND 50000 AND hrs / NULLIF(emp,0) BETWEEN 500 AND 4500, emp, 0)) emp_ok,
       SUM(IFF(emp BETWEEN 20 AND 50000 AND hrs / NULLIF(emp,0) BETWEEN 500 AND 4500, emp, 0)) emp20_ok,
       COUNT_IF(emp BETWEEN 20 AND 50000 AND hrs / NULLIF(emp,0) BETWEEN 500 AND 4500) sites20_ok,
       SUM(IFF(emp BETWEEN 1 AND 50000 AND hrs / NULLIF(emp,0) BETWEEN 500 AND 4500, dafw, 0)) dafw_ok
FROM d WHERE ESTABLISHMENT_TYPE = '1'
GROUP BY 1,2,3;

-- S13 NSF new grants by fiscal year, month and awarding office, FY2022-FY2026 (does the drop survive the Oct-Nov 2025 shutdown and span divisions?)
SELECT ACTION_DATE_FISCAL_YEAR fy, MONTH(ACTION_DATE) mo, AWARDING_OFFICE_NAME office,
       COUNT(DISTINCT IFF(ACTION_TYPE_CODE = 'A', ASSISTANCE_AWARD_UNIQUE_KEY, NULL)) new_awards,
       SUM(IFF(ACTION_TYPE_CODE = 'A', FEDERAL_ACTION_OBLIGATION, 0)) new_oblig,
       SUM(FEDERAL_ACTION_OBLIGATION) all_oblig, SUM(IFF(FEDERAL_ACTION_OBLIGATION < 0, FEDERAL_ACTION_OBLIGATION, 0)) deobligated
FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_USASPENDING_ASSISTANCE_FULL
WHERE AWARDING_AGENCY_CODE = '049' AND ACTION_DATE_FISCAL_YEAR >= 2022
GROUP BY 1,2,3;

-- S14 DHS contracts Oct-Jun: by sub-agency FY2023-FY2026, plus FY2026 top 25 recipients (is the jump a few awards?)
WITH t AS (
  SELECT AWARDING_SUB_AGENCY_NAME sub, RECIPIENT_NAME rcp, CONTRACT_AWARD_UNIQUE_KEY k, TRY_TO_DATE(ACTION_DATE::VARCHAR) d,
         TRY_TO_DOUBLE(FEDERAL_ACTION_OBLIGATION::VARCHAR) amt, PRODUCT_OR_SERVICE_CODE_DESCRIPTION psc
  FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_USASPENDING_CONTRACTS_FULL_R2
  WHERE AWARDING_AGENCY_NAME = 'Department of Homeland Security' AND LEFT(ACTION_DATE::VARCHAR, 4) >= '2022'
), w AS (SELECT *, YEAR(DATEADD(month, 3, d)) fy FROM t WHERE MONTH(d) NOT IN (7,8,9))
SELECT 'sub' kind, fy, sub name_, NULL psc_, SUM(amt) oblig, COUNT(DISTINCT k) awards FROM w WHERE fy >= 2023 GROUP BY 2,3
UNION ALL
SELECT * FROM (
  SELECT 'rcp', fy, rcp || ' | ' || ANY_VALUE(sub), ANY_VALUE(psc), SUM(amt), COUNT(DISTINCT k) FROM w WHERE fy = 2026 GROUP BY 2, rcp ORDER BY 5 DESC LIMIT 25
);

-- S15 OSHA 300A hospital filings (NAICS 622): every VT, NM, HI, WY and TN row, plus rows whose names point at big VT, NM or HI hospitals filed anywhere
WITH u AS (
  SELECT '2023' yr, ESTABLISHMENT_ID, ESTABLISHMENT_NAME, COMPANY_NAME, CITY, STATE, ZIP_CODE, NAICS_CODE, ESTABLISHMENT_TYPE, ANNUAL_AVERAGE_EMPLOYEES emp, TOTAL_HOURS_WORKED hrs
  FROM LIBRARY_MARTS.LABOR.LABOR__FED_OSHA_ITA_300A_SUMMARY_2023
  UNION ALL
  SELECT '2024', ESTABLISHMENT_ID, ESTABLISHMENT_NAME, COMPANY_NAME, CITY, STATE, ZIP_CODE, NAICS_CODE, ESTABLISHMENT_TYPE, ANNUAL_AVERAGE_EMPLOYEES, TOTAL_HOURS_WORKED
  FROM LIBRARY_MARTS.LABOR.LABOR__FED_OSHA_ITA_300A_SUMMARY_2024
)
SELECT yr, UPPER(TRIM(STATE)) st, CITY, ESTABLISHMENT_NAME, COMPANY_NAME, NAICS_CODE, ESTABLISHMENT_TYPE, emp, hrs
FROM u
WHERE (NAICS_CODE LIKE '622%' AND UPPER(TRIM(STATE)) IN ('VT','NM','HI','WY','TN'))
   OR REGEXP_LIKE(UPPER(ESTABLISHMENT_NAME || ' ' || COALESCE(COMPANY_NAME,'')),
      '.*(UNIVERSITY OF VERMONT|UVM |RUTLAND REGIONAL|CENTRAL VERMONT|PRESBYTERIAN HEALTHCARE|PRESBYTERIAN HOSPITAL|LOVELACE|CHRISTUS ST|SAN JUAN REGIONAL|MEMORIAL MEDICAL CENTER.*LAS CRUCES|QUEEN.S MEDICAL|KAPIOLANI|STRAUB|HAWAII PACIFIC HEALTH|PALI MOMI|WILCOX|ADVENTIST HEALTH CASTLE|EASTERN NEW MEXICO|GERALD CHAMPION|MOUNTAIN VIEW REGIONAL|CARLSBAD MEDICAL).*')
ORDER BY st, emp DESC;

-- S16 Fisher Sand & Gravel DHS contract rows FY2025-FY2026: repeats, ceilings, dates (does $13.35B hold up?)
SELECT CONTRACT_AWARD_UNIQUE_KEY k, AWARD_ID_PIID piid, ACTION_DATE, TRY_TO_DOUBLE(FEDERAL_ACTION_OBLIGATION::VARCHAR) amt,
       TRY_TO_DOUBLE(TOTAL_DOLLARS_OBLIGATED::VARCHAR) award_total, TRY_TO_DOUBLE(CURRENT_TOTAL_VALUE_OF_AWARD::VARCHAR) award_value,
       AWARD_TYPE, PRIMARY_PLACE_OF_PERFORMANCE_STATE_CODE pop_st, LEFT(TRANSACTION_DESCRIPTION, 120) descr, COUNT(*) OVER (PARTITION BY CONTRACT_AWARD_UNIQUE_KEY, ACTION_DATE, FEDERAL_ACTION_OBLIGATION) same_rows
FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_USASPENDING_CONTRACTS_FULL_R2
WHERE AWARDING_AGENCY_NAME = 'Department of Homeland Security' AND RECIPIENT_NAME ILIKE 'FISHER SAND%' AND LEFT(ACTION_DATE::VARCHAR, 4) >= '2024'
ORDER BY ACTION_DATE;

-- S17 OSHA 300A: biggest filers of any industry in VT, NM and HI (catches big hospitals filed under odd names or codes)
WITH u AS (
  SELECT '2023' yr, ESTABLISHMENT_NAME, COMPANY_NAME, CITY, STATE, NAICS_CODE, ESTABLISHMENT_TYPE, ANNUAL_AVERAGE_EMPLOYEES emp
  FROM LIBRARY_MARTS.LABOR.LABOR__FED_OSHA_ITA_300A_SUMMARY_2023
  UNION ALL
  SELECT '2024', ESTABLISHMENT_NAME, COMPANY_NAME, CITY, STATE, NAICS_CODE, ESTABLISHMENT_TYPE, ANNUAL_AVERAGE_EMPLOYEES
  FROM LIBRARY_MARTS.LABOR.LABOR__FED_OSHA_ITA_300A_SUMMARY_2024
)
SELECT yr, UPPER(TRIM(STATE)) st, CITY, ESTABLISHMENT_NAME, COMPANY_NAME, NAICS_CODE, ESTABLISHMENT_TYPE, emp
FROM u
WHERE (UPPER(TRIM(STATE)) = 'VT' AND emp >= 250) OR (UPPER(TRIM(STATE)) IN ('NM','HI') AND emp >= 700)
   OR (UPPER(TRIM(STATE)) IN ('VT','NM','HI') AND REGEXP_LIKE(UPPER(ESTABLISHMENT_NAME || ' ' || COALESCE(COMPANY_NAME,'')), '.*(MEDICAL CENTER|HOSPITAL|HEALTH).*') AND NAICS_CODE NOT LIKE '622%')
ORDER BY st, yr, emp DESC;

-- S18 IRS revocation vs its near-twin ECONOMICS__FED_IRS_AUTO_REVOCATIONS: EIN overlap, date and reinstatement agreement
WITH a AS (
  SELECT EIN, COUNT(*) n, MAX(TRY_TO_DATE(REVOCATION_DATE)) rd1, MAX(TRY_TO_DATE(REINSTATEMENT_DATE)) ri
  FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_IRS_REVOCATION GROUP BY 1
), b AS (
  SELECT EIN, COUNT(*) n, MAX(REVOCATION_DATE) rd1, MAX(REINSTATEMENT_DATE) ri
  FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_IRS_AUTO_REVOCATIONS GROUP BY 1
)
SELECT COUNT(*) eins, COUNT_IF(a.EIN IS NULL) only_auto, COUNT_IF(b.EIN IS NULL) only_rev, COUNT_IF(a.EIN IS NOT NULL AND b.EIN IS NOT NULL) both_,
       COUNT_IF(a.rd1 = b.rd1) same_last_rev, COUNT_IF(a.ri IS NOT DISTINCT FROM b.ri AND a.EIN IS NOT NULL AND b.EIN IS NOT NULL) same_rein,
       COUNT_IF(a.ri IS NULL AND b.ri IS NOT NULL AND a.EIN IS NOT NULL) rein_only_auto, COUNT_IF(a.ri IS NOT NULL AND b.ri IS NULL AND b.EIN IS NOT NULL) rein_only_rev,
       MIN(IFF(a.EIN IS NULL, b.rd1, NULL)) only_auto_rd_min, MAX(IFF(a.EIN IS NULL, b.rd1, NULL)) only_auto_rd_max,
       COUNT_IF(a.EIN IS NULL AND b.rd1 > '2026-03-15') only_auto_after_mar15,
       MIN(IFF(b.EIN IS NULL, a.rd1, NULL)) only_rev_rd_min, MAX(IFF(b.EIN IS NULL, a.rd1, NULL)) only_rev_rd_max,
       COUNT_IF(a.n <> b.n) diff_rowcount, MAX(b.ri) auto_rein_max, MAX(a.ri) rev_rein_max
FROM a FULL OUTER JOIN b USING (EIN);

-- S19 IRS revocation time series: by revocation month and by posting month, 501(c)(3) share, reinstated share, posting lag
SELECT 'rev_month' kind, DATE_TRUNC('month', TRY_TO_DATE(REVOCATION_DATE)) m, COUNT(*) n, COUNT_IF(EXEMPTION_TYPE = '03') c3,
       COUNT_IF(WAS_REINSTATED) rein, MEDIAN(DATEDIFF(day, TRY_TO_DATE(REVOCATION_DATE), TRY_TO_DATE(REVOCATION_POSTING_DATE))) lag_days
FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_IRS_REVOCATION GROUP BY 1,2
UNION ALL
SELECT 'post_month', DATE_TRUNC('month', TRY_TO_DATE(REVOCATION_POSTING_DATE)), COUNT(*), COUNT_IF(EXEMPTION_TYPE = '03'),
       COUNT_IF(WAS_REINSTATED), MEDIAN(DATEDIFF(day, TRY_TO_DATE(REVOCATION_DATE), TRY_TO_DATE(REVOCATION_POSTING_DATE)))
FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_IRS_REVOCATION GROUP BY 1,2
ORDER BY 1,2;

-- S20 Revoked, never reinstated, yet in today's IRS master file or Publication 78: split by ruling date vs revocation date and later filing
WITH r AS (
  SELECT EIN, MAX(TRY_TO_DATE(REVOCATION_DATE)) rd, BOOLOR_AGG(WAS_REINSTATED) rein, ANY_VALUE(EXEMPTION_TYPE) ex
  FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_IRS_REVOCATION GROUP BY 1
), bmf AS (
  SELECT EIN, MAX(RULING_DATE) rul, MAX(DEDUCTIBILITY_CODE) ded, MAX(REVENUE_AMT) rev, MAX(TAX_PERIOD_MONTH) tp
  FROM LIBRARY_MARTS.CORPORATE_REGISTRY.CORPORATE_REGISTRY__FED_IRS_EO_BMF GROUP BY 1
), p78 AS (SELECT DISTINCT EIN FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_IRS_PUB78_ELIGIBLE_DONEES)
SELECT r.rein, bmf.EIN IS NOT NULL in_bmf, bmf.ded, CASE WHEN bmf.rul IS NULL THEN 'no_ruling' WHEN bmf.rul > r.rd THEN 'ruling_after' ELSE 'ruling_before' END rul_vs,
       p78.EIN IS NOT NULL in_p78, IFF(bmf.tp > r.rd, 'filed_after', 'no') tp_after, COUNT(*) n, SUM(bmf.rev) rev_sum, MEDIAN(bmf.rev) rev_med, COUNT_IF(bmf.rev >= 1000000) rev_1m
FROM r LEFT JOIN bmf USING (EIN) LEFT JOIN p78 USING (EIN)
GROUP BY 1,2,3,4,5,6 ORDER BY n DESC;

-- S21 QCEW pay trap: does AVG_ANNUAL_PAY equal wages / jobs, by aggregation level
SELECT AGGREGATION_LEVEL_CODE agg, COUNT_IF(ANNUAL_AVG_EMPLOYMENT > 0) n,
       COUNT_IF(ANNUAL_AVG_EMPLOYMENT > 0 AND ABS(AVG_ANNUAL_PAY - TOTAL_ANNUAL_WAGES / ANNUAL_AVG_EMPLOYMENT) > 2) off_by_2,
       MEDIAN(IFF(ANNUAL_AVG_EMPLOYMENT > 0, AVG_ANNUAL_PAY / NULLIF(TOTAL_ANNUAL_WAGES / ANNUAL_AVG_EMPLOYMENT, 0), NULL)) med_ratio,
       MEDIAN(IFF(ANNUAL_AVG_EMPLOYMENT > 0, AVG_ANNUAL_PAY / NULLIF(ANNUAL_AVG_WEEKLY_WAGE * 52, 0), NULL)) med_ratio_weekly,
       ANY_VALUE(IFF(ANNUAL_AVG_EMPLOYMENT > 1000, AREA_FIPS || ' ' || INDUSTRY_CODE || ' emp=' || ANNUAL_AVG_EMPLOYMENT || ' wages=' || TOTAL_ANNUAL_WAGES || ' wk=' || ANNUAL_AVG_WEEKLY_WAGE || ' pay=' || AVG_ANNUAL_PAY, NULL)) sample_row
FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_BLS_QCEW
GROUP BY 1 ORDER BY 1;

-- S22 Revoked, no reinstatement in the file, master-file ruling date BEFORE the revocation, still in Pub 78, filed after: top 25 by revenue, plus revocation-year spread
WITH r AS (
  SELECT EIN, MAX(TRY_TO_DATE(REVOCATION_DATE)) rd, BOOLOR_AGG(WAS_REINSTATED) rein, ANY_VALUE(EXEMPTION_TYPE) ex, ANY_VALUE(LEGAL_NAME) nm, ANY_VALUE(STATE) st
  FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_IRS_REVOCATION GROUP BY 1
), bmf AS (
  SELECT EIN, MAX(RULING_DATE) rul, MAX(DEDUCTIBILITY_CODE) ded, MAX(REVENUE_AMT) rev, MAX(TAX_PERIOD_MONTH) tp, MAX(ORG_NAME) bnm, MAX(STATE) bst, MAX(SUBSECTION_CODE) sub, MAX(GROUP_EXEMPTION_NUM) grp
  FROM LIBRARY_MARTS.CORPORATE_REGISTRY.CORPORATE_REGISTRY__FED_IRS_EO_BMF GROUP BY 1
), p78 AS (SELECT DISTINCT EIN FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_IRS_PUB78_ELIGIBLE_DONEES),
x AS (
  SELECT r.*, bmf.rul, bmf.rev, bmf.tp, bmf.bnm, bmf.bst, bmf.sub, bmf.grp
  FROM r JOIN bmf USING (EIN) JOIN p78 USING (EIN)
  WHERE NOT r.rein AND bmf.rul <= r.rd AND bmf.tp > r.rd AND bmf.ded = '1'
)
SELECT * FROM (SELECT 'top' kind, EIN, nm, bnm, st, ex, sub, grp, rd, rul, tp, rev, NULL n FROM x ORDER BY rev DESC NULLS LAST LIMIT 25)
UNION ALL
SELECT 'year', NULL, NULL, NULL, NULL, NULL, NULL, NULL, DATE_TRUNC('year', rd), NULL, NULL, SUM(rev), COUNT(*) FROM x GROUP BY DATE_TRUNC('year', rd)
UNION ALL
SELECT 'grp', NULL, NULL, NULL, NULL, NULL, NULL, IFF(grp IS NULL OR grp IN ('0000','0'), 'none', 'group'), NULL, NULL, NULL, SUM(rev), COUNT(*) FROM x GROUP BY IFF(grp IS NULL OR grp IN ('0000','0'), 'none', 'group');

-- S23 OSHA 300A filing year 2025: hospital rows in VT, NM, HI, and any row naming the big absent systems
SELECT UPPER(TRIM(STATE)) st, CITY, ESTABLISHMENT_NAME, COMPANY_NAME, NAICS_CODE, ESTABLISHMENT_TYPE, ANNUAL_AVERAGE_EMPLOYEES emp, YEAR_FILING_FOR
FROM LIBRARY_MARTS.LABOR.LABOR__FED_OSHA_ITA_300A_SUMMARY_2025
WHERE (NAICS_CODE LIKE '622%' AND UPPER(TRIM(STATE)) IN ('VT','NM','HI'))
   OR REGEXP_LIKE(UPPER(ESTABLISHMENT_NAME || ' ' || COALESCE(COMPANY_NAME,'')),
      '.*(UNIVERSITY OF VERMONT MED|UVM|RUTLAND REGIONAL|CENTRAL VERMONT MED|PRESBYTERIAN HOSP|PRESBYTERIAN HEALTH|CHRISTUS ST.? VINCENT|SAN JUAN REGIONAL|QUEEN.S MEDICAL|QUEEN.S HEALTH|KAPIOLANI MEDICAL|HAWAII PACIFIC HEALTH|PALI MOMI|STRAUB MEDICAL|STRAUB BENIOFF|WILCOX MEDICAL|GERALD CHAMPION).*')
ORDER BY st, emp DESC;

-- S24 Treasury: debt series vs the debt-to-the-penny table on fiscal year-end dates, and fiscal 2026 so far vs the same window in earlier years
WITH p AS (
  SELECT RECORD_DATE, TOT_PUB_DEBT_OUT_AMT amt, YEAR(DATEADD(month, 3, RECORD_DATE)) fy
  FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_TREASURY_DEBT_TO_PENNY
), last_ AS (SELECT MAX(RECORD_DATE) d FROM p),
w AS (
  SELECT fy, MIN(RECORD_DATE) d0, MAX(IFF(DAYOFYEAR(DATEADD(month, 3, RECORD_DATE)) <= (SELECT DAYOFYEAR(DATEADD(month, 3, d)) FROM last_), RECORD_DATE, NULL)) d1
  FROM p GROUP BY fy
)
SELECT w.fy, w.d0, a.amt amt0, w.d1, b.amt amt1, b.amt - a.amt added_same_window, h.DEBT_OUTSTANDING_AMT hist_fy_end, e.amt penny_fy_end, (SELECT d FROM last_) last_date
FROM w JOIN p a ON a.RECORD_DATE = w.d0 JOIN p b ON b.RECORD_DATE = w.d1
LEFT JOIN LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_TREASURY_DEBT_OUTSTANDING h ON h.RECORD_DATE = DATE_FROM_PARTS(w.fy, 9, 30)
LEFT JOIN p e ON e.RECORD_DATE = DATE_FROM_PARTS(w.fy, 9, 30)
WHERE w.fy >= 2015 ORDER BY w.fy;

