-- deep3/g63: deep pass 3, 2026-09-24. Python door (connect/db.py), read-only SELECT/WITH only, QUERY_TAG 'deep3-2026-09-24'.
-- Every connection first ran: ALTER SESSION SET STATEMENT_TIMEOUT_IN_SECONDS = 300; ALTER SESSION SET QUERY_TAG = 'deep3-2026-09-24'. Those two are not counted.
-- Tables: ENERGY__FED_EIA860_6_2_ENVIROEQUIP, ENERGY__FED_EIA860_3_5_MULTIFUEL, ENERGY__FED_EIA861_SERVICE_TERRITORY, ENERGY__FED_EIA860_1_UTILITY, ENERGY__FED_EIA861_ADVANCED_METERS.
-- 12 statements (S01-S12), all below, in run order. Runner: g63/run.py. Outputs: g63/out_Sxx.csv. Local math: g63/coal.py, coal2.py, mf.py, am.py (+ inline pandas).
-- Note on S12: the ID list was edited once before it ran (wrong guesses swapped for IDs read from S08); only the version below ran.

-- S01 column names and types for the 5 tables and the join targets
SELECT TABLE_SCHEMA, TABLE_NAME, LISTAGG(COLUMN_NAME || ':' || LEFT(DATA_TYPE,4), ', ') WITHIN GROUP (ORDER BY ORDINAL_POSITION) cols
FROM LIBRARY_MARTS.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME IN ('ENERGY__FED_EIA860_6_2_ENVIROEQUIP','ENERGY__FED_EIA860_3_5_MULTIFUEL','ENERGY__FED_EIA861_SERVICE_TERRITORY',
  'ENERGY__FED_EIA860_1_UTILITY','ENERGY__FED_EIA861_ADVANCED_METERS','ENERGY__FED_EIA860_3_1_GENERATOR','ENERGY__FED_EIA860_2_PLANT',
  'ENERGY__FED_EIA860_6_1_ENVIROASSOC','ENVIRONMENT__FED_EPA_EGRID_PLANT_2022','ENERGY__FED_EIA861_SALES_ULT_CUST','ENERGY__FED_EIA861_RELIABILITY')
  AND COLUMN_NAME NOT LIKE 'PLANT_ANNUAL_%' AND COLUMN_NAME NOT LIKE 'PLANT_UNADJ%' AND COLUMN_NAME NOT LIKE 'PLANT_OZONE%'
GROUP BY 1,2 ORDER BY 2
;

-- S02 ENVIROEQUIP profile: boiler status x sulfur regulation x existing SO2 strategy, key uniqueness, unit mix
SELECT BOILER_STATUS, REGULATION_SULFUR, UNIT_SULFUR,
       COUNT(*) n, COUNT(DISTINCT PLANT_CODE, BOILER_ID) boiler_keys, COUNT(DISTINCT PLANT_CODE) plants,
       COUNT_IF(NULLIF(TRIM(SULFUR_DIOXIDE_CONTROL_EXISTING_STRATEGY_1),'') IS NOT NULL) so2_ctl,
       COUNT_IF(NULLIF(TRIM(NITROGEN_OXIDE_CONTROL_EXISTING_STRATEGY_1),'') IS NOT NULL) nox_ctl,
       COUNT_IF(NULLIF(TRIM(MERCURY_CONTROL_EXISTING_STRATEGY_1),'') IS NOT NULL) hg_ctl,
       MIN(STANDARD_SULFUR_RATE) r0, MEDIAN(STANDARD_SULFUR_RATE) rmed, MAX(STANDARD_SULFUR_RATE) r1,
       COUNT(DISTINCT _SOURCE_RUN_ID) runs, COUNT(DISTINCT _SRC_FILE) files
FROM LIBRARY_MARTS.ENERGY.ENERGY__FED_EIA860_6_2_ENVIROEQUIP
GROUP BY ROLLUP(1,2,3) ORDER BY 1 NULLS FIRST,2 NULLS FIRST,3 NULLS FIRST
;

-- S03 ENVIROEQUIP extract: every boiler + its linked generators (fuel, MW, retirement plan) + its plant's eGRID 2022 emissions
WITH a AS (
  SELECT PLANT_CODE, BOILER_ID, GENERATOR_ID FROM LIBRARY_MARTS.ENERGY.ENERGY__FED_EIA860_6_1_ENVIROASSOC
), g AS (
  SELECT PLANT_CODE, GENERATOR_ID, ENERGY_SOURCE_1, STATUS, NAMEPLATE_CAPACITY_MW, OPERATING_YEAR, PLANNED_RETIREMENT_YEAR
  FROM LIBRARY_MARTS.ENERGY.ENERGY__FED_EIA860_3_1_GENERATOR
), bg AS (
  SELECT a.PLANT_CODE, a.BOILER_ID, COUNT(*) gens, COUNT(g.GENERATOR_ID) gens_hit,
         LISTAGG(DISTINCT g.ENERGY_SOURCE_1, ',') fuels, LISTAGG(DISTINCT g.STATUS, ',') gen_status,
         SUM(g.NAMEPLATE_CAPACITY_MW) gen_mw, MIN(g.OPERATING_YEAR) op_yr,
         MIN(g.PLANNED_RETIREMENT_YEAR) ret_yr_min, MAX(g.PLANNED_RETIREMENT_YEAR) ret_yr_max
  FROM a LEFT JOIN g ON g.PLANT_CODE = a.PLANT_CODE AND g.GENERATOR_ID = a.GENERATOR_ID
  GROUP BY 1,2
), e AS (
  SELECT TRY_TO_NUMBER(DOE_EIA_ORIS_PLANT_OR_FACILITY_CODE) pc, COUNT(*) egrid_rows,
         MAX(PLANT_PRIMARY_FUEL) egrid_fuel,
         SUM(TRY_TO_DOUBLE(TO_VARCHAR(PLANT_ANNUAL_SO2_EMISSIONS_TONS))) so2_tons,
         SUM(TRY_TO_DOUBLE(TO_VARCHAR(PLANT_ANNUAL_NOX_EMISSIONS_TONS))) nox_tons,
         SUM(TRY_TO_DOUBLE(TO_VARCHAR(PLANT_ANNUAL_HG_EMISSIONS_LBS))) hg_lbs,
         SUM(TRY_TO_DOUBLE(TO_VARCHAR(PLANT_ANNUAL_NET_GENERATION_MWH))) net_mwh,
         SUM(TRY_TO_DOUBLE(TO_VARCHAR(PLANT_ANNUAL_COAL_NET_GENERATION_MWH))) coal_mwh,
         MAX(TRY_TO_DOUBLE(TO_VARCHAR(PLANT_ANNUAL_SO2_TOTAL_OUTPUT_EMISSION_RATE_LB_MWH))) so2_lb_mwh,
         MAX(TRY_TO_DOUBLE(TO_VARCHAR(PLANT_ANNUAL_SO2_INPUT_EMISSION_RATE_LB_MMBTU))) so2_lb_mmbtu,
         MAX(NERC_REGION_ACRONYM) nerc, MAX(PLANT_FIPS_STATE_CODE || PLANT_FIPS_COUNTY_CODE) fips
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_EGRID_PLANT_2022
  GROUP BY 1
)
SELECT b.PLANT_CODE, b.BOILER_ID, b.STATE, b.UTILITY_ID, b.UTILITY_NAME, b.PLANT_NAME, b.BOILER_STATUS, b.TYPE_OF_BOILER,
       b.STEAM_PLANT_TYPE, b.NEW_SOURCE_REVIEW, b.REGULATION_SULFUR, b.UNIT_SULFUR, b.PERIOD_SULFUR,
       b.STANDARD_SULFUR_RATE, b.STANDARD_SULFUR_PERCENT_SCRUBBED, b.COMPLIANCE_YEAR_SULFUR,
       b.SULFUR_DIOXIDE_CONTROL_EXISTING_STRATEGY_1 so2_ex1, b.SULFUR_DIOXIDE_CONTROL_EXISTING_STRATEGY_2 so2_ex2,
       b.SULFUR_DIOXIDE_CONTROL_EXISTING_STRATEGY_3 so2_ex3, b.SULFUR_DIOXIDE_CONTROL_PROPOSED_STRATEGY_1 so2_pr1,
       b.REGULATION_NITROGEN, b.UNIT_NITROGEN, b.STANDARD_NITROGEN_RATE, b.NITROGEN_OXIDE_CONTROL_EXISTING_STRATEGY_1 nox_ex1,
       b.NITROGEN_OXIDE_CONTROL_EXISTING_STRATEGY_2 nox_ex2, b.NITROGEN_OXIDE_CONTROL_PROPOSED_STRATEGY_1 nox_pr1,
       b.REGULATION_PARTICULATE, b.REGULATION_MERCURY, b.MERCURY_CONTROL_EXISTING_STRATEGY_1 hg_ex1, b.MERCURY_CONTROL_PROPOSED_STRATEGY_1 hg_pr1,
       b.COMPLIANCE_YEAR_NITROGEN, b.COMPLIANCE_YEAR_PARTICULATE, b.COMPLIANCE_YEAR_MERCURY,
       bg.gens, bg.gens_hit, bg.fuels, bg.gen_status, bg.gen_mw, bg.op_yr, bg.ret_yr_min, bg.ret_yr_max,
       e.egrid_rows, e.egrid_fuel, e.so2_tons, e.nox_tons, e.hg_lbs, e.net_mwh, e.coal_mwh, e.so2_lb_mwh, e.so2_lb_mmbtu, e.nerc, e.fips
FROM LIBRARY_MARTS.ENERGY.ENERGY__FED_EIA860_6_2_ENVIROEQUIP b
LEFT JOIN bg ON bg.PLANT_CODE = b.PLANT_CODE AND bg.BOILER_ID = b.BOILER_ID
LEFT JOIN e ON e.pc = b.PLANT_CODE
;

-- S04 eGRID 2022: where each boiler plant's SO2 number came from (EIA fuel estimate vs EPA stack monitor), unadjusted vs CHP-adjusted, plus the US total
SELECT TRY_TO_NUMBER(DOE_EIA_ORIS_PLANT_OR_FACILITY_CODE) pc, PLANT_NAME, PLANT_STATE_ABBREVIATION st, PLANT_PRIMARY_FUEL fuel,
       CAMD_PROGRAM_FLAG camd, COMBINED_HEAT_AND_POWER_CHP_PLANT_ADJUSTMENT_FLAG chp,
       PLANT_UNADJUSTED_ANNUAL_SO2_EMISSIONS_SOURCE so2_src,
       TRY_TO_DOUBLE(TO_VARCHAR(PLANT_ANNUAL_SO2_EMISSIONS_TONS)) so2_adj,
       TRY_TO_DOUBLE(TO_VARCHAR(PLANT_UNADJUSTED_ANNUAL_SO2_EMISSIONS_TONS)) so2_unadj,
       TRY_TO_DOUBLE(TO_VARCHAR(PLANT_UNADJUSTED_ANNUAL_HEAT_INPUT_FROM_COMBUSTION_MMBTU)) heat_unadj,
       TRY_TO_DOUBLE(TO_VARCHAR(PLANT_ANNUAL_HEAT_INPUT_FROM_COMBUSTION_MMBTU)) heat_adj,
       TRY_TO_DOUBLE(TO_VARCHAR(PLANT_ANNUAL_SO2_INPUT_EMISSION_RATE_LB_MMBTU)) so2_rate,
       TRY_TO_DOUBLE(TO_VARCHAR(PLANT_ANNUAL_COAL_NET_GENERATION_MWH)) coal_mwh,
       TRY_TO_DOUBLE(TO_VARCHAR(PLANT_ANNUAL_NET_GENERATION_MWH)) net_mwh,
       SUM(TRY_TO_DOUBLE(TO_VARCHAR(PLANT_ANNUAL_SO2_EMISSIONS_TONS))) OVER () us_so2_all_plants,
       COUNT(*) OVER () us_rows
FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_EGRID_PLANT_2022
QUALIFY TRY_TO_NUMBER(DOE_EIA_ORIS_PLANT_OR_FACILITY_CODE) IN (SELECT PLANT_CODE FROM LIBRARY_MARTS.ENERGY.ENERGY__FED_EIA860_6_2_ENVIROEQUIP)
;

-- S05 MULTIFUEL extract: every row + the plant's balancing authority, with a key-duplicate count
SELECT m.PLANT_CODE, m.GENERATOR_ID, m.STATE, m.UTILITY_NAME, m.PLANT_NAME, m.STATUS, m.TECHNOLOGY, m.PRIME_MOVER, m.SECTOR_NAME,
       m.ENERGY_SOURCE_1, m.ENERGY_SOURCE_2, m.MULTIPLE_FUELS, m.COFIRE_FUELS, m.SWITCH_BETWEEN_OIL_AND_NATURAL_GAS, m.SWITCH_WHEN_OPERATING,
       m.TIME_TO_SWITCH_FROM_GAS_TO_OIL, m.TIME_TO_SWITCH_FROM_OIL_TO_GAS, m.FACTORS_THAT_LIMIT_SWITCHING, m.STORAGE_LIMITS, m.AIR_PERMIT_LIMITS, m.OTHER_LIMITS,
       m.NAMEPLATE_CAPACITY_MW, m.SUMMER_CAPACITY_MW, m.WINTER_CAPACITY_MW, m.OPERATING_YEAR,
       m.NET_SUMMER_CAPACITY_WITH_NATURAL_GAS_MW, m.NET_WINTER_CAPACITY_WITH_NATURAL_GAS_MW, m.NET_SUMMER_CAPACITY_WITH_OIL_MW, m.NET_WINTER_CAPACITY_WITH_OIL_MW,
       COUNT(*) OVER (PARTITION BY m.PLANT_CODE, m.GENERATOR_ID) key_n,
       p.BALANCING_AUTHORITY_CODE ba, p.NERC_REGION nerc
FROM LIBRARY_MARTS.ENERGY.ENERGY__FED_EIA860_3_5_MULTIFUEL m
LEFT JOIN (SELECT PLANT_CODE, MAX(BALANCING_AUTHORITY_CODE) BALANCING_AUTHORITY_CODE, MAX(NERC_REGION) NERC_REGION
           FROM LIBRARY_MARTS.ENERGY.ENERGY__FED_EIA860_2_PLANT GROUP BY 1) p ON p.PLANT_CODE = m.PLANT_CODE
;

-- S06 denominator: all operating gas-fired generators by balancing authority and state (generator table), with row/plant counts to test completeness
SELECT p.BALANCING_AUTHORITY_CODE ba, g.STATE,
       COUNT(*) gens, COUNT(DISTINCT g.PLANT_CODE) plants,
       SUM(g.WINTER_CAPACITY_MW) winter_mw, SUM(g.NAMEPLATE_CAPACITY_MW) nameplate_mw,
       SUM(IFF(g.SWITCH_BETWEEN_OIL_AND_NATURAL_GAS = 'Y', g.WINTER_CAPACITY_MW, 0)) gen_tbl_switch_mw,
       COUNT_IF(g.MULTIPLE_FUELS = 'Y') gen_tbl_multi
FROM LIBRARY_MARTS.ENERGY.ENERGY__FED_EIA860_3_1_GENERATOR g
LEFT JOIN (SELECT PLANT_CODE, MAX(BALANCING_AUTHORITY_CODE) BALANCING_AUTHORITY_CODE FROM LIBRARY_MARTS.ENERGY.ENERGY__FED_EIA860_2_PLANT GROUP BY 1) p
       ON p.PLANT_CODE = g.PLANT_CODE
WHERE g.STATUS = 'OP' AND g.ENERGY_SOURCE_1 = 'NG'
GROUP BY ROLLUP(1, 2)
;

-- S07 time: operating gas generators by balancing authority and build period, and how much of each can switch to oil (generator table's own flag)
SELECT p.BALANCING_AUTHORITY_CODE ba,
       CASE WHEN g.OPERATING_YEAR < 2012 THEN 'a_pre2012' WHEN g.OPERATING_YEAR < 2021 THEN 'b_2012_2020' ELSE 'c_2021_2024' END built,
       COUNT(*) gens, SUM(g.WINTER_CAPACITY_MW) winter_mw,
       SUM(IFF(g.SWITCH_BETWEEN_OIL_AND_NATURAL_GAS = 'Y', g.WINTER_CAPACITY_MW, 0)) switch_mw,
       COUNT_IF(g.SWITCH_BETWEEN_OIL_AND_NATURAL_GAS = 'Y') switch_gens,
       COUNT_IF(g.SWITCH_BETWEEN_OIL_AND_NATURAL_GAS IS NULL OR TRIM(g.SWITCH_BETWEEN_OIL_AND_NATURAL_GAS) = '') switch_blank
FROM LIBRARY_MARTS.ENERGY.ENERGY__FED_EIA860_3_1_GENERATOR g
LEFT JOIN (SELECT PLANT_CODE, MAX(BALANCING_AUTHORITY_CODE) BALANCING_AUTHORITY_CODE FROM LIBRARY_MARTS.ENERGY.ENERGY__FED_EIA860_2_PLANT GROUP BY 1) p
       ON p.PLANT_CODE = g.PLANT_CODE
WHERE g.STATUS = 'OP' AND g.ENERGY_SOURCE_1 = 'NG'
GROUP BY ROLLUP(2, 1)
;

-- S08 ADVANCED_METERS extract: every utility-state row, meter counts by kind, plus key-duplicate count
SELECT DATA_YEAR, UTILITY_NUMBER, UTILITY_NAME, OWNERSHIP, SHORT_FORM, STATE, BA_CODE,
       RESIDENTIAL_AMR_METERS, TOTAL_AMR_METERS, RESIDENTIAL_AMI_METERS, TOTAL_AMI_METERS, RESIDENTIAL_NON_AMR_AMI_METERS, TOTAL_NON_AMR_AMI_METERS,
       RESIDENTIAL_TOTAL_METERS, TOTAL_TOTAL_METERS, TOTAL_ENERGY_SERVED_AMI_MWH, TOTAL_AMI_HOME_AREA_NETWORK_METERS, TOTAL_AMI_DAILY_DIGITAL_ACCESS_METERS,
       COUNT(*) OVER (PARTITION BY UTILITY_NUMBER, STATE) key_n, COUNT(DISTINCT _SOURCE_RUN_ID) OVER () runs
FROM LIBRARY_MARTS.ENERGY.ENERGY__FED_EIA861_ADVANCED_METERS
;

-- S09 SERVICE_TERRITORY lookup check: key uniqueness, county name forms, filler utilities, short-form flag, the lost first row
SELECT COUNT(*) n, COUNT(DISTINCT UTILITY_NUMBER, STATE, COUNTY) keys, COUNT(DISTINCT UTILITY_NUMBER) utils, COUNT(DISTINCT STATE) states,
       COUNT(DISTINCT STATE, COUNTY) state_counties, COUNT_IF(COUNTY ILIKE '%county%' OR COUNTY ILIKE '%parish%') county_word,
       COUNT_IF(UTILITY_NUMBER = 99999 OR UTILITY_NAME ILIKE 'adjust%') filler, COUNT_IF(SHORT_FORM_FLAG = 'Y') short_y,
       COUNT_IF(NULLIF(TRIM(SHORT_FORM_FLAG),'') IS NULL) short_blank, COUNT(DISTINCT DATA_YEAR) years, MIN(DATA_YEAR) y0,
       COUNT_IF(NULLIF(TRIM(COUNTY),'') IS NULL) county_blank, COUNT(DISTINCT _SOURCE_RUN_ID) runs,
       MIN(UTILITY_NUMBER) min_util, MAX_BY(UTILITY_NAME || ' / ' || STATE || ' / ' || COUNTY, -UTILITY_NUMBER) first_util_row,
       COUNT_IF(UTILITY_NUMBER = 34 AND STATE = 'AR') city_of_abbeville_probe
FROM LIBRARY_MARTS.ENERGY.ENERGY__FED_EIA861_SERVICE_TERRITORY
;

-- S10 EIA-860 UTILITY lookup check: entity types x owner/operator flags, address fillers, ZIP shape, duplicate IDs
SELECT ENTITY_TYPE, COUNT(*) n, COUNT(DISTINCT UTILITY_ID) ids,
       COUNT_IF(OWNER_OF_PLANTS_REPORTED_ON_FORM = 'Y') owner_y, COUNT_IF(OPERATOR_OF_PLANTS_REPORTED_ON_FORM = 'Y') operator_y,
       COUNT_IF(ASSET_MANAGER_OF_PLANTS_REPORTED_ON_FORM = 'Y') am_y, COUNT_IF(OTHER_RELATIONSHIPS_WITH_PLANTS_REPORTED_ON_FORM = 'Y') other_y,
       COUNT_IF(NOT REGEXP_LIKE(ZIP, '^[0-9]{5}(-?[0-9]{4})?$')) zip_bad, COUNT_IF(LENGTH(ZIP) = 4) zip4,
       COUNT_IF(STREET_ADDRESS ILIKE '%TBD%' OR STREET_ADDRESS ILIKE 'PO BOX%' OR STREET_ADDRESS ILIKE 'P.O.%' OR STREET_ADDRESS ILIKE 'P O BOX%') po_or_tbd,
       COUNT(DISTINCT STREET_ADDRESS, ZIP) addrs, COUNT(DISTINCT UPPER(UTILITY_NAME)) names
FROM LIBRARY_MARTS.ENERGY.ENERGY__FED_EIA860_1_UTILITY
GROUP BY ROLLUP(1) ORDER BY n DESC
;

-- S11 join: 2024 outage numbers for every investor-owned utility-state row (EIA-861 reliability), to set against hand-read meter share
SELECT UTILITY_NUMBER, UTILITY_NAME, STATE, OWNERSHIP,
       IEEE_SAIDI_WITHOUT_MED_MINUTES saidi_x, IEEE_SAIFI_WITHOUT_MED saifi_x, IEEE_CAIDI_WITHOUT_MED_MINUTES caidi_x,
       IEEE_SAIDI_WITH_MED_MINUTES saidi_all, IEEE_NUMBER_OF_CUSTOMERS cust, IEEE_OUTAGES_RECORDED_AUTOMATICALLY auto_rec,
       OTHER_SAIDI_WITHOUT_MED_MINUTES o_saidi_x, OTHER_CAIDI_WITHOUT_MED_MINUTES o_caidi_x, OTHER_OUTAGES_RECORDED_AUTOMATICALLY o_auto,
       COUNT(*) OVER (PARTITION BY UTILITY_NUMBER, STATE) key_n
FROM LIBRARY_MARTS.ENERGY.ENERGY__FED_EIA861_RELIABILITY
WHERE OWNERSHIP ILIKE 'investor%'
;

-- S12 second field for the meter lead: EIA-860 utility roster addresses for the hand-read-heavy utilities, plus every roster entry sharing those addresses
WITH t AS (
  SELECT UTILITY_ID, UTILITY_NAME, STREET_ADDRESS, CITY, STATE, ZIP, ENTITY_TYPE
  FROM LIBRARY_MARTS.ENERGY.ENERGY__FED_EIA860_1_UTILITY
  WHERE UTILITY_ID IN (3755, 9726, 12796, 13998, 15263, 18997, 66101, 15473, 11208, 13511, 4176, 15472, 54913)
)
SELECT 'target' k, t.* FROM t
UNION ALL
SELECT 'same_address' k, u.UTILITY_ID, u.UTILITY_NAME, u.STREET_ADDRESS, u.CITY, u.STATE, u.ZIP, u.ENTITY_TYPE
FROM LIBRARY_MARTS.ENERGY.ENERGY__FED_EIA860_1_UTILITY u
WHERE (UPPER(u.STREET_ADDRESS), LEFT(u.ZIP,5)) IN (SELECT UPPER(STREET_ADDRESS), LEFT(ZIP,5) FROM t)
  AND u.UTILITY_ID NOT IN (SELECT UTILITY_ID FROM t)
;

