-- deep3/g65: deep pass 3, 2026-09-24. Python door (connect/db.py), read-only SELECT/WITH only, QUERY_TAG 'deep3-2026-09-24'.
-- Every connection first ran: ALTER SESSION SET STATEMENT_TIMEOUT_IN_SECONDS = 300; ALTER SESSION SET QUERY_TAG = 'deep3-2026-09-24'. Those two are not counted.
-- Tables: ENERGY__FED_EIA_861_BALANCING_AUTHORITY, ENERGY__FED_EIA860_6_1_ENVIROASSOC, ENERGY__FED_EIA861_FRAME, ENERGY__FED_EIA861_MERGERS,
--         EDUCATION__FED_GOOGLE_POLADS_ADVERTISER_GEO_SPEND.
-- 19 statements (S01-S19), all below, in run order. S09-S17 are extracts; the peer, time and district math on them ran locally in pandas
-- (scripts a1.py-a10.py in g65/). Outputs: g65/out_Sxx.txt and g65/out_Sxx.csv.

-- S01 All five tables: column names, types, order (spot the header-eaten record and text-typed money)
SELECT TABLE_SCHEMA, TABLE_NAME, ORDINAL_POSITION, COLUMN_NAME, DATA_TYPE
FROM LIBRARY_MARTS.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME IN ('ENERGY__FED_EIA_861_BALANCING_AUTHORITY','ENERGY__FED_EIA860_6_1_ENVIROASSOC','ENERGY__FED_EIA861_FRAME','ENERGY__FED_EIA861_MERGERS','EDUCATION__FED_GOOGLE_POLADS_ADVERTISER_GEO_SPEND')
ORDER BY TABLE_NAME, ORDINAL_POSITION;

-- S02 Mergers: read all 4 rows
SELECT * FROM LIBRARY_MARTS.ENERGY.ENERGY__FED_EIA861_MERGERS;

-- S03 Balancing authority: confirm it is a lookup (one row per authority-state, one year)
SELECT COUNT(*) n, COUNT(DISTINCT BA_ID) ba_ids, COUNT(DISTINCT BA_CODE) ba_codes, COUNT(DISTINCT BA_ID, STATE) ba_state_pairs,
       COUNT(DISTINCT STATE) states, MIN(DATA_YEAR) y0, MAX(DATA_YEAR) y1, COUNT(DISTINCT _SOURCE_RUN_ID) runs,
       COUNT_IF(BA_CODE IS NULL OR TRIM(BA_CODE)='') blank_code
FROM LIBRARY_MARTS.ENERGY.ENERGY__FED_EIA_861_BALANCING_AUTHORITY;

-- S04 Enviro association: confirm it is a boiler-to-generator link list; STEAM_PLANT_TYPE is a 1-4 code, not an amount; land rate in the plant table
WITH a AS (SELECT * FROM LIBRARY_MARTS.ENERGY.ENERGY__FED_EIA860_6_1_ENVIROASSOC),
p AS (SELECT DISTINCT PLANT_CODE FROM LIBRARY_MARTS.ENERGY.ENERGY__FED_EIA860_2_PLANT)
SELECT COUNT(*) n, COUNT(DISTINCT a.PLANT_CODE) plants, COUNT(DISTINCT a.PLANT_CODE, BOILER_ID, GENERATOR_ID) links,
       COUNT(DISTINCT a.PLANT_CODE, BOILER_ID) boilers, COUNT(DISTINCT a.PLANT_CODE, GENERATOR_ID) gens,
       COUNT_IF(STEAM_PLANT_TYPE=1) t1, COUNT_IF(STEAM_PLANT_TYPE=2) t2, COUNT_IF(STEAM_PLANT_TYPE=3) t3, COUNT_IF(STEAM_PLANT_TYPE=4) t4,
       COUNT(DISTINCT UTILITY_ID) utils, COUNT(DISTINCT _SOURCE_RUN_ID) runs,
       COUNT(DISTINCT IFF(p.PLANT_CODE IS NOT NULL, a.PLANT_CODE, NULL)) plants_in_plant_table
FROM a LEFT JOIN p ON a.PLANT_CODE = p.PLANT_CODE;

-- S05 Frame: confirm it is the survey roster; ownership mix; which schedule flags carry X; land rate in the long-form and short-form data tables
WITH f AS (SELECT * FROM LIBRARY_MARTS.ENERGY.ENERGY__FED_EIA861_FRAME),
u AS (SELECT DISTINCT UTILITY_NUMBER FROM LIBRARY_MARTS.ENERGY.ENERGY__FED_EIA861_UTILITY_DATA),
s AS (SELECT DISTINCT UTILITY_NUMBER FROM LIBRARY_MARTS.ENERGY.ENERGY__FED_EIA861_SHORT_FORM)
SELECT COUNT(*) n, COUNT(DISTINCT f.UTILITY_NUMBER) utils, COUNT_IF(f.UTILITY_NUMBER=99999) n99999, MIN(DATA_YEAR) y0, MAX(DATA_YEAR) y1,
       COUNT_IF(SHORT_FORM='Y') short_y, COUNT_IF(SCHEDULE_FLAG_01='X') f01, COUNT_IF(SCHEDULE_FLAG_02='X') f02, COUNT_IF(SCHEDULE_FLAG_03='X') f03,
       COUNT_IF(SCHEDULE_FLAG_04='X') f04, COUNT_IF(SCHEDULE_FLAG_05='X') f05, COUNT_IF(SCHEDULE_FLAG_06='X') f06, COUNT_IF(SCHEDULE_FLAG_07='X') f07,
       COUNT_IF(SCHEDULE_FLAG_08='X') f08, COUNT_IF(SCHEDULE_FLAG_09='X') f09, COUNT_IF(SCHEDULE_FLAG_10='X') f10, COUNT_IF(SCHEDULE_FLAG_11='X') f11,
       COUNT_IF(SCHEDULE_FLAG_12='X') f12, COUNT_IF(SCHEDULE_FLAG_13='X') f13, COUNT_IF(SCHEDULE_FLAG_14='X') f14, COUNT_IF(SCHEDULE_FLAG_15='X') f15,
       COUNT(DISTINCT u.UTILITY_NUMBER) in_long_form, COUNT(DISTINCT s.UTILITY_NUMBER) in_short_form,
       COUNT_IF(u.UTILITY_NUMBER IS NULL AND s.UTILITY_NUMBER IS NULL) in_neither,
       COUNT_IF(SHORT_FORM='Y' AND s.UTILITY_NUMBER IS NULL) short_flag_not_in_short
FROM f LEFT JOIN u ON f.UTILITY_NUMBER=u.UTILITY_NUMBER LEFT JOIN s ON f.UTILITY_NUMBER=s.UTILITY_NUMBER;

-- S06 Frame and mergers landing tables: raw column names (did the loader eat a data row as the header?) and landing row counts
SELECT c.TABLE_NAME, c.ORDINAL_POSITION, c.COLUMN_NAME, t.ROW_COUNT
FROM LIBRARY_RAW.INFORMATION_SCHEMA.COLUMNS c JOIN LIBRARY_RAW.INFORMATION_SCHEMA.TABLES t ON c.TABLE_SCHEMA=t.TABLE_SCHEMA AND c.TABLE_NAME=t.TABLE_NAME
WHERE c.TABLE_SCHEMA='LANDING' AND c.TABLE_NAME IN ('FED_EIA861_FRAME','FED_EIA861_MERGERS')
ORDER BY 1,2;

-- S07 Google geo spend: profile. Grain, full-row duplicates, spend as numbers, rounding, non-USD columns
SELECT COUNT(*) n, COUNT(DISTINCT ADVERTISER_ID) adv_ids, COUNT(DISTINCT ADVERTISER_NAME) adv_names,
       COUNT(DISTINCT ADVERTISER_ID, COUNTRY, COUNTRY_SUBDIVISION_PRIMARY) id_geo_keys, COUNT(DISTINCT HASH(*)) distinct_rows,
       COUNT(DISTINCT COUNTRY_SUBDIVISION_PRIMARY) subs, COUNT_IF(COUNTRY_SUBDIVISION_PRIMARY IS NULL OR TRIM(COUNTRY_SUBDIVISION_PRIMARY)='') sub_blank,
       COUNT_IF(TRY_TO_NUMBER(SPEND_USD) IS NULL) usd_not_num, SUM(TRY_TO_NUMBER(SPEND_USD)) usd_sum, MAX(TRY_TO_NUMBER(SPEND_USD)) usd_max,
       COUNT_IF(TRY_TO_NUMBER(SPEND_USD)=0) usd_0, COUNT_IF(MOD(TRY_TO_NUMBER(SPEND_USD),100)<>0) usd_not_x100,
       COUNT_IF(COALESCE(SPEND_EUR,'0') NOT IN ('0','')) eur_nz, COUNT_IF(COALESCE(SPEND_GBP,'0') NOT IN ('0','')) gbp_nz,
       COUNT_IF(COALESCE(SPEND_INR,'0') NOT IN ('0','')) inr_nz, COUNT_IF(COALESCE(SPEND_AUD,'0') NOT IN ('0','')) aud_nz,
       COUNT_IF(COALESCE(SPEND_BRL,'0') NOT IN ('0','')) brl_nz, COUNT_IF(COALESCE(SPEND_MXN,'0') NOT IN ('0','')) mxn_nz
FROM LIBRARY_MARTS.EDUCATION.EDUCATION__FED_GOOGLE_POLADS_ADVERTISER_GEO_SPEND;

-- S08 Google geo spend: rows per advertiser-state key, and whether the repeats carry different spend
WITH k AS (SELECT ADVERTISER_ID, COUNTRY_SUBDIVISION_PRIMARY sub, COUNT(*) n, COUNT(DISTINCT SPEND_USD) dv, SUM(TRY_TO_NUMBER(SPEND_USD)) s
           FROM LIBRARY_MARTS.EDUCATION.EDUCATION__FED_GOOGLE_POLADS_ADVERTISER_GEO_SPEND GROUP BY 1,2)
SELECT n rows_per_key, COUNT(*) keys, COUNT_IF(dv>1) keys_with_diff_spend, SUM(s) usd, COUNT(DISTINCT ADVERTISER_ID) advs
FROM k GROUP BY n ORDER BY n;

-- S09 Google geo spend: extract every advertiser-place row (id, country, state, USD) for local peer math
SELECT ADVERTISER_ID, COUNTRY, COUNTRY_SUBDIVISION_PRIMARY sub, TRY_TO_NUMBER(SPEND_USD) usd
FROM LIBRARY_MARTS.EDUCATION.EDUCATION__FED_GOOGLE_POLADS_ADVERTISER_GEO_SPEND;

-- S10 Google advertiser stats (sibling table): names, regions, all-place total USD, ad count, the IDs each buyer gave Google (FEC ID lives here)
SELECT ADVERTISER_ID, ADVERTISER_NAME, REGIONS, TRY_TO_NUMBER(SPEND_USD::STRING) usd_total, TOTAL_CREATIVES, PUBLIC_IDS_LIST
FROM LIBRARY_MARTS.EDUCATION.EDUCATION__FED_GOOGLE_POLADS_ADVERTISER_STATS;

-- S11 Google geo spend: advertiser id to name as the geo table spells it
SELECT ADVERTISER_ID, ANY_VALUE(ADVERTISER_NAME) nm, COUNT(DISTINCT ADVERTISER_NAME) names
FROM LIBRARY_MARTS.EDUCATION.EDUCATION__FED_GOOGLE_POLADS_ADVERTISER_GEO_SPEND GROUP BY 1;

-- S12 FEC committees (one clean line each) for every FEC committee ID the Google buyers listed
WITH ids AS (SELECT DISTINCT f.value::STRING cmte
             FROM LIBRARY_MARTS.EDUCATION.EDUCATION__FED_GOOGLE_POLADS_ADVERTISER_STATS s,
                  LATERAL FLATTEN(input => REGEXP_SUBSTR_ALL(s.PUBLIC_IDS_LIST, 'C[0-9]{8}')) f)
SELECT ids.cmte, d.CMTE_NM, d.CMTE_ST, d.CMTE_CITY, d.CMTE_TP, d.CMTE_DSGN, d.CMTE_PTY_AFFILIATION, d.CAND_ID, d.CYCLE, d.IS_AMBIGUOUS, d.SRC
FROM ids LEFT JOIN LIBRARY_MARTS.FINANCE.FINANCE__FED_FEC_COMMITTEES_DIM d ON d.CMTE_ID = ids.cmte;

-- S13 FEC candidates behind those committees: office, office state, district, incumbent flag, party, by election year
WITH ids AS (SELECT DISTINCT f.value::STRING cmte
             FROM LIBRARY_MARTS.EDUCATION.EDUCATION__FED_GOOGLE_POLADS_ADVERTISER_STATS s,
                  LATERAL FLATTEN(input => REGEXP_SUBSTR_ALL(s.PUBLIC_IDS_LIST, 'C[0-9]{8}')) f),
c AS (SELECT DISTINCT d.CAND_ID FROM ids JOIN LIBRARY_MARTS.FINANCE.FINANCE__FED_FEC_COMMITTEES_DIM d ON d.CMTE_ID = ids.cmte WHERE d.CAND_ID IS NOT NULL AND TRIM(d.CAND_ID)<>'')
SELECT k.CAND_ID, k.CAND_NAME, k.CAND_ELECTION_YR, k.CAND_OFFICE, k.CAND_OFFICE_ST, k.CAND_OFFICE_DISTRICT, k.CAND_ICI, k.CAND_PTY_AFFILIATION, k.CAND_STATUS, k.CAND_PCC, k.CAND_ST
FROM c JOIN LIBRARY_MARTS.FINANCE.FINANCE__FED_FEC_CANDIDATES k ON k.CAND_ID = c.CAND_ID;

-- S14 State population, 2020 census, summed from the county master list
SELECT STATE_NAME, SUM(POPULATION_2020) pop, COUNT(*) counties FROM LIBRARY_MARTS.CORE.DIM_COUNTY GROUP BY 1 ORDER BY 1;

-- S15 Weekly Google political spend for every account verified with the U.S. House's own EIN (53-6002523), i.e. members' official offices
WITH o AS (SELECT ADVERTISER_ID FROM LIBRARY_MARTS.EDUCATION.EDUCATION__FED_GOOGLE_POLADS_ADVERTISER_STATS WHERE PUBLIC_IDS_LIST ILIKE '%53-6002523%')
SELECT w.ADVERTISER_ID, w.ADVERTISER_NAME, w.WEEK_START_DATE, w.ELECTION_CYCLE, TRY_TO_NUMBER(w.SPEND_USD::STRING) usd
FROM LIBRARY_MARTS.EDUCATION.EDUCATION__FED_GOOGLE_POLADS_ADVERTISER_WEEKLY_SPEND w JOIN o ON o.ADVERTISER_ID = w.ADVERTISER_ID;

-- S16 Every ad those official-office accounts ran: dates, spend range, impressions, where it was aimed
WITH o AS (SELECT ADVERTISER_ID FROM LIBRARY_MARTS.EDUCATION.EDUCATION__FED_GOOGLE_POLADS_ADVERTISER_STATS WHERE PUBLIC_IDS_LIST ILIKE '%53-6002523%')
SELECT c.ADVERTISER_ID, c.AD_ID, c.AD_TYPE, c.DATE_RANGE_START, c.DATE_RANGE_END, c.NUM_OF_DAYS, c.IMPRESSIONS,
       c.SPEND_RANGE_MIN_USD, c.SPEND_RANGE_MAX_USD, c.GEO_TARGETING_INCLUDED, c.GEO_TARGETING_EXCLUDED, c.AD_URL
FROM LIBRARY_MARTS.EDUCATION.EDUCATION__FED_GOOGLE_POLADS_CREATIVE_STATS c JOIN o ON o.ADVERTISER_ID = c.ADVERTISER_ID;

-- S17 Voteview House members, 115th-119th Congress: who held each district (to check the name on each official ad account against the district its ads aimed at)
SELECT CONGRESS, STATE_ABBREV, DISTRICT_CODE, BIONAME, BIOGUIDE_ID, PARTY_CODE, OCCUPANCY
FROM LIBRARY_MARTS.POLITICS.POLITICS__FED_VOTEVIEW_MEMBERS
WHERE CHAMBER = 'House' AND CONGRESS BETWEEN 115 AND 119;

-- S18 FEC candidate records for the members whose official accounts spent inside 60 days of a general election, plus Gomez (CA-34): on the ballot that year?
SELECT CAND_ID, CAND_NAME, CAND_ELECTION_YR, CAND_OFFICE, CAND_OFFICE_ST, CAND_OFFICE_DISTRICT, CAND_ICI, CAND_STATUS, CAND_PCC
FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_FEC_CANDIDATES
WHERE CAND_OFFICE = 'H' AND (CAND_NAME ILIKE 'CUELLAR%' OR CAND_NAME ILIKE 'MCCARTHY, KEVIN%' OR CAND_NAME ILIKE 'OLSON, PETE%'
   OR CAND_NAME ILIKE 'HOLLINGSWORTH%' OR CAND_NAME ILIKE 'GOMEZ, JIMMY%' OR CAND_NAME ILIKE 'STEEL, MICHELLE%' OR CAND_NAME ILIKE 'GOLDMAN, DAN%')
ORDER BY CAND_NAME, CAND_ELECTION_YR;

-- S19 Outside money for and against each member of Congress, 2024 and 2026 cycles (a stand-in for how tight each member's race is)
SELECT BIOGUIDE, CYCLE, OUTSIDE_FOR, OUTSIDE_AGAINST, PAC_DONATIONS, N_PAC_DONORS
FROM LIBRARY_MARTS.POLITICS.POLITICS__MEMBER_PAC_MONEY
WHERE CYCLE IN (2024, 2026);

