-- deep3/g67: deep pass 3, 2026-09-24. Python door (connect/db.py), read-only SELECT/WITH only, QUERY_TAG 'deep3-2026-09-24'.
-- Every connection first ran: ALTER SESSION SET STATEMENT_TIMEOUT_IN_SECONDS = 300; ALTER SESSION SET QUERY_TAG = 'deep3-2026-09-24'. Those two are not counted.
-- Tables: EDUCATION__FED_GOOGLE_POLADS_GEO_SPEND, EDUCATION__FED_CFTC_COT_FINANCIAL, EDUCATION__FED_GOOGLE_POLADS_ADVERTISER_STATS,
--         EDUCATION__FED_GOOGLE_POLADS_ADVERTISER_ID_MAPPING, EDUCATION__FED_CPSC_NEISS_CODES.
-- Statements numbered S01.. in run order. The small tables were pulled whole; peer, time and join math on them ran locally in pandas (scratch in g67/).

-- S01 geo_all
SELECT * FROM LIBRARY_MARTS.EDUCATION.EDUCATION__FED_GOOGLE_POLADS_GEO_SPEND;

-- S02 adv_all
SELECT * FROM LIBRARY_MARTS.EDUCATION.EDUCATION__FED_GOOGLE_POLADS_ADVERTISER_STATS;

-- S03 idmap_all
SELECT * FROM LIBRARY_MARTS.EDUCATION.EDUCATION__FED_GOOGLE_POLADS_ADVERTISER_ID_MAPPING;

-- S04 neiss_all
SELECT * FROM LIBRARY_MARTS.EDUCATION.EDUCATION__FED_CPSC_NEISS_CODES;

-- S05 cot_all
SELECT * FROM LIBRARY_MARTS.EDUCATION.EDUCATION__FED_CFTC_COT_FINANCIAL;

-- S06 house_weekly
-- Weekly Google spend for every advertiser that gave Google the U.S. House EIN 53-6002523, or is named as a House office
WITH h AS (
  SELECT ADVERTISER_ID, ADVERTISER_NAME, PUBLIC_IDS_LIST FROM LIBRARY_MARTS.EDUCATION.EDUCATION__FED_GOOGLE_POLADS_ADVERTISER_STATS
  WHERE PUBLIC_IDS_LIST LIKE '%53-6002523%' OR UPPER(ADVERTISER_NAME) LIKE '%HOUSE OF REP%')
SELECT w.ADVERTISER_ID, h.ADVERTISER_NAME, h.PUBLIC_IDS_LIST, w.WEEK_START_DATE, w.SPEND_USD
FROM LIBRARY_MARTS.EDUCATION.EDUCATION__FED_GOOGLE_POLADS_ADVERTISER_WEEKLY_SPEND w JOIN h ON h.ADVERTISER_ID = w.ADVERTISER_ID;

-- S07 house_geo
-- Where (country, state) those same accounts' spend landed
WITH h AS (
  SELECT ADVERTISER_ID, ADVERTISER_NAME, PUBLIC_IDS_LIST FROM LIBRARY_MARTS.EDUCATION.EDUCATION__FED_GOOGLE_POLADS_ADVERTISER_STATS
  WHERE PUBLIC_IDS_LIST LIKE '%53-6002523%' OR UPPER(ADVERTISER_NAME) LIKE '%HOUSE OF REP%')
SELECT g.ADVERTISER_ID, h.ADVERTISER_NAME, g.COUNTRY, g.COUNTRY_SUBDIVISION_PRIMARY, g.SPEND_USD
FROM LIBRARY_MARTS.EDUCATION.EDUCATION__FED_GOOGLE_POLADS_ADVERTISER_GEO_SPEND g JOIN h ON h.ADVERTISER_ID = g.ADVERTISER_ID;

-- S08 generic_house_creatives
-- Ads run by the generic 'US House of Representatives' account (House EIN): where they were aimed, how many, when
SELECT GEO_TARGETING_INCLUDED, COUNT(*) ads, SUM(TRY_TO_NUMBER(SPEND_RANGE_MIN_USD)) min_usd, SUM(TRY_TO_NUMBER(SPEND_RANGE_MAX_USD)) max_usd,
       MIN(DATE_RANGE_START) first_day, MAX(DATE_RANGE_END) last_day, MIN(AD_URL) sample_url
FROM LIBRARY_MARTS.EDUCATION.EDUCATION__FED_GOOGLE_POLADS_CREATIVE_STATS
WHERE ADVERTISER_ID = 'AR11776064889791971329'
GROUP BY 1 ORDER BY max_usd DESC NULLS LAST;

-- S09 house_members
-- Every House member whose service reached 2018 or later: name, state, district, party
SELECT BIOGUIDE, NAME_FIRST, NAME_LAST, NAME_OFFICIAL_FULL, STATE, DISTRICT, PARTY, TERM_TYPE, TERM_START, TERM_END
FROM LIBRARY_MARTS.POLITICS.POLITICS__FED_CONGRESS_LEGISLATORS
WHERE TERM_END >= '2019-01-03';

-- S10 house_general_results
-- House general-election results 2016-2024, for winner margin per district and who was on the ballot
SELECT ELECTION_YEAR, STATE_ABBR, DISTRICT, CANDIDATE_NAME, PARTY, CANDIDATE_VOTES, TOTAL_VOTES, STAGE, IS_SPECIAL_ELECTION, IS_WRITEIN
FROM LIBRARY_MARTS.POLITICS.POLITICS__FED_MEDSL_HOUSE_RETURNS
WHERE ELECTION_YEAR >= 2016;

-- S11 house_ie_by_district
-- Outside money (independent expenditures) per House district, 2024 and 2026 cycles, superseded lines dropped: a contested-seat yardstick
SELECT FEC_ELECTION_YR, CAN_OFFICE_STATE, CAN_OFFICE_DIS, COUNT(*) n_lines,
       SUM(TRY_TO_DECIMAL(REPLACE(EXP_AMO, ',', ''), 16, 2)) ie_usd, COUNT_IF(TRY_TO_DECIMAL(REPLACE(EXP_AMO, ',', ''), 16, 2) IS NULL) bad_amt
FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_FEC_INDEPENDENT_EXPENDITURES
WHERE CAN_OFFICE = 'H' AND FEC_ELECTION_YR IN (2024, 2026) AND COALESCE(IS_SUPERSEDED, FALSE) = FALSE
GROUP BY 1, 2, 3;

-- S12 house_ie_by_district_v2
-- Retry of S11 (0 rows: FEC_ELECTION_YR/IS_SUPERSEDED filters did not match). Uses CYCLE_FILE and the string test other reports use.
-- Lines of $5M+ counted apart: the table carries typo-sized amounts.
WITH b AS (
  SELECT CYCLE_FILE, CAN_OFFICE_STATE, CAN_OFFICE_DIS, TRY_TO_DOUBLE(EXP_AMO) amt
  FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_FEC_INDEPENDENT_EXPENDITURES
  WHERE NOT (IS_SUPERSEDED::string ILIKE 'true') AND CYCLE_FILE IN (2022, 2024, 2026) AND LEFT(CAND_ID, 1) = 'H')
SELECT CYCLE_FILE, CAN_OFFICE_STATE, CAN_OFFICE_DIS, COUNT(*) n_lines,
       SUM(IFF(amt < 5e6, amt, 0)) ie_usd, COUNT_IF(amt >= 5e6) n_huge, SUM(IFF(amt >= 5e6, amt, 0)) huge_usd
FROM b GROUP BY 1, 2, 3;

-- S13 generic_house_creative_rows
-- One row per ad for the generic 'US House of Representatives' account, to date and place each ad
SELECT AD_ID, AD_TYPE, DATE_RANGE_START, DATE_RANGE_END, NUM_OF_DAYS, IMPRESSIONS, SPEND_RANGE_MIN_USD, SPEND_RANGE_MAX_USD,
       GEO_TARGETING_INCLUDED, GEO_TARGETING_EXCLUDED, AGE_TARGETING, GENDER_TARGETING, AD_URL
FROM LIBRARY_MARTS.EDUCATION.EDUCATION__FED_GOOGLE_POLADS_CREATIVE_STATS
WHERE ADVERTISER_ID = 'AR11776064889791971329';

-- S14 house_ie_general_only
-- Same as S12 but split by election type, so general-election outside money (swing seats) is apart from primary fights
WITH b AS (
  SELECT CYCLE_FILE, CAN_OFFICE_STATE, CAN_OFFICE_DIS, LEFT(ELE_TYPE, 1) ele, TRY_TO_DOUBLE(EXP_AMO) amt
  FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_FEC_INDEPENDENT_EXPENDITURES
  WHERE NOT (IS_SUPERSEDED::string ILIKE 'true') AND CYCLE_FILE IN (2022, 2024) AND LEFT(CAND_ID, 1) = 'H')
SELECT CYCLE_FILE, CAN_OFFICE_STATE, CAN_OFFICE_DIS, ele, COUNT(*) n_lines, SUM(IFF(amt < 5e6, amt, 0)) ie_usd, COUNT_IF(amt >= 5e6) n_huge
FROM b GROUP BY 1, 2, 3, 4;

-- S15 odd_house_accounts_creatives
-- Where six odd House-EIN accounts aimed their ads: 'Rep. Steel' (spend mostly NV/OH/MN), 'Rep. Goldman' (mostly CA), 'Rep. Kevin McCarthy' (84% outside CA),
-- and the three other generic accounts ('US House of Representatives' CO-heavy, 'US House of Reps.' NY-heavy, 'Office of Finance')
SELECT ADVERTISER_ID, ADVERTISER_NAME, GEO_TARGETING_INCLUDED, COUNT(*) ads,
       SUM(TRY_TO_NUMBER(SPEND_RANGE_MIN_USD)) min_usd, SUM(TRY_TO_NUMBER(SPEND_RANGE_MAX_USD)) max_usd,
       MIN(DATE_RANGE_START) first_day, MAX(DATE_RANGE_END) last_day
FROM LIBRARY_MARTS.EDUCATION.EDUCATION__FED_GOOGLE_POLADS_CREATIVE_STATS
WHERE ADVERTISER_ID IN ('AR13522503217748901889','AR16196087374160068609','AR07280544198984466433',
                        'AR07359836459274076161','AR15487617555018809345','AR11679967951481470977')
GROUP BY 1, 2, 3;

-- S16 steel_goldman_ad_rows
-- Ad-level rows (with the public ad link) for the two House-EIN accounts named for one member whose ads aimed at other members' districts
SELECT ADVERTISER_ID, ADVERTISER_NAME, AD_ID, AD_TYPE, DATE_RANGE_START, DATE_RANGE_END, SPEND_RANGE_MIN_USD, SPEND_RANGE_MAX_USD,
       LEFT(GEO_TARGETING_INCLUDED, 200) geo, AD_URL
FROM LIBRARY_MARTS.EDUCATION.EDUCATION__FED_GOOGLE_POLADS_CREATIVE_STATS
WHERE ADVERTISER_ID IN ('AR13522503217748901889', 'AR16196087374160068609')
ORDER BY ADVERTISER_ID, DATE_RANGE_START;

-- S17 google_fec_join
-- Google spend rolled up by the FEC ID advertisers gave, joined to the FEC committee list and to PAC/party money totals (all loaded cycles)
WITH g AS (
  SELECT REGEXP_SUBSTR(PUBLIC_IDS_LIST, 'C[0-9]{8}') fec, COUNT(*) accts, SUM(TRY_TO_NUMBER(SPEND_USD)) g_usd,
         LISTAGG(DISTINCT ADVERTISER_NAME, ' | ') WITHIN GROUP (ORDER BY ADVERTISER_NAME) names
  FROM LIBRARY_MARTS.EDUCATION.EDUCATION__FED_GOOGLE_POLADS_ADVERTISER_STATS
  WHERE REGIONS LIKE '%US%' AND REGEXP_SUBSTR(PUBLIC_IDS_LIST, 'C[0-9]{8}') IS NOT NULL
  GROUP BY 1),
d AS (SELECT CMTE_ID, MAX(CMTE_NM) cmte_nm, MAX(CMTE_TP) cmte_tp, MAX(CMTE_DSGN) cmte_dsgn, MAX(CYCLE) last_cycle FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_FEC_COMMITTEES_DIM GROUP BY 1),
p AS (SELECT CMTE_ID, COUNT(*) p_rows, COUNT(DISTINCT COVERAGE_END_DATE) p_periods, SUM(TRY_TO_DOUBLE(TOTAL_DISBURSEMENTS::string)) p_disb,
             MIN(COVERAGE_END_DATE::string) p_first, MAX(COVERAGE_END_DATE::string) p_last
      FROM LIBRARY_MARTS.POLITICS.POLITICS__FED_FEC_PAC_SUMMARY GROUP BY 1)
SELECT g.*, d.cmte_nm, d.cmte_tp, d.cmte_dsgn, d.last_cycle, p.p_rows, p.p_periods, p.p_disb, p.p_first, p.p_last
FROM g LEFT JOIN d ON d.CMTE_ID = g.fec LEFT JOIN p ON p.CMTE_ID = g.fec;

-- ---- Run notes (not statements) ----
-- S10 returned 2016 and 2018 only: POLITICS__FED_MEDSL_HOUSE_RETURNS stops at 2018, so it could not give 2022/2024 margins. Not used.
-- S11 returned 0 rows (FEC_ELECTION_YR / IS_SUPERSEDED filters matched nothing). S12 is the retry on CYCLE_FILE; S14 splits by election type.
-- 17 statements used of 35.
