-- deep3/g68: deep pass 3, 2026-09-24. Python door (connect/db.py), read-only SELECT/WITH only, QUERY_TAG 'deep3-2026-09-24'.
-- Every connection first ran: ALTER SESSION SET STATEMENT_TIMEOUT_IN_SECONDS = 300; ALTER SESSION SET QUERY_TAG = 'deep3-2026-09-24'. Those two are not counted.
-- Tables: EDUCATION__FED_GOOGLE_POLADS_ADVERTISER_DECLARED_STATS, EDUCATION__FED_FRB_Z1_CSV, IMMIGRATION__FED_DHS_OHSS, IMMIGRATION__FED_DOL_OFLC, IMMIGRATION__FED_EOIR_CASES.
-- Statements below in run order (S01..). Small tables were pulled whole; the math on them ran locally in pandas (scratch in g68/).

-- S01 cols_all5
SELECT TABLE_SCHEMA, TABLE_NAME, ORDINAL_POSITION, COLUMN_NAME, DATA_TYPE
FROM LIBRARY_MARTS.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME IN ('EDUCATION__FED_GOOGLE_POLADS_ADVERTISER_DECLARED_STATS','EDUCATION__FED_FRB_Z1_CSV','IMMIGRATION__FED_DHS_OHSS','IMMIGRATION__FED_DOL_OFLC','IMMIGRATION__FED_EOIR_CASES')
ORDER BY 2,3;

-- S02 polads_declared_whole
SELECT * FROM LIBRARY_MARTS.EDUCATION.EDUCATION__FED_GOOGLE_POLADS_ADVERTISER_DECLARED_STATS;

-- S03 z1_whole
SELECT * FROM LIBRARY_MARTS.EDUCATION.EDUCATION__FED_FRB_Z1_CSV;

-- S04 ohss_whole
SELECT * FROM LIBRARY_MARTS.IMMIGRATION.IMMIGRATION__FED_DHS_OHSS;

-- S05 oflc_extract
SELECT CASE_NUMBER, CASE_STATUS, CASE_SUBMITTED, DECISION_DATE, VISA_CLASS, SOC_CODE, SOC_TITLE, FULL_TIME_POSITION,
       TOTAL_WORKER_POSITIONS, NEW_EMPLOYMENT, CONTINUED_EMPLOYMENT, CHANGE_EMPLOYER, AMENDED_PETITION,
       EMPLOYER_NAME, EMPLOYER_ADDRESS1, EMPLOYER_CITY, EMPLOYER_STATE, EMPLOYER_POSTAL_CODE, EMPLOYER_PHONE, NAICS_CODE,
       AGENT_ATTORNEY_LAW_FIRM_BUSINESS_NAME, WORKSITE_WORKERS_1, SECONDARY_ENTITY_1, SECONDARY_ENTITY_BUSINESS_NAME_1,
       WORKSITE_ADDRESS1_1, WORKSITE_CITY_1, WORKSITE_STATE_1, WORKSITE_POSTAL_CODE_1,
       WAGE_RATE_OF_PAY_FROM_1, WAGE_RATE_OF_PAY_TO_1, WAGE_UNIT_OF_PAY_1, PREVAILING_WAGE_1, PW_UNIT_OF_PAY_1, PW_WAGE_LEVEL_1,
       PW_OTHER_SOURCE_1, PW_SURVEY_NAME_1, H_1B_DEPENDENT, WILLFUL_VIOLATOR, STATUTORY_BASIS, MASTERS_EXEMPTION,
       (IFF(NULLIF(TRIM(WORKSITE_STATE_2),'') IS NOT NULL,1,0)+IFF(NULLIF(TRIM(WORKSITE_STATE_3),'') IS NOT NULL,1,0)+IFF(NULLIF(TRIM(WORKSITE_STATE_4),'') IS NOT NULL,1,0)
        +IFF(NULLIF(TRIM(WORKSITE_STATE_5),'') IS NOT NULL,1,0)+IFF(NULLIF(TRIM(WORKSITE_STATE_6),'') IS NOT NULL,1,0)+IFF(NULLIF(TRIM(WORKSITE_STATE_7),'') IS NOT NULL,1,0)
        +IFF(NULLIF(TRIM(WORKSITE_STATE_8),'') IS NOT NULL,1,0)+IFF(NULLIF(TRIM(WORKSITE_STATE_9),'') IS NOT NULL,1,0)+IFF(NULLIF(TRIM(WORKSITE_STATE_10),'') IS NOT NULL,1,0)) AS EXTRA_WORKSITES
FROM LIBRARY_MARTS.IMMIGRATION.IMMIGRATION__FED_DOL_OFLC;

-- S06 eoir_profile_by_custody
SELECT CUSTODY, CUSTODY_LABEL, COUNT(*) n, COUNT(DISTINCT CASE_ID) cases, COUNT_IF(FIELD_COUNT <> 39) odd_fields,
       COUNT_IF(IS_LPR) lpr_true, COUNT_IF(NOT IS_LPR) lpr_false, COUNT_IF(IS_LPR IS NULL) lpr_null,
       COUNT(DATE_DETAINED) detained_filled, COUNT(DATE_RELEASED) released_filled, COUNT(DATE_OF_ENTRY) entry_filled,
       MIN(DATE_DETAINED) det0, MAX(DATE_DETAINED) det1, COUNT_IF(DATE_DETAINED > '2026-09-24') det_future,
       MAX(ADDRESS_CHANGED_AT) addr_max, COUNT_IF(ADDRESS_CHANGED_AT > '2026-09-24') addr_future,
       MAX(IFF(LATEST_HEARING_AT <= '2026-09-24', LATEST_HEARING_AT, NULL)) hear_past_max, COUNT_IF(LATEST_HEARING_AT > '2026-09-24') hear_future,
       MIN(_LOADED_AT) load0, MAX(_LOADED_AT) load1, COUNT(DISTINCT _SOURCE_RUN_ID) runs,
       COUNT_IF(ALIEN_ZIPCODE = '00000') zip0, COUNT(DISTINCT COURT_CODE) courts
FROM LIBRARY_MARTS.IMMIGRATION.IMMIGRATION__FED_EOIR_CASES
GROUP BY 1,2 ORDER BY n DESC;

-- S07 eoir_detained_month_by_residence
SELECT DATE_TRUNC('month', DATE_DETAINED)::DATE mon,
       CASE WHEN DATE_OF_ENTRY IS NULL THEN 'no_entry_date'
            WHEN DATEDIFF('day', DATE_OF_ENTRY, DATE_DETAINED) < 0 THEN 'entry_after_detained'
            WHEN DATEDIFF('day', DATE_OF_ENTRY, DATE_DETAINED) <= 30 THEN 'a_0_30d'
            WHEN DATEDIFF('day', DATE_OF_ENTRY, DATE_DETAINED) < 730 THEN 'b_31d_2y'
            WHEN DATEDIFF('day', DATE_OF_ENTRY, DATE_DETAINED) < 3652 THEN 'c_2_10y'
            ELSE 'd_10y_plus' END bucket,
       COUNT(*) n, COUNT_IF(IS_LPR) lpr, COUNT_IF(CUSTODY = 'D') cust_d, COUNT_IF(DATE_RELEASED IS NOT NULL) released
FROM LIBRARY_MARTS.IMMIGRATION.IMMIGRATION__FED_EOIR_CASES
WHERE DATE_DETAINED >= '2018-01-01' AND DATE_DETAINED <= '2026-09-24'
GROUP BY 1,2 ORDER BY 1,2;

-- S08 eoir_janmay_by_entry_year
SELECT YEAR(DATE_DETAINED) det_yr, YEAR(DATE_OF_ENTRY) entry_yr, COUNT(*) n,
       MEDIAN(CASE_ID) med_case_id, MIN(CASE_ID) min_case_id, COUNT_IF(CUSTODY = 'D') cust_d, COUNT_IF(CUSTODY = 'R') cust_r
FROM LIBRARY_MARTS.IMMIGRATION.IMMIGRATION__FED_EOIR_CASES
WHERE MONTH(DATE_DETAINED) BETWEEN 1 AND 5 AND YEAR(DATE_DETAINED) IN (2023, 2024, 2025, 2026)
GROUP BY 1,2 ORDER BY 1,2;

-- S09 eoir_caseid_calibration_border
SELECT DATE_TRUNC('quarter', DATE_DETAINED)::DATE q, COUNT(*) n,
       APPROX_PERCENTILE(CASE_ID, 0.1) p10, MEDIAN(CASE_ID) p50, APPROX_PERCENTILE(CASE_ID, 0.9) p90
FROM LIBRARY_MARTS.IMMIGRATION.IMMIGRATION__FED_EOIR_CASES
WHERE DATE_DETAINED BETWEEN '2015-01-01' AND '2026-05-31'
  AND DATE_OF_ENTRY IS NOT NULL AND DATEDIFF('day', DATE_OF_ENTRY, DATE_DETAINED) BETWEEN 0 AND 30
GROUP BY 1 ORDER BY 1;

-- S10 eoir_nationality_docket_and_janmay_detained
SELECT NATIONALITY, COUNT(*) docket_all,
       COUNT_IF(DATE_DETAINED IS NOT NULL AND MONTH(DATE_DETAINED) <= 5 AND YEAR(DATE_DETAINED) = 2024) det24,
       COUNT_IF(DATE_DETAINED IS NOT NULL AND MONTH(DATE_DETAINED) <= 5 AND YEAR(DATE_DETAINED) = 2026) det26,
       COUNT_IF(MONTH(DATE_DETAINED) <= 5 AND YEAR(DATE_DETAINED) = 2024 AND DATEDIFF('day', DATE_OF_ENTRY, DATE_DETAINED) >= 730) res24,
       COUNT_IF(MONTH(DATE_DETAINED) <= 5 AND YEAR(DATE_DETAINED) = 2026 AND DATEDIFF('day', DATE_OF_ENTRY, DATE_DETAINED) >= 730) res26,
       COUNT_IF(MONTH(DATE_DETAINED) <= 5 AND YEAR(DATE_DETAINED) = 2026 AND DATE_OF_ENTRY IS NOT NULL) ent26,
       COUNT_IF(MONTH(DATE_DETAINED) <= 5 AND YEAR(DATE_DETAINED) = 2024 AND DATE_OF_ENTRY IS NOT NULL) ent24
FROM LIBRARY_MARTS.IMMIGRATION.IMMIGRATION__FED_EOIR_CASES
GROUP BY 1 ORDER BY docket_all DESC;

-- S11 eoir_fixed_cohort_entered_by_2021_by_nationality
-- Fixed cohort: entry date on or before 2021-12-31. Jan-May detentions per year. prior_case = CASE_ID below roughly the first case number issued that January (p10 of border cases detained that Q1, from S09).
SELECT NATIONALITY,
       COUNT_IF(DATE_OF_ENTRY <= '2021-12-31') pool_entered_by_2021,
       COUNT_IF(DATE_OF_ENTRY <= '2021-12-31' AND MONTH(DATE_DETAINED) <= 5 AND YEAR(DATE_DETAINED) = 2023) d23,
       COUNT_IF(DATE_OF_ENTRY <= '2021-12-31' AND MONTH(DATE_DETAINED) <= 5 AND YEAR(DATE_DETAINED) = 2024) d24,
       COUNT_IF(DATE_OF_ENTRY <= '2021-12-31' AND MONTH(DATE_DETAINED) <= 5 AND YEAR(DATE_DETAINED) = 2025) d25,
       COUNT_IF(DATE_OF_ENTRY <= '2021-12-31' AND MONTH(DATE_DETAINED) <= 5 AND YEAR(DATE_DETAINED) = 2026) d26,
       COUNT_IF(DATE_OF_ENTRY <= '2021-12-31' AND MONTH(DATE_DETAINED) <= 5 AND YEAR(DATE_DETAINED) = 2023 AND CASE_ID < 11379000) p23,
       COUNT_IF(DATE_OF_ENTRY <= '2021-12-31' AND MONTH(DATE_DETAINED) <= 5 AND YEAR(DATE_DETAINED) = 2024 AND CASE_ID < 13459000) p24,
       COUNT_IF(DATE_OF_ENTRY <= '2021-12-31' AND MONTH(DATE_DETAINED) <= 5 AND YEAR(DATE_DETAINED) = 2025 AND CASE_ID < 14828000) p25,
       COUNT_IF(DATE_OF_ENTRY <= '2021-12-31' AND MONTH(DATE_DETAINED) <= 5 AND YEAR(DATE_DETAINED) = 2026 AND CASE_ID < 15324000) p26,
       COUNT_IF(DATE_OF_ENTRY <= '2021-12-31' AND MONTH(DATE_DETAINED) <= 5 AND YEAR(DATE_DETAINED) = 2026 AND DATE_OF_ENTRY < '2006-01-01') d26_20y,
       COUNT_IF(DATE_OF_ENTRY <= '2021-12-31' AND MONTH(DATE_DETAINED) <= 5 AND YEAR(DATE_DETAINED) = 2024 AND DATE_OF_ENTRY < '2004-01-01') d24_20y,
       COUNT_IF(DATE_OF_ENTRY < '1940-01-01') entry_pre1940
FROM LIBRARY_MARTS.IMMIGRATION.IMMIGRATION__FED_EOIR_CASES
GROUP BY 1 ORDER BY pool_entered_by_2021 DESC;

-- S12 eoir_detained_date_fill_by_case_id_band
-- Dull-explanation test: did EOIR start filling DATE_DETAINED more often? Fill rate among detained/released-custody cases by case-number band (a proxy for when the case was opened, see S09).
SELECT FLOOR(CASE_ID / 500000) * 500000 band, COUNT(*) n,
       COUNT_IF(CUSTODY IN ('D','R')) dr, COUNT_IF(CUSTODY IN ('D','R') AND DATE_DETAINED IS NOT NULL) dr_det_filled,
       COUNT_IF(CUSTODY IN ('D','R') AND DATE_OF_ENTRY IS NOT NULL) dr_entry_filled,
       COUNT_IF(CUSTODY = 'N' AND DATE_DETAINED IS NOT NULL) n_with_det
FROM LIBRARY_MARTS.IMMIGRATION.IMMIGRATION__FED_EOIR_CASES
WHERE CASE_ID >= 9000000
GROUP BY 1 ORDER BY 1;

-- S13 ice_stints_corroborate_by_month
-- Second source for the EOIR lead: ICE detention stays by book-in month, split by entry date (fixed cohort: entered by 2021-12-31) and book-in criminality.
WITH s AS (
  SELECT STAY_ID, TRY_TO_DATE(LEFT(STAY_BOOK_IN_AT::VARCHAR, 10)) bi, TRY_TO_DATE(LEFT(ENTRY_DATE::VARCHAR, 10)) ent,
         ENTRY_DATE IS NOT NULL AND TRIM(ENTRY_DATE::VARCHAR) <> '' ent_raw, BOOK_IN_CRIMINALITY crim
  FROM LIBRARY_MARTS.IMMIGRATION.IMMIGRATION__FED_ICE_DETENTION_STINTS)
SELECT DATE_TRUNC('month', bi)::DATE mon, COUNT(DISTINCT STAY_ID) stays,
       COUNT(DISTINCT IFF(ent_raw, STAY_ID, NULL)) stays_entry_raw, COUNT(DISTINCT IFF(ent IS NOT NULL, STAY_ID, NULL)) stays_entry_parsed,
       COUNT(DISTINCT IFF(ent <= '2021-12-31', STAY_ID, NULL)) stays_entered_by_2021,
       COUNT(DISTINCT IFF(ent < '2006-01-01', STAY_ID, NULL)) stays_entered_pre2006,
       COUNT(DISTINCT IFF(ent <= '2021-12-31' AND crim ILIKE '%other%', STAY_ID, NULL)) by2021_other_violator,
       COUNT(DISTINCT IFF(ent <= '2021-12-31' AND crim ILIKE '%convicted%', STAY_ID, NULL)) by2021_convicted,
       COUNT(DISTINCT IFF(crim ILIKE '%other%', STAY_ID, NULL)) all_other_violator,
       ANY_VALUE(crim) crim_example
FROM s
WHERE bi >= '2023-01-01'
GROUP BY 1 ORDER BY 1;

-- Local math (no warehouse statements): g68/ohss.py (OHSS month parse + revisions), g68/clients.py and g68/clients2.py
-- (OFLC contractor-vs-client wage match on client name + SOC + worksite state [+ wage level]), g68/local_math.py (reproduces the md numbers).
