-- deep3/g75: deep pass 3, 2026-09-24. Python door (connect/db.py), read-only SELECT/WITH only, QUERY_TAG 'deep3-2026-09-24'.
-- Every connection first ran: ALTER SESSION SET STATEMENT_TIMEOUT_IN_SECONDS = 300; ALTER SESSION SET QUERY_TAG = 'deep3-2026-09-24'. Those two are not counted.
-- Tables: CORPORATE_REGISTRY__FED_ICIJ_OFFSHORELEAKS_ADDRESSES, CORPORATE_REGISTRY__FED_ICIJ_OFFSHORELEAKS_OTHERS, CORPORATE_REGISTRY__INTL_ES_BORME,
--         HOUSING__FED_HUD_ASSISTED_HOUSING_PROJECTS, HOUSING__FED_FHFA_NMDB.
-- 17 statements (S01-S17), all below, in run order. S06 failed on a type error (MONTHS_WAITING is already a number) and still counts.
-- S07-S14 are extracts; peer, time and name-match math on them ran locally in pandas (g75/match.py and inline scripts). Outputs: g75/out_Sxx.txt and .csv.

-- S01 BORME: every row, all 15
SELECT * FROM LIBRARY_MARTS.CORPORATE_REGISTRY.CORPORATE_REGISTRY__INTL_ES_BORME;

-- S02 FHFA NMDB: fill of the statistic columns, period shapes, duplicate keys
SELECT PERIOD_TYPE, COUNT(*) n, COUNT(DISTINCT GEO_CODE) geos, MIN(PERIOD_VALUE) p0, MAX(PERIOD_VALUE) p1,
       COUNT(DISTINCT PERIOD_VALUE) periods, COUNT(DISTINCT GEO_CODE, PERIOD_VALUE) keys,
       COUNT(STATISTIC_VALUE) stat_val_nonnull, COUNT(NULLIF(TRIM(STATISTIC_NAME),'')) stat_name_nonblank,
       COUNT(NULLIF(TRIM(STATISTIC_UNIT),'')) stat_unit_nonblank, COUNT(NULLIF(TRIM(DATASET_FAMILY),'')) fam_nonblank,
       COUNT(NULLIF(TRIM(GEO_TYPE),'')) geotype_nonblank, MIN(RELEASE_DATE) r0, MAX(RELEASE_DATE) r1,
       ARRAY_AGG(DISTINCT GEO_NAME) WITHIN GROUP (ORDER BY GEO_NAME) geo_names
FROM LIBRARY_MARTS.HOUSING.HOUSING__FED_FHFA_NMDB
GROUP BY 1 ORDER BY 1;

-- S03 ICIJ others: by leak, fill of every field, date range, id uniqueness
SELECT SOURCE_LEAK, COUNT(*) n, COUNT(DISTINCT NODE_ID) nodes, COUNT(INCORPORATION_DATE) inc, MIN(INCORPORATION_DATE) inc0, MAX(INCORPORATION_DATE) inc1,
       COUNT(STRUCK_OFF_DATE) struck, COUNT(CLOSED_DATE) closed, COUNT(NULLIF(TRIM(JURISDICTION),'')) jur, COUNT(NULLIF(TRIM(TYPE),'')) typ,
       COUNT(NULLIF(TRIM(COUNTRY_CODES),'')) cc, COUNT_IF(COUNTRY_CODES ILIKE '%USA%') usa, COUNT(NULLIF(TRIM(NOTE),'')) note,
       ARRAY_AGG(DISTINCT VALID_UNTIL) valid_until
FROM LIBRARY_MARTS.CORPORATE_REGISTRY.CORPORATE_REGISTRY__FED_ICIJ_OFFSHORELEAKS_OTHERS
GROUP BY ROLLUP(1) ORDER BY n DESC;

-- S04 ICIJ addresses: by leak, US share, blank names, duplicate address text, notes
SELECT SOURCE_LEAK, COUNT(*) n, COUNT(DISTINCT NODE_ID) nodes, COUNT(DISTINCT UPPER(TRIM(ADDRESS))) addr_text,
       COUNT_IF(COUNTRY_CODES ILIKE '%USA%') usa, COUNT_IF(COUNTRY_CODES = 'USA') usa_only,
       COUNT_IF(NAME IS NULL OR TRIM(NAME) IN ('','None')) name_blank, COUNT_IF(ADDRESS IS NULL OR TRIM(ADDRESS) IN ('','None')) addr_blank,
       COUNT_IF(COUNTRY_CODES IS NULL OR TRIM(COUNTRY_CODES) IN ('','XXX')) cc_blank, COUNT(NULLIF(TRIM(NOTE),'')) note,
       ARRAY_AGG(DISTINCT VALID_UNTIL) valid_until
FROM LIBRARY_MARTS.CORPORATE_REGISTRY.CORPORATE_REGISTRY__FED_ICIJ_OFFSHORELEAKS_ADDRESSES
GROUP BY ROLLUP(1) ORDER BY n DESC;

-- S05 ICIJ relationships: edge types and what sits at each end (address, officer, entity, intermediary, other)
WITH k AS (
  SELECT NODE_ID, 'address' kind FROM LIBRARY_MARTS.CORPORATE_REGISTRY.CORPORATE_REGISTRY__FED_ICIJ_OFFSHORELEAKS_ADDRESSES
  UNION ALL SELECT NODE_ID, 'officer' FROM LIBRARY_MARTS.CORPORATE_REGISTRY.CORPORATE_REGISTRY__FED_ICIJ_OFFSHORELEAKS_OFFICERS
  UNION ALL SELECT NODE_ID, 'entity' FROM LIBRARY_MARTS.CORPORATE_REGISTRY.CORPORATE_REGISTRY__FED_ICIJ_OFFSHORELEAKS_ENTITIES
  UNION ALL SELECT NODE_ID, 'intermediary' FROM LIBRARY_MARTS.CORPORATE_REGISTRY.CORPORATE_REGISTRY__FED_ICIJ_OFFSHORELEAKS_INTERMEDIARIES
  UNION ALL SELECT NODE_ID, 'other' FROM LIBRARY_MARTS.CORPORATE_REGISTRY.CORPORATE_REGISTRY__FED_ICIJ_OFFSHORELEAKS_OTHERS
), kk AS (SELECT NODE_ID, MIN(kind) kind, COUNT(*) dup FROM k GROUP BY 1)
SELECT r.REL_TYPE, s.kind start_kind, e.kind end_kind, COUNT(*) n, COUNT(DISTINCT r.NODE_ID_END) end_nodes,
       COUNT_IF(s.dup > 1 OR e.dup > 1) id_in_two_tables
FROM LIBRARY_MARTS.CORPORATE_REGISTRY.CORPORATE_REGISTRY__FED_ICIJ_OFFSHORELEAKS_RELATIONSHIPS r
LEFT JOIN kk s ON s.NODE_ID = r.NODE_ID_START
LEFT JOIN kk e ON e.NODE_ID = r.NODE_ID_END
GROUP BY 1,2,3 HAVING COUNT(*) >= 200 ORDER BY n DESC;

-- S06 HUD projects: vintage, programs, sentinels, id shape, duplicate codes
SELECT QUARTER, PROGRAM_LABEL, COUNT(*) n, COUNT(DISTINCT CODE) codes, SUM(IFF(TOTAL_UNITS > 0, TOTAL_UNITS, 0)) units,
       COUNT_IF(PCT_OCCUPIED < 0) occ_neg, COUNT_IF(SPENDING_PER_MONTH < 0) spend_neg, COUNT_IF(HH_INCOME < 0) inc_neg,
       COUNT_IF(TRY_TO_NUMBER(MONTHS_WAITING) < 0) wait_neg, COUNT_IF(TRY_TO_NUMBER(MONTHS_WAITING) >= 0) wait_ok,
       COUNT_IF(PCT_REPORTED < 0) rep_neg, MEDIAN(IFF(PCT_REPORTED >= 0, PCT_REPORTED, NULL)) med_rep,
       MEDIAN(IFF(PCT_OCCUPIED >= 0, PCT_OCCUPIED, NULL)) med_occ, MEDIAN(IFF(SPENDING_PER_MONTH >= 0, SPENDING_PER_MONTH, NULL)) med_spend,
       ANY_VALUE(CODE) code_eg, ANY_VALUE(ENTITIES) ent_eg, ARRAY_AGG(DISTINCT SUB_PROGRAM) subs, COUNT(NULLIF(TRIM(STD_ADDR),'')) addr, COUNT(NULLIF(TRIM(STD_ZIP5),'')) zip
FROM LIBRARY_MARTS.HOUSING.HOUSING__FED_HUD_ASSISTED_HOUSING_PROJECTS
GROUP BY 1,2 ORDER BY n DESC;

-- S07 HUD projects: pull the whole table (35.6K rows) for local peer math
SELECT * FROM LIBRARY_MARTS.HOUSING.HOUSING__FED_HUD_ASSISTED_HOUSING_PROJECTS;

-- S08 HUD housing authorities: status, size, vacancy, money, for the public-housing join
SELECT PARTICIPANT_CODE, FORMAL_PARTICIPANT_NAME, PHAS_DESIGNATION, HA_PROGRAM_TYPE, HA_COMBINED_SIZE_CATEGORY, HA_LOW_RENT_SIZE_CATEGORY,
       TOTAL_UNITS, TOTAL_DWELLING_UNITS, ACC_UNITS, PUBLIC_HOUSING_OCCUPIED, SECTION8_OCCUPIED, TOTAL_OCCUPIED, PCT_OCCUPIED, REGULAR_VACANT,
       PHA_TOTAL_UNITS, NUMBER_REPORTED, PCT_REPORTED, OPERATING_FUND_AMOUNT, OPERATING_FUND_AMOUNT_PREV_YR, CAPITAL_FUND_AMOUNT,
       CAPITAL_FUND_AMOUNT_PREV_YR, SPENDING_PER_MONTH, ANNUAL_EXPENSE_AMOUNT, STD_STATE, STD_CITY, CBSA_CODE, CBSA_NAME, LAST_UPDATED_AT
FROM LIBRARY_MARTS.HOUSING.HOUSING__FED_HUD_PUBLIC_HOUSING_AUTHORITIES;

-- S09 HUD Section 8 contracts: property id, expiry, units, rent-to-FMR, for the project join
SELECT CONTRACT_NUMBER, PROPERTY_ID, PROPERTY_NAME, TRACS_EFFECTIVE_DATE, TRACS_OVERALL_EXPIRATION_DATE, TRACS_CURRENT_EXPIRATION_DATE,
       TRACS_STATUS_NAME, PROGRAM_TYPE_NAME, PROGRAM_TYPE_GROUP_NAME, ASSISTED_UNITS_COUNT, RENT_TO_FMR_RATIO, CONTRACT_TERM_MONTHS_QTY
FROM LIBRARY_MARTS.HOUSING.HOUSING__FED_HUD_MF_SECTION8_CONTRACTS;

-- S10 ICIJ: every node tied to a US address (via registered_address), plus US-coded officers/intermediaries with no US address
WITH us_addr AS (
  SELECT NODE_ID, NULLIF(TRIM(ADDRESS),'') a1, NULLIF(TRIM(NAME),'') a2
  FROM LIBRARY_MARTS.CORPORATE_REGISTRY.CORPORATE_REGISTRY__FED_ICIJ_OFFSHORELEAKS_ADDRESSES
  WHERE COUNTRY_CODES ILIKE '%USA%'
), ra AS (
  SELECT NODE_ID_START, NODE_ID_END FROM LIBRARY_MARTS.CORPORATE_REGISTRY.CORPORATE_REGISTRY__FED_ICIJ_OFFSHORELEAKS_RELATIONSHIPS
  WHERE REL_TYPE = 'registered_address'
), nodes AS (
  SELECT NODE_ID, 'officer' kind, NAME, COUNTRY_CODES, SOURCE_LEAK FROM LIBRARY_MARTS.CORPORATE_REGISTRY.CORPORATE_REGISTRY__FED_ICIJ_OFFSHORELEAKS_OFFICERS
  UNION ALL SELECT NODE_ID, 'entity', NAME, COUNTRY_CODES, SOURCE_LEAK FROM LIBRARY_MARTS.CORPORATE_REGISTRY.CORPORATE_REGISTRY__FED_ICIJ_OFFSHORELEAKS_ENTITIES
  UNION ALL SELECT NODE_ID, 'intermediary', NAME, COUNTRY_CODES, SOURCE_LEAK FROM LIBRARY_MARTS.CORPORATE_REGISTRY.CORPORATE_REGISTRY__FED_ICIJ_OFFSHORELEAKS_INTERMEDIARIES
  UNION ALL SELECT NODE_ID, 'other', NAME, COUNTRY_CODES, SOURCE_LEAK FROM LIBRARY_MARTS.CORPORATE_REGISTRY.CORPORATE_REGISTRY__FED_ICIJ_OFFSHORELEAKS_OTHERS
), via_addr AS (
  SELECT n.NODE_ID, n.kind, n.NAME, n.COUNTRY_CODES, n.SOURCE_LEAK, a.NODE_ID addr_node, COALESCE(a.a1, a.a2) addr_text
  FROM us_addr a JOIN ra ON ra.NODE_ID_END = a.NODE_ID JOIN nodes n ON n.NODE_ID = ra.NODE_ID_START
), via_code AS (
  SELECT n.NODE_ID, n.kind, n.NAME, n.COUNTRY_CODES, n.SOURCE_LEAK, NULL addr_node, NULL addr_text
  FROM nodes n
  WHERE n.COUNTRY_CODES ILIKE '%USA%' AND n.kind IN ('officer','intermediary')
    AND n.NODE_ID NOT IN (SELECT NODE_ID FROM via_addr)
), unlinked AS (
  SELECT NULL NODE_ID, 'address_only' kind, NULL NAME, NULL COUNTRY_CODES, NULL SOURCE_LEAK, a.NODE_ID addr_node, COALESCE(a.a1, a.a2) addr_text
  FROM us_addr a WHERE a.NODE_ID NOT IN (SELECT NODE_ID_END FROM ra)
)
SELECT * FROM via_addr UNION ALL SELECT * FROM via_code UNION ALL SELECT * FROM unlinked;

-- S11 OIG exclusion list (LEIE): names and addresses for the ICIJ match
SELECT LAST_NAME, FIRST_NAME, MIDDLE_NAME, BUSINESS_NAME, GENERAL_CATEGORY, SPECIALTY, EXCLUSION_TYPE, EXCLUSION_DATE, REINSTATEMENT_DATE,
       ADDRESS, CITY, STATE, ZIP, IS_ENTITY_NOT_INDIVIDUAL, NPI
FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_HHS_OIG_LEIE;

-- S12 SAM exclusions: names and places for the ICIJ match
SELECT SAM_NUMBER, ENTITY_NAME, FIRST_NAME, LAST_NAME, CLASSIFICATION, EXCLUSION_TYPE, EXCLUSION_PROGRAM, EXCLUDING_AGENCY,
       ACTIVATION_DATE, TERMINATION_DATE_RAW, CITY, STATE, ZIP, COUNTRY, IS_CURRENTLY_EXCLUDED, IS_ENTITY_NOT_INDIVIDUAL
FROM LIBRARY_MARTS.PROCUREMENT.PROCUREMENT__FED_SAM_EXCLUSIONS;

-- S13 ICIJ others: whole table plus how many edges touch each node
WITH e AS (
  SELECT NODE_ID_START nid, REL_TYPE FROM LIBRARY_MARTS.CORPORATE_REGISTRY.CORPORATE_REGISTRY__FED_ICIJ_OFFSHORELEAKS_RELATIONSHIPS
  UNION ALL SELECT NODE_ID_END, REL_TYPE FROM LIBRARY_MARTS.CORPORATE_REGISTRY.CORPORATE_REGISTRY__FED_ICIJ_OFFSHORELEAKS_RELATIONSHIPS
), c AS (SELECT nid, COUNT(*) edges, LISTAGG(DISTINCT REL_TYPE, '|') rels FROM e GROUP BY 1)
SELECT o.*, c.edges, c.rels
FROM LIBRARY_MARTS.CORPORATE_REGISTRY.CORPORATE_REGISTRY__FED_ICIJ_OFFSHORELEAKS_OTHERS o LEFT JOIN c ON c.nid = o.NODE_ID;

-- S14 FHFA suspended counterparties and FDIC enforcement orders: names for the ICIJ match
SELECT 'FHFA' src, TRIM(COALESCE(FIRST_NAME,'') || ' ' || COALESCE(LAST_NAME,'')) person, COMPANY org, CITY, STATE,
       TO_VARCHAR(EFFECTIVE_DATE) dt, NULL amt, SUSPENSION_ORDER doc
FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_FHFA_SUSPENDED_COUNTERPARTIES
UNION ALL
SELECT 'FDIC', RESPONDENTS, INSTITUTION_NAME, CITY, STATE, TO_VARCHAR(ORDER_DATE), CMP_AMOUNT_TOTAL, DOCUMENT_URL
FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_FDIC_ENFORCEMENT_ORDERS;

-- S15 ICIJ: the offshore companies behind the 4 people who match the OIG exclusion list on name plus address or ZIP, with edge dates
WITH ids AS (
  SELECT column1 nid FROM VALUES ('240380892'),('240380893'),('240380894'),('116682'),('50374'),('116538'),('43492'),('292103'),('51081'),
                                 ('116734'),('56635'),('59489'),('110260'),('113850'),('171052')
), e AS (
  SELECT r.NODE_ID_START a, r.NODE_ID_END b, r.REL_TYPE, r.LINK, r.STATUS, r.START_DATE, r.END_DATE, r.SOURCE_LEAK
  FROM LIBRARY_MARTS.CORPORATE_REGISTRY.CORPORATE_REGISTRY__FED_ICIJ_OFFSHORELEAKS_RELATIONSHIPS r
  WHERE r.NODE_ID_START IN (SELECT nid FROM ids) OR r.NODE_ID_END IN (SELECT nid FROM ids)
)
SELECT e.a, COALESCE(oa.NAME, ia.NAME, ea.NAME) a_name, e.REL_TYPE, e.LINK, e.STATUS rel_status, e.START_DATE, e.END_DATE,
       e.b, COALESCE(en.NAME, ob.NAME, ib.NAME, ad.ADDRESS) b_name, en.JURISDICTION_DESCRIPTION, en.COMPANY_TYPE, en.INCORPORATION_DATE,
       en.INACTIVATION_DATE, en.STRUCK_OFF_DATE, en.STATUS ent_status, en.SERVICE_PROVIDER, e.SOURCE_LEAK
FROM e
LEFT JOIN LIBRARY_MARTS.CORPORATE_REGISTRY.CORPORATE_REGISTRY__FED_ICIJ_OFFSHORELEAKS_OFFICERS oa ON oa.NODE_ID = e.a
LEFT JOIN LIBRARY_MARTS.CORPORATE_REGISTRY.CORPORATE_REGISTRY__FED_ICIJ_OFFSHORELEAKS_INTERMEDIARIES ia ON ia.NODE_ID = e.a
LEFT JOIN LIBRARY_MARTS.CORPORATE_REGISTRY.CORPORATE_REGISTRY__FED_ICIJ_OFFSHORELEAKS_ENTITIES ea ON ea.NODE_ID = e.a
LEFT JOIN LIBRARY_MARTS.CORPORATE_REGISTRY.CORPORATE_REGISTRY__FED_ICIJ_OFFSHORELEAKS_ENTITIES en ON en.NODE_ID = e.b
LEFT JOIN LIBRARY_MARTS.CORPORATE_REGISTRY.CORPORATE_REGISTRY__FED_ICIJ_OFFSHORELEAKS_OFFICERS ob ON ob.NODE_ID = e.b
LEFT JOIN LIBRARY_MARTS.CORPORATE_REGISTRY.CORPORATE_REGISTRY__FED_ICIJ_OFFSHORELEAKS_INTERMEDIARIES ib ON ib.NODE_ID = e.b
LEFT JOIN LIBRARY_MARTS.CORPORATE_REGISTRY.CORPORATE_REGISTRY__FED_ICIJ_OFFSHORELEAKS_ADDRESSES ad ON ad.NODE_ID = e.b
ORDER BY e.a, e.REL_TYPE, e.b;

-- S16 ICIJ denominator: people at US addresses, by leak and by the kind of offshore vehicle they sit on (how many hold Cook Islands asset-protection trusts)
WITH us_addr AS (
  SELECT NODE_ID FROM LIBRARY_MARTS.CORPORATE_REGISTRY.CORPORATE_REGISTRY__FED_ICIJ_OFFSHORELEAKS_ADDRESSES WHERE COUNTRY_CODES ILIKE '%USA%'
), ppl AS (
  SELECT DISTINCT r.NODE_ID_START pid
  FROM LIBRARY_MARTS.CORPORATE_REGISTRY.CORPORATE_REGISTRY__FED_ICIJ_OFFSHORELEAKS_RELATIONSHIPS r
  JOIN us_addr a ON a.NODE_ID = r.NODE_ID_END
  WHERE r.REL_TYPE = 'registered_address'
    AND r.NODE_ID_START NOT IN (SELECT NODE_ID FROM LIBRARY_MARTS.CORPORATE_REGISTRY.CORPORATE_REGISTRY__FED_ICIJ_OFFSHORELEAKS_ENTITIES)
), links AS (
  SELECT p.pid, en.NODE_ID eid, en.SOURCE_LEAK, en.JURISDICTION_DESCRIPTION jur, en.COMPANY_TYPE, en.SERVICE_PROVIDER
  FROM ppl p
  JOIN LIBRARY_MARTS.CORPORATE_REGISTRY.CORPORATE_REGISTRY__FED_ICIJ_OFFSHORELEAKS_RELATIONSHIPS r ON r.NODE_ID_START = p.pid AND r.REL_TYPE IN ('officer_of','intermediary_of')
  JOIN LIBRARY_MARTS.CORPORATE_REGISTRY.CORPORATE_REGISTRY__FED_ICIJ_OFFSHORELEAKS_ENTITIES en ON en.NODE_ID = r.NODE_ID_END
)
SELECT SOURCE_LEAK, jur, IFF(COMPANY_TYPE ILIKE '%asset protection%', 'asset protection trust', 'other') vehicle,
       COUNT(DISTINCT pid) people, COUNT(DISTINCT eid) entities, ANY_VALUE(SERVICE_PROVIDER) provider_eg
FROM links
GROUP BY GROUPING SETS ((SOURCE_LEAK, jur, vehicle), (SOURCE_LEAK), ())
HAVING COUNT(DISTINCT pid) >= 20 OR jur IS NULL
ORDER BY people DESC;

-- S17 the two excluded doctors in the ICIJ match: were they paid after exclusion (findings table), by NPI
SELECT 'paid_after' src, NPI, LAST_NAME, FIRST_NAME, EXCLUSION_TYPE, TO_VARCHAR(EXCLUSION_YEAR) excl_year,
       TO_VARCHAR(TOTAL_PAID_AFTER_EXCLUSION) paid, TO_VARCHAR(FIRST_PAID_YEAR) first_paid, TO_VARCHAR(LAST_PAID_YEAR) last_paid
FROM LIBRARY_MARTS.FINDINGS.EXCLUDED_PROVIDER_PAID_AFTER_EXCLUSION
WHERE NPI IN ('1659445690','1639395619') OR UPPER(LAST_NAME) IN ('BRESSI','KAMRAVA','ROIX','GOLDEN');
