-- deep3/g76: deep pass 3, 2026-09-24. Python door (connect/db.py), read-only SELECT/WITH only, QUERY_TAG 'deep3-2026-09-24'.
-- Every connection first ran: ALTER SESSION SET STATEMENT_TIMEOUT_IN_SECONDS = 300; ALTER SESSION SET QUERY_TAG = 'deep3-2026-09-24'. Those two are not counted.
-- Tables: HOUSING__FED_FEMA_NFIP_COMMUNITY_STATUS_BOOK, HOUSING__FED_FHFA_HPI, HOUSING__FED_CFPB_HMDA_ARID2017_LEI_XREF, HOUSING__FED_HUD_DATA, SCIENCE__FED_NSF_AWARDS.
-- Join partner read: HOUSING__FED_FEMA_IA_HOUSING_REGISTRATIONS (aggregated before any join), HOUSING__FED_CFPB_HMDA_HISTORIC (aggregated to lenders).
-- 17 statements (S01-S17), all below, in run order. S08-S11 are extracts; the join, peer, size and time math on them ran locally in pandas
-- (g76/join_nfip.py, a_sanction.py, b_mapage.py, d_isc_and_size.py, e_hpi.py). Outputs: g76/out_Sxx.json and g76/out_Sxx.csv.

-- S01 columns and types for the five tables plus the FEMA household-aid table (join candidate)
SELECT TABLE_SCHEMA, TABLE_NAME, LISTAGG(COLUMN_NAME || ':' || DATA_TYPE, ', ') WITHIN GROUP (ORDER BY ORDINAL_POSITION) cols
FROM LIBRARY_MARTS.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME IN ('HOUSING__FED_FEMA_NFIP_COMMUNITY_STATUS_BOOK','HOUSING__FED_FHFA_HPI','HOUSING__FED_CFPB_HMDA_ARID2017_LEI_XREF',
                     'HOUSING__FED_HUD_DATA','SCIENCE__FED_NSF_AWARDS','HOUSING__FED_FEMA_IA_HOUSING_REGISTRATIONS')
GROUP BY 1,2 ORDER BY 2;

-- S02 HUD_DATA: confirm it is a link list (fill of every column, distinct links)
SELECT COUNT(*) n, COUNT(DISTINCT DATASET_URL) urls, COUNT(DISTINCT DATASET_NAME) names,
       COUNT_IF(NULLIF(TRIM(TO_VARCHAR(EIN)),'') IS NOT NULL) ein_filled, COUNT_IF(NULLIF(TRIM(TO_VARCHAR(FIPS)),'') IS NOT NULL) fips_filled,
       COUNT_IF(NULLIF(TRIM(TO_VARCHAR(ZIP)),'') IS NOT NULL) zip_filled, COUNT_IF(NULLIF(TRIM(TO_VARCHAR(YEAR)),'') IS NOT NULL) year_filled,
       COUNT_IF(NULLIF(TRIM(DESCRIPTION),'') IS NOT NULL) desc_filled, COUNT_IF(NULLIF(TRIM(VALUE),'') IS NOT NULL) value_filled,
       ARRAY_AGG(DISTINCT LEFT(DATASET_NAME, 60)) WITHIN GROUP (ORDER BY LEFT(DATASET_NAME, 60)) sample_names
FROM LIBRARY_MARTS.HOUSING.HOUSING__FED_HUD_DATA;

-- S03 ARID2017-LEI crosswalk: is it one row per lender? why do ARIDs and LEIs repeat? sample the top repeaters
WITH x AS (SELECT * FROM LIBRARY_MARTS.HOUSING.HOUSING__FED_CFPB_HMDA_ARID2017_LEI_XREF),
s AS (
  SELECT COUNT(*) n, COUNT(DISTINCT ARID_2017) arids, COUNT(DISTINCT LEI_2018) lei18,
         COUNT(DISTINCT NULLIF(TRIM(LEI_2019),'')) lei19, COUNT(DISTINCT NULLIF(TRIM(LEI_2020),'')) lei20,
         COUNT_IF(NULLIF(TRIM(LEI_2019),'') IS NULL) lei19_blank, COUNT_IF(NULLIF(TRIM(LEI_2020),'') IS NULL) lei20_blank,
         COUNT_IF(LEI_2018 = LEI_2019) same_18_19, COUNT_IF(LEI_2019 = LEI_2020) same_19_20,
         COUNT(DISTINCT RESPONDENT_NAME) names
  FROM x),
top_arid AS (SELECT ARID_2017 FROM x GROUP BY 1 ORDER BY COUNT(*) DESC LIMIT 1),
top_lei AS (SELECT LEI_2019 FROM x WHERE NULLIF(TRIM(LEI_2019),'') IS NOT NULL GROUP BY 1 ORDER BY COUNT(*) DESC LIMIT 1)
SELECT 'SUMMARY' k, n::varchar a, arids::varchar b, lei18::varchar c, lei19::varchar d, lei20::varchar e,
       'blank19=' || lei19_blank || ' blank20=' || lei20_blank || ' same1819=' || same_18_19 || ' same1920=' || same_19_20 || ' names=' || names f
FROM s
UNION ALL
SELECT * FROM (SELECT 'TOP_ARID', ARID_2017, RESPONDENT_NAME, LEI_2018, LEI_2019, LEI_2020, NULL FROM x WHERE ARID_2017 IN (SELECT * FROM top_arid) LIMIT 8)
UNION ALL
SELECT * FROM (SELECT 'TOP_LEI19', ARID_2017, RESPONDENT_NAME, LEI_2018, LEI_2019, LEI_2020, NULL FROM x WHERE LEI_2019 IN (SELECT * FROM top_lei) LIMIT 8);

-- S04 NSF awards: profile plus every award of $2M or more
WITH x AS (SELECT * FROM LIBRARY_MARTS.SCIENCE.SCIENCE__FED_NSF_AWARDS),
s AS (SELECT COUNT(*) n, COUNT(DISTINCT AWARD_ID) ids, SUM(TRY_TO_NUMBER(TO_VARCHAR(AWARD_AMOUNT))) total,
             MEDIAN(TRY_TO_NUMBER(TO_VARCHAR(AWARD_AMOUNT))) med, COUNT(DISTINCT AWARDEE_NAME) awardees, COUNT(DISTINCT PROGRAM_NAME) programs,
             COUNT_IF(NULLIF(TRIM(TO_VARCHAR(EIN)),'') IS NOT NULL) ein_filled, COUNT_IF(NULLIF(TRIM(TO_VARCHAR(STATUS)),'') IS NOT NULL) status_filled,
             MIN(AWARD_DATE) d0, MAX(AWARD_DATE) d1, COUNT(DISTINCT AWARD_DATE) days, COUNT(DISTINCT STATE) states,
             COUNT_IF(NULLIF(TRIM(ABSTRACT),'') IS NOT NULL) abstract_filled
      FROM x)
SELECT s.*, x.AWARD_ID, x.AWARDEE_NAME, x.STATE, x.PROGRAM_NAME, x.AWARD_AMOUNT, x.AWARD_DATE, x.START_DATE, x.END_DATE, LEFT(x.TITLE, 90) title
FROM s LEFT JOIN x ON TRY_TO_NUMBER(TO_VARCHAR(x.AWARD_AMOUNT)) >= 2000000
ORDER BY TRY_TO_NUMBER(TO_VARCHAR(x.AWARD_AMOUNT)) DESC NULLS LAST;

-- S05 NFIP community status book: flags, fill, date ranges, future dates (two-digit-year parse check), load runs
SELECT PARTICIPATING_IN_NFIP_FLAG p, TRIBAL_FLAG t, COUNT(*) n, COUNT(DISTINCT COMMUNITY_ID_NUMBER) ids,
       COUNT_IF(INITIAL_FLOOD_HAZARD_BOUNDARY_MAP_DATE IS NOT NULL) fhbm, COUNT_IF(INITIAL_FLOOD_INSURANCE_RATE_MAP_DATE IS NOT NULL) firm,
       COUNT_IF(CURRENTLY_EFFECTIVE_MAP_DATE IS NOT NULL) cem, COUNT_IF(CURRENTLY_EFFECTIVE_MAP_DATE_RAW ILIKE '%NSFHA%') nsfha,
       COUNT_IF(REGULAR_EMERGENCY_PROGRAM_DATE IS NOT NULL) reg, COUNT_IF(NULLIF(TRIM(CRS_CLASS_RATING),'') IS NOT NULL) crs,
       COUNT_IF(INITIAL_FLOOD_HAZARD_BOUNDARY_MAP_DATE > CURRENT_DATE) fhbm_fut, COUNT_IF(INITIAL_FLOOD_INSURANCE_RATE_MAP_DATE > CURRENT_DATE) firm_fut,
       COUNT_IF(CURRENTLY_EFFECTIVE_MAP_DATE > CURRENT_DATE) cem_fut, COUNT_IF(REGULAR_EMERGENCY_PROGRAM_DATE > CURRENT_DATE) reg_fut,
       COUNT_IF(ORIGINAL_ENTRY_DATE > CURRENT_DATE) orig_fut, COUNT_IF(CLASS_RATING_EFFECTIVE_DATE > CURRENT_DATE) cls_fut,
       MIN(INITIAL_FLOOD_HAZARD_BOUNDARY_MAP_DATE) fhbm0, MIN(INITIAL_FLOOD_INSURANCE_RATE_MAP_DATE) firm0, MAX(INITIAL_FLOOD_INSURANCE_RATE_MAP_DATE) firm1,
       MIN(CURRENTLY_EFFECTIVE_MAP_DATE) cem0, MAX(CURRENTLY_EFFECTIVE_MAP_DATE) cem1, MIN(REGULAR_EMERGENCY_PROGRAM_DATE) reg0, MAX(REGULAR_EMERGENCY_PROGRAM_DATE) reg1,
       COUNT_IF(INITIAL_FLOOD_INSURANCE_RATE_MAP_DATE < INITIAL_FLOOD_HAZARD_BOUNDARY_MAP_DATE) firm_before_fhbm,
       COUNT_IF(CURRENTLY_EFFECTIVE_MAP_DATE < INITIAL_FLOOD_INSURANCE_RATE_MAP_DATE) cem_before_firm,
       COUNT(DISTINCT _SOURCE_RUN_ID) runs, MAX(LAST_REFRESH_AT) refresh1, MIN(LAST_REFRESH_AT) refresh0
FROM LIBRARY_MARTS.HOUSING.HOUSING__FED_FEMA_NFIP_COMMUNITY_STATUS_BOOK
GROUP BY ROLLUP(1,2) ORDER BY 1,2;

-- S06 NFIP book: what the raw map-date text says when it is not a date, future-date years, CRS classes, name suffix types, ID shape
WITH b AS (SELECT * FROM LIBRARY_MARTS.HOUSING.HOUSING__FED_FEMA_NFIP_COMMUNITY_STATUS_BOOK)
SELECT * FROM (SELECT 'RAW_NOT_DATE' k, CURRENTLY_EFFECTIVE_MAP_DATE_RAW v, COUNT(*) n FROM b WHERE CURRENTLY_EFFECTIVE_MAP_DATE IS NULL GROUP BY 2 ORDER BY 3 DESC LIMIT 15)
UNION ALL SELECT * FROM (SELECT 'RAW_SAMPLE', CURRENTLY_EFFECTIVE_MAP_DATE_RAW || ' -> ' || TO_VARCHAR(CURRENTLY_EFFECTIVE_MAP_DATE), COUNT(*) FROM b WHERE CURRENTLY_EFFECTIVE_MAP_DATE IS NOT NULL GROUP BY 2 ORDER BY 3 DESC LIMIT 5)
UNION ALL SELECT 'FUT_FHBM_YR', TO_VARCHAR(YEAR(INITIAL_FLOOD_HAZARD_BOUNDARY_MAP_DATE)), COUNT(*) FROM b WHERE INITIAL_FLOOD_HAZARD_BOUNDARY_MAP_DATE > CURRENT_DATE GROUP BY 2
UNION ALL SELECT 'FUT_REG_YR', TO_VARCHAR(YEAR(REGULAR_EMERGENCY_PROGRAM_DATE)), COUNT(*) FROM b WHERE REGULAR_EMERGENCY_PROGRAM_DATE > CURRENT_DATE GROUP BY 2
UNION ALL SELECT 'REG_YR_1968_75', TO_VARCHAR(YEAR(REGULAR_EMERGENCY_PROGRAM_DATE)), COUNT(*) FROM b WHERE YEAR(REGULAR_EMERGENCY_PROGRAM_DATE) BETWEEN 1960 AND 1975 GROUP BY 2
UNION ALL SELECT 'CRS', CRS_CLASS_RATING, COUNT(*) FROM b GROUP BY 2
UNION ALL SELECT * FROM (SELECT 'SUFFIX', COALESCE(REGEXP_SUBSTR(COMMUNITY_NAME, ',\\s*([^,]*)$', 1, 1, 'e'), '(none)'), COUNT(*) FROM b GROUP BY 2 ORDER BY 3 DESC LIMIT 25)
UNION ALL SELECT 'ID_LEN', TO_VARCHAR(LENGTH(COMMUNITY_ID_NUMBER)) || ' state_prefix_distinct_per_state=' || TO_VARCHAR(COUNT(DISTINCT STATE)), COUNT(*) FROM b GROUP BY LENGTH(COMMUNITY_ID_NUMBER)
UNION ALL SELECT * FROM (SELECT 'NAME_SAMPLE', COMMUNITY_ID_NUMBER || ' | ' || COMMUNITY_NAME || ' | ' || COALESCE(COUNTY,'') || ' | ' || STATE || ' | p=' || COALESCE(PARTICIPATING_IN_NFIP_FLAG,'') || ' | cem=' || COALESCE(CURRENTLY_EFFECTIVE_MAP_DATE_RAW,''), 1 FROM b SAMPLE (12 ROWS));

-- S07 FEMA household aid: rows vs distinct registrations, incident types, flood fields, date span, load runs
SELECT INCIDENT_TYPE_CODE, COUNT(*) n, COUNT(DISTINCT REGISTRATION_ID) regs, COUNT(DISTINCT DISASTER_NUMBER) disasters,
       MIN(DECLARATION_DATE) d0, MAX(DECLARATION_DATE) d1,
       COUNT_IF(UPPER(FLOOD_DAMAGE) IN ('TRUE','1','T','Y','1.0')) flood_dmg, COUNT_IF(UPPER(FLOOD_INSURANCE) IN ('TRUE','1','T','Y','1.0')) flood_ins,
       ARRAY_AGG(DISTINCT FLOOD_DAMAGE) fd_vals, ARRAY_AGG(DISTINCT FLOOD_INSURANCE) fi_vals, ARRAY_AGG(DISTINCT OWN_RENT) own_vals,
       COUNT_IF(NULLIF(TRIM(FIPS),'') IS NOT NULL) fips_filled, COUNT_IF(NULLIF(TRIM(COUNTY),'') IS NOT NULL) county_filled,
       COUNT_IF(NULLIF(TRIM(DAMAGED_CITY),'') IS NOT NULL) city_filled, SUM(IHP_AMOUNT) ihp, SUM(REPAIR_AMOUNT) repair,
       COUNT(DISTINCT _SOURCE_RUN_ID) runs
FROM LIBRARY_MARTS.HOUSING.HOUSING__FED_FEMA_IA_HOUSING_REGISTRATIONS
GROUP BY ROLLUP(1) ORDER BY n DESC;

-- S08 EXTRACT NFIP community status book, every community (25K rows), for local peer and map-age math
SELECT COMMUNITY_ID_NUMBER, COMMUNITY_NAME, COUNTY, STATE, INITIAL_FLOOD_HAZARD_BOUNDARY_MAP_DATE fhbm, INITIAL_FLOOD_INSURANCE_RATE_MAP_DATE firm,
       CURRENTLY_EFFECTIVE_MAP_DATE_RAW cem_raw, CURRENTLY_EFFECTIVE_MAP_DATE cem, REGULAR_EMERGENCY_PROGRAM_DATE reg, ORIGINAL_ENTRY_DATE crs_entry,
       TRIBAL_FLAG, PARTICIPATING_IN_NFIP_FLAG, CLASS_RATING_EFFECTIVE_DATE, CRS_CLASS_RATING, LAST_REFRESH_AT
FROM LIBRARY_MARTS.HOUSING.HOUSING__FED_FEMA_NFIP_COMMUNITY_STATUS_BOOK;

-- S09 EXTRACT FEMA household aid, flood-damaged registrations only, aggregated to disaster x state x city x county x own/rent (aggregate before joining)
SELECT DISASTER_NUMBER, INCIDENT_TYPE_CODE, MIN(DECLARATION_DATE) decl, DAMAGED_STATE_ABBREVIATION st, UPPER(TRIM(DAMAGED_CITY)) city,
       UPPER(TRIM(COUNTY)) county, MIN(FIPS) fips_min, MAX(FIPS) fips_max, OWN_RENT,
       COUNT(*) regs, COUNT(DISTINCT REGISTRATION_ID) ids,
       COUNT_IF(FLOOD_INSURANCE = 'True') flood_ins, COUNT_IF(HOMEOWNERS_INSURANCE = 'True') home_ins,
       COUNT_IF(IHP_ELIGIBLE = 'True') ihp_elig, SUM(IHP_AMOUNT) ihp_amt, SUM(REPAIR_AMOUNT) repair_amt, COUNT_IF(REPAIR_AMOUNT > 0) repair_n,
       SUM(RPFVL) rpfvl, SUM(UNMET_NEED_RP) unmet_rp, SUM(FLOOD_DAMAGE_AMOUNT) flood_dmg_amt, COUNT_IF(PRIMARY_RESIDENCE = 'True') primary_res
FROM LIBRARY_MARTS.HOUSING.HOUSING__FED_FEMA_IA_HOUSING_REGISTRATIONS
WHERE FLOOD_DAMAGE = 'True'
GROUP BY DISASTER_NUMBER, INCIDENT_TYPE_CODE, DAMAGED_STATE_ABBREVIATION, UPPER(TRIM(DAMAGED_CITY)), UPPER(TRIM(COUNTY)), OWN_RENT;

-- S10 EXTRACT FHFA house price index, whole table (185K rows), for local metro-vs-state peer and peak-to-now math
SELECT HPI_TYPE, HPI_FLAVOR, FREQUENCY, LEVEL, PLACE_NAME, PLACE_ID, YR, PERIOD, INDEX_NSA, INDEX_SA, RSTDERR, NOTE
FROM LIBRARY_MARTS.HOUSING.HOUSING__FED_FHFA_HPI;

-- S11 NSF awards, all 115 rows (small), to read programs, dates, places and abstracts
SELECT AWARD_ID, TITLE, AWARDEE_NAME, INSTITUTION, PI_NAME, PROGRAM_OFFICER, AWARD_AMOUNT, AWARD_DATE, START_DATE, END_DATE,
       PROGRAM_NAME, CITY, STATE, ZIP, COUNTRY, CFDA_NUMBER, LEFT(ABSTRACT, 600) abstract600, LENGTH(ABSTRACT) abstract_len
FROM LIBRARY_MARTS.SCIENCE.SCIENCE__FED_NSF_AWARDS
ORDER BY AWARD_AMOUNT DESC;

-- S12 FEMA household aid, flood-damaged only: every housing-aid decision code and ineligible-reason code, with counts and repair money
SELECT 'HA_STATUS' k, HA_STATUS v, COUNT(*) n, COUNT_IF(OWN_RENT = 'O') owners, COUNT_IF(REPAIR_AMOUNT > 0) repair_n, SUM(REPAIR_AMOUNT) repair_amt, COUNT_IF(FLOOD_INSURANCE = 'True') flood_ins
FROM LIBRARY_MARTS.HOUSING.HOUSING__FED_FEMA_IA_HOUSING_REGISTRATIONS WHERE FLOOD_DAMAGE = 'True' GROUP BY 2
UNION ALL
SELECT 'INELIGIBLE_REASON', INELIGIBLE_REASON, COUNT(*), COUNT_IF(OWN_RENT = 'O'), COUNT_IF(REPAIR_AMOUNT > 0), SUM(REPAIR_AMOUNT), COUNT_IF(FLOOD_INSURANCE = 'True')
FROM LIBRARY_MARTS.HOUSING.HOUSING__FED_FEMA_IA_HOUSING_REGISTRATIONS WHERE FLOOD_DAMAGE = 'True' GROUP BY 2
ORDER BY 1, 3 DESC;

-- S13 FEMA household aid: every flood-damaged registration FEMA coded "Sanctioned Community in SFHA" (246 rows), row level
SELECT DISASTER_NUMBER, INCIDENT_TYPE_CODE, DECLARATION_DATE, DAMAGED_STATE_ABBREVIATION st, UPPER(TRIM(DAMAGED_CITY)) city, UPPER(TRIM(COUNTY)) county,
       DAMAGED_ZIP_CODE zip, LEFT(CENSUS_GEOID, 11) tract, OWN_RENT, FLOOD_INSURANCE, HA_STATUS, IHP_AMOUNT, HA_AMOUNT, REPAIR_AMOUNT,
       RENTAL_ASSISTANCE_AMOUNT, ONA_AMOUNT, RPFVL, FLOOD_DAMAGE_AMOUNT, WATER_LEVEL, HIGH_WATER_LOCATION
FROM LIBRARY_MARTS.HOUSING.HOUSING__FED_FEMA_IA_HOUSING_REGISTRATIONS
WHERE FLOOD_DAMAGE = 'True' AND HA_STATUS ILIKE '%Sanctioned Community%'
ORDER BY DECLARATION_DATE, st, city;

-- S14 FEMA household aid, flood-damaged, by disaster: is the housing-decision code filled, and how often is the sanction code used
SELECT DISASTER_NUMBER, MIN(DECLARATION_DATE) decl, ANY_VALUE(DAMAGED_STATE_ABBREVIATION) st, COUNT(*) n,
       COUNT_IF(HA_STATUS IS NULL OR TRIM(HA_STATUS) = '') ha_blank, COUNT_IF(HA_STATUS ILIKE '%Sanctioned Community%') isc,
       COUNT_IF(REPAIR_AMOUNT > 0) repair_n
FROM LIBRARY_MARTS.HOUSING.HOUSING__FED_FEMA_IA_HOUSING_REGISTRATIONS
WHERE FLOOD_DAMAGE = 'True'
GROUP BY 1 ORDER BY 2;

-- S15 eyeball: 12 flood-damaged owner registrations with repair money in two not-in-program towns (Belleville MI, Eutawville SC)
SELECT * FROM (
  SELECT DISASTER_NUMBER, DECLARATION_DATE, DAMAGED_STATE_ABBREVIATION st, DAMAGED_CITY, COUNTY, DAMAGED_ZIP_CODE, LEFT(CENSUS_GEOID, 11) tract,
         OWN_RENT, FLOOD_INSURANCE, HA_STATUS, REPAIR_AMOUNT, RPFVL, WATER_LEVEL, HIGH_WATER_LOCATION
  FROM LIBRARY_MARTS.HOUSING.HOUSING__FED_FEMA_IA_HOUSING_REGISTRATIONS
  WHERE FLOOD_DAMAGE = 'True' AND OWN_RENT = 'O' AND REPAIR_AMOUNT > 0
    AND ((DAMAGED_STATE_ABBREVIATION = 'MI' AND UPPER(TRIM(DAMAGED_CITY)) = 'BELLEVILLE') OR (DAMAGED_STATE_ABBREVIATION = 'SC' AND UPPER(TRIM(DAMAGED_CITY)) = 'EUTAWVILLE'))
  ORDER BY RANDOM() LIMIT 12)
ORDER BY st, DECLARATION_DATE;

-- S16 crosswalk follow-up: HMDA historic's lender-ID columns, and any landing copies of the ARID crosswalk with their row counts
SELECT 'HIST_COL' k, COLUMN_NAME v, DATA_TYPE x, NULL::NUMBER n
FROM LIBRARY_MARTS.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'HOUSING__FED_CFPB_HMDA_HISTORIC' AND (COLUMN_NAME ILIKE '%RESP%' OR COLUMN_NAME ILIKE '%AGENCY%' OR COLUMN_NAME ILIKE '%YEAR%' OR COLUMN_NAME ILIKE '%LEI%' OR COLUMN_NAME ILIKE '%ARID%')
UNION ALL
SELECT 'LANDING', TABLE_SCHEMA || '.' || TABLE_NAME, TABLE_TYPE, ROW_COUNT
FROM LIBRARY_RAW.INFORMATION_SCHEMA.TABLES
WHERE TABLE_NAME ILIKE '%ARID%' OR TABLE_NAME ILIKE '%LEI_XREF%'
ORDER BY 1, 2;

-- S17 crosswalk land rate: 2017 HMDA lenders (aggregated first) matched to ARID_2017 as agency code + respondent id with leading zeros stripped
WITH h AS (
  SELECT AGENCY_CODE, RESPONDENT_ID, COUNT(*) apps
  FROM LIBRARY_MARTS.HOUSING.HOUSING__FED_CFPB_HMDA_HISTORIC
  WHERE AS_OF_YEAR = '2017'
  GROUP BY 1, 2),
k AS (SELECT h.*, TRIM(AGENCY_CODE) || LTRIM(TRIM(RESPONDENT_ID), '0') arid,
             TRIM(AGENCY_CODE) || LTRIM(REGEXP_REPLACE(RESPONDENT_ID, '[^0-9A-Za-z]', ''), '0') arid_clean FROM h),
x AS (SELECT ARID_2017, LEI_2020 FROM LIBRARY_MARTS.HOUSING.HOUSING__FED_CFPB_HMDA_ARID2017_LEI_XREF)
SELECT COUNT(*) lenders_2017, SUM(apps) apps_2017,
       COUNT_IF(x1.ARID_2017 IS NOT NULL) lenders_land, SUM(IFF(x1.ARID_2017 IS NOT NULL, apps, 0)) apps_land,
       COUNT_IF(x1.ARID_2017 IS NULL AND x2.ARID_2017 IS NOT NULL) extra_land_after_clean,
       (SELECT COUNT(*) FROM x WHERE ARID_2017 NOT IN (SELECT arid FROM k)) xref_not_in_2017,
       ARRAY_AGG(IFF(x1.ARID_2017 IS NULL AND x2.ARID_2017 IS NULL AND apps > 20000, arid || ':' || apps, NULL)) big_misses
FROM k LEFT JOIN x x1 ON x1.ARID_2017 = k.arid LEFT JOIN x x2 ON x2.ARID_2017 = k.arid_clean;
