-- deep3/g77: deep pass 3, 2026-09-24. Python door (connect/db.py), read-only SELECT/WITH only, QUERY_TAG 'deep3-2026-09-24'.
-- Every connection first ran: ALTER SESSION SET STATEMENT_TIMEOUT_IN_SECONDS = 300; ALTER SESSION SET QUERY_TAG = 'deep3-2026-09-24'. Those two are not counted.
-- Tables: SCIENCE__FED_USGS_EARTHQUAKES, SCIENCE__FED_NASA_OPEN_DATA, SCIENCE__INTL_EMBL_ENSEMBL, SCIENCE__XC_OWID_AI_INCIDENTS_ANNUAL, TRANSPORT__FED_NTSB_AVIATION_INJURY.
-- 19 statements (S01-S19), all below, in run order. S10, S12, S14, S15 are extracts; the peer, time and cluster math ran locally in pandas (g77/eq*.py, g77/ntsb*.py).
-- S13 returned 0 rows: FracFocus job dates are empty in the mart (known, see g38). It still counts.
-- Outputs: g77/out_Sxx.txt and g77/out_Sxx.csv.

-- S01 NASA open data: read every row except the raw JSON
SELECT API_NAME, MEDIA_TYPE, RESPONSE_DATE, LEFT(TITLE,60) title, LEFT(DESCRIPTION,140) descr, LEFT(REQUEST_URL,90) req
FROM LIBRARY_MARTS.SCIENCE.SCIENCE__FED_NASA_OPEN_DATA ORDER BY API_NAME, RESPONSE_DATE;

-- S02 Ensembl: what the 643 rows are - feature type, chromosome, region, gene name stems
SELECT FEATURE_TYPE, SEQ_REGION_NAME, REGION, COUNT(*) n, COUNT(DISTINCT ID) ids,
       LISTAGG(DISTINCT SPLIT_PART(SYMBOL,'-',1), ',') genes, LISTAGG(DISTINCT BIOTYPE, ',') biotypes,
       COUNT_IF(TAXON_ID IS NOT NULL AND TAXON_ID::STRING NOT IN ('','None')) taxon_filled
FROM LIBRARY_MARTS.SCIENCE.SCIENCE__INTL_EMBL_ENSEMBL GROUP BY 1,2,3 ORDER BY n DESC;

-- S03 OWID AI incidents: all 14 rows
SELECT * FROM LIBRARY_MARTS.SCIENCE.SCIENCE__XC_OWID_AI_INCIDENTS_ANNUAL ORDER BY YEAR;

-- S04 Earthquakes: month by month - rows, distinct IDs, magnitude bands, type, review status, fixed 10 km depth
SELECT DATE_TRUNC('month', TIME)::DATE mo, COUNT(*) n, COUNT(DISTINCT ID) ids,
       COUNT_IF(MAG >= 3) m3, COUNT_IF(MAG >= 4.5) m45, COUNT_IF(MAG >= 6) m6,
       COUNT_IF(TYPE = 'earthquake') eq, COUNT_IF(STATUS = 'reviewed') reviewed, COUNT_IF(DEPTH = 10) d10,
       MIN(TIME) t0, MAX(TIME) t1, MAX(UPDATED) upd_max
FROM LIBRARY_MARTS.SCIENCE.SCIENCE__FED_USGS_EARTHQUAKES GROUP BY 1 ORDER BY 1;

-- S05 Earthquakes: value profile - type, status, network, magtype, the most common depths, lat/lon that do not parse
SELECT 'type' dim, TYPE val, COUNT(*) n FROM LIBRARY_MARTS.SCIENCE.SCIENCE__FED_USGS_EARTHQUAKES GROUP BY 2
UNION ALL SELECT 'status', STATUS, COUNT(*) FROM LIBRARY_MARTS.SCIENCE.SCIENCE__FED_USGS_EARTHQUAKES GROUP BY 2
UNION ALL SELECT 'net', NET, COUNT(*) FROM LIBRARY_MARTS.SCIENCE.SCIENCE__FED_USGS_EARTHQUAKES GROUP BY 2
UNION ALL SELECT 'magtype', MAGTYPE, COUNT(*) FROM LIBRARY_MARTS.SCIENCE.SCIENCE__FED_USGS_EARTHQUAKES GROUP BY 2
UNION ALL SELECT * FROM (SELECT 'depth', TO_VARCHAR(DEPTH), COUNT(*) n FROM LIBRARY_MARTS.SCIENCE.SCIENCE__FED_USGS_EARTHQUAKES GROUP BY 2 ORDER BY n DESC LIMIT 12)
UNION ALL SELECT 'latlon_bad', 'lat or lon not a number', COUNT_IF(TRY_TO_DOUBLE(LATITUDE) IS NULL OR TRY_TO_DOUBLE(LONGITUDE) IS NULL) FROM LIBRARY_MARTS.SCIENCE.SCIENCE__FED_USGS_EARTHQUAKES
UNION ALL SELECT 'dup_id', 'rows minus distinct ID', COUNT(*) - COUNT(DISTINCT ID) FROM LIBRARY_MARTS.SCIENCE.SCIENCE__FED_USGS_EARTHQUAKES
UNION ALL SELECT 'mag_lt_2_5', 'MAG under 2.5', COUNT_IF(MAG < 2.5) FROM LIBRARY_MARTS.SCIENCE.SCIENCE__FED_USGS_EARTHQUAKES
ORDER BY 1, 3 DESC;

-- S06 Earthquakes: lower-48 box, by place suffix (state), oil-field zone, year - counts by magnitude band and who located them
WITH q AS (
  SELECT TRIM(REGEXP_SUBSTR(PLACE, '[^,]+$')) region, YEAR(TIME) yr, MAG, NET, STATUS,
         TRY_TO_DOUBLE(LATITUDE) lat, TRY_TO_DOUBLE(LONGITUDE) lon
  FROM LIBRARY_MARTS.SCIENCE.SCIENCE__FED_USGS_EARTHQUAKES
  WHERE TYPE = 'earthquake' AND TRY_TO_DOUBLE(LATITUDE) BETWEEN 24 AND 50 AND TRY_TO_DOUBLE(LONGITUDE) BETWEEN -125 AND -66)
SELECT region,
       CASE WHEN lat BETWEEN 30.5 AND 33.8 AND lon BETWEEN -105.0 AND -100.5 THEN 'PERMIAN'
            WHEN lat BETWEEN 33.6 AND 37.0 AND lon BETWEEN -99.5 AND -96.0 THEN 'OK_CENTRAL'
            WHEN lat BETWEEN 36.9 AND 37.6 AND lon BETWEEN -98.8 AND -97.0 THEN 'KS_SOUTH'
            WHEN lat BETWEEN 28.0 AND 29.5 AND lon BETWEEN -99.5 AND -97.0 THEN 'EAGLE_FORD'
            WHEN lat BETWEEN 36.9 AND 37.6 AND lon BETWEEN -105.3 AND -104.3 THEN 'RATON'
            ELSE 'OTHER' END zone,
       yr, COUNT(*) n, COUNT_IF(MAG >= 3) m3, COUNT_IF(MAG >= 3.5) m35, COUNT_IF(MAG >= 4) m4, MAX(MAG) max_mag,
       COUNT_IF(NET = 'tx') net_tx, COUNT_IF(NET = 'us') net_us, COUNT_IF(NET = 'ok') net_ok, COUNT_IF(STATUS = 'reviewed') reviewed
FROM q GROUP BY 1,2,3 ORDER BY 1,2,3;

-- S07 NTSB injury: category x injury level - rows, blanks, zeros, sums, events
SELECT INJ_PERSON_CATEGORY, INJURY_LEVEL, COUNT(*) n, COUNT_IF(INJ_PERSON_COUNT IS NULL) blank, COUNT_IF(INJ_PERSON_COUNT = 0) zero,
       SUM(INJ_PERSON_COUNT) people, MAX(INJ_PERSON_COUNT) mx, COUNT(DISTINCT EV_ID) evs
FROM LIBRARY_MARTS.TRANSPORT.TRANSPORT__FED_NTSB_AVIATION_INJURY GROUP BY 1,2 ORDER BY 1,2;

-- S08 NTSB injury: keys, duplicate loads, load runs, change dates, and how many events land in the events and aircraft tables
WITH i AS (SELECT * FROM LIBRARY_MARTS.TRANSPORT.TRANSPORT__FED_NTSB_AVIATION_INJURY),
ie AS (SELECT DISTINCT EV_ID FROM i),
ia AS (SELECT DISTINCT EV_ID, AIRCRAFT_KEY FROM i),
e AS (SELECT DISTINCT EV_ID FROM LIBRARY_MARTS.TRANSPORT.TRANSPORT__FED_NTSB_AVIATION_EVENTS),
a AS (SELECT DISTINCT EV_ID, AIRCRAFT_KEY FROM LIBRARY_MARTS.TRANSPORT.TRANSPORT__FED_NTSB_AVIATION_AIRCRAFT),
m AS (SELECT LCHG_DATE d, COUNT(*) k FROM i GROUP BY 1 ORDER BY k DESC LIMIT 1)
SELECT (SELECT COUNT(*) FROM i) n, (SELECT COUNT(DISTINCT INJURY_RECORD_ID) FROM i) rec_ids,
       (SELECT COUNT(DISTINCT EV_ID, AIRCRAFT_KEY, INJ_PERSON_CATEGORY, INJURY_LEVEL) FROM i) nat_keys,
       (SELECT COUNT(DISTINCT _SOURCE_RUN_ID) FROM i) runs, (SELECT COUNT(DISTINCT _INGESTED_AT) FROM i) ingest_stamps,
       (SELECT COUNT(*) FROM ie) inj_events, (SELECT COUNT(*) FROM e) ev_events,
       (SELECT COUNT(*) FROM ie JOIN e USING (EV_ID)) inj_ev_in_events,
       (SELECT COUNT(*) FROM e WHERE EV_ID NOT IN (SELECT EV_ID FROM ie)) events_without_inj,
       (SELECT COUNT(*) FROM ia) inj_aircraft, (SELECT COUNT(*) FROM ia JOIN a USING (EV_ID, AIRCRAFT_KEY)) inj_ac_in_aircraft,
       (SELECT MIN(LEFT(EV_ID,4)) FROM i) evid_y0, (SELECT MAX(LEFT(EV_ID,4)) FROM i) evid_y1,
       (SELECT MIN(LCHG_DATE) FROM i) lchg0, (SELECT MAX(LCHG_DATE) FROM i) lchg1,
       (SELECT MAX(d) FROM m) lchg_mode, (SELECT MAX(k) FROM m) lchg_mode_n,
       (SELECT COUNT_IF(LCHG_USERID = 'None' OR LCHG_USERID IS NULL) FROM i) userid_none;

-- S09 NTSB injury: does TOTL equal the sum of the other levels, and do the per-person deaths match the events table's death count
WITH p AS (
  SELECT EV_ID, AIRCRAFT_KEY, INJ_PERSON_CATEGORY c,
         SUM(IFF(INJURY_LEVEL <> 'TOTL', COALESCE(INJ_PERSON_COUNT,0), 0)) parts,
         MAX(IFF(INJURY_LEVEL = 'TOTL', INJ_PERSON_COUNT, NULL)) totl, COUNT_IF(INJURY_LEVEL = 'TOTL') has_totl,
         SUM(IFF(INJURY_LEVEL = 'FATL', COALESCE(INJ_PERSON_COUNT,0), 0)) f
  FROM LIBRARY_MARTS.TRANSPORT.TRANSPORT__FED_NTSB_AVIATION_INJURY GROUP BY 1,2,3),
ev AS (SELECT EV_ID, SUM(f) f FROM p GROUP BY 1),
e AS (SELECT EV_ID, TRY_TO_NUMBER(TO_VARCHAR(INJ_TOT_F)) ef, TRY_TO_NUMBER(TO_VARCHAR(INJ_F_GRND)) gf, EV_HIGHEST_INJURY h
      FROM LIBRARY_MARTS.TRANSPORT.TRANSPORT__FED_NTSB_AVIATION_EVENTS)
SELECT 'groups' k, COUNT(*) n, COUNT_IF(has_totl > 0) a, COUNT_IF(totl = parts) b, COUNT_IF(totl <> parts) c, COUNT_IF(has_totl > 0 AND totl IS NULL) d
FROM p
UNION ALL
SELECT 'events', COUNT(*), COUNT_IF(COALESCE(ev.f,0) = COALESCE(e.ef,0)), COUNT_IF(COALESCE(ev.f,0) <> COALESCE(e.ef,0)),
       COUNT_IF(COALESCE(ev.f,0) + COALESCE(e.gf,0) = COALESCE(e.ef,0) AND COALESCE(ev.f,0) <> COALESCE(e.ef,0)), SUM(ev.f) - SUM(e.ef)
FROM ev JOIN e USING (EV_ID);

-- S10 Earthquakes: every event in the Permian box plus central Oklahoma and south Kansas boxes - event-level extract for local math
SELECT ID, TIME, TRY_TO_DOUBLE(LATITUDE) lat, TRY_TO_DOUBLE(LONGITUDE) lon, DEPTH, MAG, MAGTYPE, NET, STATUS, TYPE, PLACE, UPDATED,
       CASE WHEN TRY_TO_DOUBLE(LATITUDE) BETWEEN 30.5 AND 33.8 AND TRY_TO_DOUBLE(LONGITUDE) BETWEEN -105.0 AND -100.5 THEN 'PERMIAN'
            WHEN TRY_TO_DOUBLE(LATITUDE) BETWEEN 33.6 AND 37.0 AND TRY_TO_DOUBLE(LONGITUDE) BETWEEN -99.5 AND -96.0 THEN 'OK_CENTRAL'
            ELSE 'KS_SOUTH' END zone
FROM LIBRARY_MARTS.SCIENCE.SCIENCE__FED_USGS_EARTHQUAKES
WHERE (TRY_TO_DOUBLE(LATITUDE) BETWEEN 30.5 AND 33.8 AND TRY_TO_DOUBLE(LONGITUDE) BETWEEN -105.0 AND -100.5)
   OR (TRY_TO_DOUBLE(LATITUDE) BETWEEN 33.6 AND 37.0 AND TRY_TO_DOUBLE(LONGITUDE) BETWEEN -99.5 AND -96.0)
   OR (TRY_TO_DOUBLE(LATITUDE) BETWEEN 36.9 AND 37.6 AND TRY_TO_DOUBLE(LONGITUDE) BETWEEN -98.8 AND -97.0)
ORDER BY TIME;

-- S11 NTSB injury: people by kind of flight, aircraft category, year, US or not, person category and injury level (TOTL left out)
WITH ac AS (
  SELECT EV_ID, AIRCRAFT_KEY, ACFT_CATEGORY, FAR_PART, TYPE_FLY,
    CASE WHEN FAR_PART='121' THEN '121 airline'
      WHEN FAR_PART='135' AND AIR_MEDICAL='Y' THEN '135 air medical' WHEN FAR_PART='135' AND SITE_SEEING='Y' THEN '135 air tour'
      WHEN FAR_PART='135' THEN '135 charter/cargo other' WHEN FAR_PART LIKE '091%' AND AIR_MEDICAL='Y' THEN '91 air medical'
      WHEN FAR_PART LIKE '091%' AND SITE_SEEING='Y' THEN '91 air tour (LOA)' WHEN FAR_PART='091K' THEN '91K fractional'
      WHEN FAR_PART='091' AND TYPE_FLY='SKYD' THEN '91 skydiving' WHEN FAR_PART='091' AND TYPE_FLY='INST' THEN '91 instruction'
      WHEN FAR_PART='091' AND HOMEBUILT='Y' THEN '91 homebuilt' WHEN FAR_PART='091' THEN '91 other private' WHEN FAR_PART='137' THEN '137 crop dusting'
      WHEN FAR_PART='133' THEN '133 external load' WHEN FAR_PART='PUBU' THEN 'public use' WHEN FAR_PART='107' THEN '107 drone'
      WHEN FAR_PART='129' THEN '129 foreign airline' ELSE 'other/unknown '||COALESCE(FAR_PART,'null') END grp
  FROM LIBRARY_MARTS.TRANSPORT.TRANSPORT__FED_NTSB_AVIATION_AIRCRAFT),
e AS (SELECT EV_ID, EV_TYPE, YEAR(EV_DATE) yr, IFF(EV_COUNTRY='USA','US','nonUS') ctry FROM LIBRARY_MARTS.TRANSPORT.TRANSPORT__FED_NTSB_AVIATION_EVENTS)
SELECT e.ctry, ac.grp, ac.ACFT_CATEGORY cat, e.yr, i.INJ_PERSON_CATEGORY who, i.INJURY_LEVEL lvl,
       SUM(COALESCE(i.INJ_PERSON_COUNT,0)) people, COUNT(DISTINCT i.EV_ID, i.AIRCRAFT_KEY) aircraft,
       COUNT(DISTINCT IFF(i.INJ_PERSON_COUNT > 0, i.EV_ID||'-'||i.AIRCRAFT_KEY, NULL)) aircraft_with_any
FROM LIBRARY_MARTS.TRANSPORT.TRANSPORT__FED_NTSB_AVIATION_INJURY i
JOIN e ON e.EV_ID = i.EV_ID
LEFT JOIN ac ON ac.EV_ID = i.EV_ID AND ac.AIRCRAFT_KEY = i.AIRCRAFT_KEY
WHERE i.INJURY_LEVEL <> 'TOTL'
GROUP BY 1,2,3,4,5,6 ORDER BY 1,2,3,4,5,6;

-- S12 NTSB injury: per-aircraft injury pivot for US Part 121 flights, every balloon, and every aircraft with a lap child - extract for local math
WITH i AS (
  SELECT EV_ID, AIRCRAFT_KEY,
    SUM(IFF(INJ_PERSON_CATEGORY='Cabi' AND INJURY_LEVEL='FATL', INJ_PERSON_COUNT, 0)) cabi_f, SUM(IFF(INJ_PERSON_CATEGORY='Cabi' AND INJURY_LEVEL='SERS', INJ_PERSON_COUNT, 0)) cabi_s,
    SUM(IFF(INJ_PERSON_CATEGORY='Cabi' AND INJURY_LEVEL='MINR', INJ_PERSON_COUNT, 0)) cabi_m, SUM(IFF(INJ_PERSON_CATEGORY='Cabi' AND INJURY_LEVEL='NONE', INJ_PERSON_COUNT, 0)) cabi_n,
    SUM(IFF(INJ_PERSON_CATEGORY='Flig' AND INJURY_LEVEL='FATL', INJ_PERSON_COUNT, 0)) flig_f, SUM(IFF(INJ_PERSON_CATEGORY='Flig' AND INJURY_LEVEL='SERS', INJ_PERSON_COUNT, 0)) flig_s,
    SUM(IFF(INJ_PERSON_CATEGORY='Flig' AND INJURY_LEVEL='MINR', INJ_PERSON_COUNT, 0)) flig_m, SUM(IFF(INJ_PERSON_CATEGORY='Flig' AND INJURY_LEVEL='NONE', INJ_PERSON_COUNT, 0)) flig_n,
    SUM(IFF(INJ_PERSON_CATEGORY='Pass' AND INJURY_LEVEL='FATL', INJ_PERSON_COUNT, 0)) pass_f, SUM(IFF(INJ_PERSON_CATEGORY='Pass' AND INJURY_LEVEL='SERS', INJ_PERSON_COUNT, 0)) pass_s,
    SUM(IFF(INJ_PERSON_CATEGORY='Pass' AND INJURY_LEVEL='MINR', INJ_PERSON_COUNT, 0)) pass_m, SUM(IFF(INJ_PERSON_CATEGORY='Pass' AND INJURY_LEVEL='NONE', INJ_PERSON_COUNT, 0)) pass_n,
    SUM(IFF(INJ_PERSON_CATEGORY='LapC' AND INJURY_LEVEL='FATL', INJ_PERSON_COUNT, 0)) lapc_f, SUM(IFF(INJ_PERSON_CATEGORY='LapC' AND INJURY_LEVEL='SERS', INJ_PERSON_COUNT, 0)) lapc_s,
    SUM(IFF(INJ_PERSON_CATEGORY='LapC' AND INJURY_LEVEL='MINR', INJ_PERSON_COUNT, 0)) lapc_m, SUM(IFF(INJ_PERSON_CATEGORY='LapC' AND INJURY_LEVEL='NONE', INJ_PERSON_COUNT, 0)) lapc_n,
    MAX(LCHG_DATE) lchg
  FROM LIBRARY_MARTS.TRANSPORT.TRANSPORT__FED_NTSB_AVIATION_INJURY WHERE INJURY_LEVEL <> 'TOTL' GROUP BY 1,2)
SELECT e.EV_ID, e.NTSB_NO, e.EV_TYPE, e.EV_DATE, e.EV_CITY, e.EV_STATE, e.EV_COUNTRY, e.EV_HIGHEST_INJURY,
       ac.AIRCRAFT_KEY, ac.FAR_PART, ac.ACFT_CATEGORY, ac.ACFT_MAKE, ac.ACFT_MODEL, ac.REGIS_NO, ac.DAMAGE, ac.PHASE_FLT_SPEC,
       ac.OPER_NAME, ac.OWNER_ACFT, ac.OPER_SCHED, ac.OPER_PAX_CARGO, ac.SITE_SEEING, ac.TYPE_FLY, i.*
FROM i
JOIN LIBRARY_MARTS.TRANSPORT.TRANSPORT__FED_NTSB_AVIATION_EVENTS e ON e.EV_ID = i.EV_ID
JOIN LIBRARY_MARTS.TRANSPORT.TRANSPORT__FED_NTSB_AVIATION_AIRCRAFT ac ON ac.EV_ID = i.EV_ID AND ac.AIRCRAFT_KEY = i.AIRCRAFT_KEY
WHERE (ac.FAR_PART = '121' AND e.EV_COUNTRY = 'USA') OR ac.ACFT_CATEGORY = 'BALL'
   OR (i.lapc_f + i.lapc_s + i.lapc_m + i.lapc_n) > 0 OR ac.FAR_PART = '129'
ORDER BY e.EV_DATE;

-- S13 FracFocus: frac jobs by year in the New Mexico and Texas parts of the Delaware Basin, next to the quake clusters (a box count, not a key join)
SELECT YEAR(JOB_START_DATE) yr,
       CASE WHEN LATITUDE BETWEEN 32.1 AND 32.8 AND LONGITUDE BETWEEN -104.8 AND -104.2 THEN 'NM west of 104.2W (Hope-Atoka-Whites City)'
            WHEN LATITUDE BETWEEN 32.0 AND 32.8 AND LONGITUDE BETWEEN -104.2 AND -103.064 THEN 'NM east (Carlsbad-Malaga-Jal)'
            WHEN LATITUDE BETWEEN 30.8 AND 32.0 AND LONGITUDE BETWEEN -104.8 AND -103.0 THEN 'TX Delaware (Culberson-Reeves-Loving-Pecos)'
            ELSE 'other' END area,
       COUNT(DISTINCT DISCLOSURE_ID) jobs, COUNT(DISTINCT API_NUMBER) wells, ROUND(SUM(TOTAL_BASE_WATER_VOLUME)/1e6,1) water_mgal,
       MAX(JOB_START_DATE) last_job
FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_FRACFOCUS_DISCLOSURE_LIST
WHERE LATITUDE BETWEEN 30.8 AND 32.8 AND LONGITUDE BETWEEN -104.8 AND -103.0 AND YEAR(JOB_START_DATE) >= 2010
GROUP BY 1,2 ORDER BY 2,1;

-- S14 Earthquakes: lower-48 M3+ by half-degree cell and year, full year and the Jan 1 - Jun 13 window the 2026 data covers - peer set for the New Mexico cluster
SELECT FLOOR(TRY_TO_DOUBLE(LATITUDE)*2)/2 lat0, FLOOR(TRY_TO_DOUBLE(LONGITUDE)*2)/2 lon0, YEAR(TIME) yr,
       COUNT(*) m3, COUNT_IF(TO_CHAR(TIME,'MMDD') <= '0613') m3_win, COUNT_IF(MAG >= 4) m4, MAX(MAG) max_mag,
       COUNT(DISTINCT TO_DATE(TIME)) days, ANY_VALUE(PLACE) place_eg
FROM LIBRARY_MARTS.SCIENCE.SCIENCE__FED_USGS_EARTHQUAKES
WHERE TYPE = 'earthquake' AND MAG >= 3
  AND TRY_TO_DOUBLE(LATITUDE) BETWEEN 24 AND 50 AND TRY_TO_DOUBLE(LONGITUDE) BETWEEN -125 AND -66
GROUP BY 1,2,3 ORDER BY 1,2,3;

-- S15 Earthquakes: every event of any type in northwest Louisiana and east Texas (lat 30.5-33.5, lon -95.5 to -91.5), whole catalog
SELECT ID, TIME, TRY_TO_DOUBLE(LATITUDE) lat, TRY_TO_DOUBLE(LONGITUDE) lon, DEPTH, MAG, MAGTYPE, NET, STATUS, TYPE, PLACE, UPDATED,
       NST, GAP, RMS, HORIZONTALERROR, DEPTHERROR, LOCATIONSOURCE, MAGSOURCE
FROM LIBRARY_MARTS.SCIENCE.SCIENCE__FED_USGS_EARTHQUAKES
WHERE TRY_TO_DOUBLE(LATITUDE) BETWEEN 30.5 AND 33.5 AND TRY_TO_DOUBLE(LONGITUDE) BETWEEN -95.5 AND -91.5
ORDER BY TIME;

-- S16 FracFocus: frack disclosures inside the two new quake boxes (Red River Parish LA; west of Carlsbad NM), by form version and operator - context only, the mart has no job dates
SELECT CASE WHEN LATITUDE BETWEEN 31.8 AND 32.5 AND LONGITUDE BETWEEN -93.55 AND -93.25 THEN 'LA Red River box'
            WHEN LATITUDE BETWEEN 32.1 AND 32.8 AND LONGITUDE BETWEEN -104.8 AND -104.2 THEN 'NM west of Carlsbad box' END box,
       FF_VERSION, OPERATOR_NAME, COUNT(DISTINCT DISCLOSURE_ID) jobs, COUNT(DISTINCT API_NUMBER) wells,
       ROUND(SUM(TOTAL_BASE_WATER_VOLUME)/1e6,1) water_mgal, COUNT_IF(JOB_START_DATE IS NOT NULL) dated,
       LISTAGG(DISTINCT COUNTY_NAME, ',') counties
FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_FRACFOCUS_DISCLOSURE_LIST
WHERE (LATITUDE BETWEEN 31.8 AND 32.5 AND LONGITUDE BETWEEN -93.55 AND -93.25)
   OR (LATITUDE BETWEEN 32.1 AND 32.8 AND LONGITUDE BETWEEN -104.8 AND -104.2)
GROUP BY 1,2,3 ORDER BY 1,2, jobs DESC;

-- S17 Earthquakes: near-duplicate check - next event within 20 seconds and about 20 km of the previous one, by the two networks involved
WITH q AS (
  SELECT ID, TIME, NET, MAG, TRY_TO_DOUBLE(LATITUDE) lat, TRY_TO_DOUBLE(LONGITUDE) lon,
         LAG(TIME) OVER (ORDER BY TIME) pt, LAG(NET) OVER (ORDER BY TIME) pnet, LAG(MAG) OVER (ORDER BY TIME) pmag,
         LAG(TRY_TO_DOUBLE(LATITUDE)) OVER (ORDER BY TIME) plat, LAG(TRY_TO_DOUBLE(LONGITUDE)) OVER (ORDER BY TIME) plon
  FROM LIBRARY_MARTS.SCIENCE.SCIENCE__FED_USGS_EARTHQUAKES WHERE TYPE = 'earthquake')
SELECT LEAST(NET, pnet) || '+' || GREATEST(NET, pnet) nets, COUNT(*) pairs,
       COUNT_IF(DATEDIFF('millisecond', pt, TIME) <= 5000) within_5s, ROUND(AVG(ABS(MAG - pmag)),2) avg_mag_gap,
       ANY_VALUE(ID) eg_id
FROM q
WHERE DATEDIFF('millisecond', pt, TIME) <= 20000 AND ABS(lat - plat) <= 0.2 AND ABS(lon - plon) <= 0.2
GROUP BY 1 ORDER BY pairs DESC;

-- S18 Earthquakes: where the June-July 2018 spike sits - place suffix counts for those two months against the same months of 2017 and 2019
SELECT TRIM(REGEXP_SUBSTR(PLACE, '[^,]+$')) region, COUNT_IF(YEAR(TIME) = 2018) y2018, COUNT_IF(YEAR(TIME) = 2017) y2017, COUNT_IF(YEAR(TIME) = 2019) y2019,
       MAX(IFF(YEAR(TIME) = 2018, MAG, NULL)) max2018
FROM LIBRARY_MARTS.SCIENCE.SCIENCE__FED_USGS_EARTHQUAKES
WHERE MONTH(TIME) IN (6,7) AND YEAR(TIME) BETWEEN 2017 AND 2019
GROUP BY 1 ORDER BY y2018 DESC LIMIT 12;

-- S19 NASA open data: is the API key in REQUEST_URL NASA's public DEMO_KEY (count only, key not printed); hazardous asteroid count
SELECT API_NAME, COUNT(*) n, COUNT_IF(REQUEST_URL ILIKE '%api_key=DEMO_KEY%') demo_key, COUNT_IF(REQUEST_URL ILIKE '%api_key=%') any_key,
       COUNT_IF(DESCRIPTION ILIKE 'Hazardous: True%') hazardous, COUNT(DISTINCT REQUEST_URL) urls
FROM LIBRARY_MARTS.SCIENCE.SCIENCE__FED_NASA_OPEN_DATA GROUP BY 1;
