-- deep3/g79: deep pass 3, 2026-09-24. Python door (connect/db.py), read-only SELECT/WITH only, QUERY_TAG 'deep3-2026-09-24'.
-- Every connection first ran: ALTER SESSION SET STATEMENT_TIMEOUT_IN_SECONDS = 300; ALTER SESSION SET QUERY_TAG = 'deep3-2026-09-24'. Those two are not counted.
-- Tables: HISTORY__FED_WPA_SLAVE_NARRATIVES, HISTORY__FED_DENSHO_DDR, HISTORY__FED_DOCSOUTH,
--         GOVERNMENT_RECORDS__FED_NARA_AAD, GOVERNMENT_RECORDS__FED_USASPENDING_TAS_FILTER_TREE.
-- 8 statements (S01-S08), all below, in run order. All five tables are under 600 rows, so S01-S05 pull them whole
-- and every profile, duplicate, ordering and join check ran locally in pandas on the CSVs (g79/out_Sxx.csv).
-- Runner: g79/run.py (refuses anything that is not SELECT/WITH).

-- S01 WPA slave narratives: pull all 100 rows (tiny table, profile locally)
SELECT * FROM LIBRARY_MARTS.HISTORY.HISTORY__FED_WPA_SLAVE_NARRATIVES;

-- S02 Densho DDR: pull all 25 rows
SELECT * FROM LIBRARY_MARTS.HISTORY.HISTORY__FED_DENSHO_DDR;

-- S03 DocSouth: pull all 144 rows
SELECT * FROM LIBRARY_MARTS.HISTORY.HISTORY__FED_DOCSOUTH;

-- S04 NARA AAD: pull all 554 rows
SELECT * FROM LIBRARY_MARTS.GOVERNMENT_RECORDS.GOVERNMENT_RECORDS__FED_NARA_AAD;

-- S05 USAspending TAS filter tree: pull all 92 rows
SELECT * FROM LIBRARY_MARTS.GOVERNMENT_RECORDS.GOVERNMENT_RECORDS__FED_USASPENDING_TAS_FILTER_TREE;

-- S06 Sibling tables: is there a fuller copy of any of the five, in landing or marts? (row counts from the catalog)
SELECT 'RAW' db, TABLE_SCHEMA, TABLE_NAME, ROW_COUNT, LAST_ALTERED
FROM LIBRARY_RAW.INFORMATION_SCHEMA.TABLES
WHERE TABLE_NAME RLIKE '.*(WPA|SLAVE|DENSHO|DOCSOUTH|NARA|_AAD|_LOC_|LIBRARY_OF_CONGRESS|TAS_|FEDERAL_ACCOUNT|FILTER_TREE|BUDGETARY|TOPTIER).*'
UNION ALL
SELECT 'MARTS', TABLE_SCHEMA, TABLE_NAME, ROW_COUNT, LAST_ALTERED
FROM LIBRARY_MARTS.INFORMATION_SCHEMA.TABLES
WHERE TABLE_NAME RLIKE '.*(WPA|SLAVE|DENSHO|DOCSOUTH|NARA|_AAD|_LOC_|LIBRARY_OF_CONGRESS|TAS_|FEDERAL_ACCOUNT|FILTER_TREE|BUDGETARY|TOPTIER).*'
ORDER BY 1, 3;

-- S07 TAS join test: which mart columns could carry a 3- or 4-digit agency code (CGAC / FREC / toptier) to join NODE_ID
SELECT TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME, DATA_TYPE
FROM LIBRARY_MARTS.INFORMATION_SCHEMA.COLUMNS
WHERE COLUMN_NAME RLIKE '.*(TOPTIER|CGAC|FREC|AGENCY_IDENTIFIER|AGENCY_CODE|AGENCY_ID).*'
  AND TABLE_SCHEMA <> 'INFORMATION_SCHEMA'
ORDER BY 1, 2, 3;

-- S08 TAS join test: pull the 111-row toptier agency table (the only mart with a TOPTIER_CODE); join to the tree locally on NODE_ID = TOPTIER_CODE
SELECT * FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_USASPENDING_TOPTIER_AGENCIES;
