-- @S01 columns and types for the five tables plus the FEMA household-aid table (join candidate)
SELECT TABLE_SCHEMA, TABLE_NAME, LISTAGG(COLUMN_NAME || ':' || DATA_TYPE, ', ') WITHIN GROUP (ORDER BY ORDINAL_POSITION) cols
FROM LIBRARY_MARTS.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME IN ('HOUSING__FED_FEMA_NFIP_COMMUNITY_STATUS_BOOK','HOUSING__FED_FHFA_HPI','HOUSING__FED_CFPB_HMDA_ARID2017_LEI_XREF',
                     'HOUSING__FED_HUD_DATA','SCIENCE__FED_NSF_AWARDS','HOUSING__FED_FEMA_IA_HOUSING_REGISTRATIONS')
GROUP BY 1,2 ORDER BY 2;

-- @S02 HUD_DATA: confirm it is a link list (fill of every column, distinct links)
SELECT COUNT(*) n, COUNT(DISTINCT DATASET_URL) urls, COUNT(DISTINCT DATASET_NAME) names,
       COUNT_IF(NULLIF(TRIM(TO_VARCHAR(EIN)),'') IS NOT NULL) ein_filled, COUNT_IF(NULLIF(TRIM(TO_VARCHAR(FIPS)),'') IS NOT NULL) fips_filled,
       COUNT_IF(NULLIF(TRIM(TO_VARCHAR(ZIP)),'') IS NOT NULL) zip_filled, COUNT_IF(NULLIF(TRIM(TO_VARCHAR(YEAR)),'') IS NOT NULL) year_filled,
       COUNT_IF(NULLIF(TRIM(DESCRIPTION),'') IS NOT NULL) desc_filled, COUNT_IF(NULLIF(TRIM(VALUE),'') IS NOT NULL) value_filled,
       ARRAY_AGG(DISTINCT LEFT(DATASET_NAME, 60)) WITHIN GROUP (ORDER BY LEFT(DATASET_NAME, 60)) sample_names
FROM LIBRARY_MARTS.HOUSING.HOUSING__FED_HUD_DATA;

-- @S03 ARID2017-LEI crosswalk: is it one row per lender? why do ARIDs and LEIs repeat? sample the top repeaters
WITH x AS (SELECT * FROM LIBRARY_MARTS.HOUSING.HOUSING__FED_CFPB_HMDA_ARID2017_LEI_XREF),
s AS (
  SELECT COUNT(*) n, COUNT(DISTINCT ARID_2017) arids, COUNT(DISTINCT LEI_2018) lei18,
         COUNT(DISTINCT NULLIF(TRIM(LEI_2019),'')) lei19, COUNT(DISTINCT NULLIF(TRIM(LEI_2020),'')) lei20,
         COUNT_IF(NULLIF(TRIM(LEI_2019),'') IS NULL) lei19_blank, COUNT_IF(NULLIF(TRIM(LEI_2020),'') IS NULL) lei20_blank,
         COUNT_IF(LEI_2018 = LEI_2019) same_18_19, COUNT_IF(LEI_2019 = LEI_2020) same_19_20,
         COUNT(DISTINCT RESPONDENT_NAME) names
  FROM x),
top_arid AS (SELECT ARID_2017 FROM x GROUP BY 1 ORDER BY COUNT(*) DESC LIMIT 1),
top_lei AS (SELECT LEI_2019 FROM x WHERE NULLIF(TRIM(LEI_2019),'') IS NOT NULL GROUP BY 1 ORDER BY COUNT(*) DESC LIMIT 1)
SELECT 'SUMMARY' k, n::varchar a, arids::varchar b, lei18::varchar c, lei19::varchar d, lei20::varchar e,
       'blank19=' || lei19_blank || ' blank20=' || lei20_blank || ' same1819=' || same_18_19 || ' same1920=' || same_19_20 || ' names=' || names f
FROM s
UNION ALL
SELECT * FROM (SELECT 'TOP_ARID', ARID_2017, RESPONDENT_NAME, LEI_2018, LEI_2019, LEI_2020, NULL FROM x WHERE ARID_2017 IN (SELECT * FROM top_arid) LIMIT 8)
UNION ALL
SELECT * FROM (SELECT 'TOP_LEI19', ARID_2017, RESPONDENT_NAME, LEI_2018, LEI_2019, LEI_2020, NULL FROM x WHERE LEI_2019 IN (SELECT * FROM top_lei) LIMIT 8);

-- @S04 NSF awards: profile plus every award of $2M or more
WITH x AS (SELECT * FROM LIBRARY_MARTS.SCIENCE.SCIENCE__FED_NSF_AWARDS),
s AS (SELECT COUNT(*) n, COUNT(DISTINCT AWARD_ID) ids, SUM(TRY_TO_NUMBER(TO_VARCHAR(AWARD_AMOUNT))) total,
             MEDIAN(TRY_TO_NUMBER(TO_VARCHAR(AWARD_AMOUNT))) med, COUNT(DISTINCT AWARDEE_NAME) awardees, COUNT(DISTINCT PROGRAM_NAME) programs,
             COUNT_IF(NULLIF(TRIM(TO_VARCHAR(EIN)),'') IS NOT NULL) ein_filled, COUNT_IF(NULLIF(TRIM(TO_VARCHAR(STATUS)),'') IS NOT NULL) status_filled,
             MIN(AWARD_DATE) d0, MAX(AWARD_DATE) d1, COUNT(DISTINCT AWARD_DATE) days, COUNT(DISTINCT STATE) states,
             COUNT_IF(NULLIF(TRIM(ABSTRACT),'') IS NOT NULL) abstract_filled
      FROM x)
SELECT s.*, x.AWARD_ID, x.AWARDEE_NAME, x.STATE, x.PROGRAM_NAME, x.AWARD_AMOUNT, x.AWARD_DATE, x.START_DATE, x.END_DATE, LEFT(x.TITLE, 90) title
FROM s LEFT JOIN x ON TRY_TO_NUMBER(TO_VARCHAR(x.AWARD_AMOUNT)) >= 2000000
ORDER BY TRY_TO_NUMBER(TO_VARCHAR(x.AWARD_AMOUNT)) DESC NULLS LAST;
