-- @S05 NFIP community status book: flags, fill, date ranges, future dates (two-digit-year parse check), load runs
SELECT PARTICIPATING_IN_NFIP_FLAG p, TRIBAL_FLAG t, COUNT(*) n, COUNT(DISTINCT COMMUNITY_ID_NUMBER) ids,
       COUNT_IF(INITIAL_FLOOD_HAZARD_BOUNDARY_MAP_DATE IS NOT NULL) fhbm, COUNT_IF(INITIAL_FLOOD_INSURANCE_RATE_MAP_DATE IS NOT NULL) firm,
       COUNT_IF(CURRENTLY_EFFECTIVE_MAP_DATE IS NOT NULL) cem, COUNT_IF(CURRENTLY_EFFECTIVE_MAP_DATE_RAW ILIKE '%NSFHA%') nsfha,
       COUNT_IF(REGULAR_EMERGENCY_PROGRAM_DATE IS NOT NULL) reg, COUNT_IF(NULLIF(TRIM(CRS_CLASS_RATING),'') IS NOT NULL) crs,
       COUNT_IF(INITIAL_FLOOD_HAZARD_BOUNDARY_MAP_DATE > CURRENT_DATE) fhbm_fut, COUNT_IF(INITIAL_FLOOD_INSURANCE_RATE_MAP_DATE > CURRENT_DATE) firm_fut,
       COUNT_IF(CURRENTLY_EFFECTIVE_MAP_DATE > CURRENT_DATE) cem_fut, COUNT_IF(REGULAR_EMERGENCY_PROGRAM_DATE > CURRENT_DATE) reg_fut,
       COUNT_IF(ORIGINAL_ENTRY_DATE > CURRENT_DATE) orig_fut, COUNT_IF(CLASS_RATING_EFFECTIVE_DATE > CURRENT_DATE) cls_fut,
       MIN(INITIAL_FLOOD_HAZARD_BOUNDARY_MAP_DATE) fhbm0, MIN(INITIAL_FLOOD_INSURANCE_RATE_MAP_DATE) firm0, MAX(INITIAL_FLOOD_INSURANCE_RATE_MAP_DATE) firm1,
       MIN(CURRENTLY_EFFECTIVE_MAP_DATE) cem0, MAX(CURRENTLY_EFFECTIVE_MAP_DATE) cem1, MIN(REGULAR_EMERGENCY_PROGRAM_DATE) reg0, MAX(REGULAR_EMERGENCY_PROGRAM_DATE) reg1,
       COUNT_IF(INITIAL_FLOOD_INSURANCE_RATE_MAP_DATE < INITIAL_FLOOD_HAZARD_BOUNDARY_MAP_DATE) firm_before_fhbm,
       COUNT_IF(CURRENTLY_EFFECTIVE_MAP_DATE < INITIAL_FLOOD_INSURANCE_RATE_MAP_DATE) cem_before_firm,
       COUNT(DISTINCT _SOURCE_RUN_ID) runs, MAX(LAST_REFRESH_AT) refresh1, MIN(LAST_REFRESH_AT) refresh0
FROM LIBRARY_MARTS.HOUSING.HOUSING__FED_FEMA_NFIP_COMMUNITY_STATUS_BOOK
GROUP BY ROLLUP(1,2) ORDER BY 1,2;

-- @S06 NFIP book: what the raw map-date text says when it is not a date, future-date years, CRS classes, name suffix types, ID shape
WITH b AS (SELECT * FROM LIBRARY_MARTS.HOUSING.HOUSING__FED_FEMA_NFIP_COMMUNITY_STATUS_BOOK)
SELECT * FROM (SELECT 'RAW_NOT_DATE' k, CURRENTLY_EFFECTIVE_MAP_DATE_RAW v, COUNT(*) n FROM b WHERE CURRENTLY_EFFECTIVE_MAP_DATE IS NULL GROUP BY 2 ORDER BY 3 DESC LIMIT 15)
UNION ALL SELECT * FROM (SELECT 'RAW_SAMPLE', CURRENTLY_EFFECTIVE_MAP_DATE_RAW || ' -> ' || TO_VARCHAR(CURRENTLY_EFFECTIVE_MAP_DATE), COUNT(*) FROM b WHERE CURRENTLY_EFFECTIVE_MAP_DATE IS NOT NULL GROUP BY 2 ORDER BY 3 DESC LIMIT 5)
UNION ALL SELECT 'FUT_FHBM_YR', TO_VARCHAR(YEAR(INITIAL_FLOOD_HAZARD_BOUNDARY_MAP_DATE)), COUNT(*) FROM b WHERE INITIAL_FLOOD_HAZARD_BOUNDARY_MAP_DATE > CURRENT_DATE GROUP BY 2
UNION ALL SELECT 'FUT_REG_YR', TO_VARCHAR(YEAR(REGULAR_EMERGENCY_PROGRAM_DATE)), COUNT(*) FROM b WHERE REGULAR_EMERGENCY_PROGRAM_DATE > CURRENT_DATE GROUP BY 2
UNION ALL SELECT 'REG_YR_1968_75', TO_VARCHAR(YEAR(REGULAR_EMERGENCY_PROGRAM_DATE)), COUNT(*) FROM b WHERE YEAR(REGULAR_EMERGENCY_PROGRAM_DATE) BETWEEN 1960 AND 1975 GROUP BY 2
UNION ALL SELECT 'CRS', CRS_CLASS_RATING, COUNT(*) FROM b GROUP BY 2
UNION ALL SELECT * FROM (SELECT 'SUFFIX', COALESCE(REGEXP_SUBSTR(COMMUNITY_NAME, ',\\s*([^,]*)$', 1, 1, 'e'), '(none)'), COUNT(*) FROM b GROUP BY 2 ORDER BY 3 DESC LIMIT 25)
UNION ALL SELECT 'ID_LEN', TO_VARCHAR(LENGTH(COMMUNITY_ID_NUMBER)) || ' state_prefix_distinct_per_state=' || TO_VARCHAR(COUNT(DISTINCT STATE)), COUNT(*) FROM b GROUP BY LENGTH(COMMUNITY_ID_NUMBER)
UNION ALL SELECT * FROM (SELECT 'NAME_SAMPLE', COMMUNITY_ID_NUMBER || ' | ' || COMMUNITY_NAME || ' | ' || COALESCE(COUNTY,'') || ' | ' || STATE || ' | p=' || COALESCE(PARTICIPATING_IN_NFIP_FLAG,'') || ' | cem=' || COALESCE(CURRENTLY_EFFECTIVE_MAP_DATE_RAW,''), 1 FROM b SAMPLE (12 ROWS));

-- @S07 FEMA household aid: rows vs distinct registrations, incident types, flood fields, date span, load runs
SELECT INCIDENT_TYPE_CODE, COUNT(*) n, COUNT(DISTINCT REGISTRATION_ID) regs, COUNT(DISTINCT DISASTER_NUMBER) disasters,
       MIN(DECLARATION_DATE) d0, MAX(DECLARATION_DATE) d1,
       COUNT_IF(UPPER(FLOOD_DAMAGE) IN ('TRUE','1','T','Y','1.0')) flood_dmg, COUNT_IF(UPPER(FLOOD_INSURANCE) IN ('TRUE','1','T','Y','1.0')) flood_ins,
       ARRAY_AGG(DISTINCT FLOOD_DAMAGE) fd_vals, ARRAY_AGG(DISTINCT FLOOD_INSURANCE) fi_vals, ARRAY_AGG(DISTINCT OWN_RENT) own_vals,
       COUNT_IF(NULLIF(TRIM(FIPS),'') IS NOT NULL) fips_filled, COUNT_IF(NULLIF(TRIM(COUNTY),'') IS NOT NULL) county_filled,
       COUNT_IF(NULLIF(TRIM(DAMAGED_CITY),'') IS NOT NULL) city_filled, SUM(IHP_AMOUNT) ihp, SUM(REPAIR_AMOUNT) repair,
       COUNT(DISTINCT _SOURCE_RUN_ID) runs
FROM LIBRARY_MARTS.HOUSING.HOUSING__FED_FEMA_IA_HOUSING_REGISTRATIONS
GROUP BY ROLLUP(1) ORDER BY n DESC;
