-- @S08 EXTRACT NFIP community status book, every community (25K rows), for local peer and map-age math
SELECT COMMUNITY_ID_NUMBER, COMMUNITY_NAME, COUNTY, STATE, INITIAL_FLOOD_HAZARD_BOUNDARY_MAP_DATE fhbm, INITIAL_FLOOD_INSURANCE_RATE_MAP_DATE firm,
       CURRENTLY_EFFECTIVE_MAP_DATE_RAW cem_raw, CURRENTLY_EFFECTIVE_MAP_DATE cem, REGULAR_EMERGENCY_PROGRAM_DATE reg, ORIGINAL_ENTRY_DATE crs_entry,
       TRIBAL_FLAG, PARTICIPATING_IN_NFIP_FLAG, CLASS_RATING_EFFECTIVE_DATE, CRS_CLASS_RATING, LAST_REFRESH_AT
FROM LIBRARY_MARTS.HOUSING.HOUSING__FED_FEMA_NFIP_COMMUNITY_STATUS_BOOK;

-- @S09 EXTRACT FEMA household aid, flood-damaged registrations only, aggregated to disaster x state x city x county x own/rent (aggregate before joining)
SELECT DISASTER_NUMBER, INCIDENT_TYPE_CODE, MIN(DECLARATION_DATE) decl, DAMAGED_STATE_ABBREVIATION st, UPPER(TRIM(DAMAGED_CITY)) city,
       UPPER(TRIM(COUNTY)) county, MIN(FIPS) fips_min, MAX(FIPS) fips_max, OWN_RENT,
       COUNT(*) regs, COUNT(DISTINCT REGISTRATION_ID) ids,
       COUNT_IF(FLOOD_INSURANCE = 'True') flood_ins, COUNT_IF(HOMEOWNERS_INSURANCE = 'True') home_ins,
       COUNT_IF(IHP_ELIGIBLE = 'True') ihp_elig, SUM(IHP_AMOUNT) ihp_amt, SUM(REPAIR_AMOUNT) repair_amt, COUNT_IF(REPAIR_AMOUNT > 0) repair_n,
       SUM(RPFVL) rpfvl, SUM(UNMET_NEED_RP) unmet_rp, SUM(FLOOD_DAMAGE_AMOUNT) flood_dmg_amt, COUNT_IF(PRIMARY_RESIDENCE = 'True') primary_res
FROM LIBRARY_MARTS.HOUSING.HOUSING__FED_FEMA_IA_HOUSING_REGISTRATIONS
WHERE FLOOD_DAMAGE = 'True'
GROUP BY DISASTER_NUMBER, INCIDENT_TYPE_CODE, DAMAGED_STATE_ABBREVIATION, UPPER(TRIM(DAMAGED_CITY)), UPPER(TRIM(COUNTY)), OWN_RENT;

-- @S10 EXTRACT FHFA house price index, whole table (185K rows), for local metro-vs-state peer and peak-to-now math
SELECT HPI_TYPE, HPI_FLAVOR, FREQUENCY, LEVEL, PLACE_NAME, PLACE_ID, YR, PERIOD, INDEX_NSA, INDEX_SA, RSTDERR, NOTE
FROM LIBRARY_MARTS.HOUSING.HOUSING__FED_FHFA_HPI;

-- @S11 NSF awards, all 115 rows (small), to read programs, dates, places and abstracts
SELECT AWARD_ID, TITLE, AWARDEE_NAME, INSTITUTION, PI_NAME, PROGRAM_OFFICER, AWARD_AMOUNT, AWARD_DATE, START_DATE, END_DATE,
       PROGRAM_NAME, CITY, STATE, ZIP, COUNTRY, CFDA_NUMBER, LEFT(ABSTRACT, 600) abstract600, LENGTH(ABSTRACT) abstract_len
FROM LIBRARY_MARTS.SCIENCE.SCIENCE__FED_NSF_AWARDS
ORDER BY AWARD_AMOUNT DESC;
