-- @S12 FEMA household aid, flood-damaged only: every housing-aid decision code and ineligible-reason code, with counts and repair money
SELECT 'HA_STATUS' k, HA_STATUS v, COUNT(*) n, COUNT_IF(OWN_RENT = 'O') owners, COUNT_IF(REPAIR_AMOUNT > 0) repair_n, SUM(REPAIR_AMOUNT) repair_amt, COUNT_IF(FLOOD_INSURANCE = 'True') flood_ins
FROM LIBRARY_MARTS.HOUSING.HOUSING__FED_FEMA_IA_HOUSING_REGISTRATIONS WHERE FLOOD_DAMAGE = 'True' GROUP BY 2
UNION ALL
SELECT 'INELIGIBLE_REASON', INELIGIBLE_REASON, COUNT(*), COUNT_IF(OWN_RENT = 'O'), COUNT_IF(REPAIR_AMOUNT > 0), SUM(REPAIR_AMOUNT), COUNT_IF(FLOOD_INSURANCE = 'True')
FROM LIBRARY_MARTS.HOUSING.HOUSING__FED_FEMA_IA_HOUSING_REGISTRATIONS WHERE FLOOD_DAMAGE = 'True' GROUP BY 2
ORDER BY 1, 3 DESC;
