-- @S13 FEMA household aid: every flood-damaged registration FEMA coded "Sanctioned Community in SFHA" (246 rows), row level
SELECT DISASTER_NUMBER, INCIDENT_TYPE_CODE, DECLARATION_DATE, DAMAGED_STATE_ABBREVIATION st, UPPER(TRIM(DAMAGED_CITY)) city, UPPER(TRIM(COUNTY)) county,
       DAMAGED_ZIP_CODE zip, LEFT(CENSUS_GEOID, 11) tract, OWN_RENT, FLOOD_INSURANCE, HA_STATUS, IHP_AMOUNT, HA_AMOUNT, REPAIR_AMOUNT,
       RENTAL_ASSISTANCE_AMOUNT, ONA_AMOUNT, RPFVL, FLOOD_DAMAGE_AMOUNT, WATER_LEVEL, HIGH_WATER_LOCATION
FROM LIBRARY_MARTS.HOUSING.HOUSING__FED_FEMA_IA_HOUSING_REGISTRATIONS
WHERE FLOOD_DAMAGE = 'True' AND HA_STATUS ILIKE '%Sanctioned Community%'
ORDER BY DECLARATION_DATE, st, city;

-- @S14 FEMA household aid, flood-damaged, by disaster: is the housing-decision code filled, and how often is the sanction code used
SELECT DISASTER_NUMBER, MIN(DECLARATION_DATE) decl, ANY_VALUE(DAMAGED_STATE_ABBREVIATION) st, COUNT(*) n,
       COUNT_IF(HA_STATUS IS NULL OR TRIM(HA_STATUS) = '') ha_blank, COUNT_IF(HA_STATUS ILIKE '%Sanctioned Community%') isc,
       COUNT_IF(REPAIR_AMOUNT > 0) repair_n
FROM LIBRARY_MARTS.HOUSING.HOUSING__FED_FEMA_IA_HOUSING_REGISTRATIONS
WHERE FLOOD_DAMAGE = 'True'
GROUP BY 1 ORDER BY 2;

-- @S15 eyeball: 12 flood-damaged owner registrations with repair money in two not-in-program towns (Belleville MI, Eutawville SC)
SELECT * FROM (
  SELECT DISASTER_NUMBER, DECLARATION_DATE, DAMAGED_STATE_ABBREVIATION st, DAMAGED_CITY, COUNTY, DAMAGED_ZIP_CODE, LEFT(CENSUS_GEOID, 11) tract,
         OWN_RENT, FLOOD_INSURANCE, HA_STATUS, REPAIR_AMOUNT, RPFVL, WATER_LEVEL, HIGH_WATER_LOCATION
  FROM LIBRARY_MARTS.HOUSING.HOUSING__FED_FEMA_IA_HOUSING_REGISTRATIONS
  WHERE FLOOD_DAMAGE = 'True' AND OWN_RENT = 'O' AND REPAIR_AMOUNT > 0
    AND ((DAMAGED_STATE_ABBREVIATION = 'MI' AND UPPER(TRIM(DAMAGED_CITY)) = 'BELLEVILLE') OR (DAMAGED_STATE_ABBREVIATION = 'SC' AND UPPER(TRIM(DAMAGED_CITY)) = 'EUTAWVILLE'))
  ORDER BY RANDOM() LIMIT 12)
ORDER BY st, DECLARATION_DATE;
