-- @S16 crosswalk follow-up: HMDA historic's lender-ID columns, and any landing copies of the ARID crosswalk with their row counts
SELECT 'HIST_COL' k, COLUMN_NAME v, DATA_TYPE x, NULL::NUMBER n
FROM LIBRARY_MARTS.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'HOUSING__FED_CFPB_HMDA_HISTORIC' AND (COLUMN_NAME ILIKE '%RESP%' OR COLUMN_NAME ILIKE '%AGENCY%' OR COLUMN_NAME ILIKE '%YEAR%' OR COLUMN_NAME ILIKE '%LEI%' OR COLUMN_NAME ILIKE '%ARID%')
UNION ALL
SELECT 'LANDING', TABLE_SCHEMA || '.' || TABLE_NAME, TABLE_TYPE, ROW_COUNT
FROM LIBRARY_RAW.INFORMATION_SCHEMA.TABLES
WHERE TABLE_NAME ILIKE '%ARID%' OR TABLE_NAME ILIKE '%LEI_XREF%'
ORDER BY 1, 2;
