{{ config(tags=['minimal_staging']) }}

-- GRAIN: NOT YET DETERMINED -- passthrough staging view (snake_case rename only, no dedup).
-- Generated by scripts/gen_minimal_staging_for_new_sources.py, 2026-08-05 ingestion sweep
-- (housing/health/energy block, part 2). Acquisition only -- no analysis/publish.

with source as (

    select * from {{ source('ripple_raw', 'FED_EIA860_3_4_ENERGY_STORAGE') }}

),

renamed as (

    select
        UTILITY_ID as utility_id,
        UTILITY_NAME as utility_name,
        PLANT_CODE as plant_code,
        PLANT_NAME as plant_name,
        STATE as state,
        COUNTY as county,
        GENERATOR_ID as generator_id,
        STATUS as status,
        TECHNOLOGY as technology,
        PRIME_MOVER as prime_mover,
        SECTOR_NAME as sector_name,
        SECTOR as sector,
        NAMEPLATE_CAPACITY_MW as nameplate_capacity_mw,
        SUMMER_CAPACITY_MW as summer_capacity_mw,
        WINTER_CAPACITY_MW as winter_capacity_mw,
        OPERATING_MONTH as operating_month,
        OPERATING_YEAR as operating_year,
        NAMEPLATE_ENERGY_CAPACITY_MWH as nameplate_energy_capacity_mwh,
        MAXIMUM_CHARGE_RATE_MW as maximum_charge_rate_mw,
        MAXIMUM_DISCHARGE_RATE_MW as maximum_discharge_rate_mw,
        STORAGE_TECHNOLOGY_1 as storage_technology_1,
        STORAGE_TECHNOLOGY_2 as storage_technology_2,
        STORAGE_TECHNOLOGY_3 as storage_technology_3,
        STORAGE_TECHNOLOGY_4 as storage_technology_4,
        NAMEPLATE_REACTIVE_POWER_RATING as nameplate_reactive_power_rating,
        STORAGE_ENCLOSURE_TYPE as storage_enclosure_type,
        ARBITRAGE as arbitrage,
        FREQUENCY_REGULATION as frequency_regulation,
        LOAD_FOLLOWING as load_following,
        RAMPING_SPINNING_RESERVE as ramping_spinning_reserve,
        CO_LOCATED_RENEWABLE_FIRMING as co_located_renewable_firming,
        TRANSMISSION_AND_DISTRIBUTION_DEFERRAL as transmission_and_distribution_deferral,
        SYSTEM_PEAK_SHAVING as system_peak_shaving,
        LOAD_MANAGEMENT as load_management,
        VOLTAGE_OR_REACTIVE_POWER_SUPPORT as voltage_or_reactive_power_support,
        BACKUP_POWER as backup_power,
        EXCESS_WIND_AND_SOLAR_GENERATION as excess_wind_and_solar_generation,
        AC_COUPLED as ac_coupled,
        DC_COUPLED as dc_coupled,
        DC_TIGHTLY_COUPLED as dc_tightly_coupled,
        INDEPENDENT as independent,
        DIRECT_SUPPORT_OF_ANOTHER_UNIT as direct_support_of_another_unit,
        DIRECT_SUPPORT_PLANT_ID_1 as direct_support_plant_id_1,
        DIRECT_SUPPORT_GEN_ID_1 as direct_support_gen_id_1,
        DIRECT_SUPPORT_PLANT_ID_2 as direct_support_plant_id_2,
        DIRECT_SUPPORT_GEN_ID_2 as direct_support_gen_id_2,
        DIRECT_SUPPORT_PLANT_ID_3 as direct_support_plant_id_3,
        DIRECT_SUPPORT_GEN_ID_3 as direct_support_gen_id_3,
        SUPPORT_T_D_ASSET as support_t_d_asset,
        _INGESTED_AT as _loaded_at,
        _SOURCE_RUN_ID as _source_run_id,
        _SRC_FILE as _src_file

    from source

)

select * from renamed
