{{ config(materialized='table', schema='PROCUREMENT') }}

-- Source: ADB Data Library ? Projects and Economic Indicators (41 rows)
-- Generated by gen_mart_models.py

with source as (
    select * from {{ source('ripple_raw', 'INTL_ADB_DATA') }}
)

select
    COUNTRY as country,
    PROJECT_ID as project_id,
    PROJECT_NAME as project_name,
    SECTOR as sector,
    try_to_date(APPROVAL_DATE) as approval_date,
    try_to_double(LOAN_AMOUNT_USD) as loan_amount_usd,
    STATUS as status,
    INDICATOR_NAME as indicator_name,
    try_to_number("YEAR") as year,
    try_to_double("VALUE") as value
from source
