-- S01 column names and types for the 5 tables and the join targets
SELECT TABLE_SCHEMA, TABLE_NAME, LISTAGG(COLUMN_NAME || ':' || LEFT(DATA_TYPE,4), ', ') WITHIN GROUP (ORDER BY ORDINAL_POSITION) cols
FROM LIBRARY_MARTS.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME IN ('ENERGY__FED_EIA860_6_2_ENVIROEQUIP','ENERGY__FED_EIA860_3_5_MULTIFUEL','ENERGY__FED_EIA861_SERVICE_TERRITORY',
  'ENERGY__FED_EIA860_1_UTILITY','ENERGY__FED_EIA861_ADVANCED_METERS','ENERGY__FED_EIA860_3_1_GENERATOR','ENERGY__FED_EIA860_2_PLANT',
  'ENERGY__FED_EIA860_6_1_ENVIROASSOC','ENVIRONMENT__FED_EPA_EGRID_PLANT_2022','ENERGY__FED_EIA861_SALES_ULT_CUST','ENERGY__FED_EIA861_RELIABILITY')
  AND COLUMN_NAME NOT LIKE 'PLANT_ANNUAL_%' AND COLUMN_NAME NOT LIKE 'PLANT_UNADJ%' AND COLUMN_NAME NOT LIKE 'PLANT_OZONE%'
GROUP BY 1,2 ORDER BY 2
