-- S02 ENVIROEQUIP profile: boiler status x sulfur regulation x existing SO2 strategy, key uniqueness, unit mix
SELECT BOILER_STATUS, REGULATION_SULFUR, UNIT_SULFUR,
       COUNT(*) n, COUNT(DISTINCT PLANT_CODE, BOILER_ID) boiler_keys, COUNT(DISTINCT PLANT_CODE) plants,
       COUNT_IF(NULLIF(TRIM(SULFUR_DIOXIDE_CONTROL_EXISTING_STRATEGY_1),'') IS NOT NULL) so2_ctl,
       COUNT_IF(NULLIF(TRIM(NITROGEN_OXIDE_CONTROL_EXISTING_STRATEGY_1),'') IS NOT NULL) nox_ctl,
       COUNT_IF(NULLIF(TRIM(MERCURY_CONTROL_EXISTING_STRATEGY_1),'') IS NOT NULL) hg_ctl,
       MIN(STANDARD_SULFUR_RATE) r0, MEDIAN(STANDARD_SULFUR_RATE) rmed, MAX(STANDARD_SULFUR_RATE) r1,
       COUNT(DISTINCT _SOURCE_RUN_ID) runs, COUNT(DISTINCT _SRC_FILE) files
FROM LIBRARY_MARTS.ENERGY.ENERGY__FED_EIA860_6_2_ENVIROEQUIP
GROUP BY ROLLUP(1,2,3) ORDER BY 1 NULLS FIRST,2 NULLS FIRST,3 NULLS FIRST
