-- S03 ENVIROEQUIP extract: every boiler + its linked generators (fuel, MW, retirement plan) + its plant's eGRID 2022 emissions
WITH a AS (
  SELECT PLANT_CODE, BOILER_ID, GENERATOR_ID FROM LIBRARY_MARTS.ENERGY.ENERGY__FED_EIA860_6_1_ENVIROASSOC
), g AS (
  SELECT PLANT_CODE, GENERATOR_ID, ENERGY_SOURCE_1, STATUS, NAMEPLATE_CAPACITY_MW, OPERATING_YEAR, PLANNED_RETIREMENT_YEAR
  FROM LIBRARY_MARTS.ENERGY.ENERGY__FED_EIA860_3_1_GENERATOR
), bg AS (
  SELECT a.PLANT_CODE, a.BOILER_ID, COUNT(*) gens, COUNT(g.GENERATOR_ID) gens_hit,
         LISTAGG(DISTINCT g.ENERGY_SOURCE_1, ',') fuels, LISTAGG(DISTINCT g.STATUS, ',') gen_status,
         SUM(g.NAMEPLATE_CAPACITY_MW) gen_mw, MIN(g.OPERATING_YEAR) op_yr,
         MIN(g.PLANNED_RETIREMENT_YEAR) ret_yr_min, MAX(g.PLANNED_RETIREMENT_YEAR) ret_yr_max
  FROM a LEFT JOIN g ON g.PLANT_CODE = a.PLANT_CODE AND g.GENERATOR_ID = a.GENERATOR_ID
  GROUP BY 1,2
), e AS (
  SELECT TRY_TO_NUMBER(DOE_EIA_ORIS_PLANT_OR_FACILITY_CODE) pc, COUNT(*) egrid_rows,
         MAX(PLANT_PRIMARY_FUEL) egrid_fuel,
         SUM(TRY_TO_DOUBLE(TO_VARCHAR(PLANT_ANNUAL_SO2_EMISSIONS_TONS))) so2_tons,
         SUM(TRY_TO_DOUBLE(TO_VARCHAR(PLANT_ANNUAL_NOX_EMISSIONS_TONS))) nox_tons,
         SUM(TRY_TO_DOUBLE(TO_VARCHAR(PLANT_ANNUAL_HG_EMISSIONS_LBS))) hg_lbs,
         SUM(TRY_TO_DOUBLE(TO_VARCHAR(PLANT_ANNUAL_NET_GENERATION_MWH))) net_mwh,
         SUM(TRY_TO_DOUBLE(TO_VARCHAR(PLANT_ANNUAL_COAL_NET_GENERATION_MWH))) coal_mwh,
         MAX(TRY_TO_DOUBLE(TO_VARCHAR(PLANT_ANNUAL_SO2_TOTAL_OUTPUT_EMISSION_RATE_LB_MWH))) so2_lb_mwh,
         MAX(TRY_TO_DOUBLE(TO_VARCHAR(PLANT_ANNUAL_SO2_INPUT_EMISSION_RATE_LB_MMBTU))) so2_lb_mmbtu,
         MAX(NERC_REGION_ACRONYM) nerc, MAX(PLANT_FIPS_STATE_CODE || PLANT_FIPS_COUNTY_CODE) fips
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_EGRID_PLANT_2022
  GROUP BY 1
)
SELECT b.PLANT_CODE, b.BOILER_ID, b.STATE, b.UTILITY_ID, b.UTILITY_NAME, b.PLANT_NAME, b.BOILER_STATUS, b.TYPE_OF_BOILER,
       b.STEAM_PLANT_TYPE, b.NEW_SOURCE_REVIEW, b.REGULATION_SULFUR, b.UNIT_SULFUR, b.PERIOD_SULFUR,
       b.STANDARD_SULFUR_RATE, b.STANDARD_SULFUR_PERCENT_SCRUBBED, b.COMPLIANCE_YEAR_SULFUR,
       b.SULFUR_DIOXIDE_CONTROL_EXISTING_STRATEGY_1 so2_ex1, b.SULFUR_DIOXIDE_CONTROL_EXISTING_STRATEGY_2 so2_ex2,
       b.SULFUR_DIOXIDE_CONTROL_EXISTING_STRATEGY_3 so2_ex3, b.SULFUR_DIOXIDE_CONTROL_PROPOSED_STRATEGY_1 so2_pr1,
       b.REGULATION_NITROGEN, b.UNIT_NITROGEN, b.STANDARD_NITROGEN_RATE, b.NITROGEN_OXIDE_CONTROL_EXISTING_STRATEGY_1 nox_ex1,
       b.NITROGEN_OXIDE_CONTROL_EXISTING_STRATEGY_2 nox_ex2, b.NITROGEN_OXIDE_CONTROL_PROPOSED_STRATEGY_1 nox_pr1,
       b.REGULATION_PARTICULATE, b.REGULATION_MERCURY, b.MERCURY_CONTROL_EXISTING_STRATEGY_1 hg_ex1, b.MERCURY_CONTROL_PROPOSED_STRATEGY_1 hg_pr1,
       b.COMPLIANCE_YEAR_NITROGEN, b.COMPLIANCE_YEAR_PARTICULATE, b.COMPLIANCE_YEAR_MERCURY,
       bg.gens, bg.gens_hit, bg.fuels, bg.gen_status, bg.gen_mw, bg.op_yr, bg.ret_yr_min, bg.ret_yr_max,
       e.egrid_rows, e.egrid_fuel, e.so2_tons, e.nox_tons, e.hg_lbs, e.net_mwh, e.coal_mwh, e.so2_lb_mwh, e.so2_lb_mmbtu, e.nerc, e.fips
FROM LIBRARY_MARTS.ENERGY.ENERGY__FED_EIA860_6_2_ENVIROEQUIP b
LEFT JOIN bg ON bg.PLANT_CODE = b.PLANT_CODE AND bg.BOILER_ID = b.BOILER_ID
LEFT JOIN e ON e.pc = b.PLANT_CODE
