-- S04 eGRID 2022: where each boiler plant's SO2 number came from (EIA fuel estimate vs EPA stack monitor), unadjusted vs CHP-adjusted, plus the US total
SELECT TRY_TO_NUMBER(DOE_EIA_ORIS_PLANT_OR_FACILITY_CODE) pc, PLANT_NAME, PLANT_STATE_ABBREVIATION st, PLANT_PRIMARY_FUEL fuel,
       CAMD_PROGRAM_FLAG camd, COMBINED_HEAT_AND_POWER_CHP_PLANT_ADJUSTMENT_FLAG chp,
       PLANT_UNADJUSTED_ANNUAL_SO2_EMISSIONS_SOURCE so2_src,
       TRY_TO_DOUBLE(TO_VARCHAR(PLANT_ANNUAL_SO2_EMISSIONS_TONS)) so2_adj,
       TRY_TO_DOUBLE(TO_VARCHAR(PLANT_UNADJUSTED_ANNUAL_SO2_EMISSIONS_TONS)) so2_unadj,
       TRY_TO_DOUBLE(TO_VARCHAR(PLANT_UNADJUSTED_ANNUAL_HEAT_INPUT_FROM_COMBUSTION_MMBTU)) heat_unadj,
       TRY_TO_DOUBLE(TO_VARCHAR(PLANT_ANNUAL_HEAT_INPUT_FROM_COMBUSTION_MMBTU)) heat_adj,
       TRY_TO_DOUBLE(TO_VARCHAR(PLANT_ANNUAL_SO2_INPUT_EMISSION_RATE_LB_MMBTU)) so2_rate,
       TRY_TO_DOUBLE(TO_VARCHAR(PLANT_ANNUAL_COAL_NET_GENERATION_MWH)) coal_mwh,
       TRY_TO_DOUBLE(TO_VARCHAR(PLANT_ANNUAL_NET_GENERATION_MWH)) net_mwh,
       SUM(TRY_TO_DOUBLE(TO_VARCHAR(PLANT_ANNUAL_SO2_EMISSIONS_TONS))) OVER () us_so2_all_plants,
       COUNT(*) OVER () us_rows
FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_EGRID_PLANT_2022
QUALIFY TRY_TO_NUMBER(DOE_EIA_ORIS_PLANT_OR_FACILITY_CODE) IN (SELECT PLANT_CODE FROM LIBRARY_MARTS.ENERGY.ENERGY__FED_EIA860_6_2_ENVIROEQUIP)
