-- S05 MULTIFUEL extract: every row + the plant's balancing authority, with a key-duplicate count
SELECT m.PLANT_CODE, m.GENERATOR_ID, m.STATE, m.UTILITY_NAME, m.PLANT_NAME, m.STATUS, m.TECHNOLOGY, m.PRIME_MOVER, m.SECTOR_NAME,
       m.ENERGY_SOURCE_1, m.ENERGY_SOURCE_2, m.MULTIPLE_FUELS, m.COFIRE_FUELS, m.SWITCH_BETWEEN_OIL_AND_NATURAL_GAS, m.SWITCH_WHEN_OPERATING,
       m.TIME_TO_SWITCH_FROM_GAS_TO_OIL, m.TIME_TO_SWITCH_FROM_OIL_TO_GAS, m.FACTORS_THAT_LIMIT_SWITCHING, m.STORAGE_LIMITS, m.AIR_PERMIT_LIMITS, m.OTHER_LIMITS,
       m.NAMEPLATE_CAPACITY_MW, m.SUMMER_CAPACITY_MW, m.WINTER_CAPACITY_MW, m.OPERATING_YEAR,
       m.NET_SUMMER_CAPACITY_WITH_NATURAL_GAS_MW, m.NET_WINTER_CAPACITY_WITH_NATURAL_GAS_MW, m.NET_SUMMER_CAPACITY_WITH_OIL_MW, m.NET_WINTER_CAPACITY_WITH_OIL_MW,
       COUNT(*) OVER (PARTITION BY m.PLANT_CODE, m.GENERATOR_ID) key_n,
       p.BALANCING_AUTHORITY_CODE ba, p.NERC_REGION nerc
FROM LIBRARY_MARTS.ENERGY.ENERGY__FED_EIA860_3_5_MULTIFUEL m
LEFT JOIN (SELECT PLANT_CODE, MAX(BALANCING_AUTHORITY_CODE) BALANCING_AUTHORITY_CODE, MAX(NERC_REGION) NERC_REGION
           FROM LIBRARY_MARTS.ENERGY.ENERGY__FED_EIA860_2_PLANT GROUP BY 1) p ON p.PLANT_CODE = m.PLANT_CODE
