-- S07 time: operating gas generators by balancing authority and build period, and how much of each can switch to oil (generator table's own flag)
SELECT p.BALANCING_AUTHORITY_CODE ba,
       CASE WHEN g.OPERATING_YEAR < 2012 THEN 'a_pre2012' WHEN g.OPERATING_YEAR < 2021 THEN 'b_2012_2020' ELSE 'c_2021_2024' END built,
       COUNT(*) gens, SUM(g.WINTER_CAPACITY_MW) winter_mw,
       SUM(IFF(g.SWITCH_BETWEEN_OIL_AND_NATURAL_GAS = 'Y', g.WINTER_CAPACITY_MW, 0)) switch_mw,
       COUNT_IF(g.SWITCH_BETWEEN_OIL_AND_NATURAL_GAS = 'Y') switch_gens,
       COUNT_IF(g.SWITCH_BETWEEN_OIL_AND_NATURAL_GAS IS NULL OR TRIM(g.SWITCH_BETWEEN_OIL_AND_NATURAL_GAS) = '') switch_blank
FROM LIBRARY_MARTS.ENERGY.ENERGY__FED_EIA860_3_1_GENERATOR g
LEFT JOIN (SELECT PLANT_CODE, MAX(BALANCING_AUTHORITY_CODE) BALANCING_AUTHORITY_CODE FROM LIBRARY_MARTS.ENERGY.ENERGY__FED_EIA860_2_PLANT GROUP BY 1) p
       ON p.PLANT_CODE = g.PLANT_CODE
WHERE g.STATUS = 'OP' AND g.ENERGY_SOURCE_1 = 'NG'
GROUP BY ROLLUP(2, 1)
