-- S08 ADVANCED_METERS extract: every utility-state row, meter counts by kind, plus key-duplicate count
SELECT DATA_YEAR, UTILITY_NUMBER, UTILITY_NAME, OWNERSHIP, SHORT_FORM, STATE, BA_CODE,
       RESIDENTIAL_AMR_METERS, TOTAL_AMR_METERS, RESIDENTIAL_AMI_METERS, TOTAL_AMI_METERS, RESIDENTIAL_NON_AMR_AMI_METERS, TOTAL_NON_AMR_AMI_METERS,
       RESIDENTIAL_TOTAL_METERS, TOTAL_TOTAL_METERS, TOTAL_ENERGY_SERVED_AMI_MWH, TOTAL_AMI_HOME_AREA_NETWORK_METERS, TOTAL_AMI_DAILY_DIGITAL_ACCESS_METERS,
       COUNT(*) OVER (PARTITION BY UTILITY_NUMBER, STATE) key_n, COUNT(DISTINCT _SOURCE_RUN_ID) OVER () runs
FROM LIBRARY_MARTS.ENERGY.ENERGY__FED_EIA861_ADVANCED_METERS
