-- S10 EIA-860 UTILITY lookup check: entity types x owner/operator flags, address fillers, ZIP shape, duplicate IDs
SELECT ENTITY_TYPE, COUNT(*) n, COUNT(DISTINCT UTILITY_ID) ids,
       COUNT_IF(OWNER_OF_PLANTS_REPORTED_ON_FORM = 'Y') owner_y, COUNT_IF(OPERATOR_OF_PLANTS_REPORTED_ON_FORM = 'Y') operator_y,
       COUNT_IF(ASSET_MANAGER_OF_PLANTS_REPORTED_ON_FORM = 'Y') am_y, COUNT_IF(OTHER_RELATIONSHIPS_WITH_PLANTS_REPORTED_ON_FORM = 'Y') other_y,
       COUNT_IF(NOT REGEXP_LIKE(ZIP, '^[0-9]{5}(-?[0-9]{4})?$')) zip_bad, COUNT_IF(LENGTH(ZIP) = 4) zip4,
       COUNT_IF(STREET_ADDRESS ILIKE '%TBD%' OR STREET_ADDRESS ILIKE 'PO BOX%' OR STREET_ADDRESS ILIKE 'P.O.%' OR STREET_ADDRESS ILIKE 'P O BOX%') po_or_tbd,
       COUNT(DISTINCT STREET_ADDRESS, ZIP) addrs, COUNT(DISTINCT UPPER(UTILITY_NAME)) names
FROM LIBRARY_MARTS.ENERGY.ENERGY__FED_EIA860_1_UTILITY
GROUP BY ROLLUP(1) ORDER BY n DESC
