-- S11 join: 2024 outage numbers for every investor-owned utility-state row (EIA-861 reliability), to set against hand-read meter share
SELECT UTILITY_NUMBER, UTILITY_NAME, STATE, OWNERSHIP,
       IEEE_SAIDI_WITHOUT_MED_MINUTES saidi_x, IEEE_SAIFI_WITHOUT_MED saifi_x, IEEE_CAIDI_WITHOUT_MED_MINUTES caidi_x,
       IEEE_SAIDI_WITH_MED_MINUTES saidi_all, IEEE_NUMBER_OF_CUSTOMERS cust, IEEE_OUTAGES_RECORDED_AUTOMATICALLY auto_rec,
       OTHER_SAIDI_WITHOUT_MED_MINUTES o_saidi_x, OTHER_CAIDI_WITHOUT_MED_MINUTES o_caidi_x, OTHER_OUTAGES_RECORDED_AUTOMATICALLY o_auto,
       COUNT(*) OVER (PARTITION BY UTILITY_NUMBER, STATE) key_n
FROM LIBRARY_MARTS.ENERGY.ENERGY__FED_EIA861_RELIABILITY
WHERE OWNERSHIP ILIKE 'investor%'
