-- S12 second field for the meter lead: EIA-860 utility roster addresses for the hand-read-heavy utilities, plus every roster entry sharing those addresses
WITH t AS (
  SELECT UTILITY_ID, UTILITY_NAME, STREET_ADDRESS, CITY, STATE, ZIP, ENTITY_TYPE
  FROM LIBRARY_MARTS.ENERGY.ENERGY__FED_EIA860_1_UTILITY
  WHERE UTILITY_ID IN (3755, 9726, 12796, 13998, 15263, 18997, 66101, 15473, 11208, 13511, 4176, 15472, 54913)
)
SELECT 'target' k, t.* FROM t
UNION ALL
SELECT 'same_address' k, u.UTILITY_ID, u.UTILITY_NAME, u.STREET_ADDRESS, u.CITY, u.STATE, u.ZIP, u.ENTITY_TYPE
FROM LIBRARY_MARTS.ENERGY.ENERGY__FED_EIA860_1_UTILITY u
WHERE (UPPER(u.STREET_ADDRESS), LEFT(u.ZIP,5)) IN (SELECT UPPER(STREET_ADDRESS), LEFT(ZIP,5) FROM t)
  AND u.UTILITY_ID NOT IN (SELECT UTILITY_ID FROM t)
