{{ config(materialized='view') }}

/*
  Hand-built 2026-08-09 for the dead-source rebuild sprint (fed_fra_crossing_incidents).
  Grain: one row = one highway-rail grade crossing incident (Form 57)
  REPORT_KEY is NOT unique (24 of 251,149 duplicated: 2 byte-identical rows + 22 same-key amended/joint filings) -- kept as landed, no unique test, no dedup.
*/

with source as (
    select * from {{ source('ripple_raw', 'FED_FRA_CROSSING_INCIDENTS') }}
),

renamed as (
    select
        nullif(trim("RAILROAD_CODE"), '') as railroad_code,
        nullif(trim("RAILROAD_NAME"), '') as railroad_name,
        nullif(trim("REPORT_YEAR"), '') as report_year,
        nullif(trim("INCIDENT_NUMBER"), '') as incident_number,
        nullif(trim("INCIDENT_YEAR"), '') as incident_year,
        nullif(trim("INCIDENT_MONTH"), '') as incident_month,
        nullif(trim("OTHER_RAILROAD_CODE"), '') as other_railroad_code,
        nullif(trim("OTHER_RAILROAD_NAME"), '') as other_railroad_name,
        nullif(trim("OTHER_INCIDENT_NUMBER"), '') as other_incident_number,
        nullif(trim("OTHER_INCIDENT_YEAR"), '') as other_incident_year,
        nullif(trim("OTHER_INCIDENT_MONTH"), '') as other_incident_month,
        nullif(trim("MAINTENANCE_RAILROAD_CODE"), '') as maintenance_railroad_code,
        nullif(trim("MAINTENANCE_RAILROAD_NAME"), '') as maintenance_railroad_name,
        nullif(trim("MAINTAINANCE_INCIDENT_NUMBER"), '') as maintainance_incident_number,
        nullif(trim("MAINTENANCE_INCIDENT_YEAR"), '') as maintenance_incident_year,
        nullif(trim("MAINTENANCE_INCIDENT_MONTH"), '') as maintenance_incident_month,
        nullif(trim("GRADE_CROSSING_ID"), '') as grade_crossing_id,
        try_to_date(trim("DATE"), 'MM/DD/YYYY') as date,
        nullif(trim("MONTH"), '') as month,
        nullif(trim("DAY"), '') as day,
        nullif(trim("HOUR"), '') as hour,
        nullif(trim("MINUTE"), '') as minute,
        nullif(trim("AM_PM"), '') as am_pm,
        nullif(trim("TIME"), '') as time,
        nullif(trim("NEAREST_STATION"), '') as nearest_station,
        nullif(trim("DIVISION"), '') as division,
        nullif(trim("SUBDIVISION"), '') as subdivision,
        nullif(trim("COUNTY_CODE"), '') as county_code,
        nullif(trim("COUNTY_NAME"), '') as county_name,
        nullif(trim("STATE_CODE"), '') as state_code,
        nullif(trim("STATE_NAME"), '') as state_name,
        nullif(trim("CITY_NAME"), '') as city_name,
        nullif(trim("HIGHWAY_NAME"), '') as highway_name,
        nullif(trim("PUBLIC_PRIVATE_CODE"), '') as public_private_code,
        nullif(trim("PUBLIC_PRIVATE"), '') as public_private,
        nullif(trim("HIGHWAY_USER_CODE"), '') as highway_user_code,
        nullif(trim("HIGHWAY_USER"), '') as highway_user,
        try_to_number(replace(trim("ESTIMATED_VEHICLE_SPEED"), ',', '')) as estimated_vehicle_speed,
        nullif(trim("VEHICLE_DIRECTION_CODE"), '') as vehicle_direction_code,
        nullif(trim("VEHICLE_DIRECTION"), '') as vehicle_direction,
        nullif(trim("HIGHWAY_USER_POSITION_CODE"), '') as highway_user_position_code,
        nullif(trim("HIGHWAY_USER_POSITION"), '') as highway_user_position,
        nullif(trim("EQUIPMENT_INVOLVED_CODE"), '') as equipment_involved_code,
        nullif(trim("EQUIPMENT_INVOLVED"), '') as equipment_involved,
        nullif(trim("RAILROAD_CAR_UNIT_POSITION"), '') as railroad_car_unit_position,
        nullif(trim("EQUIPMENT_STRUCK_CODE"), '') as equipment_struck_code,
        nullif(trim("EQUIPMENT_STRUCK"), '') as equipment_struck,
        nullif(trim("HAZMAT_INVOLVEMENT_CODE"), '') as hazmat_involvement_code,
        nullif(trim("HAZMAT_INVOLVEMENT"), '') as hazmat_involvement,
        nullif(trim("HAZMAT_RELEASED_BY_CODE"), '') as hazmat_released_by_code,
        nullif(trim("HAZMAT_RELEASED_BY"), '') as hazmat_released_by,
        nullif(trim("HAZMAT_RELEASED_NAME"), '') as hazmat_released_name,
        nullif(trim("HAZMAT_RELEASED_QUANTITY"), '') as hazmat_released_quantity,
        nullif(trim("HAZMAT_RELEASED_MEASURE"), '') as hazmat_released_measure,
        try_to_number(replace(trim("TEMPERATURE"), ',', '')) as temperature,
        nullif(trim("VISIBILITY_CODE"), '') as visibility_code,
        nullif(trim("VISIBILITY"), '') as visibility,
        nullif(trim("WEATHER_CONDITION_CODE"), '') as weather_condition_code,
        nullif(trim("WEATHER_CONDITION"), '') as weather_condition,
        nullif(trim("EQUIPMENT_TYPE_CODE"), '') as equipment_type_code,
        nullif(trim("EQUIPMENT_TYPE"), '') as equipment_type,
        nullif(trim("TRACK_TYPE_CODE"), '') as track_type_code,
        nullif(trim("TRACK_TYPE"), '') as track_type,
        nullif(trim("TRACK_NAME"), '') as track_name,
        nullif(trim("TRACK_CLASS"), '') as track_class,
        nullif(trim("NUMBER_OF_LOCOMOTIVE_UNITS"), '') as number_of_locomotive_units,
        nullif(trim("NUMBER_OF_CARS"), '') as number_of_cars,
        try_to_number(replace(trim("TRAIN_SPEED"), ',', '')) as train_speed,
        nullif(trim("ESTIMATED_RECORDED_SPEED"), '') as estimated_recorded_speed,
        nullif(trim("TRAIN_DIRECTION_CODE"), '') as train_direction_code,
        nullif(trim("TRAIN_DIRECTION"), '') as train_direction,
        nullif(trim("CROSSING_WARNING_EXPANDED_CODE_1"), '') as crossing_warning_expanded_code_1,
        nullif(trim("CROSSING_WARNING_EXPANDED_CODE_2"), '') as crossing_warning_expanded_code_2,
        nullif(trim("CROSSING_WARNING_EXPANDED_CODE_3"), '') as crossing_warning_expanded_code_3,
        nullif(trim("CROSSING_WARNING_EXPANDED_CODE_4"), '') as crossing_warning_expanded_code_4,
        nullif(trim("CROSSING_WARNING_EXPANDED_CODE_5"), '') as crossing_warning_expanded_code_5,
        nullif(trim("CROSSING_WARNING_EXPANDED_CODE_6"), '') as crossing_warning_expanded_code_6,
        nullif(trim("CROSSING_WARNING_EXPANDED_CODE_7"), '') as crossing_warning_expanded_code_7,
        nullif(trim("CROSSING_WARNING_EXPANDED_CODE_8"), '') as crossing_warning_expanded_code_8,
        nullif(trim("CROSSING_WARNING_EXPANDED_CODE_9"), '') as crossing_warning_expanded_code_9,
        nullif(trim("CROSSING_WARNING_EXPANDED_CODE_10"), '') as crossing_warning_expanded_code_10,
        nullif(trim("CROSSING_WARNING_EXPANDED_CODE_11"), '') as crossing_warning_expanded_code_11,
        nullif(trim("CROSSING_WARNING_EXPANDED_CODE_12"), '') as crossing_warning_expanded_code_12,
        nullif(trim("CROSSING_WARNING_EXPANDED_1"), '') as crossing_warning_expanded_1,
        nullif(trim("CROSSING_WARNING_EXPANDED_2"), '') as crossing_warning_expanded_2,
        nullif(trim("CROSSING_WARNING_EXPANDED_3"), '') as crossing_warning_expanded_3,
        nullif(trim("CROSSING_WARNING_EXPANDED_4"), '') as crossing_warning_expanded_4,
        nullif(trim("CROSSING_WARNING_EXPANDED_5"), '') as crossing_warning_expanded_5,
        nullif(trim("CROSSING_WARNING_EXPANDED_6"), '') as crossing_warning_expanded_6,
        nullif(trim("CROSSING_WARNING_EXPANDED_7"), '') as crossing_warning_expanded_7,
        nullif(trim("CROSSING_WARNING_EXPANDED_8"), '') as crossing_warning_expanded_8,
        nullif(trim("CROSSING_WARNING_EXPANDED_9"), '') as crossing_warning_expanded_9,
        nullif(trim("CROSSING_WARNING_EXPANDED_10"), '') as crossing_warning_expanded_10,
        nullif(trim("CROSSING_WARNING_EXPANDED_11"), '') as crossing_warning_expanded_11,
        nullif(trim("CROSSING_WARNING_EXPANDED_12"), '') as crossing_warning_expanded_12,
        nullif(trim("SIGNALED_CROSSING_WARNING_CODE"), '') as signaled_crossing_warning_code,
        nullif(trim("SIGNALED_CROSSING_WARNING"), '') as signaled_crossing_warning,
        nullif(trim("CROSSING_WARNING_EXPLANATION_CODE"), '') as crossing_warning_explanation_code,
        nullif(trim("CROSSING_WARNING_EXPLANATION"), '') as crossing_warning_explanation,
        nullif(trim("ROADWAY_CONDITION_CODE"), '') as roadway_condition_code,
        nullif(trim("ROADWAY_CONDITION"), '') as roadway_condition,
        nullif(trim("CROSSING_WARNING_LOCATION_CODE"), '') as crossing_warning_location_code,
        nullif(trim("CROSSING_WARNING_LOCATION"), '') as crossing_warning_location,
        nullif(trim("WARNING_CONNECTED_TO_SIGNAL"), '') as warning_connected_to_signal,
        nullif(trim("CROSSING_ILLUMINATED"), '') as crossing_illuminated,
        try_to_number(replace(trim("USER_AGE"), ',', '')) as user_age,
        nullif(trim("USER_SEX"), '') as user_sex,
        nullif(trim("USER_STRUCK_BY_SECOND_TRAIN"), '') as user_struck_by_second_train,
        nullif(trim("HIGHWAY_USER_ACTION_CODE"), '') as highway_user_action_code,
        nullif(trim("HIGHWAY_USER_ACTION"), '') as highway_user_action,
        nullif(trim("DRIVER_PASSED_VEHICLE"), '') as driver_passed_vehicle,
        nullif(trim("VIEW_OBSTRUCTION_CODE"), '') as view_obstruction_code,
        nullif(trim("VIEW_OBSTRUCTION"), '') as view_obstruction,
        nullif(trim("DRIVER_CONDITION_CODE"), '') as driver_condition_code,
        nullif(trim("DRIVER_CONDITION"), '') as driver_condition,
        nullif(trim("DRIVER_IN_VEHICLE"), '') as driver_in_vehicle,
        try_to_number(replace(trim("CROSSING_USERS_KILLED"), ',', '')) as crossing_users_killed,
        try_to_number(replace(trim("CROSSING_USERS_INJURED"), ',', '')) as crossing_users_injured,
        try_to_number(replace(trim("VEHICLE_DAMAGE_COST"), ',', '')) as vehicle_damage_cost,
        try_to_number(replace(trim("NUMBER_VEHICLE_OCCUPANTS"), ',', '')) as number_vehicle_occupants,
        try_to_number(replace(trim("EMPLOYEES_KILLED"), ',', '')) as employees_killed,
        try_to_number(replace(trim("EMPLOYEES_INJURED"), ',', '')) as employees_injured,
        try_to_number(replace(trim("NUMBER_PEOPLE_ON_TRAIN"), ',', '')) as number_people_on_train,
        nullif(trim("FORM_54_FILED"), '') as form_54_filed,
        try_to_number(replace(trim("PASSENGERS_KILLED"), ',', '')) as passengers_killed,
        try_to_number(replace(trim("PASSENGERS_INJURED"), ',', '')) as passengers_injured,
        nullif(trim("VIDEO_TAKEN"), '') as video_taken,
        nullif(trim("VIDEO_USED"), '') as video_used,
        nullif(trim("SPECIAL_STUDY_1"), '') as special_study_1,
        nullif(trim("SPECIAL_STUDY_2"), '') as special_study_2,
        nullif(trim("NARRATIVE"), '') as narrative,
        try_to_number(replace(trim("TOTAL_KILLED_FORM_57"), ',', '')) as total_killed_form_57,
        try_to_number(replace(trim("TOTAL_INJURED_FORM_57"), ',', '')) as total_injured_form_57,
        nullif(trim("RAILROAD_TYPE"), '') as railroad_type,
        nullif(trim("JOINT_CODE"), '') as joint_code,
        try_to_number(replace(trim("TOTAL_KILLED_FORM_55A"), ',', '')) as total_killed_form_55a,
        try_to_number(replace(trim("TOTAL_INJURED_FORM_55A"), ',', '')) as total_injured_form_55a,
        nullif(trim("DISTRICT"), '') as district,
        nullif(trim("WHISTLE_BAN_CODE"), '') as whistle_ban_code,
        nullif(trim("WHISTLE_BAN"), '') as whistle_ban,
        nullif(trim("REPORT_KEY"), '') as report_key,
        nullif(trim("REPORTING_RAILROAD_CLASS"), '') as reporting_railroad_class,
        nullif(trim("REPORTING_RAILROAD_SMT_GROUPING"), '') as reporting_railroad_smt_grouping,
        nullif(trim("REPORTING_PARENT_RAILROAD_CODE"), '') as reporting_parent_railroad_code,
        nullif(trim("REPORTING_PARENT_RAILROAD_NAME"), '') as reporting_parent_railroad_name,
        nullif(trim("REPORTING_RAILROAD_HOLDING_COMPANY"), '') as reporting_railroad_holding_company,
        nullif(trim("URL"), '') as url,
        nullif(trim("REPORTING_RAILROAD_INDIVIDUAL_CLASS"), '') as reporting_railroad_individual_class,
        nullif(trim("REPORTING_RAILROAD_PASSENGER"), '') as reporting_railroad_passenger,
        nullif(trim("REPORTING_RAILROAD_COMMUTER"), '') as reporting_railroad_commuter,
        nullif(trim("REPORTING_RAILROAD_SWITCHING_TERMINAL"), '') as reporting_railroad_switching_terminal,
        nullif(trim("REPORTING_RAILROAD_TOURIST"), '') as reporting_railroad_tourist,
        nullif(trim("REPORTING_RAILROAD_FREIGHT"), '') as reporting_railroad_freight,
        nullif(trim("REPORTING_RAILROAD_SHORT_LINE"), '') as reporting_railroad_short_line,
        to_timestamp_ntz(_INGESTED_AT, 6) as _ingested_at,
        nullif(trim(_SOURCE_RUN_ID), '') as _source_run_id
    from source
)

select * from renamed
