SHOW TABLES LIKE '%INJURY_VIOLENCE%' IN ACCOUNT;;
WITH m AS (SELECT i.GEOID, i.PERIOD, i.COUNT_SUP, i.RATE, i.RATE_M, d.POPULATION_2020 p FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CDC_INJURY_VIOLENCE_COUNTY i LEFT JOIN LIBRARY_MARTS.CORE.DIM_COUNTY d ON d.COUNTY_FIPS = i.GEOID
  WHERE i.INTENT='Drug_OD' AND i.PERIOD IN ('2019','2020','2021','2022','2023','2024') AND LENGTH(i.GEOID)=5)
SELECT (COUNT_SUP IS NULL) sup, (RATE < 0) neg, RATE_M, COUNT(*) n,
  COUNT_IF(RATE >= 0 AND p >= 20000) n20k,
  COUNT_IF(RATE >= 0 AND RATE*p/1e5 > 9.5) implied_gt9, COUNT_IF(RATE >= 0 AND RATE*p/1e5 > 20) implied_gt20,
  ROUND(AVG(IFF(RATE>=0, RATE*p/1e5, NULL)),1) avg_implied, ROUND(MEDIAN(IFF(RATE>=0, RATE*p/1e5, NULL)),1) med_implied, MIN(COUNT_SUP) mn, MAX(COUNT_SUP) mx
FROM m GROUP BY 1,2,3 ORDER BY 1,2,3
