WITH b AS (
  SELECT BUYER_DEA_NO id, ANY_VALUE(BUYER_NAME) nm, ANY_VALUE(BUYER_BUSINESS_ACTIVITY) act, ANY_VALUE(BUYER_CITY) city, ANY_VALUE(BUYER_STATE) st, ANY_VALUE(BUYER_COUNTY_FIPS) fips, SUM(DOSAGE_UNITS) du
  FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_DEA_ARCOS WHERE TRANSACTION_CODE = 'S' GROUP BY 1),
bx AS (SELECT b.*, (du > 4e7 OR nm ILIKE '%MAIL%' OR nm ILIKE 'OPTUMRX%' OR nm ILIKE 'HUMANA PHARMACY%' OR nm ILIKE 'EXPRESS SCRIPTS%'
          OR nm ILIKE 'MEDCO%' OR nm ILIKE '%CAREMARK%' OR nm ILIKE 'INJURED WORKERS%' OR nm ILIKE 'ENCLARA%' OR nm ILIKE 'PMSI%') ex FROM b)
SELECT 'excluded' k, id, nm, act, city, st, fips, du, NULL tot, NULL share FROM bx WHERE ex
UNION ALL
SELECT 'ltc_like', id, nm, act, city, st, fips, du, NULL, NULL FROM bx WHERE NOT ex AND du > 5e6 AND (nm ILIKE ANY ('%OMNICARE%','%PHARMERICA%','%LONG TERM%','%LTC%','%EXTENDED CARE%','%INSTITUTIONAL%','%CENTRAL FILL%','%HOSPICE%','%NURSING%','%SPECIALTY%','%KAISER%','%VA %','%VETERANS%','%DEPT OF%','%CORRECTION%') OR act NOT IN ('RETAIL PHARMACY','CHAIN PHARMACY'))
UNION ALL
SELECT 'county_top', id, nm, act, city, st, fips, du, tot, du/tot FROM (
  SELECT bx.*, SUM(du) OVER (PARTITION BY fips) tot, ROW_NUMBER() OVER (PARTITION BY fips ORDER BY du DESC) rn FROM bx WHERE NOT ex AND fips IS NOT NULL) WHERE rn = 1
