SELECT BUYER_STATE, BUYER_NAME ILIKE 'FOOD CITY%' starts_fc, ANY_VALUE(BUYER_NAME) ex_name, COUNT(DISTINCT BUYER_DEA_NO) stores, SUM(DOSAGE_UNITS) du,
  SUM(IFF(DRUG_NAME='OXYCODONE' AND DOSAGE_STRENGTH>=30, DOSAGE_UNITS,0)) o30
FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_DEA_ARCOS
WHERE TRANSACTION_CODE='S' AND (BUYER_NAME ILIKE '%FOOD CITY%' OR BUYER_NAME ILIKE '%K-VA-T%' OR BUYER_NAME ILIKE '%KVAT%' OR BUYER_NAME ILIKE '%K VA T%')
GROUP BY 1,2 ORDER BY 1,2;;
WITH m AS (SELECT i.GEOID, i.COUNT_SUP, i.RATE, d.POPULATION_2020 p FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CDC_INJURY_VIOLENCE_COUNTY i JOIN LIBRARY_MARTS.CORE.DIM_COUNTY d ON d.COUNTY_FIPS=i.GEOID
  WHERE i.INTENT='Drug_OD' AND i.PERIOD IN ('2019','2020','2021','2022','2023','2024') AND LENGTH(i.GEOID)=5),
l AS (SELECT GEOID, COUNT_IF(COUNT_SUP='10-50') n1050 FROM LIBRARY_RAW.LANDING.FED_CDC_INJURY_VIOLENCE_COUNTY WHERE INTENT='Drug_OD' AND PERIOD IN ('2019','2020','2021','2022','2023','2024') GROUP BY 1)
SELECT m.GEOID, SUM(IFF(COUNT_SUP IS NULL AND RATE>=0, RATE*p/1e5, 0)) modeled_sup_deaths, COUNT_IF(COUNT_SUP IS NULL AND RATE<0) sup_no_rate, ANY_VALUE(l.n1050) n1050
FROM m LEFT JOIN l ON l.GEOID=m.GEOID GROUP BY 1
