SELECT CASE WHEN BUYER_DEA_NO IN ('FF1280089','BF7000526','BF9649508','BF7399531','FF0911811','FF2853100') THEN 'cluster' WHEN BUYER_NAME ILIKE 'FOOD CITY%' THEN 'other_tn_fc' ELSE 'kvat_named' END grp,
  DOSAGE_STRENGTH, SUM(DOSAGE_UNITS) du, COUNT(DISTINCT BUYER_DEA_NO) b, ANY_VALUE(IFF(BUYER_NAME ILIKE 'K-VA-T%', BUYER_CITY, NULL)) kcity
FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_DEA_ARCOS
WHERE TRANSACTION_CODE='S' AND BUYER_STATE='TN' AND DRUG_NAME='OXYCODONE' AND (BUYER_NAME ILIKE 'FOOD CITY%' OR BUYER_NAME ILIKE 'K-VA-T%')
GROUP BY 1,2 ORDER BY 1,2
