
-- S1
SELECT table_schema, table_name, row_count FROM LIBRARY_MARTS.information_schema.tables WHERE table_name ILIKE '%INJURY_VIOLENCE_COUNTY%' OR table_name ILIKE '%DEA_ARCOS%'

-- S2
SELECT YEAR(TRANSACTION_DATE) y, COUNT(*) n, SUM(DOSAGE_UNITS) du, TYPEOF(ANY_VALUE(DOSAGE_STRENGTH::variant)) t FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_DEA_ARCOS WHERE TRANSACTION_CODE='S' GROUP BY 1 ORDER BY 1

-- S3
SELECT column_name, data_type FROM LIBRARY_MARTS.information_schema.columns WHERE table_name='HEALTH__FED_CDC_INJURY_VIOLENCE_COUNTY' OR (table_name='HEALTH__FED_DEA_ARCOS' AND column_name IN ('DOSAGE_STRENGTH','DOSAGE_UNITS','BUYER_COUNTY_FIPS'))

-- S4
SHOW TABLES LIKE '%INJURY_VIOLENCE%' IN ACCOUNT

-- S5
WITH m AS (SELECT i.GEOID, i.PERIOD, i.COUNT_SUP, i.RATE, i.RATE_M, d.POPULATION_2020 p FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CDC_INJURY_VIOLENCE_COUNTY i LEFT JOIN LIBRARY_MARTS.CORE.DIM_COUNTY d ON d.COUNTY_FIPS = i.GEOID
  WHERE i.INTENT='Drug_OD' AND i.PERIOD IN ('2019','2020','2021','2022','2023','2024') AND LENGTH(i.GEOID)=5)
SELECT (COUNT_SUP IS NULL) sup, (RATE < 0) neg, RATE_M, COUNT(*) n,
  COUNT_IF(RATE >= 0 AND p >= 20000) n20k,
  COUNT_IF(RATE >= 0 AND RATE*p/1e5 > 9.5) implied_gt9, COUNT_IF(RATE >= 0 AND RATE*p/1e5 > 20) implied_gt20,
  ROUND(AVG(IFF(RATE>=0, RATE*p/1e5, NULL)),1) avg_implied, ROUND(MEDIAN(IFF(RATE>=0, RATE*p/1e5, NULL)),1) med_implied, MIN(COUNT_SUP) mn, MAX(COUNT_SUP) mx
FROM m GROUP BY 1,2,3 ORDER BY 1,2,3

-- S6
SELECT IFF(TRY_TO_NUMBER(COUNT_SUP) IS NULL, COUNT_SUP, 'numeric') v, PERIOD, COUNT(*) n FROM LIBRARY_RAW.LANDING.FED_CDC_INJURY_VIOLENCE_COUNTY WHERE INTENT='Drug_OD' AND LENGTH(GEOID)=5 GROUP BY 1,2 ORDER BY 1,2

-- S7
WITH b AS (
  SELECT BUYER_DEA_NO id, ANY_VALUE(BUYER_NAME) nm, ANY_VALUE(BUYER_BUSINESS_ACTIVITY) act, ANY_VALUE(BUYER_CITY) city, ANY_VALUE(BUYER_STATE) st, ANY_VALUE(BUYER_COUNTY_FIPS) fips, SUM(DOSAGE_UNITS) du
  FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_DEA_ARCOS WHERE TRANSACTION_CODE = 'S' GROUP BY 1),
bx AS (SELECT b.*, (du > 4e7 OR nm ILIKE '%MAIL%' OR nm ILIKE 'OPTUMRX%' OR nm ILIKE 'HUMANA PHARMACY%' OR nm ILIKE 'EXPRESS SCRIPTS%'
          OR nm ILIKE 'MEDCO%' OR nm ILIKE '%CAREMARK%' OR nm ILIKE 'INJURED WORKERS%' OR nm ILIKE 'ENCLARA%' OR nm ILIKE 'PMSI%') ex FROM b)
SELECT 'excluded' k, id, nm, act, city, st, fips, du, NULL tot, NULL share FROM bx WHERE ex
UNION ALL
SELECT 'ltc_like', id, nm, act, city, st, fips, du, NULL, NULL FROM bx WHERE NOT ex AND du > 5e6 AND (nm ILIKE ANY ('%OMNICARE%','%PHARMERICA%','%LONG TERM%','%LTC%','%EXTENDED CARE%','%INSTITUTIONAL%','%CENTRAL FILL%','%HOSPICE%','%NURSING%','%SPECIALTY%','%KAISER%','%VA %','%VETERANS%','%DEPT OF%','%CORRECTION%') OR act NOT IN ('RETAIL PHARMACY','CHAIN PHARMACY'))
UNION ALL
SELECT 'county_top', id, nm, act, city, st, fips, du, tot, du/tot FROM (
  SELECT bx.*, SUM(du) OVER (PARTITION BY fips) tot, ROW_NUMBER() OVER (PARTITION BY fips ORDER BY du DESC) rn FROM bx WHERE NOT ex AND fips IS NOT NULL) WHERE rn = 1

-- S8
SELECT BUYER_STATE, BUYER_NAME ILIKE 'FOOD CITY%' starts_fc, ANY_VALUE(BUYER_NAME) ex_name, COUNT(DISTINCT BUYER_DEA_NO) stores, SUM(DOSAGE_UNITS) du,
  SUM(IFF(DRUG_NAME='OXYCODONE' AND DOSAGE_STRENGTH>=30, DOSAGE_UNITS,0)) o30
FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_DEA_ARCOS
WHERE TRANSACTION_CODE='S' AND (BUYER_NAME ILIKE '%FOOD CITY%' OR BUYER_NAME ILIKE '%K-VA-T%' OR BUYER_NAME ILIKE '%KVAT%' OR BUYER_NAME ILIKE '%K VA T%')
GROUP BY 1,2 ORDER BY 1,2

-- S9
WITH m AS (SELECT i.GEOID, i.COUNT_SUP, i.RATE, d.POPULATION_2020 p FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CDC_INJURY_VIOLENCE_COUNTY i JOIN LIBRARY_MARTS.CORE.DIM_COUNTY d ON d.COUNTY_FIPS=i.GEOID
  WHERE i.INTENT='Drug_OD' AND i.PERIOD IN ('2019','2020','2021','2022','2023','2024') AND LENGTH(i.GEOID)=5),
l AS (SELECT GEOID, COUNT_IF(COUNT_SUP='10-50') n1050 FROM LIBRARY_RAW.LANDING.FED_CDC_INJURY_VIOLENCE_COUNTY WHERE INTENT='Drug_OD' AND PERIOD IN ('2019','2020','2021','2022','2023','2024') GROUP BY 1)
SELECT m.GEOID, SUM(IFF(COUNT_SUP IS NULL AND RATE>=0, RATE*p/1e5, 0)) modeled_sup_deaths, COUNT_IF(COUNT_SUP IS NULL AND RATE<0) sup_no_rate, ANY_VALUE(l.n1050) n1050
FROM m LEFT JOIN l ON l.GEOID=m.GEOID GROUP BY 1

-- S10
SELECT CASE WHEN BUYER_DEA_NO IN ('FF1280089','BF7000526','BF9649508','BF7399531','FF0911811','FF2853100') THEN 'cluster' WHEN BUYER_NAME ILIKE 'FOOD CITY%' THEN 'other_tn_fc' ELSE 'kvat_named' END grp,
  DOSAGE_STRENGTH, SUM(DOSAGE_UNITS) du, COUNT(DISTINCT BUYER_DEA_NO) b, ANY_VALUE(IFF(BUYER_NAME ILIKE 'K-VA-T%', BUYER_CITY, NULL)) kcity
FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_DEA_ARCOS
WHERE TRANSACTION_CODE='S' AND BUYER_STATE='TN' AND DRUG_NAME='OXYCODONE' AND (BUYER_NAME ILIKE 'FOOD CITY%' OR BUYER_NAME ILIKE 'K-VA-T%')
GROUP BY 1,2 ORDER BY 1,2
