-- #3 A6197 per supplier: top 12 plus peer median (suppliers with a published bene count)
with s as (select SUPLR_NPI npi, max(SUPLR_PRVDR_LAST_NAME_ORG) org, max(SUPLR_PRVDR_CITY) city, max(SUPLR_PRVDR_STATE_ABRVTN) st,
  sum(try_to_number(TOT_SUPLR_SRVCS)) sv, sum(try_to_number(TOT_SUPLR_BENES)) b, sum(try_to_number(TOT_SUPLR_SRVCS)*AVG_SUPLR_MDCR_PYMT_AMT) paid
  from LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_MEDICARE_DURABLE_MEDICAL_EQUIPMENT_DEVICES_SUPPLIES_BY_SUPPL where HCPCS_CD='A6197' group by 1)
select * from (select 'top' k, npi, org, city, st, sv, b, round(paid) paid, round(paid/nullif(b,0)) paid_per_bene, round(sv/nullif(b,0)) units_per_bene from s order by paid desc limit 12)
union all
select 'peer_median_excl_two', count(*)::varchar, null, null, null, median(sv), median(b), round(median(paid)), round(median(paid/nullif(b,0))), round(median(sv/nullif(b,0))) from s where b is not null and npi not in ('1811518392','1487343505')
union all
select 'peer_top10_excl_two_median', null,null,null,null, median(sv), median(b), round(median(paid)), round(median(ppb)), round(median(upb)) from (select sv,b,paid,paid/nullif(b,0) ppb, sv/nullif(b,0) upb from s where b is not null and npi not in ('1811518392','1487343505') order by paid desc limit 10)
-- #4 every row the two suppliers have in the supplier file
select SUPLR_NPI, SUPLR_PRVDR_LAST_NAME_ORG, SUPLR_PRVDR_ST1, SUPLR_PRVDR_ST2, SUPLR_PRVDR_CITY, SUPLR_PRVDR_STATE_ABRVTN, SUPLR_PRVDR_ZIP5, SUPLR_PRVDR_SPCLTY_DESC, HCPCS_CD, left(HCPCS_DESC,50) d, SUPLR_RENTL_IND,
 TOT_SUPLR_BENES, TOT_SUPLR_CLMS, TOT_SUPLR_SRVCS, AVG_SUPLR_MDCR_PYMT_AMT, round(try_to_number(TOT_SUPLR_SRVCS)*AVG_SUPLR_MDCR_PYMT_AMT) paid
from LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_MEDICARE_DURABLE_MEDICAL_EQUIPMENT_DEVICES_SUPPLIES_BY_SUPPL where SUPLR_NPI in ('1811518392','1487343505') order by 1, paid desc
-- #5 NPPES for the two NPIs
select NPI, ENTITY_TYPE_CODE, PROVIDER_ORGANIZATION_NAME_LEGAL_BUSINESS_NAME lbn, PROVIDER_OTHER_ORGANIZATION_NAME dba, PROVIDER_FIRST_LINE_BUSINESS_PRACTICE_LOCATION_ADDRESS a1, PROVIDER_SECOND_LINE_BUSINESS_PRACTICE_LOCATION_ADDRESS a2,
 PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_CITY_NAME city, PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_STATE_NAME st, PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_POSTAL_CODE zip, PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_TELEPHONE_NUMBER tel,
 PROVIDER_FIRST_LINE_BUSINESS_MAILING_ADDRESS m1, PROVIDER_BUSINESS_MAILING_ADDRESS_CITY_NAME mcity,
 PROVIDER_ENUMERATION_DATE, LAST_UPDATE_DATE, NPI_DEACTIVATION_DATE, NPI_REACTIVATION_DATE, CERTIFICATION_DATE,
 AUTHORIZED_OFFICIAL_FIRST_NAME aof, AUTHORIZED_OFFICIAL_MIDDLE_NAME aom, AUTHORIZED_OFFICIAL_LAST_NAME aol, AUTHORIZED_OFFICIAL_TITLE_OR_POSITION aot, AUTHORIZED_OFFICIAL_TELEPHONE_NUMBER aotel,
 HEALTHCARE_PROVIDER_TAXONOMY_CODE_1 tx1, HEALTHCARE_PROVIDER_TAXONOMY_CODE_2 tx2, PROVIDER_LICENSE_NUMBER_1 lic1, PROVIDER_LICENSE_NUMBER_STATE_CODE_1 licst, OTHER_PROVIDER_IDENTIFIER_1 oid1, OTHER_PROVIDER_IDENTIFIER_TYPE_CODE_1 oidt1, IS_ORGANIZATION_SUBPART, PARENT_ORGANIZATION_LBN
from LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_NPPES where NPI in ('1811518392','1487343505')
-- #6 LEIE and SAM: the two NPIs, or the names
select 'LEIE' src, NPI, BUSINESS_NAME nm, LAST_NAME||', '||FIRST_NAME person, SPECIALTY, EXCLUSION_TYPE, EXCLUSION_DATE::varchar dt, ADDRESS, CITY, STATE from LIBRARY_MARTS.HEALTH.HEALTH__FED_HHS_OIG_LEIE
 where NPI in ('1811518392','1487343505') or BUSINESS_NAME ilike '%SUNSHINE SENIOR%' or BUSINESS_NAME ilike '%ALMAZ%'
union all
select 'SAM', NPI, ENTITY_NAME, LAST_NAME||', '||FIRST_NAME, EXCLUDING_AGENCY, EXCLUSION_TYPE, ACTIVATION_DATE::varchar, CLASSIFICATION, CITY, STATE from LIBRARY_MARTS.PROCUREMENT.PROCUREMENT__FED_SAM_EXCLUSIONS
 where NPI in ('1811518392','1487343505') or ENTITY_NAME ilike '%SUNSHINE SENIOR%' or ENTITY_NAME ilike '%ALMAZ%'
