-- #7 NPPES siblings: same authorized-official surname, same street, or same phone as either supplier
select NPI, ENTITY_TYPE_CODE, coalesce(PROVIDER_ORGANIZATION_NAME_LEGAL_BUSINESS_NAME, PROVIDER_LAST_NAME_LEGAL_NAME||', '||PROVIDER_FIRST_NAME) nm,
 PROVIDER_FIRST_LINE_BUSINESS_PRACTICE_LOCATION_ADDRESS a1, PROVIDER_SECOND_LINE_BUSINESS_PRACTICE_LOCATION_ADDRESS a2, PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_CITY_NAME city, PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_STATE_NAME st,
 PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_TELEPHONE_NUMBER tel, PROVIDER_ENUMERATION_DATE enum_dt, NPI_DEACTIVATION_DATE deact,
 AUTHORIZED_OFFICIAL_FIRST_NAME||' '||AUTHORIZED_OFFICIAL_LAST_NAME ao, AUTHORIZED_OFFICIAL_TITLE_OR_POSITION aot, AUTHORIZED_OFFICIAL_TELEPHONE_NUMBER aotel, HEALTHCARE_PROVIDER_TAXONOMY_CODE_1 tx1,
 case when AUTHORIZED_OFFICIAL_LAST_NAME ilike any ('PESSOA','TSOTSKHALASHVILI') or PROVIDER_LAST_NAME_LEGAL_NAME ilike any ('PESSOA','TSOTSKHALASHVILI') then 'name'
      when PROVIDER_FIRST_LINE_BUSINESS_PRACTICE_LOCATION_ADDRESS ilike any ('100 E LINTON BLVD%','4407 69TH ST%') or PROVIDER_FIRST_LINE_BUSINESS_MAILING_ADDRESS ilike any ('100 E LINTON BLVD%','4407 69TH ST%') then 'address'
      else 'phone' end why
from LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_NPPES
where AUTHORIZED_OFFICIAL_LAST_NAME ilike any ('PESSOA','TSOTSKHALASHVILI')
   or PROVIDER_LAST_NAME_LEGAL_NAME ilike any ('TSOTSKHALASHVILI')
   or (PROVIDER_LAST_NAME_LEGAL_NAME ilike 'PESSOA' and PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_STATE_NAME='FL')
   or PROVIDER_FIRST_LINE_BUSINESS_PRACTICE_LOCATION_ADDRESS ilike any ('100 E LINTON BLVD%','4407 69TH ST%')
   or PROVIDER_FIRST_LINE_BUSINESS_MAILING_ADDRESS ilike any ('100 E LINTON BLVD%','4407 69TH ST%')
   or PROVIDER_BUSINESS_PRACTICE_LOCATION_ADDRESS_TELEPHONE_NUMBER in ('5613323898','7185706626','9297033500')
   or AUTHORIZED_OFFICIAL_TELEPHONE_NUMBER in ('5613323898','7185706626','9297033500')
order by why, enum_dt
-- #8 PECOS enrollment rows for the two NPIs, and anything sharing their PAC id
with me as (select NPI, PECOS_ASCT_CNTL_ID pac from LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_PECOS_PROVIDER_ENROLLMENT where NPI in ('1811518392','1487343505'))
select p.NPI, p.PECOS_ASCT_CNTL_ID, p.ENRLMT_ID, p.PROVIDER_TYPE_CD, p.PROVIDER_TYPE_DESC, p.STATE_CD, p.ORG_NAME, p.LAST_NAME, p.FIRST_NAME, iff(p.NPI in (select NPI from me),'self','shares PAC') rel
from LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_PECOS_PROVIDER_ENROLLMENT p where p.NPI in (select NPI from me) or p.PECOS_ASCT_CNTL_ID in (select pac from me)
-- #9 LEIE people by the two officials' surnames; FJC criminal and civil by names; ICIJ officers
select 'LEIE' src, LAST_NAME||', '||FIRST_NAME||' '||coalesce(BUSINESS_NAME,'') nm, SPECIALTY a, EXCLUSION_TYPE b, EXCLUSION_DATE::varchar c, CITY||' '||STATE d from LIBRARY_MARTS.HEALTH.HEALTH__FED_HHS_OIG_LEIE where LAST_NAME ilike any ('PESSOA','TSOTSKHALASHVILI')
union all
select 'FJC_CRIM', DEFENDANT_NAME, DISTRICT::varchar, DOCKET::varchar, FILE_DATE::varchar, FILING_TITLE_1||'/'||FILING_OFFENSE_CODE_1 from LIBRARY_MARTS.JUSTICE.JUSTICE__FED_FJC_IDB_CRIMINAL
 where DEFENDANT_NAME ilike any ('%PESSOA%','%TSOTSKHALASHVILI%','%SUNSHINE SENIOR%','%ALMAZ MED%')
union all
select 'FJC_CIV', PLAINTIFF||' v '||DEFENDANT, DISTRICT::varchar, DOCKET::varchar, FILE_DATE::varchar, NATURE_OF_SUIT::varchar from LIBRARY_MARTS.JUSTICE.JUSTICE__FED_FJC_IDB_CIVIL
 where PLAINTIFF ilike any ('%SUNSHINE SENIOR%','%ALMAZ MED%','%TSOTSKHALASHVILI%') or DEFENDANT ilike any ('%SUNSHINE SENIOR%','%ALMAZ MED%','%TSOTSKHALASHVILI%','%PESSOA, DANA%','DANA%PESSOA%')
union all
select 'ICIJ', NAME, COUNTRIES, SOURCE_LEAK, null, null from LIBRARY_MARTS.CORPORATE_REGISTRY.CORPORATE_REGISTRY__FED_ICIJ_OFFSHORELEAKS_OFFICERS where NAME ilike any ('%TSOTSKHALASHVILI%','%DANA%PESSOA%')
-- #10 PPP (150K+ file): the two names, or their addresses
select BORROWERNAME, BORROWERADDRESS, BORROWERCITY, BORROWERSTATE, DATEAPPROVED::varchar, CURRENTAPPROVALAMOUNT, FORGIVENESSAMOUNT, NAICSCODE, JOBSREPORTED
from LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_SBA_PPP_LOANS_150K_PLUS
where BORROWERNAME ilike any ('%SUNSHINE SENIOR%','%ALMAZ MED%') or BORROWERADDRESS ilike any ('100 E LINTON BLVD%','4407 69TH ST%')
   or (BORROWERSTATE in ('FL','NY') and BORROWERNAME ilike any ('%MEDICAL SUPPL%','%MED SUPPL%','%DME%') and BORROWERCITY ilike any ('DELRAY BEACH','WOODSIDE'))
