{{ config(tags=['minimal_staging']) }}

-- GRAIN: NOT YET DETERMINED (profiler returned AMBIGUOUS -- needs manual review)
-- This is a passthrough staging view: snake_case rename only, no dedup.
-- Once grain is resolved, replace with a full staging model via generate_staging_models.py.
-- Generated by scripts/generate_minimal_staging.py

with source as (

    select * from {{ source('ripple_raw', 'FED_FEC_INDEPENDENT_EXPENDITURES') }}

),

renamed as (

    select
        cand_id as cand_id,
        cand_name as cand_name,
        spe_id as spe_id,
        spe_nam as spe_nam,
        ele_type as ele_type,
        can_office_state as can_office_state,
        can_office_dis as can_office_dis,
        can_office as can_office,
        cand_pty_aff as cand_pty_aff,
        exp_amo as exp_amo,
        exp_date as exp_date,
        agg_amo as agg_amo,
        sup_opp as sup_opp,
        pur as pur,
        pay as pay,
        file_num as file_num,
        amndt_ind as amndt_ind,
        tran_id as tran_id,
        image_num as image_num,
        receipt_dat as receipt_dat,
        fec_election_yr as fec_election_yr,
        prev_file_num as prev_file_num,
        dissem_dt as dissem_dt,
        _INGESTED_AT as _loaded_at,
        '' as _source_url

    from source

)

select * from renamed
