-- S01 DIM_STATE: confirm it is a lookup (types, territory flag, key uniqueness)
SELECT STATE_TYPE, IS_TERRITORY, COUNT(*) n, COUNT(DISTINCT STATE_FIPS) fips, COUNT(DISTINCT STATE_USPS) usps,
       LISTAGG(STATE_USPS, ',') WITHIN GROUP (ORDER BY STATE_USPS) codes
FROM LIBRARY_MARTS.CORE.DIM_STATE
GROUP BY 1,2 ORDER BY 1,2;

-- S02 UK Companies House: profile by dimension (status x active flag, category, accounts, country, origin, number prefix, load runs, empty columns)
WITH t AS (SELECT * FROM LIBRARY_MARTS.CORPORATE_REGISTRY.CORPORATE_REGISTRY__INTL_UK_COMPANIES_HOUSE)
SELECT * FROM (
  SELECT 'status' d, COMPANY_STATUS || ' | active=' || COALESCE(IS_ACTIVE::string,'null') v, COUNT(*) n, COUNT(DISTINCT COMPANY_NUMBER) k, MIN(INCORPORATION_DATE)::string a, MAX(INCORPORATION_DATE)::string b FROM t GROUP BY 1,2
  UNION ALL SELECT 'category', COMPANY_CATEGORY, COUNT(*), COUNT(DISTINCT COMPANY_NUMBER), MIN(INCORPORATION_DATE)::string, MAX(INCORPORATION_DATE)::string FROM t GROUP BY 1,2
  UNION ALL SELECT 'accounts', ACCOUNT_CATEGORY, COUNT(*), COUNT(DISTINCT COMPANY_NUMBER), MIN(INCORPORATION_DATE)::string, MAX(INCORPORATION_DATE)::string FROM t GROUP BY 1,2
  UNION ALL SELECT 'country', COUNTRY, COUNT(*), COUNT(DISTINCT COMPANY_NUMBER), MIN(INCORPORATION_DATE)::string, MAX(INCORPORATION_DATE)::string FROM t GROUP BY 1,2
  UNION ALL SELECT 'origin', COUNTRY_OF_ORIGIN, COUNT(*), COUNT(DISTINCT COMPANY_NUMBER), MIN(INCORPORATION_DATE)::string, MAX(INCORPORATION_DATE)::string FROM t GROUP BY 1,2
  UNION ALL SELECT 'prefix', IFF(COMPANY_NUMBER RLIKE '[0-9]{8}', 'numeric', LEFT(COMPANY_NUMBER,2)), COUNT(*), COUNT(DISTINCT COMPANY_NUMBER), MIN(INCORPORATION_DATE)::string, MAX(INCORPORATION_DATE)::string FROM t GROUP BY 1,2
  UNION ALL SELECT 'load', TO_CHAR(DATE(_LOADED_AT)) || ' run=' || COALESCE(_SOURCE_RUN_ID,'null'), COUNT(*), COUNT(DISTINCT COMPANY_NUMBER), MIN(_LOADED_AT)::string, MAX(_LOADED_AT)::string FROM t GROUP BY 1,2
  UNION ALL SELECT 'filled', 'dissolution_date / inc_date / post_code / mortgages_out>0', COUNT(DISSOLUTION_DATE), COUNT(INCORPORATION_DATE), COUNT(NULLIF(TRIM(POST_CODE),''))::string, COUNT_IF(NUM_MORTGAGES_OUTSTANDING > 0)::string FROM t
  UNION ALL SELECT 'default_addr', UPPER(REPLACE(POST_CODE,' ','')) || ' | ' || UPPER(ADDRESS_LINE_1), COUNT(*), COUNT(DISTINCT COMPANY_NUMBER), MIN(INCORPORATION_DATE)::string, MAX(INCORPORATION_DATE)::string FROM t WHERE UPPER(REPLACE(POST_CODE,' ','')) = 'CF148LH' OR UPPER(ADDRESS_LINE_1) LIKE '%DEFAULT ADDRESS%' GROUP BY 1,2
) QUALIFY ROW_NUMBER() OVER (PARTITION BY d ORDER BY n DESC) <= 40
ORDER BY d, n DESC;

-- S03 Ireland CRO: profile by dimension (status, type, id uniqueness, top incorporation dates for sentinels, top addresses, year-end fill, load runs)
WITH t AS (SELECT * FROM LIBRARY_MARTS.CORPORATE_REGISTRY.CORPORATE_REGISTRY__INTL_IE_CRO)
SELECT * FROM (
  SELECT 'status' d, COMPANY_STATUS v, COUNT(*) n, COUNT(DISTINCT COMPANY_ID) k, MIN(INCORPORATION_DATE)::string a, MAX(INCORPORATION_DATE)::string b FROM t GROUP BY 1,2
  UNION ALL SELECT 'type', COMPANY_TYPE, COUNT(*), COUNT(DISTINCT COMPANY_ID), MIN(INCORPORATION_DATE)::string, MAX(INCORPORATION_DATE)::string FROM t GROUP BY 1,2
  UNION ALL SELECT 'ids', 'rows | distinct COMPANY_ID | distinct KEY | distinct id+name', COUNT(*), COUNT(DISTINCT COMPANY_ID), COUNT(DISTINCT CORPORATE_REGISTRY_KEY)::string, COUNT(DISTINCT COMPANY_ID || '|' || COMPANY_NAME)::string FROM t
  UNION ALL SELECT 'incdate_top', INCORPORATION_DATE::string, COUNT(*), COUNT_IF(COMPANY_STATUS = 'Normal'), MIN(COMPANY_ID), MAX(COMPANY_ID) FROM t GROUP BY 1,2
  UNION ALL SELECT 'addr_top', UPPER(TRIM(REGISTERED_ADDRESS)), COUNT(*), COUNT_IF(COMPANY_STATUS = 'Normal'), MIN(INCORPORATION_DATE)::string, MAX(INCORPORATION_DATE)::string FROM t GROUP BY 1,2
  UNION ALL SELECT 'fye', IFF(FINANCIAL_YEAR_END IS NULL, 'null', 'set') || ' | ' || COMPANY_STATUS, COUNT(*), COUNT(DISTINCT COMPANY_ID), MIN(FINANCIAL_YEAR_END)::string, MAX(FINANCIAL_YEAR_END)::string FROM t GROUP BY 1,2
  UNION ALL SELECT 'run', COALESCE(_SOURCE_RUN_ID,'null') || ' | ' || COALESCE(DATASET_NAME,'null') || ' | ' || COALESCE(SOURCE_ID,'null') || ' | ' || TO_CHAR(DATE(_INGESTED_AT)), COUNT(*), COUNT(DISTINCT COMPANY_ID), MIN(INCORPORATION_DATE)::string, MAX(INCORPORATION_DATE)::string FROM t GROUP BY 1,2
  UNION ALL SELECT 'agecheck', 'age = 2026 - inc_year', COUNT(*), COUNT_IF(COMPANY_AGE_YEARS = 2026 - INCORPORATION_YEAR), COUNT_IF(INCORPORATION_YEAR = YEAR(INCORPORATION_DATE))::string, COUNT_IF(COMPANY_AGE_YEARS = 2025 - INCORPORATION_YEAR)::string FROM t
) QUALIFY ROW_NUMBER() OVER (PARTITION BY d ORDER BY n DESC) <= 40
ORDER BY d, n DESC;

-- S04 ICIJ entities: profile by leak (fill rates, date ranges, impossible dates, US ties)
SELECT SOURCE_LEAK, COUNT(*) n, COUNT(DISTINCT NODE_ID) nodes, COUNT(NULLIF(STATUS,'')) status_set, COUNT(NULLIF(SERVICE_PROVIDER,'')) sp_set,
       COUNT(INCORPORATION_DATE) inc_set, MIN(INCORPORATION_DATE) inc0, MAX(INCORPORATION_DATE) inc1,
       COUNT_IF(INCORPORATION_DATE > '2026-09-24' OR INCORPORATION_DATE < '1900-01-01') inc_bad,
       COUNT(STRUCK_OFF_DATE) struck_set, COUNT(INACTIVATION_DATE) inact_set, COUNT(DORM_DATE) dorm_set,
       COUNT_IF(COUNTRY_CODES ILIKE '%USA%') usa, COUNT(DISTINCT JURISDICTION) juris, MODE(JURISDICTION) top_juris,
       MODE(NULLIF(SERVICE_PROVIDER,'')) top_sp, MODE(NULLIF(STATUS,'')) top_status, MIN(VALID_UNTIL) vu0, MAX(VALID_UNTIL) vu1,
       COUNT(DISTINCT _SOURCE_RUN_ID) runs, COUNT(DISTINCT NAME) names
FROM LIBRARY_MARTS.CORPORATE_REGISTRY.CORPORATE_REGISTRY__FED_ICIJ_OFFSHORELEAKS_ENTITIES
GROUP BY 1 ORDER BY 2 DESC;

-- S05 ICIJ entities: status and service provider by leak, top jurisdictions by leak
WITH t AS (SELECT * FROM LIBRARY_MARTS.CORPORATE_REGISTRY.CORPORATE_REGISTRY__FED_ICIJ_OFFSHORELEAKS_ENTITIES)
SELECT * FROM (
  SELECT 'status' d, SOURCE_LEAK || ' | ' || COALESCE(NULLIF(STATUS,''),'blank') v, COUNT(*) n, COUNT(INCORPORATION_DATE) inc, COUNT(STRUCK_OFF_DATE) struck, COUNT(INACTIVATION_DATE) inact FROM t GROUP BY 1,2
  UNION ALL SELECT 'sp', SOURCE_LEAK || ' | ' || COALESCE(NULLIF(SERVICE_PROVIDER,''),'blank'), COUNT(*), COUNT(INCORPORATION_DATE), COUNT(STRUCK_OFF_DATE), COUNT(INACTIVATION_DATE) FROM t GROUP BY 1,2
  UNION ALL SELECT 'juris', SOURCE_LEAK || ' | ' || COALESCE(JURISDICTION,'null') || ' ' || COALESCE(JURISDICTION_DESCRIPTION,''), COUNT(*), COUNT(INCORPORATION_DATE), COUNT(STRUCK_OFF_DATE), COUNT(INACTIVATION_DATE) FROM t GROUP BY 1,2
) QUALIFY ROW_NUMBER() OVER (PARTITION BY d ORDER BY n DESC) <= 60
ORDER BY d, n DESC;

-- S06 ICIJ intermediaries: profile (leak, status, countries, id uniqueness, repeated names)
WITH t AS (SELECT * FROM LIBRARY_MARTS.CORPORATE_REGISTRY.CORPORATE_REGISTRY__FED_ICIJ_OFFSHORELEAKS_INTERMEDIARIES)
SELECT * FROM (
  SELECT 'leak' d, SOURCE_LEAK v, COUNT(*) n, COUNT(DISTINCT NODE_ID) k, COUNT(NULLIF(STATUS,''))::string a, COUNT(NULLIF(ADDRESS,''))::string b FROM t GROUP BY 1,2
  UNION ALL SELECT 'status', SOURCE_LEAK || ' | ' || COALESCE(NULLIF(STATUS,''),'blank'), COUNT(*), COUNT(DISTINCT NODE_ID), MIN(NAME), MAX(NAME) FROM t GROUP BY 1,2
  UNION ALL SELECT 'countries', COALESCE(COUNTRIES,'null'), COUNT(*), COUNT(DISTINCT NODE_ID), MIN(SOURCE_LEAK), MAX(SOURCE_LEAK) FROM t GROUP BY 1,2
  UNION ALL SELECT 'ids', 'rows | nodes | internal ids | names', COUNT(*), COUNT(DISTINCT NODE_ID), COUNT(DISTINCT INTERNAL_ID)::string, COUNT(DISTINCT NAME)::string FROM t
  UNION ALL SELECT 'dupname', NAME, COUNT(*), COUNT(DISTINCT NODE_ID), LISTAGG(DISTINCT SOURCE_LEAK, '/'), MIN(COUNTRIES) FROM t GROUP BY 1,2 HAVING COUNT(*) > 1
  UNION ALL SELECT 'run', COALESCE(_SOURCE_RUN_ID,'null') || ' | ' || COALESCE(VALID_UNTIL,''), COUNT(*), COUNT(DISTINCT NODE_ID), MIN(_INGESTED_AT)::string, MAX(_INGESTED_AT)::string FROM t GROUP BY 1,2
) QUALIFY ROW_NUMBER() OVER (PARTITION BY d ORDER BY n DESC) <= 40
ORDER BY d, n DESC;
