-- S13 UK Companies House: monthly live companies by incorporation month at the peer outliers and the big formation addresses, 2024-01 to 2026-06, with everything else as OTHER
WITH t AS (
  SELECT COMPANY_NUMBER, INCORPORATION_DATE d, ACCOUNT_CATEGORY a, COMPANY_STATUS s, UPPER(REPLACE(POST_CODE,' ','')) pc, UPPER(TRIM(ADDRESS_LINE_1)) a1
  FROM LIBRARY_MARTS.CORPORATE_REGISTRY.CORPORATE_REGISTRY__INTL_UK_COMPANIES_HOUSE
  WHERE INCORPORATION_DATE >= '2024-01-01'),
g AS (
  SELECT *, CASE WHEN pc IN ('EC2A4NA','W1W7LT','E62JA','M408WN','WC2H9JQ','EC1V2NX','N17GU','EC2A4NE','W1W5PF','IP287DE','BR34AB','CF148LH','HR53DJ','HG11ND','E173NU') THEN pc ELSE 'OTHER' END grp
  FROM t)
SELECT grp, DATE_TRUNC('month', d)::date m, COUNT(*) n, COUNT_IF(a = 'DORMANT') dormant, COUNT_IF(s <> 'Active') not_active,
       COUNT(DISTINCT a1) a1s, MODE(a1) top_a1
FROM g GROUP BY 1,2 ORDER BY 1,2;

-- S14 UK Companies House joined to the UK PSC register (current PSCs only): who controls companies formed 18 Nov 2024-30 Jun 2025 vs 18 Nov 2025-30 Jun 2026, by address group and main nationality
WITH c AS (
  SELECT COMPANY_NUMBER, IFF(INCORPORATION_DATE >= '2025-11-18', 'post', 'prior') w,
         CASE WHEN UPPER(REPLACE(POST_CODE,' ','')) IN ('EC2A4NA','W1W7LT','E62JA','M408WN','WC2H9JQ','EC1V2NX','BR34AB','CF148LH') THEN UPPER(REPLACE(POST_CODE,' ','')) ELSE 'OTHER' END grp
  FROM LIBRARY_MARTS.CORPORATE_REGISTRY.CORPORATE_REGISTRY__INTL_UK_COMPANIES_HOUSE
  WHERE INCORPORATION_DATE BETWEEN '2024-11-18' AND '2025-06-30' OR INCORPORATION_DATE BETWEEN '2025-11-18' AND '2026-06-30'),
p AS (
  SELECT COMPANY_NUMBER, KIND, UPPER(TRIM(NATIONALITY)) nat, UPPER(TRIM(COUNTRY_OF_RESIDENCE)) res, NOTIFIED_ON
  FROM LIBRARY_MARTS.CORPORATE_REGISTRY.CORPORATE_REGISTRY__UK_COMPANIES_HOUSE_PSC
  WHERE CEASED_ON IS NULL AND COMPANY_NUMBER IN (SELECT COMPANY_NUMBER FROM c)),
pp AS (
  SELECT COMPANY_NUMBER, COUNT(*) npsc, MAX(IFF(KIND ILIKE 'individual%', 1, 0)) ind, MODE(nat) nat,
         MAX(IFF(res IN ('UNITED KINGDOM','ENGLAND','SCOTLAND','WALES','NORTHERN IRELAND','UK','GREAT BRITAIN','U.K.','BRITAIN'), 1, 0)) res_uk,
         MAX(NOTIFIED_ON) last_notified
  FROM p GROUP BY 1)
SELECT grp, w, COALESCE(nat, IFF(pp.COMPANY_NUMBER IS NULL, '(no current psc)', '(no nationality)')) nat_g, COUNT(*) n, COUNT(pp.COMPANY_NUMBER) with_psc,
       SUM(ind) with_ind, SUM(res_uk) any_uk_res, MAX(last_notified) max_notified
FROM c LEFT JOIN pp USING (COMPANY_NUMBER)
GROUP BY GROUPING SETS ((grp, w, nat_g), (grp, w))
QUALIFY ROW_NUMBER() OVER (PARTITION BY grp, w ORDER BY n DESC) <= 13
ORDER BY grp, w, n DESC;

-- S15 UK Companies House: live companies by incorporation day 3 Nov-7 Dec 2025 and the same days of 2024; plus the top postcodes in the weeks of 19 and 26 Jan 2026
WITH t AS (
  SELECT INCORPORATION_DATE d, UPPER(REPLACE(POST_CODE,' ','')) pc
  FROM LIBRARY_MARTS.CORPORATE_REGISTRY.CORPORATE_REGISTRY__INTL_UK_COMPANIES_HOUSE
  WHERE INCORPORATION_DATE BETWEEN '2024-11-01' AND '2024-12-08' OR INCORPORATION_DATE BETWEEN '2025-11-01' AND '2025-12-08' OR INCORPORATION_DATE BETWEEN '2026-01-19' AND '2026-02-01')
SELECT * FROM (
  SELECT 'day' k, d::string p, 'ALL' pc, COUNT(*) n, DAYNAME(d) dow FROM t WHERE d < '2026-01-01' GROUP BY 1,2,3,5
  UNION ALL
  SELECT 'week', DATE_TRUNC('week', d)::string, pc, COUNT(*), NULL FROM t WHERE d >= '2026-01-19' GROUP BY 1,2,3
) QUALIFY k = 'day' OR ROW_NUMBER() OVER (PARTITION BY k, p ORDER BY n DESC) <= 15
ORDER BY k, p, n DESC;

-- S16 ICIJ entities, Panama Papers (Mossack Fonseca): formations by month and jurisdiction 1999-2007, plus company type in Apr-Jun 2004 vs Apr-Jun 2005
WITH t AS (
  SELECT JURISDICTION j, COMPANY_TYPE ty, INCORPORATION_DATE i
  FROM LIBRARY_MARTS.CORPORATE_REGISTRY.CORPORATE_REGISTRY__FED_ICIJ_OFFSHORELEAKS_ENTITIES
  WHERE SOURCE_LEAK = 'Panama Papers' AND INCORPORATION_DATE BETWEEN '1999-01-01' AND '2007-12-31')
SELECT 'month' k, YEAR(i) * 100 + MONTH(i) p, CASE WHEN j IN ('BVI','PMA','BAH','NIUE','SEY','SAM') THEN j ELSE 'OTHER' END g, COUNT(*) n FROM t GROUP BY 1,2,3
UNION ALL
SELECT 'type_q2', YEAR(i), COALESCE(NULLIF(ty,''), 'blank') || ' | ' || j, COUNT(*) FROM t WHERE MONTH(i) BETWEEN 4 AND 6 AND YEAR(i) IN (2004, 2005) GROUP BY 1,2,3
ORDER BY 1, 2, 3;
