-- S17 UK Companies House x PSC: every postcode with 400+ live companies formed in the two windows (18 Nov 2024-30 Jun 2025 vs 18 Nov 2025-30 Jun 2026), with growth and the share controlled by someone living in the UK (peer table)
WITH c AS (
  SELECT COMPANY_NUMBER, UPPER(REPLACE(POST_CODE,' ','')) pc, IFF(INCORPORATION_DATE >= '2025-11-18', 'post', 'prior') w
  FROM LIBRARY_MARTS.CORPORATE_REGISTRY.CORPORATE_REGISTRY__INTL_UK_COMPANIES_HOUSE
  WHERE (INCORPORATION_DATE BETWEEN '2024-11-18' AND '2025-06-30' OR INCORPORATION_DATE BETWEEN '2025-11-18' AND '2026-06-30')
    AND NULLIF(TRIM(POST_CODE),'') IS NOT NULL),
big AS (SELECT pc FROM c GROUP BY 1 HAVING COUNT(*) >= 400),
cb AS (SELECT c.* FROM c JOIN big USING (pc)),
p AS (
  SELECT COMPANY_NUMBER,
         MAX(IFF(UPPER(COUNTRY_OF_RESIDENCE) IN ('UNITED KINGDOM','ENGLAND','SCOTLAND','WALES','NORTHERN IRELAND','UK','GREAT BRITAIN','U.K.','BRITAIN')
                 OR UPPER(COUNTRY_OF_RESIDENCE) LIKE '%ENGLAND%' OR UPPER(COUNTRY_OF_RESIDENCE) LIKE '%UNITED KINGDOM%', 1, 0)) res_uk,
         MODE(UPPER(TRIM(NATIONALITY))) nat
  FROM LIBRARY_MARTS.CORPORATE_REGISTRY.CORPORATE_REGISTRY__UK_COMPANIES_HOUSE_PSC
  WHERE CEASED_ON IS NULL AND COMPANY_NUMBER IN (SELECT COMPANY_NUMBER FROM cb)
  GROUP BY 1),
j AS (SELECT cb.pc, cb.w, cb.COMPANY_NUMBER, p.res_uk, p.nat FROM cb LEFT JOIN p USING (COMPANY_NUMBER)),
nt AS (SELECT pc, nat, COUNT(*) k FROM j WHERE w = 'post' AND nat IS NOT NULL GROUP BY 1,2),
ntop AS (SELECT pc, MAX_BY(nat, k) top_nat, MAX(k) top_nat_n FROM nt GROUP BY 1)
SELECT j.pc, COUNT_IF(w = 'prior') prior_n, COUNT_IF(w = 'post') post_n,
       COUNT_IF(w = 'prior' AND res_uk = 1) prior_ukres, COUNT_IF(w = 'post' AND res_uk = 1) post_ukres,
       COUNT_IF(w = 'post' AND res_uk IS NOT NULL) post_with_psc, ANY_VALUE(ntop.top_nat) post_top_nat, ANY_VALUE(ntop.top_nat_n) post_top_nat_n
FROM j LEFT JOIN ntop USING (pc)
GROUP BY 1 ORDER BY post_n DESC;

-- S18 UK PSC concentration: the controlling persons behind 2025-26 companies at M40 8WN, E6 2JA and BR3 4AB (current PSCs, name + birth year + nationality + residence)
WITH c AS (
  SELECT COMPANY_NUMBER, INCORPORATION_DATE d, UPPER(REPLACE(POST_CODE,' ','')) pc, ACCOUNT_CATEGORY a, COMPANY_STATUS s
  FROM LIBRARY_MARTS.CORPORATE_REGISTRY.CORPORATE_REGISTRY__INTL_UK_COMPANIES_HOUSE
  WHERE UPPER(REPLACE(POST_CODE,' ','')) IN ('M408WN','E62JA','BR34AB') AND INCORPORATION_DATE >= '2025-01-01'),
p AS (
  SELECT q.COMPANY_NUMBER, UPPER(TRIM(q.NAME)) nm, q.DOB_YEAR, UPPER(TRIM(q.NATIONALITY)) nat, UPPER(TRIM(q.COUNTRY_OF_RESIDENCE)) res
  FROM LIBRARY_MARTS.CORPORATE_REGISTRY.CORPORATE_REGISTRY__UK_COMPANIES_HOUSE_PSC q
  WHERE q.CEASED_ON IS NULL AND q.COMPANY_NUMBER IN (SELECT COMPANY_NUMBER FROM c)),
tot AS (SELECT pc, COUNT(*) cos, COUNT_IF(d >= '2025-11-18') post_cos FROM c GROUP BY 1),
g AS (
  SELECT c.pc, p.nm, p.DOB_YEAR, p.nat, p.res, COUNT(DISTINCT c.COMPANY_NUMBER) cos, COUNT(DISTINCT IFF(c.d >= '2025-11-18', c.COMPANY_NUMBER, NULL)) post_cos,
         MIN(c.d) d0, MAX(c.d) d1, COUNT_IF(c.s <> 'Active') not_active
  FROM c JOIN p USING (COMPANY_NUMBER) GROUP BY 1,2,3,4,5)
SELECT g.*, tot.cos pc_cos, tot.post_cos pc_post_cos FROM g JOIN tot USING (pc)
QUALIFY ROW_NUMBER() OVER (PARTITION BY g.pc ORDER BY g.cos DESC) <= 15
ORDER BY g.pc, g.cos DESC;

-- S19 ICIJ Panama Papers: who drove the Apr-Jun 2005 formation spike? Entities formed Apr-Jun 2004 vs Apr-Jun 2005, by intermediary country and intermediary (via the relationships table), and by the entity's own linked countries
WITH e AS (
  SELECT NODE_ID, YEAR(INCORPORATION_DATE) y, COUNTRY_CODES
  FROM LIBRARY_MARTS.CORPORATE_REGISTRY.CORPORATE_REGISTRY__FED_ICIJ_OFFSHORELEAKS_ENTITIES
  WHERE SOURCE_LEAK = 'Panama Papers' AND MONTH(INCORPORATION_DATE) BETWEEN 4 AND 6 AND YEAR(INCORPORATION_DATE) IN (2004, 2005)),
r AS (
  SELECT NODE_ID_START s, NODE_ID_END t
  FROM LIBRARY_MARTS.CORPORATE_REGISTRY.CORPORATE_REGISTRY__FED_ICIJ_OFFSHORELEAKS_RELATIONSHIPS
  WHERE REL_TYPE ILIKE 'intermediary%' AND NODE_ID_END IN (SELECT NODE_ID FROM e)),
x AS (
  SELECT e.y, e.NODE_ID, i.NAME, i.COUNTRIES
  FROM e LEFT JOIN r ON r.t = e.NODE_ID
  LEFT JOIN LIBRARY_MARTS.CORPORATE_REGISTRY.CORPORATE_REGISTRY__FED_ICIJ_OFFSHORELEAKS_INTERMEDIARIES i ON i.NODE_ID = r.s)
SELECT * FROM (
  SELECT 'total' k, 'entities | with an intermediary link' v, COUNT(DISTINCT IFF(y = 2004, NODE_ID, NULL)) q2_2004, COUNT(DISTINCT IFF(y = 2005, NODE_ID, NULL)) q2_2005,
         COUNT(DISTINCT IFF(y = 2004 AND NAME IS NOT NULL, NODE_ID, NULL)) linked_2004, COUNT(DISTINCT IFF(y = 2005 AND NAME IS NOT NULL, NODE_ID, NULL)) linked_2005 FROM x
  UNION ALL
  SELECT 'int_country', COALESCE(COUNTRIES, '(no intermediary)'), COUNT(DISTINCT IFF(y = 2004, NODE_ID, NULL)), COUNT(DISTINCT IFF(y = 2005, NODE_ID, NULL)), NULL, NULL FROM x GROUP BY 1,2
  UNION ALL
  SELECT 'intermediary', COALESCE(NAME, '(none)') || ' | ' || COALESCE(COUNTRIES, ''), COUNT(DISTINCT IFF(y = 2004, NODE_ID, NULL)), COUNT(DISTINCT IFF(y = 2005, NODE_ID, NULL)), NULL, NULL FROM x GROUP BY 1,2
  UNION ALL
  SELECT 'entity_cc', COALESCE(COUNTRY_CODES, '(none)'), COUNT_IF(y = 2004), COUNT_IF(y = 2005), NULL, NULL FROM e GROUP BY 1,2
) QUALIFY ROW_NUMBER() OVER (PARTITION BY k ORDER BY q2_2005 DESC) <= 40
ORDER BY k, q2_2005 DESC;
