-- S20 UK PSC x Companies House: every company where a PSC named ELTANTAWY/ELTANTAVY appears (current or ceased), by incorporation month and postcode; ceased and other-PSC counts test the shelf-company-seller explanation
WITH p AS (
  SELECT COMPANY_NUMBER, UPPER(TRIM(NAME)) nm, DOB_YEAR, NOTIFIED_ON, CEASED_ON
  FROM LIBRARY_MARTS.CORPORATE_REGISTRY.CORPORATE_REGISTRY__UK_COMPANIES_HOUSE_PSC
  WHERE UPPER(NAME) LIKE '%ELTANTAW%' OR UPPER(NAME) LIKE '%ELTANTAV%'),
pc AS (SELECT COMPANY_NUMBER, MIN(NOTIFIED_ON) first_notified, MAX(IFF(CEASED_ON IS NULL, 1, 0)) still_psc, MAX(IFF(CEASED_ON IS NOT NULL, 1, 0)) any_ceased FROM p GROUP BY 1),
o AS (
  SELECT COMPANY_NUMBER, COUNT(*) other_now
  FROM LIBRARY_MARTS.CORPORATE_REGISTRY.CORPORATE_REGISTRY__UK_COMPANIES_HOUSE_PSC
  WHERE CEASED_ON IS NULL AND COMPANY_NUMBER IN (SELECT COMPANY_NUMBER FROM pc)
    AND NOT (UPPER(NAME) LIKE '%ELTANTAW%' OR UPPER(NAME) LIKE '%ELTANTAV%')
  GROUP BY 1),
c AS (
  SELECT COMPANY_NUMBER, COMPANY_NAME, INCORPORATION_DATE, UPPER(REPLACE(POST_CODE,' ','')) cpc, COMPANY_STATUS, ACCOUNT_CATEGORY, COMPANY_CATEGORY
  FROM LIBRARY_MARTS.CORPORATE_REGISTRY.CORPORATE_REGISTRY__INTL_UK_COMPANIES_HOUSE
  WHERE COMPANY_NUMBER IN (SELECT COMPANY_NUMBER FROM pc))
SELECT DATE_TRUNC('month', COALESCE(c.INCORPORATION_DATE, pc.first_notified))::date m, COALESCE(c.cpc, '(not on live register)') postcode,
       COUNT(*) cos, SUM(pc.still_psc) still_psc, SUM(pc.any_ceased) any_ceased, COUNT(o.COMPANY_NUMBER) with_other_psc_now,
       COUNT_IF(c.COMPANY_STATUS <> 'Active') not_active, COUNT_IF(c.ACCOUNT_CATEGORY = 'NO ACCOUNTS FILED') no_accounts,
       COUNT_IF(c.ACCOUNT_CATEGORY = 'DORMANT') dormant, MIN(c.COMPANY_NAME) name_a, MAX(c.COMPANY_NAME) name_z, MODE(c.COMPANY_CATEGORY) category
FROM pc LEFT JOIN c USING (COMPANY_NUMBER) LEFT JOIN o USING (COMPANY_NUMBER)
GROUP BY 1,2 ORDER BY 1,2;

-- S21 UK PSC peer ranking: the persons (name + birth year) behind the most companies formed 18 Nov 2025-30 Jun 2026, with their top postcode and residence
WITH c AS (
  SELECT COMPANY_NUMBER, UPPER(REPLACE(POST_CODE,' ','')) pc
  FROM LIBRARY_MARTS.CORPORATE_REGISTRY.CORPORATE_REGISTRY__INTL_UK_COMPANIES_HOUSE
  WHERE INCORPORATION_DATE BETWEEN '2025-11-18' AND '2026-06-30'),
p AS (
  SELECT COMPANY_NUMBER, REGEXP_REPLACE(UPPER(TRIM(NAME)), '^(MR|MRS|MS|MISS|DR) ', '') nm, DOB_YEAR, UPPER(TRIM(NATIONALITY)) nat, UPPER(TRIM(COUNTRY_OF_RESIDENCE)) res
  FROM LIBRARY_MARTS.CORPORATE_REGISTRY.CORPORATE_REGISTRY__UK_COMPANIES_HOUSE_PSC
  WHERE CEASED_ON IS NULL AND KIND ILIKE 'individual%' AND COMPANY_NUMBER IN (SELECT COMPANY_NUMBER FROM c))
SELECT p.nm, p.DOB_YEAR, COUNT(DISTINCT p.COMPANY_NUMBER) cos, MODE(c.pc) top_pc, COUNT(DISTINCT c.pc) postcodes, MODE(p.nat) nat, MODE(p.res) res
FROM p JOIN c USING (COMPANY_NUMBER)
GROUP BY 1,2 ORDER BY cos DESC LIMIT 30;
