-- SCDB: the 5th Circuit's argued cases, terms 2015-2024, one row per case, for eyeballing and to see who petitioned
select distinct TERM, CASE_ID, CASE_NAME, DECISION_TYPE_CODE, PETITIONER_CODE, RESPONDENT_CODE, PARTY_WINNING,
  CASE_DISPOSITION_CODE, LC_DISPOSITION_DIRECTION_CODE, DECISION_DIRECTION_CODE, MAJ_VOTES, MIN_VOTES
from LIBRARY_MARTS.JUSTICE.JUSTICE__FED_SCDB
where CASE_SOURCE_CODE = 25 and TERM >= 2015 and DECISION_TYPE_CODE in (1,6,7)
order by TERM, CASE_ID
