-- S01 GEM hazard: whole table, confirm it is a lookup
SELECT * FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__INTL_GEM_HAZARD ORDER BY 1

-- S02 GHGRP facility: year x reporting status, facilities, duplicate facility-years, FRS fill, suppliers
SELECT REPORTING_YEAR, REPORTING_STATUS, COUNT(*) n, COUNT(DISTINCT FACILITY_ID) fac,
       COUNT_IF(FRS_ID IS NULL) frs_null, COUNT(DISTINCT FRS_ID) frs_ids,
       COUNT_IF(FACILITY_TYPES ILIKE '%supplier%') supplier_rows,
       COUNT_IF(NULLIF(TRIM(PARENT_COMPANY),'') IS NULL) parent_blank
FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_GHGRP_FACILITY
GROUP BY 1,2 ORDER BY 1,2

-- S03 GHGRP facility: facility types and status over all years, with the codes that say why they stopped
SELECT FACILITY_TYPES, REPORTING_STATUS, COUNT(*) n, COUNT(DISTINCT FACILITY_ID) fac,
       MIN(REPORTING_YEAR) y0, MAX(REPORTING_YEAR) y1, COUNT_IF(CEMS_USED = 'Y') cems_y,
       COUNT(DISTINCT FACILITY_ID, REPORTING_YEAR) fac_years
FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_GHGRP_FACILITY
GROUP BY 1,2 ORDER BY n DESC

-- S04 GHGRP emission: year x gas, rows, facilities, duplicate keys, CO2e sum
SELECT REPORTING_YEAR, GAS_ID, COUNT(*) n, COUNT(DISTINCT FACILITY_ID) fac,
       COUNT(DISTINCT FACILITY_ID, SECTOR_ID, SUBSECTOR_ID) keys_fss,
       COUNT_IF(CO2E_EMISSION IS NULL) co2e_null, SUM(CO2E_EMISSION) co2e, MAX(CO2E_EMISSION) co2e_max,
       COUNT(DISTINCT SECTOR_ID) sectors, COUNT(DISTINCT _SOURCE_RUN_ID) runs
FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_GHGRP_EMISSION
GROUP BY 1,2 ORDER BY 1,2

-- S05 Superfund boundaries: units x NPL status x program, sites, area, dates, federal flag
SELECT GIS_AREA_UNITS, NPL_STATUS_CODE, EPA_PROGRAM, COUNT(*) n, COUNT(DISTINCT EPA_ID) sites,
       COUNT_IF(FEDERAL_FACILITY_CODE IN ('Y','Yes')) fed, SUM(GIS_AREA) area, MEDIAN(GIS_AREA) med_area, MAX(GIS_AREA) max_area,
       COUNT_IF(GIS_AREA = 0 OR GIS_AREA IS NULL) area0, MIN(LAST_CHANGE_AT) lc0, MAX(LAST_CHANGE_AT) lc1,
       MIN(ORIGINALLY_CREATED_AT) oc0, MAX(ORIGINALLY_CREATED_AT) oc1, COUNT(DISTINCT SITE_FEATURE_TYPE) ftypes
FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_SUPERFUND_SITE_BOUNDARIES
GROUP BY 1,2,3 ORDER BY n DESC

-- S06 USGS minerals: by development status, fill of the columns said to be empty, ID uniqueness, coordinates, newest years
SELECT DEV_STAT, COUNT(*) n, COUNT(DISTINCT DEP_ID) dep_ids, COUNT(DISTINCT MRDS_ID) mrds_ids, COUNT_IF(MRDS_ID IS NOT NULL) mrds_filled,
       COUNT_IF(NULLIF(TRIM(DATA_SOURCE_NOTES::STRING),'') IS NOT NULL) notes_filled, COUNT_IF(COMMODITY IS NOT NULL) commodity_filled,
       COUNT_IF(PRODUCTION_QUANTITY IS NOT NULL) prod_filled, COUNT_IF(NULLIF(TRIM(STATE::STRING),'') IS NOT NULL) state_filled,
       COUNT_IF(NULLIF(TRIM(FIPS::STRING),'') IS NOT NULL) fips_filled, COUNT_IF(NULLIF(TRIM(YEAR::STRING),'') IS NOT NULL) year_filled,
       COUNT_IF(LATITUDE IS NULL OR LATITUDE::STRING IN ('0','0.0','None')) lat_bad,
       MAX(TRY_TO_NUMBER(YR_LST_PRD::STRING)) max_last_prod, MAX(TRY_TO_NUMBER(DISC_YR::STRING)) max_disc,
       MAX(TRY_TO_NUMBER(YR_FST_PRD::STRING)) max_first_prod, COUNT(DISTINCT _SOURCE_RUN_ID) runs
FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_USGS_MINERALS
GROUP BY 1 ORDER BY n DESC

-- S07 FRS facilities: by create year, flags, federal fields, tribal, coordinates, site types
SELECT YEAR(CREATE_DATE) cy, COUNT(*) n, COUNT_IF(IS_FEDERAL_FACILITY) is_fed_true, COUNT_IF(IS_ON_TRIBAL_LAND) is_trib_true,
       COUNT_IF(NULLIF(TRIM(FEDERAL_FACILITY_CODE),'') IS NOT NULL) fed_code_filled, COUNT_IF(NULLIF(TRIM(FEDERAL_AGENCY),'') IS NOT NULL) fed_agency_filled,
       COUNT_IF(TRIBAL_LAND_CODE = 'Yes') trib_yes, COUNT_IF(LATITUDE IS NULL) lat_null,
       COUNT_IF(PROGRAM_SYSTEM_ACRONYMS ILIKE '%SEMS:%') sems, COUNT_IF(PROGRAM_SYSTEM_ACRONYMS ILIKE '%E-GGRT:%') ggrt,
       COUNT_IF(SITE_TYPE = 'BROWNFIELDS SITE') brownfields, MIN(UPDATE_DATE) u0, MAX(UPDATE_DATE) u1
FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_FRS_FACILITIES
GROUP BY 1 ORDER BY 1

-- S08 Combined air emissions: program x year, rows, facilities, GHG rows
SELECT PGM_SYS_ACRNM, REPORTING_YEAR, COUNT(*) n, COUNT(DISTINCT REGISTRY_ID) regs, COUNT_IF(NEI_TYPE = 'GHG') ghg_rows,
       COUNT(DISTINCT IFF(NEI_TYPE = 'GHG', POLLUTANT_NAME, NULL)) ghg_pollutants, ANY_VALUE(IFF(NEI_TYPE='GHG', POLLUTANT_NAME || ' / ' || UNIT_OF_MEASURE, NULL)) ghg_example
FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_AIR_EMISSIONS_POLL_RPT_COMBINED_EMISSIONS
GROUP BY 1,2 ORDER BY 1,2
