-- S11 GHGRP facility: slim extract of every facility-year (136K rows) for local cohort math
SELECT FACILITY_ID, REPORTING_YEAR yr, NULLIF(TRIM(REPORTING_STATUS),'') status, NULLIF(TRIM(TO_VARCHAR(FRS_ID)),'') frs,
       FACILITY_NAME, PARENT_COMPANY, CITY, STATE, ZIP, COUNTY_FIPS, NAICS_CODE, FACILITY_TYPES, REPORTED_SUBPARTS, REPORTED_INDUSTRY_TYPES
FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_GHGRP_FACILITY

-- S12 GHGRP emission: direct emissions per facility-year (drops supplier sectors 9-13,16,17 and biogenic gas 8), plus supplier and biogenic side totals
SELECT FACILITY_ID, REPORTING_YEAR yr,
       SUM(IFF(SECTOR_ID NOT IN (9,10,11,12,13,16,17) AND COALESCE(GAS_ID,0) <> 8, CO2E_EMISSION, 0)) direct_t,
       SUM(IFF(SECTOR_ID IN (9,10,11,12,13,16,17), CO2E_EMISSION, 0)) supplier_t,
       SUM(IFF(GAS_ID = 8, CO2E_EMISSION, 0)) biogenic_t,
       LISTAGG(DISTINCT SECTOR_ID, ',') WITHIN GROUP (ORDER BY SECTOR_ID) sectors, COUNT(*) n
FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_GHGRP_EMISSION
GROUP BY 1,2

-- S13 Combined air emissions for every GHGRP registry ID: per program and year, rows and CO2 amount (the other programs that show a plant still running)
WITH ids AS (
  SELECT DISTINCT TO_VARCHAR(FRS_ID) frs FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_GHGRP_FACILITY WHERE FRS_ID IS NOT NULL
)
SELECT TO_VARCHAR(c.REGISTRY_ID) reg, c.PGM_SYS_ACRNM pgm, c.REPORTING_YEAR::INT yr, COUNT(*) n,
       SUM(IFF(c.POLLUTANT_NAME ILIKE '%carbon dioxide%', c.ANNUAL_EMISSION, NULL)) co2_amt,
       ANY_VALUE(IFF(c.POLLUTANT_NAME ILIKE '%carbon dioxide%', c.UNIT_OF_MEASURE, NULL)) co2_unit,
       ANY_VALUE(IFF(c.POLLUTANT_NAME ILIKE '%carbon dioxide%', c.POLLUTANT_NAME, NULL)) co2_name
FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_AIR_EMISSIONS_POLL_RPT_COMBINED_EMISSIONS c
JOIN ids ON ids.frs = TO_VARCHAR(c.REGISTRY_ID)
GROUP BY 1,2,3

-- S14 ECHO for every GHGRP registry ID: active flag, compliance, inspections, enforcement, penalties, program flags
WITH ids AS (
  SELECT DISTINCT TO_VARCHAR(FRS_ID) frs FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_GHGRP_FACILITY WHERE FRS_ID IS NOT NULL
)
SELECT TO_VARCHAR(e.FRS_ID) frs, COUNT(*) echo_rows, ANY_VALUE(e.FACILITY_NAME) echo_name, MAX(e.IS_ACTIVE::INT) is_active,
       ANY_VALUE(e.COMPLIANCE_STATUS) compliance, MAX(e.QUARTERS_WITH_NONCOMPLIANCE) qnc, MAX(e.TOTAL_INSPECTION_COUNT) insp,
       MAX(e.DATE_LAST_INSPECTION) last_insp, MAX(e.FORMAL_ACTION_COUNT) formal, MAX(e.DATE_LAST_FORMAL_ACTION) last_formal,
       MAX(e.TOTAL_PENALTIES) penalties, MAX(e.HAS_AIR_PROGRAM::INT) air, MAX(e.HAS_GREENHOUSE_GAS_PROGRAM::INT) ghg_prog,
       MAX(e.HAS_TOXIC_RELEASE_PROGRAM::INT) tri_prog, MAX(e.IS_MAJOR_FACILITY::INT) major, MAX(e.PCT_MINORITY) pct_minority
FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ECHO e
JOIN ids ON ids.frs = TO_VARCHAR(e.FRS_ID)
GROUP BY 1
