-- S21 The 17 flagged landfills through the FRS hub: FRS programs, ICIS-Air permit status, air violations, inspections and formal actions, before vs after they went quiet
WITH ids AS (
  SELECT column1 reg FROM VALUES ('110012168652'),('110006297499'),('110012694012'),('110009076338'),('110043790412'),('110071161064'),('110031168983'),('110040514397'),('110002524803'),('110071160106'),('110071159935'),('110070931010'),('110043786105'),('110054620665'),('110060832407'),('110043972779'),('110071161639')
), fr AS (
  SELECT TO_VARCHAR(REGISTRY_ID) reg, ANY_VALUE(FACILITY_NAME) frs_name, ANY_VALUE(SITE_TYPE) site_type, ANY_VALUE(LEFT(PROGRAM_SYSTEM_ACRONYMS, 250)) progs, MAX(UPDATE_DATE) frs_upd
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_FRS_FACILITIES WHERE TO_VARCHAR(REGISTRY_ID) IN (SELECT reg FROM ids) GROUP BY 1
), a AS (
  SELECT TO_VARCHAR(REGISTRY_ID) reg, PGM_SYS_ID, AIR_OPERATING_STATUS_DESC op_status, AIR_POLLUTANT_CLASS_DESC air_class, CURRENT_HPV
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_FACILITIES WHERE TO_VARCHAR(REGISTRY_ID) IN (SELECT reg FROM ids)
), v AS (
  SELECT PGM_SYS_ID, COUNT(*) viol, MIN(COALESCE(TRY_TO_DATE(EARLIEST_FRV_DETERM_DATE::STRING), TRY_TO_DATE(EARLIEST_FRV_DETERM_DATE::STRING,'MM/DD/YYYY'))) first_viol,
         MAX(COALESCE(TRY_TO_DATE(EARLIEST_FRV_DETERM_DATE::STRING), TRY_TO_DATE(EARLIEST_FRV_DETERM_DATE::STRING,'MM/DD/YYYY'))) last_viol,
         LEFT(LISTAGG(DISTINCT POLLUTANT_DESCS, ' | '), 150) polls, LEFT(LISTAGG(DISTINCT AGENCY_TYPE_DESC, ' | '), 60) agency
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_VIOLATION_HISTORY WHERE PGM_SYS_ID IN (SELECT PGM_SYS_ID FROM a) GROUP BY 1
), i AS (
  SELECT PGM_SYS_ID, COUNT(*) evals, MAX(ACTUAL_END_DATE) last_eval
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_FCES_PCES WHERE PGM_SYS_ID IN (SELECT PGM_SYS_ID FROM a) GROUP BY 1
), fa AS (
  SELECT PGM_SYS_ID, COUNT(*) fa_n, MAX(SETTLEMENT_ENTERED_DATE) last_fa, SUM(TRY_TO_NUMBER(PENALTY_AMOUNT::STRING)) fa_pen
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_FORMAL_ACTIONS WHERE PGM_SYS_ID IN (SELECT PGM_SYS_ID FROM a) GROUP BY 1
)
SELECT ids.reg, fr.frs_name, fr.site_type, fr.frs_upd, a.PGM_SYS_ID, a.op_status, a.air_class, a.CURRENT_HPV,
       v.viol, v.first_viol, v.last_viol, v.agency, v.polls, i.evals, i.last_eval, fa.fa_n, fa.last_fa, fa.fa_pen, fr.progs
FROM ids LEFT JOIN fr ON fr.reg = ids.reg LEFT JOIN a ON a.reg = ids.reg
LEFT JOIN v ON v.PGM_SYS_ID = a.PGM_SYS_ID LEFT JOIN i ON i.PGM_SYS_ID = a.PGM_SYS_ID LEFT JOIN fa ON fa.PGM_SYS_ID = a.PGM_SYS_ID
ORDER BY 1
