{{ config(materialized='table', schema='HISTORY') }}

-- Source: Records About Japanese Americans Relocated During World War II (NARA AAD Series 623) (36 rows)
-- Generated by gen_mart_models.py

with source as (
    select * from {{ source('ripple_raw', 'FED_NARA_WRA_AAD') }}
)

select
    PERSON_NAME as person_name,
    "DATE" as date,
    CAMP_LOCATION as camp_location,
    FIPS as fips,
    GEO as geo,
    SERIES_ID as series_id,
    RECORD_ID as record_id,
    AGE as age,
    SEX as sex,
    CITIZENSHIP_STATUS as citizenship_status,
    FAMILY_NUMBER as family_number,
    NOTES_FIELD as notes_field
from source
