{{ config(tags=['spine_generated']) }}

-- GRAIN: one row per place (GEOM+FISCAL_YEAR unique)
-- SPINE_ENTITY: place  (natural_key: SHAPE__LENGTH, FISCAL_YEAR)
-- Generated by scripts/generate_staging_models.py from SOURCE_REGISTRY -- deterministic,
-- no LLM.
-- CASTS: 10 of 30 columns, from landing_column_profile_2026-09-19.tsv. A column is cast only
-- when every filled value in the sample parsed. try_ casts: a value that does not
-- parse reads NULL. The natural key and join-key columns stay TEXT.
--   objectid: ID: whole numbers, over 90% distinct -- stays TEXT, '.0' tail removed
--   smpprojectid: ID: whole numbers, over 90% distinct -- stays TEXT, '.0' tail removed
--   segment_count: integer
--   additional_of_base_failures: float
--   of_flat_work: integer
--   weighted_pavement_condition_index: integer
--   estimated_total_cost: float
--   inside_x: float
--   inside_y: float
--   council_district: integer
-- spine_entity 'place' has no connect/ resolver yet (see connect/spine_entity.py) -- no SPINE_ENTITY_ID emitted.
-- landing table's ingestion timestamp is named INGESTED_AT (no leading underscore) rather than the usual _INGESTED_AT -- confirmed via INFORMATION_SCHEMA, not assumed.
-- DEDUPE: registry natural_key (SHAPE__LENGTH, FISCAL_YEAR) is NOT unique within a load as landed at generation time -- it would collapse 103 of 8,640 rows. Deduping on the WHOLE ROW instead (exact copies only). A record that changes between loads shows once per version. Find the real key, fix SOURCE_REGISTRY, regenerate.

with source as (

    select * from {{ source('ripple_raw', 'PORTAL_CKA_OPEN_DATA_SA_1C37EE3869') }}
    qualify row_number() over (partition by "OBJECTID", "SMPPROJECTID", "SEGMENT_COUNT", "PROJECT_CATEGORY", "PROJECT_TYPE", "COUNCIL_DISTRICT_LIST", "PROJECT_STREET", "FROM_STREET", "TO_STREET", "FISCAL_YEAR", "OF_BASE_FAILURES", "ADDITIONAL_OF_BASE_FAILURES", "OF_FLAT_WORK", "WEIGHTED_PAVEMENT_CONDITION_INDEX", "APPLICATION", "FORCE", "ESTIMATED_TOTAL_COST", "TYPE", "PROJECT_STATUS", "SCHEDULE_START", "SCHEDULE_FINISH", "ACTUAL_START", "ACTUAL_FINISH", "PROJECT_MANAGER", "CONTACT", "CLASSIFICATION", "INSIDE_X", "INSIDE_Y", "COUNCIL_DISTRICT", "SHAPE__LENGTH" order by INGESTED_AT desc) = 1

),

renamed as (

    select
        {{ stg_id_text('"OBJECTID"') }} as objectid,
        {{ stg_id_text('"SMPPROJECTID"') }} as smpprojectid,
        {{ stg_int('"SEGMENT_COUNT"') }} as segment_count,
        {{ null_junk('"PROJECT_CATEGORY"') }} as project_category,
        {{ null_junk('"PROJECT_TYPE"') }} as project_type,
        {{ null_junk('"COUNCIL_DISTRICT_LIST"') }} as council_district_list,
        {{ null_junk('"PROJECT_STREET"') }} as project_street,
        {{ null_junk('"FROM_STREET"') }} as from_street,
        {{ null_junk('"TO_STREET"') }} as to_street,
        {{ null_junk('"FISCAL_YEAR"') }} as fiscal_year,
        {{ null_junk('"OF_BASE_FAILURES"') }} as of_base_failures,
        {{ stg_float('"ADDITIONAL_OF_BASE_FAILURES"') }} as additional_of_base_failures,
        {{ stg_int('"OF_FLAT_WORK"') }} as of_flat_work,
        {{ stg_int('"WEIGHTED_PAVEMENT_CONDITION_INDEX"') }} as weighted_pavement_condition_index,
        {{ null_junk('"APPLICATION"') }} as application,
        {{ null_junk('"FORCE"') }} as force,
        {{ stg_float('"ESTIMATED_TOTAL_COST"') }} as estimated_total_cost,
        {{ null_junk('"TYPE"') }} as type,
        {{ null_junk('"PROJECT_STATUS"') }} as project_status,
        {{ null_junk('"SCHEDULE_START"') }} as schedule_start,
        {{ null_junk('"SCHEDULE_FINISH"') }} as schedule_finish,
        {{ null_junk('"ACTUAL_START"') }} as actual_start,
        {{ null_junk('"ACTUAL_FINISH"') }} as actual_finish,
        {{ null_junk('"PROJECT_MANAGER"') }} as project_manager,
        {{ null_junk('"CONTACT"') }} as contact,
        {{ null_junk('"CLASSIFICATION"') }} as classification,
        {{ stg_float('"INSIDE_X"') }} as inside_x,
        {{ stg_float('"INSIDE_Y"') }} as inside_y,
        {{ stg_int('"COUNCIL_DISTRICT"') }} as council_district,
        {{ null_junk('"SHAPE__LENGTH"') }} as shape__length,
        INGESTED_AT as _loaded_at,
        'https://data.sanantonio.gov/dataset/imp-street' as _source_url

    from source

)

select * from renamed
