{{ config(materialized='view', schema='TIMELINE', alias='PROCUREMENT__FED_SAM_EXCLUSIONS') }}

-- GENERATED by scripts/census/gen_time_views.py -- do not hand-edit.
-- Regenerate after any change to reports/time_index/clock_index.csv.
--
-- Canonical clock for PROCUREMENT.PROCUREMENT__FED_SAM_EXCLUSIONS.
--   column : ACTIVATION_DATE   (DATE)
--   means  : span_start -- Day the debarment/suspension took effect - it opens the exclusion period the model itself describes ('and for how long?') and is cast try_to_date(...,'YYYY-MM-D
--   grain  : day
--
-- The original columns pass through untouched; the canonical four sit in front
-- of them. Rule 8 of the datetime standard: the raw column is never overwritten,
-- so a mis-parse is always recoverable.

select
    {{ ripple_window('src."ACTIVATION_DATE"::timestamp_ntz') }} as ripple_ts,
    {{ ripple_grain('day') }} as ripple_grain,
    {{ ripple_clock('span_start') }} as ripple_clock,
    'PROCUREMENT.PROCUREMENT__FED_SAM_EXCLUSIONS'::varchar as ripple_source,
    src.*
from {{ ref('procurement__fed_sam_exclusions') }} as src
