{{ config(tags=['spine_generated']) }}

-- GRAIN: one row per place (ZIP+APPLICATION_DATE unique)
-- SPINE_ENTITY: place  (natural_key: ZIP_CODE, APPLICATION_DATE)
-- Generated by scripts/generate_staging_models.py from SOURCE_REGISTRY -- deterministic,
-- no LLM. Casts kept as landed (TEXT) -- add explicit type casts by hand once each
-- column's real type is confirmed; this generator has no semantic type knowledge.
-- spine_entity 'place' has no connect/ resolver yet (see connect/spine_entity.py) -- no SPINE_ENTITY_ID emitted.
-- landing table's ingestion timestamp is named INGESTED_AT (no leading underscore) rather than the usual _INGESTED_AT -- confirmed via INFORMATION_SCHEMA, not assumed.
-- DEDUPE: registry natural_key (ZIP_CODE, APPLICATION_DATE) is NOT unique within a load as landed at generation time -- it would collapse 34 of 8,250 rows. Deduping on the WHOLE ROW instead (exact copies only). A record that changes between loads shows once per version. Find the real key, fix SOURCE_REGISTRY, regenerate.

with source as (

    select * from {{ source('ripple_raw', 'PORTAL_CKA_ANALYZE_BOSTON_4EDDC3919B') }}

),

renamed as (

    select
        "APP_NUMBER" as app_number,
        "APP_NAME" as app_name,
        "STATUS" as status,
        "APPLICATION_DATE" as application_date,
        "ISSUED_DATE" as issued_date,
        "LOCATION_DESCRIPTION" as location_description,
        "STREET_NUMBER" as street_number,
        "STREET_NAME" as street_name,
        "STREET_SUFFIX" as street_suffix,
        "CITY" as city,
        "ZIP_CODE" as zip_code,
        "START_DATE_AND_TIME" as start_date_and_time,
        "END_DATE_AND_TIME" as end_date_and_time,
        INGESTED_AT as _loaded_at,
        'https://data.boston.gov/dataset/special-event-license-applications' as _source_url

    from source

)

select * from renamed
qualify row_number() over (partition by app_number, app_name, status, application_date, issued_date, location_description, street_number, street_name, street_suffix, city, zip_code, start_date_and_time, end_date_and_time order by _loaded_at desc) = 1
