{{ config(tags=['spine_generated']) }}

-- GRAIN: one row per event (TEMP_EVENT_ID+INSPECTION_DATE+ACTIVITY_TYPE+STAFF_CODE unique)
-- SPINE_ENTITY: event  (natural_key: TEMP_EVENT_ID, INSPECTION_DATE, ACTIVITY_TYPE, STAFF_CODE)
-- Generated by scripts/generate_staging_models.py from SOURCE_REGISTRY -- deterministic,
-- no LLM. Casts kept as landed (TEXT) -- add explicit type casts by hand once each
-- column's real type is confirmed; this generator has no semantic type knowledge.
-- spine_entity 'event' has no connect/ resolver yet (see connect/spine_entity.py) -- no SPINE_ENTITY_ID emitted.
-- landing table's ingestion timestamp is named INGESTED_AT (no leading underscore) rather than the usual _INGESTED_AT -- confirmed via INFORMATION_SCHEMA, not assumed.

with source as (

    select * from {{ source('ripple_raw', 'PORTAL_CKA_HOUSTON_OPEN_DAT_07C9C99EB1') }}

),

renamed as (

    select
        "TEMP_EVENT_ID" as temp_event_id,
        "C_ACCOUNT" as c_account,
        "NAME" as name,
        "SITE" as site,
        "ACTIVITY_TYPE" as activity_type,
        "CITATION_NUMBER" as citation_number,
        "STAFF_CODE" as staff_code,
        "FACILITY_TYPE" as facility_type,
        "SCORE" as score,
        "INSPECTION_DATE" as inspection_date,
        INGESTED_AT as _loaded_at,
        'https://data.houstontx.gov/dataset/city-of-houston-health-and-human-services-department-temporary-event-inspections' as _source_url

    from source

)

select * from renamed
qualify row_number() over (partition by temp_event_id, inspection_date, activity_type, staff_code order by _loaded_at desc) = 1
