    with source as (
        select * from {{ source('ripple_raw', 'FED_CMS_SNF_OWNERSHIP') }}
    )

    select
        "ENROLLMENT_ID",
"ASSOCIATE_ID",
"ORGANIZATION_NAME",
"ASSOCIATE_ID_OWNER",
"TYPE_OWNER",
"ROLE_CODE_OWNER",
"ROLE_TEXT_OWNER",
"ASSOCIATION_DATE_OWNER",
"FIRST_NAME_OWNER",
"MIDDLE_NAME_OWNER",
"LAST_NAME_OWNER",
"TITLE_OWNER",
"ORGANIZATION_NAME_OWNER",
"DOING_BUSINESS_AS_NAME_OWNER",
"ADDRESS_LINE_1_OWNER",
"ADDRESS_LINE_2_OWNER",
"CITY_OWNER",
"STATE_OWNER",
"ZIP_CODE_OWNER",
"PERCENTAGE_OWNERSHIP",
"CREATED_FOR_ACQUISITION_OWNER",
"CORPORATION_OWNER",
"LLC_OWNER",
"MEDICAL_PROVIDER_SUPPLIER_OWNER",
"MANAGEMENT_SERVICES_COMPANY_OWNER",
"MEDICAL_STAFFING_COMPANY_OWNER",
"HOLDING_COMPANY_OWNER",
"INVESTMENT_FIRM_OWNER",
"FINANCIAL_INSTITUTION_OWNER",
"CONSULTING_FIRM_OWNER",
"FOR_PROFIT_OWNER",
"NON_PROFIT_OWNER",
"PRIVATE_EQUITY_COMPANY_OWNER",
"REIT_OWNER",
"CHAIN_HOME_OFFICE_OWNER",
"TRUST_OR_TRUSTEE_OWNER",
"OTHER_TYPE_OWNER",
"OTHER_TYPE_TEXT_OWNER",
"PARENT_COMPANY_OWNER",
"OWNED_BY_ANOTHER_ORG_OR_IND_OWNER",
_INGESTED_AT,
_SOURCE_RUN_ID
    from source
    qualify row_number() over (
        partition by ENROLLMENT_ID, ASSOCIATE_ID_OWNER, ROLE_CODE_OWNER
        order by _INGESTED_AT desc
    ) = 1
