{{ config(tags=['spine_generated']) }}

-- GRAIN: one row per facility (CCN is unique)
-- SPINE_ENTITY: facility  (natural_key: CCN)
-- Generated by scripts/generate_staging_models.py from SOURCE_REGISTRY -- deterministic,
-- no LLM. Casts kept as landed (TEXT) -- add explicit type casts by hand once each
-- column's real type is confirmed; this generator has no semantic type knowledge.
-- landing table's ingestion timestamp is named INGESTED_AT (no leading underscore) rather than the usual _INGESTED_AT -- confirmed via INFORMATION_SCHEMA, not assumed.

with source as (

    select * from {{ source('ripple_raw', 'PORTAL_ARC_OPEN_BALTIMORE_6C2257F1C4') }}

),

renamed as (

    select
        "FID" as fid,
        "LOC_NAME" as loc_name,
        "STATUS" as status,
        "SCORE" as score,
        "MATCH_TYPE" as match_type,
        "MATCH_ADDR" as match_addr,
        "SIDE" as side,
        "X" as x,
        "Y" as y,
        "USER_FLD" as user_fld,
        "ADDR_TYPE" as addr_type,
        "ARC_STREET" as arc_street,
        "ARC_CITY" as arc_city,
        "ARC_STATE" as arc_state,
        "ARC_ZIP" as arc_zip,
        "COUNTY" as county,
        "FACILITY_N" as facility_n,
        "FACILITY_A" as facility_a,
        "FACILITY_C" as facility_c,
        "FACILITY_S" as facility_s,
        "FACILITY_Z" as facility_z,
        "FACILITY_P" as facility_p,
        "FACILITY_1" as facility_1,
        "LICENSE_CA" as license_ca,
        "LICENSE_IN" as license_in,
        "CCN" as ccn,
        "TYPE" as type,
        "GEOMETRY" as geometry,
        INGESTED_AT as _loaded_at,
        'https://data.baltimorecity.gov/datasets/354595606ea7464da286553b95b0f4b4_0' as _source_url,
    'ENT_' || LEFT(MD5('CCN' || '|' || (CASE WHEN LENGTH(UPPER(REGEXP_REPLACE(TO_VARCHAR("CCN"), '[^0-9A-Za-z]', ''))) = 0 OR LENGTH(UPPER(REGEXP_REPLACE(TO_VARCHAR("CCN"), '[^0-9A-Za-z]', ''))) > 6 OR LPAD(UPPER(REGEXP_REPLACE(TO_VARCHAR("CCN"), '[^0-9A-Za-z]', '')), 6, '0') = REPEAT('0', 6) THEN NULL ELSE LPAD(UPPER(REGEXP_REPLACE(TO_VARCHAR("CCN"), '[^0-9A-Za-z]', '')), 6, '0') END)), 16) as spine_entity_id  -- joins LIBRARY_META."CONNECT".ENTITY_GOLDEN.ENTITY_ID

    from source

)

select * from renamed
qualify row_number() over (partition by ccn order by _loaded_at desc) = 1
