{{ config(tags=['spine_generated']) }}

-- GRAIN: one row per place (GEOM is unique)
-- SPINE_ENTITY: place  (natural_key: SHAPE_AREA)
-- Generated by scripts/generate_staging_models.py from SOURCE_REGISTRY -- deterministic,
-- no LLM.
-- CASTS: 2 of 11 columns, from landing_column_profile_2026-09-19.tsv. A column is cast only
-- when every filled value in the sample parsed. try_ casts: a value that does not
-- parse reads NULL. The natural key and join-key columns stay TEXT.
--   objectid: ID: whole numbers, over 90% distinct -- stays TEXT, '.0' tail removed
--   site_acreage: float
-- spine_entity 'place' has no connect/ resolver yet (see connect/spine_entity.py) -- no SPINE_ENTITY_ID emitted.
-- landing table's ingestion timestamp is named INGESTED_AT (no leading underscore) rather than the usual _INGESTED_AT -- confirmed via INFORMATION_SCHEMA, not assumed.
-- DEDUPE: registry natural_key (SHAPE_AREA) is NOT unique within a load as landed at generation time -- it would collapse 4 of 263 rows. Deduping on the WHOLE ROW instead (exact copies only). A record that changes between loads shows once per version. Find the real key, fix SOURCE_REGISTRY, regenerate.

with source as (

    select * from {{ source('ripple_raw', 'PORTAL_CKA_VIRGINIA_OPEN_DA_3BB10A6097') }}
    qualify row_number() over (partition by "OBJECTID", "SSWD_NUMBER", "PERMIT_NUMBER", "DELINEATION_AGENT", "REGION", "APPLICANT", "FIC_DESCRIPTION", "APPROVAL_DATE", "SITE_ACREAGE", "SHAPE_LENGTH", "SHAPE_AREA" order by INGESTED_AT desc) = 1

),

renamed as (

    select
        {{ stg_id_text('"OBJECTID"') }} as objectid,
        {{ null_junk('"SSWD_NUMBER"') }} as sswd_number,
        {{ null_junk('"PERMIT_NUMBER"') }} as permit_number,
        {{ null_junk('"DELINEATION_AGENT"') }} as delineation_agent,
        {{ null_junk('"REGION"') }} as region,
        {{ null_junk('"APPLICANT"') }} as applicant,
        {{ null_junk('"FIC_DESCRIPTION"') }} as fic_description,
        {{ null_junk('"APPROVAL_DATE"') }} as approval_date,
        {{ stg_float('"SITE_ACREAGE"') }} as site_acreage,
        {{ null_junk('"SHAPE_LENGTH"') }} as shape_length,
        {{ null_junk('"SHAPE_AREA"') }} as shape_area,
        INGESTED_AT as _loaded_at,
        'https://data.virginia.gov/dataset/vwp-sswd-boundaries' as _source_url

    from source

)

select * from renamed
