#!/bin/bash
# Rebuilds the 247 models touched by the 2026-09-20 warehouse QA fix pass.
# Run this yourself from repo root -- the agent-side gate blocks it, you're not gated.
set -e
cd "$(dirname "${BASH_SOURCE[0]}")/../library-onboarding/ripple_dbt"

dbt build --select \
  economics__fed_dol_form5500 economics__fed_fac_single_audit economics__fed_fincen_boi \
  economics__fed_grants_gov economics__fed_irs_990_efile_index economics__fed_irs_auto_revocations \
  economics__fed_irs_eo_pr economics__fed_irs_soi_charities economics__fed_pbgc_data \
  economics__fed_pbgc_trusteed_pension_plans economics__fed_sba_ppp economics__fed_sba_ppp_loans_150k_plus \
  economics__fed_treasury_debt_outstanding economics__fed_treasury_dts_deposits economics__fed_treasury_mts_receipts \
  economics__fed_usaspending_toptier_agencies economics__intl_fao_faostat economics__intl_fao_faostat_food_security \
  economics__intl_gfi_trade economics__intl_gleif_relationships economics__intl_ipc_food_insecurity_global \
  economics__xc_owid_gini education__fed_cftc_cot_financial education__fed_cftc_cot_futures \
  education__fed_ed_edfacts education__fed_google_polads_advertiser_weekly_spend education__fed_google_polads_creative_stats \
  education__fed_senate_lda_filings environment__fed_epa_egrid_plant_2022 environment__fed_epa_frs_facilities \
  environment__fed_epa_icis_air_icis_air_fces_pces environment__fed_epa_icis_air_icis_air_formal_actions \
  environment__fed_epa_icis_air_icis_air_informal_actions environment__fed_epa_icis_air_icis_air_programs \
  environment__fed_epa_icis_air_icis_air_stack_tests environment__fed_epa_icis_air_icis_air_titlev_certs \
  environment__fed_epa_icis_air_icis_air_violation_history environment__fed_epa_npdes_icis_facilities \
  environment__fed_epa_npdes_npdes_cs_violations environment__fed_epa_npdes_npdes_formal_enforcement_actions \
  environment__fed_epa_npdes_npdes_informal_enforcement_actions environment__fed_epa_npdes_npdes_inspections \
  environment__fed_epa_npdes_npdes_ps_violations environment__fed_epa_npdes_npdes_se_violations \
  environment__fed_epa_sdwa_sdwa_events_milestones environment__fed_epa_sdwa_sdwa_facilities \
  environment__fed_epa_sdwa_sdwa_geographic_areas environment__fed_epa_sdwa_sdwa_lcr_samples \
  environment__fed_epa_sdwa_sdwa_pn_violation_assoc environment__fed_epa_sdwa_sdwa_pub_water_systems \
  environment__fed_epa_sdwa_sdwa_site_visits environment__fed_epa_sdwa_sdwa_violations_enforcement \
  environment__fed_epa_tri_basic_2023 environment__fed_noaa_storm_events environment__fed_noaa_weather_api \
  environment__fed_usgs_minerals environment__fed_usgs_water environment__intl_gem_hazard \
  environment__intl_global_witness_defenders environment__xc_owid_co2 environment__xc_owid_fossil_share \
  environment__xc_owid_temp_anomaly finance__fed_cftc_cot_financial_hist finance__fed_epa_icis_fec_epa_informal_enforcement_actions \
  finance__fed_epa_icis_fec_icis_fec_epa_inspections finance__fed_fara finance__fed_fec_cand_cmte_linkage \
  finance__fed_fec_candidates finance__fed_fec_committee_to_candidate finance__fed_fec_indiv_contributions \
  finance__fed_fec_pac_summary finance__fed_ffiec_call_reports finance__fed_irs_soi finance__fed_sec_13f_filers \
  finance__fed_sec_13f_holdings finance__fed_sec_13f_submission finance__fed_sec_business_development_company_report \
  finance__fed_sec_closed_end_fund_information finance__fed_sec_dera_sub_2024q1 finance__fed_sec_dera_sub_2024q2 \
  finance__fed_sec_dera_sub_2024q3 finance__fed_sec_dera_sub_2024q4 finance__fed_sec_dera_sub_2025q1 \
  finance__fed_sec_dera_sub_2025q2 finance__fed_sec_dera_sub_2025q3 finance__fed_sec_dera_sub_2025q4 \
  finance__fed_sec_dera_sub_2026q1 finance__fed_sec_edgar_financials finance__fed_sec_edgar_insiders \
  finance__fed_sec_insider_deriv_trans finance__fed_sec_insider_submission health__fed_cdc_anxiety_depression \
  health__fed_cdc_drug_poisoning_county health__fed_cdc_health_insurance health__fed_cdc_injury_violence_county \
  health__fed_cdc_overdose health__fed_cdc_suicide_rates health__fed_cms_dialysis \
  health__fed_cms_facility_level_minimum_data_set_frequency health__fed_cms_federally_qualified_health_center_enrollments \
  health__fed_cms_home_health health__fed_cms_home_health_agency_enrollments health__fed_cms_hospice \
  health__fed_cms_hospital_compare health__fed_cms_hospital_enrollments health__fed_cms_hospital_general \
  health__fed_cms_hpt_mrf health__fed_cms_irf health__fed_cms_ltch health__fed_cms_marketplace_plan_attributes_puf \
  health__fed_cms_medicare_dialysis_facilities health__fed_cms_medicare_durable_medical_equipment_devices_supplies_by_refer \
  health__fed_cms_medicare_durable_medical_equipment_devices_supplies_by_suppl health__fed_cms_medicare_inpatient_hospitals_by_provider \
  health__fed_cms_medicare_inpatient_hospitals_by_provider_and_service health__fed_cms_medicare_outpatient_hospitals_by_provider_and_service \
  health__fed_cms_medicare_physician_other_practitioners_by_provider health__fed_cms_medicare_physician_other_practitioners_by_provider_and_servi \
  health__fed_cms_medicare_provider health__fed_cms_nursing_home health__fed_cms_nursing_home_deficiencies \
  health__fed_cms_nursing_home_fire_deficiencies health__fed_cms_nursing_home_penalties health__fed_cms_opioid_treatment_program_providers \
  health__fed_cms_opt_out_affidavits health__fed_cms_part_d_prescribers health__fed_cms_partd_prescriber_drug \
  health__fed_cms_partd_prescribers health__fed_cms_pecos_provider_enrollment health__fed_cms_pos_other \
  health__fed_cms_quality_payment_program_experience health__fed_cms_rural_health_clinic_enrollments \
  health__fed_cms_skilled_nursing_facility_enrollments health__fed_fda_faers_drug health__fed_hrsa_shortage_areas \
  health__fed_nursinghome411 health__fed_va_suicide_appendix health__xc_owid_life_expectancy \
  history__fed_david_rumsey history__fed_docsouth housing__fed_cfpb_hmda_dc_only housing__fed_fhfa_hpi \
  housing__fed_fhfa_nmdb housing__fed_fhfa_suspended_counterparty housing__fed_hud_data \
  immigration__fed_cbp_encounters immigration__fed_cms_hospice_enrollments immigration__fed_cms_medicare_fee_for_service_public_provider_enrollment \
  immigration__fed_dhs_yearbook immigration__fed_dol_oflc immigration__fed_epa_sdwa_sdwa_service_areas \
  immigration__fed_ice_statistics immigration__fed_uscis_data immigration__xc_owid_refugees \
  int_nursing_home_prf_match justice__fed_bop_statistics justice__fed_cisa_kev \
  justice__fed_courtlistener_citations justice__fed_courtlistener_courts justice__fed_courtlistener_disclosure_agreements \
  justice__fed_courtlistener_disclosure_debts justice__fed_courtlistener_disclosure_gifts justice__fed_courtlistener_disclosure_non_investment_income \
  justice__fed_courtlistener_disclosure_positions justice__fed_courtlistener_disclosure_reimbursements justice__fed_courtlistener_disclosure_spousal_income \
  justice__fed_courtlistener_dockets justice__fed_courtlistener_financial_disclosures justice__fed_courtlistener_fjc_idb_cl_linked \
  justice__fed_courtlistener_investments justice__fed_courtlistener_judge_educations justice__fed_courtlistener_judge_political_affiliations \
  justice__fed_courtlistener_judges justice__fed_courtlistener_opinion_clusters justice__fed_courtlistener_oral_arguments \
  justice__fed_courtlistener_originating_court_info justice__fed_courtlistener_positions justice__fed_courtlistener_schools \
  justice__fed_fbi_nics_checks justice__fed_fjc_article_iii_judges justice__fed_ftc_datasets justice__intl_austlii \
  justice__intl_eu_sanctions justice__intl_eu_socta_europol justice__intl_eurlex_cellar justice__intl_nti_cns_dprk_missile_tests \
  justice__intl_opensanctions justice__intl_ucdp_ged justice__intl_uk_sanctions_list justice__xc_mapping_police_violence \
  justice__xc_owid_homicide justice__xc_owid_nuclear_warheads justice__xc_owid_terrorism_deaths \
  labor__fed_msha_mines labor__fed_osha_ita_300a_summary_2023 labor__fed_osha_ita_300a_summary_2024 \
  labor__fed_osha_ita_300a_summary_2025 labor__fed_osha_ita_case_detail_2023 labor__fed_osha_ita_case_detail_2024 \
  labor__fed_osha_ita_case_detail_2025 open_data__intl_ar_datosgob open_data__intl_br_dados_gov \
  open_data__intl_ge_datagov open_data__intl_gh_datagovgh politics__fed_fcc_licensing politics__fed_fjc_judges \
  politics__fed_fjc_service politics__fed_govinfo_bill_cosponsors politics__fed_govinfo_billstatus \
  politics__fed_voteview_members politics__fed_voteview_rollcall_meta politics__fed_voteview_rollcalls \
  politics__intl_freedomhouse politics__intl_owid_milspend politics__intl_voeten_unga_votes \
  politics__st_cannabis_policy_bundles politics__xc_jcs_medians politics__xc_owid_cpi \
  procurement__fed_sam_exclusions procurement__intl_adb_data reference__fed_usgs_topoview \
  reference__intl_eg_capmas reference__intl_eurostat reference__intl_gdelt reference__xc_owid_fertility \
  science__fed_nasa_open_data science__fed_nsf_awards science__fed_usgs_earthquakes science__xc_owid_ai_incidents_annual \
  stg_fed_bjs_data__bjs_data_collections stg_intl_hudoc__echr_cases timeline__economics__fed_usaspending_contracts_full \
  transport__fed_dot_bts transport__fed_faa_data_portal transport__fed_fra_safety uncategorized__fed_dea_arcos_full \
  uncategorized__fed_epa_frs_full uncategorized__fed_jpml_pending_mdl uncategorized__fed_trade_consolidated_screening_list \
  uncategorized__icij_offshore_leaks_entities uncategorized__icij_offshore_leaks_relationships uncategorized__int_uk_companies_house \
  uncategorized__intl_un_consolidated_sanctions uncategorized__intl_un_sc_consolidated_sanctions uncategorized__state_oehha_prop65_chemicals \
  uncategorized__xc_icij_offshore_nodes_entities uncategorized__xc_icij_offshore_relationships

echo "Done. NOTE: the FEC committee-to-candidate public aggregate (scripts/build_giant_aggs.py)"
echo "is NOT in this list on purpose -- its grain (163,388 combos) is over the script's 100k"
echo "cap. That needs your design call first (coarser grain / raised cap / different rollup)."
