{{ config(tags=['spine_generated']) }}

-- GRAIN: one row per place (GEOM is unique)
-- SPINE_ENTITY: place  (natural_key: GEOMETRY)
-- Generated by scripts/generate_staging_models.py from SOURCE_REGISTRY -- deterministic,
-- no LLM. Casts kept as landed (TEXT) -- add explicit type casts by hand once each
-- column's real type is confirmed; this generator has no semantic type knowledge.
-- spine_entity 'place' has no connect/ resolver yet (see connect/spine_entity.py) -- no SPINE_ENTITY_ID emitted.
-- landing table's ingestion timestamp is named INGESTED_AT (no leading underscore) rather than the usual _INGESTED_AT -- confirmed via INFORMATION_SCHEMA, not assumed.

with source as (

    select * from {{ source('ripple_raw', 'PORTAL_CKA_WPRDC_ALLEGHENY_2E4D4F0008') }}

),

renamed as (

    select
        "CLASS" as class,
        "CREST" as crest,
        "DAMS_ID" as dams_id,
        "DAM_HEIGHT" as dam_height,
        "DAM_NAME" as dam_name,
        "DAM_NO" as dam_no,
        "DRAIN_AREA" as drain_area,
        "EAST" as east,
        "EASTING" as easting,
        "FID" as fid,
        "NORTH" as north,
        "NORTHING" as northing,
        "PERIMETER" as perimeter,
        "PERMITTEE" as permittee,
        "PURPOSE" as purpose,
        "QUAD_NAME" as quad_name,
        "STORAGE_NO" as storage_no,
        "STORAGE_TO" as storage_to,
        "STREAM" as stream,
        "SURFACE_NO" as surface_no,
        "SURFACE_TO" as surface_to,
        "TYPE" as type,
        "ZONE" as zone,
        "GEOMETRY" as geometry,
        INGESTED_AT as _loaded_at,
        'https://data.wprdc.org/dataset/allegheny-county-dam-locations2' as _source_url

    from source

)

select * from renamed
qualify row_number() over (partition by geometry order by _loaded_at desc) = 1
