{{ config(tags=['spine_generated']) }}

-- GRAIN: one row per facility (NPDES_ID+SETTLEMENT_ENTERED_DATE+ACTIVITY_TYPE_CODE+ENF_TYPE_CODE+ACTIVITY_ID unique)
-- SPINE_ENTITY: facility  (natural_key: NPDES_ID, SETTLEMENT_ENTERED_DATE, ACTIVITY_TYPE_CODE, ENF_TYPE_CODE, ACTIVITY_ID)
-- Generated by scripts/generate_staging_models.py from SOURCE_REGISTRY -- deterministic,
-- no LLM.
-- CASTS: 2 of 10 columns, from landing_column_profile_2026-09-19.tsv. A column is cast only
-- when every filled value in the sample parsed. try_ casts: a value that does not
-- parse reads NULL. The natural key and join-key columns stay TEXT.
--   fed_penalty_assessed_amt: float
--   state_local_penalty_amt: float
-- spine_entity 'facility' has no connect/ resolver yet (see connect/spine_entity.py) -- no SPINE_ENTITY_ID emitted.

with source as (

    select * from {{ source('ripple_raw', 'FED_EPA_NPDES_NPDES_FORMAL_ENFORCEMENT_ACTIONS') }}
    qualify row_number() over (partition by "NPDES_ID", "SETTLEMENT_ENTERED_DATE", "ACTIVITY_TYPE_CODE", "ENF_TYPE_CODE", "ACTIVITY_ID" order by _INGESTED_AT desc) = 1

),

renamed as (

    select
        {{ null_junk('"NPDES_ID"') }} as npdes_id,
        {{ null_junk('"ENF_IDENTIFIER"') }} as enf_identifier,
        {{ null_junk('"ACTIVITY_ID"') }} as activity_id,
        {{ null_junk('"ACTIVITY_TYPE_CODE"') }} as activity_type_code,
        {{ null_junk('"ENF_TYPE_CODE"') }} as enf_type_code,
        {{ null_junk('"ENF_TYPE_DESC"') }} as enf_type_desc,
        {{ null_junk('"AGENCY"') }} as agency,
        {{ null_junk('"SETTLEMENT_ENTERED_DATE"') }} as settlement_entered_date,
        {{ stg_float('"FED_PENALTY_ASSESSED_AMT"') }} as fed_penalty_assessed_amt,
        {{ stg_float('"STATE_LOCAL_PENALTY_AMT"') }} as state_local_penalty_amt,
        _INGESTED_AT as _loaded_at,
        '' as _source_url

    from source

)

select * from renamed
