-- per Reliant home: Medicare enrollment legal entity, incorporation date, NPI, and NursingHome411's ownership-change flag
with rel as (select lpad(trim(CMS_CERTIFICATION_NUMBER_CCN),6,'0') ccn, PROVIDER_NAME, LEGAL_BUSINESS_NAME from LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_NURSING_HOME where CHAIN_ID='446')
select rel.ccn, rel.PROVIDER_NAME, rel.LEGAL_BUSINESS_NAME, e.ORGANIZATION_NAME, e.DOING_BUSINESS_AS_NAME, e.INCORPORATION_DATE, e.INCORPORATION_STATE, e.NPI, e.ENROLLMENT_ID, e.ADDRESS_LINE_1, e.CITY,
  f.PROVIDER_CHANGED_OWNERSHIP_IN_LAST_12_MONTHS chow411, f.OWNERSHIP_TYPE_DETAIL, f.CHAIN_NAME chain411
from rel left join LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_SKILLED_NURSING_FACILITY_ENROLLMENTS e on lpad(trim(e.CCN),6,'0')=rel.ccn
left join LIBRARY_MARTS.HEALTH.HEALTH__FED_NURSINGHOME411 f on lpad(trim(f.CMS_CERTIFICATION_NUMBER_CCN),6,'0')=rel.ccn
order by e.INCORPORATION_DATE desc
