-- OSHA 300A eyeball: every Reliant-matched filing row 2023-2025 (name prefix + city, or company RELIANT), with address to confirm
with n as (select distinct PROVIDER_NAME, upper(CITY) city, ADDRESS, regexp_replace(upper(PROVIDER_NAME),'[^A-Z0-9]','') k from LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_NURSING_HOME where CHAIN_ID='446' and STATE='MO'),
a as (select 2023 yr, ESTABLISHMENT_NAME, COMPANY_NAME, EIN, upper(CITY) city, STREET_ADDRESS, ANNUAL_AVERAGE_EMPLOYEES emp, TOTAL_HOURS_WORKED hrs, TOTAL_DAFW_CASES dafw, TOTAL_DJTR_CASES djtr, TOTAL_OTHER_CASES oth, TOTAL_DAFW_DAYS dafw_days from LIBRARY_MARTS.LABOR.LABOR__FED_OSHA_ITA_300A_SUMMARY_2023 where STATE='MO'
  union all select 2024, ESTABLISHMENT_NAME, COMPANY_NAME, EIN, upper(CITY), STREET_ADDRESS, ANNUAL_AVERAGE_EMPLOYEES, TOTAL_HOURS_WORKED, TOTAL_DAFW_CASES, TOTAL_DJTR_CASES, TOTAL_OTHER_CASES, TOTAL_DAFW_DAYS from LIBRARY_MARTS.LABOR.LABOR__FED_OSHA_ITA_300A_SUMMARY_2024 where STATE='MO'
  union all select 2025, ESTABLISHMENT_NAME, COMPANY_NAME, EIN, upper(CITY), STREET_ADDRESS, ANNUAL_AVERAGE_EMPLOYEES, TOTAL_HOURS_WORKED, TOTAL_DAFW_CASES, TOTAL_DJTR_CASES, TOTAL_OTHER_CASES, TOTAL_DAFW_DAYS from LIBRARY_MARTS.LABOR.LABOR__FED_OSHA_ITA_300A_SUMMARY_2025 where STATE='MO')
select a.yr, n.PROVIDER_NAME matched_home, n.ADDRESS home_addr, a.ESTABLISHMENT_NAME, a.COMPANY_NAME, a.EIN, a.city, a.STREET_ADDRESS, a.emp, a.hrs, a.dafw, a.djtr, a.oth, a.dafw_days
from a left join n on regexp_replace(upper(a.ESTABLISHMENT_NAME),'[^A-Z0-9]','') like n.k||'%' and a.city=n.city
where n.k is not null or a.COMPANY_NAME ilike '%RELIANT%CARE%' or a.COMPANY_NAME ilike '%RELIANTCARE%'
order by a.yr, a.ESTABLISHMENT_NAME
