-- federal civil cases (FJC IDB): plaintiff or defendant names RELIANT CARE, DESTEFANE, or a distinctive Reliant home name (generic single names like HERITAGE only with CARE CENTER)
select DISTRICT, OFFICE, DOCKET, FILE_DATE, TERM_DATE, NATURE_OF_SUIT, PLAINTIFF, DEFENDANT, DISPOSITION, JUDGMENT, AMOUNT_RECEIVED, TAPE_YEAR, count(*) over (partition by DISTRICT, DOCKET) yearly_rows
from LIBRARY_MARTS.JUSTICE.JUSTICE__FED_FJC_IDB_CIVIL
where regexp_like(upper(coalesce(PLAINTIFF,'')||' | '||coalesce(DEFENDANT,'')),
 '.*(RELIANT CARE|RELIANTCARE|DESTEFANE|NORTH VILLAGE PARK|BRIDGEWOOD HEALTH|GREGORY RIDGE|HERITAGE CARE CENTER|CRESTWOOD HEALTH|CHARITON PARK|EASTVIEW MANOR|FOUR SEASONS LIVING|EDGEWOOD MANOR HEALTH|NATHAN RICHARD|BERNARD CARE|GIETNER|GRAND MANOR HEALTH|HIDDEN LAKE HEALTH|PARKWAY HEALTH CARE|NICKS HEALTH|NICK.S HEALTH|PORTAGEVILLE HEALTH|WESTVIEW NURSING|MMA HEALTHCARE|BKY HEALTHCARE|REST HAVEN HEALTH|WELLSVILLE HEALTH|HOLTON HEALTH|BRUNSWICK HEALTH|SARCOXIE|ODESSA HEALTH|BROOKFIELD HEALTH|SOUTH COUNTY HEALTH|STONECREST HEALTH|GREENVILLE HEALTH|MILAN HEALTH|FAIR VIEW HEALTH|ST ELIZABETH CARE|CASSVILLE HEALTH).*')
order by FILE_DATE desc
