-- CourtListener dockets: case name contains RELIANT CARE, DESTEFANE, or a distinctive Reliant home/entity name; Missouri/Kansas/8th Cir/appellate courts shown with court id
select COURT_ID, DOCKET_NUMBER, DATE_FILED, DATE_TERMINATED, CASE_NAME, NATURE_OF_SUIT, CAUSE, ID
from LIBRARY_MARTS.JUSTICE.JUSTICE__FED_COURTLISTENER_DOCKETS
where regexp_like(upper(CASE_NAME), '.*(RELIANT CARE|RELIANTCARE|DESTEFANE|NORTH VILLAGE PARK|BRIDGEWOOD HEALTH|GREGORY RIDGE HEALTH|HERITAGE CARE CENTER|CRESTWOOD HEALTH CARE CENTER|CHARITON PARK|EASTVIEW MANOR|FOUR SEASONS LIVING|EDGEWOOD MANOR HEALTH|NATHAN RICHARD|BERNARD CARE|GIETNER|HIDDEN LAKE HEALTH|PARKWAY HEALTH CARE|NICK.?S HEALTH CARE|PORTAGEVILLE HEALTH|WESTVIEW NURSING|MMA HEALTHCARE OF|BKY HEALTHCARE|REST HAVEN HEALTH CARE|WELLSVILLE HEALTH|HOLTON HEALTH|SARCOXIE HEALTH|STONECREST HEALTH|MILAN HEALTH CARE).*')
order by DATE_FILED desc
