-- Provider Relief Fund, second pass: MO/KS lines for the Reliant homes the first name-prefix pass missed (corporate names MMA/BKY/EASTVIEW MANOR INC, and every 2024-25 acquisition, whose 2020-21 money went to the prior operator)
select PROVIDER_NAME, CITY, STATE, PAYMENT_AMOUNT
from LIBRARY_MARTS.HEALTH.HEALTH__FED_HRSA_PROVIDER_RELIEF_FUND
where STATE in ('MO','KS') and regexp_like(upper(PROVIDER_NAME), '.*(MMA HEALTHCARE|BKY HEALTHCARE|EASTVIEW MANOR|BERNARD CARE|WESTVIEW NURSING|MILAN HEALTH|STONECREST|ST\.? ELIZABETH CARE|HIDDEN LAKE|SOUTH COUNTY HEALTH|BROOKFIELD HEALTH|SARCOXIE|ODESSA HEALTH|HOLTON HEALTH|BRUNSWICK HEALTH|GIETNER|WELLSVILLE HEALTH|REST HAVEN HEALTH|FAIR VIEW HEALTH|FAIRVIEW HEALTH|GRAND MANOR|CASSVILLE HEALTH|RELIANT).*')
order by PROVIDER_NAME
