{{ config(tags=['spine_generated']) }}

-- GRAIN: one row per place (SAFEGRAPH_PLACE_ID unique)
-- SPINE_ENTITY: place  (natural_key: SAFEGRAPH_PLACE_ID)
-- Generated by scripts/generate_staging_models.py from SOURCE_REGISTRY -- deterministic,
-- no LLM. Casts kept as landed (TEXT) -- add explicit type casts by hand once each
-- column's real type is confirmed; this generator has no semantic type knowledge.
-- spine_entity 'place' has no connect/ resolver yet (see connect/spine_entity.py) -- no SPINE_ENTITY_ID emitted.
-- landing table's ingestion timestamp is named INGESTED_AT (no leading underscore) rather than the usual _INGESTED_AT -- confirmed via INFORMATION_SCHEMA, not assumed.

with source as (

    select * from {{ source('ripple_raw', 'PORTAL_ARC_LA_COUNTY_OPEN_D_2E79EB67C8') }}

),

renamed as (

    select
        "OBJECTID_1" as objectid_1,
        "LOCATION_NAME" as location_name,
        "STREET_ADDRESS" as street_address,
        "STREET_NAME" as street_name,
        "CITY" as city,
        "REGION" as region,
        "POSTAL_CODE" as postal_code,
        "NAICS_CODE" as naics_code,
        "BRANDS" as brands,
        "PHONE_NUMBER" as phone_number,
        "SOURCE" as source,
        "SAFEGRAPH_PLACE_ID" as safegraph_place_id,
        "DESC" as desc,
        "LATITUDE" as latitude,
        "LONGITUDE" as longitude,
        "CREATIONDATE" as creationdate,
        "CREATOR" as creator,
        "EDITDATE" as editdate,
        "EDITOR" as editor,
        "OBJECTID" as objectid,
        "JOIN_COUNT" as join_count,
        "TARGET_FID" as target_fid,
        "TRACTCE" as tractce,
        "GEOID" as geoid,
        "GEO_ID_FULL" as geo_id_full,
        "GEO_ID" as geo_id,
        "OVERALL_INDEX" as overall_index,
        "INDEX_CATEGORY" as index_category,
        "GEOMETRY" as geometry,
        INGESTED_AT as _loaded_at,
        'https://data.lacounty.gov/datasets/682f52458e3f40439caecae2c86810ee_1' as _source_url

    from source

)

select * from renamed
qualify row_number() over (partition by safegraph_place_id order by _loaded_at desc) = 1
