{{ config(tags=['spine_generated']) }}

-- GRAIN: one row per record (spine_entity not determined -- no registry hint available) (DATASET_ID is unique)
-- SPINE_ENTITY: (not determined)  (natural_key: DATASET_ID)
-- Generated by scripts/generate_staging_models.py from SOURCE_REGISTRY -- deterministic,
-- no LLM. Casts kept as landed (TEXT) -- add explicit type casts by hand once each
-- column's real type is confirmed; this generator has no semantic type knowledge.
-- spine_entity not determined (grain/natural_key proven, but no registry hint says what this row is ABOUT) -- no SPINE_ENTITY_ID emitted.

with source as (

    select * from {{ source('ripple_raw', 'INTL_DE_GOVDATA') }}

),

renamed as (

    select
        "DATASET_ID" as dataset_id,
        "TITLE" as title,
        "NAME" as name,
        "PUBLISHER" as publisher,
        "DESCRIPTION" as description,
        "TAGS" as tags,
        "GROUPS" as groups,
        "LICENSE_ID" as license_id,
        "METADATA_CREATED" as metadata_created,
        "METADATA_MODIFIED" as metadata_modified,
        "TEMPORAL_START" as temporal_start,
        "TEMPORAL_END" as temporal_end,
        "SPATIAL" as spatial,
        "IS_HVD" as is_hvd,
        "RESOURCES" as resources,
        "EXTRAS" as extras,
        _INGESTED_AT as _loaded_at,
        'https://www.govdata.de/' as _source_url

    from source

)

select * from renamed
qualify row_number() over (partition by dataset_id order by _loaded_at desc) = 1
