{{ config(materialized='table', schema='TIMELINE') }}

-- GENERATED by scripts/census/gen_time_views.py -- do not hand-edit.
--
-- The 50 clocked tables in the politics domain, rolled up to one row per
-- (source, clock kind, grain, day). Counting only -- no row detail, so
-- this stays small enough to scan across the whole warehouse at once.
-- Drill into the matching view in LIBRARY_MARTS.TIMELINE for the rows.
--
-- NOTE ON GRAIN: a year-grain source snaps to Jan 1 and a month-grain
-- source to the 1st, per rule 2. ripple_grain is what stops that from
-- reading as a real New Year's Day spike -- always filter or facet on
-- it before drawing a daily chart.

select ripple_source, ripple_clock, ripple_grain,
       date_trunc('day', ripple_ts)::date as ripple_day,
       count(*) as n_rows
from {{ ref('timeline__politics__bills') }}
where ripple_ts is not null
group by 1, 2, 3, 4
union all

select ripple_source, ripple_clock, ripple_grain,
       date_trunc('day', ripple_ts)::date as ripple_day,
       count(*) as n_rows
from {{ ref('timeline__politics__bill_cosponsors') }}
where ripple_ts is not null
group by 1, 2, 3, 4
union all

select ripple_source, ripple_clock, ripple_grain,
       date_trunc('day', ripple_ts)::date as ripple_day,
       count(*) as n_rows
from {{ ref('timeline__politics__ca_lobby_amendments') }}
where ripple_ts is not null
group by 1, 2, 3, 4
union all

select ripple_source, ripple_clock, ripple_grain,
       date_trunc('day', ripple_ts)::date as ripple_day,
       count(*) as n_rows
from {{ ref('timeline__politics__ca_lobby_chg_log') }}
where ripple_ts is not null
group by 1, 2, 3, 4
union all

select ripple_source, ripple_clock, ripple_grain,
       date_trunc('day', ripple_ts)::date as ripple_day,
       count(*) as n_rows
from {{ ref('timeline__politics__ca_lobby_contributions') }}
where ripple_ts is not null
group by 1, 2, 3, 4
union all

select ripple_source, ripple_clock, ripple_grain,
       date_trunc('day', ripple_ts)::date as ripple_day,
       count(*) as n_rows
from {{ ref('timeline__politics__ca_lobby_cover') }}
where ripple_ts is not null
group by 1, 2, 3, 4
union all

select ripple_source, ripple_clock, ripple_grain,
       date_trunc('day', ripple_ts)::date as ripple_day,
       count(*) as n_rows
from {{ ref('timeline__politics__ca_lobby_employer') }}
where ripple_ts is not null
group by 1, 2, 3, 4
union all

select ripple_source, ripple_clock, ripple_grain,
       date_trunc('day', ripple_ts)::date as ripple_day,
       count(*) as n_rows
from {{ ref('timeline__politics__ca_lobby_firm') }}
where ripple_ts is not null
group by 1, 2, 3, 4
union all

select ripple_source, ripple_clock, ripple_grain,
       date_trunc('day', ripple_ts)::date as ripple_day,
       count(*) as n_rows
from {{ ref('timeline__politics__ca_lobby_firm_employer') }}
where ripple_ts is not null
group by 1, 2, 3, 4
union all

select ripple_source, ripple_clock, ripple_grain,
       date_trunc('day', ripple_ts)::date as ripple_day,
       count(*) as n_rows
from {{ ref('timeline__politics__fec_candidate') }}
where ripple_ts is not null
group by 1, 2, 3, 4
union all

select ripple_source, ripple_clock, ripple_grain,
       date_trunc('day', ripple_ts)::date as ripple_day,
       count(*) as n_rows
from {{ ref('timeline__politics__fec_candidate_summary') }}
where ripple_ts is not null
group by 1, 2, 3, 4
union all

select ripple_source, ripple_clock, ripple_grain,
       date_trunc('day', ripple_ts)::date as ripple_day,
       count(*) as n_rows
from {{ ref('timeline__politics__fec_cand_cmte_link') }}
where ripple_ts is not null
group by 1, 2, 3, 4
union all

select ripple_source, ripple_clock, ripple_grain,
       date_trunc('day', ripple_ts)::date as ripple_day,
       count(*) as n_rows
from {{ ref('timeline__politics__fed_congress_legislators') }}
where ripple_ts is not null
group by 1, 2, 3, 4
union all

select ripple_source, ripple_clock, ripple_grain,
       date_trunc('day', ripple_ts)::date as ripple_day,
       count(*) as n_rows
from {{ ref('timeline__politics__fed_fcc_licensing') }}
where ripple_ts is not null
group by 1, 2, 3, 4
union all

select ripple_source, ripple_clock, ripple_grain,
       date_trunc('day', ripple_ts)::date as ripple_day,
       count(*) as n_rows
from {{ ref('timeline__politics__fed_fec_api') }}
where ripple_ts is not null
group by 1, 2, 3, 4
union all

select ripple_source, ripple_clock, ripple_grain,
       date_trunc('day', ripple_ts)::date as ripple_day,
       count(*) as n_rows
from {{ ref('timeline__politics__fed_fec_pac_summary') }}
where ripple_ts is not null
group by 1, 2, 3, 4
union all

select ripple_source, ripple_clock, ripple_grain,
       date_trunc('day', ripple_ts)::date as ripple_day,
       count(*) as n_rows
from {{ ref('timeline__politics__fed_fjc_judges') }}
where ripple_ts is not null
group by 1, 2, 3, 4
union all

select ripple_source, ripple_clock, ripple_grain,
       date_trunc('day', ripple_ts)::date as ripple_day,
       count(*) as n_rows
from {{ ref('timeline__politics__fed_fjc_service') }}
where ripple_ts is not null
group by 1, 2, 3, 4
union all

select ripple_source, ripple_clock, ripple_grain,
       date_trunc('day', ripple_ts)::date as ripple_day,
       count(*) as n_rows
from {{ ref('timeline__politics__fed_medsl_house_returns') }}
where ripple_ts is not null
group by 1, 2, 3, 4
union all

select ripple_source, ripple_clock, ripple_grain,
       date_trunc('day', ripple_ts)::date as ripple_day,
       count(*) as n_rows
from {{ ref('timeline__politics__fed_medsl_president_returns') }}
where ripple_ts is not null
group by 1, 2, 3, 4
union all

select ripple_source, ripple_clock, ripple_grain,
       date_trunc('day', ripple_ts)::date as ripple_day,
       count(*) as n_rows
from {{ ref('timeline__politics__fed_medsl_senate_returns') }}
where ripple_ts is not null
group by 1, 2, 3, 4
union all

select ripple_source, ripple_clock, ripple_grain,
       date_trunc('day', ripple_ts)::date as ripple_day,
       count(*) as n_rows
from {{ ref('timeline__politics__fed_voteview_rollcall_meta') }}
where ripple_ts is not null
group by 1, 2, 3, 4
union all

select ripple_source, ripple_clock, ripple_grain,
       date_trunc('day', ripple_ts)::date as ripple_day,
       count(*) as n_rows
from {{ ref('timeline__politics__intl_elections_canada_contributions') }}
where ripple_ts is not null
group by 1, 2, 3, 4
union all

select ripple_source, ripple_clock, ripple_grain,
       date_trunc('day', ripple_ts)::date as ripple_day,
       count(*) as n_rows
from {{ ref('timeline__politics__intl_owid_milspend') }}
where ripple_ts is not null
group by 1, 2, 3, 4
union all

select ripple_source, ripple_clock, ripple_grain,
       date_trunc('day', ripple_ts)::date as ripple_day,
       count(*) as n_rows
from {{ ref('timeline__politics__intl_voeten_unga_votes') }}
where ripple_ts is not null
group by 1, 2, 3, 4
union all

select ripple_source, ripple_clock, ripple_grain,
       date_trunc('day', ripple_ts)::date as ripple_day,
       count(*) as n_rows
from {{ ref('timeline__politics__irs527_8871_orgs') }}
where ripple_ts is not null
group by 1, 2, 3, 4
union all

select ripple_source, ripple_clock, ripple_grain,
       date_trunc('day', ripple_ts)::date as ripple_day,
       count(*) as n_rows
from {{ ref('timeline__politics__irs527_8872_reports') }}
where ripple_ts is not null
group by 1, 2, 3, 4
union all

select ripple_source, ripple_clock, ripple_grain,
       date_trunc('day', ripple_ts)::date as ripple_day,
       count(*) as n_rows
from {{ ref('timeline__politics__member_crosswalk') }}
where ripple_ts is not null
group by 1, 2, 3, 4
union all

select ripple_source, ripple_clock, ripple_grain,
       date_trunc('day', ripple_ts)::date as ripple_day,
       count(*) as n_rows
from {{ ref('timeline__politics__member_money_raised') }}
where ripple_ts is not null
group by 1, 2, 3, 4
union all

select ripple_source, ripple_clock, ripple_grain,
       date_trunc('day', ripple_ts)::date as ripple_day,
       count(*) as n_rows
from {{ ref('timeline__politics__member_spine') }}
where ripple_ts is not null
group by 1, 2, 3, 4
union all

select ripple_source, ripple_clock, ripple_grain,
       date_trunc('day', ripple_ts)::date as ripple_day,
       count(*) as n_rows
from {{ ref('timeline__politics__st_cannabis_policy_bundles') }}
where ripple_ts is not null
group by 1, 2, 3, 4
union all

select ripple_source, ripple_clock, ripple_grain,
       date_trunc('day', ripple_ts)::date as ripple_day,
       count(*) as n_rows
from {{ ref('timeline__politics__st_nyc_cfb_campaign_2001_contribution') }}
where ripple_ts is not null
group by 1, 2, 3, 4
union all

select ripple_source, ripple_clock, ripple_grain,
       date_trunc('day', ripple_ts)::date as ripple_day,
       count(*) as n_rows
from {{ ref('timeline__politics__st_nyc_cfb_campaign_2009_contribution') }}
where ripple_ts is not null
group by 1, 2, 3, 4
union all

select ripple_source, ripple_clock, ripple_grain,
       date_trunc('day', ripple_ts)::date as ripple_day,
       count(*) as n_rows
from {{ ref('timeline__politics__st_nyc_cfb_campaign_2013_contribution') }}
where ripple_ts is not null
group by 1, 2, 3, 4
union all

select ripple_source, ripple_clock, ripple_grain,
       date_trunc('day', ripple_ts)::date as ripple_day,
       count(*) as n_rows
from {{ ref('timeline__politics__st_nyc_cfb_campaign_2021_contributions') }}
where ripple_ts is not null
group by 1, 2, 3, 4
union all

select ripple_source, ripple_clock, ripple_grain,
       date_trunc('day', ripple_ts)::date as ripple_day,
       count(*) as n_rows
from {{ ref('timeline__politics__st_nyc_cfb_campaign_2025_contributions') }}
where ripple_ts is not null
group by 1, 2, 3, 4
union all

select ripple_source, ripple_clock, ripple_grain,
       date_trunc('day', ripple_ts)::date as ripple_day,
       count(*) as n_rows
from {{ ref('timeline__politics__tx_lobby_awards') }}
where ripple_ts is not null
group by 1, 2, 3, 4
union all

select ripple_source, ripple_clock, ripple_grain,
       date_trunc('day', ripple_ts)::date as ripple_day,
       count(*) as n_rows
from {{ ref('timeline__politics__tx_lobby_cover') }}
where ripple_ts is not null
group by 1, 2, 3, 4
union all

select ripple_source, ripple_clock, ripple_grain,
       date_trunc('day', ripple_ts)::date as ripple_day,
       count(*) as n_rows
from {{ ref('timeline__politics__tx_lobby_dockets') }}
where ripple_ts is not null
group by 1, 2, 3, 4
union all

select ripple_source, ripple_clock, ripple_grain,
       date_trunc('day', ripple_ts)::date as ripple_day,
       count(*) as n_rows
from {{ ref('timeline__politics__tx_lobby_entertainment') }}
where ripple_ts is not null
group by 1, 2, 3, 4
union all

select ripple_source, ripple_clock, ripple_grain,
       date_trunc('day', ripple_ts)::date as ripple_day,
       count(*) as n_rows
from {{ ref('timeline__politics__tx_lobby_events') }}
where ripple_ts is not null
group by 1, 2, 3, 4
union all

select ripple_source, ripple_clock, ripple_grain,
       date_trunc('day', ripple_ts)::date as ripple_day,
       count(*) as n_rows
from {{ ref('timeline__politics__tx_lobby_food_beverage') }}
where ripple_ts is not null
group by 1, 2, 3, 4
union all

select ripple_source, ripple_clock, ripple_grain,
       date_trunc('day', ripple_ts)::date as ripple_day,
       count(*) as n_rows
from {{ ref('timeline__politics__tx_lobby_gifts') }}
where ripple_ts is not null
group by 1, 2, 3, 4
union all

select ripple_source, ripple_clock, ripple_grain,
       date_trunc('day', ripple_ts)::date as ripple_day,
       count(*) as n_rows
from {{ ref('timeline__politics__tx_lobby_individual_reporting') }}
where ripple_ts is not null
group by 1, 2, 3, 4
union all

select ripple_source, ripple_clock, ripple_grain,
       date_trunc('day', ripple_ts)::date as ripple_day,
       count(*) as n_rows
from {{ ref('timeline__politics__tx_lobby_subject_matter') }}
where ripple_ts is not null
group by 1, 2, 3, 4
union all

select ripple_source, ripple_clock, ripple_grain,
       date_trunc('day', ripple_ts)::date as ripple_day,
       count(*) as n_rows
from {{ ref('timeline__politics__tx_lobby_transportation') }}
where ripple_ts is not null
group by 1, 2, 3, 4
union all

select ripple_source, ripple_clock, ripple_grain,
       date_trunc('day', ripple_ts)::date as ripple_day,
       count(*) as n_rows
from {{ ref('timeline__politics__voteview_rollcalls') }}
where ripple_ts is not null
group by 1, 2, 3, 4
union all

select ripple_source, ripple_clock, ripple_grain,
       date_trunc('day', ripple_ts)::date as ripple_day,
       count(*) as n_rows
from {{ ref('timeline__politics__xc_jcs_medians') }}
where ripple_ts is not null
group by 1, 2, 3, 4
union all

select ripple_source, ripple_clock, ripple_grain,
       date_trunc('day', ripple_ts)::date as ripple_day,
       count(*) as n_rows
from {{ ref('timeline__politics__xc_jcs_scotus') }}
where ripple_ts is not null
group by 1, 2, 3, 4
union all

select ripple_source, ripple_clock, ripple_grain,
       date_trunc('day', ripple_ts)::date as ripple_day,
       count(*) as n_rows
from {{ ref('timeline__politics__xc_owid_cpi') }}
where ripple_ts is not null
group by 1, 2, 3, 4
