-- SERVE_WH / SERVE_MON DDL is canonical in serve/serve_wh.sql — do not duplicate it here.
--
-- This file used to byte-duplicate that DDL (CREATE WAREHOUSE SERVE_WH +
-- RESOURCE MONITOR SERVE_MON + GRANT USAGE to CLAUDE_MCP_READONLY). Two
-- byte-divergent copies of the same warehouse + monitor will drift — e.g. a
-- quota change applied to one but not the other — which is exactly the
-- live-state-vs-codified-state problem this infra/ddl dir exists to prevent.
-- The serving-layer copy is the single source of truth: serve/serve_session.py
-- and serve/README.md both reference serve/serve_wh.sql.
--
-- To (re)create the serving warehouse, run as ACCOUNTADMIN:
--     snowsql -f serve/serve_wh.sql
--
-- See infra/ddl/README.md (row 05) for where this fits in the DR rebuild.
