{{ config(materialized='table', schema='ENVIRONMENT') }}

-- Source: FED_EPA_ICIS_AIR_ICIS_AIR_STACK_TESTS (620,302 rows)  [row count re-verified against the live table 2026-08-11; header had said 500000]
-- Generated by scripts/gen_mart_models.py

with source as (
    select * from {{ source('ripple_raw', 'FED_EPA_ICIS_AIR_ICIS_AIR_STACK_TESTS') }}
)

select
    PGM_SYS_ID as pgm_sys_id,
    ACTIVITY_ID as activity_id,
    COMP_MONITOR_TYPE_CODE as comp_monitor_type_code,
    COMP_MONITOR_TYPE_DESC as comp_monitor_type_desc,
    STATE_EPA_FLAG as state_epa_flag,
    try_to_date(ACTUAL_END_DATE) as actual_end_date,
    POLLUTANT_CODES as pollutant_codes,
    POLLUTANT_DESCS as pollutant_descs,
    AIR_STACK_TEST_STATUS_CODE as air_stack_test_status_code,
    AIR_STACK_TEST_STATUS_DESC as air_stack_test_status_desc
from source
