{{ config(materialized='table', schema='ENVIRONMENT') }}

-- Source: Weather.gov API (National Weather Service) (287 rows)
-- Generated by gen_mart_models.py
-- Fixed 2026-09-20: was reading source() with bare try_to_number()/try_to_double()/try_to_date() casts, which silently round decimals or mis-parse dates instead of guarding them. Now reads the already-guarded staging model (stg_fed_noaa_weather_api__records) instead -- same columns, same names, same order; every numeric/date cast there is regex-guarded (macros/staging_casts.sql): a value that doesn't parse cleanly reads NULL instead of a silently wrong value.

select
    id,
    type,
    event,
    status,
    message_type,
    severity,
    certainty,
    urgency,
    area_desc,
    sent,
    effective,
    onset,
    expires,
    ends,
    headline,
    description,
    instruction,
    sender_name,
    zone_ugc,
    geometry,
    station_id,
    temperature,
    wind_speed,
    wind_direction,
    timestamp,
    forecast_office,
    grid_x,
    grid_y,
    latitude,
    longitude,
    fips_code,
    zip_code
from {{ ref('stg_fed_noaa_weather_api__records') }}
