{{ config(materialized='table', schema='ENVIRONMENT') }}

-- Source: FED_EPA_RCRA_RCRA_VIOLATIONS (708114 rows)
-- Generated by scripts/gen_mart_models.py

with source as (
    select * from {{ source('ripple_raw', 'FED_EPA_RCRA_RCRA_VIOLATIONS') }}
)

select
    ID_NUMBER as id_number,
    ACTIVITY_LOCATION as activity_location,
    VIOLATION_TYPE as violation_type,
    VIOLATION_TYPE_DESC as violation_type_desc,
    VIOL_DETERMINED_BY_AGENCY as viol_determined_by_agency,
    try_to_date(DATE_VIOLATION_DETERMINED) as date_violation_determined,
    try_to_date(ACTUAL_RTC_DATE) as actual_rtc_date,
    try_to_date(SCHEDULED_COMPLIANCE_DATE) as scheduled_compliance_date
from source
