{{ config(materialized='table', schema='ENVIRONMENT') }}

-- Source: FED_EPA_NPDES_NPDES_CS_VIOLATIONS (82044 rows)
-- Generated by scripts/gen_mart_models.py
-- Fixed 2026-09-20: was reading source() with 5 bare try_to_date() casts, no
-- guard against a pure-digit value misreading as an epoch date. Not live-
-- checked column-by-column for this table specifically -- fixed as a landmine
-- regardless (see environment__fed_epa_sdwa_sdwa_violations_enforcement.sql /
-- environment__fed_epa_sdwa_sdwa_pub_water_systems.sql for the live before/
-- after proof run on this same bug pattern elsewhere in this batch). Column
-- list matches models/staging/fed_epa_npdes_npdes_cs_violations exactly, so
-- swapped to ref() instead of hand-wrapping: same 18 columns, same names, same
-- order, every cast regex-guarded (stg_int/stg_date, macros/staging_casts.sql).
-- Bonus from the swap: COMP_SCHEDULE_EVENT_ID and COMP_SCHEDULE_NMBR now arrive
-- cast to a guarded whole number (stg_int) instead of raw uncast text.

select
    npdes_id,
    npdes_violation_id,
    violation_type_code,
    comp_schedule_event_id,
    comp_schedule_nmbr,
    violation_code,
    violation_desc,
    schedule_event_code,
    schedule_event_desc,
    schedule_date,
    actual_date,
    rnc_detection_code,
    rnc_detection_desc,
    rnc_detection_date,
    rnc_resolution_code,
    rnc_resolution_desc,
    rnc_resolution_date,
    report_received_date
from {{ ref('stg_fed_epa_npdes_npdes_cs_violations__records') }}
