{{ config(materialized='table', schema='ENVIRONMENT') }}

-- Source: Global Witness ? Land and Environmental Defenders Database (232 rows)
-- Generated by gen_mart_models.py
-- Fixed 2026-09-20: was reading source() with bare try_to_number()/try_to_double()/try_to_date() casts, which silently round decimals or mis-parse dates instead of guarding them. Now reads the already-guarded staging model (stg_intl_global_witness_defenders__records) instead -- same columns, same names, same order; every numeric/date cast there is regex-guarded (macros/staging_casts.sql): a value that doesn't parse cleanly reads NULL instead of a silently wrong value.

select
    defender_name,
    country,
    region,
    year,
    incident_type,
    sector,
    indigenous_status,
    gender,
    perpetrator,
    source_report,
    notes_context
from {{ ref('stg_intl_global_witness_defenders__records') }}
