{{ config(materialized='table', schema='ENVIRONMENT') }}

-- Source: FED_EPA_SDWA_SDWA_GEOGRAPHIC_AREAS (578,198 rows)  [row count re-verified against the live table 2026-08-11; header had said 500000]
-- Generated by scripts/gen_mart_models.py

with source as (
    select * from {{ source('ripple_raw', 'FED_EPA_SDWA_SDWA_GEOGRAPHIC_AREAS') }}
)

select
    SUBMISSIONYEARQUARTER as submissionyearquarter,
    PWSID as pwsid,
    GEO_ID as geo_id,
    AREA_TYPE_CODE as area_type_code,
    TRIBAL_CODE as tribal_code,
    STATE_SERVED as state_served,
    ANSI_ENTITY_CODE as ansi_entity_code,
    ZIP_CODE_SERVED as zip_code_served,
    CITY_SERVED as city_served,
    COUNTY_SERVED as county_served,
    try_to_date(LAST_REPORTED_DATE) as last_reported_date
from source
