{{ config(materialized='table', schema='IMMIGRATION') }}

-- Source: FED_EPA_SDWA_SDWA_SERVICE_AREAS (422464 rows)
-- Generated by scripts/gen_mart_models.py
-- Fixed 2026-09-20: FIRST_REPORTED_DATE/LAST_REPORTED_DATE were bare
-- try_to_date() calls, no guard against a pure-digit value misreading as an
-- epoch date. Not live-checked for this table specifically -- fixed as a
-- landmine regardless (see environment__fed_epa_sdwa_sdwa_violations_
-- enforcement.sql / environment__fed_epa_sdwa_sdwa_pub_water_systems.sql for
-- the live before/after proof run on this same bug pattern elsewhere in this
-- batch). Kept on source() (not ref()): the sibling staging model
-- (models/staging/fed_epa_sdwa_sdwa_service_areas) casts none of its 6 columns
-- at all (none of them fully parsed in its 10K-row sample), so swapping to
-- ref() would have demoted both currently-working DATE columns to TEXT.
-- Wrapped both in place with stg_date instead (macros/staging_casts.sql).

with source as (
    select * from {{ source('ripple_raw', 'FED_EPA_SDWA_SDWA_SERVICE_AREAS') }}
)

select
    SUBMISSIONYEARQUARTER as submissionyearquarter,
    PWSID as pwsid,
    SERVICE_AREA_TYPE_CODE as service_area_type_code,
    IS_PRIMARY_SERVICE_AREA_CODE as is_primary_service_area_code,
    {{ stg_date('"FIRST_REPORTED_DATE"') }} as first_reported_date,
    {{ stg_date('"LAST_REPORTED_DATE"') }} as last_reported_date
from source
