-- Q8: [save:enr_ltch] Medicare enrollment rows for today's LTCH CCNs: the legal owner name, to check the brand-name chain grouping with a second field
SELECT CCN, ENROLLMENT_ID, ASSOCIATE_ID, ORGANIZATION_NAME, DOING_BUSINESS_AS_NAME, INCORPORATION_STATE, ORGANIZATION_TYPE_STRUCTURE,
       PROPRIETARY_NONPROFIT, CITY, STATE, SUBGROUP_LONG_TERM
FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_HOSPITAL_ENROLLMENTS
WHERE CCN IN (SELECT CCN FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_LTCH);
