{{ config(materialized='table', schema='UNCATEGORIZED') }}

-- Source: FED_OCC_NATIONAL_BANKS_BY_NAME (62 rows)
-- Generated by scripts/gen_mart_models.py

with source as (
    select * from {{ source('ripple_raw', 'FED_OCC_NATIONAL_BANKS_BY_NAME') }}
)

select
    UNNAMED_0 as unnamed_0,
    UNNAMED_1 as unnamed_1,
    UNNAMED_2 as unnamed_2,
    UNNAMED_3 as unnamed_3,
    UNNAMED_4 as unnamed_4,
    C_8103 as c_8103,
    ADC_UPSTATE_NEW_YORK_SYRACUSE as adc_upstate_new_york_syracuse
from source
