{{ config(enabled=false, materialized='table', schema='UNCATEGORIZED') }}
-- DISABLED 2026-08-26 (uncategorized-bucket dedup): the same OEHHA Prop 65 list
-- under an older landing name (1,021 rows vs 1,055 in ST_CA_OEHHA_PROP65_CHEMICALS,
-- which is the keeper and was refiled to environment). On drop list.

-- Source: STATE_OEHHA_PROP65_CHEMICALS (1021 rows)
-- Generated by scripts/gen_mart_models.py
-- Fixed 2026-09-20: DATE_LISTED was a bare try_to_date() -- a pure-digit
-- value would misread as epoch seconds instead of failing safely. No staging
-- model matches this source: models/staging/st_oehha_proposition_65_list
-- reads a DIFFERENT, newer landing table (ST_OEHHA_PROPOSITION_65_LIST, the
-- 1,055-row keeper this disabled duplicate mart points away from, per the
-- header above), so wrapped the one bare cast in place. This model stays
-- disabled (drop-list duplicate, see above) -- fixed anyway since it's a
-- landmine either way.

with source as (
    select * from {{ source('ripple_raw', 'STATE_OEHHA_PROP65_CHEMICALS') }}
)

select
    CHEMICAL as chemical,
    TYPE_OF_TOXICITY as type_of_toxicity,
    LISTING_MECHANISM as listing_mechanism,
    CAS_NO as cas_no,
    {{ stg_date('DATE_LISTED') }} as date_listed,
    NSRL_OR_MADL_G_DAY_A as nsrl_or_madl_g_day_a
from source
