{{ config(enabled=false, materialized='table', schema='UNCATEGORIZED') }}
-- DISABLED 2026-08-26 (uncategorized-bucket dedup): third landing copy of the same
-- ICIJ edges — duplicate of CORPORATE_REGISTRY__FED_ICIJ_OFFSHORELEAKS_RELATIONSHIPS.
-- On drop list.

-- Source: XC_ICIJ_OFFSHORE_RELATIONSHIPS (3339267 rows)
-- Generated by scripts/gen_mart_models.py

with source as (
    select * from {{ source('ripple_raw', 'XC_ICIJ_OFFSHORE_RELATIONSHIPS') }}
)

select
    NODE_ID_START as node_id_start,
    NODE_ID_END as node_id_end,
    REL_TYPE as rel_type,
    LINK as link,
    STATUS as status,
    try_to_date(START_DATE) as start_date,
    try_to_date(END_DATE) as end_date,
    SOURCEID as sourceid
from source
