{{ config(materialized='view', schema='TIMELINE', alias='ECONOMICS__FED_TREASURY_DEBT_TO_PENNY') }}

-- GENERATED by scripts/census/gen_time_views.py -- do not hand-edit.
-- Regenerate after any change to reports/time_index/clock_index.csv.
--
-- Canonical clock for ECONOMICS.ECONOMICS__FED_TREASURY_DEBT_TO_PENNY.
--   column : RECORD_DATE   (DATE)
--   means  : happened -- The model description states each row is one daily debt snapshot, and the census window 1993-04-01 to 2026-06-15 over 8,329 rows matches business-daily coverage
--   grain  : day
--
-- The original columns pass through untouched; the canonical four sit in front
-- of them. Rule 8 of the datetime standard: the raw column is never overwritten,
-- so a mis-parse is always recoverable.

select
    {{ ripple_event_ts(ripple_window('src."RECORD_DATE"::timestamp_ntz')) }} as ripple_ts,
    {{ ripple_grain('day') }} as ripple_grain,
    {{ ripple_clock('happened') }} as ripple_clock,
    'ECONOMICS.ECONOMICS__FED_TREASURY_DEBT_TO_PENNY'::varchar as ripple_source,
    src.*
from {{ ref('economics__fed_treasury_debt_to_penny') }} as src
