{{ config(materialized='view', schema='TIMELINE', alias='ECONOMICS__FED_IRS_990_EFILE_INDEX') }}

-- GENERATED by scripts/census/gen_time_views.py -- do not hand-edit.
-- Regenerate after any change to reports/time_index/clock_index.csv.
--
-- Canonical clock for ECONOMICS.ECONOMICS__FED_IRS_990_EFILE_INDEX.
--   column : SUB_DATE   (DATE)
--   means  : reported -- The submission date to the IRS, now parsed by three explicit strict formats after the documented 2026-08-18 fix; grain is only YEAR because the model's own comm
--   grain  : day
--
-- The original columns pass through untouched; the canonical four sit in front
-- of them. Rule 8 of the datetime standard: the raw column is never overwritten,
-- so a mis-parse is always recoverable.

select
    {{ ripple_event_ts(ripple_window('src."SUB_DATE"::timestamp_ntz')) }} as ripple_ts,
    {{ ripple_grain('day') }} as ripple_grain,
    {{ ripple_clock('reported') }} as ripple_clock,
    'ECONOMICS.ECONOMICS__FED_IRS_990_EFILE_INDEX'::varchar as ripple_source,
    src.*
from {{ ref('economics__fed_irs_990_efile_index') }} as src
