{{ config(materialized='view', schema='TIMELINE', alias='ECONOMICS__FED_IRS_990') }}

-- GENERATED by scripts/census/gen_time_views.py -- do not hand-edit.
-- Regenerate after any change to reports/time_index/clock_index.csv.
--
-- Canonical clock for ECONOMICS.ECONOMICS__FED_IRS_990.
--   column : TAX_YEAR   (NUMBER)
--   means  : span_start -- try_to_number(taxyr) is a plain year integer labelling the same covered period at coarser resolution; safe as a number, dangerous if ever cast to a date.
--   grain  : month
--
-- The original columns pass through untouched; the canonical four sit in front
-- of them. Rule 8 of the datetime standard: the raw column is never overwritten,
-- so a mis-parse is always recoverable.

select
    {{ ripple_ts_from_yyyymm('src."TAX_YEAR"') }} as ripple_ts,
    {{ ripple_grain('month') }} as ripple_grain,
    {{ ripple_clock('span_start') }} as ripple_clock,
    'ECONOMICS.ECONOMICS__FED_IRS_990'::varchar as ripple_source,
    src.*
from {{ ref('economics__fed_irs_990') }} as src
