{{ config(tags=['spine_generated']) }}

-- GRAIN: one row per place (GEOM is unique)
-- SPINE_ENTITY: place  (natural_key: GEOMETRY)
-- Generated by scripts/generate_staging_models.py from SOURCE_REGISTRY -- deterministic,
-- no LLM.
-- CASTS: 28 of 120 columns, from landing_column_profile_2026-09-19.tsv. A column is cast only
-- when every filled value in the sample parsed. try_ casts: a value that does not
-- parse reads NULL. The natural key and join-key columns stay TEXT.
--   fid: ID: whole numbers, over 90% distinct -- stays TEXT, '.0' tail removed
--   objectid: ID: whole numbers, over 90% distinct -- stays TEXT, '.0' tail removed
--   score: float
--   rank: float
--   addnum: ID: whole numbers, over 90% distinct -- stays TEXT, '.0' tail removed
--   addnumfrom: ID: whole numbers, over 90% distinct -- stays TEXT, '.0' tail removed
--   addnumto: ID: whole numbers, over 90% distinct -- stays TEXT, '.0' tail removed
--   postal: integer
--   distance: float
--   x: float
--   y: float
--   displayx: float
--   displayy: float
--   xmin: float
--   xmax: float
--   ymin: float
--   ymax: float
--   user_count: integer
--   user_esc_r: integer
--   user_esc_1: integer
--   user_esc_2: integer
--   user_distr: integer
--   user_dis16: integer
--   user_schoo: ID: whole numbers, over 90% distinct -- stays TEXT, '.0' tail removed
--   user_nce_1: ID: whole numbers, over 90% distinct -- stays TEXT, '.0' tail removed
--   user_sch15: ID: whole numbers, over 90% distinct -- stays TEXT, '.0' tail removed
--   user_sch17: integer
--   precinct: integer
-- spine_entity 'place' has no connect/ resolver yet (see connect/spine_entity.py) -- no SPINE_ENTITY_ID emitted.
-- landing table's ingestion timestamp is named INGESTED_AT (no leading underscore) rather than the usual _INGESTED_AT -- confirmed via INFORMATION_SCHEMA, not assumed.
-- DEDUPE: registry natural_key (GEOMETRY) is NOT unique within a load as landed at generation time -- it would collapse 1 of 100 rows. Deduping on the WHOLE ROW instead (exact copies only). A record that changes between loads shows once per version. Find the real key, fix SOURCE_REGISTRY, regenerate.

with source as (

    select * from {{ source('ripple_raw', 'PORTAL_ARC_HARRIS_COUNTY_OP_795533139C') }}
    qualify row_number() over (partition by "FID", "OBJECTID", "STATUS", "SCORE", "MATCH_TYPE", "MATCH_ADDR", "LONGLABEL", "SHORTLABEL", "ADDR_TYPE", "TYPE", "PLACENAME", "PLACE_ADDR", "PHONE", "URL", "RANK", "ADDBLDG", "ADDNUM", "ADDNUMFROM", "ADDNUMTO", "ADDRANGE", "SIDE", "STPREDIR", "STPRETYPE", "STNAME", "STTYPE", "STDIR", "BLDGTYPE", "BLDGNAME", "LEVELTYPE", "LEVELNAME", "UNITTYPE", "UNITNAME", "SUBADDR", "STADDR", "BLOCK", "SECTOR", "NBRHD", "DISTRICT", "CITY", "METROAREA", "SUBREGION", "REGION", "REGIONABBR", "TERRITORY", "ZONE", "POSTAL", "POSTALEXT", "COUNTRY", "LANGCODE", "DISTANCE", "X", "Y", "DISPLAYX", "DISPLAYY", "XMIN", "XMAX", "YMIN", "YMAX", "EXINFO", "IN_ADDRESS", "IN_ADDRE_1", "IN_ADDRE_2", "IN_NEIGHBO", "IN_CITY", "IN_SUBREGI", "IN_REGION", "IN_POSTAL", "IN_POSTALE", "IN_COUNTRY", "USER_COUNT", "USER_COU_1", "USER_ESC_R", "USER_ESC_1", "USER_ESC_2", "USER_DISTR", "USER_DIS_1", "USER_DIS_2", "USER_NCES", "USER_DIS_3", "USER_DIS_4", "USER_DIS_5", "USER_DIS_6", "USER_DIS_7", "USER_DIS_8", "USER_DIS_9", "USER_DIS10", "USER_DIS11", "USER_DIS12", "USER_DIS13", "USER_DIS14", "USER_DIS15", "USER_DIS16", "USER_SCHOO", "USER_SCH_1", "USER_INSTR", "USER_CHART", "USER_AEA", "USER_MAGNE", "USER_RESID", "USER_NCE_1", "USER_SCH_2", "USER_SCH_3", "USER_SCH_4", "USER_SCH_5", "USER_SCH_6", "USER_SCH_7", "USER_SCH_8", "USER_SCH_9", "USER_SCH10", "USER_SCH11", "USER_SCH12", "USER_SCH13", "USER_SCH14", "USER_GRADE", "USER_SCH15", "USER_SCH16", "USER_SCH17", "USER_UPDAT", "PRECINCT", "GEOMETRY" order by INGESTED_AT desc) = 1

),

renamed as (

    select
        {{ stg_id_text('"FID"') }} as fid,
        {{ stg_id_text('"OBJECTID"') }} as objectid,
        {{ null_junk('"STATUS"') }} as status,
        {{ stg_float('"SCORE"') }} as score,
        {{ null_junk('"MATCH_TYPE"') }} as match_type,
        {{ null_junk('"MATCH_ADDR"') }} as match_addr,
        {{ null_junk('"LONGLABEL"') }} as longlabel,
        {{ null_junk('"SHORTLABEL"') }} as shortlabel,
        {{ null_junk('"ADDR_TYPE"') }} as addr_type,
        {{ null_junk('"TYPE"') }} as type,
        {{ null_junk('"PLACENAME"') }} as placename,
        {{ null_junk('"PLACE_ADDR"') }} as place_addr,
        {{ null_junk('"PHONE"') }} as phone,
        {{ null_junk('"URL"') }} as url,
        {{ stg_float('"RANK"') }} as rank,
        {{ null_junk('"ADDBLDG"') }} as addbldg,
        {{ stg_id_text('"ADDNUM"') }} as addnum,
        {{ stg_id_text('"ADDNUMFROM"') }} as addnumfrom,
        {{ stg_id_text('"ADDNUMTO"') }} as addnumto,
        {{ null_junk('"ADDRANGE"') }} as addrange,
        {{ null_junk('"SIDE"') }} as side,
        {{ null_junk('"STPREDIR"') }} as stpredir,
        {{ null_junk('"STPRETYPE"') }} as stpretype,
        {{ null_junk('"STNAME"') }} as stname,
        {{ null_junk('"STTYPE"') }} as sttype,
        {{ null_junk('"STDIR"') }} as stdir,
        {{ null_junk('"BLDGTYPE"') }} as bldgtype,
        {{ null_junk('"BLDGNAME"') }} as bldgname,
        {{ null_junk('"LEVELTYPE"') }} as leveltype,
        {{ null_junk('"LEVELNAME"') }} as levelname,
        {{ null_junk('"UNITTYPE"') }} as unittype,
        {{ null_junk('"UNITNAME"') }} as unitname,
        {{ null_junk('"SUBADDR"') }} as subaddr,
        {{ null_junk('"STADDR"') }} as staddr,
        {{ null_junk('"BLOCK"') }} as block,
        {{ null_junk('"SECTOR"') }} as sector,
        {{ null_junk('"NBRHD"') }} as nbrhd,
        {{ null_junk('"DISTRICT"') }} as district,
        {{ null_junk('"CITY"') }} as city,
        {{ null_junk('"METROAREA"') }} as metroarea,
        {{ null_junk('"SUBREGION"') }} as subregion,
        {{ null_junk('"REGION"') }} as region,
        {{ null_junk('"REGIONABBR"') }} as regionabbr,
        {{ null_junk('"TERRITORY"') }} as territory,
        {{ null_junk('"ZONE"') }} as zone,
        {{ stg_int('"POSTAL"') }} as postal,
        {{ null_junk('"POSTALEXT"') }} as postalext,
        {{ null_junk('"COUNTRY"') }} as country,
        {{ null_junk('"LANGCODE"') }} as langcode,
        {{ stg_float('"DISTANCE"') }} as distance,
        {{ stg_float('"X"') }} as x,
        {{ stg_float('"Y"') }} as y,
        {{ stg_float('"DISPLAYX"') }} as displayx,
        {{ stg_float('"DISPLAYY"') }} as displayy,
        {{ stg_float('"XMIN"') }} as xmin,
        {{ stg_float('"XMAX"') }} as xmax,
        {{ stg_float('"YMIN"') }} as ymin,
        {{ stg_float('"YMAX"') }} as ymax,
        {{ null_junk('"EXINFO"') }} as exinfo,
        {{ null_junk('"IN_ADDRESS"') }} as in_address,
        {{ null_junk('"IN_ADDRE_1"') }} as in_addre_1,
        {{ null_junk('"IN_ADDRE_2"') }} as in_addre_2,
        {{ null_junk('"IN_NEIGHBO"') }} as in_neighbo,
        {{ null_junk('"IN_CITY"') }} as in_city,
        {{ null_junk('"IN_SUBREGI"') }} as in_subregi,
        {{ null_junk('"IN_REGION"') }} as in_region,
        {{ null_junk('"IN_POSTAL"') }} as in_postal,
        {{ null_junk('"IN_POSTALE"') }} as in_postale,
        {{ null_junk('"IN_COUNTRY"') }} as in_country,
        {{ stg_int('"USER_COUNT"') }} as user_count,
        {{ null_junk('"USER_COU_1"') }} as user_cou_1,
        {{ stg_int('"USER_ESC_R"') }} as user_esc_r,
        {{ stg_int('"USER_ESC_1"') }} as user_esc_1,
        {{ stg_int('"USER_ESC_2"') }} as user_esc_2,
        {{ stg_int('"USER_DISTR"') }} as user_distr,
        {{ null_junk('"USER_DIS_1"') }} as user_dis_1,
        {{ null_junk('"USER_DIS_2"') }} as user_dis_2,
        {{ null_junk('"USER_NCES"') }} as user_nces,
        {{ null_junk('"USER_DIS_3"') }} as user_dis_3,
        {{ null_junk('"USER_DIS_4"') }} as user_dis_4,
        {{ null_junk('"USER_DIS_5"') }} as user_dis_5,
        {{ null_junk('"USER_DIS_6"') }} as user_dis_6,
        {{ null_junk('"USER_DIS_7"') }} as user_dis_7,
        {{ null_junk('"USER_DIS_8"') }} as user_dis_8,
        {{ null_junk('"USER_DIS_9"') }} as user_dis_9,
        {{ null_junk('"USER_DIS10"') }} as user_dis10,
        {{ null_junk('"USER_DIS11"') }} as user_dis11,
        {{ null_junk('"USER_DIS12"') }} as user_dis12,
        {{ null_junk('"USER_DIS13"') }} as user_dis13,
        {{ null_junk('"USER_DIS14"') }} as user_dis14,
        {{ null_junk('"USER_DIS15"') }} as user_dis15,
        {{ stg_int('"USER_DIS16"') }} as user_dis16,
        {{ stg_id_text('"USER_SCHOO"') }} as user_schoo,
        {{ null_junk('"USER_SCH_1"') }} as user_sch_1,
        {{ null_junk('"USER_INSTR"') }} as user_instr,
        {{ null_junk('"USER_CHART"') }} as user_chart,
        {{ null_junk('"USER_AEA"') }} as user_aea,
        {{ null_junk('"USER_MAGNE"') }} as user_magne,
        {{ null_junk('"USER_RESID"') }} as user_resid,
        {{ stg_id_text('"USER_NCE_1"') }} as user_nce_1,
        {{ null_junk('"USER_SCH_2"') }} as user_sch_2,
        {{ null_junk('"USER_SCH_3"') }} as user_sch_3,
        {{ null_junk('"USER_SCH_4"') }} as user_sch_4,
        {{ null_junk('"USER_SCH_5"') }} as user_sch_5,
        {{ null_junk('"USER_SCH_6"') }} as user_sch_6,
        {{ null_junk('"USER_SCH_7"') }} as user_sch_7,
        {{ null_junk('"USER_SCH_8"') }} as user_sch_8,
        {{ null_junk('"USER_SCH_9"') }} as user_sch_9,
        {{ null_junk('"USER_SCH10"') }} as user_sch10,
        {{ null_junk('"USER_SCH11"') }} as user_sch11,
        {{ null_junk('"USER_SCH12"') }} as user_sch12,
        {{ null_junk('"USER_SCH13"') }} as user_sch13,
        {{ null_junk('"USER_SCH14"') }} as user_sch14,
        {{ null_junk('"USER_GRADE"') }} as user_grade,
        {{ stg_id_text('"USER_SCH15"') }} as user_sch15,
        {{ null_junk('"USER_SCH16"') }} as user_sch16,
        {{ stg_int('"USER_SCH17"') }} as user_sch17,
        {{ null_junk('"USER_UPDAT"') }} as user_updat,
        {{ stg_int('"PRECINCT"') }} as precinct,
        {{ null_junk('"GEOMETRY"') }} as geometry,
        INGESTED_AT as _loaded_at,
        'https://geo-harriscounty.opendata.arcgis.com/datasets/5a077aff9bb9424cbc81f49fe23e8ca3_0' as _source_url

    from source

)

select * from renamed
