{{ config(tags=['spine_generated']) }}

-- GRAIN: one row per place (GEOM is unique)
-- SPINE_ENTITY: place  (natural_key: GEOMETRY)
-- Generated by scripts/generate_staging_models.py from SOURCE_REGISTRY -- deterministic,
-- no LLM.
-- CASTS: 16 of 33 columns, from landing_column_profile_2026-09-19.tsv. A column is cast only
-- when every filled value in the sample parsed. try_ casts: a value that does not
-- parse reads NULL. The natural key and join-key columns stay TEXT.
--   count_allcrash: integer
--   count_bicyclecrash: integer
--   count_fatalcrash: integer
--   count_injurycrash: integer
--   count_pedestriancrash: integer
--   count_suspectedseriouscrash: integer
--   objectid_1: ID: whole numbers, over 90% distinct -- stays TEXT, '.0' tail removed
--   areasqft: float
--   council201: integer
--   council2_1: integer
--   council_lt: integer
--   council_rt: integer
--   no_lanes: integer
--   num_lanes: integer
--   roadwidth: float
--   speedlimit: integer
-- spine_entity 'place' has no connect/ resolver yet (see connect/spine_entity.py) -- no SPINE_ENTITY_ID emitted.
-- landing table's ingestion timestamp is named INGESTED_AT (no leading underscore) rather than the usual _INGESTED_AT -- confirmed via INFORMATION_SCHEMA, not assumed.
-- DEDUPE: registry natural_key (GEOMETRY) is NOT unique within a load as landed at generation time -- it would collapse 1 of 111 rows. Deduping on the WHOLE ROW instead (exact copies only). A record that changes between loads shows once per version. Find the real key, fix SOURCE_REGISTRY, regenerate.

with source as (

    select * from {{ source('ripple_raw', 'PORTAL_CKA_WESTERN_PENNSYLV_03AB547ADB') }}
    qualify row_number() over (partition by "CATEGORY", "COMPLETE_STREETS", "COUNT_ALLCRASH", "COUNT_BICYCLECRASH", "COUNT_FATALCRASH", "COUNT_INJURYCRASH", "COUNT_PEDESTRIANCRASH", "COUNT_SUSPECTEDSERIOUSCRASH", "FATAL22", "FIELD", "NUM_PROJECTS", "OBJECTID_1", "SHAPE__LENGTH", "SIDEWALK", "TRAFFIC_CALMING", "TRAFFIC_SIGNALS", "AREASQFT", "CDBG", "COUNCIL201", "COUNCIL2_1", "COUNCIL_LT", "COUNCIL_RT", "DOMI_CLASS", "HOOD_LEFT", "HOOD_RIGHT", "NO_LANES", "NUM_LANES", "ROADCLASS", "ROADWIDTH", "RSROADCLAS", "SPEEDLIMIT", "STREETNAME", "GEOMETRY" order by INGESTED_AT desc) = 1

),

renamed as (

    select
        {{ null_junk('"CATEGORY"') }} as category,
        {{ null_junk('"COMPLETE_STREETS"') }} as complete_streets,
        {{ stg_int('"COUNT_ALLCRASH"') }} as count_allcrash,
        {{ stg_int('"COUNT_BICYCLECRASH"') }} as count_bicyclecrash,
        {{ stg_int('"COUNT_FATALCRASH"') }} as count_fatalcrash,
        {{ stg_int('"COUNT_INJURYCRASH"') }} as count_injurycrash,
        {{ stg_int('"COUNT_PEDESTRIANCRASH"') }} as count_pedestriancrash,
        {{ stg_int('"COUNT_SUSPECTEDSERIOUSCRASH"') }} as count_suspectedseriouscrash,
        {{ null_junk('"FATAL22"') }} as fatal22,
        {{ null_junk('"FIELD"') }} as field,
        {{ null_junk('"NUM_PROJECTS"') }} as num_projects,
        {{ stg_id_text('"OBJECTID_1"') }} as objectid_1,
        {{ null_junk('"SHAPE__LENGTH"') }} as shape__length,
        {{ null_junk('"SIDEWALK"') }} as sidewalk,
        {{ null_junk('"TRAFFIC_CALMING"') }} as traffic_calming,
        {{ null_junk('"TRAFFIC_SIGNALS"') }} as traffic_signals,
        {{ stg_float('"AREASQFT"') }} as areasqft,
        {{ null_junk('"CDBG"') }} as cdbg,
        {{ stg_int('"COUNCIL201"') }} as council201,
        {{ stg_int('"COUNCIL2_1"') }} as council2_1,
        {{ stg_int('"COUNCIL_LT"') }} as council_lt,
        {{ stg_int('"COUNCIL_RT"') }} as council_rt,
        {{ null_junk('"DOMI_CLASS"') }} as domi_class,
        {{ null_junk('"HOOD_LEFT"') }} as hood_left,
        {{ null_junk('"HOOD_RIGHT"') }} as hood_right,
        {{ stg_int('"NO_LANES"') }} as no_lanes,
        {{ stg_int('"NUM_LANES"') }} as num_lanes,
        {{ null_junk('"ROADCLASS"') }} as roadclass,
        {{ stg_float('"ROADWIDTH"') }} as roadwidth,
        {{ null_junk('"RSROADCLAS"') }} as rsroadclas,
        {{ stg_int('"SPEEDLIMIT"') }} as speedlimit,
        {{ null_junk('"STREETNAME"') }} as streetname,
        {{ null_junk('"GEOMETRY"') }} as geometry,
        INGESTED_AT as _loaded_at,
        'https://data.wprdc.org/dataset/high-injury-network' as _source_url

    from source

)

select * from renamed
