{{ config(materialized='table', schema='EDUCATION') }}

-- Source: FED_CFTC_COT_FINANCIAL (3163 rows)
-- Generated by scripts/gen_mart_models.py

with source as (
    select * from {{ source('ripple_raw', 'FED_CFTC_COT_FINANCIAL') }}
    -- TEMPORARY SHIELD (2026-08-11 history backfill): one bundle slice landed
    -- 7,790 mis-filtered rows before its date parsing was fixed. They are
    -- exactly identifiable by source-file hash; the landing DELETE is queued
    -- for human sign-off (reports/repair_session_chris_gates_2026-08-11.md).
    -- Remove this filter after that DELETE + the backfill rerun.
    where SRC_SHA256 is null
       or SRC_SHA256 <> 'c3a8d01765133a24ce9c082de88933816497d06f1b03eec8c53750bdd818f14b'
)

select
    MARKET_AND_EXCHANGE_NAMES as market_and_exchange_names,
    -- YYMMDD strings fed to a bare try_to_date were read as epoch seconds
    -- (every row 1970-01-03); an explicit format parses them correctly.
    try_to_date(AS_OF_DATE_IN_FORM_YYMMDD, 'YYMMDD') as as_of_date_in_form_yymmdd,
    try_to_date(REPORT_DATE_AS_YYYY_MM_DD) as report_date_as_yyyy_mm_dd,
    CFTC_CONTRACT_MARKET_CODE as cftc_contract_market_code,
    CFTC_MARKET_CODE as cftc_market_code,
    CFTC_REGION_CODE as cftc_region_code,
    CFTC_COMMODITY_CODE as cftc_commodity_code,
    OPEN_INTEREST_ALL as open_interest_all,
    DEALER_POSITIONS_LONG_ALL as dealer_positions_long_all,
    DEALER_POSITIONS_SHORT_ALL as dealer_positions_short_all,
    DEALER_POSITIONS_SPREAD_ALL as dealer_positions_spread_all,
    ASSET_MGR_POSITIONS_LONG_ALL as asset_mgr_positions_long_all,
    ASSET_MGR_POSITIONS_SHORT_ALL as asset_mgr_positions_short_all,
    ASSET_MGR_POSITIONS_SPREAD_ALL as asset_mgr_positions_spread_all,
    LEV_MONEY_POSITIONS_LONG_ALL as lev_money_positions_long_all,
    LEV_MONEY_POSITIONS_SHORT_ALL as lev_money_positions_short_all,
    LEV_MONEY_POSITIONS_SPREAD_ALL as lev_money_positions_spread_all,
    OTHER_REPT_POSITIONS_LONG_ALL as other_rept_positions_long_all,
    OTHER_REPT_POSITIONS_SHORT_ALL as other_rept_positions_short_all,
    OTHER_REPT_POSITIONS_SPREAD_ALL as other_rept_positions_spread_all,
    TOT_REPT_POSITIONS_LONG_ALL as tot_rept_positions_long_all,
    TOT_REPT_POSITIONS_SHORT_ALL as tot_rept_positions_short_all,
    NONREPT_POSITIONS_LONG_ALL as nonrept_positions_long_all,
    NONREPT_POSITIONS_SHORT_ALL as nonrept_positions_short_all,
    CHANGE_IN_OPEN_INTEREST_ALL as change_in_open_interest_all,
    CHANGE_IN_DEALER_LONG_ALL as change_in_dealer_long_all,
    CHANGE_IN_DEALER_SHORT_ALL as change_in_dealer_short_all,
    CHANGE_IN_DEALER_SPREAD_ALL as change_in_dealer_spread_all,
    CHANGE_IN_ASSET_MGR_LONG_ALL as change_in_asset_mgr_long_all,
    CHANGE_IN_ASSET_MGR_SHORT_ALL as change_in_asset_mgr_short_all,
    CHANGE_IN_ASSET_MGR_SPREAD_ALL as change_in_asset_mgr_spread_all,
    CHANGE_IN_LEV_MONEY_LONG_ALL as change_in_lev_money_long_all,
    CHANGE_IN_LEV_MONEY_SHORT_ALL as change_in_lev_money_short_all,
    CHANGE_IN_LEV_MONEY_SPREAD_ALL as change_in_lev_money_spread_all,
    CHANGE_IN_OTHER_REPT_LONG_ALL as change_in_other_rept_long_all,
    CHANGE_IN_OTHER_REPT_SHORT_ALL as change_in_other_rept_short_all,
    CHANGE_IN_OTHER_REPT_SPREAD_ALL as change_in_other_rept_spread_all,
    CHANGE_IN_TOT_REPT_LONG_ALL as change_in_tot_rept_long_all,
    CHANGE_IN_TOT_REPT_SHORT_ALL as change_in_tot_rept_short_all,
    CHANGE_IN_NONREPT_LONG_ALL as change_in_nonrept_long_all,
    CHANGE_IN_NONREPT_SHORT_ALL as change_in_nonrept_short_all,
    PCT_OF_OPEN_INTEREST_ALL as pct_of_open_interest_all,
    PCT_OF_OI_DEALER_LONG_ALL as pct_of_oi_dealer_long_all,
    PCT_OF_OI_DEALER_SHORT_ALL as pct_of_oi_dealer_short_all,
    PCT_OF_OI_DEALER_SPREAD_ALL as pct_of_oi_dealer_spread_all,
    PCT_OF_OI_ASSET_MGR_LONG_ALL as pct_of_oi_asset_mgr_long_all,
    PCT_OF_OI_ASSET_MGR_SHORT_ALL as pct_of_oi_asset_mgr_short_all,
    PCT_OF_OI_ASSET_MGR_SPREAD_ALL as pct_of_oi_asset_mgr_spread_all,
    PCT_OF_OI_LEV_MONEY_LONG_ALL as pct_of_oi_lev_money_long_all,
    PCT_OF_OI_LEV_MONEY_SHORT_ALL as pct_of_oi_lev_money_short_all,
    PCT_OF_OI_LEV_MONEY_SPREAD_ALL as pct_of_oi_lev_money_spread_all,
    PCT_OF_OI_OTHER_REPT_LONG_ALL as pct_of_oi_other_rept_long_all,
    PCT_OF_OI_OTHER_REPT_SHORT_ALL as pct_of_oi_other_rept_short_all,
    PCT_OF_OI_OTHER_REPT_SPREAD_ALL as pct_of_oi_other_rept_spread_all,
    PCT_OF_OI_TOT_REPT_LONG_ALL as pct_of_oi_tot_rept_long_all,
    PCT_OF_OI_TOT_REPT_SHORT_ALL as pct_of_oi_tot_rept_short_all,
    PCT_OF_OI_NONREPT_LONG_ALL as pct_of_oi_nonrept_long_all,
    PCT_OF_OI_NONREPT_SHORT_ALL as pct_of_oi_nonrept_short_all,
    TRADERS_TOT_ALL as traders_tot_all,
    TRADERS_DEALER_LONG_ALL as traders_dealer_long_all,
    TRADERS_DEALER_SHORT_ALL as traders_dealer_short_all,
    TRADERS_DEALER_SPREAD_ALL as traders_dealer_spread_all,
    TRADERS_ASSET_MGR_LONG_ALL as traders_asset_mgr_long_all,
    TRADERS_ASSET_MGR_SHORT_ALL as traders_asset_mgr_short_all,
    TRADERS_ASSET_MGR_SPREAD_ALL as traders_asset_mgr_spread_all,
    TRADERS_LEV_MONEY_LONG_ALL as traders_lev_money_long_all,
    TRADERS_LEV_MONEY_SHORT_ALL as traders_lev_money_short_all,
    TRADERS_LEV_MONEY_SPREAD_ALL as traders_lev_money_spread_all,
    TRADERS_OTHER_REPT_LONG_ALL as traders_other_rept_long_all,
    TRADERS_OTHER_REPT_SHORT_ALL as traders_other_rept_short_all,
    TRADERS_OTHER_REPT_SPREAD_ALL as traders_other_rept_spread_all,
    TRADERS_TOT_REPT_LONG_ALL as traders_tot_rept_long_all,
    TRADERS_TOT_REPT_SHORT_ALL as traders_tot_rept_short_all,
    CONC_GROSS_LE_4_TDR_LONG_ALL as conc_gross_le_4_tdr_long_all,
    CONC_GROSS_LE_4_TDR_SHORT_ALL as conc_gross_le_4_tdr_short_all,
    CONC_GROSS_LE_8_TDR_LONG_ALL as conc_gross_le_8_tdr_long_all,
    CONC_GROSS_LE_8_TDR_SHORT_ALL as conc_gross_le_8_tdr_short_all,
    CONC_NET_LE_4_TDR_LONG_ALL as conc_net_le_4_tdr_long_all,
    CONC_NET_LE_4_TDR_SHORT_ALL as conc_net_le_4_tdr_short_all,
    CONC_NET_LE_8_TDR_LONG_ALL as conc_net_le_8_tdr_long_all,
    CONC_NET_LE_8_TDR_SHORT_ALL as conc_net_le_8_tdr_short_all,
    CONTRACT_UNITS as contract_units,
    CFTC_CONTRACT_MARKET_CODE_QUOTES as cftc_contract_market_code_quotes,
    CFTC_MARKET_CODE_QUOTES as cftc_market_code_quotes,
    CFTC_COMMODITY_CODE_QUOTES as cftc_commodity_code_quotes,
    CFTC_SUBGROUP_CODE as cftc_subgroup_code,
    FUTONLY_OR_COMBINED as futonly_or_combined
from source
