{{ config(materialized='table', schema='FINANCE') }}

-- Source: FED_SEC_CLOSED_END_FUND_INFORMATION (973 rows)
-- Generated by scripts/gen_mart_models.py

with source as (
    select * from {{ source('ripple_raw', 'FED_SEC_CLOSED_END_FUND_INFORMATION') }}
)

select
    FILE_NO as file_no,
    CIK as cik,
    REGISTRANT_NAME as registrant_name,
    ADDRESS_1 as address_1,
    ADDRESS_2 as address_2,
    CITY as city,
    STATE as state,
    ZIP_CODE as zip_code,
    try_to_date(FILING_DATE) as filing_date,
    FILING_TYPE as filing_type
from source
