{{ config(materialized='table', schema='FINANCE') }}

-- Source: FEC Committee Master (bulk, multi-cycle) (78039 rows)
-- Generated by gen_mart_models.py

with source as (
    select * from {{ source('ripple_raw', 'FED_FEC_COMMITTEES') }}
)

-- Column names restored 2026-08-10. The loader wrote this FEC bulk file with no
-- header row, so the landing table carries positional C1..CN names and the mart
-- passed them straight through -- unusable for anything downstream. The names
-- below are the official FEC bulk-data layout for this file, verified against the
-- landing values (sample row: C00000018 / IRONWORKERS LOCAL UNION / STEVEN N GULICK / NOVI / MI).
-- Layout: FEC Committee Master (cm.txt)
-- CYCLE check 2026-08-11: this landing table has NO cycle column (positional
-- C1..C15 only) -- cycle cannot be added here. The multi-cycle copy with a real
-- CYCLE column is the FEC bulk committees landing/mart, which already carries it.
--
-- DUP INVESTIGATION 2026-08-18 -- FLAGGED, NOT FIXED, NEEDS A HUMAN CALL: live
-- full-scan shows 23.08% exact-row duplication (78,039 rows / 60,031 distinct).
-- Duplicate-group samples are real committee records (verified against known FEC
-- committees, e.g. Florida Bankers Association PAC) repeating byte-identical
-- ~4x, and the whole landing table carries a SINGLE _SOURCE_RUN_ID / _INGESTED_AT
-- -- so this isn't a re-run problem, it's baked into one ingest event (source
-- bulk file spanning multiple cycles, or a chunked fetch double-pulling within
-- one run; the loader script for this landing table could not be located in the
-- repo to confirm which). Because there is no cycle/snapshot column, a blind
-- exact-row QUALIFY/ROW_NUMBER dedup would silently destroy real multi-cycle
-- history with no way to tell which cycle the surviving row came from -- so no
-- row-level fix was applied. A cleaner, actively-maintained cycle-aware
-- alternative already exists: LIBRARY_MARTS.POLITICS.POLITICS__FEC_COMMITTEE
-- (built by politics/loaders/build_cm26_refresh.py, deduped on cmte_id+cycle),
-- backed by sibling landing table FED_FEC_BULK_COMMITTEES (20,007 rows). Needs
-- Chris/loader decision: retire this mart in favor of the POLITICS family, or
-- re-derive the missing cycle tag from source before any row-level fix.

select
    C1 as cmte_id,
    C2 as cmte_nm,
    C3 as tres_nm,
    C4 as cmte_st1,
    C5 as cmte_st2,
    C6 as cmte_city,
    C7 as cmte_st,
    C8 as cmte_zip,
    C9 as cmte_dsgn,
    C10 as cmte_tp,
    C11 as cmte_pty_affiliation,
    C12 as cmte_filing_freq,
    C13 as org_tp,
    C14 as connected_org_nm,
    C15 as cand_id
from source
