{{ config(materialized='table', schema='FINANCE') }}

-- Source: SEC Financial Statement Data Sets (6699 rows)
-- Generated by gen_mart_models.py

with source as (
    select * from {{ source('ripple_raw', 'FED_SEC_EDGAR_FINANCIALS') }}
)

select
    ADSH as adsh,
    CIK as cik,
    NAME as name,
    SIC as sic,
    try_to_number(COUNTRYBA) as countryba,
    STPRBA as stprba,
    CITYBA as cityba,
    ZIPBA as zipba,
    BAS1 as bas1,
    BAS2 as bas2,
    BAPH as baph,
    try_to_number(COUNTRYMA) as countryma,
    STPRMA as stprma,
    CITYMA as cityma,
    ZIPMA as zipma,
    MAS1 as mas1,
    MAS2 as mas2,
    try_to_number(COUNTRYINC) as countryinc,
    STPRINC as stprinc,
    EIN as ein,
    FORMER as former,
    CHANGED as changed,
    AFS as afs,
    WKSI as wksi,
    FYE as fye,
    FORM as form,
    PERIOD as period,
    try_to_number(FY) as fy,
    FP as fp,
    FILED as filed,
    ACCEPTED as accepted,
    PREVRPT as prevrpt,
    DETAIL as detail,
    INSTANCE as instance,
    NCIKS as nciks,
    ACIKS as aciks,
    SOURCE_FILE as source_file
from source
