{{ config(materialized='table', schema='FINANCE') }}
-- Fixed 2026-09-21: ID columns were cast to FLOAT by ripple_num, which drops leading zeros and rounds past 15 digits. Now TEXT via stg_id_text (ruling 2026-09-19: an ID stays text).

-- Source: FEC Bulk Data -- Committee-to-Candidate (pas2/itpas2) (866730 rows)
-- MULTI-CYCLE LOAD, intentional (verified 2026-08-11): the 2024 AND 2026 cycles are both loaded (landing CYCLE column). The 2024-only pas224 file is ~703,597 records, so the higher count vs one cycle's file is expected, not a double-load.
-- Generated by gen_mart_models.py
-- Fixed 2026-09-20: TRANSACTION_AMT was a bare try_to_double() -- live-checked
-- 100% whole-dollar today (0 of 866,730 filled rows fractional) but unguarded
-- against a future decimal load and against the string 'nan' silently parsing
-- as the float NaN. Kept on source() (not ref()) because this mart also
-- carries is_memo_transaction, a computed column the staging model doesn't
-- expose -- wrapped the one cast with stg_float, not stg_int: this is a
-- dollar amount, not a whole-number count, and stg_int would NULL out any
-- future decimal load instead of keeping the cents (corrected 2026-09-20,
-- matches the sibling FEC individual-contributions mart's amount cast).

with source as (
    select * from {{ source('ripple_raw', 'FED_FEC_COMMITTEE_TO_CANDIDATE') }}
)

select
    CMTE_ID as cmte_id,
    AMNDT_IND as amndt_ind,
    RPT_TP as rpt_tp,
    TRANSACTION_PGI as transaction_pgi,
    {{ stg_id_text('IMAGE_NUM') }} as image_num,
    TRANSACTION_TP as transaction_tp,
    ENTITY_TP as entity_tp,
    NAME as name,
    CITY as city,
    STATE as state,
    ZIP_CODE as zip_code,
    EMPLOYER as employer,
    OCCUPATION as occupation,
    TRANSACTION_DT as transaction_dt,
    {{ stg_float('"TRANSACTION_AMT"') }} as transaction_amt,
    OTHER_ID as other_id,
    CAND_ID as cand_id,
    TRAN_ID as tran_id,
    {{ stg_id_text('FILE_NUM') }} as file_num,
    MEMO_CD as memo_cd,
    -- memo_cd = 'X' is FEC's memo/re-statement flag: an earmarked or pass-through
    -- contribution shown a second time on the record that received it. That money
    -- is already counted on the real (non-memo) row elsewhere in the file --
    -- summing memo rows in with the rest double-counts it. coalesce so a blank/
    -- null memo_cd reads as a clean false, never an ambiguous null.
    coalesce(MEMO_CD = 'X', false) as is_memo_transaction,
    MEMO_TEXT as memo_text,
    SUB_ID as sub_id,
    CYCLE as cycle
from source
