{{ config(enabled=false, materialized='table', schema='FINANCE') }}

-- RETIRED 2026-08-23 (13F consolidation): despite its name, the landing table
-- this reads (FED_SEC_13F_SUBMISSION, singular) holds holdings-shaped rows that
-- are a 100% subset of FED_SEC_13F_HOLDINGS (verified by key intersect). The
-- built table and its landing source are DROP candidates. Real submissions live
-- in finance__fed_sec_13f_submissions (plural).
-- Source: SEC Form 13F ? Submission Metadata (filer identity) (3822885 rows)
-- Generated by scripts/gen_mart_models.py

with source as (
    select * from {{ source('ripple_raw', 'FED_SEC_13F_SUBMISSION') }}
)

select
    ACCESSION_NUMBER as accession_number,
    INFOTABLE_SK as infotable_sk,
    NAMEOFISSUER as nameofissuer,
    TITLEOFCLASS as titleofclass,
    CUSIP as cusip,
    FIGI as figi,
    "VALUE" as value_col,
    try_to_double(SSHPRNAMT) as sshprnamt,
    SSHPRNAMTTYPE as sshprnamttype,
    PUTCALL as putcall,
    INVESTMENTDISCRETION as investmentdiscretion,
    OTHERMANAGER as othermanager,
    VOTING_AUTH_SOLE as voting_auth_sole,
    VOTING_AUTH_SHARED as voting_auth_shared,
    VOTING_AUTH_NONE as voting_auth_none
from source
