{{ config(tags=['spine_generated']) }}

-- GRAIN: one row per record (spine_entity not determined -- no registry hint available) (FAC_ID unique)
-- SPINE_ENTITY: (not determined)  (natural_key: FAC_ID)
-- Generated by scripts/generate_staging_models.py from SOURCE_REGISTRY -- deterministic,
-- no LLM. Casts kept as landed (TEXT) -- add explicit type casts by hand once each
-- column's real type is confirmed; this generator has no semantic type knowledge.
-- spine_entity not determined (grain/natural_key proven, but no registry hint says what this row is ABOUT) -- no SPINE_ENTITY_ID emitted.
-- landing table's ingestion timestamp is named INGESTED_AT (no leading underscore) rather than the usual _INGESTED_AT -- confirmed via INFORMATION_SCHEMA, not assumed.

with source as (

    select * from {{ source('ripple_raw', 'PORTAL_ARC_LA_COUNTY_OPEN_D_75836D970C') }}

),

renamed as (

    select
        "OBJECTID" as objectid,
        "X" as x,
        "Y" as y,
        "MATCH_ADDR" as match_addr,
        "STREET" as street,
        "CITY" as city,
        "ZIPCODE" as zipcode,
        "FAC_ID" as fac_id,
        "FAC_NAME" as fac_name,
        "NAICS_CODE" as naics_code,
        "FAC_ID_INTEGER" as fac_id_integer,
        "TITLEV" as titlev,
        "GEOMETRY" as geometry,
        INGESTED_AT as _loaded_at,
        'https://data.lacounty.gov/datasets/18edd7df2f14461d8a24bcc202f7b771_3' as _source_url

    from source

)

select * from renamed
qualify row_number() over (partition by fac_id order by _loaded_at desc) = 1
