{{ config(tags=['spine_generated']) }}

-- GRAIN: one row per record (spine_entity not determined -- no registry hint available) (DATASET_ID is unique)
-- SPINE_ENTITY: (not determined)  (natural_key: DATASET_ID)
-- Generated by scripts/generate_staging_models.py from SOURCE_REGISTRY -- deterministic,
-- no LLM.
-- CASTS: 3 of 16 columns, from landing_column_profile_2026-09-19.tsv. A column is cast only
-- when every filled value in the sample parsed. try_ casts: a value that does not
-- parse reads NULL. The natural key and join-key columns stay TEXT.
--   date_created: timestamp
--   metadata_modified: timestamp
--   num_resources: integer
-- spine_entity not determined (grain/natural_key proven, but no registry hint says what this row is ABOUT) -- no SPINE_ENTITY_ID emitted.
-- DEDUPE: registry natural_key (DATASET_ID) is NOT unique within a load as landed at generation time -- it would collapse 12 of 5,000 rows. Deduping on the WHOLE ROW instead (exact copies only). A record that changes between loads shows once per version. Find the real key, fix SOURCE_REGISTRY, regenerate.

with source as (

    select * from {{ source('ripple_raw', 'INTL_GR_DATAGOV') }}
    qualify row_number() over (partition by "DATASET_ID", "TITLE", "DESCRIPTION", "ORGANISATION_ID", "ORGANISATION_NAME", "THEMATIC_CATEGORY", "LICENSE_ID", "DATE_CREATED", "METADATA_MODIFIED", "NUM_RESOURCES", "RESOURCE_FORMATS", "RESOURCE_URLS", "TAGS", "IS_HVD", "ACCESS_URL", "LANGUAGE" order by _INGESTED_AT desc) = 1

),

renamed as (

    select
        {{ null_junk('"DATASET_ID"') }} as dataset_id,
        {{ null_junk('"TITLE"') }} as title,
        {{ null_junk('"DESCRIPTION"') }} as description,
        {{ null_junk('"ORGANISATION_ID"') }} as organisation_id,
        {{ null_junk('"ORGANISATION_NAME"') }} as organisation_name,
        {{ null_junk('"THEMATIC_CATEGORY"') }} as thematic_category,
        {{ null_junk('"LICENSE_ID"') }} as license_id,
        {{ stg_ts('"DATE_CREATED"') }} as date_created,
        {{ stg_ts('"METADATA_MODIFIED"') }} as metadata_modified,
        {{ stg_int('"NUM_RESOURCES"') }} as num_resources,
        {{ null_junk('"RESOURCE_FORMATS"') }} as resource_formats,
        {{ null_junk('"RESOURCE_URLS"') }} as resource_urls,
        {{ null_junk('"TAGS"') }} as tags,
        {{ null_junk('"IS_HVD"') }} as is_hvd,
        {{ null_junk('"ACCESS_URL"') }} as access_url,
        {{ null_junk('"LANGUAGE"') }} as language,
        _INGESTED_AT as _loaded_at,
        'https://data.gov.gr/' as _source_url

    from source

)

select * from renamed
