
-- Q1 probe_poisoning
-- probe NCHS modeled drug-poisoning county file: years, counties, band values
SELECT YEAR, COUNT(*) n, COUNT(DISTINCT FIPS) fips, MIN(LENGTH(FIPS)) minlen,
  LISTAGG(DISTINCT ESTIMATED_AGE_ADJUSTED_DEATH_RATE_11_CATEGORIES_IN_RANGES, ' | ') bands,
  SUM(TRY_TO_NUMBER(REPLACE(POPULATION::string, ',', ''))) pop
FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CDC_DRUG_POISONING_COUNTY GROUP BY 1 ORDER BY 1

-- Q2 top_buyers
-- ARCOS rolled up by buyer: top 15 buyers by pills (find mail-order giants that fake a county's per-person rate), plus null-FIPS share
WITH b AS (
  SELECT BUYER_DEA_NO id, ANY_VALUE(BUYER_NAME) nm, ANY_VALUE(BUYER_BUSINESS_ACTIVITY) act, ANY_VALUE(BUYER_CITY) city, ANY_VALUE(BUYER_STATE) st,
    ANY_VALUE(BUYER_COUNTY_FIPS) fips, COUNT(DISTINCT BUYER_COUNTY_FIPS) nfips, SUM(DOSAGE_UNITS) du
  FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_DEA_ARCOS WHERE TRANSACTION_CODE = 'S' GROUP BY 1)
SELECT * FROM (SELECT 'top' k, id, nm, act, city, st, fips, nfips, du FROM b ORDER BY du DESC LIMIT 15)
UNION ALL SELECT 'all', NULL, NULL, NULL, NULL, NULL, NULL, MAX(nfips), SUM(du) FROM b
UNION ALL SELECT 'null_fips', NULL, NULL, NULL, NULL, NULL, NULL, COUNT(*), SUM(du) FROM b WHERE fips IS NULL

-- Q3 county_panel
-- county panel: ARCOS pills by buyer county (all buyers, and with mail-order/central-fill buyers removed),
-- 2006-12 population and modeled overdose baseline (NCHS band midpoints), 2019-24 overdose (CDC injury, unsuppressed years only)
WITH b AS (
  SELECT BUYER_DEA_NO id, ANY_VALUE(BUYER_NAME) nm, ANY_VALUE(BUYER_COUNTY_FIPS) fips, SUM(DOSAGE_UNITS) du,
    SUM(IFF(DRUG_NAME = 'OXYCODONE' AND DOSAGE_STRENGTH >= 30, DOSAGE_UNITS, 0)) o30
  FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_DEA_ARCOS WHERE TRANSACTION_CODE = 'S' GROUP BY 1),
bx AS (SELECT b.*, (du > 4e7 OR nm ILIKE '%MAIL%' OR nm ILIKE 'OPTUMRX%' OR nm ILIKE 'HUMANA PHARMACY%' OR nm ILIKE 'EXPRESS SCRIPTS%'
          OR nm ILIKE 'MEDCO%' OR nm ILIKE '%CAREMARK%' OR nm ILIKE 'INJURED WORKERS%' OR nm ILIKE 'ENCLARA%' OR nm ILIKE 'PMSI%') ex FROM b),
ar AS (SELECT fips, SUM(du) du_all, SUM(IFF(ex, 0, du)) du, SUM(IFF(ex, 0, o30)) o30, COUNT_IF(ex) n_ex, COUNT(*) n_buyers FROM bx WHERE fips IS NOT NULL GROUP BY 1),
np AS (SELECT FIPS fips, ANY_VALUE(COUNTY) county, ANY_VALUE(ST) st,
    AVG(IFF(YEAR BETWEEN 2006 AND 2012, TRY_TO_NUMBER(REPLACE(POPULATION::string, ',', '')), NULL)) pop0612,
    COUNT_IF(YEAR BETWEEN 2006 AND 2012) y0612,
    AVG(IFF(YEAR BETWEEN 2006 AND 2012, IFF(b0 LIKE '>%', 31, (TRY_TO_DOUBLE(SPLIT_PART(b0, '-', 1)) + TRY_TO_DOUBLE(SPLIT_PART(b0, '-', 2))) / 2), NULL)) base0612,
    COUNT_IF(YEAR BETWEEN 2006 AND 2012 AND b0 LIKE '>%') top0612,
    AVG(IFF(YEAR = 2015, IFF(b0 LIKE '>%', 31, (TRY_TO_DOUBLE(SPLIT_PART(b0, '-', 1)) + TRY_TO_DOUBLE(SPLIT_PART(b0, '-', 2))) / 2), NULL)) base2015
  FROM (SELECT *, ESTIMATED_AGE_ADJUSTED_DEATH_RATE_11_CATEGORIES_IN_RANGES b0 FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CDC_DRUG_POISONING_COUNTY) GROUP BY 1),
od AS (SELECT GEOID fips, COUNT(*) rows_all,
    COUNT_IF(TRY_TO_NUMBER(COUNT_SUP::string) IS NOT NULL AND RATE >= 0) y_ok,
    AVG(IFF(TRY_TO_NUMBER(COUNT_SUP::string) IS NOT NULL AND RATE >= 0, RATE, NULL)) rate_avg,
    SUM(IFF(TRY_TO_NUMBER(COUNT_SUP::string) IS NOT NULL AND RATE > 0, TRY_TO_NUMBER(COUNT_SUP::string), NULL)) deaths,
    SUM(IFF(TRY_TO_NUMBER(COUNT_SUP::string) IS NOT NULL AND RATE > 0, TRY_TO_NUMBER(COUNT_SUP::string) / RATE * 1e5, NULL)) popyrs
  FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CDC_INJURY_VIOLENCE_COUNTY
  WHERE INTENT = 'Drug_OD' AND PERIOD IN ('2019','2020','2021','2022','2023','2024') AND LENGTH(GEOID) = 5 GROUP BY 1)
SELECT COALESCE(np.fips, ar.fips, od.fips) fips, np.county, np.st, ROUND(np.pop0612) pop0612, np.y0612, ar.du_all, ar.du, ar.o30, ar.n_ex, ar.n_buyers,
  ROUND(np.base0612, 2) base0612, np.top0612, np.base2015, od.rows_all, od.y_ok, ROUND(od.rate_avg, 2) rate_avg, od.deaths, ROUND(od.popyrs) popyrs
FROM np FULL OUTER JOIN ar ON ar.fips = np.fips FULL OUTER JOIN od ON od.fips = COALESCE(np.fips, ar.fips)
ORDER BY 1

-- Q4 dim_county
-- 2020 county population for the 2019-24 denominator
SELECT COUNTY_FIPS, COUNTY_NAME, STATE_NAME, POPULATION_2020 FROM LIBRARY_MARTS.CORE.DIM_COUNTY

-- Q5 foodcity_reporters
-- who shipped to Food City pharmacies (TN/VA/KY/GA) and to every Knox County TN pharmacy: buyer x reporter rollup, code S only
SELECT BUYER_DEA_NO, ANY_VALUE(BUYER_NAME) buyer, ANY_VALUE(BUYER_ADDL_CO_INFO) addl, ANY_VALUE(BUYER_ADDRESS1) addr, ANY_VALUE(BUYER_CITY) city, ANY_VALUE(BUYER_STATE) st, ANY_VALUE(BUYER_COUNTY_FIPS) fips,
  ANY_VALUE(BUYER_BUSINESS_ACTIVITY) act, REPORTER_DEA_NO, ANY_VALUE(REPORTER_NAME) reporter, ANY_VALUE(REPORTER_FAMILY) family, ANY_VALUE(REPORTER_CITY) rcity, ANY_VALUE(REPORTER_STATE) rst,
  ANY_VALUE(REPORTER_BUSINESS_ACTIVITY) ract,
  SUM(DOSAGE_UNITS) du, SUM(IFF(DRUG_NAME = 'OXYCODONE' AND DOSAGE_STRENGTH >= 30, DOSAGE_UNITS, 0)) o30,
  MIN(YEAR(TRANSACTION_DATE)) y0, MAX(YEAR(TRANSACTION_DATE)) y1, COUNT(*) n
FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_DEA_ARCOS
WHERE TRANSACTION_CODE = 'S' AND ((BUYER_NAME ILIKE 'FOOD CITY%' AND BUYER_STATE IN ('TN','VA','KY','GA'))
   OR (BUYER_COUNTY_FIPS = '47093' AND BUYER_BUSINESS_ACTIVITY IN ('RETAIL PHARMACY','CHAIN PHARMACY')))
GROUP BY BUYER_DEA_NO, REPORTER_DEA_NO
-- (Q5 failed: no address columns in the mart; rerun without them)

-- Q6 foodcity_reporters
-- who shipped to Food City pharmacies (TN/VA/KY/GA) and to every Knox County TN pharmacy: buyer x reporter rollup, code S only
SELECT BUYER_DEA_NO, ANY_VALUE(BUYER_NAME) buyer, ANY_VALUE(BUYER_CITY) city, ANY_VALUE(BUYER_STATE) st, ANY_VALUE(BUYER_COUNTY_FIPS) fips,
  ANY_VALUE(BUYER_BUSINESS_ACTIVITY) act, REPORTER_DEA_NO, ANY_VALUE(REPORTER_NAME) reporter, ANY_VALUE(REPORTER_FAMILY) family, ANY_VALUE(REPORTER_CITY) rcity, ANY_VALUE(REPORTER_STATE) rst,
  ANY_VALUE(REPORTER_BUSINESS_ACTIVITY) ract,
  SUM(DOSAGE_UNITS) du, SUM(IFF(DRUG_NAME = 'OXYCODONE' AND DOSAGE_STRENGTH >= 30, DOSAGE_UNITS, 0)) o30,
  MIN(YEAR(TRANSACTION_DATE)) y0, MAX(YEAR(TRANSACTION_DATE)) y1, COUNT(*) n
FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_DEA_ARCOS
WHERE TRANSACTION_CODE = 'S' AND ((BUYER_NAME ILIKE 'FOOD CITY%' AND BUYER_STATE IN ('TN','VA','KY','GA'))
   OR (BUYER_COUNTY_FIPS = '47093' AND BUYER_BUSINESS_ACTIVITY IN ('RETAIL PHARMACY','CHAIN PHARMACY')))
GROUP BY BUYER_DEA_NO, REPORTER_DEA_NO

-- Q7 cluster_by_year
-- six-store Knoxville Food City cluster, by year and distributor: pills and oxycodone 30mg+
SELECT YEAR(TRANSACTION_DATE) yr, REPORTER_FAMILY family, SUM(DOSAGE_UNITS) du,
  SUM(IFF(DRUG_NAME = 'OXYCODONE' AND DOSAGE_STRENGTH >= 30, DOSAGE_UNITS, 0)) o30, COUNT(DISTINCT BUYER_DEA_NO) stores
FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_DEA_ARCOS
WHERE TRANSACTION_CODE = 'S' AND BUYER_DEA_NO IN ('FF1280089','BF7000526','BF9649508','BF7399531','FF0911811','FF2853100')
GROUP BY 1, 2 ORDER BY 1, 2
