{{ config(tags=['minimal_staging']) }}

-- GRAIN: NOT YET DETERMINED (profiler returned AMBIGUOUS -- needs manual review)
-- This is a passthrough staging view: snake_case rename only, no dedup.
-- Once grain is resolved, replace with a full staging model via generate_staging_models.py.
-- Generated by scripts/generate_minimal_staging.py

with source as (

    select * from {{ source('ripple_raw', 'FED_BLS_QCEW') }}

),

renamed as (

    select
        AREA_FIPS as area_fips,
        OWN_CODE as own_code,
        INDUSTRY_CODE as industry_code,
        AGGLVL_CODE as agglvl_code,
        SIZE_CODE as size_code,
        YEAR as year,
        QTR as qtr,
        DISCLOSURE_CODE as disclosure_code,
        ANNUAL_AVG_ESTABS as annual_avg_estabs,
        ANNUAL_AVG_EMPLVL as annual_avg_emplvl,
        TOTAL_ANNUAL_WAGES as total_annual_wages,
        TAXABLE_ANNUAL_WAGES as taxable_annual_wages,
        ANNUAL_CONTRIBUTIONS as annual_contributions,
        ANNUAL_AVG_WKLY_WAGE as annual_avg_wkly_wage,
        AVG_ANNUAL_PAY as avg_annual_pay,
        LQ_DISCLOSURE_CODE as lq_disclosure_code,
        LQ_ANNUAL_AVG_ESTABS as lq_annual_avg_estabs,
        LQ_ANNUAL_AVG_EMPLVL as lq_annual_avg_emplvl,
        LQ_TOTAL_ANNUAL_WAGES as lq_total_annual_wages,
        LQ_TAXABLE_ANNUAL_WAGES as lq_taxable_annual_wages,
        LQ_ANNUAL_CONTRIBUTIONS as lq_annual_contributions,
        LQ_ANNUAL_AVG_WKLY_WAGE as lq_annual_avg_wkly_wage,
        LQ_AVG_ANNUAL_PAY as lq_avg_annual_pay,
        OTY_DISCLOSURE_CODE as oty_disclosure_code,
        OTY_ANNUAL_AVG_ESTABS_CHG as oty_annual_avg_estabs_chg,
        OTY_ANNUAL_AVG_ESTABS_PCT_CHG as oty_annual_avg_estabs_pct_chg,
        OTY_ANNUAL_AVG_EMPLVL_CHG as oty_annual_avg_emplvl_chg,
        OTY_ANNUAL_AVG_EMPLVL_PCT_CHG as oty_annual_avg_emplvl_pct_chg,
        OTY_TOTAL_ANNUAL_WAGES_CHG as oty_total_annual_wages_chg,
        OTY_TOTAL_ANNUAL_WAGES_PCT_CHG as oty_total_annual_wages_pct_chg,
        OTY_TAXABLE_ANNUAL_WAGES_CHG as oty_taxable_annual_wages_chg,
        OTY_TAXABLE_ANNUAL_WAGES_PCT_CHG as oty_taxable_annual_wages_pct_chg,
        OTY_ANNUAL_CONTRIBUTIONS_CHG as oty_annual_contributions_chg,
        OTY_ANNUAL_CONTRIBUTIONS_PCT_CHG as oty_annual_contributions_pct_chg,
        OTY_ANNUAL_AVG_WKLY_WAGE_CHG as oty_annual_avg_wkly_wage_chg,
        OTY_ANNUAL_AVG_WKLY_WAGE_PCT_CHG as oty_annual_avg_wkly_wage_pct_chg,
        OTY_AVG_ANNUAL_PAY_CHG as oty_avg_annual_pay_chg,
        OTY_AVG_ANNUAL_PAY_PCT_CHG as oty_avg_annual_pay_pct_chg,
        _INGESTED_AT as _loaded_at,
        'https://data.bls.gov/cew/data/files/2022/csv/2022_annual_singlefile.zip' as _source_url

    from source

)

select * from renamed
