-- @cols_all5
SELECT TABLE_SCHEMA, TABLE_NAME, ORDINAL_POSITION, COLUMN_NAME, DATA_TYPE
FROM LIBRARY_MARTS.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME IN ('EDUCATION__FED_GOOGLE_POLADS_ADVERTISER_DECLARED_STATS','EDUCATION__FED_FRB_Z1_CSV','IMMIGRATION__FED_DHS_OHSS','IMMIGRATION__FED_DOL_OFLC','IMMIGRATION__FED_EOIR_CASES')
ORDER BY 2,3
-- @polads_declared_whole
SELECT * FROM LIBRARY_MARTS.EDUCATION.EDUCATION__FED_GOOGLE_POLADS_ADVERTISER_DECLARED_STATS
-- @z1_whole
SELECT * FROM LIBRARY_MARTS.EDUCATION.EDUCATION__FED_FRB_Z1_CSV
-- @ohss_whole
SELECT * FROM LIBRARY_MARTS.IMMIGRATION.IMMIGRATION__FED_DHS_OHSS
