-- @oflc_extract
SELECT CASE_NUMBER, CASE_STATUS, CASE_SUBMITTED, DECISION_DATE, VISA_CLASS, SOC_CODE, SOC_TITLE, FULL_TIME_POSITION,
       TOTAL_WORKER_POSITIONS, NEW_EMPLOYMENT, CONTINUED_EMPLOYMENT, CHANGE_EMPLOYER, AMENDED_PETITION,
       EMPLOYER_NAME, EMPLOYER_ADDRESS1, EMPLOYER_CITY, EMPLOYER_STATE, EMPLOYER_POSTAL_CODE, EMPLOYER_PHONE, NAICS_CODE,
       AGENT_ATTORNEY_LAW_FIRM_BUSINESS_NAME, WORKSITE_WORKERS_1, SECONDARY_ENTITY_1, SECONDARY_ENTITY_BUSINESS_NAME_1,
       WORKSITE_ADDRESS1_1, WORKSITE_CITY_1, WORKSITE_STATE_1, WORKSITE_POSTAL_CODE_1,
       WAGE_RATE_OF_PAY_FROM_1, WAGE_RATE_OF_PAY_TO_1, WAGE_UNIT_OF_PAY_1, PREVAILING_WAGE_1, PW_UNIT_OF_PAY_1, PW_WAGE_LEVEL_1,
       PW_OTHER_SOURCE_1, PW_SURVEY_NAME_1, H_1B_DEPENDENT, WILLFUL_VIOLATOR, STATUTORY_BASIS, MASTERS_EXEMPTION,
       (IFF(NULLIF(TRIM(WORKSITE_STATE_2),'') IS NOT NULL,1,0)+IFF(NULLIF(TRIM(WORKSITE_STATE_3),'') IS NOT NULL,1,0)+IFF(NULLIF(TRIM(WORKSITE_STATE_4),'') IS NOT NULL,1,0)
        +IFF(NULLIF(TRIM(WORKSITE_STATE_5),'') IS NOT NULL,1,0)+IFF(NULLIF(TRIM(WORKSITE_STATE_6),'') IS NOT NULL,1,0)+IFF(NULLIF(TRIM(WORKSITE_STATE_7),'') IS NOT NULL,1,0)
        +IFF(NULLIF(TRIM(WORKSITE_STATE_8),'') IS NOT NULL,1,0)+IFF(NULLIF(TRIM(WORKSITE_STATE_9),'') IS NOT NULL,1,0)+IFF(NULLIF(TRIM(WORKSITE_STATE_10),'') IS NOT NULL,1,0)) AS EXTRA_WORKSITES
FROM LIBRARY_MARTS.IMMIGRATION.IMMIGRATION__FED_DOL_OFLC
