-- @eoir_profile_by_custody
SELECT CUSTODY, CUSTODY_LABEL, COUNT(*) n, COUNT(DISTINCT CASE_ID) cases, COUNT_IF(FIELD_COUNT <> 39) odd_fields,
       COUNT_IF(IS_LPR) lpr_true, COUNT_IF(NOT IS_LPR) lpr_false, COUNT_IF(IS_LPR IS NULL) lpr_null,
       COUNT(DATE_DETAINED) detained_filled, COUNT(DATE_RELEASED) released_filled, COUNT(DATE_OF_ENTRY) entry_filled,
       MIN(DATE_DETAINED) det0, MAX(DATE_DETAINED) det1, COUNT_IF(DATE_DETAINED > '2026-09-24') det_future,
       MAX(ADDRESS_CHANGED_AT) addr_max, COUNT_IF(ADDRESS_CHANGED_AT > '2026-09-24') addr_future,
       MAX(IFF(LATEST_HEARING_AT <= '2026-09-24', LATEST_HEARING_AT, NULL)) hear_past_max, COUNT_IF(LATEST_HEARING_AT > '2026-09-24') hear_future,
       MIN(_LOADED_AT) load0, MAX(_LOADED_AT) load1, COUNT(DISTINCT _SOURCE_RUN_ID) runs,
       COUNT_IF(ALIEN_ZIPCODE = '00000') zip0, COUNT(DISTINCT COURT_CODE) courts
FROM LIBRARY_MARTS.IMMIGRATION.IMMIGRATION__FED_EOIR_CASES
GROUP BY 1,2 ORDER BY n DESC
-- @eoir_detained_month_by_residence
SELECT DATE_TRUNC('month', DATE_DETAINED)::DATE mon,
       CASE WHEN DATE_OF_ENTRY IS NULL THEN 'no_entry_date'
            WHEN DATEDIFF('day', DATE_OF_ENTRY, DATE_DETAINED) < 0 THEN 'entry_after_detained'
            WHEN DATEDIFF('day', DATE_OF_ENTRY, DATE_DETAINED) <= 30 THEN 'a_0_30d'
            WHEN DATEDIFF('day', DATE_OF_ENTRY, DATE_DETAINED) < 730 THEN 'b_31d_2y'
            WHEN DATEDIFF('day', DATE_OF_ENTRY, DATE_DETAINED) < 3652 THEN 'c_2_10y'
            ELSE 'd_10y_plus' END bucket,
       COUNT(*) n, COUNT_IF(IS_LPR) lpr, COUNT_IF(CUSTODY = 'D') cust_d, COUNT_IF(DATE_RELEASED IS NOT NULL) released
FROM LIBRARY_MARTS.IMMIGRATION.IMMIGRATION__FED_EOIR_CASES
WHERE DATE_DETAINED >= '2018-01-01' AND DATE_DETAINED <= '2026-09-24'
GROUP BY 1,2 ORDER BY 1,2
