-- @eoir_janmay_by_entry_year
SELECT YEAR(DATE_DETAINED) det_yr, YEAR(DATE_OF_ENTRY) entry_yr, COUNT(*) n,
       MEDIAN(CASE_ID) med_case_id, MIN(CASE_ID) min_case_id, COUNT_IF(CUSTODY = 'D') cust_d, COUNT_IF(CUSTODY = 'R') cust_r
FROM LIBRARY_MARTS.IMMIGRATION.IMMIGRATION__FED_EOIR_CASES
WHERE MONTH(DATE_DETAINED) BETWEEN 1 AND 5 AND YEAR(DATE_DETAINED) IN (2023, 2024, 2025, 2026)
GROUP BY 1,2 ORDER BY 1,2
-- @eoir_caseid_calibration_border
SELECT DATE_TRUNC('quarter', DATE_DETAINED)::DATE q, COUNT(*) n,
       APPROX_PERCENTILE(CASE_ID, 0.1) p10, MEDIAN(CASE_ID) p50, APPROX_PERCENTILE(CASE_ID, 0.9) p90
FROM LIBRARY_MARTS.IMMIGRATION.IMMIGRATION__FED_EOIR_CASES
WHERE DATE_DETAINED BETWEEN '2015-01-01' AND '2026-05-31'
  AND DATE_OF_ENTRY IS NOT NULL AND DATEDIFF('day', DATE_OF_ENTRY, DATE_DETAINED) BETWEEN 0 AND 30
GROUP BY 1 ORDER BY 1
-- @eoir_nationality_docket_and_janmay_detained
SELECT NATIONALITY, COUNT(*) docket_all,
       COUNT_IF(DATE_DETAINED IS NOT NULL AND MONTH(DATE_DETAINED) <= 5 AND YEAR(DATE_DETAINED) = 2024) det24,
       COUNT_IF(DATE_DETAINED IS NOT NULL AND MONTH(DATE_DETAINED) <= 5 AND YEAR(DATE_DETAINED) = 2026) det26,
       COUNT_IF(MONTH(DATE_DETAINED) <= 5 AND YEAR(DATE_DETAINED) = 2024 AND DATEDIFF('day', DATE_OF_ENTRY, DATE_DETAINED) >= 730) res24,
       COUNT_IF(MONTH(DATE_DETAINED) <= 5 AND YEAR(DATE_DETAINED) = 2026 AND DATEDIFF('day', DATE_OF_ENTRY, DATE_DETAINED) >= 730) res26,
       COUNT_IF(MONTH(DATE_DETAINED) <= 5 AND YEAR(DATE_DETAINED) = 2026 AND DATE_OF_ENTRY IS NOT NULL) ent26,
       COUNT_IF(MONTH(DATE_DETAINED) <= 5 AND YEAR(DATE_DETAINED) = 2024 AND DATE_OF_ENTRY IS NOT NULL) ent24
FROM LIBRARY_MARTS.IMMIGRATION.IMMIGRATION__FED_EOIR_CASES
GROUP BY 1 ORDER BY docket_all DESC
