-- S01 Locate the five tables and two siblings (SCDB, transatlantic voyages)
SELECT TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, ROW_COUNT, TABLE_TYPE, LAST_ALTERED
FROM LIBRARY_MARTS.INFORMATION_SCHEMA.TABLES
WHERE TABLE_NAME IN ('SCIENCE_RESEARCH__XC_OSF_REGISTRATIONS','FCT_WAYBACK_PAGE_CHANGES','GOVERNANCE__FED_REVOLVINGDOOR_PROJECT',
  'HISTORICAL_RECORDS__FED_SLAVEVOYAGES_INTRAAMERICAN','JUDICIARY__FED_OYEZ','JUSTICE__FED_SCDB','HISTORY__FED_SLAVEVOYAGES_TRANSATLANTIC','HISTORY__FED_SLAVEVOYAGES_INTRAAMERICAN')
ORDER BY TABLE_NAME, TABLE_SCHEMA;
