-- S02 OSF: all 10 rows, key fields, to confirm it is a sample
SELECT OSF_ID, DATE_CREATED, DATE_REGISTERED, LEFT(TITLE, 70) title, REGISTRATION_SUPPLEMENT, IS_WITHDRAWN, IS_REGISTRATION,
       WITHDRAWAL_JUSTIFICATION_RAW, _SOURCE_RUN_ID, _LOADED_AT
FROM LIBRARY_MARTS.SCIENCE_RESEARCH.SCIENCE_RESEARCH__XC_OSF_REGISTRATIONS
ORDER BY DATE_REGISTERED;

-- S03 Oyez: 25 rows, which fields are filled, and whether each docket lands in the full Supreme Court Database (SCDB)
WITH s AS (
  SELECT DOCKET, TERM::STRING term, MIN(CASE_NAME) scdb_case, MIN(US_CITATION) us_cite, COUNT(*) votes
  FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_SCDB GROUP BY 1, 2)
SELECT o.DOCKET, o.TERM, o.CASE_NAME, o.DATE, o.DECISION_DATE, o.ARGUMENT_DATE,
       NULLIF(TRIM(o.DECISION),'') decision, NULLIF(TRIM(o.CITATION),'') citation, NULLIF(TRIM(o.MAJORITY_AUTHOR),'') author,
       LEFT(o.SUMMARY, 30) summary30, LENGTH(o.JUSTICE_VOTES) votes_len, o.HAS_AUDIO,
       s.scdb_case, s.us_cite, s.votes scdb_votes
FROM LIBRARY_MARTS.JUDICIARY.JUDICIARY__FED_OYEZ o
LEFT JOIN s ON s.DOCKET = o.DOCKET AND s.term = o.TERM::STRING
ORDER BY o.TERM, o.DOCKET;

-- S04 Revolving door: row shape, real sector count vs SECTOR_COUNT, position type, duplicate jobs
WITH r AS (
  SELECT *, (IFF(NULLIF(LOWER(TRIM(SECTOR1)),'nan') IS NOT NULL,1,0)+IFF(NULLIF(LOWER(TRIM(SECTOR2)),'nan') IS NOT NULL,1,0)+IFF(NULLIF(LOWER(TRIM(SECTOR3)),'nan') IS NOT NULL,1,0)
   +IFF(NULLIF(LOWER(TRIM(SECTOR4)),'nan') IS NOT NULL,1,0)+IFF(NULLIF(LOWER(TRIM(SECTOR5)),'nan') IS NOT NULL,1,0)+IFF(NULLIF(LOWER(TRIM(SECTOR6)),'nan') IS NOT NULL,1,0)
   +IFF(NULLIF(LOWER(TRIM(SECTOR7)),'nan') IS NOT NULL,1,0)+IFF(NULLIF(LOWER(TRIM(SECTOR8)),'nan') IS NOT NULL,1,0)+IFF(NULLIF(LOWER(TRIM(SECTOR9)),'nan') IS NOT NULL,1,0)
   +IFF(NULLIF(LOWER(TRIM(SECTOR10)),'nan') IS NOT NULL,1,0)+IFF(NULLIF(LOWER(TRIM(SECTOR11)),'nan') IS NOT NULL,1,0)+IFF(NULLIF(LOWER(TRIM(SECTOR12)),'nan') IS NOT NULL,1,0)
   +IFF(NULLIF(LOWER(TRIM(SECTOR14)),'nan') IS NOT NULL,1,0)+IFF(NULLIF(LOWER(TRIM(SECTOR14_1)),'nan') IS NOT NULL,1,0)+IFF(NULLIF(LOWER(TRIM(SECTOR15)),'nan') IS NOT NULL,1,0)
   +IFF(NULLIF(LOWER(TRIM(SECTOR16)),'nan') IS NOT NULL,1,0)) real_sectors
  FROM LIBRARY_MARTS.GOVERNANCE.GOVERNANCE__FED_REVOLVINGDOOR_PROJECT)
SELECT POSITION_TYPE, IS_SENATE_CONFIRMED, COUNT(*) n, COUNT(DISTINCT POSITION_KEY) keys,
       COUNT(DISTINCT POSITION_NAME, POSITION_DEPARTMENT) name_dept, COUNT(DISTINCT POSITION_DEPARTMENT) depts, COUNT(DISTINCT AGENCY) agencies,
       MIN(SECTOR_COUNT) sc_min, MAX(SECTOR_COUNT) sc_max, MIN(real_sectors) rs_min, MEDIAN(real_sectors) rs_med, MAX(real_sectors) rs_max,
       COUNT_IF(real_sectors = 0) no_sector, COUNT(DISTINCT INDUSTRY_SECTOR) industries, COUNT_IF(POSITION_DESCRIPTION IS NULL OR TRIM(POSITION_DESCRIPTION) IN ('','nan')) no_desc
FROM r GROUP BY ROLLUP(1, 2) ORDER BY 1, 2;

-- S05 Revolving door: jobs per industry (all 16 slots unpivoted), tie score mix, top departments
WITH u AS (
  SELECT POSITION_KEY, POSITION_DEPARTMENT, IS_SENATE_CONFIRMED, sector, interest
  FROM LIBRARY_MARTS.GOVERNANCE.GOVERNANCE__FED_REVOLVINGDOOR_PROJECT
  UNPIVOT INCLUDE NULLS ((sector, interest) FOR slot IN ((SECTOR1, SECTOR1_INTEREST) AS s1, (SECTOR2, SECTOR2_INTEREST) AS s2, (SECTOR3, SECTOR3_INTEREST) AS s3,
     (SECTOR4, SECTOR4_INTEREST) AS s4, (SECTOR5, SECTOR5_INTEREST) AS s5, (SECTOR6, SECTOR6_INTEREST) AS s6, (SECTOR7, SECTOR7_INTEREST) AS s7,
     (SECTOR8, SECTOR8_INTEREST) AS s8, (SECTOR9, SECTOR9_INTEREST) AS s9, (SECTOR10, SECTOR10_INTEREST) AS s10, (SECTOR11, SECTOR11_INTEREST) AS s11,
     (SECTOR12, SECTOR12_INTEREST) AS s12, (SECTOR14, SECTOR14_INTEREST) AS s14, (SECTOR14_1, SECTOR14_INTEREST_1) AS s14b,
     (SECTOR15, SECTOR15_INTEREST) AS s15, (SECTOR16, SECTOR16_INTEREST) AS s16)))
SELECT sector, COUNT(DISTINCT POSITION_KEY) jobs, COUNT_IF(interest IN ('1','1.0')) i1, COUNT_IF(interest IN ('2','2.0')) i2, COUNT_IF(interest IN ('3','3.0')) i3,
       COUNT_IF(IS_SENATE_CONFIRMED) senate, COUNT(DISTINCT POSITION_DEPARTMENT) depts
FROM u WHERE NULLIF(LOWER(TRIM(sector)),'nan') IS NOT NULL
GROUP BY 1 ORDER BY jobs DESC;

-- S06 Slave voyages: shape, duplicate voyage IDs, fill of the counting fields, load fingerprints
SELECT COUNT(*) n, COUNT(DISTINCT VOYAGEID) ids, COUNT(DISTINCT HASH(*)) distinct_rows,
       COUNT(DISTINCT VOYAGEID, SHIPNAME, YEARAM, CAPTAINA, SLAXIMP) id_ship_year_capt_n,
       MIN(TRY_TO_NUMBER(YEARAM)) y0, MAX(TRY_TO_NUMBER(YEARAM)) y1, COUNT_IF(TRY_TO_NUMBER(YEARAM) IS NULL) yr_bad,
       COUNT_IF(TRY_TO_NUMBER(SLAXIMP) IS NOT NULL) slaximp_n, SUM(TRY_TO_NUMBER(SLAXIMP)) slaximp_sum,
       COUNT_IF(TRY_TO_NUMBER(SLAMIMP) IS NOT NULL) slamimp_n, SUM(TRY_TO_NUMBER(SLAMIMP)) slamimp_sum,
       COUNT_IF(TRY_TO_NUMBER(TSLAVESD) IS NOT NULL) tslavesd_n, COUNT_IF(TRY_TO_NUMBER(SLAARRIV) IS NOT NULL) slaarriv_n,
       COUNT_IF(NULLIF(TRIM(OWNERA),'') IS NOT NULL) owner_n, COUNT_IF(NULLIF(TRIM(CAPTAINA),'') IS NOT NULL) capt_n,
       COUNT_IF(NULLIF(TRIM(SOURCEA),'') IS NOT NULL) src_n, COUNT_IF(NULLIF(TRIM(COMMENTS),'') IS NOT NULL) comments_n,
       COUNT_IF(NULLIF(TRIM(DATE_BUY1),'') IS NOT NULL) buy1_n, COUNT_IF(NULLIF(TRIM(DATEDEPC),'') IS NOT NULL) depyear_n,
       COUNT(DISTINCT SRC_SHA256) files, COUNT(DISTINCT SOURCE_RUN_ID) runs, COUNT(DISTINCT INTRAAMER) intra_vals,
       COUNT_IF(TRY_TO_NUMBER(VYMRTRAT) IS NOT NULL) mort_n
FROM LIBRARY_MARTS.HISTORICAL_RECORDS.HISTORICAL_RECORDS__FED_SLAVEVOYAGES_INTRAAMERICAN;

-- S07 Slave voyages: the most-repeated voyage IDs, what differs between the copies
SELECT VOYAGEID, COUNT(*) n, COUNT(DISTINCT HASH(*)) distinct_rows, COUNT(DISTINCT SHIPNAME) ships, COUNT(DISTINCT YEARAM) years,
       COUNT(DISTINCT CAPTAINA) capts, COUNT(DISTINCT SLAXIMP) slaximp_vals, MIN(SHIPNAME) ship_a, MAX(SHIPNAME) ship_b,
       MIN(YEARAM) y_a, MAX(YEARAM) y_b, MIN(SLA1PORT) port_a, MAX(SLA1PORT) port_b, MIN(SOURCEA) src_a
FROM LIBRARY_MARTS.HISTORICAL_RECORDS.HISTORICAL_RECORDS__FED_SLAVEVOYAGES_INTRAAMERICAN
GROUP BY 1 HAVING COUNT(*) > 1 ORDER BY n DESC LIMIT 25;

-- S08 Wayback: change kind x status x previous status, pages, dates, mimetypes
SELECT CHANGE_KIND, HTTP_STATUS, PREV_HTTP_STATUS, COUNT(*) n, COUNT(DISTINCT URLKEY) pages,
       MIN(CAPTURED_AT) t0, MAX(CAPTURED_AT) t1, COUNT(DISTINCT MIMETYPE) mimes, MIN(MIMETYPE) mime_a, MAX(MIMETYPE) mime_b,
       MEDIAN(CONTENT_BYTES) med_bytes, MEDIAN(HOURS_SINCE_PREV_CAPTURE) med_gap_h
FROM LIBRARY_MARTS.EPSTEIN.FCT_WAYBACK_PAGE_CHANGES
GROUP BY ROLLUP((1, 2, 3)) ORDER BY n DESC;

-- S09 Wayback: page families (first two path segments), pages, rows, error rows, dates
SELECT REGEXP_SUBSTR(URLKEY, '^[^)]*\)/([^/?]*(/[^/?]*)?)', 1, 1, 'e', 1) fam, COUNT(DISTINCT URLKEY) pages, COUNT(*) n,
       COUNT_IF(HTTP_STATUS >= 400) err_rows, COUNT(DISTINCT IFF(HTTP_STATUS IN (403,404,410), URLKEY, NULL)) pages_4xx,
       MIN(CAPTURED_AT) t0, MAX(CAPTURED_AT) t1, MIN(URLKEY) ex_a, MAX(URLKEY) ex_b
FROM LIBRARY_MARTS.EPSTEIN.FCT_WAYBACK_PAGE_CHANGES
GROUP BY 1 ORDER BY n DESC LIMIT 40;
