-- S10 Revolving door: jobs per industry across all 16 slots (FLATTEN, since multi-column UNPIVOT failed in S05), tie-score mix
WITH u AS (
  SELECT r.POSITION_KEY, r.POSITION_DEPARTMENT, r.IS_SENATE_CONFIRMED, f.value:s::STRING sector, f.value:i::STRING interest
  FROM LIBRARY_MARTS.GOVERNANCE.GOVERNANCE__FED_REVOLVINGDOOR_PROJECT r,
  LATERAL FLATTEN(ARRAY_CONSTRUCT(
    OBJECT_CONSTRUCT('s',SECTOR1,'i',SECTOR1_INTEREST), OBJECT_CONSTRUCT('s',SECTOR2,'i',SECTOR2_INTEREST), OBJECT_CONSTRUCT('s',SECTOR3,'i',SECTOR3_INTEREST),
    OBJECT_CONSTRUCT('s',SECTOR4,'i',SECTOR4_INTEREST), OBJECT_CONSTRUCT('s',SECTOR5,'i',SECTOR5_INTEREST), OBJECT_CONSTRUCT('s',SECTOR6,'i',SECTOR6_INTEREST),
    OBJECT_CONSTRUCT('s',SECTOR7,'i',SECTOR7_INTEREST), OBJECT_CONSTRUCT('s',SECTOR8,'i',SECTOR8_INTEREST), OBJECT_CONSTRUCT('s',SECTOR9,'i',SECTOR9_INTEREST),
    OBJECT_CONSTRUCT('s',SECTOR10,'i',SECTOR10_INTEREST), OBJECT_CONSTRUCT('s',SECTOR11,'i',SECTOR11_INTEREST), OBJECT_CONSTRUCT('s',SECTOR12,'i',SECTOR12_INTEREST),
    OBJECT_CONSTRUCT('s',SECTOR14,'i',SECTOR14_INTEREST), OBJECT_CONSTRUCT('s',SECTOR14_1,'i',SECTOR14_INTEREST_1),
    OBJECT_CONSTRUCT('s',SECTOR15,'i',SECTOR15_INTEREST), OBJECT_CONSTRUCT('s',SECTOR16,'i',SECTOR16_INTEREST))) f)
SELECT sector, COUNT(DISTINCT POSITION_KEY) jobs, COUNT_IF(interest LIKE '1%') i1, COUNT_IF(interest LIKE '2%') i2, COUNT_IF(interest LIKE '3%') i3,
       COUNT_IF(interest IS NULL OR LOWER(interest) = 'nan') i_blank, COUNT_IF(IS_SENATE_CONFIRMED) senate, COUNT(DISTINCT POSITION_DEPARTMENT) depts
FROM u WHERE NULLIF(LOWER(TRIM(sector)),'nan') IS NOT NULL
GROUP BY 1 ORDER BY jobs DESC;

-- S11 Wayback: page families (first two path segments), pages, rows, error pages, dates
SELECT REGEXP_SUBSTR(URLKEY, '^[^)]*[)]/([^/?]*(/[^/?]*)?)', 1, 1, 'e', 1) fam, COUNT(DISTINCT URLKEY) pages, COUNT(*) n,
       COUNT_IF(HTTP_STATUS >= 400) err_rows, COUNT(DISTINCT IFF(HTTP_STATUS IN (403,404,410), URLKEY, NULL)) pages_4xx,
       MIN(CAPTURED_AT) t0, MAX(CAPTURED_AT) t1, MIN(URLKEY) ex_a, MAX(URLKEY) ex_b
FROM LIBRARY_MARTS.EPSTEIN.FCT_WAYBACK_PAGE_CHANGES
GROUP BY 1 ORDER BY n DESC LIMIT 40;

-- S12 Wayback: size of each content change (bytes vs the previous change row of the same page), bucketed
WITH x AS (
  SELECT URLKEY, CAPTURED_AT, CHANGE_KIND, HTTP_STATUS, PREV_HTTP_STATUS, CONTENT_BYTES,
         LAG(CONTENT_BYTES) OVER (PARTITION BY URLKEY ORDER BY CAPTURED_AT) pb
  FROM LIBRARY_MARTS.EPSTEIN.FCT_WAYBACK_PAGE_CHANGES)
SELECT CHANGE_KIND, CASE WHEN pb IS NULL THEN 'no prev' WHEN ABS(CONTENT_BYTES-pb) <= 50 THEN 'a <=50B' WHEN ABS(CONTENT_BYTES-pb) <= 500 THEN 'b 51-500B'
         WHEN ABS(CONTENT_BYTES-pb) <= 2000 THEN 'c 501-2000B' ELSE 'd >2000B' END bucket,
       COUNT(*) n, COUNT(DISTINCT URLKEY) pages, COUNT(DISTINCT TO_DATE(CAPTURED_AT)) days, COUNT_IF(CONTENT_BYTES < pb) shrinks, COUNT_IF(CONTENT_BYTES > pb) grows
FROM x WHERE HTTP_STATUS = 200 AND COALESCE(PREV_HTTP_STATUS, 200) = 200
GROUP BY 1, 2 ORDER BY 1, 2;

-- S13 Wayback: per page, did a 403/401/404 ever stick? Pages by worst status seen and status at their last change row
WITH p AS (
  SELECT URLKEY, MAX_BY(HTTP_STATUS, CAPTURED_AT) last_status, MAX(CAPTURED_AT) last_t,
         MAX(IFF(HTTP_STATUS IN (401,403,404), 1, 0)) ever_err, MAX(IFF(HTTP_STATUS = 404, 1, 0)) ever_404,
         MAX(IFF(HTTP_STATUS = 200, CAPTURED_AT, NULL)) last_200, MIN(IFF(HTTP_STATUS IN (401,403,404), CAPTURED_AT, NULL)) first_err
  FROM LIBRARY_MARTS.EPSTEIN.FCT_WAYBACK_PAGE_CHANGES GROUP BY 1)
SELECT ever_err, ever_404, last_status, COUNT(*) pages, COUNT_IF(last_200 > first_err) back_to_200_after_err,
       MIN(last_t) last_t_min, MAX(last_t) last_t_max, MIN(URLKEY) ex_a, MAX(URLKEY) ex_b
FROM p GROUP BY 1, 2, 3 ORDER BY pages DESC;

-- S14 Slave voyages: routes, main buying region x main landing region, people, years, a sample source to label the codes
SELECT MAJBYIMP buy_region, MJSELIMP land_region, COUNT(*) voyages, SUM(TRY_TO_NUMBER(SLAXIMP)) embarked, SUM(TRY_TO_NUMBER(SLAMIMP)) landed,
       MIN(TRY_TO_NUMBER(YEARAM)) y0, MAX(TRY_TO_NUMBER(YEARAM)) y1, MEDIAN(TRY_TO_NUMBER(YEARAM)) ymed,
       MODE(MJBYPTIMP) top_buy_port, MODE(MJSLPTIMP) top_land_port, MODE(LEFT(SOURCEA, 40)) top_source, MIN(LEFT(COMMENTS, 60)) a_comment
FROM LIBRARY_MARTS.HISTORICAL_RECORDS.HISTORICAL_RECORDS__FED_SLAVEVOYAGES_INTRAAMERICAN
GROUP BY 1, 2 ORDER BY landed DESC NULLS LAST LIMIT 40;
