-- S29 Wayback: the 2026-03-11 19:2x probe of data-set-13..40: status, bytes, digest, next to every other capture in that 20-minute window and the 403/404 byte norms
SELECT 'window' grp, CAPTURED_AT, REGEXP_REPLACE(URLKEY, '^gov,justice[)]/epstein/doj-disclosures', '') path, HTTP_STATUS, CONTENT_BYTES, CONTENT_DIGEST, MIMETYPE, CHANGE_KIND
FROM LIBRARY_MARTS.EPSTEIN.FCT_WAYBACK_PAGE_CHANGES
WHERE CAPTURED_AT BETWEEN '2026-03-11 19:15:00' AND '2026-03-11 19:35:00'
UNION ALL
SELECT 'norm ' || HTTP_STATUS, NULL, 'all rows: n=' || COUNT(*) || ' pages=' || COUNT(DISTINCT URLKEY) || ' digests=' || COUNT(DISTINCT CONTENT_DIGEST),
       HTTP_STATUS, MEDIAN(CONTENT_BYTES), 'min ' || MIN(CONTENT_BYTES) || ' max ' || MAX(CONTENT_BYTES), NULL, NULL
FROM LIBRARY_MARTS.EPSTEIN.FCT_WAYBACK_PAGE_CHANGES WHERE HTTP_STATUS IN (401, 403, 404) GROUP BY HTTP_STATUS
ORDER BY 1 DESC, 2;
