{{ config(tags=['spine_generated']) }}

-- GRAIN: one row per record (spine_entity not determined -- no registry hint available) (ID is unique)
-- SPINE_ENTITY: (not determined)  (natural_key: ID)
-- Generated by scripts/generate_staging_models.py from SOURCE_REGISTRY -- deterministic,
-- no LLM. Casts kept as landed (TEXT) -- add explicit type casts by hand once each
-- column's real type is confirmed; this generator has no semantic type knowledge.
-- spine_entity not determined (grain/natural_key proven, but no registry hint says what this row is ABOUT) -- no SPINE_ENTITY_ID emitted.

with source as (

    select * from {{ source('ripple_raw', 'INTL_EMBL_ENSEMBL') }}

),

renamed as (

    select
        "ID" as id,
        "SPECIES" as species,
        "ASSEMBLY" as assembly,
        "REGION" as region,
        "FEATURE_TYPE" as feature_type,
        "SYMBOL" as symbol,
        "BIOTYPE" as biotype,
        "STRAND" as strand,
        "C_START" as c_start,
        "END" as end,
        "SEQ_REGION_NAME" as seq_region_name,
        "VERSION" as version,
        "DB_TYPE" as db_type,
        "TAXON_ID" as taxon_id,
        "CONSEQUENCE_TYPE" as consequence_type,
        "ALLELE_STRING" as allele_string,
        "POPULATION_NAME" as population_name,
        "ONTOLOGY_TERM" as ontology_term,
        "SOURCE_NAME" as source_name,
        "PRIMARY_ACCESSION" as primary_accession,
        _INGESTED_AT as _loaded_at,
        'https://rest.ensembl.org/' as _source_url

    from source

)

select * from renamed
qualify row_number() over (partition by id order by _loaded_at desc) = 1
