    with source as (
        select * from {{ source('ripple_raw', 'FED_EIA860_PLANT_Y2021') }}
    )

    select
        "UTILITY_ID",
"UTILITY_NAME",
"PLANT_CODE",
"PLANT_NAME",
"STREET_ADDRESS",
"CITY",
"STATE",
"ZIP",
"COUNTY",
"LATITUDE",
"LONGITUDE",
"NERC_REGION",
"BALANCING_AUTHORITY_CODE",
"BALANCING_AUTHORITY_NAME",
"NAME_OF_WATER_SOURCE",
"PRIMARY_PURPOSE_NAICS_CODE",
"REGULATORY_STATUS",
"SECTOR",
"SECTOR_NAME",
"FERC_COGENERATION_STATUS",
"FERC_COGENERATION_DOCKET_NUMBER",
"FERC_SMALL_POWER_PRODUCER_STATUS",
"FERC_SMALL_POWER_PRODUCER_DOCKET_NUMBER",
"FERC_EXEMPT_WHOLESALE_GENERATOR_STATUS",
"FERC_EXEMPT_WHOLESALE_GENERATOR_DOCKET_NUMBER",
"ASH_IMPOUNDMENT",
"ASH_IMPOUNDMENT_LINED",
"ASH_IMPOUNDMENT_STATUS",
"TRANSMISSION_OR_DISTRIBUTION_SYSTEM_OWNER",
"TRANSMISSION_OR_DISTRIBUTION_SYSTEM_OWNER_ID",
"TRANSMISSION_OR_DISTRIBUTION_SYSTEM_OWNER_STATE",
"GRID_VOLTAGE_KV",
"GRID_VOLTAGE_2_KV",
"GRID_VOLTAGE_3_KV",
"ENERGY_STORAGE",
"NATURAL_GAS_LDC_NAME",
"NATURAL_GAS_PIPELINE_NAME_1",
"NATURAL_GAS_PIPELINE_NAME_2",
"NATURAL_GAS_PIPELINE_NAME_3",
"PIPELINE_NOTES",
"NATURAL_GAS_STORAGE",
"LIQUEFIED_NATURAL_GAS_STORAGE",
_INGESTED_AT,
_SOURCE_RUN_ID
    from source
    qualify row_number() over (
        partition by "UTILITY_ID"
        order by _INGESTED_AT desc
    ) = 1
