SELECT TABLE_NAME, ROW_COUNT_HINT, LISTAGG(COLUMN_NAME, ', ') WITHIN GROUP (ORDER BY ORDINAL_POSITION) cols
FROM (
  SELECT c.TABLE_NAME, t.ROW_COUNT ROW_COUNT_HINT, c.COLUMN_NAME, c.ORDINAL_POSITION
  FROM LIBRARY_RAW.INFORMATION_SCHEMA.COLUMNS c
  JOIN LIBRARY_RAW.INFORMATION_SCHEMA.TABLES t ON t.TABLE_SCHEMA = c.TABLE_SCHEMA AND t.TABLE_NAME = c.TABLE_NAME
  WHERE c.TABLE_SCHEMA = 'LANDING'
    AND (c.TABLE_NAME LIKE 'FED_EIA860%Y20%' OR c.TABLE_NAME LIKE 'FED_EIA860%MULTI%')
    AND (c.COLUMN_NAME ILIKE '%SWITCH%' OR c.COLUMN_NAME ILIKE '%STATUS%' OR c.COLUMN_NAME ILIKE 'ENERGY_SOURCE_1%'
         OR c.COLUMN_NAME ILIKE '%WINTER%' OR c.COLUMN_NAME ILIKE 'PLANT_CODE%' OR c.COLUMN_NAME ILIKE 'PLANT_ID%'
         OR c.COLUMN_NAME ILIKE 'GENERATOR_ID%' OR c.COLUMN_NAME ILIKE '%BALANCING%' OR c.COLUMN_NAME ILIKE '%SHEET%'
         OR c.COLUMN_NAME ILIKE 'OPERATING_YEAR%' OR c.COLUMN_NAME ILIKE 'SECTOR%' OR c.COLUMN_NAME ILIKE '%MULTIPLE%' OR c.COLUMN_NAME ILIKE '_SRC_FILE')
)
GROUP BY 1,2 ORDER BY 1
