WITH p AS (
  SELECT PLANT_CODE, MAX(BALANCING_AUTHORITY_CODE) ba, COUNT(DISTINCT BALANCING_AUTHORITY_CODE) ba_n, MAX(SECTOR_NAME) p_sector, COUNT(*) pn
  FROM LIBRARY_MARTS.ENERGY.ENERGY__FED_EIA860_2_PLANT GROUP BY 1
), m AS (
  SELECT m.*, COUNT(*) OVER (PARTITION BY PLANT_CODE, GENERATOR_ID) mk FROM LIBRARY_MARTS.ENERGY.ENERGY__FED_EIA860_3_5_MULTIFUEL m
), g AS (
  SELECT g.*, COUNT(*) OVER (PARTITION BY PLANT_CODE, GENERATOR_ID) gk FROM LIBRARY_MARTS.ENERGY.ENERGY__FED_EIA860_3_1_GENERATOR g
)
SELECT COALESCE(g.PLANT_CODE, m.PLANT_CODE) plant_code, COALESCE(g.GENERATOR_ID, m.GENERATOR_ID) gen_id,
  g.STATUS g_status, m.STATUS m_status, g.ENERGY_SOURCE_1 g_es1, g.ENERGY_SOURCE_2 g_es2, g.ENERGY_SOURCE_3 g_es3,
  m.ENERGY_SOURCE_1 m_es1, m.ENERGY_SOURCE_2 m_es2,
  g.PRIME_MOVER, g.TECHNOLOGY, g.SECTOR_NAME g_sector, g.ASSOCIATED_WITH_COMBINED_HEAT_AND_POWER_SYSTEM chp,
  g.OPERATING_YEAR, g.PLANNED_RETIREMENT_YEAR, g.WINTER_CAPACITY_MW g_winter, g.SUMMER_CAPACITY_MW g_summer,
  g.SWITCH_BETWEEN_OIL_AND_NATURAL_GAS g_switch, g.MULTIPLE_FUELS g_multi,
  m.SWITCH_BETWEEN_OIL_AND_NATURAL_GAS m_switch, m.SWITCH_WHEN_OPERATING m_sw_op, m.COFIRE_FUELS m_cofire,
  m.TIME_TO_SWITCH_FROM_GAS_TO_OIL m_t_g2o, m.STORAGE_LIMITS m_stor, m.AIR_PERMIT_LIMITS m_air, m.OTHER_LIMITS m_other,
  m.WINTER_CAPACITY_MW m_winter, m.NET_WINTER_CAPACITY_WITH_NATURAL_GAS_MW m_w_gas, m.NET_WINTER_CAPACITY_WITH_OIL_MW m_w_oil,
  m.NET_SUMMER_CAPACITY_WITH_OIL_MW m_s_oil, m.OPERATING_YEAR m_op_year,
  COALESCE(g.UTILITY_NAME, m.UTILITY_NAME) utility_name, g.UTILITY_ID, COALESCE(g.PLANT_NAME, m.PLANT_NAME) plant_name,
  COALESCE(g.STATE, m.STATE) state, p.ba, p.ba_n, p.p_sector, p.pn, g.gk, m.mk,
  g._SRC_FILE g_src, m._SRC_FILE m_src
FROM g FULL OUTER JOIN m ON m.PLANT_CODE = g.PLANT_CODE AND m.GENERATOR_ID = g.GENERATOR_ID
LEFT JOIN p ON p.PLANT_CODE = COALESCE(g.PLANT_CODE, m.PLANT_CODE)
WHERE g.ENERGY_SOURCE_1 IN ('NG','DFO','RFO','KER','JF') OR m.PLANT_CODE IS NOT NULL
   OR 'NG' IN (g.ENERGY_SOURCE_2, g.ENERGY_SOURCE_3)
