SELECT 2019 yr, g.SHEET_NAME sheet, TRY_TO_NUMBER(TO_VARCHAR(g.PLANT_CODE)) plant_code, TO_VARCHAR(g.GENERATOR_ID) gen_id,
  TO_VARCHAR(g.STATUS) status, TO_VARCHAR(g.ENERGY_SOURCE_1) es1, TRY_TO_DOUBLE(TO_VARCHAR(g.WINTER_CAPACITY_MW)) winter,
  TRY_TO_NUMBER(TO_VARCHAR(g.OPERATING_YEAR)) op_year, TO_VARCHAR(g.SWITCH_BETWEEN_OIL_AND_NATURAL_GAS) sw, TO_VARCHAR(g.SECTOR_NAME) sector,
  p.ba, COUNT(*) OVER (PARTITION BY g.SHEET_NAME, g.PLANT_CODE, g.GENERATOR_ID) k
FROM LIBRARY_RAW.LANDING.FED_EIA860_GENERATOR_Y2019 g
LEFT JOIN (SELECT TRY_TO_NUMBER(TO_VARCHAR(PLANT_CODE)) pc, MAX(TO_VARCHAR(BALANCING_AUTHORITY_CODE)) ba FROM LIBRARY_RAW.LANDING.FED_EIA860_PLANT_Y2019 GROUP BY 1) p
  ON p.pc = TRY_TO_NUMBER(TO_VARCHAR(g.PLANT_CODE))
WHERE TO_VARCHAR(g.ENERGY_SOURCE_1) = 'NG'
UNION ALL
SELECT 2020 yr, g.SHEET_NAME sheet, TRY_TO_NUMBER(TO_VARCHAR(g.PLANT_CODE)) plant_code, TO_VARCHAR(g.GENERATOR_ID) gen_id,
  TO_VARCHAR(g.STATUS) status, TO_VARCHAR(g.ENERGY_SOURCE_1) es1, TRY_TO_DOUBLE(TO_VARCHAR(g.WINTER_CAPACITY_MW)) winter,
  TRY_TO_NUMBER(TO_VARCHAR(g.OPERATING_YEAR)) op_year, TO_VARCHAR(g.SWITCH_BETWEEN_OIL_AND_NATURAL_GAS) sw, TO_VARCHAR(g.SECTOR_NAME) sector,
  p.ba, COUNT(*) OVER (PARTITION BY g.SHEET_NAME, g.PLANT_CODE, g.GENERATOR_ID) k
FROM LIBRARY_RAW.LANDING.FED_EIA860_GENERATOR_Y2020 g
LEFT JOIN (SELECT TRY_TO_NUMBER(TO_VARCHAR(PLANT_CODE)) pc, MAX(TO_VARCHAR(BALANCING_AUTHORITY_CODE)) ba FROM LIBRARY_RAW.LANDING.FED_EIA860_PLANT_Y2020 GROUP BY 1) p
  ON p.pc = TRY_TO_NUMBER(TO_VARCHAR(g.PLANT_CODE))
WHERE TO_VARCHAR(g.ENERGY_SOURCE_1) = 'NG'
UNION ALL
SELECT 2021 yr, g.SHEET_NAME sheet, TRY_TO_NUMBER(TO_VARCHAR(g.PLANT_CODE)) plant_code, TO_VARCHAR(g.GENERATOR_ID) gen_id,
  TO_VARCHAR(g.STATUS) status, TO_VARCHAR(g.ENERGY_SOURCE_1) es1, TRY_TO_DOUBLE(TO_VARCHAR(g.WINTER_CAPACITY_MW)) winter,
  TRY_TO_NUMBER(TO_VARCHAR(g.OPERATING_YEAR)) op_year, TO_VARCHAR(g.SWITCH_BETWEEN_OIL_AND_NATURAL_GAS) sw, TO_VARCHAR(g.SECTOR_NAME) sector,
  p.ba, COUNT(*) OVER (PARTITION BY g.SHEET_NAME, g.PLANT_CODE, g.GENERATOR_ID) k
FROM LIBRARY_RAW.LANDING.FED_EIA860_GENERATOR_Y2021 g
LEFT JOIN (SELECT TRY_TO_NUMBER(TO_VARCHAR(PLANT_CODE)) pc, MAX(TO_VARCHAR(BALANCING_AUTHORITY_CODE)) ba FROM LIBRARY_RAW.LANDING.FED_EIA860_PLANT_Y2021 GROUP BY 1) p
  ON p.pc = TRY_TO_NUMBER(TO_VARCHAR(g.PLANT_CODE))
WHERE TO_VARCHAR(g.ENERGY_SOURCE_1) = 'NG'
UNION ALL
SELECT 2022 yr, g.SHEET_NAME sheet, TRY_TO_NUMBER(TO_VARCHAR(g.PLANT_CODE)) plant_code, TO_VARCHAR(g.GENERATOR_ID) gen_id,
  TO_VARCHAR(g.STATUS) status, TO_VARCHAR(g.ENERGY_SOURCE_1) es1, TRY_TO_DOUBLE(TO_VARCHAR(g.WINTER_CAPACITY_MW)) winter,
  TRY_TO_NUMBER(TO_VARCHAR(g.OPERATING_YEAR)) op_year, TO_VARCHAR(g.SWITCH_BETWEEN_OIL_AND_NATURAL_GAS) sw, TO_VARCHAR(g.SECTOR_NAME) sector,
  p.ba, COUNT(*) OVER (PARTITION BY g.SHEET_NAME, g.PLANT_CODE, g.GENERATOR_ID) k
FROM LIBRARY_RAW.LANDING.FED_EIA860_GENERATOR_Y2022 g
LEFT JOIN (SELECT TRY_TO_NUMBER(TO_VARCHAR(PLANT_CODE)) pc, MAX(TO_VARCHAR(BALANCING_AUTHORITY_CODE)) ba FROM LIBRARY_RAW.LANDING.FED_EIA860_PLANT_Y2022 GROUP BY 1) p
  ON p.pc = TRY_TO_NUMBER(TO_VARCHAR(g.PLANT_CODE))
WHERE TO_VARCHAR(g.ENERGY_SOURCE_1) = 'NG'
UNION ALL
SELECT 2023 yr, g.SHEET_NAME sheet, TRY_TO_NUMBER(TO_VARCHAR(g.PLANT_CODE)) plant_code, TO_VARCHAR(g.GENERATOR_ID) gen_id,
  TO_VARCHAR(g.STATUS) status, TO_VARCHAR(g.ENERGY_SOURCE_1) es1, TRY_TO_DOUBLE(TO_VARCHAR(g.WINTER_CAPACITY_MW)) winter,
  TRY_TO_NUMBER(TO_VARCHAR(g.OPERATING_YEAR)) op_year, TO_VARCHAR(g.SWITCH_BETWEEN_OIL_AND_NATURAL_GAS) sw, TO_VARCHAR(g.SECTOR_NAME) sector,
  p.ba, COUNT(*) OVER (PARTITION BY g.SHEET_NAME, g.PLANT_CODE, g.GENERATOR_ID) k
FROM LIBRARY_RAW.LANDING.FED_EIA860_GENERATOR_Y2023 g
LEFT JOIN (SELECT TRY_TO_NUMBER(TO_VARCHAR(PLANT_CODE)) pc, MAX(TO_VARCHAR(BALANCING_AUTHORITY_CODE)) ba FROM LIBRARY_RAW.LANDING.FED_EIA860_PLANT_Y2023 GROUP BY 1) p
  ON p.pc = TRY_TO_NUMBER(TO_VARCHAR(g.PLANT_CODE))
WHERE TO_VARCHAR(g.ENERGY_SOURCE_1) = 'NG'