SELECT 2019 yr, TRY_TO_NUMBER(TO_VARCHAR(PLANT_CODE)) plant_code, TO_VARCHAR(PLANT_NAME) plant_name, TO_VARCHAR(GENERATOR_ID) gen_id, TO_VARCHAR(STATUS) status,
  TO_VARCHAR(ENERGY_SOURCE_1) es1, TO_VARCHAR(ENERGY_SOURCE_2) es2, TO_VARCHAR(MULTIPLE_FUELS) multi, TO_VARCHAR(SWITCH_BETWEEN_OIL_AND_NATURAL_GAS) sw,
  TRY_TO_DOUBLE(TO_VARCHAR(WINTER_CAPACITY_MW)) winter, TO_VARCHAR(UTILITY_NAME) utility_name
FROM LIBRARY_RAW.LANDING.FED_EIA860_GENERATOR_Y2019
WHERE SHEET_NAME = 'Operable' AND TRY_TO_NUMBER(TO_VARCHAR(PLANT_CODE)) IN (3490, 3504, 3611, 3612, 55062) AND TO_VARCHAR(ENERGY_SOURCE_1) = 'NG'
UNION ALL
SELECT 2020 yr, TRY_TO_NUMBER(TO_VARCHAR(PLANT_CODE)) plant_code, TO_VARCHAR(PLANT_NAME) plant_name, TO_VARCHAR(GENERATOR_ID) gen_id, TO_VARCHAR(STATUS) status,
  TO_VARCHAR(ENERGY_SOURCE_1) es1, TO_VARCHAR(ENERGY_SOURCE_2) es2, TO_VARCHAR(MULTIPLE_FUELS) multi, TO_VARCHAR(SWITCH_BETWEEN_OIL_AND_NATURAL_GAS) sw,
  TRY_TO_DOUBLE(TO_VARCHAR(WINTER_CAPACITY_MW)) winter, TO_VARCHAR(UTILITY_NAME) utility_name
FROM LIBRARY_RAW.LANDING.FED_EIA860_GENERATOR_Y2020
WHERE SHEET_NAME = 'Operable' AND TRY_TO_NUMBER(TO_VARCHAR(PLANT_CODE)) IN (3490, 3504, 3611, 3612, 55062) AND TO_VARCHAR(ENERGY_SOURCE_1) = 'NG'
UNION ALL
SELECT 2021 yr, TRY_TO_NUMBER(TO_VARCHAR(PLANT_CODE)) plant_code, TO_VARCHAR(PLANT_NAME) plant_name, TO_VARCHAR(GENERATOR_ID) gen_id, TO_VARCHAR(STATUS) status,
  TO_VARCHAR(ENERGY_SOURCE_1) es1, TO_VARCHAR(ENERGY_SOURCE_2) es2, TO_VARCHAR(MULTIPLE_FUELS) multi, TO_VARCHAR(SWITCH_BETWEEN_OIL_AND_NATURAL_GAS) sw,
  TRY_TO_DOUBLE(TO_VARCHAR(WINTER_CAPACITY_MW)) winter, TO_VARCHAR(UTILITY_NAME) utility_name
FROM LIBRARY_RAW.LANDING.FED_EIA860_GENERATOR_Y2021
WHERE SHEET_NAME = 'Operable' AND TRY_TO_NUMBER(TO_VARCHAR(PLANT_CODE)) IN (3490, 3504, 3611, 3612, 55062) AND TO_VARCHAR(ENERGY_SOURCE_1) = 'NG'
UNION ALL
SELECT 2022 yr, TRY_TO_NUMBER(TO_VARCHAR(PLANT_CODE)) plant_code, TO_VARCHAR(PLANT_NAME) plant_name, TO_VARCHAR(GENERATOR_ID) gen_id, TO_VARCHAR(STATUS) status,
  TO_VARCHAR(ENERGY_SOURCE_1) es1, TO_VARCHAR(ENERGY_SOURCE_2) es2, TO_VARCHAR(MULTIPLE_FUELS) multi, TO_VARCHAR(SWITCH_BETWEEN_OIL_AND_NATURAL_GAS) sw,
  TRY_TO_DOUBLE(TO_VARCHAR(WINTER_CAPACITY_MW)) winter, TO_VARCHAR(UTILITY_NAME) utility_name
FROM LIBRARY_RAW.LANDING.FED_EIA860_GENERATOR_Y2022
WHERE SHEET_NAME = 'Operable' AND TRY_TO_NUMBER(TO_VARCHAR(PLANT_CODE)) IN (3490, 3504, 3611, 3612, 55062) AND TO_VARCHAR(ENERGY_SOURCE_1) = 'NG'
UNION ALL
SELECT 2023 yr, TRY_TO_NUMBER(TO_VARCHAR(PLANT_CODE)) plant_code, TO_VARCHAR(PLANT_NAME) plant_name, TO_VARCHAR(GENERATOR_ID) gen_id, TO_VARCHAR(STATUS) status,
  TO_VARCHAR(ENERGY_SOURCE_1) es1, TO_VARCHAR(ENERGY_SOURCE_2) es2, TO_VARCHAR(MULTIPLE_FUELS) multi, TO_VARCHAR(SWITCH_BETWEEN_OIL_AND_NATURAL_GAS) sw,
  TRY_TO_DOUBLE(TO_VARCHAR(WINTER_CAPACITY_MW)) winter, TO_VARCHAR(UTILITY_NAME) utility_name
FROM LIBRARY_RAW.LANDING.FED_EIA860_GENERATOR_Y2023
WHERE SHEET_NAME = 'Operable' AND TRY_TO_NUMBER(TO_VARCHAR(PLANT_CODE)) IN (3490, 3504, 3611, 3612, 55062) AND TO_VARCHAR(ENERGY_SOURCE_1) = 'NG'
ORDER BY plant_code, gen_id, yr