-- deep-8: coverage pass B, five tables, 2026-09-24
-- Door: Python (connect/db.py). Every statement ran after
--   ALTER SESSION SET STATEMENT_TIMEOUT_IN_SECONDS = 300
--   ALTER SESSION SET QUERY_TAG = 'coverage-b-2026-09-24'
-- Read-only. Numbered in run order.

-- [1] reimb: count + sample
SELECT COUNT(*) OVER () AS total_rows, r.*
FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_COURTLISTENER_DISCLOSURE_REIMBURSEMENTS r
LIMIT 5;

-- [2] reimb: join coverage by disclosure year
WITH r AS (
  SELECT r.*, d.YEAR_COL, d.PERSON_ID
  FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_COURTLISTENER_DISCLOSURE_REIMBURSEMENTS r
  LEFT JOIN LIBRARY_MARTS.JUSTICE.JUSTICE__FED_COURTLISTENER_FINANCIAL_DISCLOSURES d
    ON TRY_TO_NUMBER(d.ID::VARCHAR) = TRY_TO_NUMBER(r.FINANCIAL_DISCLOSURE_ID::VARCHAR)
)
SELECT YEAR_COL, COUNT(*) AS rows_, COUNT(PERSON_ID) AS with_person,
       COUNT(DISTINCT PERSON_ID) AS judges, COUNT(DISTINCT FINANCIAL_DISCLOSURE_ID) AS reports,
       COUNT_IF(REDACTED = 't') AS redacted,
       COUNT_IF(SOURCE ILIKE '%bankrupt%' OR SOURCE ILIKE 'ABI%' OR SOURCE ILIKE '%NCBJ%') AS bk_group_rows
FROM r GROUP BY 1 ORDER BY 1;

-- [3] reimb: top judges by trips 2011-19
WITH r AS (
  SELECT r.SOURCE, r.PURPOSE, d.YEAR_COL::INT AS yr, d.PERSON_ID
  FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_COURTLISTENER_DISCLOSURE_REIMBURSEMENTS r
  JOIN LIBRARY_MARTS.JUSTICE.JUSTICE__FED_COURTLISTENER_FINANCIAL_DISCLOSURES d
    ON TRY_TO_NUMBER(d.ID::VARCHAR) = TRY_TO_NUMBER(r.FINANCIAL_DISCLOSURE_ID::VARCHAR)
  WHERE d.PERSON_ID IS NOT NULL AND TRY_TO_NUMBER(d.YEAR_COL::VARCHAR) BETWEEN 2011 AND 2019
),
src AS (
  SELECT PERSON_ID, SOURCE, COUNT(*) n,
         ROW_NUMBER() OVER (PARTITION BY PERSON_ID ORDER BY COUNT(*) DESC) rk
  FROM r GROUP BY 1,2
),
j AS (
  SELECT PERSON_ID, COUNT(*) trips, COUNT(DISTINCT yr) yrs, COUNT(DISTINCT SOURCE) sources,
         COUNT_IF(SOURCE ILIKE '%bankrupt%' OR SOURCE ILIKE 'ABI%' OR SOURCE ILIKE '%NCBJ%') bk_grp
  FROM r GROUP BY 1
),
ct AS (
  SELECT PERSON_ID::VARCHAR pid, LISTAGG(DISTINCT COURT_ID, ',') courts
  FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_COURTLISTENER_POSITIONS
  WHERE COURT_ID IS NOT NULL AND COURT_ID <> '' GROUP BY 1
)
SELECT jg.NAME_FIRST || ' ' || jg.NAME_LAST AS judge, ct.courts, j.trips, j.yrs,
       ROUND(j.trips / j.yrs, 1) per_yr, j.sources, j.bk_grp,
       LISTAGG(s.SOURCE || ' (' || s.n || ')', '; ') WITHIN GROUP (ORDER BY s.n DESC) top3
FROM j
JOIN src s ON s.PERSON_ID = j.PERSON_ID AND s.rk <= 3
LEFT JOIN LIBRARY_MARTS.JUSTICE.JUSTICE__FED_COURTLISTENER_JUDGES jg ON jg.ID::VARCHAR = j.PERSON_ID::VARCHAR
LEFT JOIN ct ON ct.pid = j.PERSON_ID::VARCHAR
GROUP BY 1,2,3,4,5,6,7
ORDER BY j.trips DESC
LIMIT 30;

-- [4] reimb: bankruptcy judges vs peers, who pays
WITH ct AS (
  SELECT PERSON_ID::VARCHAR pid,
         MAX(IFF(RIGHT(COURT_ID,1)='b' AND COURT_ID NOT IN ('scotus'), 1, 0)) is_bk,
         MAX(IFF(COURT_ID LIKE 'ca%' OR COURT_ID='cafc' OR COURT_ID='scotus', 1, 0)) is_app
  FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_COURTLISTENER_POSITIONS
  WHERE COURT_ID IS NOT NULL AND COURT_ID <> '' GROUP BY 1
),
r AS (
  SELECT r.SOURCE, d.YEAR_COL::INT yr, d.PERSON_ID::VARCHAR pid,
    CASE WHEN r.SOURCE ILIKE '%conference of bankruptcy judges%' OR r.SOURCE ILIKE '%NCBJ%' THEN 'NCBJ judges own group'
         WHEN r.SOURCE ILIKE '%bankrupt%' OR r.SOURCE ILIKE 'ABI%' OR r.SOURCE ILIKE '%turnaround%' OR r.SOURCE ILIKE '%insolvency%'
              OR r.SOURCE ILIKE '%INSOL%' OR r.SOURCE ILIKE '%restructuring%' OR r.SOURCE ILIKE '%creditor%' OR r.SOURCE ILIKE '%chapter 13 trustee%' THEN 'bk practitioner group'
         WHEN r.SOURCE ILIKE '%LLP%' OR r.SOURCE ILIKE '%L.L.P%' OR r.SOURCE ILIKE '%LLC%' OR r.SOURCE ILIKE '% P.C.%' OR r.SOURCE ILIKE '%, PC%'
              OR r.SOURCE ILIKE '%PLLC%' OR r.SOURCE ILIKE '% Inc%' OR r.SOURCE ILIKE '%Corp%' OR r.SOURCE ILIKE '%law firm%' OR r.SOURCE ILIKE '%law office%' THEN 'firm or company'
         ELSE 'other' END AS kind
  FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_COURTLISTENER_DISCLOSURE_REIMBURSEMENTS r
  JOIN LIBRARY_MARTS.JUSTICE.JUSTICE__FED_COURTLISTENER_FINANCIAL_DISCLOSURES d
    ON TRY_TO_NUMBER(d.ID::VARCHAR) = TRY_TO_NUMBER(r.FINANCIAL_DISCLOSURE_ID::VARCHAR)
  WHERE d.PERSON_ID IS NOT NULL AND TRY_TO_NUMBER(d.YEAR_COL::VARCHAR) BETWEEN 2011 AND 2019
)
SELECT CASE WHEN ct.is_bk=1 THEN 'bankruptcy judge' WHEN ct.is_app=1 THEN 'appeals/scotus' WHEN ct.pid IS NULL THEN 'no court on file' ELSE 'district/magistrate/other' END grp,
       COUNT(DISTINCT r.pid) judges, COUNT(DISTINCT r.pid||'-'||r.yr) judge_years, COUNT(*) trips,
       ROUND(COUNT(*)/COUNT(DISTINCT r.pid||'-'||r.yr),2) trips_per_judge_year,
       COUNT_IF(kind='bk practitioner group') bk_prac, ROUND(100*COUNT_IF(kind='bk practitioner group')/COUNT(*),1) bk_prac_pct,
       COUNT_IF(kind='NCBJ judges own group') ncbj,
       COUNT_IF(kind='firm or company') firm_co, ROUND(100*COUNT_IF(kind='firm or company')/COUNT(*),1) firm_pct
FROM r LEFT JOIN ct ON ct.pid = r.pid
GROUP BY 1 ORDER BY 2 DESC;

-- [5] reimb: firms and companies paying judges
WITH r AS (
  SELECT r.SOURCE, r.PURPOSE, d.YEAR_COL::INT yr, d.PERSON_ID::VARCHAR pid
  FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_COURTLISTENER_DISCLOSURE_REIMBURSEMENTS r
  JOIN LIBRARY_MARTS.JUSTICE.JUSTICE__FED_COURTLISTENER_FINANCIAL_DISCLOSURES d
    ON TRY_TO_NUMBER(d.ID::VARCHAR) = TRY_TO_NUMBER(r.FINANCIAL_DISCLOSURE_ID::VARCHAR)
  WHERE d.PERSON_ID IS NOT NULL
    AND (r.SOURCE ILIKE '%LLP%' OR r.SOURCE ILIKE '%L.L.P%' OR r.SOURCE ILIKE '%LLC%' OR r.SOURCE ILIKE '% P.C.%' OR r.SOURCE ILIKE '%, PC%'
      OR r.SOURCE ILIKE '%PLLC%' OR r.SOURCE ILIKE '% Inc%' OR r.SOURCE ILIKE '%Corp%' OR r.SOURCE ILIKE '%law firm%' OR r.SOURCE ILIKE '%law office%'
      OR r.SOURCE ILIKE '%turnaround%')
)
SELECT UPPER(REGEXP_REPLACE(SOURCE, '[^A-Za-z ]', '')) src_norm, COUNT(*) trips, COUNT(DISTINCT pid) judges, MIN(yr) y0, MAX(yr) y1,
       LISTAGG(DISTINCT j.NAME_LAST, ',') WITHIN GROUP (ORDER BY j.NAME_LAST) judge_names,
       ANY_VALUE(PURPOSE) a_purpose
FROM r LEFT JOIN LIBRARY_MARTS.JUSTICE.JUSTICE__FED_COURTLISTENER_JUDGES j ON j.ID::VARCHAR = r.pid
GROUP BY 1 ORDER BY 2 DESC LIMIT 30;

-- [6] reimb: D.N.J. dockets naming Wolfson's trip sponsor
SELECT COALESCE(ASSIGNED_TO_STR,'(blank)') assigned, COUNT(*) dockets,
       MIN(DATE_FILED) first_filed, MAX(DATE_FILED) last_filed,
       LISTAGG(DISTINCT LEFT(CASE_NAME,60), ' | ') WITHIN GROUP (ORDER BY LEFT(CASE_NAME,60)) names
FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_COURTLISTENER_DOCKETS
WHERE COURT_ID IN ('njd','njb')
  AND (CASE_NAME ILIKE '%JSM at%' OR CASE_NAME ILIKE '%Edgewood Propert%' OR CASE_NAME ILIKE '%Jack Morris%'
       OR CASE_NAME ILIKE '%Sheryl Morris%' OR CASE_NAME ILIKE '%JSM Falcon%' OR CASE_NAME ILIKE '%JSM, LLC%')
GROUP BY 1 ORDER BY 2 DESC LIMIT 25;

-- [7] fjc bk: count + ch11 sample
SELECT COUNT(*) OVER () total_rows, SNAPSHOT, CASE_KEY, DISTRICT, ORIGINAL_FILING_DATE, ORIGINAL_FILING_CHAPTER, CURRENT_CHAPTER,
       DEBTOR_TYPE, NATURE_OF_DEBT, TOTAL_ASSETS, TOTAL_LIABILITIES, TOTAL_DEBT, DEBT_DISCHARGED, DEBT_NOT_DISCHARGED,
       DEBTOR1_FINAL_DISPOSITION, JOINT_ADMINISTRATION_LEAD, ESTIMATED_ASSETS
FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_FJC_IDB_BANKRUPTCY
WHERE ORIGINAL_FILING_CHAPTER = '11'
LIMIT 5;

-- [8] fjc bk: ch11 2015+ latest snapshot, discharged vs total debt by disposition
WITH c AS (
  SELECT * FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_FJC_IDB_BANKRUPTCY
  WHERE ORIGINAL_FILING_CHAPTER = '11' AND ORIGINAL_FILING_DATE >= '2015-01-01'
  QUALIFY ROW_NUMBER() OVER (PARTITION BY CASE_KEY ORDER BY SNAPSHOT DESC) = 1
)
SELECT COALESCE(NULLIF(DEBTOR1_FINAL_DISPOSITION,''),'(open/blank)') disp, DEBTOR_TYPE,
       COUNT(*) cases,
       COUNT(DEBT_DISCHARGED) dd_filled,
       COUNT_IF(DEBT_DISCHARGED = TOTAL_DEBT AND TOTAL_DEBT > 0) dd_eq_total,
       COUNT_IF(DEBT_DISCHARGED > 0) dd_pos,
       ROUND(SUM(DEBT_DISCHARGED)/1e9,1) dd_bn, ROUND(SUM(TOTAL_ASSETS)/1e9,1) assets_bn,
       ROUND(MAX(TOTAL_ASSETS)/1e9,2) max_assets_bn, ROUND(MAX(DEBT_DISCHARGED)/1e9,2) max_dd_bn,
       COUNT_IF(JOINT_ADMINISTRATION_LEAD IS NOT NULL AND JOINT_ADMINISTRATION_LEAD <> '') joint_admin
FROM c GROUP BY 1,2 HAVING COUNT(*) >= 50 ORDER BY 3 DESC LIMIT 30;

-- [9] fjc bk: ch11 business families 2015+, $1B+ by district
WITH c AS (
  SELECT CASE_KEY, DISTRICT, FILING_CALENDAR_YEAR, TOTAL_ASSETS, TOTAL_LIABILITIES,
         COALESCE(NULLIF(LEFT(JOINT_ADMINISTRATION_LEAD,12),''), SUBSTR(CASE_KEY,3,12)) fam
  FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_FJC_IDB_BANKRUPTCY
  WHERE ORIGINAL_FILING_CHAPTER = '11' AND ORIGINAL_FILING_DATE >= '2015-01-01' AND DEBTOR_TYPE <> 'i'
  QUALIFY ROW_NUMBER() OVER (PARTITION BY CASE_KEY ORDER BY SNAPSHOT DESC) = 1
),
f AS (
  SELECT fam, SUBSTR(fam,3,2) dist, COUNT(*) affiliates, MAX(TOTAL_ASSETS) fam_assets, MAX(TOTAL_LIABILITIES) fam_liab
  FROM c GROUP BY 1,2
)
SELECT dist,
       COUNT(*) families, COUNT_IF(fam_assets >= 1e9) fam_1bn_plus, COUNT_IF(fam_liab >= 1e9) liab_1bn_plus,
       ROUND(SUM(IFF(fam_assets>=1e9, fam_assets,0))/1e9,0) assets_bn_in_1bn_fams,
       ROUND(100*RATIO_TO_REPORT(COUNT_IF(fam_assets >= 1e9)) OVER (),1) pct_of_us_1bn_fams,
       ROUND(100*RATIO_TO_REPORT(COUNT(*)) OVER (),1) pct_of_all_fams,
       MAX(affiliates) max_affiliates, ROUND(MAX(fam_assets)/1e9,1) biggest_bn
FROM f GROUP BY 1 ORDER BY fam_1bn_plus DESC LIMIT 12;

-- [10] fjc bk: 20+ affiliate families by district and era; discharged on pending cases
WITH c AS (
  SELECT CASE_KEY, FILING_CALENDAR_YEAR yr, TOTAL_ASSETS, TOTAL_DEBT, DEBT_DISCHARGED, SNAPSHOT_PENDING_FLAG, DEBTOR1_FINAL_DISPOSITION,
         COALESCE(NULLIF(LEFT(JOINT_ADMINISTRATION_LEAD,12),''), SUBSTR(CASE_KEY,3,12)) fam
  FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_FJC_IDB_BANKRUPTCY
  WHERE ORIGINAL_FILING_CHAPTER = '11' AND ORIGINAL_FILING_DATE >= '2015-01-01' AND DEBTOR_TYPE <> 'i'
  QUALIFY ROW_NUMBER() OVER (PARTITION BY CASE_KEY ORDER BY SNAPSHOT DESC) = 1
),
f AS (
  SELECT fam, SUBSTR(fam,3,2) dist, MIN(yr) yr, COUNT(*) affiliates, MAX(COALESCE(TOTAL_ASSETS,0)) fam_assets
  FROM c GROUP BY 1,2 HAVING COUNT(*) >= 20
)
SELECT 'fam20+ ' || CASE WHEN dist IN ('11','08','41','12','39') THEN dist ELSE 'rest' END AS label,
       COUNT(*) n_all, COUNT_IF(yr BETWEEN 2015 AND 2018) n_15_18, COUNT_IF(yr BETWEEN 2019 AND 2022) n_19_22, COUNT_IF(yr >= 2023) n_23_plus,
       COUNT_IF(fam_assets < 1e6) assets_under_1m
FROM f GROUP BY 1
UNION ALL
SELECT 'dd check pending=' || COALESCE(SNAPSHOT_PENDING_FLAG::VARCHAR,'null') || ' disp=' || IFF(COALESCE(DEBTOR1_FINAL_DISPOSITION,'')='','blank','set'),
       COUNT(*), COUNT_IF(DEBT_DISCHARGED > 0), ROUND(SUM(DEBT_DISCHARGED)/1e9,1), COUNT_IF(DEBT_DISCHARGED = TOTAL_DEBT AND TOTAL_DEBT > 0), NULL
FROM c GROUP BY 1
ORDER BY 1;

-- [11] sanctions: count + sanctioned-company sample
SELECT COUNT(*) OVER () total_rows, ID, ENTITY_TYPE, NAME, LEFT(ALIASES,60) aliases, BIRTH_DATE, COUNTRIES, LEFT(SANCTIONS,80) sanctions, LEFT(DATASETS,120) datasets, LEFT(IDENTIFIERS,60) ids
FROM LIBRARY_MARTS.JUSTICE.JUSTICE__INTL_OPENSANCTIONS_DEFAULT
WHERE ENTITY_TYPE IN ('Company','LegalEntity') AND SANCTIONS IS NOT NULL AND SANCTIONS NOT IN ('','""','[]')
LIMIT 5;

-- [12] sanctions: sanctioned companies vs FAA registrants and USAspending R2 recipients
WITH s AS (
  SELECT NAME, COUNTRIES, LEFT(SANCTIONS,60) sanc, LEFT(DATASETS,70) ds,
    ARRAY_TO_STRING(ARRAY_SORT(SPLIT(TRIM(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(UPPER(NAME),'[^A-Z0-9 ]',' '),
      '\b(THE|LLC|L L C|INC|INCORPORATED|LTD|LIMITED|CO|CORP|CORPORATION|COMPANY|LLP|LP|PLC|SA|S A|GMBH|AG|JSC|PJSC|OJSC|CJSC|OOO|FZE|FZCO|FZ|LLP|BV|NV|SRL|SPA|PTE|PVT|DMCC)\b',' '),' +',' ')),' ')),' ') k
  FROM LIBRARY_MARTS.JUSTICE.JUSTICE__INTL_OPENSANCTIONS_DEFAULT
  WHERE ENTITY_TYPE IN ('Company','LegalEntity','Organization') AND SANCTIONS IS NOT NULL AND SANCTIONS NOT IN ('','""','[]')
),
s2 AS (SELECT k, ANY_VALUE(NAME) sname, LISTAGG(DISTINCT COUNTRIES, ',') sc, ANY_VALUE(sanc) sanc, ANY_VALUE(ds) ds, COUNT(*) srows
       FROM s WHERE ARRAY_SIZE(SPLIT(k,' ')) >= 2 AND LENGTH(k) >= 10 GROUP BY k),
faa AS (
  SELECT ARRAY_TO_STRING(ARRAY_SORT(SPLIT(TRIM(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(UPPER(REGISTRANT_NAME),'[^A-Z0-9 ]',' '),
      '\b(THE|LLC|L L C|INC|INCORPORATED|LTD|LIMITED|CO|CORP|CORPORATION|COMPANY|LLP|LP|PLC|SA|S A|GMBH|AG|JSC|PJSC|OJSC|CJSC|OOO|FZE|FZCO|FZ|LLP|BV|NV|SRL|SPA|PTE|PVT|DMCC)\b',' '),' +',' ')),' ')),' ') k,
    ANY_VALUE(REGISTRANT_NAME) oname, LISTAGG(DISTINCT STATE, ',') ostate, COUNT(*) orows, NULL::FLOAT dollars
  FROM LIBRARY_MARTS.TRANSPORT.TRANSPORT__FED_FAA_AIRCRAFT_REGISTRY GROUP BY 1
),
r2n AS (
  SELECT RECIPIENT_NAME, ANY_VALUE(RECIPIENT_COUNTRY_CODE) cc, COUNT(*) n, SUM(FEDERAL_ACTION_OBLIGATION) dol,
         MIN(ACTION_DATE) d0, MAX(ACTION_DATE) d1
  FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_USASPENDING_CONTRACTS_FULL_R2 GROUP BY 1
),
r2 AS (
  SELECT ARRAY_TO_STRING(ARRAY_SORT(SPLIT(TRIM(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(UPPER(RECIPIENT_NAME),'[^A-Z0-9 ]',' '),
      '\b(THE|LLC|L L C|INC|INCORPORATED|LTD|LIMITED|CO|CORP|CORPORATION|COMPANY|LLP|LP|PLC|SA|S A|GMBH|AG|JSC|PJSC|OJSC|CJSC|OOO|FZE|FZCO|FZ|LLP|BV|NV|SRL|SPA|PTE|PVT|DMCC)\b',' '),' +',' ')),' ')),' ') k,
    ANY_VALUE(RECIPIENT_NAME) oname, LISTAGG(DISTINCT cc, ',') || ' ' || MIN(d0)::VARCHAR || '..' || MAX(d1)::VARCHAR ostate, SUM(n) orows, SUM(dol) dollars
  FROM r2n GROUP BY 1
)
SELECT 'FAA' side, s2.sname, s2.sc, s2.sanc, s2.ds, faa.oname, faa.ostate, faa.orows, faa.dollars FROM s2 JOIN faa ON faa.k = s2.k
UNION ALL
SELECT 'USASPENDING_R2', s2.sname, s2.sc, s2.sanc, s2.ds, r2.oname, r2.ostate, r2.orows, ROUND(r2.dollars) FROM s2 JOIN r2 ON r2.k = s2.k
ORDER BY 1, 9 DESC NULLS LAST, 8 DESC
LIMIT 80;

-- [13] sanctions: rerun with RECIPIENT_COUNTRY_NAME
WITH s AS (
  SELECT NAME, COUNTRIES, LEFT(SANCTIONS,60) sanc, LEFT(DATASETS,70) ds,
    ARRAY_TO_STRING(ARRAY_SORT(SPLIT(TRIM(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(UPPER(NAME),'[^A-Z0-9 ]',' '),
      '\b(THE|LLC|L L C|INC|INCORPORATED|LTD|LIMITED|CO|CORP|CORPORATION|COMPANY|LLP|LP|PLC|SA|S A|GMBH|AG|JSC|PJSC|OJSC|CJSC|OOO|FZE|FZCO|FZ|LLP|BV|NV|SRL|SPA|PTE|PVT|DMCC)\b',' '),' +',' ')),' ')),' ') k
  FROM LIBRARY_MARTS.JUSTICE.JUSTICE__INTL_OPENSANCTIONS_DEFAULT
  WHERE ENTITY_TYPE IN ('Company','LegalEntity','Organization') AND SANCTIONS IS NOT NULL AND SANCTIONS NOT IN ('','""','[]')
),
s2 AS (SELECT k, ANY_VALUE(NAME) sname, LISTAGG(DISTINCT COUNTRIES, ',') sc, ANY_VALUE(sanc) sanc, ANY_VALUE(ds) ds, COUNT(*) srows
       FROM s WHERE ARRAY_SIZE(SPLIT(k,' ')) >= 2 AND LENGTH(k) >= 10 GROUP BY k),
faa AS (
  SELECT ARRAY_TO_STRING(ARRAY_SORT(SPLIT(TRIM(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(UPPER(REGISTRANT_NAME),'[^A-Z0-9 ]',' '),
      '\b(THE|LLC|L L C|INC|INCORPORATED|LTD|LIMITED|CO|CORP|CORPORATION|COMPANY|LLP|LP|PLC|SA|S A|GMBH|AG|JSC|PJSC|OJSC|CJSC|OOO|FZE|FZCO|FZ|LLP|BV|NV|SRL|SPA|PTE|PVT|DMCC)\b',' '),' +',' ')),' ')),' ') k,
    ANY_VALUE(REGISTRANT_NAME) oname, LISTAGG(DISTINCT STATE, ',') ostate, COUNT(*) orows, NULL::FLOAT dollars
  FROM LIBRARY_MARTS.TRANSPORT.TRANSPORT__FED_FAA_AIRCRAFT_REGISTRY GROUP BY 1
),
r2n AS (
  SELECT RECIPIENT_NAME, ANY_VALUE(LEFT(RECIPIENT_COUNTRY_NAME,14)) cc, COUNT(*) n, SUM(FEDERAL_ACTION_OBLIGATION) dol,
         MIN(ACTION_DATE) d0, MAX(ACTION_DATE) d1
  FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_USASPENDING_CONTRACTS_FULL_R2 GROUP BY 1
),
r2 AS (
  SELECT ARRAY_TO_STRING(ARRAY_SORT(SPLIT(TRIM(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(UPPER(RECIPIENT_NAME),'[^A-Z0-9 ]',' '),
      '\b(THE|LLC|L L C|INC|INCORPORATED|LTD|LIMITED|CO|CORP|CORPORATION|COMPANY|LLP|LP|PLC|SA|S A|GMBH|AG|JSC|PJSC|OJSC|CJSC|OOO|FZE|FZCO|FZ|LLP|BV|NV|SRL|SPA|PTE|PVT|DMCC)\b',' '),' +',' ')),' ')),' ') k,
    ANY_VALUE(RECIPIENT_NAME) oname, LISTAGG(DISTINCT cc, ',') || ' ' || MIN(d0)::VARCHAR || '..' || MAX(d1)::VARCHAR ostate, SUM(n) orows, SUM(dol) dollars
  FROM r2n GROUP BY 1
)
SELECT 'FAA' side, s2.sname, s2.sc, s2.sanc, s2.ds, faa.oname, faa.ostate, faa.orows, faa.dollars FROM s2 JOIN faa ON faa.k = s2.k
UNION ALL
SELECT 'USASPENDING_R2', s2.sname, s2.sc, s2.sanc, s2.ds, r2.oname, r2.ostate, r2.orows, ROUND(r2.dollars) FROM s2 JOIN r2 ON r2.k = s2.k
ORDER BY 1, 9 DESC NULLS LAST, 8 DESC
LIMIT 80;

-- [14] sanctions: real sanctions regimes only, companies + 3-word persons vs FAA and R2
WITH s AS (
  SELECT NAME, ENTITY_TYPE et, COUNTRIES, LEFT(SANCTIONS,40) sanc, LEFT(DATASETS,90) ds,
    ARRAY_TO_STRING(ARRAY_SORT(SPLIT(TRIM(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(UPPER(NAME),'[^A-Z0-9 ]',' '),
      '\b(THE|LLC|L L C|INC|INCORPORATED|LTD|LIMITED|CO|CORP|CORPORATION|COMPANY|LLP|LP|PLC|SA|S A|GMBH|AG|JSC|PJSC|OJSC|CJSC|OOO|FZE|FZCO|FZ|LLP|BV|NV|SRL|SPA|PTE|PVT|DMCC)\b',' '),' +',' ')),' ')),' ') k
  FROM LIBRARY_MARTS.JUSTICE.JUSTICE__INTL_OPENSANCTIONS_DEFAULT
  WHERE ENTITY_TYPE IN ('Company','LegalEntity','Organization','Person')
    AND (DATASETS ILIKE '%OFAC Specially%' OR DATASETS ILIKE '%OFAC Consolidated%' OR DATASETS ILIKE '%EU Financial Sanctions%'
      OR DATASETS ILIKE '%OFSI%' OR DATASETS ILIKE '%HMT%' OR DATASETS ILIKE '%UK FCDO%' OR DATASETS ILIKE '%UN Security Council%'
      OR DATASETS ILIKE '%Canadian Consolidated Autonomous%' OR DATASETS ILIKE '%Australia%Sanction%' OR DATASETS ILIKE '%SECO%'
      OR DATASETS ILIKE '%Japan%Sanction%')
),
s2 AS (SELECT k, ANY_VALUE(et) || ':' || ANY_VALUE(NAME) sname, LISTAGG(DISTINCT COUNTRIES, ',') sc, ANY_VALUE(sanc) sanc, ANY_VALUE(ds) ds, COUNT(*) srows
       FROM s WHERE LENGTH(k) >= 10 AND ARRAY_SIZE(SPLIT(k,' ')) >= IFF(et = 'Person', 3, 2) GROUP BY k),
faa AS (
  SELECT ARRAY_TO_STRING(ARRAY_SORT(SPLIT(TRIM(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(UPPER(REGISTRANT_NAME),'[^A-Z0-9 ]',' '),
      '\b(THE|LLC|L L C|INC|INCORPORATED|LTD|LIMITED|CO|CORP|CORPORATION|COMPANY|LLP|LP|PLC|SA|S A|GMBH|AG|JSC|PJSC|OJSC|CJSC|OOO|FZE|FZCO|FZ|LLP|BV|NV|SRL|SPA|PTE|PVT|DMCC)\b',' '),' +',' ')),' ')),' ') k,
    ANY_VALUE(REGISTRANT_NAME) oname, LISTAGG(DISTINCT STATE, ',') ostate, COUNT(*) orows, NULL::FLOAT dollars
  FROM LIBRARY_MARTS.TRANSPORT.TRANSPORT__FED_FAA_AIRCRAFT_REGISTRY GROUP BY 1
),
r2n AS (
  SELECT RECIPIENT_NAME, ANY_VALUE(LEFT(RECIPIENT_COUNTRY_NAME,14)) cc, COUNT(*) n, SUM(FEDERAL_ACTION_OBLIGATION) dol,
         MIN(ACTION_DATE) d0, MAX(ACTION_DATE) d1
  FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_USASPENDING_CONTRACTS_FULL_R2 GROUP BY 1
),
r2 AS (
  SELECT ARRAY_TO_STRING(ARRAY_SORT(SPLIT(TRIM(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(UPPER(RECIPIENT_NAME),'[^A-Z0-9 ]',' '),
      '\b(THE|LLC|L L C|INC|INCORPORATED|LTD|LIMITED|CO|CORP|CORPORATION|COMPANY|LLP|LP|PLC|SA|S A|GMBH|AG|JSC|PJSC|OJSC|CJSC|OOO|FZE|FZCO|FZ|LLP|BV|NV|SRL|SPA|PTE|PVT|DMCC)\b',' '),' +',' ')),' ')),' ') k,
    ANY_VALUE(RECIPIENT_NAME) oname, LISTAGG(DISTINCT cc, ',') || ' ' || MIN(d0)::VARCHAR || '..' || MAX(d1)::VARCHAR ostate, SUM(n) orows, SUM(dol) dollars
  FROM r2n GROUP BY 1
)
hits AS (
SELECT 'FAA' side, s2.sname, s2.sc, s2.sanc, s2.ds, faa.oname, faa.ostate, faa.orows, faa.dollars FROM s2 JOIN faa ON faa.k = s2.k
UNION ALL
SELECT 'USASPENDING_R2', s2.sname, s2.sc, s2.sanc, s2.ds, r2.oname, r2.ostate, r2.orows, ROUND(r2.dollars) FROM s2 JOIN r2 ON r2.k = s2.k
)
SELECT COUNT(*) OVER (PARTITION BY side) side_hits, * FROM hits
QUALIFY ROW_NUMBER() OVER (PARTITION BY side ORDER BY dollars DESC NULLS LAST, orows DESC) <= 40
ORDER BY side, dollars DESC NULLS LAST, orows DESC;

-- [15] sanctions: rerun, comma fix
WITH s AS (
  SELECT NAME, ENTITY_TYPE et, COUNTRIES, LEFT(SANCTIONS,40) sanc, LEFT(DATASETS,90) ds,
    ARRAY_TO_STRING(ARRAY_SORT(SPLIT(TRIM(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(UPPER(NAME),'[^A-Z0-9 ]',' '),
      '\b(THE|LLC|L L C|INC|INCORPORATED|LTD|LIMITED|CO|CORP|CORPORATION|COMPANY|LLP|LP|PLC|SA|S A|GMBH|AG|JSC|PJSC|OJSC|CJSC|OOO|FZE|FZCO|FZ|LLP|BV|NV|SRL|SPA|PTE|PVT|DMCC)\b',' '),' +',' ')),' ')),' ') k
  FROM LIBRARY_MARTS.JUSTICE.JUSTICE__INTL_OPENSANCTIONS_DEFAULT
  WHERE ENTITY_TYPE IN ('Company','LegalEntity','Organization','Person')
    AND (DATASETS ILIKE '%OFAC Specially%' OR DATASETS ILIKE '%OFAC Consolidated%' OR DATASETS ILIKE '%EU Financial Sanctions%'
      OR DATASETS ILIKE '%OFSI%' OR DATASETS ILIKE '%HMT%' OR DATASETS ILIKE '%UK FCDO%' OR DATASETS ILIKE '%UN Security Council%'
      OR DATASETS ILIKE '%Canadian Consolidated Autonomous%' OR DATASETS ILIKE '%Australia%Sanction%' OR DATASETS ILIKE '%SECO%'
      OR DATASETS ILIKE '%Japan%Sanction%')
),
s2 AS (SELECT k, ANY_VALUE(et) || ':' || ANY_VALUE(NAME) sname, LISTAGG(DISTINCT COUNTRIES, ',') sc, ANY_VALUE(sanc) sanc, ANY_VALUE(ds) ds, COUNT(*) srows
       FROM s WHERE LENGTH(k) >= 10 AND ARRAY_SIZE(SPLIT(k,' ')) >= IFF(et = 'Person', 3, 2) GROUP BY k),
faa AS (
  SELECT ARRAY_TO_STRING(ARRAY_SORT(SPLIT(TRIM(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(UPPER(REGISTRANT_NAME),'[^A-Z0-9 ]',' '),
      '\b(THE|LLC|L L C|INC|INCORPORATED|LTD|LIMITED|CO|CORP|CORPORATION|COMPANY|LLP|LP|PLC|SA|S A|GMBH|AG|JSC|PJSC|OJSC|CJSC|OOO|FZE|FZCO|FZ|LLP|BV|NV|SRL|SPA|PTE|PVT|DMCC)\b',' '),' +',' ')),' ')),' ') k,
    ANY_VALUE(REGISTRANT_NAME) oname, LISTAGG(DISTINCT STATE, ',') ostate, COUNT(*) orows, NULL::FLOAT dollars
  FROM LIBRARY_MARTS.TRANSPORT.TRANSPORT__FED_FAA_AIRCRAFT_REGISTRY GROUP BY 1
),
r2n AS (
  SELECT RECIPIENT_NAME, ANY_VALUE(LEFT(RECIPIENT_COUNTRY_NAME,14)) cc, COUNT(*) n, SUM(FEDERAL_ACTION_OBLIGATION) dol,
         MIN(ACTION_DATE) d0, MAX(ACTION_DATE) d1
  FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_USASPENDING_CONTRACTS_FULL_R2 GROUP BY 1
),
r2 AS (
  SELECT ARRAY_TO_STRING(ARRAY_SORT(SPLIT(TRIM(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(UPPER(RECIPIENT_NAME),'[^A-Z0-9 ]',' '),
      '\b(THE|LLC|L L C|INC|INCORPORATED|LTD|LIMITED|CO|CORP|CORPORATION|COMPANY|LLP|LP|PLC|SA|S A|GMBH|AG|JSC|PJSC|OJSC|CJSC|OOO|FZE|FZCO|FZ|LLP|BV|NV|SRL|SPA|PTE|PVT|DMCC)\b',' '),' +',' ')),' ')),' ') k,
    ANY_VALUE(RECIPIENT_NAME) oname, LISTAGG(DISTINCT cc, ',') || ' ' || MIN(d0)::VARCHAR || '..' || MAX(d1)::VARCHAR ostate, SUM(n) orows, SUM(dol) dollars
  FROM r2n GROUP BY 1
),
hits AS (
SELECT 'FAA' side, s2.sname, s2.sc, s2.sanc, s2.ds, faa.oname, faa.ostate, faa.orows, faa.dollars FROM s2 JOIN faa ON faa.k = s2.k
UNION ALL
SELECT 'USASPENDING_R2', s2.sname, s2.sc, s2.sanc, s2.ds, r2.oname, r2.ostate, r2.orows, ROUND(r2.dollars) FROM s2 JOIN r2 ON r2.k = s2.k
)
SELECT COUNT(*) OVER (PARTITION BY side) side_hits, * FROM hits
QUALIFY ROW_NUMBER() OVER (PARTITION BY side ORDER BY dollars DESC NULLS LAST, orows DESC) <= 40
ORDER BY side, dollars DESC NULLS LAST, orows DESC;

-- [16] sanctions: listing date vs contract dates for country-agreeing hits
WITH s AS (
  SELECT UPPER(REGEXP_REPLACE(NAME,'[^A-Za-z ]','')) nk, NAME, MIN(FIRST_SEEN::VARCHAR) first_seen, LISTAGG(DISTINCT LEFT(SANCTIONS,160), ' || ') sanc
  FROM LIBRARY_MARTS.JUSTICE.JUSTICE__INTL_OPENSANCTIONS_DEFAULT
  WHERE NAME IN ('NAI Logistics B.V.','Fidelis Logistic and Supply Services','EIGER Shipping SA','GEOTECH ENGINEERING LIMITED','Idronaut S.R.L.','Phnom Penh Hotel')
     OR NAME ILIKE '%Gateway Ventures FZC%'
  GROUP BY 1,2
),
r AS (
  SELECT UPPER(REGEXP_REPLACE(RECIPIENT_NAME,'[^A-Za-z ]','')) nk, RECIPIENT_NAME, AWARDING_AGENCY_NAME, TRY_TO_DATE(ACTION_DATE::VARCHAR) ad, FEDERAL_ACTION_OBLIGATION amt
  FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_USASPENDING_CONTRACTS_FULL_R2
  WHERE RECIPIENT_NAME IN ('NAI LOGISTICS B.V.','FIDELIS LOGISTIC AND SUPPLY SERVICES','EIGER SHIPPING SA','GEOTECH ENGINEERING LIMITED','IDRONAUT S.R.L.','PHNOM PENH HOTEL','GATEWAY VENTURES FZC')
)
SELECT s.NAME, s.first_seen, r.RECIPIENT_NAME, LISTAGG(DISTINCT r.AWARDING_AGENCY_NAME, ',') agencies,
       COUNT(*) actions, ROUND(SUM(r.amt)) dollars, MAX(r.ad) last_action,
       COUNT_IF(r.ad >= TRY_TO_DATE(LEFT(s.first_seen,10))) actions_after_listed, ROUND(SUM(IFF(r.ad >= TRY_TO_DATE(LEFT(s.first_seen,10)), r.amt, 0))) dollars_after,
       ANY_VALUE(s.sanc) sanc
FROM s JOIN r ON r.nk = REPLACE(s.nk,'  ',' ') OR r.nk = s.nk
GROUP BY 1,2,3 ORDER BY dollars DESC;

-- [17] schedule sb: count + sample (largest asset rows)
SELECT COUNT(*) OVER () total_rows, ACK_ID, SB_PLAN_YEAR_BEGIN_DATE, SB_EIN, SB_PN, SB_PLAN_TYPE_CODE, SB_CURR_VALUE_AST_01_AMT, SB_ACTRL_VALUE_AST_AMT,
       SB_RTD_FNDNG_TGT_AMT, SB_TERM_FNDNG_TGT_AMT, SB_LIAB_ACT_TOT_FNDNG_TGT_AMT, SB_TOT_FNDNG_TGT_AMT, SB_TOT_PARTCP_CNT, SB_PLAN_AT_RISK_IND, SB_EFF_INT_RATE_PRCNT, SB_ACTUARY_FIRM_NAME
FROM LIBRARY_MARTS.LABOR.LABOR__FED_DOL_EBSA_FORM5500_SCHEDULE_SB
ORDER BY SB_CURR_VALUE_AST_01_AMT DESC NULLS LAST
LIMIT 5;

-- [18] schedule sb: plan years, amendment dups, funded buckets
WITH d AS (
  SELECT *, COUNT(*) OVER (PARTITION BY SB_EIN, SB_PN, SB_PLAN_YEAR_BEGIN_DATE) dup_n
  FROM LIBRARY_MARTS.LABOR.LABOR__FED_DOL_EBSA_FORM5500_SCHEDULE_SB
  QUALIFY ROW_NUMBER() OVER (PARTITION BY SB_EIN, SB_PN, SB_PLAN_YEAR_BEGIN_DATE ORDER BY ACK_ID DESC) = 1
)
SELECT YEAR(SB_PLAN_YEAR_BEGIN_DATE) py, COUNT(*) plans, COUNT_IF(dup_n > 1) had_amendment_dups,
       COUNT_IF(SB_TOT_FNDNG_TGT_AMT > 0) tgt_pos,
       ROUND(SUM(SB_CURR_VALUE_AST_01_AMT)/1e9,1) assets_bn, ROUND(SUM(SB_TOT_FNDNG_TGT_AMT)/1e9,1) target_bn,
       ROUND(100*SUM(SB_CURR_VALUE_AST_01_AMT)/NULLIF(SUM(SB_TOT_FNDNG_TGT_AMT),0),1) agg_funded_pct,
       COUNT_IF(SB_TOT_FNDNG_TGT_AMT >= 1e8 AND SB_CURR_VALUE_AST_01_AMT < 0.8*SB_TOT_FNDNG_TGT_AMT) big_under80,
       COUNT_IF(SB_TOT_FNDNG_TGT_AMT >= 1e8 AND SB_CURR_VALUE_AST_01_AMT < 0.6*SB_TOT_FNDNG_TGT_AMT) big_under60,
       COUNT_IF(SB_TOT_FNDNG_TGT_AMT >= 1e8) big_plans,
       ROUND(SUM(IFF(SB_TOT_FNDNG_TGT_AMT > SB_CURR_VALUE_AST_01_AMT, SB_TOT_FNDNG_TGT_AMT - SB_CURR_VALUE_AST_01_AMT, 0))/1e9,1) shortfall_bn,
       COUNT_IF(SB_PLAN_AT_RISK_IND = '1' OR SB_PLAN_AT_RISK_IND = 1) at_risk_flag,
       COUNT_IF(SB_TOT_FNDNG_TGT_AMT = 0 AND SB_CURR_VALUE_AST_01_AMT > 0) tgt_zero_assets_pos
FROM d GROUP BY 1 ORDER BY 1;

-- [19] schedule sb: top 25 shortfalls 2024 with sponsor names
WITH d AS (
  SELECT * FROM LIBRARY_MARTS.LABOR.LABOR__FED_DOL_EBSA_FORM5500_SCHEDULE_SB
  WHERE YEAR(SB_PLAN_YEAR_BEGIN_DATE) = 2024
  QUALIFY ROW_NUMBER() OVER (PARTITION BY SB_EIN, SB_PN, SB_PLAN_YEAR_BEGIN_DATE ORDER BY ACK_ID DESC) = 1
),
m AS (SELECT ACK_ID, ANY_VALUE(SPONSOR_DFE_NAME) sp, ANY_VALUE(PLAN_NAME) pn FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_DOL_FORM5500 GROUP BY 1),
me AS (SELECT SPONS_DFE_EIN, ANY_VALUE(SPONSOR_DFE_NAME) sp FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_DOL_FORM5500 GROUP BY 1),
x AS (
  SELECT d.*, COALESCE(m.sp, me.sp) sponsor, m.pn plan_name, IFF(m.ACK_ID IS NULL, 'ein', 'ack') name_via,
         SB_TOT_FNDNG_TGT_AMT - SB_CURR_VALUE_AST_01_AMT shortfall,
         COUNT_IF(SB_UNP_MIN_CONTRIB_ALL_YR_AMT > 0) OVER () plans_unpaid_min, SUM(SB_UNP_MIN_CONTRIB_ALL_YR_AMT) OVER () unpaid_min_total,
         MEDIAN(IFF(SB_TOT_FNDNG_TGT_AMT >= 1e9, SB_CURR_VALUE_AST_01_AMT / NULLIF(SB_TOT_FNDNG_TGT_AMT,0), NULL)) OVER () med_funded_1bn
  FROM d LEFT JOIN m ON m.ACK_ID = d.ACK_ID LEFT JOIN me ON me.SPONS_DFE_EIN = d.SB_EIN
)
SELECT SB_EIN, SB_PN, LEFT(sponsor,40) sponsor, name_via, LEFT(plan_name,35) plan_name, SB_TOT_PARTCP_CNT partic,
       ROUND(SB_TOT_FNDNG_TGT_AMT/1e9,2) tgt_bn, ROUND(SB_CURR_VALUE_AST_01_AMT/1e9,2) mkt_ast_bn, ROUND(shortfall/1e9,2) short_bn,
       ROUND(100*SB_CURR_VALUE_AST_01_AMT/NULLIF(SB_TOT_FNDNG_TGT_AMT,0),1) funded_pct_mkt, SB_FNDNG_TGT_PRCNT rep_pct, SB_PR_YR_FNDNG_PRCNT prior_pct,
       ROUND(SB_TOT_EMPLR_CONTRIB_AMT/1e6,1) contrib_m, ROUND(SB_FNDNG_RQMT_TOT_AMT/1e6,1) min_req_m, SB_UNP_MIN_CONTRIB_ALL_YR_AMT unpaid_min,
       SB_EFF_INT_RATE_PRCNT rate, LEFT(SB_ACTUARY_FIRM_NAME,22) actuary,
       plans_unpaid_min, ROUND(unpaid_min_total/1e6,1) unpaid_min_total_m, ROUND(100*med_funded_1bn,1) med_funded_pct_1bn_plans
FROM x WHERE shortfall > 0 ORDER BY shortfall DESC LIMIT 25;

-- [20] schedule sb: plans with unpaid minimum contributions, named
WITH d AS (
  SELECT * FROM LIBRARY_MARTS.LABOR.LABOR__FED_DOL_EBSA_FORM5500_SCHEDULE_SB
  WHERE YEAR(SB_PLAN_YEAR_BEGIN_DATE) = 2024
  QUALIFY ROW_NUMBER() OVER (PARTITION BY SB_EIN, SB_PN, SB_PLAN_YEAR_BEGIN_DATE ORDER BY ACK_ID DESC) = 1
),
u AS (
  SELECT LPAD(REGEXP_REPLACE(SB_EIN::VARCHAR,'[^0-9]',''),9,'0') ein, SB_PN, SB_TOT_PARTCP_CNT partic, SB_TOT_FNDNG_TGT_AMT tgt, SB_CURR_VALUE_AST_01_AMT ast,
         SB_UNP_MIN_CONTRIB_ALL_YR_AMT unpaid, SB_FNDNG_RQMT_TOT_AMT minreq, SB_TOT_EMPLR_CONTRIB_AMT contrib, SB_PR_YR_FNDNG_PRCNT prior_pct,
         SB_WAIVED_AMT waived, LEFT(SB_ACTUARY_FIRM_NAME,20) actuary,
         COUNT(*) OVER () n_plans_unpaid, SUM(SB_UNP_MIN_CONTRIB_ALL_YR_AMT) OVER () tot_unpaid,
         COUNT_IF(SB_CURR_VALUE_AST_01_AMT < 0.6*SB_TOT_FNDNG_TGT_AMT) OVER () n_under60
  FROM d WHERE SB_UNP_MIN_CONTRIB_ALL_YR_AMT > 0
),
nm AS (
  SELECT LPAD(REGEXP_REPLACE(EIN::VARCHAR,'[^0-9]',''),9,'0') ein, ANY_VALUE(ENTITYNAME) nm, 'sec' src FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_SEC_EDGAR WHERE EIN IS NOT NULL GROUP BY 1
  UNION ALL
  SELECT LPAD(REGEXP_REPLACE(EIN::VARCHAR,'[^0-9]',''),9,'0'), ANY_VALUE(ORGANIZATION_NAME), 'irs_bmf' FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_IRS_BMF WHERE EIN IS NOT NULL GROUP BY 1
  UNION ALL
  SELECT LPAD(REGEXP_REPLACE(SPONS_DFE_EIN::VARCHAR,'[^0-9]',''),9,'0'), ANY_VALUE(SPONSOR_DFE_NAME), '5500' FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_DOL_FORM5500 WHERE SPONS_DFE_EIN IS NOT NULL GROUP BY 1
),
nm1 AS (SELECT ein, LISTAGG(DISTINCT src, ',') srcs, ANY_VALUE(nm) nm FROM nm WHERE ein <> '000000000' GROUP BY 1),
pb AS (SELECT LPAD(REGEXP_REPLACE(EIN::VARCHAR,'[^0-9]',''),9,'0') ein, COUNT(*) pbgc_plans, ANY_VALUE(PLAN_SPONSOR_NAME) pbgc_name FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_PBGC_TRUSTEED_PENSION_PLANS GROUP BY 1)
SELECT u.ein, u.SB_PN, LEFT(COALESCE(nm1.nm, pb.pbgc_name),38) name, nm1.srcs, pb.pbgc_plans, u.partic,
       ROUND(u.tgt/1e6,1) tgt_m, ROUND(u.ast/1e6,1) ast_m, ROUND(100*u.ast/NULLIF(u.tgt,0),1) funded_pct, u.prior_pct,
       ROUND(u.unpaid/1e6,2) unpaid_m, ROUND(u.minreq/1e6,2) minreq_m, ROUND(u.contrib/1e6,2) contrib_m, u.waived, u.actuary,
       u.n_plans_unpaid, ROUND(u.tot_unpaid/1e6,1) tot_unpaid_m, u.n_under60
FROM u LEFT JOIN nm1 ON nm1.ein = u.ein LEFT JOIN pb ON pb.ein = u.ein
ORDER BY u.unpaid DESC LIMIT 20;

-- [21] msha: count + sample (largest DAYS_LOST)
SELECT COUNT(*) OVER () total_rows, DOCUMENT_NO, MINE_ID, CONTROLLER_NAME, CAL_YR, ACCIDENT_DATE, COAL_METAL_IND, DEGREE_INJURY_CD, DEGREE_INJURY,
       IS_FATALITY, NO_INJURIES, DAYS_LOST, DAYS_RESTRICT, CLASSIFICATION, LEFT(NARRATIVE,60) narr
FROM LIBRARY_MARTS.LABOR.LABOR__FED_MSHA_ACCIDENTS
ORDER BY DAYS_LOST DESC NULLS LAST
LIMIT 5;

-- [22] msha: degree codes vs fatality flag and days lost 2015-25
SELECT DEGREE_INJURY_CD, ANY_VALUE(DEGREE_INJURY) degree, COUNT(*) rows_, COUNT_IF(IS_FATALITY::VARCHAR ILIKE 'true') fatal_flag,
       COUNT(DAYS_LOST) dl_filled, SUM(DAYS_LOST) dl_sum, MAX(DAYS_LOST) dl_max, COUNT_IF(DAYS_LOST > 365) dl_over_365,
       COUNT(DISTINCT MINE_ID) mines, MIN(CAL_YR) y0, MAX(CAL_YR) y1
FROM LIBRARY_MARTS.LABOR.LABOR__FED_MSHA_ACCIDENTS
WHERE CAL_YR BETWEEN 2015 AND 2025
GROUP BY 1 ORDER BY 3 DESC;

-- [23] msha: mine lost-time rates 2018-24 vs peer type, current headcount denominator
WITH a AS (
  SELECT MINE_ID, COUNT_IF(DEGREE_INJURY_CD IN ('03','04')) lost_time_cases,
         SUM(IFF(DEGREE_INJURY_CD IN ('03','04'), LEAST(COALESCE(DAYS_LOST,0),365), 0)) days_capped,
         SUM(IFF(DEGREE_INJURY_CD IN ('03','04'), COALESCE(DAYS_LOST,0), 0)) days_raw,
         MAX(IFF(DEGREE_INJURY_CD IN ('03','04'), COALESCE(DAYS_LOST,0), 0)) top_one,
         COUNT_IF(DEGREE_INJURY_CD = '01') deaths, COUNT_IF(DEGREE_INJURY_CD = '02') perm_disab
  FROM LIBRARY_MARTS.LABOR.LABOR__FED_MSHA_ACCIDENTS
  WHERE CAL_YR BETWEEN 2018 AND 2024 GROUP BY 1
),
m AS (
  SELECT m.MINE_ID, m.CURRENT_MINE_NAME, m.CURRENT_CONTROLLER_NAME, m.STATE, m.COAL_METAL_IND, m.CURRENT_MINE_TYPE, m.CURRENT_MINE_STATUS, m.NO_EMPLOYEES,
         a.lost_time_cases, a.days_capped, a.days_raw, a.top_one, a.deaths, a.perm_disab,
         100 * a.lost_time_cases / (m.NO_EMPLOYEES * 7) ltc_per100_yr,
         a.days_capped / (m.NO_EMPLOYEES * 7) days_per_emp_yr
  FROM LIBRARY_MARTS.LABOR.LABOR__FED_MSHA_MINES m JOIN a ON a.MINE_ID = m.MINE_ID
  WHERE m.NO_EMPLOYEES >= 100
),
p AS (
  SELECT *, MEDIAN(ltc_per100_yr) OVER (PARTITION BY COAL_METAL_IND, CURRENT_MINE_TYPE) peer_med_ltc,
            MEDIAN(days_per_emp_yr) OVER (PARTITION BY COAL_METAL_IND, CURRENT_MINE_TYPE) peer_med_days,
            COUNT(*) OVER (PARTITION BY COAL_METAL_IND, CURRENT_MINE_TYPE) peer_n
  FROM m
)
SELECT MINE_ID, LEFT(CURRENT_MINE_NAME,22) mine, LEFT(CURRENT_CONTROLLER_NAME,28) controller, STATE, COAL_METAL_IND cm, LEFT(CURRENT_MINE_TYPE,11) typ, LEFT(CURRENT_MINE_STATUS,8) status,
       NO_EMPLOYEES emp, lost_time_cases ltc, ROUND(ltc_per100_yr,1) ltc100, ROUND(peer_med_ltc,1) peer_ltc100,
       days_capped, days_raw, top_one, ROUND(days_per_emp_yr,2) d_emp_yr, ROUND(peer_med_days,2) peer_d, peer_n, deaths, perm_disab
FROM p ORDER BY days_per_emp_yr DESC LIMIT 20;

-- [24] msha: controller deaths 2015-25 and lost-time 2018-24 per current workers, 1000+ employees
WITH f AS (
  SELECT MINE_ID, COUNT(DISTINCT ACCIDENT_DATE) fatal_events, COUNT(*) deaths, MIN(ACCIDENT_DATE) first_death, MAX(ACCIDENT_DATE) last_death
  FROM LIBRARY_MARTS.LABOR.LABOR__FED_MSHA_ACCIDENTS
  WHERE DEGREE_INJURY_CD = '01' AND CAL_YR BETWEEN 2015 AND 2025 GROUP BY 1
),
lt AS (
  SELECT MINE_ID, COUNT_IF(DEGREE_INJURY_CD IN ('03','04')) ltc FROM LIBRARY_MARTS.LABOR.LABOR__FED_MSHA_ACCIDENTS WHERE CAL_YR BETWEEN 2018 AND 2024 GROUP BY 1
),
c AS (
  SELECT m.CURRENT_CONTROLLER_ID cid, ANY_VALUE(m.CURRENT_CONTROLLER_NAME) controller, MAX(m.COAL_METAL_IND) cm,
         SUM(m.NO_EMPLOYEES) emp_now, SUM(COALESCE(f.deaths,0)) deaths_15_25, SUM(COALESCE(f.fatal_events,0)) fatal_events,
         COUNT_IF(f.fatal_events >= 2) mines_2plus_fatal, COUNT_IF(f.fatal_events >= 2 AND m.CURRENT_MINE_STATUS ILIKE 'Active%') still_active_2plus,
         SUM(COALESCE(lt.ltc,0)) ltc_18_24
  FROM LIBRARY_MARTS.LABOR.LABOR__FED_MSHA_MINES m LEFT JOIN f ON f.MINE_ID = m.MINE_ID LEFT JOIN lt ON lt.MINE_ID = m.MINE_ID
  GROUP BY 1
)
SELECT cid, LEFT(controller,34) controller, cm, emp_now, deaths_15_25, fatal_events, ROUND(1000*deaths_15_25/emp_now,2) deaths_per_1k_now,
       mines_2plus_fatal, still_active_2plus, ltc_18_24, ROUND(100*ltc_18_24/(emp_now*7),2) ltc_per100_yr,
       ROUND(MEDIAN(1000*deaths_15_25/emp_now) OVER (),2) med_deaths_per_1k_big, ROUND(MEDIAN(100*ltc_18_24/(emp_now*7)) OVER (),2) med_ltc100_big
FROM c WHERE emp_now >= 1000
ORDER BY deaths_per_1k_now DESC LIMIT 25;

-- [25] msha: ACNR mines by year and controller at time of accident
SELECT a.CAL_YR, LEFT(a.CONTROLLER_NAME,30) controller_at_accident,
       COUNT_IF(a.DEGREE_INJURY_CD IN ('03','04')) ltc, COUNT_IF(a.DEGREE_INJURY_CD = '01') deaths, COUNT_IF(a.DEGREE_INJURY_CD = '02') perm,
       COUNT_IF(a.DEGREE_INJURY_CD IN ('03','04') AND a.MINE_ID = '4601437') ltc_marshall,
       SUM(IFF(a.DEGREE_INJURY_CD IN ('03','04'), LEAST(COALESCE(a.DAYS_LOST,0),365), 0)) days_capped,
       COUNT(DISTINCT a.MINE_ID) mines
FROM LIBRARY_MARTS.LABOR.LABOR__FED_MSHA_ACCIDENTS a
JOIN LIBRARY_MARTS.LABOR.LABOR__FED_MSHA_MINES m ON m.MINE_ID = a.MINE_ID
WHERE m.CURRENT_CONTROLLER_ID = '0157801' AND a.CAL_YR BETWEEN 2015 AND 2025
GROUP BY 1,2 ORDER BY 1,3 DESC;

-- [26] msha: underground coal controllers, fractures/amputations vs sprains per 100 current workers 2018-24
WITH a AS (
  SELECT m.CURRENT_CONTROLLER_ID cid, a.MINE_ID, a.NATURE_INJURY, a.DEGREE_INJURY_CD
  FROM LIBRARY_MARTS.LABOR.LABOR__FED_MSHA_ACCIDENTS a JOIN LIBRARY_MARTS.LABOR.LABOR__FED_MSHA_MINES m ON m.MINE_ID = a.MINE_ID
  WHERE a.CAL_YR BETWEEN 2018 AND 2024 AND m.COAL_METAL_IND = 'C' AND m.CURRENT_MINE_TYPE ILIKE 'Underground%'
),
e AS (
  SELECT CURRENT_CONTROLLER_ID cid, ANY_VALUE(CURRENT_CONTROLLER_NAME) controller, SUM(NO_EMPLOYEES) emp
  FROM LIBRARY_MARTS.LABOR.LABOR__FED_MSHA_MINES WHERE COAL_METAL_IND = 'C' AND CURRENT_MINE_TYPE ILIKE 'Underground%' GROUP BY 1
),
g AS (
  SELECT cid, COUNT_IF(DEGREE_INJURY_CD IN ('03','04')) ltc,
         COUNT_IF(NATURE_INJURY ILIKE '%FRACTURE%' OR NATURE_INJURY ILIKE '%AMPUTAT%' OR NATURE_INJURY ILIKE '%ENUCLEAT%') fract_amp,
         COUNT_IF(NATURE_INJURY ILIKE '%SPRAIN%' OR NATURE_INJURY ILIKE '%STRAIN%') sprain
  FROM a GROUP BY 1
)
SELECT LEFT(e.controller,32) controller, e.emp emp_now_ug_coal, g.ltc, g.fract_amp, g.sprain,
       ROUND(100*g.ltc/(e.emp*7),2) ltc_per100_yr, ROUND(100*g.fract_amp/(e.emp*7),2) fract_amp_per100_yr, ROUND(100*g.sprain/(e.emp*7),2) sprain_per100_yr,
       ROUND(100*g.fract_amp/NULLIF(g.ltc,0),1) fract_share_of_ltc_pct
FROM e JOIN g ON g.cid = e.cid WHERE e.emp >= 500 ORDER BY ltc_per100_yr DESC;

-- [27] schedule sb: unpaid minimum, timing vs arrears
WITH d AS (
  SELECT * FROM LIBRARY_MARTS.LABOR.LABOR__FED_DOL_EBSA_FORM5500_SCHEDULE_SB
  WHERE YEAR(SB_PLAN_YEAR_BEGIN_DATE) = 2024 AND SB_UNP_MIN_CONTRIB_ALL_YR_AMT > 0
  QUALIFY ROW_NUMBER() OVER (PARTITION BY SB_EIN, SB_PN, SB_PLAN_YEAR_BEGIN_DATE ORDER BY ACK_ID DESC) = 1
)
SELECT CASE WHEN ABS(SB_UNP_MIN_CONTRIB_ALL_YR_AMT - SB_FNDNG_RQMT_TOT_AMT) < 1 THEN 'unpaid = this year minimum (timing?)'
            WHEN SB_UNP_MIN_CONTRIB_ALL_YR_AMT > SB_FNDNG_RQMT_TOT_AMT + 1 THEN 'unpaid > this year minimum (arrears)'
            ELSE 'unpaid < this year minimum (part paid)' END bucket,
       COUNT(*) plans, ROUND(SUM(SB_UNP_MIN_CONTRIB_ALL_YR_AMT)/1e6,1) unpaid_m, SUM(SB_TOT_PARTCP_CNT) participants,
       COUNT_IF(SB_CURR_VALUE_AST_01_AMT < 0.6*SB_TOT_FNDNG_TGT_AMT) under60,
       COUNT_IF(SB_UNP_MIN_CONT_CUR_YR_TOT_AMT > 0) cur_yr_unpaid_filled,
       COUNT_IF(SB_TOT_EMPLR_CONTRIB_AMT >= SB_FNDNG_RQMT_TOT_AMT AND SB_FNDNG_RQMT_TOT_AMT > 0) contrib_ge_min,
       MEDIAN(SB_TOT_PARTCP_CNT) med_partic
FROM d GROUP BY 1 ORDER BY 3 DESC;

-- [28] sanctions: real regimes vs PPP borrowers
WITH s AS (
  SELECT NAME, ENTITY_TYPE et, COUNTRIES, LEFT(SANCTIONS,40) sanc, LEFT(DATASETS,90) ds,
    ARRAY_TO_STRING(ARRAY_SORT(SPLIT(TRIM(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(UPPER(NAME),'[^A-Z0-9 ]',' '),
      '\b(THE|LLC|L L C|INC|INCORPORATED|LTD|LIMITED|CO|CORP|CORPORATION|COMPANY|LLP|LP|PLC|SA|S A|GMBH|AG|JSC|PJSC|OJSC|CJSC|OOO|FZE|FZCO|FZ|LLP|BV|NV|SRL|SPA|PTE|PVT|DMCC)\b',' '),' +',' ')),' ')),' ') k
  FROM LIBRARY_MARTS.JUSTICE.JUSTICE__INTL_OPENSANCTIONS_DEFAULT
  WHERE ENTITY_TYPE IN ('Company','LegalEntity','Organization','Person')
    AND (DATASETS ILIKE '%OFAC Specially%' OR DATASETS ILIKE '%OFAC Consolidated%' OR DATASETS ILIKE '%EU Financial Sanctions%'
      OR DATASETS ILIKE '%OFSI%' OR DATASETS ILIKE '%HMT%' OR DATASETS ILIKE '%UK FCDO%' OR DATASETS ILIKE '%UN Security Council%'
      OR DATASETS ILIKE '%Canadian Consolidated Autonomous%' OR DATASETS ILIKE '%Australia%Sanction%' OR DATASETS ILIKE '%SECO%'
      OR DATASETS ILIKE '%Japan%Sanction%')
),
s2 AS (SELECT k, ANY_VALUE(et) || ':' || ANY_VALUE(NAME) sname, LISTAGG(DISTINCT COUNTRIES, ',') sc, ANY_VALUE(sanc) sanc, ANY_VALUE(ds) ds, COUNT(*) srows
       FROM s WHERE LENGTH(k) >= 10 AND ARRAY_SIZE(SPLIT(k,' ')) >= IFF(et = 'Person', 3, 2) GROUP BY k),
ppn AS (SELECT BORROWER_NAME, ANY_VALUE(BORROWER_STATE) st, COUNT(*) n, SUM(CURRENT_APPROVAL_AMOUNT) amt, MIN(DATE_APPROVED) d0
  FROM LIBRARY_MARTS.ECONOMICS.ECONOMICS__FED_SBA_PPP GROUP BY 1),
pp AS (SELECT ARRAY_TO_STRING(ARRAY_SORT(SPLIT(TRIM(REGEXP_REPLACE(REGEXP_REPLACE(REGEXP_REPLACE(UPPER(BORROWER_NAME),'[^A-Z0-9 ]',' '),
      '\b(THE|LLC|L L C|INC|INCORPORATED|LTD|LIMITED|CO|CORP|CORPORATION|COMPANY|LLP|LP|PLC|SA|S A|GMBH|AG|JSC|PJSC|OJSC|CJSC|OOO|FZE|FZCO|FZ|LLP|BV|NV|SRL|SPA|PTE|PVT|DMCC)\b',' '),' +',' ')),' ')),' ') k, ANY_VALUE(BORROWER_NAME) oname, LISTAGG(DISTINCT st, ',') ostate, SUM(n) orows, SUM(amt) dollars, MIN(d0) d0 FROM ppn GROUP BY 1)
SELECT COUNT(*) OVER () hits, s2.sname, s2.sc, s2.sanc, s2.ds, pp.oname, pp.ostate, pp.orows, ROUND(pp.dollars) dollars, pp.d0
FROM s2 JOIN pp ON pp.k = s2.k ORDER BY pp.dollars DESC NULLS LAST LIMIT 40;

-- [29] reimb: mega-venue bankruptcy judges vs other bk judges, practitioner-paid share
WITH ct AS (
  SELECT PERSON_ID::VARCHAR pid,
         MAX(IFF(COURT_ID IN ('deb','nysb','txsb','njb'), 1, 0)) mega,
         MAX(IFF(RIGHT(COURT_ID,1)='b', 1, 0)) is_bk, LISTAGG(DISTINCT IFF(RIGHT(COURT_ID,1)='b', COURT_ID, NULL), ',') bk_courts
  FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_COURTLISTENER_POSITIONS WHERE COURT_ID IS NOT NULL AND COURT_ID <> '' GROUP BY 1
),
r AS (
  SELECT d.PERSON_ID::VARCHAR pid, d.YEAR_COL::INT yr, r.SOURCE,
    IFF(r.SOURCE ILIKE '%turnaround%' OR r.SOURCE ILIKE '%American Bankruptcy Inst%' OR r.SOURCE ILIKE 'ABI%' OR r.SOURCE ILIKE '%insolvency%'
        OR r.SOURCE ILIKE '%INSOL%' OR r.SOURCE ILIKE '%restructuring%' OR r.SOURCE ILIKE '%American College of Bankruptcy%'
        OR (r.SOURCE ILIKE '%bankrupt%' AND r.SOURCE NOT ILIKE '%conference of bankruptcy judges%'), 1, 0) prac,
    IFF(r.SOURCE ILIKE '%turnaround%', 1, 0) tma
  FROM LIBRARY_MARTS.JUSTICE.JUSTICE__FED_COURTLISTENER_DISCLOSURE_REIMBURSEMENTS r
  JOIN LIBRARY_MARTS.JUSTICE.JUSTICE__FED_COURTLISTENER_FINANCIAL_DISCLOSURES d
    ON TRY_TO_NUMBER(d.ID::VARCHAR) = TRY_TO_NUMBER(r.FINANCIAL_DISCLOSURE_ID::VARCHAR)
  WHERE d.PERSON_ID IS NOT NULL AND TRY_TO_NUMBER(d.YEAR_COL::VARCHAR) BETWEEN 2011 AND 2019
)
SELECT IFF(ct.mega=1, 'mega-venue bk judge: ' || COALESCE(j.NAME_LAST,'?') || ' (' || ct.bk_courts || ')', 'ALL OTHER BK JUDGES') who,
       COUNT(DISTINCT r.pid) judges, COUNT(DISTINCT r.pid||r.yr) judge_yrs_with_trips, COUNT(*) trips, SUM(prac) prac_trips, SUM(tma) tma_trips,
       ROUND(100*SUM(prac)/COUNT(*),1) prac_pct, ROUND(COUNT(*)/COUNT(DISTINCT r.pid||r.yr),2) trips_per_yr
FROM r JOIN ct ON ct.pid = r.pid AND ct.is_bk = 1
LEFT JOIN LIBRARY_MARTS.JUSTICE.JUSTICE__FED_COURTLISTENER_JUDGES j ON j.ID::VARCHAR = r.pid
GROUP BY 1 ORDER BY trips DESC LIMIT 30;

-- [30] msha: underground coal controllers, all recordables vs days-away share 2018-24
WITH a AS (
  SELECT m.CURRENT_CONTROLLER_ID cid, a.DEGREE_INJURY_CD cd, a.NATURE_INJURY nat
  FROM LIBRARY_MARTS.LABOR.LABOR__FED_MSHA_ACCIDENTS a JOIN LIBRARY_MARTS.LABOR.LABOR__FED_MSHA_MINES m ON m.MINE_ID = a.MINE_ID
  WHERE a.CAL_YR BETWEEN 2018 AND 2024 AND m.COAL_METAL_IND = 'C' AND m.CURRENT_MINE_TYPE ILIKE 'Underground%'
),
e AS (
  SELECT CURRENT_CONTROLLER_ID cid, ANY_VALUE(CURRENT_CONTROLLER_NAME) controller, SUM(NO_EMPLOYEES) emp
  FROM LIBRARY_MARTS.LABOR.LABOR__FED_MSHA_MINES WHERE COAL_METAL_IND = 'C' AND CURRENT_MINE_TYPE ILIKE 'Underground%' GROUP BY 1
),
g AS (
  SELECT cid, COUNT_IF(cd IN ('03','04')) away, COUNT_IF(cd = '05') restricted_only, COUNT_IF(cd = '06') no_lost_time,
         COUNT_IF(cd IN ('03','04','05','06')) recordable,
         COUNT_IF(cd IN ('03','04','05','06') AND (nat ILIKE '%SPRAIN%' OR nat ILIKE '%STRAIN%')) sprain_all
  FROM a GROUP BY 1
)
SELECT LEFT(e.controller,32) controller, e.emp, g.recordable, ROUND(100*g.recordable/(e.emp*7),2) recordable_per100_yr,
       ROUND(100*g.away/(e.emp*7),2) away_per100, ROUND(100*g.restricted_only/(e.emp*7),2) restr_only_per100, ROUND(100*g.no_lost_time/(e.emp*7),2) no_lost_per100,
       ROUND(100*g.away/NULLIF(g.recordable,0),1) away_share_pct, ROUND(100*g.sprain_all/(e.emp*7),2) sprain_any_per100
FROM e JOIN g ON g.cid = e.cid WHERE e.emp >= 500 ORDER BY recordable_per100_yr DESC;

-- NOTE: [12] failed to compile (R2 has no RECIPIENT_COUNTRY_CODE) and [14] failed to compile (missing comma between CTEs).
-- Both count toward the 30-statement total. [13] and [15] are the fixed reruns.
-- Total statements sent: 30 of a 35 budget.
