-- deep-1 coverage pass, 2026-09-24. Read-only. Session: STATEMENT_TIMEOUT_IN_SECONDS=300, QUERY_TAG='coverage-b-2026-09-24'.

-- Q1: row counts, all five tables
SELECT 'PENALTY_GAP' t, COUNT(*) n FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__EPA_PENALTY_GAP
UNION ALL SELECT 'AIR_FORMAL', COUNT(*) FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_FORMAL_ACTIONS
UNION ALL SELECT 'AIR_VIOL', COUNT(*) FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_VIOLATION_HISTORY
UNION ALL SELECT 'NPDES_FORMAL', COUNT(*) FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_NPDES_NPDES_FORMAL_ENFORCEMENT_ACTIONS
UNION ALL SELECT 'RCRA_VIOL', COUNT(*) FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_RCRA_VIOLATIONS;

-- Q2: sample PENALTY_GAP
SELECT * FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__EPA_PENALTY_GAP LIMIT 5;

-- Q3: sample AIR_FORMAL
SELECT * FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_FORMAL_ACTIONS LIMIT 5;

-- Q4: sample AIR_VIOL
SELECT * FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_VIOLATION_HISTORY LIMIT 5;

-- Q5: sample NPDES_FORMAL
SELECT * FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_NPDES_NPDES_FORMAL_ENFORCEMENT_ACTIONS LIMIT 5;

-- Q6: sample RCRA_VIOL
SELECT * FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_RCRA_VIOLATIONS LIMIT 5;

-- Q7: PENALTY_GAP profile: what the flags mean and what is blank
SELECT COUNT(*) n,
  COUNT_IF(QUARTERS_WITH_NONCOMPLIANCE::NUMBER >= 8) q8,
  COUNT_IF(QUARTERS_WITH_NONCOMPLIANCE::NUMBER = 12) q12,
  COUNT_IF(QUARTERS_WITH_NONCOMPLIANCE::NUMBER = 0) q0,
  COUNT_IF(LOWER(CHRONIC_NO_PENALTY::STRING) = 'true') chronic,
  COUNT_IF(LOWER(CHRONIC_NO_PENALTY::STRING) = 'true' AND QUARTERS_WITH_NONCOMPLIANCE::NUMBER < 8) chronic_lt8,
  MIN(IFF(LOWER(CHRONIC_NO_PENALTY::STRING) = 'true', QUARTERS_WITH_NONCOMPLIANCE::NUMBER, NULL)) chronic_min_q,
  COUNT_IF(LOWER(CHRONIC_NO_PENALTY::STRING) = 'true' AND LAST_PENALTY_AMT > 0) chronic_but_last_pen_pos,
  COUNT_IF(LOWER(CHRONIC_NO_PENALTY::STRING) = 'true' AND TOTAL_PENALTIES > 0) chronic_but_total_pos,
  COUNT_IF(TOTAL_PENALTIES = 0 AND LAST_PENALTY_AMT > 0) total0_last_pos,
  COUNT_IF(LOWER(NEVER_INSPECTED_NONCOMPLIANT::STRING) = 'true') never_insp_flag,
  COUNT_IF(LOWER(NEVER_INSPECTED_NONCOMPLIANT::STRING) = 'true' AND DATE_LAST_INSPECTION IS NOT NULL) never_insp_but_has_date,
  COUNT_IF(TOTAL_INSPECTION_COUNT = 0 AND DATE_LAST_INSPECTION IS NOT NULL) insp0_with_date,
  COUNT_IF(TOTAL_INSPECTION_COUNT = 0 AND DATE_LAST_INSPECTION >= '2021-09-24') insp0_date_last5y,
  COUNT_IF(PCT_MINORITY IS NULL) pct_min_null,
  COUNT_IF(LOWER(IN_MAJORITY_MINORITY_COMMUNITY::STRING) = 'true') mm_true,
  COUNT_IF(IN_MAJORITY_MINORITY_COMMUNITY IS NULL) mm_null,
  COUNT_IF(LOWER(HAS_AIR_PROGRAM::STRING) <> 'true' AND LOWER(HAS_WATER_PROGRAM::STRING) <> 'true' AND LOWER(HAS_HAZWASTE_PROGRAM::STRING) <> 'true') no_program,
  COUNT_IF(LAST_PENALTY_SHARED_FACILITY_N = 3013568) shared_filler,
  COUNT_IF(LAST_PENALTY_SHARED_FACILITY_N = 3013568 AND LAST_PENALTY_AMT > 0) filler_with_pen,
  COUNT(DISTINCT COMPLIANCE_STATUS) n_status,
  LISTAGG(DISTINCT COMPLIANCE_STATUS, ' / ') statuses
FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__EPA_PENALTY_GAP;

-- Q8: PENALTY_GAP program mix of the 8+ quarter group, with the drinking-water flag pulled from ECHO by FRS_ID
WITH e AS (
  SELECT FRS_ID, MAX(LOWER(HAS_DRINKING_WATER_PROGRAM::STRING) = 'true') dw
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ECHO GROUP BY FRS_ID
), g AS (
  SELECT p.*, e.dw,
    CASE WHEN LOWER(HAS_AIR_PROGRAM::STRING) = 'true' THEN 'AIR'
         WHEN LOWER(HAS_HAZWASTE_PROGRAM::STRING) = 'true' THEN 'HAZ'
         WHEN LOWER(HAS_WATER_PROGRAM::STRING) = 'true' THEN 'WATER'
         ELSE 'NONE' END prog
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__EPA_PENALTY_GAP p LEFT JOIN e ON e.FRS_ID = p.FRS_ID
)
SELECT prog, COUNT(*) n, COUNT_IF(e_match) echo_matched, COUNT_IF(dw) drinking_water,
  COUNT_IF(q >= 8) q8,
  COUNT_IF(q >= 8 AND COALESCE(LAST_PENALTY_AMT_ALLOCATED, 0) = 0) q8_never_pen,
  COUNT_IF(q >= 8 AND COALESCE(LAST_PENALTY_AMT_ALLOCATED, 0) = 0 AND COALESCE(TOTAL_INSPECTION_COUNT, 0) = 0) q8_never_pen_no_insp,
  COUNT_IF(q >= 8 AND COALESCE(LAST_PENALTY_AMT_ALLOCATED, 0) = 0 AND DATE_LAST_INSPECTION IS NULL) q8_never_pen_no_insp_ever,
  COUNT_IF(q >= 8 AND PCT_MINORITY IS NULL) q8_pct_null
FROM (SELECT g.*, QUARTERS_WITH_NONCOMPLIANCE::NUMBER q, dw IS NOT NULL e_match FROM g) x
GROUP BY prog ORDER BY n DESC;

-- Q9: PENALTY_GAP: among 8+ quarter violators, share never fined and share never inspected, by neighborhood minority band, within program
WITH g AS (
  SELECT QUARTERS_WITH_NONCOMPLIANCE::NUMBER q, LAST_PENALTY_AMT_ALLOCATED pen, TOTAL_INSPECTION_COUNT insp, DATE_LAST_INSPECTION dli,
    CASE WHEN LOWER(HAS_AIR_PROGRAM::STRING) = 'true' THEN 'AIR'
         WHEN LOWER(HAS_HAZWASTE_PROGRAM::STRING) = 'true' THEN 'HAZ'
         WHEN LOWER(HAS_WATER_PROGRAM::STRING) = 'true' THEN 'WATER'
         ELSE 'NONE' END prog,
    CASE WHEN PCT_MINORITY IS NULL THEN '9 null'
         WHEN PCT_MINORITY < 10 THEN '1 <10' WHEN PCT_MINORITY < 25 THEN '2 10-25'
         WHEN PCT_MINORITY < 50 THEN '3 25-50' WHEN PCT_MINORITY < 75 THEN '4 50-75' ELSE '5 75+' END band
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__EPA_PENALTY_GAP
)
SELECT prog, band, COUNT(*) all_fac, COUNT_IF(q >= 8) q8,
  ROUND(COUNT_IF(q >= 8) / COUNT(*) * 100, 1) pct_q8_of_all,
  ROUND(COUNT_IF(q >= 8 AND COALESCE(pen, 0) = 0) / NULLIF(COUNT_IF(q >= 8), 0) * 100, 1) pct_q8_never_pen,
  ROUND(COUNT_IF(q >= 8 AND dli IS NULL) / NULLIF(COUNT_IF(q >= 8), 0) * 100, 1) pct_q8_never_insp,
  ROUND(COUNT_IF(q >= 8 AND COALESCE(pen, 0) = 0 AND COALESCE(insp, 0) = 0) / NULLIF(COUNT_IF(q >= 8), 0) * 100, 1) pct_q8_nopen_noinsp_window
FROM g WHERE prog <> 'NONE' GROUP BY prog, band ORDER BY prog, band;

-- Q10: PENALTY_GAP top 20: all 12 of 12 quarters out, never fined, no formal action, ranked by how many times inspected
SELECT FRS_ID, FACILITY_NAME, CITY, STATE, COMPLIANCE_STATUS, QUARTERS_WITH_NONCOMPLIANCE q, TOTAL_INSPECTION_COUNT insp, DATE_LAST_INSPECTION,
  FORMAL_ACTION_COUNT fa, LAST_PENALTY_AMT, LAST_PENALTY_AMT_ALLOCATED, PCT_MINORITY, IN_MAJORITY_MINORITY_COMMUNITY mm,
  HAS_AIR_PROGRAM air, HAS_WATER_PROGRAM wat, HAS_HAZWASTE_PROGRAM haz, TRI_ON_SITE_RELEASES tri
FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__EPA_PENALTY_GAP
WHERE QUARTERS_WITH_NONCOMPLIANCE::NUMBER = 12 AND COALESCE(LAST_PENALTY_AMT_ALLOCATED, 0) = 0 AND COALESCE(FORMAL_ACTION_COUNT, 0) = 0
  AND (LOWER(HAS_AIR_PROGRAM::STRING) = 'true' OR LOWER(HAS_WATER_PROGRAM::STRING) = 'true' OR LOWER(HAS_HAZWASTE_PROGRAM::STRING) = 'true')
ORDER BY TOTAL_INSPECTION_COUNT DESC NULLS LAST, PCT_MINORITY DESC NULLS LAST
LIMIT 25;

-- Q11: PENALTY_GAP: no-inspection-on-record gap, 8+ quarter WATER and HAZ violators, 50%+ minority vs under 25% minority, state by state (peers inside each state); PR row shown
WITH g AS (
  SELECT STATE, DATE_LAST_INSPECTION dli, PCT_MINORITY pm
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__EPA_PENALTY_GAP
  WHERE QUARTERS_WITH_NONCOMPLIANCE::NUMBER >= 8 AND LOWER(HAS_AIR_PROGRAM::STRING) <> 'true'
    AND (LOWER(HAS_WATER_PROGRAM::STRING) = 'true' OR LOWER(HAS_HAZWASTE_PROGRAM::STRING) = 'true')
    AND PCT_MINORITY IS NOT NULL
), s AS (
  SELECT STATE, COUNT_IF(pm >= 50) n_hi, COUNT_IF(pm >= 50 AND dli IS NULL) ni_hi,
         COUNT_IF(pm < 25) n_lo, COUNT_IF(pm < 25 AND dli IS NULL) ni_lo
  FROM g GROUP BY STATE
)
SELECT STATE, n_hi, ROUND(ni_hi / NULLIF(n_hi, 0) * 100, 1) pct_noinsp_hi, n_lo, ROUND(ni_lo / NULLIF(n_lo, 0) * 100, 1) pct_noinsp_lo,
  SUM(n_hi) OVER () tot_hi, SUM(ni_hi) OVER () tot_ni_hi, SUM(n_lo) OVER () tot_lo, SUM(ni_lo) OVER () tot_ni_lo
FROM s WHERE (n_hi >= 25 AND n_lo >= 25) OR STATE = 'PR'
ORDER BY n_hi DESC;

-- Q12: AIR_FORMAL profile: how one case's penalty spreads over facilities
WITH c AS (
  SELECT ENF_IDENTIFIER, COUNT(*) n, COUNT(DISTINCT PGM_SYS_ID) nf, COUNT(DISTINCT PENALTY_AMOUNT) np,
         MAX(PENALTY_AMOUNT) mx, SUM(PENALTY_AMOUNT) s
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_FORMAL_ACTIONS GROUP BY 1
), b AS (
  SELECT COUNT(*) rows_all, COUNT_IF(ENF_IDENTIFIER IS NULL) enf_null, COUNT_IF(PENALTY_AMOUNT IS NULL) pen_null,
    COUNT_IF(PENALTY_AMOUNT = 0) pen_zero, COUNT_IF(PENALTY_AMOUNT < 0) pen_neg, COUNT(DISTINCT ACTIVITY_ID) acts,
    COUNT_IF(STATE_EPA_FLAG = 'S') st, COUNT_IF(STATE_EPA_FLAG = 'L') lo, COUNT_IF(STATE_EPA_FLAG = 'E') epa,
    COUNT_IF(SETTLEMENT_ENTERED_DATE BETWEEN '2015-01-01' AND '2025-12-31') rows_1525,
    LISTAGG(DISTINCT ACTIVITY_TYPE_CODE, ',') types
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_FORMAL_ACTIONS
)
SELECT b.*, (SELECT COUNT(*) FROM c) cases, (SELECT COUNT_IF(nf > 1) FROM c) multi_fac_cases,
  (SELECT COUNT_IF(nf > 1 AND np = 1 AND mx > 0) FROM c) repeat_pen_cases,
  (SELECT SUM(IFF(nf > 1 AND np = 1 AND mx > 0, n, 0)) FROM c) rows_in_repeat,
  (SELECT SUM(s) FROM c) raw_sum, (SELECT SUM(IFF(np = 1, mx, s)) FROM c) dedup_sum, (SELECT MAX(n) FROM c) max_rows_per_case
FROM b;

-- Q13: AIR_FORMAL top 12 cases by penalty, repeats counted once, with a facility name
WITH f AS (
  SELECT PGM_SYS_ID, ANY_VALUE(FACILITY_NAME) nm, ANY_VALUE(STATE) st, ANY_VALUE(AIR_POLLUTANT_CLASS_DESC) cls
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_FACILITIES GROUP BY 1
), c AS (
  SELECT ENF_IDENTIFIER, COUNT(*) n, COUNT(DISTINCT a.PGM_SYS_ID) nf, COUNT(DISTINCT PENALTY_AMOUNT) np, MAX(PENALTY_AMOUNT) mx,
    SUM(PENALTY_AMOUNT) s, MIN(SETTLEMENT_ENTERED_DATE) d, ANY_VALUE(ENF_TYPE_DESC) typ, ANY_VALUE(STATE_EPA_FLAG) ag,
    ANY_VALUE(f.nm) nm, ANY_VALUE(f.st) st
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_FORMAL_ACTIONS a LEFT JOIN f ON f.PGM_SYS_ID = a.PGM_SYS_ID
  GROUP BY 1
)
SELECT ENF_IDENTIFIER, n, nf, np, mx, s raw_sum, IFF(np = 1, mx, s) dedup, d, typ, ag, nm, st
FROM c ORDER BY dedup DESC LIMIT 12;

-- Q14: AIR_FORMAL by state, 2015-2025, one row per case-state (penalty counted once), all sources vs major sources
WITH f AS (
  SELECT PGM_SYS_ID, MAX(AIR_POLLUTANT_CLASS_DESC ILIKE 'major%') maj
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_FACILITIES GROUP BY 1
), c AS (
  SELECT LEFT(a.PGM_SYS_ID, 2) st, ENF_IDENTIFIER, MAX(PENALTY_AMOUNT) pen, BOOLOR_AGG(COALESCE(f.maj, FALSE)) maj,
    MAX(STATE_EPA_FLAG) ag
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_FORMAL_ACTIONS a LEFT JOIN f ON f.PGM_SYS_ID = a.PGM_SYS_ID
  WHERE SETTLEMENT_ENTERED_DATE BETWEEN '2015-01-01' AND '2025-12-31'
  GROUP BY 1, 2
)
SELECT st, COUNT(*) cases, ROUND(COUNT_IF(pen > 0) / COUNT(*) * 100, 1) pct_pen, MEDIAN(IFF(pen > 0, pen, NULL)) med_pen,
  ROUND(SUM(pen)) sum_pen, ROUND(COUNT_IF(ag = 'E') / COUNT(*) * 100, 1) pct_epa,
  COUNT_IF(maj) maj_cases, ROUND(COUNT_IF(maj AND pen > 0) / NULLIF(COUNT_IF(maj), 0) * 100, 1) maj_pct_pen,
  MEDIAN(IFF(maj AND pen > 0, pen, NULL)) maj_med_pen
FROM c GROUP BY st HAVING COUNT(*) >= 100 ORDER BY cases DESC;

-- Q15: AIR_FORMAL repeat facilities 2015-2025: most formal cases, total penalty (each case's amount once per facility), with size class
WITH f AS (
  SELECT PGM_SYS_ID, ANY_VALUE(FACILITY_NAME) nm, ANY_VALUE(CITY) city, ANY_VALUE(STATE) st, ANY_VALUE(AIR_POLLUTANT_CLASS_DESC) cls,
    ANY_VALUE(CURRENT_HPV) hpv, ANY_VALUE(AIR_OPERATING_STATUS_DESC) ops
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_FACILITIES GROUP BY 1
), c AS (
  SELECT PGM_SYS_ID, ENF_IDENTIFIER, MAX(PENALTY_AMOUNT) pen
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_FORMAL_ACTIONS
  WHERE SETTLEMENT_ENTERED_DATE BETWEEN '2015-01-01' AND '2025-12-31' GROUP BY 1, 2
)
SELECT c.PGM_SYS_ID, f.nm, f.city, f.st, f.cls, f.hpv, f.ops, COUNT(*) cases, COUNT_IF(pen > 0) pen_cases, SUM(pen) tot_pen,
  ROUND(SUM(pen) / COUNT(*)) pen_per_case, MEDIAN(pen) med_pen
FROM c LEFT JOIN f ON f.PGM_SYS_ID = c.PGM_SYS_ID
GROUP BY 1, 2, 3, 4, 5, 6, 7 ORDER BY cases DESC LIMIT 25;

-- Q16: AIR_FORMAL peers: petroleum refineries only (NAICS 324110), state or local agency cases 2015-2025, penalty per case by state
WITH f AS (
  SELECT PGM_SYS_ID, ANY_VALUE(STATE) st
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_FACILITIES
  WHERE NAICS_CODES LIKE '%324110%' GROUP BY 1
), c AS (
  SELECT f.st, a.PGM_SYS_ID, ENF_IDENTIFIER, MAX(PENALTY_AMOUNT) pen
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_FORMAL_ACTIONS a JOIN f ON f.PGM_SYS_ID = a.PGM_SYS_ID
  WHERE SETTLEMENT_ENTERED_DATE BETWEEN '2015-01-01' AND '2025-12-31' AND STATE_EPA_FLAG IN ('S', 'L')
  GROUP BY 1, 2, 3
)
SELECT st, COUNT(DISTINCT PGM_SYS_ID) refineries, COUNT(*) cases, ROUND(COUNT(*) / COUNT(DISTINCT PGM_SYS_ID), 1) cases_per_ref,
  ROUND(COUNT_IF(pen > 0) / COUNT(*) * 100, 1) pct_pen, MEDIAN(IFF(pen > 0, pen, NULL)) med_pen, ROUND(SUM(pen)) sum_pen,
  ROUND(SUM(pen) / COUNT(DISTINCT PGM_SYS_ID)) pen_per_refinery
FROM c GROUP BY st HAVING COUNT(DISTINCT PGM_SYS_ID) >= 3 ORDER BY cases DESC;

-- Q17: AIR_VIOL profile by violation class (FRV vs HPV): date fill, junk dates, repeat IDs
SELECT ENF_RESPONSE_POLICY_CODE, COUNT(*) n, COUNT(DISTINCT COMP_DETERMINATION_UID) uids, COUNT(DISTINCT ACTIVITY_ID) acts,
  COUNT(DISTINCT PGM_SYS_ID) facs, COUNT(HPV_DAYZERO_DATE) dz, COUNT(HPV_RESOLVED_DATE) resolved, COUNT(EARLIEST_FRV_DETERM_DATE) frv_d,
  COUNT_IF(EARLIEST_FRV_DETERM_DATE < '1990-01-01') frv_pre1990, COUNT_IF(HPV_DAYZERO_DATE < '1990-01-01') dz_pre1990,
  MIN(HPV_DAYZERO_DATE) dz_min, MAX(HPV_DAYZERO_DATE) dz_max, MIN(IFF(EARLIEST_FRV_DETERM_DATE >= '1990-01-01', EARLIEST_FRV_DETERM_DATE, NULL)) frv_min_real,
  COUNT_IF(HPV_RESOLVED_DATE < HPV_DAYZERO_DATE) resolved_before_dz
FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_VIOLATION_HISTORY GROUP BY 1 ORDER BY n DESC;

-- Q18: AIR_VIOL: what repeats inside the most-repeated determination IDs
SELECT COMP_DETERMINATION_UID, COUNT(*) n, COUNT(DISTINCT PGM_SYS_ID) facs, COUNT(DISTINCT ACTIVITY_ID) acts,
  COUNT(DISTINCT POLLUTANT_CODES) pol, COUNT(DISTINCT PROGRAM_CODES) prog, COUNT(DISTINCT EARLIEST_FRV_DETERM_DATE) dates,
  MIN(EARLIEST_FRV_DETERM_DATE) d_min, MAX(EARLIEST_FRV_DETERM_DATE) d_max, ANY_VALUE(ENF_RESPONSE_POLICY_CODE) cls, ANY_VALUE(PGM_SYS_ID) one_fac,
  SUM(COUNT(*)) OVER () rows_top
FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_VIOLATION_HISTORY
GROUP BY 1 HAVING COUNT(*) > 50 ORDER BY n DESC LIMIT 8;

-- Q19: AIR_VIOL: HPVs that started 2012-2021 (so 4+ years to act); resolved share, time to resolve, and any formal action or penalty at the same facility after day zero, by state
WITH h AS (
  SELECT PGM_SYS_ID, COMP_DETERMINATION_UID uid, ANY_VALUE(STATE_CODE) st, MIN(HPV_DAYZERO_DATE) dz, MAX(HPV_RESOLVED_DATE) res
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_VIOLATION_HISTORY
  WHERE ENF_RESPONSE_POLICY_CODE = 'HPV' AND HPV_DAYZERO_DATE BETWEEN '2012-01-01' AND '2021-12-31'
  GROUP BY 1, 2
), a AS (
  SELECT PGM_SYS_ID, ENF_IDENTIFIER, MIN(SETTLEMENT_ENTERED_DATE) d, MAX(PENALTY_AMOUNT) pen
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_FORMAL_ACTIONS GROUP BY 1, 2
), j AS (
  SELECT h.st, h.uid, h.dz, h.res,
    COUNT(IFF(a.d >= h.dz AND a.d <= DATEADD(day, 730, h.dz), 1, NULL)) fa_2y,
    COUNT(IFF(a.d >= h.dz, 1, NULL)) fa_after,
    SUM(IFF(a.d >= h.dz, a.pen, 0)) pen_after
  FROM h LEFT JOIN a ON a.PGM_SYS_ID = h.PGM_SYS_ID
  GROUP BY 1, 2, 3, 4
)
SELECT st, COUNT(*) hpvs, ROUND(COUNT_IF(res IS NULL) / COUNT(*) * 100, 1) pct_unresolved,
  MEDIAN(DATEDIFF(day, dz, res)) med_days_to_resolve,
  ROUND(COUNT_IF(fa_2y > 0) / COUNT(*) * 100, 1) pct_formal_2y, ROUND(COUNT_IF(fa_after = 0) / COUNT(*) * 100, 1) pct_no_formal_ever,
  ROUND(COUNT_IF(COALESCE(pen_after, 0) = 0) / COUNT(*) * 100, 1) pct_no_pen_after,
  SUM(COUNT(*)) OVER () all_hpvs, SUM(COUNT_IF(fa_after = 0)) OVER () all_no_formal, SUM(COUNT_IF(res IS NULL)) OVER () all_unres
FROM j GROUP BY st HAVING COUNT(*) >= 40 ORDER BY hpvs DESC;

-- Q20: AIR_VIOL: oldest HPVs (day zero 2012-2021) still unresolved with no formal action since day zero, named, with facility-file HPV status and operating status
WITH h AS (
  SELECT PGM_SYS_ID, COMP_DETERMINATION_UID uid, ANY_VALUE(STATE_CODE) st, MIN(HPV_DAYZERO_DATE) dz, MAX(HPV_RESOLVED_DATE) res,
    ANY_VALUE(AGENCY_TYPE_DESC) ag, ANY_VALUE(POLLUTANT_DESCS) pol
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_VIOLATION_HISTORY
  WHERE ENF_RESPONSE_POLICY_CODE = 'HPV' AND HPV_DAYZERO_DATE BETWEEN '2012-01-01' AND '2021-12-31'
  GROUP BY 1, 2
), a AS (
  SELECT PGM_SYS_ID, MAX(SETTLEMENT_ENTERED_DATE) last_fa, COUNT(DISTINCT ENF_IDENTIFIER) n_fa
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_FORMAL_ACTIONS GROUP BY 1
), f AS (
  SELECT PGM_SYS_ID, ANY_VALUE(FACILITY_NAME) nm, ANY_VALUE(CITY) city, ANY_VALUE(CURRENT_HPV) hpv, ANY_VALUE(AIR_OPERATING_STATUS_DESC) ops,
    ANY_VALUE(AIR_POLLUTANT_CLASS_DESC) cls
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_FACILITIES GROUP BY 1
)
SELECT h.PGM_SYS_ID, f.nm, f.city, h.st, f.cls, f.ops, f.hpv facility_file_hpv, h.ag, h.dz, a.last_fa, a.n_fa, LEFT(h.pol, 50) pol,
  COUNT(*) OVER () n_open_no_action
FROM h LEFT JOIN a ON a.PGM_SYS_ID = h.PGM_SYS_ID LEFT JOIN f ON f.PGM_SYS_ID = h.PGM_SYS_ID
WHERE h.res IS NULL AND (a.last_fa IS NULL OR a.last_fa < h.dz)
ORDER BY h.dz LIMIT 25;

-- Q21: NPDES profile: case repeats across permits, federal vs state fill, agency values, the BP Gulf permit
WITH c AS (
  SELECT ENF_IDENTIFIER, COUNT(*) n, COUNT(DISTINCT NPDES_ID) np, COUNT(DISTINCT FED_PENALTY_ASSESSED_AMT) nf, MAX(FED_PENALTY_ASSESSED_AMT) mf,
    SUM(FED_PENALTY_ASSESSED_AMT) sf, COUNT(DISTINCT STATE_LOCAL_PENALTY_AMT) ns, MAX(STATE_LOCAL_PENALTY_AMT) ms, SUM(STATE_LOCAL_PENALTY_AMT) ss,
    BOOLOR_AGG(NPDES_ID = 'GMG290110') bp
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_NPDES_NPDES_FORMAL_ENFORCEMENT_ACTIONS GROUP BY 1
), b AS (
  SELECT COUNT(*) rows_all, COUNT(DISTINCT ACTIVITY_ID) acts, COUNT(DISTINCT NPDES_ID) permits, COUNT_IF(ENF_IDENTIFIER IS NULL) enf_null,
    COUNT(FED_PENALTY_ASSESSED_AMT) fed_filled, COUNT_IF(FED_PENALTY_ASSESSED_AMT > 0) fed_pos, COUNT(STATE_LOCAL_PENALTY_AMT) st_filled,
    COUNT_IF(STATE_LOCAL_PENALTY_AMT > 0) st_pos, COUNT_IF(FED_PENALTY_ASSESSED_AMT > 0 AND FED_PENALTY_ASSESSED_AMT = STATE_LOCAL_PENALTY_AMT) fed_eq_state,
    LISTAGG(DISTINCT AGENCY, ',') agencies, COUNT_IF(AGENCY = 'EPA') epa_rows,
    COUNT_IF(SETTLEMENT_ENTERED_DATE BETWEEN '2015-01-01' AND '2026-12-31') rows_1526, COUNT_IF(NPDES_ID = 'GMG290110') bp_rows
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_NPDES_NPDES_FORMAL_ENFORCEMENT_ACTIONS
)
SELECT b.*, (SELECT COUNT(*) FROM c) cases, (SELECT COUNT_IF(np > 1) FROM c) multi_permit_cases,
  (SELECT COUNT_IF(np > 1 AND nf = 1 AND mf > 0) FROM c) fed_repeat_cases, (SELECT COUNT_IF(np > 1 AND ns = 1 AND ms > 0) FROM c) st_repeat_cases,
  (SELECT SUM(sf) FROM c) fed_raw, (SELECT SUM(IFF(nf = 1, mf, sf)) FROM c) fed_dedup,
  (SELECT SUM(ss) FROM c) st_raw, (SELECT SUM(IFF(ns = 1, ms, ss)) FROM c) st_dedup,
  (SELECT LISTAGG(ENF_IDENTIFIER || ':' || n || 'rows/' || np || 'permits/' || mf, ' ; ') FROM c WHERE bp) bp_case
FROM b;

-- Q22: NPDES top 12 cases by federal+state penalty, each case counted once, with one facility name
WITH f AS (
  SELECT NPDES_ID, ANY_VALUE(FACILITY_NAME) nm, ANY_VALUE(CITY) city FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_NPDES_ICIS_FACILITIES GROUP BY 1
), c AS (
  SELECT ENF_IDENTIFIER, COUNT(*) n, COUNT(DISTINCT a.NPDES_ID) np, MAX(FED_PENALTY_ASSESSED_AMT) fed, MAX(STATE_LOCAL_PENALTY_AMT) st,
    SUM(FED_PENALTY_ASSESSED_AMT) fed_raw, MIN(SETTLEMENT_ENTERED_DATE) d, ANY_VALUE(AGENCY) ag, ANY_VALUE(ENF_TYPE_DESC) typ,
    MIN(a.NPDES_ID) one_permit, ANY_VALUE(f.nm) nm
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_NPDES_NPDES_FORMAL_ENFORCEMENT_ACTIONS a LEFT JOIN f ON f.NPDES_ID = a.NPDES_ID
  GROUP BY 1
)
SELECT ENF_IDENTIFIER, n, np, fed, st, fed_raw, COALESCE(fed, 0) + COALESCE(st, 0) tot, d, ag, typ, one_permit, nm
FROM c ORDER BY tot DESC LIMIT 12;

-- Q23: NPDES by state 2015-2026, BP Gulf case removed, one row per case-state (penalty counted once)
WITH bp AS (
  SELECT DISTINCT ENF_IDENTIFIER FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_NPDES_NPDES_FORMAL_ENFORCEMENT_ACTIONS WHERE NPDES_ID = 'GMG290110'
), c AS (
  SELECT LEFT(NPDES_ID, 2) st, ENF_IDENTIFIER, MAX(FED_PENALTY_ASSESSED_AMT) fed, MAX(STATE_LOCAL_PENALTY_AMT) stp, MAX(AGENCY) ag,
    COUNT(DISTINCT NPDES_ID) np
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_NPDES_NPDES_FORMAL_ENFORCEMENT_ACTIONS
  WHERE SETTLEMENT_ENTERED_DATE BETWEEN '2015-01-01' AND '2026-12-31' AND ENF_IDENTIFIER NOT IN (SELECT ENF_IDENTIFIER FROM bp)
  GROUP BY 1, 2
)
SELECT st, COUNT(*) cases, ROUND(COUNT_IF(ag = 'EPA') / COUNT(*) * 100, 1) pct_epa,
  ROUND(COUNT_IF(COALESCE(fed, 0) + COALESCE(stp, 0) > 0) / COUNT(*) * 100, 1) pct_pen,
  MEDIAN(IFF(COALESCE(fed, 0) + COALESCE(stp, 0) > 0, COALESCE(fed, 0) + COALESCE(stp, 0), NULL)) med_pen,
  ROUND(SUM(COALESCE(fed, 0))) fed_sum, ROUND(SUM(COALESCE(stp, 0))) st_sum,
  SUM(COUNT(*)) OVER () all_cases, SUM(COUNT_IF(COALESCE(fed, 0) + COALESCE(stp, 0) > 0)) OVER () all_pen
FROM c GROUP BY st HAVING COUNT(*) >= 300 ORDER BY cases DESC;

-- Q24: NPDES repeat permits 2015-2026: most formal cases, total penalty (each case's amount once), with facility name
WITH f AS (
  SELECT NPDES_ID, ANY_VALUE(FACILITY_NAME) nm, ANY_VALUE(CITY) city FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_NPDES_ICIS_FACILITIES GROUP BY 1
), c AS (
  SELECT NPDES_ID, ENF_IDENTIFIER, MAX(COALESCE(FED_PENALTY_ASSESSED_AMT, 0) + COALESCE(STATE_LOCAL_PENALTY_AMT, 0)) pen, MAX(AGENCY) ag,
    MIN(SETTLEMENT_ENTERED_DATE) d
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_NPDES_NPDES_FORMAL_ENFORCEMENT_ACTIONS
  WHERE SETTLEMENT_ENTERED_DATE BETWEEN '2015-01-01' AND '2026-12-31' GROUP BY 1, 2
)
SELECT c.NPDES_ID, f.nm, f.city, COUNT(*) cases, COUNT_IF(pen > 0) pen_cases, SUM(pen) tot_pen, MEDIAN(pen) med_pen,
  MIN(d) first_d, MAX(d) last_d, COUNT_IF(ag = 'EPA') epa_cases
FROM c LEFT JOIN f ON f.NPDES_ID = c.NPDES_ID
GROUP BY 1, 2, 3 ORDER BY cases DESC LIMIT 20;

-- Q25: RCRA profile by decade the violation was found: open (no fix date) share, schedule fill, junk dates, exact repeats; VIOSNC flag values alongside
SELECT CASE WHEN DATE_VIOLATION_DETERMINED IS NULL THEN 'null' WHEN YEAR(DATE_VIOLATION_DETERMINED) < 1980 THEN 'pre1980'
            ELSE TO_VARCHAR(FLOOR(YEAR(DATE_VIOLATION_DETERMINED) / 5) * 5) END bucket,
  COUNT(*) n, COUNT_IF(ACTUAL_RTC_DATE IS NULL) rtc_null, ROUND(COUNT_IF(ACTUAL_RTC_DATE IS NULL) / COUNT(*) * 100, 1) pct_open,
  COUNT(SCHEDULED_COMPLIANCE_DATE) sched_filled, COUNT_IF(ACTUAL_RTC_DATE < DATE_VIOLATION_DETERMINED) rtc_before_found,
  COUNT_IF(YEAR(ACTUAL_RTC_DATE) < 1980) rtc_junk, COUNT_IF(VIOL_DETERMINED_BY_AGENCY = 'E') by_epa,
  COUNT(*) - COUNT(DISTINCT HASH(ID_NUMBER, VIOLATION_TYPE, DATE_VIOLATION_DETERMINED, ACTUAL_RTC_DATE, SCHEDULED_COMPLIANCE_DATE)) exact_repeats,
  COUNT(DISTINCT ID_NUMBER) handlers,
  (SELECT LISTAGG(DISTINCT VIO_FLAG || '/' || SNC_FLAG, ',') FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_RCRA_VIOSNC_HISTORY) viosnc_values,
  (SELECT MIN(YRMONTH) || '..' || MAX(YRMONTH) || ' ids=' || COUNT(DISTINCT ID_NUMBER) FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_RCRA_VIOSNC_HISTORY) viosnc_span
FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_RCRA_VIOLATIONS GROUP BY 1 ORDER BY 1;

-- Q26: RCRA: handlers with open violations (no fix date) found 1980-2020, named, with EPA's own monthly violation flag as a second check
WITH o AS (
  SELECT ID_NUMBER, COUNT(*) open_n, MIN(DATE_VIOLATION_DETERMINED) oldest, MAX(DATE_VIOLATION_DETERMINED) newest_open,
    COUNT(DISTINCT VIOLATION_TYPE) types, MODE(VIOLATION_TYPE) top_type, MAX(VIOL_DETERMINED_BY_AGENCY) ag, ANY_VALUE(ACTIVITY_LOCATION) st
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_RCRA_VIOLATIONS
  WHERE ACTUAL_RTC_DATE IS NULL AND DATE_VIOLATION_DETERMINED BETWEEN '1980-01-01' AND '2020-12-31'
  GROUP BY 1
), v AS (
  SELECT ID_NUMBER, MAX(YRMONTH) last_flag_month, MAX_BY(VIO_FLAG || '/' || SNC_FLAG, YRMONTH) last_flags
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_RCRA_VIOSNC_HISTORY WHERE ID_NUMBER IN (SELECT ID_NUMBER FROM o) GROUP BY 1
), f AS (
  SELECT ID_NUMBER, ANY_VALUE(FACILITY_NAME) nm, ANY_VALUE(CITY_NAME) city, MAX(FED_WASTE_GENERATOR) gen
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_RCRA_FACILITIES WHERE ID_NUMBER IN (SELECT ID_NUMBER FROM o) GROUP BY 1
)
SELECT o.ID_NUMBER, f.nm, f.city, o.st, f.gen, o.open_n, o.oldest, o.newest_open, o.types, o.top_type, o.ag, v.last_flag_month, v.last_flags,
  COUNT(*) OVER () handlers_open, SUM(o.open_n) OVER () viol_open,
  COUNT_IF(v.last_flag_month >= 202601) OVER () flagged_2026, COUNT_IF(v.ID_NUMBER IS NULL) OVER () never_flagged
FROM o LEFT JOIN v ON v.ID_NUMBER = o.ID_NUMBER LEFT JOIN f ON f.ID_NUMBER = o.ID_NUMBER
ORDER BY o.open_n DESC, o.oldest LIMIT 25;

-- Q27: RCRA by state, violations found 2010-2020: open share, schedule fill, fixed after the due date, median days late
SELECT ACTIVITY_LOCATION st, COUNT(*) n, ROUND(COUNT_IF(ACTUAL_RTC_DATE IS NULL) / COUNT(*) * 100, 2) pct_open,
  ROUND(COUNT(SCHEDULED_COMPLIANCE_DATE) / COUNT(*) * 100, 1) pct_sched,
  ROUND(COUNT_IF(ACTUAL_RTC_DATE > SCHEDULED_COMPLIANCE_DATE) / NULLIF(COUNT(SCHEDULED_COMPLIANCE_DATE), 0) * 100, 1) pct_late_of_sched,
  MEDIAN(IFF(ACTUAL_RTC_DATE > SCHEDULED_COMPLIANCE_DATE, DATEDIFF(day, SCHEDULED_COMPLIANCE_DATE, ACTUAL_RTC_DATE), NULL)) med_days_late,
  COUNT_IF(DATEDIFF(day, SCHEDULED_COMPLIANCE_DATE, ACTUAL_RTC_DATE) > 365) late_1y_plus,
  MEDIAN(DATEDIFF(day, DATE_VIOLATION_DETERMINED, ACTUAL_RTC_DATE)) med_days_to_fix,
  SUM(COUNT(*)) OVER () all_n, SUM(COUNT_IF(DATEDIFF(day, SCHEDULED_COMPLIANCE_DATE, ACTUAL_RTC_DATE) > 365)) OVER () all_late_1y
FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_RCRA_VIOLATIONS
WHERE DATE_VIOLATION_DETERMINED BETWEEN '2010-01-01' AND '2020-12-31'
GROUP BY 1 HAVING COUNT(*) >= 3000 ORDER BY n DESC;

-- Q28: AIR_FORMAL refineries 2015-2025, all agencies, split by who acted (state, local, EPA), key states
WITH f AS (
  SELECT PGM_SYS_ID, ANY_VALUE(STATE) st FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_FACILITIES
  WHERE NAICS_CODES LIKE '%324110%' GROUP BY 1
), c AS (
  SELECT f.st, STATE_EPA_FLAG ag, a.PGM_SYS_ID, ENF_IDENTIFIER, MAX(PENALTY_AMOUNT) pen, ANY_VALUE(ENF_TYPE_DESC) typ
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_FORMAL_ACTIONS a JOIN f ON f.PGM_SYS_ID = a.PGM_SYS_ID
  WHERE SETTLEMENT_ENTERED_DATE BETWEEN '2015-01-01' AND '2025-12-31' GROUP BY 1, 2, 3, 4
)
SELECT st, ag, COUNT(DISTINCT PGM_SYS_ID) refineries_hit, COUNT(*) cases, COUNT_IF(pen > 0) pen_cases, ROUND(SUM(pen)) sum_pen,
  LISTAGG(DISTINCT typ, ' | ') types
FROM c WHERE st IN ('LA', 'TX', 'CA', 'IL', 'OK', 'WA') GROUP BY 1, 2 ORDER BY 1, 2;

-- Q29: NPDES: every row on the BP Gulf permit and on the Jonesborough TN sewage plant (is the $3.35B logged twice? is $30M a typo?)
SELECT NPDES_ID, ENF_IDENTIFIER, ACTIVITY_ID, ACTIVITY_TYPE_CODE, ENF_TYPE_DESC, AGENCY, SETTLEMENT_ENTERED_DATE, FED_PENALTY_ASSESSED_AMT, STATE_LOCAL_PENALTY_AMT
FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_NPDES_NPDES_FORMAL_ENFORCEMENT_ACTIONS
WHERE NPDES_ID IN ('GMG290110', 'TN0021547')
ORDER BY NPDES_ID, COALESCE(FED_PENALTY_ASSESSED_AMT, 0) + COALESCE(STATE_LOCAL_PENALTY_AMT, 0) DESC;

-- Q30: AIR refineries (NAICS 324110) by state, 2015-2025: violations found (FRV + HPV) vs formal cases and penalty (all agencies, each case once), penalty per violation
WITH f AS (
  SELECT PGM_SYS_ID, ANY_VALUE(STATE) st FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_FACILITIES
  WHERE NAICS_CODES LIKE '%324110%' GROUP BY 1
), v AS (
  SELECT f.st, COUNT(*) viol, COUNT_IF(ENF_RESPONSE_POLICY_CODE = 'HPV') hpv, COUNT(DISTINCT v.PGM_SYS_ID) ref_viol
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_VIOLATION_HISTORY v JOIN f ON f.PGM_SYS_ID = v.PGM_SYS_ID
  WHERE COALESCE(HPV_DAYZERO_DATE, EARLIEST_FRV_DETERM_DATE) BETWEEN '2015-01-01' AND '2025-12-31' GROUP BY 1
), c AS (
  SELECT f.st, a.PGM_SYS_ID, ENF_IDENTIFIER, MAX(PENALTY_AMOUNT) pen
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_FORMAL_ACTIONS a JOIN f ON f.PGM_SYS_ID = a.PGM_SYS_ID
  WHERE SETTLEMENT_ENTERED_DATE BETWEEN '2015-01-01' AND '2025-12-31' GROUP BY 1, 2, 3
), p AS (
  SELECT st, COUNT(DISTINCT PGM_SYS_ID) ref_fa, COUNT(*) cases, ROUND(SUM(pen)) pen FROM c GROUP BY 1
), r AS (SELECT st, COUNT(*) refineries FROM f GROUP BY 1)
SELECT r.st, r.refineries, v.ref_viol, v.viol, v.hpv, p.cases, p.pen, ROUND(p.pen / NULLIF(v.viol, 0)) pen_per_viol,
  ROUND(p.pen / NULLIF(v.hpv, 0)) pen_per_hpv, ROUND(p.cases / NULLIF(v.viol, 0), 2) cases_per_viol
FROM r LEFT JOIN v ON v.st = r.st LEFT JOIN p ON p.st = r.st
WHERE v.viol >= 20 ORDER BY v.viol DESC;

-- Q31: AIR refineries: how many NAICS 324110 facilities and how many violations 2015-2025 each state reported, for the states under the earlier cut (LA, IL, KY, MS, WY, others)
WITH f AS (
  SELECT PGM_SYS_ID, ANY_VALUE(STATE) st FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_FACILITIES
  WHERE NAICS_CODES LIKE '%324110%' GROUP BY 1
), v AS (
  SELECT f.st, COUNT(*) viol, COUNT_IF(ENF_RESPONSE_POLICY_CODE = 'HPV') hpv
  FROM LIBRARY_MARTS.ENVIRONMENT.ENVIRONMENT__FED_EPA_ICIS_AIR_ICIS_AIR_VIOLATION_HISTORY v JOIN f ON f.PGM_SYS_ID = v.PGM_SYS_ID
  WHERE COALESCE(HPV_DAYZERO_DATE, EARLIEST_FRV_DETERM_DATE) BETWEEN '2015-01-01' AND '2025-12-31' GROUP BY 1
)
SELECT f.st, COUNT(*) refinery_coded_facilities, ANY_VALUE(v.viol) viol, ANY_VALUE(v.hpv) hpv
FROM f LEFT JOIN v ON v.st = f.st
GROUP BY f.st HAVING COUNT(*) >= 8 ORDER BY refinery_coded_facilities DESC;
