-- deep-5: coverage deep pass, 2026-09-24. Query tag coverage-b-2026-09-24.
-- Every connection first ran the two session settings: statement timeout 300s and the query tag.
-- Numbered statements below are the SELECT/WITH budget (cap 35). 29 used.
-- [5] and [9] failed at compile (those two tables have no _SOURCE_RUN_ID column); [11] and [12] are the reruns.
-- Runs from a private runner; results were saved to scratchpad TSVs, not the repo.

-- [1] HH owners: count and shape
SELECT COUNT(*) n, COUNT(DISTINCT ENROLLMENT_ID) enr, COUNT(DISTINCT ASSOCIATE_ID) agencies_assoc, COUNT(CCN) ccn_filled, COUNT(DISTINCT CCN) ccn_d,
 COUNT(DISTINCT ASSOCIATE_ID_OWNER) owners_d, SUM(IFF(TYPE_OWNER='I',1,0)) ind_rows, SUM(IFF(TYPE_OWNER='O',1,0)) org_rows,
 COUNT(DISTINCT AGENCY_STATE) states, COUNT(DISTINCT ROLE_TEXT_OWNER) roles, COUNT(DISTINCT _SOURCE_RUN_ID) runs
FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_HOME_HEALTH_OWNERS;

-- [2] HH owners: sample
SELECT * FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_HOME_HEALTH_OWNERS LIMIT 5;

-- [3] Dialysis: count and shape
SELECT COUNT(*) n, COUNT(DISTINCT CCN) ccn_d, COUNT(DISTINCT YEAR_COL) yrs, MIN(YEAR_COL) y0, MAX(YEAR_COL) y1, COUNT(DISTINCT MEASURE_ID) measures, COUNT(DISTINCT CHAIN) chains, COUNT(DISTINCT STATE) states
FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_MEDICARE_DIALYSIS_FACILITIES;

-- [4] Dialysis: sample
SELECT * FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_MEDICARE_DIALYSIS_FACILITIES LIMIT 5;

-- [5] Inpatient: count and shape
SELECT COUNT(*) n, COUNT(DISTINCT RNDRNG_PRVDR_CCN) ccn_d, COUNT(DISTINCT DRG_CD) drg_d, COUNT(DISTINCT RNDRNG_PRVDR_CCN||'|'||DRG_CD) ccn_drg_d,
 SUM(TRY_TO_NUMBER(TOT_DSCHRGS)) dschrg, MIN(TRY_TO_NUMBER(TOT_DSCHRGS)) min_d, SUM(TRY_TO_NUMBER(TOT_DSCHRGS)*AVG_MDCR_PYMT_AMT) mdcr_paid_total,
 COUNT(DISTINCT _SOURCE_RUN_ID) runs
FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_MEDICARE_INPATIENT_HOSPITALS_BY_PROVIDER_AND_SERVICE;

-- [6] Inpatient: sample
SELECT * FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_MEDICARE_INPATIENT_HOSPITALS_BY_PROVIDER_AND_SERVICE LIMIT 5;

-- [7] NADAC: count and shape
SELECT COUNT(*) n, COUNT(DISTINCT NDC) ndc_d, COUNT(DISTINCT AS_OF_DATE) asof_d, MIN(AS_OF_DATE) asof0, MAX(AS_OF_DATE) asof1,
 COUNT(DISTINCT EFFECTIVE_DATE) eff_d, MIN(EFFECTIVE_DATE) eff0, MAX(EFFECTIVE_DATE) eff1, COUNT(DISTINCT NDC||'|'||EFFECTIVE_DATE) ndc_eff_d,
 COUNT(DISTINCT RATE_CLASSIFICATION) cls_d, COUNT(DISTINCT PRICING_UNIT) unit_d
FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_NADAC;

-- [8] NADAC: sample
SELECT * FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_NADAC LIMIT 5;

-- [9] Fire: count and shape
SELECT COUNT(*) n, COUNT(DISTINCT CMS_CERTIFICATION_NUMBER_CCN) ccn_d, MIN(SURVEY_DATE) s0, MAX(SURVEY_DATE) s1, COUNT(DISTINCT INSPECTION_CYCLE) cyc_d,
 COUNT(DISTINCT PROCESSING_DATE) proc_d, MAX(PROCESSING_DATE) proc, COUNT(DISTINCT STATE) states, COUNT(DISTINCT SCOPE_SEVERITY_CODE) sev_d,
 COUNT(DISTINCT CMS_CERTIFICATION_NUMBER_CCN||SURVEY_DATE||DEFICIENCY_PREFIX||DEFICIENCY_TAG_NUMBER) uniq_cite, COUNT(DISTINCT _SOURCE_RUN_ID) runs
FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_NURSING_HOME_FIRE_DEFICIENCIES;

-- [10] Fire: sample
SELECT * FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_NURSING_HOME_FIRE_DEFICIENCIES LIMIT 5;

-- [11] Inpatient: count and shape (rerun without run id)
SELECT COUNT(*) n, COUNT(DISTINCT RNDRNG_PRVDR_CCN) ccn_d, COUNT(DISTINCT DRG_CD) drg_d, COUNT(DISTINCT RNDRNG_PRVDR_CCN||'|'||DRG_CD) ccn_drg_d,
 SUM(TRY_TO_NUMBER(TOT_DSCHRGS)) dschrg, MIN(TRY_TO_NUMBER(TOT_DSCHRGS)) min_d, SUM(TRY_TO_NUMBER(TOT_DSCHRGS)*AVG_MDCR_PYMT_AMT) mdcr_paid_total,
 SUM(TRY_TO_NUMBER(TOT_DSCHRGS)*TRY_TO_DOUBLE(AVG_SUBMTD_CVRD_CHRG::string)) charged_total, COUNT_IF(TRY_TO_DOUBLE(AVG_SUBMTD_CVRD_CHRG::string) IS NULL) chg_unparsed
FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_MEDICARE_INPATIENT_HOSPITALS_BY_PROVIDER_AND_SERVICE;

-- [12] Fire: count and shape (rerun without run id)
SELECT COUNT(*) n, COUNT(DISTINCT CMS_CERTIFICATION_NUMBER_CCN) ccn_d, MIN(SURVEY_DATE) s0, MAX(SURVEY_DATE) s1, COUNT(DISTINCT INSPECTION_CYCLE) cyc_d,
 COUNT(DISTINCT PROCESSING_DATE) proc_d, MAX(PROCESSING_DATE) proc, COUNT(DISTINCT STATE) states, COUNT(DISTINCT SCOPE_SEVERITY_CODE) sev_d,
 COUNT(DISTINCT CMS_CERTIFICATION_NUMBER_CCN||SURVEY_DATE||DEFICIENCY_PREFIX||DEFICIENCY_TAG_NUMBER) uniq_cite,
 COUNT_IF(SCOPE_SEVERITY_CODE >= 'G') sev_g_plus, COUNT_IF(YEAR(SURVEY_DATE) >= 2023) since_2023
FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_NURSING_HOME_FIRE_DEFICIENCIES;

-- [13] HH owners: top 25 owners per type by distinct agencies, 5%+ ownership roles only
WITH o AS (
 SELECT ASSOCIATE_ID_OWNER oid, TYPE_OWNER t, MAX(OWNER_NAME) nm, COUNT(DISTINCT ASSOCIATE_ID) agencies, COUNT(DISTINCT CCN) ccns,
  COUNT(DISTINCT AGENCY_STATE) st, COUNT(DISTINCT IFF(AGENCY_STATE='CA',ASSOCIATE_ID,NULL)) ca, COUNT(DISTINCT IFF(AGENCY_STATE='TX',ASSOCIATE_ID,NULL)) tx,
  MIN(TRY_TO_DATE(ASSOCIATION_DATE_OWNER::string)) d0, MAX(TRY_TO_DATE(ASSOCIATION_DATE_OWNER::string)) d1
 FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_HOME_HEALTH_OWNERS
 WHERE ROLE_CODE_OWNER::string IN ('34','35') GROUP BY 1,2)
SELECT * FROM o QUALIFY ROW_NUMBER() OVER (PARTITION BY t ORDER BY agencies DESC) <= 25 ORDER BY t, agencies DESC;

-- [14] HH owners: per state, share of agencies with a 5%+ direct individual owner who owns 3+ / 5+ agencies nationally
WITH t AS (SELECT * FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_HOME_HEALTH_OWNERS),
ind AS (SELECT ASSOCIATE_ID_OWNER oid, COUNT(DISTINCT ASSOCIATE_ID) n FROM t WHERE TYPE_OWNER='I' AND ROLE_CODE_OWNER::string='34' GROUP BY 1),
ag AS (SELECT t.AGENCY_STATE st, t.ASSOCIATE_ID aid,
  MAX(IFF(t.TYPE_OWNER='I' AND t.ROLE_CODE_OWNER::string='34',1,0)) has_ind,
  MAX(IFF(t.TYPE_OWNER='I' AND t.ROLE_CODE_OWNER::string='34' AND i.n>=3,1,0)) m3,
  MAX(IFF(t.TYPE_OWNER='I' AND t.ROLE_CODE_OWNER::string='34' AND i.n>=5,1,0)) m5
 FROM t LEFT JOIN ind i ON i.oid=t.ASSOCIATE_ID_OWNER GROUP BY 1,2)
SELECT st, COUNT(*) agencies, SUM(has_ind) w_ind_owner, SUM(m3) w_owner3plus, SUM(m5) w_owner5plus, ROUND(SUM(m3)/COUNT(*),3) share3, ROUND(SUM(m5)/COUNT(*),3) share5
FROM ag GROUP BY ROLLUP(st) ORDER BY agencies DESC LIMIT 16;

-- [15] HH owners: matches to OIG exclusion list (person name + state, org name + state, agency NPI)
WITH o AS (SELECT DISTINCT ASSOCIATE_ID, ORGANIZATION_NAME, CCN, NPI, AGENCY_STATE, TYPE_OWNER, ROLE_TEXT_OWNER, ASSOCIATION_DATE_OWNER,
   UPPER(TRIM(FIRST_NAME_OWNER)) fn, UPPER(TRIM(MIDDLE_NAME_OWNER)) mn, UPPER(TRIM(LAST_NAME_OWNER)) ln, UPPER(TRIM(ORGANIZATION_NAME_OWNER)) orgn, STATE_OWNER
  FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_HOME_HEALTH_OWNERS),
l AS (SELECT UPPER(TRIM(FIRST_NAME)) fn, UPPER(TRIM(MIDDLE_NAME)) mn, UPPER(TRIM(LAST_NAME)) ln, UPPER(TRIM(BUSINESS_NAME)) bn, NPI, STATE, EXCLUSION_TYPE, EXCLUSION_DATE, REINSTATEMENT_DATE, GENERAL_CATEGORY
  FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_HHS_OIG_LEIE)
SELECT 'person' mt, o.fn||' '||COALESCE(o.mn,'')||' '||o.ln who, l.mn leie_mn, o.ORGANIZATION_NAME agency, o.CCN, o.AGENCY_STATE, o.ROLE_TEXT_OWNER, o.ASSOCIATION_DATE_OWNER, l.EXCLUSION_TYPE, l.EXCLUSION_DATE, l.REINSTATEMENT_DATE, l.GENERAL_CATEGORY
 FROM o JOIN l ON o.TYPE_OWNER='I' AND o.fn=l.fn AND o.ln=l.ln AND o.AGENCY_STATE=l.STATE AND o.fn<>'' AND o.ln<>''
UNION ALL
SELECT 'org', o.orgn, NULL, o.ORGANIZATION_NAME, o.CCN, o.AGENCY_STATE, o.ROLE_TEXT_OWNER, o.ASSOCIATION_DATE_OWNER, l.EXCLUSION_TYPE, l.EXCLUSION_DATE, l.REINSTATEMENT_DATE, l.GENERAL_CATEGORY
 FROM o JOIN l ON o.TYPE_OWNER='O' AND o.orgn=l.bn AND l.bn<>'' AND o.STATE_OWNER=l.STATE
UNION ALL
SELECT DISTINCT 'agency_npi', o.NPI, NULL, o.ORGANIZATION_NAME, o.CCN, o.AGENCY_STATE, NULL, NULL, l.EXCLUSION_TYPE, l.EXCLUSION_DATE, l.REINSTATEMENT_DATE, l.GENERAL_CATEGORY
 FROM (SELECT DISTINCT NPI, ORGANIZATION_NAME, CCN, AGENCY_STATE FROM o) o JOIN l ON o.NPI=l.NPI AND l.NPI NOT IN ('0000000000','') AND l.NPI IS NOT NULL
ORDER BY 1, 6, 2;

-- [16] Landing: is a hospice owner file landed anywhere
SELECT TABLE_SCHEMA, TABLE_NAME, ROW_COUNT FROM LIBRARY_RAW.INFORMATION_SCHEMA.TABLES
WHERE TABLE_NAME ILIKE '%HOSPICE%' OR (TABLE_NAME ILIKE '%OWNER%' AND TABLE_NAME ILIKE '%CMS%') ORDER BY 2;

-- [17] HH owners x OIG exclusions: one row per matched person (first+last+state), with agency city vs exclusion city as the second check
WITH o AS (SELECT ENROLLMENT_ID, ASSOCIATE_ID, ORGANIZATION_NAME, CCN, AGENCY_STATE, ASSOCIATE_ID_OWNER oid, ROLE_CODE_OWNER::string rc,
   TRY_TO_DATE(ASSOCIATION_DATE_OWNER::string) ad, UPPER(TRIM(FIRST_NAME_OWNER)) fn, UPPER(TRIM(MIDDLE_NAME_OWNER)) mn, UPPER(TRIM(LAST_NAME_OWNER)) ln
  FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_HOME_HEALTH_OWNERS WHERE TYPE_OWNER='I' AND COALESCE(TRIM(FIRST_NAME_OWNER),'')<>'' AND COALESCE(TRIM(LAST_NAME_OWNER),'')<>''),
e AS (SELECT ENROLLMENT_ID, MAX(UPPER(TRIM(CITY))) acity FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_HOME_HEALTH_AGENCY_ENROLLMENTS GROUP BY 1),
l AS (SELECT UPPER(TRIM(FIRST_NAME)) fn, UPPER(TRIM(MIDDLE_NAME)) lmn, UPPER(TRIM(LAST_NAME)) ln, STATE, UPPER(TRIM(CITY)) lcity, EXCLUSION_TYPE, EXCLUSION_DATE, REINSTATEMENT_DATE, GENERAL_CATEGORY,
   COUNT(*) OVER (PARTITION BY UPPER(TRIM(FIRST_NAME)), UPPER(TRIM(LAST_NAME))) leie_same_name_us
  FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_HHS_OIG_LEIE WHERE COALESCE(TRIM(LAST_NAME),'')<>''),
m AS (SELECT o.*, e.acity, l.lmn, l.lcity, l.EXCLUSION_TYPE, l.EXCLUSION_DATE, l.REINSTATEMENT_DATE, l.GENERAL_CATEGORY, l.leie_same_name_us
  FROM o JOIN l ON o.fn=l.fn AND o.ln=l.ln AND o.AGENCY_STATE=l.STATE LEFT JOIN e ON e.ENROLLMENT_ID=o.ENROLLMENT_ID)
SELECT oid, fn||' '||ln who, MAX(mn) owner_mn, lmn leie_mn, AGENCY_STATE st, COUNT(DISTINCT ASSOCIATE_ID) agencies,
  LISTAGG(DISTINCT ORGANIZATION_NAME, '; ') WITHIN GROUP (ORDER BY ORGANIZATION_NAME) agency_names,
  LISTAGG(DISTINCT CCN, ',') ccns, MAX(IFF(rc IN ('34','35'),1,0)) owner_5pct, MIN(ad) first_role, MAX(ad) last_role,
  EXCLUSION_DATE, REINSTATEMENT_DATE, EXCLUSION_TYPE, GENERAL_CATEGORY, lcity, LISTAGG(DISTINCT acity, ',') agency_cities,
  MAX(IFF(lcity=acity,1,0)) city_agrees, MAX(leie_same_name_us) leie_same_name_us
FROM m GROUP BY oid, fn, ln, lmn, AGENCY_STATE, EXCLUSION_DATE, REINSTATEMENT_DATE, EXCLUSION_TYPE, GENERAL_CATEGORY, lcity
ORDER BY st, who;

-- [18] HH owners x OIG: chance baseline - owners whose first+last name is on the exclusion list, same state vs other state only, next to that state's share of the list
WITH o AS (SELECT DISTINCT ASSOCIATE_ID_OWNER oid, UPPER(TRIM(FIRST_NAME_OWNER)) fn, UPPER(TRIM(LAST_NAME_OWNER)) ln, AGENCY_STATE st
  FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_HOME_HEALTH_OWNERS
  WHERE TYPE_OWNER='I' AND ROLE_CODE_OWNER::string IN ('34','35') AND COALESCE(TRIM(FIRST_NAME_OWNER),'')<>'' AND COALESCE(TRIM(LAST_NAME_OWNER),'')<>''),
l AS (SELECT DISTINCT UPPER(TRIM(FIRST_NAME)) fn, UPPER(TRIM(LAST_NAME)) ln, STATE FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_HHS_OIG_LEIE WHERE COALESCE(TRIM(LAST_NAME),'')<>''),
ls AS (SELECT STATE, COUNT(*) / SUM(COUNT(*)) OVER () leie_share FROM l GROUP BY 1),
os AS (SELECT st, COUNT(DISTINCT oid) owners FROM o GROUP BY 1),
m AS (SELECT o.oid, o.st, MAX(IFF(l.STATE=o.st,1,0)) same_st FROM o JOIN l ON o.fn=l.fn AND o.ln=l.ln GROUP BY 1,2)
SELECT os.st, os.owners, COUNT(m.oid) name_on_list_anywhere, SUM(m.same_st) same_state, COUNT(m.oid)-SUM(m.same_st) other_state_only,
  ROUND(SUM(m.same_st)/NULLIF(COUNT(m.oid),0),3) same_share, ROUND(MAX(ls.leie_share),3) state_share_of_list
FROM os LEFT JOIN m ON m.st=os.st LEFT JOIN ls ON ls.STATE=os.st GROUP BY 1,2 ORDER BY 3 DESC;

-- [19] Dialysis: which standardized-ratio measures exist in 2024, clinic counts
SELECT MEASURE_ID, MEASURE, COUNT(*) n, COUNT(DISTINCT CCN) clinics, MEDIAN(MEASURE_SCORE) med, MIN(MEASURE_SCORE) mn, MAX(MEASURE_SCORE) mx
FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_MEDICARE_DIALYSIS_FACILITIES
WHERE YEAR_COL = 2024 AND (MEASURE ILIKE '%SMR%' OR MEASURE ILIKE '%SHR (Admissions)%' OR MEASURE ILIKE '%SIR%' OR MEASURE ILIKE '%Mortality Ratio%')
GROUP BY 1,2 ORDER BY 2 LIMIT 60;

-- [20] Inpatient: per hospital, charge and Medicare payment vs the median hospital for the same DRG in the same state (DRG-states with 5+ hospitals)
WITH b AS (SELECT RNDRNG_PRVDR_CCN ccn, RNDRNG_PRVDR_ORG_NAME nm, RNDRNG_PRVDR_STATE_ABRVTN st, DRG_CD drg, TRY_TO_NUMBER(TOT_DSCHRGS) n,
   TRY_TO_DOUBLE(AVG_SUBMTD_CVRD_CHRG::string) chg, AVG_MDCR_PYMT_AMT pay
  FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_MEDICARE_INPATIENT_HOSPITALS_BY_PROVIDER_AND_SERVICE),
m AS (SELECT st, drg, MEDIAN(chg) mchg, MEDIAN(pay) mpay, COUNT(*) nh FROM b GROUP BY 1,2),
r AS (SELECT b.*, b.chg/m.mchg cr, b.pay/m.mpay pr, m.mpay FROM b JOIN m ON b.st=m.st AND b.drg=m.drg WHERE m.nh>=5),
h AS (SELECT ccn, nm, st, COUNT(*) drgs, SUM(n) dis, COUNT_IF(cr>=3) drgs_chg3x, ROUND(MEDIAN(cr),2) med_chg_ratio, ROUND(MEDIAN(pr),2) med_pay_ratio,
   COUNT_IF(pr>=1.5) drgs_pay15x, ROUND(SUM(n*(pay-mpay))/1e6,1) pay_above_state_median_m, ROUND(SUM(n*chg)/NULLIF(SUM(n*pay),0),1) chg_to_pay
  FROM r GROUP BY 1,2,3 HAVING COUNT(*)>=20)
SELECT IFF(RANK() OVER (ORDER BY med_chg_ratio DESC)<=20,'CHG','PAY') list, h.* FROM h
QUALIFY RANK() OVER (ORDER BY med_chg_ratio DESC)<=20 OR RANK() OVER (ORDER BY med_pay_ratio DESC)<=20
ORDER BY list, med_chg_ratio DESC, med_pay_ratio DESC;

-- [21] Fire: chains with 10+ homes, fire/emergency citations per home vs what their homes' states average (all homes incl. zero-citation homes)
WITH nh AS (SELECT CMS_CERTIFICATION_NUMBER_CCN ccn, STATE st, NULLIF(TRIM(CHAIN_NAME),'') chain FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_NURSING_HOME),
f AS (SELECT CMS_CERTIFICATION_NUMBER_CCN ccn, COUNT(*) defs, COUNT_IF(SCOPE_SEVERITY_CODE >= 'F') f_plus,
   COUNT_IF(DEFICIENCY_TAG_NUMBER IN ('0351','0353','0372','0374','0918')) core_life_safety
  FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_NURSING_HOME_FIRE_DEFICIENCIES GROUP BY 1),
h AS (SELECT nh.*, COALESCE(f.defs,0) defs, COALESCE(f.f_plus,0) f_plus, COALESCE(f.core_life_safety,0) cls, IFF(f.ccn IS NULL,0,1) in_fire FROM nh LEFT JOIN f ON f.ccn=nh.ccn),
s AS (SELECT st, AVG(defs) sd, AVG(f_plus) sf, AVG(cls) sc FROM h GROUP BY 1),
x AS (SELECT h.*, s.sd, s.sf, s.sc FROM h JOIN s ON s.st=h.st)
SELECT COALESCE(chain,'(no chain)') chain, COUNT(*) homes, COUNT(DISTINCT st) states, SUM(in_fire) homes_in_fire_file, SUM(defs) cites, ROUND(SUM(defs)/COUNT(*),1) per_home,
  ROUND(SUM(defs)/NULLIF(SUM(sd),0),2) obs_exp, ROUND(SUM(f_plus)/NULLIF(SUM(sf),0),2) obs_exp_f_plus, ROUND(SUM(cls)/NULLIF(SUM(sc),0),2) obs_exp_core,
  (SELECT COUNT(DISTINCT CMS_CERTIFICATION_NUMBER_CCN) FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_NURSING_HOME_FIRE_DEFICIENCIES z WHERE z.CMS_CERTIFICATION_NUMBER_CCN NOT IN (SELECT ccn FROM nh)) fire_ccns_not_in_nh
FROM x GROUP BY 1 HAVING COUNT(*)>=10 ORDER BY obs_exp DESC;

-- [22] HH owners x OIG: are the 55 agencies tied to the 44 name-matched excluded 5%+ owners still on Care Compare, and how do their spend and stars sit vs their state
WITH hh AS (SELECT CCN, STATE, PROVIDER_NAME, CERTIFICATION_DATE, TRY_TO_DOUBLE(QUALITY_OF_PATIENT_CARE_STAR_RATING::string) star,
   TRY_TO_DOUBLE(HOW_MUCH_MEDICARE_SPENDS_ON_AN_EPISODE_OF_CARE_AT_THIS_AGENCY_COMPARED_TO_MEDICARE_SPENDING_ACROSS_ALL_AGENCIES_NATIONALLY::string) spend
  FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_HOME_HEALTH),
st AS (SELECT STATE, AVG(star) st_star, AVG(spend) st_spend, MEDIAN(spend) st_spend_med, COUNT(*) st_n FROM hh GROUP BY 1)
SELECT hh.CCN, hh.PROVIDER_NAME, hh.STATE, hh.CERTIFICATION_DATE, hh.star, ROUND(st.st_star,2) st_star, hh.spend, ROUND(st.st_spend,2) st_spend, ROUND(st.st_spend_med,2) st_spend_med,
  (SELECT COUNT(*) FROM hh h2 WHERE h2.STATE=hh.STATE AND h2.spend > hh.spend) agencies_spending_more_in_state, st.st_n
FROM hh JOIN st ON st.STATE=hh.STATE WHERE hh.CCN IN ('059417','103116','107643','108182','108194','108275','108304','108316','108456','108491','109043','109338','109361','109540','109668','148124','148316','368153','368281','368489','457702','559315','559402','559751','679589','679737','679780','687221','687253','687357','747028','747060','747298','747307','747460','747563','747575','747609','747649','748068','748174','753177','757131','757300','757501','757515','757628','757722','757921','757922','757963','757985','758098','758111','758135') ORDER BY hh.STATE, hh.spend DESC;

-- [23] Dialysis: 2024 mortality and infection measure names
SELECT MEASURE_ID, MEASURE, COUNT(DISTINCT CCN) clinics, MEDIAN(MEASURE_SCORE) med, MAX(MEASURE_SCORE) mx
FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_MEDICARE_DIALYSIS_FACILITIES
WHERE YEAR_COL = 2024 AND (MEASURE ILIKE 'F: All Patient Mortality -%' OR MEASURE ILIKE '%infection%' OR MEASURE ILIKE '%BSI%' OR MEASURE ILIKE '%NHSN%')
GROUP BY 1,2 ORDER BY 2 LIMIT 40;

-- [24] NADAC: generic drugs whose price per unit jumped 3x+ from one price to the next (same unit), counted across NDCs (makers and package sizes)
WITH x AS (SELECT NDC, DRUG_DESCRIPTION dd, RATE_CLASSIFICATION cls, IS_OTC, PRICING_UNIT u, EFFECTIVE_DATE d, NADAC_PER_UNIT p,
   LAG(NADAC_PER_UNIT) OVER (PARTITION BY NDC ORDER BY EFFECTIVE_DATE) pp, LAG(PRICING_UNIT) OVER (PARTITION BY NDC ORDER BY EFFECTIVE_DATE) pu,
   LAG(EFFECTIVE_DATE) OVER (PARTITION BY NDC ORDER BY EFFECTIVE_DATE) pd, LEAD(NADAC_PER_UNIT) OVER (PARTITION BY NDC ORDER BY EFFECTIVE_DATE) np
  FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_NADAC),
dn AS (SELECT DRUG_DESCRIPTION dd, COUNT(DISTINCT NDC) ndcs_listed FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_NADAC GROUP BY 1),
j AS (SELECT * FROM x WHERE cls='G' AND pp>0 AND u=pu AND p/pp>=3)
SELECT j.dd, j.u, j.IS_OTC, COUNT(DISTINCT j.NDC) ndcs_jumped, MAX(dn.ndcs_listed) ndcs_listed, ROUND(MEDIAN(p/pp),1) med_jump, ROUND(MAX(p/pp),1) max_jump,
  ROUND(MEDIAN(pp),4) old_price_med, ROUND(MEDIAN(p),4) new_price_med, MIN(d) first_jump, MAX(d) last_jump, COUNT_IF(np < p*0.5) fell_back_by_half,
  (SELECT COUNT(*) FROM j) all_jump_rows, (SELECT COUNT(DISTINCT dd) FROM j) all_jump_drugs
FROM j JOIN dn ON dn.dd=j.dd GROUP BY 1,2,3 ORDER BY ndcs_jumped DESC, med_jump DESC LIMIT 40;

-- [25] Fire: same home, same fire tag, cited in all 3 inspection cycles - share of homes by chain vs their states
WITH nh AS (SELECT CMS_CERTIFICATION_NUMBER_CCN ccn, STATE st, NULLIF(TRIM(CHAIN_NAME),'') chain FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_NURSING_HOME),
rep AS (SELECT CMS_CERTIFICATION_NUMBER_CCN ccn, DEFICIENCY_PREFIX||DEFICIENCY_TAG_NUMBER tag, COUNT(DISTINCT INSPECTION_CYCLE) cyc
  FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_NURSING_HOME_FIRE_DEFICIENCIES GROUP BY 1,2),
hr AS (SELECT ccn, COUNT_IF(cyc=3) tags_all3 FROM rep GROUP BY 1),
h AS (SELECT nh.*, COALESCE(hr.tags_all3,0) t3, IFF(COALESCE(hr.tags_all3,0)>0,1,0) any3 FROM nh LEFT JOIN hr ON hr.ccn=nh.ccn),
s AS (SELECT st, AVG(any3) s_any3, AVG(t3) s_t3 FROM h GROUP BY 1)
SELECT COALESCE(chain,'(no chain)') chain, COUNT(*) homes, SUM(any3) homes_with_3cycle_repeat, ROUND(AVG(any3),2) share, ROUND(SUM(any3)/NULLIF(SUM(s.s_any3),0),2) obs_exp_homes,
  ROUND(SUM(t3)/NULLIF(SUM(s.s_t3),0),2) obs_exp_tags, (SELECT ROUND(AVG(any3),3) FROM h) national_share
FROM h JOIN s ON s.st=h.st GROUP BY 1 HAVING COUNT(*)>=10 ORDER BY obs_exp_homes DESC LIMIT 25;

-- [26] Dialysis 2024: chains with 20+ clinics - deaths and admissions vs CMS expected, re-based to each clinic's own state; infection ratio joined from the clinic file
WITH c AS (SELECT CCN, MAX(STATE) st, MAX(CHAIN) chain,
   MAX(IFF(MEASURE_ID='deay4_f',MEASURE_SCORE,NULL)) deaths, MAX(IFF(MEASURE_ID='exdy4_f',MEASURE_SCORE,NULL)) exp_deaths,
   MAX(IFF(MEASURE_ID='smry4_f',MEASURE_SCORE,NULL)) smr, MAX(IFF(MEASURE_ID='pmy4_f',MEASURE_SCORE,NULL)) p_smr, MAX(IFF(MEASURE_ID='rkmsy4_f',MEASURE_SCORE,NULL)) rk_smr,
   MAX(IFF(MEASURE_ID='htay4_f',MEASURE_SCORE,NULL)) adm, MAX(IFF(MEASURE_ID='exty4_f',MEASURE_SCORE,NULL)) exp_adm,
   MAX(IFF(MEASURE_ID='shrty4_f',MEASURE_SCORE,NULL)) shr, MAX(IFF(MEASURE_ID='pchtay4_f',MEASURE_SCORE,NULL)) p_shr
  FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_MEDICARE_DIALYSIS_FACILITIES
  WHERE YEAR_COL=2024 AND MEASURE_ID IN ('deay4_f','exdy4_f','smry4_f','pmy4_f','rkmsy4_f','htay4_f','exty4_f','shrty4_f','pchtay4_f') GROUP BY 1),
s AS (SELECT st, SUM(deaths)/NULLIF(SUM(exp_deaths),0) st_smr, SUM(adm)/NULLIF(SUM(exp_adm),0) st_shr FROM c GROUP BY 1),
f AS (SELECT CCN, TRY_TO_DOUBLE(STANDARD_INFECTION_RATIO::string) sir, PATIENT_INFECTION_CATEGORY_TEXT icat, PATIENT_SURVIVAL_CATEGORY_TEXT scat FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_DIALYSIS),
x AS (SELECT c.*, s.st_smr, s.st_shr, f.sir, f.icat, f.scat, IFF(f.CCN IS NULL,0,1) in_fac, CORR(c.smr, c.rk_smr) OVER () corr_smr_rank FROM c JOIN s ON s.st=c.st LEFT JOIN f ON f.CCN=c.CCN)
SELECT chain, COUNT(*) clinics, COUNT(DISTINCT st) states, ROUND(SUM(deaths)) deaths, ROUND(SUM(exp_deaths)) exp_deaths,
  ROUND(SUM(deaths)/NULLIF(SUM(exp_deaths),0),3) smr_vs_us, ROUND(SUM(deaths)/NULLIF(SUM(exp_deaths*st_smr),0),3) smr_vs_own_states,
  ROUND(AVG(IFF(smr>1 AND p_smr<0.05,1,0)),3) share_smr_worse_sig, ROUND(AVG(rk_smr),1) avg_state_rank_smr,
  ROUND(SUM(adm)/NULLIF(SUM(exp_adm),0),3) shr_vs_us, ROUND(SUM(adm)/NULLIF(SUM(exp_adm*st_shr),0),3) shr_vs_own_states, ROUND(AVG(IFF(shr>1 AND p_shr<0.05,1,0)),3) share_shr_worse_sig,
  SUM(in_fac) in_fac_file, ROUND(MEDIAN(sir),2) med_sir, COUNT(sir) n_sir, ROUND(AVG(IFF(icat ILIKE 'Worse%',1,0)),3) share_inf_worse, ROUND(AVG(IFF(scat ILIKE 'Worse%',1,0)),3) share_surv_worse,
  ROUND(MAX(corr_smr_rank),2) corr_smr_rank
FROM x GROUP BY 1 HAVING COUNT(*)>=20 ORDER BY clinics DESC;

-- [27] NADAC: how often generic prices step up or down between consecutive prices, and the biggest 2x+ Rx generic step-ups
WITH x AS (SELECT NDC, DRUG_DESCRIPTION dd, RATE_CLASSIFICATION cls, IS_OTC, PRICING_UNIT u, EFFECTIVE_DATE d, NADAC_PER_UNIT p,
   LAG(NADAC_PER_UNIT) OVER (PARTITION BY NDC ORDER BY EFFECTIVE_DATE) pp, LAG(PRICING_UNIT) OVER (PARTITION BY NDC ORDER BY EFFECTIVE_DATE) pu,
   LEAD(NADAC_PER_UNIT) OVER (PARTITION BY NDC ORDER BY EFFECTIVE_DATE) np, LEAD(EFFECTIVE_DATE) OVER (PARTITION BY NDC ORDER BY EFFECTIVE_DATE) nd
  FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_NADAC),
g AS (SELECT * FROM x WHERE cls='G' AND pp>0 AND u=pu),
tot AS (SELECT COUNT(*) steps, COUNT_IF(p/pp>=2) up2, COUNT_IF(p/pp>=3) up3, COUNT_IF(p/pp<=0.5) down2, COUNT(DISTINCT IFF(p/pp>=2,dd,NULL)) drugs_up2,
   (SELECT COUNT(*) FROM x WHERE d < '2024-01-01') rows_before_2024, (SELECT COUNT(DISTINCT NDC) FROM x WHERE d < '2024-01-01') ndcs_before_2024 FROM g),
top AS (SELECT dd, u, IS_OTC, MIN(d) d, ROUND(MEDIAN(pp),4) old_p, ROUND(MEDIAN(p),4) new_p, ROUND(MEDIAN(p/pp),2) jump, COUNT(DISTINCT NDC) ndcs, ROUND(MEDIAN(np),4) next_p, MIN(nd) next_d
   FROM g WHERE p/pp>=2 AND IS_OTC='N' GROUP BY dd, u, IS_OTC)
SELECT top.*, tot.* FROM top CROSS JOIN tot ORDER BY jump DESC LIMIT 30;

-- [28] Fire: the chains that ran high on both counts - where they are and what they keep getting cited for
WITH nh AS (SELECT CMS_CERTIFICATION_NUMBER_CCN ccn, STATE st, TRIM(CHAIN_NAME) chain, OVERALL_RATING FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_NURSING_HOME
   WHERE TRIM(CHAIN_NAME) IN ('CARECORE HEALTH','APERION CARE','EDEN SENIOR CARE','ALLIANCE HEALTH GROUP','JOURNEY HEALTHCARE','BRIA HEALTH SERVICES','MADISON CREEK PARTNERS','THE GRAND HEALTHCARE')),
f AS (SELECT CMS_CERTIFICATION_NUMBER_CCN ccn, DEFICIENCY_PREFIX||DEFICIENCY_TAG_NUMBER tag, DEFICIENCY_DESCRIPTION de, SCOPE_SEVERITY_CODE sev, INSPECTION_CYCLE cyc
   FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_NURSING_HOME_FIRE_DEFICIENCIES),
j AS (SELECT nh.chain, nh.st, nh.ccn, f.tag, f.de, f.sev, f.cyc FROM nh JOIN f ON f.ccn=nh.ccn),
t AS (SELECT chain, tag, MAX(de) de, COUNT(*) n, ROW_NUMBER() OVER (PARTITION BY chain ORDER BY COUNT(*) DESC) rn FROM j GROUP BY 1,2)
SELECT n2.chain, n2.states, n2.homes, n2.cites, n2.g_plus, n2.f_plus, LISTAGG(t.tag||' '||LEFT(t.de,40)||' ('||t.n||')', ' | ') WITHIN GROUP (ORDER BY t.rn) top_tags
FROM (SELECT chain, LISTAGG(DISTINCT st, ',') states, COUNT(DISTINCT ccn) homes, COUNT(*) cites, COUNT_IF(sev>='G') g_plus, COUNT_IF(sev>='F') f_plus FROM j GROUP BY 1) n2
JOIN t ON t.chain=n2.chain AND t.rn<=3 GROUP BY 1,2,3,4,5,6 ORDER BY 1;

-- [29] HH: agencies on Care Compare certified 2023 or later, by state - denominator for the name-matched excluded owners
SELECT STATE, COUNT(*) agencies, COUNT_IF(CERTIFICATION_DATE >= '2023-01-01') cert_2023_plus,
  COUNT_IF(CERTIFICATION_DATE >= '2023-01-01' AND CCN IN ('059417','103116','107643','108182','108194','108275','108304','108316','108456','108491','109043','109338','109361','109540','109668','148124','148316','368153','368281','368489','457702','559315','559402','559751','679589','679737','679780','687221','687253','687357','747028','747060','747298','747307','747460','747563','747575','747609','747649','748068','748174','753177','757131','757300','757501','757515','757628','757722','757921','757922','757963','757985','758098','758111','758135')) cert_2023_plus_with_matched_owner, COUNT_IF(CCN IN ('059417','103116','107643','108182','108194','108275','108304','108316','108456','108491','109043','109338','109361','109540','109668','148124','148316','368153','368281','368489','457702','559315','559402','559751','679589','679737','679780','687221','687253','687357','747028','747060','747298','747307','747460','747563','747575','747609','747649','748068','748174','753177','757131','757300','757501','757515','757628','757722','757921','757922','757963','757985','758098','758111','758135')) with_matched_owner
FROM LIBRARY_MARTS.HEALTH.HEALTH__FED_CMS_HOME_HEALTH GROUP BY ROLLUP(STATE) ORDER BY cert_2023_plus DESC LIMIT 8;
