{{ config(tags=['spine_generated']) }}

-- GRAIN: one row per facility (CCN is unique)
-- SPINE_ENTITY: facility  (natural_key: CCN)
-- Generated by scripts/generate_staging_models.py from SOURCE_REGISTRY -- deterministic,
-- no LLM.
-- CASTS: 45 of 70 columns, from landing_column_profile_2026-09-19.tsv. A column is cast only
-- when every filled value in the sample parsed. try_ casts: a value that does not
-- parse reads NULL. The natural key and join-key columns stay TEXT.
--   objectid: ID: whole numbers, over 90% distinct -- stays TEXT, '.0' tail removed
--   crimeid: ID: whole numbers, over 90% distinct -- stays TEXT, '.0' tail removed
--   reportdate: integer
--   measure: float
--   offset: float
--   streetsegid: integer
--   roadwayseg: integer
--   fromdate: integer
--   marid: integer
--   xcoord: float
--   ycoord: float
--   mar_score: float
--   majorinjuries_bicyclist: integer
--   minorinjuries_bicyclist: integer
--   unknowninjuries_bicyclist: integer
--   fatal_bicyclist: integer
--   majorinjuries_driver: integer
--   minorinjuries_driver: integer
--   unknowninjuries_driver: integer
--   fatal_driver: integer
--   majorinjuries_pedestrian: integer
--   minorinjuries_pedestrian: integer
--   unknowninjuries_pedestrian: integer
--   fatal_pedestrian: integer
--   total_vehicles: integer
--   total_bicycles: integer
--   total_pedestrians: integer
--   pedestrians_impaired: integer
--   bicyclists_impaired: integer
--   drivers_impaired: integer
--   total_taxi: integer
--   total_government: integer
--   speeding_involved: integer
--   offintersection: float
--   lastupdate: integer
--   mpdlatitude: float
--   mpdlongitude: float
--   mpdgeox: float
--   mpdgeoy: float
--   objectid_12: ID: whole numbers, over 90% distinct -- stays TEXT, '.0' tail removed
--   join_count: integer
--   target_fid: ID: whole numbers, over 90% distinct -- stays TEXT, '.0' tail removed
--   district: integer
--   psa: integer
--   poldist_id: integer
-- landing table's ingestion timestamp is named INGESTED_AT (no leading underscore) rather than the usual _INGESTED_AT -- confirmed via INFORMATION_SCHEMA, not assumed.
-- DEDUPE: registry natural_key (CCN) is NOT unique within a load as landed at generation time -- it would collapse 17 of 26,559 rows. Deduping on the WHOLE ROW instead (exact copies only). A record that changes between loads shows once per version. Find the real key, fix SOURCE_REGISTRY, regenerate.

with source as (

    select * from {{ source('ripple_raw', 'PORTAL_ARC_OPEN_DATA_DC_32AD83D2EC') }}
    qualify row_number() over (partition by "OBJECTID", "OBJECTID_1", "CRIMEID", "CCN", "REPORTDATE", "ROUTEID", "MEASURE", "OFFSET", "STREETSEGID", "ROADWAYSEG", "FROMDATE", "TODATE", "MARID", "ADDRESS", "LATITUDE", "LONGITUDE", "XCOORD", "YCOORD", "WARD", "EVENTID", "MAR_ADDRESS", "MAR_SCORE", "MAJORINJURIES_BICYCLIST", "MINORINJURIES_BICYCLIST", "UNKNOWNINJURIES_BICYCLIST", "FATAL_BICYCLIST", "MAJORINJURIES_DRIVER", "MINORINJURIES_DRIVER", "UNKNOWNINJURIES_DRIVER", "FATAL_DRIVER", "MAJORINJURIES_PEDESTRIAN", "MINORINJURIES_PEDESTRIAN", "UNKNOWNINJURIES_PEDESTRIAN", "FATAL_PEDESTRIAN", "TOTAL_VEHICLES", "TOTAL_BICYCLES", "TOTAL_PEDESTRIANS", "PEDESTRIANS_IMPAIRED", "BICYCLISTS_IMPAIRED", "DRIVERS_IMPAIRED", "TOTAL_TAXI", "TOTAL_GOVERNMENT", "SPEEDING_INVOLVED", "NEARESTINTROUTEID", "NEARESTSTREETNAME", "OFFINTERSECTION", "INTAPPROACHDIRECTION", "LOCATIONERROR", "LASTUPDATE", "MPDLATITUDE", "MPDLONGITUDE", "MPDGEOX", "MPDGEOY", "OBJECTID_12", "JOIN_COUNT", "TARGET_FID", "DISTRICT", "PSA", "NAME", "WEB_URL", "POLDIST_ID", "SECTOR", "SE_ANNO_CAD_DATA", "GIS_ID", "CREATOR", "CREATED", "EDITOR", "EDITED", "POLICEDISTRICT", "GEOMETRY" order by INGESTED_AT desc) = 1

),

renamed as (

    select
        {{ stg_id_text('"OBJECTID"') }} as objectid,
        {{ null_junk('"OBJECTID_1"') }} as objectid_1,
        {{ stg_id_text('"CRIMEID"') }} as crimeid,
        {{ null_junk('"CCN"') }} as ccn,
        {{ stg_int('"REPORTDATE"') }} as reportdate,
        {{ null_junk('"ROUTEID"') }} as routeid,
        {{ stg_float('"MEASURE"') }} as measure,
        {{ stg_float('"OFFSET"') }} as offset,
        {{ stg_int('"STREETSEGID"') }} as streetsegid,
        {{ stg_int('"ROADWAYSEG"') }} as roadwayseg,
        {{ stg_int('"FROMDATE"') }} as fromdate,
        {{ null_junk('"TODATE"') }} as todate,
        {{ stg_int('"MARID"') }} as marid,
        {{ null_junk('"ADDRESS"') }} as address,
        {{ null_junk('"LATITUDE"') }} as latitude,
        {{ null_junk('"LONGITUDE"') }} as longitude,
        {{ stg_float('"XCOORD"') }} as xcoord,
        {{ stg_float('"YCOORD"') }} as ycoord,
        {{ null_junk('"WARD"') }} as ward,
        {{ null_junk('"EVENTID"') }} as eventid,
        {{ null_junk('"MAR_ADDRESS"') }} as mar_address,
        {{ stg_float('"MAR_SCORE"') }} as mar_score,
        {{ stg_int('"MAJORINJURIES_BICYCLIST"') }} as majorinjuries_bicyclist,
        {{ stg_int('"MINORINJURIES_BICYCLIST"') }} as minorinjuries_bicyclist,
        {{ stg_int('"UNKNOWNINJURIES_BICYCLIST"') }} as unknowninjuries_bicyclist,
        {{ stg_int('"FATAL_BICYCLIST"') }} as fatal_bicyclist,
        {{ stg_int('"MAJORINJURIES_DRIVER"') }} as majorinjuries_driver,
        {{ stg_int('"MINORINJURIES_DRIVER"') }} as minorinjuries_driver,
        {{ stg_int('"UNKNOWNINJURIES_DRIVER"') }} as unknowninjuries_driver,
        {{ stg_int('"FATAL_DRIVER"') }} as fatal_driver,
        {{ stg_int('"MAJORINJURIES_PEDESTRIAN"') }} as majorinjuries_pedestrian,
        {{ stg_int('"MINORINJURIES_PEDESTRIAN"') }} as minorinjuries_pedestrian,
        {{ stg_int('"UNKNOWNINJURIES_PEDESTRIAN"') }} as unknowninjuries_pedestrian,
        {{ stg_int('"FATAL_PEDESTRIAN"') }} as fatal_pedestrian,
        {{ stg_int('"TOTAL_VEHICLES"') }} as total_vehicles,
        {{ stg_int('"TOTAL_BICYCLES"') }} as total_bicycles,
        {{ stg_int('"TOTAL_PEDESTRIANS"') }} as total_pedestrians,
        {{ stg_int('"PEDESTRIANS_IMPAIRED"') }} as pedestrians_impaired,
        {{ stg_int('"BICYCLISTS_IMPAIRED"') }} as bicyclists_impaired,
        {{ stg_int('"DRIVERS_IMPAIRED"') }} as drivers_impaired,
        {{ stg_int('"TOTAL_TAXI"') }} as total_taxi,
        {{ stg_int('"TOTAL_GOVERNMENT"') }} as total_government,
        {{ stg_int('"SPEEDING_INVOLVED"') }} as speeding_involved,
        {{ null_junk('"NEARESTINTROUTEID"') }} as nearestintrouteid,
        {{ null_junk('"NEARESTSTREETNAME"') }} as neareststreetname,
        {{ stg_float('"OFFINTERSECTION"') }} as offintersection,
        {{ null_junk('"INTAPPROACHDIRECTION"') }} as intapproachdirection,
        {{ null_junk('"LOCATIONERROR"') }} as locationerror,
        {{ stg_int('"LASTUPDATE"') }} as lastupdate,
        {{ stg_float('"MPDLATITUDE"') }} as mpdlatitude,
        {{ stg_float('"MPDLONGITUDE"') }} as mpdlongitude,
        {{ stg_float('"MPDGEOX"') }} as mpdgeox,
        {{ stg_float('"MPDGEOY"') }} as mpdgeoy,
        {{ stg_id_text('"OBJECTID_12"') }} as objectid_12,
        {{ stg_int('"JOIN_COUNT"') }} as join_count,
        {{ stg_id_text('"TARGET_FID"') }} as target_fid,
        {{ stg_int('"DISTRICT"') }} as district,
        {{ stg_int('"PSA"') }} as psa,
        {{ null_junk('"NAME"') }} as name,
        {{ null_junk('"WEB_URL"') }} as web_url,
        {{ stg_int('"POLDIST_ID"') }} as poldist_id,
        {{ null_junk('"SECTOR"') }} as sector,
        {{ null_junk('"SE_ANNO_CAD_DATA"') }} as se_anno_cad_data,
        {{ null_junk('"GIS_ID"') }} as gis_id,
        {{ null_junk('"CREATOR"') }} as creator,
        {{ null_junk('"CREATED"') }} as created,
        {{ null_junk('"EDITOR"') }} as editor,
        {{ null_junk('"EDITED"') }} as edited,
        {{ null_junk('"POLICEDISTRICT"') }} as policedistrict,
        {{ null_junk('"GEOMETRY"') }} as geometry,
        INGESTED_AT as _loaded_at,
        'https://opendata.dc.gov/datasets/9298eac628614f0d93f0bb284db54ad1_0' as _source_url,
    'ENT_' || LEFT(MD5('CCN' || '|' || (CASE WHEN LENGTH(UPPER(REGEXP_REPLACE(TO_VARCHAR("CCN"), '[^0-9A-Za-z]', ''))) = 0 OR LENGTH(UPPER(REGEXP_REPLACE(TO_VARCHAR("CCN"), '[^0-9A-Za-z]', ''))) > 6 OR NOT REGEXP_LIKE(UPPER(REGEXP_REPLACE(TO_VARCHAR("CCN"), '[^0-9A-Za-z]', '')), '^[0-9]+$') OR LPAD(UPPER(REGEXP_REPLACE(TO_VARCHAR("CCN"), '[^0-9A-Za-z]', '')), 6, '0') = REPEAT('0', 6) OR (LENGTH(UPPER(REGEXP_REPLACE(TO_VARCHAR("CCN"), '[^0-9A-Za-z]', ''))) >= 4 AND UPPER(REGEXP_REPLACE(TO_VARCHAR("CCN"), '[^0-9A-Za-z]', '')) = REPEAT(LEFT(UPPER(REGEXP_REPLACE(TO_VARCHAR("CCN"), '[^0-9A-Za-z]', '')), 1), LENGTH(UPPER(REGEXP_REPLACE(TO_VARCHAR("CCN"), '[^0-9A-Za-z]', ''))))) OR LPAD(UPPER(REGEXP_REPLACE(TO_VARCHAR("CCN"), '[^0-9A-Za-z]', '')), 6, '0') = REPEAT(LEFT(LPAD(UPPER(REGEXP_REPLACE(TO_VARCHAR("CCN"), '[^0-9A-Za-z]', '')), 6, '0'), 1), 6) OR UPPER(REGEXP_REPLACE(TO_VARCHAR("CCN"), '[^0-9A-Za-z]', '')) IN ('123456789', '987654321', '1234567890', '0987654321', '12345678', '87654321', '123456', '654321') OR LPAD(UPPER(REGEXP_REPLACE(TO_VARCHAR("CCN"), '[^0-9A-Za-z]', '')), 6, '0') IN ('123456789', '987654321', '1234567890', '0987654321', '12345678', '87654321', '123456', '654321') THEN NULL ELSE LPAD(UPPER(REGEXP_REPLACE(TO_VARCHAR("CCN"), '[^0-9A-Za-z]', '')), 6, '0') END)), 16) as spine_entity_id  -- joins LIBRARY_META."CONNECT".ENTITY_GOLDEN.ENTITY_ID

    from source

)

select * from renamed
