-- Q6: [save:fecid] member-to-FEC-candidate-ID bridge, whole table
SELECT * FROM LIBRARY_MARTS.POLITICS.POLITICS__MEMBER_FEC_ID

-- Q7: [save:fcand] FEC Senate and President candidates, 2024 and 2026 cycles, with money raised
SELECT c.CAND_ID, c.CYCLE, c.CAND_NAME, c.INCUMBENT_CHALLENGER, c.CAND_STATUS, c.CAND_ELECTION_YR, c.PARTY, c.OFFICE, c.OFFICE_STATE,
       s.TTL_RECEIPTS, s.TTL_DISB, s.COVERAGE_END_DATE
FROM LIBRARY_MARTS.POLITICS.POLITICS__FEC_CANDIDATE c
LEFT JOIN LIBRARY_MARTS.POLITICS.POLITICS__FEC_CANDIDATE_SUMMARY s ON s.CAND_ID = c.CAND_ID AND s.CYCLE = c.CYCLE
WHERE c.OFFICE IN ('S','P')

-- Q8: [save:vvmonth] Voteview individual votes rolled to member-month: votes, not-voting, present, code-0, unmatched dates
WITH r AS (
  SELECT CONGRESS, UPPER(CHAMBER) AS CH, TRY_TO_NUMBER(TO_VARCHAR(ROLLNUMBER)) AS RN,
         DATE_TRUNC('month', TRY_TO_DATE(LEFT(TO_VARCHAR(VOTE_DATE),10))) AS MON
  FROM LIBRARY_MARTS.POLITICS.POLITICS__VOTEVIEW_ROLLCALLS
  WHERE CONGRESS IN (118,119)
)
SELECT v.CONGRESS, UPPER(v.CHAMBER) AS CH, v.ICPSR, r.MON,
       COUNT(*) AS N, SUM(IFF(v.CAST_CODE IN (9), 1, 0)) AS NV, SUM(IFF(v.CAST_CODE IN (7,8), 1, 0)) AS PRES,
       SUM(IFF(v.CAST_CODE = 0, 1, 0)) AS C0, SUM(IFF(r.RN IS NULL, 1, 0)) AS NO_RC
FROM LIBRARY_MARTS.POLITICS.POLITICS__VOTEVIEW_VOTES v
LEFT JOIN r ON r.CONGRESS = v.CONGRESS AND r.CH = UPPER(v.CHAMBER) AND r.RN = TRY_TO_NUMBER(TO_VARCHAR(v.ROLLNUMBER))
GROUP BY 1,2,3,4

-- Q9: bills, 118th Congress: how "advanced past committee" lines up with the latest stage, House vs Senate bills
SELECT BILL_TYPE, LATEST_STAGE, ADVANCED_PAST_COMMITTEE, COUNT(*) AS N,
       SUM(IFF(SPONSOR_BIOGUIDE = 'B001302', 1, 0)) AS BIGGS
FROM LIBRARY_MARTS.POLITICS.POLITICS__BILLS
WHERE CONGRESS = 118 AND BILL_TYPE IN ('HR','S')
GROUP BY 1,2,3 ORDER BY 1,2,3

-- Q10: bills flagged advanced but stuck at committee_action: the top latest-action texts, 118th House bills
SELECT LEFT(LATEST_ACTION_TEXT, 90) AS ACT, COUNT(*) AS N, SUM(IFF(SPONSOR_BIOGUIDE = 'B001302', 1, 0)) AS BIGGS
FROM LIBRARY_MARTS.POLITICS.POLITICS__BILLS
WHERE CONGRESS = 118 AND BILL_TYPE = 'HR' AND ADVANCED_PAST_COMMITTEE = TRUE
GROUP BY 1 ORDER BY 2 DESC LIMIT 25
