-- Q14: Andy Biggs's 118th-Congress bills: second source (GovInfo bill status) vs the Congress.gov bills table, count by bill type
SELECT 'govinfo' AS SRC, BILL_TYPE, COUNT(*) AS N, COUNT(DISTINCT BILL_NUMBER) AS NUMS, MIN(INTRODUCED_DATE) AS FIRST_DT, MAX(INTRODUCED_DATE) AS LAST_DT
FROM LIBRARY_MARTS.POLITICS.POLITICS__FED_GOVINFO_BILLSTATUS
WHERE CONGRESS = 118 AND SPONSOR_BIOGUIDE = 'B001302' GROUP BY 1, 2
UNION ALL
SELECT 'bills', BILL_TYPE, COUNT(*), COUNT(DISTINCT BILL_NUMBER), MIN(INTRODUCED_DATE)::VARCHAR, MAX(INTRODUCED_DATE)::VARCHAR
FROM LIBRARY_MARTS.POLITICS.POLITICS__BILLS
WHERE CONGRESS = 118 AND SPONSOR_BIOGUIDE = 'B001302' GROUP BY 1, 2

-- Q15: Andy Biggs's 118th-Congress bills: introduced month and the most common title openings
SELECT TO_CHAR(TRY_TO_DATE(LEFT(TO_VARCHAR(INTRODUCED_DATE), 10)), 'YYYY-MM') AS MON, COUNT(*) AS N,
       COUNT(DISTINCT LEFT(TITLE, 25)) AS TITLE_OPENINGS, ANY_VALUE(LEFT(TITLE, 110)) AS EXAMPLE
FROM LIBRARY_MARTS.POLITICS.POLITICS__BILLS
WHERE CONGRESS = 118 AND SPONSOR_BIOGUIDE = 'B001302'
GROUP BY 1 ORDER BY 1
