{{ config(tags=['spine_generated']) }}

-- GRAIN: one row per record (spine_entity not determined -- no registry hint available) (GEO_ID is unique)
-- SPINE_ENTITY: (not determined)  (natural_key: GEO_ID)
-- Generated by scripts/generate_staging_models.py from SOURCE_REGISTRY -- deterministic,
-- no LLM.
-- CASTS: 1 of 3 columns, from landing_column_profile_2026-09-19.tsv. A column is cast only
-- when every filled value in the sample parsed. try_ casts: a value that does not
-- parse reads NULL. The natural key and join-key columns stay TEXT.
--   b25064_001e: integer
-- spine_entity not determined (grain/natural_key proven, but no registry hint says what this row is ABOUT) -- no SPINE_ENTITY_ID emitted.
-- landing table's ingestion timestamp is named INGESTED_AT (no leading underscore) rather than the usual _INGESTED_AT -- confirmed via INFORMATION_SCHEMA, not assumed.

with source as (

    select * from {{ source('ripple_raw', 'PORTAL_CKA_HOUSTON_OPEN_DAT_442A765041') }}
    qualify row_number() over (partition by "GEO_ID" order by INGESTED_AT desc) = 1

),

renamed as (

    select
        {{ null_junk('"GEO_ID"') }} as geo_id,
        {{ null_junk('"NAME"') }} as name,
        {{ stg_int('"B25064_001E"') }} as b25064_001e,
        INGESTED_AT as _loaded_at,
        'https://data.houstontx.gov/dataset/acs-5-year-median-gross-rent-estimates-at-block-group-level' as _source_url

    from source

)

select * from renamed
