{{ config(tags=['spine_generated']) }}

-- GRAIN: one row per facility (CCN+PENALTY_DATE+PAYMENT_DENIAL_START_DATE+PROCESSING_DATE+FINE_ID unique)
-- SPINE_ENTITY: facility  (natural_key: CMS_CERTIFICATION_NUMBER_CCN, PENALTY_DATE, PAYMENT_DENIAL_START_DATE, PROCESSING_DATE, FINE_ID)
-- Generated by scripts/generate_staging_models.py from SOURCE_REGISTRY -- deterministic,
-- no LLM. Casts kept as landed (TEXT) -- add explicit type casts by hand once each
-- column's real type is confirmed; this generator has no semantic type knowledge.
-- spine_entity 'facility' has no connect/ resolver yet (see connect/spine_entity.py) -- no SPINE_ENTITY_ID emitted.

with source as (

    select * from {{ source('ripple_raw', 'FED_CMS_NURSING_HOME_PENALTIES') }}

),

renamed as (

    select
        "CMS_CERTIFICATION_NUMBER_CCN" as cms_certification_number_ccn,
        "PROVIDER_NAME" as provider_name,
        "PROVIDER_ADDRESS" as provider_address,
        "CITY_TOWN" as city_town,
        "STATE" as state,
        "ZIP_CODE" as zip_code,
        "PENALTY_DATE" as penalty_date,
        "PENALTY_TYPE" as penalty_type,
        "FINE_ID" as fine_id,
        "FINE_AMOUNT" as fine_amount,
        "PAYMENT_DENIAL_START_DATE" as payment_denial_start_date,
        "PAYMENT_DENIAL_LENGTH_IN_DAYS" as payment_denial_length_in_days,
        "LOCATION" as location,
        "PROCESSING_DATE" as processing_date,
        _INGESTED_AT as _loaded_at,
        '' as _source_url

    from source

)

select * from renamed
qualify row_number() over (partition by cms_certification_number_ccn, penalty_date, payment_denial_start_date, processing_date, fine_id order by _loaded_at desc) = 1
