{{ config(tags=['minimal_staging']) }}

-- GRAIN: NOT YET DETERMINED (profiler returned AMBIGUOUS -- needs manual review)
-- This is a passthrough staging view: snake_case rename only, no dedup.
-- Once grain is resolved, replace with a full staging model via generate_staging_models.py.
-- Generated by scripts/generate_minimal_staging.py

with source as (

    select * from {{ source('ripple_raw', 'INTL_ADB_DATA') }}

),

renamed as (

    select
        COUNTRY as country,
        PROJECT_ID as project_id,
        PROJECT_NAME as project_name,
        SECTOR as sector,
        APPROVAL_DATE as approval_date,
        LOAN_AMOUNT_USD as loan_amount_usd,
        STATUS as status,
        INDICATOR_NAME as indicator_name,
        YEAR as year,
        VALUE as value,
        _INGESTED_AT as _loaded_at,
        'https://data.adb.org/' as _source_url

    from source

)

select * from renamed
