{{ config(materialized='view', schema='TIMELINE', alias='HISTORICAL_RECORDS__FED_SLAVEVOYAGES_INTRAAMERICAN') }}

-- GENERATED by scripts/census/gen_time_views.py -- do not hand-edit.
-- Regenerate after any change to reports/time_index/clock_index.csv.
--
-- Canonical clock for HISTORICAL_RECORDS.HISTORICAL_RECORDS__FED_SLAVEVOYAGES_INTRAAMERICAN.
--   column : YEARAM   (TEXT)
--   means  : happened -- The sibling staging model's codebook comment states 'YEARAM = Year of arrival at port of disembarkation' - the canonical voyage year. In this mart it is a raw u
--   grain  : year
--
-- The original columns pass through untouched; the canonical four sit in front
-- of them. Rule 8 of the datetime standard: the raw column is never overwritten,
-- so a mis-parse is always recoverable.

select
    {{ ripple_event_ts(ripple_ts_from_year('src."YEARAM"')) }} as ripple_ts,
    {{ ripple_grain('year') }} as ripple_grain,
    {{ ripple_clock('happened') }} as ripple_clock,
    'HISTORICAL_RECORDS.HISTORICAL_RECORDS__FED_SLAVEVOYAGES_INTRAAMERICAN'::varchar as ripple_source,
    src.*
from {{ ref('historical_records__fed_slavevoyages_intraamerican') }} as src
