{{ config(tags=['spine_generated']) }}

-- GRAIN: one row per record (spine_entity not determined -- no registry hint available) (TYPE_ID is unique)
-- SPINE_ENTITY: (not determined)  (natural_key: TYPE_ID)
-- Generated by scripts/generate_staging_models.py from SOURCE_REGISTRY -- deterministic,
-- no LLM.
-- CASTS: none of 17 columns. landing_column_profile_2026-09-19.tsv found no TEXT column where
-- every filled value parsed as a number, date or boolean.
-- spine_entity not determined (grain/natural_key proven, but no registry hint says what this row is ABOUT) -- no SPINE_ENTITY_ID emitted.
-- landing table's ingestion timestamp is named INGESTED_AT (no leading underscore) rather than the usual _INGESTED_AT -- confirmed via INFORMATION_SCHEMA, not assumed.

with source as (

    select * from {{ source('ripple_raw', 'PORTAL_CKA_ISRAEL_NATIONAL_964780E58D') }}
    qualify row_number() over (partition by "TYPE_ID" order by INGESTED_AT desc) = 1

),

renamed as (

    select
        {{ null_junk('"TYPE_ID"') }} as type_id,
        {{ null_junk('"TYPE"') }} as type,
        {{ null_junk('"NAME"') }} as name,
        {{ null_junk('"TITLE"') }} as title,
        {{ null_junk('"AIR_QUALITY"') }} as air_quality,
        {{ null_junk('"FILE_LINK"') }} as file_link,
        {{ null_junk('"FILL_COLOR"') }} as fill_color,
        {{ null_junk('"SHOW"') }} as show,
        {{ null_junk('"DAY_OF_WEEK"') }} as day_of_week,
        {{ null_junk('"DATE"') }} as date,
        {{ null_junk('"CONTENT"') }} as content,
        {{ null_junk('"MORNING"') }} as morning,
        {{ null_junk('"MORNING_CONTENT"') }} as morning_content,
        {{ null_junk('"NOON"') }} as noon,
        {{ null_junk('"NOON_CONTENT"') }} as noon_content,
        {{ null_junk('"EVENING"') }} as evening,
        {{ null_junk('"EVENING_CONTENT"') }} as evening_content,
        INGESTED_AT as _loaded_at,
        'https://data.gov.il/dataset/cf-output' as _source_url

    from source

)

select * from renamed
