WITH nid AS (SELECT DISTINCT OTHER_ID id FROM LIBRARY_RAW.LANDING.FED_FEC_COMMITTEE_TO_COMMITTEE
             WHERE CMTE_ID = 'C00464339' AND UPPER(NAME) LIKE '%NORTHWOODS%' AND OTHER_ID IS NOT NULL AND OTHER_ID <> '')
SELECT 'landing' part, CMTE_ID a, COALESCE(OTHER_ID, '') b, LEFT(UPPER(NAME), 60) c,
       TRANSACTION_TP || ' memo=' || COALESCE(MEMO_CD, '') || ' ent=' || COALESCE(ENTITY_TP, '') || ' ' || COALESCE(CITY, '') || ' ' || COALESCE(STATE, '') || ' ' || COALESCE(ZIP_CODE, '') d,
       COUNT(*) n, SUM(TRY_TO_DECIMAL(TRANSACTION_AMT, 18, 2)) amt,
       MIN(TRY_TO_DATE(TRANSACTION_DT, 'MMDDYYYY'))::string d0, MAX(TRY_TO_DATE(TRANSACTION_DT, 'MMDDYYYY'))::string d1
FROM LIBRARY_RAW.LANDING.FED_FEC_COMMITTEE_TO_COMMITTEE
WHERE UPPER(NAME) LIKE '%NORTHWOODS%' OR UPPER(NAME) LIKE '%NORTH WOODS%' OR CMTE_ID IN (SELECT id FROM nid) OR OTHER_ID IN (SELECT id FROM nid)
GROUP BY 1, 2, 3, 4, 5
UNION ALL
SELECT 'pol_committee', CMTE_ID, CYCLE, CMTE_NM,
       'tp=' || COALESCE(CMTE_TP, '') || ' dsgn=' || COALESCE(CMTE_DSGN, '') || ' freq=' || COALESCE(CMTE_FILING_FREQ, '') || ' ' || COALESCE(CMTE_CITY, '') || ' ' || COALESCE(CMTE_ST, '') || ' treas=' || COALESCE(TRES_NM, '') || ' cand=' || COALESCE(CAND_ID, ''),
       1, NULL, NULL, NULL
FROM LIBRARY_MARTS.POLITICS.POLITICS__FEC_COMMITTEE
WHERE UPPER(CMTE_NM) LIKE '%NORTHWOODS%' OR UPPER(CMTE_NM) LIKE '%NORTH WOODS%' OR CMTE_ID IN (SELECT id FROM nid) OR CMTE_ID = 'C00464339'
UNION ALL
SELECT 'fin_committees', CMTE_ID, '', CMTE_NM,
       'tp=' || COALESCE(CMTE_TP, '') || ' dsgn=' || COALESCE(CMTE_DSGN, '') || ' ' || COALESCE(CMTE_CITY, '') || ' ' || COALESCE(CMTE_ST, '') || ' treas=' || COALESCE(TRES_NM, ''),
       1, NULL, NULL, NULL
FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_FEC_COMMITTEES
WHERE UPPER(CMTE_NM) LIKE '%NORTHWOODS%' OR UPPER(CMTE_NM) LIKE '%NORTH WOODS%' OR CMTE_ID IN (SELECT id FROM nid)
UNION ALL
SELECT 'bulk_committees', FEC_CMTE_ID, CYCLE, CMTE_NM,
       'tp=' || COALESCE(CMTE_TP, '') || ' dsgn=' || COALESCE(CMTE_DSGN, '') || ' ' || COALESCE(CMTE_CITY, '') || ' ' || COALESCE(CMTE_ST, ''),
       1, NULL, NULL, NULL
FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_FEC_BULK_COMMITTEES
WHERE UPPER(CMTE_NM) LIKE '%NORTHWOODS%' OR UPPER(CMTE_NM) LIKE '%NORTH WOODS%' OR FEC_CMTE_ID IN (SELECT id FROM nid)
UNION ALL
SELECT 'ie', SPE_ID, COALESCE(CAND_ID, ''), LEFT(SPE_NAM, 60), COALESCE(SUP_OPP, '') || ' ' || COALESCE(CAND_NAME, ''),
       COUNT(*), SUM(TRY_TO_DECIMAL(EXP_AMO, 18, 2)), NULL, NULL
FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_FEC_INDEPENDENT_EXPENDITURES
WHERE UPPER(SPE_NAM) LIKE '%NORTHWOODS%' OR SPE_ID IN (SELECT id FROM nid) GROUP BY 1, 2, 3, 4, 5
UNION ALL
SELECT 'cmte_to_cand', CMTE_ID, COALESCE(CAND_ID, ''), LEFT(UPPER(NAME), 60), TRANSACTION_TP, COUNT(*), SUM(TRANSACTION_AMT), NULL, NULL
FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_FEC_COMMITTEE_TO_CANDIDATE
WHERE CMTE_ID IN (SELECT id FROM nid) OR UPPER(NAME) LIKE '%NORTHWOODS%' GROUP BY 1, 2, 3, 4, 5
UNION ALL
SELECT 'nid', id, '', '', '', 1, NULL, NULL, NULL FROM nid
