WITH c AS (SELECT CAND_ID, CYCLE, MAX(PRINCIPAL_CMTE_ID) pcc, MAX(CAND_ELECTION_YR) ey FROM LIBRARY_MARTS.POLITICS.POLITICS__FEC_CANDIDATE GROUP BY 1, 2),
s AS (SELECT s.CYCLE, s.CAND_ID, s.CAND_NAME, s.TTL_INDIV_CONTRIB, s.TTL_DISB, s.TTL_RECEIPTS, s.CASH_ON_HAND_CLOSE, c.pcc, c.ey
      FROM LIBRARY_MARTS.POLITICS.POLITICS__FEC_CANDIDATE_SUMMARY s JOIN c ON c.CAND_ID = s.CAND_ID AND c.CYCLE = s.CYCLE
      WHERE LEFT(s.CAND_ID, 1) IN ('H', 'S') AND c.pcc IS NOT NULL),
p AS (SELECT CYCLE, pcc, MAX(TTL_INDIV_CONTRIB) mi, MAX(ey) mey FROM s GROUP BY 1, 2),
d AS (SELECT s.* FROM s JOIN p ON p.CYCLE = s.CYCLE AND p.pcc = s.pcc WHERE p.mi <= 0 AND p.mey < s.CYCLE::int
      QUALIFY ROW_NUMBER() OVER (PARTITION BY s.CYCLE, s.pcc ORDER BY s.TTL_DISB DESC, s.CAND_ID) = 1),
o AS (SELECT CMTE_ID, MAX(TRY_TO_DECIMAL(TRANSACTION_AMT, 18, 2)) max_single, SUM(TRY_TO_DECIMAL(TRANSACTION_AMT, 18, 2)) tot_out, COUNT(*) n_out
      FROM LIBRARY_RAW.LANDING.FED_FEC_COMMITTEE_TO_COMMITTEE WHERE COALESCE(MEMO_CD, '') <> 'X' AND LEFT(TRANSACTION_TP, 2) = '24'
        AND TRY_TO_DATE(TRANSACTION_DT, 'MMDDYYYY') >= '2025-01-01' AND CMTE_ID IN (SELECT pcc FROM d WHERE CYCLE = '2026') GROUP BY 1),
r AS (SELECT d.*, o.max_single, o.tot_out, o.n_out,
             RANK() OVER (PARTITION BY d.CYCLE ORDER BY d.TTL_DISB DESC) rk_disb,
             RANK() OVER (PARTITION BY d.CYCLE ORDER BY COALESCE(o.max_single, 0) DESC) rk_single
      FROM d LEFT JOIN o ON o.CMTE_ID = d.pcc AND d.CYCLE = '2026')
SELECT 'agg' part, CYCLE, NULL pcc, NULL nm, COUNT_IF(TTL_DISB > 0) n_pos, MEDIAN(IFF(TTL_DISB > 0, TTL_DISB, NULL)) med_pos,
       SUM(IFF(TTL_DISB > 0, TTL_DISB, 0)) tot_pos, COUNT_IF(TTL_DISB >= 100000) n_100k, COUNT(*) n_incl_zero, MEDIAN(TTL_DISB) med_incl_zero,
       COUNT_IF(TTL_DISB >= 1000000) n_1m, COUNT_IF(max_single >= 100000) n_single_100k, MAX(max_single) top_single, NULL rk_disb, NULL rk_single
FROM r GROUP BY 1, 2
UNION ALL
(SELECT 'top2026', CYCLE, pcc, LEFT(CAND_NAME, 28), NULL, TTL_DISB, CASH_ON_HAND_CLOSE, TTL_RECEIPTS, n_out, tot_out, NULL, NULL, max_single, rk_disb, rk_single
 FROM r WHERE CYCLE = '2026' AND (rk_disb <= 12 OR rk_single <= 12) ORDER BY rk_single, rk_disb LIMIT 20)
