SELECT DATE_TRUNC('month', TRY_TO_DATE(TRANSACTION_DT, 'MMDDYYYY'))::string m, COUNT(*) n, COUNT_IF(TRANSACTION_TP = '24K') n24k,
       COUNT_IF(TRANSACTION_TP = '18K') n18k, COUNT(DISTINCT CMTE_ID) filers, COUNT(DISTINCT SUB_ID) subs
FROM LIBRARY_RAW.LANDING.FED_FEC_COMMITTEE_TO_COMMITTEE WHERE COALESCE(MEMO_CD, '') <> 'X' AND TRY_TO_DATE(TRANSACTION_DT, 'MMDDYYYY') >= '2025-01-01'
GROUP BY 1 ORDER BY 1
