SELECT 'summary' part, CAND_ID, CYCLE, CAND_NAME, INCUMBENT_CHALLENGER x1, TTL_RECEIPTS, TRANS_FROM_AUTH, TTL_DISB, TRANS_TO_AUTH,
       CASH_ON_HAND_CLOSE, TTL_INDIV_CONTRIB, NET_RECEIPTS, NET_DISBURSEMENTS, COVERAGE_END_DATE x2
FROM LIBRARY_MARTS.POLITICS.POLITICS__FEC_CANDIDATE_SUMMARY WHERE CAND_ID = 'H0WI07051' OR CAND_NAME ILIKE 'DUFFY%'
UNION ALL
SELECT 'cand', CAND_ID, CYCLE, CAND_NAME, CAND_STATUS || ' ' || COALESCE(OFFICE, '') || COALESCE(OFFICE_STATE, '') || COALESCE(OFFICE_DISTRICT, ''),
       CAND_ELECTION_YR, NULL, NULL, NULL, NULL, NULL, NULL, NULL, PRINCIPAL_CMTE_ID
FROM LIBRARY_MARTS.POLITICS.POLITICS__FEC_CANDIDATE WHERE CAND_ID = 'H0WI07051' OR PRINCIPAL_CMTE_ID = 'C00464339'
UNION ALL
SELECT 'dupcheck', NULL, CYCLE, NULL, NULL, COUNT(*), COUNT(DISTINCT CAND_ID), COUNT(DISTINCT CAND_ID || '|' || TTL_DISB::string), NULL, NULL, NULL, NULL, NULL, NULL
FROM LIBRARY_MARTS.POLITICS.POLITICS__FEC_CANDIDATE_SUMMARY GROUP BY CYCLE
