SELECT 'nw_receipts' part, CMTE_ID, LEFT(UPPER(DONOR_NAME), 50) donor, COALESCE(ENTITY_TYPE, '') || ' ' || COALESCE(TRANSACTION_TYPE, '') || ' memo=' || COALESCE(MEMO_CD, '') || ' oth=' || COALESCE(OTHER_ID, '') || ' ' || COALESCE(CITY, '') || ' ' || COALESCE(STATE, '') k,
       COUNT(*) n, COUNT(DISTINCT SUB_ID) subs, SUM(TRANSACTION_AMT) amt, MIN(TRANSACTION_DATE)::string d0, MAX(TRANSACTION_DATE)::string d1, LISTAGG(DISTINCT CYCLE_FILE, ',') cyc
FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_FEC_INDIV_CONTRIBUTIONS
WHERE CMTE_ID = 'C00922955'
GROUP BY 1, 2, 3, 4
UNION ALL
SELECT 'names_duffy_cmte', CMTE_ID, LEFT(UPPER(DONOR_NAME), 50), COALESCE(ENTITY_TYPE, '') || ' ' || COALESCE(TRANSACTION_TYPE, '') || ' memo=' || COALESCE(MEMO_CD, '') || ' oth=' || COALESCE(OTHER_ID, ''),
       COUNT(*), COUNT(DISTINCT SUB_ID), SUM(TRANSACTION_AMT), MIN(TRANSACTION_DATE)::string, MAX(TRANSACTION_DATE)::string, LISTAGG(DISTINCT CYCLE_FILE, ',')
FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_FEC_INDIV_CONTRIBUTIONS
WHERE TRANSACTION_DATE >= '2025-01-01' AND (OTHER_ID = 'C00464339' OR UPPER(DONOR_NAME) LIKE '%DUFFY FOR WIS%')
GROUP BY 1, 2, 3, 4
ORDER BY 1, 7 DESC
