SELECT 'ie_dedup' part, SPE_ID a, CAND_ID b, LEFT(CAND_NAME, 30) c, COALESCE(SUP_OPP, '') || ' ' || COALESCE(CAN_OFFICE, '') || COALESCE(CAN_OFFICE_STATE, '') || COALESCE(CAN_OFFICE_DIS, '') || ' sup=' || COALESCE(IS_SUPERSEDED::string, '') d,
       COUNT(*) n, COUNT(DISTINCT TRAN_ID) trans, SUM(TRY_TO_DECIMAL(EXP_AMO, 18, 2)) amt,
       MIN(TRY_TO_DATE(EXP_DATE, 'DD-MON-YY'))::string d0, MAX(TRY_TO_DATE(EXP_DATE, 'DD-MON-YY'))::string d1
FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_FEC_INDEPENDENT_EXPENDITURES WHERE SPE_ID = 'C00922955' GROUP BY 1, 2, 3, 4, 5
UNION ALL
SELECT 'cand', CAND_ID, CYCLE, CAND_NAME, COALESCE(PARTY, '') || ' ' || COALESCE(OFFICE, '') || COALESCE(OFFICE_STATE, '') || COALESCE(OFFICE_DISTRICT, '') || ' st=' || COALESCE(CAND_STATUS, '') || ' ic=' || COALESCE(INCUMBENT_CHALLENGER, '') || ' pcc=' || COALESCE(PRINCIPAL_CMTE_ID, ''),
       1, NULL, CAND_ELECTION_YR, NULL, NULL
FROM LIBRARY_MARTS.POLITICS.POLITICS__FEC_CANDIDATE WHERE CAND_ID = 'H6WI07223' OR (OFFICE_STATE = 'WI' AND OFFICE_DISTRICT = '07' AND CYCLE = '2026')
UNION ALL
SELECT 'sum', CAND_ID, CYCLE, CAND_NAME, 'indiv=' || TTL_INDIV_CONTRIB::string || ' coh=' || CASH_ON_HAND_CLOSE::string || ' end=' || COALESCE(COVERAGE_END_DATE, ''),
       1, NULL, TTL_RECEIPTS, NULL, NULL
FROM LIBRARY_MARTS.POLITICS.POLITICS__FEC_CANDIDATE_SUMMARY WHERE CAND_ID IN (SELECT CAND_ID FROM LIBRARY_MARTS.POLITICS.POLITICS__FEC_CANDIDATE WHERE OFFICE_STATE = 'WI' AND OFFICE_DISTRICT = '07' AND CYCLE = '2026') AND CYCLE = '2026'
UNION ALL
SELECT 'ie_district', SPE_ID, CAND_ID, LEFT(SPE_NAM, 30), COALESCE(SUP_OPP, '') || ' ' || LEFT(CAND_NAME, 25),
       COUNT(*), COUNT(DISTINCT TRAN_ID), SUM(TRY_TO_DECIMAL(EXP_AMO, 18, 2)), MIN(TRY_TO_DATE(EXP_DATE, 'DD-MON-YY'))::string, MAX(TRY_TO_DATE(EXP_DATE, 'DD-MON-YY'))::string
FROM LIBRARY_MARTS.FINANCE.FINANCE__FED_FEC_INDEPENDENT_EXPENDITURES
WHERE CAN_OFFICE_STATE = 'WI' AND CAN_OFFICE_DIS IN ('07', '7') AND COALESCE(IS_SUPERSEDED::string, 'false') NOT IN ('true', 'TRUE', 'Y')
  AND TRY_TO_DATE(EXP_DATE, 'DD-MON-YY') >= '2025-01-01'
GROUP BY 1, 2, 3, 4, 5
