{{ config(materialized='table', schema='HOUSING') }}

-- Source: FHFA House Price Index (HPI) ? Master File (184807 rows)
-- Generated by gen_mart_models.py
-- Fixed 2026-09-20: was reading source() with bare try_to_number()/try_to_double()/try_to_date() casts, which silently round decimals or mis-parse dates instead of guarding them. Now reads the already-guarded staging model (stg_fed_fhfa_hpi__records) instead -- same columns, same names, same order; every numeric/date cast there is regex-guarded (macros/staging_casts.sql): a value that doesn't parse cleanly reads NULL instead of a silently wrong value.

select
    hpi_type,
    hpi_flavor,
    frequency,
    level,
    place_name,
    place_id,
    yr,
    period,
    index_nsa,
    index_sa,
    rstderr,
    note
from {{ ref('stg_fed_fhfa_hpi__records') }}
