{{ config(materialized='table', schema='HOUSING') }}

-- Source: HUD Open Data (huduser.gov) (77 rows)
-- Generated by gen_mart_models.py
-- Fixed 2026-09-20: bare try_to_number()/try_to_double()/try_to_date() casts replaced in place with the project's guarded macros (stg_int/stg_float/stg_date, macros/staging_casts.sql) -- a value that doesn't parse cleanly now reads NULL instead of being silently rounded or misparsed. Kept on source() (not ref()) because this mart carries its own documented dedup (qualify) that must stay intact.

-- DEDUP (2026-08-18 verification): 6 duplicate groups, all size 2, single load
-- run (1 distinct _SOURCE_RUN_ID) -- a handful of HUD dataset-listing pages
-- captured twice, same shape as the NSF sample. Live: 77 rows / 71 distinct --
-- single-load duplication, exact dups carry no information.
with source as (
    select * from {{ source('ripple_raw', 'FED_HUD_DATA') }}
    qualify row_number() over (
        partition by DATASET_NAME, DATASET_URL, DESCRIPTION, FIPS, ZIP, EIN,
                     "YEAR", "VALUE"
        order by _INGESTED_AT) = 1
)

select
    DATASET_NAME as dataset_name,
    DATASET_URL as dataset_url,
    DESCRIPTION as description,
    FIPS as fips,
    ZIP as zip,
    EIN as ein,
    {{ stg_int('"YEAR"') }} as year,
    nullif(trim("VALUE"), '') as value
from source
