{{ config(materialized='table', schema='HOUSING') }}

-- Source: FED_FHFA_SUSPENDED_COUNTERPARTY (241 rows)
-- Generated by scripts/gen_mart_models.py

with source as (
    select * from {{ source('ripple_raw', 'FED_FHFA_SUSPENDED_COUNTERPARTY') }}
)

select
    FIRST_NAME as first_name,
    LAST_NAME as last_name,
    COMPANY as company,
    CITY as city,
    STATE as state,
    try_to_date(EFFECTIVE_DATE) as effective_date,
    try_to_date(SUSPENSION_END_DATE) as suspension_end_date,
    ORDER_LINK as order_link
from source
